### ISSUE TITLE
ArchLinux下卡住了...

### ISSUE THREAD

**Issue by MeowAlienOwO** [poooi/poi#1000]
如题,前段时间(4月底)还好好的,最近卡在这种界面:
![2016-05-10 17-16-04](https://cloud.githubusercontent.com/assets/6614456/15144002/c12d6c32-16e7-11e6-89f1-2c9feb85f3cf.png)
最近系统更新前:
- poi 6.2.0 => 挂
- poi 6.1.3 => 挂
系统更新后:
- poi 6.2.0 => 挂
虽然linux下资源非常波动甚至刷到100(跟chromium,android studio三开)但是卡在开头让我很方...
以下是挂掉的时候资源占用情况...
![2016-05-10 17-16-04](https://cloud.githubusercontent.com/assets/6614456/15144110/49202ea4-16e8-11e6-9f00-9e2bd288191a.png)
求问有木有日志之类的,或者命令行输出...
我用命令行启动也只有这种:
`[INFO] Proxy listening on 36266
`

**Comment by taroxd** [comment]
dupicated with #1001
