### ISSUE TITLE
ArchLinux下卡住了...

### ISSUE THREAD

**Issue by MeowAlienOwO** [poooi/poi#1001]
如题,前段时间(4月底)还好好的,最近卡在这种界面:
![2016-05-10 17-11-23](https://cloud.githubusercontent.com/assets/6614456/15144280/5ca9bab6-16e9-11e6-9b27-57d478b9dc30.png)

最近系统更新前:
- poi 6.2.0 => 挂
- poi 6.1.3 => 挂

系统更新后:
- poi 6.2.0 => 挂

虽然linux下资源非常波动甚至刷到100(跟chromium,android studio三开)但是卡在开头让我很方...
以下是挂掉的时候资源占用情况...
![2016-05-10 17-16-04](https://cloud.githubusercontent.com/assets/6614456/15144110/49202ea4-16e8-11e6-9f00-9e2bd288191a.png)
求问有木有日志之类的,或者命令行输出...
我用命令行启动也只有这种:

`[INFO] Proxy listening on 36266
`

**Comment by yukixz** [comment]
--debug

On Tuesday, 10 May 2016, 死鱼眼的喵星人 <notifications@github.com> wrote:

> 如题,前段时间(4月底)还好好的,最近卡在这种界面:
> [image: 2016-05-10 17-11-23]
> <https://cloud.githubusercontent.com/assets/6614456/15144280/5ca9bab6-16e9-11e6-9b27-57d478b9dc30.png>
>
> 最近系统更新前:
>
>    - poi 6.2.0 => 挂
>    - poi 6.1.3 => 挂 系统更新后:
>    - poi 6.2.0 => 挂 虽然linux下资源非常波动甚至刷到100(跟chromium,android
>    studio三开)但是卡在开头让我很方... 以下是挂掉的时候资源占用情况... [image: 2016-05-10 17-16-04]
>    <https://cloud.githubusercontent.com/assets/6614456/15144110/49202ea4-16e8-11e6-9f00-9e2bd288191a.png>
>    求问有木有日志之类的,或者命令行输出... 我用命令行启动也只有这种: [INFO] Proxy listening on 36266
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/poooi/poi/issues/1001>
>


-- 
*Dazzy Ding*
Email: h@dazzyd.org

**Comment by chocotan** [comment]
archlinux卡住+1
4.x的时候是好的，从5.x的时候开始就办法用了

![image](https://cloud.githubusercontent.com/assets/1758565/15151547/2aaf9212-1697-11e6-92ae-0fdbdf3beca6.png)

**Comment by yukixz** [comment]
想起来了、electron 0.36.* 是会卡死的、需要 electron 0.37.3+ 才正常。

**Comment by chocotan** [comment]
先去下了个electron 0.37用着了 
：）

**Comment by MeowAlienOwO** [comment]
嗯...我之前没有用过electron, 现在做了如下尝试:
1. 从npm装了electron的prebuilt版本,版本号1.0.1
2. 运行electron poi发现无论是命令行还是拖拽都不行
3. 看了一眼electron的quick start, 但是觉得除了明白了不能用如上方法运行以外没有任何对解决目前问题有用的信息
4. `poi --debug` 跟 @chocotan 一样卡住,并且跳Inspected target disconnected
5. 脑洞一开改了version文件- -没有卵用
6. 按照主页的Run这一节重新安装以后可以用了.但是编成日记,航海日志跟装备信息不兼容.猜想是否是插件问题?
命令:
```shell
git clone https://github.com/poooi/poi && cd poi
npm i
./node_modules/.bin/gulp install
/path/to/electron ./
```
运行时用
`electron /path/to/poi`

总之我是解决了,过程跟方法写出来分享下,大大觉得制杖的话请轻拍><
如果没有和我一样的卡住的话就请close吧~

**Comment by chocotan** [comment]
我是到electron的github页面下新版的，然后解压覆盖poi文件夹
然后运行./electron

在 2016年5月13日 上午1:39，死鱼眼的喵星人 <notifications@github.com>写道：

**Comment by yukixz** [comment]
未兼容 electron 1.0+
请使用 0.37.*

On Friday, 13 May 2016, 天羽ちよこ <notifications@github.com> wrote:

> 我是到electron的github页面下新版的，然后解压覆盖poi文件夹
> 然后运行./electron
>
> 在 2016年5月13日 上午1:39，死鱼眼的喵星人 <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>>写道：
>
> > 嗯...我之前没有用过electron, 现在做了如下尝试:
> > 1. 从npm装了electron的prebuilt版本,版本号1.0.1
> > 2. 运行electron poi发现无论是命令行还是拖拽都不行
> > 3. 看了一眼electron的quick start, 但是觉得除了明白了不能用如上方法运行以外没有任何对解决目前问题有用的信息
> > 4. poi --debug 跟 @chocotan <https://github.com/chocotan>
> > 一样卡住,并且跳Inspected target disconnected
> > 5. 脑洞一开改了version文件- -没有卵用
> > 6. 按照主页的Run这一节重新安装以后可以用了.但是编成日记,航海日志跟装备信息不兼容.猜想是否是插件问题?
> > 命令:
> >
> > git clone https://github.com/poooi/poi && cd poi
> > npm i
> > ./node_modules/.bin/gulp install
> > /path/to/electron ./
> >
> > 运行时用
> > electron /path/to/poi
> >
> > 总之我是解决了,过程跟方法写出来分享下,大大觉得制杖的话请轻拍><
> > 如果没有和我一样的卡住的话就请close吧~
> >
> > —
> > You are receiving this because you were mentioned.
> > Reply to this email directly or view it on GitHub
> > <https://github.com/poooi/poi/issues/1001#issuecomment-218830826>
> >
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/poooi/poi/issues/1001#issuecomment-218836636>
>


-- 
*Dazzy Ding*
Email: h@dazzyd.org

**Comment by MeowAlienOwO** [comment]
这样子啊，那是不是在主页上注明会比较好呢？这种说法可能造成误解吧……

> First, get the latest x64 version of Electron and Node.js.

不过1.0.*也能运行本体就是了

**Comment by dkwingsmt** [comment]
@MeowAlienOwO 因为前两天electron才放出1.0⋯⋯ ＿|￣|○

**Comment by taroxd** [comment]
@yukixz 本体已兼容，部分插件还未兼容（我自己使用的插件都已经发了pr）

**Comment by MeowAlienOwO** [comment]
这样啊……那就只能希望尽早兼容咯……我姑且把版本先降回去了
开发团队辛苦了m(_ _)m
感觉可以关了吧。
