### ISSUE TITLE
概览面板无法使用高清图标

### ISSUE THREAD

**Issue by wafer-li** [poooi/poi#1002]
Electron v0.36.12
Win 10 Pro x64
commit: 1e984c6cfd61916994774b734128e2c3f695eb62

情况如题。即使勾选了选项，重启之后也无法使用。

Console 报了一个 Waring

![image](https://cloud.githubusercontent.com/assets/12459199/15168334/91fc63a8-176b-11e6-945f-4d4c87e49915.png)

**Comment by taroxd** [comment]
Confirmed.

warning 与标题无关。bug 应该是 https://github.com/poooi/poi/commit/6b07a3ffb09cd6bb606c9029b3ab1774a5226f50 引进的，我去看一看

**Comment by yukixz** [comment]
@wafer-li warning 是kcwiki 插件的、无视它
大概是高清图标 fallback 到普通图标的代码出错了？
