### ISSUE TITLE
制空值计算 熟练度和非熟练度2种模式 因为支援不算熟练度

### ISSUE THREAD

**Issue by ibicdlcod** [poooi/poi#1004]
夏活实装的时候就知道 攻击机的熟练度 对航空支援没有影响

现已查明 舰战的熟练度 如果放在航空支援 也没有影响 必须按照无熟练度来配对空

并且已查明 这次春活E6决战 E7无论道中决战 都要上航空支援 （E6E7boss是因为舰爆有对陆加成。E7道中是因为目标不是给对面造成伤害而是通过空确减少对面的航空战力 减少劝退 可以说是E7要诀）

我问一下 poi目前是不是没有算制空可以关掉熟练度的功能？

**Comment by KagamiChan** [comment]
没有找到改修对航空支援的制空影响的信息，在 #1296 中也是没有按不考虑改修来处理的，有新的情报的话再修正
