### ISSUE TITLE
建议:增加设置选项:保存配置在根目录

### ISSUE THREAD

**Issue by HsoYo** [poooi/poi#1006]
经常在陌生的 PC 上运行 POI,每次都要把打包好的 %appdata% 里的 poi 配置文件夹解压到新电脑里,不然就得自己再改界面和重新下载扩展.
能不能提供个选项保存配置文件在 POI 根目录?这样就可以主程序和配置文件夹打包在一起了.

**Comment by KochiyaOcean** [comment]
@HsoYo 就目前的情况而言无法实现

**Comment by taroxd** [comment]
用软链接吧。具体可以百度 `mklink`

**Comment by traumax16** [comment]
@echo off
cd /d %~dp0
if exist "poi" goto SSS else goto AAA

:AAA
mkdir "poi"
goto SSS

:SSS
set save_dir=%~dp0poi
cd /d %UserProfile%\AppData\Roaming\
if exist "poi" (
echo.
echo poi数据已经存在
echo.) else (
mklink /d "poi" "%save_dir%"
echo.
echo 完成。
echo.)
pause


复制到记事本，改文件名.bat管理员身份运行，没做太多测试，大神发现问题再帮着改改吧。我自己写的没这么复杂，我是poi和配置文件分开放的，poi随时更新，走的时候只带配置文件。

**Comment by yukixz** [comment]
@traumax16 linux/mac 如何处理？

**Comment by tommytroylin** [comment]
是electron的限制所以不能直接保存么？ @KochiyaOcean 

由于我上网电脑不是特别固定，每次重新设置都感到很麻烦。

**Comment by taroxd** [comment]
@traumax16 这个应该不需要管理员权限吧

**Comment by taroxd** [comment]
当  `%appdata%/poi/config.cson` 不存在的时候，poi 会自动读取 poi 根目录下的 config.cson，虽然不会将配置保存在这个文件里面。

缓存文件由 electron 管理，做不到迁移至根目录。

航海日志数据可以自定义保存位置。

任务计数和其他插件暂不支持，大概也没有支持的打算。仍然建议使用软链接。

**Comment by dkwingsmt** [comment]
Marked as wontfix and close for now.
