### ISSUE TITLE
poi白屏 

### ISSUE THREAD

**Issue by zz9988** [poooi/poi#1009]
周日在家使用正常 然后到周一到杭州就白屏 一开始是6.13 昨天重下了6.13还是白屏并且特卡 然后换6.20也一样白屏+卡顿 试用火狐可以开游戏 kvc可开游戏 poi白屏同时岛风显示没有检测到游戏 求助

**Comment by KochiyaOcean** [comment]
@zz9988 这种问题去问岛风Go的客服比较好哦……
