### ISSUE TITLE
关于基本设置里,网址后面按钮的问题

### ISSUE THREAD

**Issue by yortiss** [poooi/poi#1010]
win7 32bit
poi V6.2.0 

![default](https://cloud.githubusercontent.com/assets/19453236/15381915/09ccd468-1dbf-11e6-8211-7e577f035d78.PNG)
在网址后面那个钩的图标(见图),在加载失败时会变成叉.
点那个钩或叉会自动刷新.
我记得chrome里点叉后停止加载,而不会刷新.
希望能修正一下
PS: 主要是进入游戏后,停止加载能快速调整FLASH的大小,求修正

**Comment by yukixz** [comment]
那个按钮是「前往」、不是「停止」
