### ISSUE TITLE
[OS X]The screen becomes blurred when moving poi between screens

### ISSUE THREAD

**Issue by LukeXuan** [poooi/poi#1013]
When I move poi from the external monitor's screen to the mbp's own screen, the flash interface becomes blurred. However any other flash components of safari or chrome(like bilibili) does not encounters this issue.

**update**: After clear check, the flash player of chrome have the same problem. So this may be flash's bug but not poi's. However, flash in safari behaves well...

**Comment by edwardaaaa** [comment]
@LukeXuan 你在Mac主屏上冷启动POI就ok了，如此，POI在不同PPI的屏幕间来回切换就会自动调整，而不会造成你所说的问题。

**Comment by taroxd** [comment]
@edwardaaaa 路过歪楼求一下陆航的高清图标

**Comment by edwardaaaa** [comment]
@taroxd，已经上传好了，https://drive.google.com/open?id=0B-J-nq9cHXQxckx4X3BPOEhpck0
名字是“陆攻”和“陆战”。

**Comment by charlie5188** [comment]
I guess this is not a bug. MBP uses retina-display. Meanwhile, Kancolle consists of 1x bitmap elements. That's why Kancolle is expected to be 'blurred' on MBP's display.

**Comment by KagamiChan** [comment]
It seems to me this issue is no longer valid on latest macOS / poi
