### ISSUE TITLE
POI-v6.2.0 一心二用插件Flash更新問題

### ISSUE THREAD

**Issue by ZKENZI** [poooi/poi#1016]
![image](https://cloud.githubusercontent.com/assets/19538633/15481843/362242c0-215f-11e6-9ba5-844d5f5ca8ec.png)
各位開發者辛苦了~
如題~小弟在使用一心二用遊玩DMM遊戲〝戦国プロィデンス〞時出現Flash版本不符問題。
但使用v6.1.3卻無此問題~煩請幫忙排除問題~謝謝

**Comment by KochiyaOcean** [comment]
原来除了舰以外还有在使用 Flash 的游戏……还以为都转到 canvas 去了呢（。
请等待下个版本

**Comment by ZKENZI** [comment]
OK~謝謝解答
