### ISSUE TITLE
希望增加一键清理所有相关文件的功能

### ISSUE THREAD

**Issue by edwardaaaa** [poooi/poi#1018]
经常在贴吧和论坛可以看到类似的问题，具体为：“**POI突然失效了/POI重新安装无效/POI在系统升级后无法工作**”等等这类问题。

一般的比较简单，快速，有效的解决办法就是删除全部相关文件，然后重新安装一遍，基本就能解决。

然而这点正好和POI为了方便玩家在某个本版本后将一部分文件挪至系统文件夹后发生矛盾了，导致这些发生问题的玩家无法彻底删除相关文件，导致一遍遍重装失败无效。

也因此希望能完善一下相关的功能，在全部版本中能够增加一个**一键清理所有相关文件**的功能，功能**发生前有文字警告**，这样类似问题能够有一个比较亲民的解决方案。

毕竟现在不少玩家喜欢“企鹅/数字全家桶”的（没别的意思），可能在相关电脑知识方面还不够。

**Comment by KagamiChan** [comment]
如果只是舰娘部分白屏的话，可以试试看——虽然更多时候是某软件的锅
如果全部无法显示，那么这个功能用户也点击不到了吧

我觉得，就随发布版附带一个文本文档之类的给一个 FAQ？

**Comment by edwardaaaa** [comment]
代理的问题其实没算进去，我看到问题的多数是：
1.右边信息类似于没有抓取，而无法显示数据。
2.用chrome或者别的浏览器没问题，用POI就白屏。
3.系统升级了，POI无法启动。

FAQ的话如何呈现是个问题，用户出现问题会一般会火急火燎的贴吧论坛发帖问。
如果是以文档的方式，很容易造成忽略而没有发挥实际效果。

- 因此是否考虑作成插件的形式，将POI以往以及现在希望告知用户的信息全部集成在一起，类似于一个POI的小百科，疑难杂症，功能介绍等等。

POI发展到现在功能日趋丰富，在往后的版本中希望继续在用用户体验的优化，完善的方面有所突破。
