### ISSUE TITLE
[Feature Request] 基地航空队的概况显示

### ISSUE THREAD

**Issue by wafer-li** [poooi/poi#1019]
如题，不知道开发组有没有这方面的打算。

暂时给一些相关资料和验证吧。

[API List](https://github.com/andanteyk/ElectronicObserver/blob/master/ElectronicObserver/Other/Information/apilist.txt)

[NGA 转载翻译的陆航相关验证](http://bbs.nga.cn/read.php?tid=9306401)
## 新资料

http://bbs.nga.cn/read.php?tid=9759958

**Comment by yukixz** [comment]
@wafer-li 春活后看稳定的api再实现

**Comment by taroxd** [comment]
并不能直接拿到飞机的状态数值（0~100），而只能判断是否红脸，而且要点出击，进地图之后才能得到API。
由于娇喘学聪明了，我觉得这个效果没有必要实现。

**Comment by wafer-li** [comment]
@taroxd 改了一下标题，以免误解。

其实重要的还是熟练度、制空值、是否补给、航空队牌子的状态这些。

至于状态(condition) 嘛，这个重要性并不高，因为……航空队貌似刷不了闪。

**Comment by taroxd** [comment]
同样需要点开才能拿到 API

既然你点开了你还要看 poi 干什么

**Comment by wafer-li** [comment]
@taroxd :joy:

1. poi 展现的信息密度更高，信息更为迅速直观。

2. 航空队最重要的**制空值**属性无法通过 flash 查看。
    - 这次春活本人就吃了不知道制空乱配陆航的亏。

**Comment by KochiyaOcean** [comment]
@wafer-li 实际上也只有制空值是比较有价值的信息。
需要活动结束后根据该系统的存续情况再做判断

**Comment by taroxd** [comment]
如果要做的话，感觉插件的用户体验不好，主面板又塞不下……？

**Comment by wafer-li** [comment]
@taroxd 我个人觉得搞插件挺好的，在列表里面排序高一点就没什么问题（前三为好）。

**Comment by KochiyaOcean** [comment]
@taroxd 到时候再说啦说不定都没这系统了（。

**Comment by wafer-li** [comment]
突然发现开始抓陆航的包了。

附上一点新资料

http://bbs.nga.cn/read.php?tid=9759958

**Comment by dkwingsmt** [comment]
![image](https://cloud.githubusercontent.com/assets/1596656/18306848/517261c6-7520-11e6-8a27-7bd32de7707b.png)
这就没法做……
