### ISSUE TITLE
6.2.0後魔改失效?

### ISSUE THREAD

**Issue by artoodetoo3301** [poooi/poi#1021]
是改了什麼啦?

**Comment by taroxd** [comment]
@artoodetoo3301 见 changelog

**Comment by artoodetoo3301** [comment]
要怎樣改 可給我路徑嗎?

**Comment by edwardaaaa** [comment]
@artoodetoo3301 见 changelog

**Comment by artoodetoo3301** [comment]
即是怎樣 不明白呀
可以打出來嗎?

**Comment by KagamiChan** [comment]
![image](https://cloud.githubusercontent.com/assets/3816900/15598075/3c962bd8-2409-11e6-914d-426f751ede3d.png)

就是点击闪电图标，会弹出一个窗口，然后里面有一个 Kancolle 子文件夹
