### ISSUE TITLE
扩展程序不能成功安装-QWQ

### ISSUE THREAD

**Issue by onepiece233** [poooi/poi#1022]
poi 的 扩展程序的插件没办法 正常安装啊，更新也不可以。点了之后只是不停的转圈  是什么问题啊- - 之前都是可以正常安装和更新了 。也换了好几个版本的游览器尝试过了。都是一样的。

**Comment by KagamiChan** [comment]
请完善以下信息：
- poi 版本（现在和之前）
- npm 服务器（点击高级设置即可看到
- 如果勾选了使用代理连接至 npm 服务器，代理是什么代理
- 点击开发者工具，Console 内是否有报错信息的显示

**Comment by onepiece233** [comment]
poi之前是6.20的 现在是 6.13的~                                                                                                                       npm那边的服务器 四个都有选过 但是都不可以- - 现在是用的Taobao（CN）                                                         代理连接至npm没有勾                                                                                                                                          console 里面有提示一些 报错的信息

Unhandled rejection Error: getaddrinfo ENOTFOUND cdn.npm.taobao.org cdn.npm.taobao.org:443
    at errnoException (dns.js:26:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:77:26)

**Comment by KochiyaOcean** [comment]
@onepiece233 纯粹的连不上而已……换一个就行了

**Comment by taroxd** [comment]
检查一下你的 DNS？按下 win+R，输入 cmd，往命令行里输入 `ping cdn.npm.taobao.org` 试试看吧。如果 ping 不通的话就是你自己网络（应该是 DNS）的锅咯

**Comment by yukixz** [comment]
建议带刀找ISP

**Comment by onepiece233** [comment]
QAQ  没有错 ..  换了个DNS一下子就好了  谢谢各位啦！！
