### ISSUE TITLE
禁止 Babel 在用户目录生成 .babel.json 文件

### ISSUE THREAD

**Issue by xupefei** [poooi/poi#1029]
如题……

参见 http://stackoverflow.com/questions/32757306/why-babel-stores-babel-json-in-userprofile-path

**Comment by taroxd** [comment]
It is said in https://babeljs.io/docs/usage/require/#environment-variables that
>
> By default `babel-node` and `babel-register` will save to a json cache in your temporary directory.
>
> This will heavily improve with the startup and compilation of your files. There are however scenarios  where you want to change this behaviour and there are environment variables exposed to allow you to do this.

Why should we disable it?

~~Is there any substitute for Locale Emulator?~~

**Comment by xupefei** [comment]
Now the fact is this file will not be in the temporary, but `X:\Users\<your_username>` dictionary (of course, it's for Windows). I believe there is no such file when using old version of poi, only 6.2.0 is affected.

Locale Emulator is still under maintenance, but mainly by one of my friends. I will also make some improvements (e.g. support for 4K screen), but quite rarely.

**Comment by taroxd** [comment]
Babel support is introduced in 6.2.0. It is not a bug.

**Comment by KagamiChan** [comment]
现在，应该，没有了吧

**Comment by xupefei** [comment]
![3d0d6bdcdc1b812baf2e15f38ad26f87](https://user-images.githubusercontent.com/1687847/46128438-22a70e80-c23c-11e8-86db-01022b2b90a3.gif)不知不觉已经AFK两年了
