### ISSUE TITLE
切换插件时，部分插件不显示

### ISSUE THREAD

**Issue by wafer-li** [poooi/poi#1031]
Electron v0.36.12
OS X 10.11.5
poi version: at master 62917af71fa384b8e857eb8457db85b9ac42c966

不知道是不是 Bug。

仅在勾选了 `切分组件与插件面板` 时存在。

准确的来说，在切换插件的时候，只有新建窗口的插件能显示出来。
如果选择了非新建窗口的插件，则插件面板无变化（即维持原来显示的插件不变）

重启过软件，然并卵。

Console 有几个 Warning，个人感觉应该没什么关系。

![image](https://cloud.githubusercontent.com/assets/12459199/15635079/1b1d668e-2610-11e6-85ba-60aff116e5c3.png)

**Comment by KochiyaOcean** [comment]
@wafer-li 这个 warning 只是 react bootstrap 弃用旧 API 导致的，没什么问题

**Comment by wafer-li** [comment]
@KochiyaOcean 😳  这个我也猜到了，只不过为了以防万一顺便截上来的而已。

**Comment by wafer-li** [comment]
@KochiyaOcean  
😊  开发辛苦了，还是少熬夜为好。

**Comment by KochiyaOcean** [comment]
@wafer-li 周常还在做……
