### ISSUE TITLE
求助：舰娘信息插件无法读取舰娘信息。

### ISSUE THREAD

**Issue by zmk1997** [poooi/poi#1041]
打开舰娘信息无显示，重装插件或者poi浏览器都没作用。

**Comment by KochiyaOcean** [comment]
@zmk1997 poi 版本号和插件版本号？

**Comment by zmk1997** [comment]
poi 6.20正式版
插件 1.9.2

**Comment by zmk1997** [comment]
@KochiyaOcean

**Comment by KochiyaOcean** [comment]
@zmk1997 如果是初次登录不显示数据，回一次母港试试看

**Comment by zmk1997** [comment]
@KochiyaOcean 回母港刷新后只显示几艘刚获得的船，之前的船没有显示。

**Comment by KochiyaOcean** [comment]
@zmk1997 @Ayaphis 接锅

**Comment by ruiii** [comment]
@zmk1997 其实昨天也有用户报这个问题，让他等了下。
想不到是什么原因，就让他等今天看看，结果今天就好了。

**Comment by yukixz** [comment]
@zmk1997 检查过滤条件

**Comment by zmk1997** [comment]
@yukixz 把过滤条件全调成全部，出来了一部分。

**Comment by zmk1997** [comment]
@yukixz 关掉poi又开了一次，恢复正常了。

**Comment by zmk1997** [comment]
谢谢各位大神~~~~~~
