### ISSUE TITLE
更新后的二式水战和RO44的制空熟练变成+25了 希望可以更新制空计算

### ISSUE THREAD

**Issue by castore** [poooi/poi#1042]

**Comment by KochiyaOcean** [comment]
@castore 早就更新了

**Comment by castore** [comment]
@KochiyaOcean
更新6.2.0正式版好了 感谢

**Comment by castore** [comment]
@KochiyaOcean
更新6.2.0正式版好了 感谢

**Comment by yukixz** [comment]
你不更新又来报bug我们很难做啊

On Friday, 3 June 2016, castore <notifications@github.com> wrote:

> @KochiyaOcean <https://github.com/KochiyaOcean>
> 更新6.2.0正式版好了 感谢
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/poooi/poi/issues/1042#issuecomment-223570877>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/ADLuwfr1XtM0L2AiY7NUP4eSRVSCXu8dks5qICPngaJpZM4ItfWe>
> .
>


-- 
*Dazzy Ding*
Email: h@dazzyd.org
