### ISSUE TITLE
如何关闭显卡加速

### ISSUE THREAD

**Issue by ilikecola** [poooi/poi#1051]
如何关闭显卡加速？有时候会卡。。。上一个版本就不会，我想是不是更新了chrome默认开启显卡加速有关？

**Comment by KochiyaOcean** [comment]
@ilikecola 对于现在的正式版，用命令行启动并在后面加入 --disable-gpu 选项；现在的 Git Master 上已经具有关闭的选项。

**Comment by ilikecola** [comment]
OK.看起来挺好的。谢谢啦~
