### ISSUE TITLE
网络错误之后的任务计数

### ISSUE THREAD

**Issue by FXuZ** [poooi/poi#1054]
并不是严重的bug, 只是robustness的问题, 大概...
症状是:
  - 任务显示完成并且游戏进入任务界面
  - 交任务请求没有完全完成, 但是服务器端已经判定任务已经交了奖励也发了, 这时候猫了
  - 刷新(不退出poi)之后重进回到游戏的任务界面, 虽然那个任务在服务器端已经判定完成(游戏播放器也显示如此)但是poi的任务列表中仍然存在一个已经完成的任务, 一般需要重开poi重置任务列表才能回复正常.

不过关于修改的方案, 暂时没想法... 因为任务相关的api只有在进了任务列表的界面才能看到, 所以无法保证当前的本地列表是完整的...

**Comment by yukixz** [comment]
Merge to #1060.
