### ISSUE TITLE
npm安装插件的时候显示npm ERR! code SELF_SIGNED_CERT_IN_CHAIN

### ISSUE THREAD

**Issue by BILIBIBI** [poooi/poi#1055]
需要执行`npm config set strict-ssl false`之后才能安装插件
不知道是否是个别问题

**Comment by yukixz** [comment]
@BILIBIBI 安装哪个插件啊

**Comment by BILIBIBI** [comment]
哪个都出错……
在poi里面表现为点击安装后一直安装中

**Comment by KochiyaOcean** [comment]
https 被劫持了？

**Comment by BILIBIBI** [comment]
开着代理也一样……
岛风GO和Shadowsocks都试了一遍

**Comment by KochiyaOcean** [comment]
@BILIBIBI DNScrypt 呢

**Comment by KagamiChan** [comment]
npm 是可以通过 `--proxy` 参数来指定运行时的代理的，`--registry`来指定源，也都试过了吗

会不会是把某些根证书被禁用了，或者某些杀毒软件劫持了

**Comment by KochiyaOcean** [comment]
目前源列表里 npm 和清华是使用 https 的，淘宝的两个源（淘宝，cnpm）http
换成淘宝系的应该就不会有证书问题了
