### ISSUE TITLE
poi v6.3.1 -beta.0 无法在Windows平板上通过触屏选中输入框

### ISSUE THREAD

**Issue by saigusaharuka** [poooi/poi#1059]
无法在Windows平板上通过触屏选中输入框   从而导致无法输入帐号密码  其他按钮点击正常

 连接鼠标可以正常选中输入框 

不仅dmm login界面输入框无法通过触屏选中  用poi打开百度首页 搜索框也无法通过触屏选中

之前的6.3.0版本同样有此问题  但是6.2.0是正常的

**Comment by yukixz** [comment]
Duplicate of #1061

**Comment by KochiyaOcean** [comment]
见 Chrome Issue: https://bugs.chromium.org/p/chromium/issues/detail?id=600395
