### ISSUE TITLE
设备切换之后的任务计数

### ISSUE THREAD

**Issue by KagamiChan** [poooi/poi#1060]
以四艘建造为例，可能的复现步骤如下：

1. poi 上登录，接任务，完成任务的一部分，比如建造一艘
2. 在 Android 上登录，完成剩下的部分，清结该任务
3. 在 poi 上继续操作，然后会 201 猫，此时不重启 poi 而是刷新登录
4. 可以观察到这个任务还会存在于任务计数中，并且不随新的任务列表数据而刷新

![2016-06-11 10_31_34-poi](https://cloud.githubusercontent.com/assets/3816900/15982661/2a5cb0e6-2fc0-11e6-830a-e0cc4b44b05c.png)

虽然和 #1054 一样，重启 poi 就好，不过感觉以后切换设备的情况会更多，不知道有没有改善的方法

**Comment by yukixz** [comment]
poi为本地计数
手机网页登录互斥

On Saturday, 11 June 2016, Seki Kagami <notifications@github.com> wrote:

> 以四艘建造为例，可能的复现步骤如下：
>
>    1. poi 上登录，接任务，完成任务的一部分，比如建造一艘
>    2. 在 Android 上登录，完成剩下的部分，清结该任务
>    3. 在 poi 上继续操作，然后会 201 猫，此时不重启 poi 而是刷新登录
>    4. 可以观察到这个任务还会存在于任务计数中，并且不随新的任务列表数据而刷新
>
> [image: 2016-06-11 10_31_34-poi]
> <https://cloud.githubusercontent.com/assets/3816900/15982661/2a5cb0e6-2fc0-11e6-830a-e0cc4b44b05c.png>
>
> 虽然和 #1054 <https://github.com/poooi/poi/issues/1054> 一样，重启 poi
> 就好，不过感觉以后切换设备的情况会更多，不知道有没有改善的方法
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/poooi/poi/issues/1060>, or mute the thread
> <https://github.com/notifications/unsubscribe/ADLuwYKSedO4P1_ScWDmo0K_ibkbbc_Aks5qKh_wgaJpZM4Izc-V>
> .
>


-- 
*Dazzy Ding*
Email: h@dazzyd.org

**Comment by yukixz** [comment]
服务器给出任务列表不完整、无法判断任务是完成了还是在另一页

**Comment by KagamiChan** [comment]
这种情况下能不能够加一个手动重新初始化任务列表的功能，就像 poi 重启动的时候那样

**Comment by KagamiChan** [comment]
毕竟以后网页版携带版互相切换的情况会比较多，我觉得专门改善还是有价值的

**Comment by yukixz** [comment]
可以按照任务排序规则猜测任务列表

**Comment by KagamiChan** [comment]
想了想不如点击刷新按钮的时候把任务列表进行一个初始化，或者主面板做初始化应该也可以，这些组件的信息本身也在再次进入游戏的过程中会更新。

**Comment by dkwingsmt** [comment]
7.0.0 版的 activeQuests 机制能够有效删除过时的活动任务。试试看吧

**Comment by KagamiChan** [comment]
嗯，这两天已经在用了，明天~~如果记得的话~~会测试一下 - -
P.S. 重新打开程序之后，未进入游戏情况下主面板状态数据会也会复原，这是设计的功能吧

**Comment by dkwingsmt** [comment]
@KagamiChan 虽然不是刻意追求的，不过换了新的架构带来的功能，也算是新功能

**Comment by KagamiChan** [comment]
在我所举的例子上是有效的，感觉可以 close 了

**Comment by KagamiChan** [comment]
@dkwingsmt 
当前任务计数对于跨周更新的任务计数貌似支持不够完美，比如上周我在这台机器上接了あ号任务，然后直到这周才重新再用，发现这个任务的计数出现了问题。
有可能对于跨周期任务都会有同样的问题，但一般其它任务可以根据新数据来更新计数，あ号比较特殊……
![image](https://cloud.githubusercontent.com/assets/3816900/17534679/eb21a824-5ebc-11e6-891e-9d95b51ed274.png)
