### ISSUE TITLE
6.3.0以后 UI对触屏操作无反应

### ISSUE THREAD

**Issue by einbrain** [poooi/poi#1061]
10号随系统维护结束更新到6.3.0，发现使用30分钟到1个小时左右(也有可能是放置这么长时间之后)，poi的UI对触屏操作的反应会逐渐迟钝直到完全无反应。
此时舰娘游戏界面触摸操作没有问题，poi UI用鼠标或者Touchmousepointer之类模拟鼠标操作也没有问题。换回到6.2.0 release可以消除此问题。
6.3.1 beta0也有同样问题，6.3.0 beta因为没有提供32bit版没有测试。
windows 10 home 32bit， Z3740平板，2GB内存

**Comment by yukixz** [comment]
Bug by Chromium 51.

**Comment by einbrain** [comment]
そうだと思ったずい

**Comment by KochiyaOcean** [comment]
尝试在命令行下运行如下命令 `poi.exe --js-flags="--touch-events"` 看看是否有效？

**Comment by einbrain** [comment]
改chrome flag没有发现明显变化。
新发现：猛戳ui可以恢复响应。
触摸不响应好像是随机出现的。数据更新/鼠标操作此时正常。

**Comment by KochiyaOcean** [comment]
没有触摸屏设备所以很难长时间测试……OTL

**Comment by dkwingsmt** [comment]
麻烦测试 poi v6.3.1-beta.2 是否已经修复，可在最新 release 或度盘找到。

**Comment by einbrain** [comment]
v6.3.1-beta.2 (32bit)还是会失去反应。跟文本框不是同一个问题？
有时候多点几下能有反应；或者会有鼠标悬停效果，但是不执行Button-down/up
问题出现的时机也有随机性，不太好测试Orz

**Comment by einbrain** [comment]
订正，发作时无法选择文本框/点击登录按钮。

**Comment by EdiTurn** [comment]
Android，Microsoft remote desktop 远程控制 Windows 10 64 bit 主机，同样存在此问题，或可用此途径测试。

另：beta 2 在我的两台 Windows 10 64 bit 电脑上，web 界面均无法显示，始终为白屏。

**Comment by KochiyaOcean** [comment]
不容易复现的话实在没办法测试……

**Comment by KochiyaOcean** [comment]
@EdiTurn 右键点左下角按钮开下开发者工具看看网络状态

**Comment by EdiTurn** [comment]
@KochiyaOcean 网络状态为空白，点击 F5 后也是一样，如图。**但即便使用 beta 1，Network 同样空白。**
![1](https://cloud.githubusercontent.com/assets/5492805/16219133/af0f73e8-37b6-11e6-8338-3339e70f9856.png)

提供一些额外的测试步骤：
1. 删除 Roaming 下的 poi 文件夹，打开 6.3.0-beta 2，web 界面可以显示内容，但：
1）一开始页面内容正常，有滚动条，可以用鼠标滚轮滚动页面
2）随即大约一秒后，页面布局错乱，滚动条消失，亦无法用鼠标滚轮滚动页面，如图：
![2016-6-21t13 49 56](https://cloud.githubusercontent.com/assets/5492805/16219262/a9d27532-37b7-11e6-8fbc-ec7cebadb3c9.png)
2. 打开 6.3.0-beta 1，以上问题消失。

**Comment by KochiyaOcean** [comment]
@EdiTurn 左键开发者工具按钮为本体工具，右击才是网页的开发者工具

**Comment by KochiyaOcean** [comment]
@EdiTurn Fixed by https://github.com/poooi/poi/commit/c2f8288b2585962877197bddf8ee50996687b85a

**Comment by KochiyaOcean** [comment]
点了两小时 Nexus7 的屏幕没有一次复现的 OTL

**Comment by einbrain** [comment]
两个小时有可能不会再现问题。
我这台最长上午开机晚上才会出问题，不需要一直操作。

**Comment by castore** [comment]
thinkpad8也出现了这个问题 吃饭前打开游戏放置i之后就无法触控
