### ISSUE TITLE
kcwiki語音字幕異常?

### ISSUE THREAD

**Issue by scarletnight** [poooi/poi#1063]
我的是poi6.3.0版  語音字幕0.3.2版  無法顯示字幕
重新安裝也沒有用 檢查更新也沒有新的版本
不知道是不是不支援6.3.0版 還是有新版本沒檢查到?

**Comment by yukixz** [comment]
游戏内打开语音

On Saturday, 11 June 2016, scarletnight <notifications@github.com> wrote:

> 我的是poi6.3.0版 語音字幕0.3.2版 無法顯示字幕
> 重新安裝也沒有用 檢查更新也沒有新的版本
> 不知道是不是不支援6.3.0版 還是有新版本沒檢查到?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/poooi/poi/issues/1063>, or mute the thread
> <https://github.com/notifications/unsubscribe/ADLuwViRFi3mPgnxcmxx9RQNRh3yu40tks5qKo_sgaJpZM4Izhdr>
> .
>


-- 
*Dazzy Ding*
Email: h@dazzyd.org

**Comment by scarletnight** [comment]
已開 還是一樣 求解

**Comment by yukixz** [comment]
https://github.com/kcwikizh/poi-plugin-subtitle
cc @grzhan

**Comment by grzhan** [comment]
收到，我开个6.3.0的POI看看

**Comment by grzhan** [comment]
@scarletnight 在0.3.2更新字幕连接超时的异常处理可能有问题，导致游戏中无法正常显示字幕。

可以尝试重新安装字幕插件，或者打开beta更新提前升级到0.4.0-beta.0。

也可以尝试删除用于存放用户数据的目录下的`plugin-poi-subtitle`文件夹（OS X 上是`$HOME/Library/Application Support/poi`，Windows 上是 `%AppData%/poi`，其他类 unix 操作系统上是 `~/.config/poi`）

如果仍有问题，请打开开发者工具（软件左下角齿轮图标）把错误信息反馈给我

**Comment by scarletnight** [comment]
刪除資料夾後問題已解決!!
十分感謝!!
