### ISSUE TITLE
延遲

### ISSUE THREAD

**Issue by c933103** [poooi/poi#1064]
![screenshot 171](https://cloud.githubusercontent.com/assets/1525293/15986588/d97bed26-303d-11e6-9024-2876d5e41c5d.png)

**Comment by KochiyaOcean** [comment]
是游戏内的响应还是 UI 上的响应？

**Comment by feyfeytw** [comment]
請將 POI 完整刪除，並刪除 C:\Users\[username]\AppData\Roaming\ 下的 POI 資料夾刪除，再安裝一次，這應該能解決你遇到的問題
