### ISSUE TITLE
关于岛风go和POI的连接问题

### ISSUE THREAD

**Issue by ilikecola** [poooi/poi#1065]
直接通过HTTP协议连接岛风go启动后会卡黑屏，即游戏位置上没有网页，同时开发者工具表现为无法连接github头像库
通过socks5（SS）亦或者通过Fiddler转接到岛风go 均可进入网页

windows10
poi6.3.0~6.3beta
岛风go1.6.2.4

**Comment by yukixz** [comment]
这很明显是岛风狗的问题、你应该去找岛风狗开发者

On Sunday, 12 June 2016, ilikecola <notifications@github.com> wrote:

> 直接通过HTTP协议连接岛风go启动后会卡黑屏，即游戏位置上没有网页，同时开发者工具表现为无法连接github头像库
> 通过socks5（SS）亦或者通过Fiddler转接到岛风go 均可进入网页
>
> windows10
> poi6.3.0~6.3beta
> 岛风go1.6.2.4
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/poooi/poi/issues/1065>, or mute the thread
> <https://github.com/notifications/unsubscribe/ADLuwZSE6nGv9AQ_9w8otUWE4ExRkHG-ks5qK6PWgaJpZM4Izt3K>
> .
>


-- 
*Dazzy Ding*
Email: h@dazzyd.org

**Comment by ilikecola** [comment]
以及6.2.0是正常可以使用的 @yukixz

**Comment by KochiyaOcean** [comment]
6.3.1-beta.0 呢

**Comment by ilikecola** [comment]
@KochiyaOcean 同样
![qq 20160612142354](https://cloud.githubusercontent.com/assets/12741416/15989452/54bac956-30a9-11e6-841e-8e700eb99193.jpg)

**Comment by KochiyaOcean** [comment]
=_,= 6.2.0 到 6.3.x 的代理层没修改过(Chrome 内核从 49 升到 51), 除了你神秀逗以外真想不到别的可能性

**Comment by KochiyaOcean** [comment]
如果把 6.3.1-beta.0 的 `resources/app.asar` 和 `resources/PepperFlash` 复制到 6.2.0 的相同目录下依然有此问题就可以比较好的定位到原因所在

**Comment by ilikecola** [comment]
@KochiyaOcean 我尝试一下。我刚刚重启电脑以后立马只开poi似乎就可以打开网页。所以，我现在更倾向于岛风go侧的问题。如果再次发生问题是替换下文件试试。谢谢w
主要是这个问题只在更新6.3.0以后出现，6.3.0以前未曾出现过。

**Comment by DSakura1987** [comment]
岛风狗是要求你用他提供的PAC进行代理的，可能程序本身同样内置有白名单。
一句话，请勿使用不标准的HTTP代理玩游戏
