### ISSUE TITLE
6.3版本chrome bug

### ISSUE THREAD

**Issue by ggg17226** [poooi/poi#1070]
平板上（台电x2pro，coreM 5y10c），用google账户登录后跳转到dmm主页后点击dmm games按钮时画面卡住（本地地址已经变更，network可以看到资源文件下载），使用6.2版本的环境运行正常（使用6.3版本的app.asar）

**Comment by KochiyaOcean** [comment]
@ggg17226 请报告完整版本号

**Comment by ggg17226** [comment]
出现问题版本：v6.3.0
目前是使用v6.3.0的app.asar放入v6.2.0的环境中运行

**Comment by ggg17226** [comment]
系统版本 win10 10586
