### ISSUE TITLE
POI代理问题

### ISSUE THREAD

**Issue by edwardaaaa** [poooi/poi#1071]
把POI代理设置关闭，和chrome一样走系统代理，为何chrome能上舰娘，POI却连墙都爬不了了？

PS:chrome零插件。

**Comment by yukixz** [comment]
@edwardaaaa 系统？

**Comment by KochiyaOcean** [comment]
@edwardaaaa poi 在关闭代理时不会使用系统代理的 PAC（而 Chrome 会），如果有使用 PAC 的必要请在设置里设置 PAC 的地址

**Comment by edwardaaaa** [comment]
@yukixz 10.11

**Comment by edwardaaaa** [comment]
@KochiyaOcean 我用的是Mac 版本的surge，按原作者说是整个系统都套上代理服从地理IP国内外的区分规则，没有使用pac。

**Comment by yukixz** [comment]
@edwardaaaa 系统设置 网络 代理

**Comment by edwardaaaa** [comment]
@yukixz 
![screen shot 2016-06-20 at 13 06 28](https://cloud.githubusercontent.com/assets/11089376/16183737/d9bdb55c-36e7-11e6-86b1-b33ddda5dc64.png)
![screen shot 2016-06-20 at 13 06 31](https://cloud.githubusercontent.com/assets/11089376/16183739/da26d1e0-36e7-11e6-946b-698959004eef.png)
![screen shot 2016-06-20 at 13 06 33](https://cloud.githubusercontent.com/assets/11089376/16183738/da0df102-36e7-11e6-95d8-fade9a686111.png)

**Comment by yukixz** [comment]
@edwardaaaa surge 同时开了这么多服务…… 随便挑一个塞 poi 里呗

**Comment by edwardaaaa** [comment]
@yukixz POI里设置代理本身都是没问题的一直可以玩，但因为POI总是比chrome慢半拍，我想可能是代理模块之类的问题，所以想试着和chrome一样走系统代理，才关闭POI的代理设置的。。。

**Comment by KochiyaOcean** [comment]
@edwardaaaa 要扒数据所以多经过一层代理肯定会慢一点……现在的最新 beta 有稍微优化代理性能可以看看
