### ISSUE TITLE
当焦点位于开发者工具窗口时点击 F5 导致程序关闭

### ISSUE THREAD

**Issue by EdiTurn** [poooi/poi#1073]
操作系统：Windows 10 pro 14367
测试已存在问题的版本：6.3.0 及以上版本。
复现步骤：打开开发者工具，点击 F5。如果开启了「关闭前确认」功能则会弹出提示框。

**Comment by yukixz** [comment]
@EdiTurn 可能不会修复🌚

**Comment by KagamiChan** [comment]
ref electron/electron#664
