### ISSUE TITLE
集中反馈关于触屏、任务、更新版本的几个问题

### ISSUE THREAD

**Issue by yxmxyxy** [poooi/poi#1074]
以下使用的环境均为32位Win10，POI均为32位windows版本：

1：使用过的6.2、6.3.1Beta2均有任务列表与游戏内不符的情况，在“全”标签里把任务全翻一遍后还有实际已完成或未解锁的顽固任务一直赖在POI的任务列表里。（问题是在游戏实装任务标签一段时间之后出现的）

2：6.3.1B2，POI的UI界面经常不响应触屏操作（好像刚打开POI的一段时间基本没事，搁置一段时间再按就没反应了，狂点有小概率响应一下…），游戏界面内没问题，用TouchMouesPointer模拟鼠标也全正常。
（小情况：有一次POI界面不响应中，点击右上退出游戏时弹出是否确实要退出的对话框，这时触屏点击对话框不仅没关闭，还点到后面的游戏界面里去了）
（最新情况：界面不响应时点一下关闭弹出确认对话框之后会恢复-_-|||）

3：各版本均存在，新版本覆盖旧版本文件，或是删除旧版本把新版本放在原目录下，运行新版本游戏几乎一定会导致游戏白屏或灰屏，重装、回退版本、重启系统均无效，要换一个路径（给文件夹重命名一个以前没用过的名字）才有可能解决。

**Comment by dkwingsmt** [comment]
1 的问题是 duplicate of #1060 ，7.0.0 版的 activeQuests 机制能够有效删除过时的活动任务
