### ISSUE TITLE
6.3.1 分辨率随窗口变化的情况下会导致白屏

### ISSUE THREAD

**Issue by FungJiHsu** [poooi/poi#1079]
如題

**Comment by KochiyaOcean** [comment]
请提供更加详细的信息谢谢……

**Comment by FungJiHsu** [comment]
@KochiyaOcean 網絡環境ACGP；一開始exe更新，發現默認在C盤，刪除后，用壓縮包覆蓋更新

**Comment by einbrain** [comment]
PS 6.2.0 正常Again

**Comment by yukixz** [comment]
尝试显示设置改一下分辨率

**Comment by einbrain** [comment]
固定分辨率解决问题
自适应分辨率再次白屏

**Comment by yukixz** [comment]
根据qq群里反馈、自适应导致白屏仍然能听到 flash 的声音。
cc @KochiyaOcean

**Comment by lilipeipei** [comment]
【MAC】启动白屏，有flash声音

**Comment by Shallong11** [comment]
Mac 上也是白屏，尝试清空缓存和cookie之后会有DMM登陆界面，登陆完成之后重定向到游戏URL就白屏了~

**Comment by KochiyaOcean** [comment]
@Shallong11 bug 已经知道在哪里了，回去修

**Comment by KochiyaOcean** [comment]
对应的正式版 6.3.2 已经发布噜

**Comment by FungJiHsu** [comment]
@KochiyaOcean 6.3.3的自動適配變成這樣
![2016-7-1t8 50 23](https://cloud.githubusercontent.com/assets/14539399/16508778/080f272c-3f69-11e6-8f15-462af642e28d.png)

**Comment by KochiyaOcean** [comment]
@FungJiHsu webview 宽度？

**Comment by FungJiHsu** [comment]
@KochiyaOcean 744*446px

**Comment by FungJiHsu** [comment]
@KochiyaOcean 我用縱版佈局

**Comment by KochiyaOcean** [comment]
@FungJiHsu 没有重现*2
![image](https://cloud.githubusercontent.com/assets/8194131/16508975/e0985df6-3f6a-11e6-87b6-7b0e11228cf3.png)

**Comment by FungJiHsu** [comment]
@KochiyaOcean ...這樣就神奇了..我試一下切換到橫版再換回來

**Comment by FungJiHsu** [comment]
@KochiyaOcean 果然..切換一下之後，恢復正常
