### ISSUE TITLE
[Win] 第二次启动程序卡白屏

### ISSUE THREAD

**Issue by wafer-li** [poooi/poi#1080]
OS: Win 10 Pro x64
Electron: v1.2.5
Poi: 6.3.1

症状：开机第一次打开 poi 正常，关掉，再打开，卡白屏。此时进行 Windows 重启，卡在蓝屏转圈圈。

测试过：
1. 打开电脑立即重启，正常
2. 使用 electron 官方的 app 进行上述步骤，正常
3. 在第一次打开 poi 能正常使用的情况下，使用任务管理器结束 poi 的 electron 进程，则第二次启动也正常，系统重启正常。

此 Bug 仅在本人机器上重现过，不知是个案还是真的 Bug。

**Comment by yukixz** [comment]
@wafer-li 尝试显示设置改一下分辨率

**Comment by wafer-li** [comment]
@yukixz  指的是 poi 的显示设置还是系统的？

**Comment by yukixz** [comment]
see #1079

**Comment by wafer-li** [comment]
@yukixz 
跟那个 issue 有一点不一样，我即使去除勾选自适应，也依然出现了这种状况。

**Comment by KochiyaOcean** [comment]
看看最新的 commit 有没有修复罢

**Comment by wafer-li** [comment]
@KochiyaOcean negative. 尝试着重新 clone 一次之后就进化到直接卡白屏了，删除了 appdata 下的 poi 文件夹也不起什么作用。

**Comment by KagamiChan** [comment]
今天我是直接 pull 和 npm i 之后白屏，然后整个删了重 clone 也白屏，最后下了 release 也白屏
不过虽然不知道原理是什么，但是重启之后就好了 - -

**Comment by wafer-li** [comment]
@KochiyaOcean 嗯…… 目前我找到了另一个重现方式。

把 `分辨率随窗口自适应` 复选框从勾选状态变为非勾选状态，第二次重启必定卡白屏。

我这边可以稳定重现，不知道这个是不是症结所在。

**Comment by wafer-li** [comment]
目前版本使用将近 2 天后未重现 bug，应该已经没了。
