### ISSUE TITLE
希望在舰娘信息插件属性中加入对潜一栏

### ISSUE THREAD

**Issue by kaneyukikaze** [poooi/poi#1081]
更新对潜后在舰娘信息中发现没有对潜属性，希望能增加一项，这样比较方便找到加装备后对潜值大于100的船。。

**Comment by jayjayzju** [comment]
Done.

https://github.com/poooi/plugin-ship-info/commit/86fbdc7b36ac6ee2aa051ce6036f56665cec68f6
