### ISSUE TITLE
更新6.3.3之后poi一直黑屏

### ISSUE THREAD

**Issue by 273126559** [poooi/poi#1082]
本来3.1用的好好的昨天更新了新反潜 所以更新了 然后更新回来发现黑屏 但是听得到游戏声音，就无限这样，然后我想降版本 降回3.1 还是黑屏 完全不懂什么情况 也没开什么软件 就1个qq  不知道和什么冲突，win10系统 还是说poi不支持win10盗版？

**Comment by KochiyaOcean** [comment]
如果说降回旧版本也一样的话就很难判定为代码上的问题了哦……

**Comment by 273126559** [comment]
@KochiyaOcean 嗯，，其实我也不是很懂 但是今晚的时候解决了，我把兼容性改成win7 就可以正常使用了，但是奇怪的是 昨天win10突然需要重新激活 我又找不到win10的那个激活码就无视了。 然后我升级了poi最新版就黑屏了， 估计我这是特例吧

**Comment by yangkki** [comment]
你不是一个人，，，正版win10一样黑，6.3.1-6.3.3都是黑的。。。除非你换6.2

**Comment by 273126559** [comment]
@yangkki 你要是升级6.3后面的版本可以试试我说那个方法 把兼容性改成win7 好像就可以了，目前我是这样玩的，假如不调兼容性的话 还是黑屏的说。。。

**Comment by yangkki** [comment]
我改了也没办法。。。我一般是重启就好了，感觉是概率事件，时好时坏，非常神奇，但是太麻烦了，我直接用6.2的版本了，目前非常正常，无黑屏的说
