### ISSUE TITLE
未卜先知血量移位

### ISSUE THREAD

**Issue by Aisuzuka** [poooi/poi#1083]
插件的Issues不知道是不是也能開在這，如果不是的話請告訴我～
![2016-07-01 1](https://cloud.githubusercontent.com/assets/13333257/16524155/8ffa8896-3fd9-11e6-8b78-99786651f025.png)

未卜先知的艦娘血量殘值，會隨著血條移動，不知道是Code寫錯，還是新的設計呢?

**Comment by KochiyaOcean** [comment]
@Aisuzuka 版本太旧了，更新一下

**Comment by Aisuzuka** [comment]
POI版本6.3.3
未卜先知版本5.2.1
