### ISSUE TITLE
Centos 6.5 图形化界面运行报错

### ISSUE THREAD

**Issue by YazawaMadoka** [poooi/poi#1090]
打开无反应 在终端输入poi系统返回undefined symbol: g_bytes_unref

**Comment by axmmisaka** [comment]
试试之前的版本先看看哪个好用吧

**Comment by KagamiChan** [comment]
我手头有一个全新安装的 centos 6.5，upgrade 了之后因为 libstdc++ 的版本原因是提示不能启动的
所以你是自己编译安装了吗

**Comment by YazawaMadoka** [comment]
> 我手头有一个全新安装的 centos 6.5，即使 upgrade 了之后也因为 libstdc++ 的版本原因是提示不能启动的
所以你是自己编译安装了这些依赖吗

是的，网上查了解决办法然后重新编译了，不过依旧报错undefined symbol: g_bytes_unref

**Comment by dkwingsmt** [comment]
electron 的问题去[https://github.com/electron/electron](找 electron 发 issue) 呀。尝试运行一下[https://github.com/electron/electron-quick-start](最小测试样例)看看会不会出错。

**Comment by dkwingsmt** [comment]
electron 的问题去[找 electron 发 issue](https://github.com/electron/electron/issues) 呀。尝试运行一下[最小测试样例](https://github.com/electron/electron-quick-start)看看会不会出错。

**Comment by KagamiChan** [comment]
可以先试试运行 electron 的 build，如果也不行的话，再检查一下你自己编译依赖的过程
（CentOS 包更新比较保守，如果是玩游戏的话建议换到新版本或者别的发行版
