### ISSUE TITLE
分辨率设为0X0后闪退

### ISSUE THREAD

**Issue by choohoo** [poooi/poi#1091]
操作系统：windows10 64bit
软件版本：v6.3.3 64bit 7z版
复现步骤：分辨率设为0X0，不做其他操作直接关闭poi，再次启动poi，加载完成后显示内容的瞬间进程消失。
备注：我在Win10 64位的虚拟机下试了一下，至少在我的虚拟机中是100%复现的。

**Comment by KochiyaOcean** [comment]
Will be fixed on the branch merged to master.
