### ISSUE TITLE
编成日记制空显示bug

### ISSUE THREAD

**Issue by RyoLee** [poooi/poi#1098]
编成日记显示的制空值="基础制空"+"熟练度加成"
错误显示为最小制空+最大制空 ，得到了接近翻倍的结果
举个栗子↓
![-1](https://cloud.githubusercontent.com/assets/1842651/16979421/9da31b98-4e93-11e6-81cc-b43e6c1bbb95.png)
![qq 20160720160626](https://cloud.githubusercontent.com/assets/1842651/16979493/f5663c66-4e93-11e6-883b-d498647bc448.jpg)

实际值↓
翔鶴改二	152～153
雲龍改	87
千歳航改二	114～115
総制空値：353～355
舰队页面显示的和算出来的一样↓
![qq 20160720160658](https://cloud.githubusercontent.com/assets/1842651/16979511/0241192e-4e94-11e6-91db-1cd1ec8c7f62.jpg)

**Comment by ruiii** [comment]
请更新到最新版本的编成日记
 v3.9.1 - v3.9.2 版本之间添加的记录都可以删除掉。。
