### ISSUE TITLE
添加一个 poi 模块的 require path

### ISSUE THREAD

**Issue by dkwingsmt** [poooi/poi#1099]
使用 `require('module').globalPaths.push` 将 poi 的根目录放进 `require` 的目录后，可以避免
```
import Foo from '../../../../Bar/Baz'
```
这种代码的出现，而改为
```
import Foo from 'view/Bar/Baz'
```
便于下一步拆分 utils 。

现在有两个方案，一是设定在根目录（ `index.html` 所在的文件夹），二是设定在 `view`。

后者的好处自然是，因为几乎全部的 `import` 都是 `view` 文件夹里的，所以可以少写一大堆 `view/`。
有个潜在的问题是，可能跟库冲突（虽然现在应该还没有），比如如果有个库叫 `components` 的话。

所以，选择哪种？

**Comment by KochiyaOcean** [comment]
@dkwingsmt eslint 的配置也要相应更改说……

**Comment by dkwingsmt** [comment]
为啥？
