### ISSUE TITLE
POI打开以后黑屏

### ISSUE THREAD

**Issue by LunaPapillon** [poooi/poi#1104]
打开poi之后始终黑屏
<img src="http://imgsrc.baidu.com/forum/w%3D580/sign=72ae636a9ceef01f4d1418cdd0fe99e0/7b104cf790529822b42fe3cddfca7bcb0a46d450.jpg" width="300" height="225" />

之前遇到过两次这个问题 删除了岛风go的那个proxy.pac就能用了 
但是这次删除了proxy.pac 清理了cookies和缓存 重新校对了Internet时间 注销重启了 几次都不能用 想请问一下怎么解决

**Comment by KochiyaOcean** [comment]
代理设置是什么

**Comment by GaloisGun** [comment]
HTTP 代理  地址 127.0.0.1  端口8099  也是一样的问题

**Comment by FXuZ** [comment]
同样的问题, v6.3.4, debug console在一大堆warning 之后出error
```
/home/my/linux/resources/app.asar/node_modules/react-overlays/lib/Modal.js:478 Uncaught RangeError: Maximum call stack size exceeded. enforceFocus @ /home/my/linux/resources/app.asar/node_modules/react-overlays/lib/Modal.js:478
4web-view.js:101 Uncaught RangeError: Maximum call stack size exceeded.
```
