### ISSUE TITLE
想請問win10遊戲沒有反應

### ISSUE THREAD

**Issue by roderichlind** [poooi/poi#1106]
按下poi捷徑後沒有任何反應也沒有任何視窗開啟
但是工作台後方卻有顯示poi有在執行
請問這是問甚麼造成的..?
謝謝!!

**Comment by KochiyaOcean** [comment]
@roderichlind 托盘有图标么，点击是否有响应

**Comment by roderichlind** [comment]
@KochiyaOcean 阿回復得好快啊~
抱歉台灣人, 請問托盤是甚麼?
我點遊戲是沒反應的, 但是工作管理員卻有顯示在執行
然後現在poi的捷徑沒有圖示了

**Comment by KochiyaOcean** [comment]
@roderichlind 
![image](https://cloud.githubusercontent.com/assets/8194131/17225442/8d1e45ea-5537-11e6-8ef0-be7c98d9c7e7.png)
总而言之就是这东西……如果加载成功的话右键会有菜单出来

**Comment by roderichlind** [comment]
並沒有...長期都有再用poi剛剛在整理電腦的時候有將explorer.exe重啟過
不知會不會是這個問題

**Comment by KochiyaOcean** [comment]
@roderichlind 在任务栏的搜索框搜寻 cmd 然后在结果中右键选择用管理员运行（不懂台湾的用语不过差不多是这个意思），输入 netsh winsocks reset 看看

**Comment by roderichlind** [comment]
他寫 the following command was not found: winsocks reset

**Comment by KochiyaOcean** [comment]
@roderichlind 刚才打错了，是 winsock 没有 s

**Comment by roderichlind** [comment]
恩~剛重開了電腦

**Comment by roderichlind** [comment]
沒變...情況還是一樣

**Comment by roderichlind** [comment]
![default](https://cloud.githubusercontent.com/assets/20709927/17225932/8abbe83c-5539-11e6-9821-339cc73ede84.jpg)
大概是這樣

**Comment by KochiyaOcean** [comment]
@roderichlind 不是很清楚什么情况说实话……重新下载一次最新版看看？

**Comment by roderichlind** [comment]
下載過了還是一樣~

**Comment by roderichlind** [comment]
完了...準備要活動了

**Comment by KochiyaOcean** [comment]
@roderichlind 同样打开 cmd，把 poi.exe 拖进去回车有报错么

**Comment by roderichlind** [comment]
剛剛拖曳到CMD有開啟了...
可是一直這樣也不是辦法

**Comment by KochiyaOcean** [comment]
@roderichlind 唔，可能需要更多信息……

**Comment by roderichlind** [comment]
我是可以讓你遠端我不介意..

**Comment by KochiyaOcean** [comment]
@roderichlind 今天太晚了，改天吧

**Comment by roderichlind** [comment]
喔好的請問明天都可以找到你嗎?

**Comment by KochiyaOcean** [comment]
@roderichlind 给个邮箱之类的到时候我邮你？

**Comment by roderichlind** [comment]
ok

roderichlind@gmail.com
