### ISSUE TITLE
可以使用了

### ISSUE THREAD

**Issue by roderichlind** [poooi/poi#1107]
稍早自己隨便用一用就修復了, 現在還有兩個小問題

1. 收回工具列的圖示變成了不明檔案的圖示
2.遠征插件Ver. 3.0.0 beta似乎更新不了?
![default](https://cloud.githubusercontent.com/assets/20709927/17237206/fc2970f0-5581-11e6-84ca-7a251546ccb1.jpg)

**Comment by ruiii** [comment]
@roderichlind 远征插件 3.0.0-beta 版不兼容目前发布的本体版本，暂时还不需要更新插件。@dkwingsmt 可以 unpublish 吗？

**Comment by KochiyaOcean** [comment]
@roderichlind v3.0.0-beta.0 是下一个版本将要使用的，并不支持 6.3.3

**Comment by roderichlind** [comment]
@ruiii @KochiyaOcean 了解了
請問那個不明程式的圖案有解嗎?

**Comment by KochiyaOcean** [comment]
@roderichlind 重新钉到任务栏上看看？

**Comment by roderichlind** [comment]
變這樣...
![dsadsa](https://cloud.githubusercontent.com/assets/20709927/17237728/8e550fca-5587-11e6-8472-cf1be2f12fe6.png)

**Comment by KagamiChan** [comment]
之前看你的 poi.exe 程序图标就是这样的，正常情况下会是：
![image](https://cloud.githubusercontent.com/assets/3816900/17237895/519a9832-5589-11e6-8b7c-aa94f82cd5b6.png)

可先清除一下图标缓存看一下能不能解决
按 win+R，输入

```
ie4uinit.exe -ClearIconCache
```

和

```
ie4uinit.exe -show
```

试试看
（参考 http://superuser.com/questions/499078/refresh-icon-cache-without-rebooting）

**Comment by roderichlind** [comment]
@KochiyaOcean 我找到之前打不開似乎是開啟時建立捷徑我把他勾選了, 
然而因為我剛找到答案, 現在又打不開了.....

**Comment by roderichlind** [comment]
@KochiyaOcean 等我打開後我來測試

**Comment by roderichlind** [comment]
請問可以給我poI在電腦裡面緩存的路徑嗎?
我乾脆全部砍掉, 搞不好問題都解決了

**Comment by roderichlind** [comment]
@KochiyaOcean 好了基本上問題都解決了
我剛測試了"啟動時建立捷徑"會影響poi的開啟
您的圖片緩存也將我的圖案問題解決了
不好意思占用您這麼時間~
![default](https://cloud.githubusercontent.com/assets/20709927/17238185/21e46b9c-558c-11e6-8310-aaf7d44f7ca3.jpg)
