### ISSUE TITLE
插件升级 i18n 更新

### ISSUE THREAD

**Issue by dkwingsmt** [poooi/poi#1109]
插件在更新之后，如果 i18n 文件更新了的话，现在不会更新 i18n 文件。
复现：远征插件，新版（3.0.0）比旧版（2.1.2）新添了 i18n 条目（新版把鼠标放到中栏的红叉上可以看到不满足的条件），如果从旧版更新到新版然后不重启 poi 的情况下，插件会是新版，但是那几条没有翻译。
（复现的时候注意，如果现在是安装的3.0.0的话，那么先删除3.0.0然后重启 poi，再安装旧版，否则内存中存的还是新版的 i18n）

**Comment by KochiyaOcean** [comment]
可能需要去看一下 i18n-2 的实现

**Comment by KochiyaOcean** [comment]
哦好吧大概重载一下 i18n-2 就行了
