### ISSUE TITLE
poi无法使用

### ISSUE THREAD

**Issue by sgdb17** [poooi/poi#1111]
poi在使用中突然报错，再开之后整个窗口都是白的，点上去毫无反应，等待较长一段时间后会显示黑色面板但点击依旧无反应，只要打开之后就只能在进程里强关
重启电脑重下poi都试过了，就算换了版本也依旧有这个问题，求解决方法
代理用的是岛风go

**Comment by KochiyaOcean** [comment]
至少给个截图啊……

**Comment by sgdb17** [comment]
![731231236](https://cloud.githubusercontent.com/assets/20754437/17277058/d2e43208-5774-11e6-9678-d02601346006.png)

**Comment by sgdb17** [comment]
![731101556](https://cloud.githubusercontent.com/assets/20754437/17277071/01e482ba-5775-11e6-8221-9d62631fded7.png)

**Comment by sgdb17** [comment]
![731232120](https://cloud.githubusercontent.com/assets/20754437/17277089/908b25f0-5775-11e6-87be-b347005cf1c3.jpg)
最后卡在这里完全动不了

**Comment by dkwingsmt** [comment]
@sgdb17 已复现，我来调下

**Comment by KochiyaOcean** [comment]
Fixed?

**Comment by sgdb17** [comment]
今天看到更新，下了v7.0.0-beta.1，打开之后依旧有长时间的白屏，不过之后出现的新版本提示已经可以关掉了，下方面板的设置等按钮也可以操作，只是网页没有自动打开，手动在地址栏输入www.dmm.com之后响应了很久网页才打开，而且点击网页无反应，之后在地址栏重新输入http://www.dmm.com/netgame/，结果不论上方网页还是下方面板都无响应了
![qq 20160803192547](https://cloud.githubusercontent.com/assets/20754437/17362769/9b7428ca-59b1-11e6-803c-0dfaa642408f.png)

**Comment by sgdb17** [comment]
等了一顿饭的时间网页跳转过去了，但点击网页依旧无反应
下方面板也可以点击选择，只是响应速度非常慢
![qq 20160803195955](https://cloud.githubusercontent.com/assets/20754437/17363405/36f05866-59b5-11e6-8340-d208c5f8cda1.png)

**Comment by sgdb17** [comment]
下方面板现在已经可以顺畅点击切换，插件也能正常更新了，只是网页始终无响应

**Comment by KochiyaOcean** [comment]
@sgdb17 你机器的配置是什么

**Comment by sgdb17** [comment]
![qq 20160803201116](https://cloud.githubusercontent.com/assets/20754437/17363620/7cf42e18-59b6-11e6-9d61-957eacced1d9.png)

**Comment by KochiyaOcean** [comment]
开发者工具有无报错

**Comment by sgdb17** [comment]
@KochiyaOcean 那是什么。。。？

**Comment by sgdb17** [comment]
![qq 20160803223257](https://cloud.githubusercontent.com/assets/20754437/17367283/61408360-59ca-11e6-8416-b72e37ee54a8.png)
![qq 20160803223327](https://cloud.githubusercontent.com/assets/20754437/17367279/5edab212-59ca-11e6-939f-0c3ec56e8efa.png)

是这部分么？

**Comment by KochiyaOcean** [comment]
大概想到原因了，你在这里执行 delete localStorage 然后重启试试看

**Comment by sgdb17** [comment]
重启之后poi还是老样子，不过这下连岛风go都无法正常使用了。。。
![qq 20160804001049](https://cloud.githubusercontent.com/assets/20754437/17370703/0026f20e-59d8-11e6-83fc-0835b4812d7e.jpg)

**Comment by KochiyaOcean** [comment]
总感觉这就和 poi 没什么关系了呀……

**Comment by sgdb17** [comment]
原来正好碰上岛风go炸了。。。这时间太巧了。。。
只是poi问题依旧在

**Comment by sgdb17** [comment]
原来正好碰上岛风go炸了。。。这时间太巧了。。。
只是poi问题依旧在

**Comment by KochiyaOcean** [comment]
@sgdb17 卸载字幕插件看看？

**Comment by sgdb17** [comment]
把所有插件都卸载并重启了，现在poi响应虽然还是很缓慢但是已经能点开登入页面了，只是点击login或回车网页都无反应
![qq 20160804193552](https://cloud.githubusercontent.com/assets/20754437/17399110/56dfba10-5a7b-11e6-998e-8cc82e136356.jpg)
![qq 20160804193621](https://cloud.githubusercontent.com/assets/20754437/17399123/64779e5e-5a7b-11e6-96cd-f6bdeef6b659.jpg)

**Comment by KochiyaOcean** [comment]
@sgdb17 进程的内存和 CPU 占用如何

**Comment by sgdb17** [comment]
![qq 20160804195759](https://cloud.githubusercontent.com/assets/20754437/17399583/d8ccbbde-5a7d-11e6-82ed-d05c48c48f5f.png)
试着重输网址使poi变成无响应状态并一直等到页面刷新成功，期间内存和cpu没什么大变化

**Comment by KochiyaOcean** [comment]
@sgdb17 其它 poi 进程的占用呢？

**Comment by sgdb17** [comment]
![qq 20160804202130](https://cloud.githubusercontent.com/assets/20754437/17400113/148b5e98-5a81-11e6-84fc-6c4cd642aeb5.jpg)

**Comment by sgdb17** [comment]
今天win10系统有更新，开机后提示了一个没记住名字的权限和岛风go的权限，都选择了确定并尝试开poi之后发现能用了，既不卡也没发生无响应的情况。然而在重装了所有插件之后，产生了基本信息和设置的界面图层重叠的情况（没截到图），关掉poi重开之后这次变成了白屏→黑屏，只是现在已经不会有很卡或者无响应的情况了
![qq 20160811194804](https://cloud.githubusercontent.com/assets/20754437/17586412/9a9bb32c-5ffc-11e6-801d-b4dc1f97a10d.png)

**Comment by KochiyaOcean** [comment]
@sgdb17 版本？

**Comment by sgdb17** [comment]
poi-7.0.0-beta.1-win-x64
怀疑是插件的锅

**Comment by sgdb17** [comment]
原来有过版本更新，换用poi-7.0.0-beta.2-win-x64之后使用正常了
