### ISSUE TITLE
[7.0.0-beta.0] poi 黑屏

### ISSUE THREAD

**Issue by wafer-li** [poooi/poi#1112]
OSX 10.11.5
poi's version: At this commit 3995f2f3e7d94cb1a2b813c8f9054e93ce31a323

如图。

![image](https://cloud.githubusercontent.com/assets/12459199/17277062/eb2450f0-5774-11e6-8bb5-2d0d9ff80e07.png)

**Comment by dkwingsmt** [comment]
`npm i` 过吗？试试

**Comment by wafer-li** [comment]
@dkwingsmt 

试过的。

![image](https://cloud.githubusercontent.com/assets/12459199/17277086/7ba40e68-5775-11e6-909e-bf1bd48ed43d.png)

**Comment by KochiyaOcean** [comment]
最好 `npm ls` 然后把里面的版本和 `package.json` 里的对比一下

**Comment by wafer-li** [comment]
@KochiyaOcean  

我不知道应该如何对比，下面是我 `npm ls` 出来的内容。
https://gist.github.com/wafer-li/07bf5fb905a3d77869bdbdbe824412f7

PS：不过我用了个 online diff 稍微看了一下，上面的版本应该比 `package.json` 只高不低。大概版本号的差别在 0.0.1 到 0.1 之间。

我用的是 `npm run deploy_directly` 这个，我试着看用 `npm run deploy` 会怎么样。

**Comment by dkwingsmt** [comment]
@wafer-li 试下最新的 poi commit

**Comment by dkwingsmt** [comment]
@wafer-li 另外如果要安装3.0.0版远征插件的话，要么在第一次进入游戏之后安装/升级，要么npm link最新的 commit （还未发布），因为也有类似问题。

**Comment by wafer-li** [comment]
@dkwingsmt 

问题解决了。

PS1: 还有个界面上的小问题，如图

![image](https://cloud.githubusercontent.com/assets/12459199/17277288/54fd0774-577a-11e6-9d8e-6a8d1c6915d3.png)

那个加载圈在公转，而不是自转，不知道看不看得清楚。。。

PS2: 😂 所以我这边现在要不要安装远征插件 3.0.0？

**Comment by KochiyaOcean** [comment]
@wafer-li 我本地测试没有这种问题就是……

**Comment by wafer-li** [comment]
@KochiyaOcean 
negative.

![image](https://cloud.githubusercontent.com/assets/12459199/17277355/04b7e84a-577c-11e6-9c6a-84e9401b6111.png)

**Comment by dkwingsmt** [comment]
@wafer-li 我发布了，如果看到是 beta.2的话就可以装

**Comment by wafer-li** [comment]
@KochiyaOcean 

取消了动画效果之后发现加载圈并没有垂直居中，有没有可能是这个引起的？

![image](https://cloud.githubusercontent.com/assets/12459199/17277440/a2cb3112-577d-11e6-8274-0e2de614f0b2.png)

**Comment by wafer-li** [comment]
@dkwingsmt 

顺便一提现在 console 还有一大堆 warning ，不过游戏倒是能玩起来了。

**Comment by dkwingsmt** [comment]
@wafer-li 有 warning 的话你……再 npm i react-bootstrap 一次试试看……我这里是没有任何 warning 了。

**Comment by KochiyaOcean** [comment]
@dkwingsmt 其实原因是 React 15.3.0 加了新的 warning 项目，如果要去掉只能降级到 15.2.1

**Comment by wafer-li** [comment]
@KochiyaOcean 
@dkwingsmt 

😂 那我就不管 warning 了

**Comment by KagamiChan** [comment]
作为参考，我这边重新 clone 之后，删掉插件文件夹之后好了
（不排除我自己写的插件没跟着文档更新的原因

**Comment by wafer-li** [comment]
All fixed.
