### ISSUE TITLE
主面板舰娘信息显示不正确

### ISSUE THREAD

**Issue by FXuZ** [poooi/poi#1114]
更新到master上最近的commit, 之前6.3.3的黑屏没有了但是仍然有几十个warning, 界面很多地方没有换成正确的语言, 舰娘信息插件没法工作, 然后打开之后内存会一直上涨, 在半小时左右可以吃到3G以上, 然后再过20min左右可以吃得比FF还多吃到5G以上一直吃到swap... 之后有时候可以恢复正常. 以及, 主面板的舰队信息貌似没法更新了, 于是和实际舰队完全不一样.

下面是截图, 主要想说第一舰队在主面板的显示在打开之后仍然正确但是后来会完全停止更新编队中舰娘的状态, 舰队信息面板则是完全没有更新. 以及, 舰娘信息插件完全没有显示, 

![bug_front_panel.png](https://ooo.0o0.ooo/2016/08/01/579fe5146c559.png)
![bug_fleet_info.png](https://ooo.0o0.ooo/2016/08/01/579fe516f24b3.png)
![舰娘信息_033.png](https://ooo.0o0.ooo/2016/08/01/579fe95022538.png)

这部分相关的报错(我看log猜的...)我贴在了 [这里](http://pastebin.com/EW9z8Nsw) 和 [这里](http://pastebin.com/gXaCaukp).

测试中node_modules 确定更新过, 舰娘信息插件删除重新安装过, app_compiled 重新gulp deploy过... 本地的electron-prebuilt 是更新过的v1.3.1, 所以我猜应该不是其他包没更新的问题吧...

以上.

**Comment by FXuZ** [comment]
#### 追加 comment
之前本人只是发现poi内存吃得特别快, 吃到swap之后开始响应非常慢, 于是我认为有内存泄漏. 在内存不断上涨的时候会发现主面板信息部分没更新的问题, 过一段时间之后内存占用可以降下来然后主面板信息又继续更新, 接着内存占用就会升上去到一个稳定值的样子, 并不会吃到swap影响性能.

**Comment by KochiyaOcean** [comment]
@FXuZ 是最新的 commit 么

**Comment by dkwingsmt** [comment]
@FXuZ 把舰娘信息插件关了看是否还会出现内存泄露和信息不正确？

**Comment by dkwingsmt** [comment]
@FXuZ 我指的是，删除了

**Comment by FXuZ** [comment]
@KochiyaOcean 嗯大概2小时前pull的...

**Comment by KochiyaOcean** [comment]
无法重现……

**Comment by KochiyaOcean** [comment]
npm script 那块太烂了找个时间重写一遍好了 OTL

**Comment by FXuZ** [comment]
删掉舰娘信息插件, 我一直看着内存占用正常肝船,

- 我能看到内存占用上涨大致都和出击进下一点和回港动作巧合(随便找可以打的点, 在4-5发现这一点)
- 以及能看到后台log回港都会出一堆warning/error

上次测试看到内存泄露就是在刷闪这样进击还有回港频率比较高的时候出现的. 到内存占用快到顶的时候可以看到flash画面的动作和主面板信息更新有明显的延迟. 这次我在3-2A反复刷就可以重现. 因为出击回港频率比较高. 所以难道并不是内存泄露而是debuggability.js占用的内存太多了吗..?

不知道信息显示错误是不是跟这个有关. 因为开始进swap之后就会有很大的延迟然后动作快一些就可能出错. 目前为止我还没能第二次重现上面截图的错误... 抱歉... 一直重复出现的error我贴在了 pastebin http://pastebin.com/mFnLr2FK

**Comment by dkwingsmt** [comment]
你既然用的是 git 版本，最新版本有 `npm i` 过吗？

**Comment by FXuZ** [comment]
嗯测试前我把`node_modules`里面全清空重新 `npm i` 了

**Comment by dkwingsmt** [comment]
@FXuZ 你贴的这一堆看起来都是 kcwiki report 插件的，这个插件正好我也没安所以没测。试试把这个插件删了。

**Comment by FXuZ** [comment]
@dkwingsmt 看来应该是 kcwiki 插件的问题, 看来这个issue可以close了... 多谢...

**Comment by KochiyaOcean** [comment]
建议去 kcwiki 那边发个 issue 看看

**Comment by grzhan** [comment]
应该是这边插件和上游poi对接有问题，稍后会修复。

**Comment by FXuZ** [comment]
kcwiki的人已经来了我还要过去发issue吗...
