### ISSUE TITLE
win10更新后桌面的的快键方式无法使用

### ISSUE THREAD

**Issue by GX-9900-DV** [poooi/poi#1120]
昨天把电脑更新了然后装了7.0.0BETA1后，只要把图标拉倒桌面就会提示计算机丢失 node.dll和ffmpeg.dll
![v dt4pv no _12_1 sem](https://cloud.githubusercontent.com/assets/20826824/17385977/308671ba-5a21-11e6-9dc8-70b03f3e70df.png)
![ktny336_ n5a b0wvp q nh](https://cloud.githubusercontent.com/assets/20826824/17385980/3644f14e-5a21-11e6-8eae-0f59d43103ec.png)

**Comment by KochiyaOcean** [comment]
@GX-9900-DV 这… 确定不是 exe 而是快捷方式？
