### ISSUE TITLE
7.0.0-beta1 索敌值偏高

### ISSUE THREAD

**Issue by EdiTurn** [poooi/poi#1123]
6.3.3：
![screenshot_20160805-082536](https://cloud.githubusercontent.com/assets/5492805/17422786/a8196a2c-5ae7-11e6-8a45-88c62c82fcf5.png)

7.0.0-beta 1
![-2](https://cloud.githubusercontent.com/assets/5492805/17422789/af40013a-5ae7-11e6-978b-64d6ef81b128.png)

**Comment by KochiyaOcean** [comment]
还是麻烦检查一下是否已经修正 OTL
