### ISSUE TITLE
[7.0.0-beta.1] 任务进度没有更新

### ISSUE THREAD

**Issue by wafer-li** [poooi/poi#1124]
OSX 10.11.5
poi's version: 5fe9cc5036d93bf2f53601a89d6fe2c2c925c04f

第一次打开程序任务读取正常，随后更换任一正在执行的任务，bug 出现。

![image](https://cloud.githubusercontent.com/assets/12459199/17427083/d8a56f7a-5b18-11e6-89e8-b36ad43eea91.png)

![image](https://cloud.githubusercontent.com/assets/12459199/17427090/e5d13b16-5b18-11e6-9d49-cd3c6460ae04.png)

![image](https://cloud.githubusercontent.com/assets/12459199/17427102/f28b92ca-5b18-11e6-9868-e68f8080d808.png)

**Comment by dkwingsmt** [comment]
你的任务插件可能是3.0.0，3.0.0的任务插件需要7.0.0-beta.2（还未发布）的 poi 才能成功运行。你重启 poi 应该会看到这个插件有回滚标志，你先回滚到2.2.1

**Comment by wafer-li** [comment]
@dkwingsmt  

😂  原来概览面板的任务信息是插件提供的？

**Comment by dkwingsmt** [comment]
@wafer-li 任务要求的中文（和别的文）的翻译，是任务插件提供的。

**Comment by wafer-li** [comment]
@dkwingsmt 

重启之后并没有发现回滚标志。
尝试了进行删除后重装，概览功能已经正常，但是任务信息插件无法使用。

![image](https://cloud.githubusercontent.com/assets/12459199/17442810/9ba0af68-5b72-11e6-8b3f-47a8f2602b79.png)

**Comment by wafer-li** [comment]
@dkwingsmt 

With the latest commit, I manage to install the poi-plugin-quest-info **v2.2.1**

But it seems the roll back still not functioning.

**Comment by wafer-li** [comment]
目前应该没有插件需要 rollback 了。
