### ISSUE TITLE
POI打开后一直黑屏，无代理

### ISSUE THREAD

**Issue by GaloisGun** [poooi/poi#1125]
改host直连的 没有使用岛风go  [关闭重启，清缓存都试过了，求指导……

**Comment by herron9** [comment]
我跟你碰到一样的问题..好几天了也不知道怎么解决。一直黑屏完全无法读取数据

**Comment by KochiyaOcean** [comment]
*右击* 左下角的开发者工具按钮，切换到 network 标签看看有没有元素载入吧
没有的话基本可以确定是网络问题
![image](https://cloud.githubusercontent.com/assets/8194131/17486234/a9490cc6-5dc2-11e6-8ee3-8fd2ba0819d6.png)

**Comment by herron9** [comment]
看起来似乎是网络问题，但是在同一个网络内上周一直是正常使用的，从上周五开始突然不可用


________________________________

**Comment by oufumihiko** [comment]
＋1 同样问题，ss链接，黑屏
