### ISSUE TITLE
poi登陆进去会黑屏

### ISSUE THREAD

**Issue by yuesui** [poooi/poi#1126]
Failed to load resource: net::ERR_TUNNEL_CONNECTION_FAILED
https://fonts.googleapis.com/css?family=Roboto:300,400,500,700 

仅仅只是网络的问题吗？
能不能手动改成本地的css文件？

**Comment by KochiyaOcean** [comment]
@yuesui 这个文件和是否黑屏毛线关系也没有
建议检查网络连接是否有效，你神 Go 这两天似乎运营爆破了

**Comment by yuesui** [comment]
@KochiyaOcean  感谢·
