### ISSUE TITLE
有关反潜

### ISSUE THREAD

**Issue by KenLiu2** [poooi/poi#1127]
就是个很单纯的建议...
poi的舰娘信息一直以来都没有反潜这项
随著开幕反潜的出现 有时候没办法很直观的看到并比较各舰娘的反潜值
所以长期待在1-5肝船的我就跳槽74eo了
回头来希望能增加这个栏目 毕竟poi的功能比较完善

另外还是很期待poi这边能加上舰娘跟装备图鉴功能

**Comment by KochiyaOcean** [comment]
ALREADY FIXED BY https://github.com/poooi/plugin-ship-info/commit/86fbdc7b36ac6ee2aa051ce6036f56665cec68f6
