### ISSUE TITLE
7.0.0-beta2 舰娘与装备数量更新滞后

### ISSUE THREAD

**Issue by EdiTurn** [poooi/poi#1128]
在战斗中捞到舰娘时，界面上的舰娘数量与装备数量不会实时更新，而要等到回港后才会。

**Comment by GX-9900-DV** [comment]
同问题，为何舰娘在通常状态下全都是显示在修理中呢？？

**Comment by JenningsWu** [comment]
@GX-9900-DV 显示修理中是 beta2 的 bug，换 beta3 吧

**Comment by GX-9900-DV** [comment]
@JenningsWu 昨晚才下beta2这就出3了？

**Comment by dkwingsmt** [comment]
@GX-9900-DV 你回复之前先去看一下 release 页面或者淘宝源下载页面呀。

**Comment by EdiTurn** [comment]
在 7.1.0-beta0 中此问题仍然存在。不知为何关闭 issue。

**Comment by dkwingsmt** [comment]
是没修，我先开一下吧。不过不一定什么时候修了，这个修起来非常麻烦

**Comment by KochiyaOcean** [comment]
现在会更新舰娘计数了，由于提供的信息只有舰娘 id 和名字所以没法更新详细信息和装备。
