### ISSUE TITLE
poi 黑屏报错

### ISSUE THREAD

**Issue by whitecodes** [poooi/poi#1129]
debug 结果
```
[DEBUG] Debug Mode
[DEBUG] Config loaded from: , C:\Users\white\AppData\Roaming\poi\config.cson
[DEBUG] Debugging Flash Loader
[DEBUG] Loading Pepper Flash Player:
D:\poi\resources\PepperFlash\win-x64\pepflashplayer.dll
[DEBUG] Pepper Flash Player version: 21.0.0.242
[INFO] Proxy listening on 1511
[DEBUG] Registering shortcut: Ctrl+Shift+I      => Open Focused Window Dev Tools
```

![sp160808_234140](https://cloud.githubusercontent.com/assets/8749745/17486913/46623f62-5dc5-11e6-9a6d-defe1f2f7610.png)

系统环境：win7 SP1 64位
POI：v7.0.0-beta.1(v7.0.0-beta.2 同样的问题)
```
proxy:
  use: "socks5"
  socks5:
    host: "127.0.0.1"
    port: "1080"
```

**Comment by KochiyaOcean** [comment]
确定依赖是最新版本么

**Comment by whitecodes** [comment]
@KochiyaOcean win 需要什么依赖？

**Comment by KochiyaOcean** [comment]
不是 git 版么

**Comment by whitecodes** [comment]
@KochiyaOcean 不是，淘宝 npm 上的 poi-7.0.0-beta.2-win-x64.7z

**Comment by whitecodes** [comment]
update 删除(重命名) C:\Users\XXX\AppData\Roaming\ 下 poi 文件夹后，正常

**Comment by dkwingsmt** [comment]
3a5a265cb63bac2d442cd45d4d7896861adbd683 尝试修复了你遇到的这个问题。大概是 localStorage 的迷之问题。不过总之既然你已经删除了 localStorage 然后正常了，嗯……总之感谢。
