### ISSUE TITLE
在fedora上似乎存在内存泄露？

### ISSUE THREAD

**Issue by DC1937** [poooi/poi#1130]
大概就是运行半天左右，然后航海日志、舰娘信息、装备信息这三个插件占了7G内存？

**Comment by KochiyaOcean** [comment]
分析过 heap 了，初步认为是 Chrome 的问题
我改天会去上游发 issue
现在的策略是在收到数据后进行 `global.gc()` 进行强制回收，请确认是否已经使用 beta.2 之后的版本
