### ISSUE TITLE
mac os 64 poi  6.3.3一直黑屏

### ISSUE THREAD

**Issue by shoukakuzyq** [poooi/poi#1132]
网页加载不出来，除了dmm的网页也加载不出来，开发者工具显示有错误

![Uploading 屏幕快照 2016-08-10 下午11.59.55.png…]()

**Comment by KochiyaOcean** [comment]
[Uploading 屏幕快照 2016-08-10 下午11.59.55.png…]()
上传图片的时候不要心急，上传完成后再点发布……

**Comment by shoukakuzyq** [comment]
Something went really wrong, and we can’t process that file. 出现这个应该怎么办

**Comment by KochiyaOcean** [comment]
大概是因为你网络状态不是很好吧

**Comment by ruiii** [comment]
@shoukakuzyq 建议还是把发图上来

**Comment by shoukakuzyq** [comment]
好的，我换流量试试

**Comment by shoukakuzyq** [comment]
@KochiyaOcean 我发邮件截屏在你的邮箱里面了，希望你可以帮我上传一下图片，谢谢

**Comment by KochiyaOcean** [comment]
@shoukakuzyq 截图里的报错并非是网络故障的原因而是结果……换句话说你网络设置出问题啦

**Comment by shoukakuzyq** [comment]
我是用的改host，是哪里设置错了

**Comment by KochiyaOcean** [comment]
@shoukakuzyq 你 ping 一下 hosts 的地址看看是不是 hosts 崩了，以及代理设置里看看设置成了什么

**Comment by shoukakuzyq** [comment]
代理是不使用代理，如果不用poi直接用浏览器是可以上dmm玩的

**Comment by KochiyaOcean** [comment]
话说回来这是整个程度都无法连接网络啊……建议检查一下防火墙什么的

**Comment by shoukakuzyq** [comment]
hosts     106.186.27.62 www.dmm.com

**Comment by shoukakuzyq** [comment]
我已经把系统防火墙关了

**Comment by shoukakuzyq** [comment]
如果我买岛风go可不可以恢复

**Comment by KochiyaOcean** [comment]
@shoukakuzyq 应该不是 hosts 本身的问题而是整个程序没有任何网络连接

**Comment by shoukakuzyq** [comment]
是的，感觉hosts没出问题，是什么倒置程序没有网络，7月处还可以玩，后来因为有事没玩，八月初打开poi就加载不出网页，之后换了几个版本都不行，换了网络也不行

**Comment by KochiyaOcean** [comment]
@shoukakuzyq 看你有装 360 之类的，检查一下？

**Comment by shoukakuzyq** [comment]
360之前安过，后来卸载了

**Comment by shoukakuzyq** [comment]
@KochiyaOcean 防火墙设置：

  模式：	允许所有传入连接
  防火墙记录：	是
  秘密行动模式：	否
Wi-Fi：
  类型：	IEEE80211
  BSD 设备名称：	en0
  硬件 (MAC) 地址：	2c:f0:ee:1f:35:a8
  IPv4：
  配置方法：	DHCP
  IPv6：
  配置方法：	自动
  DNS：
  服务器地址：	8.8.8.8
  代理：
  HTTP 代理已启用：	否
  HTTPS 代理已启用：	否
  自动配置已启用：	0
  SOCKS 代理已启用：	否
  IEEE80211：
  JoinModeFallback：	DoNothing
  PowerEnabled：	1
  RememberJoinedNetworks：	1
  版本：	2200

**Comment by shoukakuzyq** [comment]
@KochiyaOcean 打扰你休息了，要不先休息明天再看，谢谢了

**Comment by shoukakuzyq** [comment]
@ruiii 为什么poi整个程序没有任何网络连接，安装的360已经卸载，系统的防火墙也允许poi进行数据交换

**Comment by KochiyaOcean** [comment]
@shoukakuzyq 代理设置里的端口设置是什么

**Comment by shoukakuzyq** [comment]
不使用代理

**Comment by KochiyaOcean** [comment]
@shoukakuzyq 不使用代理也有端口设置的

**Comment by shoukakuzyq** [comment]
端口设置这个在哪看 @KochiyaOcean

**Comment by KochiyaOcean** [comment]
@shoukakuzyq 同样在代理设置啊看截图

**Comment by shoukakuzyq** [comment]
我换了7.0.0beat2
![2016-08-12 2 49 11](https://cloud.githubusercontent.com/assets/20951581/17613809/f5a69364-609b-11e6-8f7f-0d9ccda01735.png)

**Comment by shoukakuzyq** [comment]
![2016-08-12 2 49 11](https://cloud.githubusercontent.com/assets/20951581/17613856/6d5ad7d0-609c-11e6-8043-37e4660a2f63.png)

**Comment by shoukakuzyq** [comment]
![2016-08-12 3 00 13](https://cloud.githubusercontent.com/assets/20951581/17614376/c92b93e8-60a0-11e6-951d-545f34eab48f.jpg)

**Comment by shoukakuzyq** [comment]
@KochiyaOcean 这是截图

**Comment by KochiyaOcean** [comment]
@shoukakuzyq 说实话不是很清楚什么情况……如果网络和防火墙设置都正常的话

**Comment by shoukakuzyq** [comment]
好吧

**Comment by shoukakuzyq** [comment]
![2016-08-12 5 24 27](https://cloud.githubusercontent.com/assets/20951581/17616851/a4c1a61c-60b1-11e6-8263-3e43407b958a.png)
@KochiyaOcean 我更新了电脑版本和poi的版本现在poi是7.0.0beat2

**Comment by KochiyaOcean** [comment]
只是插件检查更新失败的报错而已，并没有更多有价值的信息……

**Comment by shoukakuzyq** [comment]
好的，那就等我在看看

**Comment by yukixz** [comment]
远古 poi
