### ISSUE TITLE
poi-7.0.0-beta.2-win-x64 舰队信息面板错误

### ISSUE THREAD

**Issue by marktheonlyone** [poooi/poi#1134]
无论是否在入渠，全员信息都显示在修理中
![image](https://cloud.githubusercontent.com/assets/20993038/17626283/a3ba30a4-607a-11e6-9f44-6caa158b2c49.png)

**Comment by dkwingsmt** [comment]
4eff52b6df0c668c2e7a6e863049fa9235fc0f49 已修复

**Comment by marktheonlyone** [comment]
请问我应该重新下载一遍么

**Comment by KochiyaOcean** [comment]
@marktheonlyone 等会会出新版本

**Comment by dkwingsmt** [comment]
很快就会发新版 beta.3

**Comment by marktheonlyone** [comment]
好的，谢谢了~
