### ISSUE TITLE
[bug]7.0.0-beta2所有船状态均为维修

### ISSUE THREAD

**Issue by tangpei506** [poooi/poi#1135]
下载的最新的7.0.0-beta2，玩了一次之后再打开，进入游戏后所有船均被标记为维修状态并呈灰色，但是补给状态依然能正常显示。系统win10，连接vpn直连和岛风狗都试过。

**Comment by ruiii** [comment]
@tangpei506 请更新 poi

**Comment by KochiyaOcean** [comment]
下载 beta.3

**Comment by tangpei506** [comment]
感谢，抱歉刚才没发现更新
