### ISSUE TITLE
mac ox 一直黑屏

### ISSUE THREAD

**Issue by Adrianchan9029** [poooi/poi#1136]
console:
Failed to load resource: net::ERR_EMPTY_RESPONSE

**Comment by KochiyaOcean** [comment]
只是普通的说了没法连上网络而已，并没有什么有价值的信息……

**Comment by Adrianchan9029** [comment]
需要screenshot 嗎?web版能用

**Comment by Adrianchan9029** [comment]
![screen shot 2016-08-14 at 5 00 07 pm](https://cloud.githubusercontent.com/assets/21001763/17647963/050a953e-6241-11e6-9d16-b4526a8f7f5c.png)

**Comment by Adrianchan9029** [comment]
new reply

2016-08-13 12:16 GMT+08:00 東風谷オーシャン <notifications@github.com>:

**Comment by KochiyaOcean** [comment]
检查下代理设置和网络设置有没有问题吧
还有就是注意到系统版本也比较旧不知道有没有这方面的问题（只是怀疑
