### ISSUE TITLE
7.0.0 beta3 win10周年版补丁 黑屏（已解决，留作记录给其他朋友做参考）

### ISSUE THREAD

**Issue by cion1840** [poooi/poi#1137]
没开VPN什么的，程序内设置点不了，切换插件什么的无效，开始菜单右侧小图标右键退出那个菜单闪没无法选择

**Comment by cion1840** [comment]
回滚到未打周年补丁后依然黑屏

**Comment by cion1840** [comment]
已解决，删除appdata\roaming下的POI目录再启动POI就好了，应该是什么插件不兼容的问题

**Comment by KagamiChan** [comment]
估计是插件兼容性问题，下次先删除插件目录吧，删了 poi 文件夹相当于数据记录全都没有了
