### ISSUE TITLE
v7.0.0的版本 防猫功能失效

### ISSUE THREAD

**Issue by linzhibinghan** [poooi/poi#1139]
![qq 20160814053337](https://cloud.githubusercontent.com/assets/12961467/17645743/cec3c140-61e0-11e6-8ee7-30317f52b9a2.png)
![qq 20160814053315](https://cloud.githubusercontent.com/assets/12961467/17645745/d2b98118-61e0-11e6-87c7-0409c8a1d0d9.png)

刚更新的新版本,结果发现网络超时,就在那里一直不动,直到过很久自动猫.

这个截图是我先开ss进入游戏,然后关闭ss(断网),再游戏里面点按钮,之后显示的状态,之后我再开ss也并没有触发断线重连,如果正常触发,和以前一样,应该会显示正在尝试重新连接,网络正常就会续连的.

我使用的版本是poi win64的版本,然后是下载之后直接覆盖之前的.

之前的6.3的版本防猫功能依旧正常.
![qq 20160814055002](https://cloud.githubusercontent.com/assets/12961467/17645825/160bf868-61e3-11e6-9bfa-836db7bc6e77.png)

**Comment by JenningsWu** [comment]
@linzhibinghan 应该是昨天刚刚修复了。新版本还没发的样子
