### ISSUE TITLE
和七四式的对比

### ISSUE THREAD

**Issue by zhailingzy** [poooi/poi#1140]
一直在用七四式，今天查掉落的时候看到poi，下载来用了下。
优点就不多说了，说下觉得不如七四式顺手的地方。
1.七四式的dock模式可以方便修改各面板大小位置，有些不常用的可以缩小或关掉。<---很重要……比如我觉得主界面太大了……不但显示上有锯齿而且把可以用来做别的事的空间全部占用……
2.七四式可以看到各舰修理时间，poi没找到……可能是不太会找？
3.七四式的舰娘列表可选的过滤条件更多。例如可以只显示某个锁船标签。当然这个是插件的锅，不能怪poi。
4.明石修理的时候七四式能计算修了多久……虽然不是很准……

最喜欢的插件大概是语音字幕……七四式开发是日本人完全没这个需求……所以用不上……

**Comment by yukixz** [comment]
@zhailingzy 2 舰娘信息
3 请更新
4 @Ayaphis

**Comment by KochiyaOcean** [comment]
1、你干脆直接叫我重写得嘞……
2、 6.3.3 以前的版本可以直接把鼠标悬浮在血量条上，不过 7.0.0 这个功能暂时没用（有 bug

**Comment by zhailingzy** [comment]
@yukixz 
我昨天才知道poi……难道会有版本问题？我试了插件能显示锁船标签，但是无法过滤只显示带标签的船。
74主要是舰娘信息可以自定义过滤条件，需要一定的逻辑（and or）知识，但是很好用，poi那个插件的过滤条件定死了……
@KochiyaOcean 
我只是觉得dock模式挺好……不知道poi的界面能不能把主界面缩小点……我没说要改dock啊……

**Comment by KochiyaOcean** [comment]
显示设置里有一个缩放可以调，如果不嫌弃字体太小的话

**Comment by zhailingzy** [comment]
@KochiyaOcean 
试了一下放大果然好很多……
ps我指的是flash的部分太大……你肯定理解错了……

**Comment by ruiii** [comment]
@zhailingzy flash 在设置里也可以调

**Comment by zhailingzy** [comment]
@ruiii 
谢，看到了原来叫游戏分辨率
