### ISSUE TITLE
7.0.0 BETA-3插件航海日誌篩選的功能是不是壞掉了

### ISSUE THREAD

**Issue by SenbaMichiyo** [poooi/poi#1141]
前個版本還能用，是我的出了問題還是插件出了問題
http://i593.photobucket.com/albums/tt17/anderstse34/GGAG_zpsbmhd2bdr.jpg

**Comment by BeemoLin** [comment]
同樣情況 有紀錄但不能篩選

**Comment by JenningsWu** [comment]
@SenbaMichiyo @BeemoLin 更新航海日志，用 v5.0.2 或者 6.0.0-beta.1
