### ISSUE TITLE
poi 似乎没办法从 npm 更新或者下载插件

### ISSUE THREAD

**Issue by winooxx** [poooi/poi#1142]
在 Windows 和 OS X 点击查找更新后均未发现 poi 有连接产生，麻烦请跟进一下

**Comment by KochiyaOcean** [comment]
代理和镜像设置？

**Comment by winooxx** [comment]
代理正常，可以进入游戏，并且尝试过勾选使用代理连接 npm 服务，无效。四个镜像源也都尝试过，也无法建立连接。

**Comment by KochiyaOcean** [comment]
从本机直接 ping 过去呢，以及开发者工具报错？

**Comment by winooxx** [comment]
刚试了一下，四个镜像源均可 ping 通。console 报错，提示 SyntaxError: Unexpected token < in JSON at position 0 （路径为 \resources\app.asar\views\services\plugin-manager.js）

**Comment by KochiyaOcean** [comment]
本体版本？

**Comment by winooxx** [comment]
你是指的 poi 版本号吗？poi 6.3.3 和 7.0.0 beta 均发现问题

**Comment by KochiyaOcean** [comment]
@winooxx 最新版 beta.3 呢

**Comment by winooxx** [comment]
嗯，现在在用的 beta.3 有同样问题， 需要我把 console 报错信息完整贴出来吗？

**Comment by KochiyaOcean** [comment]
贴一下吧
（顺便直接访问 https://www.npmjs.com/package/poi-plugin-prophet 的结果？

**Comment by winooxx** [comment]
通过浏览器访问 npmjs 正常，log 已经贴上（
[-1471173595338.txt](https://github.com/poooi/poi/files/416999/-1471173595338.txt)

**Comment by winooxx** [comment]
唔，不知道你们有没有留意到，我从 github 上把插件拖回来扔进 poi 里头安装他会立马报错，但实际上查看 poi 的 plugin 目录发现插件已经放进去了，重启 poi 后发现插件可正常工作。开发者工具里头没有任何错误提示，版本为 7.0.0-beta.5 ，平台为 OS X El Capitan 10.11.6 / Windows 10 Redstone 1

**Comment by dkwingsmt** [comment]
@winooxx 呃，插一句，正确的安装 github 版插件的方式是：
1. 在任意地点 git clone repo
2. 在 repo 内 npm i 然后 npm link
3. 在 poi 的 plugin/node_modules 内 npm link <插件 packageName>

**Comment by winooxx** [comment]
噢原来如此，这个我知道了，然而那个 plugin 没法更新或者下载的问题是 known issue 还是我这边是个例？

**Comment by dkwingsmt** [comment]
@winooxx 老实说比较个例…… 不过你前面的帖子我也没看【

**Comment by respire** [comment]
v7.0.0 所有源均无法安装与更新。系统是OS X EI Capitan 10.11.1
直接访问正常。
建议提供打开插件管理详尽LOG的功能，以便查错。
另外有没有办法直接通过命令行更新？

**Comment by ruiii** [comment]
@respire 请提供报错的截图或是文字信息

**Comment by respire** [comment]
@ruiii 没有报错。是无限转圈，过了一段时间后圈圈消失，但是并没有更新成功，新版本提示图标依然存在。开发者工具下也没有错误Log。

**Comment by ruiii** [comment]
@respire 在设置里更换源 然后再试试？

**Comment by respire** [comment]
@ruiii 已经做出了所有尝试了。我四个源都试过，也试过走Proxy的那个选项与源之间的所有组合。然而还是无限转圈。在前两周刚安装poi的时候（记得好像是6.3左右，当时7.0还在beta）可以正常安装和更新插件。我也成功更新过好几次插件了。但是在活动开始后提示更新就再也没有成功过。现在活动打完了我才去重新处理这个问题。

**Comment by yukixz** [comment]
@respire 试试离线插件包

**Comment by respire** [comment]
@yukixz 我现在就是用离线插件包凑合。不过这个问题也不能不解决，毕竟挺不方便的。而且直接导入离线插件包(tar格式)的时候ui好像有点问题。虽然成功安装了，但是会提示安装失败，而且需要重新启动poi才能显示新安装的插件。

**Comment by respire** [comment]
我在命令行给npm设置全局proxy后问题解决。可以直接在ui里更新插件了。

**Comment by KochiyaOcean** [comment]
这和设置里选择代理安装插件一样的啊

**Comment by respire** [comment]
@KochiyaOcean 但是之前设置里选择后依然无法安装。

**Comment by KochiyaOcean** [comment]
@respire 设置以后重新开一下

**Comment by respire** [comment]
@KochiyaOcean 设置完重开没有试过。我先靠npm的全局proxy吧。给有类似issue的人一个work around.
