### ISSUE TITLE
卡画面，无法进入战斗

### ISSUE THREAD

**Issue by csjtc** [poooi/poi#1144]
进点就蓝屏，无法进入战斗画面，战斗开始四个字出不来，用kcv或者直接上dmm网页却可以， 顺便用的是岛风go，之前六月份不会这样的，一段时间没玩就变成这样了，换了挺多版本的poi,插件全关 还是没解决

**Comment by KochiyaOcean** [comment]
@csjtc 清理缓存

**Comment by csjtc** [comment]
缓存和cookie删了好几次了， 还是不行呐

**Comment by Sakuryou** [comment]
我也是这样，出击不能战斗，演习也不能进入战斗。换过各种版本的POI还有几个代理。缓存全删

**Comment by KochiyaOcean** [comment]
设置里的清理缓存，第三方缓存文件夹里的清理缓存，岛风 Go 的缓存校检都要做……
按照问题的描述，或者是缓存有问题，或者是网络太渣下载不了缓存文件，只能是这两种情况了

**Comment by csjtc** [comment]
海域战斗一片蓝，演戏今天也点进去看了，一进演戏马上猫，是不是我poi的哪个设置出问题了，直接用dmm网页是可以玩的

**Comment by KochiyaOcean** [comment]
瞬间猫的话，缓存文件过期的可能性非常大。
校检岛风 Go 的缓存，（如果 poi 自定义缓存文件夹里有文件）删除自定义缓存，然后在设置里清除缓存

**Comment by csjtc** [comment]
把cache里面的东西删了就可以用了- -，感激不尽，没有poi玩的好不习惯

**Comment by Sakuryou** [comment]
刚才迷之原因好了，时间就是办法
