### ISSUE TITLE
poi显示内存崩溃

### ISSUE THREAD

**Issue by lzl32947** [poooi/poi#1145]
[http://imgsrc.baidu.com/forum/w%3D580/sign=015779e20b3b5bb5bed720f606d2d523/d6f7f24543a98226e69f536e8282b9014b90ebd4.jpg](url)
这是结果图...
poi在连续运行大约四个小时后，在某次出击中电脑直接蓝屏（我才不会说是E4甲级斩杀boss点呢....T_T），图片在上面的url里（github没图片选项？）在点击“夜战”选项后大约6s后系统崩溃，不知是否为poi的问题，特此提交bug，感谢。
如果图片无法显示，可以访问以下网址[http://tieba.baidu.com/p/4726735907?pn=3](url)，在第72楼放了图片。

**Comment by KochiyaOcean** [comment]
使用的版本？

**Comment by lzl32947** [comment]
poi6.3.3 ，因为不知道是不是poi浏览器的问题，麻烦您了。

**Comment by lzl32947** [comment]
poi6.3.3 ，因为不知道是不是poi浏览器的问题，麻烦您了。

**Comment by lzl32947** [comment]
windows7，如果不是poi的问题，很抱歉给您添麻烦了，十分感谢。

**Comment by KochiyaOcean** [comment]
参照 https://msdn.microsoft.com/zh-cn/library/windows/hardware/ff559023(v=vs.85).aspx
虽然不能完全排除 poi 的上游 (electron, flash) 的嫌疑，不过可能性相对还是比较小的
