### ISSUE TITLE
POI7.0.0 beta3版一直黑屏。。

### ISSUE THREAD

**Issue by AURORA233** [poooi/poi#1147]
![kgay34769c45 450zn udr](https://cloud.githubusercontent.com/assets/21049177/17685496/198e0cdc-6397-11e6-952d-f312b7037fd4.png)    求解，完全不知道为什么--，昨天都是好的。。

**Comment by ruiii** [comment]
@AURORA233 麻烦把错误左边的三角点开 再截一次图

**Comment by AURORA233** [comment]
![image](https://cloud.githubusercontent.com/assets/21049177/17685608/22077c30-6398-11e6-97f9-0d260809d0ed.png)
这个？

**Comment by KochiyaOcean** [comment]
![image](https://cloud.githubusercontent.com/assets/8194131/17685615/33f12504-6398-11e6-80ff-84575a12dd3e.png)

**Comment by AURORA233** [comment]
![image](https://cloud.githubusercontent.com/assets/21049177/17685621/45b8aaaa-6398-11e6-90cc-c4ed56bca02d.png)
好吧。

**Comment by AURORA233** [comment]
==为啥关闭问题了，，，

**Comment by KochiyaOcean** [comment]
因为修复了啊……

**Comment by AURORA233** [comment]
但是我这里还是黑屏的耶==

**Comment by KochiyaOcean** [comment]
等下个版本……

**Comment by AURORA233** [comment]
我哪里设置错了么--

**Comment by KochiyaOcean** [comment]
可能是因为某种比较特殊的装备配置引起的
临时解决措施是进入 `%appdata%/poi` 删除里面的 `Local Storage` 文件夹

**Comment by AURORA233** [comment]
好的，我试试--
