### ISSUE TITLE
Surface上信息界面无法触屏操控

### ISSUE THREAD

**Issue by LukeXuan** [poooi/poi#1151]
poi 版本 / The version of poi: poi v6.3.3

操作系统 / OS: Windows

插件名和版本 (如果这是一个关于插件的 issue) / Plugin name and version (If its a issue about plugin):

详细描述 (建议提供开发者工具的截图) / Details (A screenshot of dev tools would be better):

如题，游戏界面(flash)触摸屏没有问题，鼠标没有问题，触摸笔也没有问题。

无响应区域包括overview fleet plugins settings.

应该是poi版本无关bug，以前就有但是是偶发性的。

**Comment by KochiyaOcean** [comment]
更新到 `7.0.0-beta.5` 看看

**Comment by LukeXuan** [comment]
Solved.

但是这个版本有不确定的全界面变白bug...

**Comment by KochiyaOcean** [comment]
看看 beta.6 有没有安定一些吧，我是都没遇到啦……

**Comment by LukeXuan** [comment]
嗯。关键是白屏的时候没发打开开发者工具……

**Comment by nvidiaowner** [comment]
@KochiyaOcean beta5` beta6只修复了触屏失效的问题，但是没有修复触屏滑动失效的问题，需要滑动的界面和插件依旧会失灵

**Comment by KochiyaOcean** [comment]
@nvidiaowner 说到底这只是一个 workaround 罢了，需要收集更多信息然后报告 Chromium 那边才行
