### ISSUE TITLE
Poi 黑屏

### ISSUE THREAD

**Issue by wafer-li** [poooi/poi#1154]
**poi 版本 / The version of poi:**
At this commit: 4fc3405fcc13eb06a4dae5ff22ee50cfe50a8554

**操作系统 / OS:**
Win 10 x64

**详细描述 (建议提供开发者工具的截图) / Details (A screenshot of dev tools would be better):**

![image](https://cloud.githubusercontent.com/assets/12459199/17737308/88cdcf3e-64c7-11e6-99d3-796e69ed3d18.png)

**Comment by KagamiChan** [comment]
flash player 库载入失败，我今天在 electron 1.3.2 版本也遇到过一次，后来换成 1.2.8 就好了 = =
可能重启也能好
