### ISSUE TITLE
艦隊的訊息錯誤

### ISSUE THREAD

**Issue by ff96710** [poooi/poi#1156]
**poi 版本 / poi version:**
7.0.0 beta 5
**操作系统 / OS:**
Windows 10
**插件名和版本 / Plugin name & version:**
_(如果这是一个关于插件的 issue / If its a issue about plugin)_

**详细描述 / Details:**
_(建议提供开发者工具的截图 / A screenshot of developer tools would be better)_
![image](https://cloud.githubusercontent.com/assets/21099015/17766662/c92ed63a-655e-11e6-8d7f-9b4f50648bdf.png)
多開POI 不同帳號的時候 艦隊的各種訊息經常出現錯誤 不管血量還是裝備 或者疲勞 都不會更新
圖片上 第一艦隊秘書艦是鬼怒 但是在POI上顯示的是北上

**Comment by KochiyaOcean** [comment]
点一下左下角的齿轮图标看看有没有报错信息？

**Comment by KochiyaOcean** [comment]
目前并不支持多开的说……

**Comment by ff96710** [comment]
但我之前用6.X的時候 用這種方法開都正常@@ 換成7.0.0才出現這問題

**Comment by KochiyaOcean** [comment]
代理设置里的端口设置如果为 0 的话理论上 poi 的不同实例之间不会有数据冲突
虽然如此由于所有 poi 实例共用相同的 cookie 所以有可能导致非常不妙的情况……所以还是不很建议多开

**Comment by ff96710** [comment]
而且錯誤情況的出現 不用多開就會發生 
只要先登入A帳號在換成B帳號
(不論是否有關閉POI 關閉再開 也會發生同樣錯誤)
前一個帳號 訊息被保存下來 切換帳號後 就會出現錯誤
目前解決辦法只有 登入要使用的帳號=>關閉POI =>重新開啟POI 之後這問題才會解決

**Comment by ff96710** [comment]
恩 是的 之前版本 兩個實例之間 數據並沒有衝突 但7.0.0開始衝突了

**Comment by KochiyaOcean** [comment]
大概是因为现在会读取上次保存的状态导致的
需要追加一个检查到不同账号登录时刷新 `store.info` 等项目的机制
cc @dkwingsmt

**Comment by dkwingsmt** [comment]
@KochiyaOcean 但为啥重开 poi 就可以了呢

**Comment by KochiyaOcean** [comment]
@ff96710 请问你的某个账号是不是没有开启全部舰队？

**Comment by ff96710** [comment]
兩個帳號都是全艦隊開啟

**Comment by KochiyaOcean** [comment]
总之 beta.6 大概是解决了？
