### ISSUE TITLE
声音开关在某种情况下会失效

### ISSUE THREAD

**Issue by KagamiChan** [poooi/poi#1157]
**poi 版本 / poi version:**
7.0.5b f427791edf161b6c16b26a543b512a15fbfcf4e9

**操作系统 / OS:**
windows 10
electron 1.2.8

**插件名和版本 / Plugin name & version:**
*(如果这是一个关于插件的 issue / If its a issue about plugin)*

**详细描述 / Details:**
*(建议提供开发者工具的截图 / A screenshot of developer tools would be better)*
某种情况下声音开关会失效，每次点击按钮会出现报错：
![image](https://cloud.githubusercontent.com/assets/3816900/17778116/9091f15e-6595-11e6-88de-c8529cf01d39.png)
```
C:\tools\electron\resources\electron.asar\renderer\api\remote.js:176 Uncaught Error: Could not call remote function ''. Check that the function signature is correct. Underlying error: Attempting to call a function in a renderer window that has been closed or released. Function provided here: Object.<anonymous> (D:\Projects\poi\views\components\etc\icon.es:50:8.
Error: Could not call remote function ''. Check that the function signature is correct. Underlying error: Attempting to call a function in a renderer window that has been closed or released. Function provided here: Object.<anonymous> (D:\Projects\poi\views\components\etc\icon.es:50:8.
    at callFunction (C:\tools\electron\resources\electron.asar\browser\rpc-server.js:225:11)
    at EventEmitter.<anonymous> (C:\tools\electron\resources\electron.asar\browser\rpc-server.js:306:5)
    at emitMany (events.js:127:13)
    at EventEmitter.emit (events.js:201:7)
    at EventEmitter.<anonymous> (C:\tools\electron\resources\electron.asar\browser\api\web-contents.js:165:13)
    at emitTwo (events.js:106:13)
    at EventEmitter.emit (events.js:191:7)
```

**Comment by dkwingsmt** [comment]
@KagamiChan 我也出现过这种情况，在开了很长时间后会出现，并且会伴随所有设置均无法使用。
我刚想到，可能是某个窗口被 gc ，导致对这个窗口调用的 event listener 出错，从而导致后面所有调用失败。
@KochiyaOcean

**Comment by KochiyaOcean** [comment]
Already fixed by #f427791

**Comment by KochiyaOcean** [comment]
在 f427791 依然有触发的话就不知道怎么处理啦，毕竟连 unload 都不叫一下实在是没法处理

**Comment by KagamiChan** [comment]
嗯，我先再试试，忘了有没有 pull 之后重启 poi ……

**Comment by KagamiChan** [comment]
问题在 8f50d0cda9b3da4747508640fdf371e596880562 版本仍然出现，不过这一次开发者工具里面没有任何显示了……只有`1876 console messages are not shown.`这个，应该和我中途关闭过开发者工具有没有关系

P.S. 我注意到这个是因为秘书通知的语音不能正常更改了

**Comment by KagamiChan** [comment]
过一会 pull 一下昨天和今天的更新再试试

**Comment by KagamiChan** [comment]
b2e3fc07fb7792631234e8de41bf5f3eff519932
仍然出现，而且开发者工具一片干净
![image](https://cloud.githubusercontent.com/assets/3816900/17827065/f0a9a658-66a9-11e6-8a59-fbcaa8a91d83.png)

**Comment by KochiyaOcean** [comment]
@KagamiChan 其他新窗口插件的开发者工具呢

**Comment by KagamiChan** [comment]
嗯，下次再遇到的时候打开看一下

**Comment by KagamiChan** [comment]
这几天没有能够再现，估计没问题了，先关了
