### ISSUE TITLE
POI無法開啟

### ISSUE THREAD

**Issue by eiriciii** [poooi/poi#1159]
**poi 版本 / poi version:6.33

**操作系统 / OS:winx64 旗艦

![14060371_1068118859967864_1185691092_o](https://cloud.githubusercontent.com/assets/21108054/17782514/6bcace2a-65a6-11e6-9dfe-425c7381907e.jpg)

不知道是甚麼原因 舊版的POI可以正常開啟 可是艦隊會有顯示上的問題
新版的POI開起來只有這種最小視窗模式可以用 
不知道問題是出在哪裡

**Comment by KochiyaOcean** [comment]
进入 `%appdata%/poi` 备份一下 `config.cson` 然后删除看看？

**Comment by eiriciii** [comment]
感謝解答 已經正常了 謝謝大大
