### ISSUE TITLE
觉得POI在“舰队“栏排版更紧凑一些会更好

### ISSUE THREAD

**Issue by zx35728** [poooi/poi#1160]
<a href="http://i4.buimg.com/4851/0fad34b2e0558ac1.png" title="点击显示原始图片"><img src="http://i4.buimg.com/4851/0fad34b2e0558ac1t.jpg"></a>
在“舰队”栏中，有很多未利用的空间，这些空间导致在版面中无法同时显示全部舰船。我觉得如果能把舰船等级和经验放在舰名和血条之间就会省下不少纵向空间，同时缩短舰船血条，能使界面更加紧凑。

**Comment by KochiyaOcean** [comment]
只有纵向非切分面板有这种情况，暂时没有为其专门进行调整的打算
如果觉得空间浪费比较严重不妨开启切分面板
