### ISSUE TITLE
flash下载重试次数应该设置一个上限

### ISSUE THREAD

**Issue by swordfeng** [poooi/poi#1161]
https://github.com/poooi/poi/blob/7172dc126aad7476c449216d3a8ca34f8a69a942/build_detail.coffee#L150-L160
这里会无限重试……希望能加上重试次数的限制

**Comment by dkwingsmt** [comment]
呃，既然是在 build 那么下载不下来也就无法继续了，无法继续的话，不如自己按 Ctrl-C ？

**Comment by KochiyaOcean** [comment]
@swordfeng 直接 ctrl+c 不就行了

**Comment by swordfeng** [comment]
@KochiyaOcean 昨天自动编译脚本据说这里卡了6h = =

**Comment by dkwingsmt** [comment]
是有点惨……心疼 ci 网……那加一个吧……
