### ISSUE TITLE
有時候點擊航海日誌和戰鬥詳情沒反應

### ISSUE THREAD

**Issue by FungJiHsu** [poooi/poi#1164]
**poi 版本 / poi version:**
7.0 B5
**操作系统 / OS:**
WIN7 64
**插件名和版本 / Plugin name & version:**
*(如果这是一个关于插件的 issue / If its a issue about plugin)*
日誌5.0.2 記錄3.0.9
**详细描述 / Details:**
*(建议提供开发者工具的截图 / A screenshot of developer tools would be better)*
![qq 20160820162828](https://cloud.githubusercontent.com/assets/14539399/17830048/68867aae-66f3-11e6-8f5d-12061abbe2c3.png)

**Comment by KochiyaOcean** [comment]
升到 beta.6 看看？

**Comment by FungJiHsu** [comment]
@KochiyaOcean 那我先試試B6
