### ISSUE TITLE
通知栏显示补给消耗

### ISSUE THREAD

**Issue by yukixz** [poooi/poi#1165]
现在通知栏会显示舰队补给的铝消耗。

建议：
1. 舰队补给时显示所有消耗（油弹铝）
2. 陆航补给时显示所有消耗

可选：
1. 显示陆航出击消耗

**Comment by yukixz** [comment]
陆航出击消耗相关报告：http://bbs.ngacn.cc/read.php?tid=9759958

**Comment by KochiyaOcean** [comment]
可以考虑用 toastr 感觉

**Comment by dkwingsmt** [comment]
@KochiyaOcean 如果这些用 toastr 那么补给耗铝就也用 toastr。如果这三者都是 toastr 你觉得可以的话（只是询问）

**Comment by dkwingsmt** [comment]
@yukixz 我感到的是耗资记录终于可以做陆航了……

**Comment by KochiyaOcean** [comment]
@dkwingsmt 我是觉得这类没必要常驻的信息可以丢 toastr 那边分担一下 alert 的压力

**Comment by dkwingsmt** [comment]
@KochiyaOcean toastr 容易让强迫症不得不关掉，太琐碎的消息移过去可能让人疯掉噢……

**Comment by dkwingsmt** [comment]
@KochiyaOcean 以及补给有个问题是补给按钮在右下吧（

**Comment by KochiyaOcean** [comment]
@dkwingsmt 可以减少显示时间，虽然默认是 5s

**Comment by dkwingsmt** [comment]
@KochiyaOcean 先试试吧。toastr 随便点一下就能 dismiss 问题也不大

**Comment by KagamiChan** [comment]
可不可以采用这样的方式：在资源数有变动的时候，在资源栏处临时显示变动量，比如这样的效果：
![image](https://cloud.githubusercontent.com/assets/3816900/17833182/825f28f4-6748-11e6-8d4a-84de752a0bdd.png)
虽然这是向别的游戏学的

**Comment by wafer-li** [comment]
@KagamiChan 

这样的话是不是浮动的动画会更好看一点？难的话当我没说。

**Comment by KagamiChan** [comment]
突然想到，由于自然增长的存在，可能每次载入 port 也会有增量
所以上边说的条件是非自然增长的消耗和收入方面的增减才对……

思路是这样，如果这样的方案可以的话，看怎么表示比较方便吧 = =
