### ISSUE TITLE
经验计算器显示效果糟糕

### ISSUE THREAD

**Issue by LukeXuan** [poooi/poi#1169]
**poi 版本 / poi version:**
v7.0.0-beta6
**操作系统 / OS:**
Mac OS
**插件名和版本 / Plugin name & version:**
*(如果这是一个关于插件的 issue / If its a issue about plugin)*
Exp Calculator
**详细描述 / Details:**
*(建议提供开发者工具的截图 / A screenshot of developer tools would be better)*
![image](https://cloud.githubusercontent.com/assets/3363954/17842942/a9965b96-685a-11e6-94f2-f938fb968743.png)

`<select>`和`<input>`是否加点 margin 或者 padding 比较好……

**Comment by KochiyaOcean** [comment]
插件作者 @Chibaheit 天天沉迷千年战争 Aigis 不更新插件必须谴责一下了

**Comment by LukeXuan** [comment]
[滑稽]

我什么时候学会了cjsx也来凑热闹开发了［flag

**Comment by Chibaheit** [comment]
fixed
