### ISSUE TITLE
RMP安裝包中似乎沒有寫libXss的依賴關係，順帶一提poi連個圖標都沒有嗎？

### ISSUE THREAD

**Issue by sjx95** [poooi/poi#1172]
**poi 版本 / poi version:** 6.3.3

**操作系统 / OS:** Fedora 24

**详细描述 / Details:**
*(建议提供开发者工具的截图 / A screenshot of developer tools would be better)*

安裝完畢後發現poi無法啓動，使用命令行啓動時發現缺少libXss的依賴，手動安裝後解決。
另外，在應用程序列表裏面，poi只有一個菱形的應用程序符號，連個圖標都沒有。。

**Comment by KochiyaOcean** [comment]
现在的打包是通过 https://github.com/electron-userland/electron-builder/ 自动执行的， 如果有问题可以去那里提交 issue
图标至少在 Windows 和 macOS 上是正常的……

**Comment by sjx95** [comment]
thx，圖標剛安裝RPM包時確實時沒有的，用了一會後莫名其妙的就出現了（也有可能是裝了poi的插件

**Comment by KagamiChan** [comment]
可能是没有更新图标的缓存？
