### ISSUE TITLE
Exp calculator 

### ISSUE THREAD

**Issue by TouhouYao** [poooi/poi#1173]
**poi 版本 / poi version:**
poi-7.0.1-win-x64

**操作系统 / OS:**
windows10

**插件名和版本 / Plugin name & version:**
*(如果这是一个关于插件的 issue / If its a issue about plugin)*
Exp calculator  ver.3.0.0

**详细描述 / Details:**
miscalculation

*(建议提供开发者工具的截图 / A screenshot of developer tools would be better)*
![1](https://cloud.githubusercontent.com/assets/21211012/17916989/b07296be-69ea-11e6-97fb-35f1d28d5b1f.png)

**Comment by KochiyaOcean** [comment]
@Chibaheit 做个 `Math.round` 罢

**Comment by KagamiChan** [comment]
启动时：
`D:\Projects\poi\node_modules\fbjs\lib\warning.js:36 Warning: Each child in an array or iterator should have a unique "key" prop. Check the render method of `PoiPluginExpCalc`. See https://fb.me/react-warning-keys for more information`

换船时：
`index.es:134 Uncaught ReferenceError: remodelLvs is not defined`

**Comment by Chibaheit** [comment]
fixed
