### ISSUE TITLE
一直显示poi等待游戏数据中是什么情况 chrome可以用

### ISSUE THREAD

**Issue by dowey** [poooi/poi#1174]
**poi 版本 / poi version:**

**操作系统 / OS:**

**插件名和版本 / Plugin name & version:**
_(如果这是一个关于插件的 issue / If its a issue about plugin)_

**详细描述 / Details:**
_(建议提供开发者工具的截图 / A screenshot of developer tools would be better)_

**Comment by KochiyaOcean** [comment]
@dowey 下面空着这么多就是让你填的……

**Comment by dowey** [comment]
7.0.1简直有毒 
回去下6.3.3就没问题

**Comment by KochiyaOcean** [comment]
@dowey 希望能提供一些比较有建设性的信息（比如代理设置、开发者工具截图等）

**Comment by wafer-li** [comment]
@dowey 
点击工具栏最左边的齿轮图标打开开发者工具，然后选择 `Console` 截个图贴上来。

**Comment by dowey** [comment]
代理设置没变啊 127.0.0.1 8099端口
6.33的console
![6 33](https://cloud.githubusercontent.com/assets/21232269/17955038/abae59f2-6ab1-11e6-9f04-ac2bc8e0746a.png)
7.01的
![7 1](https://cloud.githubusercontent.com/assets/21232269/17955042/b3f35c48-6ab1-11e6-855d-43127fde2ec2.png)

![qq 20160825105048](https://cloud.githubusercontent.com/assets/21232269/17955049/ce214076-6ab1-11e6-9c4c-1c278744b62f.png)

**Comment by KochiyaOcean** [comment]
资源管理器的地址栏内输入 `%appdata%/poi` 回车进入，删除 `Local Storage` 文件夹看看
