### ISSUE TITLE
请教问题，关于如何获取数据包

### ISSUE THREAD

**Issue by lhc-clover** [poooi/poi#1175]
想请教一下poi是如何抓取与dmm的http请求的？是在中间加了个代理还是修改了swf
这个过程有没有什么参考或通用的做法？

我已经在读poi的源码了，但是由于我不是web开发人员，对nodejs也不熟，如果得到回答的话会节省大量的时间。如果可能的话请帮忙附上相关源码的位置。

非常感谢

**Comment by dkwingsmt** [comment]
@lhc-clover 所有的和底层相关的都在 /lib 文件夹，和网络相关的在 /lib/proxy

**Comment by KochiyaOcean** [comment]
实现上就是架设一个本地代理然后抓包……
除去上级代理服务器啊缓存之类的功能实际上就是一个标准的 node http proxy 实现……

**Comment by lhc-clover** [comment]
@dkwingsmt @KochiyaOcean 非常感谢你们的回答～
