### ISSUE TITLE
最新版poi的幾個問題

### ISSUE THREAD

**Issue by cheunghim** [poooi/poi#1176]
**poi 版本 / 7.0.1

**操作系统 / OS: Windows 7

**插件名和版本 / 遠征資訊&任務信息&經驗值計算&戰果計算&海域血量

**详细描述 / Details:**
安裝時顯示安裝失敗，另外打開戰鬥記錄時一直顯示“Indexing battle from disk. Please wait...”

**Comment by KochiyaOcean** [comment]
显示失败的话试试看重新开启一遍

**Comment by cheunghim** [comment]
重新開啟插件還是瀏覽器？

**Comment by KochiyaOcean** [comment]
@cheunghim 浏览器

**Comment by cheunghim** [comment]
好

**Comment by cheunghim** [comment]
重啟之後安裝插件的問題解決了，但是戰鬥記錄還是顯示“Indexing battle from disk. Please wait...”

**Comment by KochiyaOcean** [comment]
cc @yukixz

**Comment by yukixz** [comment]
@cheunghim please wait
