### ISSUE TITLE
关于poi的计算制空值插件的建议

### ISSUE THREAD

**Issue by Margular** [poooi/poi#1177]
希望能出个能计算制空值的插件，如果作者没有时间，我也会写程序，愿意帮POI写个插件，希望作者提供API接口，写插件相关的资料

**Comment by KochiyaOcean** [comment]
@Margular 制空的话面板上已经有显示了啊…… 插件文档在 docs 文件夹下

**Comment by Margular** [comment]
不好意思，问题没描述清楚，已经新发问题了

**Comment by Ayaphis** [comment]
问题可以修改，补充的=。=那这边先关了
