### ISSUE TITLE
关于poi的根据制空值自动配飞机插件的建议

### ISSUE THREAD

**Issue by Margular** [poooi/poi#1178]
如题，比如知道330的制空值之后我带赤城+加贺+飞龙改二如何配置最佳的飞机，就像这个网站的功能一样：http://acc.rpman.net/

**Comment by Ayaphis** [comment]
https://github.com/poooi/plugin-aircraft-optimize

好像曾经有人开坑，然后因为老司机系统开发停滞了（x

**Comment by Margular** [comment]
为什么要开发停滞呢，老司机系统又不难，这个功能很实用，希望poi的攻城狮们能考虑一下

**Comment by ruiii** [comment]
@Chibaheit

**Comment by KochiyaOcean** [comment]
算法实现上是一个相当麻烦的贪心，现在坑太多而且在已经有实现的情况下优先度不会太高

**Comment by Margular** [comment]
好吧，我会一直关注poi的

**Comment by cnrpman** [comment]
老司机和改修主要涉及一系列ui等方面的外围调整
近期会着手做这件事

**Comment by wafer-li** [comment]
@KochiyaOcean 

我觉得这个完全可以交给那个网站去做。

就像签名生成插件一样，获取第一舰队，然后 POST

**Comment by KochiyaOcean** [comment]
@wafer-li 这个作者没提供接口啊……签名生成是有一个接口的所以没问题

**Comment by cnrpman** [comment]
天啊，网站脱坑已久
你们实现个现代版的吧(づ￣ 3￣)づ
