### ISSUE TITLE
輸入網址的地方一直讀取 無法輸入網址

### ISSUE THREAD

**Issue by ff96710** [poooi/poi#1179]
**poi 版本 / poi version:**
7.0.2
**操作系统 / OS:**
windows 10
**插件名和版本 / Plugin name & version:**
_(如果这是一个关于插件的 issue / If its a issue about plugin)_

**详细描述 / Details:**
_(建议提供开发者工具的截图 / A screenshot of developer tools would be better)_
![image](https://cloud.githubusercontent.com/assets/21099015/18009613/9cd876b8-6bdf-11e6-9558-9e72088e1a74.png)

右邊輸入網址的地方 從開啟後 常常一直保持著讀取圖示狀態 就算輸入新的網址也無法進入網頁
停止的功能也無效

**Comment by KochiyaOcean** [comment]
输入地址之前先点 x 把载入进程停掉……

**Comment by ff96710** [comment]
剛剛又在測試了一下 只要點到左邊網頁視窗裡面的東西 就會點x也無效了
而且必須一進去就點x 不然都會卡著 重新整理什麼都沒有用 必須重新開啟才能再去先點x

**Comment by ff96710** [comment]
![image](https://cloud.githubusercontent.com/assets/21099015/18153312/3ded3ae0-702f-11e6-8b27-94f53381ace3.png)

**Comment by yukixz** [comment]
不是很懂=。=

**Comment by gnattu** [comment]
This is cause by remote module crash in the earlier version of electron: https://github.com/electron/electron/issues/7351 , which should be fixed by https://github.com/electron/electron/pull/8110
