### ISSUE TITLE
遠征回歸，突然沒了聲音和氣泡提示（其他提示正常）

### ISSUE THREAD

**Issue by FungJiHsu** [poooi/poi#1180]
**poi 版本 / poi version:**
7.0.1
**操作系统 / OS:**
win7 64
**插件名和版本 / Plugin name & version:**
_(如果这是一个关于插件的 issue / If its a issue about plugin)_

**详细描述 / Details:**
_(建议提供开发者工具的截图 / A screenshot of developer tools would be better)_
![qq 20160827211033](https://cloud.githubusercontent.com/assets/14539399/18027603/12c450ca-6c9b-11e6-99d1-6641dece13f3.png)

**Comment by KochiyaOcean** [comment]
cc @yukixz

**Comment by KochiyaOcean** [comment]
错误信息能展开一下么

**Comment by FungJiHsu** [comment]
@KochiyaOcean 
展開也沒東西
![qq 20160827223757](https://cloud.githubusercontent.com/assets/14539399/18028073/fb938c0c-6ca6-11e6-9358-8fd4b933d640.png)

**Comment by FungJiHsu** [comment]
@KochiyaOcean 剛才又重現了...原因依然不明

![qq 20160831094558](https://cloud.githubusercontent.com/assets/14539399/18113141/078de208-6f60-11e6-8873-dfad3644a249.png)

**Comment by yukixz** [comment]
不是很懂

**Comment by FungJiHsu** [comment]
@KochiyaOcean 7.2b2都還是有這問題

![qq 20161110211827](https://cloud.githubusercontent.com/assets/14539399/20178316/8a506da6-a78b-11e6-9e2e-7e4114e1b372.png)

**Comment by KochiyaOcean** [comment]
插件版本？

**Comment by FungJiHsu** [comment]
@KochiyaOcean 秘書通知0.71

**Comment by KagamiChan** [comment]
请问，在 Console 里面输入
```
notify('test',{type:'expedition'})
```
是否也会同样报错？

输入
```
config.get('poi.notify.expedition')
```
的结果是什么？

**Comment by FungJiHsu** [comment]
@KagamiChan 
![qq 20161110214452](https://cloud.githubusercontent.com/assets/14539399/20179028/03da9d42-a78f-11e6-8d8a-1ed499d6b479.png)
![qq 20161110214505](https://cloud.githubusercontent.com/assets/14539399/20179029/049830d2-a78f-11e6-870f-fc46e0869100.png)

**Comment by KagamiChan** [comment]
@FungJiHsu 执行前一条能听到声音，并看到气泡提示吗？

**Comment by FungJiHsu** [comment]
@KagamiChan 現在有，剛剛那次沒有

**Comment by KagamiChan** [comment]
@FungJiHsu 于是现在在秘书通知插件里面点击 远征，能否听到声音？

**Comment by FungJiHsu** [comment]
@KagamiChan 可以

**Comment by KagamiChan** [comment]
@FungJiHsu 看起来设置是好的……poi 内部的通知也是调用 notify， 所以你手动执行没有问题的话，自动的通知也应怪是正常的

**Comment by FungJiHsu** [comment]
@KagamiChan 不是一直出問題，時好時壞的

**Comment by FungJiHsu** [comment]
@KagamiChan 再一次執行notify('test',{type:'expedition'})
有氣泡沒聲音
![qq 20161110220656](https://cloud.githubusercontent.com/assets/14539399/20179633/1fe1b892-a792-11e6-9d69-6b2ae8172e99.png)

**Comment by KagamiChan** [comment]
可以让我看看你 Network 标签页那边的截图吗

**Comment by FungJiHsu** [comment]
@KagamiChan 是不是要測試一下再截圖
現在空白的
![qq 20161110221418](https://cloud.githubusercontent.com/assets/14539399/20179897/247a070a-a793-11e6-96ec-7b195ba5191f.png)

**Comment by KagamiChan** [comment]
嗯，这个貌似是开了开发者工具才记录的……
换一下秘书舰娘，然后再执行几次`notify('test',{type:'expedition'})`，如果有错的话，再看看 `config.get('poi.notify.expedition')` 的结果，还有 Network 的记录吧

**Comment by FungJiHsu** [comment]
這幾次都正常，中途又有個遠征回來（正常）
![qq 20161110222457](https://cloud.githubusercontent.com/assets/14539399/20180223/8dc36908-a794-11e6-9be0-7efc8281b32c.png)

**Comment by KagamiChan** [comment]
嗯，这个是正常的表现，在换秘书舰的时候会先检测语音是否存在，才写入设置的
似乎得等出现再看了……

顺便问一下，你的别的插件是不是也更新到最新版本了？还有是使用什么方式连上游戏的（代理，加速方面的

**Comment by FungJiHsu** [comment]
所以我這陣子都要開著開發者工具記錄？

今天之前除了kcwiki的還沒更新之外，其他都是最新
網絡環境：廣東電信
代理：acgp

**Comment by FungJiHsu** [comment]
@KagamiChan 
剛又一個遠征有氣泡沒聲音，已記錄
![qq 20161110222457](https://cloud.githubusercontent.com/assets/14539399/20180606/1bc97c96-a796-11e6-9c96-9e0fa041006f.png)

**Comment by KagamiChan** [comment]
于是现在执行 `config.get('poi.notify.expedition')` 会显示什么？

**Comment by FungJiHsu** [comment]
@KagamiChan 沒聲音
![qq 20161110222457](https://cloud.githubusercontent.com/assets/14539399/20180808/ea3ccf4c-a796-11e6-8f43-60f41b759690.png)

**Comment by KagamiChan** [comment]
显示在 Console 里面的是什么？（执行命令的话是需要那里的结果），在 117882.mp3 上的这一项右键，copy link address，也粘贴一下？

**Comment by FungJiHsu** [comment]
@KagamiChan 
![qq 20161110222457](https://cloud.githubusercontent.com/assets/14539399/20181283/752f62ee-a798-11e6-80aa-53a965edd066.png)

兩個都是
http://125.6.189.71/kcs/sound/kcavfbkpphumso/117882.mp3
http://125.6.189.71/kcs/sound/kcavfbkpphumso/117882.mp3

**Comment by KagamiChan** [comment]
这些 url 看上去都是有效的，有点怀疑是播放的时候请求超时了……
总之先建议确保 acgp 缓存是最新的，如果有线路选择的话试试换换线路，然后清空 poi 的缓存再重新启动 poi 试试看……

**Comment by FungJiHsu** [comment]
@KagamiChan 

明天起床再弄=。=麻煩您了

**Comment by KagamiChan** [comment]
或者，也可以试试不使用本地缓存
（没用过 acgp，不清楚有什么功能 - -
