### ISSUE TITLE
7.0.2POI無法開啟

### ISSUE THREAD

**Issue by popda123** [poooi/poi#1181]
**poi 版本 / poi version:7.0.2

**操作系统 / OS:WIN10 64BIT

**插件名和版本 / Plugin name & version:**
*(如果这是一个关于插件的 issue / If its a issue about plugin)*

**详细描述 / Details:[開啟後一直處於白色畫面](http://upload.lsforum.net/users/public/p46514poie207.png)
*(建议提供开发者工具的截图 / A screenshot of developer tools would be better)*

**Comment by KochiyaOcean** [comment]
试试看 `ctrl + shift + i` 能否打开开发者工具？

**Comment by dkwingsmt** [comment]
@popda123 按 Ctrl-Shift-i 能弹出来 devtools 吗？可以的话切换到 console 选项卡看看有没有错误，然后截图发上来。

**Comment by popda123** [comment]
用了Ctrl-Shift-i後就開起來了 謝謝兩位的幫忙!! 另外[這是](http://upload.lsforum.net/users/public/t12578po01b207.png)我開起來後console中的東西

**Comment by KochiyaOcean** [comment]
其实你可以直接把图片粘进来不用图床的……
