### ISSUE TITLE
7.0.2的航海日志无法进行过滤

### ISSUE THREAD

**Issue by ccen3020** [poooi/poi#1182]
**poi 版本 / poi version:**
7.0.2
**操作系统 / OS:**
Microsoft Windows [版本 10.0.10586]
**插件名和版本 / Plugin name & version:**
_(如果这是一个关于插件的 issue / If its a issue about plugin)_
航海日志V5.0.1 战斗记录V2.6.5
**详细描述 / Details:**
_(建议提供开发者工具的截图 / A screenshot of developer tools would be better)_
航海日志中，筛选框功能失效。填入信息后按回车键无效
有的战斗信息不能保存
图传不上来，是否需要提供航海日志记录文件？
![image](https://cloud.githubusercontent.com/assets/5616211/18034575/15e0d002-6d73-11e6-9728-a05e715b950b.png)
![Uploading image.png…]()

**Comment by dkwingsmt** [comment]
@ccen3020 请在设置-扩展程序-高级设置中选择 检查 beta 版插件，然后点击检查更新，把航海日志更新到 6.0.0-beta 版

**Comment by ccen3020** [comment]
解决
