### ISSUE TITLE
戰果計算問題

### ISSUE THREAD

**Issue by gj1223** [poooi/poi#1185]
**poi 版本 / poi version:**7.0.2

**操作系统 / OS:**WIN7

**插件名和版本 / Plugin name & version:**戰果計算 4.0.1

**详细描述 / Details:**怎麼自己戰果不會自己計算= =一直都是 0--->XXXXXXXX(經驗數)
看第1,5,20,100,500名的經驗是XXX.XXXXXXXXX 
會有這麼多的小數位嗎= =

**Comment by ruiii** [comment]
@gj1223 昨天维护 娇喘改了 api 我还没空更新 晚点更

**Comment by ruiii** [comment]
@gj1223 另外因为娇喘更改 api 的原因 战果基础值是要自己设置的 左上角有个设置按钮

**Comment by gj1223** [comment]
感謝!!!晚點看看!!

**Comment by ruiii** [comment]
@gj1223 发了一个 beta 版
麻烦到设置的插件 tab 里高级设置勾上检查 beta 版更新
之后就可以下到了。。

**Comment by gj1223** [comment]
@ruiii 找到了~感謝你的更新喔:3`````

**Comment by magicae** [comment]
@gj1223 @ruiii 看起来解决了
