### ISSUE TITLE
如何正确打包插件

### ISSUE THREAD

**Issue by GaoSui** [poooi/poi#1186]
**poi 版本 / poi version: 7.0.2**

**操作系统 / OS: Windows 10 1607**

我在尝试开发插件但是始终不能让poi载入我的插件。
比如我下载了未卜先知的源码，压缩成tar.gz拖到poi上，就会出如下错误：
![image](https://cloud.githubusercontent.com/assets/16461362/18166621/b1ef8b10-707e-11e6-8ec4-2669c4bab297.png)
很明显操作姿势不对，请求作者们能指点一下开发过程中怎样让poi载入自己的插件，谢谢！

**Comment by KochiyaOcean** [comment]
@GaoSui 文档在 doc 下面

**Comment by yukixz** [comment]
@GaoSui https://github.com/poooi/poi/blob/master/docs/plugin-cn.md#插件安装包的发布

**Comment by GaoSui** [comment]
我读过文档了，用tar cvf [repo].tar.gz [repo] 打包还是不行，不知道哪做的不对。

**Comment by KochiyaOcean** [comment]
@GaoSui 请使用 `npm pack`……

**Comment by GaoSui** [comment]
啊。。谢谢，我试试

**Comment by yukixz** [comment]
@KochiyaOcean 你 poi 已然是文档无用的大型开源项目了

**Comment by GaoSui** [comment]
我发现不管是tar还是npm pack打包，直接拖入都是一样的报错，之后重启poi就正常载入了。
应该还不是tar的锅。。怎么搞才能不用重启呢

**Comment by GaoSui** [comment]
总之我找到办法不用重启了。。谢谢
希望能尽快更新插件文档，大概还有些错误，比如import store from 'views/createStore'返回的是undefined

**Comment by yukixz** [comment]
@GaoSui @DKWings

**Comment by GaoSui** [comment]
啊 好使 谢谢

**Comment by leeyc0** [comment]
@GaoSui 我遇到了相同問題，請問怎樣才能打 tar.gz 檔拉進 poi 又不用重啟？

**Comment by leeyc0** [comment]
我好像找到workaround了，似乎是安裝後禁用，再覆蓋代碼，最後啟用plugin……
不過這方法很蠢……

**Comment by dkwingsmt** [comment]
32e6ce90e20b1bbe7bd539f890c1be2118f86e4e 更新了插件文档。

另外 `views/createStore` 现在是 deprecated 状态，如果你们有做第三方插件的话建议尽早换成 `views/create-store`，如文档所示。如果文档里还有什么错误的地方也麻烦指出，感谢 @GaoSui

**Comment by dkwingsmt** [comment]
@leeyc0 能给一下插件安装错误的开发者工具截图吗？或者直接把你们的插件包发给我们也行，如果你不在意的话……

**Comment by leeyc0** [comment]
附上開發者工具的輸出
[1473809345552.txt](https://github.com/poooi/poi/files/470995/1473809345552.txt)

另外，插件可在此下載
https://www.sendspace.com/file/raf6b9

**Comment by leeyc0** [comment]
另外，docs/plugin-cn.md 好像把打 settingsClass 寫錯了成 settingClass……

**Comment by dkwingsmt** [comment]
@leeyc0 非常感谢，大概清楚原因了，是 poi 的问题。会修复

**Comment by GaoSui** [comment]
啊，有修复就好，谢谢
