### ISSUE TITLE
`updateTime` undefined 导致任务进度无法更新

### ISSUE THREAD

**Issue by wafer-li** [poooi/poi#1187]
**poi 版本 / poi version:**
At this commit: 11b9de8d2cf103d4369d13813cf37e9205edcb25

**操作系统 / OS:**
Win 10

**详细描述 / Details:**
*(建议提供开发者工具的截图 / A screenshot of developer tools would be better)*

任务进度无法及时更新，必须点进任务(quest)里面才能更新任务进度。

![image](https://cloud.githubusercontent.com/assets/12459199/18220586/95f5b994-71ae-11e6-9d9a-3d4777436fa4.png)

 console 错误过多，基本上每一个 response 都会出现这个错误，并不仅限于图中的 `api_start2`

**Comment by KochiyaOcean** [comment]
cc @dkwingsmt

**Comment by dkwingsmt** [comment]
卸载战果插件再重新安装（最新版 4.1.1）之后再看几天会不会有类似问题

**Comment by wafer-li** [comment]
应该是没问题了，2 天之内都未重现。
