### ISSUE TITLE
音效與介面問題

### ISSUE THREAD

**Issue by KuRoic** [poooi/poi#1188]
**poi 版本 / poi version:**7.0.2

**操作系统 / OS:**Windows10

**插件名和版本 / Plugin name & version:**瀏覽器
_(如果这是一个关于插件的 issue / If its a issue about plugin)_

**详细描述 / Details:**一直以來都使用介面版的"關閉遊戲聲音"更新後將介面版的"關閉遊戲聲音"給關閉後
發現遊戲還是沒有聲音 遊戲內的音效都是開啟的 還有開啟遊戲時 遊戲畫面要等一段時間後才會與介面切齊
_(建议提供开发者工具的截图 / A screenshot of developer tools would be better)_

**Comment by KochiyaOcean** [comment]
无法关闭声音是上游 bug，已经确认
等待时间大体上和你网页加载进度相关，这个是没办法的事……

**Comment by magicae** [comment]
如果是 Electron 的 bug 的话可以考虑参考这个 commit 的写法改一下。https://github.com/electron/electron/commit/8aa559fe51beff28bc47be9138b461bed2a06779

**Comment by KagamiChan** [comment]
7.3.0-beta.0 应该已经修复了无法关闭声音的问题
