### ISSUE TITLE
[不兼容性公告] 把工具函数从 window 移到 views/utils/tools

### ISSUE THREAD

**Issue by dkwingsmt** [poooi/poi#1191]
## 背景
- commit 1ec4c48728c06537df9277f1228e5a362fd40684 把原来放在 `views/env-parts/utils` 中的工具函数全部移到了 `views/utils/tools` 中，这其中包括了 `indexify`、`reduxSet`、`compareUpdate` 等 store 中常用的工具。
- commit 4fc3724dbee23ed13883eee8bb70e4526beadb20 把原来放在 `views/components/ship-parts/utils` 中的和游戏相关的工具函数移到了  `views/utils/game-utils` 中。
## 目的

这两个改动是为了收纳原来散落在代码各处的工具函数，使代码分布更加整洁。同时，将其位置从 `window` 变为 `import` 可以避免担心 env 代码执行顺序的问题。
## 要求

插件中如果有使用这部分函数的，在未来的某一个时刻应考虑改为使用 `import` 进行导入。
改动举例：

``` javascript
// Before
const { indexify, compareUpdate } = window
// Now
import { indexify, compareUpdate } from 'views/utils/tools'

// Before
import { equipIsAircraft, getStatusStyle } from 'views/components/ship-parts/utils'
// Now
 import { equipIsAircraft, getStatusStyle } from 'views/utils/game-utils'
```
## 兼容性

原来在 `views/env-parts/utils` 中的所有函数都仍然暂时保留了兼容性，即 `window` 中仍然保留了这些的入口。但 `window` 的入口应被当作 deprecated。

注意，由于该改动在下个版本（应该是 7.1.0）才会实装，所以更改了这部分的插件需要在 `apiVer` 字段表明 7.1.0 以后才可用。
为了 7.1.0 之前的用户可用，可以考虑在 7.1.0 正式版推出一个月以后再进行改动。

**Comment by KagamiChan** [comment]
我计划把 window 上挂着的类似的工具函数在下一个大版本之中去掉

**Comment by KagamiChan** [comment]
哇，这个都忘记移除了，下个版本之前移除好了
