### ISSUE TITLE
内存占用过高

### ISSUE THREAD

**Issue by wafer-li** [poooi/poi#1192]
**poi 版本 / poi version:**
f85302a04c9b8abb12ff42fd8253b0e5b407b63e

**操作系统 / OS:**
win 10

**详细描述 / Details:**
![image](https://cloud.githubusercontent.com/assets/12459199/18263147/a01a86d4-7442-11e6-8d3b-bc2750c229f0.png)

不是很明白为什么，我只开了 2 小时不到啊。。。 :joy:

**Comment by KochiyaOcean** [comment]
@wafer-li 似乎 Electron 1.3.5 又有内存泄漏问题了……先降到 1.3.4 吧

**Comment by dkwingsmt** [comment]
最新 commit 01f64e017363f6a56e5312a987eb18c0c2dc4d11 可能解决了这个问题，试试看

**Comment by wafer-li** [comment]
挂机 3 小时

![image](https://cloud.githubusercontent.com/assets/12459199/18379914/e1ae9a30-76af-11e6-8d2d-5846328d8165.png)

应该算是修复了。
