### ISSUE TITLE
Linux下的一个BUG

### ISSUE THREAD

**Issue by Margular** [poooi/poi#1194]
poi V7.0.2
linux/kali linux 2016.1 rolling
linux下刷新的话flash会变得啥也看不见，黑屏。但是能点，也有声音。只有关了poi再开才能变回正常。好蛋疼。4-3练级的时候不小心进了门神就刷新，结果黑屏，poi关掉再开，好繁琐。希望能解决这个bug

**Comment by yukixz** [comment]
上游问题
