### ISSUE TITLE
建议使用更好的措辞

### ISSUE THREAD

**Issue by wafer-li** [poooi/poi#1196]
**poi 版本 / poi version:**
f7588c9e0f5a94ab9ca31fce8bde8b492e1f7698

![image](https://cloud.githubusercontent.com/assets/12459199/18454713/e62b51d8-7980-11e6-88b4-ef555ef4c1f7.png)

这里改成 **取消** 比较好

因为 **关闭** 也可能指关闭游戏窗口（程序）

**Comment by magicae** [comment]
兹磁 @KochiyaOcean

**Comment by KochiyaOcean** [comment]
我记得不这么做的原因是只有一个按钮的 modal 也会显示取消
不过不是什么大不了的问题，有空去看看

**Comment by KochiyaOcean** [comment]
![image](https://cloud.githubusercontent.com/assets/8194131/18771830/a3df495a-8174-11e6-8d0d-a06095ff37b6.png)
比如这种场合也不好说是哪种措辞好
