### ISSUE TITLE
任务计数 /装备改修插件问题

### ISSUE THREAD

**Issue by yuan51** [poooi/poi#1197]
**poi 版本 / poi version: 7.02**

**操作系统 / OS: win10**

**插件名和版本 / Plugin name & version: 装备改修2.3.2**
_(如果这是一个关于插件的 issue / If its a issue about plugin)_

**详细描述 / Details: 装备改修打开以后一直黑的， 任务计数，比如周常这类的，第二天会重置归零**
_(建议提供开发者工具的截图 / A screenshot of developer tools would be better)_

**Comment by dkwingsmt** [comment]
@yuan51 装备改修你打开多久一直黑？另外任务计数下个版本会修复（下个版本应该就没问题了）

**Comment by yuan51** [comment]
装备改修是更新了新版本以后就用不了了，开了以后就一直黑。尝试了重装都不行

**Comment by KagamiChan** [comment]
经过了这么多个版本，应该可以关掉了
