### ISSUE TITLE
Window10通知导致整个工具卡顿

### ISSUE THREAD

**Issue by ilikecola** [poooi/poi#1198]
**poi 版本 / poi version:**
poi-7.0.2-win-x64

**操作系统 / OS:**
Windows10

**详细描述 / Details:**
打开以后过段时间整个程序死掉，点击没有任何反应，但是没有占用CPU或者任何内存。

**Comment by ilikecola** [comment]
这几天观察，运行时CPU占用在7%~25%之间，不知道是Flash的问题还是，具体参数无法观察。。。。

**Comment by KochiyaOcean** [comment]
报错都只是和网络相关，没有什么特别的地方

**Comment by ilikecola** [comment]
只会发生在用一心两用插件时，整个程序会卡顿，无法进行任何交互。

**Comment by ilikecola** [comment]
![qq 20160919220428](https://cloud.githubusercontent.com/assets/12741416/18634770/0cc8c486-7eb5-11e6-99e2-98249e0fbef2.png)
但是这占用也太高了吧///

**Comment by maomaohenmao** [comment]
同发生此问题，是占用太高导致的吗？ 我的笔记本电脑会出现此问题，台式机却从没出现过。在7.2.1版本同样出现。

**Comment by KochiyaOcean** [comment]
合计 1GB 内存左右的消耗没问题啊……
花骑士确实巨耗资源就是了……如果没有兼容性问题建议打开硬件加速

**Comment by ilikecola** [comment]
新版本似乎卡顿解决了，但是纯舰娘的CPU占用在10-15%，花骑士就不说了高峰50%都有。。。6700K表示带不动。。。。似乎还和电脑有关，换了一个低配的笔记本就不会那么高占用。。好神奇啊。。。

**Comment by KochiyaOcean** [comment]
@ilikecola Flash 这种程度的占用算正常的，如果有婚舰樱吹雪 + 其他一堆奇怪的家具特效之类的负担会更高……

**Comment by ilikecola** [comment]
但是采用基于WPF或者WinForm的Chromium组件以及同样的pepflashplayer.dll，系统占用却低于10%。。。

**Comment by KochiyaOcean** [comment]
@ilikecola Electron 毕竟不能算纯粹的 Chromium，详细的实现我也不是很清楚，只能说这种资源占用程度在 Electron 中算正常的……

**Comment by ilikecola** [comment]
好吧。。。看来只能算是ELectron架构的锅了。。。

**Comment by maomaohenmao** [comment]
近来在旅行，使用我的笔记本电脑登录依旧出现此问题（高配台式机从来没出现过此问题），不过用得多了看出一些端倪。每次该问题出现都是在弹出通知的时候（比如远征结束弹通知）。是不是通知插件的bug或者占用太高所致?

**Comment by KagamiChan** [comment]
@maomaohenmao 希望能够提供操作系统，poi 版本，以及笔记本电脑配置相关的一些信息
此外可以通过关闭弹出通知、在开发者工具中使用 `notify()` 来手动触发通知等方式进行更细致的确认

**Comment by KagamiChan** [comment]
@maomaohenmao 鉴于你的情况可能和这个 issue 的发起者不一样，你可以新开 issue ……

**Comment by maomaohenmao** [comment]
系统为win10 64位，poi版本7.2.1，笔记本电脑为2013年macbookair（对我就是双系统）,内存4G，CPU是I5。
关于手动触发通知，能提供一些括号内的信息吗，比方说远征结束通知或者建造结束通知，我自己瞎猜猜不到……都是undefined，谢谢

**Comment by KagamiChan** [comment]
@maomaohenmao 
`notify('Message', {type: 'TYPE'})`
TYPE 可以替换成 expedition, morale, construction 或者 repair
因为这个函数没有返回值，所以执行完毕之后打印 undefined，这是正常现象

**Comment by maomaohenmao** [comment]
嗯  测试过了，一般刚开的时候没事，但开得久一点之后，再弹出通知的时候就很容易发生卡顿，如果等待3-5分钟会自动恢复，个人猜测还是电脑内存比较小，开久了占用一高就卡死了

**Comment by KagamiChan** [comment]
@maomaohenmao 能确认和弹出通知直接相关吗？
不知道你有没有开着任务管理器查看过内存占用，如果的确是内存占用的话，可以暂停部分不常用插件试试——虽然我觉得 4G 内存应该是够用的

**Comment by KagamiChan** [comment]
@maomaohenmao 顺便最近出了一个测试版，可以试一下有没有改善

**Comment by maomaohenmao** [comment]
我认为就是和弹出通知直接有关，因为每次出现卡死都是弹出远征回港通知然后切屏收的时候会卡死。不过因为这情况从来没出现在我的高配台式机上，所以跟硬件配置也应该有关系。  好的我会试用一下！

**Comment by gnattu** [comment]
早期版本Win10的通知确实有导致卡死的现象，请问Creator Update后是否还有这种现象？
