### ISSUE TITLE
频繁出现错误201

### ISSUE THREAD

**Issue by GaoSui** [poooi/poi#1200]
**poi 版本 / poi version: 7.0.2**

**操作系统 / OS: win10**

**详细描述 / Details:**
*(建议提供开发者工具的截图 / A screenshot of developer tools would be better)*

本人在北美，不管是用日本的代理服务器还是设置cookie直连，都会出现201错误。感觉上大部分出错时都是几分钟没有操作，再出现http请求时就201了。请问201是个什么问题呢。

**Comment by KochiyaOcean** [comment]
太肝了，休息一下吧
