### ISSUE TITLE
About the quest information 任務信息

### ISSUE THREAD

**Issue by slui** [poooi/poi#1201]
poi version:
V7.0.2
 OS:
Windows 10 64bit
Plugin name & version:
Quest Info 任務信息 V3.01
 Details:This plug-in has not been update for at least 4 months . Therefore, i would like to know if someone else can help the project to keep running.

**Comment by KagamiChan** [comment]
The development has not ceased, in my opinion they just forgot to publish a newer version :(

**Comment by KochiyaOcean** [comment]
I've just published a new version.
