### ISSUE TITLE
如何强制刷新？

### ISSUE THREAD

**Issue by sgqy** [poooi/poi#1202]
**poi 版本 / poi version:**
v7.0.2
**操作系统 / OS:**
Windows 10 LTSB 2016 (Enterprise 14393)
**插件名和版本 / Plugin name & version:**
*(如果这是一个关于插件的 issue / If its a issue about plugin)*

**详细描述 / Details:**
*(建议提供开发者工具的截图 / A screenshot of developer tools would be better)*

浏览器操作，停止与刷新按钮均无反应。
地址栏图标永远转圈。
Alt菜单内操作无效。
只能重新启动程序。
如果可行的话，希望能取消对页面加载过程的判断。

**Comment by KochiyaOcean** [comment]
@sgqy 上游 bug，现在已经修复，请等待新版
