### ISSUE TITLE
[不兼容性公告] createStore.es 改名为 create-store.es

### ISSUE THREAD

**Issue by dkwingsmt** [poooi/poi#1204]
## 简介

为了响应学姐关于统一文件命名方式的号召，作如下改动
- `createStore.es` 改名为 `create-store.es`，同时 `createStore.es` 改为对 `create-store.es` 引用。
## 要求
- 对于 `views/createStore` 的引用应全部改为 `views/create-store`
## 向前兼容
- 所有引用 `views/createStore` 的语句都会转向引用 `views/create-store`，因此不会产生不兼容问题。
- 该改动要求 v7.0.0-beta.3 或以上版本。
  - 建议所有插件从即日起按照改动后执行。
## 向后兼容
- 暂无删除 `createStore.es` 的时间计划。
## 其它
- `views/services` 文件夹里的几个文件也需要作类似改动，不过因为这几个文件没有被任何外部插件引用，所以不会产生不兼容问题。

**Comment by ruiii** [comment]
@dkwingsmt 这个东西和上次 electron.clipboard 是在同一个版本更新么

**Comment by dkwingsmt** [comment]
@ruiii 你翻一下那个 commit （可以翻对应文件然后 blame），就能在上面看到该 commit 支持的所有版本

**Comment by magicae** [comment]
- [ ] views/utils/fileWriter.es
- [ ] views/services/developmentProphecy.coffee
- [ ] views/services/sortieDangerousCheck.coffee
- [] views/services/sortieFreeSlotCheck.coffee

**Comment by dkwingsmt** [comment]
@magicae 嗯正文最后一段提到了的，有机会会去改掉，不过不会产生不兼容性问题。

**Comment by KagamiChan** [comment]
残留的 coffee 文件的重命名已经在 coffee 到 es 的重构中完成
fileWriter 已经在 8949676dd2324831dced74dd9c07e179c8b3ea35 中更名
