### ISSUE TITLE
有关于任务所需舰娘查找的实现

### ISSUE THREAD

**Issue by rsanemo** [poooi/poi#1205]
本人只是个菜鸡，只是学了点python，又爱折腾。
之前船位不够了，所以有了这个想法。
首先，数据来源萌娘百科的任务信息，利用八爪鱼采集器的任务信息（百科要是用数据库就方便多了）。然后用python3.5.3的sqlite3建立数据库和表，利用sqlite expert professional 导入数据。最后，用python编写程序，中间还用了递归……，实现了输入现在可执行的任务（反过来查找已完成任务也是可以实现的，只是需要改一下），查找未来任务的所需舰娘。
由于数据源本身不是很好弄（主要是任务舰娘那块数据），加上我没有数据处理的经验，数据库的数据有点混乱，连第一范式都不符合，最终的显示结果，也有点不直观。
第一次用github，下面明明说可以传zip，但是一直显示不支持，不造为毛，就用了毒盘，下面附上链接(里面是数据还有python的文件)
还有Bm6后续的任务以及所需舰娘结果截图。链接 ：/s/1i5Nllzf     密码： phjp

PS:本人只是个单纯 菜鸡，做这个的目的只是希望有大佬能看到并实现这个查询未来所需舰娘的功能，别无他想。
拜托了，各位大佬
![qq 20160918173021](https://cloud.githubusercontent.com/assets/22272596/18614668/bc870e28-7dc5-11e6-847a-b04b31782b23.png)

**Comment by Gizeta** [comment]
数据源的话，kcwiki 和 poi 各在维护一份 json 任务数据，应该会比直接抓 wiki 页面简单很多。
http://kcwikizh.github.io/kcdata/quest/all.json
http://kcwikizh.github.io/kcdata/quest/poi.json

**Comment by Kitami** [comment]
直接把任务树图形化列出来岂不是更好，像暗黑2的技能树一样，不仅是舰娘，未来任务需要的装备也能查看就最好了

**Comment by rsanemo** [comment]
@Kitami 图形化是我一开始就想做的，但是舰娘的任务树太复杂了，任务之间存在不定性的关系，而且后期实装的任务还可能与早期或中期任务相关联，不便于维护。

**Comment by rsanemo** [comment]
@Gizeta  抱歉，前段时间在忙找工作的事情，一直没来看这边。
感谢提供数据源！！ ！
不过json啊，调用和维护都不是太方便直观吧？至少我觉得用数据库表，甚至excel都会好一点，不知道是有何考量。

**Comment by Gizeta** [comment]
@rsanemo 就我目前维护的方向，我是倾向用 poi 的格式做条件文字转译，kcwiki 的格式做完成条件判断。

两种格式都需要包含全部的任务描述，角川每次更新任务都出新花样，感觉行列结构维护起来并不灵活。
毕竟是 js 程序，json 肯定会更方便一些。

**Comment by rsanemo** [comment]
原来是这样，受教了。

**Comment by rsanemo** [comment]
@Gizeta 原来是这样，受教了。

**Comment by KochiyaOcean** [comment]
@Kitami 由于前置任务可能有复数个所以实际上的表现是一张有向无环图。
构建这样一张图不是难事，但是要表现为人类能一眼就能简单理解的形式实在不容易……

**Comment by Kitami** [comment]
最近发现其实需要的舰娘和道具wiki上都有人整理过，在任务页面的最下面

**Comment by KagamiChan** [comment]
@Kitami 如果你对全部任务所需舰娘和道具数据感兴趣的话，可以看一下 gizeta 发的链接里的 json 数据，这里面应该已经包括了，只是需要对数据进行一些处理

**Comment by Kitami** [comment]
其实所需道具还好，所需舰娘根据任务的完全进度其实会越来越多不用的吧，对于我这样的无课金玩家来说，母港压迫是个很大的问题
