### ISSUE TITLE
Linux Deepin 15.3系统下白屏

### ISSUE THREAD

**Issue by Cuiyn** [poooi/poi#1206]
**poi 版本 / poi version:**
poi-7.0.2-linux-x64
**操作系统 / OS:**
Deepin 15.3
**详细描述 / Details:**
*(建议提供开发者工具的截图 / A screenshot of developer tools would be better)*
![20160919111832](https://cloud.githubusercontent.com/assets/13913903/18621818/0e1ba132-7e5b-11e6-9413-e0a64eef5a4e.png)
从大约Poi 6.0、Deepin 15开始出现的这个问题吧，程序打开后白屏，除标题栏外不能正常显示任何内容，退出后给出上述提示。本人比较小白，尝试自己解决未果，怀疑是Deepin系统对桌面环境做了某些改动，导致Poi找不到相应的主题文件。

不知能否在下一版本提高兼容性，谢谢！

**Comment by KochiyaOcean** [comment]
@Cuiyn 看起来只是没有下载完整

**Comment by Cuiyn** [comment]
@KochiyaOcean 您好，我尝试过直接从GitHub下载Release、下载源码执行、Poi官网下载压缩包运行，都会出现上述问题，而同样的程序文件在Ubuntu虚拟机下没有问题，感觉不是程序不完整，可能是系统缺了点什么

**Comment by KochiyaOcean** [comment]
@Cuiyn 并没有使用过这个发行版…… 你试试看直接按照 readme 构建一遍能否运行

**Comment by Cuiyn** [comment]
@KochiyaOcean 好的，我最近抽空试一下，感谢您的帮助

**Comment by Cuiyn** [comment]
按照Readme构建后，程序运行仍然白屏，但是上面的错误提示消失。
![20160928113640](https://cloud.githubusercontent.com/assets/13913903/18900011/0dfc2836-8570-11e6-8396-85f0ec4b8681.png)
![20160928113803](https://cloud.githubusercontent.com/assets/13913903/18900012/0e0b8ba0-8570-11e6-8134-abf206b3cc50.png)
可能是我用的发行版有点小众了……希望没有影响开发组的正常工作

**Comment by dkwingsmt** [comment]
按一下 Ctrl-Shift-i 打开开发者工具，找到命令行看看有没有错误截下图

**Comment by Cuiyn** [comment]
@dkwingsmt 您好，命令行输出是这样的：
![20160928114539](https://cloud.githubusercontent.com/assets/13913903/18900110/24a7f8de-8571-11e6-869f-cae4afe9f3b7.png)

**Comment by KagamiChan** [comment]
![deepin-2016-09-28-17-14-50](https://cloud.githubusercontent.com/assets/3816900/18907664/184a462c-859f-11e6-980a-bf8c4de05aa3.png)

虚拟机里面安装了一个 deepin 15.3，看起来工作正常的样子
我安装的是 1.7.1 deb 包，然后 nodejs 用了 6.x 版，npm 升级到了最新版

**Comment by KagamiChan** [comment]
开发版也运行成功了，看来是和系统无关的，毕竟本来就是 debian 系
建议先把 ~/.config/ 下面的 poi 文件夹改个名字，或者在把里面的 plugins 文件夹删掉，再运行看看

**Comment by Cuiyn** [comment]
@KagamiChan 谢谢您的回复，看来是只有我自己存在这个问题，也确实home目录好久没有整理了。我抽空琢磨一下，整理一个解决方法就会关闭issue的。感谢Poi开发组！

**Comment by Cuiyn** [comment]
按照@KagamiChan 的回复，问题已经成功解决。

> 建议先把 ~/.config/ 下面的 poi 文件夹改个名字，或者在把里面的 plugins 文件夹删掉，再运行看看

感谢开发组的热心解答！

**Comment by KagamiChan** [comment]
嗯，如果是改名字修复的话，那么可以试试把  config.cson 给重命名，这样如果也能运行成功的话，会重置设置，但是别的记录之类的应该还会在
删除 plugins 文件夹好的话，那就是重装插件的事情了 - -
