### ISSUE TITLE
一心二用插件中Flash的右键菜单失效

### ISSUE THREAD

**Issue by supercatexpert** [poooi/poi#1207]
**poi 版本 / poi version:**
7.0.2
**操作系统 / OS:**
Debian Linux 8.6 AMD64
**插件名和版本 / Plugin name & version:**
一心二用 2.5.0

**详细描述 / Details:**
一心二用插件中Flash的右键菜单失效，在6.3.2版本中还是可用的，在终端显示错误：

```
[ERROR] TypeError: Menu.buildFromTemplate is not a function
    at WebContents.<anonymous> (/home/supercat/Games/poi/resources/electron.asar/browser/api/web-contents.js:223:23)
    at emitTwo (events.js:106:13)
    at WebContents.emit (events.js:191:7)
```
在Google上搜索相关信息发现似乎是electron修改了菜单相关的函数：
[https://github.com/electron/electron/issues/5862]

**Comment by supercatexpert** [comment]
[https://github.com/electron/electron/pull/7110]
看来是electron的问题，似乎新版本就正常了？

**Comment by KochiyaOcean** [comment]
@supercatexpert electron 1.3.6 之后的版本已修复，如果有条件可以自行更新
