### ISSUE TITLE
一心二用 插件不正常

### ISSUE THREAD

**Issue by Joehere** [poooi/poi#1208]
**poi 版本 / poi version:**
7.0.2
**操作系统 / OS:**
windows 10
**插件名和版本 / Plugin name & version:**
*(如果这是一个关于插件的 issue / If its a issue about plugin)*
插件 一心二用 2.3.3
**详细描述 / Details:**
*(建议提供开发者工具的截图 / A screenshot of developer tools would be better)*
无法正常显示, 无法关闭
![qq 20160920111853](https://cloud.githubusercontent.com/assets/1538910/18676570/0bf4e520-7f24-11e6-8c61-cfe359fbda8c.jpg)

**Comment by KochiyaOcean** [comment]
@Joehere 最新版 2.5.0 请更新
