### ISSUE TITLE
内存占用太大

### ISSUE THREAD

**Issue by septluna** [poooi/poi#1212]
poi四个后台browser tool进程在不启用插件的情况下
基础占用是150m，算上主进程130m，合计280±50m
这样是可以接受的，但是之后的问题
在启用一个插件之后
四个后台browser tool进程的占用增加了100m
然后再启用某些特殊插件之后，会多出一个browser tool进程
这样一来就会出现一次性增加200m的情况（合计大约500m）
接着在启用2个插件之后（一共4个插件）
合计6个browser tool进程，一共占用了将近700m的内存
这样算下来poi这个程序一共用掉了1g以上的内存
这对于4g内存的电脑来说是无论如何都无法接受的
不管是进程还是线程，都太重了，更别说是使用vm了
我觉得插件的权限应该由poi实现相应的接口
以事件驱动的方式去主动触发插件的相应功能，而不是靠插件监听
对于需要定时监听的，poi只要定义一个轮询事件，然后剩下的
插件的所有实现全部靠委托完成
这样一来就只需要由poi进行多线程的管理
性能的消耗将会大大减少，最多可能只需要300m

**Comment by dkwingsmt** [comment]
@septluna 建议换成 8G 内存的电脑

**Comment by KochiyaOcean** [comment]
@septluna 参照 electron 的架构，每一个窗口都是独立的 render process，内存占用大也是没办法的事
不过话说回来这个时代 4G 内存真的能用么……

**Comment by dkwingsmt** [comment]
总之你的想法很有见解，可惜架构不是我们自己写的。

**Comment by septluna** [comment]
说真的。。。现在这个做法，如果单开一个进程，实现udp交互，也不过50m左右，但是插件比单独进程实现的内存占用还大啊。

**Comment by KochiyaOcean** [comment]
@septluna 参照 http://github.com/electron/electron ，poi 的设计思路上并没有对资源占用有太高的要求，如果是对资源占用敏感的话还是使用 native 的解决方案比较好

**Comment by JenningsWu** [comment]
poi 是基于 [Electron](https://github.com/electron/electron) 开发的，并没有自己写进程管理。Electron 就是这个内存使用风格。我们认为使用 Electron 带来的好处多于内存占用大及其他缺点，所以并没有更换平台的想法。
有得必有失把。

**Comment by septluna** [comment]
我还是觉得应该考虑减少性能开支，重复的东西应该尽可能合并起来，几个插件之间都需要的东西统一搞成接口，进程压缩成线程，线程压缩成task，需要长时等待的搞成异步委托，在等待期间就不占用资源，这样的做法至少可以使得每一个插件的内存占用减少50m，然后总内存增加50m左右，poi运行期间，根本没有必要使得每一个插件都处于常驻状态

**Comment by KochiyaOcean** [comment]
@septluna 要做这么复杂的架构的话跨平台基本无法实现，而且与其要这么改不如推倒重来

**Comment by dkwingsmt** [comment]
你先了解一下 Chrome 和 Electron 的内存模型吧，这里我们没法做。链接上面都给出来了。
只要 poi 还基于 Electron 一天，这些就都没有可能。

**Comment by dkwingsmt** [comment]
如果你愿意的话我们很欢迎你 Fork 一下 Electron，做一个支持单进程多线程的 Electron 窗口模型的。
这对于人类的进步是件好事。

**Comment by dkwingsmt** [comment]
最后，开发 poi 的本质目的只是给自己一个自己喜欢的工具，发布给大家用只是次要目的。如果你觉得这是必要的，那么欢迎你能自行 fork 并提交 pull request，如果（你做得到并且）合适的话我们当然会欣然 merge，在此过程中如果有什么想要了解的信息可以通过各种渠道联系我们。但是很显然，如果我们觉得成本太高/做不到，同时收效又微小（照顾罕见的4G内存用户）的话，那么仅仅是以 issue 提出来请求，我们肯定有选择不做的权利。
