### ISSUE TITLE
斬殺提醒關閉 (v7.1.0-beta.1)

### ISSUE THREAD

**Issue by Harunalive** [poooi/poi#1213]
**poi 版本 / poi version:      poi v7.1.0-beta.1

請問新版本斬殺提醒可以關閉嗎

感覺實務上不太需要一直提醒

甚至到「無戰鬥的點」還會再提醒你一次是斬殺期 (一點提醒一次?)

------------
新用戶~

如果已經有按鈕/方法關閉還請各位不吝教導  感謝~

**Comment by KochiyaOcean** [comment]
@Harunalive 每点提醒的 bug 已经修复了

**Comment by Harunalive** [comment]
抱歉能細問一下這是插件還是程式本身的問題嗎

因為目前我還是每點提醒一次    (戰鬥完/到無戰鬥的點)

**Comment by KochiyaOcean** [comment]
@Harunalive 下一个 beta 版本会修复

**Comment by Harunalive** [comment]
好的  麻煩了

**Comment by hyq77766177** [comment]
@Harunalive
