### ISSUE TITLE
一心二用內置browser有問題

### ISSUE THREAD

**Issue by artoodetoo3301** [poooi/poi#1214]
**poi 版本 / poi version:** 7.1.0

**操作系统 / OS:** Windows 10

**插件名和版本 / Plugin name & version:** 一心二用內置browser Ver. 2.3.3
*(如果这是一个关于插件的 issue / If its a issue about plugin)*

**详细描述 / Details:** 
*(建议提供开发者工具的截图 / A screenshot of developer tools would be better)*

1) 開了出來不能關掉
2) 基本網址功能都沒了
3) 顯示網頁只有這個小部分, 又不能放大

Screenshot: 

![snag-0002 2016-09-30 1 55 22](https://cloud.githubusercontent.com/assets/12843291/18965862/759fc94c-86b1-11e6-859a-f2c7d2f232a8.png)

**Comment by KagamiChan** [comment]
插件最新版本是 2.5.0，请升级看看

**Comment by artoodetoo3301** [comment]
不知道剛才為什麼無法找到更新
解決了 謝謝
