### ISSUE TITLE
圖標無法正確顯示

### ISSUE THREAD

**Issue by sodasu11** [poooi/poi#1215]
**poi 版本 / poi version:**
v7.1.0

**操作系统 / OS:**
Windows

**插件名和版本 / Plugin name & version:**
_(如果这是一个关于插件的 issue / If its a issue about plugin)_

**详细描述 / Details:**
_(建议提供开发者工具的截图 / A screenshot of developer tools would be better)_
如圖，按鍵上的圖示顯示為方框:
![poi](https://cloud.githubusercontent.com/assets/7804877/19007552/2efb75c0-872b-11e6-9575-96eb59d11bdf.png)

**Comment by KochiyaOcean** [comment]
你使用的字体不支持 Font Awesome 图标

**Comment by sodasu11** [comment]
請問Font Awesome 支持那些字體?

**Comment by KochiyaOcean** [comment]
理论上 poi 是自带字体支持的…… 你看一下 node_modules/font-awesome/fonts 里有没有字体文件在

![image](https://cloud.githubusercontent.com/assets/8194131/19012069/049844c2-87dd-11e6-9107-2d5be2670840.png)

**Comment by KagamiChan** [comment]
你是不是自定义了 CSS 样式表？是怎么写的

**Comment by sodasu11** [comment]
我有用MacType渲染，不確定是不是會碰到CSS...

**Comment by dkwingsmt** [comment]
@sodasu11 不太懂 MacType，看了下是用来使得字体更好看的插件？感觉并不会影响，poi 整个的格式是用 CSS 指定的。以及有可能就是因为 MacType，因为那些图标的本质是文字和字体，可能被 MacType 给覆盖了字体了。

**Comment by yukixz** [comment]
@dkwingsmt 傻 dk
mactype 是代替 cleartype 的、没影响

**Comment by yukixz** [comment]
@yukixz 除非替换了字体

**Comment by yukixz** [comment]
@sodasu11 mactype 有个例外设置、把 poi 加上试试
