### ISSUE TITLE
能否解决下Poi的cpu和内存占用过大的问题？

### ISSUE THREAD

**Issue by Fire1nRain** [poooi/poi#1216]
**poi 版本 / poi version:7.1**

**操作系统 / OS:Win10（使用win7兼容模式运行）**

**插件名和版本 / Plugin name & version:**
_(如果这是一个关于插件的 issue / If its a issue about plugin)_

**详细描述 / Details:Poi真的是个好用的工具，但是不知道从哪个版本开始，我发现Poi的CPU占用和内存占用变得特别的大了。在我台式机上面能彪到75%+，在买来玩舰娘的国产平板上干脆直接两个都是100%了。试着结束了一下占用最多的那个线程，发现是游戏画面的进程。这个问题我用同一台电脑，在KCV和ING上都没有遇到过。有时候晚上挂机，风扇转速高的吓人，只能换用ing。请问能否在后续的版本中解决下这个问题？**
_(建议提供开发者工具的截图 / A screenshot of developer tools would be better)_

**Comment by KochiyaOcean** [comment]
@Fire1nRain 好好用普通模式啊为什么要用兼容模式

**Comment by KagamiChan** [comment]
我在我自己的平板上用的时候，只要游戏界面在前台，KCV 和 poi 的 CPU 占用基本差不多
然后如果最小化 poi 的话，占用率立刻下降了
推测还是 flash 本身的性能问题 - -

至于内存，估计没有办法吧……

至于台式机，可以问一下台式机是什么配置吗，我这边是还好的

P.S. @KochiyaOcean 一直想问 pepflashplayer.dll 会不会跟着 chrome 的更新而更新

**Comment by taroxd** [comment]
@KagamiChan flash 会更新，不过不一定是跟着 chrome

**Comment by KochiyaOcean** [comment]
@KagamiChan 并不会

**Comment by KagamiChan** [comment]
嗯……了解了。@KochiyaOcean  @taroxd

**Comment by Fire1nRain** [comment]
@KochiyaOcean 用不用兼容模式都一样……笔记本，台式机和平板都遇到了这个问题，只不过笔记本的配置比较好，所以没有100%而已。第一次发现这问题就是暑假期间用笔记本挂机的时候发现用kcv晚上很安静，poi晚上风扇会是不是加速。

**Comment by Fire1nRain** [comment]
@KagamiChan 我平板1000出头一点的国产山寨货，配置渣就不说了，纯粹用来玩舰娘的→_→
我这儿KCV和ING可以很流畅的运行，然而POI在平板上打开来就开始卡死，有种本科的时候用垃圾本玩孤岛危机的感觉。。。

**Comment by KochiyaOcean** [comment]
@Fire1nRain 纯粹就功能性的讲，因为 Win7 和 Win10 的行为不甚相同所以不建议使用兼容模式运行

**Comment by KochiyaOcean** [comment]
@Fire1nRain 以及如果是某特性进程占用过多，在任务管理器里杀掉然后看看哪个插件不能用就行了

**Comment by Fire1nRain** [comment]
@KochiyaOcean 首先，开不开兼容模式都有占用高的问题，所以我觉得应该不是兼容模式引起的。
其次，我试过了，你猜猜看我杀掉的那个进程是啥？（请看问题描述→_→我已经提到了）

**Comment by KochiyaOcean** [comment]
@Fire1nRain 不知道说的游戏画面是什么，如果是 flash 的话那就真没办法了

**Comment by KochiyaOcean** [comment]
@Fire1nRain 显示设置里把 flash 画质调低或许是个选择

**Comment by Fire1nRain** [comment]
@KochiyaOcean 就是flash那个进程。。。问题在于，为什么在我的三台电脑上，同样的画质下，poi的flash界面内存占用比kcv和ing高呢？调低画质确实有可能解决问题，然而这只是治标不治本啊。为何不能从根本上解决POI的flash界面占用高的问题呢？

**Comment by KochiyaOcean** [comment]
@Fire1nRain poi 的是 chrome 的 ppapi，kcv 是 ie 的 npapi。一般来说资源占用都很正常（我所有测试机都没有这种问题），如果你要找解决方案大概只能去问 adobe 了

**Comment by Fire1nRain** [comment]
@KochiyaOcean 然而我ING用的是chromium内核，依然占用内存比poi低。。。。So……

**Comment by Fire1nRain** [comment]
@KochiyaOcean 我暑假期间发现问题后也是试了很多可能性之后才提交问题的……

**Comment by KochiyaOcean** [comment]
@Fire1nRain 你看看你 ing 的 flash 版本吧

**Comment by Fire1nRain** [comment]
@KochiyaOcean goodpoint，然而，怎么查……？

**Comment by KochiyaOcean** [comment]
@Fire1nRain https://www.adobe.com/jp/software/flash/about

**Comment by Fire1nRain** [comment]
我用的Chrome是23,0,0,162
老的ING上是21,0,0,157
Poi上是23,0,0,162
新版的ING上chromium没更新，应该还是21（网络有问题，github上新版的ing拖不下来）

**Comment by KochiyaOcean** [comment]
@Fire1nRain 那把 ING 的 flash 复制覆盖掉 poi 的就行了嘛（ poi 的 flash 在 PepperFlash 文件夹下

**Comment by Fire1nRain** [comment]
@KochiyaOcean 我午觉睡醒了去试试。我有种不一定有用的感觉→_→

**Comment by KagamiChan** [comment]
@Fire1nRain 我的平板是 Z3795/ 4g RAM 的配置，启动时候略有卡顿，不过玩起来是正常的
如果是卡在内存占用的话，可以尝试卸载或者禁用一些不常用插件

以前试过换 flash 版本，结果是会有微小的性能差异 - -

**Comment by ziyu-clp** [comment]
@KochiyaOcean 我怎么觉得7.10更新之后似乎变得更卡了呢 之前的版本同时开chrome看视频毫无压力的

**Comment by KochiyaOcean** [comment]
@ziyu-clp 开 / 关硬件加速看看
