### ISSUE TITLE
Poi按刷新按钮后前往和刷新两个按钮就失效的问题

### ISSUE THREAD

**Issue by Fire1nRain** [poooi/poi#1217]
**poi 版本 / poi version:7.1**

**操作系统 / OS:win10**

**插件名和版本 / Plugin name & version:**
_(如果这是一个关于插件的 issue / If its a issue about plugin)_

**详细描述 / Details:正常进入游戏后，如果遇到某些情况需要刷新游戏（比如一不小心大破进击了）。按刷新按钮后，检测页面是否载入完全的部分似乎出错了，导致明明都进入母港了，下面的地址栏依旧提示正在载入，同时”X”按钮不会变回“→”，“X”和刷新两个按钮这时候都没有用了。点了没用。
具体情况如截图所示
![qq 20161003133946](https://cloud.githubusercontent.com/assets/10319645/19027834/82a1c116-896f-11e6-9bc9-51f6c574ee6f.png)

开发者工具那边不知道你们需要哪个界面的截图。所以没截取**

_(建议提供开发者工具的截图 / A screenshot of developer tools would be better)_

**Comment by KochiyaOcean** [comment]
Electron 的 remote 模组在某些特殊情况下崩溃，具体原因不明，我正在调查准备回报

**Comment by Fire1nRain** [comment]
我是次次都会有这问题，希望能尽快解决吧


发自网易邮箱大师





在2016年10月03日 16:20 ，東風谷オーシャン<mailto:notifications@github.com>写道：


Electron 的 remote 模组在某些特殊情况下崩溃，具体原因不明，我正在调查准备回报

**Comment by KochiyaOcean** [comment]
@Fire1nRain 并不是 poi 组这里能够解决的 bug……

**Comment by Fire1nRain** [comment]
那就只能期待electron可以修复这问题了


发自网易邮箱大师


在2016年10月03日 16:29 ，東風谷オーシャン<mailto:notifications@github.com>写道：


@Fire1nRain<https://github.com/Fire1nRain> 并不是 poi 组这里能够解决的 bug……

**Comment by gnattu** [comment]
Fixed in https://github.com/electron/electron/pull/8110
