### ISSUE TITLE
7.1.0 高DPI缩放时，截图只能截一部分

### ISSUE THREAD

**Issue by pcsjx** [poooi/poi#1219]
**poi 版本 / poi version:**
7.1.0
**操作系统 / OS:**
Windows 10 专业版 14393 on Surface Pro 4（缩放200%）
**插件名和版本 / Plugin name & version:**
*(如果这是一个关于插件的 issue / If its a issue about plugin)*

**详细描述 / Details:**
*(建议提供开发者工具的截图 / A screenshot of developer tools would be better)*
因为Surface Pro 4屏幕分辨率比较高，所以一直以来系统默认的DPI缩放比例都是200%的。此前截图一直没有问题，但在7.1.0里，200%缩放时截图只能截左上1/4，如果是100%缩放则可以全部截取到。

**Comment by KochiyaOcean** [comment]
@pcsjx 重现不能，不过准备改回旧方法了

**Comment by pcsjx** [comment]
![2016-10-4t1 49 51](https://cloud.githubusercontent.com/assets/22597540/19045646/e94c4d86-89d4-11e6-8f26-878a4ca9fe7a.png)
截图出来就是这个样子的。

**Comment by KochiyaOcean** [comment]
Fixed
