### ISSUE TITLE
EO海域提督等级与编成

### ISSUE THREAD

**Issue by satsukikai2** [poooi/poi#1220]
**详细描述 / Details:**
请问是否能统计不同提督等级下，EO海域出某种编成的机率呢？
主要是4-5的门神点与王点。

**Comment by yukixz** [comment]
太麻烦不想做

**Comment by yukixz** [comment]
dropshiprecords 中已经包含了提督等级和深海舰队信息。

**Comment by Gizeta** [comment]
数据汇报插件已经收集了相关的数据，如果有能力可以自己写代码统计。
数据库文档见 https://github.com/poooi/poi-server/wiki
