### ISSUE TITLE
关于代理链设置

### ISSUE THREAD

**Issue by sgqy** [poooi/poi#1221]
**poi 版本 / poi version:**
7.1.0

**详细描述 / Details:**
设poi端口为8888。
本issue通过此端口代理发送。（即poi本身没问题）
防火墙已设置允许通过并重启。（相同规则，ss可用）

局域网内无法连接poi：

![1](https://cloud.githubusercontent.com/assets/4893302/19119840/9a1cf62c-8b53-11e6-9443-7781047b3310.PNG)

如何设置poi对局域网的代理？

**Comment by KochiyaOcean** [comment]
这个端口只是用来获得游戏数据的，代理建议使用上级代理
一定要将此端口开放的话，修改 `lib/proxy.es` 的 `369` 行，修改 `127.0.0.1` 为 `0.0.0.0`

```javascript
    this.server.listen(listenPort, '127.0.0.1', () => { // 修改此处
      this.port = this.server.address().port
      app.commandLine.appendSwitch('proxy-server', `127.0.0.1:${this.port}`)
      app.commandLine.appendSwitch('ignore-certificate-errors')
      app.commandLine.appendSwitch('ssl-version-fallback-min', "tls1")
      log(`Proxy listening on ${this.port}`)
    })
```
