### ISSUE TITLE
更新後海域血量插件秀斗

### ISSUE THREAD

**Issue by Harunalive** [poooi/poi#1222]
**poi 版本 / poi version:**   7.1.0

**插件名和版本 / Plugin name & version:**       海域血量  V 3.0.2
*(如果这是一个关于插件的 issue / If its a issue about plugin)*

http://imgur.com/a/tsAKi

上圖

剛剛打完3-5  海域血量還是沒變動

1-5  1-6  2-5都正常顯示

是今天更新之後插件秀斗了嗎?

**Comment by KagamiChan** [comment]
娇喘又改 api 了

![image](https://cloud.githubusercontent.com/assets/3816900/19129447/e538e410-8b79-11e6-888c-0070be5e0943.png)

**Comment by KochiyaOcean** [comment]
@Chibaheit @Chibaheit @Chibaheit @Chibaheit @Chibaheit @Chibaheit @Chibaheit @Chibaheit @Chibaheit @Chibaheit @Chibaheit @Chibaheit @Chibaheit @Chibaheit @Chibaheit @Chibaheit @Chibaheit @Chibaheit @Chibaheit @Chibaheit @Chibaheit @Chibaheit @Chibaheit @Chibaheit

**Comment by Chibaheit** [comment]
fixed

**Comment by wafer-li** [comment]
poooi/plugin-map-hp#9

**Comment by KagamiChan** [comment]
好像其实不用加 `api_map_info`，自动就识别好了的样子
貌似是 info.maps 里面的数据就没有在更新
![image](https://cloud.githubusercontent.com/assets/3816900/19166200/3b8cdc44-8c39-11e6-8b0b-3458a8a63681.png)

![image](https://cloud.githubusercontent.com/assets/3816900/19166217/4d2c920a-8c39-11e6-8a3e-3a338c8bcc65.png)

**Comment by KagamiChan** [comment]
P.S. 开了陆航之后会多出来基地航空队相关的内容，可能在处理的时候就得再分个类？

**Comment by dkwingsmt** [comment]
@KagamiChan 在 info.airbase

**Comment by KagamiChan** [comment]
@dkwingsmt 现在 info.maps 里面多出了若干个 undefined，是基地航空队的混进去了

**Comment by dkwingsmt** [comment]
@KagamiChan 是厉害了
