### ISSUE TITLE
Linux下deb版poi显示无法加载

### ISSUE THREAD

**Issue by Margular** [poooi/poi#1223]
**poi 版本 / poi version:**
7.1.0
**操作系统 / OS:**
kali rolling 2016.2

**详细描述 / Details:**
运行后一片白色背景，中央写着六个字：无法加载插件
但是下载7z打包的poi能运行

**Comment by KochiyaOcean** [comment]
@Margular 你确定照着 readme 做了么

**Comment by Margular** [comment]
我是在releases下载的deb包，然后gdebi安装，运行后就出现这个。你说的readme是README.md吗，那儿并没有相关说明啊

**Comment by KochiyaOcean** [comment]
@Margular 可能是 electron-builder 的 bug，不过没有机器不能测试

**Comment by Margular** [comment]
好吧，不知道别的发行版如何，比如ubuntu

**Comment by KagamiChan** [comment]
前几天才在 deepin 里面装了一遍： #1206 
当时用的命令是 `dpkg -i`，因为想着可能还要测试一遍开发版的情况，所以下载 deb 的途中还去安装了 nodejs。虽然我觉得没什么影响才对 - -

**Comment by Tanmy1998** [comment]
Ubuntu 16.04.1 LTS下表示也有相同问题。

**Comment by KagamiChan** [comment]
嗯，刚才看了一下，的确是出现 flash 播放器无法加载的错误，orz

**Comment by Tanmy1998** [comment]
发现问题所在了,flash插件权限是0600的锅。
于是:
sudo chmod 0644 /opt/poi/resources/PepperFlash/linux-x64/libpepflashplayer.so
然后就好啦lol

**Comment by dkwingsmt** [comment]
@Tanmy1998 吃精，你 linux 权限是厉害

**Comment by KagamiChan** [comment]
嗯……刚才我也发现了- - 用 gksudo poi 就能载入……
这个貌似可以在 build 脚本里面设置？

**Comment by Tanmy1998** [comment]
@KagamiChan 小白表示postinst里面加行chmod就行啦。

**Comment by sjx95** [comment]
不止deb版本，rpm打包的也不能加载flash。我的系统是openSUSE，7.0.0版本的poi还是可以的。

**Comment by KochiyaOcean** [comment]
@sjx95 可能和 https://github.com/electron-userland/electron-builder/issues/786 有关（如果是因为这个，下个版本将会修复

**Comment by sjx95** [comment]
@KochiyaOcean 已经chmod 755了。
所以以后还是zip自己动手比较靠谱？
哦对了，顺便一问，一心二用里面神基project玩着玩着没声音了的问题有修正吗……

**Comment by KochiyaOcean** [comment]
@sjx95 没玩过所以也没测试。Chrome 内核升级到 53 版本，如果这个问题与此有关就可能被修复

**Comment by sjx95** [comment]
@KochiyaOcean 我猜是这样的，这个游戏本身检测到窗口不是焦点的话（比如切换到别的页面标签了），就自己给静音了。然后一心二用有时候会自动捕获到那个flash，捕获之后不知道为啥神基就认为自己不是焦点了，就自己静音了……

**Comment by KochiyaOcean** [comment]
@sjx95 神姬是 canvas 不是 flash 吧

**Comment by sjx95** [comment]
@KochiyaOcean 是在下煞笔了，原来不是个flash
