### ISSUE TITLE
关于poi新版本提示地点功能

### ISSUE THREAD

**Issue by Margular** [poooi/poi#1224]
**poi 版本 / poi version:**
7.1.0

**详细描述 / Details:**
居然是显示数字，我表示记不住啊。。能不能搞成弹出小图片框的那种，还带显示自己曾经走过的轨迹

**Comment by KochiyaOcean** [comment]
@Margular 非常不好做

**Comment by KagamiChan** [comment]
有过一些切换成字母的讨论，见 #445 #760 
（为什么现在读起来有一种当初我接了这个任务的感觉
图的讨论有 #821

@KochiyaOcean 请教一下如果需要数字点和字母点转换的插件的话，应该用什么思路来和主程序配合？现在重构过了是不是可行性更好了

**Comment by dkwingsmt** [comment]
当前，yuki 在每次有新地图发布之后去拆地图 swf 并从中提取各点位置以及和数字点的联系，来得到方向， hardcode 到未卜先知中，用于未卜先知的显示。见 https://github.com/poooi/plugin-prophet/blob/master/assets/data/mapspot.cson。

数字点和字母点的转换，如果是我做的话，我会仍然把这个数据放到未卜先知里面。主要是一个插件只负责数字和字母的转换的话稍微有点太琐碎了，然后这个转换的数据和地图点方向的信息是需要同步更新的，所以放在一起的话比较合理。

当然，不管是额外开插件还是放到未卜先知，和本体的交流方式都是共通的。
插件和本体之间的数据交流，现在 redux 化之后确实有一个比较不错的方案，这个方案任务插件已经在使用了，用于传递任务要求的翻译。任务要求的翻译是任务插件做的，它把这些任务要求保存到该插件专用的 reducer 里面（`store.ext.poi-plugin-quest-info._`）。本体可以读取整个 store， 如果任务插件 substore 存在的话就读取这些翻译来显示，如果没有的话就显示原日文任务要求。

**Comment by dkwingsmt** [comment]
如果能帮忙整理信息的话，要实现这个功能代码量并不大。（考虑到之前所说的 “有人比起字母更喜欢看数字”，可能会加入一个设置来开关。）

**Comment by KagamiChan** [comment]
嗯，了解了。
如果我没理解错的话，mapspot.cson 里面也是位移，或者说是线。
不过和 #445 说的一样，KC3Kai 那边有[整理好的信息](https://github.com/KC3Kai/KC3Kai/blob/master/src/data/edges.json)，看了一下提交历史，貌似是人肉整理的位移和点的关系

**Comment by dkwingsmt** [comment]
@KagamiChan 这是因为数字不是点，而是线。

**Comment by dkwingsmt** [comment]
@KagamiChan 还要去请求许可，好麻烦啊（躺

**Comment by KochiyaOcean** [comment]
https://github.com/poooi/poi/pull/1227
大概是这种感觉
![image](https://cloud.githubusercontent.com/assets/8194131/19192394/af24efc6-8cd8-11e6-9cab-96d0b2342608.png)

**Comment by KagamiChan** [comment]
简直太棒了
如果维护另外一份数据的话，是不是还能对照地把地图上的可能通路给都画出来，比如
````cson
1:
  1:[
    [0,1]
    [1,2]
    [1,3]
  ]
````
将这些可能的通路用浅灰色表示的话，就更接近真实的地图了

**Comment by dkwingsmt** [comment]
很高兴你喜欢 OwO
确实是可以的。如果能帮忙整理数据的话就帮了大忙了。

**Comment by KagamiChan** [comment]
做了 mapspot 数据的可视化，方便和图对比
考虑到后期图的复杂程度，估计要花一点时间来进行整理……

**Comment by KagamiChan** [comment]
@KochiyaOcean @dkwingsmt 
完成了…… poooi/plugin-prophet#96
~~快把我加到 contributers 里~~

**Comment by KochiyaOcean** [comment]
@KagamiChan https://github.com/poooi/poi/commit/e9941b958deb2fd8e5507943350c6f1b7ad4eae7
加了

**Comment by KagamiChan** [comment]
非常荣幸
