### ISSUE TITLE
10.05维护后海域血量不可用

### ISSUE THREAD

**Issue by castore** [poooi/poi#1225]
**poi 版本 / poi version:**
7.0.2-7.1.0
**操作系统 / OS:**
WIN7专业版X64
**插件名和版本 / Plugin name & version:**
海域血量 3.0.3
*(如果这是一个关于插件的 issue / If its a issue about plugin)*

**详细描述 / Details:**
*(建议提供开发者工具的截图 / A screenshot of developer tools would be better)*

**Comment by KochiyaOcean** [comment]
@castore 更新插件版本

**Comment by avenger404** [comment]
同上...海域血量插件不可用,Ver.3.0.3
Win10 x64

**Comment by wafer-li** [comment]
同 3.0.4 同样失效。

poi's ver: e9941b9

![image](https://cloud.githubusercontent.com/assets/12459199/19210503/2dbbd1a6-8d60-11e6-83e3-e34aec3edbf9.png)

**Comment by wafer-li** [comment]
sorry，没看到另一个 issue。

感觉这个 issue 可以 merge 到 #1226  了。
