### ISSUE TITLE
部分插件集体出现功能障碍

### ISSUE THREAD

**Issue by zzh1216** [poooi/poi#1226]
**poi 版本 / poi version:**
7.1.0
**操作系统 / OS:**
windows 7 X64
**插件名和版本 / Plugin name & version:**
1.海域血量v3.0.4
2.经验计算v3.0.4
3.耗资纪录v0.5.2
4.我变强了v4.1.4

**详细描述 / Details:**
1.海域血量点击出击后无法获得数据
2.经验计算的经验信息不会随出击自动刷新
3.耗资记录重启poi后清空
4.我变强了的提督经验值和战果值记录在poi重启后变双0。

（看别人的好像没啥问题，是我电脑缺了什么兼容性软件么，求助。）

**Comment by KochiyaOcean** [comment]
因为换 API 了所以比较麻烦，等待插件 & 本体更新

**Comment by zzh1216** [comment]
感谢答疑，我还以为是我系统缺啥东西了。（不过问了下群友，他们的耗资纪录好像并不会重启清零）

**Comment by dkwingsmt** [comment]
@zzh1216 耗资记录重启清空发生过很多次了么？你在耗资记录按一下 ctrl-shift-i 看下 console 有没有错误

**Comment by zzh1216** [comment]
@dkwingsmt 看了下，没生成存放记录的文件夹。。。[http://p1.bqimg.com/4851/6dd1e3d991d2241d.png](url)

**Comment by dkwingsmt** [comment]
@zzh1216 那几个错误是正常的，是刚打开的时候没有文件的意思。你看看那个文件夹（直到 19027429 为止）是否存在？不存在的话你把文件夹创建一次，看看还有没有问题

**Comment by zzh1216** [comment]
@dkwingsmt 可以了，自己创建目录之后问题解决了。秃秃和经验计算的问题。。。难道也少了？我去找个别人的文件夹对照下？

**Comment by dkwingsmt** [comment]
秃秃有可能，但我不清楚秃秃是用 member_id 做的还是用 nickname_id 做的 @ruiii 
（耗资记录这个数字是 member_id）

经验计算是吃吧的锅。和这个无关。 @Chibaheit 别玩千年了快来修

**Comment by ruiii** [comment]
@dkwingsmt 秃秃用的是 memberId

**Comment by dkwingsmt** [comment]
@ruiii 好

**Comment by ruiii** [comment]
@zzh1216 秃秃这边 有部分值是存在 localStorage 里的 比如计算的基础值

**Comment by dkwingsmt** [comment]
@zzh1216 耗资记录有可能会出现新玩家无法创建目录的问题，我晚点检查一下。

**Comment by ruiii** [comment]
@zzh1216 请问秃秃数据清零的时候，插件上有显示你的用户名吗？

**Comment by zzh1216** [comment]
@ruiii 有，这个倒是不会清零，不过好像不准？我看实际是1309，插件显示1324，排名倒是没错。在自定义战果值里面的设置，重启就会失效。看样子也是本地存储问题了？

**Comment by ruiii** [comment]
@zzh1216 应该是本地存储的问题 另外如果今天更新的数值也出错的话 麻烦告诉我

**Comment by zzh1216** [comment]
@ruiii 数值没问题了，辛苦了。话说请问下秃秃的本地存储路径是什么？

**Comment by ruiii** [comment]
@zzh1216 路径是 'plugin-senka' 这个问题应该修复了，麻烦更新到 v4.1.5 试试

**Comment by sgqy** [comment]
原来耗资记录自动清空不是feature而是bug啊……
虽然点一下“打开记录文件存放处”会创建目录（刚点的，不知有没有效果）……

**Comment by KagamiChan** [comment]
貌似只剩下问题 2 了
