### ISSUE TITLE
 7.1.0 無法截圖

### ISSUE THREAD

**Issue by artoodetoo3301** [poooi/poi#1228]
**poi 版本 / poi version:** 7.1.0

**操作系统 / OS:** Windows 10

**插件名和版本 / Plugin name & version:** 不是插件
*(如果这是一个关于插件的 issue / If its a issue about plugin)*

**详细描述 / Details:** 無法截圖
*(建议提供开发者工具的截图 / A screenshot of developer tools would be better)*

按了截圖沒有圖產生出來
轉了位置也是一樣
如果如何解決?

**Comment by KochiyaOcean** [comment]
Dumplicated https://github.com/poooi/poi/issues/1219

**Comment by artoodetoo3301** [comment]
我是使用1080P的桌機
也是100%
但是沒有圖跑出來

**Comment by KochiyaOcean** [comment]
@artoodetoo3301 原因相同
下个版本修复

**Comment by artoodetoo3301** [comment]
好的
