### ISSUE TITLE
高DPI模式下截图范围问题

### ISSUE THREAD

**Issue by einbrain** [poooi/poi#1231]
**poi 版本 / poi version:**
7.1.0

**操作系统 / OS:**
Windows 10 Home 64bit

**详细描述 / Details:**
高DPI模式（小屏高分辨率设备，整个系统UI放大150%）下游戏分辨率会比设置值高，
此时截图分辨率为放大后值，而实际截图范围为原设置值。

举例：
系统UI放大倍数150%，设置分辨率800x480，实际分辨率1200x720，
截图分辨率1200x720，而截图实际内容为左上角800x480的部分。

截图效果例：
![2016-10-10t16 50 47](https://cloud.githubusercontent.com/assets/10205651/19232517/1eba8c26-8f1b-11e6-993a-4c37ff9671e7.png)

**Comment by KochiyaOcean** [comment]
Dup https://github.com/poooi/poi/issues/1219
