### ISSUE TITLE
添加安全模式

### ISSUE THREAD

**Issue by yukixz** [poooi/poi#1233]
添加安全模式（`--safe-mode`）或者无插件选项（`--no-plugin`）用于快速定位是否 poi bug。

**Comment by KagamiChan** [comment]
安全模式下不载入插件，那么存储在 localstorage 的 store 缓存需要清理吗，还是说加一个 `--clean-store` 的选项

**Comment by yukixz** [comment]
@KagamiChan 当然还没有store……😂
