### ISSUE TITLE
游戏界面没有声音

### ISSUE THREAD

**Issue by wafer-li** [poooi/poi#1234]
**poi 版本 / poi version:**
a312f1b

**操作系统 / OS:**
OSX 10.11.6

**详细描述 / Details:**

本体声音不受影响。

![image](https://cloud.githubusercontent.com/assets/12459199/19473459/be3b2ae8-9566-11e6-95c2-1630b748b029.png)

点击开关声音按钮，出现蓝色箭头的错误

**Comment by yukixz** [comment]
@wafer-li issue 1234

**Comment by wafer-li** [comment]
😂

**Comment by KochiyaOcean** [comment]
https://github.com/electron/electron/issues/7351

**Comment by wafer-li** [comment]
@KochiyaOcean 

OK，坐等上游。

**Comment by wafer-li** [comment]
1.4.8 版本更新了。
electron/electron#8003

**Comment by KochiyaOcean** [comment]
@wafer-li 并没有修复

**Comment by wafer-li** [comment]
@KochiyaOcean 呃，我的意思是现在可以更深一步看到调用栈了，或许能给上游提供一些必要的信息。

**Comment by wafer-li** [comment]
https://github.com/electron/electron/issues/7351#issuecomment-265528552

**Comment by KochiyaOcean** [comment]
自行升级一下吧……目前还在测试

**Comment by wafer-li** [comment]
Fixed.
