### ISSUE TITLE
工具列卡未出擊、插件小問題

### ISSUE THREAD

**Issue by Harunalive** [poooi/poi#1235]
**poi 版本 / poi version:** 7.1.0

**操作系统 / OS:**  WIN7 
# 

**详细描述 / Details:**
_(建议提供开发者工具的截图 / A screenshot of developer tools would be better)_

這問題卡蠻久了

目前出擊工具列都會卡未出擊

http://imgur.com/vVBsg8s.jpg

http://i.imgur.com/r1XZ7K1.jpg

但是鼠標過去顯示的位置點卻沒錯誤
(見圖1跟圖2 有正確顯示出差異)
(耗資記錄跟航海日誌<出擊>都可正確讀取出擊海域編號)

試過清快取和cookie 無效

 =================================

海域血量插件死透了....

http://i.imgur.com/h8O6vpi.jpg
# 

另外問一下耗資記錄

像1-1刷閃個人是1+2免洗DD

刷完就拆掉卻被插件記錄入渠消耗鋼

這部分算BUG嗎

還是不管有沒有入渠插件都會幫你記錄呢?
# 

不太知道開發者工具要截圖那個部分  如有需要的話就教教我吧(′・ω・‵)a

**Comment by KagamiChan** [comment]
海域血量都是实装陆航之后角川的 API 更改导致的数据读取错误，目测出击编号这个也是。目前开发版已经修复

虽然我没有读过代码，但是耗资记录的修理消耗应该是按照出击后的舰娘损伤程度估算的

**Comment by KagamiChan** [comment]
新的测试版已经修复了这两个问题，暂时把 issue 关了，如果有任何新情况的话还可以在这里追加
