### ISSUE TITLE
poi黑屏

### ISSUE THREAD

**Issue by violenceandroid** [poooi/poi#1236]
**poi 版本 / poi version:7.1.0**

**操作系统 / OS:windows10**

**详细描述 / Details:**
開啟後便黑屏 打開開發者工具點一下也是黑屏
用poi上其他網站不能點擊/打字
![iokn b2lvnbh jx axo](https://cloud.githubusercontent.com/assets/13573553/19618695/9c1ca4f2-9884-11e6-9942-9214940992d0.png)
![u9w_iu1z3b4_y7 cqr_m06l](https://cloud.githubusercontent.com/assets/13573553/19618698/9f77dbb2-9884-11e6-9a72-6415d5ce0154.png)

**Comment by KochiyaOcean** [comment]
关闭硬件加速看看
