### ISSUE TITLE
海域血量插件还是无效

### ISSUE THREAD

**Issue by deepsea666** [poooi/poi#1237]
**poi 版本 / poi version:7.1.0

**操作系统 / OS:**win1064位

**插件名和版本 / Plugin name & version:海域血量 V3.0.6
*(如果这是一个关于插件的 issue / If its a issue about plugin)*

**详细描述 / Details:**
血量的信息还是停留在10.5的状态

**Comment by KagamiChan** [comment]
#1235

**Comment by KochiyaOcean** [comment]
月初维护娇喘更改 API 导致的
master 早已修复，请等待新版
