### ISSUE TITLE
POI黑屏

### ISSUE THREAD

**Issue by mmzsq456** [poooi/poi#1238]
**poi 版本 / poi version:**
7.10
**操作系统 / OS:**
w7
**插件名和版本 / Plugin name & version:**
_(如果这是一个关于插件的 issue / If its a issue about plugin)_

**详细描述 / Details:**
_(建议提供开发者工具的截图 / A screenshot of developer tools would be better)_
![cg o n0vn a7 q9ho66yt6](https://cloud.githubusercontent.com/assets/23033300/19649198/7eb46242-9a37-11e6-928e-987fe31eb3bf.png)
![k1tk x c h6cx1pfuh z86](https://cloud.githubusercontent.com/assets/23033300/19649203/8099527a-9a37-11e6-9925-dde5717bc354.png)
![l9wee8 4my 5g t4ms343ef](https://cloud.githubusercontent.com/assets/23033300/19649218/8fcb671a-9a37-11e6-83e5-bd6bf502357d.png)

**Comment by KochiyaOcean** [comment]
试着删除 `%appdata%/poi/plugin` 下的文件（删除插件）然后再重新装上
