### ISSUE TITLE
小提示滚屏时CPU占用飙升

### ISSUE THREAD

**Issue by wwftherocksp** [poooi/poi#1239]
**poi 版本 / poi version:**
7.1.0
**操作系统 / OS:**
WIN10 1607
**插件名和版本 / Plugin name & version:**
_(如果这是一个关于插件的 issue / If its a issue about plugin)_

**详细描述 / Details:**
_(建议提供开发者工具的截图 / A screenshot of developer tools would be better)_

RT，如果提示语句过长，提示栏开始滚屏时，CPU风扇根本停不了

滚屏时的占用
![sp20161025_132918](https://cloud.githubusercontent.com/assets/894504/19674063/eafdf960-9ab7-11e6-8ca9-75ae26238bd3.png)
![sp20161025_132953](https://cloud.githubusercontent.com/assets/894504/19674062/eafdbbd0-9ab7-11e6-8327-c6c0db71032b.png)

不滚的时候非常老实
![sp20161025_133246](https://cloud.githubusercontent.com/assets/894504/19674064/eb099810-9ab7-11e6-8eee-af53f5f44b40.png)
![sp20161025_133255](https://cloud.githubusercontent.com/assets/894504/19674065/eb294d36-9ab7-11e6-9c4a-f7311ac0cf9b.png)

**Comment by KochiyaOcean** [comment]
@wwftherocksp 什么机器…

**Comment by wwftherocksp** [comment]
@KochiyaOcean 这机器是A10-5800K

**Comment by KochiyaOcean** [comment]
@wwftherocksp 硬件加速开了么

**Comment by wwftherocksp** [comment]
![sp20161025_135451](https://cloud.githubusercontent.com/assets/894504/19674418/9f27600a-9aba-11e6-8c81-5c1b8be31f1c.png)
@KochiyaOcean 开了

**Comment by KochiyaOcean** [comment]
CPU 占用上升属于预想中情况，然而风扇狂转就……

**Comment by wwftherocksp** [comment]
@KochiyaOcean 嘛不要在意细节，家里的电脑也能重现，滚屏时CPU占用能增加20%

**Comment by KochiyaOcean** [comment]
@wwftherocksp 调查了以后认为这是正常情况。如果有必要的话可以考虑加入开关

**Comment by KochiyaOcean** [comment]
https://github.com/poooi/poi/commit/08d8ac9fefd1a910021bff28c02b3ac46264fe26 使用硬件加速稍微优化了一下性能，个人测试 CPU 占用能从 32% 掉到 18% 左右（关闭硬件加速则无此效果

**Comment by wwftherocksp** [comment]
![snipaste20161112_230648](https://cloud.githubusercontent.com/assets/894504/20238744/1501207e-a92d-11e6-89d5-3afc9ea4cdf6.png)
7.1.0

![snipaste20161112_223218](https://cloud.githubusercontent.com/assets/894504/20238656/720bfdc2-a92b-11e6-9eee-5121bf0d5165.png)
beta3

@KochiyaOcean 升到beta3测了一下，这次是直接进入更换家具界面，可以将主界面的干扰降到最低，这样CPU消耗最多的应该就是滚屏了，CPU占用从30%降到10%，不滚的时候是3%，感觉已经可以了
