### ISSUE TITLE
高分屏更改了默认缩放大小之后截屏有问题

### ISSUE THREAD

**Issue by wwftherocksp** [poooi/poi#1240]
**poi 版本 / poi version:**
7.1.0
**操作系统 / OS:**
WIN10
**插件名和版本 / Plugin name & version:**
*(如果这是一个关于插件的 issue / If its a issue about plugin)*

**详细描述 / Details:**
*(建议提供开发者工具的截图 / A screenshot of developer tools would be better)*

RT，设置了大于100%的缩放比例之后截图就出问题了，7.0.0版貌似没问题的（忘了是不是6.9.x）

![222](https://cloud.githubusercontent.com/assets/894504/19694105/957dee88-9b10-11e6-8c53-6bf6f8a1f784.PNG)
![default](https://cloud.githubusercontent.com/assets/894504/19693671/f7c5ef5c-9b0e-11e6-9b30-3ab3cc756d0c.PNG)

200%时截图效果就是这样：
![2016-10-25t23 40 33](https://cloud.githubusercontent.com/assets/894504/19694027/52973e94-9b10-11e6-9fd8-3a1b1c3f0577.png)

这是100%的效果：
![2016-10-25t23 41 14](https://cloud.githubusercontent.com/assets/894504/19693853/b84b8f16-9b0f-11e6-891d-36bfeb723b99.png)

改缩放比例之后记得重启

**Comment by KochiyaOcean** [comment]
现在的机制改回旧版了……下个版本就能修复
