### ISSUE TITLE
檔案權限錯誤

### ISSUE THREAD

**Issue by l12436** [poooi/poi#1245]
**poi 版本 / poi version:**
7.1.0

**操作系统 / OS:**
Ubuntu 16.04

**插件名和版本 / Plugin name & version:**
_(如果这是一个关于插件的 issue / If its a issue about plugin)_

**详细描述 / Details:**
_(建议提供开发者工具的截图 / A screenshot of developer tools would be better)_
linux的deb檔案權限錯誤
/opt/poi/resources/PepperFlash/裡面的檔案權限應該是644而非600，這樣會造成poi無法讀取到flash的library

**Comment by KagamiChan** [comment]
pls refer to #1223

**Comment by l12436** [comment]
並沒有解決
他還是持續`root`+`600`的權限
使用`poi 7.2.0 beta.2`
![image](https://cloud.githubusercontent.com/assets/2596649/19992084/c4c7a64a-a275-11e6-8ddf-48b5b355b839.png)

**Comment by KochiyaOcean** [comment]
这就很尴尬了……

**Comment by l12436** [comment]
雖然我有能力自己改，但是應該要從編譯包裝的地方去把他改掉吧。

**Comment by KochiyaOcean** [comment]
总之还是要和上游说一下……

**Comment by l12436** [comment]
順便說一下，這個權限會造成poi完全無法載入flash，所以基本上這個沒有解決，deb安裝的poi基本上無法使用，除非使用者自己去把他修正

**Comment by KochiyaOcean** [comment]
总之还是要等上游修复……因为我自己用的不是 Linux 所以没法测试……

**Comment by KagamiChan** [comment]
上游已经更新了，在我本机上 build 的结果，权限应该没问题了
```shell
➜  linux-x64 ls -l 
total 18256
-rw-r--r-- 1 root root 18682816 Dec  4 09:20 libpepflashplayer.so
-rw-r--r-- 1 root root     2222 Dec  4 09:20 manifest.json
```

**Comment by KagamiChan** [comment]
试了一下 deb 包，自动编译版本的权限也是一样修复了
