### ISSUE TITLE
編成日記無法使用

### ISSUE THREAD

**Issue by michael19951216** [poooi/poi#1248]
**poi 版本 / poi version: 各版本

**操作系统 / OS:win7

小弟的電腦最近使用過系統還原
之後打開POI發現編成日記裡面的紀錄全部消失不見了
而且增加編成,匯入編成通通失效
下載過其他舊版本的POI都一樣 求解
![default](https://cloud.githubusercontent.com/assets/23148302/19835559/fa2b61b0-9ecd-11e6-839d-568a507f27aa.png)

**Comment by KochiyaOcean** [comment]
进入 `%appdata%/poi/hensei-nikki` 看看是什么情况
然后试着备份以后删掉是否可行

**Comment by michael19951216** [comment]
我把"hensei-nikki"整個資料夾刪掉 再重新安裝一次
也是沒用 資源夾沒有再出現
![default](https://cloud.githubusercontent.com/assets/23148302/19836648/4e49cba8-9eea-11e6-8108-f94d5a731b1c.png)

**Comment by KochiyaOcean** [comment]
cc @ruiii

**Comment by ruiii** [comment]
@michael19951216 那个文件夹删掉之后就没数据了。。数据是存在那的
另外看你这个截图 是没安装插件吗

**Comment by michael19951216** [comment]
@ruiii 我就是試著刪掉文件夹再重新安裝
還沒刪掉之前也是一樣完全沒有反應
刪掉文件夹再重新安裝插件 "hensei-nikki"的文件夾沒有再出現

**Comment by KagamiChan** [comment]
就是说，这样子删除了再安装插件，插件还是不能使用吗
麻烦卸载掉插件，重新启动 poi，打开一下开发者工具，安装插件和添加编成，再把开发者工具截一下图，
（打开开发者工具的方式是游戏界面的下方通知条的左手边第一个按钮）

**Comment by michael19951216** [comment]
卸载掉插件>重新启动 poi>打开一下开发者工具>安装插件和添加编成>截图
這樣?
![default](https://cloud.githubusercontent.com/assets/23148302/19899528/d725b1ca-a0a3-11e6-9ca9-a8daed01fb88.png)

**Comment by KagamiChan** [comment]
@michael19951216 不好意思，麻烦切换到 Console 那边

**Comment by michael19951216** [comment]
重裝插件
![2](https://cloud.githubusercontent.com/assets/23148302/19899815/c937adc4-a0a4-11e6-8e51-dc6e10fe5ac8.png)
添加编成
![3](https://cloud.githubusercontent.com/assets/23148302/19899816/c939267c-a0a4-11e6-8561-96d726557258.png)

**Comment by KagamiChan** [comment]
@michael19951216 请问一下每次添加都会在 Console 里出现新的红色的信息吗？还是说之后没有任何反应

**Comment by michael19951216** [comment]
每按一次左邊的數字都會增加..
![2](https://cloud.githubusercontent.com/assets/23148302/19900279/507bed8a-a0a6-11e6-9ac5-b4071ef61fb1.png)

**Comment by KagamiChan** [comment]
因为我这边没有办法复现这个问题，所以可能还需要多一点的信息
具体一点的话，这是在进行编成记录的哪一个细的动作时候会出现？
还有，你有没有安装别的插件比如航海日志，战斗记录和耗资记录，它们都能够正常地显示数据吗？

**Comment by ruiii** [comment]
@michael19951216 编成日记属于老插件 不支持热启动 麻烦安装插件之后 重启 poi 再进行添加操作

**Comment by michael19951216** [comment]
@ruiii 呃 還是出現同樣的問題+錯誤信息

**Comment by michael19951216** [comment]
@KagamiChan 其他插件沒問題 唯獨是编成日記無法進行增加編成的操作..

**Comment by michael19951216** [comment]
算了 我還是不使用编成日記就好了.. 不好意思打擾你們了= =
