### ISSUE TITLE
艦娘名字顯示不全

### ISSUE THREAD

**Issue by l12436** [poooi/poi#1252]
**poi 版本 / poi version:**
7.2.0 beta.2

**操作系统 / OS:**
Ubuntu 16.04

**插件名和版本 / Plugin name & version:**
*(如果这是一个关于插件的 issue / If its a issue about plugin)*

**详细描述 / Details:**
*(建议提供开发者工具的截图 / A screenshot of developer tools would be better)*

艦娘的名字顯示不完全，艦隊裡面的基本上也顯示不完全。

![image](https://cloud.githubusercontent.com/assets/2596649/20003702/f37d4046-a255-11e6-958d-88159e4cd194.png)
![image](https://cloud.githubusercontent.com/assets/2596649/20003715/fd43f3cc-a255-11e6-86b4-958dea4eb16d.png)

**Comment by yukixz** [comment]
@l12436 拉宽点

**Comment by KagamiChan** [comment]
宽度低的时候是会变成 ellipsis，比如 #958 里面的情况

**Comment by l12436** [comment]
再寬就超過我的畫面了，所以是遊戲畫面太大了就是

**Comment by KagamiChan** [comment]
这种情况可以在显示设置里面对游戏界面大小进行调节

**Comment by l12436** [comment]
我是覺得如果真的不夠寬，滑鼠移上去的時候可以popup一個小畫面顯示全名。就跟瀏覽那裡顯示經驗一樣

**Comment by KagamiChan** [comment]
如果你是开启了分辨率随窗口大小自动调整，可以尝试将窗口的高度调低

**Comment by l12436** [comment]
我有調整了，確實是因為右邊不夠寬，不過希望可以再有彈出氣球上面顯示全名的功能

**Comment by KagamiChan** [comment]
目前滑鼠悬浮状态下已经有经验值和装备的显示了，再加的话感觉有点过于密集。

**Comment by Kitami** [comment]
其实名字显示在等级和舰种的后面就好了

**Comment by c933103** [comment]
可以自行改變字體嗎？例如說這個 http://forest.watch.impress.co.jp/library/software/hankakufont/
