### ISSUE TITLE
几个影响体验的小问题。

### ISSUE THREAD

**Issue by lainstein** [poooi/poi#1255]
**poi 版本 / poi version:**
7.10
**操作系统 / OS:**
win8.1
**插件名和版本 / Plugin name & version:**
*(如果这是一个关于插件的 issue / If this is an issue about plugin)*

**详细描述 / Details:**
*(建议提供开发者工具 Console 选项卡的截图 / A screenshot of developer tool console tab is welcome)*
亲爱的开发团队：
       感谢你们的辛勤劳动！
       使用poi已经有一年了，这是本人感觉目前最好用的舰娘浏览器。近日发现了一些问题，特来反馈。
       1.每次打开poi，窗口不会自动最大化。
       2.连续打开了两个poi，结果都没法正常关闭，点了x只是关掉窗口，桌面右下角和进程里还有，只能强行结束，希望能添加一个只允许一个poi运行的设置。
       3.右下任务栏图标，右键菜单-poi子菜单，鼠标移至子菜单上，子菜单即消失，必须在“poi”处单击一次才不会消失。
以上，再次感谢。

**Comment by KochiyaOcean** [comment]
@lainstein 第三个问题是上游的 bug，自从 2015 年以来从未修复

**Comment by KagamiChan** [comment]
关于第一个问题，poi 会在退出的时候在配置文件中记录窗口是否最大化，从你的说法来看，可能是 poi 没有能够正常完成退出过程

第二个问题，目前 poi 本身并不支持多开

**Comment by nsmvykonqd** [comment]
每次退出时 config.cson 的 isMaximized 都会重置为 false

poi 版本 / poi version:
7.10
操作系统 / OS:
win10

**Comment by KagamiChan** [comment]
@nsmvykonqd 请问在 7.2.0 beta3 上也是这样吗

**Comment by KagamiChan** [comment]
在我这边的 windows 10 上得到了确认，同时 linux 上不会有这样的问题

**Comment by KagamiChan** [comment]
597b832 应该能将无法记忆最大化的问题修复了，下一个新版本还有问题的话请反馈
