### ISSUE TITLE
无法加载Flash

### ISSUE THREAD

**Issue by dynos01** [poooi/poi#1256]
**poi 版本 / poi version:**
7.1.0
**操作系统 / OS:**
Arch Linux
**插件名和版本 / Plugin name & version:**
*(如果这是一个关于插件的 issue / If this is an issue about plugin)*

**详细描述 / Details:**
*(建议提供开发者工具 Console 选项卡的截图 / A screenshot of developer tool console tab is welcome)*

Arch Linux系统，使用7.1.0以上的poi就无法加载游戏，报插件过期。系统中同时安装有stable版本的Chrome

**Comment by KagamiChan** [comment]
不知道你是不是使用的 pacman 包，目测是和 #1245 #1223 一样的权限错误？
如果用独立版本 poi-7.\*,\*-linux-x64.7z 的话，是不是就能够运行？

**Comment by dynos01** [comment]
是的，pacman包。还未尝试7z包，一会试试

**Comment by KochiyaOcean** [comment]
https://github.com/electron-userland/electron-builder/issues/786 和这个 issue 相关，需要等待上游修复……

**Comment by dynos01** [comment]
那么在新版本的初次启动界面中加入提示吧，希望能减少因此受影响的用户
