### ISSUE TITLE
移动指针时画面发生闪烁

### ISSUE THREAD

**Issue by ShiinaGensho** [poooi/poi#1259]
在远征选择、舰娘选择等界面时移动指针会导致画面闪烁，这个问题从6.几一直存在，7.1正式版也存在这个问题，目前版本是7.2.0beta3
系统版本：Windows10 14959 x64

屏幕录制：
[poi 2016_11_12 12_43_56.zip](https://github.com/poooi/poi/files/587054/poi.2016_11_12.12_43_56.zip)

**Comment by KochiyaOcean** [comment]
@ShiinaGensho 总而言之先开 / 关下硬件加速？

**Comment by ShiinaGensho** [comment]
开关硬件加速均存在这个问题

**Comment by KochiyaOcean** [comment]
@ShiinaGensho 看起来像是 chromiumlibconcent 的问题，我回去后看看…

**Comment by ShiinaGensho** [comment]
勾选“禁用硬件加速”后重启poi
[poi 2016_11_12 12_56_53.zip](https://github.com/poooi/poi/files/587057/poi.2016_11_12.12_56_53.zip)

取消勾选“禁用硬件加速”后重启poi
[poi 2016_11_12 12_58_00.zip](https://github.com/poooi/poi/files/587059/poi.2016_11_12.12_58_00.zip)

**Comment by KochiyaOcean** [comment]
是否有触摸屏？

**Comment by ShiinaGensho** [comment]
无触摸屏，有数位板

**Comment by KochiyaOcean** [comment]
@ShiinaGensho 那就不是很清楚什么情况了……

**Comment by ShiinaGensho** [comment]
数位板可作为触控板使用，是否与wacom驱动有关？

**Comment by KochiyaOcean** [comment]
@ShiinaGensho 拔掉看看？

**Comment by ShiinaGensho** [comment]
问题仍存在

**Comment by KochiyaOcean** [comment]
@ShiinaGensho chrome 上没有这个问题么

**Comment by ShiinaGensho** [comment]
chrome上没有问题

**Comment by wwftherocksp** [comment]
我也是这样，依稀记得差不多是Synergy升级之后才出的问题一直没在意

**Comment by gnattu** [comment]
使用Electron 1.3.9运行poi时无此问题
使用Electron 1.4.7时此bug出现
Electron作者既然把1.3.9作为最新稳定版，是不是不要那么激进比较好

**Comment by KochiyaOcean** [comment]
@gnattu electron 并没有稳定版的概念，1.3.9 只是原则性的修复本次要版本和上一个次要版本的 bug 而已

**Comment by KochiyaOcean** [comment]
@gnattu 以及由于怀疑这可能是 Chrome53（electron 1.4.x 的上游版本）的问题，麻烦尝试一下用 Chrome 插件的形式安装 https://github.com/KochiyaOcean/chrome-webview-bug 看看能否在 54 上重现？

**Comment by Artoria-0x04** [comment]
相关bug,
[electron#7655](https://github.com/electron/electron/issues/7655)

似乎跟HiDpi也有关，缩放调整至100%也可能临时解决问题。

**Comment by gnattu** [comment]
@KochiyaOcean 已测试，Chrome使用webview无此问题

**Comment by KochiyaOcean** [comment]
@gnattu Chrome 54 没有问题的话等 Electron 1.5.0 修复吧……

**Comment by maomaohenmao** [comment]
关于该问题，其实非常影响用户体验，光标闪烁实际上会影响拖动操作以及在使用舰娘选择装备类型时，一旦闪烁就会关闭装备类型菜单。请重视，谢谢！

**Comment by KochiyaOcean** [comment]
@maomaohenmao 基本确定是 Chrome 53 的 bug，等待上游修复

**Comment by ilikecola** [comment]
但是在chrome下没有这个问题。。。。

**Comment by KochiyaOcean** [comment]
@ilikecola Chrome 的稳定版已经是 55 了（Electron 仍然是 53）而且出 bug 的并非渲染本体而是一个叫做 webview 的组件，平常的使用 Chrome 访问网站的话是用不到这个组件的

**Comment by ilikecola** [comment]
大概何时会更新（= =），因为闪烁会影响到任何drag响应。。。

**Comment by KochiyaOcean** [comment]
@ilikecola 如果有自己替换 Electron 的能力的话可以去下载 1.3.x 版的 Electron (Chrome 52)，至于新版的 Electron…… 我们也在等啊……

**Comment by ilikecola** [comment]
明天试试。。。electron完全不懂。。不过还是辛苦了，谢谢！

**Comment by KochiyaOcean** [comment]
@ilikecola 最简单的方法是去 https://github.com/electron/electron/releases 下载之后双击 electron.exe 然后把 poi 里的 resource/app.asar 拖进去（不要更改 poi 目录结构

**Comment by ilikecola** [comment]
了解。。。谢谢！！

**Comment by KagamiChan** [comment]
@gnattu 请问在使用 poi 的 github 开发版吗？今天我重新看了一下关联的 issue，加了一个修复，在我这里测试是有效果。如果方便的话请帮忙用 electron 1.4.x 测一下 master 分支

**Comment by gnattu** [comment]
@KagamiChan 已测试，问题没有出现. 使用Electron 1.4.13

**Comment by KagamiChan** [comment]
@gnattu 多谢多谢～
