### ISSUE TITLE
最近打開poi登入後就被貓

### ISSUE THREAD

**Issue by KuRoic** [poooi/poi#1260]
**poi 版本 / poi version:**7.2.0 beta.3

**操作系统 / OS:**Win10

**插件名和版本 / Plugin name & version:**
*(如果这是一个关于插件的 issue / If this is an issue about plugin)*

**详细描述 / Details:**你好 從7.1.0後 每次一打開poi 按下登入鍵後就會馬上被貓 
清過快取 清過cookie 甚至改了時區 仍舊無法遊玩 
當7.2.0推出之後 我將它下載下來 剛裝完還是正常的 但隔天再打開又被貓了 
我只好使用google瀏覽器遊玩 不過沒有提示 很常忘記自己在幹嘛
不知道這是不是我自己的問題 還是瀏覽器的問題 希望可以早日繼續使用poi 這是我用過最好用的艦娘專用瀏覽器了*(建议提供开发者工具 Console 选项卡的截图 / A screenshot of developer tool console tab is welcome)*

**Comment by KochiyaOcean** [comment]
@KuRoic 缓存错误，在设置中清除缓存

**Comment by KagamiChan** [comment]
@KuRoic 有没有试过校准系统时间啊，有时候时间不对也会猫

**Comment by KuRoic** [comment]
都有 但是沒有甚麼作用 剛剛又重新安裝了一次7.2.0 不會被貓了 也許是7.1.0的關係?

**Comment by KuRoic** [comment]
對了 雖說與本問題無關 但是在使用OBS時 無法擷取到POI的視窗 這是正常的嗎?

**Comment by KochiyaOcean** [comment]
@KuRoic 设置里关闭硬件加速

**Comment by hyq77766177** [comment]
@KuRoic poi 删除缓存 1. 在 poi 左下角工具栏中，点击闪电图标打开自定义缓存目录，清空该目录 2. 在 poi 设置中点击「删除缓存」3. 请检查代理软件的缓存设置
不知是不是这么做的？

**Comment by KuRoic** [comment]
OK了 謝謝各位
