### ISSUE TITLE
艦娘信息視窗無法顯示

### ISSUE THREAD

**Issue by KenLiu2** [poooi/poi#1262]
**poi 版本 / poi version:**
7.2.1
**操作系统 / OS:**
Windows8.1 (安裝於蘋果筆記本)
**插件名和版本 / Plugin name & version:**
*(如果这是一个关于插件的 issue / If this is an issue about plugin)*
艦娘信息 1.10.0
**详细描述 / Details:**
*(建议提供开发者工具 Console 选项卡的截图 / A screenshot of developer tool console tab is welcome)*
雖然現在正在維護 還是描述一下情況...
打開艦娘信息時 視窗跳不出來
但是桌面最下方的工作列顯示是有新視窗的
鼠標移到工作列上 進行視窗預覽時 看得到艦娘信息的視窗
但是點了以後卻又跳不出來
就像是有個透明的艦娘信息視窗一樣 無法顯示
插件也去目錄刪過重裝 無法解決問題
不曉得是我的電腦 還是插件的問題
麻煩你們了 謝謝

**Comment by KagamiChan** [comment]
请问别的需要打开新窗口的插件会有这样的现象吗，还是说只是舰娘信息插件会

**Comment by yukixz** [comment]
之前是否双屏、然后现在拔掉了一个？

**Comment by KenLiu2** [comment]
只有艦娘信息會 其他都沒問題

**Comment by KagamiChan** [comment]
@KenLiu2 是不是和 yuki 说的一样之前用的是双屏？
可以试试打开开发者工具，在 console 里面输入
```javascript
config.set('plugin.ShipInfo.bounds')
```
开发者工具可以通过游戏画面下方的信息栏的最左边的按钮打开

**Comment by KenLiu2** [comment]
請問雙屏還有拔掉一個指的是什麼?
不太瞭解意思...

**Comment by KagamiChan** [comment]
@KenLiu2 就是问你原来是不是有两个显示器，然后现在只用了一个

**Comment by KenLiu2** [comment]
這倒是沒有
剛才在開發者工具輸入了那串
顯示undefined
然後突然能用了.........
看起來是修好了

**Comment by KenLiu2** [comment]
不好意思麻煩你們了
祝各位活動順利
謝謝

**Comment by KagamiChan** [comment]
嗯，这可能是插件记忆的窗口坐标有问题所以超出显示屏范围了……
