### ISSUE TITLE
加入Homebrew cask

### ISSUE THREAD

**Issue by darg20127** [poooi/poi#1263]
習慣用brew cask安裝app，如果poi也能加入我會很感激的。

我已經寫好了brew的腳本，如果各位允許我就送request給homebrew順便維護了。

**Comment by KochiyaOcean** [comment]
好呀好呀

**Comment by yukixz** [comment]
脚本发出来看一下？

**Comment by darg20127** [comment]
cask 'poi' do
  version '7.2.1'
  sha256 '4dffcb2790d22c2769f60f8615eff9421bc44320ed759ddd2458c46f6c716466'

  url "https://github.com/poooi/poi/releases/download/v#{version}/poi-#{version}-macos-x64.dmg"
  name 'poi'
  homepage 'https://github.com/poooi/poi'

  app 'poi.app'
end

**Comment by yukixz** [comment]
😂原来这么简单

**Comment by darg20127** [comment]
哈哈 照著homebrew規則走就是了。

**Comment by KochiyaOcean** [comment]
@darg20127 homepage 改成 poi.io 比较好大概？

**Comment by darg20127** [comment]
＠KochiyaOcean 恩，好的

**Comment by darg20127** [comment]
謝謝各位，Homebrew-cask 也接受了 [homebrew-cask/pull/26909](https://github.com/caskroom/homebrew-cask/pull/26909)
現在可以用
``` shell
brew cask update && brew cask install poi 
```
來安裝

關閉issue了

**Comment by dkwingsmt** [comment]
poi 每次发布一个新版本都得手动去 push 一个最新版 version 是么

**Comment by darg20127** [comment]
目前是這樣，不過brew cask有在準備實現brew cask upgrade這樣的指令。

在這之前我就辛苦點XD

**Comment by dkwingsmt** [comment]
真是非常感谢~
