### ISSUE TITLE
poi开启后卡住

### ISSUE THREAD

**Issue by AutumnPie** [poooi/poi#1264]
**poi 版本 / poi version:**
7.2.1
**操作系统 / OS:**
Windows10 x64
**插件名和版本 / Plugin name & version:**
*(如果这是一个关于插件的 issue / If this is an issue about plugin)*

**详细描述 / Details:**
*(建议提供开发者工具 Console 选项卡的截图 / A screenshot of developer tool console tab is welcome)*
开启后卡在“poi等待游戏数据中”，并且有如图所示的报错：
![1](https://cloud.githubusercontent.com/assets/23611408/20461905/c3ca5788-af04-11e6-8f84-96158d336f86.png)
![2](https://cloud.githubusercontent.com/assets/23611408/20461906/c5d9dc92-af04-11e6-9dbd-b424af8dabd5.png)

**Comment by KochiyaOcean** [comment]
确定是 7.2.1 而非 7.2.0?
如果确定是 7.2.1, 你使用的平台是？

**Comment by KagamiChan** [comment]
麻烦试一下在关掉 poi 的情况下，打开 %appdata%/poi，并删掉其中的 plugins 和 Local Storage 两个文件夹，之后再启动 poi
如果启动正常的话，可能需要再重新安装插件

**Comment by AutumnPie** [comment]
确实是7.2.1，平台是我win10 64

**Comment by AutumnPie** [comment]
这个问题是昨天在活动过程中猫了一次刷新之后出现的。

**Comment by AutumnPie** [comment]
十分感谢，已经解决问题了！

**Comment by KochiyaOcean** [comment]
大概有处理损坏包数据的必要……
