### ISSUE TITLE
Kcwiki语音字幕显示不能（手动删除插件文件夹并重启也无效）

### ISSUE THREAD

**Issue by CLELOUCHC** [poooi/poi#1266]
**poi 版本 / poi version:**
从poi-7.0.1-win-x64到poi-7.2.1-win-x64

**操作系统 / OS:**
WIN10专业版

**插件名和版本 / Plugin name & version:**
*(如果这是一个关于插件的 issue / If this is an issue about plugin)*
Kcwiki语音字幕

**你遇到了什么样的问题 / The problem you've met:**
在一次正常游玩时意外停电，恢复电力后。使用POI时Kcwiki语音字幕不能正常显示字幕。不论是插件控制面板删除该插件或者手动在文件夹删除插件，并重启均无效。
之后等待新版本并且把旧版本完全手动删除（包括所有插件），再安装新版本，也无效。
后来到现在版本，发现在领取任务界面大淀语音和开始游戏语音有字幕。其他均没有

**有没有重现的方法，或者与问题相关的任何信息 / The way to reproduce, or any information that might be related:**
*(可以的话请提供开发者工具 Console 选项卡的截图 / Please provide a screenshot of developer tool's console tab, if possible)*
![image](https://cloud.githubusercontent.com/assets/23616063/20464181/f1b2a636-af7d-11e6-97d7-4e4329fe63b8.png)
![image](https://cloud.githubusercontent.com/assets/23616063/20464183/fc7c333e-af7d-11e6-8d74-9b9f07fa5843.png)

**Comment by KochiyaOcean** [comment]
删除 `%appdata%/poi/local storage` 试试看

**Comment by KagamiChan** [comment]
字幕文件资源是放在 %appdata%/poi/poi-plugin-subtitle 文件夹的，可以卸载掉字幕插件后删除这个文件夹再安装试试看

**Comment by grzhan** [comment]
以及可以的话，麻烦把 `%appdata%/poi/poi-plugin-subtitle` 的文件夹压缩打包作为附件邮件发给我（envy518@gmail.com），我希望在本地复现一下以排除 bug 。

**Comment by CLELOUCHC** [comment]
删除了字幕文件（%appdata%/poi/poi-plugin-subtitle文件夹）以及字幕插件后。运行POI重装字幕插件。马上正常了。![image](https://cloud.githubusercontent.com/assets/23616063/20473602/c963d8ec-affc-11e6-9ec5-660e578420f6.png)
但为什么我之前都是把整个POI文件夹都删除然后再装新版本，又不行呢？

**Comment by Divinity123** [comment]
我遇到了相同的问题
在index.cjsx第100行之后加了一行url输出（通过alert）以后神奇地解决了问题
故此推测bug为无法正确通过url获取api
