### ISSUE TITLE
12 vs 12

### ISSUE THREAD

**Issue by wafer-li** [poooi/poi#1267]
**poi 版本 / poi version:**
bfd68dd79798b276fcedbb3ffe8a5ca2e1658044

**操作系统 / OS:**
OSX 10.11.6

E3 出现了 12 vs 12。
希望尽快支持。

**Comment by yukixz** [comment]
@wafer-li 请暂时用战斗记录插件代替未卜先吃插件。

**Comment by wafer-li** [comment]
😂 发现忘记更新了。
