### ISSUE TITLE
航海日誌資源無法顯示圖表

### ISSUE THREAD

**Issue by Vik1n9** [poooi/poi#1269]
**poi 版本 / poi version:**
Ver 7.2.1

**操作系统 / OS:**
Win10 

**插件名和版本 / Plugin name & version:**
*(如果这是一个关于插件的 issue / If this is an issue about plugin)*
航海日誌 Ver 5.0.6

**你遇到了什么样的问题 / The problem you've met:**
昨天勾選了擴展程式中的beta選項，今天在更新了航海日誌之後，發現資源頁籤上原本可以正常顯示的曲線圖現在無法正常顯示。嘗試移除航海日誌後重新安裝，無法改善，取消beta更新後重新安裝航海日誌耶樣無法改善。在資料全數匯出之後，嘗試刪除數據，找不到數據存放的正確位置，失敗。

**有没有重现的方法，或者与问题相关的任何信息 / The way to reproduce, or any information that might be related:**
*(可以的话请提供开发者工具 Console 选项卡的截图 / Please provide a screenshot of developer tool's console tab, if possible)*

![1](https://cloud.githubusercontent.com/assets/23635680/20485730/437905ce-b040-11e6-8c29-0bf7d5e80304.jpg)
![2](https://cloud.githubusercontent.com/assets/23635680/20485737/4b29eb94-b040-11e6-9945-0dbf06b7aa45.jpg)

還需要其他的信息請和我說。

**Comment by Vik1n9** [comment]
回報，今天找到了航海日誌的資料存點，於是將航海日誌移除，並且刪除紀錄等資訊後重開POI，然後重新安裝最新版的航海日誌，並將記錄匯入，然並卯月。

**Comment by JenningsWu** [comment]
@Vik1n9 Console 的截图有点模糊，看不清。不知是否可以重新截一个？（并把 tab 那里切到 Console）
另外，如果可以的话，能否把数据文件夹下的 resource 打包发我，我看看是不是数据格式出了错

**Comment by Vik1n9** [comment]
![1](https://cloud.githubusercontent.com/assets/23635680/20523277/9f13ca42-b0f7-11e6-8827-96e57874f84a.png)

[resource.zip](https://github.com/poooi/poi/files/606257/resource.zip)

不知道這些是不是你要的，如果不是請再告訴我。

P.S. console裡面有些錯誤資訊可能是因為我有使用HD的快取資料的關係。

**Comment by Vik1n9** [comment]
回報

剛剛發現了有趣的情況，請讓我用圖來說明。
![1](https://cloud.githubusercontent.com/assets/23635680/20525186/a43af9e6-b101-11e6-8655-0ead9458975a.png)
這是直接打開航海日誌的畫面，如各位所見是一片空白。

![2](https://cloud.githubusercontent.com/assets/23635680/20525209/bf4a98fe-b101-11e6-95dd-f25cae871062.png)
然後下方的日期區間稍微拉動一下之後

![3](https://cloud.githubusercontent.com/assets/23635680/20525234/d8581c68-b101-11e6-8a42-5dc1c15898ce.png)
神奇的圖表竟然出現了！但仔細一看圖表上的資料和X軸上的時間不吻合。

![4](https://cloud.githubusercontent.com/assets/23635680/20525280/fc85a1be-b101-11e6-8106-33f8eeae4266.png)
然後再把區間往前調整，剛剛無法顯示的區間也能出現圖表了(儘管時間不正確)，但是拉到底之後又回到圖一的一片空白了。

以上是剛剛的發現。

**Comment by JenningsWu** [comment]
@Vik1n9 抱歉，前两天有点忙。
感谢汇报，我这边用了你的 resource 文件之后能够重现。
这几天看一下这个问题（如果不急的话我先去打个秋活 0v0

**Comment by Vik1n9** [comment]
@JenningsWu 你客氣了，現在這時間大家都在"忙"吧？希望下個版本可以修正就行了。祝你武運昌隆。

**Comment by yukixz** [comment]
@Vik1n9 不用担心、这吴钩老师还没开始打 E0

**Comment by Vik1n9** [comment]
看紀錄就知道，我是新米提督啊..活動前幾天才剛接觸這遊戲，秋活根本不太會XD，目前也才過E1丙 HAHA

**Comment by KagamiChan** [comment]
这个，看起来，应该解决了吧
