### ISSUE TITLE
发现poi后台进程很多，是必须的么

### ISSUE THREAD

**Issue by kaneyukikaze** [poooi/poi#1270]
**poi 版本 / poi version:**
7.2.1

**操作系统 / OS:**
win10 64

**插件名和版本 / Plugin name & version:**
*(如果这是一个关于插件的 issue / If this is an issue about plugin)*

**你遇到了什么样的问题 / The problem you've met:**
发现poi后台进程很多，是必须的么

**有没有重现的方法，或者与问题相关的任何信息 / The way to reproduce, or any information that might be related:**
*(可以的话请提供开发者工具 Console 选项卡的截图 / Please provide a screenshot of developer tool's console tab, if possible)*

![qq 20161122112128](https://cloud.githubusercontent.com/assets/20235499/20508618/2734cb3a-b0a6-11e6-9fc0-632a30988430.jpg)

**Comment by KochiyaOcean** [comment]
@kaneyukikaze 因为是 Chrome 内核所以进程多很正常啊…… 内存总消耗量在 1G 左右算正常情况

**Comment by dkwingsmt** [comment]
@kaneyukikaze 是正常的。每个新窗口插件单独一个进程，本体是两个进程。

**Comment by kaneyukikaze** [comment]
一个插件一个进程，好吧。。
