### ISSUE TITLE
频繁更新数据的处理方案

### ISSUE THREAD

**Issue by yukixz** [poooi/poi#1271]
鉴于存在一部分「属于游戏数据、但目前只能由开发者手动更新」的频繁更新数据（FCD），且这些数据都分散在 poi 本体和各个插件上，给数据维护造成了一定不便。
因此我希望通过此方案实现：
1. 更新插件即可更新数据，而无需更新 poi 本体
2. 统一此类数据的储存，随手更新（想到更新贴条就要 clone 舰娘信息插件我就不想动了）

## 实现方案
数据储存到 FCD 插件中，暂定为 poi-plugin-fcd。poi 在依赖中添加该插件最新版本（自带），同时在插件安装列表添加该插件（插件）。  
poi 本体读取自带的 FCD 和插件中的 FCD，比对版本信息。然后将较新的数据添加到 store 中。
插件通过 store 直接使用，无需自己处理读取。

### 用户不一定会安装此插件

每次 poi 更新都会包含此插件的最新版本（poi/node_modules），即使用户没有安装插件（plugins/node_modules）也能获得该版本发布时的 FCD。

### 哪些数据要放到 FCD 插件中，判断标准是什么？

很重要！对于把数据放到 FCD 的的操作一定要谨慎！

一般而言、用户对于插件的想法是「哪个插件坏了，那我更新他应该就会好」，而不会想到去更新另一个插件。所以如果数据放到 FCD 会增加用户的认知成本，也会增加我们的客服成本。

我认为，以下数据不适合放到 FCD 插件：
1. 该数据即该插件的核心功能，如装备改修插件。

满足以下条件的数据可以考虑放到 FCD 插件：
1. 是游戏数据，但只能由开发者手动更新
2. 有两个或以上插件（含本体）使用的数据

### 目前有什么数据适合放到 FCD 插件？
活动锁船信息、海域地图（mapspot、maproute）

**Comment by yukixz** [comment]
不小心点到 submit，容我慢慢写

**Comment by yukixz** [comment]
@dkwingsmt 如果实现的话，放在 store 哪里比较好？
我是希望放在 store.const （不过不懂 redux 似乎不好实现？（=x=

**Comment by dkwingsmt** [comment]
倒没有不好实现。const是可以的，只是现在const的定位是$系列，即“start2给的原包”。虽然你这部分也确实是constants，要扩展下const的定位也没有问题。
技术上来说我觉得应该没有限制，放在const、直接放到ext里甚至单独放个根路径应该都没有问题。
唯一注意的点就是可以考虑在本体utils/selectors里面导出改路径的selector，这样以后想要更改路径也非常方便。

**Comment by KochiyaOcean** [comment]
我是觉得单独拖出来比较好，避免 const 被炸的可能性……

**Comment by dkwingsmt** [comment]
怕炸那最简单的方式就还是是丢 ext

**Comment by yukixz** [comment]
@dkwingsmt poi 处理的数据塞 ext 感觉有点微妙

**Comment by dkwingsmt** [comment]
我觉得问题不是特别大，当初把这个地方命名为 extension 而不是 plugin 的原因就是~~~已经有 plugins 用作插件中心了~~~不仅仅是用来给插件的，还可能用来给别的目的。而且讲道理你主贴里面都说了这个库的名字叫 poi-__plugin__-fcd （虽然其实我想说可以换个分类）

**Comment by yukixz** [comment]
@dkwingsmt 叫 poi-plugin-fcd 是因为目前 poi 只处理 poi-plugin 开头的插件呀。
要是支持其他的我就叫 poi-core-fcd嗯🙈

**Comment by yukixz** [comment]
更新：包名可以叫 poi-core-fcd，然后在插件列表中添加 poi-core-*

**Comment by yukixz** [comment]
一个致命问题、FCD 插件更新后如何通知所有窗口重新加载数据？

**Comment by KochiyaOcean** [comment]
@yukixz 如果是 redux 的话就很方便了

**Comment by yukixz** [comment]
@KochiyaOcean redux 是所有新窗口插件共享一个 store？

**Comment by KochiyaOcean** [comment]
@yukixz 大意了，妹想到！

**Comment by KagamiChan** [comment]
海域斩杀线

**Comment by yukixz** [comment]
@KagamiChan 斩杀提醒好像是海域血量发出的

**Comment by KagamiChan** [comment]
@yukixz https://github.com/poooi/poi/blob/master/views/components/info/map-reminder.es#L97

**Comment by yukixz** [comment]
抛弃使用 npm 插件机制的方案。
采用维护多个 json 到 cdn，通过 env 代码下载插入 store 的方案。

1. 需要维护 meta.json，保存 json 的版本、下载路径和 store 路径。
2. json 需要预处理为 store 的格式，即 env 读取后直接插入 store 不做任何处理。
