### ISSUE TITLE
未卜先知插件的問題

### ISSUE THREAD

**Issue by YuuXuan** [poooi/poi#1272]
**poi 版本 / poi version:**
Ver. 7.2.1

**操作系统 / OS:**
Win8.1 64x

**插件名和版本 / Plugin name & version:**
*(如果这是一个关于插件的 issue / If this is an issue about plugin)*
未卜先知 Ver. 5.4.0

**你遇到了什么样的问题 / The problem you've met:**
為了斬E4乙紅血而派了雙砲擊支援，但未卜先知似乎沒有讀到王點支援的資訊
附圖：戰鬥中全畫面、回港後調出的戰鬥紀錄（Ver. 3.3.2）

![default](https://cloud.githubusercontent.com/assets/24191178/20641185/54cfdc8a-b42d-11e6-8b57-7b50dc43d238.png)

![download](https://cloud.githubusercontent.com/assets/24191178/20641183/48eb7352-b42d-11e6-9d12-a211cb3539e3.png)

**有没有重现的方法，或者与问题相关的任何信息 / The way to reproduce, or any information that might be related:**
*(可以的话请提供开发者工具 Console 选项卡的截图 / Please provide a screenshot of developer tool's console tab, if possible)*

**Comment by yukixz** [comment]
未卜先吃支持深海联合舰队的测试版已经发布，我们会尽快发布正式版。
