### ISSUE TITLE
黑屏

### ISSUE THREAD

**Issue by hyw19940325** [poooi/poi#1274]
**poi 版本 / poi version:**

7.2.1
**操作系统 / OS:**
win 10
**插件名和版本 / Plugin name & version:**
*(如果这是一个关于插件的 issue / If this is an issue about plugin)*

**你遇到了什么样的问题 / The problem you've met:**
 打开后一直这样

![image](https://cloud.githubusercontent.com/assets/24352802/20859839/6577e9c4-b9a5-11e6-8544-e132d7badf32.png)

**有没有重现的方法，或者与问题相关的任何信息 / The way to reproduce, or any information that might be related:**
*(可以的话请提供开发者工具 Console 选项卡的截图 / Please provide a screenshot of developer tool's console tab, if possible)*
![image](https://cloud.githubusercontent.com/assets/24352802/20859832/4e730466-b9a5-11e6-9d18-3b15939a3610.png)

**Comment by KagamiChan** [comment]
如果我的打开放式没问题的话，这个截图看不清啊……

**Comment by KagamiChan** [comment]
duplicated with #1276
