### ISSUE TITLE
黑屏

### ISSUE THREAD

**Issue by hyw19940325** [poooi/poi#1276]
**poi 版本 / poi version:**
7.2.1

**操作系统 / OS:**
WIN10

**插件名和版本 / Plugin name & version:**
*(如果这是一个关于插件的 issue / If this is an issue about plugin)*

**你遇到了什么样的问题 / The problem you've met:**

打开后就一直这样 弄了半天都不行 
![image](https://cloud.githubusercontent.com/assets/24352802/20859849/92c01a78-b9a5-11e6-8d6d-eb8dfc3a1c0e.png)

**有没有重现的方法，或者与问题相关的任何信息 / The way to reproduce, or any information that might be related:**
*(可以的话请提供开发者工具 Console 选项卡的截图 / Please provide a screenshot of developer tool's console tab, if possible)*

![image](https://cloud.githubusercontent.com/assets/24352802/20859870/e5856eac-b9a5-11e6-9190-4a468579b19e.png)

**Comment by KochiyaOcean** [comment]
试着把 `%appdata%/poi/Local Storage` 删掉看看

**Comment by yukixz** [comment]
关闭 poi 再删除 local storage

**Comment by KagamiChan** [comment]
如果还是不行，把 `%appdata%/poi/plugins` 也删掉
