### ISSUE TITLE
黑屏！！！

### ISSUE THREAD

**Issue by hyw19940325** [poooi/poi#1278]
**poi 版本 / poi version:**

**操作系统 / OS:**

**插件名和版本 / Plugin name & version:**
*(如果这是一个关于插件的 issue / If this is an issue about plugin)*

**你遇到了什么样的问题 / The problem you've met:**
之前问过 按别人说的做了 也没用 重新下也没用
![image](https://cloud.githubusercontent.com/assets/24352802/20866927/f756f136-ba73-11e6-89ba-c5b135e19603.png)

![image](https://cloud.githubusercontent.com/assets/24352802/20866926/effc4756-ba73-11e6-8b85-96328bdd0560.png)

**有没有重现的方法，或者与问题相关的任何信息 / The way to reproduce, or any information that might be related:**
*(可以的话请提供开发者工具 Console 选项卡的截图 / Please provide a screenshot of developer tool's console tab, if possible)*

![image](https://cloud.githubusercontent.com/assets/24352802/20866938/1928378e-ba74-11e6-96cc-72fc65f1789c.png)

**Comment by yukixz** [comment]
@hyw19940325 关闭 poi 再删除 local storage

**Comment by KochiyaOcean** [comment]
话说能不能直接在同一个 issue 下回复啊……

**Comment by yukixz** [comment]
Dup #1276
