### ISSUE TITLE
战果计算器读取不准确.

### ISSUE THREAD

**Issue by coblade14** [poooi/poi#1279]
**poi 版本 / poi version:** poi v7.2.1

**操作系统 / OS:** windows 10

**插件名和版本 / Plugin name & version:** 我变强了 4.1.8

**你遇到了什么样的问题 / The problem you've met:**

战果计算器读取战果数值完全不准. 大概是实际值的2-3倍. 
![qq 20161205053832](https://cloud.githubusercontent.com/assets/3360053/20886951/5d3b1426-baad-11e6-9107-9017cc86c7d8.png)
第一名实际3154, 战果计算器显示6074.5. 其他顺位也都不准.

![2](https://cloud.githubusercontent.com/assets/3360053/20887116/2dace058-baae-11e6-8e22-4e209f1c927f.png)
点击"使用榜上的战果值"读取到基础战果值245.3点, 实际86点.

**有没有重现的方法，或者与问题相关的任何信息 / The way to reproduce, or any information that might be related:**

我以为和我设定的时区(UTC-8)有关. 但是换了日本(UTC+9)或者北京(UTC+8)时区都没有任何帮助.

试过删除插件然后从新下载, 读取战果还是一样.

**Comment by ruiii** [comment]
麻烦打开开发者工具，在 console 输入 window.getStore('info.basic.api_member_id')，把输出的那串数字发上来，我测下。。

**Comment by coblade14** [comment]
window.getStore('info.basic.api_member_id')
"14055370"

**Comment by ruiii** [comment]
呃 那啥 重启并重试过了吗

**Comment by coblade14** [comment]
额...这问题很久了... 自从api改过之后就一直这样=.=

**Comment by ruiii** [comment]
哎 上次更新也是 尾号（？）是 0 的用户计算结果总是不准。。4.1.9 发了 可以试试

**Comment by coblade14** [comment]
恩, 修好了. 现在正常了. 谢谢~

**Comment by ruiii** [comment]
猴（比心
