### ISSUE TITLE
没有勾选“检查beta版插件更新“但还是更新到了beta版

### ISSUE THREAD

**Issue by GaoSui** [poooi/poi#1280]
poi 版本 / poi version: 7.2.1

操作系统 / OS: OSX

插件名和版本 / Plugin name & version: 未卜先知

你遇到了什么样的问题 / The problem you've met:

没有勾选“检查beta版插件更新“但还是更新到了beta版。

<img width="452" alt="screen shot 2016-12-05 at 9 22 34 am" src="https://cloud.githubusercontent.com/assets/16461362/20895103/e9efbace-bacc-11e6-8efd-6f8f28842032.png">

**Comment by KochiyaOcean** [comment]
应该是 npm tag 推错了，是发布方的问题，和本体无关
cc @KagamiChan

**Comment by KagamiChan** [comment]
十分抱歉，推送时候的命令错了……
这个版本已经撤下了
