### ISSUE TITLE
黑屏

### ISSUE THREAD

**Issue by wafer-li** [poooi/poi#1285]
**poi 版本 / poi version:**
9a80e36b2518a15e7f92231fedabaf560c40c5a9

**操作系统 / OS:**
macOS 10.11.6

**你遇到了什么样的问题 / The problem you've met:**

![image](https://cloud.githubusercontent.com/assets/12459199/21047684/96c85786-be4e-11e6-8069-0139e340ff19.png)

**有没有重现的方法，或者与问题相关的任何信息 / The way to reproduce, or any information that might be related:**

![image](https://cloud.githubusercontent.com/assets/12459199/21047690/9f2b315a-be4e-11e6-8dbc-9e399bb9ffb9.png)

顺便一提之前改了一下 `package.json`，结果 `npm i` 下来的 electron 就一直是 1.4.11 了。。
用了一下 `npm cache clean` 好像也没什么用。

**Comment by KagamiChan** [comment]
@wafer-li 因为 fcd 的路径换了的原因。关闭 poi 删除 local storage 就好了

**Comment by wafer-li** [comment]
@KagamiChan 呃……请问具体是哪个目录呢？

windows 的我倒是知道…… 😂

**Comment by yukixz** [comment]
@wafer-li poi 数据目录：
* Windows: %APPDATA%/poi
* Mac: ~/Library/Application Support/poi
* Linux: ~/.config/poi

**Comment by wafer-li** [comment]
@yukixz 
希望加入到 WIKI 中，这样至少有一些人不需要再问这种小问题了。

**Comment by yukixz** [comment]
@wafer-li 🙈poi 群有个机器人小鳖会自动回复这些问题

**Comment by KagamiChan** [comment]
@wafer-li 嗯嗯嗯，wiki 是需要维护一下了，咕咕咕

**Comment by wafer-li** [comment]
@yukixz 
😂 但是怎么是你的号来回答这个问题啊？

不应该是类似这种账号的吗？
![image](https://cloud.githubusercontent.com/assets/12459199/21048235/90a23996-be51-11e6-9119-07b50ef68927.png)

**Comment by yukixz** [comment]
@wafer-li 妹有 github developer program 呀🙈

**Comment by wafer-li** [comment]
@yukixz 好吧 :sweat_smile:

**Comment by KagamiChan** [comment]
关于 electron 版本的问题，先 `npm rm electron` 再安装会不会就回去了？
npm 我不熟 - -

**Comment by wafer-li** [comment]
@KagamiChan 这个问题不大，1.4.11 主要解决了 #1234  的问题，如果能用的话我还是希望尽量用新版的。
