### ISSUE TITLE
[咕咕咕]喷气式飞机实装相关记录

### ISSUE THREAD

**Issue by KagamiChan** [poooi/poi#1286]
# 简要情报
+ 新增两种喷气式飞机：喷式景云改，橘花改，分类上均属于“噴式戦闘爆撃機”
+ 新增四种装备分类：
  + 噴式戦闘機
  + 噴式戦闘爆撃機
  + 噴式攻撃機
  + 噴式偵察機
+ 目前只能看到喷式战斗暴击机的图标，上有黄色喷字，喷式景云改与橘花改的飞机形状不同
+ 新增喷气式战斗爆击机的战斗机制

# 需要做的
- [ ] lib battle 适配
  - [x] lib battle 及战斗详情
  - [x] 本体 lib battle 适配
  - [ ] 未卜先吃 lib battle 适配
    - [x] 战斗
    - [ ] 基地防空（不清楚有没有
- [x] 图标
  - [x] 位图图标
  - [x] 矢量图标
- [x] 英语翻译
- [x] ne 式引擎图标（用于装备改修）
  - [x] 位图
  - [x] 矢量
# 并不清楚有没有，需要确认一下的
- [ ] 对空值公式
  - [x] 旧版公式考虑喷气机
- [ ] 索敌值公式

--------------------
未尽之处请补充

**Comment by KagamiChan** [comment]
@edwardaaaa 看样子又需要麻烦设计一些新图标了

**Comment by edwardaaaa** [comment]
KagamiChan 没问题,周末完成预定.

**Comment by gnattu** [comment]
未卜先<del>吃</del>知

**Comment by edwardaaaa** [comment]
@KagamiChan https://drive.google.com/file/d/0B-J-nq9cHXQxOUcxSUNwemxMa2s/view?usp=sharing

**Comment by KagamiChan** [comment]
@edwardaaaa 因为从 API 来看将有四种喷气式飞机的实装，并且对应舰战，舰攻，舰爆和舰侦，所以可以讨论一下计划和想法吗，后续有新飞机实装是否还增加一种颜色？
这样子的话，因为和游戏中的表示出现了差别，会不会给用户带来迷惑？

**Comment by edwardaaaa** [comment]
这次的喷气式战斗机位图图标是类似舰侦的黄色和水侦的青色所结合的感觉,和现有矢量图标的配色方案不同,故这次的喷气式战斗机的矢量图标采用了有别于原始色调的全新色彩-紫色,一方面是强化了新装备的辨识度,另一方面也是一个折中的方案.

不久的将来我会对目前2.0版本的矢量图标进行一定的修正和改进.当然如果有能人志士那是更好不过了

**Comment by KagamiChan** [comment]
过了这么久也没有人报未卜先知的 bug，那大概是没有 bug 了罢
