### ISSUE TITLE
黑屏

### ISSUE THREAD

**Issue by stella6678** [poooi/poi#1288]
**poi 版本 / poi version:**
v7.2.1

**操作系统 / OS:**
win8.1

**你遇到了什么样的问题 / The problem you've met:**
 黑屏 重启重装都试过了毫无反应

**有没有重现的方法，或者与问题相关的任何信息 / The way to reproduce, or any information that might be related:**
*(可以的话请提供开发者工具 Console 选项卡的截图 / Please provide a screenshot of developer tool's console tab, if possible)*

![qq 20161216152254](https://cloud.githubusercontent.com/assets/24601528/21253642/89c73b10-c3a3-11e6-90ba-975c2804d709.png)

**Comment by KagamiChan** [comment]
请问黑屏指的是游戏界面没有出现，还是整个 poi 的界面都没有出现？
用的是什么上网方式，代理吗？

**Comment by stella6678** [comment]
游戏界面 右边的各种插件都可以正常显示和点击 但是本该显示游戏画面的地方一直是黑屏 选择刷新页面很快的转一下就没反应了

上网用的acgpower的代理

**Comment by KagamiChan** [comment]
@stella6678 那建议你检查一下代理设置，比如在 poi 的地址栏里面输入 baidu.com 看看能不能访问，使用相同的设置能不能在 chrome 里面也登上，之类的

**Comment by a5040991** [comment]
能成功運行了 非常感謝你
