### ISSUE TITLE
7.3.0 changelog

### ISSUE THREAD

**Issue by KagamiChan** [poooi/poi#1289]
# poi v7.3.0

## 实时更新数据模块（FCD，Frequently Changing Data）
- 现在，一些经常更新的数据会被包含在一个名为 FCD 的专门的模块当中。
- 每次 poi 启动时会检查并更新 FCD。同时，每次 poi 的新版本都会包含最新 FCD 数据。
- 因此，从 7.3.0 起，在 poi 或插件未发布新版本的情况下，FCD 所包含的数据也能实时更新。
- 可以在 “设置 - 关于poi” 中查看 FCD 数据版本并手动检查更新。
- 当前包含在 FCD 模块中的数据有：
  - 地图数据
  - 活动锁船
  - 海域血量

## 功能
- 支持多海域的陆航信息更新。
- 支持以字母形式显示地图点。
- 喷气式飞机实装的相关支持。
- 支持 Flash 显示模式设置。
- 增加用于航空支援的不含熟练度与改修加成的制空值显示
- 在关于页面增加感谢组织

## 修正
- 修正了退避舰娘的表示，修正了空母退避情况下的制空值计算结果。
- 修正了小地图在地图数据不完整情况（如 16 年秋活 E5 解谜）下的显示。
- 修正了网络重连次数的设置。
- 修正了由 Electron 导致的音量开关、刷新按钮等有时会无效的问题。
- 修正了 Windows 平台高分辨率显示情况下的鼠标闪烁问题

### 未卜先知
- 代码重构与界面重新设计，支持 6v12 与 12v12 的显示。
- 支持基地防空结果的显示。
- 与本体一样，支持以字母形式显示地图点（本体 7.3.0 以上限定）。

### 任务信息
- 更新信息到最新。

### 装备改修
- 更新信息到最新。
- 支持显示 ne 式引擎作为改修所需材料。

### 经验计算
- 加入固定经验值计算模式。

### 战斗详情
- 支持喷气强袭
- 支持过滤浏览

### 泊地修理
- 修正了计时器显示与重置机制

------------------
## 7.3.0 正式版相对于 7.3.0-beta.1 的更新：
- 增加用于航空支援的不含熟练度与改修加成的制空值显示
- 修正了 Windows 平台高分辨率显示情况下的鼠标闪烁问题

**Comment by hyq77766177** [comment]
###任务信息
-更新到了最新信息（12.9）
###装备改修
-更新到了最新信息（12.9），添加了 NE 式引擎图标

**Comment by KagamiChan** [comment]
@yukixz 有空来写写战斗详情的改进

**Comment by yukixz** [comment]
支持喷气强袭
支持过滤浏览

**Comment by yukixz** [comment]
electron 是修复了所有与 remote 相关的 bug
比如音量按钮、刷新按钮（）一时想不起来、

**Comment by KagamiChan** [comment]
# poi v7.3.0

## FCD (Frequently Changing Data) Module
- frequent updated data are included in this module, including map, ship tagging and last dance HP
- every release of poi will contain a copy of FCD data, and poi will download the updates upon initialization
- FCD data can be updated without upgrading main poi version

## Functionalities
- airbase information update for multiple areas supported
- alphabetic map cell name supported 
- jet plane related functionalities
- Flash display mode settings

## Fixes
- Retreated ship display fixed, and AS formula fixed to take retreats into account
- mini map display fixed for map cells uncovered in map data
- network retry settings fixed
- occasionally `remote` exceptions (e.g. game audio switch) introduced by `Electron` fixed

**Comment by KagamiChan** [comment]
changelog updated
