### ISSUE TITLE
Air control terminology

### ISSUE THREAD

**Issue by Tsubakura** [poooi/poi#1290]
**poi 版本 / poi version:**
All

Hello everyone,

I want to state that the viewer is using the wrong air control terminology.
The current terminology order which was widely used till recently has the following order:
- Air Supremacy (AS+)
- Air Superiority (AS)
- Air Parity (AP)
- Air Inferiority (AI)
- Air Denial (AD)

However, it immediately came apparant to most historians that the last 2 terminologies are wrong and should be the following:
- Air Supremacy (AS+)
- Air Superiority (AS)
- Air Parity (AP)
- Air Denial (AD)
- Air Incapability (AI)

Source: https://en.wikipedia.org/wiki/Air_supremacy

As I am part of the english KC wikia, I have pushed the changes at our wikia, the en.kancolle.wiki and the KC3改 extension. Since I found out recently that this viewer also supports an english language, I was wondering whether you guys are willing to make this change as well, so that the english community are all on the same page.

Anyway, thanks for your time!

Best regards,

Tsubakura

**Comment by yukixz** [comment]
@Tsubakura Thanks for your state.
Wikia is used as ours translated reference and we followed its mistake. :(
We will fix it soon.

**Comment by KagamiChan** [comment]
Thank you for the information, fixed now. Btw I'm a frequent user of English kancolle wikia, you guys are doing a great job

**Comment by Tsubakura** [comment]
Haha thanks! 
Keep up the good job as well, we rely heavily on your information during events after all. :)
