### ISSUE TITLE
登陆界面显示服务器之后就会猫

### ISSUE THREAD

**Issue by ccen3020** [poooi/poi#1291]
**poi 版本 / poi version:**
7.2.1~7.3.0-beat0

**操作系统 / OS:**
Windows 10 10.0.14393

**你遇到了什么样的问题 / The problem you've met:**

在登陆界面显示服务器名称之后，会猫
每次都会出现
重启电脑，更换版本，清缓存和COOKIES，清空APPDATA数据，删掉POI重新装都没用
不过直接网页登陆没有问题
问题出现在某一次系统的FLASH崩溃之后，就这样了

**有没有重现的方法，或者与问题相关的任何信息 / The way to reproduce, or any information that might be related:**
*(可以的话请提供开发者工具 Console 选项卡的截图 / Please provide a screenshot of developer tool's console tab, if possible)*
![image](https://cloud.githubusercontent.com/assets/5616211/21389730/1c02bb9e-c7be-11e6-992d-b8024d43676d.png)

**Comment by KagamiChan** [comment]
@ccen3020 浏览器直接登录游戏没问题的话，麻烦检查一下浏览器和 poi 的网络设置是不是一致

**Comment by ccen3020** [comment]
都是走的本地SS，一样的设置……
有没有方法能知道是收到什么东西导致猫的？

**Comment by KochiyaOcean** [comment]
@ccen3020 瞬间猫一般是缓存错误

**Comment by ccen3020** [comment]
再清一次缓存和COOKIE之后好像就可以了……
但是为什么之前清缓存无效还是不懂……
