### ISSUE TITLE
不知道是不是问题，不过我无法解决

### ISSUE THREAD

**Issue by LunHuiShiKong** [poooi/poi#1292]
**poi 版本 / poi version:**
7.2.1

**操作系统 / OS:**
Macos

**插件名和版本 / Plugin name & version:**
*(如果这是一个关于插件的 issue / If this is an issue about plugin)*
一心二用：2.5.0

**你遇到了什么样的问题 / The problem you've met:**
当打开一心二用时，窗口会出现在左上角，通常想要拖动窗口需要拖窗口上方那行白色的。但是它直接出现在电脑那个苹果标志下面了。
<img width="1113" alt="2016-12-26 9 59 17" src="https://cloud.githubusercontent.com/assets/24786988/21492147/9feabaf0-cbb6-11e6-926c-2f7d16ee3645.png">

**有没有重现的方法，或者与问题相关的任何信息 / The way to reproduce, or any information that might be related:**
*(可以的话请提供开发者工具 Console 选项卡的截图 / Please provide a screenshot of developer tool's console tab, if possible)*

**Comment by gnattu** [comment]
在我这里是正常的，也许是你的屏幕出现过变化（比如拔掉了外置显示器导致分辨率切换，但是浏览器没有正确响应这些变化）[这个Apple Script](http://snipplr.com/view/8645/gather-windows/)可能可以帮到你。

**Comment by KochiyaOcean** [comment]
一心二用新窗口生成的位置是参照本体位置的
可以用任务管理器强杀掉 poi 进程来强制关闭
或者在一心二用的开发者工具中输入 `window.close()`

**Comment by LunHuiShiKong** [comment]
正常了。。。。
