### ISSUE TITLE
黑頻

### ISSUE THREAD

**Issue by a5040991** [poooi/poi#1297]
**poi 版本 / poi version:**

V7.2.1 wni x64
**操作系统 / OS:**
win7 64bit

**你遇到了什么样的问题 / The problem you've met:**
黑頻

**有没有重现的方法，或者与问题相关的任何信息 / The way to reproduce, or any information that might be related:**
*(可以的话请提供开发者工具 Console 选项卡的截图 / Please provide a screenshot of developer tool's console tab, if possible)*
![image](https://s29.postimg.org/4izln75t3/jpg131.jpg)
![image](https://s27.postimg.org/7qbvk09cj/561.jpg)

**Comment by KagamiChan** [comment]
@a5040991 请检查poi 的网络设置，并且尝试同样设置能否在浏览器中打开游戏

**Comment by KochiyaOcean** [comment]
检查代理设置是否正确以及代理是否在运行（如果有）

**Comment by a5040991** [comment]
在瀏覽器中運行皆正常，試著其他網頁也是沒有畫面

**Comment by KagamiChan** [comment]
@a5040991 如果在 设置-基本设置 的浏览器里面输入一个常用网址，比如 google.com，yahoo.com 之类的，也是一样打不开的话，就建议检查一下 poi 的网络代理设置了

**Comment by a5040991** [comment]
能成功運行了非常感謝你
