### ISSUE TITLE
poi右边任务的详情全变成日文了，就是鼠标移上去显示的那个，求解- -

### ISSUE THREAD

**Issue by csjtc** [poooi/poi#1298]
**poi 版本 / poi version:**

**操作系统 / OS:**

**插件名和版本 / Plugin name & version:**
*(如果这是一个关于插件的 issue / If this is an issue about plugin)*

**你遇到了什么样的问题 / The problem you've met:**

**有没有重现的方法，或者与问题相关的任何信息 / The way to reproduce, or any information that might be related:**
*(可以的话请提供开发者工具 Console 选项卡的截图 / Please provide a screenshot of developer tool's console tab, if possible)*

**Comment by KochiyaOcean** [comment]
@csjtc 任务插件装了没……

**Comment by csjtc** [comment]
装了的，所以扩展都下了而且都是最新的

**Comment by KagamiChan** [comment]
@csjtc 麻烦提供一下 poi 版本，插件版本，然后开发者工具 console 选项卡的截图

**Comment by csjtc** [comment]
[
![default](https://cloud.githubusercontent.com/assets/21023431/21577617/9499fcc6-cf9c-11e6-8332-ae29d96ab7e5.png)
![default](https://cloud.githubusercontent.com/assets/21023431/21577624/b2d46ffa-cf9c-11e6-8e49-b0c12b8de6dd.png)

](url)

**Comment by KagamiChan** [comment]
@csjtc 在 扩展程序 的 高级设置 里面换一个 npm 服务器（建议 taobao 的），然后再检查一下更新吧，你的插件版本有点老

**Comment by csjtc** [comment]
可以了，不换服务器我还不知道我的插件这么久了，谢谢了，每次有问题都回的好快，十分感谢

**Comment by KagamiChan** [comment]
@csjtc 我也刚刚才发现清华源已经停止服务了 - -
