### ISSUE TITLE
POI黑频打不开

### ISSUE THREAD

**Issue by cuso4nico** [poooi/poi#1300]
**poi 版本 / poi version:**7.3.0 window32/64

**操作系统 / OS:**windows 32

**插件名和版本 / Plugin name & version:**
*(如果这是一个关于插件的 issue / If this is an issue about plugin)*

**你遇到了什么样的问题 / The problem you've met:**
黑频，长时间黑频。因为转不开DMM页面突然变成空白页不小心点了设为主页。
随后试试各类网站都打不开。
看其他处理黑屏的问题的时候我也看了看我的岛风go背后可以运行网页舰c

**有没有重现的方法，或者与问题相关的任何信息 / The way to reproduce, or any information that might be related:**
*(可以的话请提供开发者工具 Console 选项卡的截图 / Please provide a screenshot of developer tool's console tab, if possible)*

![qq 20170102201421](https://cloud.githubusercontent.com/assets/24875272/21589105/534d0162-d129-11e6-8246-bc6f7af86a9a.png)
![qq 20170102202519](https://cloud.githubusercontent.com/assets/24875272/21589129/9c97e620-d129-11e6-9d1a-87531f1195a9.png)

**Comment by KagamiChan** [comment]
@cuso4nico 检查一下 poi 的代理设置吧

**Comment by cuso4nico** [comment]
代理类型：HTTP代理 地址：127.0.0.1 端口：8099 其他不要设置....?

**Comment by KagamiChan** [comment]
@KagamiChan 一般情况来说，如果你在 poi 地址栏里键入 baidu.com，163.com 之类的地址都打不开网页的话，那就是网络设置问题，或者代理软件的问题 - -

**Comment by KagamiChan** [comment]
@cuso4nico 一般情况来说，如果你在 poi 地址栏里键入 baidu.com，163.com 之类的地址都打不开网页的话，那就是网络设置问题，或者代理软件的问题 - -

**Comment by cuso4nico** [comment]
Oh my God..真的...连百度都打不开...代理软件现在在后台开着...舰C网页能登陆...网络是家用的路由器....需要在本机上设置吗...?

**Comment by KagamiChan** [comment]
@cuso4nico 关掉 poi，重启岛风 go，再打开 poi 试试？检查你的 chrome 设置是不是也一致的吧

**Comment by cuso4nico** [comment]
chrome?那是啥....

**Comment by cuso4nico** [comment]
浏览器也是用岛风go，也是按照岛风go的设置的...

**Comment by KagamiChan** [comment]
@cuso4nico 嘛，就是你的浏览器的代理设置

**Comment by cuso4nico** [comment]
我把那个测试错误的-6改成了0...现在进去了....谢谢大佬帮忙（鞠躬）

**Comment by KagamiChan** [comment]
@cuso4nico 好的 - -
