### ISSUE TITLE
Cant extract some files

### ISSUE THREAD

**Issue by Uesakatsukiriko** [poooi/poi#1301]
**poi7.3.0**

**Windows 7 Enterprise Service Pack 1(32-bit operating system)**

**poi 7.3.0**

# **i cannot extract 75 files with 7 zip."unsupported extraction method "message is shown.**

![image](https://cloud.githubusercontent.com/assets/24911497/21635979/a28e448e-d29b-11e6-84e8-5019a3c57f92.png)

plz fix it....

**Comment by KagamiChan** [comment]
I've just downloaded the archive and it passed the test. The reason might be the compression method is not backward compatible
What version of 7-zip are you using?

**Comment by KagamiChan** [comment]
Tested under Windows 10 with 7-zip version 16.04, no problem found. Please consider updating your 7-zip software. Closing this, and you may also comment here in case the problem still exists
