### ISSUE TITLE
希望经验计算扩展能够改进一下布局

### ISSUE THREAD

**Issue by castore** [poooi/poi#1305]
**poi 版本 / poi version:**
7.3.0

**操作系统 / OS:**
win7 x64

**插件名和版本 / Plugin name & version:**
*(如果这是一个关于插件的 issue / If this is an issue about plugin)*
经验计算 3.2.2

**你遇到了什么样的问题 / The problem you've met:**
1080P屏幕下使用纵版布局+切分面板，游戏分辨率100%时右侧插件面板面积有限 导致快速选择第一舰队按钮默认只能看见前4只舰娘，需要滚动滚轮才能选择到下面舰娘的信息。如果能把下面计算面板位置稍微往下调节一下就好。而且舰娘等级、目标等级、合计经验数字显示不全。

**有没有重现的方法，或者与问题相关的任何信息 / The way to reproduce, or any information that might be related:**
*(可以的话请提供开发者工具 Console 选项卡的截图 / Please provide a screenshot of developer tool's console tab, if possible)*
![default](https://cloud.githubusercontent.com/assets/7022156/21762890/0e0d6958-d696-11e6-955a-40f4935138f4.png)
![default](https://cloud.githubusercontent.com/assets/7022156/21763002/9c692bba-d696-11e6-8dfc-f97856e2f64e.png)

**Comment by KagamiChan** [comment]
好的，这个是版面设计时候的问题，下一版修复

**Comment by KagamiChan** [comment]
多谢提出

**Comment by KagamiChan** [comment]
@castore 刚刚发布了 3.2.3，更新一下看看？纵向切分的布局调整为和横版布局一致了

**Comment by castore** [comment]
完全没有问题了 光速修复感谢
