### ISSUE TITLE
[Feature] 舰队速度

### ISSUE THREAD

**Issue by KagamiChan** [poooi/poi#1306]
170110 的更新实装了新的舰娘航速机制，并且
>「高速」以上の機関部強化は現時点では「回避」のみ影響がありますが、今後の実装では同艦速が有効な作戦海域/戦況も存在します。

由此：
~~- 如果舰队内舰娘速度一致，则显示“全”，比如“全高速”~~
- 如果不一致，暂时采用原有的舰队速度判断方式，即取决于最低速的舰娘的速度
- 每艘船显示速度

于是，小面板要不要加？

**Comment by KochiyaOcean** [comment]
@KagamiChan 直接木桶原则就行了吧

**Comment by KagamiChan** [comment]
@KochiyaOcean 主要是官推那句话放了一个同航速带路的卫星，不如一起做了

**Comment by c933103** [comment]
官推不是說由高速以上艦構成的艦隊也是高速艦隊嗎？

2017年1月10日 19:51 於 "東風谷オーシャン" <notifications@github.com> 寫道：

**Comment by c933103** [comment]
那個
※「高速」以上の機関部強化は現時点では「回避」のみ影響がありますが、今後の実装では同艦速が有効な作戦海域/戦況も存在します。 #艦これ
這裡的「同艦速」在日文裡是「該艦速」的意思吧？

2017年1月10日 20:22 於 "gfb hjjhjh" <c933103@gmail.com> 寫道：

**Comment by KagamiChan** [comment]
目前还不知道官方计划的同航速机制具体情况如何，所以暂时不显示同速度相关的信息，以后机制判明了再添加也不困难
此外虽然有说法目前高速以上的舰队和高速本身没什么区别，不过姑且还是把舰队航速也分成了四档……
