### ISSUE TITLE
如何获取敌舰最大血量

### ISSUE THREAD

**Issue by dislido** [poooi/poi#1308]
**poi 版本 / poi version:7.3.0**

**操作系统 / OS:Windows 7**

我方舰娘的最大血量/战斗前血量/战斗后血量和敌舰的战斗后血量都能从store.const._ships或store.battle.
  result中获取到。但是似乎找不到敌舰最大血量，这个数据要在哪里获取？

**Comment by KochiyaOcean** [comment]
敌舰的相关数据都在 battle 包里，因为并非本体需要的数据所以目前没有放在 redux store 中
未卜先知等插件处理敌舰数据的相关代码可以参照 https://github.com/poooi/lib-battle

**Comment by KochiyaOcean** [comment]
`store.battle.packet[0].api_maxhps` 里面存有 battle 包里的自敌舰最大 HP 数据，不过基于双方的舰队交战形态不同（单舰队 || 连合舰队 vs 单舰队 || 连合舰队）处理该 API 的方法也比较麻烦，如果有必要还是推荐参照 lib-battle 的代码

**Comment by yukixz** [comment]
@dislido 敌舰战斗前血量即最大血量
