### ISSUE TITLE
Poi 7.4.0 （暂定） changelog

### ISSUE THREAD

**Issue by KagamiChan** [poooi/poi#1309]
# 功能
- 支持不同装备加成系数下的 33 式索敌公式，可以在舰队面板中进行查看
- 增加舰娘与舰队的速度显示
- 可以通过设置关闭最终战提示
- 更新部分装备图标，支持 17 冬活新装备
- 优化游戏区域缩放机制
- 增加插件自动更新功能，可以在插件设置面板中打开
- 优化 fcd 数据更新机制
- 增加安全模式，安全模式下插件将不会自动启用。进入方式为在命令行下增加参数 `--safe` 或 `-S`，或使用设置中的`下次启动进入安全模式`选项
- 支持调节面板区域的最小宽度或高度，希望得到更大面板区域的用户可以适当进行调整
- [Linux] 加入托盘图标支持，可以在设置中关闭
- [windows] 如果勾选启动时建立快捷方式，会在原有快捷方式之外建立名为 `poi (safe mode)` 的安全模式快捷方式
# 修正
- 修正网络重试次数为负数时的网络错误
- 修正网络重试次数为 0 时仍然显示重试信息
- 由于清华插件源已关闭，将自动帮助原先选择了清华源的用户转移到其它源上
- 修正非第一舰队参加演习时，未卜先知无法正确判断参与演习舰队

## 自 7.4.0 beta.0 以来的更新
- 支持调节面板区域的最小宽度或高度，希望得到更大面板区域的用户可以适当进行调整
- [Linux] 加入托盘图标支持，可以在设置中关闭
- [windows] 如果勾选启动时建立快捷方式，会建立名为 `poi (safe mode)` 的安全模式快捷方式

# 主要插件更新
## 舰娘信息
- 去除排序设置区域，将当前排序信息显示在列表表头
- 类型大类改为可以复选，并增加了“别的舰娘”的分类，来帮助提督找到他们深爱的水母、潜母、补给舰、扬陆舰与工作舰
- 对增设补强中的装备使用与本体一致的提示
- 支持舰娘所在舰队的显示
- 支持切换显示舰娘裸装数值与包含装备加成数值
- 支持切换单页显示与分页显示
- 增加“在舰队中”、“战意高昂”与“增设补强”的筛选选项
- 使用本体 FCD 数据来进行出击限定筛选
- 增加重置所有筛选与显示设置的按钮
- 支持自定义 css 与缩放系数
- 修正了每 HP 维修所需时间
- 修正排序使结果与游戏内保持一致性

## 经验计算
- 修正了竖版分栏界面下的插件内容布局
- 舰娘选择列表中，同等级舰娘按剩余升级经验值升序排列

## 远征信息
- 修复大发动艇相关加成计算及显示
- 增加鬼怒改二与特大发动艇相关加成的计算支持
- 部分不满足条件会显示具体的原因

## 未卜先知
- 在下一点信息中增加上次战斗所选阵型的提示
- 在战斗中显示敌我舰队名
- 增加敌我船只的火力，雷击，对空，装甲的显示
- 上述功能可以在设置中开关

**Comment by KagamiChan** [comment]
有更新的，麻烦自己加一下

**Comment by yukixz** [comment]
自动更新插件

**Comment by KagamiChan** [comment]
# Feature:
- Map-based variate Type-33 formulae
- Speed indicator for ship girl and fleet
- Last sortie notification could be turned off
- New icons for new equipment of 17 winter event
- Optimized game area scaling mechanism
- Option for auto update plugins
- Optimized fcd data update check mechanism
- Safe mode with all plugins disabled and store empty, turned on with `--safe` or `-S` arguments or setting option.
- Option for controling minimal width/height of panel area
- [Linux] Tray icon support, could be turned off
- [Windows] Creates `poi (safe mode)` start menu shortcut with the normal one

# Bugfixes
- Network error when maximum retry count is set to negative
- Info display even maximum retry count is set to 0
- Tsinghua mirror closed, redirect users to other mirrors
- Prophet plugin cannot find the correct fleet in practice if it is not the 1st fleet
