### ISSUE TITLE
[Feature] 运输量计算

### ISSUE THREAD

**Issue by KagamiChan** [poooi/poi#1310]
输送量计算功能用于输送为目标的活动海域，帮助用户获得当前舰队配置的可输送量的信息。当前的输送机制参考 http://nga.178.com/read.php?tid=8741165 

# 实现方式
在舰队面板内移除“总Lv”项目（该项目主要用于远征计算，且在远征信息插件中会有计算），以输送量取代，以舰队为单位计算，提供 S 胜与 A 胜的输送量（默认显示 S 胜）
在 fcd 中加入以下结构的 `transport` 数据
```cson
data:
  item:
    75: 5 #ドラム缶(輸送用)
    68: 8 #大発動艇
    166: 8 #大発動艇(八九式中戦車&陸戦隊)
    193: 8 #特大発動艇
    167: 2 #特二式内火艇
    145: 1 #戦闘糧食
    150: 1 #秋刀魚の缶詰
  ship: 
    487: 5 #鬼怒改二
  shipType:
    2: 5 #駆逐艦
    3: 2 #軽巡洋艦
    21: 6 #練習巡洋艦
    6: 4 #航空巡洋艦
    10: 7 #航空戦艦
    16: 9 #水上機母艦
    14: 1 #潜水空母
    17: 12 #揚陸艦
    15: 15 #補給艦
    22: 15 #補給艦
    20: 7 #潜水母艦
```

# 可能存在的问题
- 在舰队为联合舰队的情况下，需要用户自行对两个舰队的输送量相加
- 只有输送图才会用到
- 目前的机制中，登陆点前的大破与退避的舰娘的输送值不参与计算；登陆点之后则不会去掉。面板内计算时将不予考虑，统一按照不参与计算来处理
- 改修目前不提供输送量的加成，如果有的话，将考虑新增 `itemBonus` 项来兼容

**Comment by wafer-li** [comment]
😂  有一个比较重要的问题就是， TP 值的计算方法，很可能每个活动都不一样。

**Comment by KagamiChan** [comment]
是的，所以计划再观察一次活动（

**Comment by c933103** [comment]
出於每次活動都要更新TP計算值的考慮，以插件形式實現會否較好？

**Comment by KagamiChan** [comment]
嗯……从这次活动来看，放插件里会更好，不过我暂时没想到能放到哪个插件里

**Comment by wafer-li** [comment]
嗯……
我倒建议新造一个插件，不然的话就只能摆到编成记录里面了。

因为 TP 值的有效计量单位是一整个舰队

在 2017年2月12日 上午1:37，かがみ <notifications@github.com>写道：

**Comment by zeropad** [comment]
加在未卜先知里吧，毕竟是活动开得最多的插件。
