### ISSUE TITLE
poi用不了岛风go的live2d

### ISSUE THREAD

**Issue by Margular** [poooi/poi#1311]
**poi 版本 / poi version:**
7.3.0

**操作系统 / OS:**
windows 7

**插件名和版本 / Plugin name & version:**
*(如果这是一个关于插件的 issue / If this is an issue about plugin)*
岛风Go 1.6.7.14,打了岛风Go官网下载的live2d补丁

**你遇到了什么样的问题 / The problem you've met:**
火狐浏览器能用live2d，poi浏览器不行，是空白的，已经清了缓存并且重启poi，两次。。

**有没有重现的方法，或者与问题相关的任何信息 / The way to reproduce, or any information that might be related:**
*(可以的话请提供开发者工具 Console 选项卡的截图 / Please provide a screenshot of developer tool's console tab, if possible)*

**Comment by hyq77766177** [comment]
@Margular 打开设置找到显示里面切换一下窗口模式试试

**Comment by Margular** [comment]
卧槽，可以了，改成了GPU模式，这几个模式哪个适合舰娘哇

**Comment by KochiyaOcean** [comment]
@Margular 非魔改的情况下 window 的占用最小，如果使用了 live2d 之类的还是 gpu 或者 direct
