### ISSUE TITLE
Fleet information bug 

### ISSUE THREAD

**Issue by AlanJager** [poooi/poi#1314]
**poi 版本 / poi version:**
poi@7.3.0

**操作系统 / OS:**
macOS Sierra 10.12.2

**你遇到了什么样的问题 / The problem you've met:**
Fleets information shows blank for some reason but actually the information is right while changing the tag from Overview tag to Fleet or Plugin. And when shifting the tag, there tend to have a blank window(not sure if it is really a window)  between the changing duration.

**有没有重现的方法，或者与问题相关的任何信息 / The way to reproduce, or any information that might be related:**
#### Reproduce Steps:
1. start poi
2. shift fleet tag after game loaded
3. the fleet ships'  name shows blank but only show the HP bar

the screenshot of the situation
<img width="367" alt="2017-01-28 10 23 47" src="https://cloud.githubusercontent.com/assets/8843214/22393640/9f783144-e545-11e6-8d93-13e3ad8255cf.png">

*(可以的话请提供开发者工具 Console 选项卡的截图 / Please provide a screenshot of developer tool's console tab, if possible)*
I'm not really sure which log caused this situation so just paste all.
#### Terminal log
[ERROR] Connection failed: GET http://m.one.impact-ad.jp/push_sync Error: getaddrinfo ENOTFOUND m.one.impact-ad.jp m.one.impact-ad.jp:80
[ERROR] Error: write EPIPE
[ERROR] Error: write EPIPE
[ERROR] Error: read ECONNRESET
[ERROR] Error: read ECONNRESET
[ERROR] Error: read ECONNRESET
[ERROR] Error: read ECONNRESET
[ERROR] Error: write EPIPE
[ERROR] Connection failed: GET http://platform.twitter.com/widgets.js Error: connect ETIMEDOUT 104.244.42.3:80
[ERROR] Connection failed: GET http://www.googleadservices.com/pagead/conversion_async.js Error: connect ETIMEDOUT 220.255.2.153:80
[ERROR] Connection failed: GET http://static.ads-twitter.com/uwt.js Error: connect ETIMEDOUT 69.171.234.29:80
[ERROR] Connection failed: GET http://platform.twitter.com/oct.js Error: connect ETIMEDOUT 104.244.42.3:80
[ERROR] Error: connect ETIMEDOUT 220.255.2.153:443
[ERROR] Error: connect ETIMEDOUT 220.255.2.153:443
[ERROR] Error: connect ETIMEDOUT 220.255.2.153:443
[ERROR] Connection failed: GET http://platform.twitter.com/widgets.js Error: connect ETIMEDOUT 104.244.42.3:80
[ERROR] Connection failed: GET http://www.googleadservices.com/pagead/conversion_async.js Error: connect ETIMEDOUT 220.255.2.153:80
[ERROR] Connection failed: GET http://static.ads-twitter.com/uwt.js Error: connect ETIMEDOUT 69.171.234.29:80
[ERROR] Connection failed: GET http://platform.twitter.com/oct.js Error: connect ETIMEDOUT 104.244.42.3:80
[ERROR] Connection failed: GET http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js Error: connect ETIMEDOUT 220.255.2.153:80
[ERROR] Error: connect ETIMEDOUT 104.244.42.3:443
[ERROR] Error: connect ETIMEDOUT 104.244.42.3:443
[ERROR] Connection failed: GET http://t.co/i/adsct?p_id=Twitter&tw_order_quantity=0&tw_sale_amount=0&txn_id=nuhjn Error: connect ETIMEDOUT 104.244.42.197:80
[ERROR] Connection failed: GET http://t.co/i/adsct?p_id=Twitter&tw_order_quantity=0&tw_sale_amount=0&txn_id=nugfy Error: connect ETIMEDOUT 104.244.42.197:80
[ERROR] Error: connect ETIMEDOUT 104.244.42.3:443
[ERROR] Connection failed: GET http://t.co/i/adsct?p_id=Twitter&tw_order_quantity=0&tw_sale_amount=0&txn_id=nvbbo Error: connect ETIMEDOUT 104.244.42.197:80
[ERROR] Connection failed: GET http://pixel.rubiconproject.com/tap.php?v=7751&nid=2249&expires=30&put=CAESED4sER1aDmYJdRkfnOoMSg8&google_cver=1 Error: connect ETIMEDOUT 210.176.156.45:80
[ERROR] Connection failed: GET http://spdmg-backend.i-mobile.co.jp/adv.aspx?sid=15842&cq=other=1 Error: getaddrinfo ENOTFOUND spdmg-backend.i-mobile.co.jp spdmg-backend.i-mobile.co.jp:80
[ERROR] Connection failed: GET http://spdmg-backend.i-mobile.co.jp/adv.aspx?sid=16968&cq=top=2 Error: getaddrinfo ENOTFOUND spdmg-backend.i-mobile.co.jp spdmg-backend.i-mobile.co.jp:80

**Comment by AlanJager** [comment]
Maybe the information display blank was caused by already opened a developer tool's console tab, but the blink problem still remaining.

**Comment by KochiyaOcean** [comment]
Trying to turn off Hardware Acceleration in settings?

**Comment by AlanJager** [comment]
Thanks, Hardware Acceleration was to blame for this problem.
