### ISSUE TITLE
Use codacy for code reviews and monitors code quality

### ISSUE THREAD

**Issue by AlanJager** [poooi/poi#1317]
How about using this [site](https://www.codacy.com) to automate code reviews and monitors code quality over time

**Comment by KagamiChan** [comment]
I'll be glad to see frequent PRs to push us to deploy a such system :)

**Comment by AlanJager** [comment]
Thanks for your reply. Actually, I just think code review will help to improve the quality of code.

**Comment by KagamiChan** [comment]
To explain to everyone interested:
We do have code review for every PR, although some communications take place within IM, not on github pages. And we have eslint as linter which could prevent many mistakes
For now, poi has only a few tests and limited code coverage. It is not something to show off, but writing tests will take more effort than implementation. If we recieve more frequent PRs or have more active devs, we could make up the tests.

Anyway, bug reports, suggestions, idea, PRs, and devs are always welcome :)

**Comment by AlanJager** [comment]
I know spectron could be a good way for testing electron app. But I still need sometime to find a good solution for the test part of poi. So....

**Comment by AlanJager** [comment]
There are some [issues](https://www.codacy.com/app/AlanJager/poi/issues) came up by this site where I add a forked poi. I'm not really understand are these issues making any sense, but they just throw bad issues.

**Comment by yukixz** [comment]
wow auto-test for poi.

**Comment by AlanJager** [comment]
@yukixz it's just the result came out with cadacy's code review, but when come to auto-test, maybe it is another concept.

**Comment by KochiyaOcean** [comment]
Hmm, one of the problems is, some codes' stability is depends on Takana and is hard to generate a test case :-(

**Comment by AlanJager** [comment]
Oops, maybe we need more time to consider solutions for this problem.

**Comment by KagamiChan** [comment]
As we have introduced eslint into ci, code will be linted per pull request
