### ISSUE TITLE
【UI相關】我變強了

### ISSUE THREAD

**Issue by FungJiHsu** [poooi/poi#1319]
**poi 版本 / poi version:**

7.3.0
**操作系统 / OS:**
win7 64

**插件名和版本 / Plugin name & version:**
我變強了4.1.13
*(如果这是一个关于插件的 issue / If this is an issue about plugin)*

**你遇到了什么样的问题 / The problem you've met:**
經驗值，戰果值總是從0開始

![qq 20170206090617](https://cloud.githubusercontent.com/assets/14539399/22631640/0589f578-ec4c-11e6-9787-95cacf71099f.png)

**Comment by ruiii** [comment]
.....请阅读插件介绍
ruiii/plugin-Hairstrength#31
