### ISSUE TITLE
瀏覽器相關

### ISSUE THREAD

**Issue by FungJiHsu** [poooi/poi#1320]
之前我安裝了chorme（現在已卸載）
用POI登錄的時候，右下角會跳出一個廣告框
在此之前，並沒有這廣告出現

請問應該怎麼解決（已更改過dns，也不是運營商劫持，清理過不良插件，殺過毒）

**Comment by KochiyaOcean** [comment]
@FungJiHsu 有截图么

**Comment by FungJiHsu** [comment]
@KochiyaOcean 
![qq 20170207111551](https://cloud.githubusercontent.com/assets/14539399/22676507/d5a45b10-ed26-11e6-8109-bca6194bbde6.png)

**Comment by AlanJager** [comment]
@FungJiHsu 有没有可能是修改过host的原因

**Comment by FungJiHsu** [comment]
今天开始没有了...不知道怎么回事
host也没变
