### ISSUE TITLE
黑屏

### ISSUE THREAD

**Issue by stella6678** [poooi/poi#1324]
**poi 版本 / poi version:**
7.3.0

**操作系统 / OS:**
win8 64x

**插件名和版本 / Plugin name & version:**

**你遇到了什么样的问题 / The problem you've met:**
开启poi后游戏界面黑屏 重启刷新无数次之后也没反应

**有没有重现的方法，或者与问题相关的任何信息 / The way to reproduce, or any information that might be related:**

![qq 20170210063559](https://cloud.githubusercontent.com/assets/24601528/22804182/36d11e92-ef5b-11e6-991b-a80f15185732.jpg)

**Comment by stella6678** [comment]
刚刚检查了一下各类浏览器在打开ACGP的情况下能否正常上网 登陆dmm的时候也显示的是ERR_SSL_PROTOCOL_ERROR

**Comment by stella6678** [comment]
另外用OOI可以正常登陆 希望临近冬活各位dalao能帮忙解决一下QAQ

**Comment by JenningsWu** [comment]
意思是所有浏览器都不能用 ACGP 登陆上去？
这不是 ACGP 挂了么（。

**Comment by stella6678** [comment]
但是我看开发者工具的代码里一开始读取失败的是从poi的地址来的 另外poi的官网我也打不开.....

**Comment by stella6678** [comment]
@JenningsWu 但是我看代码一开始读取失败的是从poi开始的 另外poi的官网我也点不进去...一样说是connection failed

**Comment by JenningsWu** [comment]
@stella6678 poi 官网貌似挂了，但是那个不影响 poi 浏览器的运行。所以说其他浏览器用 acgp 也不能上的话，这不应该去检查 acgp 么…？

**Comment by stella6678** [comment]
@JenningsWu 检查是检查了....几个线路我挨个都换了一下 基本都是一样的内容说ERR_CONNECTION_CLOSED或者ERR_SSL_PROTOCOL_ERROR 网站方面则是说
![image](https://cloud.githubusercontent.com/assets/24601528/22805687/1815359a-ef62-11e6-9860-38ee5ee95e6a.png) 这样

昨天开始也有联系ACGP的客服但是完全没人理 现在是完全一头雾水不知道从哪弄起 百度搜了搜也没什么有相同问题的有解决办法_(:з」∠)_

**Comment by dkwingsmt** [comment]
@stella6678 暂时换个代理吧，比如 crystalACG ，ooi，或者买个短期岛风 go

**Comment by stella6678** [comment]
@dkwingsmt 换了岛风GO 现在代码变成了这样

依旧是黑屏
![qq 20170210075803](https://cloud.githubusercontent.com/assets/24601528/22806762/e9ec0c70-ef66-11e6-97cf-55d653a81978.png)

**Comment by JenningsWu** [comment]
@stella6678 换了岛风 GO 之后代理设置是否正确？poi 能正常打开百度之类的普通网页么

**Comment by stella6678** [comment]
@JenningsWu 看来是没重启的缘故 换了岛风GO之后重启了一下终于又能用了 谢谢！
