### ISSUE TITLE
战斗记录不显示敌方装备

### ISSUE THREAD

**Issue by chiwei** [poooi/poi#1325]
**poi 版本 / poi version:**
7.3.1

**操作系统 / OS:**
Win10

**插件名和版本 / Plugin name & version:**

battle detail v3.6.1

**你遇到了什么样的问题 / The problem you've met:**

战斗记录不显示敌方装备

**有没有重现的方法，或者与问题相关的任何信息 / The way to reproduce, or any information that might be related:**

**Comment by yukixz** [comment]
请给出更多信息：在哪个地图的哪个点没有显示地方装备。以及将没有显示的包上传上来（点复制数据、然后粘贴到记事本保存为文件）

**Comment by chiwei** [comment]
基本上都没有，发个2-3boss点和一个演习的，请查看。

[2-3.txt](https://github.com/poooi/poi/files/768183/2-3.txt)
![2-3](https://cloud.githubusercontent.com/assets/3197925/22850570/99dc7da6-f046-11e6-91d7-3bba31a7d5c2.png)

[演习 神撃　白兎 (Lv.109).txt](https://github.com/poooi/poi/files/768184/Lv.109.txt)
![lv 109](https://cloud.githubusercontent.com/assets/3197925/22850580/cedb361e-f046-11e6-9e20-20309ee3e3ab.png)

**Comment by yukixz** [comment]
thx 我下午看看

**Comment by yukixz** [comment]
Fixed
