### ISSUE TITLE
Mac下白屏

### ISSUE THREAD

**Issue by ibicdlcod** [poooi/poi#1328]
**poi 版本 / poi version:**
7.3.0

**操作系统 / OS:**
Mac OS 10.12.3

**插件名和版本 / Plugin name & version:**

**你遇到了什么样的问题 / The problem you've met:**

游戏白屏 但是用chrome能打开

**有没有重现的方法，或者与问题相关的任何信息 / The way to reproduce, or any information that might be related:**

**Comment by KochiyaOcean** [comment]
描述太简单了难以判断
通用的解决方法的话请检查代理设置是否正确
