### ISSUE TITLE
关于老板键的问题及一些建议

### ISSUE THREAD

**Issue by EdiTurn** [poooi/poi#1330]
**poi 版本 / poi version:** 7.3.0

**操作系统 / OS:** Windows 10 Pro 14393.726 64-bit

**你遇到了什么样的问题 / The problem you've met:** 
1. 当使用老板键隐藏 poi 后，立即 Win+L 锁屏，再解锁，系统任务栏上会出现poi的图标.
隐藏 poi 后如果将焦点移动到桌面或其他窗口上，锁屏解锁后则不会出现此问题。

2. 将最大化的 poi 窗口最小化后，使用老板键隐藏 poi 并重新显示，poi 窗口不是最大化状态。

**建议：**
1. 能否同时隐藏托盘图标？
2. 希望 poi 隐藏后能暂停声音的输出。

**Comment by KagamiChan** [comment]
我看了一下老板键的相关代码，并没有涉及对托盘图标的操作。并且目前托盘图标也不存在一个隐藏选项，应该都是由 windows 系统自己进行的管理。可行的思路可能是删掉现有图标然后重建一个……

声音的输出包括游戏的声音输出和 poi 自身的通知，是希望两个都停止掉吗

最大化 poi 最小化后重新显示可能是 windows 上的特殊情况 - -

**Comment by KochiyaOcean** [comment]
维持托盘图标不隐藏是为了避免整个隐藏掉以后用户误以为是闪退等
隐藏托盘图标的软件本身有很多，可以结合使用

**Comment by EdiTurn** [comment]
@KagamiChan 从「隐蔽」的角度来说，我的设想的确是要同时暂停游戏声音及 poi 本身的通知。（虽然我是直接把声音和通知都关掉的）

@KochiyaOcean 由于老板键是需要用户自行去设置的，我觉得出现这样的误解应该不会太多。

由于上面所说的都无碍于日常使用，此 issue 优先级可以无限低，如果改起来麻烦就算了。

**Comment by EdiTurn** [comment]
又一些无关紧要、不影响正常使用的 bug：

1. 用老板键隐藏程序窗口，然后通过点击托盘图标（或通过托盘图标右键菜单中的「显示 poi」）显示程序窗口，此后需要连按两次老板键才能隐藏程序窗口。

2. 通过托盘图标右键菜单中的「隐藏 poi」来隐藏的话，无法通过老板键来显示。

3. 打开插件窗口（如舰娘信息等），然后将主程序窗口移动到前台，然后使用老板键隐藏并显示 poi，此时插件窗口会显示在前。

4. 托盘图标右键菜单中的「隐藏 poi」无法隐藏插件窗口。
