### ISSUE TITLE
poi的win10通知導致卡死

### ISSUE THREAD

**Issue by lodpdp** [poooi/poi#1334]
poi版本是v7.3.0
os是windows10

觀察很多次 poi在跳出win10的右下角通知的時候 不論是大破通知還是遠征通知 有機會卡死 等一段時間就好

確認是win10通知的問題  因為一關掉就沒事了

**Comment by KochiyaOcean** [comment]
@lodpdp 尽量关闭后台试试看？

**Comment by KagamiChan** [comment]
感觉和 #1198  是一样的问题

**Comment by KochiyaOcean** [comment]
想到一种可能性
如果有使用秘书语音，禁用掉试试看

**Comment by lodpdp** [comment]
好的我先試試關閉秘書語音

**Comment by gnattu** [comment]
Windows10早期版本的通知提示有bug，安装Creator更新后是否问题依然存在？

**Comment by lodpdp** [comment]
經過不知道哪段時間之後 就沒有這個問題了 我用下載包的也沒事 感謝大佬的修正
