### ISSUE TITLE
语音字幕不更新好久了，翻译不显示期间限定语音

### ISSUE THREAD

**Issue by csjtc** [poooi/poi#1336]
**poi 版本 / poi version:**7.3.0

**操作系统 / OS:**windows7

**插件名和版本 / Plugin name & version:**语音字幕0.5.5

**你遇到了什么样的问题 / The problem you've met:**

**有没有重现的方法，或者与问题相关的任何信息 / The way to reproduce, or any information that might be related:**

**Comment by KochiyaOcean** [comment]
cc @grzhan
