### ISSUE TITLE
关于概览面板舰队信息UI的建议

### ISSUE THREAD

**Issue by dislido** [poooi/poi#1339]
目前概览面板下的舰队信息显示的内容比较少，有时候会发生忘换装备就出击的情况，某些星际提督（比如我）有时候还会无视掉需要补给的图标忘记补给就出击。
稍微尝试修改了一下，做了一个参考图：
![image](https://cloud.githubusercontent.com/assets/25094788/23123289/232522e6-f7ab-11e6-87e8-1b0de66c55db.png)
把疲劳值移到了等级右面
贴条用舰娘名字颜色代替显示
血条、油、弹分三个条显示在原本疲劳、贴条的位置
原本血条的位置显示装备

（右下空的那一块想不出拿什么补了
（似乎可以把疲劳值放在那里

（另外希望鼠标移上去时显示的信息更丰富点，比如火力昼夜战CI类型之类的

**Comment by d956381604** [comment]
贴条改动可能有用（？）
剩下的..鼠标移上去显示较慢不如双击一下切换到舰队面板

**Comment by KochiyaOcean** [comment]
三个条重合到一起的话还是比较容易混淆的
有空看一下有没有合理的解决方案

**Comment by dislido** [comment]
把血条透明一点扔到背景上如何
