### ISSUE TITLE
没有舰队信息显示

### ISSUE THREAD

**Issue by Richousama** [poooi/poi#1341]
**poi 版本 / poi version:**
v7.3.0

**操作系统 / OS:**
win10

**插件名和版本 / Plugin name & version:**

**你遇到了什么样的问题 / The problem you've met:**

如题。用socks5登录的，游戏运行正常，但是没有舰队信息。
![image](https://cloud.githubusercontent.com/assets/25531368/23197868/ab691598-f906-11e6-90c1-af0d75afc018.png)

**有没有重现的方法，或者与问题相关的任何信息 / The way to reproduce, or any information that might be related:**

**Comment by KochiyaOcean** [comment]
代理设置截图看看？
出现这种情况有很大可能性是代理设置里设置了不能设置的东西……

**Comment by yukixz** [comment]
代理设置poi端口填0
