### ISSUE TITLE
POI没法登录舰娘

### ISSUE THREAD

**Issue by were** [poooi/poi#1342]
**poi 版本 / poi version:** 7.4.0

**操作系统 / OS:** MacOS X

**插件名和版本 / Plugin name & version:**

**你遇到了什么样的问题 / The problem you've met:**
我遇到了一个严峻的问题：POI不能登录舰娘了，我可能前面几次是能够登录的，然后突然就有一次输入的用户名密码都是正确的，但是第一次登录之后并没有给我进入舰娘的界面，而是大咪咪的主页，然后也并没有登录，如果我点右边的log in重新登录，就会出现用户名或者密码不正确。

删缓存 Cookie也没有用。

<del> 我不确定这是不是代理的锅，我用的ACGPower。 </del>

**有没有重现的方法，或者与问题相关的任何信息 / The way to reproduce, or any information that might be related:**

**Comment by KagamiChan** [comment]
看上去像是你要更新你的密码了。大咪咪不定期要求你更新密码，查看你的注册邮箱里面有没有相应的邮件，或者在 dmm 网站上请求一下重设密码

**Comment by were** [comment]
貌似是代理的锅，我换了ACGP的线路就好了。

**Comment by KagamiChan** [comment]
那就好~
