### ISSUE TITLE
“概览”选项卡下舰队编成信息部分刷新故障

### ISSUE THREAD

**Issue by FX9590** [poooi/poi#1343]
v7.4.0-beta.0
Windows 10 x64 Enterprise

“概览”选项卡下舰队编成信息部分（非“舰队”选项卡），在回到母港时、点“进击”后不再刷新，更换舰队编成时才会。

Console 里满屏红色，内容很多，不好截图。我就全弄出来了。
[1487950552965.txt](https://github.com/poooi/poi/files/799865/1487950552965.txt)

这个换了版本后打开就有，我确实不清楚怎么触发的。

**Comment by KochiyaOcean** [comment]
已知未卜先知 6.5.0 在基地空袭后可能导致此结果，请确保版本是最新的

**Comment by FX9590** [comment]
这个 issues 是不是关得太快了……

本次活动压根没有基地空袭啊。
是指使用陆航？

未卜先知为 Ver. 6.5.1

在 issues #1344  中，KagamiChan 提出的对于另一问题的解决方法：
"作为一个可能的解决方法，可以删除 %appdata%/poi 目录下的 Local Storage 文件夹之后再重启 poi 看看。"
对该问题有效。

**Comment by KagamiChan** [comment]
@FX9590 那个是 6.5.0 有的一个 bug，6.5.1 修正了，升级插件是为了确认是不是这个 bug 。本次活动没有基地空袭，但是 6-5 还是有的 = =
