### ISSUE TITLE
“未卜先知”插件故障

### ISSUE THREAD

**Issue by FX9590** [poooi/poi#1344]
v7.4.0-beta.0
Windows 10 x64 Enterprise
未卜先知 Ver. 6.5.1

之前的时候，该插件顶端会提示当前对阵舰队名。
比如：“第1舰队 vs 敌侦察舰”。
现在，所有曾经出现过的对阵内容会全部显示出来，而不是只显示当前的：
<
第1舰队 vs 敌侦察舰
第1舰队 vs 敌主力舰队
……
>

Console 里满屏红色，内容很多，不好截图。我就全弄出来了。
[1487950552965.txt](https://github.com/poooi/poi/files/799907/1487950552965.txt)

同上一个 issues 一样。
这个问题换了版本后打开就有，我确实不清楚怎么触发的。

**Comment by KochiyaOcean** [comment]
cc @KagamiChan

**Comment by KagamiChan** [comment]
具体出错的原因在分析。作为一个可能的解决方法，可以删除 `%appdata%/poi` 目录下的 `Local Storage` 文件夹之后再重启 poi 看看。

**Comment by FX9590** [comment]
@KagamiChan 
删除该文件夹并重启后，故障排除。
非常感谢您提供帮助。

**Comment by KagamiChan** [comment]
会晚些时候发布 6.5.2 彻底解决这个问题 - -

**Comment by KagamiChan** [comment]
已发布，请更新，暂时关闭 issue
