### ISSUE TITLE
Windows （7） 下安装插件显示 unabled to verify the first certificate 的问题

### ISSUE THREAD

**Issue by KagamiChan** [poooi/poi#1347]
目前已经有一些报告，由于出现该错误而无法下载该插件的情况：
微博上的一例：
![image](https://cloud.githubusercontent.com/assets/3816900/23332750/bdeeb834-fbb9-11e6-8a5b-7b912b7407dd.png)
nga 上的一例：
http://bbs.ngacn.cc/read.php?pid=215835129

这两起都是 windows 7 下的结果
根据关键词搜索得到的一些回答是对于 windows 7 设置 `NODE_TLS_REJECT_UNAUTHORIZED` 环境变量，忽略 https 错误强行进行不安全连接。

感觉可能的原因如下：
- 网络有中间人劫持
- 系统上没有安装相应的根证书或根证书被禁用（考虑到 npmjs.org, npm.taobao.org 使用的是 GMO 的证书，应该是被禁用）
- 没有开启 TLS /SSL 支持（对于 node 的这一块我并不了解）

于是，需不需要在 poi 服务器上为这部分用户部署一个插件打包分发系统？

**Comment by yukixz** [comment]
根据我之前解决的这个问题，原因是用户用了 Ghost 版盗版 Windows 系统，重装成官方版 Windows 即可解决。
怀疑是 Ghost 系统修改了某些系统组件，破坏了 SSL。

**Comment by KagamiChan** [comment]
补充：在我的 windows 7 虚拟机上，关掉 Internet 设置里面的 TLS 与 SSL 开关并不能复现类似的错误

**Comment by KagamiChan** [comment]
嗯，那还是装原版系统好了
