### ISSUE TITLE
未卜先知 資訊顯示有誤

### ISSUE THREAD

**Issue by bckps7336** [poooi/poi#1349]
**poi 版本 / poi version:**
poi v7.3.0

**操作系统 / OS:**
Kubuntu 16.10

**插件名和版本 / Plugin name & version:**
未卜先知 v6.5.1

**你遇到了什么样的问题 / The problem you've met:**
使用第4隊去打演習，血量計算在第一隊。
![spectacle wx6966](https://cloud.githubusercontent.com/assets/8579700/23338262/a34988a6-fc40-11e6-8a72-0e4bbda0277e.png)

**有没有重现的方法，或者与问题相关的任何信息 / The way to reproduce, or any information that might be related:**
用第一隊之外的隊伍去演習(出擊沒有試過)

![screenshot_20170226_162616](https://cloud.githubusercontent.com/assets/8579700/23338253/602e1096-fc40-11e6-9bda-2c227ab33db3.png)

**Comment by yukixz** [comment]
已知问题、不打算修复

**Comment by KagamiChan** [comment]
在 poi 7.4.0 版本会修复
