### ISSUE TITLE
关于触摸的支持问题

### ISSUE THREAD

**Issue by ccen3020** [poooi/poi#1350]
**poi 版本 / poi version:**
7.3.0

**操作系统 / OS:**
win10

**你遇到了什么样的问题 / The problem you've met:**
目前版本似乎是如果程序启动的时候有触摸，就可以用触摸来操作，如果没有触屏，就没法触摸的样子？
现在在没有触摸的台式机上开了POI，然后转到PAD/ANDROID上用远程桌面来操作的时候，就只能用鼠标模式了……触摸模式点程序就没有反应了
我记得以前没有改触摸支持的时候，好像是可以触摸戳FLASH，但是戳程序没反应的样子
=======================================

此外，还有个问题
目前插件更新的时候似乎不会判断POI版本？在版本切换的时候希望可以判断一下
比如这次更新插件之后，7.3.0任务信息和主面板上正在进行的任务信息都没法正常工作了

**Comment by KagamiChan** [comment]
关于第二个问题，如果插件升级界面能够正常使用的话，请升级未卜先知到 6.5.3 版本，如果不能的话，到 `%appdata%poi` 目录下删除 `Local Storage` 文件夹，然后再重启 poi，升级未卜先知到 6.5.3 版本

**Comment by KochiyaOcean** [comment]
触摸屏支持也是老问题了， Chromium 堆了一堆 issue 在那里……
这几天准备用设备测试一下了
