### ISSUE TITLE
打开黑屏,chrome可以正常使用

### ISSUE THREAD

**Issue by ff511** [poooi/poi#1353]
**poi 版本 / poi version:**
7.4
**操作系统 / OS:**
win10 64

原本的7.3突然无法使用,打开黑屏,chrome可以正常访问kancolle,使用shadowsocks

console 截图
![1](https://cloud.githubusercontent.com/assets/26131224/23493422/b182790a-fed9-11e6-8948-21c0a5e66d22.png)

![2](https://cloud.githubusercontent.com/assets/26131224/23493452/e55f4b36-fed9-11e6-9080-3c415c84485c.png)

**Comment by KagamiChan** [comment]
和 #1344 类似，删除 `%appdata%/poi` 目录下的 `Local Storage` 文件夹之后再重启 poi
同时请尽快将未卜先知插件升级到最新版本

**Comment by ff511** [comment]
Thanks!
