### ISSUE TITLE
poi 7.4.0 flash player 路徑問題

### ISSUE THREAD

**Issue by darg20127** [poooi/poi#1354]
**poi 版本: 7.4.0**

**操作系统: MacOS Sierra**

**插件名和版本: Flash Player Plugin**

**你遇到了什么样的问题:**
7.4.0會找不到flash player，裝回7.3.0是正常的。
比較了一下兩個版本的差異
7.4.0的PepperFlashPlayer.plugin在
Resources/PepperFlash/mac-x64/darwin-x64
7.3.0在
Resources/PepperFlash/mac-x64

於是我把7.4.0的PepperFlashPlayer.plugin拖回mac-x64就找得到了

**Comment by KochiyaOcean** [comment]
总之正在 build 7.4.1，之后应该就没问题了

**Comment by darg20127** [comment]
ok. 7.4.1沒有問題，辛苦了。
