### ISSUE TITLE
TouchBar Support

### ISSUE THREAD

**Issue by yukixz** [poooi/poi#1355]
What functions should we show on TouchBar?

**Comment by KochiyaOcean** [comment]
@yukixz Tab switch, for example

**Comment by infinitysky** [comment]
I think this feature will not be able to implement until the Electron provides the new API for MacOS Touch Bar. 
Even the Electron just released the API on 1.6.4-beta. I believe that it has a lot of jobs there. (Current Electron version is 1.6.2 ) 
I think the Touch Bar could include current HP Level, '大破' warning, the countdown of constructions, the countdown of repairing and countdown of the expedition (遠征).

**Comment by c933103** [comment]
Perhaps it can be used to shown expedition timer, repair timer, morale recover timer, as well as bucket and resource count in the touch bar when sorting, as all battle-related reminders would be displayed on screen during sortie anyway so I think there're no need to duplicate those info down to the touchbar.

**Comment by gnattu** [comment]
#1504 Added basic control function to the TouchBar. As far as I concern, the TouchBar is not designed for and not good at displaying information. The available space for it is limited, and it can only display one single line while information on the poi main-window is plentiful and clear. To display information on the TouchBar is therefore not a good idea. TouchBar replaces the function key-area of the keyboard, and should be used for controlling functions to give play to its flexibility which traditional function keys don't have, as well as to keep the connivence of using a function key. The tabs switch feature sounds great, and may be implemented in the future ("satellite").

**Comment by KagamiChan** [comment]
Implemented, closing this
