### ISSUE TITLE
关于未配装检查的设计

### ISSUE THREAD

**Issue by LostXine** [poooi/poi#1358]
经常遇到出击/演习忘记带装备的情况，于是想增加一个点击出击时检查空装备栏然后弹窗报警的功能，想请教一下各位大佬这样的需求是做在poi本体里面合适还是另起一个插件？如果要起插件是否有适合萌新的demo？（btw开发规范我都看了然而……
谢谢！

**Comment by yukixz** [comment]
@LostXine 触发条件是什么？只带了一个装备提不提示？

**Comment by LostXine** [comment]
检查的触发是在点过出击按钮之后（我记得会有接收消息）
报警的触发设想是有空位就提示，提示内容可以放在中间的状态栏，格式大概是“XXX空X个格子，XXX空X个格子”这样。
（后来又觉得是该写个插件，至少有个页面控制一下提示开关和条件

**Comment by yukixz** [comment]
@LostXine 那么对于练级或者其他情况下、装备故意不带满的情况，怎么办

**Comment by LostXine** [comment]
@yukixz 我觉得是这样的：
1.如果只是出现在中间状态栏的消息，并不会引起用户太大的困扰/反感
2.可以设置检查筛选，比如根据海图或者上锁船筛选是否检测

**Comment by KagamiChan** [comment]
@LostXine 状态栏区域已经有船位和装备位上限检测了，两个之间会有冲突 - -

**Comment by LostXine** [comment]
@KagamiChan 抱歉描述有问题，想指的是字幕插件发送的那个状态栏

**Comment by yukixz** [comment]
@LostXine 就是同一个

**Comment by LostXine** [comment]
@yukixz @KagamiChan 麻烦确认一下是这个咯↓ 
![image](https://cloud.githubusercontent.com/assets/10805205/23585094/48af169e-01af-11e7-8975-4f747797d137.png)
如果有冲突的话改为弹出类似最终战的小窗是否可行呢？
(只是做成插件向这个窗口推消息应该没问题的吧…

**Comment by KagamiChan** [comment]
@LostXine 是的，就是这里。
如果要检测的话，就是母港点击 出击-出击 之后弹出信息。像最终战提示那样的小气泡信息会显示在游戏画面之上，阻挡点击选择——虽然可能也的确是这个功能的实现目标

**Comment by LostXine** [comment]
@KagamiChan 好的。
（我觉得阻挡点击选择就有些干扰用户了，只是告诉用户一下有船有空装备栏就可以了。
另外有几个问题：
1.关于船位和装备位上限检测应该是游戏本体在做？是poi中也有相关所以会导致冲突吗？
2.想请教下如果作为一个插件，下面途径是否可行：
利用上一次进入母港获得的舰队与装备信息进行检测，在点击出击-出击/演习后向状态栏发送消息。

谢谢！

**Comment by KagamiChan** [comment]
@LostXine 栏位上限检测是这个：https://github.com/poooi/poi/blob/master/views/services/sortie-free-slot-check.es

1. 因为信息栏一次只能显示一条信息，因此两个检测信息总会有一条无法显示（其实，上限检测的两个信息也是互相竞争显示的 - -）
2. 可以参考刚才给你的上限检测的方法，监听这个包，然后进行判断发送提示。这个也可以和上限检测合并到一起，欢迎贡献代码

**Comment by KagamiChan** [comment]
顺便，关于开发者文档，或者开发相关的问题，都可以发 issue 或者加我们的 telegram 讨论群来交流的

**Comment by LostXine** [comment]
@KagamiChan 看到了，谢谢！（难怪一开始没反应过来原来这两个检测我常年关闭…
后面装备检测的话我倾向于用插件的形式，会先学习一段时间，有问题再向大佬请教，谢谢！

**Comment by KochiyaOcean** [comment]
@LostXine 因为没法在出击前预测将要出击的舰队所以不可避免要检查全舰队然后就会出现被远征队装备警告骚扰的情况

**Comment by LostXine** [comment]
@KochiyaOcean 了解，应对这种情况有如下考量：
1.已经远征的舰队会被筛选出去的，我记得在母港页面就可以做。
2.仅在进入出击海域选择/演习页面时进行检测。
3.为每个舰队设置检测开关，默认开启1/2舰队。

**Comment by LostXine** [comment]
我觉得新版本中自动切换的设定已经比较好地解决了这个问题，可以关了。
