### ISSUE TITLE
windows安装包的目录名设置问题

### ISSUE THREAD

**Issue by Nidhoggur1993** [poooi/poi#1361]
**poi 版本 / poi version:**
7.4.1 windows安装版（之前的版本应该也是这样）

**操作系统 / OS:**
win10

**插件名和版本 / Plugin name & version:**
issue无关

**你遇到了什么样的问题 / The problem you've met:**
poi在使用exe程序更新版本/新安装的时候，目录名会带当前的版本号，导致更新安装时原有的快捷方式失效。
是不是可以在之后重新更改一下目录的命名规则，这样即使更新了程序也可以用原有的快捷方式

**有没有重现的方法，或者与问题相关的任何信息 / The way to reproduce, or any information that might be related:**
随手装一个就能重现_(:з」∠)_

**Comment by KochiyaOcean** [comment]
安装包安装完成后会启动然后快捷方式应该会覆盖掉才是……

**Comment by KagamiChan** [comment]
如果勾选了创建快捷方式的话，那么安装时候开始菜单内的快捷方式会更新。不过如果是自己复制出来的，或者是发送到桌面的这种就没有办法跟着更新了，目前的安装程序制作工具没有给这方面的选项

**Comment by KagamiChan** [comment]
我看了一下，如果要自己做快捷方式的话，可以把带版本号的比如 `app-7.4.1` 部分去掉，比如：
`C:\Users\kagami\AppData\Local\poi\app-7.4.1\poi.exe` 改成
`C:\Users\kagami\AppData\Local\poi\poi.exe`

我看看有没有能够在创建快捷方式的时候就考虑到这样的情况的可能性吧 = =

**Comment by KagamiChan** [comment]
然而看了一下有一些版本的安装程序并没有创建这个的样子，囧rz

**Comment by Nidhoggur1993** [comment]
@KagamiChan 恩你这么一提醒。。这个快捷方式好像是我自己丢桌面上的，似乎早期版本只会在开始菜单里丢一个快捷方式来着_(:з」∠)_
那这个issue应该可以close了，多谢~
