### ISSUE TITLE
資源の再利用&対空機銃量産 任務計數問題

### ISSUE THREAD

**Issue by Kikokushijo** [poooi/poi#1362]
**poi 版本 / poi version:** 7.4.1

**操作系统 / OS:** Windows 10

**插件名和版本 / Plugin name & version:** -

**你遇到了什么样的问题 / The problem you've met:**
資源の再利用　和　対空機銃量産　兩任務同時接取時，每廢棄一次機銃會造成前者計數一次加２。

**有没有重现的方法，或者与问题相关的任何信息 / The way to reproduce, or any information that might be related:** -

**Comment by KagamiChan** [comment]
@Kikokushijo 我来领锅了，呜呜呜

**Comment by yukixz** [comment]
@KagamiChan kagami背过了、咕咕咕

**Comment by KagamiChan** [comment]
3514aae1f12d35e103a3e132388f756ce33b2d82 修复了，请静候下一版更新
