### ISSUE TITLE
小提示 17 年度更新

### ISSUE THREAD

**Issue by KagamiChan** [poooi/poi#1367]
RT 快有一年多没有进行过维护了，是时候加一点新内容，并更正已经过时的信息了

当前小提示（删除线表示已经过时）：
    "“小提示”时常更新一些不容易注意到的小功能，不过你也可以在设置里关掉~",
    "欢迎关注我们的新浪微博 @今天poi出新版本了吗",
    "时常逛逛设置列表，看看有没有新插件，可能会发现新功能poi~",
    "任何防猫功能都有危险性，请慎重使用，慎重使用，慎重使用！",
    "使用poi的插件来减少查wiki吧——比如[远征信息]和[任务信息]",
    "poi保证绝不会修改发包或主动发包，但请使用可信的本体和插件",
    "快捷键Ctrl/Cmd+1/2可以切换概览面板和详细舰队面板",
    "快捷键Ctrl/Cmd+3/4/5/6/7/8可以切换插件",
    "快捷键Tab可以按顺序切换插件~",
    "舰队概览和详细舰队之间的切换也可以通过双击来进行！",
    "鼠标移到提督名会显示升级所需经验~",
    "资源低于低保线时，资源图标会发光哦",
    "poi的制空计算是包含了熟练度的，把鼠标移上去能看到详情~",
    "poi的索敌计算默认是33式，把鼠标移到索敌上能看到多种计算公式",
    "按下老板键可以立即隐藏游戏窗口，再按一下就恢复，可以在设置里启用",
    "任务计数器是保存在本地的，所以要一直使用同一台电脑才能正确计数",
    "屏幕太小放不下？设置里面可以缩放面板~",
    "在设置面板里面开启“关闭程序时提示”以避免误触关闭poi",
    "如果游戏有规律地卡死（特别是游戏大更新后），很可能需要删掉自定义缓存",
    ~~"尺寸自动适应慢的话很可能是代理的缘故，一般等两分钟就会好",~~
    "设置里面可以选择开启哪些通知，点击最右的箭头还能自定义通知详情",
    "在通知设置里，插件更新提示是由\"其它\"开关的。",
    "舰船大破提示音是由通知设置里的\"其它\"开启的，大破进击警告是由[未卜先知]插件提供的。",
    "在设置里试试切换成别的主题吧~！换一种颜色，换一种心情",
    "可以自定义poi启动时的主页啦！就在设置里地址栏右边哦",
    "右键点击设置里的“主页”按钮就能跳转到主页！",
    "基本设置里面的“高级功能”，如果不知道是什么请不要随便开启",
    "安装插件不顺的话，尝试在插件设置的高级设置里换一个npm服务器",
    "现在一些插件也添加了设置，去插件列表看看吧！",
    "想要截图带有装备名字的舰队？在[编成日记]里可以做到，还能直接把代码共享给朋友！",
    ~~"[未卜先知]里，双击可以切换显示舰船等级哦",~~
    "[未卜先知]里的MVP预测没有包含开幕航空战，因为娇喘没提供呢",
    "[海域血量]里的血条在下次选择出击地图时才能更新哦",
    "[远征信息]里把鼠标放到插件面板里三个舰队上还能看到远征收益信息~",
    "[航海日志]提供有搜索功能！看看自己已经大建了多少次，或出击了多少回活动图",
    "[舰娘信息]里可以直接点击表头进行排序啦~",

**Comment by KochiyaOcean** [comment]
@KagamiChan 感觉这些消息基本不会有人去看啊所以这么久没更新也没人吐槽

**Comment by KagamiChan** [comment]
从用户报错截图来看，一般没有关的居多

**Comment by KochiyaOcean** [comment]
@KagamiChan 关没关和看没看还是不一样的嘛

**Comment by KagamiChan** [comment]
计划加入内容：
使用电池供电的话，在不使用的时候将 poi 最小化能延长续航时间
Windows 用户可以在开始菜单中找到以安全方式打开 poi 的快捷方式
如果发现设置的魔改 / live2d 失效的话，在显示中将 Flash 窗口调整为 gpu 或 direct
想要更大的面板区域？在显示设置中调节面板区域的最小宽度 / 高度
poi 提供了触摸屏友好的网格插件1菜单，可以在显示设置中开启
现在可以在插件的高级设置中开启自动更新插件了
自动更新的 fcd 数据包括了地图与贴条等信息，，可以在关于 poi 的页面手动更新
poi 的主页是 http://poi.io，在上面能获得最新的 poi 版本
现在可以在基本设置中关闭最终战提示啦
