### ISSUE TITLE
做废弃装备任务的时候任务进度显示错误

### ISSUE THREAD

**Issue by ccen3020** [poooi/poi#1370]
**poi 版本 / poi version:**
7.4.1

**操作系统 / OS:**
windows 10

**你遇到了什么样的问题 / The problem you've met:**
终于有拆对空机枪的计数了……lol感谢开发的大大们
不过同时接拆24次装备和拆对空机枪两个任务，两个任务计数都是0
先拆对空机枪，拆一个机枪，拆24次装备的计数+2，拆机枪的计数+1
完成了拆机枪任务之后再拆其他装备，拆24次的任务计数就正确了
拆了6个机枪完成之后才拆的其他装备，没有测试两个任务都没有完成的时候会不会出现这个问题……

**Comment by KochiyaOcean** [comment]
@ccen3020 已修复

**Comment by KagamiChan** [comment]
多谢报告，已背锅修复，见 #1362

**Comment by ccen3020** [comment]
我就说怎么找不到了……
