### ISSUE TITLE
[一件多星] 作战信息相关的插件

### ISSUE THREAD

**Issue by KagamiChan** [poooi/poi#1374]
随着田中脑洞越来越多，poi 也需要增加更多的信息展示，不过由于 API 仍然随活动变化，并且本身界面为了显示这些信息也需要进行重写，所以综合计划是先发布一个新插件将基本功能实现，之后再进行整合（gugugu）。
计划中的功能包括~~然而只是计划，并不一定都有~~：
+ 陆航信息展示
  - 当前装备飞机，当前设置的状态
  - 是否疲劳，是否需要补充
  - 制空值与航程
  - 陆航是区分中部海域和活动海域的
+ 运输值，见 #1310 
+ 对空 CI 分析
+ 主炮适重分析
+ 昼夜战输出分析

目前缺少的，一方面是完整的资料整理，一方面是人月，所以没有一个确切的完成期限……

**Comment by yukixz** [comment]
@KagamiChan 两弹一星功勋kagami

**Comment by KagamiChan** [comment]
这次阈值改了之后适重显得没有卯月了，去掉……

**Comment by KagamiChan** [comment]
坑了，关了
