### ISSUE TITLE
20170317更新后水战增加了一个专属分类 无法计算制空 装备信息中图标也是缺少状态

### ISSUE THREAD

**Issue by castore** [poooi/poi#1375]
**poi 版本 / poi version:**
7.4.1

**操作系统 / OS:**
WIN7 X64 PRO

**插件名和版本 / Plugin name & version:**

**你遇到了什么样的问题 / The problem you've met:**
水战增加了一个专属分类 无法计算制空 装备信息中图标也是缺少状态

**有没有重现的方法，或者与问题相关的任何信息 / The way to reproduce, or any information that might be related:**

**Comment by KagamiChan** [comment]
@castore 多写报告，下一版会修正

**Comment by KagamiChan** [comment]
添加完毕，请静候下一版本
