### ISSUE TITLE
進入 DMM其他的遊戲 "社にほへと"時無法正確顯示

### ISSUE THREAD

**Issue by GibbsPan** [poooi/poi#1376]
**poi 版本 / poi version:**
v7.4.1

**操作系统 / OS:**
win7

**插件名和版本 / Plugin name & version:**
一心二用 v2.5.0

**你遇到了什么样的问题 / The problem you've met:**
進入 DMM其他的遊戲 "社にほへと"時無法正確顯示

**有没有重现的方法，或者与问题相关的任何信息 / The way to reproduce, or any information that might be related:**
由 http://www.dmm.com/netgame/ 進入點事前登錄時無法正確顯示，由其他瀏覽器事前登錄後再由一心二用進入仍無法正確顯示
![1](https://cloud.githubusercontent.com/assets/26485090/24045177/87b326c6-0b61-11e7-9cec-11de3591c519.jpg)

**Comment by KochiyaOcean** [comment]
临时处理的解决方法
右键开发者工具按 esc 出下栏， Network Condition 里面的 UA 选 Chrome
![image](https://cloud.githubusercontent.com/assets/8194131/24046931/3174b592-0b5f-11e7-89a9-12f1f65c43c0.png)

**Comment by KochiyaOcean** [comment]
2.6.0 已发布

**Comment by GibbsPan** [comment]
感謝您，更新之後已可正常登入
