### ISSUE TITLE
请问以后能做关于“战斗结束/进入夜战”的提醒吗？

### ISSUE THREAD

**Issue by d956381604** [poooi/poi#1380]
**poi 版本 / poi version:** v7.4.1

**操作系统 / OS:** Windows 8.1

**插件名和版本 / Plugin name & version:**  poi原生功能 i.e. none

**你遇到了什么样的问题 / The problem you've met:**
Multitasking 的时候肝船时常忘掉有舰队还在海图里，平时的习惯又是按老板键隐藏poi。 请问dalao能做 “战斗结束/进入夜战“ 的提醒吗（伸手）？ 还是这个没有什么价值做呢？

**有没有重现的方法，或者与问题相关的任何信息 / The way to reproduce, or any information that might be related:**

**Comment by KagamiChan** [comment]
有点没有理解你的描述，你是希望在什么情况下，发出什么样的提醒？如果没有这个提醒的话，对你造成了什么不便？

**Comment by d956381604** [comment]
哦，就是边肝船边查阅资料时需要暂时隐藏poi确保网页最大化，经常忘掉舰队还在出击，所以很多时候战斗结束敌方残兵时忘记去操作界面点一下不追击，如果没有船大破的话poi浏览器不会进行提醒。
也就是想要在这个界面进行提醒:
http://i.imgur.com/2UCCtca.png
没有的话经常等到远征队回来了才记起来舰队在出击中，比较浪费时间...

**Comment by KagamiChan** [comment]
感觉能做的就是增加一个久战提示，进入海域或者进入演习 15 分钟之后每隔 5 分钟提示一下，这种 = =

**Comment by d956381604** [comment]
也挺不错的啊！
不过我需要 close and comment 呢， 还是关掉之后这个enhancement label会消失？

**Comment by KagamiChan** [comment]
我只是提一个想法，具体怎么实现还是需要讨论的，所以留着 open 就行

**Comment by dislido** [comment]
一个简单的方法：
打开开发者模式，输入
var a = setInterval(() => { notify('提醒'); }, 600000);
每10分钟提醒一次
clearInterval(a);
关闭提醒

**Comment by KagamiChan** [comment]
战斗结束已经有了
