### ISSUE TITLE
i18n for update message

### ISSUE THREAD

**Issue by KagamiChan** [poooi/poi#1382]
Formerly, poi checks update through requesting `http://${global.SERVER_HOSTNAME}/update/latest.json`, then picks and renders the update message in HTML via `dangerouslySetInnerHTML`. This is not so elegant as it
- is not localized
- has a risk of XSS attack (though the connection will be redirected to HTTPS at poi server)

-------
From poi 7.5.0, new update check procedure will be:
1. check `https://${global.SERVER_HOSTNAME}/update/latest.json` for latest version number,
1. if there's an update and it is unknown to user, download `https://${global.SERVER_HOSTNAME}/update/${currentLang}.md` for update information,
1. render the markdown content in modal.

We will not touch any raw HTML things, and the rendering uses react-remarkable, which disables HTML by default, so it is safer.

For every new release, one has to update:
- latest.json
- zh-CN.md / zh-TW.md / en-US.md (ko-KR will fallback to en-US)

**Comment by yukixz** [comment]
@KagamiChan https？
