### ISSUE TITLE
在3/27强风改实装后 装备信息插件的装备信息读取错误问题

### ISSUE THREAD

**Issue by SenbonKuma** [poooi/poi#1384]
**poi 版本 / poi version:**
7.4.1

**操作系统 / OS:**
win10

**插件名和版本 / Plugin name & version:**
装备信息 Ver. 2.2.0

**你遇到了什么样的问题 / The problem you've met:**
在3/27装备强风改实装后 在未锁定强风改的情况下 装备信息插件只显示已锁定装备信息 锁定强风改的情况下 只显示未锁定装备信息

**有没有重现的方法，或者与问题相关的任何信息 / The way to reproduce, or any information that might be related:**
首先上锁强风改 打开装备信息插件 发现全部装备列表为空 在点击筛选项的锁定/未锁定图标后 装备刷出 发现所显示装备为全部为未锁定装备 反之 解锁强风改 再按如上步骤操作之后 发现所显示装备全部为锁定装备 推断所实装的新装备「強風改」与其他装备存在冲突

**Comment by KagamiChan** [comment]
装备信息插件正在改造中 - - 烦请耐心等待

**Comment by SenbonKuma** [comment]
@KagamiChan  好的 dalao辛苦了

**Comment by KagamiChan** [comment]
@SenbonKuma 现在装备信息插件改造完毕了，请问还有类似的问题吗。虽然感觉应该没有了，不过我没有强风改没法确认

**Comment by SenbonKuma** [comment]
@KagamiChan 该问题在次日校验缓存之后便得到解决 推测装备信息插件的装备显示与游戏游戏缓存是否加载完毕有关 在次月战果先行发放一式战时该类似问题有再次发生 重新加载缓存之后解决。
至于结论...我觉得插件本身应该是没有问题的 应该缓存来背锅...只要缓存将新实装装备的缓存加载出来 插件就能正常运作了
