### ISSUE TITLE
晚上无法用poi打开网页

### ISSUE THREAD

**Issue by GX-9900-DV** [poooi/poi#1385]
**poi 版本 / poi version:**
7.4.1

**操作系统 / OS:**

WIN10
**插件名和版本 / Plugin name & version:**
poi本体

**你遇到了什么样的问题 / The problem you've met:**
打开浏览器无限加载网页一直黑屏，只能清除Cookies后重启电脑重新登录，而且掉线之后无法刷新，输入特定网站也无法跳转

**有没有重现的方法，或者与问题相关的任何信息 / The way to reproduce, or any information that might be related:**
![Uploading IL`)Q4[01F]81{BM@{%AJ@I.png…]()
![Uploading LP5HR1~3~MQJ~]$F0{WOO1Y.png…]()
![Uploading 20(14FYBO}$L~S)YVN[FR9Y.png…]()

**Comment by KagamiChan** [comment]
请提供开发者工具 console 选项卡的截图
