### ISSUE TITLE
macOS 12.4 内嵌浏览器的flash部分会不断闪烁

### ISSUE THREAD

**Issue by jilulu** [poooi/poi#1387]
**poi 版本 / poi version:** v7.4.1
**操作系统 / OS:** macOS 12.4
**插件名和版本 / Plugin name & version:** 未安装

**你遇到了什么样的问题 / The problem you've met:**
内嵌浏览器的flash部分会不断闪烁，其他部分则没有问题。

**有没有重现的方法，或者与问题相关的任何信息 / The way to reproduce, or any information that might be related:** 不确定是不是个例，同样出现问题的话请在issue下方留言。
升级macOS12.4后才出现此问题，试过完全删除后重新安装，未解决问题。

**Comment by liangzhenduo0608** [comment]
![ezgif com-crop 1](https://cloud.githubusercontent.com/assets/9461191/24402411/0c32c884-13eb-11e7-8a3e-6f148b283099.gif)

我系统升10.12.4后有时会出现图中白色噪点

**Comment by KochiyaOcean** [comment]
这种情况看起来是苹果吃吧的可能性比较大啊……

**Comment by KochiyaOcean** [comment]
总之去设置里开 / 关下硬件加速看看

**Comment by jilulu** [comment]
感谢回复。

其实提 issue 之前就试过关硬件加速，并没有用。

发自我的 iPhone

**Comment by KochiyaOcean** [comment]
@jilulu 那就只能等苹果 || Adobe 发新版修复了

**Comment by KagamiChan** [comment]
同样，与硬件加速无关，同时非游戏界面部分在关闭硬件加速后也可能会花
很大概率是苹果的锅了，electron 也有一定可能性

**Comment by KochiyaOcean** [comment]
基本上证实是 macOS 12.4 的 bug 了……

**Comment by KagamiChan** [comment]
黑苹果上没发现这样的问题，囧rz

**Comment by theNded** [comment]
同样的闪烁问题；在Chrome浏览器下flash运行正常

**Comment by KochiyaOcean** [comment]
@theNded 确认一下 Chrome 的 Flash 版本比较好……如果有条件的话可以把 poi 的那个 flash 文件替换掉

**Comment by theNded** [comment]
@KochiyaOcean 感谢提醒。
Chrome PepperFlashPlayer.plugin版本为25.0.0.127；
poi的版本（在Resources/PepperFlash/mac-x64文件夹中）为24.0.0.194。
替换该文件夹下的PepperFlashPlayer.plugin及manifest.json后问题未解决。

**Comment by KochiyaOcean** [comment]
@theNded 目前 poi 正式版的内核还是 Chromium 54，可能与此有关

**Comment by theNded** [comment]
@KochiyaOcean 明白了，我的Chrome版本是56.0.2924.87
辛苦您了！

**Comment by jilulu** [comment]
**开发者这两天发布新版本辛苦了！**

在我的机器（`MacBookPro11,4`）上使用最新版本的 poi (`v7.5.1`) 似乎没有闪烁的问题了。
重启游戏仍然没有问题。
