### ISSUE TITLE
关于浏览器语言选项的问题

### ISSUE THREAD

**Issue by Ryuuen** [poooi/poi#1391]
**poi 版本 / poi version:**
7.4.1

**操作系统 / OS:**
Win10 Pro

**插件名和版本 / Plugin name & version:**
装备改修3.3.3

**你遇到了什么样的问题 / The problem you've met:**
非常感谢开发者的辛勤劳动。

Poi浏览器似乎是根据系统语言设置浏览器语言的。当系统语言为日语的时候，浏览器界面显示为日语。
然而，打开装备改修这个插件的时候，里面显示的好像是日语和韩语的混合，这样就看不懂了，如果可以的话希望能修正一下。
参考图：
![default](https://cloud.githubusercontent.com/assets/7549347/24453585/7137de08-14c3-11e7-9b66-337acdb86447.png)

其实最好能在浏览器里面设置一个语言选项，比如在日语系统下也能显示中文。

**有没有重现的方法，或者与问题相关的任何信息 / The way to reproduce, or any information that might be related:**

**Comment by KochiyaOcean** [comment]
@Ryuuen 初始设置可能有问题，请手动切换一次语言

**Comment by Ryuuen** [comment]
@KochiyaOcean  将语言重新切换了一遍之后，日语系统状态下，该插件的显示没有发生变化。

**Comment by KochiyaOcean** [comment]
@Ryuuen 重开一下

**Comment by Ryuuen** [comment]
@KochiyaOcean 切换语言的过程中是需要注销的，涉及了关闭与重新开启程序的过程。

**Comment by KagamiChan** [comment]
@Ryuuen 在改修插件上按 ctrl + shift + i，看看 console 里面有没有什么报错，同时输入`console.log(config.get('poi.language'), window.language)` 运行的话，结果是什么？

**Comment by KochiyaOcean** [comment]
@Ryuuen 啊…… 我说的是 poi 设置里面的不是系统设置的

**Comment by Ryuuen** [comment]
@KagamiChan 没有报错，当时的结果是 
console.log(config.get('poi.language'), window.language)
VM1106:1 undefined "ja"
undefined

@KochiyaOcean 原来在程序里面是能修改语言的啊，不知道我以前为什么没找到，这里重新选择后就好了。

现在有个关于航海日志插件的问题，求问大大们我是重新开个issue比较好还是直接在这里提？

**Comment by KagamiChan** [comment]
麻烦重新开吧
