### ISSUE TITLE
关于航海日志插件的问题

### ISSUE THREAD

**Issue by Ryuuen** [poooi/poi#1392]
poi 版本 / poi version:
7.4.1

操作系统 / OS:
Win10 Pro

**插件名和版本 / Plugin name & version:**
航海日志6.0.1 

**你遇到了什么样的问题 / The problem you've met:**
1. 航海日志里面，有多条战斗记录会被吞掉，显示不出来，比如：

筛选海域为4-5，有十几条记录被吞掉了

![default](https://cloud.githubusercontent.com/assets/7549347/24456069/c24fa614-14cc-11e7-8b0e-bf2c0211f286.png)

或者跳转到150页，不做筛选，也有多条记录消失

![default](https://cloud.githubusercontent.com/assets/7549347/24456097/e1e07b48-14cc-11e7-8ad2-9bc5602d4452.png)

2. 航海日志内时间显示错误。

这是当时在冬季活动期间发现的，不止一个。当时有截图，不过现在这些记录查询不到了（可能就是跟上面的情况一个道理，有些记录会被吞）

时间显示有问题，出现大于等于60的时间：

![default](https://cloud.githubusercontent.com/assets/7549347/24456222/4e930e18-14cd-11e7-87a5-60591b0aeae3.png)

**有没有重现的方法，或者与问题相关的任何信息 / The way to reproduce, or any information that might be related:**

**Comment by Ryuuen** [comment]
补充一点关于记录被吞的细节。

被吞的记录很可能还是存在于数据库中的，可以用特定的方法查看。

比如，在刚才4-5的截图中，一些记录被吞。

如果筛选掉落为 清霜 ，那么会出现这么个情况，比对一下时间，在刚才筛选4-5记录中本应出现但却没有出现的记录出现了：（实际上是磨血的时候接连掉了两个）

![default](https://cloud.githubusercontent.com/assets/7549347/24458375/b7e1b9fe-14d3-11e7-8e16-28f89d663f5f.png)

但如果直接根据时间排序，不作任何筛选，跳到那个时间的页面，结果还是麻耶这条记录：

![default](https://cloud.githubusercontent.com/assets/7549347/24458445/e3b021d8-14d3-11e7-875a-3c20025dc84c.png)

**Comment by JenningsWu** [comment]
这问题是由于新版航海日志 (ver >= 6.0.0) 与旧版 poi (ver < 7.4.0) 不兼容导致航海日志收到的战斗时间是错误的。这个不兼容大概就发生在二月低三月初。7.4.0 版 poi 正式发布之后已经不会再有这个问题了。

关于如何让吞掉的数据显示出来：
%APPDATA%/poi/plugins/akashic-records 下，找到你的 id，进去然后进 attack，打开对应要修改的数据，会发现很多数据的第一列那些数据（表示时间）是相同的。此时应当念一首诗， +1s 或者 -1s 让他们不同。

关于时间显示错误，存在 60min/60s：
这是之前 v6.0.0-beta.7 日志的 bug，v6.0.0 开始已经修正了。
