### ISSUE TITLE
[Feature Enhancement] 进入改装界面自动切换到舰队面板

### ISSUE THREAD

**Issue by wafer-li** [poooi/poi#1393]
先赞一个最近更新的这个自动切换功能 👍

但是，根据我将近一年的使用来看，舰队面板通常是用于检查装备情况的，而不是用来看舰队编成的

舰队编成一般只需在概览界面就可以获取到足够的信息，而对于舰娘的整体装备情况，则需要进入舰队界面进行查看。

所以最好在进入改装界面的时候也进行自动切换。

**Comment by yukixz** [comment]
@wafer-li 改装界面没有 API ...

**Comment by wafer-li** [comment]
😂  好吧，没仔细看
