### ISSUE TITLE
航海日誌 資源 圖表問題

### ISSUE THREAD

**Issue by mcmcmmc** [poooi/poi#1395]
**poi 版本 / poi version:**
7.4.1, 剛剛更新了 7.5.0 beta.0 也是一樣

**操作系统 / OS:**
Win 10

**插件名和版本 / Plugin name & version:**
航海日誌 Ver 6.0.1

**你遇到了什么样的问题 / The problem you've met:**
在航海日誌-->資源-->圖那一板, 不論我按"還原/按天顯示/顯示節點/睡眠模式"都沒有任何變動, 但可以剔除資源,圖表亦有更新
有嘗試過移除重裝也是一樣

**有没有重现的方法，或者与问题相关的任何信息 / The way to reproduce, or any information that might be related:**
請見下圖console capture:
http://i.imgur.com/oVrRlO0.jpg

Thanks 大佬!!!

**Comment by JenningsWu** [comment]
Fixed.
