### ISSUE TITLE
水战未计入制空值

### ISSUE THREAD

**Issue by DSakura1987** [poooi/poi#1396]
**poi 版本 / poi version:**
7.4.1

**操作系统 / OS:**
Windows 10 Version 1607， Build14393.953

**插件名和版本 / Plugin name & version:**
（考虑可能为本体的错误）

**你遇到了什么样的问题 / The problem you've met:**
舰队装备的水战全部没有计算制空值，舰队总制空显示为0。实际装备2个二式水战改和2个RO.44

**有没有重现的方法，或者与问题相关的任何信息 / The way to reproduce, or any information that might be related:**
此错误可稳定重现，在重启POI之后依旧。所有水战显示为一个乌龟图标，并且没有相应格子的最大搭载数。

DevTools 控制台信息：
Scheduling daily refresh at 331200000 (now 1491056945017)
D:\poi\resources\app.asar\views\components\settings\parts\others.js:101 No newer version of map: current 2017/02/13/01, remote 2017/02/13/01, mode default
D:\poi\resources\app.asar\views\components\settings\parts\others.js:101 No newer version of maphp: current 2016/08/20/01, remote 2016/08/20/01, mode default
D:\poi\resources\app.asar\views\components\settings\parts\others.js:101 No newer version of shiptag: current 2017/02/12/01, remote 2017/02/12/01, mode default
D:\poi\resources\app.asar\views\components\settings\parts\others.js:108 Update fcd from https://poi.io/fcd/ successfully in mode default.
D:\poi\resources\app.asar\views\services\update.js:36 Remote version: 7.4.0. Current version: v7.4.1
D:\poi\resources\app.asar\views\env-parts\devtool-message.js:16 This is poi@v7.4.1 on win32 x64 with Electron@1.4.15, 
        PLUGINS: poi-plugin-prophet@6.6.0, poi-plugin-expedition@3.1.0, poi-plugin-quest-info@3.2.2, poi-plugin-senka-calc@4.2.2, poi-plugin-map-hp@3.0.6, poi-plugin-item-improvement@3.3.3, poi-plugin-ship-info@2.3.2, ItemInfo@2.2.0, poi-plugin-new-window@2.6.0, poi-plugin-subtitle@0.5.7, 
        FCD: map@2017/02/13/01, maphp@2016/08/20/01, shiptag@2017/02/12/01

**Comment by KagamiChan** [comment]
@DSakura1987 因为水战上次维护中换了新分类的原因，7.5.0beta 已修复
