### ISSUE TITLE
7.5.0 版本中出现的 app.asar.unpacked 文件夹的问题

### ISSUE THREAD

**Issue by KagamiChan** [poooi/poi#1398]
7.5.0 版本中，出现了部分资源无法被 asar 打包的情况，导致在 windows 上由于文件路径过长而无法正常解压与安装。
![image](https://cloud.githubusercontent.com/assets/3816900/24604534/ae4089da-1897-11e7-8aa1-9d707f619fc9.png)
该问题的引入是在 5bb77be19b5bbe0369e04ff883c4dca99113ad67 之中，对于 npm dependency 的更新。在 npm/npm/pull/15774 之中，引入了 update-notifier，其依赖中包含有 `term-size` native module，无法被 asar 打包。
在目前情况下，需要使用 npm 4.4.0 之前的版本作为依赖

**Comment by KochiyaOcean** [comment]
Fixed by https://github.com/poooi/poi/commit/24530b1857432a20b823e077cf7b32525103be45
