### ISSUE TITLE
20170405更新后所有敌舰ID变化 无法识别

### ISSUE THREAD

**Issue by castore** [poooi/poi#1400]
**poi 版本 / poi version:**
v7.5.0-beta.0

**操作系统 / OS:**
win7 professional x64

**插件名和版本 / Plugin name & version:**
未卜先知

**你遇到了什么样的问题 / The problem you've met:**
20170405更新后所有敌舰ID增加了1000 无法识别

**有没有重现的方法，或者与问题相关的任何信息 / The way to reproduce, or any information that might be related:**

**Comment by yukixz** [comment]
@castore 无法识别什么
