### ISSUE TITLE
第一下載後是可以用到的,其後再次開啟便沒有反应

### ISSUE THREAD

**Issue by Momoses** [poooi/poi#1402]
**poi 版本 / poi version:**
7.5.2

**操作系统 / OS:**
win7

**插件名和版本 / Plugin name & version:**
poi本体
[](url)

**你遇到了什么样的问题 / The problem you've met:**
第一下載後是可以用到的,其後再次開啟便沒有反应 , 開了开发者工具 Console 选项卡 , error 有47個 , warning   ##有3個

![](https://cloud.githubusercontent.com/assets/26994374/24786050/120c487c-1b91-11e7-80d7-cc2875ee3226.png)

**有没有重现的方法，或者与问题相关的任何信息 / The way to reproduce, or any information that might be related:**

**Comment by KochiyaOcean** [comment]
尝试在资源管理器里进入 `%appdata%/poi` 删除里面的 `plugins` 文件夹然后进入 poi 重新安装插件看看

**Comment by Momoses** [comment]
source 嗎?

**Comment by KochiyaOcean** [comment]
直接在地址栏里输入就行

**Comment by Momoses** [comment]
對不起,對programing沒甚麼認識

**Comment by KochiyaOcean** [comment]
哦抱歉忘记切换用词了…… 台湾似乎是叫 档案总管 来着？

**Comment by KagamiChan** [comment]
也可以按 win + R，在弹出的窗口里面输入 `%appdata%/poi`，再确认，也可以打开这个文件夹

**Comment by Momoses** [comment]
其實我是香港的 haha 


![problem 2](https://cloud.githubusercontent.com/assets/26994374/24786238/80e0060c-1b92-11e7-8a14-97723ffc7f9a.png)

**Comment by KagamiChan** [comment]
资源管理器是平常用来看电脑里面的文件档案的那个

还是不行的话，试试开始菜单里面的 poi (safe mode)，进入 poi 之后把扩展程式都升级一下

**Comment by Momoses** [comment]
ok , delete了 pluguins , poi-plugin-subtitle也要delete嗎?

**Comment by KochiyaOcean** [comment]
不用了，现在再打开然后重新下载一遍插件看看

**Comment by Momoses** [comment]
ok

**Comment by Momoses** [comment]
有種watchdog 駭客的感覺,很神奇

**Comment by Momoses** [comment]
行了,感謝你們,好好加油,其實我是中Bug 嗎?


![problem 2](https://cloud.githubusercontent.com/assets/26994374/24786356/5dad590e-1b93-11e7-812b-12437cefbd61.png)

**Comment by KochiyaOcean** [comment]
@Momoses 感觉应该是由于某些谜之原因导致插件文件损坏……比如下载中途由于网路原因中断之类

**Comment by Momoses** [comment]
原來如此

**Comment by Momoses** [comment]
oh

**Comment by Momoses** [comment]
重曡了......

![problem 2](https://cloud.githubusercontent.com/assets/26994374/24786699/27c35444-1b96-11e7-8d70-4a784b231f54.png)

**Comment by KochiyaOcean** [comment]
@Momoses 还是开开发者工具看看报错吧，最好截的全一点……

**Comment by Momoses** [comment]
很長

**Comment by Momoses** [comment]
![problem 2](https://cloud.githubusercontent.com/assets/26994374/24786824/f2f67d08-1b96-11e7-99cf-22c708311b4c.png)

**Comment by Momoses** [comment]
藍色是分開用的,怕我 自已眼花

**Comment by KochiyaOcean** [comment]
看来是 易及远征 出问题了，我去调查一下……

**Comment by Momoses** [comment]
![problem 3](https://cloud.githubusercontent.com/assets/26994374/24786879/4d0be864-1b97-11e7-9ef6-a36c063b19a9.png)

**Comment by KagamiChan** [comment]
@Momoses 或者在安全模式下能不能打开

**Comment by KochiyaOcean** [comment]
看起来你的第四舰队并没有开启？可能是因为这个导致了易及远征的崩溃

**Comment by Momoses** [comment]
剛剛在非安全開了,開不到
![problem 4](https://cloud.githubusercontent.com/assets/26994374/24787056/914cb692-1b98-11e7-97bb-50f94b5bea92.png)

**Comment by KagamiChan** [comment]
那……就跑到 `%appdata%/poi` 下面，把 plugins 档案夹里的 poi-plugin-ezexped 先删掉……

**Comment by Momoses** [comment]
安全模式下也重疊了

![problem 5](https://cloud.githubusercontent.com/assets/26994374/24787123/096aef04-1b99-11e7-94fe-557a59b20f66.png)

**Comment by KochiyaOcean** [comment]
总之暂时删除易及远征…… 之后发布修复无多舰队的版本的时候会说一下的

**Comment by Momoses** [comment]
poi-plugin-ezexped  刪除了

**Comment by KochiyaOcean** [comment]
之后还能启动么

**Comment by Javran** [comment]
问题应该已经修了,马上会发布新版本,issue先开着确认没问题了再关(才知道可以跨repo关issue
