### ISSUE TITLE
7.5.2的hidpi调整不完全

### ISSUE THREAD

**Issue by pcsjx** [poooi/poi#1403]
**poi 版本 / poi version: 7.5.2

**操作系统 / OS: Windows 10

**插件名和版本 / Plugin name & version:**

**你遇到了什么样的问题 / The problem you've met:
在Surface Pro 4的200%DPI下，其他界面可以通过把缩放100%改为200%、分辨率长宽各乘2达到原来的显示效果，但是显示字幕的状态栏和截图按钮等部分固定为100%缩放倍率，在200%下看起来非常小。

**有没有重现的方法，或者与问题相关的任何信息 / The way to reproduce, or any information that might be related:**

**Comment by KochiyaOcean** [comment]
目前暂时是这样的情况，未来会做调整

**Comment by KagamiChan** [comment]
顺便问一下，sp4 上面的 200% 缩放是否满足了需求，需不需要有更大的缩放百分比

**Comment by pcsjx** [comment]
SP4的系统默认DPI缩放就是200%，所以200%够用了。如果有4K显示器的可能会需要更高的缩放比。

**Comment by EdiTurn** [comment]
**关于此问题的进一步反馈**

1. 由插件打开的独立窗口在 7.5.2 中也不受面板大小设置影响，看起来非常小。

2. 我主要采用远程桌面的方式玩游戏（为了满足插件数据的一致性），会在几个不同缩放设置的显示设备上去连接到运行 poi 的主机。
由于在 7.5.2 上，面板的显示大小不再受系统级的缩放设置影响，因此我不得不频繁改动面板的缩放设置。
希望未来能够改进缩放的控制策略，如以“读取的系统缩放比例”×“用户在 poi 中设置的自定义比例” 来决定面板的显示大小。

**Comment by KochiyaOcean** [comment]
@EdiTurn 由于涉及到舰娘等 webview 元素的表示导致系统托管的缩放非常蹩脚故没有使用的打算

**Comment by EdiTurn** [comment]
@KochiyaOcean 我的意思是，poi 去读取系统的缩放设置（如 200%），再乘以用户在 poi 设置的面板缩放尺寸（如 105%），来作为实际的显示缩放比例，当然缩放处理仍旧由程序自身进行。

另一个建议：对于设置面板缩放的滑块，能否在松开鼠标左键后再改变界面大小？现在会一边拖动一边改变大小，一不小心就会跳到 200%。

**Comment by KochiyaOcean** [comment]
@EdiTurn 这样显示还是比较容易造成误解的，不过考虑将系统设置作为默认值考虑
难以实现

**Comment by KochiyaOcean** [comment]
读取系统缩放设置暂时还没找到什么方法，不过其他的都已经实现了就先 close 吧

**Comment by KagamiChan** [comment]
还有 zoom 的范围，以及 zoom 滚动条的 laziness

**Comment by KagamiChan** [comment]
OK

**Comment by KochiyaOcean** [comment]
应用了刚才的 commit 的 build 可以在 https://ci.appveyor.com/project/KochiyaOcean/poi/build/1.0.1272/artifacts 下载到，如果诸君方便还是麻烦测试一下

**Comment by KagamiChan** [comment]
等到有更多的测试结果前，暂时先打开吧
