### ISSUE TITLE
Poi在高分辨率屏幕中如何等比例调整大小

### ISSUE THREAD

**Issue by maomaohenmao** [poooi/poi#1407]
**poi 版本 / poi version:**
7.5.2

**操作系统 / OS:**
Window 10

**你遇到了什么样的问题 / The problem you've met:**
今天更新了Poi。由于电脑是3K屏幕，分辨率高，所以将窗口等比例调大到200%，可是出现了菜单栏不调整的问题。

![3 tz8e1 t udtiw e y](https://cloud.githubusercontent.com/assets/23692871/24843810/0c644bd8-1d5b-11e7-850e-1cd2bb299f45.png)
不知道有没有什么好的解决办法，上一个版本7.4就没有问题。 谢谢！

**Comment by KochiyaOcean** [comment]
Dumplicated issue https://github.com/poooi/poi/issues/1403
