### ISSUE TITLE
About HiDPi

### ISSUE THREAD

**Issue by ilikecola** [poooi/poi#1408]
**poi 版本 / poi version:**
v7.5.2

**操作系统 / OS:**
Windows 10 RS

**你遇到了什么样的问题 / The problem you've met:**
initial start cannot auto change dpi setting. But previous version can do that.
It's manually setting or just a bug?
Thanks!

System DPI setting 200%, poi initial setting 100%.In 4K screen it's too small....

**Comment by KagamiChan** [comment]
possibly dup with #1403, please take a screenshot for better identifying. 
Please try the builds on https://ci.appveyor.com/project/KochiyaOcean/poi/build/1.0.1272/artifacts, will it fit better?

**Comment by ilikecola** [comment]
Thanks.Main window fit better but not plugin....like inside browser.

**Comment by KagamiChan** [comment]
Which plugin？Plugins have not yet catched up with this update, we are collecting feedbacks

**Comment by ilikecola** [comment]
built-in browser
