### ISSUE TITLE
POI在Mac上会闪啊闪？

### ISSUE THREAD

**Issue by were** [poooi/poi#1410]
**poi 版本 / poi version:** 7.5.2

**操作系统 / OS:** OS X 10.12

**插件名和版本 / Plugin name & version:** General

**你遇到了什么样的问题 / The problem you've met:**

我POI在右边插件切换的时候，整个屏幕会闪白条。貌似是在我装完新的远征插件之后，POI就开始闪了。

**有没有重现的方法，或者与问题相关的任何信息 / The way to reproduce, or any information that might be related:**

**Comment by were** [comment]
现在的状态：重启之后时好时坏。

**Comment by KagamiChan** [comment]
和 #1387 一样，属于上水果版本的问题。虽然这几天我又观察不到了

**Comment by were** [comment]
我不仅flash会闪。整个屏幕都会。上半个整个屏幕都闪得瞎。

**Comment by KagamiChan** [comment]
确定是和这个插件有关么，如果禁用了就不闪？

**Comment by were** [comment]
不是很确定。我禁用了也会闪。

启用了现在也不闪了。

但是第一次闪是装了新的插件。

**Comment by KagamiChan** [comment]
应该只是巧合吧 - -

**Comment by gnattu** [comment]
已知问题：https://bugs.chromium.org/p/chromium/issues/detail?id=359108#c42
Chromium把它标记为`wontfix`,那么poi这里应该就没有什么能做的了。
此问题似乎就是chrome和macOS的多GPU切换（抑或是独显驱动）有关。

两个可能可行的workaround：

1. 关闭硬件加速
2.禁用macOS的多显卡切换（如果有），有只使用核显不出现此问题的报告出现

**Comment by were** [comment]
你们是咋知道我这两天回坑了。

这两天还被这个问题又折腾了。

昨天试着关闭了硬件加速（是不是关了要重启poi啊？

今天暂时没问题了（希望不是乱立flag。

**Comment by KochiyaOcean** [comment]
@were 需要重启

**Comment by were** [comment]
那work了！今天不闪了！
