### ISSUE TITLE
高DPI时显示缩放不正确

### ISSUE THREAD

**Issue by zeropad** [poooi/poi#1412]
**poi 版本 / poi version:7.5.2

**操作系统 / OS:Windows10 64-bit

**插件名和版本 / Plugin name & version:**

**你遇到了什么样的问题 / The problem you've met:**

我用2880*1920的平板玩，系统一般是200%显示缩放。更新7.5.2之后没有正确缩放，程序变得很小。现在我只能调Poi的缩放，但是通知栏和那几个按钮不能调整。而且poi的缩放比例有限，全屏使用的时候很尴尬。

**有没有重现的方法，或者与问题相关的任何信息 / The way to reproduce, or any information that might be related:**

**Comment by KagamiChan** [comment]
duplicate with #1403

**Comment by KagamiChan** [comment]
这是由于内核升级的原因而进行的改动，我们已经调整了放大的上限，同时也对通知栏和按钮进行了调整，你可以试用一下这里面的开发版，看看有没有解决你的问题 https://ci.appveyor.com/project/KochiyaOcean/poi/build/1.0.1285/artifacts

**Comment by KochiyaOcean** [comment]
如果可能的话我需要一个 1.4.1 和 1.5.1（不是 1.5.2）的主界面截图，没有高分辨率显示器没法评估高 DPI 策略改变后的影响

**Comment by zeropad** [comment]
7.5.2的截图
![7 5 2](https://cloud.githubusercontent.com/assets/14156303/25042652/26786738-215d-11e7-847a-2044b2f8c92b.png)
![7 5 2](https://cloud.githubusercontent.com/assets/14156303/25042651/2677a8fc-215d-11e7-9a37-aa59240b140f.png)
7.5.1的截图
![7 5 1](https://cloud.githubusercontent.com/assets/14156303/25042655/2ea63430-215d-11e7-820a-54e9c824869d.png)
![7 5 1](https://cloud.githubusercontent.com/assets/14156303/25042657/2ed1b434-215d-11e7-88a7-300cd36d3666.png)
7.4.1的截图
![7 4 1](https://cloud.githubusercontent.com/assets/14156303/25042663/37e7ca22-215d-11e7-9796-df5794b9c0ac.png)
![7 4 1](https://cloud.githubusercontent.com/assets/14156303/25042664/382492ea-215d-11e7-8a1d-9e865b4b9e6a.png)

**Comment by KochiyaOcean** [comment]
@zeropad 多谢

**Comment by zeropad** [comment]
@KochiyaOcean 应该多谢你们
