### ISSUE TITLE
我能以任何形式得到apireq这类信息的dump么？

### ISSUE THREAD

**Issue by were** [poooi/poi#1417]
如题，这回我不是遇到了任何poi使用上的问题。

**Comment by KochiyaOcean** [comment]
@were dbg.enableExtra("gameResponse")

**Comment by were** [comment]
然后哪里看log呢？

**Comment by were** [comment]
按照`command-line-args.md`里面说的。
我`npm start -- --debug-extra=gameResponse`了，啥也没得到啊在terminal里面。

**Comment by were** [comment]
> poi@7.5.2 start /Users/were/poi
> electron . "--debug" "--debug-extra=gameResponse"

[DEBUG] Debug Mode
[DEBUG] Extra Option: gameResponse
[DEBUG] Config loaded from: , /Users/were/Library/Application Support/poi/config.cson
[DEBUG] Debugging Flash Loader
[ERROR] Could not load 'PepperFlashPlayer.plugin' from: 
/Users/were/PepperFlash/mac-x64
[DEBUG] Loading Pepper Flash Player: 
/Users/were/poi/PepperFlash/mac-x64/PepperFlashPlayer.plugin
[DEBUG] Pepper Flash Player version: 24.0.0.194
[INFO] Proxy listening on 54251
[DEBUG] Registering shortcut: Ctrl+Shift+I	=> Open Focused Window Dev Tools
/Library/Caches/com.apple.xbs/Sources/AppleGVA/AppleGVA-10.1.16/Sources/Slices/Driver/AVD_loader.cpp: failed to get a service for display 4 
NOT SANDBOXED
Vector smash protection is enabled.
[ERROR] Error: write EPIPE

**Comment by yukixz** [comment]
@were 左下角齿轮点开开发者工具、console

**Comment by were** [comment]
我有可能将这个dump到文件么？

**Comment by yukixz** [comment]
没有直接方法。你可以利用 nodejs api 和 js api 实现

**Comment by KochiyaOcean** [comment]
参照文档
```js
window.addEventListener('game.response', function (e) {
  e.detail.method // HTTP 方法(POST / GET)
  e.detail.path // API 路径
  e.detail.body // 返回的数据包
  e.detail.postBody // 发送的数据包
})
```
在函数里用 fs 写入到文件就行了，开心愉快
