### ISSUE TITLE
Bad DPI with macOS

### ISSUE THREAD

**Issue by wafer-li** [poooi/poi#1418]
**poi 版本 / poi version:**
4e7c362e8f3fb96332edb24c2dfb945adb23d5d4

**操作系统 / OS:**
macOS 10.11.6

**你遇到了什么样的问题 / The problem you've met:**
![image](https://cloud.githubusercontent.com/assets/12459199/25163713/3bda4968-2507-11e7-99e5-90f566caf3d1.png)

**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:**
Initial start, no error in console

**Comment by KagamiChan** [comment]
你的 mac 是 retina 屏幕吗，有没有外接显示器？在 console 里面运行 `require('electron').screen.getPrimaryDisplay().scaleFactor` 得到的结果是多少？或者把 `require('electron').screen.getPrimaryDisplay()` 的结果展开看一下

**Comment by wafer-li** [comment]
retina，外接 1080p 显示器。

好难复制啊，能不能写成 ``` 的形式？

**Comment by KagamiChan** [comment]
嗯我的错……没有办法直接看结果
那就 `_.map(require('electron').screen.getAllDisplays(), disp => disp.scaleFactor)` 的结果吧

**Comment by wafer-li** [comment]
![image](https://cloud.githubusercontent.com/assets/12459199/25164092/bd4c5962-2509-11e7-8ff5-fbc6cd553275.png)

**Comment by KagamiChan** [comment]
在我们修复之前，可以手动调整一下缩放倍率，这个是因为设置没有值所以默认用了结果里面的这个 2
