### ISSUE TITLE
拖拽文件或链接到 webview 上时会载入文件或链接

### ISSUE THREAD

**Issue by KagamiChan** [poooi/poi#1422]
原来的 `webview` 上写的 `ondrop` `preventDefault()` 已经无效

目前已经进行过的尝试：
- `$('webview')` 上监听 `ondrop` / `ondrag` 进行 `preventDefault`
- `$('webview').shadowRoot.querySelector('object')` 上监听 `ondrop` / `ondrag` 进行 `preventDefault`
- `webview-preload.js` 内进行 `document`/`window` 上监听 `ondrop` / `ondrag` 进行 `preventDefault`

估计可行的就是在 `will-navigate` 事件处进行拦截，然而正常情况下也会有跳转，并且为了测试网络联通性/玩别的游戏/当作浏览器来用，也会进行一些跳转

**Comment by shakugannoaria** [comment]
7.6.0版舰队界面装备小图标也有拖拽问题，会跳转。。。先把小图标拖拽效果取消掉如何

**Comment by KagamiChan** [comment]
@shakugannoaria 多谢指出……试试这里的版本 https://ci.appveyor.com/project/KochiyaOcean/poi/build/1.0.1405/artifacts 是不是解决了界面内元素可以拖拽的问题

**Comment by shakugannoaria** [comment]
解决了，感谢~（话说好快）
