### ISSUE TITLE
关于 poi 每次更新后的面板错位问题

### ISSUE THREAD

**Issue by EdiTurn** [poooi/poi#1424]
**poi 版本 / poi version:**
似乎与版本无关

**操作系统 / OS:**
Windows 10 Pro 15063.138

**你遇到了什么样的问题 / The problem you've met:**
每次更新 poi 的版本，面板均存在微小的显示错位，如图所示：
![-1](https://cloud.githubusercontent.com/assets/5492805/25186186/0a106e30-2552-11e7-83c5-e3cf6dd93d7d.png)

此次 7.6.0 更新后错位尤其严重，如图：
![screenshot_20170419-225258](https://cloud.githubusercontent.com/assets/5492805/25186566/1aa6318e-2553-11e7-933a-2fe22f414b32.png)

重启 poi 可恢复正常。

**Comment by KochiyaOcean** [comment]
其实开一个新窗口的插件就能恢复布局
原因不明……

**Comment by EdiTurn** [comment]
是的，因为 7.6.0 上不得不重启所以来反映一下。

**Comment by KagamiChan** [comment]
以前的版本里 windows 上按两下 alt 或者改变下窗口大小，触发重新布局就能好

**Comment by KagamiChan** [comment]
这个是只要弹出 welcome 就会有的，以前一直觉得不是很严重就没管
https://ci.appveyor.com/project/KochiyaOcean/poi/build/1.0.1303/artifacts
如果还会切换版本的话可以试试这里面提供的版本

**Comment by EdiTurn** [comment]
试了试，看起来是没有问题了，谢谢。
