### ISSUE TITLE
windows10 高分辨率屏幕下字体过小

### ISSUE THREAD

**Issue by dyzdyz010** [poooi/poi#1429]
**poi 版本 / poi version:** v7.5.2

**操作系统 / OS:** Windows 10 1607

**插件名和版本 / Plugin name & version:**

**你遇到了什么样的问题 / The problem you've met:**
安装新版本的poi后，文字变得非常小，面板区域还可以缩放比例，但是字幕区文字不可以，导致在高分辨率屏幕上表现极差。

屏幕分辨率为**3840x2160**，系统文本缩放比例为**200%**

**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:**

![qq 20170423111933](https://cloud.githubusercontent.com/assets/1324420/25310444/e79b73c8-2816-11e7-88a6-cb5b1a412754.png)

![qq 20170423112004](https://cloud.githubusercontent.com/assets/1324420/25310461/4e9a8aaa-2817-11e7-93cb-00c9f5039895.png)

**Comment by KochiyaOcean** [comment]
@dyzdyz010 更新到 7.6.0-beta.0

**Comment by dyzdyz010** [comment]
@KochiyaOcean 安装 7.6.0-beta.0 后正常了
