### ISSUE TITLE
slow startup on poor network

### ISSUE THREAD

**Issue by Javran** [poooi/poi#1430]
**poi 版本 / poi version:** latest master branch

**操作系统 / OS:**

**插件名和版本 / Plugin name & version:**

**你遇到了什么样的问题 / The problem you've met:**

startup is very slow on poor network: it gets stuck on a white screen for a long while before it starts to function which can be solved by disconnecting right before starting poi and reconnecting back after the program starts functioning.

**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:**

would suggest timeout things that require network connection or use asynchrous methods.

**Comment by KagamiChan** [comment]
如果在国内的话可能是 google fonts 的加载，不过既然你在国外……
你换个不带 google font 的主题看看？比如 darklykai

**Comment by Javran** [comment]
darklykai好像挺快...什么原因?

**Comment by KagamiChan** [comment]
#956 是不是可以再讨论了，至少，自己维护一个去除 google font 的主题库什么的……

**Comment by Javran** [comment]
也就是说可能是font的问题吗,有没什么cache的方法?

**Comment by KagamiChan** [comment]
@Javran 并不能完全确认，只能说有可能吧……但是你不用翻墙，理论上 google font 是卡不了的

**Comment by Javran** [comment]
@KagamiChan 现在在用wife比较慢,回去再确认一下. 我之前是在已经开了程序的情况下改主题再重启的,不知道会不会已经有一些cache机制在起作用了.
