### ISSUE TITLE
poi目录更改到onedrive 

### ISSUE THREAD

**Issue by seagullyyx** [poooi/poi#1432]
你好，我想问问是否可以将耗子记录，编程记录等的记录存档位置改到onedrive folder?
目前似乎只有航海日志提供这个功能。
我能理解这是插件不能改的问题。

或者 poi是否支持将C:\Users\sanvn\AppData\Roaming\poi 这个目录 更改到C:\Users\sanvn\OneDrive\Poi ,这样不单航海日志可以，所有的插件都能支持云储存了。

因为平常在外用平板，在家用台式 所以希望能将记录合在一起

**Comment by KochiyaOcean** [comment]
建立一个符号链接就行了
`MKLINK /D %appdata%/poi C:\Users\sanvn\OneDrive\Poi`
