### ISSUE TITLE
[Feature Request] OpenDB integration.

### ISSUE THREAD

**Issue by c933103** [poooi/poi#1433]
KanColle OpenDB is a multilingual drop/construction/development/improvement/expedition database, that support Chinese and English among various other languages. 
It could be nice to allow users report their data to the database if they wish to do so with an opt-in mechanism, by providing such functionality in an existing or new plugin.

**Comment by yukixz** [comment]
You can make a poidb dump and import data into KCODB.

**Comment by KagamiChan** [comment]
note that poi ship drop records are a little different, poi's reporter (too simple, sometimes naïve) dose not check if there's enough ship/item slot. So the drop rate on normal maps will be biased, while for event maps the game has checks at map start so it seems OK.

**Comment by WolfgangKurz** [comment]
Please DO NOT MIGRATE or PUT IN another database data into OpenDB.
