### ISSUE TITLE
Win10中poi無法開啟

### ISSUE THREAD

**Issue by dcfvgb123456** [poooi/poi#1434]
poi 版本 / poi version: 7.5以上

操作系统 / OS: win10 1607

你遇到了什么样的问题 / The problem you've met:

poi在第一次打開時是沒問題的，第二次以後的開啟就完全沒有視窗，只剩下工作管理員中的處理程序。
7.4版本是可以使用的，從7.5以上的版本都會出現這個問題。

**Comment by KochiyaOcean** [comment]
@dcfvgb123456 win + R 在弹出的窗口中输入 cmd，在弹出的窗口里把 poi.exe 拖进去回车看看

**Comment by dcfvgb123456** [comment]
[INFO] Proxy listening on 57134 
只有這行就不再跑了

**Comment by KochiyaOcean** [comment]
@dcfvgb123456 https://ci.appveyor.com/project/KochiyaOcean/poi/build/1.0.1346/artifacts 这个版本看看有没有问题？

**Comment by dcfvgb123456** [comment]
@KochiyaOcean 
一樣無法開啟
cmd訊息也是差不多的

**Comment by KochiyaOcean** [comment]
@dcfvgb123456 把 %appdata%/poi 里面的 config.cson 改个名会如何？ %appdata%/poi 也改名呢

**Comment by dcfvgb123456** [comment]
@KochiyaOcean  
config.cson改名後一樣不能開啟
poi改名後開啟 他會創建一個空的poi資料夾 然後一樣不能開啟

**Comment by KochiyaOcean** [comment]
@dcfvgb123456 https://github.com/electron/electron/releases/tag/v1.6.6 这里下载的可以打开么

**Comment by dcfvgb123456** [comment]
@KochiyaOcean 
剛剛我打開時沒反應，於是我重啟電腦
重啟後electron和poi都可以打開，但是我關閉了electron和poi後，第二次開啟就沒有反應了，electron也是

**Comment by KochiyaOcean** [comment]
@dcfvgb123456 看来是上游的问题…… Windows 是最新的版本么

**Comment by dcfvgb123456** [comment]
@KochiyaOcean 
剛剛少了一個    適用於 x64 系統Windows 10 Creators Update 隱私權設定 (KB4013214)  的更新
我更新完了

**Comment by KagamiChan** [comment]
@dcfvgb123456 你按一下 win + R，输入 winver 然后点击确定，打开的 windows 版本窗口信息里面显示的是哪个版本？

**Comment by dcfvgb123456** [comment]
@KochiyaOcean 
版本1607 (OS組建 14393.1066)
WIN10家用版

**Comment by KagamiChan** [comment]
@dcfvgb123456 请问你是用的是 7z 压缩档的版本还是安装程式的版本？

**Comment by dcfvgb123456** [comment]
@KochiyaOcean 7z版本

**Comment by KagamiChan** [comment]
@dcfvgb123456 麻烦试一下这里的版本： https://ci.appveyor.com/project/KochiyaOcean/poi/build/1.0.1347/artifacts
当然可能还是需要重启一次

**Comment by dcfvgb123456** [comment]
@KochiyaOcean 
這個版本在重啟後連第一次開啟都失敗了0.0

**Comment by KagamiChan** [comment]
@dcfvgb123456 这个呢？
https://ci.appveyor.com/project/KochiyaOcean/poi/build/1.0.1348/artifacts

在我这里下载了打开，和再次打开是没有问题的，我现在的 windows 版本是 1703 creators upodate。你下载的是哪个 7z 档，然后电脑上有没有装什么资安软件呀

**Comment by dcfvgb123456** [comment]
@KochiyaOcean 
我下載的是 dist\poi-7.6.0-beta.1-win.7z
版本也是1073，電腦上並沒有安裝防護軟體0.0
但依然是不能開啟

**Comment by KochiyaOcean** [comment]
@dcfvgb123456 如果 electron 本体也没法启动的话就是上游问题了，等待 electron 或者 Windows Creators Update 推送吧

**Comment by dcfvgb123456** [comment]
@KochiyaOcean 好的，那我先用32的版本，感謝你

**Comment by dcfvgb123456** [comment]
@KagamiChan 回來看才發現一直tag另外一名作者，真的很抱歉......

**Comment by KagamiChan** [comment]
没事~我们这边是能够看到消息更新的

**Comment by zfwei1999** [comment]
我也遇到了同样的问题，而且是一开始用的正常，忽然就变成一个小视窗了，下老版的7.2也不行，也是win10

**Comment by zfwei1999** [comment]
@KagamiChan

**Comment by KagamiChan** [comment]
@zfwei1999 听你的描述并不是同样的问题，请单开 issue 详细描述一下吧

**Comment by gnattu** [comment]
请问现在版本是否还有这个问题？
如果是，[这里版本](https://ci.appveyor.com/project/KochiyaOcean/poi/build/artifacts)能否复现？
