### ISSUE TITLE
QAQ上不去了

### ISSUE THREAD

**Issue by PatchouliQ** [poooi/poi#1436]
**poi 版本 / poi version:**
poi-7.6.0-win-x64

**操作系统 / OS:**
win7

**插件名和版本 / Plugin name & version:**
poi-7.6.0-win-x64

**你遇到了什么样的问题 / The problem you've met:**
我的poi加载不进去黑屏

**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:**

**Comment by KochiyaOcean** [comment]
QUQ 我不知道你在讲什么

**Comment by PatchouliQ** [comment]
![Uploading image.png…]()

**Comment by KagamiChan** [comment]
TuT 图没传上来。
请说一说自己是用什么上网方式上舰的呀

**Comment by PatchouliQ** [comment]
用win7=.=用poi上,之后我谷歌浏览器能上,就是poi打不开

**Comment by PatchouliQ** [comment]
![Uploading DOF2F(L1FHM9M@)0FDRYK5A.png…]()

**Comment by KochiyaOcean** [comment]
@PatchouliQ 等图片传上去以后再点发布……

**Comment by PatchouliQ** [comment]
![dof2f l1fhm9m 0fdryk5a](https://cloud.githubusercontent.com/assets/27882064/25629640/c6444b2c-2f9c-11e7-90f9-678dd50fe74a.png)

**Comment by PatchouliQ** [comment]
上传好了

**Comment by KochiyaOcean** [comment]
@PatchouliQ 进 %appdata%/poi/plugins 删掉，插件重新下载

**Comment by PatchouliQ** [comment]
好的谢谢

**Comment by KagamiChan** [comment]
解决了吗

**Comment by PatchouliQ** [comment]
解决了谢谢大家!!
