### ISSUE TITLE
調整希望: 超連結拖曳問題

### ISSUE THREAD

**Issue by mcmcmmc** [poooi/poi#1437]
**poi 版本 / poi version:**
ver 7.6.0

**操作系统 / OS:**

win 10.0 build10240
**插件名和版本 / Plugin name & version:**
N/A

**你遇到了什么样的问题 / The problem you've met:**
更新到7.6.0版之後, 當在POI 操作界面時不小心點擊後拖曳到遊戲畫面後再放手,網址會轉到該連結去.
如下圖:
http://i.imgur.com/H9XwCy3.png

這個有點不便,如果有可能的話希望可以在設定裡選擇停用?
不然打到尾關再手賤一下又要重打了orz

**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:**

如上,感謝大佬,順祝活動順利!

**Comment by mcmcmmc** [comment]
不好意思...剛剛才看看到跟你的#1422 內容一樣..請無視掉這個#1437吧

**Comment by KagamiChan** [comment]
poi 原来是有这个阻止拖拽的设置的，但是某个版本之后就失效了，并且暂时找不到既有效又便利的替代方法……只能先搁置了
不过原本还不知道还可以拖拽的……别人告诉我我才注意到

也祝你武运昌隆
