### ISSUE TITLE
触屏变双击

### ISSUE THREAD

**Issue by zeropad** [poooi/poi#1441]
**poi 版本 / poi version:7.6.0

**操作系统 / OS:win10 14393.1066

**插件名和版本 / Plugin name & version:**

**你遇到了什么样的问题 / The problem you've met:**
触屏变双击，在出击和编成换页的时候特别明显。 
只在触摸操作的时候会有该问题，必现。用笔和鼠标的时候很正常。换回7.5.2该问题消失。

**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:**

[-1493924635266.zip](https://github.com/poooi/poi/files/977285/-1493924635266.zip)

**Comment by KochiyaOcean** [comment]
dup issue https://github.com/poooi/poi/issues/1423

**Comment by KochiyaOcean** [comment]
离下个版本发布还有一些工作，可以先去 https://ci.appveyor.com/project/KochiyaOcean/poi/build/artifacts 下载开发版
