### ISSUE TITLE
CPU使用率偏高

### ISSUE THREAD

**Issue by bigshawn1478** [poooi/poi#1443]
#

**poi 版本 / poi version:**
v7.6.0

**已安裝插件**
遠征資訊 v3.1.0
任務信息 v3.2.3
秘書通知 v0.7.1
裝備改修 v4.0.0

**操作系统 / OS:**

OS: win10 1607
CPU: i5-3470
RAM: 16G DDR3-1600
VGA:RX 480 8GDDR5

**你遇到了什么样的问题 / The problem you've met:**
忘記在哪次改版後，CPU的使用率就變得比以前高
常常只開艦娘的程式，CPU就進入滿載狀態
有試過在工作管理員那停用使用率最高的那個process，測出來結果是flash的那個process的關係
想請教一下，這是我電腦的問題還是程式優化的問題?

**Comment by KochiyaOcean** [comment]
@bigshawn1478 设置里是否有禁用硬体加速？

**Comment by bigshawn1478** [comment]
@KochiyaOcean  已經禁用了

**Comment by KochiyaOcean** [comment]
@bigshawn1478 禁用的话 CPU 占用肯定比不占用的高……

**Comment by smlrx1** [comment]
@KochiyaOcean  bigshawn1478的问题应该和硬件加速无关。一般人不会在早期版本开启硬件加速而在较新版本中关闭硬件加速，所以你的解释没有解决该问题。
我的poi是从7.5.0开始变卡的（未开启硬件加速，早期显卡不开启反而效果更好）。经测试，如果以安全模式开启poi的话就不会出现变卡的现象，所以初步怀疑是由插件造成的（具体哪个或哪几个还不清楚）。poi 7.4.1就没有该问题。

**Comment by KagamiChan** [comment]
@smlrx1 如果可以的话麻烦定位一下是哪几个插件，最好也说一下计算机配置。计算机配置不一样，使用感受也是不同的

**Comment by smlrx1** [comment]
@KagamiChan 抱歉，前几天忙于海域搜救神威，一直未能测试。
注：在活动前我一直使用ooi的在线缓存进行游戏，活动期间由于ooi不稳定，我更改为代理连接方式进行游戏，poi版本一直为7.4。
昨天采用7.7的版本进行测试，发现插件并不是导致卡顿的原因，主要原因是ooi的在线缓存。

一开始采用的是代理连接的方式，逐项开启某一插件直至我日常的所有插件均开启（12个），均无卡顿现象。后又多次重开poi（运行12个插件），也没有重复出卡顿现象。后又采用7.6版本（12个插件）也没有卡顿现象。
之后切换到ooi的在线缓存（7.7，12个插件），卡顿现象立即出现。采用安全模式同样也有卡顿现象。
综上，初步推断卡顿现象可能和ooi的在线缓存有关。

P.S.前述回复所说的“以安全模式开启poi的话就不会出现变卡的现象”是在7.5的版本中发现的，但此次未能在7.5版本中重复出该现象。
