### ISSUE TITLE
Bad style of landbase

### ISSUE THREAD

**Issue by wafer-li** [poooi/poi#1444]
**poi 版本 / poi version:**
bbf98a9c924731556697d906a0e55d9ccba36cb4

**操作系统 / OS:**
macOS 10.11.6

**你遇到了什么样的问题 / The problem you've met:**

![image](https://cloud.githubusercontent.com/assets/12459199/25772053/eb457e84-329c-11e7-9ffd-642baf6b84f2.png)

**Comment by wafer-li** [comment]
顺便提一下显示设置吧

![image](https://cloud.githubusercontent.com/assets/12459199/25772070/4664eebc-329d-11e7-83d4-b0c9f3a68f39.png)

**Comment by KochiyaOcean** [comment]
没看懂……

**Comment by wafer-li** [comment]
@KochiyaOcean 
这里这行字没显示完。

![image](https://cloud.githubusercontent.com/assets/12459199/25773206/5ad212b4-32b4-11e7-8e4d-7ecec71d606a.png)

**Comment by KochiyaOcean** [comment]
@wafer-li 纵向也不能滚动？
没开第三个机场不是很清楚

**Comment by wafer-li** [comment]
是的。
