### ISSUE TITLE
windows 上的通知可能會喚醒睡眠模式

### ISSUE THREAD

**Issue by KagamiChan** [poooi/poi#1446]
因為提示音是獨立於通知播放的，因此會在某些設備上使聲卡喚醒，從而中斷睡眠模式

可行的解決方法：記錄系統是否處於睡眠狀態，並且增加“睡眠狀態下不播放聲音”的選項
https://github.com/electron/electron/blob/master/docs/api/power-monitor.md#event-suspend

**Comment by yukixz** [comment]
Web Notification 不支持sound我也很绝望啊

**Comment by yukixz** [comment]
别增加选项了

**Comment by KagamiChan** [comment]
有些人就喜歡睡眠時候被喚醒然後起來收發遠征呢……
