### ISSUE TITLE
有个奇怪的信息消除不掉

### ISSUE THREAD

**Issue by ccen3020** [poooi/poi#1447]
**poi 版本 / poi version:**
7.6.0

**操作系统 / OS:**
windows 10 64bit 10.0.14393

**你遇到了什么样的问题 / The problem you've met:**

![image](https://cloud.githubusercontent.com/assets/5616211/25777727/90b29e4e-3318-11e7-9dfd-e1fb45d1f4d9.png)
如上图，不知道是哪来的提示……
消不掉，也不知道怎么复现……
与左边框保持固定距离

**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:**

![image](https://cloud.githubusercontent.com/assets/5616211/25777748/4f616c80-3319-11e7-9b65-a1887a3c9d37.png)

**Comment by KochiyaOcean** [comment]
泊地修理的 tooltip，切换到那边去鼠标移动一下应该就可以了
不算是程序性的 bug 的一个小问题吧……
