### ISSUE TITLE
当截图目录指向的文件夹不存在时，无法打开目录选择窗口

### ISSUE THREAD

**Issue by EdiTurn** [poooi/poi#1453]
**poi 版本 / poi version:**
7.7.0-beta1

**操作系统 / OS:**
Windows 10 1703

**你遇到了什么样的问题 / The problem you've met:**
当截图目录指向的文件夹实际不存在时，在设置中点击相应地址无法弹出目录选择窗口，只能手动修改配置文件。
缓存目录我偷懒没试，不知道是不是有同样的问题。

**Comment by KochiyaOcean** [comment]
@EdiTurn macOS 上无法重现， 应该和 Windows 的相关实现有关

**Comment by KochiyaOcean** [comment]
@EdiTurn 是否有报错？

**Comment by EdiTurn** [comment]
![screenshot_20170511-190830](https://cloud.githubusercontent.com/assets/5492805/25946413/93cf047e-367d-11e7-9a0e-3de1a58b5071.png)

**Comment by KochiyaOcean** [comment]
@EdiTurn 与其说是文件夹不存在应该讲是整个分区不存在啊…… 只是文件夹不存在的时候是能处理的
