### ISSUE TITLE
对于显示布局的建议

### ISSUE THREAD

**Issue by Ryuuen** [poooi/poi#1454]
**poi 版本 / poi version:**
7.7.0

**操作系统 / OS:**
Win 10 1703

**插件名和版本 / Plugin name & version:**

**你遇到了什么样的问题 / The problem you've met:**
在显示设置中，勾选了“切分组件与插件面板”后，组件与插件只能同时位于主界面的左边、右边或者是下面。

然而空间有限，这样显示的话会有一些内容被隐藏，需要滚动鼠标滚轮才能看见。

如果可以的话，能否开发一个功能，使得组件面板和插件面板能够分开，比如，组件面板在主界面下方，插件面板在主界面右边？这样的话就能够利用比较多的空间了。

大概是这样的：
![image](https://cloud.githubusercontent.com/assets/7549347/25958437/896778a8-36ab-11e7-8cc8-88ab9d4bfd7c.png)

**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:**

**Comment by KochiyaOcean** [comment]
不太好写……
而且窗口必须在某种特定比例下才能比较好看……

**Comment by EdiTurn** [comment]
@KochiyaOcean 可否增加 flash 在底部的纵向布局，以方便在手机上竖屏使用？其余三种目前都有了。

**Comment by KochiyaOcean** [comment]
@EdiTurn 不是吧我本来就是觉得这种布局没人用所以才不加的……

**Comment by EdiTurn** [comment]
@KochiyaOcean 以前试过手机竖屏远程，虽然游戏界面比较小倒还不至于会按错，但游戏界面在屏幕顶部却不太方便。 ~~大拇指太短~~
作为~~要求特别多的~~奇葩用户真是对不起！

**Comment by KochiyaOcean** [comment]
@EdiTurn https://github.com/poooi/poi/compare/e54382e06630...915526513355

**Comment by Ryuuen** [comment]
嘛，其实吧，如果各个模块，比如资源、远征、建造/入局这样的，可以随意拖动改变位置的话就最好了，用户可以自己设定布局。
不过这个好像很难实现的样子。。

**Comment by KochiyaOcean** [comment]
@Ryuuen 主要是现在 poi 的各种组件和插件的设计师就是写死在一个地方的，实现不难实现就是麻烦……

**Comment by Ryuuen** [comment]
@KochiyaOcean 啊，写在一个地方就没什么办法了。
不过，poi浏览器现在是功能越来越多，我觉得单一模块后利用更多的空间可能是一个发展趋势吧。
不过，这大概就是卫星了吧。

**Comment by EdiTurn** [comment]
@KochiyaOcean 工作正常，暂未发现什么异常。

**Comment by Kirayao** [comment]
![image](https://user-images.githubusercontent.com/1212154/27515022-24b76cd6-59d5-11e7-90f2-5506fa2568c0.png)
這一塊空間可以拿來放擴充功能的面板嗎?
目前的切分只有左右切 但是面板在左右的時候是上下切比較自然

**Comment by KagamiChan** [comment]
@Kirayao 大家的使用习惯不一样，有像这样最大化的；但是有正常大小窗口搜小到游戏区域上下无黑边的，概览面板的这个高度是差不多正好适合这种情况

**Comment by Kirayao** [comment]
所以我是希望可以多一個水平分割面板的選項 
對於全螢幕的使用者整體感會好很多
