### ISSUE TITLE
编成日记看不到打洞放的装备

### ISSUE THREAD

**Issue by KagurasakaAkuryou** [poooi/poi#1455]
**poi 版本 / poi version:**7.7.0 x64

**操作系统 / OS:**Windows 10 Pro 64bit 1703

**插件名和版本 / Plugin name & version:**编程日记 v3.10.3

**你遇到了什么样的问题 / The problem you've met:**编成日记看不到打洞放的装备

**Comment by NotoOotori** [comment]
请问一下这个问题现在解决了吗
