### ISSUE TITLE
近代化改造任务问题

### ISSUE THREAD

**Issue by Wei98** [poooi/poi#1460]
**poi 版本 / poi version:**
v7.7.0

**操作系统 / OS:**
masOS

**插件名和版本 / Plugin name & version:**

**你遇到了什么样的问题 / The problem you've met:**
接取日常任务近代化改造后改造一次就出现猫的情况，任务也被修改为完成

**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:**

<img width="803" alt="screen shot 2017-05-17 at 9 57 31 am" src="https://cloud.githubusercontent.com/assets/21072746/26135315/4a3d417c-3ae7-11e7-816f-8fc8b4d20b4a.png">

**Comment by KochiyaOcean** [comment]
@Wei98 目前知道的情况是连击改修的确定按钮会导致重复发包而猫，至于为什么这个按钮会允许重复发包则暂不可知

**Comment by Wei98** [comment]
@KochiyaOcean 那请问为什么任务会被修改为完成？

**Comment by KochiyaOcean** [comment]
@Wei98 连续发了两个包并且都被判定成功了，任务计两次，然后你客户端因为重复发包的原因猫了……

**Comment by KochiyaOcean** [comment]
@Wei98 总之因为原因不明所以目前的解决方法是改修的确定按钮不要连击而只是点一次

**Comment by Wei98** [comment]
@KochiyaOcean 好的，谢谢

**Comment by KagamiChan** [comment]
outdated
