### ISSUE TITLE
下方信息栏有错位现象

### ISSUE THREAD

**Issue by AkitsukiYuu** [poooi/poi#1461]
poi 版本 / poi version:7.7.0

操作系统 / OS:win7

**你遇到了什么样的问题 / The problem you've met:**
下方的信息栏（就是显示演习、近代化改修、开发信息的地方）可能错位了，满5条信息之后，最上方的几个像素在收起状态下也无法隐藏（会多出一条绿色或黄色）

**Comment by KagamiChan** [comment]
请问你使用的是哪个主题？
试试看这里面的版本是不是好了
https://ci.appveyor.com/project/KochiyaOcean/poi/build/1.0.1448/artifacts

如果还是有问题的话麻烦截一下图看一下

**Comment by AkitsukiYuu** [comment]
@KagamiChan 主题是Paperdark，用了您提供的版本已经没有问题了

**Comment by KagamiChan** [comment]
哦，那就好，下个版本应该就能修复了
