### ISSUE TITLE
7.7版本用了什么黑科技么，直接用不了，开发者工具报错具体如下

### ISSUE THREAD

**Issue by Lin-Yiheng** [poooi/poi#1462]
**poi 版本 / poi version:**7.7

**操作系统 / OS:** win10 15063.296

**插件名和版本 / Plugin name & version:**

**你遇到了什么样的问题 / The problem you've met:** 7.7跑不起来

**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:** 就是7.7的问题，之前版本正常，秉承用新不用旧的原则来问问

![](http://i1.piimg.com/588926/6c99ee7d09449c73.png)

**Comment by KochiyaOcean** [comment]
@Lin-Yiheng win+r 输入 %appdata%/poi 删除 local storage 文件夹

**Comment by Lin-Yiheng** [comment]
回复好快，完美解决了。
