### ISSUE TITLE
poi 7.8.0 changelog

### ISSUE THREAD

**Issue by KagamiChan** [poooi/poi#1463]
## 功能
- [Windows] 增加自动更新功能
  - 建议使用安装包
  - Linux 和 mac OS 暂不支持
- [Windows] [mac OS] 优先使用系统的 flash player
- 加入第四种界面布局（垂直，游戏界面位于下方）
- 重写了命令行界面，原有的 `--debug` 参数更改为 `--dev` / `-d`，`--debug-extra` 更改为 `--dev-extra` / `--extra`
- 加入 google analytics 统计，可以在设置中进行关闭
- 为保证升级本体程序后的插件兼容性，现在插件默认将自动更新到最新版本
- 增加月常任务 `輸送船団護衛を強化せよ` 的支持

## 修正
- 修正某些情况下，插件载入的是系统目录，而非 poi 本体目录的依赖，而导致的出错
- [linux] 修正 poi 内按钮打开的魔改目录路径大小写不正确的错误
- 分辨率支持的更新与修正
---------
### 装备信息
- 重构，并加入了基地航空队装备飞机的支持

### 签名生成
- 原来的签名生成网站已经停止维护，更新地址为在维护的另一分支 http://www.sanya.moe/kcbadge/

**Comment by AkitsukiYuu** [comment]
装备信息3.0.4版本关闭时貌似会把窗口的坐标和大小信息保存到config.cson中的ShipInfo条目下，应该是保存到ItemInfo条目下才对

**Comment by KagamiChan** [comment]
多谢指出……手滑了
