### ISSUE TITLE
舰队详情中婚舰的油弹提示

### ISSUE THREAD

**Issue by Ryuuen** [poooi/poi#1465]
**poi 版本 / poi version:**
7.7.0

**操作系统 / OS:**
Win10 1703

**插件名和版本 / Plugin name & version:**

**你遇到了什么样的问题 / The problem you've met:**
婚舰在补充油弹时，会有大约15%的节省，然而在面板中油弹的数字是按照婚前计算的。
![image](https://cloud.githubusercontent.com/assets/7549347/26255069/787e9dfc-3cf3-11e7-8467-391540b04a7a.png)

**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:**

**Comment by KochiyaOcean** [comment]
因为油弹节省是在补给阶段才会发生的所以是这么显示的，实际上 API 给的油弹的量依然是原值。
这是游戏本身的机制，为了避免歧义不做另外的处理。

**Comment by KagamiChan** [comment]
fix by af0ee23

**Comment by KagamiChan** [comment]
![image](https://cloud.githubusercontent.com/assets/3816900/26259096/08ef6c12-3cfa-11e7-814a-e93c18f905be.png)
