### ISSUE TITLE
浏览器无法载入

### ISSUE THREAD

**Issue by Ryuuen** [poooi/poi#1467]
**poi 版本 / poi version:**

**操作系统 / OS:**
Win 10 1703
**插件名和版本 / Plugin name & version:**

**你遇到了什么样的问题 / The problem you've met:**
打开后，浏览器卡在如下的画面，无法载入。
旧版本可以运行。
![image](https://cloud.githubusercontent.com/assets/7549347/26305379/fdb141d6-3f29-11e7-9a2d-33d96523cec8.png)

求问一个解决的办法，谢谢。

**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:**

**Comment by KochiyaOcean** [comment]
@Ryuuen 删除 `%appdata%/poi/local storage`
开发版已经修复可能导致该问题的代码
