### ISSUE TITLE
HElp

### ISSUE THREAD

**Issue by Alan0811** [poooi/poi#1468]
**poi 版本 / poi version:**7.7.0

**操作系统 / OS:**win10

**插件名和版本 / Plugin name & version:**

**你遇到了什么样的问题 / The problem you've met:**

![image](https://cloud.githubusercontent.com/assets/28862556/26305451/e68bfb16-3f21-11e7-94b2-f84a2a7bb183.png)
我開了poi,但是沒反應.

**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:**

**Comment by Amaki316** [comment]
我出现了同样的问题

**Comment by KagamiChan** [comment]
请通过开始菜单的 poi (safe mode) 打开 poi，之后就能回复正常
如果找不到这个快捷方式的话，请打开 `%appdata%/poi`，然后把 local storage 文件夹删掉并重新启动

**Comment by wafer-li** [comment]
删除 Local Storage 之后成功启动，不过报了一个错：

![image](https://cloud.githubusercontent.com/assets/12459199/26305926/456d455e-3f2c-11e7-9862-9a2dce4b4df0.png)

**Comment by KochiyaOcean** [comment]
@wafer-li 正常情况

**Comment by KochiyaOcean** [comment]
Fixed.
