### ISSUE TITLE
黑屏

### ISSUE THREAD

**Issue by meowingss** [poooi/poi#1469]
**poi 版本 / poi version:7.8.0 beta**

**操作系统 / OS:Win 7**

**插件名和版本 / Plugin name & version:**

**你遇到了什么样的问题 / The problem you've met:**

![image](https://cloud.githubusercontent.com/assets/28867602/26313433/73429bf8-3f3d-11e7-827f-8b90da1d2411.png)
完全開不了

**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:**

**Comment by l12436** [comment]
把poi-plugins-translate刪掉就會正常了

**Comment by meowingss** [comment]
在那兒？

**Comment by KochiyaOcean** [comment]
有开发者工具截图么……

**Comment by meowingss** [comment]
![image](https://cloud.githubusercontent.com/assets/28867602/26314669/4736e830-3f41-11e7-832d-c83fb8a08129.png)

**Comment by KochiyaOcean** [comment]
@meowingss 
![image](https://cloud.githubusercontent.com/assets/8194131/26314688/58c8b15a-3f41-11e7-9a52-5e4265d00799.png)
这部份麻烦截全一点（点 console 标签页）

**Comment by meowingss** [comment]
![image](https://cloud.githubusercontent.com/assets/28867602/26314776/98fcaeca-3f41-11e7-9e42-08e2e6ce3ad5.png)

**Comment by KagamiChan** [comment]
还是麻烦重新启动一下 poi，把带有红色的错误信息的那部分截一下

**Comment by meowingss** [comment]
![image](https://cloud.githubusercontent.com/assets/28867602/26314934/1f930f56-3f42-11e7-9713-56d1849bd900.png)
![image](https://cloud.githubusercontent.com/assets/28867602/26314972/38bbe566-3f42-11e7-82ae-39a80879911f.png)
![image](https://cloud.githubusercontent.com/assets/28867602/26314987/4751389c-3f42-11e7-916d-d32b84d429c4.png)
![image](https://cloud.githubusercontent.com/assets/28867602/26314995/4f07d55a-3f42-11e7-95e2-c41636dbf08e.png)

**Comment by meowingss** [comment]
請問該怎麼辦

**Comment by KochiyaOcean** [comment]
@meowingss 麻烦测试一下 https://ci.appveyor.com/project/KochiyaOcean/poi/build/1.0.1464/artifacts 是否还有这个问题？（正在 build，请稍等一下 Orz

**Comment by meowingss** [comment]
可以了！
