### ISSUE TITLE
在macos上的啟動問題，版本7.7.0

### ISSUE THREAD

**Issue by nekoNep** [poooi/poi#1470]
**poi 版本 / poi version:**

7.7.0
**操作系统 / OS: MACOS Sierra 10.12.4（16E195）**

**插件名和版本 / Plugin name & version:**

**你遇到了什么样的问题 / The problem you've met:**

軟件不能夠啟動，當在如圖的畫面上。

**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:** 有試過重裝軟件和重啓電腦，不能解決
<img width="1440" alt="2017-05-23 0 02 25" src="https://cloud.githubusercontent.com/assets/28868725/26315661/cf0d7da4-3f4c-11e7-904a-de5220cdbbb4.png">
<img width="1440" alt="2017-05-23 0 10 32" src="https://cloud.githubusercontent.com/assets/28868725/26315674/d78f013c-3f4c-11e7-9a74-1edfd01fb93a.png">

**Comment by KagamiChan** [comment]
请删除 ` ~/Library/Application\ Support/poi/plugins/` 文件夹然后重新打开 poi，插件重新安装一下

**Comment by nekoNep** [comment]
啊想問下這個是從那個路徑打開呢

**Comment by KagamiChan** [comment]
@nekoNep Finder 里面的话，就是你的 home 目录然后开始找 Library

**Comment by KochiyaOcean** [comment]
@nekoNep 如果觉得麻烦的话可以试试看 https://ci.appveyor.com/project/KochiyaOcean/poi/build/1.0.1464/artifacts  这个测试版能否解决

**Comment by KochiyaOcean** [comment]
@nekoNep 在 finder 里 `shift + cmd + G` 直接输入就行了

**Comment by nekoNep** [comment]
@KochiyaOcean @KagamiChan 似乎在application support 裡面並不存在poi這個文件夾
<img width="1129" alt="2017-05-23 0 44 28" src="https://cloud.githubusercontent.com/assets/28868725/26317021/1e6611b4-3f51-11e7-87ed-e90872dc190b.png">

**Comment by KagamiChan** [comment]
![image](https://cloud.githubusercontent.com/assets/3816900/26317102/f8cb3b26-3f48-11e7-922d-c794b4bd3bb9.png)

路径是这样的

我们正在编译新的测试版，如果没找到的话就稍等一下也可以

**Comment by KagamiChan** [comment]
不好意思……你的问题好像还是插件太老阻碍了升级，所以恐怕还是需要麻烦你找到这个目录删除掉

你的 poi.app 是放在 Applications 里的吗，也可以打开 terminal 运行 /Applications/poi.app/Contents/MacOS/poi -s，然后把所有的插件升级一下

**Comment by nekoNep** [comment]
@KagamiChan 在安全模式下沒有問題，現在試下升級插件先。
感謝！
