### ISSUE TITLE
在Retina显示屏下分辨率调整出错（macOS）

### ISSUE THREAD

**Issue by iTZQing** [poooi/poi#1471]
poi 版本 / poi version:
v7.7.0

已安裝插件
无

操作系统 / OS:

OS: macOS10.12.5
CPU: 3.5 GHz Intel Core i5
RAM: 8 GB 1600 MHz DDR3
VGA:AMD Radeon R9 M290X

在Retina显示屏下分辨率调整出错。。。（我已经不能用语言来形容了）。。。

设定分辨率大小那个好像是根据显示器实际大小来调整而不是根据设定值来的，，，Ratina显示屏一般都是设定显示器实际分辨率的一半，我是iMac 5K，（5120x2880）但设定值是2560x1440。。。然后窗口偏小。

**Comment by iTZQing** [comment]
来个截图吧。话说刚刚Mac卡死了。。。
[https://drive.google.com/file/d/0B400AniyJJWWbkNBVm16MGQ4UjQ/view?usp=sharing](url)

**Comment by iTZQing** [comment]
不走系统代理VPN啊～～～删除缓存和删除COOKIES后“关于”里的图就崩了。。。

**Comment by KochiyaOcean** [comment]
其实 Github Issue 可以直接贴图片的……
为了对应 Chrome 内核升级带来的机制变更，现在的游戏分辨率设置表现的是 **实际占用的像素数量**，所以如果是 Retina 用户应该设置为 1600 宽度……
已知分辨率设置 UI 方面有一些 bug，计划在这两天拿到 4k 屏的新电脑以后进行修复

**Comment by iTZQing** [comment]
分辨率设定有误，不能按照正常的百分比设定。。，也不能自行设定（好像因为是即时应用，前面开头总要有个数。。。），是不能设定吗？

**Comment by KochiyaOcean** [comment]
@iTZQing 这就是我说的 UI 的 bug 了……你可以复制粘贴一个 1600 进去（x
不影响实际设置

**Comment by iTZQing** [comment]
@KochiyaOcean 网页的缩放也是吗。。。_(:з」∠)_

**Comment by KochiyaOcean** [comment]
@iTZQing 是的

**Comment by KochiyaOcean** [comment]
@iTZQing 缩放是什么情况不是很清楚……设置为 1600 的话在 Retina 上应该是不会出问题的

**Comment by iTZQing** [comment]
@KochiyaOcean 好吧，要反馈的基本上整合到了上面的对话（vpn什么的）。。

**Comment by gnattu** [comment]
Fixed in 7.9
