### ISSUE TITLE
360误报安装程序为木马

### ISSUE THREAD

**Issue by momoblydblk** [poooi/poi#1472]
**poi 版本 / poi version:**
7.8.0

**操作系统 / OS:**
Win10 1703 15063

**你遇到了什么样的问题 / The problem you've met:**
在运行安装程序时，360检测出安装程序为木马。

**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:**
装360，点开安装程序

**Comment by KochiyaOcean** [comment]
呃……加白名单不就行了

**Comment by vuryleo** [comment]
不该卸载360么（手动滑稽

**Comment by onno424** [comment]
poi 版本 :
7.8.0(poi-7.8.0-win.7z)
操作系统 : 
Win7 SP1  
防毒軟體 : 
AVAST(版本17.4.2294) 病毒定義版本(170605-0)
你遇到了什么样的问题 : 
AVAST 回報Win64:MdeClass
有没有重现的方法，或者与问题相关的任何信息:
開啟AVAST直接砍EXE檔,病毒掃描顯示Win64:MdeClass

**Comment by yukixz** [comment]
@onno424 卸载360

**Comment by onno424** [comment]
防毒軟體 :AVAST(版本17.4.2294) 病毒定義版本(170605-0) .....
不是360報的..

**Comment by KagamiChan** [comment]
尽管我们自己也很重视安全方面的问题，但是在误报问题上我们并没有精力去对个别的杀软厂商进行反馈。

以下是 7.8.0 64位版本在 virustotal 上的扫描结果

https://www.virustotal.com/en/file/4dd674fdfd82bef4e2063b26288760df9a752d0ea354d7a49fa1d37bafa275f2/analysis/

https://www.virustotal.com/en/file/0cdbcbdfb5a462ae4a33f6e674ff04ef6d0913cbe73a874ebacbd142caace96c/analysis/1496662355/

**Comment by onno424** [comment]
感謝您解答
我也有用該網站去掃毒來確認是誤報
抱歉占用您的時間

**Comment by KagamiChan** [comment]
没关系，也感谢你指出这个情况。也欢迎你去厂商那边反馈误报 XD
