### ISSUE TITLE
mac下黑屏问题

### ISSUE THREAD

**Issue by HolicEro** [poooi/poi#1474]
**poi 版本 / poi version:**
7.7.0.3730

**操作系统 / OS:**
macOS Sierra 10.12.4 (16E195)

**插件名和版本 / Plugin name & version:**

似乎所有在主窗口显示的插件会出现这个问题，单独弹出窗口的插件不会出现

**你遇到了什么样的问题 / The problem you've met:**

问题似乎类似#1285，在只安装单独窗口插件时正常运行，在安装某个插件后布局发生错乱，重启后黑屏无法载入，删除掉这些插件后可以正常载入。按照#1285的方法删除local storage并无法解决。console里出现的错误基本都是说_lodash.get类型错误

**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:**

![qq20170525-0](https://cloud.githubusercontent.com/assets/1622467/26417130/d4864a46-40ea-11e7-8a07-458eccd28872.png)

![b2a89405-26fd-458c-b757-4156865ecddf](https://cloud.githubusercontent.com/assets/1622467/26417183/052e9180-40eb-11e7-8cf7-9a18ed5fa46b.png)

![539fdedf-b628-4e79-add5-a6d60fab120d](https://cloud.githubusercontent.com/assets/1622467/26417237/2eff5f26-40eb-11e7-906a-d941b59d253e.png)

![5e073fa4-a497-496f-b765-575f92cd54ca](https://cloud.githubusercontent.com/assets/1622467/26417260/42b3b468-40eb-11e7-87c2-cc9dce8e2b8e.png)

大概是以上两种错误

**Comment by KochiyaOcean** [comment]
确定所有插件都是最新的么

**Comment by KochiyaOcean** [comment]
最好测试一下是哪个插件导致的……

**Comment by HolicEro** [comment]
@KochiyaOcean 我随机挑了几个试了一下，总结下来就是独立窗口的插件比如装备信息舰娘信息不会出现这种问题，集成在窗口内的插件似乎都会出现这个问题

**Comment by KochiyaOcean** [comment]
@HolicEro 考虑一下本体文件损坏的情况？

**Comment by HolicEro** [comment]
@KochiyaOcean 考虑过，这个问题其实是6.x的时候就开始有了，之前也以为是文件的问题，后来跟着几次新版本更新以后还是出现这个问题，也是刚才下的7.7，来源是poi.io，感觉不对劲了

**Comment by KagamiChan** [comment]
请问有没有试过删掉和 local storage 旁边的 plugins 文件夹？

**Comment by KochiyaOcean** [comment]
在 windows 的 cmd 下成功复现，但是 powershell 下并无此问题……
需要进一步调查

**Comment by HolicEro** [comment]
@KagamiChan 试过删除plugins文件夹以后重新启动回复正常，重新安装插件以后又出现这个问题

**Comment by KagamiChan** [comment]
@HolicEro 如果只安装一个插件的话，比如只有海域血量，也会出现这样的问题吗？

**Comment by KagamiChan** [comment]
海域血量有一些时间没有更新了……只安装未卜先知的话，会出现这样的问题吗

**Comment by HolicEro** [comment]
@KagamiChan 我删掉了所有插件，然后重启安装未卜先知，taobao源，然后重启，仍然出现同样的问题，console两种错误
![a86e41f8-f8b8-4018-ab9a-324b755f6c97](https://cloud.githubusercontent.com/assets/1622467/26436701/f3c3cdd8-414a-11e7-8f9b-1b26d8d69457.png)
![18ccc7f1-9a5d-4567-88b3-b04a1c914ddf](https://cloud.githubusercontent.com/assets/1622467/26436715/0a2157a8-414b-11e7-822e-bd016e3701d7.png)

**Comment by KagamiChan** [comment]
如果你把 `~/Library/Application Support/poi` 文件夹的名字改成别的，再重新启动呢？

**Comment by KagamiChan** [comment]
再麻烦你在 console 里面输入这些命令，然后贴一下结果

```js
console.log(require('module').globalPaths)
console.log(_.VERSION)
console.log(require('lodash').VERSION)
```

**Comment by HolicEro** [comment]
@KochiyaOcean 把文件夹改名以后重启，又生成了叫做poi的文件夹相当于初次启动吧大概
，我在出现问题的情况下输了你说的命令，结果如下

![42ef31cb-151a-45bb-adf8-7f06d7e49103](https://cloud.githubusercontent.com/assets/1622467/26438481/d21b1c62-4155-11e7-870d-155a104cd473.png)

**Comment by KagamiChan** [comment]
[poi-plugin-dash-1.0.0.tgz.zip](https://github.com/poooi/poi/files/1029239/poi-plugin-dash-1.0.0.tgz.zip)
麻烦下载一下上边的这个，解压一遍之后把 tgz 文件拖放到 poi 的插件面板安装
这个会在 console 里面打出一堆的信息，你可以右键 save as，然后贴上来或发到我的邮箱 seki@kagami.me

**Comment by HolicEro** [comment]
@KagamiChan 抱歉，昨晚挺早就睡了

[-1495758980421.log.zip](https://github.com/poooi/poi/files/1030522/-1495758980421.log.zip)

**Comment by KagamiChan** [comment]
@HolicEro 直接的原因是你的 home 目录下有一个 node_modules 文件夹，载入插件的时候载入了那里面的上古版本的 lodash。所以如果可以的话，建议你删除掉那个 node_modules 文件夹

**Comment by KagamiChan** [comment]
至于本体怎么根本上修复这个问题，我们还在讨论中，也许下一个版本就能解决……

**Comment by KochiyaOcean** [comment]
刚刚修复了，如果有使用开发版本也请麻烦测试一下……

**Comment by HolicEro** [comment]
@KagamiChan ok解决了，多谢多谢， @KochiyaOcean 手太快把回收站都清空了233，总算是正常了，如果我不来提交issue可能下半辈子都没法好好玩耍了_(:3J
