### ISSUE TITLE
航海日誌中資材的圖表問題

### ISSUE THREAD

**Issue by arno15505** [poooi/poi#1475]
**poi 版本 / poi version:**
7.7.0 (更早版本也有同樣的問題

**操作系统 / OS:**

Win8.1
**插件名和版本 / Plugin name & version:**
航海日誌ver.6.0.4 (更早版本也有同樣的問題

**你遇到了什么样的问题 / The problem you've met:**
航海日誌中的資材圖表：上方資源選擇有實際按鈕位置右偏的狀況(詳見圖一與二鼠標位置)，右上方四個功能無法按(詳見圖三)，最底下橫桿無法縮放圖表(詳見圖四/主要困擾的問題)
已經嘗試過移除插件重裝、清除資材資料重抓檔案，皆無法解決上列問題

**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:**
雖然Console沒有跳error，但還是附上了(詳見圖五)
圖片連結(共五張)：http://imgur.com/a/t9AA5

**Comment by VongolaXI11** [comment]
同上，大概五月中旬开始有这个问题的。
简言之，就是UI的位置跑掉了，跟显示出来的不一样。

**Comment by KagamiChan** [comment]
你们在本体显示设定中的缩放是不是都不是 100% ？
这些错位与当前本体给插件自动应用的缩放方式有关系，我们正在尝试用另外的方式进行缩放
cc @KochiyaOcean

**Comment by arno15505** [comment]
是的 縮放並不是100%

**Comment by VongolaXI11** [comment]
我也不是100%，不过以前没问题的说。
