### ISSUE TITLE
Deepin 无限猫

### ISSUE THREAD

**Issue by Schummacher** [poooi/poi#1477]
**poi 版本 / poi version:**
7.7.0

**操作系统 / OS:**

Deepin
**插件名和版本 / Plugin name & version:**

**你遇到了什么样的问题 / The problem you've met:**

用OOI登陆舰娘在GAME START界面点击进入后无限猫

**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:**

**Comment by KochiyaOcean** [comment]
@Schummacher 清缓存

**Comment by Schummacher** [comment]
连续清了三次，但还是猫

**Comment by KochiyaOcean** [comment]
@Schummacher 是 201 猫么

**Comment by Schummacher** [comment]
100猫

**Comment by KochiyaOcean** [comment]
@Schummacher 检查系统时间

**Comment by Schummacher** [comment]
我关了deepin的系统自动对时

**Comment by ghpjc** [comment]
关于这个毛病，说个我的发现：7.7和7.8b0，win下使用ss http模式或路由器搞openvpn+squid缓存做策略路由，两种情况下均有猫过，甚至官方android客户端在后者网络环境下都猫。目前7.8 b0使用SS的socks5模式情况有好转，没再出现过。猫的时候各种缓存都清理过，但是问题依旧，原因不明。

**Comment by KagamiChan** [comment]
为什么要关系统对时？自己用 ntp 之类的命令校准一下时间看看吧……

**Comment by KagamiChan** [comment]
@KagamiChan 或者 https://time.is/ 这样的

**Comment by KagamiChan** [comment]
或者 https://time.is/ 这样的

**Comment by UberNicky** [comment]
我也有相同的問題. 在今天早上開始出現無限貓的情況. 
Window 10. 7.7 和 7.80beta1 兩個版本都試過. 清過缓存,裝了ntp, 改日本時間 也出現無限貓情況.
