### ISSUE TITLE
遠征資訊擴展程式, 大發改修增加的遠征量不正確

### ISSUE THREAD

**Issue by suzinweng** [poooi/poi#1482]
**poi 版本 / poi version:**
7.6.0

**操作系统 / OS:**
Windows 10 版本1607

**插件名和版本 / Plugin name & version:**
遠征資訊 ver 3.1.0

**你遇到了什么样的问题 / The problem you've met:**

帶有改修的大發遠征時, 顯示的收益理論值過高, 不符合實際拿到的量
以我鬼怒帶3台大發共改修24星為例, 收益顯示增加48.2%, 查詢其他網站應該是20%~22%之間的數字才對
最近有新的"易及遠征"插件, 顯示的值就比較合理

![2017-06-03 00 09 35](https://cloud.githubusercontent.com/assets/29148468/26734880/3c139b38-47f2-11e7-8b89-8c8b69897032.png)

![2017-06-03 00 10 02](https://cloud.githubusercontent.com/assets/29148468/26734920/6495c5fe-47f2-11e7-83fb-bf162be0173c.png)

**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:**
帶改修大發就能重現

**Comment by KagamiChan** [comment]
多谢指出，以前的代码没有经过完整的测试（我没有改修大发，也没有两个特大发 囧rz）。近期会考虑进行一下维护（咕咕
