### ISSUE TITLE
经验计算插件添加星标功能

### ISSUE THREAD

**Issue by DavidDiao** [poooi/poi#1484]
能不能在 经验计算 的插件中加一个类似星标的功能，用于记录自己准备给哪些船练级
可以有例如改造/二段改造后自动取消星标这样的选项
如果可以的话不同舰种也区分开来，方便配置练级的舰队
<del>代码不加注释真的令人崩溃</del>

**Comment by KagamiChan** [comment]
歡迎使用艦步如飛插件 - -
經驗計算插件現在的代碼的確是很難做維護了……

**Comment by KochiyaOcean** [comment]
都怪吃吧
