### ISSUE TITLE
可以设置字幕语种吗？

### ISSUE THREAD

**Issue by fc4soda** [poooi/poi#1486]
**poi 版本 / poi version:**
V7.8.0

**操作系统 / OS:**
Ubuntu 16.04.2 LTS

**插件名和版本 / Plugin name & version:**
KCwiki Quotes Subtitle V1.0.2

**你遇到了什么样的问题 / The problem you've met:**
我想在语言设置为简中的时候语音字幕能够显示日文。现在只能在English下显示日文台词，但是英语翻译还是没有中文方便。

**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:**

**Comment by KagamiChan** [comment]
cc @grzhan

**Comment by grzhan** [comment]
> 现在只能在 English 下显示日文台词
是说现在把 POI 的界面设置成日文无法显示日文台词吗？

目前插件是根据 POI 界面的语种来设置语种的，如果需要可以自行设置，可能插件需要做面板了吧

**Comment by KochiyaOcean** [comment]
@grzhan 有 settingClass

**Comment by fc4soda** [comment]
@grzhan 就是希望能自行设置，看到NGA发布的74eo移植了POI的语音字幕插件，提供了在右键菜单里选择字幕语种的功能~

**Comment by KagamiChan** [comment]
需要帮忙吗 @grzhan

**Comment by grzhan** [comment]
@fc4soda 了解了，这两天我实现一下。
@KagamiChan 谢谢，应该没问题。有问题的话再找你

**Comment by grzhan** [comment]
测试版 `1.1.0-beta.0` 开始支持语种设置。
这几天看下有没有问题，没问题的话就切到正式版。

**Comment by grzhan** [comment]
`1.1.1` 开始支持字幕语种
