### ISSUE TITLE
poi v7.9.0 changelog

### ISSUE THREAD

**Issue by KochiyaOcean** [poooi/poi#1488]
## 功能
- [Windows] [Linux] 使用定制标题栏代替原有系统标题栏
- [Windows] 安装包支持选择安装路径
- [macOS] 增加 TouchBar 支持
- [macOS] 增加透明窗口模式
- 支持自定义 poi 界面背景图片，自定义背景图片将以类似亚克力特效的方式显示
- 大幅优化启动速度
- 在新窗口插件单独设置下追加是否常驻后台选项
  - 如果禁止具有记录功能的新窗口插件常驻后台, 记录功能将会失效
- 增加缓存大小设置，使用一心二用玩多个游戏的用户可以适当地提高缓存大小
- 在设置-关于中加入性能监视器，可以查看 poi 的 CPU 与内存占用情况
- 移除了全部的亮色系主题
- 更新制空值计算公式，现在默认显示最小制空值

## 修复
- 修复了设定自定义缩放倍率时新窗口插件缩放显示不正常的 bug
- 修正类型 id 12 的对空 ci 满足条件的错误
- 修正大鹰改及改二的先制反潜满足条件的判断
- 修复在锁定窗口大小的情况下可以进行最大化的问题
- 修复部分主题因为请求 webfont 原因导致的载入失败
- 修复月末战果倒计时显示错误的问题

---------
### 新插件：舰步如飞
- 帮助进行舰娘练级规划管理，并包含了经验计算的功能

### 新插件：海色相簿
- poi 第一次能够查看舰娘立绘，第一次能够听到舰娘的所有语音，两件快乐的事情重合在一起

### 任务信息
- 为不同类型的任务增加对应颜色标签
- 重构任务下拉选单，现在在触摸屏上也可以翻页
- 在接取任务时自动切换到所接取的任务

### 泊地修理
- 增加可修理舰娘的标签页，列出可以进行泊地修理的舰娘

### 装备改修
- 改修信息展示重构，大幅提升启动与切换速度
- 星级争霸整合进改修信息当中

### 舰娘信息
- 完全重写了整个舰娘列表，优化了启动及刷新速度
- 筛选区域重新组织为两个下拉菜单
- 测试版本的出击计划，用于帮助定制活动图海域的舰娘出击计划

### 未卜先知
- 当舰娘装备与运输作战相关的装备（桶，大发及饭团等）时，显示舰队的运输值

**Comment by KochiyaOcean** [comment]
## poi v7.9.0 changelog
### Function
- [Windows] Use custom titlebar instead of system titlbar
- [Windows] Installer supports install to specifed path
- Improvement on startup speed of new window plugins
- Add an option on new window plugin settings to set whether keep process running in background
  - Disable background process for plugins that have recording function will breaks its recording function
- Other performance improvements

### Fix
- Fix wrong display on some new window plugins with custom zoomlevel setting

**Comment by seagullyyx** [comment]
@KochiyaOcean 
我用了最新的7.9.0-beta.1
我把最大缓存大小设置20000MB， 重新进了，但是缓存还是被控制在300~350之间。飙到过400左右，但是之后又被删到300多。

**Comment by KochiyaOcean** [comment]
@seagullyyx 和使用命令行的时候表现不一样么

**Comment by KochiyaOcean** [comment]
@seagullyyx https://ci.appveyor.com/project/KochiyaOcean/poi/build/1.0.1585/artifacts 使用这个版本看看（正在 build， build 完以后会有下载链接

**Comment by seagullyyx** [comment]
@KochiyaOcean 7.9.0-beta.1　命令行很流畅， 但是超过460MB之后就被删到300MB左右

**Comment by seagullyyx** [comment]
@KochiyaOcean 我试试

**Comment by seagullyyx** [comment]
@KochiyaOcean 有点事出门下，晚点回来试试那个。麻烦你了！

**Comment by seagullyyx** [comment]
@KochiyaOcean  
![wn5d jjv r2w972h nd vhe](https://user-images.githubusercontent.com/28121173/27095269-05b01ad4-503b-11e7-9763-46afa0d98f5d.png)

这个是那个链接的版本，也是同样到了缓存460左右就开始就被删到300左右了

**Comment by KochiyaOcean** [comment]
@seagullyyx 在命令行里加了 `--disk-cache-size` 和没加的的开发者工具里分别输入 `process.argv` 结果是一样的么

**Comment by seagullyyx** [comment]
@KochiyaOcean                开发者工具我不太清楚在哪里输入process.argv

![jnj 2i9a ov 86bg36j62](https://user-images.githubusercontent.com/28121173/27106039-bf68c128-505f-11e7-8848-80ede63ca661.png)

命令行老样子，430左右被删到300左右

**Comment by KagamiChan** [comment]
虽然我们实现了这个，但是上游支持这个功能的 electron 还没有发布正式版……所以还要等一段时间

**Comment by edwardaaaa** [comment]
本周日可以上传重新绘制的2.0版本的SVG矢量图标，各位不嫌弃的话届时还请帮忙加入下次更新，在此先谢过大家之前的支持。

**Comment by dkwingsmt** [comment]
@edwardaaaa

**Comment by dkwingsmt** [comment]
@edwardaaaa 辛苦了！

**Comment by edwardaaaa** [comment]
<img width="1515" alt="screen shot 2017-08-25 at 14 22 29" src="https://user-images.githubusercontent.com/11089376/29701886-087d8798-89a1-11e7-83a2-be4676a4365e.png">
请问下这三个图标代表什么含义

**Comment by KagamiChan** [comment]
@dkwingsmt 
小家具箱，中家具箱和大家具箱，囧rz

**Comment by KagamiChan** [comment]
@edwardaaaa 小家具箱，中家具箱和大家具箱，囧rz

**Comment by edwardaaaa** [comment]
@KagamiChan 现在poi界面也会显示家具箱？

**Comment by KagamiChan** [comment]
@edwardaaaa 在显示海域的掉落的时候会用到

**Comment by KagamiChan** [comment]
@KagamiChan 也包括远征插件显示收益的时候
