### ISSUE TITLE
关于一心二用缓存

### ISSUE THREAD

**Issue by seagullyyx** [poooi/poi#1489]
版本7.8.0
一心二用 2.8.0

我用一心二用玩城娘，但是如果开了一心二用的话我发现舰娘的缓存被删了(舰娘需要重新加载素材什么的)
其实我还想玩三国志cross，但是按照这个趋势舰娘估计要无限下载新缓存了。
请问如何增加poi或者一心二用的缓存上限?

**Comment by KochiyaOcean** [comment]
@seagullyyx 你 C 盘空间剩多少……

**Comment by seagullyyx** [comment]
@KochiyaOcean    目前是 56.8GB free of 110GB

**Comment by KochiyaOcean** [comment]
@seagullyyx 考虑加一个设置，目前需要使用命令行参数才能设置容量

**Comment by seagullyyx** [comment]
@KochiyaOcean 可以说的详细点吗。。不是很懂。谢谢

**Comment by KochiyaOcean** [comment]
@seagullyyx 使用命令行的话就是 `poi.exe --disk-cache-size=[缓存大小]`。
比如 `poi.exe --disk-cache-size=1000000000` 就是设置 1G 的缓存大小
如果不会使用命令行的话就等新版吧……

**Comment by seagullyyx** [comment]
@KochiyaOcean 
请问下这样是成功了吗？
![pgs bdf6 xf5ri4y k xh](https://user-images.githubusercontent.com/28121173/27013922-410a6854-4ebb-11e7-95d5-ea5981be5a87.png)

**Comment by KochiyaOcean** [comment]
@seagullyyx 应该是可以的

**Comment by seagullyyx** [comment]
@KochiyaOcean 谢谢

**Comment by seagullyyx** [comment]
@KochiyaOcean  我自己观察了下，C:\Users\sanvn\AppData\Roaming\poi\Cache 的存储在350MB左右的时候，似乎Poi就开始删缓存了，似乎是控制在了350MB以下。 

你说的用cmd的方法似乎没有效果。。

**Comment by KochiyaOcean** [comment]
@seagullyyx 每次都用命令行启动？

**Comment by seagullyyx** [comment]
@KochiyaOcean 所以是要每次都命令行启动，而且要带poi.exe --disk-cache-size=1000000000 这一行是吗？

**Comment by KochiyaOcean** [comment]
@seagullyyx 目前是这样，我这两天会发一个包装成设置的版本

**Comment by KochiyaOcean** [comment]
v7.9.0-beta.1 已经包含此设置，可以更新看看了
