### ISSUE TITLE
i18n

### ISSUE THREAD

**Issue by magicae** [poooi/poi#149]
- [x] English
- [x] Japanese
- [x] Traditional Chinese

**Comment by c933103** [comment]
language request: traditional chinese.

**Comment by magicae** [comment]
@KochiyaOcean @c933103 Add traditional Chinese.

**Comment by KochiyaOcean** [comment]
Roger that.

**Comment by KochiyaOcean** [comment]
@c933103 traditional Chinese translation has been merged into branch 'i18n'.

**Comment by magicae** [comment]
We are working on i18n now and need more help.

**Comment by c933103** [comment]
It would be helpful for non-Chinese/Japanese users to translate ship name, equipment namex engagement pattern, quest name, etc. into English.

**Comment by magicae** [comment]
@c933103 work in progress now.

**Comment by c933103** [comment]
You can take existing translation from kancolle.wikia.com or en.kancollewiki.net as long as you follow their terms.

**Comment by myzWILLmake** [comment]
Different languages need different fonts. It is be hard to bear the font YaHei on Windows when the language is ja_JP.

**Comment by PHELiOX** [comment]
翻译文件是不是按插件做一个分级比较好？

**Comment by igax** [comment]
> Different languages need different fonts. It is be hard to bear the font YaHei on Windows when the language is ja_JP.

i think  web font.  a font set which is connected with locale change and corresponds is loaded.
there is also an advantage which becomes the same outward appearance in spite of OS.
http://www.google.com/get/noto/

**Comment by Wafer-Li** [comment]
What about support the ship and the equipment?
Only for english.
See here: https://github.com/yuyuvn/KanColleViewer/tree/master/resources/translations
