### ISSUE TITLE
签名生成需更新

### ISSUE THREAD

**Issue by lucktd** [poooi/poi#1492]
**poi 版本 / poi version:7.8.0

**操作系统 / OS:**

Windows 10 64位
1703
**插件名和版本 / Plugin name & version:签名生成/0.3.1

**你遇到了什么样的问题 / The problem you've met:**
全船仅184船，现在已经194船了
**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:**

**Comment by KochiyaOcean** [comment]
签名生成的网站并不是我们维护的，插件仅负责提交数据
关于网站的 issue 请移步 https://github.com/Nya-chan/k2badge/issues

**Comment by lucktd** [comment]
刚才才看到7.8的更新日志上面有说这件事情

**Comment by KagamiChan** [comment]
可能是地址更新没弄好……我修一下

**Comment by KagamiChan** [comment]
不知道为什么，他们的英文版页面更新了，但是其它语言的页面回退到旧版本了
我在做测试的时候是更新了的，所以这题超纲了……

**Comment by KagamiChan** [comment]
提交了一个 issue，等回复吧 Nya-chan/k2badge#14 - -

**Comment by KagamiChan** [comment]
现在的维护者的回复是，他们不对非英文版进行维护，因为他们不懂日文 / 中文。他们也说了维护的方法。在非英文版得到维护之前，签名生成插件会一直只使用英文版的生成器。

（我会在签名生成插件更新之后关闭此 issue）

**Comment by EAirPeter** [comment]
个人对此也有需求。。。打算自己做一个日文版的更新。。。到时候会发一个PR给原repo。。。

**Comment by EAirPeter** [comment]
https://github.com/Nya-chan/k2badge/pull/17
