### ISSUE TITLE
[Question] Should package-lock.json be ignored?

### ISSUE THREAD

**Issue by wafer-li** [poooi/poi#1493]
跑个 `npm i` 居然提示 modified。

**Comment by KagamiChan** [comment]
Simply running `npm i` will install the same packages locked by package-lock.json

**Comment by KochiyaOcean** [comment]
https://docs.npmjs.com/files/package-lock.json
……This file is intended to be committed into source repositories.

**Comment by KagamiChan** [comment]
Please use npm > 5.0 so that this lock file is respected

**Comment by wafer-li** [comment]
@KagamiChan 
更新了一遍 npm，回滚之后再 `npm i` 同样出现了 modified。

![image](https://user-images.githubusercontent.com/12459199/27318869-75d3a716-55c9-11e7-996e-bd9279c0f764.png)

![image](https://user-images.githubusercontent.com/12459199/27318876-81312520-55c9-11e7-9d7f-3431fb67fdb7.png)

理论上不是应该不会出现 modified 的吗？
否则你跑一遍我跑一遍这样就会造成大规模 conflict。

**Comment by KagamiChan** [comment]
It seems to me the hash is updated because your local package in node_modules contains only sha-1 hash.
I suggest a complete removal of your node_modules folder and running `npm i` again.

**Comment by KagamiChan** [comment]
Anyway, this should be documented, thank you for reminding me this.

**Comment by wafer-li** [comment]
OK, after removing the `node_module` and re-`npm i`.
Problem solved.
