### ISSUE TITLE
poi 在全屏后再返回窗口会导致窗口位置及排版异常

### ISSUE THREAD

**Issue by bibizai** [poooi/poi#1497]
**poi 版本 / poi version:**
v7.8.0

**操作系统 / OS:**
mac OS 10.12.6 Beta (16G8c)

**插件名和版本 / Plugin name & version:**

**你遇到了什么样的问题 / The problem you've met:**
poi 在全屏后再返回窗口会导致窗口位置及排版异常，窗口位置在忽略菜单栏的屏幕顶端，并且窗口高度会增加一个菜单栏的高度。

**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:**
点击全屏按钮后再返回窗口。
![2017-07-01 12 53 17](https://user-images.githubusercontent.com/29809548/27759514-1fc68fd8-5e65-11e7-914c-aeb35391f86e.png)

**Comment by KagamiChan** [comment]
在普通屏幕分辨率下没能复现
也有可能是上游 electron 的 bug，需要等下一个搭载 electron 1.7 的版本测一下

**Comment by KagamiChan** [comment]
retina 屏上开发版本也没能复现，还是等下一个版本看看吧

**Comment by bibizai** [comment]
居然不能重现么=-=那再详细描述一下
我的是非R屏的（显示布局最后那个，高度正好够游戏和底部的字幕栏，宽度拉满整个屏幕宽度）
自己又试了下
√允许改变窗口大小----全屏返回后正常，不会上移加高
  允许改变窗口大小----全屏返回后会出现bug
是不是这个功能的锅啊

不知道有没有用，我把Preferences文件上传一下。
[Preferences.zip](https://github.com/poooi/poi/files/1125563/Preferences.zip)

**Comment by KagamiChan** [comment]
@bibizai 理解你的意思了。不过从不允许改变窗口大小的本意上看，这种情况下也不应该允许全屏或者最大化的……

**Comment by bibizai** [comment]
就我个人来说，能不允许全屏最好了，每次都是点母港不小心点到全屏的，poi从来不用全屏模式，不过不清楚别人用不用全屏的。
