### ISSUE TITLE
部分舰娘的单位修理时间不正确

### ISSUE THREAD

**Issue by EdiTurn** [poooi/poi#1498]
**poi 版本 / poi version:**
7.9.0-beta1

**操作系统 / OS:**
Windows 10 build 16226

**插件名和版本 / Plugin name & version:**
泊地修理 0.5.1
舰娘信息 3.2.0

**你遇到了什么样的问题 / The problem you've met:**
春活后开始观察到，某些在春活中获取到的舰娘，插件显示的单位修理时间乘以损失的耐久与总修理时间相比有很大出入。
如图为甘古特在泊地修理中的显示情况：
![screenshot_20170704-185528](https://user-images.githubusercontent.com/5492805/27828865-12ca4e08-60f1-11e7-8a40-bd59dcd86fda.png)

如图为舰娘信息中的显示情况：
![default](https://user-images.githubusercontent.com/5492805/27829319-a24933d0-60f3-11e7-8d08-d2f493f06ae9.png)

**Comment by KagamiChan** [comment]
海防舰是因为没有加系数，现在加上了
战舰的总修理时间是直接从 API 里面取得的，单位修理时间是通过公式计算得到的。目前在我这里的显示是一致，不知道是时间不更新还是解析时间的函数有问题。

发布了 3.2.1 版本，试一下看看？

**Comment by EdiTurn** [comment]
3.2.1 版本里甘古特显示的单位修理时间还是 17:20。

我查了下公式，甘古特属于高速战舰，应选用 1.5 的倍率。

**Comment by KagamiChan** [comment]
@EdiTurn 嗯……我写的时候 FBB 的倍率写成 2 了
现在两边都发了新版本
