### ISSUE TITLE
对空 CI 舰队界面未显示

### ISSUE THREAD

**Issue by SykieChen** [poooi/poi#1501]
**poi 版本 / poi version:**
7.8.0

**操作系统 / OS:**
10.0.14393

**你遇到了什么样的问题 / The problem you've met:**
配置为机枪 CI 时，舰队编成界面未提示对空 CI。
如图，吹雪配置了三联装集中配备机枪+机枪+对空电探的机枪 CI 配置并发动，但未显示如夕立和时雨的对空 CI 标签。
![image](https://user-images.githubusercontent.com/5460009/27996804-d7434440-651c-11e7-9066-5f018e0a7e8d.png)

对空 CI 的配备参考了 http://nga.178.com/read.php?tid=7538533&rand=504

**Comment by KagamiChan** [comment]
多谢指出，是装备条件写错了
