### ISSUE TITLE
窗口模式提供的5个选项都有什么区别及舰C游戏的缓存问题

### ISSUE THREAD

**Issue by deeporist** [poooi/poi#1502]
**poi 版本 / poi version:**
7.8.0

**操作系统 / OS:**
win 8.1 x64

**插件名和版本 / Plugin name & version:**

**你遇到了什么样的问题 / The problem you've met:**

**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:**

1.
显示设置->FLASH画质和窗口模式:
window,direct,opaque,transparent,gpu
这5个都有什么区别?
2.
github项目wiki页面的内容感觉有点过时了。。。。。。
3.
我也在用岛风go以及岛风go的舰C缓存(包括高清缓存) 那天我尝试
mklink /d H:\POI\MyCache\KanColle\kcs H:\ShimakazeGo\cache\kcs
这个H:\POI本身就是我从C盘里这么mklink /d 到H盘的 这个命令我也用到了kca这个文件夹上 然后我再开启poi进入舰C收远征 点击了一下flash的窗口后 没有出现结算画面 而且flash画面就那么无响应了 鼠标怎么点都没反应 我把H:\POI\MyCache\KanColle\下那两个硬链接删掉后就恢复正常了
我知道我这么做是多此一举 但是我原本是想测试一下在用poi的时候能不能单独使用岛风go的缓存 以备以后在poi里改用其他proxy
这个现象的原因我怎么都没想明白 特此来问问

**Comment by KochiyaOcean** [comment]
1、在没用出现兼容性问题的情况下就使用 window，使用魔改等时出现显示不正确时使用 gpu，其他选项在显示上没有明显区别
2、有空补，咕咕咕
3、岛风 Go 曾经对自己打包的高清缓存等做过加密，不知道现在是否还是如此
