### ISSUE TITLE
mac 无法使用粘贴快捷键

### ISSUE THREAD

**Issue by wafer-li** [poooi/poi#1505]
**poi 版本 / poi version:**
4144db7f3338f7e0d482ddfb27ee86092902abc2

**操作系统 / OS:**
macOS 10.11.6

**你遇到了什么样的问题 / The problem you've met:**
 无法 cmd + v 粘贴

**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:**

![image](https://user-images.githubusercontent.com/12459199/28249234-aa50ede6-6a8c-11e7-9d3f-51ffe9dd4ba1.png)

**Comment by KagamiChan** [comment]
你需要粘贴什么内容到哪个区域？

**Comment by gnattu** [comment]
在macOS10.12中粘贴到Webview和主窗口中都是正常的，请问你是直接下载新版源码npm start运行的还是打包成了app？

**Comment by gnattu** [comment]
在10.11 EI Captain下使用npm start运行确认可以正常粘贴到Webview，主窗口和开发者窗口中，似乎并不是操作系统兼容性问题。Electron也是使用1.7.4版本。
可能是打包之后菜单乱了套？（macOS的快捷键依赖系统原生菜单）

**Comment by gnattu** [comment]
已确认，打包后的dmg中的app原生菜单丢失，导致快捷键不可用。这个问题在7.9.0-beta1中就存在，不过似乎一直没有被人发现。7.8.0正式版中还是有那个原生菜单的。

**Comment by gnattu** [comment]
Looks like [684d387b99ab30736541a52ecc3063ea9ae2db8b](https://github.com/poooi/poi/commit/684d387b99ab30736541a52ecc3063ea9ae2db8b) breaks the poi-menu which designed for macOS.
