### ISSUE TITLE
从AUR安装poi失败

### ISSUE THREAD

**Issue by fc4soda** [poooi/poi#1508]
**poi 版本 / poi version:**
poi 7.9.0.beta.1.0.gd0db1978-1

**操作系统 / OS:**

Linux fca 4.11.9-1-ARCH #1 SMP PREEMPT Wed Jul 5 18:23:08 CEST 2017 x86_64 GNU/Linux

**你遇到了什么样的问题 / The problem you've met:**
用yaourt安装失败：
npm ERR! May not delete: /tmp/yaourt-tmp-fc/aur-poi/src/poi/node_modules/.bin
npm ERR! A complete log of this run can be found in: /home/fc/.npm/_logs/2017-07-18T11_57_36_528Z-debug.log
[Pastebin地址](https://pastebin.com/ahTpbytV)

**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:**
新装的系统。。看了一下依赖的包都安装成功了，小白还不太熟arch

**Comment by KochiyaOcean** [comment]
cc @swordfeng

**Comment by swordfeng** [comment]
https://github.com/npm/npm/issues/17781
NPM is fucking things up.
换yarn了
以及建议使用archlinuxcn源，里面有自动编译的

**Comment by KagamiChan** [comment]
npm ^5 有 lock 文件了，不  prune 感觉问题也不大

**Comment by swordfeng** [comment]
@KagamiChan prune是为了删掉多装的electron。。。

**Comment by fc4soda** [comment]
感谢！安装好了，添加了archlinuxcn的源之后直接安装就没问题了 0.0果然是打包好的比较好么

**Comment by swordfeng** [comment]
@fc4soda 打包好的一般是好的，如果没有出现什么意外情况……一般AUR的也是好的（两边是同步的）但是也存在比如npm又搭错筋崩掉的情况。。这个算上游问题……
