### ISSUE TITLE
poi在macbook pro中CPU占用率过高，远高于在外界显示器

### ISSUE THREAD

**Issue by muguang** [poooi/poi#1520]
**poi 版本 / poi version:**  Version 7.8.0 (7.8.0.3836)

**操作系统 / OS:** 
  MacBook Pro (Retina, 13-inch, Early 2015)
CPUL: 2.7Ghz Intel i5 
内存：8G 1867Mhz DDR3
显卡：Intel Iris Graphics 6100 1536 MB

显示器： Dell  U2515H

**你遇到了什么样的问题 / The problem you've met:**
poi在macbook pro中CPU占用率过高，且在面板切换过程中整个屏幕会闪烁（闪烁一闪而过，就不截图了）
下图左边为外接显示器的CPU占用； 150%左右
右侧为macbook pro的CPU占用， 200%为日常， 250% 经常。
<img width="428" alt="screen shot 2017-07-31 at 23 36 41" src="https://user-images.githubusercontent.com/7148519/28785644-94a822d4-7649-11e7-8253-f9b61f08594b.png">

为什么外界显示器能够做到CPU占用率低，而本机显示器占用率高，是不是能够做到将本机的CPU占用率降低下来

多谢

**Comment by KochiyaOcean** [comment]
@muguang 因为 flash 的矢量特性，分辨率越高，资源占用越大

**Comment by gnattu** [comment]
HiDPi模式下确实会占用更高的CPU，U2515H并没有macOS的原生HiDPi支持。
但是你这个CPU占用还是比较令人困惑，我这里的MBP占用大概在100%上下（全插件，Flash AutoHigh+direct）
请问是在游戏的哪个画面占用这么高的，如果是母港的话，是不是用了一些会动的家具（那些家具是CPU杀手）

**Comment by muguang** [comment]
@KagamiChan  长见识了
@gnattu 哇， 多谢，确实母港的CPU会更多一点
<img width="754" alt="screen shot 2017-08-01 at 9 14 39" src="https://user-images.githubusercontent.com/7148519/28805171-ac21cc48-769a-11e7-8751-af505ec63978.png">
母港时 ，秘书舰会动，感觉应该是这部分特效很耗cpu，但是经过搜索，没有发现怎么关闭

<img width="761" alt="screen shot 2017-08-01 at 9 36 13" src="https://user-images.githubusercontent.com/7148519/28805483-ef6ed354-769c-11e7-9e0f-1552e5fcf2c6.png">
非母港状态好一点，但是也快100% ，和你母港状态差不多

**Comment by KagamiChan** [comment]
7.9.0 beta.3 里面集成了一个性能监视器，可以确认一下是否 flash player 的进程占用比较高

**Comment by KagamiChan** [comment]
在设置-关于  poi 下面

**Comment by muguang** [comment]
@KagamiChan 多谢，之前看是beta版就没下载，母港状态是下图的状态,  45%左右，
<img width="425" alt="screen shot 2017-08-01 at 18 08 00" src="https://user-images.githubusercontent.com/7148519/28820601-d74a0cb0-76e4-11e7-9283-d8d9ec974447.png">

pepper flash？ 感觉确实是flash的锅

**Comment by gnattu** [comment]
@muguang 那么从这个图表来看你Flash的占用和我的差不多，但是你Browser项占用的CPU还是比较多的，我这里只有5%左右。 但是Browser项的占用并不是poi可以控制的，所以。。。

**Comment by muguang** [comment]
@gnattu 那就可怜我笔记本的电池了，掉的飞快， 外出也得悠着点
总之多谢大佬么了
