### ISSUE TITLE
各种通知没有音效提醒

### ISSUE THREAD

**Issue by Sheoldred-WO** [poooi/poi#1522]
**poi 版本 / poi version:**
7.8.0 和7.9.0beta3

**操作系统 / OS:**
windows10版本1703 内部版本15063.483

**你遇到了什么样的问题 / The problem you've met:**
在某次poi版本自动更新以后poi的各种提醒就没有语音提醒了，将所有poi相关内容删除后重装依然出现了这种情况，换了个版本依然如此，

**Comment by Sheoldred-WO** [comment]
![qq 20170804165805](https://user-images.githubusercontent.com/30212172/28961883-7559cd98-7936-11e7-9d2f-0629f1c32692.jpg)

**Comment by Sheoldred-WO** [comment]
另外，windows通知中心的提醒已经开了，游戏内部的提醒音量也开了

**Comment by yukixz** [comment]
@Sheoldred-WO 关掉秘书语音试试

**Comment by Sheoldred-WO** [comment]
@yukixz 还是不行

**Comment by KagamiChan** [comment]
试试看在 Developer Tools 里面输入 `notify('Message', {type: 'expedition'})`，会不会播放声音
输入 `config.get('poi.notify.expedition')` 会得到什么结果？

游戏自己的声音是正常的吧

**Comment by Sheoldred-WO** [comment]
@KagamiChan 游戏本身的声音是正常的
输入第一个弹了个消息但是依然没有声音
输入第二个的结果如下
![qq 20170804203619](https://user-images.githubusercontent.com/30212172/28968893-c55d8af0-7954-11e7-92df-ef418e119698.jpg)

**Comment by yukixz** [comment]
@Sheoldred-WO 第二个你少个右括号……

**Comment by Sheoldred-WO** [comment]
@yukixz 。。。。。
不好意思
![qq 20170804204701](https://user-images.githubusercontent.com/30212172/28969291-9448105a-7956-11e7-9104-06ad1dd5b3e1.jpg)

**Comment by KochiyaOcean** [comment]
你检查一下这里的设置是否正确
![image](https://user-images.githubusercontent.com/8194131/28969430-27604894-7957-11e7-8be5-ea65ed6e22f6.png)

**Comment by Sheoldred-WO** [comment]
@KochiyaOcean 
![qq 20170804205620](https://user-images.githubusercontent.com/30212172/28969546-8fee4a96-7957-11e7-9d99-890609c241af.jpg)

**Comment by KochiyaOcean** [comment]
@Sheoldred-WO 改个别的值点下保存然后再看看 `config.get('poi.notify.expedition')`

**Comment by Sheoldred-WO** [comment]
@KochiyaOcean 
![qq 20170804210230](https://user-images.githubusercontent.com/30212172/28969709-4ff73b0e-7958-11e7-9a39-750b1df51e96.jpg)
我之前在秘书舰通知音那里测试过也没有反应

**Comment by KagamiChan** [comment]
试试看暂停秘书通知，再重新开启

**Comment by KagamiChan** [comment]
再在秘书通知里面换一两个语音试试看

**Comment by Sheoldred-WO** [comment]
@KagamiChan 已经关掉了，而且重启了游戏了

**Comment by KagamiChan** [comment]
直接暂停再重新打开插件，再重启游戏
然后在插件里面换几个秘书舰，也是一样测试没有声音吗

**Comment by KagamiChan** [comment]
试试新发布的 1.0.0 版吧，这个不需要重新启动游戏

**Comment by Sheoldred-WO** [comment]
@KagamiChan 主要是就连原本的poi都听不见了

**Comment by KagamiChan** [comment]
那你就执行一下 `config.set('poi.notify', {})`，把提示部分的设置全部重置一下

**Comment by Sheoldred-WO** [comment]
@KagamiChan 这个命令输入以后变成了undifined

**Comment by KagamiChan** [comment]
于是输入 `notify('Message', {type: 'expedition'})` 还是没有播放声音吗

**Comment by Sheoldred-WO** [comment]
@KagamiChan 是啊...

**Comment by KagamiChan** [comment]
于是运行 `require('fs').statSync(`${ROOT}/assets/audio/poi.mp3`)` 的显示内容是啥

运行 `new Audio(`file://${ROOT}/assets/audio/poi.mp3`).play()` 也是没有声音的吗

**Comment by Sheoldred-WO** [comment]
好像语法不对？
![qq 20170804225320](https://user-images.githubusercontent.com/30212172/28974094-c4235c60-7967-11e7-824e-b5b0ae162c08.jpg)

**Comment by KagamiChan** [comment]
你直接复制我给你的代码执行就好了

**Comment by Sheoldred-WO** [comment]
@KagamiChan 咦，我刚刚就是复制的怎么没反应= =
![qq 20170804233500](https://user-images.githubusercontent.com/30212172/28975719-a1151654-796d-11e7-83aa-607dc5a4be30.jpg)

**Comment by KagamiChan** [comment]
@Sheoldred-WO 所以第二个命令打出去之后有声音吗

**Comment by Sheoldred-WO** [comment]
@KagamiChan 没有....

**Comment by KagamiChan** [comment]
@Sheoldred-WO 这样的话只能认为是你的系统方面的问题了，比如单独给 poi 静音了什么的

**Comment by Sheoldred-WO** [comment]
@KagamiChan 好吧，谢谢大佬们了，辛苦了一晚上

**Comment by gnattu** [comment]
右键任务栏声音图标，打开音量合成器，看看里面是不是这个样子
![default](https://user-images.githubusercontent.com/12995396/29062752-7ea73aa8-7c55-11e7-8882-aa631cf84912.PNG)

**Comment by Sheoldred-WO** [comment]
@gnattu 我是只有提示没有声音，游戏本身的声音是有的

**Comment by gnattu** [comment]
@Sheoldred-WO 你去poi目录下找resources/app/assets/audio/poi.mp3，播放有声音吗

**Comment by Sheoldred-WO** [comment]
@gnattu 有声音的

**Comment by DavidDiao** [comment]
同问，以及`notify('Message', {type: 'expedition'})`执行后发送了http://125.6.189.39/kcs/sound/kcyfpnftpuwkrx/151005.mp3这么一个请求，请求花了20多秒完成（其中绝大部分时间都是Waiting(TTFB)，好像是Chrome一个历史问题。。），然后控制台返回了一个错误`Uncaught (in promise) DOMException: Failed to load because no supported source was found.`

**Comment by gnattu** [comment]
@DavidDiao 你那个纯粹就是网络太差秘书语音没有读出来，超时了是会这样

**Comment by DavidDiao** [comment]
@gnattu 返回的是200，但Content-Length是0。。这应该不能当做网络差吧。。然后挂了VPN能正常使用
想到现在呆的地方的网络环境，驻岛的服务器也不能直接访问我就不说什么了。。

**Comment by gnattu** [comment]
@DavidDiao Content-size都0了就是因为网络差。舰娘的服务器的http连接是close模式，也就是说服务器传输完数据会发送EOF来告诉客户端传输已经完成并断开连接。网络由于未知原因被打断的时候，没有继续收到来自服务器的信息，客户端会认为那是个EOF，所以你就有可能没有收到任何数据／收到不完整的数据。至于200不200不能反映是否完整的传输了数据，因为200是写在header里的，而你的数据在body里，200总是比你的数据先到。

**Comment by DavidDiao** [comment]
@gnattu  ![image](https://user-images.githubusercontent.com/21342724/29358096-7320ba30-82ac-11e7-9f79-05bd5b207783.png)
请求头什么的不存在的

**Comment by yukixz** [comment]
@DavidDiao 你这都连接不上服务器了小哥……

**Comment by DavidDiao** [comment]
@yukixz 所以说这个 125.6.189.39 是什么的服务器啊

**Comment by KagamiChan** [comment]
@DavidDiao DMM 的服务器

**Comment by gnattu** [comment]
@DavidDiao 当然是你游服务器了

**Comment by yukixz** [comment]
@DavidDiao ブイン基地

**Comment by DavidDiao** [comment]
看了源码发现请求资源的服务器居然是伪随机的么。。这样不合理吧。。
比如把
`const server = SERVERS[(ship_id + admiral_id) % SERVERS.length];`改成
`const server = /https?:\/\/.+?\//.exec($('kan-game webview').getURL())[0];`之类的，然后后面的
`http://${server}/kcs/sound/kc${shipFilename}/${audioFN}.mp3`改成
`${server}kcs/sound/kc${shipFilename}/${audioFN}.mp3`是不是更合理呢

**Comment by gnattu** [comment]
@DavidDiao 你那样取不到服务器的ip，以前这个ip是只有proxy知道的，即使是现在也是靠静态维护一个服务器列表然后选出对应的ip

**Comment by gnattu** [comment]
@DavidDiao 并且并不是所有poi用户都有用那个webview，服务器ip是断断不能从webview去取的。

**Comment by DavidDiao** [comment]
@gnattu 因为我现在用的是OOI所以想错了。。而且刚才也没找到什么方法能够获取地址我也很无奈 ~~是不是真的就是没有~~
