### ISSUE TITLE
资源变化时矩形无法完全盖住数字

### ISSUE THREAD

**Issue by Kurotsuba** [poooi/poi#1524]
**poi 版本 / poi version:**
poi 7.8.0

**操作系统 / OS:**
Windows 10 1703

**插件名和版本 / Plugin name & version:**
插件无关

**你遇到了什么样的问题 / The problem you've met:**
当资源数量超过10000以后，资源变化的红色/绿色矩形无法完全盖住数字
虽然感觉并不影响使用，但是还是希望fix一下

**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:**
攒资然后补给一下咯

**Comment by KagamiChan** [comment]
请问使用的是哪个主题？

**Comment by KagamiChan** [comment]
有没有自定义过字体？

**Comment by Kurotsuba** [comment]
没有使用过自定义字体，主题是paperdark，布局是上面舰C下面插件的纵向布局（左起第二个）
