### ISSUE TITLE
打演习的同时在花骑士抽花 程序直接崩溃

### ISSUE THREAD

**Issue by Innowa** [poooi/poi#1527]
**poi 版本 / poi version:** v7.9.0

**操作系统 / OS:** 14393.1480

**插件名和版本 / Plugin name & version:** 一心二用 v2.9.0

**你遇到了什么样的问题 / The problem you've met:**
打演习的同时在花骑士抽花 程序直接崩溃

**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:**

**Comment by KagamiChan** [comment]
崩溃的表现是？

**Comment by Innowa** [comment]
一心二用和主程序的窗口直接没了 emmmm..刚开始加载花的时候就有卡顿了

**Comment by gnattu** [comment]
请问电脑内存大小和CPU？听起来很像资源耗尽

**Comment by Innowa** [comment]
Intel(R) Core(TM) i7-4710HQ 8G
