### ISSUE TITLE
POI鼠标预览功能（我都不知道实际怎么称呼...）

### ISSUE THREAD

**Issue by FungJiHsu** [poooi/poi#1528]
**poi 版本 / poi version:**
7.9

**操作系统 / OS:**

win10 版本1607

**你遇到了什么样的问题 / The problem you've met:**

如图，当POI最小化的时候，这个在鼠标放到POI最小化按钮上显示的气泡会出现在屏幕中央
去不掉，而且跟POI是同一个窗口置顶优先度
当POI没有最小化的时候，这个气泡就不见了

![qq 20170808103817](https://user-images.githubusercontent.com/14539399/29054076-64281dde-7c26-11e7-9f9d-0bd4b5628b2d.png)

**Comment by KagamiChan** [comment]
谢谢汇报，已知，已修复

**Comment by KagamiChan** [comment]
这个算是 windows 自己的 bug，chrome 上也会有类似的现象出现，我们能做的只是不让这个 minimize 显示出来 - -

**Comment by gnattu** [comment]
等待下个版本之前的一个临时应急方案：鼠标停在最小化按钮上等这个minimize出来然后再点最小化，他就没有了。
