### ISSUE TITLE
缩放后某些主题状态栏字体模糊的问题

### ISSUE THREAD

**Issue by Ryuuen** [poooi/poi#1530]
**poi 版本 / poi version:**
7.9.0

**操作系统 / OS:**
Win 10 15063.483

**插件名和版本 / Plugin name & version:**

**你遇到了什么样的问题 / The problem you've met:**
字体大小选择在90%时，状态栏的字体在某些主题下回变的模糊。

一个变模糊的例子：
![image](https://user-images.githubusercontent.com/7549347/29114810-62a072c6-7d30-11e7-8289-80de1a5cebd3.png)

可以看到，左侧的图标也是模糊的。

当点开状态栏的一瞬间，字体会变得清晰，然后又变得模糊。

请问有什么解决办法吗？
**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:**

**Comment by KochiyaOcean** [comment]
Chrome 的次级像素渲染问题，只能等待 Chrome 方面解决

**Comment by Ryuuen** [comment]
刚刚试了一下，好像点了禁用硬件加速重启程序之后，状态栏的字体就能变得清晰了。

**Comment by gnattu** [comment]
@Ryuuen 禁用硬件加速变清晰是意料之中的行为。从Chrome 37开始，Chrome在Windows上的字体渲染默认使用的是一种叫做DirectWrite的通过硬件加速的方法，一般认为这种方法比起之前的要先进，但是从启用之初就有各种表示字体模糊的报告，这个渲染机制也一度可以通过Chrome的flag关掉。但是很可惜，从Chrome53开始，这个flag就不复存在了，也就是说在支持硬件加速的场合将强制使用DirectWrite。
poi这边很难做出什么改变，只能说如果真的很介意的话就别开硬件加速了。
