### ISSUE TITLE
Game loops to account page ||  游戏循环到帐户页面

### ISSUE THREAD

**Issue by RitzyBusiness** [poooi/poi#1533]
操作系统 / OS: 15063.540 (Windows 10)
poi 版本 / poi version: 7.9.0

**你遇到了什么样的问题 / The problem you've met:**

![image](https://user-images.githubusercontent.com/18676276/29231865-d3b2e2f0-7eb6-11e7-9499-2f47d0a112f4.png)

Every time I click on Kancolle it loops back to this profile page.  (doesn't happen on my browser).
Google Translate: 每当我点击Kancolle，它会循环回到此个人资料页面。 （不会在我的浏览器上发生）。

**Developer Console**
![image](https://user-images.githubusercontent.com/18676276/29232031-92430696-7eb7-11e7-9c5e-45cb12674afa.png)

**Comment by gnattu** [comment]
登陆游戏后将游戏页面设为主页后还会这样吗

**Comment by RitzyBusiness** [comment]
It is fine, I figured it out with translate.  

I set the home page to http://www.dmm.com/netgame/social/-/gadgets/=/app_id=854854/ which works on chrome.  But in Poi it keeps redirecting to http://www.dmm.com/netgame/foreign/-/enable-list/=/app_id=854854/

**Comment by gnattu** [comment]
The "foreign" looks weird as it should not be in the url. Could you try to check the "Editing DMM Cookie's Region Flag" in settings and see if it works? It's located near the bottom of the `Common` tab.

**Comment by RitzyBusiness** [comment]
Yea thats what I just did, it worked perfectly.  Thanks for the response!
