### ISSUE TITLE
plugin-ship-info display bug

### ISSUE THREAD

**Issue by Jasonnor** [poooi/poi#1534]
**poi 版本 / poi version:** 
v7.9.0

**操作系统 / OS:** 
Windows 10 1703

**插件名和版本 / Plugin name & version:** 
舰娘信息 Ver 4.0.0

**你遇到了什么样的问题 / The problem you've met:**
在左上角锁头未锁（上方面板在往下卷动时会自动隐藏）的情况下，如果舰娘清单太短并且往下卷动，画面就会快速弹回，导致无法显示下方舰娘资讯。把锁头上锁就可以正常显示。

**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:**
如下图所示
![演示](http://i.imgur.com/lKwcOXA.gif)

**Comment by KagamiChan** [comment]
这个算是已知问题，并且暂时没有想到很好的解决方案，建议的操作还是把锁给锁上

技术分析：折叠的条件是下方表格的 scrollTop 大于 0，因此在这里往下滑动会触发折叠，但是折叠之后下方表格的高度增加，scrollTop 又变为 0 了，所以又回复到了不折叠的状态

**Comment by gnattu** [comment]
目前我认为比较可行也比较简单的方案就是延迟折叠触发，在滚动到一定行数之前不触发这个折叠效果。这样既不影响较短列表看到每一行数据，也能让较长列表充分利用窗口空间显示尽可能多的数据。由于存在折叠时本身就需要滚动来看翻阅所有数据，而且短列表远远达不到页面高度，并不存在滚动造成的额外操作成本在我看来微乎其微。

**Comment by KenLiu2** [comment]
顺便提醒一下
虽然舰娘一览更新了夏活贴条，但是出击计画beta没有跟著更新

**Comment by KagamiChan** [comment]
贴条数据都是一致的，外边的贴条显示更新了，出击计划里的区域也会跟着一起更新

你所说的没有跟着更新的表现是什么？

**Comment by gnattu** [comment]
Fixed via https://github.com/poooi/plugin-ship-info/pull/77

**Comment by KenLiu2** [comment]
回复晚了，的確就是出擊計畫跟外面不一致的情形，一覽已經是夏活貼條，出擊計畫卻是春活的，只到E4，勞您費心了，謝謝

**Comment by KochiyaOcean** [comment]
@KenLiu2 到设置-关于里更新数据

**Comment by KenLiu2** [comment]
修復了，十分感謝
