### ISSUE TITLE
出击计划不保存

### ISSUE THREAD

**Issue by DavidDiao** [poooi/poi#1535]
**poi 版本 / poi version:**
7.9.0

**操作系统 / OS:**
Windows 7 旗舰版

**插件名和版本 / Plugin name & version:**
舰娘信息 Ver 4.0.1

**你遇到了什么样的问题 / The problem you've met:**
出击计划是不保存的吗，一重启就都没了，还是我这里出了什么问题
另外建议加一个把已经锁上的船自动添加进去的功能

**Comment by KagamiChan** [comment]
@DavidDiao 嗯，前面这个是个 bug，后面这个有类似计划

**Comment by KagamiChan** [comment]
@DavidDiao 4.1.0 版已发，麻烦看一下是否解决了保存的问题

**Comment by DavidDiao** [comment]
@KagamiChan 解决了，谢谢。~~顺便吐槽好像更新后打开是上上次关闭时的状态。。~~
