### ISSUE TITLE
耗資記錄錯誤計算陸航消耗

### ISSUE THREAD

**Issue by jerry78424** [poooi/poi#1536]
**poi 版本 / poi version:**
7.9.0

**操作系统 / OS:**

windows7
**插件名和版本 / Plugin name & version:**

耗資記錄0.6.0 beta1

**你遇到了什么样的问题 / The problem you've met:**

![2017-08-17 - 00 37 42 myimgur v3 90 - myimgur eden fm x64](https://user-images.githubusercontent.com/3656749/29374540-507c96ce-82e4-11e7-8e1d-9cc3fab6f3ae.png)

**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:**

**Comment by KochiyaOcean** [comment]
这样看不出来哪里出错了啊……

**Comment by gnattu** [comment]
@KochiyaOcean 2-3陆航是不出击的，也自然没有消耗

**Comment by KochiyaOcean** [comment]
@gnattu 没直接说一下子没看出来🌚👌🏿

**Comment by dkwingsmt** [comment]
@jerry78424 麻烦展开陆基航空队一项，截图发一下

**Comment by KenLiu2** [comment]
其實我也遇到類似的事情，我是用token偷資源，發現到出擊會被記入。

**Comment by jerry78424** [comment]
@dkwingsmt 
![2017-08-17 - 04 00 53 myimgur v3 90 - myimgur eden fm x64](https://user-images.githubusercontent.com/3656749/29382921-cba2d108-8300-11e7-8b80-ced60b4533d0.png)

**Comment by dkwingsmt** [comment]
@jerry78424 ok果然是这样…… 我晚上发个新版看看

**Comment by jerry78424** [comment]
@dkwingsmt 
感謝您！

**Comment by dkwingsmt** [comment]
@jerry78424 发布了0.6.0-beta.2，看看还有没有问题

**Comment by jerry78424** [comment]
@dkwingsmt 已經修好了，謝謝。

**Comment by jerry78424** [comment]
<img width="491" alt="2017-10-07 - 02 04 37 myimgur v3 90 - myimgur eden fm x64" src="https://user-images.githubusercontent.com/3656749/31292132-d0174756-ab04-11e7-9e64-b6295c935f69.png">

Sorry to reopen this issue, but I found same bug on 6-1.
BTW the fuel required for repair isn't shown.
Plugin version is 0.6.1.

**Comment by dkwingsmt** [comment]
@jerry78424 非常感谢。我大概能想到这个是什么原因，晚点就修复
