### ISSUE TITLE
最小化提示不正常運作

### ISSUE THREAD

**Issue by polar2031** [poooi/poi#1537]
poi 版本 / poi version: v7.9.0

操作系统 / OS: Windows 10 1703

你遇到了什么样的问题 / The problem you've met:
點選最小化時若未等到提示出現，提示會在Poi最小化後跳出且不會消失，直到再次開啟
![default](https://user-images.githubusercontent.com/11768032/29449100-707b2c36-83c7-11e7-8ef3-9e91b9d1fccc.PNG)

**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:**
如上述

**Comment by KochiyaOcean** [comment]
属于 Windows 的 bug，现在已经移除
