### ISSUE TITLE
耗资记录无法正确记录修复桶的使用数量

### ISSUE THREAD

**Issue by 8972** [poooi/poi#1538]
**poi 版本 / poi version:**

v7.9.0

**操作系统 / OS:**

Version 1703 (Build 15063.540)

**插件名和版本 / Plugin name & version:**

耗资记录 v0.5.5

**你遇到了什么样的问题 / The problem you've met:**

打完e1，e2之后想看看一共花了多少桶。打开耗资记录，添加筛选，39-1。
下方的表格里每一次的出击记录都有正确的记录，但是第一行的总计里面桶的消耗确实0。
BUG 截图

![bug](https://user-images.githubusercontent.com/31164434/29488728-2d96b414-8550-11e7-97fa-6942f1c085a4.PNG)

PS
最新的测试版插件可以正常显示，但添加到书签时又会有0桶的现象发生

**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:**

**Comment by dkwingsmt** [comment]
更新了0.6.0-beta.3，你看看还有没有问题。
如果还有问题的话麻烦在设置里点击“打开记录文件存放处”，并把文件夹打个包发我下。

**Comment by 8972** [comment]
已经没问题了。

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10
