### ISSUE TITLE
显示伤害为实际伤害双倍

### ISSUE THREAD

**Issue by mirawy** [poooi/poi#1539]
**poi 版本 / poi version: ver.7.9.0**

**操作系统 / OS:win10 ver.1703**

**插件名和版本 / Plugin name & version:未卜先知 ver6.9.4**

**你遇到了什么样的问题 / The problem you've met:未卜先知显示伤害为实际伤害的双倍（演习时白天正常，夜战也会显示为伤害的双倍）；任务计数也显示为实际数量的双倍（不知道这是什么插件里的所以放一起说了）。**

**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:
未卜先知显示的伤害：
![default](https://user-images.githubusercontent.com/30952231/29525757-4a0dd39e-86c6-11e7-99da-0bb0119cc20b.png)
实际伤害/战斗记录的伤害：
![default](https://user-images.githubusercontent.com/30952231/29525738-37b3dde2-86c6-11e7-87e8-dd7aa5a16fb4.png)
开发者工具 Console 选项卡的截图：
![j _oh2 fr crog i lpdy](https://user-images.githubusercontent.com/30952231/29525923-c5057dcc-86c6-11e7-85ea-bd4febbb0698.png)
**

**Comment by KagamiChan** [comment]
可否方便在战斗记录里面点击复制数据，把出现双倍的战斗的数据粘贴到文本文件里传上来

**Comment by KagamiChan** [comment]
顺便，请问你是用什么方式连接游戏的，网络代理方面有没有做过什么设置

**Comment by mirawy** [comment]
复制数据如下（最近的一场战斗）：
{"version":"2.1","type":"Normal","map":[39,1,20],"desc":null,"time":1503329574131,"fleet":{"type":0,"main":[{"api_id":583,"api_sortno":102,"api_ship_id":82,"api_lv":89,"api_exp":[529409,16091,13],"api_nowhp":77,"api_maxhp":77,"api_soku":5,"api_leng":3,"api_onslot":[11,11,11,14,0],"api_kyouka":[23,0,47,18,0],"api_backs":6,"api_fuel":38,"api_bull":63,"api_slotnum":4,"api_ndock_time":0,"api_ndock_item":[0,0],"api_srate":4,"api_cond":91,"api_karyoku":[112,86],"api_raisou":[0,0],"api_taiku":[99,92],"api_soukou":[93,92],"api_kaihi":[72,77],"api_taisen":[9,0],"api_sakuteki":[68,60],"api_lucky":[30,79],"api_locked":1,"api_locked_equip":1,"api_sally_area":1,"poi_slot":[{"api_id":19333,"api_slotitem_id":161,"api_locked":1,"api_level":0},{"api_id":33380,"api_slotitem_id":10,"api_locked":0,"api_level":0},{"api_id":29372,"api_slotitem_id":62,"api_locked":1,"api_level":0,"api_alv":7},{"api_id":36497,"api_slotitem_id":208,"api_locked":1,"api_level":0,"api_alv":7},null],"poi_slot_ex":null},{"api_id":45,"api_sortno":160,"api_ship_id":160,"api_lv":96,"api_exp":[737841,23659,60],"api_nowhp":48,"api_maxhp":48,"api_soku":10,"api_leng":2,"api_onslot":[1,1,1,0,0],"api_kyouka":[46,56,51,39,0],"api_backs":6,"api_fuel":10,"api_bull":21,"api_slotnum":3,"api_ndock_time":0,"api_ndock_item":[0,0],"api_srate":4,"api_cond":85,"api_karyoku":[80,68],"api_raisou":[84,84],"api_taiku":[86,75],"api_soukou":[68,68],"api_kaihi":[81,82],"api_taisen":[88,85],"api_sakuteki":[58,54],"api_lucky":[13,84],"api_locked":1,"api_locked_equip":1,"api_sally_area":1,"poi_slot":[{"api_id":9463,"api_slotitem_id":50,"api_locked":1,"api_level":6},{"api_id":14197,"api_slotitem_id":91,"api_locked":1,"api_level":0},{"api_id":38957,"api_slotitem_id":59,"api_locked":1,"api_level":0,"api_alv":7},null,null],"poi_slot_ex":null},{"api_id":2024,"api_sortno":1393,"api_ship_id":293,"api_lv":76,"api_exp":[335916,7484,39],"api_nowhp":12,"api_maxhp":36,"api_soku":10,"api_leng":2,"api_onslot":[0,0,0,0,0],"api_kyouka":[40,55,49,21,0],"api_backs":6,"api_fuel":10,"api_bull":24,"api_slotnum":4,"api_ndock_time":12270000,"api_ndock_item":[19,36],"api_srate":4,"api_cond":49,"api_karyoku":[68,63],"api_raisou":[79,79],"api_taiku":[91,69],"api_soukou":[49,49],"api_kaihi":[68,69],"api_taisen":[59,69],"api_sakuteki":[37,44],"api_lucky":[17,69],"api_locked":1,"api_locked_equip":1,"api_sally_area":1,"poi_slot":[{"api_id":17326,"api_slotitem_id":122,"api_locked":1,"api_level":1},{"api_id":13103,"api_slotitem_id":91,"api_locked":1,"api_level":0},{"api_id":31764,"api_slotitem_id":129,"api_locked":1,"api_level":0},{"api_id":39411,"api_slotitem_id":40,"api_locked":0,"api_level":0},null],"poi_slot_ex":null},{"api_id":300,"api_sortno":141,"api_ship_id":141,"api_lv":90,"api_exp":[553692,10808,43],"api_nowhp":31,"api_maxhp":44,"api_soku":10,"api_leng":1,"api_onslot":[0,0,0,0,0],"api_kyouka":[41,55,39,39,0],"api_backs":5,"api_fuel":10,"api_bull":18,"api_slotnum":3,"api_ndock_time":7570000,"api_ndock_item":[10,19],"api_srate":4,"api_cond":49,"api_karyoku":[65,59],"api_raisou":[79,79],"api_taiku":[105,84],"api_soukou":[69,69],"api_kaihi":[80,79],"api_taisen":[90,94],"api_sakuteki":[57,59],"api_lucky":[13,67],"api_locked":1,"api_locked_equip":1,"api_sally_area":1,"poi_slot":[{"api_id":17008,"api_slotitem_id":122,"api_locked":1,"api_level":0},{"api_id":18477,"api_slotitem_id":122,"api_locked":1,"api_level":0},{"api_id":27111,"api_slotitem_id":129,"api_locked":1,"api_level":0},null,null],"poi_slot_ex":null},{"api_id":66,"api_sortno":268,"api_ship_id":468,"api_lv":92,"api_exp":[606481,19,99],"api_nowhp":30,"api_maxhp":34,"api_soku":10,"api_leng":1,"api_onslot":[0,0,0,0,0],"api_kyouka":[40,50,44,40,0],"api_backs":7,"api_fuel":6,"api_bull":12,"api_slotnum":3,"api_ndock_time":2430000,"api_ndock_item":[1,3],"api_srate":4,"api_cond":59,"api_karyoku":[58,52],"api_raisou":[86,86],"api_taiku":[103,74],"api_soukou":[55,55],"api_kaihi":[88,88],"api_taisen":[85,89],"api_sakuteki":[51,55],"api_lucky":[17,70],"api_locked":1,"api_locked_equip":1,"api_sally_area":1,"poi_slot":[{"api_id":11139,"api_slotitem_id":122,"api_locked":1,"api_level":6},{"api_id":9797,"api_slotitem_id":122,"api_locked":1,"api_level":6},{"api_id":14995,"api_slotitem_id":131,"api_locked":1,"api_level":0},null,null],"poi_slot_ex":null},{"api_id":169,"api_sortno":218,"api_ship_id":418,"api_lv":92,"api_exp":[595869,10631,51],"api_nowhp":28,"api_maxhp":28,"api_soku":10,"api_leng":1,"api_onslot":[0,0,0,0,0],"api_kyouka":[34,51,42,33,0],"api_backs":6,"api_fuel":6,"api_bull":9,"api_slotnum":3,"api_ndock_time":0,"api_ndock_item":[0,0],"api_srate":4,"api_cond":49,"api_karyoku":[48,42],"api_raisou":[78,78],"api_taiku":[111,82],"api_soukou":[45,45],"api_kaihi":[96,96],"api_taisen":[77,81],"api_sakuteki":[42,45],"api_lucky":[20,79],"api_locked":1,"api_locked_equip":1,"api_sally_area":1,"poi_slot":[{"api_id":25823,"api_slotitem_id":122,"api_locked":1,"api_level":6},{"api_id":9000,"api_slotitem_id":122,"api_locked":1,"api_level":6},{"api_id":4978,"api_slotitem_id":131,"api_locked":1,"api_level":0},null,null],"poi_slot_ex":null}],"escort":null,"support":null,"LBAC":null},"packet":[{"api_dock_id":1,"api_ship_ke":[-1,1621,1526,1639,1638,1638,-1],"api_ship_lv":[-1,1,1,1,1,1,-1],"api_nowhps":[-1,77,48,12,31,30,28,39,80,15,9,9,-1],"api_maxhps":[-1,77,48,36,44,34,28,39,80,15,9,9,-1],"api_midnight_flag":0,"api_eSlot":[[502,502,559,-1,-1],[501,503,503,-1,-1],[515,515,-1,-1,-1],[515,515,-1,-1,-1],[515,515,-1,-1,-1],[-1,-1,-1,-1,-1]],"api_eKyouka":[[0,0,0,0],[0,0,0,0],[0,0,0,0],[0,0,0,0],[0,0,0,0],[0,0,0,0]],"api_fParam":[[86,0,92,92],[68,84,75,68],[63,79,69,49],[59,79,84,69],[52,86,74,55],[42,78,82,45]],"api_eParam":[[48,76,40,30],[15,0,0,35],[15,98,18,29],[9,98,18,29],[9,98,18,29],[0,0,0,0]],"api_search":[1,5],"api_formation":[1,2,1],"api_stage_flag":[1,1,1],"api_kouku":{"api_plane_from":[[1],[-1]],"api_stage1":{"api_f_count":25,"api_f_lostcount":0,"api_e_count":0,"api_e_lostcount":0,"api_disp_seiku":1,"api_touch_plane":[-1,-1]},"api_stage2":{"api_f_count":25,"api_f_lostcount":1,"api_e_count":0,"api_e_lostcount":0},"api_stage3":{"api_frai_flag":[-1,0,0,0,0,0,0],"api_erai_flag":[-1,0,0,0,0,0,0],"api_fbak_flag":[-1,0,0,0,0,0,0],"api_ebak_flag":[-1,1,0,1,0,0,0],"api_fcl_flag":[-1,0,0,0,0,0,0],"api_ecl_flag":[-1,0,0,0,0,0,0],"api_fdam":[-1,0,0,0,0,0,0],"api_edam":[-1,0,0,0,0,0,0]}},"api_support_flag":0,"api_support_info":null,"api_opening_taisen_flag":0,"api_opening_taisen":null,"api_opening_flag":0,"api_opening_atack":null,"api_hourai_flag":[1,1,0,0],"api_hougeki1":{"api_at_list":[-1,1,2,8,3,7,6,4,5],"api_at_type":[-1,0,2,0,0,0,0,0,0],"api_df_list":[-1,[10],[11,11],[2],[9],[4],[11],[8],[8]],"api_si_list":[-1,[161],["50","91"],[501],[122],[502],[122],[122],[122]],"api_cl_list":[-1,[1],[1,1],[1],[1],[1],[1],[1],[1]],"api_damage":[-1,[61],[1,0],[6],[54.1],[3],[55],[36],[24]]},"api_hougeki2":{"api_at_list":[-1,1,2],"api_at_type":[-1,3,0],"api_df_list":[-1,[7],[8]],"api_si_list":[-1,["62","161","10"],[50]],"api_cl_list":[-1,[1],[2]],"api_damage":[-1,[93],[94]]},"api_hougeki3":null,"api_raigeki":null,"poi_path":"/kcsapi/api_req_sortie/battle","poi_time":1503329574131},{"api_dock_id":1,"api_ship_ke":[-1,1621,1526,1639,1638,1638,-1],"api_ship_lv":[-1,1,1,1,1,1,-1],"api_nowhps":[-1,77,48,12,31,30,28,39,80,15,9,9,-1],"api_maxhps":[-1,77,48,36,44,34,28,39,80,15,9,9,-1],"api_midnight_flag":0,"api_eSlot":[[502,502,559,-1,-1],[501,503,503,-1,-1],[515,515,-1,-1,-1],[515,515,-1,-1,-1],[515,515,-1,-1,-1],[-1,-1,-1,-1,-1]],"api_eKyouka":[[0,0,0,0],[0,0,0,0],[0,0,0,0],[0,0,0,0],[0,0,0,0],[0,0,0,0]],"api_fParam":[[86,0,92,92],[68,84,75,68],[63,79,69,49],[59,79,84,69],[52,86,74,55],[42,78,82,45]],"api_eParam":[[48,76,40,30],[15,0,0,35],[15,98,18,29],[9,98,18,29],[9,98,18,29],[0,0,0,0]],"api_search":[1,5],"api_formation":[1,2,1],"api_stage_flag":[1,1,1],"api_kouku":{"api_plane_from":[[1],[-1]],"api_stage1":{"api_f_count":25,"api_f_lostcount":0,"api_e_count":0,"api_e_lostcount":0,"api_disp_seiku":1,"api_touch_plane":[-1,-1]},"api_stage2":{"api_f_count":25,"api_f_lostcount":1,"api_e_count":0,"api_e_lostcount":0},"api_stage3":{"api_frai_flag":[-1,0,0,0,0,0,0],"api_erai_flag":[-1,0,0,0,0,0,0],"api_fbak_flag":[-1,0,0,0,0,0,0],"api_ebak_flag":[-1,1,0,1,0,0,0],"api_fcl_flag":[-1,0,0,0,0,0,0],"api_ecl_flag":[-1,0,0,0,0,0,0],"api_fdam":[-1,0,0,0,0,0,0],"api_edam":[-1,0,0,0,0,0,0]}},"api_support_flag":0,"api_support_info":null,"api_opening_taisen_flag":0,"api_opening_taisen":null,"api_opening_flag":0,"api_opening_atack":null,"api_hourai_flag":[1,1,0,0],"api_hougeki1":{"api_at_list":[-1,1,2,8,3,7,6,4,5],"api_at_type":[-1,0,2,0,0,0,0,0,0],"api_df_list":[-1,[10],[11,11],[2],[9],[4],[11],[8],[8]],"api_si_list":[-1,[161],["50","91"],[501],[122],[502],[122],[122],[122]],"api_cl_list":[-1,[1],[1,1],[1],[1],[1],[1],[1],[1]],"api_damage":[-1,[61],[1,0],[6],[54.1],[3],[55],[36],[24]]},"api_hougeki2":{"api_at_list":[-1,1,2],"api_at_type":[-1,3,0],"api_df_list":[-1,[7],[8]],"api_si_list":[-1,["62","161","10"],[50]],"api_cl_list":[-1,[1],[2]],"api_damage":[-1,[93],[94]]},"api_hougeki3":null,"api_raigeki":null,"poi_path":"/kcsapi/api_req_sortie/battle","poi_time":1503329574134},{"api_ship_id":[-1,1621,1526,1639,1638,1638,-1],"api_win_rank":"S","api_get_exp":100,"api_mvp":1,"api_member_lv":109,"api_member_exp":5823547,"api_get_base_exp":160,"api_get_ship_exp":[-1,576,192,192,192,192,192],"api_get_exp_lvup":[[529409,545500],[737841,761500],[335916,343400],[553692,564500],[606481,606500,631500],[595869,606500]],"api_dests":5,"api_destsf":1,"api_lost_flag":[-1,0,0,0,0,0,0],"api_quest_name":"リンガ泊地沖","api_quest_level":7,"api_enemy_info":{"api_level":"","api_rank":"","api_deck_name":"深海南方配備魚雷艇部隊 I群"},"api_first_clear":0,"api_mapcell_incentive":0,"api_get_flag":[0,0,0],"api_get_eventflag":0,"api_get_exmap_rate":0,"api_get_exmap_useitem_id":0,"poi_path":"/kcsapi/api_req_sortie/battleresult","poi_time":1503329624480}]}

通过poi浏览器和岛风go连接游戏
http代理

**Comment by KagamiChan** [comment]
可以看到的是同一个包被接收了两次
检查一下你的代理设置吧，包括 poi 网络设置里面的高级设置

**Comment by mirawy** [comment]
谢谢。
