### ISSUE TITLE
无法显示猫的类型

### ISSUE THREAD

**Issue by LowenSunday** [poooi/poi#1540]
poi 版本 / poi version: v7.9.0

操作系统 / OS: Windows 10 版本1703

你遇到了什么样的问题 / The problem you've met:
原来poi的小提示出现的那个底栏在猫的时候会给出是什么类型的猫，然而现在却没有了_( ﾟДﾟ)ﾉ

有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:
本人用的是ssr，poi里面的网络代理选的是HTTP代理。一般猫的时候服务器连接统计里面显示的是连续4次超时，然后就猫了_(:зゝ∠)_

![image](https://user-images.githubusercontent.com/23163322/29563307-888c592a-876f-11e7-9d78-836e34551db2.png)
![image](https://user-images.githubusercontent.com/23163322/29563316-8c50aa66-876f-11e7-87a9-bb694317d565.png)

**Comment by KochiyaOcean** [comment]
@LowenSunday 没有提示就是普通的断网而已

**Comment by LowenSunday** [comment]
@KochiyaOcean 原来是酱紫嘛_(:зゝ∠)_谢谢(｡･∀･)ﾉﾞ
