### ISSUE TITLE
能否提供一个还原为系统标题栏的功能

### ISSUE THREAD

**Issue by WAAutoMaton** [poooi/poi#1543]
**poi 版本 / poi version:**
7.9.0

**操作系统 / OS:**

Ubuntu 16.04 LTS （桌面管理器为Unity）

**你遇到了什么样的问题 / The problem you've met:**
![image](https://user-images.githubusercontent.com/24771667/29694643-65a508ea-8903-11e7-9860-8d52303dfa82.png)
更新到7.9.0之后poi自行绘制了标题栏，但是没能取消掉Unity的默认标题栏，导致2个标题栏同时显示。（而且poi自己绘制的标题栏风格和Unity差距较大）
希望能提供一个还原为7.9.0以前的默认标题栏的选项

**Comment by gnattu** [comment]
poi的标题栏其实是无边框窗口画一个自己的标题达成的，unity最大化窗口的时候会隐藏窗口的标题栏，但是由于对于unity来讲poi是个无边框窗口，也就是没有标题栏，poi也并不会在最大化的时候隐藏自己的标题栏，所以会有这样的情况。

现在其实是有这么个隐藏选项的: `poi.useCustomTitleBar`设置为`false`的时候就不会使用自定义标题栏。可以打开poi的设置目录找到`config.cson`，如果找不到可以打开插件目录然后查找其上级目录（可能要连跳两级），在`config.cson`的poi区块中加入`useCustomTitleBar: false`并保存。
比如：
```
poi:
  theme: "darklykai"
  layout: "horizontal"
  useCustomTitleBar: false
```

**Comment by WAAutoMaton** [comment]
十分感谢！
