### ISSUE TITLE
无法打开插件和设置页面

### ISSUE THREAD

**Issue by toooonyy** [poooi/poi#1546]
**poi 版本 / poi version:**
7.9.1

**操作系统 / OS:**
macOS 10.12.6

**插件名和版本 / Plugin name & version:**
未卜先知
经验计算
编成记录
航海日志
战斗记录
自动刷新 poi-plugin-auto-refresher
耗资记录
装备改修
舰娘信息
装备信息
战果计算 poi-plugin-achievement
(都是最新版本)

**你遇到了什么样的问题 / The problem you've met:**
开 poi 后设置和插件点击无反应，游戏正常显示，console 的图在下方，safe mode 下可以开设置。

**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:**
不清楚怎么重现，最近出现了两次，前一次把 poi 那个缓存文件夹清掉就好了。用了魔改，应该和 poi 本体问题没关系？

![screen shot 2017-08-26 at 12 15 35](https://user-images.githubusercontent.com/3480434/29738575-6516b6fc-8a58-11e7-92ce-5f3a496ed06d.png)

**Comment by gnattu** [comment]
请发一下console页面顶部的截图，谢谢

**Comment by toooonyy** [comment]
呃，现在又好了...这是正常启动的画面。![screen shot 2017-08-26 at 12 56 23](https://user-images.githubusercontent.com/3480434/29738720-1b2d6094-8a5e-11e7-8a4f-e7b59fdc0b9f.png)

出现问题的只有文字 log 了


[2.txt](https://github.com/poooi/poi/files/1253414/2.txt)
[1.txt](https://github.com/poooi/poi/files/1253413/1.txt)

**Comment by KagamiChan** [comment]
poi-plugin-achievement 出错了，目测是没有考虑初始启动没有数据的情况。cc @Javran @a26214311

**Comment by a26214311** [comment]
已修复
