### ISSUE TITLE
希望装备改修插件能显示「要被消耗的装备」之所持数量

### ISSUE THREAD

**Issue by Jasonnor** [poooi/poi#1549]
例如：（此为改图）
![示意图](http://i.imgur.com/SCgETBm.png)

在**消耗装备**後方显示自己还剩多少这个装备，如此可以快速判断是否可以改修

平常都得打开装备一览进行确认，有点麻烦

目前我的替代作法是在上面另外设一个**持有**的计画，例如我想快速看到91AP有几个能当肥料，就设定如图：![示意图2](http://i.imgur.com/jXiBd94.png)

然而，缺点一：它会把所有改修星级的数量加总显示，上图就把+MAX的91AP也加上去列出来了，但是我想看的是无星的91AP肥料，只能自己列持有和+MAX两列，然後相减得解，而且得展开才能看到

缺点二：有些可消耗装备不在改修列表中，还是得去装备一览查看数量

希望能有这辅助功能，或者有其他现成解法也欢迎告知！

**Comment by KochiyaOcean** [comment]
有此预定，不过并没有详细的完成计划
