### ISSUE TITLE
能不能加个F5是否刷新页面的选项

### ISSUE THREAD

**Issue by DavidDiao** [poooi/poi#1553]
**poi 版本 / poi version:**
7.9.1

**操作系统 / OS:**
Win7

**你遇到了什么样的问题 / The problem you've met:**
平时切窗口用的都是Alt+Tab，然后一不小心切到了poi上，因为在调JS所以顺手一个F5，并且正好在出击中，然后就悲剧了。。。
或者就像关闭时那样加个确认框也行

**Comment by KagamiChan** [comment]
@DavidDiao 这个算是某种应急刷新措施。行为更改之后可能会造成新的更严重的困扰。举个例子，三舰大破进击，如果 f5 之后还有一个提示的话，可能就来不及了

**Comment by DavidDiao** [comment]
@KagamiChan 所以我的建议是加一个选项，而不是取消这个功能。而且大破进击只要在选阵型、开始战斗四个字出现前都不会有问题不是么

**Comment by KagamiChan** [comment]
@DavidDiao 三舰及以下进击是没有选阵型的。这个就和大破提示没有关闭选项一样，不希望有因为手滑勾选造成的遗憾

**Comment by KagamiChan** [comment]
@DavidDiao 你有需要的话可以自己本地修改一下

**Comment by KagamiChan** [comment]
@DavidDiao https://github.com/poooi/poi/blob/bc48d812b08d7b27172543cd0ec97669eb7a0bce/views/services.es#L59

你可以使用 git 开发版本

**Comment by KochiyaOcean** [comment]
@KagamiChan 7.9.0 以后放弃了 asar 打包方式，直接进安装目录修改也是可以的

**Comment by gnattu** [comment]
我觉得加个选项其实依然是可行的，只要不在GUI中提供更改的方式便不会有手滑勾选的问题。总不至于说有人能手滑到手操配置文件弄成了不刷新。
