### ISSUE TITLE
关于POI浏览器在高分屏下的显示问题

### ISSUE THREAD

**Issue by DasElfenLied** [poooi/poi#1554]
**poi 版本 / poi version:**

v7.9.1

**操作系统 / OS:**

Version 10.0 (Build 10240)

**插件名和版本 / Plugin name & version:**

**你遇到了什么样的问题 / The problem you've met:**

我的电脑使用2K显示器（分辨率2560 * 1440）进行游戏，运行过程中发现菜单界面的字体能够高分辨率显示，但flash中的游戏本体出现了画面不清晰的情况。尝试过设置“禁用高DPI下缩放”，但没有效果。

**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:**

**Comment by KochiyaOcean** [comment]
@DasElfenLied 缩放倍率是？

**Comment by gnattu** [comment]
如果没有高清魔改，Flash游戏本体就是会不清晰。游戏资源本身分辨率并不高。

**Comment by DasElfenLied** [comment]
缩放倍率是100%，实际上将缩放倍率调整为50%字体和画面也同样不清晰。

**Comment by KochiyaOcean** [comment]
@DasElfenLied 唯一能够清晰的游戏分辨率是 800*480，在显示设置里面设置

**Comment by gnattu** [comment]
缩放字体不清晰是Chrome的问题，详情参见：
https://github.com/poooi/poi/issues/1530
游戏只要不是原生大小都不可能清晰，除非使用高清魔改
默认大小800*480
如果是使用800*480，请检查系统屏幕缩放比例，然后按照比例缩小游戏画面。
或者直接使用高清魔改

**Comment by DasElfenLied** [comment]
![image](https://user-images.githubusercontent.com/19374026/29834407-5fdb208a-8d21-11e7-928d-8d9c01519c8b.png)
这个是目前的设置

**Comment by KochiyaOcean** [comment]
系统的缩放倍率是？（右击桌面 - 系统分辨率

**Comment by gnattu** [comment]
很明显你的系统已经有缩放了，这个截图里面游戏占用了1000x600的游戏画面。
请把比例缩小到75%以下

**Comment by DasElfenLied** [comment]
系统的缩放倍率是125%

**Comment by gnattu** [comment]
使用高清魔改或者poi设置中缩小游戏画面比例可以避免模糊，这个不是poi的问题，而是游戏自身素材分辨率过低导致

**Comment by KochiyaOcean** [comment]
@DasElfenLied 那你应该设置为 800 / 1.25 = 640

**Comment by DasElfenLied** [comment]
@KochiyaOcean @gnattu 设置分辨率640*384后恢复正常了，多谢二位的解答！
