### ISSUE TITLE
卡登入小白船

### ISSUE THREAD

**Issue by SoutouKakka** [poooi/poi#1556]
**poi 版本 / poi version:** v7.9.1

**操作系统 / OS:** windows 10 (1607)

**你遇到了什么样的问题 / The problem you've met:** 
卡登入小白船  
![](http://i.imgur.com/fahX4ZS.png)  
console log  
![](http://i.imgur.com/e8YUvyx.png)

**Comment by KochiyaOcean** [comment]
@SoutouKakka 清除缓存，如果无效，检查代理是否出现问题

**Comment by SoutouKakka** [comment]
緩存清除了, 沒使用代理
能看到game start頁面, 之後就卡小白船了
![](http://i.imgur.com/p6252EO.png)

**Comment by KochiyaOcean** [comment]
@SoutouKakka 感觉是网络状态不好导致缓存无法下载……

**Comment by SoutouKakka** [comment]
可是在chrome是能正常打開的, poi的話就卡在這邊
一心二用也是同樣情況

DMM網站能正常加載

**Comment by KochiyaOcean** [comment]
@SoutouKakka cookie 也清除呢

**Comment by SoutouKakka** [comment]
cookie已經清除了, 連在app data的poi資料夾也砍了也不行
這下真是耐人尋味

**Comment by KochiyaOcean** [comment]
@SoutouKakka 上一次正常使用 poi 是什么时候

**Comment by SoutouKakka** [comment]
今天早上

**Comment by KochiyaOcean** [comment]
@SoutouKakka Chrome 清除缓存后重新打开呢

**Comment by SoutouKakka** [comment]
依舊卡在小白船

**Comment by KagamiChan** [comment]
@SoutouKakka 如果 chrome 里面清除了缓存也和 poi 里一样卡小白船的话，那大致可以推定是网络的问题了

**Comment by SoutouKakka** [comment]
對不起表達有誤,
chrome 清除了緩存依舊可以登入,
poi依舊卡小白船

**Comment by KochiyaOcean** [comment]
@SoutouKakka poi 是否使用了缓存包

**Comment by SoutouKakka** [comment]
沒有使用緩存包

**Comment by KochiyaOcean** [comment]
@SoutouKakka 感觉这个问题已经进入玄学领域了……

**Comment by KagamiChan** [comment]
虽然不确认有没有用，可以在开发者工具图标上右键，打开游戏网页的开发者工具，切换到 network，勾选 disable cache，然后刷新一下重新进入游戏，看看有没有哪一些请求是标成红色的（status 是 4xx 和 5xx 的），有红色的话一般就是有问题的。

![image](https://user-images.githubusercontent.com/3816900/29885675-347f82fe-8dea-11e7-87bc-61f3304d10e0.png)

请注意这里面的 mainD2.swf 的地址 __会暴露你的敏感信息，截图的时候检查一下__

**Comment by SoutouKakka** [comment]
連不上api_start2
![](http://i.imgur.com/c9xPANG.png)
