### ISSUE TITLE
poi打开的情况下， PS无法使用快捷键ctrl shift I 进行选区反选

### ISSUE THREAD

**Issue by yortiss** [poooi/poi#1557]
**poi 版本 / poi version:7.9.1**

**操作系统 / OS:win10 X64 1703**

**插件名和版本 / Plugin name & version:**

**你遇到了什么样的问题 / The problem you've met:**

poi打开的情况下， PS无法使用快捷键ctrl shift I 进行选区反选
关闭后就正常了

**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:**

**Comment by gnattu** [comment]
看起来是Ctrl+Shift+I开启开发者工具的热键与PS的区域反选冲突了。

**Comment by gnattu** [comment]
https://github.com/poooi/poi/blob/1cacd3a946f0aaaf043099e1f34cdc32e737ca90/lib/shortcut.es#L1
现在这个快捷键绑定方式是Global Shortcuts，会在窗口不处于激活状态时依然监听快捷键，老板键是必然要这么做的，但是我不清楚开发者工具使用Global Shortcuts的原因，因为没有窗口激活的时候开发者工具并不会打开，改成Local Shortcuts可以避免此类问题。
