### ISSUE TITLE
Question regarding when can we expect English subs

### ISSUE THREAD

**Issue by Kristjan-Zagar** [poooi/poi#1559]
I've heard that you'll be adding support for also showing quotes from the english database or should I say JSON, for the subtitles in English. That would really really be amazing, because not always knowing what our shipgirls are saying on the Poi viewer can be quite sad sometimes

When can we expect that? 

Thanks in advance for your reply.

**Comment by KochiyaOcean** [comment]
cc @grzhan

**Comment by KagamiChan** [comment]
There has been a similar issue #1550, let's continue our discussion there
