### ISSUE TITLE
關於耗資紀錄多位使用者的問題

### ISSUE THREAD

**Issue by daic50577** [poooi/poi#1561]
poi 版本 / poi version: v7.9.0

操作系统 / OS: window7 x64

插件名和版本 / Plugin name & version:耗資記錄 Ver 0.6.0

你遇到了什么样的问题 / The problem you've met:
約幾個小時前使用第二個遊戲帳號登入出擊，隨後關閉poi之後再重登主帳號，發現主帳號之前的耗資紀錄都讀不到了，只剩下切回來之後的出擊耗資記錄，請問有用回原先記錄的方法嗎?
![55555](https://user-images.githubusercontent.com/31574246/29998164-51d9658c-905f-11e7-98c6-ff256af2e3aa.jpg)

**Comment by KagamiChan** [comment]
耗资记录的内容是分帐号记录的
再次使用主帐号登入就可以看到了

**Comment by daic50577** [comment]
有試著切回來，但先前的紀錄都消失了，之前的書籤變成
![default](https://user-images.githubusercontent.com/31574246/29998263-9a41f6ac-9061-11e7-96d8-396d69524dd0.jpg)
這樣

**Comment by KagamiChan** [comment]
cc @dkwingsmt

**Comment by jerry78424** [comment]
same problem here, record log is wiped while changing accounts.

**Comment by WAAutoMaton** [comment]
poi v8.0.0
耗资记录插件 v0.6.3
先登录其他人的账号，再登录自己的账号后遇到了同样的问题，存放数据的文件夹中已找不到以前的耗资信息
