### ISSUE TITLE
[Discussion] What should we improve for English-speaking users?

### ISSUE THREAD

**Issue by magicae** [poooi/poi#1562]
After some analysis, we found out that there have been much more English users using poi with this summer event. Everyday we might face ~40 new English-speaking users in these days. And it's noticeable that more English users came to our GitHub and submitted issues.
Databoard: https://datastudio.google.com/open/0BwFJCLDPMeLEN2ZYNU44X19TNkU

So it should be a good time to make progress in our English support, and I open this issue as a meta issue that collects and tracks English-related issues. Feel free to comment and modify this issue content if you have new idea/request/progress.

- [ ] English group (Telegram?)
- [ ] English subtitle https://github.com/poooi/poi/issues/1550

**Comment by KagamiChan** [comment]
Suggestions:
- another telegram channel for English speaking users
- more translation strings (mission, map, maparea) in poi-translator
- internationalized user guide, and the Chinese one seems a little outdated
