### ISSUE TITLE
Contributor graph

### ISSUE THREAD

**Issue by KagamiChan** [poooi/poi#1564]
With #1542 we introduced an contributor graph on readme, but this graph is not complete since the contribution data only go from poooi/poi repo, and we are missing:
- contributors that do not directly send commit to the project
- contributors from other repo, e.g. plugins

I'm planning to make a more complete contributor graph for the project, it will be similar to what opencollective provides but includes the missing parts

**Comment by KagamiChan** [comment]
finished creating contributor graph and data
we could use this data for main poi contributor display

**Comment by yukixz** [comment]
would better build graph on poi building

**Comment by KagamiChan** [comment]
@yukixz 收集数据和制作 svg 的时候有大量的网络请求，感觉会增加 ci 崩的机率

github API 有访问数量限制，需要请求时填 auth 信息才能保证不被拉闸，需要在 ci 上设置环境变量

**Comment by KagamiChan** [comment]
制作 svg 用的 sharp.js 有一些要本地下载编译的 native 模块
如果只是收集数据不生成 svg 的话倒是还好

**Comment by yukixz** [comment]
@KagamiChan 居然不是一个api搞定...

**Comment by KagamiChan** [comment]
@yukixz 获取信息：
- 请求 org 的 repo 列表
- 请求 repo 的 contribution stat
- 请求 contributor 的 profile 获取 name

制作 svg：
- 请求 avatar
