### ISSUE TITLE
poi和OOI - 舰娘在线缓存系统有迷之兼容不良问题

### ISSUE THREAD

**Issue by lhwlhw** [poooi/poi#1566]
用ooi+poi游戏会经常卡住，比如接任务右下角那个小圈圈经常就卡住或者无限转，要不回母港要不战斗结束七七八八的，都非常容易卡。不得不频繁刷新flash。
版本我试过最新版到去年的版本，都一样，试过电信宽带试过移动宽带，试过win和osx，缓存cookies都清过多次，都是这样。
但是ooi和kcv或者浏览器直接运行时又非常稳定，只有当使用poi时会频繁卡住。
现在我也不懂什么问题，不知道是poi对ooi兼容不行还是ooi对poi兼容不行。
希望能作者能抽空看看这个奇怪的问题。

**Comment by KagamiChan** [comment]
能在网络日志里面看到是某个 api 超时失败，但是无法确认是什么原因

**Comment by lhwlhw** [comment]
目前靠增加网络错误重试次数缓解这个问题，不懂会不会翻车
