### ISSUE TITLE
耗资记录图片错位？

### ISSUE THREAD

**Issue by wafer-li** [poooi/poi#1567]
**poi 版本 / poi version:** 
7.9.1

**操作系统 / OS:** 
OSX 10.11.6

**插件名和版本 / Plugin name & version:** 
耗资记录 0.6.0

**你遇到了什么样的问题 / The problem you've met:**
图片错位？

![image](https://user-images.githubusercontent.com/12459199/30121001-5dd94330-9365-11e7-83c6-7b908af84cb8.png)

**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:**

![image](https://user-images.githubusercontent.com/12459199/30121018-6b3df232-9365-11e7-935a-abd035c1d4f8.png)

**Comment by KagamiChan** [comment]
@wafer-li 重启 poi 看一下？

**Comment by wafer-li** [comment]
@KagamiChan 没用

**Comment by KagamiChan** [comment]
哦，我这边也看到了 cc @dkwingsmt

**Comment by gnattu** [comment]
看起来是新版图标导致的样式丢失
