### ISSUE TITLE
航海日志时间穿越？

### ISSUE THREAD

**Issue by wafer-li** [poooi/poi#1568]
**poi 版本 / poi version:**
7.9.1

**操作系统 / OS:**

OSX 10.11.6

**插件名和版本 / Plugin name & version:**
航海日志 6.1.2

**你遇到了什么样的问题 / The problem you've met:**
时间穿越？
![image](https://user-images.githubusercontent.com/12459199/30157561-999dbef8-93fd-11e7-93b7-97aa2effc3c7.png)

看来只发生在资源图上，表格没有这个问题。　
![image](https://user-images.githubusercontent.com/12459199/30157574-a6963450-93fd-11e7-8c4e-5d9933c31b63.png)

**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:**
![image](https://user-images.githubusercontent.com/12459199/30157642-d166e292-93fd-11e7-96ac-57ea77a4d60e.png)

顺便一提系统时间是正确的。
![image](https://user-images.githubusercontent.com/12459199/30157654-d53d2142-93fd-11e7-8f3a-5e7cd5cf25b3.png)

**Comment by gnattu** [comment]
看起来是这几行+1导致的穿越，+1的原因不明。

https://github.com/poooi/plugin-Akashic-records/blob/ab2cd1db71fb840bc755d4f35d17f530d8d2d81f/views/components/akashic-resource-chart.es#L21-L32

**Comment by JenningsWu** [comment]
@gnattu 可能因为太穷，日常 +1 的愿望无法满足而发泄在了这里。晚上 fix！
