### ISSUE TITLE
所有舰队都被标记为第一舰队

### ISSUE THREAD

**Issue by toooonyy** [poooi/poi#1571]
**poi 版本 / poi version:**
7.9.1

**操作系统 / OS:**
macOS 10.12.6

**插件名和版本 / Plugin name & version:**
应该和插件无关，在安全模式下依然可以重现。

**你遇到了什么样的问题 / The problem you've met:**
所有舰队都被标记为第一舰队，截图见下方。

**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:**

![screen shot 2017-09-08 at 15 30 41](https://user-images.githubusercontent.com/3480434/30201192-69fea66c-94ac-11e7-96fe-5704ff98e5e4.png)
![screen shot 2017-09-08 at 15 40 50](https://user-images.githubusercontent.com/3480434/30201193-6a0f8e00-94ac-11e7-8b6d-31c74b86323a.png)
![screen shot 2017-09-08 at 15 41 46](https://user-images.githubusercontent.com/3480434/30201194-6a2b3a4c-94ac-11e7-865a-c73cd25535a1.png)

**Comment by yukixz** [comment]
你检查一下游戏里的舰队名……

**Comment by KagamiChan** [comment]
你是不是把第一舰队的编成记录展开到别的舰队上过，展开的时候是会把舰队名也给覆盖的

**Comment by toooonyy** [comment]
囧，第一次知道还会复制名字的，原来是游戏的原因。
