### ISSUE TITLE
poi遊覽器無法開啟

### ISSUE THREAD

**Issue by onlff25v** [poooi/poi#1572]
poi 版本 / poi version: 7.9.1 X64

操作系统 / OS: win8.1 

你遇到了什么样的问题 / The problem you've met:

poi在第一次打開時是沒問題的，第二次以後的開啟就完全沒有視窗，只剩下工作管理員中的處理程序。
不管怎麼開都沒視窗，工作管理員的處理程序倒是變超多
https://imgur.com/AMpLAEy.png

**Comment by KochiyaOcean** [comment]
开始菜单搜 cmd 然后右击管理员权限打开，然后敲 `netsh winsock reset` 回车看看
记得杀光残余的 poi 进程
![image](https://user-images.githubusercontent.com/8194131/30225596-9c92d64e-9505-11e7-83c7-78552f0240d6.png)

**Comment by onlff25v** [comment]
弄完後重開機第一次可開啟，但變黑頻
關掉重開後就無法再開
現在的問題是重新開機後第一次可以開啟程式，但關掉後就無法再度開啟

**Comment by KochiyaOcean** [comment]
将 poi.exe 拖入 cmd 回车看看输出什么

**Comment by onlff25v** [comment]
Wait for app 
[INFO] Proxy listening on 49410

**Comment by KochiyaOcean** [comment]
@onlff25v 从这里看没有异样……

**Comment by onlff25v** [comment]
剛剛測試了一遍
從7.5以上的版本都會出現這個問題(開機後只能開啟一次，關掉重開後就無法開啟)
7.4版本可以關掉重開沒問題

**Comment by KochiyaOcean** [comment]
看来和 https://github.com/poooi/poi/issues/1434 是一个问题

**Comment by onlff25v** [comment]
32 位版本也一樣
第一次可以開啟程式，但關掉後就無法再度開啟

**Comment by gnattu** [comment]
@onlff25v 有沒有試過關閉後把工作管理員中的electron和poi全部殺掉再重開？

**Comment by onlff25v** [comment]
有
一樣是重開機完後第二次開啟就會失敗

**Comment by gnattu** [comment]
比較了7.4和7.5,poi的代碼上應該是沒有問題的，問題可能還是上遊，並且極有可能是Chrome，因爲7.4與7.5的Chrome版本並不一樣。
[這個Bug Ticket](https://bugs.chromium.org/p/chromium/issues/detail?id=337996)極有可能和這個問題相關聯。該Ticket中有卸載殺毒軟體或者Realplayer解決此問題的報告，但是也有完全不使用上述軟體也無法重開的報告。chrome已將此問題歸檔並且沒有進一步的解決方案，poi組暫時無法提供更進一步的幫助了。
