### ISSUE TITLE
7.9.1POI装备插件自动卸载且无法安装- -

### ISSUE THREAD

**Issue by cydad111** [poooi/poi#1573]
**poi 版本 / poi version:**
7.9.1

**操作系统 / OS:**

WIN7 SP1
**插件名和版本 / Plugin name & version:**
装备改修，版本最新- -

**你遇到了什么样的问题 / The problem you've met:**

装备插件自动卸载且无法重新安装- -

**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:**

**Comment by KochiyaOcean** [comment]
试着打开插件文件夹（插件设置 - 高级设置）全部删除后再安装

**Comment by cydad111** [comment]
还是不行- -就是装备改修安装不了

**Comment by cydad111** [comment]
就是一直显示安装中，其他安装的在慢总能完成

**Comment by KochiyaOcean** [comment]
上一层的文件夹也删掉呢（需要重启

**Comment by cydad111** [comment]
检查过了- -新版的装备改修我直接放进插件文件夹居然没用- -而且文件名都不同- -

**Comment by cydad111** [comment]
我怀疑就是因为更新插件时候出错了，顺便我试过删掉POI阅览器然后重新用7P解压，进去就显示装备改修插件损坏

**Comment by KochiyaOcean** [comment]
@cydad111 ……你从哪里下的

**Comment by cydad111** [comment]
从POI镜像网站，插件直接从这里下载。。。。文件名为plugin-item-improvement-master

**Comment by KochiyaOcean** [comment]
@cydad111 呃那个并不是完整的插件文件……

**Comment by cydad111** [comment]
。。。。。

**Comment by cydad111** [comment]
但是上面显示的是plugin-item-improvement，我下载下来是plugin-item-improvement-master

**Comment by KochiyaOcean** [comment]
@cydad111 严格的讲那个是源代码，不是插件本身。
修复的本体版本将在近日发布

**Comment by cydad111** [comment]
。。。。。。原来是出问题了啊。。。。

**Comment by cydad111** [comment]
那么等几天吧= =反正看看网页的明石工厂。。。。

**Comment by KagamiChan** [comment]
还可以看这个 - -
https://kagamichan.github.io/yuubari/

虽然目前只能够自己手动网页上搜索，不过数据是最新的

**Comment by KagamiChan** [comment]
请下载 https://ci.appveyor.com/project/KochiyaOcean/poi/build/1.0.1874/artifacts 这里的版本来试一下是否可以正常安装插件
