### ISSUE TITLE
poi 7.10.x  changelog

### ISSUE THREAD

**Issue by KagamiChan** [poooi/poi#1574]
## 功能
- 矢量图标全面更新！感谢作者 edwardaaaa 的辛勤劳动
- 更新 electron 到 1.8.0，优化内存占用
- 远征面板显示更多的舰队信息
- 支持新的夜战型飞机
- 新的任务计数支持：
  + D24 海上通商航路の警戒を厳とせよ 
  + F55 新型艤装の継続研究
  + Bq2 戦果拡張任務！「Z作戦」前段作戦
- 加入 UIT-25 / I-504 的 AACI 的判定
- 新增海域出击贴条警告：出击活动海域时，当第一舰队或联合舰队中存在未贴条的船，且舰队全未贴条或只有一种贴条时，发出警告。该警告可以在设置中关闭
- 调整水战改修对制空值的加成效果
- 加入 opencolletive 信息
- 远征面板现在会显示远征编号

## 修复
- 修复首次使用时，无法显示开发结果
- 修复插件更新热重载后插件翻译没有更新
- 修复 Ctrl + Shift + I 的快捷方式其它程序的冲突
- 修正部分 AACI 的判定
- 修复插件安装时可能导致的出错
- 修复 `允许来自局域网的连接` 设置项
- 修复不使用代理安装插件时可能出现的安装错误

## 其它
- [macOS High Sierra] 由于上游原因，隐藏窗口标题栏会导致显示异常，在上游修复之前，暂时保持显示标题栏

---------
7.10.0-beta.0 ~ 7.10.0-beta.1
- 调整水战改修对制空值的加成效果
- 修复不使用代理安装插件时可能出现的安装错误
- 暂时降级到 electron 1.7.8 以修复上游的安全漏洞

------
7.10.0-beta.1 ~
- 加入 opencolletive 信息
- 远征面板现在会显示远征编号

**Comment by gnattu** [comment]
快捷键冲突其实不是macOS独有的问题，只是修复快捷键冲突的时候顺便把快捷键改回Comman+Shift+I了而已。

**Comment by edwardaaaa** [comment]
SVG2.0重制和新增夜间战斗机系列：
夜战，夜攻和未来有可能出现的夜爆，编号分别为45，46，47。原地址已更新。
