### ISSUE TITLE
任务信息翻译错误，翻译太随意

### ISSUE THREAD

**Issue by jackjtr** [poooi/poi#1576]
**poi 版本 / poi version:**
7.9.1

**操作系统 / OS:**
Windows 8.1

**插件名和版本 / Plugin name & version:**

**你遇到了什么样的问题 / The problem you've met:**
概览界面，F51任务信息翻译有严重错误，请立刻更改，如果不能提供准确翻译请显示原文，随便翻译只会招来不满。
![20170915133443](https://user-images.githubusercontent.com/6552755/30467930-a8163780-9a1a-11e7-91c3-be36213d4bd2.jpg)

**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:**

**Comment by gnattu** [comment]
怒气冲冲的指责翻译随意前可以适当了解一下完成条件是如何生成的。如果那么多任务全部用独立的翻译文本，那么光是翻译文字量可能就比整个插件的代码还要多。因此现在的完成条件是使用机器组合出来的，对于机种转换任务，所使用的句法是这样的：
```javascript
    "modelconversion": {
      "main": "{{{secretary_equip}}}，然后{{{objects}}}{{{note}}}",
      "equip": "秘书舰{{{secretary}}}搭载未上锁的{{{fullyskilled}}}{{{maxmodified}}}{{{equipment}}}",
      "noequip": "秘书舰设为{{{secretary}}}",
      "secretarydefault": "空母",
      "scraps": "废弃{{{scraps}}}",
      "scrap": "{{{name}}}{{{amount}}}只",
      "consumptions": "消耗{{{consumptions}}}",
      "consumption": "{{{name}}}{{{amount}}}个",
      "equipmentdelim": "、",
      "scrapdelim": "，",
      "fullyskilled": "、满熟练度的",
      "maxmodified": "、改修Max的",
      "useskilledcrew": "，同时消耗一个熟练搭乘员"
    },
```
由于该任务没有指定旗舰，而机种转换任务在翻译模块运行时会给未指定旗舰的任务默认成空母，所以这个并不是“翻译随意”，而是“逻辑缺失”。

**Comment by gnattu** [comment]
https://github.com/poooi/plugin-quest/commit/72f25ee10a0f95dcb6afc197eaf317bae19e958a 已更改，下个版本将显示为“任意舰船”

**Comment by KochiyaOcean** [comment]
田意难测，出现新的任务条件并非能够预测到的情况，出现错误在所难免
非常感谢汇报错误，如果发现有错误的话我们也会及时修正
虽然如此我们也不是服务业从业人员，这样一通劈头盖脸骂下来心理上未免有点不平衡

**Comment by jackjtr** [comment]
[黑人问号]如果各位大佬觉得很委屈那我就认错好了。浪费零式舰战21型x2与瑞云x2然后又去开发也是我的错！

>>可以适当了解一下完成条件是如何生成的

在出现这个问题之前我是对poi的翻译是信任的，所以没有去原文确认。
其实我想说逻辑缺失的部分就不要翻译了吧，翻译不到位，没有人会受益，不管是开发者还是用户

>>并且目前没有对于第一个格的处理代码。所以这个并不是“翻译随意”，而是“逻辑缺失”

在普通用户看来就是翻译错误，而且插件还写的是由舰娘百科维护数据，可是我在[百科](https://zh.kcwiki.org/wiki/%E4%BB%BB%E5%8A%A1#.E5.B7.A5.E5.8E.82)里面找到的任务描述是

> 精锐“水战”队的新编成
精锐飞行队的新编成：在秘书舰第一格装备练度max且改修max的二式水战改，并废弃零式舰战21型x2与瑞云x2！　※新飞行队编成中需要熟练搭乘员。

那到底该不该舰娘百科背锅呢？

F50倒是准确翻译出了第一格和第二格
>![qq 20171020222241](https://user-images.githubusercontent.com/6552755/31825597-5cdd9d9e-b5e5-11e7-80ad-bcefc7da5a5f.jpg)


另外，谢谢你们没有着手翻译F58
>以日向改为秘书舰，将改修max的瑞云(六三四空)装备在第四个格子，废弃2个桶(运输用)，准备好2个九九式舰爆和2个瑞云!※新飞行队编成中需要熟练搭乘员。

这个任务我顺利完成了

**Comment by KochiyaOcean** [comment]
@jackjtr 因为在你这么长没回复的时间内这个 bug 早就被修了，你现在看到的当然是正确的了

**Comment by Gizeta** [comment]
@jackjtr 
嘛，数据我们舰百在维护，锅在头上是跑不掉的。
F58没有翻译，只是因为维护的人（我）犯懒了_(:з)∠)_

虽然都是舰百的数据，但是插件上的和舰百的页面不一样，因为数据不是直接抓网页，要我一个一个手输进去。

**Comment by jackjtr** [comment]
我感觉大佬们高高在上，给大佬递茶

**Comment by KochiyaOcean** [comment]
@jackjtr 如果您觉得开发任务素材所无端消耗的资源是足以让您破口大骂的深仇大恨的话请务必直接说出来

**Comment by jackjtr** [comment]
一开始没什么好生气的，但是看完回复我是觉得莫名其妙，如果大佬们都是抖M体质一定想在issue里面看到恶狠狠骂自己的话才能爽的话，好的，我很开心，就是不骂，连脏话都不想打，不过这样好像也满足了抖M

2017-10-20 22:44 GMT+08:00 東風谷オーシャン <notifications@github.com>:

**Comment by KochiyaOcean** [comment]
那么，就将此条回复理解为对于此 bug 的解决方式并无异议吧
