### ISSUE TITLE
更新到最新版的windows10之后poi就完全白屏了

### ISSUE THREAD

**Issue by naruru** [poooi/poi#1577]
**poi 版本 / poi version:**
7.9.1

**操作系统 / OS:windows10 1709 16288.1

**插件名和版本 / Plugin name & version:**

**你遇到了什么样的问题 / The problem you've met:**
更新了最新版本的windows10以后，poi完全白屏，联系了poi微博和使用了官博提供的方法也无效

**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:**

**Comment by gnattu** [comment]
使用安全模式启动是否白屏？

**Comment by naruru** [comment]
也是白屏

**Comment by gnattu** [comment]
@naruru 具体什么地方白屏，是游戏区域白屏还是整个poi什么都看不见就是个空白窗口

**Comment by naruru** [comment]
整个poi什么都看不见，一个空白的窗口

**Comment by bbbyguo** [comment]
POI:  7.9.1
OS: windows 10 170315063.608

同样问题，win10 自动更新后进入游戏游戏窗口空白，插件栏滚轮无法滚动，需要最大化再缩小才能正常滚动。

**Comment by KagamiChan** [comment]
insider 版本，以及上游 electron 的变更频繁，不好确保 insider 的兼容性。当然如果附上一些截图的话也许能对分析有帮助

如果在 cmd 里面运行 poi.exe 的话会有什么输出吗

@bbbyguo 你的问题和这个 issue 里面的不一样，建议新开 issue 提问，同时请附上截图

**Comment by naruru** [comment]
16288.1已经是正式版了……

需要提供什么截图呢？

**Comment by gnattu** [comment]
@naruru 16288是Insider Preview的版本号，并不是正式版，于9/15发布

**Comment by naruru** [comment]
poi更新到7.10以后，从白屏变成黑屏了……

**Comment by KagamiChan** [comment]
提供一下 poi 窗口的截图和开发者工具的截图吧

**Comment by naruru** [comment]
![20170930140046](https://user-images.githubusercontent.com/31871876/31042653-d626b6a8-a5e7-11e7-873c-844aa729fa3e.png)
就是一个黑乎乎的界面

**Comment by KagamiChan** [comment]
@naruru 你下载 https://npm.taobao.org/mirrors/electron/1.8.1/electron-v1.8.1-win32-x64.zip 这个然后解压运行里面的 exe 的话，出来的也是全黑的窗口吗

**Comment by naruru** [comment]
显示一个对话框【drag your app here to run it】

**Comment by KagamiChan** [comment]
@naruru 求截图

**Comment by naruru** [comment]
![20170930141455](https://user-images.githubusercontent.com/31871876/31042747-c1bf0ccc-a5e9-11e7-942b-3cdc76ca2add.png)

**Comment by KagamiChan** [comment]
@naruru 如果你从 https://ci.appveyor.com/project/KochiyaOcean/poi/build/1.0.1912/artifacts 这里下载一个版本运行一下呢

**Comment by naruru** [comment]
中间的那个版本，也是黑屏……

**Comment by gnattu** [comment]
@naruru 请问还在用Insider版本的Windows吗？这种黑屏是Chrome页面渲染bug，一般是因为和显卡驱动有兼容性问题，poi没有办法提供太多帮助。一个比较常见的workaround是关闭GPU加速。

**Comment by naruru** [comment]
@gnattu 那请问怎么关闭？而且win10的正式版总会推出，这个问题也总要修正的呀……

在用没大破预警的KCV已经好几次差点沉船了……

**Comment by KagamiChan** [comment]
关闭 gpu 加速在 poi 里面有设置

**Comment by naruru** [comment]
@KagamiChan 打开是一片黑乎乎又怎么关呢……

**Comment by KagamiChan** [comment]
按 ctrl + shift + I 调出的开发者工具的 console 是可以输入的吗，如果可以的话输入
`config.set('poi.disableHA', true)`，然后重启看一下
不能输入的话只能手动改 `%appdata%/poi/config.cson` 文件了

**Comment by KagamiChan** [comment]
还有请问你的显卡型号是什么？

**Comment by KagamiChan** [comment]
另外的一个方案是在 poi 的快捷方式里面加入一个参数 `--ignore-gpu-blacklist`，也可以在 cmd 里面切到 poi 程序所在目录运行 `poi.exe --ignore-gpu-blacklist`

**Comment by mammothrider** [comment]
我也是这个问题，查了一下发现一直停在初始index, console报了一堆bug。
`Scheduling daily refresh at 331200000 (now 1509626407626)
C:\Program Files\poi\resources\app\views\services\plugin-manager-utils.js:370 poi-plugin-kcwiki-report: No translate file found.
updateI18n @ C:\Program Files\poi\resources\app\views\services\plugin-manager-utils.js:370
poi.io/fcd/meta.json Failed to load resource: net::ERR_EMPTY_RESPONSE
C:\Program Files\poi\resources\app\views\components\settings\parts\others.js:338 Update fcd from https://poi.io/fcd/ failed in mode default.
(anonymous) @ C:\Program Files\poi\resources\app\views\components\settings\parts\others.js:338
analytics.js Failed to load resource: net::ERR_EMPTY_RESPONSE
11089376 Failed to load resource: net::ERR_EMPTY_RESPONSE
8042869 Failed to load resource: net::ERR_EMPTY_RESPONSE
3362438 Failed to load resource: net::ERR_EMPTY_RESPONSE
6753092 Failed to load resource: net::ERR_EMPTY_RESPONSE
6861365 Failed to load resource: net::ERR_EMPTY_RESPONSE
11897118 Failed to load resource: net::ERR_EMPTY_RESPONSE
6986642 Failed to load resource: net::ERR_EMPTY_RESPONSE
10855724 Failed to load resource: net::ERR_EMPTY_RESPONSE
8194131 Failed to load resource: net::ERR_EMPTY_RESPONSE
12459199 Failed to load resource: net::ERR_EMPTY_RESPONSE
3337921 Failed to load resource: net::ERR_EMPTY_RESPONSE
5024901 Failed to load resource: net::ERR_EMPTY_RESPONSE
1183568 Failed to load resource: net::ERR_EMPTY_RESPONSE
1572561 Failed to load resource: net::ERR_EMPTY_RESPONSE
11754367 Failed to load resource: net::ERR_EMPTY_RESPONSE
3395113 Failed to load resource: net::ERR_EMPTY_RESPONSE
9245514 Failed to load resource: net::ERR_EMPTY_RESPONSE
6070540 Failed to load resource: net::ERR_EMPTY_RESPONSE
12785565 Failed to load resource: net::ERR_EMPTY_RESPONSE
1596656 Failed to load resource: net::ERR_EMPTY_RESPONSE
13615512 Failed to load resource: net::ERR_EMPTY_RESPONSE
13725370 Failed to load resource: net::ERR_EMPTY_RESPONSE
10178964 Failed to load resource: net::ERR_EMPTY_RESPONSE
12995396 Failed to load resource: net::ERR_EMPTY_RESPONSE
1854100 Failed to load resource: net::ERR_EMPTY_RESPONSE
3816900 Failed to load resource: net::ERR_EMPTY_RESPONSE
6183259 Failed to load resource: net::ERR_EMPTY_RESPONSE
7111791 Failed to load resource: net::ERR_EMPTY_RESPONSE
2235314 Failed to load resource: net::ERR_EMPTY_RESPONSE
7548 Failed to load resource: net::ERR_EMPTY_RESPONSE
6459309 Failed to load resource: net::ERR_EMPTY_RESPONSE
7316929 Failed to load resource: net::ERR_EMPTY_RESPONSE
17797795 Failed to load resource: net::ERR_EMPTY_RESPONSE
5426308 Failed to load resource: net::ERR_EMPTY_RESPONSE
20371009 Failed to load resource: net::ERR_EMPTY_RESPONSE
20397245 Failed to load resource: net::ERR_EMPTY_RESPONSE
1846356 Failed to load resource: net::ERR_EMPTY_RESPONSE
5018356 Failed to load resource: net::ERR_EMPTY_RESPONSE
C:\Program Files\poi\resources\app\views\services\plugin-manager-utils.js:370 poi-plugin-kcwiki-report: No translate file found.
updateI18n @ C:\Program Files\poi\resources\app\views\services\plugin-manager-utils.js:370
10805205 Failed to load resource: net::ERR_EMPTY_RESPONSE
1755431 Failed to load resource: net::ERR_EMPTY_RESPONSE
8843214 Failed to load resource: net::ERR_EMPTY_RESPONSE
4893302 Failed to load resource: net::ERR_EMPTY_RESPONSE
1525293 Failed to load resource: net::ERR_EMPTY_RESPONSE
842383 Failed to load resource: net::ERR_EMPTY_RESPONSE
21342724 Failed to load resource: net::ERR_EMPTY_RESPONSE
250x250.png Failed to load resource: net::ERR_EMPTY_RESPONSE
74358 Failed to load resource: net::ERR_EMPTY_RESPONSE
11714395 Failed to load resource: net::ERR_EMPTY_RESPONSE
raw.githubusercontent.com/poooi/poi/master/assets/data/fcd/meta.json Failed to load resource: net::ERR_EMPTY_RESPONSE
C:\Program Files\poi\resources\app\views\components\settings\parts\others.js:338 Update fcd from https://raw.githubusercontent.com/poooi/poi/master/assets/data/fcd/ failed in mode default.
(anonymous) @ C:\Program Files\poi\resources\app\views\components\settings\parts\others.js:338
avatar.svg Failed to load resource: net::ERR_EMPTY_RESPONSE
avatar.svg Failed to load resource: net::ERR_EMPTY_RESPONSE
avatar.svg Failed to load resource: net::ERR_EMPTY_RESPONSE
600px-Kcwiki-banner.png Failed to load resource: net::ERR_EMPTY_RESPONSE
AppIcon_64.png Failed to load resource: net::ERR_EMPTY_RESPONSE
avatar.svg Failed to load resource: net::ERR_EMPTY_RESPONSE
avatar.svg Failed to load resource: net::ERR_EMPTY_RESPONSE
avatar.svg Failed to load resource: net::ERR_EMPTY_RESPONSE
UQvFKvLLWPPmxTM.png Failed to load resource: net::ERR_EMPTY_RESPONSE
avatar.svg Failed to load resource: net::ERR_EMPTY_RESPONSE
avatar.svg Failed to load resource: net::ERR_EMPTY_RESPONSE
avatar.svg Failed to load resource: net::ERR_EMPTY_RESPONSE
avatar.svg Failed to load resource: net::ERR_EMPTY_RESPONSE
backers.svg Failed to load resource: net::ERR_EMPTY_RESPONSE
6C:\Program Files\poi\resources\app\views\services\plugin-manager.js:366 SyntaxError: Unexpected end of JSON input
(anonymous) @ C:\Program Files\poi\resources\app\views\services\plugin-manager.js:366
C:\Program Files\poi\resources\app\views\components\settings\parts\others.js:338 Update fcd from http://7xj6zx.com1.z0.glb.clouddn.com/ failed in mode default.
(anonymous) @ C:\Program Files\poi\resources\app\views\components\settings\parts\others.js:338
C:\Program Files\poi\resources\app\views\services\update.js:108 Remote version: 7.10.1. Current version: v7.10.1
16C:\Program Files\poi\resources\app\views\services\plugin-manager.js:366 SyntaxError: Unexpected end of JSON input
(anonymous) @ C:\Program Files\poi\resources\app\views\services\plugin-manager.js:366
C:\Program Files\poi\resources\app\views\env-parts\devtool-message.js:17 This is poi@v7.10.1 on win32 x64 with Electron@1.7.9,
        PLUGINS: poi-plugin-prophet@6.9.11, poi-plugin-exp-calc@3.4.1, poi-plugin-expedition@3.2.2, poi-plugin-quest-info@4.2.1, poi-plugin-hensei-nikki@3.10.3, poi-plugin-senka-calc@4.3.1, poi-plugin-map-hp@4.0.0, poi-plugin-secretary@1.0.1, poi-plugin-almanac@2.0.0, poi-plugin-anchorage-repair@0.6.1, poi-plugin-akashic-records@6.1.4, poi-plugin-leveling@1.2.0, poi-plugin-battle-detail@3.7.2, poi-plugin-wheres-my-fuel-gone@0.6.2, poi-plugin-item-improvement@5.0.4, poi-plugin-ship-info@4.5.0, poi-plugin-item-info@3.1.0, poi-plugin-k2badge@0.3.2, poi-plugin-kcwiki-report@3.0.4, poi-plugin-report@3.6.0, poi-plugin-subtitle@1.2.1,
        FCD: map@2017/08/12/01, maphp@2016/08/20/01, shiptag@2017/08/12/01`

**Comment by naruru** [comment]
GeForce 540M

iPhoneから送信

H29/10/25 19:47、かがみ <notifications@github.com<mailto:notifications@github.com>>のメール:


还有请问你的显卡型号是什么？

**Comment by KagamiChan** [comment]
嗯，那就尝试一下我上边说的参数看看吧 - -

**Comment by mishimareika** [comment]
在 poi 的快捷方式里面加参数，试了一下，没有用。

**Comment by KagamiChan** [comment]
@mishimareika 请问你遇到的是不是同样的问题

**Comment by mishimareika** [comment]
@KagamiChan 是啊，一样的，win10更新后就这样了，试了试没法解决

**Comment by KagamiChan** [comment]
@mishimareika 显卡是什么型号

**Comment by mishimareika** [comment]
@KagamiChan GT520M

**Comment by KagamiChan** [comment]
@mishimareika 试试看快捷方式里面加 `--disable-gpu` 参数看看？

**Comment by KagamiChan** [comment]
@mishimareika 然后还有更新驱动到最新版本

**Comment by mishimareika** [comment]
@KagamiChan 可以打开了，谢谢解决问题

**Comment by KagamiChan** [comment]
@naruru 也请你看看用 `--disable-gpu` 参数是不是可行

**Comment by Qualiazero** [comment]
没有用，仍然白屏
