### ISSUE TITLE
新的插件更新安装错误

### ISSUE THREAD

**Issue by cydad111** [poooi/poi#1579]
**poi 版本 / poi version:**

7.9.1
**操作系统 / OS:**

WIN7 SP1 64位
**插件名和版本 / Plugin name & version:**
任务信息 4.2.1

任务信息从4.1.2更新到4.2.1

**你遇到了什么样的问题 / The problem you've met:**

插件直接更新失败- -昨天开始一直更新不了，另一个易及远征倒是更新完了- -然后今天就更新错误- -

**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:**

**Comment by cydad111** [comment]
补充下，- -我试过重启然后删除再安装，结果还是错误，而且重启后显示插件有兼容性错误

**Comment by KochiyaOcean** [comment]
@cydad111 使用 7.9.0 呢

**Comment by VConfused** [comment]
@KochiyaOcean 
我也有碰到相同問題，剛好看到有人有相同反映，也是在任務信息無法使用
我有嘗試降版本至7.9.0，問題無法解決

另外，還有裝備改修的部分，原本也是可以使用
不確定是不是有進行更新，但目前使用上顯示全黑

最後，戰果計算部分，數值好像不太正確

另外附上我的系統
Win10 x64

**Comment by KagamiChan** [comment]
@VConfused 请下载 https://ci.appveyor.com/project/KochiyaOcean/poi/build/1.0.1874/artifacts 这里的版本试一下

**Comment by VConfused** [comment]
@KagamiChan 
有進行測試了，在擴展程式顯示，任務信息進行安裝時，卡在安裝中不會結束

**Comment by KagamiChan** [comment]
@VConfused 删除 %appdata%/poi/plugins 文件夹再重新开启 poi 的话能不能安装上？

**Comment by VConfused** [comment]
@KagamiChan 
我用上面那個版本的，清除plugins後，每個擴充插件都無法安裝，都會卡在安裝過程
然後，我解除安裝，重新安裝7.9.0，並一樣清除plugins後
任務信息、裝備改修，就都回復正常了，除了戰果計算好像還是和戰積顯示不符

**Comment by KagamiChan** [comment]
@VConfused 那请麻烦测试一下这边的版本： https://ci.appveyor.com/project/KochiyaOcean/poi/build/1.0.1879/artifacts，是不是也一样可以安装，多谢

**Comment by cydad111** [comment]
啊- -任务信息好了，但是，改修插件还是不行- -

**Comment by cydad111** [comment]
试过多次删除插件，还是不行，改修插件兼容错误

**Comment by KagamiChan** [comment]
@cydad111 你是在用 7.10.0-beta.0 吗
如果删除 %appdata%/poi 下面的 plugins 文件夹，再重新安装的话可不可以

**Comment by cydad111** [comment]
我用的是解压缩版- -不是安装版，而且之前是删除过了才安装的

**Comment by KagamiChan** [comment]
@cydad111 那你删除插件文件夹再试一下安装吧

**Comment by cydad111** [comment]
还是不行- -一样的，都显示错误

**Comment by cydad111** [comment]
就是插件安装完后就是一个叉和一个删除按键

**Comment by KagamiChan** [comment]
@cydad111 有没有开发者工具的截图？卸载插件再安装插件之后，如果看到叉和删除键的话，游戏区域下边的第一个按钮点一下，切到 console 截个图

**Comment by cydad111** [comment]
问题是截什么图？那个按键我知道，但是截什么内容啊。。。。

**Comment by KagamiChan** [comment]
@cydad111 把出现的 developer tools 窗口整个截图就好了，记得是切换到 console

**Comment by cydad111** [comment]
能看到我截好的图么

**Comment by KagamiChan** [comment]
截图太小看不到前面的内容，你在这个窗口上右键点 save as，然后把整个记录保存了传上来吧

**Comment by cydad111** [comment]
LOG文件- -喘不上来，ZIP压缩后找不到文件去哪里了- -

**Comment by gnattu** [comment]
@cydad111 用记事本打开直接复制里面的内容粘贴进评论

**Comment by cydad111** [comment]
E:\BaiduYunDownload\poi-7.10.0-beta.0-win\resources\app\views\services\plugin-manager-utils.js:338 poi-plugin-item-improvement: No translate file found.
updateI18n @ E:\BaiduYunDownload\poi-7.10.0-beta.0-win\resources\app\views\services\plugin-manager-utils.js:338
(anonymous) @ E:\BaiduYunDownload\poi-7.10.0-beta.0-win\resources\app\views\services\plugin-manager-utils.js:117
step @ E:\BaiduYunDownload\poi-7.10.0-beta.0-win\resources\app\views\services\plugin-manager-utils.js:242
(anonymous) @ E:\BaiduYunDownload\poi-7.10.0-beta.0-win\resources\app\views\services\plugin-manager-utils.js:242
tryCatcher @ E:\BaiduYunDownload\poi-7.10.0-beta.0-win\resources\app\node_modules\bluebird\js\release\util.js:16
Promise._settlePromiseFromHandler @ E:\BaiduYunDownload\poi-7.10.0-beta.0-win\resources\app\node_modules\bluebird\js\release\promise.js:512
Promise._settlePromise @ E:\BaiduYunDownload\poi-7.10.0-beta.0-win\resources\app\node_modules\bluebird\js\release\promise.js:569
Promise._settlePromise0 @ E:\BaiduYunDownload\poi-7.10.0-beta.0-win\resources\app\node_modules\bluebird\js\release\promise.js:614
Promise._settlePromises @ E:\BaiduYunDownload\poi-7.10.0-beta.0-win\resources\app\node_modules\bluebird\js\release\promise.js:693
Async._drainQueue @ E:\BaiduYunDownload\poi-7.10.0-beta.0-win\resources\app\node_modules\bluebird\js\release\async.js:133
Async._drainQueues @ E:\BaiduYunDownload\poi-7.10.0-beta.0-win\resources\app\node_modules\bluebird\js\release\async.js:143
Async.drainQueues @ E:\BaiduYunDownload\poi-7.10.0-beta.0-win\resources\app\node_modules\bluebird\js\release\async.js:17
E:\BaiduYunDownload\poi-7.10.0-beta.0-win\resources\app\views\services\plugin-manager-utils.js:151 Error: Cannot find module 'C:\Users\Administrator\AppData\Roaming\poi\plugins\node_modules\poi-plugin-item-improvement'
    at Module._resolveFilename (module.js:485)
    at Function.Module._resolveFilename (E:\BaiduYunDownload\poi-7.10.0-beta.0-win\resources\electron.asar\common\reset-search-paths.js:35)
    at Function.Module._load (module.js:437)
    at Module.require (module.js:513)
    at require (internal/module.js:11)
    at Promise.resolve.then (E:\BaiduYunDownload\poi-7.10.0-beta.0-win\resources\app\views\services\plugin-manager-utils.js:144)
    at tryCatcher (E:\BaiduYunDownload\poi-7.10.0-beta.0-win\resources\app\node_modules\bluebird\js\release\util.js:16)
    at Promise._settlePromiseFromHandler (E:\BaiduYunDownload\poi-7.10.0-beta.0-win\resources\app\node_modules\bluebird\js\release\promise.js:512)
    at Promise._settlePromise (E:\BaiduYunDownload\poi-7.10.0-beta.0-win\resources\app\node_modules\bluebird\js\release\promise.js:569)
    at Promise._settlePromiseCtx (E:\BaiduYunDownload\poi-7.10.0-beta.0-win\resources\app\node_modules\bluebird\js\release\promise.js:606)
    at Async._drainQueue (E:\BaiduYunDownload\poi-7.10.0-beta.0-win\resources\app\node_modules\bluebird\js\release\async.js:138)
    at Async._drainQueues (E:\BaiduYunDownload\poi-7.10.0-beta.0-win\resources\app\node_modules\bluebird\js\release\async.js:143)
    at Async.drainQueues (E:\BaiduYunDownload\poi-7.10.0-beta.0-win\resources\app\node_modules\bluebird\js\release\async.js:17)
    at <anonymous>
(anonymous) @ E:\BaiduYunDownload\poi-7.10.0-beta.0-win\resources\app\views\services\plugin-manager-utils.js:151
step @ E:\BaiduYunDownload\poi-7.10.0-beta.0-win\resources\app\views\services\plugin-manager-utils.js:242
(anonymous) @ E:\BaiduYunDownload\poi-7.10.0-beta.0-win\resources\app\views\services\plugin-manager-utils.js:242
tryCatcher @ E:\BaiduYunDownload\poi-7.10.0-beta.0-win\resources\app\node_modules\bluebird\js\release\util.js:16
Promise._settlePromiseFromHandler @ E:\BaiduYunDownload\poi-7.10.0-beta.0-win\resources\app\node_modules\bluebird\js\release\promise.js:512
Promise._settlePromise @ E:\BaiduYunDownload\poi-7.10.0-beta.0-win\resources\app\node_modules\bluebird\js\release\promise.js:569
Promise._settlePromise0 @ E:\BaiduYunDownload\poi-7.10.0-beta.0-win\resources\app\node_modules\bluebird\js\release\promise.js:614
Promise._settlePromises @ E:\BaiduYunDownload\poi-7.10.0-beta.0-win\resources\app\node_modules\bluebird\js\release\promise.js:689
Async._drainQueue @ E:\BaiduYunDownload\poi-7.10.0-beta.0-win\resources\app\node_modules\bluebird\js\release\async.js:133
Async._drainQueues @ E:\BaiduYunDownload\poi-7.10.0-beta.0-win\resources\app\node_modules\bluebird\js\release\async.js:143
Async.drainQueues @ E:\BaiduYunDownload\poi-7.10.0-beta.0-win\resources\app\node_modules\bluebird\js\release\async.js:17

**Comment by gnattu** [comment]
打开目录`C:\Users\Administrator\AppData\Roaming\poi\plugins\node_modules\poi-plugin-item-improvement`，里面的内容截图传上来。

**Comment by cydad111** [comment]
就一个package.json，怎么上传？

**Comment by gnattu** [comment]
@cydad111 那就是下载被中断了，删除这个文件夹，扩展程序设置里面选高级设置，换一个npm服务器尝试重新安装

**Comment by cydad111** [comment]
终于好了- -直接选择US服务器+用代理下载- -

**Comment by cydad111** [comment]
貌似2个CN服务器不带代理都不行
