### ISSUE TITLE
假如dmm營運正式棄用flash並將切換至html

### ISSUE THREAD

**Issue by slui** [poooi/poi#1580]
最近有情報指出dmm營運會將艦これ從flash切換至html5.
假設切換的話poi viewer 會受到很大的影響嗎?並且須於多長時間修正?

**Comment by KochiyaOcean** [comment]
田意难测

**Comment by JenningsWu** [comment]
@slui 如果是单纯的从 flash 到 h5 的话，poi 可以无缝切换。如果通讯方式换 https 的话也很好解决。加新 API 的话那和以前那种活动维护情况一样。如果田中打算重写整个游戏例如改成街机模式（？）的话…… 嗯……
