### ISSUE TITLE
poi 7.9.1黑屏问题

### ISSUE THREAD

**Issue by bakadamare** [poooi/poi#1581]
**poi 版本 / poi version:**
v7.9.1版本的poi

**操作系统 / OS:**
操作系统是win8.1操作系统

**插件名和版本 / Plugin name & version:**

**你遇到了什么样的问题 / The problem you've met:**

安装完win版本的7.9.1的poi浏览器后打开后黑屏
用普通的chorme浏览器可以正常进入DMM玩游戏

**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:**
![qq 20170918020356](https://user-images.githubusercontent.com/32016066/30523543-a8336fce-9c15-11e7-8d0a-e11696c41748.jpg)

![qq 20170918020127](https://user-images.githubusercontent.com/32016066/30523532-7cb2f900-9c15-11e7-9714-93f1c24cde3f.jpg)
![qq 20170918020137](https://user-images.githubusercontent.com/32016066/30523533-7cc56982-9c15-11e7-86c1-d1b4654bfa36.jpg)

**Comment by KagamiChan** [comment]
这是代理的设置问题，请检查你的 poi 的代理设置是否与 chrome 里的一致

**Comment by bakadamare** [comment]
@KagamiChan 
你好 我的代理设置与chorme是一致的 如下图所示（右侧边栏）

用普通的浏览器可以正常的使用岛风go来游玩游戏  或者进入Twitter等网站 
![qq 20170918125642](https://user-images.githubusercontent.com/32016066/30529542-06051fde-9c71-11e7-9710-cdba2f206e15.jpg)

**Comment by KagamiChan** [comment]
@bakadamare 你点保存之后有没有重启 poi ？

在基本设置的地址栏里面输入 http://baidu.com 是否能够正常打开百度网站？

**Comment by bakadamare** [comment]
@KagamiChan 保存后按提示重启了POI 输入baidu。com后依然是黑屏状态

![qq 20170918150600](https://user-images.githubusercontent.com/32016066/30531792-16b6e242-9c83-11e7-9e9a-6be41dcba997.jpg)

**Comment by bakadamare** [comment]
@KagamiChan 话说每次最开始打开POI浏览器的时候 网址栏末尾都会有个叉 不知道跟黑屏有无关联
如下图所示
![qq 20170918155713](https://user-images.githubusercontent.com/32016066/30533121-48eea6f8-9c8a-11e7-8dd8-da0c5182860e.jpg)

**Comment by KagamiChan** [comment]
@bakadamare 请删除 %appdata%/poi/plugins 文件夹，之后下载 https://ci.appveyor.com/project/KochiyaOcean/poi/build/1.0.1874/artifacts 这里的版本试一下

**Comment by bakadamare** [comment]
@KagamiChan 我把%appdata%/poi/plugins 文件夹删除后下载了所给网址里的EXE安装包的poi7.9.1 安装后打开问题依旧 然后分别下载了所给网址里的其他两个poi 7.9.1的压缩包 解压后打开poi.exe发现依然是黑屏状态。

**Comment by gnattu** [comment]
@bakadamare 如果设置过代理，取消之，如果更改过host，重置之，然后用安全模式启动poi，黑屏不黑屏？

**Comment by bakadamare** [comment]
@gnattu 我把hosts恢复成初始了  然后运行了poi（safe mode） 进去后依然是黑屏状态 插件栏提示poi在安全模式下运行 插件没有自动启用

**Comment by gnattu** [comment]
保持上述状态能否正常访问百度？

**Comment by bakadamare** [comment]
@gnattu    保持安全模式也无法访问百度

**Comment by bakadamare** [comment]
@KagamiChan @gnattu  问题目前得到了解决
我来讲一下我的解决方法吧
1.把%appdata%/poi文件夹删除
2.把poi浏览器删除（就是安装路径）
3.进入控制面板-防火墙-允许通过防火墙的应用列表，将POI从列表中删除。
3.1管理员模式的命令符输入 netsh winsock reset 回车 然后重启电脑。
4.重新下载poi 7.9.1 .EXE 并正常安装poi
5.安装完成后先不要开启poi先去控制面板-防火墙-允许通过防火墙的应用列表中点允许其他应用程序，然后在重新安装的poi的安装路径下将poi.exe添加进去。
6.开启poi浏览器然后进行网络设置，设置完成后点保存并关闭poi。
7.再次开启poi后，恢复正常了，不再出现黑屏。

**Comment by gnattu** [comment]
@bakadamare 所以这个不是poi的问题，是你的代理软件把你的系统玩坏掉了

**Comment by bakadamare** [comment]
@gnattu 嗯，这两天多谢两位dalao了
all fixed
