### ISSUE TITLE
poi可否作为代理服务器并监听手机端收发的数据？

### ISSUE THREAD

**Issue by LostXine** [poooi/poi#1582]
想在使用手机时让poi的插件也可以读取到游戏数据，已经在手机上设置了pc的ip作为代理服务器，想知道poi是否有相应端口可以作为手机http的代理服务器？（试了下高级设置里面的poi端口好像不管用）以及如果手机通讯经过poi是否就可以将信息读取到插件中？

不知道讲明白没有_(:з」∠)_

先谢谢各位大佬

**Comment by KochiyaOcean** [comment]
@LostXine poi 端口设置为 1000-65535 中间的一个数就可以作为固定端口使用

**Comment by yukixz** [comment]
@LostXine 把高级设置里允许局域网访问勾上，重启

**Comment by LostXine** [comment]
@KochiyaOcean @yukixz 谢谢回复，试了下并不成功，用wireshark查看只有手机向电脑发的tcp包，电脑这边并没有回复，防火墙添加了例外，换过一次端口也不行，还有哪些操作可以做呢？

**Comment by gnattu** [comment]
我可以确认“允许局域网访问”选项没有生效。如果需求强烈可以用privoxy或者meow之类的东西来做二级代理共享至局域网。

**Comment by gnattu** [comment]
Fixed via https://github.com/poooi/poi/commit/abcc9889e0c88a034fec7425d7feed1d4166a108

**Comment by yukixz** [comment]
@gnattu 我TM智障！
