### ISSUE TITLE
[Feature Request] 能否增加一个主页按钮

### ISSUE THREAD

**Issue by wafer-li** [poooi/poi#1584]
类似于浏览器的『主页』按钮，点击之后可以返回主页。

需求痛点：
      校园网，有时候忘记登录或者被踢下线之后，访问网页会自动跳转到内网的登录页面；
      然后我就得手输 DMM 网址，然后进行数下点击才能进入游戏页面。

**Comment by KochiyaOcean** [comment]
@wafer-li 设置的地址栏那个设置主页按钮，右击就是跳转

**Comment by wafer-li** [comment]
哦，好吧。
