### ISSUE TITLE
7.9.1有时无法通过关闭按钮关闭

### ISSUE THREAD

**Issue by Kurotsuba** [poooi/poi#1586]
**poi 版本 / poi version:**
7.9.1

**操作系统 / OS:**

Win10 1073
**插件名和版本 / Plugin name & version:**

插件无关，大概

**你遇到了什么样的问题 / The problem you've met:**
[有时]无法通过右上角红叉关闭poi

**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:**
无法重现
通过任务栏右键关闭窗口可以关闭

**Comment by Kurotsuba** [comment]
长时间运行后容易出现这个问题，但是依旧没法100%复现

**Comment by KochiyaOcean** [comment]
https://ci.appveyor.com/project/KochiyaOcean/poi/build/1.0.1893/artifacts 先试试看这个吧

**Comment by Kurotsuba** [comment]
没有再出现问题，感谢
