### ISSUE TITLE
poi标题栏显示错位

### ISSUE THREAD

**Issue by RikaSugisawa** [poooi/poi#1588]
**poi 版本 / poi version:**
poi v7.10.0-beta.0

**操作系统 / OS:**

Win10 专业版 1703

**你遇到了什么样的问题 / The problem you've met:**
poi标题栏显示错位
![图片1](https://user-images.githubusercontent.com/22655313/30843265-f1a7a4be-a2c2-11e7-9758-00905ff1708f.png)

**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:**

使用该版本的poi即会产生该问题（无论是下载已编译的还是通过npm启动），7.9.0的已编译版本没有问题。

开发者工具

![default](https://user-images.githubusercontent.com/22655313/30843324-3e9e5e48-a2c3-11e7-8dc1-15eefb717121.png)

webview开发者工具

![default](https://user-images.githubusercontent.com/22655313/30843307-2beaedca-a2c3-11e7-9c3f-8d925231cbf1.png)

**Comment by KochiyaOcean** [comment]
开发者工具输入 `require('electron-react-titlebar/package.json').version` 显示什么

**Comment by RikaSugisawa** [comment]
0.4.0

**Comment by KochiyaOcean** [comment]
你是使用了压缩包版本并直接覆盖的么

**Comment by RikaSugisawa** [comment]
我是用Github同步的

**Comment by KochiyaOcean** [comment]
@RikaSugisawa 运行 npm i 以安装新的依赖

**Comment by KagamiChan** [comment]
@RikaSugisawa npm 版本是要 5 及以上的

**Comment by RikaSugisawa** [comment]
谢谢
