### ISSUE TITLE
任務信息, 泊地修理插件載入失敗

### ISSUE THREAD

**Issue by ricky0070140** [poooi/poi#1589]
**poi 版本 / poi version:**
7.9.10.b0

**操作系统 / OS:**
Win 10 ver1703

**插件名和版本 / Plugin name & version:**
任務信息4.2.1, 泊地修理0.6.0

**你遇到了什么样的问题 / The problem you'e met:**
插件載入一直失敗

**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:**

![2222](https://user-images.githubusercontent.com/32288258/30843552-70f1d656-a2bc-11e7-8930-f88922158163.png)

**Comment by KochiyaOcean** [comment]
是否尝试过卸载重新安装

**Comment by ricky0070140** [comment]
清空 %appdate/poi/plugins 後重裝可行, 但我不想清零戰鬥記錄

**Comment by KochiyaOcean** [comment]
@ricky0070140 战斗记录不在这里，删除也没问题的

**Comment by ricky0070140** [comment]
刪了現重裝問題解決了
可能是我外裝了其他插件出現相容問題?
如poi-plugin-mini-senka poi-plugin-mo2 poi-plugin-navy-album
plugins 入亦是一團亂
舊plugins 圖(備份
![image](https://user-images.githubusercontent.com/32288258/30850948-cd09fce4-a2d9-11e7-9f2b-9bdd61d3489b.png)

**Comment by KochiyaOcean** [comment]
其实是和 7.9.x 的一个 bug 有关，导致安装过程最终的解压失败
依赖的组织形式不是关键原因不过为了目录结构的维护性所以顺便改成这样了
