### ISSUE TITLE
任务信息插件错误

### ISSUE THREAD

**Issue by canonho** [poooi/poi#1590]
**poi 版本 / poi version:**
7.9.1

**操作系统 / OS:**
WIN7 64bit

**插件名和版本 / Plugin name & version:**

任務信息 4.2.1

**你遇到了什么样的问题 / The problem you've met:**

不能使用插件
 打開POI後出現 插件錯誤 相容性問題的表格

**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:**
![consule](https://user-images.githubusercontent.com/32305815/30871045-2b6dab9e-a318-11e7-806d-b586b34f55e9.jpg)

**Comment by KochiyaOcean** [comment]
@canonho 升级到 7.10.0-beta.0, 删除插件重新安装

**Comment by canonho** [comment]
@KochiyaOcean 還是顯示錯誤

**Comment by KochiyaOcean** [comment]
@canonho 插件设置 - 高级设置 - 插件文件夹 删除全部文件夹后重启 poi 并再次安装插件

**Comment by canonho** [comment]
@KochiyaOcean  謝謝 已解決
