### ISSUE TITLE
关于大破进击警告

### ISSUE THREAD

**Issue by momoblydblk** [poooi/poi#1592]
**poi 版本 / poi version:**
7（齐）.8（柏）.0（林）

**操作系统 / OS:**

Win10 1703 15063
**插件名和版本 / Plugin name & version:**

**你遇到了什么样的问题 / The problem you've met:**
poi的大破进击警告是只有通知吗？还是会想74EO那样直接遮挡进击按钮？

**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:**

**Comment by KochiyaOcean** [comment]
@momoblydblk 本体在进击后有警告 + 安装未卜先知后结算界面有警告

**Comment by momoblydblk** [comment]
可不可以做到像74eo一样有一个额外的确认？毕竟肝船机械，精污可能……

**Comment by KochiyaOcean** [comment]
@momoblydblk 设计上是不太希望有太过侵占性的操作的，而且由本体进行的阻拦可靠性不足（主要是对于战斗系统更改后对应的灵活度不足）

**Comment by momoblydblk** [comment]
那么大破后点进击的话先不发包，弹出窗口提示呢？相当于一个二次确认

**Comment by KagamiChan** [comment]
> 改代理层这种事是不可触碰的底线

以前有相关的讨论 #1095

**Comment by momoblydblk** [comment]
……好吧，不过win10下面的提示警告真的是不醒目……

**Comment by KochiyaOcean** [comment]
@momoblydblk 有语音提示 + toast 感觉足够醒目了
进击的时候也有一个提示框可以 f5 啊

**Comment by jerry78424** [comment]
主要是弹窗警告點擊任意處就會消失，很怕沒有看到

**Comment by gnattu** [comment]
@jerry78424 用户自身要为可能的沉船负责，而不是交给一个软件去负责。更何况结算页面能很清楚的看到各舰的状态，通常而言在进击之前就要确认好是否可能沉船。

**Comment by jerry78424** [comment]
@gnattu 
無意爭論沉船的責任歸屬，
我只想說人類在進行大量重複性工作時犯錯的機率要比電腦高的多。

**Comment by JenningsWu** [comment]
@jerry78424 除非干涉代理层，其他的侵占式提示都会引入更多的风险，得不偿失。另外，因为 poi 目前是不干涉网络代理的，我们能有底气说用 poi 玩舰娘就和普通 browser 一致（也方便甩锅 233）。如果干涉代理层的话就就无法确保这一点。综上考虑，我们采用的是目前的大破提示方案。

**Comment by aimao058** [comment]
大破进击通知不能关闭吗？把未卜先知也关了，还是会弹出窗口，2-2，B点打完收铝，根本没有战斗，但也弹出提示，，
