### ISSUE TITLE
poi浏览器自己清除缓存(或是根本无法保存缓存)

### ISSUE THREAD

**Issue by 81minator** [poooi/poi#1594]
**poi 版本 / poi version:**
7.9.1

**操作系统 / OS:**
Windows 10 Version 1607 / OS Build 14393.1715

**插件名和版本 / Plugin name & version:**

**你遇到了什么样的问题 / The problem you've met:**
poi会自己清除所有缓存(或是无法保留缓存，暂时没办法分辨), 每次更新缓存大小时都显示为0MB, 切换界面时经常需要重新加载

**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:**
每次开启都会发生。开始出现问题前的一段时间经常为了方便玩其他游戏而在POI和浏览器DMM之间来回切换, 不知是否有关。

**Comment by KochiyaOcean** [comment]
缓存大小设置是多少？

**Comment by 81minator** [comment]
谢谢您的回复！

秋刀鱼活动第一天时改成了360，之后改回了默认的320

**Comment by KochiyaOcean** [comment]
唔，备份一下 `%appdata%/poi/config.cson` 然后删除（相当于重置设置）是否能修复?
另外如果是同一账号的其他 DMM 游戏可以安装一心二用插件玩

**Comment by 81minator** [comment]
谢谢您，DMM恢复后我回去试试。

另外我在使用一心二用插件时常会遇到画面跟窗口严重对不上的情况，因此不太常使用。这个问题是否有解决办法呢？

**Comment by KochiyaOcean** [comment]
大概是什么样子的？如果没有保证本体和插件都是最新版本的话有可能出现兼容性问题

**Comment by 81minator** [comment]
我经常点检查插件更新，所以应当是最新版没问题。

举例来说 御城的游戏视窗会出现在窗口非常右上的地方，不调整分辨率并且最大化的话根本无法显示全部画面。而且似乎跟触摸屏不太兼容，这个可能是御城自己的问题...?

**Comment by KochiyaOcean** [comment]
有一个自动适配按钮可以对齐位置
因为我自己也是御城玩家所以应该是没什么问题的才对……

**Comment by 81minator** [comment]
是吗...我印象里好像是点了那个按钮仍然对不上...

不过我上次用一心二用是半个多月之前，现在已经好了也说不定。有什么情况我会再通知的。

谢谢您的帮助！

**Comment by 81minator** [comment]
不好意思又来打扰...
刚才您说的方法试了 仍然不行 请问有其他的解决方式吗？

另外有个情况忘了提 就是虽然在比较快的网络情况下还至少可以正常玩，但是网络慢的情况下进游戏加载要非常久，而且点了进入游戏就直接猫。这个是因为加载超时吗？

**Comment by KochiyaOcean** [comment]
缓存大小改到一个比较大的值呢？比如 1024

**Comment by DavidDiao** [comment]
啊啊这个问题我也遇到了
改大了缓存，重启poi了也没用（而且刚改完的时候flash的进程还崩溃了）
改前显示的最大缓存是320MB，但是改前好像config.cson里没有cacheSize？

**Comment by 81minator** [comment]
不好意思之前忘了回复！
其实我后来解决了，电脑提示我升级系统我拖了几天没升，问题就发生在那段时间。
升级了以后就可以用了，而且后来又出了一回这个情况，也是升级之后就好了。
我不懂系统方面的东西，希望这个回答能提供一些线索。

**Comment by DavidDiao** [comment]
电脑重启了就能正常工作了。。前面试过重启poi好像没用来着
原来一直显示缓存大小0MB也一下子有了数据，我觉得至少缓存的读取出了问题？比如获取路径有问题之类的~~不负责任的乱猜~~
如果下次又遇到了我试试不重启电脑只彻底重启Chrome试试？
