### ISSUE TITLE
Minimap breaks on aerial reconnaissance location

### ISSUE THREAD

**Issue by vuryleo** [poooi/poi#1597]
![2017-10-17 1](https://user-images.githubusercontent.com/1854100/31693421-77d63ee2-b36c-11e7-96b6-9aed66e4726f.png)

The mini map will break on all aerial reconnaissance locations (G, H of 6-3)

The error console has logs like

[-1508280601208.log](https://github.com/poooi/poi/files/1392886/-1508280601208.log)

**Comment by KagamiChan** [comment]
This has already been fixed via https://github.com/poooi/poi/commit/e22ef67f78ab530238b61f20669fa17a20b10305, please update your poi version to 7.9.1
