### ISSUE TITLE
舰娘信息的导出到CSV功能导出的文件开头为ID 导致EXCEL无法正确打开导出文件

### ISSUE THREAD

**Issue by castore** [poooi/poi#1598]
**poi 版本 / poi version:**
7.10.0 beta1

**操作系统 / OS:**

Windows7 Professional
**插件名和版本 / Plugin name & version:**
舰娘信息4.3.2

**你遇到了什么样的问题 / The problem you've met:**
如题 其实只要改成首字符为舰娘ID就好

**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:**

**Comment by KagamiChan** [comment]
无法是怎样一个无法

**Comment by castore** [comment]
CSV文件开头是ID 会被EXCEL判定是SYLK文件 ID后面的字符串被认为是SYLK代码 导致无法正确转换 打开就是乱码
把扩展的ID那一列名改成"舰娘ID"就好了 
![default](https://user-images.githubusercontent.com/7022156/31754800-b9a15bc0-b4cc-11e7-96d3-c0db5d31fb14.png)
![a](https://user-images.githubusercontent.com/7022156/31754811-c9f0fbf2-b4cc-11e7-8f8c-29814b485027.png)
