### ISSUE TITLE
请教plugin-quest对require部分进行序列化的原因

### ISSUE THREAD

**Issue by jackjtr** [poooi/poi#1600]
找了一个实例作为例子，请教一下这样设计有哪些好处，是为以后的新功能做准备？望不吝赐教，以解在下心中疑惑
![sample](https://user-images.githubusercontent.com/6552755/31848128-85b7514c-b65d-11e7-8f7e-ff49d6cae1d5.jpg)

**Comment by KagamiChan** [comment]
一方面是任务信息有显示这些信息的需要；另一方面是 poi 是支持多语言的，和按语言分别收集任务描述的翻译相比，写完一个任务描述数据就能够翻译到所有语言。

缺点就是田中的任务要求越来越刁钻，需要对数据格式进行维护，并且需要有人来按照格式填写任务

**Comment by dkwingsmt** [comment]
关于多国化，以A13作为例子，
```
  {
    "game_id": 113,
    "wiki_id": "A13",
    "category": 1,
    "type": 1,
    "name": "戦艦と重巡による主力艦隊を編成せよ！",
    "detail": "戦艦1隻以上、重巡2隻以上を主力とした水上打撃艦隊を編成せよ！",
    "reward_fuel": 0,
    "reward_ammo": 150,
    "reward_steel": 0,
    "reward_bauxite": 0,
    "reward_other": [
      {
        "name": "高速建造材",
        "amount": 2
      }
    ],
    "prerequisite": [
      107
    ],
    "requirements": {
      "category": "fleet",
      "groups": [
        {
          "ship": "戦艦",
          "amount": 1
        },
        {
          "ship": "重巡",
          "amount": 2
        }
      ],
      "disallowed": "航戦"
    }
  },
```
任务类型是`fleet`，en-US的格式指定是
```
    "fleet": {
      "main": "Have {{{groups}}} in your{{{fleet}}} fleet{{{disallowed}}}",
      "fleetid": " %s",
      "disallowed": ", %s not allowed"
    },
```

zh-CN的格式指定是
```
    "fleet": {
      "main": "编组{{{groups}}}{{{disallowed}}}{{{fleet}}}",
      "fleetid": "，限第%s舰队",
      "disallowed": "，%s不可"
    },
```

同一个任务数据文档，只要“任务类型”和该类型在不同语言中的格式指定事先设计好，那么`reqstr.es`就会把该任务自动翻译为两种语言
> Have 1 BB, 2CAs in your fleet, BBA not allowed

> 编组1战舰，2重巡，航战不可

除此之外，这种格式化的构筑方式还有助于统一任务信息格式细节，在此之前各描述有很多比如全角半角差异，用语细节差异等等。

**Comment by jackjtr** [comment]
Localization可以理解，这和直接录入完整翻译比起来，个人觉得前者维护数据结构是很艰难的，耦合性太强，而且用json存储不好维护。再者任务数量目前来说很有限，过去的任务不会有变化，而采取目前的存储和管理方式，一旦有新的任务使原有的序列化结构变化，还要人工检查对过去任务的影响吧。

比起目前这个我认为制作一个包含Localization功能的生成任务翻译的工具会更方便，i18n文件管理起来更方便也更易读，不需要考虑新增任务分类或者服务端数据结构重构。这个方法应该更适用于单次任务。

PS：原来我以为这样序列化是为了准备检测当前队伍/装备编成是否符合任务要求，除了あ号这类统计次数的功能应该是插件能做到的极限了吧

**Comment by KagamiChan** [comment]
@jackjtr 这是一个解决方案，不过恐怕不能满足之前提到的那些需求。

**Comment by jackjtr** [comment]
你说的意思我理解了，如果要新增一个语言，目前的办法是可扩展性最好的。
那么能不能为中文增加一个字段显示完整的翻译，这个要求不是必须的。但是之前就出现了翻译功能不完整就提交翻译版本的问题，实际上是因为翻译工作其实已经做好了，转化成插件格式后信息不对称导致给用户传递错误信息。这个bug其实在发布新的json之前就可以检查到，但不知道为什么翻译先于重构发生，就这样发布了错误的翻译信息。
相对而言中文用户群体最多，翻译速度也很快，但翻译功能需要重构的时候就无法体现速度了。虽然还有其他提供任务翻译或攻略的地方。
另一方面，现在任务插件做的已经不是单纯的文本翻译了，确切说可以算攻略。但是并非所有任务都需要测试才能总结成攻略，直接翻译就可以算是攻略了（例如机种转换），然而现在的插件却要等重构、测试完成后才能发布准确的翻译，我觉得是不够灵活的，添加一个纯翻译字段至少可以避免人为因素导致的bug。
以上是站在不懂日文的用户角度提的一些想法。
站在懂日文的用户角度来看，恐怕是测试环节出了一些问题。

**Comment by KagamiChan** [comment]
@jackjtr 人为出错的因素是存在的，翻译本身的出错和转换格式时出错其实没有什么差别。

现在的任务信息的主要问题不是结构没有维护，而是信息本身缺乏维护。信息无法表示的时候再升级一下数据结构就可以。

在你提出的方案当中，需要有自动收集各语言的任务描述的爬虫，最好还有自动从爬虫中读取任务奖励信息及后续任务解锁信息的功能，欢迎你的 pr
