### ISSUE TITLE
High CPU Utilization

### ISSUE THREAD

**Issue by ilikecola** [poooi/poi#1601]
**poi 版本 / poi version:**
poi v7.9.1

**操作系统 / OS:**
Windows Version 1709 (OS Build 16299.19)

**你遇到了什么样的问题 / The problem you've met:**
High CPU Utilization after enter flowerknight game homepage.

**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:**
Enter flowerknight game homepage with build-in browser plugin.

**Comment by KagamiChan** [comment]
What makes you think the CPU activity is relatively high? Could you provide more info?

**Comment by ilikecola** [comment]
poi (or electron) is incompatible with 1709 fall update, I guess.the whole poi files are the same as what is in 1703.

**Comment by KagamiChan** [comment]
It is reported that Electron 1.8.x does not behave well with 1709 update, we've switched back to 1.7.x in poi v7.10.1. Please have a try and see if it is OK
