### ISSUE TITLE
版本更新导致截图被删除？

### ISSUE THREAD

**Issue by scrsht** [poooi/poi#1604]
**poi 版本 / poi version:** 7.10.0 (7.9.0?)

**操作系统 / OS:** Win10

**插件名和版本 / Plugin name & version:**

**你遇到了什么样的问题 / The problem you've met:** 从7.9.0版本开始，版本更新时自动删除前一版本的截图，无提示（之前的版本更新没有删除截图），丢失约800张截图，基本无法恢复

**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:** 怀疑跟更新版本时的使用者选项有关（选择仅本用户使用就会删除截图？）

**Comment by KochiyaOcean** [comment]
@scrsht 不会是把截图文件夹设置在 poi 本体文件夹下了吧……

**Comment by scrsht** [comment]
一直是的。但从去年8月19日到今年8月7日的截图均没有被覆盖或删除，在7.9.0版本更新后才出现这个问题，刚才的7.10.0也是

**Comment by KagamiChan** [comment]
你现在设置的截图文件夹路径是哪个

**Comment by scrsht** [comment]
poi\screenshots

**Comment by KochiyaOcean** [comment]
@scrsht 如果使用安装包的话会把旧文件删除后再进行安装

**Comment by KochiyaOcean** [comment]
@KochiyaOcean 下一个版本将会加入禁止设置为危险位置的功能

**Comment by scrsht** [comment]
查了一下记录，至少7.2.1版更新时是使用安装包安装的，但当时的截图没有被删除

**Comment by KochiyaOcean** [comment]
@scrsht 7.2.1 的安装包与现在使用的安装包不同，并且不适用于自动更新，在 7.7.0 换装了现在的安装包系统

**Comment by scrsht** [comment]
确认是使用安装包更新导致的截图删除。多谢解惑。

**Comment by KochiyaOcean** [comment]
@scrsht 对于数据丢失我们深表遗憾。
