### ISSUE TITLE
7.10.0对触控笔支持问题

### ISSUE THREAD

**Issue by pcsjx** [poooi/poi#1605]
7.10.0才有的问题，甚至7.10.0 beta1都没有，怀疑是“Update electron to 1.8.1”这条带来的新bug

表现为手指的普通触摸操作一切正常，用触摸笔点poi的UI也正常，但是用笔点游戏画面时，无法正确触发“点击”的动作（未点下时是正常的圆点，点下后圆点变为手图标，未触发点击）。怀疑是electron更新带来的问题。

**Comment by KagamiChan** [comment]
7.10.1 已经回退到 electron 1.7.x，可以更新一下
只能等上游的修复了
