### ISSUE TITLE
关于老板键的小bug

### ISSUE THREAD

**Issue by 0CBH0** [poooi/poi#1607]
poi : 7.10.0
OS : win10 x64 1703
ーーーーーーーーーーーー
使用老板键隐藏界面后，如果通过点状态栏图标来显示界面，老板键会失效一次（显/隐状态未变更？）

**Comment by KagamiChan** [comment]
老板键是隐藏所有的窗口（包括插件），而点击状态栏图标只影响主窗口的显示。这两个的行为本身不是一致的

**Comment by 0CBH0** [comment]
那可以让点击状态栏图标显示出来的主窗口通过老板键再藏起来么，
虽然不是什么大事情，多按一次就行ww
