### ISSUE TITLE
岛风go live2d魔改无法加载

### ISSUE THREAD

**Issue by hyc1365308** [poooi/poi#1609]
**poi 版本 / poi version:**
v7.10.1

**操作系统 / OS:**

版本1703（OS内部版本15063.674）

**插件名和版本 / Plugin name & version:**

**你遇到了什么样的问题 / The problem you've met:**
岛风go的live2d魔改无法加载
使用chrome可以正常加载魔改，在poi里母港里没有船的立绘
清除浏览器缓存与重开岛风go都没办法解决。

**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:**

**Comment by KochiyaOcean** [comment]
@hyc1365308 显示设置里面更改 flash 渲染为 gpu，刷新看看

**Comment by hyc1365308** [comment]
这样可以解决，感谢了。
