### ISSUE TITLE
黑屏没反应

### ISSUE THREAD

**Issue by raisertime** [poooi/poi#1613]
**poi 版本 / poi version:7.9.1.1792

**操作系统 / OS:win10

**插件名和版本 / Plugin name & version:**

**你遇到了什么样的问题 / The problem you've met:**

**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:**

[](url)
![image](https://user-images.githubusercontent.com/33452852/32492524-b25030a2-c40e-11e7-954d-b991d37c7ed6.png)

**Comment by KagamiChan** [comment]
打开 %appdata%/poi，删除掉里面的 plugins 文件夹再重启看看
