### ISSUE TITLE
7-ship fleet issue

### ISSUE THREAD

**Issue by KagamiChan** [poooi/poi#1616]
It is likely to be outdated that each fleet could have at most 6 ships. This issue collects the usage of this assumption and tracks the working progress.

- [x] getSaku33: https://github.com/poooi/poi/blob/master/views/utils/game-utils.es#L373
- [x] escapedPos, seems totally breaking: https://github.com/poooi/poi/blob/master/views/redux/sortie/index.es#L6
But this is for combined fleet and it is originated from `api_req_combined_battle/battleresult` api
``` json
  "api_escape_flag": 1,
  "api_escape": {
    "api_escape_idx": [
      8
    ],
    "api_tow_idx": [
      9,
      10
    ]
  }
```

- [x] lib-battle

**Comment by yukixz** [comment]
lib-battle fixed. How about escapepos

**Comment by KagamiChan** [comment]
All done
