### ISSUE TITLE
多个代理设置的优先级问题

### ISSUE THREAD

**Issue by LostXine** [poooi/poi#1617]
**poi 版本 / poi version:**
7.10.1

**操作系统 / OS:**
win10 1607 14393.1770

**你遇到了什么样的问题 / The problem you've met:**
机器上运行了两个代理软件（Http:ACGPower；S5:Shadowsock）监听不同端口，在poi中分别设置了HTTP代理和Socks5代理，即使我在poi的网络代理页面选择的是HTTP代理，poi也会优先连接Socks5代理。
个人的理解是在多个代理被设置可用的情况下，poi应该只连接代理服务器详情中选择的代理方式。
谢谢各位大佬解惑_(:з」∠)_

**Comment by KochiyaOcean** [comment]
更改设置后重启结果如何

**Comment by LostXine** [comment]
已经重启过多次确认问题。

**Comment by KochiyaOcean** [comment]
网络设置里面的 PAC 地址指向的是哪个代理

**Comment by LostXine** [comment]
PAC地址我没有改过，目前是空的。

**Comment by KochiyaOcean** [comment]
感觉需要调查一下……

**Comment by LostXine** [comment]
还需要我提供哪些信息？

**Comment by KochiyaOcean** [comment]
我先测试一下吧，之后再看情况

**Comment by LostXine** [comment]
好的，谢谢。

**Comment by gnattu** [comment]
8.1.0beta4在macOS10.13.2和Win10 1703均未能复现此bug，唯一的区别是所使用的代理工具，请问现在是否还有这个问题
