### ISSUE TITLE
界面字体非常模糊

### ISSUE THREAD

**Issue by 794673085** [poooi/poi#1618]
**poi 版本 / poi version:**
7.10.1

**操作系统 / OS:**1703（15063.674）

**插件名和版本 / Plugin name & version:**

**你遇到了什么样的问题 / The problem you've met:**
抓取到flash后整个面板都变得很模糊

**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:**没抓取到flash之前界面字体很清晰，抓取后字体就变得非常模糊，鼠标在字体上移动可以暂时恢复清晰。

图传不了，具体的图在nga：http://bbs.ngacn.cc/read.php?tid=8270146的2246楼

**Comment by KochiyaOcean** [comment]
@794673085 关闭硬件加速试试看
