### ISSUE TITLE
士气速查插件导致面板无法切换

### ISSUE THREAD

**Issue by BTmanMk2** [poooi/poi#1619]
**poi 版本 / poi version:**
7.10.1

**操作系统 / OS:**
win7 x64

**插件名和版本 / Plugin name & version:**
士气速查

**你遇到了什么样的问题 / The problem you've met:**
安装士气速查后导致面板无法切换，设置中的插件列表内没有显示该插件

**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:**
安装士气速查插件

面板点击时错误
![poi-error](https://user-images.githubusercontent.com/13958726/32780532-9337545c-c97c-11e7-8381-8782e2bbf70c.PNG)

安装时错误：
![poi-plugin-error](https://user-images.githubusercontent.com/13958726/32780708-3fb5a38c-c97d-11e7-91af-077f30f9f4ce.PNG)

**Comment by KochiyaOcean** [comment]
插件设置 - 高级设置 - 打开插件文件夹
里面的东西全删掉以后重启再安装插件看看？

**Comment by BTmanMk2** [comment]
删掉mo2插件文件夹后恢复，装好就报错

**Comment by KochiyaOcean** [comment]
@BTmanMk2 全删呢

**Comment by BTmanMk2** [comment]
@KochiyaOcean 全删后同样恢复正常，今天重启电脑后问题消失，很神秘
我再试试能不能重现

**Comment by BTmanMk2** [comment]
好吧在把AppData\Roaming\poi文件夹全删了之后再打开poi装士气速查会触发问题

**Comment by Javran** [comment]
士气速查已发新版 0.4.5, 试试.
