### ISSUE TITLE
poi 8.0.x changelog

### ISSUE THREAD

**Issue by KagamiChan** [poooi/poi#1620]
## 2017 秋季活动支持
- 地图与贴条 FCD 数据更新
- 增加对潜哨戒机图标
- 支持新战斗 API，修复任务计数与航海日志记录
- 支持游击部队退避显示
- 大破进击的判断方式更改，目前联合舰队伴随舰队旗舰大破也会触发大破进击警告
- 海域贴条警告的判断方式更改，非联合舰队情况下，对于所有未出击舰队都会进行判断
- 扩展 33 索敌公式支持 7 船编制

__请注意：新机制未经完全验证，请以游戏界面显示为准__

## 功能
- 升级至 React 16
- 优化对插件出错崩溃的处理，现在插件崩溃不再会影响主程序，并且更方便用户将错误信息回报
- 增强了对于直接输入插件名安装插件的防错处理
- [Windows] 支持半透明背景，此功能对机器性能要求较高，请酌情开启
- 插件高级设置中增加`自动修复`功能，能够帮助修复部分无法安装插件或插件出错的问题
- [Linux] 支持自动更新
- 优化 CJK 与中文混合排版

## 修复
- 修复一心二用中部分游戏无法检测 flash player 版本的问题

## 8.0.0-beta.2 到 8.0.0 的更新：
- 修正对游击部队退避的支持
- 修复一心二用中部分游戏无法检测 flash player 版本的问题
- 优化 CJK 与中文混合排版

**Comment by KochiyaOcean** [comment]
`[Windows] 插件窗口支持使用使用定制标题栏代替原有系统标题栏` 这条测试后决定先暂停了

**Comment by vuryleo** [comment]
> 插件高级设置中增加自动修复功能，能够帮助修复部分无法安装插件或插件出错的问题

（感觉就是卸载重装

**Comment by KochiyaOcean** [comment]
＠vuryleo　そうだよ

**Comment by wafer-li** [comment]
试了一下，目前二队旗舰仍然具有保护。
![download](https://user-images.githubusercontent.com/12459199/33087008-b9ced51c-cf2c-11e7-96f5-b873bef23913.png)

**Comment by KagamiChan** [comment]
@wafer-li 主要是目前谁也不能保证各种情况下真的不会有问题，而一旦出事损失就比较惨重了；这大概也是大家在有事件报告的情况下，宁可持怀疑态度的原因。二队旗舰保护是否值得相信，希望等一段时间能有比较明确的共识吧
