### ISSUE TITLE
航海日志不记录出击

### ISSUE THREAD

**Issue by seagullyyx** [poooi/poi#1622]
POI版本 7.10.1
航海日志版本 6.1.4
活动维护后航海日志无法记录出击
还有每日任务BD01， BD02， BD03, BD05，BD07，BD08 任务计数器失效
演习远征工厂入渠任务正常

**Comment by KochiyaOcean** [comment]
@seagullyyx 游戏修改 API 导致的失效，插件可以安装新测试版修复

**Comment by seagullyyx** [comment]
KochiyaOcean 好的，谢谢
