### ISSUE TITLE
請問任務追蹤的進度卡到不跟進是怎麼回事

### ISSUE THREAD

**Issue by yanagi310** [poooi/poi#1624]
**poi 版本 / poi version:7.10.1

**操作系统 / OS:win10 x64

**插件名和版本 / Plugin name & version:**

**你遇到了什么样的问题 / The problem you've met:任務追蹤不會跟到任務實際進度或者是完全的不更新進度

**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:**

**Comment by KagamiChan** [comment]
因为战斗 api 更改了，所有与战斗相关的数据都无法处理
