### ISSUE TITLE
希望增加两个小功能

### ISSUE THREAD

**Issue by Miyoshichi** [poooi/poi#1625]
**战斗结束通知**
经常是看到未卜先知的战斗结果就切出去做其他事了，而不看战斗动画，这样不知道战斗具体什么时候结束，遇到比较长的战斗需要反复确认。

**远征补给确认通知**
有时候会手滑没看补给状态就点出去跑远征了，现在有直接在远征界面补给的功能，配合这个通知应该能减少手滑现象。

**Comment by KagamiChan** [comment]
第一个和 #1380  是一样的

第二个没有办法做，程序只能知道你进入了战斗界面，但是不知道什么时候点开远征项目准备远征

**Comment by Miyoshichi** [comment]
第一个在KCV的一个插件[BattleInfoPlugin](https://github.com/veigr/BattleInfoPlugin)里实现过，感觉是可以做的，您能不能方便看一下。

第二个我刚才看了一下，已经了解了，谢谢。

**Comment by KochiyaOcean** [comment]
@Miyoshichi 这个插件的实现是每秒检查一次游戏界面是否变更，说实话有点蠢……
未来或许会采用类似实现，但是现在的情况是优先级更高的事情还挺多的，短时间内大概不会处理

**Comment by Miyoshichi** [comment]
@KochiyaOcean 了解了，先谢谢了。

**Comment by EdiTurn** [comment]
关于第二点，进入远征界面时会有一次网络请求，这时候程序应该知道吧？能否在此时检查后三个舰队中空闲舰队的补给情况并发出警告？

**Comment by KagamiChan** [comment]
@EdiTurn 哦，忘了还有这个请求了，那是可以做的

**Comment by Ayaphis** [comment]
关于第一点，battle 里解析出出手的舰娘，然后在资源请求里等到对应语音请求全部完成。或者直接简单延时2min 提示， 或者静态资源请求空闲超过 设定时间（不如交给插件

**Comment by KagamiChan** [comment]
远征的通知交给远征信息相关插件处理可能会比较好
