### ISSUE TITLE
poi 8.0.0-beta.0 在使用自定义缓存时无法进入游戏

### ISSUE THREAD

**Issue by EdiTurn** [poooi/poi#1626]
**poi 版本 / poi version:**
v8.0.0-beta.0，虽然不知道为什么包被撤回了，但还是报告一下吧。

**操作系统 / OS:**
Windows 10 Build 17040

**你遇到了什么样的问题 / The problem you've met:**
1. 在使用自定义缓存的情况下，清除缓存并刷新页面，会一直停留在第一个小船漂的界面中。
已尝试清除 cookie、关闭硬件加速等均无效。回滚到 7.10.1 后能正常进入。

2. （虽然可能不是 poi 的锅，electron 1.8.2 也还是测试版，但既然遇到了就提一下）在我的渣笔记本上，使用 electron 1.8.2 跑 8.0.0，打开后持续高 CPU 占用；大约几十秒后整个窗口全黑（包括标题栏） ，有几个 poi 进程消失，之后 CPU 占用回落正常。
笔记本上使用 electron 1.7.9 正常，在配置相对较好的台式机上使用 electron 1.8.2 也正常。

**Comment by KagamiChan** [comment]
自定义缓存是否是最新的？清除缓存之后重启是不是能进入？

目前 1.8.x 存在一些 bug，所以 8.0.0 版本是基于 1.7.9 的

**Comment by EdiTurn** [comment]
问题出现的过程：
一开始，poi 7.10.1 配合[此处](https://bbs.ngacn.cc/read.php?tid=8392124&page=70#pid252241987Anchor)的整合包，使用正常。随后更新至 poi 8.0.0，未清除缓存，此时也能正常进入游戏。然后看到缓存有了[更新](https://bbs.ngacn.cc/read.php?tid=8392124&page=70&pid=252316875&to=1)，叠加此更新并在 poi 里清除缓存并刷新，就卡在小船漂的界面中了。

做过的尝试：
清除缓存，重启 poi 等，无效。
移除缓存的更新并回退到之前的整合包，无效。
删除 poi 配置文件夹，打开 poi 仅修改代理和自定义缓存设置后重启，无效。
在叠加缓存更新的情况下，回退 poi 到 7.10.1，正常进入游戏。

**Comment by KochiyaOcean** [comment]
electron 1.8.x 有一个迷之 bug 会炸 v8
https://github.com/electron/electron/issues/10455

**Comment by KagamiChan** [comment]
处理缓存的 https://github.com/poooi/poi/blob/master/lib/proxy.es
在两个版本之间没有任何更新，所以暂时不知道是什么原因。你在 cmd 里面运行 poi.exe --dev 会有什么奇怪报错输出吗

**Comment by EdiTurn** [comment]
![default](https://user-images.githubusercontent.com/5492805/33105935-b0a60742-cf6a-11e7-8427-913ccd033bbb.PNG)
出现 TypeError: _mime2.default.lookup is not a function 后就会卡住，删除对应文件，清除缓存并刷新后又会因另一个文件的相同错误信息并卡住。

**Comment by KochiyaOcean** [comment]
https://ci.appveyor.com/project/KochiyaOcean/poi/build/artifacts 应该是修复了，求测试（还在 build

**Comment by EdiTurn** [comment]
已解决
