### ISSUE TITLE
11月15日之前的战斗记录无法查看

### ISSUE THREAD

**Issue by YiliangLin** [poooi/poi#1629]
**poi 版本 / poi version:** V8.0.0-beta. 1

**操作系统 / OS:** Window 10 版本1703

**插件名和版本 / Plugin name & version:** 战斗记录 Ver. 3.7.5

**你遇到了什么样的问题 / The problem you've met:** 2017年11月15号之前所有的战斗记录中，均可以看到出击的航线，海域和胜利。但是点击查看之后，里面的战斗概览和战斗详情均无法显示。

**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:**

**Comment by KochiyaOcean** [comment]
现在的主要任务是秋活新战斗 API 的对应和验证，对于旧 API 的兼容将在之后进行

**Comment by YiliangLin** [comment]
好的，多谢！辛苦了~

**Comment by yukixz** [comment]
Fixed

**Comment by KagamiChan** [comment]
需要一个从 trash 恢复旧记录的功能
