### ISSUE TITLE
点击“今すぐ出击”按钮没有反应，进不了游戏

### ISSUE THREAD

**Issue by shigure1224** [poooi/poi#1630]
**poi 版本 / poi version :**  v7.10.1

**操作系统 / OS:**  win7 sp1 x64

**你遇到了什么样的问题 / The problem you've met:**  在游戏首页，点击“今すぐ出击”按钮没有反应，进不了游戏。重启poi，重启电脑，重装poi等方法都无效

**Comment by KochiyaOcean** [comment]
八成是插件在载入，等一段时间就行了

**Comment by KagamiChan** [comment]
在开始菜单里面找到 poi (safe mode)，用从这个快捷方式进去看看

**Comment by shigure1224** [comment]
又开了下poi想等等试试看，然后这次连页面都没跳出来了。又重启了几次，试了下safe mode 一样没用

**Comment by KagamiChan** [comment]
@shigure1224 你是通过什么手段连游戏的，岛风 go 吗

**Comment by shigure1224** [comment]
是的

**Comment by KagamiChan** [comment]
@shigure1224 试试看换一条线路。岛风 go 连接问题请咨询岛风 go 客服

**Comment by shigure1224** [comment]
试了下换了谷歌浏览器网页倒是能上去，不是岛风go的问题

**Comment by KochiyaOcean** [comment]
@shigure1224 关闭硬件加速看看

**Comment by shigure1224** [comment]
切不到设置那栏去，卡住了，点设置没反应

**Comment by KochiyaOcean** [comment]
@shigure1224 win + r 输入 %appdata%/poi/plugins

**Comment by shigure1224** [comment]
硬件加速关了，但还是没用

**Comment by KochiyaOcean** [comment]
@shigure1224 %appdata%/poi/ 这个文件夹直接改名呢

**Comment by shigure1224** [comment]
改成啥

**Comment by shigure1224** [comment]
随便改了下名字，进登录页面了

**Comment by KochiyaOcean** [comment]
把名字改回来，然后删除下图选中的文件夹看看
![image](https://user-images.githubusercontent.com/8194131/33159044-d9d68b44-d052-11e7-97f7-3e74679925b5.png)

**Comment by shigure1224** [comment]
问题解决了，多谢！
