### ISSUE TITLE
[未卜先知]空袭后进入战斗未能及时显示结果

### ISSUE THREAD

**Issue by wafer-li** [poooi/poi#1631]
**poi 版本 / poi version:** 
8320de3f1d9a29fa6a85534287fb75466f816292

**操作系统 / OS:** 
OSX 10.11.6

**插件名和版本 / Plugin name & version:**
未卜先知 7.0.0-beta13

**你遇到了什么样的问题 / The problem you've met:**
![image](https://user-images.githubusercontent.com/12459199/33165830-928a0c42-d07b-11e7-9b29-f6fa35fd8424.png)

**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:**
![image](https://user-images.githubusercontent.com/12459199/33165953-e1a8d40c-d07b-11e7-89fa-56c074872579.png)

**Comment by KagamiChan** [comment]
麻烦在战斗记录里面把这一场战斗的数据复制到文本文件里发给我，seki@kagami.me

**Comment by KagamiChan** [comment]
或者你如果用 telegram 的话也可以加中文讨论群然后发给我 - -

**Comment by wafer-li** [comment]
![image](https://user-images.githubusercontent.com/12459199/33166518-e7b11d58-d07d-11e7-902c-8ba273ea3b18.png)

战斗记录中找不到这一场战斗信息，但是在阿克夏记录中存在。
点击 i 图标显示无法找到该战斗
![image](https://user-images.githubusercontent.com/12459199/33166562-0354add6-d07e-11e7-8356-ba02e357e597.png)

**Comment by KagamiChan** [comment]
@wafer-li 你看看 ~/Library/Application support/poi/battle-detail/trash 里面有没有创建时间接近的 tar.gz？

**Comment by wafer-li** [comment]
![image](https://user-images.githubusercontent.com/12459199/33166725-948605e8-d07e-11e7-8dfd-3bdadc306f80.png)

没有在 trash 中找到，但是从时间上来看，应该是这里的最后一个 json

**Comment by KagamiChan** [comment]
![image](https://user-images.githubusercontent.com/3816900/33167816-c4750164-d079-11e7-9dc1-43feac05bc3d.png)

预期的战斗结果是不是类似这样

**Comment by wafer-li** [comment]
对的。

**Comment by KagamiChan** [comment]
@wafer-li 已经发布 beta.14 修复了这个问题，poi 本体需要到下一个版本
