### ISSUE TITLE
[Plugin Request] 是时候做一个解谜清单插件了

### ISSUE THREAD

**Issue by wafer-li** [poooi/poi#1632]
先问一下有没有这类插件？

-----
## 背景
目前活动地图流程越来越长，解谜流程越来越多，解谜条件越来越复杂
而且接下来的冬季活动作为后篇，可以预见的解谜会越来越多
所以，需要一个插件来自动记录解谜要素的达成情况。

## 目前的解谜要素
目前的解谜要索主要包括：

- 阶段
- 地图点的 S/A 胜利
- 地图点的制空权状况
- 空袭无伤
- 点亮某个地图点

## 未来可能出现的解谜要素

- 舰队的损害状况
    - 旗舰无伤
    - 全员小破及以下等

## 可能出现的坑
上述条件结合 fcd/map 和战斗包解决。

点亮地图点的判定或比较困难，自动判定时
对于战斗点，应以『进入该点的战斗』作为判定条件
对于无战斗点，则应以『前往下一个点』作为判定条件

比较复杂，所以对于条件自身而言，应允许用户自行勾选达成。

**Comment by KagamiChan** [comment]
如果你能把这次 e4 的各种解锁条件写成一个可用的 json 数据格式的话，那应该是可行的 = =

**Comment by KochiyaOcean** [comment]
@wafer-li 说实话不是很希望以官方身份做攻略类相关的插件……

**Comment by wafer-li** [comment]
@KochiyaOcean 
这个…… 达成条件说到底还是用户自己添加的
插件只是做一个条件的达成记录并尽量实现自动化而已

这个……和官方身份有什么冲突吗？

**Comment by KagamiChan** [comment]
在我看来你说的这个插件的逻辑是这样的：
1. 定义一套 DSL，把所有的解谜条件都用这套 DSL 写出来
2. 写一个 DSL parser，根据 DSL 生成对应的检测函数
3. 对每一个包依次进行上述函数的检测，并相应地记录是否完成

这和任务计数以及任务信息描述比较类似，然而基本得重新来一遍

虽然今后可以扩展成为自定义目标和自定义计数插用的插件，不过开发组目前恐怕没有余力 / 兴趣开发并维护

**Comment by yukixz** [comment]
@KagamiChan 沿用任务的dsl？

**Comment by KagamiChan** [comment]
@yukixz 任务信息的 dsl 只负责描述不负责计算
任务计数的 dsl 则只能处理部分简单类型的任务
