### ISSUE TITLE
一心二用 Flash问题

### ISSUE THREAD

**Issue by Jiongsky** [poooi/poi#1633]
**poi 版本 / poi version:**
poi v7.10.1

**操作系统 / OS:**
Windows10 1703

**插件名和版本 / Plugin name & version:**
一心二用　Ver. 2.9.0

**你遇到了什么样的问题 / The problem you've met:**
在一心二用中(poi主界面无问题)Flash无法载入，
在之前的poi版本(v7.7.0)中，一心二用内的Flash正常运行

**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:**

![image](https://user-images.githubusercontent.com/33966270/33222011-ee95e2c2-d18e-11e7-8e0a-a6568af8f769.png)

**Comment by KagamiChan** [comment]
你是使用哪个游戏验证一心二用的 flash 无法载入的？

**Comment by Jiongsky** [comment]
戦国プロヴィデンスX

**Comment by KagamiChan** [comment]
你下载一下 flash player 并安装，然后重启 poi 试一下？下载地址
https://fpdownload.adobe.com/pub/flashplayer/pdc/27.0.0.187/install_flash_player_ppapi.exe

**Comment by KagamiChan** [comment]
我想确认一下你用 chrome 能玩这游戏么。我这边在浏览器里打开是这样的

![image](https://user-images.githubusercontent.com/3816900/33250512-e802f88a-d36b-11e7-9a08-33752cf81c6b.png)

**Comment by Jiongsky** [comment]
我chrome上能玩这游戏(截图不知为何上传不了)

**Comment by KagamiChan** [comment]
@Jiongsky 在 chrome 上访问 chrome://flash/ 显示的安装的 flash 版本是多少？

**Comment by KagamiChan** [comment]
@Jiongsky 或者 chrome://plugins

**Comment by Jiongsky** [comment]
依然无法上传截图
以下是 chrome//flash/的内容
chrome://plugins好像chrome的最新版本已经删掉了


Google Chrome | 62.0.3202.94 ()
-- | --
操作系统 | Windows UNKNOWN SP0 64 bit
Flash plugin | 27.0.0.187 C:\WINDOWS\system32\Macromed\Flash\pepflashplayer64_27_0_0_187.dll
  | --- Crash data ---
Crash Reporting | Enable crash reporting to see crash IDs
For more details | https://support.google.com/chrome/?p=ui_usagestat
  | --- GPU information ---
Graphics card | NVIDIA GeForce GTX 1080
Driver display name | C:\WINDOWS\System32\DriverStore\FileRepository\nv_dispi.inf_amd64_c791f781cd94491f\nvldumdx.dll,C:\WINDOWS\System32\DriverStore\FileRepository\nv_dispi.inf_amd64_c791f781cd94491f\nvldumdx.dll,C:\WINDOWS\System32\DriverStore\FileRepository\nv_dispi.inf_amd64_c791f781cd94491f\nvldumdx.dll,C:\WINDOWS\System32\DriverStore\FileRepository\nv_dispi.inf_amd64_c791f781cd94491f\nvldumdx.dll
Driver name (strong) | oem82.inf:0f066de361856a84:Section136:23.21.13.8831:pci\ven_10de&dev_1b80
Graphics card | NVIDIA GeForce GTX 1080
Driver display name | C:\WINDOWS\System32\DriverStore\FileRepository\nv_dispi.inf_amd64_c791f781cd94491f\nvldumdx.dll,C:\WINDOWS\System32\DriverStore\FileRepository\nv_dispi.inf_amd64_c791f781cd94491f\nvldumdx.dll,C:\WINDOWS\System32\DriverStore\FileRepository\nv_dispi.inf_amd64_c791f781cd94491f\nvldumdx.dll,C:\WINDOWS\System32\DriverStore\FileRepository\nv_dispi.inf_amd64_c791f781cd94491f\nvldumdx.dll
Driver name (strong) | oem82.inf:0f066de361856a84:Section136:23.21.13.8831:pci\ven_10de&dev_1b80
  | --- GPU driver, more information ---
Vendor Id | 0x10de
Device Id | 0x1b80
Driver vendor | NVIDIA
Driver version | 23.21.13.8831
Driver date | 11-14-2017
Pixel shader version | 5.0
Vertex shader version | 5.0
GL_VENDOR | Google Inc.
GL_RENDERER | ANGLE (NVIDIA GeForce GTX 1080 Direct3D11 vs_5_0 ps_5_0)
GL_VERSION | OpenGL ES 3.0 (ANGLE 2.1.0.842c43ae67ba)
GL_EXTENSIONS | GL_ANGLE_client_arrays GL_ANGLE_depth_texture GL_ANGLE_framebuffer_blit GL_ANGLE_framebuffer_multisample GL_ANGLE_instanced_arrays GL_ANGLE_lossy_etc_decode GL_ANGLE_multiview GL_ANGLE_pack_reverse_row_order GL_ANGLE_program_cache_control GL_ANGLE_request_extension GL_ANGLE_robust_client_memory GL_ANGLE_robust_resource_initialization GL_ANGLE_texture_compression_dxt3 GL_ANGLE_texture_compression_dxt5 GL_ANGLE_texture_usage GL_ANGLE_translated_shader_source GL_CHROMIUM_bind_generates_resource GL_CHROMIUM_bind_uniform_location GL_CHROMIUM_color_buffer_float_rgb GL_CHROMIUM_color_buffer_float_rgba GL_CHROMIUM_copy_compressed_texture GL_CHROMIUM_copy_texture GL_CHROMIUM_sync_query GL_EXT_blend_minmax GL_EXT_color_buffer_float GL_EXT_color_buffer_half_float GL_EXT_debug_marker GL_EXT_discard_framebuffer GL_EXT_disjoint_timer_query GL_EXT_draw_buffers GL_EXT_frag_depth GL_EXT_map_buffer_range GL_EXT_occlusion_query_boolean GL_EXT_read_format_bgra GL_EXT_robustness GL_EXT_sRGB GL_EXT_shader_texture_lod GL_EXT_texture_compression_dxt1 GL_EXT_texture_compression_s3tc_srgb GL_EXT_texture_filter_anisotropic GL_EXT_texture_format_BGRA8888 GL_EXT_texture_norm16 GL_EXT_texture_rg GL_EXT_texture_storage GL_EXT_unpack_subimage GL_KHR_debug GL_NV_EGL_stream_consumer_external GL_NV_fence GL_NV_pack_subimage GL_NV_pixel_buffer_object GL_OES_EGL_image GL_OES_EGL_image_external GL_OES_EGL_image_external_essl3 GL_OES_compressed_ETC1_RGB8_texture GL_OES_depth32 GL_OES_element_index_uint GL_OES_get_program_binary GL_OES_mapbuffer GL_OES_packed_depth_stencil GL_OES_rgb8_rgba8 GL_OES_standard_derivatives GL_OES_surfaceless_context GL_OES_texture_float GL_OES_texture_float_linear GL_OES_texture_half_float GL_OES_texture_half_float_linear GL_OES_texture_npot GL_OES_vertex_array_object

**Comment by KagamiChan** [comment]
@Jiongsky 再请问 chrome://version 里面的 User Agent 的值是多少？

**Comment by Jiongsky** [comment]
用户代理 | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36
-- | --

**Comment by KochiyaOcean** [comment]
Fixed by https://github.com/poooi/poi/commit/5f79ed82d83a7e73ea090079bcbc849b17f1b53e

**Comment by KagamiChan** [comment]
错误原因是这个游戏用了一个代码来检测 flash player 版本，然而这个版本信息不能被 Electron 自动读取。因此增加了读取并设置 flash player 版本的代码。8.0.0 版发布之后应该就能工作了

**Comment by Jiongsky** [comment]
OK 期待新版本 感谢！
