### ISSUE TITLE
[战斗记录]夜转昼作战并未记录支援舰队战况

### ISSUE THREAD

**Issue by wafer-li** [poooi/poi#1635]
**poi 版本 / poi version:** 
3a0fe6771344a3a9e522467f98f2913e58797bfc

**操作系统 / OS:**
OSX 10.11.6

**插件名和版本 / Plugin name & version:**
战斗记录 3.7.5

**你遇到了什么样的问题 / The problem you've met:**
![download](https://user-images.githubusercontent.com/12459199/33236685-7af96c92-d29e-11e7-8844-6db76d34297a.png)

另外顺序似乎不太对，夜转昼应为夜战在前。

**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:**
Console 除了几个 Warning 以外无异常。

**Comment by wafer-li** [comment]
而且很神奇的是，这场战斗的结果是 S ，但是敌方舰队却存在未击沉的舰船。

**Comment by KagamiChan** [comment]
@wafer-li 麻烦把对应战斗的战斗记录数据发给我，seki@kagami.me

**Comment by wafer-li** [comment]
@KagamiChan 已经发送，请查收

**Comment by KagamiChan** [comment]
@wafer-li 已收到，多谢。数据是在的，只是没有显示。我们需要花一点时间来思考怎么做

**Comment by wafer-li** [comment]
@KagamiChan OK，顺便提供一下夜转昼的战斗流程
![image](https://user-images.githubusercontent.com/12459199/33238592-46089676-d2d4-11e7-9b2d-95a61c3aed17.png)

**Comment by yukixz** [comment]
fixed
