### ISSUE TITLE
[编成日记]竖直长度不够时，最后一个编成难以点击

### ISSUE THREAD

**Issue by wafer-li** [poooi/poi#1636]
**poi 版本 / poi version:**
3a0fe6771344a3a9e522467f98f2913e58797bfc

**操作系统 / OS:**
OSX  10.11.6

**插件名和版本 / Plugin name & version:**
编成日记 4.0.0-beta

**你遇到了什么样的问题 / The problem you've met:**
如图
![image](https://user-images.githubusercontent.com/12459199/33239783-c11facf6-d2ec-11e7-906d-3951ba4be72c.png)

**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:**

**Comment by wwftherocksp** [comment]
![snipaste_20171129_104526](https://user-images.githubusercontent.com/894504/33355494-a425f74c-d4f2-11e7-8a5a-14e3bfdaff38.png)

+1
我这个是无法点击的，一放上去就是修改大小的光标，上一编成日记版本至少能稍微碰到那个按钮
