### ISSUE TITLE
[海色相簿]获取不到舰娘卡面

### ISSUE THREAD

**Issue by wafer-li** [poooi/poi#1637]
**poi 版本 / poi version:**
3a0fe6771344a3a9e522467f98f2913e58797bfc

**操作系统 / OS:**
OSX 10.11.61

**插件名和版本 / Plugin name & version:**
海色相簿 0.3.1

**你遇到了什么样的问题 / The problem you've met:**
![image](https://user-images.githubusercontent.com/12459199/33241449-c312fba0-d308-11e7-87e4-38582f5c256b.png)

**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:**
![image](https://user-images.githubusercontent.com/12459199/33241453-cfab88aa-d308-11e7-87a6-20ba87738a9e.png)
![image](https://user-images.githubusercontent.com/12459199/33241455-d6177190-d308-11e7-9614-af09afb068d0.png)

**Comment by Javran** [comment]
清空缓存, 然后打开 `%APPDATA%\poi\` 删掉或者备份其中的 navy-album 目录,然后再试试?

**Comment by wafer-li** [comment]
尝试删除 `navy-album` 并重装插件，无效。

不过倒是发现 BUG 好像在快速点击的时候容易出现。

**Comment by Javran** [comment]
一直出不来还是偶然这样?
应该和快速点击没什么关系,因为下载和解析swf是异步的.

**Comment by wafer-li** [comment]
试了一下，只要一次没能加载出来，之后就再也加载不出来；

相反，只要之前能加载出来，之后虽然显示了一段时间的等待数据，但是最终都能加载出来。

**Comment by Javran** [comment]
有用高清魔改吗? 如果有的话,能否提供一个天城对应的魔改文件? (在魔改目录里搜下有没叫 `zgscfjpbxnir.swf` 这个名字的文件)

**Comment by wafer-li** [comment]
有的，用的是岛风 GO 的.hack 类型。

**Comment by Javran** [comment]
文件收到了,目前定位到node自带的zlib库的问题 (zlib-flate命令可以正常执行无报错)

![2017-12-19_052414_3840x1080_scrot](https://user-images.githubusercontent.com/1096354/34152542-f0f6e970-e47c-11e7-8331-2ace21989761.jpg)

初步测试, node 9.3.0 和 node 7.10.0 都有这问题

![2017-12-19_053248_3840x1080_scrot](https://user-images.githubusercontent.com/1096354/34152891-1a6a01e2-e47e-11e7-8d3c-d569e62713c9.jpg)

. 有空进一步跟进

**Comment by Javran** [comment]
找到问题了 https://github.com/nodejs/node/issues/17041
不过等上游感觉太慢,我这边临时修一下好了.

**Comment by Javran** [comment]
@wafer-li 海色相簿已发布 0.3.5 确认没问题的话可以关闭了.

(不过只是足以应付一部分情况的修法,将来会进一步更新)

**Comment by Javran** [comment]
跟进: 目前的修法没什么需要改进的了,错误只发生在解压空Buffer的时候,而另外两个用到unzip的地方,数据本身为空意义不大,所以也没啥好进一步修的了.
