### ISSUE TITLE
Battle Detail plugin

### ISSUE THREAD

**Issue by kossori** [poooi/poi#1639]
**poi 版本 / poi version:8.0.0-beta2**

**操作系统 / OS:Win10 Professional build 15063.674**

**插件名和版本 / Plugin name & version:Battle Detail 3.7.5, Akashic-records 6.1.4**

**你遇到了什么样的问题 / The problem you've met: The Battle Detail plugin opens a blank window. The Akashic-records plugin will load correctly the first time I open it, but after an undetermined amout of time will become blank similar to Battle Detail plugin.**

**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:**

Battle Plugin Console
![battle-detail plugin console](https://user-images.githubusercontent.com/7861328/33301331-3a285ff4-d3c3-11e7-81df-14ff49af3ae3.png)

**Comment by KagamiChan** [comment]
I've published a newer version 3.7.6, please update

The root cause of the error might be certain new type of game API, please tell me if you see anything strange in engagement phase
