### ISSUE TITLE
战果计算器的问题

### ISSUE THREAD

**Issue by seagullyyx** [poooi/poi#1641]
**poi 版本 / poi version:** V8.0.0

**操作系统 / OS:**  Windows10 1703

**插件名和版本 / Plugin name & version:**   战果计算 1.4.4

**你遇到了什么样的问题 / The problem you've met:** 战果计算器显示NaN

![e13 yxl1 j894 ub 78hx](https://user-images.githubusercontent.com/28121173/33326477-0c6ed9f2-d423-11e7-8dfc-7c46017661d8.png)

**Comment by KagamiChan** [comment]
cc @a26214311

**Comment by a26214311** [comment]
能否提供下插件记录的数据
在poi/achieve/achieve.json
用记事本打开此文件，把里面的内容复制一下发来

**Comment by seagullyyx** [comment]
@a26214311 

{"achieve":{"exphis":{}},"exphis":{"1":10307922},"lastmonth":11,"r1":0,"r501":269,"ranktime":"2017-11-30T23:02:25.475Z","rankuex":["1-5","1-6","2-5","3-5","4-5","5-5","6-5"],"r1time":"2017-11-28T14:40:59.358Z","r501time":"2017-11-30T23:02:28.921Z","r1last":0,"r501last":0,"r1lasttime":0,"r501lasttime":55,"r5":1223,"r5time":"2017-11-30T23:02:27.807Z","r5last":0,"r5lasttime":55,"r20":0,"r20time":"2017-11-28T14:40:51.102Z","r20last":0,"r20lasttime":0,"r5his":{"0":1223},"r20his":{},"r100his":{},"r501his":{"0":269},"myhis":{"0":225},"mylastno":720,"mylastranktime":59,"mymagic":90,"tmpexp":10327322,"tmpno":1,"reviseType":1,"mysenka":225,"targetsenka":"2400","ignoreex":{},"need_load":false,"fensureexp":0,"fensurets":0,"fensuresenka":0,"tensureexp":10295082,"tensurets":"2017-11-30T04:00:01.003Z","tensureuex":[],"fensureuex":["1-5","1-6","2-5","3-5","4-5","5-5","6-5"],"extraSenka":0,"zclearts":0,"checksum":570139,"senkaType":"calendar","chartType":"mon","myno":685}

**Comment by a26214311** [comment]
请问你现在是正常的么，当时出现NaN的时候是几点？
还有你所在的时区是？

**Comment by seagullyyx** [comment]
@a26214311  诶，现在这里是凌晨3点半是正常的耶，我的时区是 easterm time , 当时发这里的时候是早上10点左右

**Comment by a26214311** [comment]
感谢反馈
大概知道是什么问题了
下个版本会修复
你美帝的时区还真复杂233

**Comment by seagullyyx** [comment]
![image](https://user-images.githubusercontent.com/28121173/34464168-a3b4cf68-ee42-11e7-9bc1-cb62a7d2637e.png)

easterm time ， 上个月都很正常，不过今天又出现NaN的问题了

**Comment by KagamiChan** [comment]
@a26214311 
poi 从半年前的某个版本开始就自带了 moment-timezone，或许可以利用一下（虽然没看过代码不知道你是怎么实现的

**Comment by seagullyyx** [comment]
@a26214311 今天发现正常了

**Comment by a26214311** [comment]
应该还是时区的问题，我在看看怎么回事

**Comment by a26214311** [comment]
@KagamiChan 之前用的getTimeZoneOffset，现在改成了setUTCHours计算差值
我想之前应该是夏令时和冬令时切换的会出问题

**Comment by KagamiChan** [comment]
@a26214311 我之前本体里面倒计时也是转换 UTC 再计算，后来换成用 moment-timezone 直接获得 JP 时区的时间直接计算了

**Comment by seagullyyx** [comment]
@a26214311   新问题。。

![image](https://user-images.githubusercontent.com/28121173/35956164-f183b514-0c61-11e8-9431-37774f96b58f.png)    

![image](https://user-images.githubusercontent.com/28121173/35956237-5ff7e5ce-0c62-11e8-9be9-147fdc9177bf.png)

**Comment by a26214311** [comment]
请问你的poi版本？

**Comment by seagullyyx** [comment]
@a26214311  poi 版本：8.1.0 , 战果计算 1.7.0 . 时区是eastern time
