### ISSUE TITLE
藍屏

### ISSUE THREAD

**Issue by yk6** [poooi/poi#1642]
**poi 版本 / poi version:**
7.10.1

**操作系统 / OS:**
win10 ver1709 os build 16299.15

**插件名和版本 / Plugin name & version:**

**你遇到了什么样的问题 / The problem you've met:**
在隨機的時候  造成電腦藍屏自動關機 每次都原因好像都不太一樣 但其中一次是IRQL_NOT_LESS_OR_EQUAL_TO_ZERO  cause: tcpip.sys
然後在這次第三次藍屏之後 開啟poi都顯示 502 bad gateway

**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:**

**Comment by KagamiChan** [comment]
@yk6 蓝屏一般是系统软硬件的问题与 poi 无关，建议先检查测试一下内存与网卡，再升级一下驱动

**Comment by yk6** [comment]
@KagamiChan  好的 謝謝
