### ISSUE TITLE
游戏主界面卡住动不了

### ISSUE THREAD

**Issue by wwftherocksp** [poooi/poi#1643]
**poi 版本 / poi version:**
v8.0.0

**操作系统 / OS:**
win10 1709 16299.64

**你遇到了什么样的问题 / The problem you've met:**
游戏主界面随便切页面的时候有几率卡死不动，昨天还好好的，今天一更新8.0之后就这样了，安全模式也不行，删掉Roaming里的poi也不行，降回7.10.1也一样

**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:**
![snipaste_20171129_112725](https://user-images.githubusercontent.com/894504/33356851-bdd0af50-d4f9-11e7-94a1-4d50cb577d38.png)

https://youtu.be/vPDyxLq2-g4
录了个重现视频

**Comment by KochiyaOcean** [comment]
@wwftherocksp 既然降级回去也一样那大概不是 poi 自己的问题了……

**Comment by KochiyaOcean** [comment]
是否有进行了系统或者驱动的更新？

**Comment by wwftherocksp** [comment]
@KochiyaOcean 呃，貌似重启电脑就好了，打扰了，我这台电脑能不重启就不重启，赌5毛是win10的问题，真操蛋win10 1709是真的垃圾
