### ISSUE TITLE
poi显示502 bad gateway

### ISSUE THREAD

**Issue by solaract** [poooi/poi#1644]
**poi 版本 / poi version:**
7.10.1

**操作系统 / OS:**

win7 service pack 1
**插件名和版本 / Plugin name & version:**

**你遇到了什么样的问题 / The problem you've met:**

poi显示502 bad gateway

**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:**
昨天还可以使用，今天打开就显示502，poi可以打开国内网页，走代理显示502，chrome上一切正常

console:
![image](https://user-images.githubusercontent.com/5858546/33360475-c4e5407a-d50e-11e7-882f-0b77697ad8c4.png)
wireshark抓不到games.dmm.com:
![image](https://user-images.githubusercontent.com/5858546/33360573-394d088a-d50f-11e7-8203-c3cd322fcfa4.png)
cmd打开poi:
![image](https://user-images.githubusercontent.com/5858546/33360686-bbe70818-d50f-11e7-8bef-ab3aefe8bc52.png)

**Comment by KochiyaOcean** [comment]
DMM 的舰娘页面炸了，从 dmm.com 点进去玩

**Comment by solaract** [comment]
(╯°Д°)╯︵┴┴
