### ISSUE TITLE
Mac更新版本後無法開啟

### ISSUE THREAD

**Issue by Ppetrua** [poooi/poi#1646]
安裝完要開啟時會跳出「未預期的結束」的訊息
大約在poi的v7.8以後有這問題⋯⋯拖了很久，最近打活動不得不更新
換了最新版本以後發現問題還在，再換幾個其他的例如beta版也是一樣情況
Poi版本：如上述
MacOS版本：10.12.1

系統的問題報告很長，放連結：https://justpaste.it/1e3rm

**Comment by Ppetrua** [comment]
補充一下，Chrome版本是 62.0.3202.94 (正式版本) (64 位元)

**Comment by KagamiChan** [comment]
@Ppetrua 需要升级系统到 10.12.2 之后
