### ISSUE TITLE
[Feature request]希望增加“浏览器”的后退功能

### ISSUE THREAD

**Issue by slime7** [poooi/poi#1648]
**poi 版本 / poi version:** v8.0.0

**操作系统 / OS:** win10_x64_1079

**你遇到了什么样的问题 / The problem you've met:**

因为一些原因，我登录游戏是用自己的一个程序获取到带token的flash链接玩的，于是需要“F5”的时候，会出现一个问题：超过一定时间后再F5这个链接就失效了。这时候我需要后退到获取这个链接的页面（放在我自己的博客服务器上）重新来一次。然后我发现poi并没有后退按钮，再控制台打`history.back()`也没有任何反应。

可能这个问题只有我这种特俗需求才会出现，不过还是希望——只是增加快捷键也可以——加上“浏览器”的后退这个功能。

**Comment by KochiyaOcean** [comment]
@slime7 右击打开的控制台才是网页的

**Comment by slime7** [comment]
@KochiyaOcean 哦，确实。我还在想菜单栏怎么2个控制台呢。
不过我还是希望能加个后退按钮。

**Comment by slime7** [comment]
自己试了一下加上后退后，在主页直接后退会退回到空白页，确实不妥。
后来发现右键点主页是到主页页面，满足我的需求，关闭了。
