### ISSUE TITLE
POI显示无法加载插件

### ISSUE THREAD

**Issue by catcatcat321** [poooi/poi#1652]
**poi 版本 / poi version:**8.0.0

**操作系统 / OS:**WINDOWS7

**插件名和版本 / Plugin name & version:**

**你遇到了什么样的问题 / The problem you've met:**

启动POI浏览器后 输入账号密码登陆阶段无问题  但是切换游戏读条界面时POI浏览器内部会白屏 并显示无法加载插件   重启或者重装POI都无效

**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:**

**Comment by KochiyaOcean** [comment]
@catcatcat321 检查下载的文件是否完整

**Comment by catcatcat321** [comment]
删除重装过几次  应该不是这个问题吧  下的8.0.0版本的  系统环境也没选错

**Comment by catcatcat321** [comment]
![qq 20171209203224](https://user-images.githubusercontent.com/34386790/33795192-c8e14050-dd17-11e7-8ae7-1ec3cd842537.png)

**Comment by KochiyaOcean** [comment]
![image](https://user-images.githubusercontent.com/8194131/33795435-80da5cda-dd24-11e7-8345-19d9c7ca6d0b.png)
确认目录是否有这个文件，以及大小是否正确

**Comment by catcatcat321** [comment]
有这个文件 不过大小是30498KB   8.0.0版本的

**Comment by KochiyaOcean** [comment]
是否有另外安装 flash

**Comment by catcatcat321** [comment]
貌似没有  今早突然不行的  清理了一批电脑上几个月没用的旧插件  但是没动FLASH  发现不行后试着更新FLASH但是没成功

**Comment by KochiyaOcean** [comment]
@catcatcat321 卸载呢

**Comment by catcatcat321** [comment]
卸载重装重启电脑貌似都不行   试了下KVC和智能连装炮都能正常用  唯独POI登陆后就白屏并且显示无法加载插件

**Comment by KochiyaOcean** [comment]
@catcatcat321 说卸载 flash

**Comment by catcatcat321** [comment]
额。。。。我试试

**Comment by catcatcat321** [comment]
解决了。。。。。非常感谢。。。。。。
