### ISSUE TITLE
poi黑屏问题

### ISSUE THREAD

**Issue by dkeninen** [poooi/poi#1655]
**poi 版本 / poi version:8.0

**操作系统 / OS:win10

**插件名和版本 / Plugin name & version:**

**你遇到了什么样的问题 / The problem you've met:poi完全黑屏 什么都没有

**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:**

**Comment by KagamiChan** [comment]
有截图吗？

**Comment by dkeninen** [comment]
不会发... 就是整个窗口黑屏

**Comment by dkeninen** [comment]
http://wx2.sinaimg.cn/bmiddle/771b40fdly1flxs0sn4o2j211g0ibjrk.jpg 就像这样

**Comment by KagamiChan** [comment]
@dkeninen 是从什么时候开始发生的，之前做过什么操作吗

**Comment by dkeninen** [comment]
没有什么操作 重下好几遍了 都是黑屏

**Comment by KagamiChan** [comment]
@KagamiChan 是从什么时候开始发生的

**Comment by dkeninen** [comment]
没正常过

**Comment by KagamiChan** [comment]
@dkeninen 你下载一个 7z 版本解压运行呢

**Comment by dkeninen** [comment]
解压版 安装版都试过了

**Comment by KagamiChan** [comment]
@dkeninen 麻烦在 cmd 里面把 poi.exe 拖进去然后按回车运行，截一下图

**Comment by mosonze** [comment]
我也遇到了同样的问题，试过了从7.0开始到8.0的所有版本，poi的浏览器窗口一直是黑屏，岛风go也检测不到游戏连接。
cmd运行报告：
[WARN] Cannot get system flash plugin path
[INFO] Proxy listening on 53384

**Comment by mosonze** [comment]
附上控制台的错误报告
（看起来应该是代理问题，但是检查了poi、岛风go和chrome浏览器的代理设置都是对的，chrome本身也可以上舰，只有poi不行）

![2017-12-16_101501](https://user-images.githubusercontent.com/34589446/34066488-54edc1ea-e24a-11e7-9bd5-004f34db33e4.jpg)

**Comment by KagamiChan** [comment]
@mosonze 你这个错误是代理设置有问题，请检查一下 poi 的代理设置，或者删掉 %appdata%/poi 下的 config.cson 文件重置一下设置看看

**Comment by mosonze** [comment]
我检查了poi的代理设置，地址和端口都是对的；我删掉了config.cson后重新设置了代理后重新启动，依然黑屏，控制台报错内容相同（绝望

**Comment by KagamiChan** [comment]
@mosonze 把你的 config.cson 内容发上来看一下？

**Comment by mosonze** [comment]
poi:
  theme: "darklykai"
  homepage: "http://www.dmm.com/netgame/social/application/-/detail/=/app_id=854854/"
  first: "v8.0.0"
  window:
    x: 0
    y: 1
    width: 1366
    height: 727
    isFullScreen: false
    isMaximized: true
  panelMinSize: 1.3
packageManager:
  mirrorName: "taobao"
  proxy: false
  enableBetaPluginCheck: false
plugin:
  Akashic:
    nickNameId: "133778307"
  "poi-plugin-wheres-my-fuel-gone":
    lastShowChangelogVersion: "0.6.3"
  ShipInfo:
    bounds:
      x: 0
      y: 0
      width: 1366
      height: 728
proxy:
  use: "http"
  pacAddr: ""
  http:
    host: "127.0.0.1"
    port: 8099
    requirePassword: false
    username: ""
    password: ""
  socks5:
    host: "127.0.0.1"
    port: 1080
  retries: 0
  port: 0
  allowLAN: false

**Comment by KagamiChan** [comment]
@mosonze 你试试在 cmd 里面输入 `netsh winsock reset` 执行一下试试，还是不行的话只能岛风 go 换条线路，再问问岛风 go 的客服了

**Comment by mosonze** [comment]
可以登陆了，谢谢！
