### ISSUE TITLE
POI无法加载Flash插件

### ISSUE THREAD

**Issue by hxs001** [poooi/poi#1657]
**poi 版本 / poi version:8.0.0**

**操作系统 / OS:Windows10 1709 16299.98**

**你遇到了什么样的问题 / The problem you've met:无法加载Flash（显示为6个灰字“无法加载插件。”），已重启、重装，均无法解决**

**Comment by KochiyaOcean** [comment]
@hxs001 是否是 64 位系统使用 32 位的 poi

**Comment by hxs001** [comment]
不是，系统和poi都是64位，晚上还正常，刚才系统异常重启了一次以后就这样了

**Comment by KochiyaOcean** [comment]
@hxs001 重新安装 poi，如果有另外安装 flash，也另外安装一遍

**Comment by hxs001** [comment]
重装Flash之后解决，谢谢解惑
