### ISSUE TITLE
win10 pro 1709 poi主界面缩放问题

### ISSUE THREAD

**Issue by TinyBai** [poooi/poi#1660]
**poi 版本 / poi version:8.0.0**

**操作系统 / OS: Win10 Pro 1709**

**插件名和版本 / Plugin name & version:**

**你遇到了什么样的问题 / The problem you've met: poi主程序界面在每次最小化然后恢复之后，窗口大小会发生变化。屏幕分辨率1920*1080，系统缩放比例124%**

**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:重复最小化然后恢复窗口数次，窗口大小发生变化。取消勾选poi本身的【允许改变窗口大小】选项，不能解决问题**

**Comment by KochiyaOcean** [comment]
非整数缩放倍率，尤其是 124% 这么微妙的倍率，目前无法修复
需要等待上游做出对应

**Comment by TinyBai** [comment]
多谢回复，辛苦了！实际上windows默认缩放比例125%时会导致其他软件显示问题，同时poi界面仍旧存在这个问题。

**Comment by KochiyaOcean** [comment]
只能保证整数倍缩放的时候是没有问题的
参照 https://github.com/electron/electron/issues/10862

**Comment by TinyBai** [comment]
好的了解！issue可以关闭了
