### ISSUE TITLE
我的poi不知道為什麼按了改cookie都上不了我清除了,重裝了都上不了艦娘

### ISSUE THREAD

**Issue by kageura** [poooi/poi#1661]
**poi 版本 / poi version:**
8.0

**操作系统 / OS:**
win10(1709)

**插件名和版本 / Plugin name & version:**

**你遇到了什么样的问题 / The problem you've met:**

**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:**

我google網頁版可以用poi不行
![screenshot_54](https://user-images.githubusercontent.com/31682800/33973493-0c035bf2-e038-11e7-9d6e-ae0d2297fde6.png)
![screenshot_56](https://user-images.githubusercontent.com/31682800/33973494-0c1df1c4-e038-11e7-8311-6e4af77d8e75.png)
![screenshot_55](https://user-images.githubusercontent.com/31682800/33973495-0c346c7e-e038-11e7-9896-51478144c550.png)

**Comment by KagamiChan** [comment]
是报地域错误吗

请问你在 console 里面复制下面内容然后输入执行之后，是不是就不会报地域错误了
```js
ua = $('kan-game webview').getWebContents().session.getUserAgent()
$('kan-game webview').getWebContents().session.setUserAgent(ua, 'ja-JP')
$('kan-game webview').loadURL('http://www.dmm.com/netgame/social/application/-/detail/=/app_id=854854/')

```

**Comment by kageura** [comment]
謝謝我終於能在poi玩艦娘了
