### ISSUE TITLE
[战斗记录]黑屏

### ISSUE THREAD

**Issue by wafer-li** [poooi/poi#1662]
**poi 版本 / poi version:**
532bc775441ada165e9cc2fcb0936ddb560458df

**操作系统 / OS:**

macOS 10.11.6

**插件名和版本 / Plugin name & version:**

战斗记录 3.8.2

**你遇到了什么样的问题 / The problem you've met:**
黑屏

**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:**

![image](https://user-images.githubusercontent.com/12459199/33983037-124de662-e0f6-11e7-8cd3-c9299813fd3e.png)

**Comment by KagamiChan** [comment]
@wafer-li 在这之前应该还有别的错误吧

**Comment by wafer-li** [comment]
嗯…… 之前的错误是战斗包解析错误的。

不过看来这个 BUG 是偶发的，目前无法重现。​


2017-12-14 18:14 GMT+09:00 かがみ <notifications@github.com>:

**Comment by KagamiChan** [comment]
@wafer-li 如果是战斗包解析错误导致的，那么黑屏是正常预期的现象

**Comment by wafer-li** [comment]
OK
