### ISSUE TITLE
舰队面板横向长度不足时，血条受挤压

### ISSUE THREAD

**Issue by wafer-li** [poooi/poi#1673]
**poi 版本 / poi version:**
5d9deb792a345beb1c52426a41f884a822cda802

**操作系统 / OS:**

macOS 10.11.6

**你遇到了什么样的问题 / The problem you've met:**
![image](https://user-images.githubusercontent.com/12459199/34463396-d8e6e936-ee9d-11e7-88e4-7a31bc3788f8.png)

**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:**

**Comment by KochiyaOcean** [comment]
这种情况只能建议关闭头像叻……

**Comment by wafer-li** [comment]
@KochiyaOcean 
新版稍微拉宽一点可以看见必要信息了
![image](https://user-images.githubusercontent.com/12459199/34465417-12248fea-eeef-11e7-9d4b-5db503dda72c.png)

不过，被挤进去的经验值就看不到了……

**Comment by KochiyaOcean** [comment]
@wafer-li 毕竟图片就是要占那个宽度，没办法的事

**Comment by wafer-li** [comment]
@KochiyaOcean 
所以我的想法是，在头像做一个信息的 popup，不知意下如何

**Comment by KochiyaOcean** [comment]
@wafer-li 有点麻烦……

**Comment by KagamiChan** [comment]
已经针对宽度的问题做了一些处理

**Comment by wafer-li** [comment]
测试了一下，问题解决了。
不过有了头像之后个人觉得可以和海色相簿联动联动

**Comment by KochiyaOcean** [comment]
@wafer-li 具体的讲？

**Comment by wafer-li** [comment]
@KochiyaOcean 
意思就是点击头像之后能够跳转到海色相簿里面；
或者说类似未卜先知那样显示一个 `i` 标志之类的。
