### ISSUE TITLE
某些舰娘的头像看不完头

### ISSUE THREAD

**Issue by wafer-li** [poooi/poi#1678]
**poi 版本 / poi version:**
8eb248933209b7b55d91f69b9baedf1c4fcc2e3a

**操作系统 / OS:**

macOS 10.11.6

**你遇到了什么样的问题 / The problem you've met:**
![](https://ws2.sinaimg.cn/large/006tNc79ly1fn5kkjqtwtj309i02b0sn.jpg)

建议你们联合大波胡再确认一下，或者看看能不能把所有头像导出来给我看看也行。

**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:**

**Comment by Javran** [comment]
@wafer-li 别急,这问题正在处理中

![2018-01-04_223039_3840x1080_scrot](https://user-images.githubusercontent.com/1096354/34594425-f31fef06-f19e-11e7-9b3c-83fde1f880d7.jpg)

**Comment by KochiyaOcean** [comment]
Fixed by #7850b0d
