### ISSUE TITLE
推特登陆dmm页面无法转到

### ISSUE THREAD

**Issue by cocorei** [poooi/poi#1680]
**poi 版本 / poi version:**

**操作系统 / OS:**

**插件名和版本 / Plugin name & version:**

**你遇到了什么样的问题 / The problem you've met:**

**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:**

**Comment by cocorei** [comment]
版本号8.0
WIN10
用推特账号登陆时无法转到推特页面

**Comment by KagamiChan** [comment]
你使用的什么连接方式？岛风 go？VPN？直连？
