### ISSUE TITLE
可否於艦娘頭像處直接顯示船艦等級

### ISSUE THREAD

**Issue by jianhuatw** [poooi/poi#1683]
**poi 版本 / poi version:**
8.1.0-beta.4

**操作系统 / OS:**
win7

**插件名和版本 / Plugin name & version:**

**你遇到了什么样的问题 / The problem you've met:**
顯示艦娘頭像是一個很棒的改動，但是可否於頭像上直接顯示等級信息，加強信息直讀性，而不需將鼠標移至頭像上才跳出等級信息。

**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:**

**Comment by KochiyaOcean** [comment]
需要有设计大师帮忙整理一个不太难看的方案……

**Comment by KagamiChan** [comment]
如果你的面板足够宽的话，不需要悬停就能看到等级信息

**Comment by jianhuatw** [comment]
右邊欄位拉寬可以看到等級信息了，但相對左邊主畫面變小了，眼力不好的我..還是忍痛把頭像功能關了...

**Comment by gnattu** [comment]
<img width="227" alt="screen shot 2018-01-13 at 01 02 26" src="https://user-images.githubusercontent.com/12995396/34903356-77939bb6-f7fd-11e7-9c69-08550a7e8982.png">
尝试用遮罩糊了一个demo，说实话我觉得不是很好看
会有这个问题的基本上都是小屏幕，小屏幕的头像本身就没几个像素，右下角显示等级的话字会非常小，不是很容易看得清楚

**Comment by jianhuatw** [comment]
感謝gnattu做的這個，我個人是覺得蠻好的...簡單明瞭!

**Comment by gnattu** [comment]
<img width="218" alt="screen shot 2018-01-14 at 01 50 07" src="https://user-images.githubusercontent.com/12995396/34913830-f4c428c6-f8d4-11e7-9f98-dca0024b9b2a.png">
最终决定的显示方式稍微有所变化。因为有相当一部分舰娘的立绘头是往右边（血条方向）看的，这样的立绘上应用遮罩的话会把舰娘的一大半脸都挖掉，部分舰娘眼睛都会被影响到（比如sara），会显得比较猎奇，所以我把遮罩去掉了。同时为了保证可读性，给文字加了比较厚的深色阴影，即使是像511一样白的立绘也能看得清等级了。虽然这不是最美观的显示方法，但是至少不算很丑（自认）

**Comment by KochiyaOcean** [comment]
其实放到左下角比较好一些

**Comment by jianhuatw** [comment]
我提供一個小建議，可以把"Lv."的字體縮小，然後和等級資訊同一列(都放在底部)，應該可以稍稍減少立繪被擋住的困擾。

**Comment by KochiyaOcean** [comment]
![image](https://user-images.githubusercontent.com/8194131/34916828-7f072b62-f981-11e7-866a-66d6050e37fd.png)

**Comment by KochiyaOcean** [comment]
![image](https://user-images.githubusercontent.com/8194131/34917332-4ccea6e6-f988-11e7-81b2-ecb99658a7e1.png)
![image](https://user-images.githubusercontent.com/8194131/34917336-5da2f0b2-f988-11e7-9c98-b48e97253b81.png)
姑且先这样叻

**Comment by jianhuatw** [comment]
感謝開發人員的辛勞！再提一些小建議，等級字體在一些淡色背景視覺上略顯吃力，建議把"Lv."拿掉並加大字體(比照士氣值字體大小...)，另加厚陰影，或許會好些；當然這或許是個人視力上的問題，也可能是長時間肝船造成的視覺疲勞(常關注等級資訊)，已經做得很棒了！僅供參考...

**Comment by KagamiChan** [comment]
再放大的话就变成舰娘头像看不清了

我个人觉得等级信息在悬停里面看到就足够了，因为变化不会很快，不需要一直盯着看，至少和我们保留下来的其它血量，士气值，贴条，补给状况的信息相比，这个信息不是很重要

**Comment by Javran** [comment]
我大概也觉得悬停,或是换其他方式(试过直接占一些血条的空间吗?)好些, 现在这么做好些等级挡在嘴上...

![2018-01-21_101618_3840x1080_scrot](https://user-images.githubusercontent.com/1096354/35195610-2ffba742-fe94-11e7-822e-39acacd16430.jpg)

**Comment by gnattu** [comment]
占用血条空间的话上面的hp指示也必须右移，这样留出的高度对等级而言太大了，即使折行成两行要填满高度字号也会比较大，视觉上不是很协调。我觉得可以做个开关，不喜欢遮挡头像关掉就行。

**Comment by KochiyaOcean** [comment]
@gnattu 自 定 义 c s s

**Comment by Javran** [comment]
@KochiyaOcean 你书的队

**Comment by dislido** [comment]
或许可以试试鼠标移动到任意舰娘头像上时显示所有的等级信息，
最好还能显示一下升级剩余经验，装备等信息

**Comment by KochiyaOcean** [comment]
@dislido 这不是已经有了么……

**Comment by gnattu** [comment]
他说的是“所有”
