### ISSUE TITLE
航海日志数据丢失

### ISSUE THREAD

**Issue by daijunchen** [poooi/poi#1686]
**poi 版本 / poi version:8.0.0**

**操作系统 / OS:win10 1709**

**插件名和版本 / Plugin name & version:航海日志 v6.1.6**

**你遇到了什么样的问题 / The problem you've met:航海日志从17.6.9到18.1.4号的日志全部丢失。**

**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:没有**

**Comment by JenningsWu** [comment]
1. 是否是全部数据丢失？之前以及之后的数据是否还在？
2. 是所有种类的数据均丢失，还是只丢失了特定种类数据？（例如战斗记录丢失）
3.  18.1.4 日附近是否重装过 poi 或是通过任何方式清理过“数据垃圾”？
4. 日志插件设置的数据目录是在哪里？（查看方式：打开设置-扩展程序，在列表里找到航海日志，点击齿轮按钮）
5. 是否曾更改过数据目录？

**Comment by daijunchen** [comment]
1.全部丢失，之前的数据还在，之后的数据也还在。
2.所有种类全部丢失，包括分解建造等。
3.没有过，我电脑上没装此类软件。
4. ../user/AppData/Roaming/poi/akashic-records
5.没有这类操作。
![qq 20180118174700](https://user-images.githubusercontent.com/34501634/35091463-b512e57c-fc77-11e7-9f41-57d2231f6985.png)
就是这个样子的。。。。。中间跟断节了一样。。。。。但是战斗记录里面就有后面的记录

**Comment by JenningsWu** [comment]
@daijunchen 方便的话能否打开文件资源管理器，在地址栏输入 %APPDATA%/poi/akashic-records，然后把里面的所有内容打包发给我？我邮箱是 jenningswu@gmail.com
