### ISSUE TITLE
[海色相簿]吃内存过多将近 1.7G

### ISSUE THREAD

**Issue by wafer-li** [poooi/poi#1688]
**poi 版本 / poi version:**
8.1.0

**操作系统 / OS:**

macOS 10.13.2

**插件名和版本 / Plugin name & version:**
海色相簿 0.4.2

**你遇到了什么样的问题 / The problem you've met:**
吃内存过多

![image](https://user-images.githubusercontent.com/12459199/35043309-7b738ef0-fbcf-11e7-881a-e65e22746ece.png)

**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:**

poi:

![image](https://user-images.githubusercontent.com/12459199/35043328-87927e08-fbcf-11e7-9b97-63c8495665d4.png)

海色相簿：

![image](https://user-images.githubusercontent.com/12459199/35043348-9a48847a-fbcf-11e7-8d90-82f9bcacfced.png)

**Comment by KochiyaOcean** [comment]
一套图片缓存 4M，多几个就……

**Comment by wafer-li** [comment]
也不用把所有缓存都 load 进内存吧……

**Comment by KochiyaOcean** [comment]
@wafer-li 怀疑是 GC 没做到位

**Comment by Javran** [comment]
计划内部机制换个血,应该能比现在好很多..

**Comment by wafer-li** [comment]
@Javran 
顺便一提现在头像好像会导致帧率迅速下降，实测从 50 下降到了 22；

目前不得不把海色相簿和头像功能关掉了

**Comment by KochiyaOcean** [comment]
@wafer-li 确定是头像全部加载完成以后的结果么

**Comment by Javran** [comment]
@wafer-li 先禁用海色相簿的后台运行吧, 我最近在忙别的插件. 头像功能用的机制不一样大概继续开着没问题.

**Comment by wafer-li** [comment]
@KochiyaOcean 
是的，我尝试了复现了同样的情况：

开 10 个网页、Hexo 生成。

在关掉海色相簿和头像的时候

![image](https://user-images.githubusercontent.com/12459199/35312510-2d68cb96-00ff-11e8-8962-897a55322c61.png)


但是在开海色相簿和头像的时候就只有 20 多，明显感觉到卡。

**Comment by gnattu** [comment]
我这里无法复现啊，没有头像/立绘在加载中的话无论是webview还是本体都不会有明显的帧数负面影响。
<img width="698" alt="screen shot 2018-01-23 at 22 16 07" src="https://user-images.githubusercontent.com/12995396/35312750-0b943902-008b-11e8-89a6-af850e0393e0.png">

----
开启五个dmm games 海色相簿关闭 帧数要影响明显的多。
<img width="666" alt="screen shot 2018-01-23 at 22 18 05" src="https://user-images.githubusercontent.com/12995396/35312804-53914c68-008b-11e8-90a9-3f66b289c807.png">

**Comment by wafer-li** [comment]
🤣 看起来是 atom 引起的…… 准备考虑换 VSC 了

不好意思。。

**Comment by Javran** [comment]
0.5.1 发布, 这问题应该已经解决, 还有问题再汇报吧.
![2018-01-31_035510_3840x1080_scrot](https://user-images.githubusercontent.com/1096354/35613633-b110cd82-063a-11e8-84b5-cd6200facec9.jpg)

**Comment by wafer-li** [comment]
@Javran 
Negative.

![image](https://user-images.githubusercontent.com/12459199/35624850-8c0f32dc-06d3-11e8-8617-1047506308c3.png)

在 win 下突然就飚上 4G 了，使用的是最新的 0.5.1。

![image](https://user-images.githubusercontent.com/12459199/35625102-6cc14856-06d4-11e8-8ca2-84d3ed9a98c3.png)

别叫饶老师了，触摸设备，截图比较麻烦……

**Comment by Javran** [comment]
先reopen好了. 如果放那让插件处理完的话内存会降回去还是持续4G?

**Comment by wafer-li** [comment]
试了一下，全新安装海色相簿，未打开头像功能，吃内存 400M。

然后清除头像缓存，打开头像功能，内存开始飞升，直到头像加载完成后内存也不下降。

**Comment by KochiyaOcean** [comment]
@wafer-li 这个毫无关系啊

**Comment by wafer-li** [comment]
@KochiyaOcean 
嗯…… 现在内存倒是降下来了。

> 这个毫无关系啊

你说的是和插件没关系，是头像加载的问题吗？

@Javran 
顺便一提，我打开海色相簿，然后不停点击船的列表，成功的把 Navy Album 的内存弄上了 2G 😂

**Comment by Javran** [comment]
我也觉得头像和插件没关系.

上2G之后降回去没? 我测试的时候也xjb点了百来条,不过没上过2G

**Comment by KochiyaOcean** [comment]
@wafer-li 本体的头像使用的是另外的代码，这个插件没有使用

**Comment by wafer-li** [comment]
@Javran 
后来降回去了，插件应该是没有什么问题了，之后我再看看不用插件只进行头像加载的话会不会让内存爆掉。

**Comment by wafer-li** [comment]
也不对。

总结一下目前的测试情况：

无缓存、无头像缓存、并未安装海色相簿的情况下

1. 不开头像，不装海色相簿：正常 总共 1.6G 左右

2. 开头像，不装海色相簿：头像加载期间略微升高，总最高 4G，poi 主体 2.3G 左右，后回落到正常水平，持续时间 1-2 分钟左右。

3. 头像加载完成，装海色相簿：内存迅速升高，总最高接近 6.5G，Navy Album 5G 左右(poi 内置性能监视器数据) 而且将近 10 分钟左右内存才回落。

**Comment by KagamiChan** [comment]
@wafer-li 对 flash 中的图像解压和保存势必要带来内存的占用，只能够依赖于 node 的 gc 来回收内存。海色相簿此次内存的占用主要原因是不使用原来的缓存信息，并且把所有舰娘当作有更新的了，在更新后进行了几乎全部我方舰娘的 flash 数据的处理。你如果等全部加载完成之后重新打开，内存占用应该就能回复正常

**Comment by wafer-li** [comment]
@KagamiChan 
是的，加载完成之后内存的确回复正常了。

不过我认为这个内存吃得这么多，应该要做一下懒加载。我仅仅是将海色相簿安装好，还尚未打开它，就直接把我内存吃满了，而且这个满内存状态持续了将近 10 分钟，从用户体验来看的确说不上好。

**Comment by gnattu** [comment]
海色相簿的设定是自动开启后台加载，启用插件时窗口内容其实已经生成了，只是你看不见。`realclose: true`应该就没这个问题了，你现在也可以手动禁止它常驻后台。

**Comment by wafer-li** [comment]
@gnattu OK

**Comment by KagamiChan** [comment]
虽然解压 flash 吃内存不可避免，但是现有的立绘更新舰娘的判定方式需要修复一下，避免出现删除缓存之后就认为全部有更新而一次性处理大量数据

**Comment by Javran** [comment]
当前的立绘更新判断机制是: 对 `api_start2` 的数据取一个摘要并且在有更新的时候比较, 而如果原先的摘要不存在, 会有一个默认摘要文件,而不是判定为全部有更新 (相关代码在 https://github.com/poooi/plugin-navy-album/blob/fe7765d1d75b21a49a26ef0c5d5000ccb534939f/ui/index.es#L59-L62)

在这个机制下我不觉得会出现全部都更新的情况, 只是 `assets/default-digest.json` 这个文件要在每次维护之前手动更新而已(这是为了让在维护后安装插件的新用户看到更新的内容). 0.7.0 发布, `default-digest.json` 已更新, 可以关issue了.
