### ISSUE TITLE
被禁用的扩展程序会被自动启用

### ISSUE THREAD

**Issue by EdiTurn** [poooi/poi#1689]
**poi 版本 / poi version:**
8.1.0 正式版

**操作系统 / OS:**
Windows 10 1709

**插件名和版本 / Plugin name & version:**
此次相关：舰步如飞和海色相簿，此前士气速查也出现过此情况。

**你遇到了什么样的问题 / The problem you've met:**
被禁用的扩展程序自动变成启用状态，重启 poi 后对应扩展又会恢复禁用状态。

**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:**
根据舰步如飞和海色相簿的 github，这两个插件昨天都有版本更新，猜想是否与此有关。

**Comment by KochiyaOcean** [comment]
删除 `%appdata%/poi/config.cson` 看看

**Comment by EdiTurn** [comment]
@KochiyaOcean 谢谢你的建议，已按照你的吩咐删除了此文件。但因为没有稳定可以重现此问题的方式，所以只能观察一段时间看看了。

**Comment by KagamiChan** [comment]
有可能是自动升级所以重新开启了，我调查一下升级的逻辑看看

**Comment by EdiTurn** [comment]
@KochiyaOcean 昨天删除了此文件并重新配置了，但刚才海色相簿更新之后又自动变成启用状态了。
