### ISSUE TITLE
日语翻译的一些问题

### ISSUE THREAD

**Issue by Ryuuen** [poooi/poi#1690]
**poi 版本 / poi version:**
8.1.0

poi浏览器提供了多语言支持，在日语状态下，翻译可能存在一个问题，下面举一个例子，是浏览器说明文的：

中文原文是：poi 基于 Electron v%s 和 React.js 开发，是一个开源的跨平台舰队 Collection 浏览器。poi 的游戏行为与 Chrome 一致，原则上不提供任何影响收发包的功能。poi 仅提供基本浏览器功能，扩展功能请等待插件开发。
现有的日语翻译是：poi は Electron v%s と React.js で開発した、クロスプラットフォーム対応のオープンソースの艦コレ専用ブラウザです。poi でゲームをプレイする場合の送受信情報は Chrome でプレイしている場合と同じです、送受信内容に対する改変は、一切行っておりません。poi 本体は基本的なブラウジング機能を提供し、拡張機能はプラグインとしで提供する。

可以看出，有一些用词和语法错误，以及文风没有统一，建议做这么一个修改：
poi は Electron v%s と React.js で開発された、マルチプラットフォーム対応のオープンソース艦これ専用ブラウザです。ゲームにおける受送信仕様について、poiはChromeと異なりがなく、原則的にはパケット通信に影響を与える機能は一切提供しません。poi本体は基本的なブラウジング機能を提供し、拡張機能はプラグインで実現する仕様となります。

**Comment by Ryuuen** [comment]
想了想有点不对，我还不会用pull request这个功能，大概还是要再学习一个

**Comment by dkwingsmt** [comment]
@Ryuuen 下面是一个（可能可行的）网页版PR的方法
1. 在 https://github.com/poooi/poi 右上角点击 Fork
2. 进入 https://github.com/Ryuuen/poi
3. 找到 Branch: master 下拉菜单，在文本框里输入一个新branch名（比如 fix-jp-translation）然后回车
4. 然后修改你想修改的文件
5. 修改完之后进入 https://github.com/poooi/poi/compare ，点击 compare across forks
6. 右边fork选择你自己的 Ryuuen/poi 及正确的 branch，左边是 poooi/poi 和master，然后填写标题和简介，提交

我没有完整地试过，如果有任何问题的话可以继续回复

**Comment by KochiyaOcean** [comment]
可以直接编辑并 pr 的，会自动开 fork

**Comment by Ryuuen** [comment]
对setting目录下面的语言文件做了一定的修改，提交了pull request，不知道弄得对不对。
我给出的一些修改很可能也会有一定的瑕疵，但应该比现在好一点。
