### ISSUE TITLE
v8.1.0平板电脑触击会重复触发点击

### ISSUE THREAD

**Issue by HawkingChen** [poooi/poi#1693]
**poi 版本 / poi version:**
8.1.0

**操作系统 / OS:**
win10 v1607(平板电脑)
win10 v1709(平板电脑)

**插件名和版本 / Plugin name & version:**

**你遇到了什么样的问题 / The problem you've met:**
使用屏幕触摸操作，会同时触发两次点击。
换回8.0.0版本没有这个问题

**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:**
"编成"中切换排序方式时可以很明显观察到点击一下会同时切换两次。
“远征”点击“决定”时可以明显观察到会同时触发下个界面中的“远征开始”按钮。

**Comment by KochiyaOcean** [comment]
在我的笔记本电脑的触摸屏上没有成功复现

**Comment by jerry78424** [comment]
我先前用iphone7+以Teamviewer遠端操作電腦上的poi(舊的版本7.x)時也很容易觸發連點，新版沒試過
