### ISSUE TITLE
航海日志、耗资记录、舰娘信息完全无加载。

### ISSUE THREAD

**Issue by wzhzzmzzy** [poooi/poi#1694]
**poi 版本 / poi version:** 8.1,0

**操作系统 / OS:** Windows 10 1709

**插件名和版本 / Plugin name & version:** 航海日志、耗资记录、舰娘信息，均为最新版本。

**你遇到了什么样的问题 / The problem you've met:** 航海日志、耗资记录、舰娘信息完全无加载。

**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:**

Chromium Console报错信息为 `Uncaught Error: Minified React`，猜测是React中使用require的问题？（瞎猜的）。截图在下方。

[![bPTyX.png](https://s1.ax2x.com/2018/01/20/bPTyX.png)](https://simimg.com/i/bPTyX)
[![bPXll.png](https://s1.ax2x.com/2018/01/20/bPXll.png)](https://simimg.com/i/bPXll)
[![bPzFJ.png](https://s1.ax2x.com/2018/01/20/bPzFJ.png)](https://simimg.com/i/bPzFJ)

**Comment by KagamiChan** [comment]
@wzhzzmzzy 请在扩展程序-高级设置中点一下自动修复

**Comment by KagamiChan** [comment]
看起来不知道为什么从你的用户目录下的 node_modules 里面载入了 react，建议把那个 node_modules 文件夹删掉

**Comment by KochiyaOcean** [comment]
@KagamiChan 确认一下 preload 有没有被 override

**Comment by KagamiChan** [comment]
从 #1729 的情况来看，preload 本身还是无法完全防止这样的问题，删除不知道为什么加入的 node_modules 可能是更合理的方案
