### ISSUE TITLE
耗資紀錄無法翻頁、書籤版面異常

### ISSUE THREAD

**Issue by jerry78424** [poooi/poi#1695]
**poi 版本 / poi version:**

8.1.0

**操作系统 / OS:**

win7-64bit

**插件名和版本 / Plugin name & version:**

耗資紀錄0.6.3

**你遇到了什么样的问题 / The problem you've met:**

![2018-01-21 - 00 46 51 myimgur v3 90 - myimgur eden fm x64](https://user-images.githubusercontent.com/3656749/35185815-eaa266e4-fe44-11e7-9dfe-d5839d85df6e.png)
無法翻頁

![2018-01-21 - 00 50 38](https://user-images.githubusercontent.com/3656749/35185833-24239bd6-fe45-11e7-9d3b-0bc7d751165e.png)
書籤版面異常

**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:**

![2018-01-21 - 00 53 44](https://user-images.githubusercontent.com/3656749/35185864-9482ea1c-fe45-11e7-8665-c481442ef954.png)

**Comment by KochiyaOcean** [comment]
@jerry78424 等新版插件
