### ISSUE TITLE
程序崩掉之后就会丢数据

### ISSUE THREAD

**Issue by ccen3020** [poooi/poi#1697]
**poi 版本 / poi version:**
8.1.0

**操作系统 / OS:**
Microsoft Windows [版本 10.0.16299.98]

**你遇到了什么样的问题 / The problem you've met:**
poi因为异常原因关闭之后，本次运行的所有数据就会全部丢失。

poi吃内存太多，有时候一边玩一遍看视频什么的内存不足，主程序就会崩掉
因为是长时间挂机，poi基本不关，所以丢一次可能一两天的记录就全都没了

还有有时候崩掉之后后台的poi并没有完全关掉，这时候再新开程序的话，记录文件似乎会无法写入，也会丢失记录数据。

**Comment by KagamiChan** [comment]
具体来说是什么数据？插件的数据都是插件单独处理的
崩溃之后没有办法保存数据很正常，毕竟已经没法运行了，至于内存占用，当前的架构下我们没有什么办法

**Comment by ccen3020** [comment]
各种战斗记录，任务记录，开发建造记录之类的
能否做成定时写入之类的，而不是等关闭的时候才一次性写入

**Comment by KagamiChan** [comment]
现在基本是定时或者有更新的时候写入的
但是程序崩溃的时候肯定没法定时了

**Comment by gnattu** [comment]
上述插件需要常驻后台才能记录。大部分记录应该是有数据变化的时候实时写入的才对，即使是定时写入也不可能几天记录全丢。
我觉得一个可能性是如果内存不够的话，在后台的时候就被系统杀掉了，导致根本没有记录。
等到主程序崩溃的时候应该已经是后台不够杀开始杀前台了。
请问电脑内存一共多少，如果特别小的话是有这个可能性的

**Comment by ccen3020** [comment]
原来是要常驻啊…
我嫌占内存把后台关了xd

内存是8G，poi大概吃1-2G

**Comment by gnattu** [comment]
关了上述插件的后台，你需要保持插件窗口开启才能记录数据。8G内存足够poi的使用了，只开需要后台记录的插件大概只会多1G左右的占用。
