### ISSUE TITLE
自动更新总是失败

### ISSUE THREAD

**Issue by Pyywu** [poooi/poi#1700]
**poi 版本 / poi version:**
8.0以来至今

**操作系统 / OS:**

1709 win10
**插件名和版本 / Plugin name & version:**

**你遇到了什么样的问题 / The problem you've met:**
poi的自动更新总是把自己的本体删的一干二净，全盘已经不存在poi.exe。 并且没有后续动作。我每次都要重新安装。

**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:**

**Comment by KochiyaOcean** [comment]
@Pyywu 自动更新后关闭程序应该会自动安装

**Comment by Pyywu** [comment]
没有进行有关poi的操作。每次更新后关闭poi之后只能观测到把桌面图标删除，然后开始菜单的快捷方式都还没删除，点开会提示指向的文件已经不存在。之后找到poi安装目录就看见是空的。

**Comment by gnattu** [comment]
请问观察到图标被删除后等待了大概多久？

**Comment by Pyywu** [comment]
之前有打完一局dota（40分钟）在回来看的记录。 现在重现了一下，安装了8.0版本再自动更新，至少5分钟内已经没有任何反应了。也没找到任何有关poi的进程在运行。 查看安装目录是空的。

**Comment by KochiyaOcean** [comment]
@Pyywu 是否有安装第三方杀毒软件？如果有，试着禁用看看？

**Comment by Pyywu** [comment]
没有，只有windows defender
