### ISSUE TITLE
dmm登陆界面输用户名和密码的对话框出不来

### ISSUE THREAD

**Issue by pandaduo** [poooi/poi#1703]
**poi 版本 / poi version:8.1.0**

**操作系统 / OS:win10 1607**

**插件名和版本 / Plugin name & version:**

**你遇到了什么样的问题 / The problem you've met:打开poi后dmm登陆界面输用户名和密码的对话框出不来，用ie和其他游览器都行。好困惑啊，poi也重装过了，用户信息里poi文件夹也删过，都没什么用，偶尔有时开开关关会好两次，麻烦帮忙看下，谢谢。**

**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:**

[image](https://user-images.githubusercontent.com/35768918/35440240-da159cfa-02e1-11e8-8d5f-30b7c566b45e.png)
![image](https://user-images.githubusercontent.com/35768918/35440270-ffb304e8-02e1-11e8-945a-3d4e51546484.png)

**Comment by gnattu** [comment]
如果您是岛风go用户，请尝试更换线路或者F5连打。这个问题是代理没能加载出登录框，poi这边无能为力，不同浏览器均有这个问题的报告。

**Comment by KagamiChan** [comment]
@pandaduo 并不能复现

**Comment by pandaduo** [comment]
我再试试看，，虽然之前已经F5连打更换线路。。谢谢了。。但是火狐和ie都挺正常

**Comment by KagamiChan** [comment]
在 cmd 里面输入 `netsh winsock reset` 执行一下试试，还是不行的话只能问问岛风 go 的客服了
