### ISSUE TITLE
POI界面无法加载

### ISSUE THREAD

**Issue by Megumi-RQY** [poooi/poi#1707]
**poi 版本 / poi version:8.1.0

**操作系统 / OS:WIN10 版本1709

**你遇到了什么样的问题 / POI界面无法加载（
![1](https://user-images.githubusercontent.com/26399538/35472292-d9b25606-03c0-11e8-82c1-cdb958d75af0.png)
）

**有没有重现的方法，或者与问题相关的任何信息 / POI打开后一直是黑屏，可以在黑屏下正常执行任何操作（在黑屏下点击右上角可以最小化和关闭），游戏也可以正常加载和操作，游戏声音正常。但黑屏下只能听声音凭印象操作所以基本上什么都干不了。Webview打开也是黑屏，因此也无法检查哪里出了问题：(
尝试过重新安装POI，无效。

**Comment by KagamiChan** [comment]
麻烦打开 cmd.exe，把 poi.exe 拖动到里面去，按回车运行，把运行结果发一下

**Comment by Megumi-RQY** [comment]
@KagamiChan 
[WARN] Cannot get system flash plugin path
[INFO] Proxy listening on 64407

**Comment by gnattu** [comment]
Ctrl+Shift+i 弹出来的开发者工具截个图 然后点击顶部的console 在截个图

**Comment by Megumi-RQY** [comment]
@KagamiChan 
Sorry, 刚才应该是cmd卡住了所以运行结果没给全。完整的运行结果如下图
![1](https://user-images.githubusercontent.com/26399538/35604734-d11d38ba-0697-11e8-905c-cedddacf4833.png)

@gnattu 
开发者工具打开是黑屏。
![2](https://user-images.githubusercontent.com/26399538/35604751-ec82ce9e-0697-11e8-9f16-c6f75401c1f3.png)

**Comment by gnattu** [comment]
在命令后加`--disable-gpu`，注意和命令前要留有空格，比如`XXXX/poi.exe --disable-gpu`,然后回车 能不能加载画面。

**Comment by Megumi-RQY** [comment]
@gnattu 
可以了，一切正常

**Comment by gnattu** [comment]
那请你在高级设置里勾选禁用硬件加速。这个是Windows10最新版下面某些显卡驱动的兼容性问题，poi组只能等上游的修复。
