### ISSUE TITLE
插件"舰娘信息"里怎么关闭头像显示？

### ISSUE THREAD

**Issue by deeporist** [poooi/poi#1709]
**poi 版本 / poi version:**
8.1

**操作系统 / OS:**
Win 8.1 x64

**插件名和版本 / Plugin name & version:**
ship girls info ver 5.0.1

**你遇到了什么样的问题 / The problem you've met:**
can not close "show avatar" in this plugin

**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:**
POI的设置里已经把头像显示关掉了 但是"舰娘信息"插件里还是会显示
感觉和配置文件有关
之前设置背景时也折腾过一次 先是通过poi自己的设置选项(设置-显示-选择背景图片)但是效果不满意就在选项里切回默认了 后来我又自己在css里设置好了
但是这个设置就留死在配置文件里 后来调Console时老是有这条设置的报错(我把那张测试的背景图片删掉了结果Console就报错找不到文件) 找了试了半天才找到正确的文件和写法把这行设置给去了
感觉这次也是 是不是poi和插件是共用一个配置文件, 但是poi里改了设置后却没有反映进配置文件里 结果插件就照着旧配置来了

**Comment by KochiyaOcean** [comment]
@deeporist 舰娘信息目前没用不显示头像的选项
