### ISSUE TITLE
插件我变强了内容被挡住

### ISSUE THREAD

**Issue by dhhxkdz** [poooi/poi#1710]
**poi 版本 / poi version:** 8.1.0

**操作系统 / OS:**  WIN7

**插件名和版本 / Plugin name & version:** 我变强了，4.3.1

**你遇到了什么样的问题 / The problem you've met:**
我变强了插件里的上半部分内容被其插件内容挡住了，而且挡住的东西无法取消。
![qq 20180129201018](https://user-images.githubusercontent.com/36038925/35679694-026776aa-0793-11e8-9bb6-68854e4d0e69.png)

**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:**

**Comment by nagatoyk** [comment]
这插件好像很久没更新了吧

**Comment by KagamiChan** [comment]
> @chibaheit 你良心不会痛吗

**Comment by KochiyaOcean** [comment]
要重构了，要重构了
吃吧再不上只能我上了……

**Comment by KagamiChan** [comment]
日常 @Chibaheit
