### ISSUE TITLE
8.1.0版本窗口宽度800时 100以上血量舰娘在有闪未补给时舰名信息会多一行显示

### ISSUE THREAD

**Issue by castore** [poooi/poi#1711]
**poi 版本 / poi version:**
8.1.0

**操作系统 / OS:**

Win7 x64 pro
**插件名和版本 / Plugin name & version:**

**你遇到了什么样的问题 / The problem you've met:**
![_](https://user-images.githubusercontent.com/7022156/35680820-5da94bda-0796-11e8-8092-f54cd48cc21b.png)换行显示

补给图标遮挡
![2](https://user-images.githubusercontent.com/7022156/35681185-925a036e-0797-11e8-9984-93af307257d4.png)

**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:**

**Comment by KagamiChan** [comment]
@castore 不同主题的图标宽度不一致，此外也和字体的宽度有关，很难做到完美，建议把最小宽度调高一点
