### ISSUE TITLE
请求授权地图路径点数据文件的使用

### ISSUE THREAD

**Issue by lhc-clover** [poooi/poi#1712]
Hi，在下是[KanColleCommand](https://github.com/lhc-clover/KanColleCommand)的开发者。
目前在开发罗盘剧透功能，希望能得到地图路径点数据文件[map.json](https://github.com/poooi/poi/blob/master/assets/data/fcd/map.json) 的使用授权。
Thanks.

**Comment by KochiyaOcean** [comment]
符合 MIT 协议就行了
