### ISSUE TITLE
战斗记录插件无法使用

### ISSUE THREAD

**Issue by deadfish0** [poooi/poi#1713]
**poi 版本 / poi version:**8.1.0

**操作系统 / OS:**win10 1607

**插件名和版本 / Plugin name & version:**战斗记录 ver.3.9.0

**你遇到了什么样的问题 / The problem you've met:**
无法显示任何内容
![image](https://user-images.githubusercontent.com/36107736/35768714-8157edce-093b-11e8-90fc-5806de4a0915.png)

**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:**
![image](https://user-images.githubusercontent.com/36107736/35768745-18136a9a-093c-11e8-8e69-ff6f18c45e72.png)

**Comment by KagamiChan** [comment]
请在激活战斗记录插件窗口的时候按 ctrl + shift + i，把打开的插件的开发者工具的窗口内容截图

**Comment by deadfish0** [comment]
![image](https://user-images.githubusercontent.com/36107736/35777314-d867bc1a-09e6-11e8-9291-02c58a0f3922.png)

**Comment by Javran** [comment]
@deadfish0 开devtools (随便哪个), 这段输入进去把结果截图一下:

```javascript
getStore().const.$equips
```

**Comment by deadfish0** [comment]
![q dbc 3 rap1tj6h 6iss](https://user-images.githubusercontent.com/36107736/35808346-6bb3252a-0ac0-11e8-9682-06d2b752a8c6.png)

**Comment by Javran** [comment]
@deadfish0 试一下新版本 (3.10.0)看下有没问题

**Comment by deadfish0** [comment]
@Javran 更新了一下插件，还是没有任何改变
