### ISSUE TITLE
poi最小化后无法复原

### ISSUE THREAD

**Issue by ylft** [poooi/poi#1714]
**poi 版本 / poi version:**
8.1.0

**操作系统 / OS:**

win10 1709
**插件名和版本 / Plugin name & version:**

**你遇到了什么样的问题 / The problem you've met:**
最小化poi以后，无法复原poi 窗口，预览一切正常，但是就是无法看到软件窗口，重启，删除，重装软件皆不可修复此问题

**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:**

![image](https://user-images.githubusercontent.com/36120842/35774079-6c3a2316-09b9-11e8-9447-c11cf24dcadf.png)

**Comment by KagamiChan** [comment]
开发者工具请切换到 console 再截图

**Comment by ylft** [comment]
![image](https://user-images.githubusercontent.com/36120842/35790619-752c3796-0a97-11e8-8e4c-70ada6902e90.png)

**Comment by KochiyaOcean** [comment]
怀疑是系统本身问题

**Comment by KagamiChan** [comment]
@ylft 保留这个窗口，然后最小化，看看能不能复现你说的问题，复现的时候这个窗口显示什么内容

**Comment by ylft** [comment]
换8.1.0之前用poi4个多月，一直没问题

**Comment by KochiyaOcean** [comment]
@ylft 换回 8.0.0 呢

**Comment by KochiyaOcean** [comment]
@ylft 提供一下 %appdata%/config.cson 的信息

**Comment by KagamiChan** [comment]
@ylft 我是说，保留开发者工具的窗口

**Comment by ylft** [comment]
poi:
  theme: "paperblack"
  homepage: "http://www.dmm.com/netgame/social/-/gadgets/=/app_id=854854/"
  first: "8.1.0"
  language: "zh-CN"
  screenshotFormat: "jpg"
  window:
    x: 2560
    y: 1500
    width: 1080
    height: 1400
    isFullScreen: false
    isMaximized: false
  enableDMMcookie: true
  cacheSize: "800"
  flashQuality: "best"
  webview:
    width: -1
  tabarea:
    double: false
    grid: true
  useSVGIcon: true
  layout: "vertical"
  reverseLayout: false
  content:
    muted: false
packageManager:
  mirrorName: "npm"
  proxy: false
  enableBetaPluginCheck: false
plugin:
  Akashic:
    nickNameId: "161835795"
  ShipInfo:
    sortName: "lv"
    sortOrder: 0
    rawValue: 0
    bounds:
      x: 432
      y: 170
      width: 1684
      height: 896
    sallyAreaChecked: [
      true
      true
      true
      true
    ]
    modernizationRadio: 0
    lvRadio: 0
    lockedRadio: 1
    shipTypes: 8388607
  Leveling:
    bounds:
      x: 1268
      y: 293
      width: 801
      height: 601
  ItemInfo:
    bounds:
      x: 205
      y: 103
      width: 671
      height: 401
  "poi-plugin-wheres-my-fuel-gone":
    lastShowChangelogVersion: "0.6.3"
  WheresMyFuelGone:
    bounds:
      x: 0
      y: 0
      width: 1699
      height: 913
  "poi-plugin-prophet":
    enable: true
  prophet:
    notify:
      enable: true

**Comment by KochiyaOcean** [comment]
```cson
window:
x: 2560
y: 1500
width: 1080
height: 1400
```
这段删掉
看起来是因为某种误操作（双屏情况下在最小化状态拔掉显示器之类）导致位置记录到未知领域了

**Comment by ylft** [comment]
解决了，谢谢
