### ISSUE TITLE
游戏无声音问题

### ISSUE THREAD

**Issue by hxiao3** [poooi/poi#1715]
poi 版本 / poi version: 8.1.0

操作系统 / OS: win 10

插件名和版本 / Plugin name & version: 初始默认

你遇到了什么样的问题 / The problem you've met: 
海外美国直连。游戏内无声音。使用火狐浏览器登陆游戏声音正常；使用poi浏览器登陆bilibili看视频，声音正常。

有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:

**Comment by KochiyaOcean** [comment]
@hxiao3 确定没关掉游戏内的声音设置么……

**Comment by hxiao3** [comment]
@KochiyaOcean 
确认。
游戏内声音设置，poi声音设置均为最大。
同设置下火狐浏览器正常。
是从登陆界面的kancolle都开始没声音的。
