### ISSUE TITLE
装备改修无法显示内容

### ISSUE THREAD

**Issue by janmelin** [poooi/poi#1717]
**poi 版本 / poi version:** 8.1.0

**操作系统 / OS:** macOS 10.13.3

**插件名和版本 / Plugin name & version:** 装备改修 Ver. 6.0.1

**你遇到了什么样的问题 / The problem you've met:** 装备改修无法显示内容，包括页面上部的星期几。

**Comment by KagamiChan** [comment]
请在激活装备改修窗口的情况下按下 command + option + i
并把弹出的开发者工具的 console 部分截图

**Comment by janmelin** [comment]
这两天又能显示了
