### ISSUE TITLE
黑屏

### ISSUE THREAD

**Issue by DavidDiao** [poooi/poi#1721]
**poi 版本 / poi version:**
8.1.0

**操作系统 / OS:**
Windows 7

**你遇到了什么样的问题 / The problem you've met:**
Flash的那个窗口突然直接全黑，插件基本正常。Alt+F4不提示直接退出poi同时关闭正常工作的插件。以前没出现过，这个版本出现了3次
这一次窗口还带alpha
![image](https://user-images.githubusercontent.com/21342724/36196484-3ab9633a-11b4-11e8-97aa-0840926622f3.png)
顺带一提插件们也不定时出现类似的问题，不过重启一下都能解决。但是出击跑到一半突然炸掉非常不爽所以忍不住来这边问问

**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:**
没找到什么规律。。好像都是在出击的时候？
~~Console？不存在的。本体都炸了哪来的Console~~

**Comment by KochiyaOcean** [comment]
用 cmd 启动看看炸的时候有没有报错吧
就是开命令提示符以后直接 exe 拖进去回车

**Comment by DavidDiao** [comment]
诶poi居然可以有命令行输出的啊
不过这问题是不定时出现的啊
输出重定向到文件没问题吧。。挂着个命令行嫌烦

**Comment by KochiyaOcean** [comment]
@DavidDiao 总之有输出就行了……

**Comment by DavidDiao** [comment]
开始疯狂报错了。。
Attempting to call a function in a renderer window that has been closed or released.
Function provided here: 后面跟的就是五花八门的了
看上去就是这个窗口被整个卸载了

**Comment by KochiyaOcean** [comment]
此错误应该无关

**Comment by KochiyaOcean** [comment]
看看 8.2.0-beta.0 是否还有吧

**Comment by gnattu** [comment]
```
A Parser-blocking, cross site (i.e. different eTLD+1) script, http://rt.gsspat.jp/g?rtid=13973&j=1, is invoked via document.write. The network request for this script MAY be blocked by the browser in this or a future page load due to poor network connectivity. If blocked in this page load, it will be confirmed in a subsequent console message.See https://www.chromestatus.com/feature/5718547946799104 for more details.
```
8.2.0已复现，“聪明”的Chrome会自动在他认为”不良“的网络环境中阻止部分外部脚本加载，然后整个页面似乎都会受到影响。

**Comment by toooonyy** [comment]
macOS 10.13.3
Poi 8.1.0
可以复现，一般在按登陆按钮的时候会黑一次。刚刚甚至进去收了一个远征然后黑掉，刷新后收了第二个

**Comment by KochiyaOcean** [comment]
由于 `#disallow-doc-written-script-loads` 早在 Chromium 55 就已经实装，目前判断为与此无关

**Comment by KagamiChan** [comment]
我自己也碰见过几次类似的情况，但是一直没有能够有机会看到对应的信息来印证。想要印证的时候就出不来。不知道是不是需要模拟一个很差的网络才能稳定复现

**Comment by DavidDiao** [comment]
自己体感不是网络的问题，更像是内存炸了之类的感觉
其实关键是能想办法弄到出错信息吧

**Comment by KagamiChan** [comment]
@DavidDiao 是的，这个就需要在命令行底下执行 poi 才能看到主程序的出错信息，但是很多时候我们都是直接运行的

**Comment by DavidDiao** [comment]
@KagamiChan 我当时有过几次通过poi>log.log这种方法记录到出错时的输出，但并没有看到什么有价值的东西，只有大量重复的报错信息（我前面提到了）
大概是因为真正有用的信息是在标准错误流里的？以后用poi>log.log 2>err.log试试
另外输出的内容没有时间戳，无法分辨哪些是出错前的内容哪些是出错后的内容，比较难受

**Comment by DavidDiao** [comment]
又出现了，然而err.log什么也没有
好吧我以后还是老老实实开着命令行吧
