### ISSUE TITLE
[Feature Request] 出擊時主面板自動切換回第一艦隊

### ISSUE THREAD

**Issue by lycsjm** [poooi/poi#1722]
**poi 版本 / poi version:**
8.1.0

**操作系统 / OS:**

Arch Linux

**你遇到了什么样的问题 / The problem you've met:**
接收遠征後，主面板會自動切換到回來的艦隊。
但是並不會在出擊時自動切換回第一艦隊，或是禁止自動切換到非第一艔隊。
希望能在出擊時主面板自動切換回第一艦隊，或是至少增加選項禁用遠征自動切換艦隊。

**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:**

**Comment by KochiyaOcean** [comment]
![image](https://user-images.githubusercontent.com/8194131/36217163-13fc31b0-11f4-11e8-88a6-8b34de50ebf6.png)

**Comment by KochiyaOcean** [comment]
![image](https://user-images.githubusercontent.com/8194131/36217215-344e93fe-11f4-11e8-9872-19e6bfaa47f6.png)
插件的自动切换

**Comment by lycsjm** [comment]
@KochiyaOcean 
現在的使用狀況是這樣的：
第 2 艦隊回來了， 切換到「艦隊面板」中的「第  2 艦隊」
派遠征出去後，接著出擊
這時後他會切換到「主面板」但依然維持在「第 2 艦隊」
這三個功能就我之前使用的感想是這只用來切換面板，但不會自動切換主面板和艦隊面板中的艦隊。

**Comment by KagamiChan** [comment]
目前本体好像没有根据远征来自动切换当前显示的舰队的功能。听起来像是易及远征插件提供的自动切换
cc @Javran
