### ISSUE TITLE
无法登陆 持续黑屏？

### ISSUE THREAD

**Issue by nanjoshika** [poooi/poi#1724]
**poi 版本 / poi version:**
8.1.0

**操作系统 / OS:**
win 10 版本1709(OS 内部版本 16299.125)

Windows 10 用户请说明具体的发行版本号（可以通过 `winver` 命令来获得）
For Windows 10 users, please specify your build version (can be obtained through `winver` command)
-->

**你遇到了什么样的问题 / The problem you've met:**
我是北美用户 前几天更新windows后
游戏就黑屏 一直等待游戏数据中 无法连接到登陆界面
网络代理 PAC 文件
https://super.crystalacg.com/proxy_ssl.pac
也是无效的
![image](https://user-images.githubusercontent.com/36521954/36284688-9e0d5690-1276-11e8-9c33-dfce6f8a1fc3.png)

**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:**
chrome 上可以登录

![qq 20180215173344](https://user-images.githubusercontent.com/36521954/36284675-924a25b8-1276-11e8-993c-e8d9e5a3ea48.png)

**Comment by gnattu** [comment]
`return 'HTTPS super.crystalacg.com:443'`
不支持https代理，所以加载不出页面

**Comment by nanjoshika** [comment]
@gnattu 我该如何解决这个问题。不开代理的话

**Comment by gnattu** [comment]
如果不开代理一直等待数据一般是网络原因，但是考虑到你最近升级了Windows，可以尝试命令行中输入`netsh winsock reset`重置winsock试试看。

**Comment by nanjoshika** [comment]
@gnattu 已按上述方法尝试 还是在需要登录的时候 一直黑屏显示等待游戏数据 无法 连接显示 切换到登录界面
![1](https://user-images.githubusercontent.com/36521954/36286596-77481344-127e-11e8-9c9a-6d15d926e790.png)

**Comment by nanjoshika** [comment]
@gnattu 应该是代理问题。我买了岛风go设置了下端口就好了。麻烦你这么久辛苦啦。
