### ISSUE TITLE
POI运行弹窗

### ISSUE THREAD

**Issue by stella6678** [poooi/poi#1725]
**poi 版本 / poi version:**
8.1.0

**操作系统 / OS:**
WIN8 64

**你遇到了什么样的问题 / The problem you've met:**

安装8.1.0之后 只要一运行POI就会弹窗显示

Windows cannot access specific device, path, or file. You my not have the appropriate permissions to access the item.

但是我POI的运行是管理员模式下的 不知道这个问题要怎么避免
**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:**

**Comment by KochiyaOcean** [comment]
安装到了哪个路径下？可以试试看安装到其他的路径看看（比如 D 盘

**Comment by stella6678** [comment]
一开始选了C盘 刚刚也试过D盘 都是一样的问题说是我没有权限

**Comment by KochiyaOcean** [comment]
https://support.microsoft.com/en-ca/help/2669244/windows-cannot-access-the-specified-device-path-or-file-error-when-you 微软官方的解释
虽然是英语姑且参照一下吧……

**Comment by KagamiChan** [comment]
https://support.microsoft.com/zh-cn/help/2669244/windows-cannot-access-the-specified-device-path-or-file-error-when-you

机翻中文
