### ISSUE TITLE
8.20 beta0更新后，任务的中文详情显示有误

### ISSUE THREAD

**Issue by azuse** [poooi/poi#1726]
**poi 版本 / poi version:**
8.20 beta0

**操作系统 / OS:**

windows10 1709
**插件名和版本 / Plugin name & version:**

**你遇到了什么样的问题 / The problem you've met:**
过年还在更新开发人员辛苦了。

8.20更新后，任务的中文详情显示有误，不知道是怎么回事。
希望能有解决方法。

**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:**

如图
<img src="http://azusebox.moe/wp-content/uploads/2018/02/草图2.png" />
<img src="http://azusebox.moe/wp-content/uploads/2018/02/草图.png" />

<img src="http://azusebox.moe/wp-content/uploads/2018/02/2018-02-17-1.png" />

**Comment by KagamiChan** [comment]
5.0 版本的任务信息插件应该基本修好了这个问题，如果还有不正常的请留言指出
