### ISSUE TITLE
POI本身会突然卡死的问题

### ISSUE THREAD

**Issue by iamajar** [poooi/poi#1727]
**poi 版本 / poi version:**
8.1.0~8.2.0 beta 均出现了该问题

**操作系统 / OS:**

window10 1607

**插件名和版本 / Plugin name & version:**

2018.2.17当天更新的所有插件的最新版本

**你遇到了什么样的问题 / The problem you've met:**
打开poi一段时间后，会在某个时刻，poi本身直接卡死，窗口无法拖动，面板区无法点击，游戏界面也是卡住不动。过几分钟后会恢复 。

**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:**
目前不知道如何重现，我这里出现的频率还挺高的，3~7分钟一次

<img src="https://user-images.githubusercontent.com/15335713/36337515-117db6bc-13d3-11e8-89ae-81f099eff6e8.png">
![poi](https://user-images.githubusercontent.com/15335713/36337515-117db6bc-13d3-11e8-89ae-81f099eff6e8.png)

**Comment by KochiyaOcean** [comment]
是否有安装海色相簿插件？

**Comment by iamajar** [comment]
这是所有插件列表

![poi2](https://user-images.githubusercontent.com/15335713/36338615-190ee8f8-13ef-11e8-9dcd-7bf3d530dbbc.png)

**Comment by iamajar** [comment]
windows10升级到了1709后这个问题就没有出现了
