### ISSUE TITLE
冬活活动地图难度读取错误

### ISSUE THREAD

**Issue by Ziziru** [poooi/poi#1733]
**poi 版本 / poi version:** 8.0.0

**操作系统 / OS:** win10 1709  OS内部版本 16299.248

**插件名和版本 / Plugin name & version:**

**你遇到了什么样的问题 / The problem you've met:**
冬活过程中，e1的地图难度读取为 undefined;
e2地图难度选择是丙，记录却是乙
![qq 20180220162213](https://user-images.githubusercontent.com/21362277/36413713-8b2f825e-165a-11e8-9fef-662bf8b44739.png)
![qq 20180220162223](https://user-images.githubusercontent.com/21362277/36413714-8b5cce12-165a-11e8-8ff4-202be4698e1b.png)

**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:**

**Comment by KochiyaOcean** [comment]
由于追加丁难度，全部难度 API 向后移一位
本体已经修复，其他插件需要各自处理

**Comment by KagamiChan** [comment]
涉及插件：
- 战斗记录
- 耗资记录
- 海域血量
- 航海日志
- 数据汇报（？）

**Comment by KagamiChan** [comment]
应该已经都修复了
