### ISSUE TITLE
概览和舰队等需要读取游戏数据的功能失效

### ISSUE THREAD

**Issue by Bellshigure** [poooi/poi#1734]
**poi 版本 / poi version:**
8.2.0(及测试版）

**操作系统 / OS:**
win10 版本号1709
**插件名和版本 / Plugin name & version:**

**你遇到了什么样的问题 / The problem you've met:**
我的概览和舰队两栏，包括所有需要读取数据的功能，如耗资记录和打捞记录等，不再随游戏的进行而更新数据，而是一直停在半个月前的一天

**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:**

![default](https://user-images.githubusercontent.com/36678896/36448651-359da186-16c3-11e8-8885-df67095e9bc8.png)
![default](https://user-images.githubusercontent.com/36678896/36448657-3a23a73c-16c3-11e8-8d07-955d7754ca26.png)
![default](https://user-images.githubusercontent.com/36678896/36448732-6ee810f2-16c3-11e8-83dd-372c67e3fd0b.png)

**Comment by KagamiChan** [comment]
你是什么方式连入的游戏？

关闭 poi，删除 %appdata%/poi/Local Stoarge 文件夹，再重新打开看看

**Comment by Bellshigure** [comment]
不好意思。。我找不到这个文件夹，就连查询本机下也没看到

**Comment by Bellshigure** [comment]
补充 我是通过shadowsocks全局连入的，因为不全局无法代理

**Comment by KagamiChan** [comment]
按 win + r，输入 `%appdata%/poi`，按确定，删掉里面的 Local Storage 文件夹

**Comment by Bellshigure** [comment]
嗯。。更尴尬的问题出现了 右边虽然清空了，但也没有再次读取新的数据，包括清除缓存和cookies之后重新登录，麻烦请问我是应该在删除之后再次安装吗？

**Comment by KagamiChan** [comment]
删除 %appdata%/poi/config.cson 文件呢

**Comment by Bellshigure** [comment]
还是不行。给您附上截图
![1](https://user-images.githubusercontent.com/36678896/36620165-c1aa281e-192c-11e8-9021-560da42df1f0.png)
![2](https://user-images.githubusercontent.com/36678896/36620167-c36f6f6a-192c-11e8-89fd-305697799f4e.png)
![3](https://user-images.githubusercontent.com/36678896/36620170-c4a8b3d2-192c-11e8-9897-e4b7b0902ad0.png)
![4](https://user-images.githubusercontent.com/36678896/36620173-c625edd8-192c-11e8-8e56-ceb42ddbe2eb.png)
![5](https://user-images.githubusercontent.com/36678896/36620174-c7902ada-192c-11e8-9835-3e495762c745.png)
![6](https://user-images.githubusercontent.com/36678896/36620176-c9d23ebe-192c-11e8-85c7-375e92fb9871.png)
![7](https://user-images.githubusercontent.com/36678896/36620180-cb24e42e-192c-11e8-9058-7bea39147968.png)

**Comment by gnattu** [comment]
能更详细地说明一下游戏的连接方式吗？
比如是使用何种代理软件连接的SS，poi又是如何设置的代理，是否是在dmm页面上进行的游戏，还是说使用了在线缓存？

**Comment by Bellshigure** [comment]
![default](https://user-images.githubusercontent.com/36678896/36632522-98164f78-19c2-11e8-9b5f-188e3397c346.png)
用的是这个4.0.6版本的ss代理软件链接
poi的设置如下
![default](https://user-images.githubusercontent.com/36678896/36632545-d19b49a6-19c2-11e8-8198-1d868913ac08.png)
是直接在poi内打开dmm页面游戏的
缓存方式没有改过，从开始用poi就没有动过的

**Comment by KagamiChan** [comment]
@Bellshigure 为什么要设置 poi 端口？

**Comment by KochiyaOcean** [comment]
@Bellshigure poi 端口不应该设置为和代理端口相同的数值，会起冲突
没有和其他辅助工具串联的需求就保持 0
