### ISSUE TITLE
poi8.2.2視窗跑掉

### ISSUE THREAD

**Issue by M4Tank** [poooi/poi#1737]
**poi 版本 / poi version:**
wind10 1709

**操作系统 / OS:**

**插件名和版本 / Plugin name & version:**

poi8.2.2

**你遇到了什么样的问题 / The problem you've met:**
https://i.imgur.com/qtrqI7O.png

**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:**

**Comment by KochiyaOcean** [comment]
删除 `%appdata%/poi/config.cson` 重置设置看看

**Comment by M4Tank** [comment]
%appdata%/poi/config.cson <怎麼刪除

**Comment by KochiyaOcean** [comment]
![image](https://user-images.githubusercontent.com/8194131/36460720-096c6f7c-16fd-11e8-8e8c-cc2fc16276bd.png)
![image](https://user-images.githubusercontent.com/8194131/36460730-1cffbf9e-16fd-11e8-9e83-0ad9106c7bcf.png)

**Comment by M4Tank** [comment]
https://i.imgur.com/zKL3XcE.jpg

視窗還是一樣跑掉
wind10 縮放已經調到100%

**Comment by KochiyaOcean** [comment]
由于排版策略变动，现在的面版不再强制设置最小尺寸，请自行调整布局（使用指定游戏界面大小，或者调低窗口高度
