### ISSUE TITLE
poi的提示窗口被屏蔽了如何恢复，就是大破提示和远征回来的那个提示窗口

### ISSUE THREAD

**Issue by Mathemaster** [poooi/poi#1739]
**poi 版本 / poi version:**

**操作系统 / OS:**

**插件名和版本 / Plugin name & version:**

**你遇到了什么样的问题 / The problem you've met:**

**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:**

**Comment by KochiyaOcean** [comment]
看不懂在说什么

**Comment by Mathemaster** [comment]
就是右下角不是有个弹窗吗，我上次不小心点到了忽略弹窗，然后就只有提示音，没有弹窗了

**Comment by KochiyaOcean** [comment]
在系统设置里面改……
