### ISSUE TITLE
有關8.2 視窗調整問題

### ISSUE THREAD

**Issue by canonho** [poooi/poi#1740]
**poi 版本 / poi version:**
8.2 beta 2.0

**操作系统 / OS:**
Windows 7

**你遇到了什么样的问题 / The problem you've met:**
得知8,2更新調整了面版設置 
昨天還在用8.1 beta 4.0時 
能夠將其他程式 如chrome 和poi 各設定視窗為一半一半(能調整到可完全看到遊戲畫面和插件功能)
現在8.2 我不知道為什麼 poi的視窗 拖拉到某一個位置時便不能調整了 

![default](https://user-images.githubusercontent.com/32305815/36465183-f98aecde-170e-11e8-8bb4-dac5e9a19785.png)

**Comment by canonho** [comment]
我不太會表達 希望你能夠明白

**Comment by KochiyaOcean** [comment]
在 8.2.0 以后的版本中，如果设置了固定游戏尺寸则窗口大小不会允许小于该尺寸
请使用根据窗口动态调整功能或者指定更小的尺寸

**Comment by canonho** [comment]
這功能在哪裡?

**Comment by canonho** [comment]
我如果照8.1版本開啟自動調整解析度 窗口會變得好大 
那麼我現在應該調整至什麼尺寸

**Comment by KochiyaOcean** [comment]
![image](https://user-images.githubusercontent.com/8194131/36465445-64d279cc-1718-11e8-87d4-0a75568ec739.png)
![image](https://user-images.githubusercontent.com/8194131/36465455-7175b7fc-1718-11e8-8a00-7f1e8a32c9c6.png)

**Comment by KochiyaOcean** [comment]
如果设置了自动调整，游戏宽度会基于窗口宽度自动调整（纵向布局时会填满宽度）
如果设置了固定解析度，游戏尺寸会固定在设置的大小上，并且窗口宽度被限制不得低于游戏尺寸

**Comment by canonho** [comment]
所以現在要自己手動調整合適的尺寸嗎?

**Comment by KochiyaOcean** [comment]
是的，建议的游戏尺寸是 800（原始分辨率）

**Comment by canonho** [comment]
那麼面版布局 是第2個嗎? 以往用第4個布局 現在第4個我不太會調整了

**Comment by KochiyaOcean** [comment]
面版在下面是第二个，第四个是面板在右边（参照图标所示）
