### ISSUE TITLE
8.2.1無法截圖跟關音效

### ISSUE THREAD

**Issue by M4Tank** [poooi/poi#1742]
**poi 版本 / poi version:**
bata8.2.1
**操作系统 / OS:**

Windows1709
**插件名和版本 / Plugin name & version:**

**你遇到了什么样的问题 / The problem you've met:**

poi下方的工具欄無法使用
無法截圖跟關音效 而且截圖存放目錄也無法更改

**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:**

**Comment by KochiyaOcean** [comment]
更新到 beta.3
