### ISSUE TITLE
8.20-beta3在平板窗口無法最大化

### ISSUE THREAD

**Issue by yanagi310** [poooi/poi#1743]
**poi 版本 / poi version:**
8.20-beta3

**操作系统 / OS:**
win10  14393

**你遇到了什么样的问题 / The problem you've met:**
之前沒有使用過8.20的其他版本，beta3版本在微軟的平板設備上無法窗口最大化
卸載該版本之後，更低的版本也變得無法窗口最大化，設置自動調整分辨率后窗口無限橫向拉伸
不能正常使用，設置縱向佈局之後依然無法窗口最大化，UI部分完全看不到

**Comment by KagamiChan** [comment]
无法最大化是说最大化按钮没有办法点击吗

关于 ui 部分：
> 如果设置了自动调整，游戏宽度会基于窗口宽度自动调整（纵向布局时会填满宽度）
> 如果设置了固定解析度，游戏尺寸会固定在设置的大小上，并且窗口宽度被限制不得低于游戏尺寸
