### ISSUE TITLE
E3 海域小地图路线问题

### ISSUE THREAD

**Issue by tkmikan** [poooi/poi#1744]
**poi 版本 / poi version:**
8.1.0

**操作系统 / OS:**
1709  16299.248

~~**插件名和版本 / Plugin name & version:**~~

**你遇到了什么样的问题 / The problem you've met:**
![image](https://user-images.githubusercontent.com/36260601/36523259-b3f60d20-17db-11e8-89fa-1dfa948843a6.png)

实际上是从右边出发点出发的

**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:**

![image](https://user-images.githubusercontent.com/36260601/36523283-cf6dce12-17db-11e8-80de-209d3b1a32ef.png)

**Comment by KagamiChan** [comment]
部分两个出发点的地图，之中的一个出发点的标注会有问题，e3 的这个已经修复
