### ISSUE TITLE
未卜先知结果错误

### ISSUE THREAD

**Issue by Ziziru** [poooi/poi#1745]
**poi 版本 / poi version:**8.0.0

**操作系统 / OS:**1709 家庭版  16299.248

**插件名和版本 / Plugin name & version:**未卜先知 Ver 7.1.0

**你遇到了什么样的问题 / The problem you've met:**
在e4boss点选择夜战后，结果错误，乙难度，支援舰队到达后将boss打死，而插件显示并没有打死

![screenshot](https://user-images.githubusercontent.com/21362277/36536724-f10cbce0-1808-11e8-95d1-09be6946e32c.png)

**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:**
目前只出现过一次，在第一次进入boss点将其打死，然后之后进入boss点两次，没有击杀boss，预测结果是正确的

**Comment by KagamiChan** [comment]
在战斗详情里面看是正常的吗？麻烦把这一场战斗对应的数据发给我

**Comment by Ziziru** [comment]
![qq 20180222223212](https://user-images.githubusercontent.com/21362277/36544044-6d09efd6-1820-11e8-86b3-a6998b60df55.png)
![qq 20180222223219](https://user-images.githubusercontent.com/21362277/36544056-73410c40-1820-11e8-8e49-06885f37d6eb.png)
进夜战后先来了支援舰队，然后数据就对不上了

**Comment by KagamiChan** [comment]
麻烦把这场战斗的数据发给我看一下

**Comment by Ziziru** [comment]
战斗的数据怎么查看？

**Comment by KagamiChan** [comment]
战斗详情内找到对应的战斗
点击复制数据
在这里粘贴

**Comment by Ziziru** [comment]
{"version":"2.1","type":"Boss","map":[41,4,30],"desc":null,"time":1519270890123,"fleet":{"type":2,"main":[{"api_id":66,"api_sortno":228,"api_ship_id":428,"api_lv":75,"api_exp":[330745,255,97],"api_nowhp":57,"api_maxhp":57,"api_soku":10,"api_leng":2,"api_onslot":[3,3,3,3,0],"api_kyouka":[22,32,19,30,0,0,0],"api_backs":6,"api_fuel":11,"api_bull":26,"api_slotnum":4,"api_ndock_time":0,"api_ndock_item":[0,0],"api_srate":3,"api_cond":100,"api_karyoku":[65,77],"api_raisou":[66,84],"api_taiku":[112,106],"api_soukou":[79,78],"api_kaihi":[74,81],"api_taisen":[0,0],"api_sakuteki":[50,55],"api_lucky":[14,64],"api_locked":1,"api_locked_equip":0,"api_sally_area":2,"poi_slot":[{"api_id":10264,"api_slotitem_id":272,"api_locked":0,"api_level":0},{"api_id":12606,"api_slotitem_id":131,"api_locked":0,"api_level":0},{"api_id":9298,"api_slotitem_id":106,"api_locked":0,"api_level":0},{"api_id":1245,"api_slotitem_id":135,"api_locked":0,"api_level":0},null],"poi_slot_ex":null},{"api_id":10,"api_sortno":1383,"api_ship_id":283,"api_lv":78,"api_exp":[362349,7051,46],"api_nowhp":46,"api_maxhp":50,"api_soku":5,"api_leng":1,"api_onslot":[15,14,13,9,0],"api_kyouka":[29,0,44,29,0,0,0],"api_backs":5,"api_fuel":11,"api_bull":16,"api_slotnum":4,"api_ndock_time":3150000,"api_ndock_item":[5,10],"api_srate":4,"api_cond":51,"api_karyoku":[29,29],"api_raisou":[0,0],"api_taiku":[109,69],"api_soukou":[59,59],"api_kaihi":[60,69],"api_taisen":[0,0],"api_sakuteki":[70,79],"api_lucky":[12,59],"api_locked":1,"api_locked_equip":0,"api_sally_area":2,"poi_slot":[{"api_id":10948,"api_slotitem_id":22,"api_locked":0,"api_level":0,"api_alv":7},{"api_id":6633,"api_slotitem_id":22,"api_locked":0,"api_level":0,"api_alv":7},{"api_id":3043,"api_slotitem_id":22,"api_locked":0,"api_level":0,"api_alv":7},{"api_id":2420,"api_slotitem_id":22,"api_locked":0,"api_level":0,"api_alv":7},null],"poi_slot_ex":null},{"api_id":3574,"api_sortno":157,"api_ship_id":157,"api_lv":75,"api_exp":[325202,5798,51],"api_nowhp":50,"api_maxhp":50,"api_soku":10,"api_leng":1,"api_onslot":[13,19,5,3,0],"api_kyouka":[13,0,8,21,0,0,0],"api_backs":6,"api_fuel":9,"api_bull":16,"api_slotnum":4,"api_ndock_time":0,"api_ndock_item":[0,0],"api_srate":2,"api_cond":51,"api_karyoku":[13,40],"api_raisou":[0,0],"api_taiku":[74,48],"api_soukou":[49,62],"api_kaihi":[65,69],"api_taisen":[0,0],"api_sakuteki":[71,79],"api_lucky":[15,59],"api_locked":1,"api_locked_equip":0,"api_sally_area":2,"poi_slot":[{"api_id":10946,"api_slotitem_id":22,"api_locked":0,"api_level":0,"api_alv":7},{"api_id":2688,"api_slotitem_id":157,"api_locked":0,"api_level":1,"api_alv":7},{"api_id":10973,"api_slotitem_id":22,"api_locked":0,"api_level":0,"api_alv":7},{"api_id":2288,"api_slotitem_id":22,"api_locked":0,"api_level":0,"api_alv":7},null],"poi_slot_ex":null},{"api_id":1461,"api_sortno":148,"api_ship_id":148,"api_lv":77,"api_exp":[349663,6537,48],"api_nowhp":84,"api_maxhp":97,"api_soku":5,"api_leng":4,"api_onslot":[7,7,7,7,0],"api_kyouka":[47,0,39,27,0,0,0],"api_backs":7,"api_fuel":50,"api_bull":104,"api_slotnum":4,"api_ndock_time":13420000,"api_ndock_item":[104,195],"api_srate":4,"api_cond":100,"api_karyoku":[199,139],"api_raisou":[0,0],"api_taiku":[110,99],"api_soukou":[119,119],"api_kaihi":[55,63],"api_taisen":[2,0],"api_sakuteki":[40,40],"api_lucky":[9,79],"api_locked":1,"api_locked_equip":0,"api_sally_area":2,"poi_slot":[{"api_id":10986,"api_slotitem_id":9,"api_locked":0,"api_level":0},{"api_id":10618,"api_slotitem_id":36,"api_locked":0,"api_level":0},{"api_id":5714,"api_slotitem_id":9,"api_locked":0,"api_level":0},{"api_id":11709,"api_slotitem_id":25,"api_locked":0,"api_level":0,"api_alv":7},null],"poi_slot_ex":null},{"api_id":873,"api_sortno":341,"api_ship_id":541,"api_lv":88,"api_exp":[522820,4180,76],"api_nowhp":82,"api_maxhp":91,"api_soku":5,"api_leng":3,"api_onslot":[3,3,6,3,0],"api_kyouka":[27,0,60,22,0,0,0],"api_backs":8,"api_fuel":38,"api_bull":72,"api_slotnum":4,"api_ndock_time":10290000,"api_ndock_item":[51,97],"api_srate":4,"api_cond":90,"api_karyoku":[170,118],"api_raisou":[0,0],"api_taiku":[107,100],"api_soukou":[110,110],"api_kaihi":[65,70],"api_taisen":[2,0],"api_sakuteki":[55,55],"api_lucky":[40,108],"api_locked":1,"api_locked_equip":0,"api_sally_area":2,"poi_slot":[{"api_id":8572,"api_slotitem_id":245,"api_locked":0,"api_level":0},{"api_id":12522,"api_slotitem_id":105,"api_locked":0,"api_level":0},{"api_id":8918,"api_slotitem_id":25,"api_locked":0,"api_level":0,"api_alv":7},{"api_id":10840,"api_slotitem_id":116,"api_locked":0,"api_level":0},null],"poi_slot_ex":null},{"api_id":77,"api_sortno":149,"api_ship_id":149,"api_lv":122,"api_exp":[1329754,42246,1],"api_nowhp":76,"api_maxhp":90,"api_soku":10,"api_leng":4,"api_onslot":[3,3,3,3,0],"api_kyouka":[22,0,54,24,3,0,0],"api_backs":7,"api_fuel":20,"api_bull":40,"api_slotnum":4,"api_ndock_time":15990000,"api_ndock_item":[44,84],"api_srate":4,"api_cond":51,"api_karyoku":[153,98],"api_raisou":[0,0],"api_taiku":[94,84],"api_soukou":[94,94],"api_kaihi":[80,72],"api_taisen":[7,0],"api_sakuteki":[62,49],"api_lucky":[18,79],"api_locked":1,"api_locked_equip":0,"api_sally_area":2,"poi_slot":[{"api_id":2318,"api_slotitem_id":9,"api_locked":0,"api_level":0},{"api_id":8610,"api_slotitem_id":8,"api_locked":0,"api_level":0},{"api_id":10203,"api_slotitem_id":238,"api_locked":0,"api_level":0,"api_alv":7},{"api_id":942,"api_slotitem_id":36,"api_locked":0,"api_level":6},null],"poi_slot_ex":null}],"escort":[{"api_id":5620,"api_sortno":138,"api_ship_id":138,"api_lv":12,"api_exp":[7747,53,95],"api_nowhp":30,"api_maxhp":30,"api_soku":10,"api_leng":2,"api_onslot":[2,2,2,0,0],"api_kyouka":[7,14,16,11,0,0,0],"api_backs":5,"api_fuel":8,"api_bull":12,"api_slotnum":3,"api_ndock_time":0,"api_ndock_item":[0,0],"api_srate":1,"api_cond":89,"api_karyoku":[39,42],"api_raisou":[38,72],"api_taiku":[40,60],"api_soukou":[28,32],"api_kaihi":[41,72],"api_taisen":[30,70],"api_sakuteki":[16,45],"api_lucky":[10,49],"api_locked":1,"api_locked_equip":0,"api_sally_area":2,"poi_slot":[{"api_id":8137,"api_slotitem_id":65,"api_locked":0,"api_level":0},{"api_id":947,"api_slotitem_id":5,"api_locked":0,"api_level":0},{"api_id":8003,"api_slotitem_id":101,"api_locked":0,"api_level":0},null,null],"poi_slot_ex":null},{"api_id":6989,"api_sortno":1426,"api_ship_id":346,"api_lv":95,"api_exp":[668157,33343,16],"api_nowhp":33,"api_maxhp":37,"api_soku":10,"api_leng":1,"api_onslot":[0,0,0,0,0],"api_kyouka":[34,31,34,36,0,0,0],"api_backs":7,"api_fuel":5,"api_bull":8,"api_slotnum":3,"api_ndock_time":2490000,"api_ndock_item":[2,4],"api_srate":4,"api_cond":100,"api_karyoku":[64,58],"api_raisou":[56,56],"api_taiku":[138,114],"api_soukou":[52,52],"api_kaihi":[88,87],"api_taisen":[70,72],"api_sakuteki":[51,49],"api_lucky":[11,59],"api_locked":1,"api_locked_equip":0,"api_sally_area":2,"poi_slot":[{"api_id":10393,"api_slotitem_id":122,"api_locked":0,"api_level":2},{"api_id":10770,"api_slotitem_id":122,"api_locked":0,"api_level":0},{"api_id":5144,"api_slotitem_id":106,"api_locked":0,"api_level":0},null,null],"poi_slot_ex":null},{"api_id":258,"api_sortno":115,"api_ship_id":119,"api_lv":99,"api_exp":[1000000,0,0],"api_nowhp":43,"api_maxhp":43,"api_soku":10,"api_leng":2,"api_onslot":[0,0,0,0,0],"api_kyouka":[46,49,34,40,0,0,0],"api_backs":7,"api_fuel":6,"api_bull":24,"api_slotnum":3,"api_ndock_time":0,"api_ndock_item":[0,0],"api_srate":4,"api_cond":61,"api_karyoku":[80,63],"api_raisou":[151,139],"api_taiku":[55,49],"api_soukou":[63,63],"api_kaihi":[83,83],"api_taisen":[79,79],"api_sakuteki":[43,43],"api_lucky":[30,79],"api_locked":1,"api_locked_equip":0,"api_sally_area":2,"poi_slot":[{"api_id":530,"api_slotitem_id":41,"api_locked":0,"api_level":0},{"api_id":10924,"api_slotitem_id":6,"api_locked":0,"api_level":0},{"api_id":3387,"api_slotitem_id":90,"api_locked":0,"api_level":0},null,null],"poi_slot_ex":null},{"api_id":307,"api_sortno":151,"api_ship_id":151,"api_lv":142,"api_exp":[3058113,103887,26],"api_nowhp":76,"api_maxhp":89,"api_soku":10,"api_leng":4,"api_onslot":[3,3,3,3,0],"api_kyouka":[21,0,51,23,7,0,0],"api_backs":7,"api_fuel":20,"api_bull":40,"api_slotnum":4,"api_ndock_time":16995000,"api_ndock_item":[41,78],"api_srate":4,"api_cond":71,"api_karyoku":[149,96],"api_raisou":[0,0],"api_taiku":[104,92],"api_soukou":[100,93],"api_kaihi":[88,74],"api_taisen":[4,0],"api_sakuteki":[68,49],"api_lucky":[48,89],"api_locked":1,"api_locked_equip":0,"api_sally_area":2,"poi_slot":[{"api_id":791,"api_slotitem_id":103,"api_locked":0,"api_level":10},{"api_id":10902,"api_slotitem_id":116,"api_locked":0,"api_level":0},{"api_id":1793,"api_slotitem_id":9,"api_locked":0,"api_level":0},{"api_id":2465,"api_slotitem_id":59,"api_locked":0,"api_level":0,"api_alv":7},null],"poi_slot_ex":{"api_id":920,"api_slotitem_id":136,"api_locked":0,"api_level":0}},{"api_id":22,"api_sortno":194,"api_ship_id":194,"api_lv":88,"api_exp":[520294,6706,62],"api_nowhp":46,"api_maxhp":57,"api_soku":10,"api_leng":2,"api_onslot":[2,2,4,4,0],"api_kyouka":[32,50,48,30,0,0,0],"api_backs":5,"api_fuel":11,"api_bull":24,"api_slotnum":4,"api_ndock_time":9435000,"api_ndock_item":[15,29],"api_srate":4,"api_cond":51,"api_karyoku":[100,84],"api_raisou":[84,84],"api_taiku":[83,72],"api_soukou":[77,77],"api_kaihi":[79,84],"api_taisen":[1,0],"api_sakuteki":[56,58],"api_lucky":[19,70],"api_locked":1,"api_locked_equip":0,"api_sally_area":2,"poi_slot":[{"api_id":6988,"api_slotitem_id":6,"api_locked":0,"api_level":0},{"api_id":6978,"api_slotitem_id":6,"api_locked":0,"api_level":0},{"api_id":6998,"api_slotitem_id":35,"api_locked":0,"api_level":0},{"api_id":7394,"api_slotitem_id":102,"api_locked":0,"api_level":0,"api_alv":7},null],"poi_slot_ex":null},{"api_id":208,"api_sortno":1328,"api_ship_id":228,"api_lv":80,"api_exp":[395969,1031,92],"api_nowhp":30,"api_maxhp":32,"api_soku":10,"api_leng":1,"api_onslot":[0,0,0,0,0],"api_kyouka":[47,61,43,45,0,0,0],"api_backs":6,"api_fuel":3,"api_bull":6,"api_slotnum":3,"api_ndock_time":1090000,"api_ndock_item":[0,1],"api_srate":4,"api_cond":61,"api_karyoku":[59,59],"api_raisou":[123,89],"api_taiku":[59,59],"api_soukou":[59,59],"api_kaihi":[92,99],"api_taisen":[52,59],"api_sakuteki":[33,39],"api_lucky":[60,99],"api_locked":1,"api_locked_equip":0,"api_sally_area":2,"poi_slot":[{"api_id":1405,"api_slotitem_id":58,"api_locked":0,"api_level":0},{"api_id":1030,"api_slotitem_id":58,"api_locked":0,"api_level":0},{"api_id":1707,"api_slotitem_id":15,"api_locked":0,"api_level":7},null,null],"poi_slot_ex":null}],"support":null,"LBAC":[{"api_area_id":41,"api_rid":1,"api_name":"第一基地航空隊","api_distance":6,"api_action_kind":1,"api_plane_info":[{"api_squadron_id":1,"api_state":1,"api_count":18,"api_max_count":18,"api_cond":1,"poi_slot":{"api_id":11008,"api_slotitem_id":180,"api_locked":0,"api_level":0,"api_alv":6}},{"api_squadron_id":2,"api_state":1,"api_count":18,"api_max_count":18,"api_cond":1,"poi_slot":{"api_id":8596,"api_slotitem_id":169,"api_locked":0,"api_level":0,"api_alv":5}},{"api_squadron_id":3,"api_state":1,"api_count":18,"api_max_count":18,"api_cond":1,"poi_slot":{"api_id":12391,"api_slotitem_id":96,"api_locked":0,"api_level":0,"api_alv":7}},{"api_squadron_id":4,"api_state":1,"api_count":18,"api_max_count":18,"api_cond":1,"poi_slot":{"api_id":8125,"api_slotitem_id":221,"api_locked":0,"api_level":1,"api_alv":7}}]},{"api_area_id":41,"api_rid":2,"api_name":"第二基地航空隊","api_distance":6,"api_action_kind":1,"api_plane_info":[{"api_squadron_id":1,"api_state":1,"api_count":18,"api_max_count":18,"api_cond":1,"poi_slot":{"api_id":6018,"api_slotitem_id":18,"api_locked":0,"api_level":0,"api_alv":7}},{"api_squadron_id":2,"api_state":1,"api_count":18,"api_max_count":18,"api_cond":1,"poi_slot":{"api_id":8172,"api_slotitem_id":18,"api_locked":0,"api_level":0,"api_alv":7}},{"api_squadron_id":3,"api_state":1,"api_count":18,"api_max_count":18,"api_cond":1,"poi_slot":{"api_id":10939,"api_slotitem_id":18,"api_locked":0,"api_level":0,"api_alv":7}},{"api_squadron_id":4,"api_state":1,"api_count":18,"api_max_count":18,"api_cond":1,"poi_slot":{"api_id":731,"api_slotitem_id":18,"api_locked":0,"api_level":0,"api_alv":7}}]}]},"packet":[{"api_deck_id":1,"api_formation":[14,14,1],"api_f_nowhps":[57,46,50,84,82,76],"api_f_maxhps":[57,50,50,97,91,90],"api_f_nowhps_combined":[30,33,43,76,46,30],"api_f_maxhps_combined":[30,37,43,89,57,32],"api_fParam":[[64,66,91,78],[29,0,69,59],[13,0,32,49],[139,0,99,119],[118,0,100,110],[98,0,84,94]],"api_fParam_combined":[[27,38,33,28],[58,56,114,52],[63,139,49,63],[96,0,92,93],[84,84,72,77],[59,89,59,59]],"api_ship_ke":[1784,1558,1558,1558,1529,1529],"api_ship_lv":[1,1,1,1,1,1],"api_ship_ke_combined":[1594,1594,1576,1576,1501,1501],"api_ship_lv_combined":[1,1,1,1,1,1],"api_e_nowhps":[650,130,130,130,98,98],"api_e_maxhps":[650,130,130,130,98,98],"api_e_nowhps_combined":[80,80,37,37,20,20],"api_e_maxhps_combined":[80,80,37,37,20,20],"api_eSlot":[[581,582,583,580,-1],[506,504,504,-1,-1],[506,504,504,-1,-1],[506,504,504,-1,-1],[509,509,525,528,-1],[509,509,525,528,-1]],"api_eSlot_combined":[[505,505,515,525,-1],[505,505,515,525,-1],[502,545,542,-1,-1],[502,545,542,-1,-1],[501,-1,-1,-1,-1],[501,-1,-1,-1,-1]],"api_eParam":[[124,130,108,198],[55,0,40,65],[55,0,40,65],[55,0,40,65],[90,0,80,99],[90,0,80,99]],"api_eParam_combined":[[73,66,72,82],[73,66,72,82],[38,66,32,26],[38,66,32,26],[5,15,6,5],[5,15,6,5]],"api_midnight_flag":1,"api_search":[1,1],"api_air_base_attack":[{"api_base_id":2,"api_stage_flag":[1,1,1],"api_plane_from":[null,[1,5,6,7,8]],"api_squadron_plane":[{"api_mst_id":18,"api_count":18},{"api_mst_id":18,"api_count":18},{"api_mst_id":18,"api_count":18},{"api_mst_id":18,"api_count":18}],"api_stage1":{"api_f_count":72,"api_f_lostcount":34,"api_e_count":130,"api_e_lostcount":5,"api_disp_seiku":4,"api_touch_plane":[-1,583]},"api_stage2":{"api_f_count":38,"api_f_lostcount":3,"api_e_count":0,"api_e_lostcount":0},"api_stage3":{"api_erai_flag":[0,0,1,0,0,0],"api_ebak_flag":[0,0,0,0,0,0],"api_ecl_flag":[0,0,0,0,0,0],"api_edam":[0,0,9,0,0,0]},"api_stage3_combined":{"api_erai_flag":[0,0,1,1,0,0],"api_ebak_flag":[0,0,0,0,0,0],"api_ecl_flag":[0,0,0,1,0,0],"api_edam":[0,0,44,94,0,0]}},{"api_base_id":2,"api_stage_flag":[1,1,1],"api_plane_from":[null,[1,5,6,7,8]],"api_squadron_plane":[{"api_mst_id":18,"api_count":18},{"api_mst_id":18,"api_count":18},{"api_mst_id":18,"api_count":18},{"api_mst_id":18,"api_count":18}],"api_stage1":{"api_f_count":72,"api_f_lostcount":26,"api_e_count":125,"api_e_lostcount":2,"api_disp_seiku":4,"api_touch_plane":[-1,525]},"api_stage2":{"api_f_count":46,"api_f_lostcount":4,"api_e_count":0,"api_e_lostcount":0},"api_stage3":{"api_erai_flag":[0,0,0,1,0,0],"api_ebak_flag":[0,0,0,0,0,0],"api_ecl_flag":[0,0,0,0,0,0],"api_edam":[0,0,0,11,0,0]},"api_stage3_combined":{"api_erai_flag":[0,0,0,0,0,1],"api_ebak_flag":[0,0,0,0,0,0],"api_ecl_flag":[0,0,0,0,0,0],"api_edam":[0,0,0,0,0,206]}}],"api_stage_flag":[1,1,0],"api_kouku":{"api_plane_from":[[2,3],[1]],"api_stage1":{"api_f_count":91,"api_f_lostcount":0,"api_e_count":105,"api_e_lostcount":66,"api_disp_seiku":1,"api_touch_plane":[238,-1]},"api_stage2":{"api_f_count":0,"api_f_lostcount":0,"api_e_count":31,"api_e_lostcount":31,"api_air_fire":{"api_idx":0,"api_kind":10,"api_use_items":[135,131,106]}},"api_stage3":null,"api_stage3_combined":null},"api_support_flag":0,"api_support_info":null,"api_opening_taisen_flag":0,"api_opening_taisen":null,"api_opening_flag":1,"api_opening_atack":{"api_frai":[-1,-1,-1,-1,-1,-1,-1,-1,4,-1,-1,-1],"api_fcl":[0,0,0,0,0,0,0,0,2,0,0,0],"api_fdam":[0,0,0,0,0,0,0,0,0,0,0,0],"api_fydam":[0,0,0,0,0,0,0,0,87,0,0,0],"api_erai":[-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1],"api_ecl":[0,0,0,0,0,0,0,0,0,0,0,0],"api_edam":[0,0,0,0,87,0,0,0,0,0,0,0],"api_eydam":[0,0,0,0,0,0,0,0,0,0,0,0]},"api_hourai_flag":[1,1,1,1],"api_hougeki1":{"api_at_eflag":[0,0,1,0,1,0,1],"api_at_list":[3,5,5,4,1,0,2],"api_at_type":[6,6,0,2,0,0,0],"api_df_list":[[4],[3],[4],[0,0],[1],[5],[4]],"api_si_list":[["25","9","9"],["238","9","8"],[509],["245","105"],[506],[135],[506]],"api_cl_list":[[1],[1],[0],[1,1],[1],[1],[1]],"api_damage":[[147],[143],[0],[46,54],[33],[8],[6]]},"api_hougeki2":{"api_at_eflag":[0,1,0,1,0,0],"api_at_list":[0,1,3,2,4,5],"api_at_type":[0,0,6,0,6,2],"api_df_list":[[5],[3],[5],[8],[10],[2,2]],"api_si_list":[[135],[506],["25","9","9"],[506],["25","245","105"],["9","8"]],"api_cl_list":[[1],[0],[1],[0],[1],[1,1]],"api_damage":[[6],[0],[145.1],[0],[198],[126,105]]},"api_hougeki3":{"api_at_eflag":[0,1,0,0,0,0,0],"api_at_list":[9,6,6,10,8,7,11],"api_at_type":[2,0,0,0,0,0,0],"api_df_list":[[7,7],[6],[6],[6],[6],[6],[6]],"api_si_list":[["103","9"],[505],[65],[6],[6],[122],[-1]],"api_cl_list":[[1,1],[0],[1],[1],[1],[1],[1]],"api_damage":[[97,116],[0],[5],[40],[4],[2],[5]]},"api_raigeki":{"api_frai":[-1,-1,-1,-1,-1,-1,1,6,6,-1,1,1],"api_fcl":[0,0,0,0,0,0,0,1,1,0,1,1],"api_fdam":[0,0,0,0,0,0,0,0,0,0,0,0],"api_fydam":[0,0,0,0,0,0,0,2,54,0,31,65],"api_erai":[-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1],"api_ecl":[0,0,0,0,0,0,0,0,0,0,0,0],"api_edam":[0,96,0,0,0,0,56,0,0,0,0,0],"api_eydam":[0,0,0,0,0,0,0,0,0,0,0,0]},"poi_path":"/kcsapi/api_req_combined_battle/each_battle_water","poi_time":1519270890123},{"api_deck_id":1,"api_formation":[14,14,1],"api_f_nowhps":[57,13,50,84,76,76],"api_f_maxhps":[57,50,50,97,91,90],"api_f_nowhps_combined":[30,33,43,76,46,30],"api_f_maxhps_combined":[30,37,43,89,57,32],"api_fParam":[[64,66,91,78],[29,0,69,59],[13,0,32,49],[139,0,99,119],[118,0,100,110],[98,0,84,94]],"api_fParam_combined":[[27,38,33,28],[58,56,114,52],[63,139,49,63],[96,0,92,93],[84,84,72,77],[59,89,59,59]],"api_ship_ke":[1784,1558,1558,1558,1529,1529],"api_ship_lv":[1,1,1,1,1,1],"api_ship_ke_combined":[1594,1594,1576,1576,1501,1501],"api_ship_lv_combined":[1,1,1,1,1,1],"api_e_nowhps":[369,0,0,0,0,0],"api_e_maxhps":[650,130,130,130,98,98],"api_e_nowhps_combined":[0,0,0,0,0,0],"api_e_maxhps_combined":[80,80,37,37,20,20],"api_eSlot":[[581,582,583,580,-1],[506,504,504,-1,-1],[506,504,504,-1,-1],[506,504,504,-1,-1],[509,509,525,528,-1],[509,509,525,528,-1]],"api_eSlot_combined":[[505,505,515,525,-1],[505,505,515,525,-1],[502,545,542,-1,-1],[502,545,542,-1,-1],[501,-1,-1,-1,-1],[501,-1,-1,-1,-1]],"api_eParam":[[124,130,108,198],[55,0,40,65],[55,0,40,65],[55,0,40,65],[90,0,80,99],[90,0,80,99]],"api_eParam_combined":[[73,66,72,82],[73,66,72,82],[38,66,32,26],[38,66,32,26],[5,15,6,5],[5,15,6,5]],"api_friendly_info":{"api_production_type":1,"api_ship_id":[364,393,392,519],"api_ship_lv":[86,85,62,40],"api_nowhps":[82,71,89,15],"api_maxhps":[82,71,89,15],"api_Slot":[[190,190,190,191,-1],[244,243,242,242,-1],[245,245,247,-1,-1],[280,280,260,-1,-1]],"api_Param":[[93,0,66,84],[35,0,52,43],[85,0,41,88],[32,65,43,18]],"api_voice_id":[141,15,15,15],"api_voice_p_no":[1,0,0,0]},"api_friendly_battle":{"api_flare_pos":[-1,-1],"api_hougeki":{"api_at_eflag":[0,0,0,0],"api_at_list":[0,1,2,3],"api_n_mother_list":[0,0,0,0],"api_df_list":[[1,-1,-1],[0],[0],[0,0]],"api_si_list":[[190,190,190],[-1],[245],[280,280]],"api_cl_list":[[1,-1,-1],[0],[1],[1,1]],"api_sp_list":[5,0,0,1],"api_damage":[[243,-1,-1],[0],[70],[53,58]]}},"api_active_deck":[2,1],"api_touch_plane":[-1,-1],"api_flare_pos":[-1,-1],"api_hougeki":{"api_at_eflag":[0,0,0,0,0,0],"api_at_list":[6,7,8,9,10,11],"api_n_mother_list":[0,0,0,0,0,0],"api_df_list":[[0,0],[0,0],[0,0],[0,0],[0,0],[0,0]],"api_si_list":[["65","5"],["122","122"],["6","90"],["103","9"],["6","6"],["58","58"]],"api_cl_list":[[1,1],[1,1],[1,2],[1,1],[1,1],[1,1]],"api_sp_list":[1,1,1,1,1,3],"api_damage":[[40,30],[23,1],[37,156],[7,10],[54,4],[0,45]]},"poi_path":"/kcsapi/api_req_combined_battle/ec_midnight_battle","poi_time":1519271016843},{"api_ship_id":[1784,1558,1558,1558,1529,1529],"api_win_rank":"S","api_get_exp":350,"api_mvp":6,"api_mvp_combined":3,"api_member_lv":104,"api_member_exp":2825099,"api_get_base_exp":400,"api_get_ship_exp":[-1,720,480,480,480,480,960],"api_get_ship_exp_combined":[-1,720,480,960,480,480,480],"api_get_exp_lvup":[[330745,331000,343400],[362349,369400],[325202,331000],[349663,356200],[522820,527000],[1329754,1372000]],"api_get_exp_lvup_combined":[[7747,7800,9100],[668157,701500],[1000000],[3058113,3162000],[520294,527000],[395969,397000]],"api_dests":12,"api_destsf":1,"api_quest_name":"サマール沖/レイテ湾","api_quest_level":13,"api_enemy_info":{"api_level":"","api_rank":"","api_deck_name":"深海レイテ侵攻 主力輸送船団"},"api_first_clear":0,"api_get_flag":[0,1,0],"api_get_ship":{"api_ship_id":552,"api_ship_type":"海防艦","api_ship_name":"大東","api_ship_getmes":"日振型海防艦、その二番艦、大東さ！<br>ちゃっくにーん！　あんたが提督かー。へへ、いいね！<br>あたいもよろしくなー！　さ、いってみよー！"},"api_get_exmap_rate":0,"api_get_exmap_useitem_id":0,"api_escape_flag":0,"api_escape":null,"poi_path":"/kcsapi/api_req_combined_battle/battleresult","poi_time":1519271091618}]}

**Comment by KagamiChan** [comment]
![image](https://user-images.githubusercontent.com/3816900/36551837-7b6d8cc8-1833-11e8-9220-2f48f0f4ca08.png)
在我本地是这个结果

有可能是你当时的未卜先知没有更新

战斗详情的需要再等一段时间才能支持

**Comment by Ziziru** [comment]
那可能是当时卡住了吧，后几次进boss点来支援后显示都是正常的，那应该没什么问题了
