### ISSUE TITLE
poi64位元用不到 只能轉用32

### ISSUE THREAD

**Issue by kazepoi** [poooi/poi#1746]
poi-8.2.0-beta.3 
**poi 版本 / poi version:**
**操作系统 / OS:**
win8.1
-->
系統是64位元,從2年前一直就在用64位元,然後1年前開64位元一直沒反應 很多地方都沒有解決辦法
安裝完64後點開之後工作管理員會多了POI.exe運行,正常是在應用程式, 現在是會在背景運行
轉用32位元正常
但想真正解決他
找到版上有使用electron開啟的辦法 但使用後出現這樣 全黑甚麼都沒  如果不用electron的話開POI是甚麼都沒出現就是 只有在背景運行多出一個POI.exe 
 
![default](https://user-images.githubusercontent.com/36750025/36573015-1b07135a-1882-11e8-91af-61eb24fd8cad.JPG)

**Comment by KochiyaOcean** [comment]
win+r 输出 cmd 回车，把 poi.exe 拖进去回车看有什么信息
