### ISSUE TITLE
联合舰队贴条提示有误

### ISSUE THREAD

**Issue by Shimushushushu** [poooi/poi#1749]
**poi 版本 / poi version:**
8.2.0-beta3

**操作系统 / OS:**
Windows10,64bit,16299.248

**插件名和版本 / Plugin name & version:**
N/A

**你遇到了什么样的问题 / The problem you've met:**
E2联合舰队出击时显示至少有一艘没贴条,实际上一二队全部贴了条.

**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:**
点进活动图,点决定,跳出没贴条,如果不回母港再点不会再次弹出,但是回母港后再点进去会重新提示.

**Comment by KochiyaOcean** [comment]
@Shimushushushu 受 API 限制，所有空闲舰队中有未贴条的就会通知
