### ISSUE TITLE
Poi在平板上无法正常使用

### ISSUE THREAD

**Issue by UNSCONI** [poooi/poi#1750]
**poi 版本 / poi version
8.2.0-beta 3
**操作系统 / OS:**

win10 ver1703

**你遇到了什么样的问题 / The problem you've met:**
只要打开poi就没有下半的UI部分，无法进行代理修改，面板设置，各项操作，poi处于无法使用的状态

![capture](https://user-images.githubusercontent.com/36778356/36621690-330583a2-18ae-11e8-8599-b9142f2b0467.PNG)

**Comment by KagamiChan** [comment]
见 #1740

**Comment by UNSCONI** [comment]
1740号case的解决方案无法适用于此情况因为我根本无法调出poi的设置选项

**Comment by KagamiChan** [comment]
请调整窗口尺寸

**Comment by KagamiChan** [comment]
我想我大概明白你的问题所在了……在小分辨率横向显示的情况下，没有办法靠缩小高度来缩小游戏区域的宽度，也不能够再增加横向高度来调出界面部分

呼唤界面之神 @KochiyaOcean

**Comment by KagamiChan** [comment]
像这种一上来非最大化且已经填满了整个屏幕的情况，需要有一些方法来拯救

我觉得要不要菜单里面加一个固定分辨率之类的项目

**Comment by KochiyaOcean** [comment]
@KagamiChan 允许增加超过屏幕的宽度的，把窗口一半拉到屏幕外面去然后再拉大就行

**Comment by KagamiChan** [comment]
嗯也可以，那就这样操作吧
