### ISSUE TITLE
长期老板键切换导致画面冻结问题

### ISSUE THREAD

**Issue by d956381604** [poooi/poi#1751]
**poi 版本 / poi version:**
8.2.0 beta3

**操作系统 / OS:**
win8.1 9600

**你遇到了什么样的问题 / The problem you've met:**
长期老板键切换显示会导致flash显示区域冻结，但是flash还在运行，有声音，并且可以进行操作（鼠标会有可点击提示并且能点击）。刚打完一场蒙眼E4...
通过刷新可以解决。(但这样就没法打活动了)
好像最小化放置几分钟也会好
这个问题好像8.1.0以前均没有。

**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:**
额，长按ctrl+p多切换几次[闪屏警告]应该就可以在重现吧，至少我的电脑可以。

**Comment by KagamiChan** [comment]
请试试 8.3.0-beta.1 是否还存在类似问题

**Comment by KochiyaOcean** [comment]
https://ci.appveyor.com/project/KochiyaOcean/poi/build/1.0.2594/artifacts 试试看这个版本还有什么问题么
<del>通过本人的脸滚老板键测试似乎是已经修复了</del>

**Comment by d956381604** [comment]
额，这个看不懂怎么用...

**Comment by KochiyaOcean** [comment]
刚刚 build 完，刷新一下点下面那个 exe 文件就能下载安装包了

**Comment by d956381604** [comment]
几乎是完全好了，偶尔会冻结但是再按两下老板键就恢复了，目前看来不影响正常使用的样子，谢谢dalao！
