### ISSUE TITLE
切换编辑面板开关时 通知重复出现

### ISSUE THREAD

**Issue by tkmikan** [poooi/poi#1752]
**poi 版本 / poi version:**
8.2.0 beta.3

**操作系统 / OS:**
win10 1709 16299.248

~~**插件名和版本 / Plugin name & version:**~~

**你遇到了什么样的问题 / The problem you've met:**
切换`编辑面板`开关时，若有已完成但暂未收取的建造、远征等，会重复出现提醒

**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:**

> This is poi@8.2.0-beta.3 on win32 x64 with Electron@1.8.2,
        PLUGINS: poi-plugin-prophet@7.1.1, poi-plugin-exp-calc@4.1.0, poi-plugin-quest-info@5.0.0, poi-plugin-ezexped@1.6.0, poi-plugin-hensei-nikki@4.0.3, poi-plugin-map-hp@4.0.1, poi-plugin-anchorage-repair@0.6.1, poi-plugin-akashic-records@6.2.3, poi-plugin-leveling@1.2.3, poi-plugin-battle-detail@3.10.0, poi-plugin-wheres-my-fuel-gone@0.6.4, poi-plugin-item-improvement@6.0.1, poi-plugin-ship-info@5.0.4, poi-plugin-item-info@3.1.0, poi-plugin-kcwiki-report@3.0.21, poi-plugin-subtitle@1.2.9,
        FCD: map@2018/02/21/01, maphp@2016/08/20/01, shipavatar@2018/02/21/01, shiptag@2018/02/23/01

**Comment by KochiyaOcean** [comment]
因为编辑时面版会重载，根据通知机制会重新通知
