### ISSUE TITLE
poi一直遭到貓襲

### ISSUE THREAD

**Issue by Limoncool** [poooi/poi#1753]
**poi 版本 / poi version:**
8.1.0

**操作系统 / OS:**

win10 版本1709

**插件名和版本 / Plugin name & version:**

**你遇到了什么样的问题 / The problem you've met:**
poi瀏覽器一直遭到貓襲
貓襲時間點在遊戲載入完成之後進入game start按鈕畫面時
不管有沒有按下game start鈕都會遭到貓襲
但直接使用chrome網路瀏覽器拜訪艦娘網頁可正常執行遊戲
已知使用poi清除緩存與cookies的功能後仍無法排除問題
已知重新校正作業系統時間後仍無法排除問題
已知重新連結網路後仍無法排除問題
已知刪除poi並重新安裝後仍無法排除問題
已知電腦重新開機後再開啟poi瀏覽器仍無法排除問題
已知同時使用8.1.0安裝版與8.2beta免安裝版 兩版本都會遇到相同問題

**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:**

**Comment by KagamiChan** [comment]
请尝试完全移除 %appdata%/poi/cache 资料夹看看，方法是按 win + r，输入 %appdata%/poi 并确认，之后删除 cache 资料夹

**Comment by Limoncool** [comment]
刪除cache資料夾後問題仍存在

**Comment by KochiyaOcean** [comment]
@Limoncool 上述的整个 poi 文件夹改名看看

**Comment by Limoncool** [comment]
問題仍存在

**Comment by KochiyaOcean** [comment]
@Limoncool 连接游戏是靠什么方法

**Comment by Limoncool** [comment]
烤餅乾直連

**Comment by KagamiChan** [comment]
会不会和 #1556 类似，请求时间过长导致 poi 内置的代理模块超时呀

**Comment by Limoncool** [comment]
目前的作法是 將poi解除安裝後把 %appdata%/poi 整個刪除後重新安裝poi
如果仍然無法的話再參考 #1556

**Comment by Limoncool** [comment]
按照#1556的方式打開開發者工具 可是看不到東西

**Comment by KagamiChan** [comment]
@Limoncool 需要右击开发者工具的按钮，打开游戏网页的开发者工具，然后刷新进入游戏。不应该在 network 里面看不到内容的

**Comment by Limoncool** [comment]
如圖
![image](https://user-images.githubusercontent.com/14809302/36713808-531c84b4-1bca-11e8-9c2a-129a960fdaf5.png)

**Comment by KagamiChan** [comment]
mainD2.swf 的地址会暴露你的敏感信息，截图的时候检查一下自己打个码或者隐藏起来，姑且帮你删了，但是你重新再登录一下帐号吧

你点击 game start，看看这个窗体出什么内容

**Comment by Limoncool** [comment]
好的 謝謝
但我是連game start都還沒按就貓了
是要我用chrome登出dmm再重新登入的意思嗎

**Comment by KagamiChan** [comment]
@Limoncool 是的，稳妥起见吧
然后你的主页是自己又重新设置过了吗，因为一般情况下的请求内容不会这么少的

**Comment by Limoncool** [comment]
因為我還沒按game start就貓了
剛剛照做之後仍然無法解決
但我剛剛幫電腦的防毒軟體更新之後poi就好了
所以我在想有沒有可能是防毒軟體的設定問題呢
需要給防毒軟體的資訊嗎

**Comment by KochiyaOcean** [comment]
@Limoncool 那可能是被误杀了……

**Comment by Limoncool** [comment]
我的情況說一下好了
我的防毒軟體過了授權期限時
poi就會貓
剛剛更新防毒授權之後poi就正常了

**Comment by KochiyaOcean** [comment]
可以说是宇宙未解之谜了……

**Comment by KochiyaOcean** [comment]
总之姑且算是解决了
