### ISSUE TITLE
在windows显示设置里使用125%缩放时，游戏窗口也被缩放了125%

### ISSUE THREAD

**Issue by fgvg500** [poooi/poi#1754]
**poi 版本 / poi version:V8.2.0-beta.3**

**操作系统 / OS:windows10 1709 **

**插件名和版本 / Plugin name & version:**

**你遇到了什么样的问题 / The problem you've met:**

**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:在windows 显示设置里选用了125%的缩放时，使用poi时游戏窗口800X480的大小貌似也被放大了（游戏窗口有1000x600了）
![image](https://user-images.githubusercontent.com/36877756/36716207-6a062e46-1bd4-11e8-8ff5-b06474dfd2d9.png)
**

**Comment by KochiyaOcean** [comment]
属于预想内结果，请自行调整分辨率至 640px
