### ISSUE TITLE
白船一直跑卻進不去...

### ISSUE THREAD

**Issue by LikuElist** [poooi/poi#1755]
您好,以下是我打開 POI 後發現的問題想請求協助

無法進入遊戲,會一直在白船那跑;
之後關掉卡巴斯基後再開就能進入了,但是重新開啟後馬上貓並且又回復無法進入的問題;
從卡巴內關掉 網頁防護 這個功能後又重新能開了,並且發現是 http://ad.maist.jp 及 http://4735422.fls.doubleclick.net 被封鎖的問題才無法進入

想請教各位提督們有沒有辦法在不關掉防毒軟體的情況下讓我能夠使用 POI ??
感恩協助!!

**Comment by KagamiChan** [comment]
可以看看防毒软体有没有白名单功能，没有的话就联系他们的客户服务吧，我们这边无能为力
