### ISSUE TITLE
輸入我的帳號密碼卻連到其他玩家的帳號

### ISSUE THREAD

**Issue by Warwolf4** [poooi/poi#1756]
**v8.2.0-beta.3**

**Windows10**
<版本1709>

**輸入自己的帳號密碼，卻意外登入其他人的帳號(玩家名:KSHRoach)，我截個圖就退出了，請該玩家放心，但我不知道其他人會不會也意外登進去...**

**重開poi就正常了**

[
![2018-2-28t23 6 5](https://user-images.githubusercontent.com/36926993/36796927-a9cd280a-1ce1-11e8-88c7-3acbdeff35a8.png)
](url)

**Comment by KochiyaOcean** [comment]
@Warwolf4 你用的什么代理服务器么

**Comment by Warwolf4** [comment]
沒有用代理服務器耶

**Comment by Warwolf4** [comment]
這才是我的鎮守府[
![2018-2-28t23 55 19](https://user-images.githubusercontent.com/36926993/36797612-59f414ea-1ce3-11e8-9700-d894d81c77db.png)
](url)

**Comment by KagamiChan** [comment]
很遗憾 poi 本身不提供穿越功能，可能是田中安排的穿越

**Comment by Warwolf4** [comment]
交換身體了(X
倒是我也很怕別人登進我的帳號ㄚㄚㄚ

**Comment by KagamiChan** [comment]
@Warwolf4 还有一种可能是 ISP 那边无良地把请求内容给缓存了，不过还是 poi 这边没办法处理的事情

**Comment by Warwolf4** [comment]
總之用網頁版先改個密碼求心安
還有什麼辦法ㄇ

**Comment by KochiyaOcean** [comment]
@Warwolf4 超低概率事件，应该不会发生第二次

**Comment by Warwolf4** [comment]
我覺得這個運氣應該用在撈船上阿
怎麼變成超低機率誤闖別人家呢(汗
