### ISSUE TITLE
未卜先知 無法顯示完整的戰鬥結果

### ISSUE THREAD

**Issue by knm1993** [poooi/poi#1757]
**poi 版本 / poi version:**
8.1.0

**操作系统 / OS:**
Windows 7 Professional

**插件名和版本 / Plugin name & version:**
未卜知先 7.1.1

**你遇到了什么样的问题 / The problem you've met:**
在演習時,進入戰鬥後沒有顯示敵方血量,航空戰預測以及戰鬥評級。
![image](https://user-images.githubusercontent.com/15081337/36822636-0c5e9ab0-1d34-11e8-95c3-619ddadcf2fc.png)

**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:**
直接進入演習戰鬥就會看到了。

這是開發者工具的截圖。進行了兩次演習,兩次也是沒有航空戰,敵方陣容,血量以及戰鬥評級。
這個紅色的錯誤出現了兩次。
![image](https://user-images.githubusercontent.com/15081337/36822608-d46d59ac-1d33-11e8-93b9-39b997214551.png)

回報到這裡了,辛苦大大啦

**Comment by KagamiChan** [comment]
@knm1993 请在开发者工具里面输入 window.$ships[518]
也会报错吗？
有没有安装战斗详情扩展？扩展里面这场战斗可以显示吗？

**Comment by knm1993** [comment]
鍵入指令後出現了這段log
![image](https://user-images.githubusercontent.com/15081337/36830809-27dad1ba-1d60-11e8-8148-ba60a4378fdc.png)
另外在戰鬥紀錄裡也能正常顯示紀錄

**Comment by KagamiChan** [comment]
@knm1993 那麻烦把战斗记录里面对应的战斗的数据贴一下，就是战斗记录里面找到这个战斗，然后点击复制数据的按钮

**Comment by knm1993** [comment]
{"version":"2.1","type":"Pratice","map":[],"desc":"Lumi (Lv.97)","time":1519867076707,"fleet":{"type":0,"main":[{"api_id":2030,"api_sortno":318,"api_ship_id":518,"api_lv":32,"api_exp":[50860,1940,39],"api_nowhp":9,"api_maxhp":9,"api_soku":5,"api_leng":1,"api_onslot":[0,0,0,0,0],"api_kyouka":[14,0,16,12,0,0,0],"api_backs":4,"api_fuel":10,"api_bull":10,"api_slotnum":2,"api_ndock_time":0,"api_ndock_item":[0,0],"api_srate":4,"api_cond":68,"api_karyoku":[18,19],"api_raisou":[0,0],"api_taiku":[22,22],"api_soukou":[16,16],"api_kaihi":[54,82],"api_taisen":[61,70],"api_sakuteki":[7,14],"api_lucky":[35,78],"api_locked":1,"api_locked_equip":0,"api_sally_area":0,"poi_slot":[{"api_id":528,"api_slotitem_id":47,"api_locked":0,"api_level":0},{"api_id":656,"api_slotitem_id":45,"api_locked":0,"api_level":0},null,null,null],"poi_slot_ex":null},{"api_id":590,"api_sortno":1310,"api_ship_id":210,"api_lv":72,"api_exp":[290243,5957,44],"api_nowhp":75,"api_maxhp":75,"api_soku":10,"api_leng":3,"api_onslot":[3,3,3,3,0],"api_kyouka":[22,0,40,22,0,0,0],"api_backs":6,"api_fuel":90,"api_bull":120,"api_slotnum":4,"api_ndock_time":0,"api_ndock_item":[0,0],"api_srate":4,"api_cond":70,"api_karyoku":[129,94],"api_raisou":[0,0],"api_taiku":[81,79],"api_soukou":[89,89],"api_kaihi":[59,69],"api_taisen":[2,0],"api_sakuteki":[48,49],"api_lucky":[12,69],"api_locked":1,"api_locked_equip":0,"api_sally_area":0,"poi_slot":[{"api_id":4892,"api_slotitem_id":8,"api_locked":0,"api_level":0},{"api_id":872,"api_slotitem_id":7,"api_locked":0,"api_level":0},{"api_id":1840,"api_slotitem_id":25,"api_locked":0,"api_level":0,"api_alv":7},{"api_id":1241,"api_slotitem_id":30,"api_locked":0,"api_level":0},null],"poi_slot_ex":null},{"api_id":177,"api_sortno":1312,"api_ship_id":212,"api_lv":65,"api_exp":[221014,6986,17],"api_nowhp":69,"api_maxhp":75,"api_soku":10,"api_leng":3,"api_onslot":[3,3,3,3,0],"api_kyouka":[22,0,45,21,0,0,0],"api_backs":6,"api_fuel":90,"api_bull":120,"api_slotnum":4,"api_ndock_time":4035000,"api_ndock_item":[17,32],"api_srate":4,"api_cond":57,"api_karyoku":[129,94],"api_raisou":[0,0],"api_taiku":[86,79],"api_soukou":[88,89],"api_kaihi":[57,69],"api_taisen":[2,0],"api_sakuteki":[46,49],"api_lucky":[12,69],"api_locked":1,"api_locked_equip":0,"api_sally_area":0,"poi_slot":[{"api_id":4865,"api_slotitem_id":8,"api_locked":0,"api_level":0},{"api_id":506,"api_slotitem_id":25,"api_locked":0,"api_level":1,"api_alv":7},{"api_id":125,"api_slotitem_id":7,"api_locked":0,"api_level":0},{"api_id":1982,"api_slotitem_id":30,"api_locked":0,"api_level":0},null],"poi_slot_ex":null},{"api_id":2798,"api_sortno":339,"api_ship_id":531,"api_lv":24,"api_exp":[29031,969,59],"api_nowhp":9,"api_maxhp":9,"api_soku":5,"api_leng":1,"api_onslot":[0,0,0,0,0],"api_kyouka":[12,0,11,9,0,0,0],"api_backs":4,"api_fuel":10,"api_bull":10,"api_slotnum":2,"api_ndock_time":0,"api_ndock_item":[0,0],"api_srate":3,"api_cond":49,"api_karyoku":[16,19],"api_raisou":[0,0],"api_taiku":[18,29],"api_soukou":[13,16],"api_kaihi":[49,81],"api_taisen":[57,73],"api_sakuteki":[5,15],"api_lucky":[7,49],"api_locked":1,"api_locked_equip":0,"api_sally_area":0,"poi_slot":[{"api_id":1043,"api_slotitem_id":46,"api_locked":0,"api_level":0},{"api_id":4784,"api_slotitem_id":227,"api_locked":0,"api_level":0},null,null,null],"poi_slot_ex":null},{"api_id":2127,"api_sortno":334,"api_ship_id":524,"api_lv":28,"api_exp":[38531,2069,26],"api_nowhp":9,"api_maxhp":9,"api_soku":5,"api_leng":1,"api_onslot":[0,0,0,0,0],"api_kyouka":[14,0,15,12,0,0,0],"api_backs":4,"api_fuel":10,"api_bull":10,"api_slotnum":2,"api_ndock_time":0,"api_ndock_item":[0,0],"api_srate":4,"api_cond":49,"api_karyoku":[18,18],"api_raisou":[0,0],"api_taiku":[22,27],"api_soukou":[16,16],"api_kaihi":[52,83],"api_taisen":[61,72],"api_sakuteki":[6,14],"api_lucky":[37,78],"api_locked":1,"api_locked_equip":0,"api_sally_area":0,"poi_slot":[{"api_id":1035,"api_slotitem_id":45,"api_locked":0,"api_level":0},{"api_id":1242,"api_slotitem_id":45,"api_locked":0,"api_level":0},null,null,null],"poi_slot_ex":null},{"api_id":2086,"api_sortno":1460,"api_ship_id":380,"api_lv":72,"api_exp":[295700,500,95],"api_nowhp":47,"api_maxhp":47,"api_soku":5,"api_leng":1,"api_onslot":[14,14,5,3,0],"api_kyouka":[9,0,19,30,0,0,0],"api_backs":6,"api_fuel":30,"api_bull":30,"api_slotnum":4,"api_ndock_time":0,"api_ndock_item":[0,0],"api_srate":3,"api_cond":80,"api_karyoku":[13,23],"api_raisou":[20,0],"api_taiku":[36,42],"api_soukou":[52,52],"api_kaihi":[42,49],"api_taisen":[96,79],"api_sakuteki":[63,64],"api_lucky":[9,54],"api_locked":1,"api_locked_equip":0,"api_sally_area":0,"poi_slot":[{"api_id":4348,"api_slotitem_id":242,"api_locked":0,"api_level":0,"api_alv":7},{"api_id":4001,"api_slotitem_id":94,"api_locked":0,"api_level":0,"api_alv":7},{"api_id":4628,"api_slotitem_id":242,"api_locked":0,"api_level":0,"api_alv":6},{"api_id":4852,"api_slotitem_id":70,"api_locked":0,"api_level":0},null],"poi_slot_ex":null}],"escort":null,"support":null,"LBAC":null},"packet":[{"api_deck_id":1,"api_formation":[1,3,1],"api_f_nowhps":[9,75,69,9,9,47],"api_f_maxhps":[9,75,75,9,9,47],"api_fParam":[[18,0,22,16],[94,0,68,89],[94,0,73,88],[16,0,18,13],[18,0,22,16],[9,0,35,52]],"api_ship_ke":[157,284,275,209,150,148],"api_ship_lv":[83,40,71,66,81,77],"api_e_nowhps":[50,50,90,75,83,97],"api_e_maxhps":[50,50,90,75,83,97],"api_eSlot":[[52,22,54,107,-1],[22,55,18,22,-1],[8,8,28,25,-1],[7,7,11,25,-1],[7,7,12,25,-1],[9,9,29,25,-1]],"api_eParam":[[40,0,48,62],[25,0,47,59],[99,0,78,98],[94,0,79,89],[98,0,82,95],[139,0,99,119]],"api_midnight_flag":1,"api_search":[1,1],"api_stage_flag":[1,1,1],"api_kouku":{"api_plane_from":[[6],[1,2]],"api_stage1":{"api_f_count":33,"api_f_lostcount":14,"api_e_count":112,"api_e_lostcount":4,"api_disp_seiku":4,"api_touch_plane":[-1,54]},"api_stage2":{"api_f_count":19,"api_f_lostcount":5,"api_e_count":34,"api_e_lostcount":5},"api_stage3":{"api_frai_flag":[0,1,0,0,0,0],"api_erai_flag":[0,0,0,0,1,1],"api_fbak_flag":[0,0,0,0,0,0],"api_ebak_flag":[0,0,0,0,0,0],"api_fcl_flag":[0,0,0,0,0,0],"api_ecl_flag":[0,0,0,0,0,0],"api_fdam":[0,6,0,0,0,0],"api_edam":[0,0,0,0,10,0]}},"api_opening_taisen_flag":0,"api_opening_taisen":null,"api_opening_flag":0,"api_opening_atack":null,"api_hourai_flag":[1,1,0,0],"api_hougeki1":{"api_at_eflag":[0,1,0,1,0,1,0,1,0,1],"api_at_list":[1,5,2,4,0,2,4,3,3,1],"api_at_type":[0,0,0,3,0,0,0,3,0,0],"api_df_list":[[1],[4],[0],[4],[3],[5],[4],[4],[3],[5]],"api_si_list":[[8],[9],[8],[25,7,12],[-1],[8],[-1],[25,7,11],[-1],[-1]],"api_cl_list":[[0],[0],[1],[1],[1],[1],[0],[1],[0],[0]],"api_damage":[[0],[0],[60],[6],[10],[43],[0],[2],[0],[0]]},"api_hougeki2":{"api_at_eflag":[0,1,0,1,0,1,0,1,0,1],"api_at_list":[0,1,1,2,2,3,3,4,4,5],"api_at_type":[0,0,0,0,0,2,0,2,0,0],"api_df_list":[[4],[5],[2],[4],[1],[1,1],[5],[3,3],[5],[5]],"api_si_list":[[-1],[-1],[8],[8],[8],[7,7],[-1],[7,7],[-1],[9]],"api_cl_list":[[0],[0],[1],[1],[1],[1,1],[0],[1,1],[2],[1]],"api_damage":[[0],[0],[18],[0],[75],[29,31],[0],[6,1],[13],[2]]},"api_hougeki3":null,"api_raigeki":null,"poi_path":"/kcsapi/api_req_practice/battle","poi_time":1519867076707},{"api_ship_id":[157,284,275,209,150,148],"api_win_rank":"B","api_get_exp":24,"api_member_lv":99,"api_member_exp":1116934,"api_get_base_exp":563,"api_mvp":3,"api_get_ship_exp":[-1,844,563,1126,563,563,563],"api_get_exp_lvup":[[50860,52800],[290243,296200],[221014,228000],[29031,30000],[38531,40600],[295700,296200,307400]],"api_enemy_info":{"api_user_name":"","api_level":97,"api_rank":"少将","api_deck_name":"第1艦隊"},"poi_path":"/kcsapi/api_req_practice/battle_result","poi_time":1519867231225}]}

這是戰鬥紀錄。另外,我在另一台電腦測試發現未卜先知是正常在運作的。
