### ISSUE TITLE
kcwiki语音字幕，中文操作系统下字幕显示为日语

### ISSUE THREAD

**Issue by yezirun4649** [poooi/poi#1758]
**poi 版本 / poi version:**
8.2.0-beta.3

**操作系统 / OS:**

WIN7
**插件名和版本 / Plugin name & version:**
kcwiki语音字幕 v1.2.10

**你遇到了什么样的问题 / The problem you've met:**
中文操作系统下字幕显示为日语。

**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:**
重启Poi，重启电脑等常规操作后，显示的字幕还是日语的。问题反复出现。

![qq20180301-0](https://user-images.githubusercontent.com/28726451/36822981-361a7d38-1d3e-11e8-83a0-411d5a43471f.jpg)
![qq20180301-0](https://user-images.githubusercontent.com/28726451/36822982-3642fe52-1d3e-11e8-9a4c-5b032c032042.png)

**Comment by SoraYama** [comment]
@yezirun4649 可以在扩展程序的设置里面找到 kcwiki 字幕插件设置语言

**Comment by yezirun4649** [comment]
@SoraYama 问题解决了，谢谢。
