### ISSUE TITLE
舰队信息里舰娘的名字完全被缩到看不见了

### ISSUE THREAD

**Issue by deepsea666** [poooi/poi#1761]
**poi 版本 / poi version:**8.2.0-beta.3

**操作系统 / OS:win7-32位

**你遇到了什么样的问题 / The problem you've met:**
![45](https://user-images.githubusercontent.com/21211204/36882051-94816e4e-1e0c-11e8-9229-ba5f5ba7669e.jpg)
我的显示器是1440*900，窗口已经是最大化了
这个版本的舰队信息在插件和主面板切分的时候舰队名字完全被缩到看不见了，我知道是为了给六格武藏的装备留出足够的空间，建议优化一下这个界面，最理想的是左边游戏窗口的上下空白部分可以利用起来，比如让游戏窗口紧贴上方，下方留出的空间可以放插件面板或主面板
使用舰娘头像的时候这个问题倒是能解决，但我32位系统想尽可能的降低内存的使用，顺便我也问一下，使用舰娘头像会不会增加内存使用

**Comment by KochiyaOcean** [comment]
@deepsea666 只有 1440 的横向分辨率不建议使用切分面板
关于上下切分的讨论https://github.com/poooi/poi/issues/1692

**Comment by KochiyaOcean** [comment]
舰娘头像在第一次加载的时候会消耗比较多的 CPU 资源，之后就几乎没有消耗了

**Comment by deepsea666** [comment]
不增加消耗我就使用头像吧
