### ISSUE TITLE
mac版poi运行后网页窗口占满了全屏

### ISSUE THREAD

**Issue by str0078** [poooi/poi#1762]
**poi 版本 / poi version:**
820beta3

**操作系统 / OS:**

10.13.3 
**插件名和版本 / Plugin name & version:**

**你遇到了什么样的问题 / The problem you've met:**
mac版poi，最新测试版，运行后网页窗口占满了全屏，插件设置都完全看不到了，无法缩小窗口

**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:**

![qq20180303-001923 2x](https://user-images.githubusercontent.com/36996434/36909752-eb8c6a46-1e79-11e8-9449-8ad08bd6de06.jpg)

**Comment by KagamiChan** [comment]
舰 #1740 
可以拉长窗口然后调整游戏区域尺寸

**Comment by str0078** [comment]
这2个问题我看过了，无法解决，现在是整个画面全是网页，根本点不到设置里面去，左右上下拉伸都没用。请问配置文件在哪里，我手动修改

**Comment by KagamiChan** [comment]
一般来说你把窗口拉一半到显示区域外，就可以拉伸了，文件在 `~/Library/Application support/poi/config.cson`

**Comment by KochiyaOcean** [comment]
开开发者工具切 console 输入 `config.set('poi.webview.width', 800)`
