### ISSUE TITLE
8.2 切換畫面定格 

### ISSUE THREAD

**Issue by canonho** [poooi/poi#1763]
**poi 版本 / poi version:**
8.2

**操作系统 / OS:*
-win7

**你遇到了什么样的问题 / The problem you've met:**
切換POI至其他畫面後 畫面會定格 flash和聲音會依舊運行 
如何解決呢?

**Comment by KochiyaOcean** [comment]
听不懂……

**Comment by KagamiChan** [comment]
请问你的计算机是什么配置？

**Comment by canonho** [comment]
![image](https://user-images.githubusercontent.com/32305815/36933006-ce9d1f50-1f0c-11e8-80c5-882581930209.png)
就這樣定格 只有聲音
我以前用8.1 沒這問題的

**Comment by canonho** [comment]
https://github.com/poooi/poi/issues/1751 和這篇一樣

**Comment by KochiyaOcean** [comment]
那就只能说目前原因不明了

**Comment by canonho** [comment]
我現在畫面定格只能 按一下自動調整畫面大小 
然後畫面回復正常 不再定格 會不會是這裡有問題?

**Comment by canonho** [comment]
我現在是自訂大小的狀態 定格的時候只好 選自動調整畫面大小
然後再取消

**Comment by KochiyaOcean** [comment]
那么问题的可能性就指向 electron 或者 chromium，然后就更没法确定了
等上游更新吧……

**Comment by canonho** [comment]
好的 因為我之前用8.2beta時就有這情況 所以換回8.1 
剛看到8.2出了正式版試試用 結果也一樣
所以我推算是面版更新了的問題

**Comment by KagamiChan** [comment]
请试试 8.3.0-beta.1 是否还存在类似问题

**Comment by ymdtzx** [comment]
系统 mac High Sierra 10.13.4 无论使用8.30还是9.0版本都会遇到这个问题
