### ISSUE TITLE
卡在黑色漂船讀取畫面

### ISSUE THREAD

**Issue by Reddingtondaita** [poooi/poi#1765]
**poi 版本 / poi version:**
8.2

**操作系统 / OS:**
Windows 10 

**插件名和版本 / Plugin name & version:**

**你遇到了什么样的问题 / The problem you've met:**
卡在黑色漂船讀取畫面
已經試過: 重新安裝, 重啟電腦, 清cookies和快取, 输入 netsh winsock reset 并回车也用了
但是用poi開了艦娘後按了start game就卡在黑色漂船讀取畫面, 過了2分鐘多就猫了
(用google chrome打開就沒有問題  **

**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:**

![image](https://user-images.githubusercontent.com/37019312/36935170-961f95b0-1f37-11e8-9bfa-c5b95d96dd88.png)

**Comment by KagamiChan** [comment]
把 `%appdata%/poi/cache` 文件夹整个删除掉试试看

**Comment by Reddingtondaita** [comment]
试了 還是這樣.....
![image](https://user-images.githubusercontent.com/37019312/36937315-b833cbe0-1f54-11e8-9cb1-98a4a3f48d59.png)

**Comment by KagamiChan** [comment]
你是通过烤饼干直连的吗

**Comment by KagamiChan** [comment]
可以参考 #1556 和 #1753 的情况看一下，看一下是不是因为网路请求超时了
