### ISSUE TITLE
更新8.2后，进入E4地图的boss点，一直卡在战斗开始！已经连续两次这个情况，心态要爆炸了

### ISSUE THREAD

**Issue by audyfan** [poooi/poi#1766]
**poi 版本 / poi version:**

**操作系统 / OS:**

**插件名和版本 / Plugin name & version:**

**你遇到了什么样的问题 / The problem you've met:**

**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:**

**Comment by audyfan** [comment]
![snipaste_2018-03-03_22-45-13](https://user-images.githubusercontent.com/11060097/36935680-a109db68-1f35-11e8-8911-c357c82708b7.png)

**Comment by KagamiChan** [comment]
清理一遍缓存吧，把 %appdata%/poi/cache 文件夹整个删掉再打开 poi

**Comment by KochiyaOcean** [comment]
@audyfan 如果可以的话，看看 8.1 是否有相同问题？

**Comment by audyfan** [comment]
昨天用8.1推到了E4的boss，卡了很长时间，最后进去了。今天收到8.2升级推送，自动升级失败，手动全删了升级的，然后连续两次E4，都是进到boss点，卡屏，等了至少一个小时，没反应

**Comment by KochiyaOcean** [comment]
@audyfan 这种情况感觉是网路问题……

**Comment by audyfan** [comment]
代理都是正常的。卡住等待的时候，也担心是网络的原因，特意开了chrome，开youtube，都是正常的

**Comment by KagamiChan** [comment]
@audyfan 有时候是本地缓存本身就有问题，需要清除一遍缓存

**Comment by audyfan** [comment]
@KagamiChan 自动升级失败了，是手动下载升的级。手动升级的时候，把所有都删了，相当全新安装poi。今天实在没心情再去试了，改天再试试看吧

**Comment by KagamiChan** [comment]
我看到这个 issue 的时候就在打 e4，现在活动都打完了，大概是没有问题了吧
