### ISSUE TITLE
v1.2.11的语音字幕。金刚的：提督ぅ……私達三戦隊も……準備を始めるネ…。这句话显示是：HI！ 今天天气也不错呢～！ 

### ISSUE THREAD

**Issue by FlanreCinro** [poooi/poi#1767]
**poi 版本 / poi version:**

**操作系统 / OS:**

**插件名和版本 / Plugin name & version:**

**你遇到了什么样的问题 / The problem you've met:**

**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:**

**Comment by KagamiChan** [comment]
cc @grzhan

**Comment by grzhan** [comment]
似乎是舰娘百科的源字幕收录出现了些问题，我去找有关同学咨询一下。

**Comment by grzhan** [comment]
@FlanreCinro 字幕数据已更新，可以更新到最新版插件（v1.2.12）检查问题是否仍然存在。
谢谢勘误！
