### ISSUE TITLE
关于v8.2.0正式版flash卡屏

### ISSUE THREAD

**Issue by kookinhard** [poooi/poi#1768]
flash卡屏，但是仍然可以点击，而且有声音，战斗过程正常
请问是poi的原因吗？还是我电脑的原因？

**Comment by KagamiChan** [comment]
> 关于游戏界面在最小化等操作时时冻结的问题
> 目前的情报推测是 Chromium 内核本身的 bug，已知可以通过右键工具栏的自动调节按钮解除自动调整可以解决（之后再左键进行自动调整即可） ​​​​

**Comment by KagamiChan** [comment]
请试一下 8.3.0-beta.1 看看是否还存在卡屏问题
