### ISSUE TITLE
更新8.2後，資源圖示無法顯示

### ISSUE THREAD

**Issue by starchaos** [poooi/poi#1769]
![eee](https://user-images.githubusercontent.com/37036658/36944071-c5dc381a-1fcf-11e8-823c-cf7441ce5a87.JPG)
更新8.2後，資源圖示無法顯示
請問一下如何解決

**Comment by KagamiChan** [comment]
无法显示是什么意思？

**Comment by starchaos** [comment]
![ee](https://user-images.githubusercontent.com/37036658/36944180-dd501b22-1fd1-11e8-949d-0809888fefd5.JPG)
原本的圖示是這個樣子的，更新8.2後變成了上面PO的那種

**Comment by KochiyaOcean** [comment]
@starchaos 显示设置里面关闭高清图标即可

**Comment by starchaos** [comment]
@KochiyaOcean 感謝，剛剛試了好久，以解決。
