### ISSUE TITLE
8.2版本窗口调节问题

### ISSUE THREAD

**Issue by kangred** [poooi/poi#1770]
**poi 版本 / poi version:**
8.2

**操作系统 / OS:**

WIN7
**插件名和版本 / Plugin name & version:**

**你遇到了什么样的问题 / The problem you've met:**
窗口拉小，游戏界面无法同比例变小，导致部分游戏画面和全部插件界面在窗口外，无法看到和点击，严重影响要一边做其他事一边打游戏的体验

**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:**

**Comment by KagamiChan** [comment]
> 关于 8.2.0 以后布局的变更点
> 取消面板强制大小限制，如果使用可变游戏分辨率，游戏界面将以窗口高度（横版）或者窗口宽度（纵版）占满，如果发现有此情况可以调整窗口大小。
> 当设置固定分辨率时，窗口大小被限制为不得低于游戏尺寸。
> 添加界面编辑模式，快捷工具栏内的笔按钮可以开启，开启后可以调整主面板的子面板大小位置和切分面板的比例
