### ISSUE TITLE
8.2.0,full screen with nothing on it.

### ISSUE THREAD

**Issue by Cageofreedom** [poooi/poi#1771]
**poi 版本 / poi version:8.2.0

**操作系统 / OS:Win10

**插件名和版本 / Plugin name & version:**

**你遇到了什么样的问题 / The problem you've met:, [_20180304084115](https://user-images.githubusercontent.com/15911826/36946692-a0fa0a20-1fb8-11e8-9590-409f6b626c3e.jpg)
(Don't mind about the photographer)

**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:Just a new one installed. Don't know how to reproduce it again.

**Comment by KagamiChan** [comment]
Try reloading the game
You may change you window size to make the settings panel visible

**Comment by KagamiChan** [comment]
We've changed the game area sizing mechanism, now the game area size only depends on window dimension.

Drag your window half out of the screen and then you could expand you window horizontally
