### ISSUE TITLE
8.2.0 自动切换动作不正常

### ISSUE THREAD

**Issue by zlyzly777** [poooi/poi#1772]
**poi 版本 / poi version:**
8.2.0

**插件名和版本 / Plugin name & version:**
未卜先知 v7.3.2（但推测与插件本身无关）

**你遇到了什么样的问题 / The problem you've met:**
扩展程序→高级设置→“允许自动切换至主面板”选项的动作不正常

**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:**
1.勾选“允许自动切换至主面板”，而不勾选“自动切换至插件”：点击编成、返回母港等操作时不会自动切换到对应主面板；
2.同时勾选“允许自动切换至主面板”和“自动切换至插件”：点击编成、返回母港等操作时会自动切换到对应主面板，即和之前 8.1.0 版本动作相同；
另外“自动切换至插件”选项对应插件的自动切换动作和之前版本相同，虽然只测试了未卜先知插件，而且禁用插件后以上情况依旧。

简而言之就是这两个选项的关系在 8.1.0 中是并列，而 8.2.0 中则是从属。

**Comment by KagamiChan** [comment]
看了一下代码，控制自动切换的代码从去年到现在都没有什么变化。「自动切换至插件」是一个总开关，之后的「自动切换至主面板」是一个在前者基础上的一个选项。虽然我觉得文件描述和选项位置可能需要换一下，但是应该没有你说的这个变化

https://github.com/poooi/poi/blame/master/views/tabarea.es#L213

**Comment by zlyzly777** [comment]
看了一下应该是我把这个插件内的切换搞混了。谢谢。
