### ISSUE TITLE
战斗记录无法打开

### ISSUE THREAD

**Issue by Aoiwhite** [poooi/poi#1774]
**poi 版本 / poi version:8.2.0

**操作系统 / OS:WIN7 64位旗舰版

**插件名和版本 / Plugin name & version:战斗记录Ver.4.0.1

**你遇到了什么样的问题 / The problem you've met:打开战斗记录之后一直黑屏，另外从航海日志点左边感叹号后提示“欲查看战斗详情，请先下载并启用「战斗详情」插件”。我已卸载并重装POI两次，还是没有解决

**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:有一次内存不足死机，用任务管理器强制结束过一次POI

![image](https://user-images.githubusercontent.com/33090165/36960239-0014afec-2081-11e8-8930-9bf04b2f66f2.png)
![image](https://user-images.githubusercontent.com/33090165/36960253-0fb14316-2081-11e8-89a8-ddc94f7b275b.png)
![image](https://user-images.githubusercontent.com/33090165/36960314-6827765a-2081-11e8-9930-2fccbdcbb4ad.png)

**Comment by KagamiChan** [comment]
@Aoiwhite 请在激活战斗详情窗口的情况下按 ctrol + shift + i 打开开发者工具并截图

**Comment by Aoiwhite** [comment]
![image](https://user-images.githubusercontent.com/33090165/36961375-fe867854-2085-11e8-8469-4af4597b25cb.png)

**Comment by Aoiwhite** [comment]
已解决
