### ISSUE TITLE
8.2.0windows未响应问题

### ISSUE THREAD

**Issue by annoft** [poooi/poi#1775]
**poi 版本 / poi version:**8.2.0

**操作系统 / OS:**Windows 10 v1709 (build 16299.192)

**插件名和版本 / Plugin name & version:**

**你遇到了什么样的问题 / The problem you've met:**
E7P2最终战时，昼战结束后夜战选项出现前，程序卡死。

**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:**
[https://pbs.twimg.com/media/DXhFrqWVAAEwOtv.jpg:large](url) 程序卡死截图
[https://twitter.com/AnnoFT_001/status/970603047343726593](url) 插件和数据版本情况

**Comment by annoft** [comment]
补充一下，8.2.0beta版本也出现过这个问题。只在E7的boss点出现过这个情况，都是昼战第二轮炮击战结束以后卡死。

**Comment by KagamiChan** [comment]
这是每次都会出现的，还是偶发现象？

**Comment by annoft** [comment]
@KagamiChan 偶发现象，昨天2-3也出现了这个问题。
