### ISSUE TITLE
黑屏

### ISSUE THREAD

**Issue by Enoru** [poooi/poi#1777]
**poi 版本 / poi version:**
poi-8.2.0

**操作系统 / OS:**
win7

**插件名和版本 / Plugin name & version:**

**你遇到了什么样的问题 / The problem you've met:**

上一局游戏进行一半突然poi整个画面全黑只有游戏显示，重启后一直保持黑屏状态。重下或者使用旧版本都打不开

**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:**

**Comment by Enoru** [comment]
![20180305192837](https://user-images.githubusercontent.com/37070803/36973277-4c87e48a-20ad-11e8-92ac-97b145f42d2a.jpg)

**Comment by m14815** [comment]
为也遇到了同样的情况，我一般是刚进游戏。
poi version 8.2.0
windows 10

**Comment by KochiyaOcean** [comment]
@Qualiazero 全新安装都不能解决很难说是这里的问题了

**Comment by Qualiazero** [comment]
@KochiyaOcean 8.1.0从官网下的正式版目前还是flash界面黑屏

**Comment by KochiyaOcean** [comment]
8.1 之前能连之后不能连就更不是 poi 本身的问题了……
检查下 poi 能否获得正确的 ip 地址（访问 ipaddress.com 之类）看看？

**Comment by Qualiazero** [comment]
@m14815 和你描述的情况并不一样，是打开直接无显示，没有其他动作

**Comment by m14815** [comment]
@Qualiazero 那应该是你的poi没得到数据吧，很可能与网络有关

**Comment by Qualiazero** [comment]
@m14815 请看上方管理员的回复。网络没有问题。

**Comment by Qualiazero** [comment]
@KochiyaOcean 是这样，8.1.0没出现过类似问题，8.2.0是大约三日前才出现问题，之前一直正常使用

**Comment by KochiyaOcean** [comment]
@Qualiazero 这种情况说明 poi 本身也没有问题... 检查 dns 之类的吧

**Comment by Qualiazero** [comment]
@KochiyaOcean https://ci.appveyor.com/project/KochiyaOcean/poi/build/1.0.2575/artifacts 这个版本确实也没有恢复

**Comment by Qualiazero** [comment]
找到解决办法了
https://tieba.baidu.com/p/5332436085?red_tag=1668574608
我直接修改了防火墙内的允许应用列表，之前可以正常使用的时候没有修改过这些东西，推荐给有相同问题的同志看看
