### ISSUE TITLE
8.2.0 一个显示问题

### ISSUE THREAD

**Issue by lexpha** [poooi/poi#1779]
**poi 版本 / poi version:**
8.2.0

**操作系统 / OS:**

Windows 10 1709

**你遇到了什么样的问题 / The problem you've met:**
鼠标悬停在状态栏左侧截屏等按钮上时显示的注释会错位到游戏画面中，截屏的时候会被截下来。
![tim 20180307222931](https://user-images.githubusercontent.com/12905814/37099206-c14e2244-225a-11e8-97c9-3b3c7386bea8.png)

**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:**
可能的重现要点：

- 设置布局为横板

- 缩放比率80%（显示设置里滑块控件那个）（实测缩放比率小于100%都会出现错位，比率越小错位越夸张）

- 窗口高度不为最大

另外8.1的时候是没问题的，覆盖安装8.2之后设置还在，但莫名其妙的出现了这个问题( ´_ゝ` )

**Comment by lexpha** [comment]
![2018-3-7t21 56 41](https://user-images.githubusercontent.com/12905814/37099623-c5e9390a-225b-11e8-8c6b-0c0bb031f296.png)
再补充一张冻鳗美图，可以看见一键截图被一键截图了……

**Comment by KochiyaOcean** [comment]
https://ci.appveyor.com/project/KochiyaOcean/poi/build/1.0.2575/artifacts 用这个看看吧

**Comment by KochiyaOcean** [comment]
Fixed by #6ae8130
