### ISSUE TITLE
無法調整視窗大小

### ISSUE THREAD

**Issue by KenLiu2** [poooi/poi#1780]
**poi 版本 / poi version:8.2.0**

**操作系统 / OS: Windows 8.1**

**插件名和版本 / Plugin name & version:**

**你遇到了什么样的问题 / The problem you've met:
下載8.2.0正式版以後，遊戲介面占了整個屏幕，無法用滑鼠拖曳縮放，根本點不到底下來設置，如圖。
[IMGUR](https://imgur.com/oa9MlIB)

**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:**

**Comment by KochiyaOcean** [comment]
开开发者工具切换到 console 输入 `config.set('poi.webview.width', 800)` 然后回车
<del>所以为什么要设置一个巨大的游戏分辨率呢……</del>

**Comment by KenLiu2** [comment]
emmm，剛才暫時換回8.1就沒這事
我的分辨率一直是800的
不論nga和貼吧都有人在問這個
主要的問題是，就算分辨率或視窗太大，原本只要將鼠標點在視窗邊緣拖曳縮小就行了
這8.2版拖曳到一個程度就不能再縮小了，好像什麼東西卡著一樣

**Comment by KochiyaOcean** [comment]
8.2 以后窗口尺寸被限制不得小于游戏尺寸
所以是你的屏幕的分辨率小于 800 么……

**Comment by KenLiu2** [comment]
分辨率夠的
你可能提到重點了，窗口尺寸如果不得小於遊戲尺寸，那窗口就會不能縮小
我設置的是縱向，遊戲在上、艦隊一覽在下，結果因為窗口太大，下面的地方都超出屏幕了，上緣也碰到頂了，根本沒辦法點到設置介面，想換橫向都不行

**Comment by KochiyaOcean** [comment]
所以为什么游戏分辨率会设置的那么大……
`config.set('poi.webview.width', 800)` 应该是没问题的

**Comment by KenLiu2** [comment]
我剛才先開8.1把窗口調小再開8.2就成功了
然後用你的方法也成功了
不過我還是很納悶為什麼第一次開啟會那麼大，是不是8.2默認的呢.....
總之解決了，謝謝您
