### ISSUE TITLE
8.2版poi经常闪屏

### ISSUE THREAD

**Issue by a26214311** [poooi/poi#1781]
8.2版poi
ubuntu14.04下
经常动不动就屏幕闪一下，不好截图，瞬间闪一下，亮眼睛

8.1版正常
在windows下正常

**Comment by KochiyaOcean** [comment]
@a26214311 关闭硬件加速看看吧

**Comment by a26214311** [comment]
关闭硬件减速好像并没什么用

**Comment by KagamiChan** [comment]
@a26214311 是整个屏幕都闪了还是窗口闪？用的什么显卡和什么驱动？别的 electron 程序也会闪吗？

**Comment by a26214311** [comment]
只有窗口闪

lspci |grep -i vga
01:00.0 VGA compatible controller: NVIDIA Corporation GM206 [GeForce GTX 950] (rev a1)

没用过别的electron程序，至少poi8.1是不闪的

**Comment by KagamiChan** [comment]
@a26214311 不知道用的是开源驱动还是闭源驱动？

**Comment by a26214311** [comment]
不知道这个怎么查
sudo lshw -c video | grep configuration 
       configuration: driver=nouveau latency=0

**Comment by a26214311** [comment]
想起来一件事
曾经有段时间（大概不到半年？）看bilibili（chrome63）也差不多一直闪，好像持续了1-2个月，之后就好了
不知道有没有帮助

**Comment by KagamiChan** [comment]
@a26214311 nouveau 就是开源驱动了，可以考虑换成 nvidia 的闭源驱动看看。poi 8.2 只在 chrome 59 倒是

**Comment by a26214311** [comment]
ok
换成了nvidia的显卡驱动，目前没出现过闪屏了

**Comment by a26214311** [comment]
不行，好像还是闪
但少了很多了

**Comment by ArchmageTony** [comment]
那个。。我也碰到这个问题了。。。win7系统 NVIDIA显卡驱动，禁用硬件加速。。 就是游戏画面会突然白一下。。

**Comment by KochiyaOcean** [comment]
@carey1997517 没法针对没法重现的问题做修改
