### ISSUE TITLE
自定义背景模式下，背景图片被0.9不透明度的bg-overlay遮挡，几乎无法看到背景图

### ISSUE THREAD

**Issue by slime7** [poooi/poi#1782]
设置自定义背景后（重开过poi），背景覆盖层的不透明度过高，几乎无法使背景透过，只能看到一片灰色背景。其他版本没试过使用自定义背景。把`bg-overlay`的背景色去掉后可以看到背景图（有对比图），试着换了几个主题，是一样的效果。第一次尝试使用自定义背景，不确定操作是否正确。
![2](https://user-images.githubusercontent.com/8674371/37194006-1df03b16-23a7-11e8-9333-5f27f5e6adc7.png)
![3](https://user-images.githubusercontent.com/8674371/37194007-1e2d0302-23a7-11e8-914f-35bab30509fa.png)

**poi 版本 / poi version:**
v8.2.0

**操作系统 / OS:**

win10

**插件名和版本 / Plugin name & version:**

**你遇到了什么样的问题 / The problem you've met:**

**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:**

**Comment by KochiyaOcean** [comment]
为了保证前面字体的能见度而特意做的调整，如果有不满可以使用自定义 CSS 功能

**Comment by slime7** [comment]
@KochiyaOcean 说实话，为了防止字体看不清而设置90%的不透明度有点高了（自认为），自定义图片基本没什么用处，我换了几张图，换到个gif才能看到确实有背景图并且在动。
<s>有个设置遮罩不透明度百分比的滑块就好了！</s>
