### ISSUE TITLE
Poi 9.0.0 changelog

### ISSUE THREAD

**Issue by SoraYama** [poooi/poi#1783]
### 舰队收藏二期对应
- [beta.1] API 变更对应
- [beta.1] 移除内置 flash
- [beta.1] 设置默认分辨率为 1200x720

### 功能
- [beta.0] 全新的窗口插件系统
  - 本体插件和窗口插件可以互相转换
  - 窗口插件将不再常驻后台，节省系统资源
- [beta.0] 游戏界面在不设置固定分辨率的时候可以在编辑模式下设置比率
  - 编辑模式按钮可在游戏画面左下角点击 > 后找到
  - 编辑模式下双击游戏界面边缘可以使游戏界面适应窗口高度或宽度
- [beta.1] 游戏界面可以弹出为独立窗口
- [beta.1] 本体新增加了 “重置视窗和分辨率” 功能
  - 可以在标题栏 “显示” 选项卡/托盘右击菜单中找到该选项
- [beta.2] 更新了战术地图数据
- [beta.0] 更新 Electron 到 3.0
  - 注：MacOS 因上游原因仍然是 2.0.7
- [beta.0] 更新 FontAwesome5

### 修复
- [beta.0] 修复部分面板在放大的情况下表示不正常的问题
- [beta.0] 恢复了上游原因导致的 macOS High Sierra 下标题栏无法隐藏的问题
- [beta.2] 玄学硬件加速优化
- [beta.2] 修复舰娘头像无法显示问题
- [beta.2] 修复游戏画面上方出现白条的问题

**Comment by KochiyaOcean** [comment]
# POI v9.0.0 changelog
## Function
- All-new window plugin system
  - Add support of switching inline & new-window mode
  - No back-end processes of new-window plugins
- Add support of edit width of game area by drag & drop
- Update to Electron 2.0
- Update to FontAwesome 5
## Fixes
- Fix display on zooming
- Fix transparent title-bar on macOS

**Comment by SoraYama** [comment]
- 本体新增加了 “重置视窗和分辨率” 功能
  - 可以在标题栏 “显示” 选项卡/托盘右击菜单中找到该选项

**Comment by KagamiChan** [comment]
9.0.0-beta.2 ~ 9.0.0-beta.3

- 舰娘头像换为使用改造界面立绘
- 各类图标更新为二期
- 加入陆航图标显示
- 任务面板的任务显示对应 wiki 编号（需要安装任务信息插件）
- 新的界面模式：
  + 信息面板与插件面板上下分隔与左右分隔模式，分隔可以调节
  + 面板隐藏模式
- 加入舰娘对空喷进弹幕的标志
- Electron 升级到 3.0.0-beta.8/ chrome 66
- 大量的稳定性升级与修复

**Comment by KochiyaOcean** [comment]
9.0.0-beta.4 ~ 9.0.0
- 增加缺失的 AACI 类型
- 修复访问网页以外的访问方式的自动适配
- 移除斩杀警告，因为数据难以维护

**Comment by KochiyaOcean** [comment]
9.0.1 ~ 9.0.2
- 优化编辑模式的操作逻辑
- 如果没有布局变更，编辑模式将在一分钟之后自动关闭
- 修复一些布局逻辑问题

**Comment by KochiyaOcean** [comment]
9.0.2 ~ 9.0.1
- 修复 flash 载入
- 支持 Nelson Touch
- UI 杂项修复
