### ISSUE TITLE
poi面板调不出来了

### ISSUE THREAD

**Issue by naoh2005** [poooi/poi#1785]
dalao好

**poi 版本 / poi version:poi-8.2.0**

**操作系统 / OS:win10**

**插件名和版本 / Plugin name & version:**

**你遇到了什么样的问题 / The problem you've met:**
我的poi面板被调没了  这几天玩别的游戏 导致一些分辨率在调来调去的 结果poi的面板界面就在一直缩小
但是一直都能勉强看  今天直接就几乎没了 怎么设置都调不出来  卸载然后重装 重启都不好使

**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:**

**Comment by naoh2005** [comment]
![qq 20180310143154](https://user-images.githubusercontent.com/37235016/37238950-a2bc05f0-2474-11e8-8395-bafff91ec3e8.png)

**Comment by naoh2005** [comment]
![qq 20180310143154](https://user-images.githubusercontent.com/37235016/37238954-ac887dd4-2474-11e8-8586-1ce1c466b32b.png)

**Comment by naoh2005** [comment]
最右面窄窄的一小条是poi面板  但是怎么也调不回来了 点左上角poi→设置  也显示出不来了 不知道怎么调 求求各位dalao百忙之中帮下忙 谢谢了

**Comment by KochiyaOcean** [comment]
@naoh2005 更新 8.3.0 的 beta 版看看

**Comment by naoh2005** [comment]
@KochiyaOcean  我当初用8.1.0的时候就有这毛病 结果我以为升级成8.2.0能好 结果也没好

**Comment by KochiyaOcean** [comment]
@naoh2005 因为这三个版本布局逻辑都有变动，需要确认问题是否还存在于新的代码中

**Comment by naoh2005** [comment]
@KochiyaOcean 好吧  谢谢dalao 我先下载一下看看 但是假如要是还是不行 还有别的办法吗

**Comment by KochiyaOcean** [comment]
@naoh2005 删除 %appdata%/poi/config.cson

**Comment by naoh2005** [comment]
@KochiyaOcean  好用了  谢谢dalao
