### ISSUE TITLE
建議加入艦隊裝備全名詳細列表

### ISSUE THREAD

**Issue by linarse31183** [poooi/poi#1786]
**poi 版本 / poi version:** 8.2.0

**操作系统 / OS:** win10

**你遇到了什么样的问题 / The problem you've met:**

非報錯帖，想詢問未來是否會加入艦隊裝備總覽畫面。
目前的做法是僅顯示裝備圖示，將鼠標移過去才會出現完整裝備名稱，在與別人分享或討論時不是很方便，若能顯示該艦隊的詳細裝備列表(能在同一頁面顯示所有裝備的全名)幫助會很大。已有瀏覽poi的wiki但沒看到類似功能才來發文，若poi已有內建或插件可做到這個功能，請告訴我這個笨蛋怎麼做...謝謝。

**Comment by KagamiChan** [comment]
我们目前有编成日记与正在开发中的 poi-plugin-cqc 两个扩展，支持编成总览及向外部工具导出编成。此外对于特定战斗中的编成，可以查看战斗记录扩展

wiki 那边已经有很长一段时间没有更新了，抱歉

**Comment by linarse31183** [comment]
原來在編成日記，感謝解惑!
