### ISSUE TITLE
一鍵截圖切到邊

### ISSUE THREAD

**Issue by HandAxe** [poooi/poi#1787]
**poi 版本 / poi version:**
v8.3.0-beta.0

**操作系统 / OS:**

win10_1709(OS組建16299.248)
**插件名和版本 / Plugin name & version:**

**你遇到了什么样的问题 / The problem you've met:**
更新上8.3beta.0之後變成在版面編輯那調整遊戲視窗大小，調整後按下一鍵截圖會切到邊邊

**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:**

![2018-3-11t1 6 51](https://user-images.githubusercontent.com/37238962/37244765-827212ea-24c8-11e8-8fb5-7d44baf2f843.png)

**Comment by KagamiChan** [comment]
@HandAxe 多谢汇报，已知问题，会修复

**Comment by KagamiChan** [comment]
已在 beta.1 修复

**Comment by HandAxe** [comment]
I see THX.
