### ISSUE TITLE
poi無法截圖

### ISSUE THREAD

**Issue by Scorpion1121** [poooi/poi#1788]
**poi 版本 / poi version:**
8.3.0-beta.1

**操作系统 / OS:** win7 64位元

**插件名和版本 / Plugin name & version:**

**你遇到了什么样的问题 / The problem you've met:**

po無法截圖，按下一鍵截圖沒有反應

**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:**

**Comment by KochiyaOcean** [comment]
那……再按一下？
（如果是出错最好提供开发者工具出错的相关信息

**Comment by Scorpion1121** [comment]
按了一鍵截圖好幾次沒有反應，開發者工具我要從哪邊查找問題點??

新人對程式語言不熟.... 抱歉

**Comment by SoraYama** [comment]
@Scorpion1121 点击开发者工具后看到 console 选项卡找到红色报错部分截图贴一下就好

**Comment by Scorpion1121** [comment]
![111](https://user-images.githubusercontent.com/37282613/37267038-ee9ecaf4-25f8-11e8-9b22-311f8e8d38e9.png)

**Comment by KochiyaOcean** [comment]
试试看这里的版本 https://ci.appveyor.com/project/KochiyaOcean/poi/build/1.0.2594/artifacts 能不能截图？

**Comment by Scorpion1121** [comment]
![333](https://user-images.githubusercontent.com/37282613/37267941-3fbf45ee-25fe-11e8-8e16-8a60781b6524.png)


載了上面的載點還是一樣，沒反應。 還是我要把原本的poi的檔案刪除再重新安裝一次？

上面載點我直接覆蓋舊的檔案會影響？

**Comment by Scorpion1121** [comment]
![444](https://user-images.githubusercontent.com/37282613/37273477-f5073b80-2614-11e8-8f34-18f5f5177a38.png)

**Comment by KochiyaOcean** [comment]
你在 console 下面输入 `getStore('layout.webview')` 回车的结果是怎么样的

**Comment by Scorpion1121** [comment]
{width: 939, height: 563.390625, useFixedResolution: false}

顯示這一段

**Comment by KochiyaOcean** [comment]
懂了，马上修

**Comment by KochiyaOcean** [comment]
https://ci.appveyor.com/project/KochiyaOcean/poi/build/1.0.2596/artifacts 这个版本应该是修复了，球确认（正在 build，大概 10 分钟之后可以下载

**Comment by Scorpion1121** [comment]
不好意思，請問這個修復檔是直接丟到資料夾內解壓縮就好了？

還是要放在哪？

2018-03-12 17:40 GMT+08:00 東風谷オーシャン <notifications@github.com>:

**Comment by KochiyaOcean** [comment]
下载 exe 的话直接安装，7z 直接解压

**Comment by Scorpion1121** [comment]
謝謝你的幫助，沒問題了。

2018-03-12 18:56 GMT+08:00 東風谷オーシャン <notifications@github.com>:
