### ISSUE TITLE
无法显示友军

### ISSUE THREAD

**Issue by s8637800** [poooi/poi#1789]
**poi 版本 / poi version: v8.3

**操作系统 / OS: win10

**插件名和版本 / Plugin name & version: 战斗记录4.0.2

**你遇到了什么样的问题 / The problem you've met: 今天突然开始无法显示友军战斗数据，包过之前的历史战斗数据也看不发到友军数据了，但是复制到了KC3是可以显示友军战斗

![qq 20180312145225](https://user-images.githubusercontent.com/25460072/37269385-058487ca-2605-11e8-9385-150790973de5.png)
这是之前能正常显示的友军的
![qq 20180312001825](https://user-images.githubusercontent.com/25460072/37269414-26a402f0-2605-11e8-88f4-3e0a109cd91d.png)

**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:**

![3](https://user-images.githubusercontent.com/25460072/37269327-d19c8296-2604-11e8-946b-9e40150ef367.png)

**Comment by KagamiChan** [comment]
鸡丁忘记更新 submodules 了吧……

**Comment by KagamiChan** [comment]
我发个新版本吧
