### ISSUE TITLE
截图缩放问题

### ISSUE THREAD

**Issue by Hydralick** [poooi/poi#1790]
**poi 版本 / poi version:8.3 beta2**

**操作系统 / OS:win10 1709**

**插件名和版本 / Plugin name & version:**

**你遇到了什么样的问题 / The problem you've met:截图缩放存在问题。系统缩放150%，因此poi我设置为534x320，以往（8.2，8.3beta1未测试）截图时仍是800x480分辨率，今天换用beta2后发现截图也变成了534x320。**

**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:**

**Comment by KochiyaOcean** [comment]
@Hydralick 现在的设定如此，因为低分辨率下就算拉大也无法保证画质
