### ISSUE TITLE
8.3.0 beta2 闪屏 黑屏 花屏

### ISSUE THREAD

**Issue by toooonyy** [poooi/poi#1791]
**poi 版本 / poi version:**
8.3.0 beta2

**操作系统 / OS:**
macOS 10.13.3

**你遇到了什么样的问题 / The problem you've met:**
8.3 版本切应用高概率闪屏，只发生在 poi 被遮挡后切换（就是说，如果 poi 未被其他应用完全遮挡，则切换不闪）。集显，停用硬件加速无影响。
存在黑屏状况，一般为点击登陆后进入母港小概率发生，刷新后正常。
另外，如果开了半透明+停用硬件加速还有额外 bug
8.2 版本无闪屏问题，但存在黑屏情况。

**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:**
随便打开一个全屏应用 cmd+tab 切换高概率会闪（变白），只发生在 flash 部分。flash 的 wmode 是 direct，改成其他的似乎无明显变化。
黑屏情况无法稳定复现，猜测和网络有关？

半透明+停用硬件加速
![screen shot 2018-03-14 at 19 01 44](https://user-images.githubusercontent.com/3480434/37398684-406090e4-27ba-11e8-8798-9be2bf3b7f34.png)

**Comment by KochiyaOcean** [comment]
干死苹果！！！！！！！！！！！！！

**Comment by toooonyy** [comment]
9.0.0-beta0 依旧存在闪屏情况，花屏情况未测试（但是看 commit 应该还能复现）。
这里反馈另外一个严重的问题。在 9.0.0 下，新型插件窗口无法改变大小（eg 舰娘信息 航海日志），从而导致部分窗口信息被遮盖。确认 poi 设置了允许变更窗口大小。

**Comment by KochiyaOcean** [comment]
测试窗口插件可以正常调整大小，无法复现

**Comment by KochiyaOcean** [comment]
在插件窗口 `cmd + shift + i` 调出控制台输入 `remote.getCurrentWindow().isResizable()` 回车是什么结果

**Comment by gnattu** [comment]
稍微看了下8.2-8.3的改动，应该是给webview应用了react-resizable-area导致的闪烁，macOS会自说自话的给不可见窗口卸载资源用来节能，导致每次把窗口从不可见状态激活都要触发一下resize，自然会闪一下了

黑屏的话是某些js脚本的document.write的问题，9.0的话应该已经修复了的

那个花屏的话原因不明，但是从窗口行为（背景完全没有透明度）来看，似乎没有GPU的场合窗口半透明根本就不会启用，然而主题却依然使用了背景基本上是alpha的半透明主题。这样子的话，就能透过主题看到本应该被遮挡住的部分了。
如果使用普通主题的话，由于是没有alpha的背景色，所以不该被看到的地方是被背景的颜色盖住的。

**Comment by toooonyy** [comment]
@KochiyaOcean 我等`document.write`那个 commit 整合进发布了再测试下，先感谢各位的工作。

**Comment by toooonyy** [comment]
9.0.0 beta1 不再出现闪屏，黑屏也暂未遇到。

**Comment by toooonyy** [comment]
9.0.0 beta1 不再出现闪屏，黑屏也暂未遇到。
