### ISSUE TITLE
艦娘信息按鈕異常

### ISSUE THREAD

**Issue by harry71129tw** [poooi/poi#1792]
**poi 版本 / poi version:**
8.3.0 beta2

**操作系统 / OS:**
win10 1709

**插件名和版本 / Plugin name & version:**
艦娘信息 5.1.1

**你遇到了什么样的问题 / The problem you've met:**
一旦觸發「艦娘信息」開啟一次列表，之後想要再度開啟，卻發現「艦娘信息」的按鈕失效。
※到設定的擴展程式中禁用再重新啟用後能夠開啟，但開啟後按鈕又會失效，需要進行同樣設定操作

console：
![image](https://user-images.githubusercontent.com/22185853/37409486-6cc32182-27d9-11e8-98b1-8f9d8aa66429.png)

**Comment by KochiyaOcean** [comment]
目前没有成功复现
