### ISSUE TITLE
POI無法開啟

### ISSUE THREAD

**Issue by lay9438721** [poooi/poi#1795]
poi 版本 / poi version:
8.2.0
操作系统 / OS:
WIN7
插件名和版本 / Plugin name & version:

你遇到了什么样的问题 / The problem you've met:
更新後不小心把解析度調得太高導致POI直接沒有回應 重新安裝也不能解決

有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:
![error](https://user-images.githubusercontent.com/37425583/37498152-9dd6e0fa-28f7-11e8-920a-6da5e2cc76df.jpg)

**Comment by KagamiChan** [comment]
试一下删除 %appdata%/poi/config.cson 看看
