### ISSUE TITLE
Windows 10 style notification

### ISSUE THREAD

**Issue by skyyu901** [poooi/poi#1796]
**poi 版本 / poi version:**
8.2.0

**操作系统 / OS:**
Windows 7

**插件名和版本 / Plugin name & version:**

**你遇到了什么样的问题 / The problem you've met:**
How can I disable the Windows 10 style notification?
I want the previous notification style back.

**Comment by KochiyaOcean** [comment]
Balloon on Windows 7 requires extra logic and is removed from code base.
