### ISSUE TITLE
Poi 8.2.0 无法显示游戏界面以外的功能

### ISSUE THREAD

**Issue by Lifeline1234** [poooi/poi#1798]
**poi 版本 / poi version:** - POI 8.2.0

**操作系统 / OS:**

**你遇到了什么样的问题 / The problem you've met:**

无法显示插件栏与设置栏。

**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:**

![image](https://user-images.githubusercontent.com/37507608/37566720-6d9485a8-2a93-11e8-9a55-7af4c87721d9.png)

**Comment by KochiyaOcean** [comment]
改变窗口大小

**Comment by Lifeline1234** [comment]
谢谢， 已解决
