### ISSUE TITLE
http://bh.contextweb.com/bh/rtset请问这个网站是什么？为什么poi游览器会往这个网站发信息？

### ISSUE THREAD

**Issue by ZIWUHW** [poooi/poi#1800]
**poi 版本 / poi version:**

**操作系统 / OS:**

**插件名和版本 / Plugin name & version:**

**你遇到了什么样的问题 / The problem you've met:**

**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:**

**Comment by KochiyaOcean** [comment]
怀疑是被 DNS 劫持了，更换 DNS 设置看看

**Comment by ZIWUHW** [comment]
@KochiyaOcean 我用的是114的DNS，应该不是吧？而且IP是美国的，这个访问不是你们游览器进行的吗？如果不是的话那我就得好好研究研究了
URL：http://bh.contextweb.com/bh/rtset
IP Port：151.101.228.166:80

**Comment by KochiyaOcean** [comment]
并不是

**Comment by JenningsWu** [comment]
@ZIWUHW 搜了下，这似乎是一个恶意网站，弹广告下病毒窃隐私的那种

**Comment by ZIWUHW** [comment]
@JenningsWu 请问这是怎么回事呢？DNS没有被篡改，hosts文件只改了pixiv和dmm的，为啥会出现这种情况？怎么解决呢？求大神指条道。

**Comment by ZIWUHW** [comment]
@JenningsWu 只有用POI的时候才会出现恶意访问。。本来以为是游览器上传游戏概率什么的被误报了，结果不是。。真蛋疼，不过我想不起来安过什么乱七八糟的软件啊，还有大佬是怎么查到这个网站是恶意网站的？

**Comment by JenningsWu** [comment]
@ZIWUHW Google。。
