### ISSUE TITLE
一键截图无效

### ISSUE THREAD

**Issue by BTmanMk2** [poooi/poi#1801]
**poi 版本 / poi version:**
poi-8.3.0-beta.0 

**操作系统 / OS:**

Win7 x64

**插件名和版本 / Plugin name & version:**

**你遇到了什么样的问题 / The problem you've met:**
一键截图无效

**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:**

![](https://i.loli.net/2018/03/23/5ab50d94e9ea3.png)

**Comment by KochiyaOcean** [comment]
更新
