### ISSUE TITLE
舰娘信息问题

### ISSUE THREAD

**Issue by flawxh** [poooi/poi#1802]
**poi 版本 / poi version:8.3.0 beta.2

**操作系统 / OS:win10 1607

**插件名和版本 / Plugin name & version:舰娘信息 ver5.1.1

**你遇到了什么样的问题 / The problem you've met:舰娘信息插件在返回母港后黑屏

**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:
![qq 20180324175323](https://user-images.githubusercontent.com/37380048/37862248-c19f2998-2f41-11e8-99cc-eda0809af2e0.png)

**Comment by KochiyaOcean** [comment]
请提供舰娘信息的截图（在插件界面按 `ctrl + shift + i`

**Comment by flawxh** [comment]
![2018-03-24_181049](https://user-images.githubusercontent.com/37380048/37862376-9d154c18-2f43-11e8-992c-958d42a66708.png)
@KochiyaOcean

**Comment by KagamiChan** [comment]
禁用再启用舰娘信息的话，返回母港还会出现这样的现象吗

**Comment by flawxh** [comment]
会的

**Comment by KagamiChan** [comment]
@flawxh 重启 poi 呢？

**Comment by flawxh** [comment]
仍然有

**Comment by KagamiChan** [comment]
@flawxh 那麻烦关闭 poi，删除 %appdata%/poi/local storage 文件夹再重启

**Comment by flawxh** [comment]
@KagamiChan 解决了谢谢
