### ISSUE TITLE
好像就这一个船名字过长

### ISSUE THREAD

**Issue by a26214311** [poooi/poi#1803]
**poi 版本 / poi version:**
8.2.0

**操作系统 / OS:**

**插件名和版本 / Plugin name & version:**

**你遇到了什么样的问题 / The problem you've met:**

![image](https://user-images.githubusercontent.com/5009469/37870540-30b6f65c-300b-11e8-9a66-c7d073fa8cf8.png)

**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:**

**Comment by Javran** [comment]
已经在 3c4f77f 修了,等下个版本就好了
