### ISSUE TITLE
視窗的問題

### ISSUE THREAD

**Issue by ken0905** [poooi/poi#1804]
不小心把視窗調太大...
現在沒辦法調回來.......
請問要怎麼做才能調回來....? 
![default](https://user-images.githubusercontent.com/37955558/38163034-2c0c6ebc-3528-11e8-9dda-f0fb93d5eaf4.jpg)

**Comment by KochiyaOcean** [comment]
ctrl + shift + i 打开开发者工具，切到 console 面板输入 `config.set('poi.webview.width', 800)` 回车
