### ISSUE TITLE
（Version 8.2）Persistent plug-in installation fails/更新8.2版本后插件安装失败问题

### ISSUE THREAD

**Issue by FuSencho** [poooi/poi#1806]
poi 版本 / poi version:
8.2.0

操作系统 / OS:
Win10专业版

插件名和版本 / Plugin name & version:
Null

你遇到了什么样的问题 / The problem you've met:

自从更新8.2以来，就遇到了插件无法安装的问题，安装插件的时候无限转圈，一开始以为是网络问题，但是后来发现下载的安装包也无法使用。（目前尝试直接复制其他人的plugin文件夹，但是部分插件会乱码）

在线安装：
![image](https://user-images.githubusercontent.com/37668506/38183750-648e2856-3632-11e8-8284-298889c92cc1.png)

本地安装：
 @![image](https://user-images.githubusercontent.com/37668506/38183754-67d9531e-3632-11e8-91c2-88171fdc2a99.png)

有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:
持续性问题，从8.2开始就一直存在

QQ：961744219

**Comment by KagamiChan** [comment]
请尝试一下高级设置当中的自动修复功能

**Comment by FuSencho** [comment]
尝试过了，并且多次手动删除文件并重装，都没有效果

**Comment by KagamiChan** [comment]
试一下安装 9.0.0-beta.0 看看？

**Comment by KagamiChan** [comment]
或者打开 cmd，拖动 poi.exe 到窗口里面，回车，看看安装插件的时候有没有打出什么报错信息

**Comment by FuSencho** [comment]
感谢回复！

9.0.0-beta.0问题仍然存在，系统和环境不变，在线安装和本地安装文件均失败。

在线安装结果（点击全部安装）：
![default](https://user-images.githubusercontent.com/37668506/38930544-e242b36c-4342-11e8-8f05-f2fc8040342c.png)

本地安装使用的文件：
![default](https://user-images.githubusercontent.com/37668506/38930584-fbcb5550-4342-11e8-9bfb-6d3bd498b186.png)

本地安装结果：
![default](https://user-images.githubusercontent.com/37668506/38930626-23ca77b6-4343-11e8-8e42-c02b741e7e8b.png)

**Comment by KagamiChan** [comment]
如果重命名 `%appdata%/poi` 文件夹，然后打开 poi，能不能安装上插件？

文件夹名称可以试完之后改回来

**Comment by FuSencho** [comment]
可以安装，两种方法均没有问题。
所以问题具体是出在哪里呢？

**Comment by KagamiChan** [comment]
@FuSencho 我只能理解为你原来的文件夹有某种权限方面的限制，或者有一些奇怪的内容
