### ISSUE TITLE
未卜先知在打乾燃油彈藥後，顯示錯誤數據

### ISSUE THREAD

**Issue by Davinais** [poooi/poi#1808]
**poi 版本 / poi version:**
v8.2.0

**操作系统 / OS:**
Linux Mint 17 64bit Kernel 3.13.0-139-generic

**插件名和版本 / Plugin name & version:**
未卜先知 v7.3.3

**你遇到了什么样的问题 / The problem you've met:**
當艦娘打空燃油及彈藥後，顯示錯誤的數據

**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:**
在近乎欠缺燃料彈藥的狀態下出擊，打了幾場等到完全乾掉之後，反而又變回100%

![aaa](https://user-images.githubusercontent.com/5267712/38386272-b51de740-3946-11e8-9960-9df6868c8c47.png)
![bbb](https://user-images.githubusercontent.com/5267712/38386279-b9dcb950-3946-11e8-854c-2f78fea9a57e.png)

**Comment by KagamiChan** [comment]
已修复
