### ISSUE TITLE
poi在Unity/GNOME桌面开启缩放时画面显示不正常

### ISSUE THREAD

**Issue by WAAutoMaton** [poooi/poi#1815]
**poi 版本 / poi version:**
8.2.0+（测试过8.2.0,8.3.0 beta 2, 9.0.0 beta 0）

**操作系统 / OS:**

Ubuntu 16.04 LTS 
桌面为Unity

**你遇到了什么样的问题 / The problem you've met:**

![image](https://user-images.githubusercontent.com/24771667/38762954-25f3f016-3fc5-11e8-97e0-938a0e97747b.png)

如上图，游戏窗口显示不全，且无法通过调整窗口大小的方式解决。
poi的“概览”面板也有同样的问题。

**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:**
![image](https://user-images.githubusercontent.com/24771667/38762976-9b176e22-3fc5-11e8-8ac2-83d6cea9f9ef.png)
这个问题仅在开启Unity桌面的窗口缩放时（如上图设置）出现，关闭窗口缩放后问题消失。

**Comment by KochiyaOcean** [comment]
不清楚 Unity 是怎么实现缩放的……

**Comment by WAAutoMaton** [comment]
最新版本（9.0.3）已修复这个问题
