### ISSUE TITLE
9.0.0beta版本无法自定义css改变字体，切换回8.2.0正式版已解决

### ISSUE THREAD

**Issue by Noza220** [poooi/poi#1816]
**poi 版本 / poi version:**
9.0.0beta

**操作系统 / OS:**

win10家庭版 1709
**插件名和版本 / Plugin name & version:**

**你遇到了什么样的问题 / The problem you've met:**
9.0.0beta版本无法自定义css改变字体
css代码如下：
*, h1, h2, h3, h4, h5{
    font-family: "Arial", "Loli";
}

**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:**
切换回8.2.0正式版已解决

**Comment by KochiyaOcean** [comment]
@Noza220 加上 !important
