### ISSUE TITLE
poi无限未响应

### ISSUE THREAD

**Issue by KongoDesu** [poooi/poi#1819]
**poi 版本 / poi version:**
8.2.0/9.0.0beta

**操作系统 / OS:**

win10 1709

**插件名和版本 / Plugin name & version:**

**你遇到了什么样的问题 / The problem you've met:**
poi安装后（安装包与解压均已尝试）无限未响应，删除缓存文件夹后问题依然存在

**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:**

**Comment by KochiyaOcean** [comment]
删除 `%appdata%/poi/plugins` 重启看看

**Comment by KongoDesu** [comment]
已经把appdata下的poi文件夹整个删除重启过了，能够成功运行poi但是无法加载舰娘游戏页面，关闭重启之后就变成打开以后立即未响应。我使用的是修改dns直连的方式。

**Comment by KochiyaOcean** [comment]
有办法尝试 hosts 以外的方法么比如 ooi 或者代理之类

**Comment by KongoDesu** [comment]
我使用pac代理之后重启poi会立即未响应。使用谷歌浏览器可以正常游戏。

**Comment by KochiyaOcean** [comment]
最后一个正常工作的版本是？

**Comment by KongoDesu** [comment]
最后能够正常使用的版本是8.0.0，之后暂时卸载了poi，前两天准备装回来发现未响应的问题

**Comment by KochiyaOcean** [comment]
@KongoDesu 8.0.0 现在有这个问题么

**Comment by KongoDesu** [comment]
8.0.0现在也无法使用，打开后立刻未响应
![1](https://user-images.githubusercontent.com/38753039/39303853-46fcc890-498a-11e8-8838-dd4fa0381262.png)

**Comment by KochiyaOcean** [comment]
@KongoDesu 可能是系统或者驱动更新导致的

**Comment by KongoDesu** [comment]
需要重装驱动试一试么？

**Comment by KochiyaOcean** [comment]
@KongoDesu 看看最近更新了什么吧

**Comment by KongoDesu** [comment]
@KochiyaOcean 好的，我先暂时用别的插件替代了

**Comment by lwkanjao** [comment]
要重装什么驱动啊
