### ISSUE TITLE
希望能增加战斗结束后通知的功能

### ISSUE THREAD

**Issue by chipoez** [poooi/poi#1823]
**poi 版本 / poi version:8.2.0

**操作系统 / OS:windows10

**插件名和版本 / Plugin name & version:**

**你遇到了什么样的问题 / The problem you've met:希望能增加战斗结束后通知的功能

**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:**

**Comment by KagamiChan** [comment]
你是说和 #1380 一样的功能吗

**Comment by KagamiChan** [comment]
鉴于没有得到回应，合并到 #1380 去讨论吧
