### ISSUE TITLE
关于浏览器提示音的请求

### ISSUE THREAD

**Issue by attfishbed** [poooi/poi#1824]
**poi 版本 / poi version:8.2.0

**操作系统 / OS:windows7

之前的poi更为习惯一些，现在改成了大淀（？）的语音有些不太适应，但是找不到在哪里改变，如果可以的话，希望能够变还为poi或仅跳出提示但无提示音

**Comment by KagamiChan** [comment]
不知道你有没有安装舰娘语音插件，看一下？

**Comment by attfishbed** [comment]
没有安装，之前曾经装过，但是已经卸了

かがみ <notifications@github.com> 于 2018年5月2日周三 上午11:45写道：

**Comment by KagamiChan** [comment]
再装回来看看？只有那个会更改通知语音

**Comment by attfishbed** [comment]
重新安装后恢复正常

かがみ <notifications@github.com> 于 2018年5月15日周二 上午9:48写道：
