### ISSUE TITLE
POI始终都在显示等待游戏数据中，poi完全没有捕捉到游戏数据

### ISSUE THREAD

**Issue by wangchen9311** [poooi/poi#1825]
**poi 版本 / poi version:8.2

**操作系统 / OS:win764位

**插件名和版本 / Plugin name & version:8.2

**你遇到了什么样的问题 / The problem you've met:游戏能通过POI进去，但是POI始终都在显示等待游戏数据中，poi完全没有捕捉到游戏数据

**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:**

![image](https://user-images.githubusercontent.com/39007269/39664020-777f83dc-50af-11e8-9256-4fc1b7fa2305.png)
![image](https://user-images.githubusercontent.com/39007269/39664024-93a999b2-50af-11e8-91f1-a00041164a3c.png)
![image](https://user-images.githubusercontent.com/39007269/39664033-a7515ebe-50af-11e8-8821-8a1322e88ba2.png)
![image](https://user-images.githubusercontent.com/39007269/39664044-c02cefb6-50af-11e8-88a4-48975f6709f2.png)

**Comment by KagamiChan** [comment]
请检查你的 poi 的网络设置，poi 端口需要设置为 0

**Comment by wangchen9311** [comment]
设置成0就打不开网页的，设置成岛风GO的8099就能打开游戏，但是依旧是正在捕捉游戏数据

**Comment by yukixz** [comment]
@wangchen9311 高级设置里面的poi端口设置为0。代理设置在上面别乱用

**Comment by wangchen9311** [comment]
就这样了，我都换了电脑了

**Comment by wangchen9311** [comment]
好吧，只能用HTTP代理啊
