### ISSUE TITLE
黑屏问题

### ISSUE THREAD

**Issue by XPAiki** [poooi/poi#1826]
**poi 版本 / poi version:8.1.0/8.2.0

**操作系统 / OS:win10
版本号1709

**你遇到了什么样的问题 / The problem you've met:使用岛风go代理只能进去DMM官网，游戏界面和输密码界面都打不开只有黑屏，poi提示等待游戏数据中，岛风go显示未检测到游戏

**Comment by KagamiChan** [comment]
@XPAiki 岛风 go 换线路，或咨询岛风 go 客服

**Comment by XPAiki** [comment]
@KagamiChan 好的
