### ISSUE TITLE
CPU boom!

### ISSUE THREAD

**Issue by ASIjacket** [poooi/poi#1829]
**poi 版本 / poi version:**
8.2

**操作系统 / OS:**
win 10 1803 [最新bug10]

**Q:Q:Q:Q:Q:Q:**
poi是一个基于web的应用(大概，在最近的一段时间里，CPU占用率一度超过30-40%(7700)，之前cpu没涂好的时候几分钟内便会过热蓝屏，这让我很不能理解
请问poi是否自带一些分析工具来分析资源占用呢，或者有什么其他工具或者方法可以提供。(开发工具里貌似没有看出什么
PS：win7 虚拟机下 pooi cpu占用会少很多

**Comment by KagamiChan** [comment]
在设置-关于里面有一个简易的资源管理器

**Comment by ASIjacket** [comment]
你好，
pepper plugin 在资源监视中占用最高，but，所有项目cpu占用总和<<总计值，那是poi本身的占用么

**Comment by KagamiChan** [comment]
pepper plugin 是 flash player，你可以试试看更新一下会不会有什么效果

总计值指的是在操作系统的资源管理器里面看到的吗？

**Comment by ASIjacket** [comment]
对的，随机截了个图
<a href="http://tinypic.com?ref=14xid6f" target="_blank"><img src="http://i67.tinypic.com/14xid6f.jpg" border="0" alt="Image and video hosting by TinyPic"></a>

**Comment by KagamiChan** [comment]
和哪里的加起来不相等呢

**Comment by ASIjacket** [comment]
我更新下player试试 〒▽〒

**Comment by ASIjacket** [comment]
:(

**Comment by ASIjacket** [comment]
可能确实是因为基于flash的原因吧，再坚持下，就h5了
