### ISSUE TITLE
一直出现选服务器的页面

### ISSUE THREAD

**Issue by westernnero** [poooi/poi#1830]
**poi 版本 / poi version:**

**操作系统 / OS:**
win10 1803

**插件名和版本 / Plugin name & version:**

**你遇到了什么样的问题 / The problem you've met:**
一直出现那个选服务器的页面，然后随便点一个就必定猫。用网页版上很正常，双清过很多次了还是不行。还有什么可行的解决方案吗

**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:**

**Comment by KagamiChan** [comment]
请问用的什么方式上的舰，然后你在网页版已经选了服务器了，但是 poi 里面登录还会出现选服务器的页面的意思吗

**Comment by westernnero** [comment]
谢谢回复。就用的poi+岛风go，选的HTTP直连。
对，我不是新玩家，以前一直再用poi，今天重装了一下系统，然后poi的东西都没了，然后我就新下载了一个，但是进游戏之后永远是选服务器的界面，双清了很多次了。
网页版是可以正常使用的。

2018-05-11 1:08 GMT+08:00 かがみ <notifications@github.com>:

**Comment by KagamiChan** [comment]
先试试看岛风 go 换线路吧，并且我感觉你可能登了一个别的帐号

**Comment by westernnero** [comment]
不会啊 我只有一个dmm帐号，而且登录界面都可以正常显示，点登录之后进游戏，短暂黑屏之后就出现选服务器的界面了，然后这个界面随便选一个服务器就会猫。

2018年5月11日 上午1:13，"かがみ" <notifications@github.com>写道：

先试试看岛风 go 换线路吧，并且我感觉你可能登了一个别的帐号

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/poooi/poi/issues/1830#issuecomment-388120395>, or mute
the thread
