### ISSUE TITLE
无法load，控制台一直在报js错误

### ISSUE THREAD

**Issue by feifeikulou** [poooi/poi#1832]
poi 版本：v9.0.0-beta.0
操作系统：win 10 1803
插件名和版本：为了排除问题已经全部卸载
你遇到了什么样的问题：打开poi控制台一直报错，“C:\Program Files\poi\resources\app.asar\assets\js\webview-preload.js:141 Failed. Will retry in 1000ms.”
近期更新了flash 怀疑是新版本flash的问题？flash版本号Adobe Flash Player 29 PPAPI /29.0.0.171
proxy：go和ss都试过 貌似跟代理没关系

![qq 20180515093356](https://user-images.githubusercontent.com/19323774/40031616-223ca7a8-5823-11e8-810f-85491e64aa74.jpg)

**Comment by KagamiChan** [comment]
的确是连不上，你可以试试在 poi 的地址栏里面输入 baidu.com 看看能不能打开

**Comment by feifeikulou** [comment]
已经试过打开baidu了 都连不上

**Comment by KagamiChan** [comment]
那就检查一下你的代理和代理设置吧
