### ISSUE TITLE
触控识别问题

### ISSUE THREAD

**Issue by death-steps** [poooi/poi#1834]
**poi 版本 / poi version:** v8.2.0

**操作系统 / OS:** Windows10 家庭版 64位 版本1803 OS内部版本17134.48

**插件名和版本 / Plugin name & version:**

**你遇到了什么样的问题 / The problem you've met:**
游戏主界面无法识别surface触控笔的点击，手指点击可以识别，poi设置界面笔和手指的点击操作可以识别，但是上下滑动均无法识别

**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:**

在Console界面发现chrome版本似乎是59，个人了解chrome在62版本添加了对surface触控笔的支持，不知道开发者能否更新一下chrome版本

**Comment by KochiyaOcean** [comment]
@death-steps Chromium 的 bug，等待上游修复

**Comment by death-steps** [comment]
刚刚也发现原因了，多谢回答

**Comment by Ziziru** [comment]
同样的问题，重开poi后surface pen可以使用一段时间，但一段时间后pen就无法点击，但触控任然可用

**Comment by KochiyaOcean** [comment]
@Ziziru 上游 bug，没法修
