### ISSUE TITLE
插件-耗資記錄-應用篩選問題

### ISSUE THREAD

**Issue by mcmcmmc** [poooi/poi#1836]
**poi 版本 / poi version:**
v9.0.0-beta.0

**操作系统 / OS:**
win10 pro 版本1709 OS組建16299.431
**插件名和版本 / Plugin name & version:**

耗資記錄, Ver 0.7.0

**你遇到了什么样的问题 / The problem you've met:**
在添加篩選後, 本來在"當前應用的篩選有"X" 可以去除已添加的篩選,但現在不論該插件視窗大小怎樣調,"X"也不見了

**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:**
請見附圖,可見中間藍色"當前應用篩選不知為何置中&"X"不見了.
https://i.imgur.com/wlxpaWm.png

開發者工具好像只針對POI本體? 不太懂如何針對插件選項截圖,還請指示~

謝謝!

**Comment by KochiyaOcean** [comment]
@gnattu 9.0 版本直接用本体的开发者工具即刻

**Comment by KochiyaOcean** [comment]
0.7.1 版本已修复
