### ISSUE TITLE
黑屏问题

### ISSUE THREAD

**Issue by Elevenleee** [poooi/poi#1837]
**poi 版本 / poi version:**
8.2.0    9.0.0

**操作系统 / OS:**
Win10版本1803

**你遇到了什么样的问题 / The problem you've met:**

打开后所有界面都没有加载，只是黑屏状态，什么都没有，卸载后重新安装也没有用，8.20或者9.00都是一样的，重启也解决不了，appdata/Roaming里没有poi的文件夹，岛风GO正常，chrome浏览器可以玩，但是poi界面什么都没有，这是打开后界面的截图，加载了一天一直都是这样.

![qq 20180526233626](https://user-images.githubusercontent.com/38997753/40577850-0bc65a9a-613e-11e8-970d-9eee3bf418d4.png)

**Comment by Elevenleee** [comment]
打开就是这样的

**Comment by KagamiChan** [comment]
请打开 cmd，然后把 poi.exe 拖动到窗口里面，按一下回车，看看报什么错误
