### ISSUE TITLE
kcwiki语音字幕显示为数字

### ISSUE THREAD

**Issue by attfishbed** [poooi/poi#1838]
**poi 版本 / poi version:8.2.0

**操作系统 / OS:windows10 home 1803

-->

**插件名和版本 / Plugin name & version:kcwiki语音字幕

**你遇到了什么样的问题 / The problem you've met:看板娘字幕均为数字

曾尝试使用http://bbs.ngacn.cc/read.php?tid=11609400&rand=724
中的解决办法，但是仅能在登场或收取任务的大淀获取正常字幕。

**Comment by SoraYama** [comment]
是什么样的数字能提供下截图吗
另外请试试在删除以上两个文件夹之后重新安装字幕插件，然后再重启poi

**Comment by KochiyaOcean** [comment]
插件版本太旧

2018年5月28日(月) 23:02 SoraYama <notifications@github.com>:

**Comment by attfishbed** [comment]
删除目录后重新安装解决，数字具体格式应为206.3（当时使用那智改，凭印象记录）
