### ISSUE TITLE
設置介面縮放問題

### ISSUE THREAD

**Issue by Grey1999** [poooi/poi#1845]
<img width="960" alt="001" src="https://user-images.githubusercontent.com/40167464/41226647-06d1e3d2-6d6a-11e8-8618-52ca35145550.png">

我不小心在設置介面將縮放調為最大，現在苦於怎麼縮小，希望有好心之士能幫忙，感謝

Poi9.0 Windows

**Comment by KagamiChan** [comment]
点击一下 >_ 这个图标，然后切换到 conosle，输入 `config.set('poi.zoomLevel')`，然后回车

**Comment by Grey1999** [comment]
感謝大佬
