### ISSUE TITLE
出现百度云加速

### ISSUE THREAD

**Issue by IceZotaku** [poooi/poi#1848]
操作系统 WIN7
版本 Ver 8.2.0

打开poi后出现以下文字
ouCTYPE html>
请打开cookies。
只差一步

输入验证码，可以浏览 k15-2.591mogu.com

为什么需要输入验证码?

输入验证码证明您不是机器人，输入后可以暂时浏览网站。

如何避免？

如果您使用私人电脑，可以下载杀毒软件，进行全盘扫描保证没有中毒。

如果您使用公用电脑，可以请网络管理员修正配置选项或查找病毒来源。

云加速 Event ID: 42ad0bb3aafe89e9 • 你的IP: 120.41.166.173 • 帮助中心 • 百度云加速

刷新、清楚cookie和缓存也无法打开游戏，依然是这些文字

**Comment by gnattu** [comment]
使用的代理/连接方式是？

**Comment by IceZotaku** [comment]
岛风go
HTTP代理

**Comment by gnattu** [comment]
@IceZotaku 岛风go换条线试试看
