### ISSUE TITLE
poi.exe 启动黑屏问题

### ISSUE THREAD

**Issue by hbj1000** [poooi/poi#1849]
**poi 版本 / poi version:**
7.9以后所有版本 
现在版本：9.0.0-beta.0

**操作系统 / OS:**

WIN10专业版  版本  1803

**插件名和版本 / Plugin name & version:**
暂未安装任何插件

**你遇到了什么样的问题 / The problem you've met:**
点开POI.exe后弹出黑屏窗口，等待约10分钟以上出现正常窗口，但无法访问任何网站。
将poi.exe拖入CMD运行显示一大堆错误。
![image](https://user-images.githubusercontent.com/30901271/41420148-6d5b1466-7026-11e8-965d-32b1f0b114ce.png)

\AppData\Roaming下poi文件夹和poi的本体文件全部删除过N次。
在CMD中执行过netsh winsock reset ，依旧没有用。

**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:**

![image](https://user-images.githubusercontent.com/30901271/41420330-c31efcf0-7026-11e8-8134-b00bec1a3e0b.png)

![image](https://user-images.githubusercontent.com/30901271/41420388-d9dc7c06-7026-11e8-9ab4-25d38ae29245.png)

**Comment by gnattu** [comment]
请问代理设置？

**Comment by hbj1000** [comment]
@gnattu     岛风go代理，  随时检查最优线路更换，使用网页或者KCV都可正常进行游戏。

**Comment by gnattu** [comment]
@hbj1000 请提供代理设置页面截图（包括高级设置）

**Comment by hbj1000** [comment]
@gnattu   点开一次poi.exe要卡至少5分钟才能进行点击操作，稍等……

**Comment by hbj1000** [comment]
@gnattu  重启2次后等待良久后的结果，这是代理设置，和之前能用的时候一致。
![image](https://user-images.githubusercontent.com/30901271/41422127-da638a6c-702a-11e8-90f8-3d878cda3f13.png)

**Comment by KagamiChan** [comment]
所以你的问题还是启动的时候 poi 会卡很久吗？计算机配置怎么样，有没有安装什么杀毒软件

**Comment by hbj1000** [comment]
@KagamiChan   对，会卡非常非常久，没有安装杀毒软件。计算机配置运行poi完全无压力，5月迷你春活更新之前poi运行一切正常，之后就一直出现这种状况。

**Comment by KagamiChan** [comment]
当时也是同一个版本的 poi 吗？
要不要试试把 poi 解压到别的盘上试试看，比如 C 盘？

**Comment by hbj1000** [comment]
@KagamiChan   当时是8.2，不记得是beta还是正式版了。
重新解压到C盘根目录后运行依旧会卡。
![image](https://user-images.githubusercontent.com/30901271/41422757-32818c3e-702c-11e8-945c-38d8cc27680e.png)

**Comment by gnattu** [comment]
`ECONNABORTED ` 是在`Proxy Listen On` 之后多久出现的？
是否尝试过取消代理使用直连设置启动poi？

**Comment by hbj1000** [comment]
@gnattu  3秒内就会出现。
删除\AppData\Roaming下poi文件夹时使用的默认设置就是直连设置吧？  那时候就已经卡得不行了，反而代理设置是之后强行设置的。

**Comment by gnattu** [comment]
@hbj1000 下载[这里的版本](https://ci.appveyor.com/project/KochiyaOcean/poi/build/artifacts)是否能够加快窗口的启动？

**Comment by hbj1000** [comment]
@gnattu  没有什么实质性的变化……
![image](https://user-images.githubusercontent.com/30901271/41426895-bc8f2656-7037-11e8-9b71-f6b21bb392fc.png)

**Comment by hbj1000** [comment]
@gnattu 最终的启动画面也和之前一样
![image](https://user-images.githubusercontent.com/30901271/41427217-ce9031fa-7038-11e8-8560-2b13e0fa9b87.png)

**Comment by gnattu** [comment]
@hbj1000 现在是否设置了代理？

**Comment by hbj1000** [comment]
@gnattu   改成直连后窗口的启动速度快了一点，但还是卡住要等好一会儿才能点击。
![image](https://user-images.githubusercontent.com/30901271/41427646-2c7451ba-703a-11e8-9740-fc7533b98b7f.png)

**Comment by gnattu** [comment]
所有的Timeout都指向`151.101.0.133`，属于Github的一个IP
虽然可能有点异想天开，但是你能不能试试切断网络连接启动poi，看看启动速度是否会更快。

**Comment by hbj1000** [comment]
@gnattu 
禁用网络之后，启动poi就完全不卡，瞬间就好了。

**Comment by gnattu** [comment]
看来和我想像的一样。。。
不稳定的网络连接大幅降低了poi的启动速度（耗费大量时间在重试网络连接）
切断网络以后，无网络的错误会瞬间反应，因此没有办法加载的资源会直接被跳过而不是重试。

**Comment by hbj1000** [comment]
@gnattu 
代理并没有出问题的样子，用网页或者KCV开代理可以正常游戏
宽带网络应该也不会有问题，用平板开poi接相同的网络同样没有任何问题。

**Comment by gnattu** [comment]
@hbj1000 但是poi确实在访问网络上受到了不小的阻碍
确切的原因我也只能猜测，并且你执行过`netsh winsock reset`，那winsock应该也不太会有问题才对
或许你可以检查一下防火墙设置？

**Comment by hbj1000** [comment]
@gnattu

**Comment by hbj1000** [comment]
@gnattu 
![image](https://user-images.githubusercontent.com/30901271/41428963-327ada8a-703e-11e8-8b00-f622ef9589ad.png)

**Comment by hbj1000** [comment]
@gnattu 
重置了winsock
关闭了防火墙
不开代理直连
依旧很卡……
![image](https://user-images.githubusercontent.com/30901271/41429377-8f66a00c-703f-11e8-95c1-8962aecf91b0.png)

**Comment by hbj1000** [comment]
@gnattu 
等到可以操作的时候，强行访问网页，卡死。
![image](https://user-images.githubusercontent.com/30901271/41429821-cb5948e8-7040-11e8-93a1-e4e4a733936c.png)

**Comment by hbj1000** [comment]
@gnattu  请问这么久都没有答复，是不是只能重做系统回避这个问题了？

**Comment by KagamiChan** [comment]
@hbj1000 主要是找不到具体的原因，在我这里也没有办法复现

有没有试过给系统安装一个 flash player ？

**Comment by hbj1000** [comment]
@KagamiChan  安装了最新的flash player   似乎[WARN]那一行消失了，其他照旧
![image](https://user-images.githubusercontent.com/30901271/41918128-4b050dce-798e-11e8-90c0-c3b1b039dce0.png)
