### ISSUE TITLE
poi游戏过程中突然黑屏

### ISSUE THREAD

**Issue by erlltye** [poooi/poi#1853]
**poi 版本 / poi version:**
v8.2.0

**操作系统 / OS:**

**插件名和版本 / Plugin name & version:**

**你遇到了什么样的问题 / The problem you've met:**
poi在游戏过程中突然黑屏，不是游戏界面黑屏，而是整个poi的界面黑屏（附黑屏截图），将poi.exe拖入cmd,并进行游戏，直到出现黑屏时截图如下

**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:**
进行游戏10分钟左右必定黑屏，不进入游戏仅打开poi时不出现黑屏

![_1nxi 7wrtyscu9 our6wnf](https://user-images.githubusercontent.com/41019325/42466003-96fbd370-83e8-11e8-9970-709dc1edc091.png)
![ya glsxr lisotjz zpld](https://user-images.githubusercontent.com/41019325/42466020-a7d4457e-83e8-11e8-8e37-dabee00769c2.jpg)

**Comment by erlltye** [comment]
操作系统windows7

**Comment by erlltye** [comment]
重装poi也不行

**Comment by KochiyaOcean** [comment]
@erlltye 没有什么能够判断的信息，总之看看 9.0 测试版

**Comment by erlltye** [comment]
@KochiyaOcean 请问这样的问题有可能与flash player有关吗

**Comment by KochiyaOcean** [comment]
@erlltye 有可能，但是无法确定

**Comment by erlltye** [comment]
@KochiyaOcean 因为在第一次用poi打开游戏时，有弹窗提示flash player未运行什么的，要求下载flash player,然后我去更新了flash player,再次用poi打开游戏时没有出现之前的弹窗，但是就出现了现在黑屏的情况

**Comment by KochiyaOcean** [comment]
@erlltye 那你更新 9.0 看看吧

**Comment by erlltye** [comment]
@KochiyaOcean 9.0问题依旧
