### ISSUE TITLE
poi无法获取游戏中的更新信息 改变编成 舰娘等级变更都未更新

### ISSUE THREAD

**Issue by fishfive** [poooi/poi#1854]
**poi 版本 / poi version:**

**操作系统 / OS:**

**插件名和版本 / Plugin name & version:**

**你遇到了什么样的问题 / The problem you've met:**

**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:**

**Comment by KagamiChan** [comment]
![image](https://user-images.githubusercontent.com/3816900/42644442-318e6faa-862e-11e8-9252-82ec2735b288.png)
poi 端口请填 0
