### ISSUE TITLE
启动poi后出现屏幕乱码/黑屏/白屏的现象

### ISSUE THREAD

**Issue by hbj1000** [poooi/poi#1855]
**poi 版本 / poi version:**
9.0.0-beta.0

**操作系统 / OS:**
WIN10专业版 版本 1803

**插件名和版本 / Plugin name & version:**

**你遇到了什么样的问题 / The problem you've met:**
启动poi后出现屏幕乱码/黑屏/白屏的现象。
使用的是岛风go代理，不启用代理时未出现异常现象（但并非代理问题，开代理使用网页或者KCV都是正常的）
重新清理缓存文件与本体后问题依旧存在。
![image](https://user-images.githubusercontent.com/30901271/43000777-683d631c-8c55-11e8-9c8f-27717eab3367.png)

**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:**

**Comment by KochiyaOcean** [comment]
换线
