### ISSUE TITLE
关于手动更新到9.0.0以后插件记录全部消失的问题

### ISSUE THREAD

**Issue by LuckyStar0026** [poooi/poi#1856]
从8.2.0更新过来，用的是poi.io上面的安装包，之前插件记录的信息都没了。（其实之前更新的时候也有类似的问题，有没有找回记录的方法）

**Comment by KochiyaOcean** [comment]
一般来讲不会发生，确认一下有没有使用了某些安全软件的清理垃圾功能之类

**Comment by LuckyStar0026** [comment]
没有，在上上次自动更新的时候也出现的一样的情况，然后我上次更新的时候直接下载压缩包然后覆盖就没有出现过插件丢失的问题

**Comment by KochiyaOcean** [comment]
你的安装目录是什么

**Comment by LuckyStar0026** [comment]
C:\Users\Adam\AppData\Roaming\poi

**Comment by KochiyaOcean** [comment]
@LuckyStar0026 你不应该把程序安装在数据目录，安装到其他文件夹就可以了

**Comment by LuckyStar0026** [comment]
好的，我知道了
