### ISSUE TITLE
要更换台电脑装POI 原来是64位的 现在是32位

### ISSUE THREAD

**Issue by sinlolicon** [poooi/poi#1857]
那么重新安装以后想要用户数据应该怎么做？

**Comment by KochiyaOcean** [comment]
@sinlolicon 不会删除

**Comment by sinlolicon** [comment]
@KochiyaOcean 不不 我意思是我换了台32位的电脑想要原来那台64位的POI的数据 应该拷贝哪些文件夹又不会影响32位的POI程序运行

**Comment by KochiyaOcean** [comment]
@sinlolicon %appdata%/poi

**Comment by sinlolicon** [comment]
@KochiyaOcean 
是哪个？
AppData\Local\Programs\poi
AppData\Roaming\poi

**Comment by sinlolicon** [comment]
@KochiyaOcean 谢谢解答~~
