### ISSUE TITLE
一心二用插件的建议

### ISSUE THREAD

**Issue by KenLiu2** [poooi/poi#1858]
**poi 版本 / poi version: v9.0.0-beta.0**

**操作系统 / OS: Windows8**

**插件名和版本 / Plugin name & version: 一心二用 Ver. 3.0.3**

**你遇到了什么样的问题 / The problem you've met: 只是想给个建议，最近才知道poi可以靠一心二用来分屏(把本体长宽设为0x0)，但是使用一心二用的时候没办法截图，且一心二用的视窗无法固定，每次开启就要重新调整位置和大小，使用上有些不便，若是插件作者能够拨空改善那就再好不过了，谢谢。**

**Comment by KagamiChan** [comment]
分离模式已实现
