### ISSUE TITLE
瑞凤先制对潜舰队面板不显示

### ISSUE THREAD

**Issue by chipoez** [poooi/poi#1860]
**poi 版本 / poi version: 9.0.0 beta.0

**操作系统 / OS: 1803 os build 17134.165

**插件名和版本 / Plugin name & version:**

**你遇到了什么样的问题 / The problem you've met: 瑞凤先制对潜舰队面板不显示

**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related: 瑞凤ka号观测机X2+三式指挥联络机X2去打1-5

![image](https://user-images.githubusercontent.com/33197406/43582787-2613f5c4-9690-11e8-8751-51a5c55477d8.png)

**Comment by KagamiChan** [comment]
是瑞凤改二还是瑞凤？
等级是多少？面板对潜值是多少？
确定实际游戏中可以出现先制对潜吗

**Comment by chipoez** [comment]
> 是瑞凤改二还是瑞凤？
> 等级是多少？面板对潜值是多少？
> 确定实际游戏中可以出现先制对潜吗

瑞凤改二确定实际游戏中可以先制，刚改二的等级按照描述配装，具体面板对潜值记不清了

**Comment by KagamiChan** [comment]
@chipoez 瑞凤改二，还是改二乙
还有印象等里是多少吗
