### ISSUE TITLE
Poi用不了,沒有回應

### ISSUE THREAD

**Issue by chan1c24** [poooi/poi#1866]
前天還是好好的,昨天突然用不了,本來是用最新的8.2.0的,之後換作舊的8.0.1情況還是一樣
一打開就如下圖一樣一片黑色的
https://gyazo.com/3899d1feac494b54446bdd7cc332091e
縮小後要不斷按才能喚回視窗

然後大概等數分鐘,才能在小視窗看到吹雪的樣子/或者下圖的樣子,依舊要按很多次才能喚回大視窗,但在大視窗亦無法作任何操作,並顯示沒有回應
https://gyazo.com/a542c01741f80ba9de7a911c876e6d47

望能幫助,謝謝

**poi 版本 / poi version:**
8.0.1

**操作系统 / OS:**
Win 10
版本1803

**Comment by chan1c24** [comment]
C:\WINDOWS\system32>D:\poi_8.01\poi.exe

C:\WINDOWS\system32>
[WARN] Cannot get system flash plugin path
附上cmd運行
[INFO] Proxy listening on 1552
[ERROR] Error: read ECONNRESET
[ERROR] Error: read ECONNRESET
[ERROR] Error: read ECONNRESET
[ERROR] Error: read ECONNRESET
[ERROR] Error: read ECONNRESET
[ERROR] Error: read ECONNRESET
[ERROR] Error: read ECONNRESET
[ERROR] Error: read ECONNRESET
[ERROR] Error: write after end
[ERROR] Error: write after end
[ERROR] Error: read ECONNRESET
[ERROR] Error: read ECONNRESET
[ERROR] Error: read ECONNRESET
[ERROR] Error: read ECONNRESET
[ERROR] Error: read ECONNRESET
[ERROR] Error: write after end
[ERROR] Error: write after end
[ERROR] Error: write after end
[ERROR] Error: write after end
[ERROR] Error: write after end
[ERROR] Error: read ECONNRESET
[ERROR] Error: read ECONNRESET
[ERROR] Error: write after end
[ERROR] Error: write after end
[ERROR] Error: write after end
[ERROR] Error: write after end
[ERROR] Error: write after end
[ERROR] Error: write after end
[ERROR] Error: write after end
[ERROR] Error: write after end
[ERROR] Error: write after end
[ERROR] Error: write after end
[ERROR] Error: write after end
[ERROR] Error: write after end
[ERROR] Error: write after end
[ERROR] Error: write after end
[ERROR] Error: write after end
[ERROR] Error: write after end
[ERROR] Error: write after end
[ERROR] Error: write after end
[ERROR] Error: write after end
[ERROR] Error: write after end
[ERROR] Error: write after end
[ERROR] Error: write after end
[ERROR] Error: write after end
[ERROR] Error: write after end
[ERROR] Error: write after end
[ERROR] Error: write after end
[ERROR] Error: write after end
[ERROR] Error: write after end
[ERROR] Error: write after end
[ERROR] Error: write after end
[ERROR] Error: write after end
[ERROR] Error: write after end
[ERROR] Error: write after end
[ERROR] Error: write after end
[ERROR] Error: write after end
[ERROR] Error: write after end
[ERROR] Error: write after end
[ERROR] Error: write after end
[ERROR] Error: write after end
[ERROR] Error: write after end
[ERROR] Error: read ECONNRESET
[ERROR] Error: read ECONNRESET
[ERROR] Error: read ECONNRESET
[ERROR] Error: read ECONNRESET
[ERROR] Error: read ECONNRESET
[ERROR] Error: read ECONNRESET
[ERROR] Error: read ECONNRESET
[ERROR] Error: write after end
[ERROR] Error: read ECONNRESET
[ERROR] Error: read ECONNRESET

**Comment by slui** [comment]
游戲更新到第二期轉html5

**Comment by chan1c24** [comment]
是轉了HTML…但其他人起碼能去到登入畫面…我直接黑屏進不了了…

**Comment by chan1c24** [comment]
更新了9.0.0也是同樣狀況

**Comment by KagamiChan** [comment]
既然之前是好的，那么后来有没有做过什么相关操作？

**Comment by chan1c24** [comment]
就只換了一只新的HDD,但是系統是安裝在原有的SSD上的,加上換了HDD後第一天還能正常運行…我想大概沒有關係吧…
