### ISSUE TITLE
解析度調太大改不回來

### ISSUE THREAD

**Issue by ab100777** [poooi/poi#1870]
不好意思我的解析度不小心調成1920，結果畫面太大讓右邊的工具列完全不見讓我無法調回來，請問哪裡可以讓工具列出現或是重製設定呢?
![default](https://user-images.githubusercontent.com/42470167/44267464-e3f75f00-a260-11e8-98c2-b06fe9587bf6.png)

**Comment by FX9590** [comment]
C:\Users\User Name\AppData\Roaming\poi\config.cson

**Comment by KagamiChan** [comment]
尝试一下新 beta 版本？
