### ISSUE TITLE
开启“禁用硬件加速”之后 浏览器异常缓慢

### ISSUE THREAD

**Issue by Ryuuen** [poooi/poi#1872]
**poi 版本 / poi version:**
v9.0.0-beta.1

**操作系统 / OS:**
1803 17134.228

**插件名和版本 / Plugin name & version:**

**你遇到了什么样的问题 / The problem you've met:**
很感谢新出的测试版。

如果勾选“禁用硬件加速”这个选项，在浏览器刚打开的时候是可以正常运行的。在登录到游戏后，母港出现之后，操作的反应就明显减慢：

1. 贴图加载缓慢，加载过程中明明没有网络流量发生（即已在缓存中）
2. 任何点击的反应都很慢，包括游戏区域和浏览器控制区域
3. 渐渐地失去相应，通过浏览器界面都无法正常关闭。但如果是在任务栏上右键图标后关闭，则可正常关闭

以上情况在关闭“禁用硬件加速”这个选项后消失。

**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:**

**Comment by KochiyaOcean** [comment]
并不是 poi 的问题，无法解决

**Comment by KagamiChan** [comment]
这个是正常现象……因为 html5 小游戏就是会吃 cpu 和 gpu

**Comment by Ryuuen** [comment]
那就建议干脆删掉那个选项，一旦勾上了就很难使用了
