### ISSUE TITLE
游戏主界面下方有白条画面显示不全

### ISSUE THREAD

**Issue by kasamiya** [poooi/poi#1874]
**poi 版本 / poi version:**
9.0.0 beta1

**操作系统 / OS:**
Win10 build 17134.228

**插件名和版本 / Plugin name & version:**

**你遇到了什么样的问题 / The problem you've met:**
画面下方显示白条导致画面显示不全

**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:**

![tim 20180817161438](https://user-images.githubusercontent.com/42482053/44292383-08d7dc00-a239-11e8-8276-77d59cd740cb.png)
![tim 20180817161523](https://user-images.githubusercontent.com/42482053/44292384-0bd2cc80-a239-11e8-8778-7e9e739dff23.png)

![tim 20180817161532](https://user-images.githubusercontent.com/42482053/44292385-0e352680-a239-11e8-83ee-c0d9eac2a6c7.png)

**Comment by DeckerCHAN** [comment]
目前使用chrome浏览器的网页版也有相同问题。
无法确定是否和岛风go有关。

**Comment by TaihouKai** [comment]
我看微博上说把岛风go的缩放调一下就行了，估计是岛风go的问题。

**Comment by kasamiya** [comment]
嗯嗯删除岛风的缓存就可以了谢谢

**Comment by kasamiya** [comment]
是的
