### ISSUE TITLE
Poi v9.0.0.beta-1不能运行(v8.2.0自动更新/ 手动重装皆不行)

### ISSUE THREAD

**Issue by PangCY1812** [poooi/poi#1875]
**poi 版本 / poi version:**
9.0.0 beta-1

**操作系统 / OS:** 
Win 7 32 bits

**插件名和版本 / Plugin name & version:**

**你遇到了什么样的问题 / The problem you've met:**
更新 Poi后不能运行

**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:**

目前使用v8.2.0。

利用Poi自动更新功能，下载完毕后，Poi自行关闭，之后不能运行了
移出Poi，手动下载v9.0.0 beta-1，重装后，依然不能运行。
Task Manager里没有显示Poi.exe运行。检查C:\Program Files\Poi 里面并非空白。
重装v8.2.0，Poi依然可以运行

Using v8.2.0 currently.

Using the auto update feature, the download progress finish, Poi will close itself, then no longer executable.
Uninstall Poi, manual download v9.0.0 beta-1, after install, Poi still failed to run.
Task manager list doesnt show Poi.exe was running. Checked the C:\Program Files\Poi folder show not empty.
Reinstall v8.2.0, Poi can be executed.

**Comment by PangCY1812** [comment]
刚测试了Win 7 64位元没有更新问题，Poi自动更新顺利，一切运行良好。
怀疑Poi 9.0.0 beta-1和32位元有兼容问题？

I had test in Win 7 64 bits and found no issue. Poi can update via auto update feature, everything is fine.
Suspect Poi 9.0.0 beta-1 has compatible issue with 32 bits OS?

**Comment by PangCY1812** [comment]
![image](https://user-images.githubusercontent.com/42483836/44297727-e6ad8f00-a308-11e8-8288-2598534d2c98.png)

附上v8.2.0自动更新时的状况

**Comment by KochiyaOcean** [comment]
可能是上游问题

**Comment by PangCY1812** [comment]
尝试更新beta-2，问题依然一样
v8.2.0自动更新下载后，poi就卡了，和之前一样。
手动下载更新，重装后依然不能运行Poi。
有什么记录可以上载帮忙？已经3天不能用Poi了

Try to update to beta-2 version, problem still remained.
using v8.2.0 auto update feature, poi will just hung and forced to close, same as previous update beta-1.
manual download, reinstall but still not able to run Poi.
any log needed to help to resolve the issue? it had been 3 days since the last i used Poi

**Comment by KochiyaOcean** [comment]
Win7 32 位这个条件限制太大，没有什么线索能够确定问题所在……

**Comment by PangCY1812** [comment]
刚测试了手动装v8.3.0，想测试自动更新，装载完毕后不能运行。
Window Event Viewer没有显示任何Poi不能运行的警告。

Test with manual install v8.3.0, to try the auto update feature, however Poi cant run after finish install
Window event viewer didnt show any warning message refer to Poi.

**Comment by KochiyaOcean** [comment]
%appdata%/poi 改个名试试看行不行
这个搞不定我也想不到别的解决方案了

**Comment by PangCY1812** [comment]
更改执行捷径还是档案名？
可以更具体地解释？

**Comment by KochiyaOcean** [comment]
![image](https://user-images.githubusercontent.com/8194131/44331013-666f6100-a4a3-11e8-9e73-63a1d713038d.png)
把这个 poi 文件夹改成别的（相当于重置数据

**Comment by PangCY1812** [comment]
执行结果如下：

![image](https://user-images.githubusercontent.com/42483836/44332409-8fd9be00-a49e-11e8-8bd5-f1c0ed572c06.png)

成功？

**Comment by KochiyaOcean** [comment]
运行 electron.exe

**Comment by PangCY1812** [comment]
搜索了整个硬盘，包括刚才的chromedriver文件内，查无此档。

**Comment by KochiyaOcean** [comment]
https://github.com/electron/electron/releases/download/v3.0.0-beta.5/electron-v3.0.0-beta.5-win32-ia32.zip 抱歉放错链接了，应该是这个

**Comment by PangCY1812** [comment]
第一次执行，类似Poi.exe，Task Manager显示确实有执行，只是大概3-5秒后就自动关闭。
之后再执行时，和Poi一样，直接在不出现在Task Manager里(没有执行？)

**Comment by KochiyaOcean** [comment]
也就是说这个不是 poi 能解决的范围了……

**Comment by PangCY1812** [comment]
怀疑是插件导致问题，重装v8.2.0，更改%appdata\Roam\poi档名，以便无视插件和之前的设定
然后用安全模式打开，自动更新下载完毕。出现系统通知关闭Poi以便升级。到目前为止和我的Win 7 64位元一样。

suspect plugin causing the issue, reinstall v.8.2.0, renaming the %appdata\Roam\poi folder name, this is to prevent plugin and previous configuration.
following with running Poi in safe mode, auto update feature download finish. Apps show notification to close Poi and update. This outcome was exactly same as my Win 7 64 bits.

![image](https://user-images.githubusercontent.com/42483836/44338095-7db44b80-a4af-11e8-9016-8c1da9e93eab.png)

准备关闭，看升级是否顺利。
Going to close Poi, check if the update go well

**Comment by PangCY1812** [comment]
开始更新:
start updating:

![image](https://user-images.githubusercontent.com/42483836/44338487-95d89a80-a4b0-11e8-818d-525290b60b2c.png)
估计升级完毕, Task Manager 里没有显示卸载和beta-2的process
assume update progress end, Task manager no longer show the old-uninstaller and Poi v9.0.0 beta-2 process

![image](https://user-images.githubusercontent.com/42483836/44338576-df28ea00-a4b0-11e8-955d-cd2dde48f245.png)

尝试运行Poi
Start run Poi to find out

**Comment by PangCY1812** [comment]
Program Files\poi 文件消失。另外%Appdata/Roam/Poi里有遗留 v9.0.0-beta-2安装档。看来，卸载v8.2.0是成功，只是安装v9.0.0-beta-2失败。完整重现了整个问题，剩下就看你们了

the folder in Program Files\Poi was missing. in the same time, %Appdata/Roam/Poi show v9.0.0-beta-2 installer was remained. It seems that uninstalling v8.2.0 was success, however v9.0.0-beta-2 install failed. reproduce scenario was success, i will leave the rest to you guys.

![image](https://user-images.githubusercontent.com/42483836/44338938-34193000-a4b2-11e8-8888-c87bbc9faa1a.png)

**Comment by PangCY1812** [comment]
主要是重现自动更新失败。手动安装beta-2基本上是成功，只是不能运行。
差别在于，自动更新时，安装档根本没运行。

至于免安装版，我beta-1已经尝试了，beta-2依然无功而返。

**Comment by gnattu** [comment]
上游bug electron/electron#12980
只发生在特定的Windows7下

**Comment by PangCY1812** [comment]
64位元是公司的，家里用32。看来无法肝了，只能暂时用ooi.moe凑合了，希望活动前解决 :\

**Comment by KochiyaOcean** [comment]
只能看上游吃饭了……

**Comment by PangCY1812** [comment]
还有3天就开始夏活了，依然期待beta-3(?)出现 :\

**Comment by KochiyaOcean** [comment]
@PangCY1812 上游不修我们也没法修，而且夏活没了现在是秋活（9 月 7 日开）

**Comment by KagamiChan** [comment]
beta.3 升级 electron 到了 3.0
不知道现在是否可以正常打开

**Comment by PangCY1812** [comment]
测试了beta-3，依然无解

**Comment by KochiyaOcean** [comment]
https://github.com/electron/electron/issues/12980 这个 issue 不修复的话应该是没希望的

**Comment by GreenDou** [comment]
从上游看到有中文就滚进来了……我们这边遇到的是跟鲁大师和360什么的冲突了，控制台 netsh winsock reset 重启后就可以使用了

**Comment by PangCY1812** [comment]
> 从上游看到有中文就滚进来了……我们这边遇到的是跟鲁大师和360什么的冲突了，控制台 netsh winsock reset 重启后就可以使用了

刚测试了，Poi可以启动了。感恩！！！
