### ISSUE TITLE
分离布局的下的建议

### ISSUE THREAD

**Issue by toooonyy** [poooi/poi#1877]
**poi 版本 / poi version:**
poi v9.0.0-beta.1

**操作系统 / OS:**

macOS 10.13.6
**插件名和版本 / Plugin name & version:**
<del>未卜先知 7.4.6</del>

**你遇到了什么样的问题 / The problem you've met:**
<del>1. 分离模式下主窗口无法变更大小，插件窗口正常。</del>
<del>2. 每次重新打开 Poi，主窗口无法显示全部游戏画面，需要下滑。</del>

建议：希望能在主窗口在最前时（同时插件面板被部分遮盖时）能使用 cmd+数字键快捷键来切换插件面版，并将插件面板放到前排。

追加：
<del>未卜先知无法看到双方装备，见图（确认跟插件窗口大小无关）</del>
![screen shot 2018-08-18 at 12 14 54](https://user-images.githubusercontent.com/3480434/44295675-74c14f80-a2e0-11e8-8518-0186c704b39e.png)

**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:**

**Comment by KochiyaOcean** [comment]
@toooonyy 游戏窗口能否缩放取决于分辨率设置；请提供截图

**Comment by toooonyy** [comment]
@KochiyaOcean 啊，原来是自己蠢了。。已改，但是顺便发现了一个未卜先知的 bug

**Comment by toooonyy** [comment]
bug 已均已修复
