### ISSUE TITLE
畫面太大 按不到下面的選項

### ISSUE THREAD

**Issue by hjk500221** [poooi/poi#1878]
**poi 版本 / poi version:**
9.0.0 beta1

**操作系统 / OS:**
Windows 7

**插件名和版本 / Plugin name & version:**

**你遇到了什么样的问题 / The problem you've met:**
畫面太大 按不到下面的選項

![default](https://user-images.githubusercontent.com/42486104/44295904-5a3da500-a2e5-11e8-8698-9f1ab4ec9aeb.jpg)

**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:**

**Comment by nikeio** [comment]
同问题

**Comment by SoraYama** [comment]
@nikeio 临时解决方案 ctrl+shift+i 到 console 选项卡下 输入 config.set('poi.webview.width', 800) 回车
