### ISSUE TITLE
调整到一定的游戏分辨率，舰娘头像显示错误

### ISSUE THREAD

**Issue by HawkingChen** [poooi/poi#1879]
**poi 版本 / poi version:**
9.0.0 beta1

**操作系统 / OS:** 
win10

**插件名和版本 / Plugin name & version:**

**你遇到了什么样的问题 / The problem you've met:**
本机测试中，只要宽度设置在1000<=widh<=1110的范围内(1111和999都没事)就会出现舰娘头像显示错误。
![qq 20180818140630](https://user-images.githubusercontent.com/18342961/44296021-3b90db80-a2f0-11e8-9e14-cfdb97483de5.png)
![qq 20180818140647](https://user-images.githubusercontent.com/18342961/44296022-3c297200-a2f0-11e8-8e86-ea5a57fab8d1.png)
![qq 20180818140925](https://user-images.githubusercontent.com/18342961/44296026-61b67b80-a2f0-11e8-81ae-2f0fa5e6de2f.png)
![qq 20180818140934](https://user-images.githubusercontent.com/18342961/44296027-61b67b80-a2f0-11e8-9cd2-eddbb9faf55a.png)

**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:**

**Comment by KochiyaOcean** [comment]
没有复现

**Comment by KochiyaOcean** [comment]
Fixed by 57f7201
