### ISSUE TITLE
Win 10 couldn't load plugin

### ISSUE THREAD

**Issue by Wafer-Li** [poooi/poi#188]
electron-v0.30.0-win32-x64
Win 10 Pro x64

I follow the instruction in README to run the application. But finally I got a **couldn't load plugin**
But when I download the files in **Release** and **[baidu](http://pan.baidu.com/s/1kT2zGwf)**, it works well.
I have try the `ia32` and the `x64` versions, the situation is totally the same.

**Comment by myzWILLmake** [comment]
Make sure that the path only contains English?

**Comment by Wafer-Li** [comment]
Yeap

**Comment by Wafer-Li** [comment]
And I place the electron folder in **the root of a driver**, it won't be the reason that the path is too long.
Actually, when I use win 7, I place it in the same location, it also worked well.

**Comment by myzWILLmake** [comment]
I have a try on my win10 tablet, it run well on electron-v0.30.0-win32-ia32 and Win 10 Pro x64.
If you want to run the application from git, ia32 is supported.

Don't put the folder in a long path.

**Comment by Wafer-Li** [comment]
Ok, I will have a try

**Comment by Wafer-Li** [comment]
@myzWILLmake 
I find that I haven't install FlashPlayer, but just only install the latest Chrome, does it cause the problem?

**Comment by myzWILLmake** [comment]
No. The flash in poi is unattached.

**Comment by Wafer-Li** [comment]
@myzWILLmake 
I copy a git version from my pad, then run `git pull`, and it solved right away. It seems that the reason is that my poor network

**Comment by Wafer-Li** [comment]
@myzWILLmake 
@magicae 
经过试验，好像是由于新的 `PepperFlash` 的 `DLL` 名字从 `pepflashplayer32.dll`  变成了 `pepflashplayer32_18_0_0_209.dll` 从而导致了 **couldn't load plugin** 的出现。

我重新克隆了一遍，然后把名字改回来之后就好了

**Comment by magicae** [comment]
哦突然想起来我忘了改

**Comment by Wafer-Li** [comment]
@magicae 
GMT+9 2015/7/25 21:50
commit SHA: 9d2b7fa9405f9517f2b1f8df2750ae438869dc6e
When I want to update the electron version to v0.30.1, I reclone it, but I find it hasn't been corrected yet.
![qq 20150725215315](https://cloud.githubusercontent.com/assets/12459199/8889494/a65c0c1a-3317-11e5-9518-34df46e3b226.png)

**Comment by magicae** [comment]
@Wafer-Li 
In the building progress, use `gulp` only with Electron win32 because of `gulpfile.coffee` now only downloads 32bit pepper flash. And I had renamed `pepflashplayer32_18_0_0_209.dll` to `pepflashplayer32.dll`

**Comment by Wafer-Li** [comment]
@magicae 
It's really weird.
I follow your instruction to download a new one. The file name still remain the **wrong** one.
But when I use `gulp build` command, the file name is **right**.
And I also try to click the link which is in the `gulpfile.coffee` to download, and I find the filename is also **right**.

**Comment by PHELiOX** [comment]
咦 我用了下windows的git版结果也是不能载入flash =。=

**Comment by Wafer-Li** [comment]
@PHELiOX 
这个问题应该已经修复了才对啊，看看Flash的名字对不对？

**Comment by PHELiOX** [comment]
@Wafer-Li 对的呀，而且我还从chrome里复制了一份新的过来。。

**Comment by PHELiOX** [comment]
把electron换成30.2 x86的就好了。。之前是30.4的x64.。。。

**Comment by magicae** [comment]
Pepper Flash我上传到七牛的只有32位的 所以用x64的会不能用

**Comment by PHELiOX** [comment]
我看chrome是直接pepflashplayer.dll，如果64位也能使用32位flash，共用一个dll是不是就行了？

**Comment by magicae** [comment]
不能用

**Comment by magicae** [comment]
不能用

**Comment by Wafer-Li** [comment]
@magicae 
既然出现了这个问题，那以后windows下的release 就只放x86的？

**Comment by magicae** [comment]
@Wafer-Li x64的release版我放了正确的x64 pepper flash…现在问题是我懒得加x64的windows判断到gulpfile里...
