### ISSUE TITLE
[Bug]截图时依旧使用旧的分辨率

### ISSUE THREAD

**Issue by DSakura1987** [poooi/poi#1880]
**poi 版本 / poi version:**
v9.0.0-beta.1

**操作系统 / OS:**
Windows 10 Version 1803

**你遇到了什么样的问题 / The problem you've met:**
截图时不能适应新的分辨率1200 * 720，依旧是800 * 480

**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:**

**Comment by DSakura1987** [comment]
我确定我设定的分辨率是正确的。
![poi](https://user-images.githubusercontent.com/4421906/44302235-c0c0c400-a2e1-11e8-989c-8c2120aad580.png)

**Comment by KochiyaOcean** [comment]
我这里是正常的
![image](https://user-images.githubusercontent.com/8194131/44302430-52244a80-a363-11e8-97ab-7de14c5970a6.png)

**Comment by DSakura1987** [comment]
好吧，让我清理一下。需要清理Appdata下面的那些文件夹？

**Comment by KochiyaOcean** [comment]
哦我知道了是分离窗口的问题
