### ISSUE TITLE
[Poi-9.0.0-beta.1] 遊戲視窗顯示位置不對

### ISSUE THREAD

**Issue by NikuPAN** [poooi/poi#1881]
**poi 版本 / poi version:** poi-9.0.0-beta.1

**操作系统 / OS:** Windows 10 x64 1803

**插件名和版本 / Plugin name & version:** N/A

**你遇到了什么样的问题 / The problem you've met:**

遊戲視窗顯示位置不對，視窗上方出現白邊，遊戲畫面最下方也被吃掉了一小部分。

**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:** 一開啟新版poi就這樣

![1534577426543](https://user-images.githubusercontent.com/28862516/44297015-021a9900-a30d-11e8-8994-b55999ebff94.jpg)

對比正常畫面

![1534577839149](https://user-images.githubusercontent.com/28862516/44297048-c7653080-a30d-11e8-9504-e8c5f48bc590.jpg)

**Comment by KagamiChan** [comment]
这是岛风 go 的问题，请咨询岛风 go 客服
