### ISSUE TITLE
更新HTML5之后任务信息面板及装备面板文字太纤细太淡 是否有增强渲染的方法？

### ISSUE THREAD

**Issue by castore** [poooi/poi#1883]
**poi 版本 / poi version:**
9.0.0 beta1

**操作系统 / OS:**

Win7 Professional
**插件名和版本 / Plugin name & version:**

**你遇到了什么样的问题 / The problem you've met:**

**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:**

**Comment by KochiyaOcean** [comment]
没有
