### ISSUE TITLE
Poi v9.0.0.beta-1版本下演习过程中最小化浏览器后暂停

### ISSUE THREAD

**Issue by KagerouClass** [poooi/poi#1884]
**poi 版本 / poi version:**
Poi v9.0.0.beta-1

**操作系统 / OS:**

Windows 10 17134.228
**插件名和版本 / Plugin name & version:**

**你遇到了什么样的问题 / The problem you've met:**
目前在打演习的时候，只要最小化整个poi浏览器，演习进度就会暂停，直到我下一次取消最小化poi浏览器，请问这个是h5二期的feature还是poi的glitch

**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:**

**Comment by KochiyaOcean** [comment]
HTML5 版本受到 [Page Visibility API](https://developer.mozilla.org/ja/docs/Web/Guide/User_experience/Using_the_Page_Visibility_API) 的影响，被判定为不可见的时候会停止动画等以减少性能消耗
