### ISSUE TITLE
最小化再次打开后自动刷新

### ISSUE THREAD

**Issue by SnowolFPoI** [poooi/poi#1885]
poi版本
9.0.0-beta1

操作系统：
MS Win 10 v.1803 Build 17134.228

你遇到了什么样的问题：
最小化后再次打开就会自动刷新页面

重现方式：
最小化后再次打开

**Comment by KochiyaOcean** [comment]
重新载入页面？

**Comment by ccen3020** [comment]
我这面是最小化一段时间后再恢复，poi界面会死一阵，布局死掉，游戏画面电机没反应，但是游戏看上去是在正常运行的

**Comment by SnowolFPoI** [comment]
对的，重新载入页面。
打到一半然后最小化了一下，再打开就emmmm
我的士气值因为这个掉了好几次。。。。。。

**Comment by SnowolFPoI** [comment]
bata2版本也实验了，依旧如此。。。。

**Comment by doomedtraveler** [comment]
我也有这个问题，win10六十四位系统

**Comment by KochiyaOcean** [comment]
开发者工具是否有报错信息

**Comment by doomedtraveler** [comment]
@KochiyaOcean 欸。。报错如果是指弹出窗口的话没有，最小化后再恢复就像是我摁了刷新一样

**Comment by KochiyaOcean** [comment]
@doomedtraveler 是否稳定复现

**Comment by doomedtraveler** [comment]
@KochiyaOcean 复现？ 嗯就是白屏一下然后回到开始游戏界面

**Comment by KochiyaOcean** [comment]
@doomedtraveler 就是每次最小化都肯定刷新的意思

**Comment by doomedtraveler** [comment]
@KochiyaOcean 嗯，是的大佬

**Comment by KochiyaOcean** [comment]
@doomedtraveler 使用分离模式时，最小化游戏窗口是否刷新

**Comment by doomedtraveler** [comment]
@KochiyaOcean 分离模式是哪个。。（丢人）

**Comment by KochiyaOcean** [comment]
![image](https://user-images.githubusercontent.com/8194131/44654022-4acc0380-aa2b-11e8-9e02-73fd379da192.png)
@doomedtraveler

**Comment by doomedtraveler** [comment]
@KochiyaOcean ！！大佬可以了

**Comment by KochiyaOcean** [comment]
@doomedtraveler 顺便问一下，使用的是什么连接方式

**Comment by doomedtraveler** [comment]
@KochiyaOcean 忘记说了，我用的ooi，因为我不知道怎么把我的蓝灯拿来上舰23333

**Comment by KochiyaOcean** [comment]
@doomedtraveler https://ci.appveyor.com/project/KochiyaOcean/poi/build/artifacts 试试看这里的版本在非分离模式下的情况

**Comment by doomedtraveler** [comment]
@KochiyaOcean 对不起，似乎浪费了大佬的时间，我改了改poi配置挂上蓝灯（一款vpn）之后即使不使用分离模式也不会出现之前的问题，但是用ooi.moe提供的方式不用分离模式仍有问题，所以大概是ooi的问题，而不是poi浏览器的。

**Comment by KochiyaOcean** [comment]
@doomedtraveler 如果可能的话还是麻烦用 ooi 测试一下

**Comment by doomedtraveler** [comment]
@KochiyaOcean 大佬给的三个都可以，我用的不行。。总之大概与ooi的相性是9.0.0.2862 ❌（我之前用的版本）
9.0.0.2925 ✔ 的样子

**Comment by SnowolFPoI** [comment]
表示现在比较稳定了，刷新状况有时发生

**Comment by Cuiyn** [comment]
这里使用macOS下的9.0.0-beta2+ooi遇到了类似的问题。macOS有个功能是全屏的窗口左右切换，在全屏化poi后，切出再切回，游戏画面会刷新。把poi放在桌面，从其它窗口切回桌面也会使游戏刷新。以上均能够稳定复现。使用代理直连无此问题，其它网站也没有观察到类似问题。使用分享模式也无此问题。希望能有参考价值。
