### ISSUE TITLE
黑屏 全黑的那种 连插件都没有显示~

### ISSUE THREAD

**Issue by RemiliaSeven** [poooi/poi#1886]
**poi 版本 / poi version:8.2.0 和 9.0.0

**操作系统 / OS: win7

**插件名和版本 / Plugin name & version:只有一个一心二用

**你遇到了什么样的问题 / The problem you've met:打开后所有界面都没有加载，只是黑屏状态，什么都没有，卸载后重新安装也没有用，8.20或者9.00都是一样的，重启也解决不了，appdata/Roaming里没有poi的文件夹，ACGP正常，chrome浏览器可以玩，但是poi界面什么都没有

![qq 20180818230418](https://user-images.githubusercontent.com/42496163/44300598-42454000-a33c-11e8-9490-f15d9acbb6c9.png)

然后用CMD打开后显示 
![qq 20180818230431](https://user-images.githubusercontent.com/42496163/44300602-5a1cc400-a33c-11e8-81d9-66ce25d364a2.png)

**Comment by RemiliaSeven** [comment]
电脑是重装过的 没有安装杀毒软件 下载的安装版的 还有硬盘版 都一样 还是什么都不显示 开服前倒是正常打开过 用一心二用这个插件上过新版的游戏 然后POI主程序就成这样了 当时没有在意 结果发现一直变成这样了。求问 POI在C盘的缓存或者配置位置记录在哪 我删了试试

**Comment by KochiyaOcean** [comment]
@RemiliaSeven 都在 %appdata%/poi 里面

**Comment by RemiliaSeven** [comment]
问题解决了 非常抱歉 打扰了 在 用户\AppData\Roaming里删了POI的缓存和设置里 成功出现插件了
