### ISSUE TITLE
遊戲畫面無法 變換

### ISSUE THREAD

**Issue by Yamoshilo** [poooi/poi#1887]
**poi 版本 / poi version:**
poi-setup-9.0.0-beta.1

**操作系统 / OS:**

**插件名和版本 / Plugin name & version:**
無

**你遇到了什么样的问题 / The problem you've met:**

遊戲畫面太大 [無法自動縮放]([url](url))

可以的话请提供开发者工具 Console 选项卡的截图，
开发者工具的打开方式是按 ctrl + shift + i (macOS 上为 ⌥ + ⌘ + i），或游戏区域下方信息栏的最左边齿轮按钮。
Please provide a screenshot of developer tool's console tab, if possible.
To open the dev tool, press ctrl + shift + i (⌥ + ⌘ + i for macOS), or the leftmost gear button on the info bar below the game area.
-->
![2018-08-18](https://user-images.githubusercontent.com/42496919/44300901-d2858400-a340-11e8-8687-9461459b1482.png)

**Comment by KochiyaOcean** [comment]
你这个不是 9.0.0 吧

**Comment by marktheonlyone** [comment]
我也有同样的问题，版本是8.2.0

**Comment by KagamiChan** [comment]
@marktheonlyone 游戏更新了，请使用 9.0.0-beta.1
