### ISSUE TITLE
无法显示舰娘头像

### ISSUE THREAD

**Issue by Ziziru** [poooi/poi#1889]
**poi 版本 / poi version:**9.00 beta1

**操作系统 / OS:**win10  1803 17713.1002

**插件名和版本 / Plugin name & version:**

**你遇到了什么样的问题 / The problem you've met:**
重启poi，还是开关舰娘头像这个选项，都没有头像显示

![annotation](https://user-images.githubusercontent.com/21362277/44304988-042d3800-a39f-11e8-9f0c-29146bd69555.png)

**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:**

**Comment by KochiyaOcean** [comment]
打开开发者工具在 console 输入 `getStore('info.server.ip')` 回车是什么结果

**Comment by Ziziru** [comment]
![annotation 1](https://user-images.githubusercontent.com/21362277/44305045-d2b56c00-a3a0-11e8-912c-7f6c84458e3f.png)
这样的

**Comment by KochiyaOcean** [comment]
`$('.ship-avatar').src` 呢

**Comment by Ziziru** [comment]
没有出现过

**Comment by KochiyaOcean** [comment]
![image](https://user-images.githubusercontent.com/8194131/44305197-e797fc80-a3ac-11e8-9332-499dfdca6331.png)
![image](https://user-images.githubusercontent.com/8194131/44305201-fbdbf980-a3ac-11e8-9b8d-c0075cdca1c3.png)
看一下 `$('.ship-avatar')` 的定位是不是这样的

**Comment by Ziziru** [comment]
![21](https://user-images.githubusercontent.com/21362277/44305258-c384ed00-a3a5-11e8-8aa2-68d33b8f72f2.png)

**Comment by KochiyaOcean** [comment]
![image](https://user-images.githubusercontent.com/8194131/44305266-6d687780-a3ae-11e8-80a2-f01965e9e919.png)
这样定位到 DOM tree 上
![image](https://user-images.githubusercontent.com/8194131/44305267-7bb69380-a3ae-11e8-949e-6346be182be5.png)
看看这边的 style 是什么样的

**Comment by KochiyaOcean** [comment]
![image](https://user-images.githubusercontent.com/8194131/44305273-bd473e80-a3ae-11e8-983a-7671dc374448.png)
上一级也看一下

**Comment by wwftherocksp** [comment]
我这边也是无法显示头像，看network是有请求图片的，但是请求成功后preview什么都没显示
用的是锅go，换自己的代理之后可以显示头像了，我猜是锅go的锅

**Comment by wwftherocksp** [comment]
看到请求回来的链接是这个：
http://203.104.209.55//kcs2/resources/ship/banner/0436_9196.png?version=15
http://203.104.209.55后有两个反斜杠，锅go打开这个图片的时候是打开不了的，要去掉一个反斜杠

**Comment by KochiyaOcean** [comment]
Fixed by b74d093

**Comment by KochiyaOcean** [comment]
那么去 https://ci.appveyor.com/project/KochiyaOcean/poi/build/artifacts 下载每夜版就可以了

**Comment by Ziziru** [comment]
对，我也发现我style设置并没有问题，问题出在请求的连接
http://125.6.189.39//kcs2/resources/ship/banner/0109_8157.png?version=22
后面125.6.189.39后面是双反斜杠，去掉一个就能正常显示图片，这个该如何修改回来？

**Comment by KochiyaOcean** [comment]
@Ziziru 看上面的链接
