### ISSUE TITLE
請問可以透過poi來魔改字型嗎?

### ISSUE THREAD

**Issue by jianhuatw** [poooi/poi#1893]
**poi 版本 / poi version:**
9.0.0-Beta1

**操作系统 / OS:**
WIN7

**你遇到了什么样的问题 / The problem you've met:**
內建的字型太細了，請問可以透過poi來魔改字型嗎?

**Comment by KochiyaOcean** [comment]
理论上可行

**Comment by KagamiChan** [comment]
/kcs2/resources/font/A-OTF-UDShinGoPro-Light.woff2

替换掉这个说不定就可以

**Comment by KagamiChan** [comment]
/kcs2/css/main.css

或者直接把 font_j 对应的 woff 改掉也行

**Comment by jianhuatw** [comment]
/kcs2/resources/font/A-OTF-UDShinGoPro-Light.woff2  這個路徑是在哪裡呢?
