### ISSUE TITLE
POI在后台时不能弹出通知

### ISSUE THREAD

**Issue by SkywalkerJi** [poooi/poi#1894]
**poi 版本 / poi version:**
V9.0.0-beta.1

**操作系统 / OS:**

win10 1709（16299.547）

**插件名和版本 / Plugin name & version:**

**你遇到了什么样的问题 / The problem you've met:**
poi最小化或者在后台时不会弹出远征完成等通知。平时玩的时候正常。
之前的版本也不会弹。

**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:**

**Comment by KagamiChan** [comment]
这个问题是否还存在？
我前不久使用的时候觉得通知是正常的
