### ISSUE TITLE
游戏窗口设置大小与实际不一致

### ISSUE THREAD

**Issue by ntqjz** [poooi/poi#1895]
**poi 版本 / poi version:**
9.0.0-beta.1

**操作系统 / OS:**

win10 1803 (17134.228)
**插件名和版本 / Plugin name & version:**

**你遇到了什么样的问题 / The problem you've met:**
对poi禁用高DPI缩放后仍然是和系统设置一样的125%缩放的状态。
![image](https://user-images.githubusercontent.com/21212113/44309973-720a4b80-a401-11e8-8b07-f5db64922a5e.png)

如图，窗口实际宽度已经有800而设置显示的是640，用poi的截图功能也只能截出640×384的图片。
![image](https://user-images.githubusercontent.com/21212113/44309976-7fbfd100-a401-11e8-9faa-d34b27bf9072.png)

**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:**

**Comment by KochiyaOcean** [comment]
Chrome 内核行为如此。
需要强制指定缩放比率请加上参数 `--force-device-scale-factor=1` 运行（在快捷方式的目标后加上这条

**Comment by ntqjz** [comment]
加上这个以后确实有用，但是关闭poi后再次打开时发现快捷方式属性里这条参数又没了，回到了和修改之前一样的状态。请问这有什么解决方法吗？

**Comment by KochiyaOcean** [comment]
@ntqjz 你另外建一个快捷方式
