### ISSUE TITLE
poi v9.0.0 beta-2 存在明显的掉帧卡顿问题

### ISSUE THREAD

**Issue by Colonel-Colt** [poooi/poi#1900]
**poi 版本 / poi version:9.0.0 beta-2**

**操作系统 / rOS:Windows 10 版本号1803**

**插件名和版本 / Plugin name & version:**

**你遇到了什么样的问题 / The problem you've met:掉帧，卡顿**

**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:无论开启还是关闭硬件加速都卡顿。 CPU i7-7700 内存16G 显卡GTX1080**

**Comment by KochiyaOcean** [comment]
@Colonel-Colt 性能问题没法修，田中修了我再修

**Comment by KagamiChan** [comment]
显示器是 4k 的吗

**Comment by KochiyaOcean** [comment]
我 i7 7700HQ + 1050 + 4k 屏幕 2 块完全没问题，说明完全不是配置因素导致的……

**Comment by KochiyaOcean** [comment]
还是试试看每夜版能不能解决 https://ci.appveyor.com/project/KochiyaOcean/poi/build/1.0.2872/artifacts
没办法的话这里也没什么办法，现在阶段的性能问题太玄学了

**Comment by Colonel-Colt** [comment]
用chrome不掉帧，poi就掉，应该是poi问题，我试试每夜版

**Comment by KochiyaOcean** [comment]
poi 和 chrome 的内核版本号不一样，不知道差别在哪里
就算知道了也没法解决，这不是 poi 的代码能左右的事情

**Comment by Colonel-Colt** [comment]
每夜版能解决问题

**Comment by KochiyaOcean** [comment]
干我对这玄学的世界绝望了

**Comment by constantinevi6** [comment]
poi 版本 / poi version:9.0.0 beta-2

操作系统 / rOS: macOS High Sierra (MacBook Air Mid2013)

插件名和版本 / Plugin name & version:

你遇到了什么样的问题 / The problem you've met:同樣掉帧，卡顿

有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:卡頓，同時處理器佔用率極高(poi跟一個poi helper會佔用70% up)，在safari或chrome上開遊戲執行很順暢，硬體資源佔用也不會這麼誇張。

**Comment by KochiyaOcean** [comment]
@constantinevi6 请参照上面的评论
