### ISSUE TITLE
艦娘沒有語音

### ISSUE THREAD

**Issue by XxJimmy122xX** [poooi/poi#1902]
**poi 版本 / poi version:**
v9.0.0-beta.2

**操作系统 / OS:**
Window 10 (1803)

**你遇到了什么样的问题 / The problem you've met:**
艦娘沒有語音

**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:**
Chrome打開表現正常，Poi打開沒有語音。

以下方法無法解決問題:
更新POI版本
刪除POI
刪除%appdata%/poi/cache
重開機
清除Cookie, Cache

**Comment by absence19** [comment]
同样的问题，请问楼主解决了吗
