### ISSUE TITLE
组件位置总是会自动跳

### ISSUE THREAD

**Issue by cmt76711** [poooi/poi#1907]
**poi 版本 / poi version:9.0.1和9.0.2
![poi](https://user-images.githubusercontent.com/26247653/44501977-f1f11980-a67e-11e8-9fe2-a1c78746dade.gif)

**操作系统 / OS:windows10

**插件名和版本 / Plugin name & version:**

**你遇到了什么样的问题 / The problem you've met:组件位置总是会自动变

**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:**

**Comment by KochiyaOcean** [comment]
@cmt76711 在快捷工具栏关闭编辑模式看看
