### ISSUE TITLE
请问有没有 macOS 的 nightly build 版本？

### ISSUE THREAD

**Issue by nasyxx** [poooi/poi#1908]
**poi 版本 / poi version:**
9.0.0-beta2

**操作系统 / OS:**

macOS Mojave

**你遇到了什么样的问题 / The problem you've met:**

请问有没有 macOS 的 nightly build 版本？最近这个一直会卡住不动（

**Comment by KochiyaOcean** [comment]
@nasyxx Travis CI 暂时不支持

**Comment by KagamiChan** [comment]
@nasyxx 你是说 9.0.0-beta.2 会卡着不动吗……
不知道是不是 Mojave 的原因，我这边 sierra 上是可以的

目前暂时没有提供 macOS 的 nightly 的计划

**Comment by nasyxx** [comment]
是的，也许是 Mojave 的问题。也难说是网络的问题。卡住不动后，我一点刷新页面，他就开始动，然后开始刷新（

但是卡住的时候，我很确定，网络请求是已经完成。

没有提供的话就算了...我再忍几天吧！

感谢！

**Comment by nasyxx** [comment]
我看到这个 commit 可能解决了问题 
https://github.com/poooi/poi/commit/1cd2ddc97d44951f5e3fe3f653162512ed1dfdd9

**Comment by KagamiChan** [comment]
你是在用 git 上的 master 版本还是下载好的呀

我刚才试了一下打包好的版本在 high sierra 下面也没问题

**Comment by nasyxx** [comment]
@KagamiChan GitHub 上下载的 dmg. 没事，我等下一个 beta 或者 再次出现的时候，我打开 dev 看看...

**Comment by nasyxx** [comment]
我重新下了一次后，一直没再出现卡住了，可能真是网络问题
