### ISSUE TITLE
poi游戏界面窗口模式

### ISSUE THREAD

**Issue by euareless** [poooi/poi#1910]
我现在是9.0.0版本
![Uploading image.png…]()
每次登陆后游戏界面都会有拉条，改了游戏分辨率之类的都没法去掉= =

**Comment by KochiyaOcean** [comment]
是否使用 ooi

**Comment by euareless** [comment]
是的

**Comment by KochiyaOcean** [comment]
ooi 的页面残留了一些一期的代码导致了这个问题，已经知会 ooi 开发者，应该近期会修复

**Comment by euareless** [comment]
好的，谢谢，打扰到您了
