### ISSUE TITLE
8.2.0版本使用ooi为主页游戏界面无法完全显示（分辨率有问题）

### ISSUE THREAD

**Issue by niconicocnico** [poooi/poi#1911]
**poi 版本 / poi version:**

**操作系统 / OS:**

**插件名和版本 / Plugin name & version:**

**你遇到了什么样的问题 / The problem you've met:**

**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:**

**Comment by KochiyaOcean** [comment]
ooi 网站的问题，似乎已经修复了才对

**Comment by KochiyaOcean** [comment]
![image](https://user-images.githubusercontent.com/8194131/44621897-97a7c100-a8e9-11e8-9867-670e97a70826.png)
已确认修复
