### ISSUE TITLE
對應二期高解析度的版面配置更動

### ISSUE THREAD

**Issue by sam910037** [poooi/poi#1912]
**poi 版本 / poi version:**

poi v9.0.0-beta.2
**操作系统 / OS:**

Windows 10 1803 x64

**你遇到了什么样的问题 / The problem you've met:**
二季改為1280x720解析度後poi介面幾乎都會以1920x1080全螢幕執行，但是UI介面還是原本480的配置，導致下方空了一大塊
![example1](https://i.imgur.com/erZU01N.png)
使用插件與UI切分卻又只有左右切分，結果就成了這樣
![example2](https://i.imgur.com/aADPYM0.png)
下方還是空了一大塊

**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:**
可以將插件和UI切分改成可選左右或上下嗎?基本上這年頭大部分顯示器都會到1080的解析度了，如果可以上下切分應該更能有效的利用螢幕空間

**Comment by KochiyaOcean** [comment]
15 寸笔记本的 1080p 屏幕实质分辨率只有 864px
目前可以使用自定义 css 进行上下切分，作为功能实装则需要再做讨论
以及受不了空白可以考虑使用窗口分离模式，或者在快捷工具栏里面开启编辑模式编辑主面板

**Comment by KochiyaOcean** [comment]
顺便个人的用法是继续使用 800*480 分辨率

**Comment by Squall-Lucifer** [comment]
想問一下POI能否追加一個版面配置，是將遊戲本體的畫面放置在4個角落，之後用各個add-on包圍著它呢?現在主畫面上下方都浪費了很多空間

**Comment by KochiyaOcean** [comment]
@Squall-Lucifer 自己改自定义 css 可以，不过要改成能让大部分屏幕都能获得比较好的显示效果则很难，暂时不考虑做成通用设置

**Comment by KochiyaOcean** [comment]
@Squall-Lucifer 实现比较麻烦，我有空的时候看看……

**Comment by Squall-Lucifer** [comment]
多謝開發者的努力Poi !

**Comment by deepsea666** [comment]
要是能实现Squall-Lucifer 说的这种板面，那使用观感能提升不少，毕竟都二期了，还是只能用800*480有点浪费高清了

**Comment by KochiyaOcean** [comment]
@deepsea666 其实并不是没有做过，只是效果实在不好所以最后放弃了而已

**Comment by KochiyaOcean** [comment]
![image](https://user-images.githubusercontent.com/8194131/44777469-b4781900-abb5-11e8-9cc9-e7c4a2aa4b73.png)
@Squall-Lucifer @deepsea666 简单的讲就是会便乘这种情况（1080P 1 倍率缩放的场合）

**Comment by sam910037** [comment]
@KochiyaOcean 
可能我講得太模糊，簡單用小畫家弄出一張圖
![](https://i.imgur.com/PC0VuDr.png)
插件可選放左或放右，就跟現在的一樣，至於 @Squall-Lucifer 說的那種圍繞式的就改成放在上或下方，然後列為可選用，畢竟不是每個人都想塞好塞滿

**Comment by KochiyaOcean** [comment]
@sam910037 plug1 实现不是很难而且准备做，plug2 的位置太小价值不高，而且要改的地方太多，短期内就不考虑了

**Comment by sam910037** [comment]
@KochiyaOcean 
感謝開發群的努力

**Comment by deepsea666** [comment]
_
![qq 20180829174418](https://user-images.githubusercontent.com/21211204/44780075-b345ec80-abb3-11e8-8791-cfc3130c0964.png)
_
@KochiyaOcean 
这是我在1980*1080的情况下的布置
实际上 PLUG2 很适合用来放概览里的那些面板，也就是舰队那一块会显得高度差了那么一行，不过实际上有了右边的舰队，下面那个已经可有可无了

**Comment by KochiyaOcean** [comment]
@deepsea666 重点在于 “改的地方太多”
本组的活人一只手就能数过来了而且手指还有剩 OTL

**Comment by Squall-Lucifer** [comment]
能更有效利用畫面空間實在太好了，感謝開發組各位(｀・ω・´)ｂ

**Comment by KochiyaOcean** [comment]
https://ci.appveyor.com/project/KochiyaOcean/poi/build/1.0.2943/artifacts 已经实现，可以试试看这个版本了

**Comment by Squall-Lucifer** [comment]
@KochiyaOcean 請問能否提供你這的CSS參考一下?
https://user-images.githubusercontent.com/8194131/44777469-b4781900-abb5-11e8-9cc9-e7c4a2aa4b73.png
@deepsea666  同求你這配置的CSS
https://user-images.githubusercontent.com/21211204/44780075-b345ec80-abb3-11e8-8791-cfc3130c0964.png

**Comment by deepsea666** [comment]
@Squall-Lucifer 
我这个游戏画面下方的概览是PS过去的，只是用来示意一下我理想中的布局

**Comment by KochiyaOcean** [comment]
完全针对窗口大小糊的，窗口大小一改就会崩，不建议套用这套 css

**Comment by Squall-Lucifer** [comment]
ORZ
