### ISSUE TITLE
History of Poi Viewer

### ISSUE THREAD

**Issue by fajarmf94** [poooi/poi#1918]
i want to ask about this poi viewer history, when it was born and the story behind this poi viewer
cos after kc3kai isn't good for me now especially for HTML 5 right now, i move to Poi Viewer. this viewer is one of my alternate viewer after KCV Grabacr07 will not update again. but back then poi still hard to use for me then i choose kc3
and then after HTML 5 is release, i move to poi viewer to get more stable then use chrome with kc3kai

so cos i want to introduce this viewer to my friend, i want to know about the history for this viewer

**Comment by KochiyaOcean** [comment]
Did you mean changelog?
