### ISSUE TITLE
Poi Viewer plugin conflict

### ISSUE THREAD

**Issue by fajarmf94** [poooi/poi#1919]
my poi viewer now is broken, it can not open the game page
the first problem is when poi get conflict with secretary plugin and subtitle plugin, i try to reinnstall them and it's not work, i try to delete that plugin the game still not open the page and i try to reinstall it's not working

anyone know how to full unsintall this poi viewer? so i can restart all the setting that i do before, because when i reinstall poi, it still same setting

screenshot error
https://cdn.discordapp.com/attachments/367575898313981952/484129601434681345/unknown.png

**Comment by gakada** [comment]
On Windows you can open `%APPDATA%\poi` in Explorer (will be something like `C:\Users\Your User\AppData\Roaming\poi`). That is the config folder with settings, plugins, browser stuff, etc.

**Comment by KochiyaOcean** [comment]
Check your network config (proxy, etc) and trying delete you cache in setting
