### ISSUE TITLE
程式內遊戲螢幕跑掉

### ISSUE THREAD

**Issue by bigtnt01** [poooi/poi#1922]
**poi 版本 / poi version:**

**操作系统 / OS:**

**插件名和版本 / Plugin name & version:**

**你遇到了什么样的问题 / The problem you've met:**

程式內遊戲螢幕跑掉
**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:**

**Comment by KochiyaOcean** [comment]
@bigtnt01 更新到 9.0 测试版
