### ISSUE TITLE
poi運行不久會完全卡死，但是遊戲畫面左上角的齒輪仍在轉動

### ISSUE THREAD

**Issue by Davinais** [poooi/poi#1925]
**poi 版本 / poi version:**
poi v9.0.0-beta2

**操作系统 / OS:**
 Linux Mint 17 64bit Kernel 3.13.0-139-generic

**插件名和版本 / Plugin name & version:**

**你遇到了什么样的问题 / The problem you've met:**
打開poi過後不久，試著點開補給或者圖鑑等需要讀取艦娘資料的部分，過不久之後整個poi會愈來愈頓最後卡死，不過這期間遊戲左上角的齒輪仍然會繼續轉動

已測試過以Chrome v68.0.3440.106 並不會發生此現象，得以正常運行

**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:**
![](https://user-images.githubusercontent.com/5267712/44810155-6f7ad380-ac03-11e8-85e5-73d8635c94c9.png)

**Comment by KagamiChan** [comment]
@Davinais 有没有观察过记忆体的使用量情况？

**Comment by KagamiChan** [comment]
那就是 cpu 和记忆体的占用都没有满，但是游戏会卡死吗

这个还没有其它 linux 用户来反馈过类似现象，如果关掉所有的扩展的话，也是一样吗

**Comment by Davinais** [comment]
@KagamiChan 關掉所有的擴展還是會有一樣的情形
不過有個新的分別，就是現在卡住的時候記憶體跟CPU會飆高了，而且只能強制結束程序才能停止
![](https://user-images.githubusercontent.com/5267712/44959477-5c2c7880-af21-11e8-840e-b2acba3aa06f.png)

另外一提就是左上角的補給還是會動的，只是沒辦法點了，視窗整個卡死

**Comment by Davinais** [comment]
下載v9.0.0-beta3版本已經無此現象，應該是暫時沒有問題了
