### ISSUE TITLE
Way too zoomed in

### ISSUE THREAD

**Issue by liminalitythree** [poooi/poi#1927]
**poi 版本 / poi version:**
8.2.0

**操作系统 / OS:**

windows 7

**插件名和版本 / Plugin name & version:**

**你遇到了什么样的问题 / The problem you've met:**

The viewer is really zoomed in, I tried changing the display settings but I couldn't find any way to get it to zoom out.

![capture](https://user-images.githubusercontent.com/30793687/44938615-51b18980-ad3d-11e8-80fc-91607eb53039.PNG)

**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:**

**Comment by masashik16** [comment]
poi v 8.2.0 only supports resolution around Adobe Flash. If you play this, use v9.0.0 beta2 or wait for an update.

Translate by Google. JP to EN

**Comment by liminalitythree** [comment]
Upgrading to v9.0.0 beta2 worked. Thanks!
