### ISSUE TITLE
浮窗有时候会出现不消失的情况

### ISSUE THREAD

**Issue by Westernnero** [poooi/poi#1928]
**poi 版本 / poi version:**

**操作系统 / OS:**

Win10 1803

**插件名和版本 / Plugin name & version:**

**你遇到了什么样的问题 / The problem you've met:**
鼠标移到舰船上悬停，出现的那个装备的浮窗，有时候会出现不消失的情况。会遮挡界面。
可以参考截图：https://wx4.sinaimg.cn/mw690/64de23b2gy1futv2dufocj21bo0lbhdt.jpg

**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:**

**Comment by KagamiChan** [comment]
这个属于已知问题，重新移动到原来的舰船上可以解除掉

需要等上游的更新，目前还没有确切的修复时间……

**Comment by KochiyaOcean** [comment]
fixed
