### ISSUE TITLE
POI 视窗底部出现白边,任务栏的翻页被遮挡

### ISSUE THREAD

**Issue by LING996** [poooi/poi#1929]
**poi 版本 / poi version:**

9.0.0-beta2
**操作系统 / OS:**

Windows 10    10.0.17134.228
**插件名和版本 / Plugin name & version:**

**你遇到了什么样的问题 / The problem you've met:**

视窗底部出现白边

**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:**
![2018-9-1t21 29 45](https://user-images.githubusercontent.com/42892167/44946408-8cdfb580-ae2e-11e8-993d-e2e6f7702963.png)

**Comment by KagamiChan** [comment]
请试试 beta.3
