### ISSUE TITLE
Add an ability to set DMM cookie's region flag

### ISSUE THREAD

**Issue by seishun** [poooi/poi#193]
See here: http://kancolle.wikia.com/wiki/Tutorial:_Proxy_Connection#Option_1:_Editing_DMM_Cookie.27s_Region_Flag_RECOMMENDED

This allows logging in without using a VPN.

**Comment by KochiyaOcean** [comment]
Right-click the Developer Tool icon in the quick setting bar, then you can set DMM cookies' in the Developer Tool's window.

**Comment by seishun** [comment]
How? I tried pasting the lines from the wiki, but it doesn't work. It seems the developer tools work in the context of the Electron window, rather than the website frame.

**Comment by KochiyaOcean** [comment]
If you left-click on the icon you could get developer tools of the Electron window, and if you right-click on the icon there will be the developer tools of webview frame.

**Comment by seishun** [comment]
Oh, that worked. For some reason it didn't work on the first try. But I would like to suggest adding an option that would do this automatically. What do you think?

**Comment by KochiyaOcean** [comment]
Fixed by https://github.com/poooi/poi/commit/17ea6d209931e1426e7250c464f34be1108e4f4f
