### ISSUE TITLE
用poi放后台一段时间后，游戏会白屏然后重新加载 

### ISSUE THREAD

**Issue by rinyama** [poooi/poi#1937]
poi 版本 / poi version:9.0 beta2

**操作系统 / OS:**

**插件名和版本 / Plugin name & version:**

**你遇到了什么样的问题 / The problem you've met:**
如题，最小化到后台会重新加载游戏

**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:**

**Comment by KochiyaOcean** [comment]
已修复
