### ISSUE TITLE
9.0.0 beta.3 未卜先知插件竖屏下显示问题

### ISSUE THREAD

**Issue by yortiss** [poooi/poi#1939]
**poi 版本 / poi version:**
9.0.0 beta.3

**操作系统 / OS:**
 win10 1803

**插件名和版本 / Plugin name & version:**
未卜先知  Ver.7.6.1

**你遇到了什么样的问题 / The problem you've met:**
这个版本竖屏幕下，无法显示完全编队信息，看完整的需要鼠标滚动，略微不方便，现在是上下结构，以前版本是左右并排。 PS：屏幕分辨率1920X1080. 游戏分辨率800X480.

**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:**

![capture2](https://user-images.githubusercontent.com/19453236/45156377-fbe75080-b218-11e8-835e-9ae64db27a6b.JPG)
![capture3](https://user-images.githubusercontent.com/19453236/45156387-00136e00-b219-11e8-9c24-26ac4cc7b18d.JPG)

**Comment by KagamiChan** [comment]
已发布 7.7 版
