### ISSUE TITLE
v9.0.0-beta.3无法运行

### ISSUE THREAD

**Issue by Donchka** [poooi/poi#1941]
**poi 版本 / poi version:**9.0.0-beta3

**操作系统 / OS:**windows10 Home 1803

**插件名和版本 / Plugin name & version:**

**你遇到了什么样的问题 / The problem you've met:**尝试运行时弹出错误会话框“The procedure entry point avcodec_send_packet could not be located in the dynamic link library E:\...\poi\poi.exe.”

**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:**

**Comment by KochiyaOcean** [comment]
重新下载安装包安装看看
