### ISSUE TITLE
9.0.0-beta.3 的缩放比率对截图和游戏画面的影响，及文字上偏

### ISSUE THREAD

**Issue by HAzzZ7** [poooi/poi#1942]
**poi 版本 / poi version:**

v9.0.0-beta.3

**操作系统 / OS:**

windows 10 1803 (17134.228) 和 1709 (16299.492)

**你遇到了什么样的问题 / The problem you've met:**

1. 设置-显示设置-缩放比率，对截图大小的影响
2. 上述缩放比率对游戏画面的奇怪影响
3. 游戏中非缓存的文字会向上偏若干像素（相比 Chrome 的游戏画面）

**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:**

关于 1：
截图的横纵像素数都会除以缩放比率，即：若游戏分辨率为 1200\*720，缩放比率为 150%，那么截图大小将会是800\*480。<del>这应该不是 feature 吧</del>

关于 2：
简单说就是缩放比率对游戏分辨率和 poi 对游戏画面大小的判断造成 1 像素的偏差。
具体来说将缩放比率设为 100%，勾选“设置固定分辨率”，选择内置的 67%，此时下方的分辨率显示为 800\*480，然后
1）将缩放比率设置为 105%，此时分辨率自动变为 799\*479，输入分辨率 801，分辨率自动变为 800\*480，缩放比率设置为 100%，分辨率自动变为 801\*481。此现象在缩放比率设置为 90%、105%、120%、135%、145% 出现，更大的缩放比率未测试。
2）将 poi 窗口左右收缩到最窄，此时窗口与游戏画面等宽，宽度为 800 且不可再缩窄，将缩放比率改为 55%~75%、85%~95%、105%~120%、130%~155%，窗口可再缩窄 1 像素，除1）中所述缩放比率外，会导致游戏画面最右侧一列像素被遮挡在窗口范围外。

上述两个现象在 beta.2 里应该是不存在的，推测是缩放比率参与了一些计算，且存在精度下溢。

关于3：
在 poi 中以缩放比率 100%，游戏分辨率 1200\*720 截图（），对比在 Chrome (69.0.3497.81) 中以右键保存的截图（右）：
![mypois](https://user-images.githubusercontent.com/36129742/45208313-db70d200-b2bc-11e8-9b89-d869370e0666.png) ![mychromes](https://user-images.githubusercontent.com/36129742/45208321-df045900-b2bc-11e8-86df-6df7636424f1.png)
poi 中的文字偏高 2~3 像素。该现象在 beta.2 里也存在。

**Comment by KochiyaOcean** [comment]
1 之后会修复
2 已经修复（其实只是数值显示的问题而已）
3 推测是 Electron 或者 Chromium 排版引擎的问题，目前没有人力调查（=没时间看 Chromium源码），接下来会做一些简单的调查但是无法把太多时间花在这上面

**Comment by KagamiChan** [comment]
![image](https://user-images.githubusercontent.com/3816900/45211820-e1b77c00-b2c5-11e8-81b2-25b660bdb1a6.png)
这是 chrome 66 上的效果。我倾向于认为这是浏览器版本的问题。poi 自身没有什么办法能够影响到游戏内的渲染

**Comment by zlyzly777** [comment]
十分感谢👍，其实主要是截图的问题，另两个倒无伤大雅。
那么考虑到从夏天咕到秋天的活动终于有望在维护不延迟的前提下在明天晚上开始，有无可能在田鸽鸽出手<del>众提督倒下</del>之前发布一版呢？

**Comment by KagamiChan** [comment]
我们是计划活动开始之后根据维护更新做一些调整，然后再发一个新版本
