### ISSUE TITLE
9.0.0-beta.3无法正常缩放游戏画面

### ISSUE THREAD

**Issue by Illusorys** [poooi/poi#1943]
设置固定分辨率 设置成67%依然是大屏幕画面，点不了游戏开始按钮
回档到beta2会每次开POI都需要输入账号和密码登录

**Comment by Illusorys** [comment]
![Uploading QQ图片20180907210928.png…]()

**Comment by Illusorys** [comment]
![Uploading QQ图片20180907210928.png…]()

**Comment by KochiyaOcean** [comment]
![image](https://user-images.githubusercontent.com/8194131/45221681-2571ac00-b2ed-11e8-91e6-221952c6ec8c.png)

**Comment by Illusorys** [comment]
点了 没有用

**Comment by Illusorys** [comment]
还是那么大的框体 只有等1-2分钟 点击取消设置固定分辨率 然后再勾上才会自动适应
我的系统是WIN7 64位的

**Comment by KochiyaOcean** [comment]
https://ci.appveyor.com/project/KochiyaOcean/poi/build/artifacts 试试看这个版本吧

**Comment by Illusorys** [comment]
这个版本可以正常屏幕启动 没延时

**Comment by Illusorys** [comment]
问题解决了 谢谢
