### ISSUE TITLE
9.0.0 beta3 記憶體洩漏？

### ISSUE THREAD

**Issue by jerry78424** [poooi/poi#1945]
**poi 版本 / poi version:**
9.0.0 beta3

**操作系统 / OS:**
win7 64bit

**插件名和版本 / Plugin name & version:**

**你遇到了什么样的问题 / The problem you've met:**

poi突然變很卡頓，接著就失去回應，一看工作管理員才發現，
不知為何從某時間點開始記憶體消耗急遽上升，
在9.0.0 beta2未發生此情況。

![2018-09-07 - 23 45 40 myimgur v3 90 - myimgur eden fm x64](https://user-images.githubusercontent.com/3656749/45229732-4809c200-b2f9-11e8-8fbd-0803c1ba833c.png)
![2018-09-07 - 23 45 30 myimgur v3 90 - myimgur eden fm x64](https://user-images.githubusercontent.com/3656749/45229738-4a6c1c00-b2f9-11e8-893e-66805c8ae0fd.png)

**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:**

**Comment by gnattu** [comment]
@jerry78424 打开poi关于页面的资源监视器，截图

**Comment by jerry78424** [comment]
![2018-09-08 - 00 25 07](https://user-images.githubusercontent.com/3656749/45231175-cbc5ad80-b2fd-11e8-9049-2eed7b1c73fa.png)
重啟玩了10分鐘，目前還沒開始洩漏....

**Comment by KochiyaOcean** [comment]
![image](https://user-images.githubusercontent.com/8194131/45234496-e2293480-b310-11e8-9592-f5d9fdb0284b.png)
指的是这个部分
现在内存泄漏的主要在游戏本体，能不能修好得看田意

**Comment by KagamiChan** [comment]
先把扩展程式更新到最新版看看 = =

**Comment by KagamiChan** [comment]
有了一个新 beta 版本，试一下?

**Comment by jerry78424** [comment]
已更新為beta4，目前無問題
