### ISSUE TITLE
请问可以设置把poi-info条移到poi-app里面吗

### ISSUE THREAD

**Issue by vansto** [poooi/poi#1947]
**poi 版本 / poi version:**
v9.0.0-beta.3

**操作系统 / OS:**
Windows 10 1803

**你遇到了什么样的问题 / The problem you've met:**
我想尝试把游戏窗口控制条移动右边的信息页面里，但是alert-history会造成重叠问题需要改js，请问有什么办法解决吗
![2018-09-08_110808](https://user-images.githubusercontent.com/10329221/45249723-8d5cdc80-b357-11e8-984f-2a4c0c9b1a41.png)
预想实现的效果：
![2018-09-08_110831](https://user-images.githubusercontent.com/10329221/45249724-9d74bc00-b357-11e8-9f0d-cf20b5a27ad9.png)
黑色的是历史信息，会造成与当前信息的重叠（虽然图上没显示出来）
具体的方法找到了，但是本人不懂electron什么的，改不了。。

二期后我使用所有的插件浏览器均掉帧，没办法只能用chrome+poi的方式但是这样就看不到poi的信息记录了，所以想这样改一下。。

不过也不影响使用就是了。。

另外启动时会提示kcwiki字幕与秘书通知冲突
**插件名和版本 / Plugin name & version:**
kcwiki语音字幕 Ver. 1.2.15
秘书通知 Ver .2.0.0

**Comment by KochiyaOcean** [comment]
这部分就是 react+css 而已，你从源码改的话应该不是很麻烦

**Comment by vansto** [comment]
恩，已经弄好了
