### ISSUE TITLE
任务信息永远提示任务未收录

### ISSUE THREAD

**Issue by nordaraail** [poooi/poi#1948]
**poi 版本 / poi version:** 9.00-beta3

**操作系统 / OS:** Windows10 1803 17134.228

**插件名和版本 / Plugin name & version:**  任务信息5.3.2

**你遇到了什么样的问题 / The problem you've met:** 任务信息永远提示任务未收录

![1](https://user-images.githubusercontent.com/17372271/45260499-06256c80-b41c-11e8-9906-d1d759d68b26.PNG)

**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:**

![2](https://user-images.githubusercontent.com/17372271/45260504-1d645a00-b41c-11e8-9d85-6b888f2a8215.PNG)

**Comment by KagamiChan** [comment]
请删掉 `C:\Users\zhang\node_modules` 目录
