### ISSUE TITLE
POI 每次開啟都要重新登入

### ISSUE THREAD

**Issue by canonho** [poooi/poi#1951]
**poi 版本 / poi version:**

9.0.0 beta 2
**操作系统 / OS:**
Win7

**你遇到了什么样的问题 / The problem you've met:**
POI 每次開啟都要重新登入,已經試過 在%appdata%/poi 删除 cookie 和 cookie-journal 这两个文件

**Comment by KagamiChan** [comment]
用 beta.3 呢
