### ISSUE TITLE
9.0.0 beta3 一心二用插件页面容易卡死

### ISSUE THREAD

**Issue by Illusorys** [poooi/poi#1953]
poi 版本 / poi version:9.0.0 beta3
操作系统 / OS:WIN7 64位
插件名和版本 / Plugin name & version:一心二用

9.0.0 beta3的一心二用开启后页面容易整体卡死 ，具体是点游戏进入的时候整个页面卡死在DMM GAME页面上 同时无法进行点击等任何页面操作（画面为DMM GAME的页面），进入游戏之后部分游戏感觉操作延时比较严重（比如千年战争，进战斗后点击加速没反应要再点一下才有反应）

**Comment by KagamiChan** [comment]
卡死是 electron 的问题。希望下个版本可以修复

操作延时比较严重的话，我在和千年同一个引擎的城pro re 上没有复现

**Comment by Illusorys** [comment]
是只有战斗才有特有的卡顿 就是感觉 有点操作延时 点技能的时候点不动需要稍微等那么快1秒才能点。。有时候操作快一点就反应不过来 上一个版本没有这种问题 @KagamiChan
