### ISSUE TITLE
未貼條提醒會被大淀字幕覆蓋

### ISSUE THREAD

**Issue by jerry78424** [poooi/poi#1956]
**poi 版本 / poi version:**
9.0.0 beta3

**操作系统 / OS:**
win7 64bit

**插件名和版本 / Plugin name & version:**

**你遇到了什么样的问题 / The problem you've met:**

點進活動海域時會有未貼條船的提醒，
但是會立刻被大淀的語音字幕洗上去，
除非刻意點開歷史記錄不然是看不到提醒的
![2018-09-12 - 20 29 19](https://user-images.githubusercontent.com/3656749/45424940-8ec93480-b6ca-11e8-81a4-4ed692508b03.png)
![2018-09-12 - 20 29 26](https://user-images.githubusercontent.com/3656749/45425072-e8316380-b6ca-11e8-88d6-58f07d9ed3d5.png)

能否將提示修改成較醒目的氣泡窗口？

**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:**

**Comment by KagamiChan** [comment]
下个 beta 版本会换回来
