### ISSUE TITLE
poi v9.0.0-beta.4 一心二用 無法執行Flash遊戲

### ISSUE THREAD

**Issue by kwf25346** [poooi/poi#1958]
**poi 版本 / poi version:**poi v9.0.0-beta.4

**操作系统 / OS:**win7 x64

**插件名和版本 / Plugin name & version:**一心二用

**你遇到了什么样的问题 / The problem you've met:**執行一心二用跑花騎顯示瀏覽器不支援Flash 重新安裝過Flash Player及一心二用插件均無法正常執行，重裝回beta 3可正常。

**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:**

**Comment by KochiyaOcean** [comment]
请自行去 Adobe 官方网站下载安装 ppapi 版 flash

**Comment by KochiyaOcean** [comment]
cc @skagami

**Comment by KochiyaOcean** [comment]
理论上应该无影响

**Comment by KochiyaOcean** [comment]
https://github.com/electron/electron/issues/14580 相关 issue

**Comment by kwf25346** [comment]
今天試了9.0.1仍相同問題 只能繼續用9.0.0 beta3
![9 0 1 error](https://user-images.githubusercontent.com/43220519/45583922-a2141400-b905-11e8-9e1b-dcc29d2bb2f8.jpg)

**Comment by Illusorys** [comment]
补充下。。。我用9.0.2的POI 玩花骑士打开是一个裂图。。。游戏压根打不开

**Comment by KochiyaOcean** [comment]
因为不是 poi 代码的问题，在上面提到的 issue 解决之前不会修复

**Comment by KagamiChan** [comment]
这个问题应该已经解决了
