### ISSUE TITLE
poi9.0.0.4 Beta 改變遊戲解析度無效

### ISSUE THREAD

**Issue by cat2009** [poooi/poi#1959]
**poi 版本 / poi version:**
9.0.0.4 beta

**操作系统 / OS:**
Windows 10

**插件名和版本 / Plugin name & version:**

**你遇到了什么样的问题 / The problem you've met:**

改變解析度時遊戲畫面沒有跟著視窗變小

**Comment by KochiyaOcean** [comment]
需要更详细的描述

**Comment by cat2009** [comment]
就是設定較小的固定解析度時就只有視窗變小了,遊戲畫面沒有跟著縮小,變成只能看到部份畫面的情況...

**Comment by cat2009** [comment]
![9 0 0 3 beta](https://user-images.githubusercontent.com/43223484/45463710-b367ef80-b750-11e8-9309-73292317fbc1.png)
這是在9.0.0.3beta下正常縮小的截圖
![qq 20180913122817](https://user-images.githubusercontent.com/43223484/45463741-d4304500-b750-11e8-8027-98cacde98255.png)
這是9.0.0.4beta無縮放的情況下的圖,能看得到畫面沒有正常貼合
![qq 20180913122656](https://user-images.githubusercontent.com/43223484/45463784-fd50d580-b750-11e8-8818-827c4dd8662a.png)
這是9.0.0.4beta縮小後的情況,就只能看到畫面的一部份了

**Comment by KochiyaOcean** [comment]
点击 
![image](https://user-images.githubusercontent.com/8194131/45464883-8e25b200-b74d-11e8-8fcb-937e0a70db72.png) 是否you有效果

**Comment by cat2009** [comment]
沒有

**Comment by gnattu** [comment]
能提供一下安装的插件列表吗？

**Comment by cat2009** [comment]
![qq 20180913131454](https://user-images.githubusercontent.com/43223484/45465127-270cfb00-b757-11e8-8e11-cad5d42e7e0e.png)
ps. 9.0.0.3跟9.0.0.4下用的插件是一樣的

**Comment by KochiyaOcean** [comment]
开发者工具运行 `getStore('layout.webview.width')` 的结果是什么
![image](https://user-images.githubusercontent.com/8194131/45465171-f6c15e80-b74e-11e8-9045-38846e3fb8fc.png)

**Comment by cat2009** [comment]
![qq 20180913133731](https://user-images.githubusercontent.com/43223484/45465806-32adf100-b75a-11e8-8c61-cf29c651dbe5.png)

**Comment by KochiyaOcean** [comment]
@cat2009 `ipc.access('WebView').width` 是相同的结果么

**Comment by gnattu** [comment]
你就放那儿不管 等着 过一会儿会不会适配？

**Comment by cat2009** [comment]
已經放雪風置play了半小時了還是沒適配

**Comment by cat2009** [comment]
> ipc.access('WebView').width

![qq 20180913134726](https://user-images.githubusercontent.com/43223484/45466119-94228f80-b75b-11e8-98b1-e1ef11ada266.png)

**Comment by KochiyaOcean** [comment]
@cat2009 加载的 URL 是什么

**Comment by cat2009** [comment]
大概是我直連的URL

**Comment by KochiyaOcean** [comment]
@cat2009 跑一下 `$('webview').getURL()` 和 `$('webview').getURL().includes('854854')`

**Comment by cat2009** [comment]
![qq 20180913140720](https://user-images.githubusercontent.com/43223484/45466622-5ecb7100-b75e-11e8-805f-f0e6e6fb773c.png)
我直連的URL就塗黑處理了一下

**Comment by cat2009** [comment]
二邊都是直連的大概沒關系吧?
ps.話說poi的烤餅幹功能失效很久了....

**Comment by KochiyaOcean** [comment]
https://ci.appveyor.com/project/KochiyaOcean/poi/build/artifacts ←这里的版本应该已经修复（到 build 完成为止需要花几分钟时间）
对于特定的 IP，烤饼干也是无效的，这是 DMM 方面的设定的影响

**Comment by cat2009** [comment]
![qq 20180913160230](https://user-images.githubusercontent.com/43223484/45469812-6f83e300-b76e-11e8-8739-52593fa6576f.png)
好像還是不行

**Comment by cat2009** [comment]
@KochiyaOcean 求幫忙

**Comment by KochiyaOcean** [comment]
等下在上面的地址再下载一下吧

**Comment by cat2009** [comment]
好的謝謝
