### ISSUE TITLE
任务信息显示错误

### ISSUE THREAD

**Issue by attfishbed** [poooi/poi#1961]
**poi 版本 / poi version:9.0.0-beta.4

**操作系统 / OS:windows10 1803

**插件名和版本 / Plugin name & version:任务信息ver5.3.2

**你遇到了什么样的问题 / The problem you've met:未进行的任务显示已完成

![snipaste_2018-09-14_09-16-51](https://user-images.githubusercontent.com/18608745/45524739-97248b00-b802-11e8-8aff-eb6d3368e6c2.png)

**Comment by KochiyaOcean** [comment]
@attfishbed 需要详细描述

**Comment by KagamiChan** [comment]
需要一些截图，以及了解一下是什么任务

**Comment by attfishbed** [comment]
具体情况是这样的：我报错的那天才出的秋云，但是在任务信息中，A56空母机动部队再编成却显示该任务已完成，这个时候我发现不对劲，检查了一下任务信息中甲板任务流程，发现如果按插件显示的结果的话，我两个任务获取的甲板都有了，然而实际上我一个也没有。

かがみ <notifications@github.com> 于2018年9月14日周五 下午3:17写道：

**Comment by KagamiChan** [comment]
任务信息插件并不会存储任务的完成进度，而是根据任务链的依赖关系推断哪一些任务是已经完成的。因为没有看到你的任务列表，所以我觉得可能是某些任务依赖关系数据和实际不一致

**Comment by KagamiChan** [comment]
任务信息插件还没有机会更新
