### ISSUE TITLE
出击海域地图无法正确显示

### ISSUE THREAD

**Issue by yezirun4649** [poooi/poi#1963]
**poi 版本 / poi version:**
v9.0.0 beta.1

**操作系统 / OS:**

win10    OS内部版本17134.285

**插件名和版本 / Plugin name & version:**

**你遇到了什么样的问题 / The problem you've met:**

出击海域地图无法正确显示

![image](https://user-images.githubusercontent.com/28726451/45550722-b2c17d00-b866-11e8-8a74-1fb0835e83ca.png)

**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:**

![image](https://user-images.githubusercontent.com/28726451/45550764-d258a580-b866-11e8-819e-cb98107d297c.png)

**Comment by KochiyaOcean** [comment]
@yezirun4649 太旧了，更新本体
