### ISSUE TITLE
展开舰队编成时，POI变黑屏了

### ISSUE THREAD

**Issue by Voidgear** [poooi/poi#1964]
**poi 版本 / poi version:** 9.0.0 release

**操作系统 / OS:** 1809.17754.1

**插件名和版本 / Plugin name & version:**

**你遇到了什么样的问题 / The problem you've met:**

展开舰队编成时，POI变黑了

**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:**

**Comment by gnattu** [comment]
请试一下9.0.1是否还黑屏
