### ISSUE TITLE
遊戲BGM出不來

### ISSUE THREAD

**Issue by stu92054** [poooi/poi#1966]
**poi 版本 / poi version:**
9.0.1

**操作系统 / OS:**
win10 1803
 

**你遇到了什么样的问题 / The problem you've met:**
遊戲BGM無法撥放，但其他聲音如艦娘語音均正常
檢查遊戲設定部分並未將BGM靜音
嘗試清除快取及cookie均無效
嘗試解安裝poi並進入Appdata資料夾下刪除設定後重新安裝也無效
更換使用chrome瀏覽器測試均正常

**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:**

![image](https://user-images.githubusercontent.com/26442582/45587204-3ea1da80-b935-11e8-9d5b-c9c16e5d254f.png)

**Comment by KochiyaOcean** [comment]
删除 cache 呢

**Comment by stu92054** [comment]
嘗試過了，無效

**Comment by KochiyaOcean** [comment]
使用的连接方式是？

**Comment by stu92054** [comment]
使用的连接方是意思是我有沒有使用代理之類的嗎?
我沒有使用任何代理，直接改cookie連的

**Comment by KochiyaOcean** [comment]
右键打开网页界面开发者工具，切到 network tab，然后刷新看看音乐文件的加载状态
（开发者工具可能会很小，需要手动拉大
![image](https://user-images.githubusercontent.com/8194131/45587536-e6250a00-b941-11e8-8b06-516c1d8fa2c3.png)

**Comment by stu92054** [comment]
![image](https://user-images.githubusercontent.com/26442582/45587720-4749df00-b93c-11e8-9fcd-6180779d6a9b.png)
![image](https://user-images.githubusercontent.com/26442582/45587725-5c267280-b93c-11e8-9ca8-6bca27f35b47.png)
以上是重新刷新後的音樂加載狀況

**Comment by stu92054** [comment]
試著執行上述指令，確實有成功撥放音樂，不過並非母港音樂
另外剛才network擷圖有誤
以下重新擷圖
![image](https://user-images.githubusercontent.com/26442582/45589979-b554cd00-b961-11e8-877b-99f2b2616aa8.png)

**Comment by KochiyaOcean** [comment]
首先确定一下是不是游戏内设置的音乐关了……

**Comment by KagamiChan** [comment]
@stu92054 bgm 的播放方式是一样的，你可以找找看这些 mp3 档的请求里面有没有母港的 bgm，用同样的方式播放看看

**Comment by stu92054** [comment]
確定沒關
![image](https://user-images.githubusercontent.com/26442582/45590057-0dd89a00-b963-11e8-8be5-bdfceed02cd0.png)
能聽到艦娘語音跟戰鬥台詞等表示poi本身聲音應該也沒關

**Comment by KochiyaOcean** [comment]
BGM 的 URL 格式是 http://203.104.209.71/kcs2/resources/bgm/port/101_9163.mp3 这样的

**Comment by stu92054** [comment]
執行"new Audio('http://203.104.209.87/kcs2/resources/bgm/battle/101_9163.mp3').play()"指令
顯示404 not fround

**Comment by stu92054** [comment]
執行'new Audio('http://203.104.209.87/kcs2/resources/bgm/port/101_9163.mp3').play()' 指令
成功播放母港音樂

**Comment by AuTa** [comment]
这个问题我碰到的是当电脑其他程序播放音乐时，poi 就没有声音了。
