### ISSUE TITLE
游戏界面内有一竖条无法点击

### ISSUE THREAD

**Issue by 794673085** [poooi/poi#1970]
**poi 版本 / poi version:**
v9.0.1

**操作系统 / OS:**
win10 版本1803（OS内部版本17134/285）

**你遇到了什么样的问题 / The problem you've met:**
游戏界面有一竖条无法点击，调整poi分辨率变大会使得无法点击的部分往中间偏移，使用edge的话都可以点

![qq 20180916122715](https://user-images.githubusercontent.com/33588311/45595997-9731b000-b9e7-11e8-91e4-828161534971.png)
![qq 20180916122721](https://user-images.githubusercontent.com/33588311/45595998-9731b000-b9e7-11e8-91f3-d001c5a9c491.png)
![qq 20180916122728](https://user-images.githubusercontent.com/33588311/45595999-97ca4680-b9e7-11e8-9bfe-d27ae315a13b.png)
![qq 20180916122329](https://user-images.githubusercontent.com/33588311/45596002-a284db80-b9e7-11e8-9d9a-ba619fe33aeb.png)

**Comment by KagamiChan** [comment]
我们关闭的话说明已经解决了，不需要重复发 issue
请下载 9.0.2

**Comment by KagamiChan** [comment]
dup of #1968

**Comment by 794673085** [comment]
好的，才发现是我的网络问题导致没有检测到更新，使用代理更新后已解决
