### ISSUE TITLE
切换到插件和游戏分离模式以后游戏窗口的高度被锁定在150

### ISSUE THREAD

**Issue by JerryRich** [poooi/poi#1973]
![image](https://user-images.githubusercontent.com/31468229/45660255-db937d80-bac5-11e8-9ade-bdae7f20c58f.png)
版本9.0.2

**Comment by KochiyaOcean** [comment]
@JerryRich 修改设置的分辨率

**Comment by JerryRich** [comment]
@KochiyaOcean  只能改宽度，高度怎么改都是150

**Comment by KochiyaOcean** [comment]
@JerryRich 显示设置截图看看

**Comment by JerryRich** [comment]
@KochiyaOcean  截图
![image](https://user-images.githubusercontent.com/31468229/45691355-6e640480-bb26-11e8-83b7-8b5d667a1ec2.png)

**Comment by JerryRich** [comment]
@KochiyaOcean 我发现能够通过调整缩放比率（就是字体大小的那个）来增加高度，但是这样插件面板的字体会变的太大，用起来很不方便

**Comment by JerryRich** [comment]
已解决，在分离模式下重启游戏即可
