### ISSUE TITLE
poi放置一段时间游戏界面白屏

### ISSUE THREAD

**Issue by Ziziru** [poooi/poi#1974]
**poi 版本 / poi version:**9.0.0-beta.3

**操作系统 / OS:**win10  17754.1

**插件名和版本 / Plugin name & version:**

**你遇到了什么样的问题 / The problem you've met:**
母港放置一段时间后，有时poi的界面全部消失，然后点一下鼠标插件等其他界面恢复，游戏画面一片白，还能有bgm播放以及放置语音，且点击白色界面的相应位置，能听到操作的特效声。

重启poi后可以正常游戏
![default](https://user-images.githubusercontent.com/21362277/45684837-19ea7480-bb7a-11e8-9d64-fe24bc350c5d.png)

**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:**
暂无重现方法，不过出现这种问题总共5次，每次poi运行时常都超过8小时

**Comment by Ziziru** [comment]
出现上述情况前poi就下图所示，什么都没有
![23](https://user-images.githubusercontent.com/21362277/45835945-07209d00-bd3e-11e8-8a43-84d2a3a22bcd.png)
![24](https://user-images.githubusercontent.com/21362277/45835963-156eb900-bd3e-11e8-87e6-8156f1d267b2.png)
只有任务管理器杀掉重启才能正常使用

**Comment by KochiyaOcean** [comment]
推断和内存泄漏过度有关
试试看游戏内设置关闭音效有无改善
或者定期刷新
