### ISSUE TITLE
poi V9.0.3 舰娘信息插件无法正常安装

### ISSUE THREAD

**Issue by Illusorys** [poooi/poi#1975]
V9.02版本poi有安装舰娘信息 ，更新到9.03之后舰娘信息插件突然消失了，重新安装点了之后也是无限转圈读取，无法正常安装

**Comment by KagamiChan** [comment]
已修复。安装 6.2.1 版

**Comment by Illusorys** [comment]
还是在无限转圈，无法安装上去 @KagamiChan  重启POI重新安装都没用

**Comment by KagamiChan** [comment]
@Illusorys 删除 %appdata%/poi/plugins 再重新启动 poi 呢？

**Comment by Illusorys** [comment]
@KagamiChan 删除完plugins重新启动再安装所有插件 舰娘信息依旧在无限转圈 装不上

**Comment by KagamiChan** [comment]
求看一下 6.2.3 版本是不是可以运行了

**Comment by Illusorys** [comment]
@KagamiChan 已经可以正常安装了 抱歉，工作比较迟下班
