### ISSUE TITLE
win10版本17314.286 poi9.0.3黑屏无法游戏

### ISSUE THREAD

**Issue by speakfu** [poooi/poi#1976]
**poi 版本 / poi version:**

**操作系统 / OS:**

**插件名和版本 / Plugin name & version:**

**你遇到了什么样的问题 / The problem you've met:**
全屏都是黑色无法游戏

**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:**
每次打开poi都是这样

![image](https://user-images.githubusercontent.com/43433120/45800866-2a6f2c00-bced-11e8-9263-55559bec65df.png)

**Comment by KochiyaOcean** [comment]
代理设置错误，请确定设置了正确的代理
