### ISSUE TITLE
POI无法加载界面

### ISSUE THREAD

**Issue by billysunnyfake** [poooi/poi#1977]
**poi 版本 / poi version:**
9.0.3

**操作系统 / OS:**WIN10 64

**插件名和版本 / Plugin name & version:**

**你遇到了什么样的问题 / The problem you've met:**
POI无法加载游戏界面

**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:**

**Comment by billysunnyfake** [comment]
[https://imgur.com/PeUrCNJ](url)这个是运行截图

**Comment by billysunnyfake** [comment]
https://imgur.com/a/tesJluf 运行截图

**Comment by billysunnyfake** [comment]
https://imgur.com/a/Y2ltGOO

**Comment by KochiyaOcean** [comment]
检查下代理设置，以及 GitHub 是支持直接上传图片的……

**Comment by billysunnyfake** [comment]
> 检查下代理设置，以及 GitHub 是支持直接上传图片的……

我找不到哪里上传图片，这不是重点。代理设置一直是没问题的，127.0.0.1 8099这样

**Comment by KochiyaOcean** [comment]
如果是岛风 GO 的话，换线看看
直接复制图片到剪切板然后粘贴即刻

**Comment by billysunnyfake** [comment]
> 如果是岛风 GO 的话，换线看看
> 直接复制图片到剪切板然后粘贴即刻

所有线都换过一次了，用CHROME玩就没事

**Comment by KochiyaOcean** [comment]
保险起见代理设置还是截图过来看看

**Comment by KochiyaOcean** [comment]
访问非 dmm 的其他网站是否能够连接

**Comment by billysunnyfake** [comment]
![10](https://user-images.githubusercontent.com/43497194/45919841-f66d4580-be69-11e8-85a2-c1ebb437f1d2.jpg)

**Comment by billysunnyfake** [comment]
关了岛风GO就能连接，但是上不了游戏是肯定的

**Comment by KochiyaOcean** [comment]
高级设置是否有改动

**Comment by billysunnyfake** [comment]
就是无法加载游戏啊……右键弹不出任何东西

**Comment by KochiyaOcean** [comment]
【右键】【开发者工具按钮】

**Comment by billysunnyfake** [comment]
没有弹出任何东西

**Comment by KochiyaOcean** [comment]
会有一个很小的窗口，需要手动拉大

**Comment by billysunnyfake** [comment]
![15](https://user-images.githubusercontent.com/43497194/45919983-fec68000-be6b-11e8-90f8-29b6ab7cfff8.jpg)

**Comment by KochiyaOcean** [comment]
现在是进入游戏的状态么

**Comment by billysunnyfake** [comment]
![17](https://user-images.githubusercontent.com/43497194/45920017-95933c80-be6c-11e8-8497-ce20e054365b.jpg)

**Comment by KochiyaOcean** [comment]
试图清除一下缓存，如果无效，在关闭 poi 的情况下删除 `%appdata%/poi/cache` `%appdata%/poi/config.cson`

**Comment by billysunnyfake** [comment]
没有用，只要开了代理就没法加载任何东西

**Comment by KochiyaOcean** [comment]
![image](https://user-images.githubusercontent.com/8194131/45920140-26086600-bedb-11e8-8d14-34e7427158c1.png)
在关闭 poi 的情况下删除 `%appdata%/poi` 下如图的文件

**Comment by billysunnyfake** [comment]
设置完代理后依旧黑屏

**Comment by KochiyaOcean** [comment]
更换 DNS 之后清除缓存看看

**Comment by billysunnyfake** [comment]
怎么更换

**Comment by KochiyaOcean** [comment]
系统网络设置里面更换

**Comment by billysunnyfake** [comment]
更换为什么

**Comment by KochiyaOcean** [comment]
114.114.114.114 或者 8.8.8.8

**Comment by billysunnyfake** [comment]
换了8.8.8.8，依旧不行

**Comment by KochiyaOcean** [comment]
是否有尝试过重启岛风 Go 或者重启计算机
目前的报错信息判断是由于代理或者别的网络原因导致加载出错

**Comment by billysunnyfake** [comment]
重启了快一天了

**Comment by KochiyaOcean** [comment]
如果有其他代理，试试看其他代理能否正常使用

**Comment by billysunnyfake** [comment]
没有

**Comment by KochiyaOcean** [comment]
更换网络环境，比如使用手机热点连接网络？

**Comment by billysunnyfake** [comment]
也试过了

**Comment by KochiyaOcean** [comment]
岛风 Go 确定是最新版么

**Comment by billysunnyfake** [comment]
![18](https://user-images.githubusercontent.com/43497194/45920383-35eb6000-be71-11e8-8b69-367e185f1014.jpg)

**Comment by KochiyaOcean** [comment]
关闭岛风 Go 缓存和各种优化功能后清除缓存看看

**Comment by billysunnyfake** [comment]
试过了

**Comment by KochiyaOcean** [comment]
Chrome 是使用了 PAC 文件还是也设置为 127.0.0.1:8099 代理？如果是前者，也设置成该代理看看能不能工作

**Comment by billysunnyfake** [comment]
不懂设置

**Comment by KochiyaOcean** [comment]
或者你使用 kcv 或者 74eo 之类的浏览器看看相同代理设置有无问题

**Comment by billysunnyfake** [comment]
用KCV没有问题

**Comment by KochiyaOcean** [comment]
说明 poi 本身功能并没有问题
因为缺少更多信息，目前没法进一步判断问题原因
