### ISSUE TITLE
poi最小化后显卡占用过高

### ISSUE THREAD

**Issue by FerrariFA** [poooi/poi#1978]
**poi 版本 / poi version:** 9.0.3

**操作系统 / OS:** win10 1803 17134.285

**插件名和版本 / Plugin name & version:**

**你遇到了什么样的问题 / The problem you've met:** poi正常运行时，显卡占用率约8%，最小化后升至41%。奇怪的是温度并没有相应的变化，风扇转速其实也是正常运行时高，这个占用率可能是假的。

**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:**  自poi9.0.0beta3起每次最小化均会出现该问题。

此外还有两点：
1. 有没有做帧数限制的可能，高刷新率笔记本有点吃不消这个功耗，60hz到144hz的提升对于砍口垒也不大。
2. 9.0.0beta3更新了最小化后不暂停线程，对笔记本的续航影响很大，现在不插电的时候只能用老板键隐藏来让独显idle，对于这点有没有加一个选项的可能。

前半部分是正常运行，后半部分是最小化以后
![default](https://user-images.githubusercontent.com/12068945/45919981-f8d09f00-be6b-11e8-8a9b-03913c173b5b.PNG)

**Comment by gnattu** [comment]
<img width="170" alt="screen shot 2018-09-24 at 16 46 24" src="https://user-images.githubusercontent.com/12995396/45978102-6110b380-c019-11e8-8d1e-22ca15dade69.png">
这个表比较有意思 可以看到伴随独显飙升的使用率核心显卡的使用率骤降。
怀疑最小化trigger了某种开关把负载从核心显卡转移到独显上去了。
NV驱动中能否强行让poi使用核心显卡？

**Comment by gnattu** [comment]
如果不仅仅是限制游戏本身，而是把整个浏览器所有的帧数都进行限制的话，还是有办法的。
Chrome有锁最大fps的设定：[传送门](https://cs.chromium.org/chromium/src/ui/compositor/compositor_switches.cc?q=kLimitFps&sq=package:chromium&type=cs&l=23)

<img width="1312" alt="screen shot 2018-09-24 at 16 54 35" src="https://user-images.githubusercontent.com/12995396/45978645-d9c43f80-c01a-11e8-89a4-4243a0f67bc6.png">
目前看下来确实能锁到30fps。

**Comment by FerrariFA** [comment]
![default](https://user-images.githubusercontent.com/12068945/45982596-552bee00-c027-11e8-9d69-92726f03d76a.PNG)
直接用核显运行就比较正常

**Comment by KagamiChan** [comment]
@gnattu 那个锁 fps 的设置在命令行里面加参数可以吗，也许我们可以在设置里面加一个专门的设置

**Comment by KagamiChan** [comment]
关于最小化后不暂停，是因为有提督反映战斗时切到背景就没有办法自动播放

我们会考虑看是不是也做成一个单独的设置

**Comment by gnattu** [comment]
> @gnattu 那个锁 fps 的设置在命令行里面加参数可以吗，也许我们可以在设置里面加一个专门的设置

`app.commandLine.appendSwitch('limit-fps', 30)`
这个是可以用的

**Comment by KochiyaOcean** [comment]
一期的时候 Flash 在后台也不 throttle，禁止 throttle 能够保持行为一致
