### ISSUE TITLE
Providing Chocolatey Packages for POI

### ISSUE THREAD

**Issue by drelatgithub** [poooi/poi#1979]
**poi 版本 / poi version:**
Current and future versions

**操作系统 / OS:**
Windows

**你遇到了什么样的问题 / The problem you've met:**
Personally I prefer to manage software installation on Windows using Chocolatey, so I wrapped up the poi installers and made a chocolatey package for poi install/uninstall. The installation scripts will be submitted via a PR to the chocolatey community if you think they are good.

The metadata are mostly in `poi.nuspec`, with minor exceptions like the `releaseNotes` will be a link auto generated and redirecting to the github release page, and `description` will be automatically generated from `README.md`. Version information will be also updated by Automatic Update module. Please let me know if you have any suggestions.

**Comment by KochiyaOcean** [comment]
LGTM

**Comment by drelatgithub** [comment]
https://github.com/chocolatey/chocolatey-coreteampackages/pull/1116

**Comment by drelatgithub** [comment]
The PR has been merged, and [the package](https://chocolatey.org/packages/poi) has been approved.

Now windows users can use `choco install poi` to install poi. In the future, `choco upgrade poi` can be used to update poi.

**Comment by KagamiChan** [comment]
That's cool

Thanks for your hard work for making this possible. I'll update the README file asap
