### ISSUE TITLE
win10版本17314.286 poi9.0.3更改截图或缓存位置浏览器卡死

### ISSUE THREAD

**Issue by speakfu** [poooi/poi#1980]
**poi 版本 / poi version:**

**操作系统 / OS:**

**插件名和版本 / Plugin name & version:**

**你遇到了什么样的问题 / The problem you've met:**
![image](https://user-images.githubusercontent.com/43433120/45924392-33a10880-bf3a-11e8-8726-86842209c2a4.png)

**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:**
修改截图或缓存路径

**Comment by KochiyaOcean** [comment]
没有重现
你修改到哪里去了
