### ISSUE TITLE
在游戏分辨率为67%，布局为隐藏面板时，于未卜先知插件处无法完整显示舰娘装备

### ISSUE THREAD

**Issue by 794673085** [poooi/poi#1982]
**poi 版本 / poi version:**
9.0.3

**操作系统 / OS:**
1803(17134.285)

**插件名和版本 / Plugin name & version:**
未卜先知 7.8.0

**你遇到了什么样的问题 / The problem you've met:**
在游戏分辨率为67%，布局为隐藏面板时，于未卜先知插件处无法完整显示舰娘装备，其他布局会识别到窗口边缘贴边显示。

**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:**

![qq 20180926182107](https://user-images.githubusercontent.com/33588311/46074010-0ada7680-c1b9-11e8-8897-ebee4612defd.png)

**Comment by KagamiChan** [comment]
现在应该好了
