### ISSUE TITLE
耗资记录显示问题

### ISSUE THREAD

**Issue by toooonyy** [poooi/poi#1983]
**poi 版本 / poi version:**
poi@9.0.3

**操作系统 / OS:**
macOS Mojave

**插件名和版本 / Plugin name & version:**
耗资记录 poi-plugin-wheres-my-fuel-gone@0.7.2

**你遇到了什么样的问题 / The problem you've met:**
耗资记录按时间过滤的显示时候把 placeholder 直接暴露出来了（其他过滤器看起来没问题）。
![screen shot 2018-09-26 at 18 57 43](https://user-images.githubusercontent.com/3480434/46099251-30b64a00-c1be-11e8-9de1-bd2abb49c675.png)

**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:**
稳定复现。没尝试过清除 poi/wheres-my-fuel-gone，如果需要可以清掉再试试。

**Comment by SoraYama** [comment]
Fixed in ![bdd51b0](https://github.com/SoraYama/plugin-wheres-my-fuel-gone/commit/bdd51b022437f85cb4618f0d36f65932244b17bf), v0.7.4
