### ISSUE TITLE
POI的插件显示都是问号

### ISSUE THREAD

**Issue by blearmoon** [poooi/poi#1986]
**poi 版本 / poi version:**
9.0.3

**操作系统 / OS:**
  WIN7 64

**插件名和版本 / Plugin name & version:**
 

**你遇到了什么样的问题 / The problem you've met:**
### **
![Uploading QQ截图20180927145028.png…]()
**
![qq 20180927160849](https://user-images.githubusercontent.com/43633710/46128795-aaf2d700-c26f-11e8-8f44-d224b912a54f.png)

**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:**

**
![qq **_**20180927145106](https://user-images.githubusercontent.com/43633710/46128705-53546b80-c26f-11e8-8293-32b9880b3a6b.png)**_**
**
![qq 20180927145118](https://user-images.githubusercontent.com/43633710/46128733-6cf5b300-c26f-11e8-8fe7-97d92051e96c.png)
![qq 20180927160432](https://user-images.githubusercontent.com/43633710/46128737-6ff0a380-c26f-11e8-8e19-0fea8884c22f.png)

**Comment by KochiyaOcean** [comment]
代理设置里的 poi 端口（不是端口）不要和代理设置成一个，如果不知道这是什么就设置成 0

**Comment by blearmoon** [comment]
不行啊 不设置成同一个我游戏都进不去 显示不在利用地域 设置应该怎么改啊

**Comment by KochiyaOcean** [comment]
代理类型选择 http, ip 127.0.0.1, 端口 8123, poi 端口 0

**Comment by blearmoon** [comment]
![qq 20180927165055](https://user-images.githubusercontent.com/43633710/46130967-84d03580-c275-11e8-9098-69d243bd8590.png)
这里到底要怎么改呀。。

**Comment by blearmoon** [comment]
哦 我 试试

**Comment by blearmoon** [comment]
恢复了了 DALAO你是神 谢谢！
