### ISSUE TITLE
1,2队为联合舰队时使用3/4队出击 舰队名称仍显示为联合舰队名称

### ISSUE THREAD

**Issue by Shimushushushu** [poooi/poi#1990]
**poi 版本 / poi version:**
9.0.3 64bit

**操作系统 / OS:**
Win10 1809 OS 17763.1 64bit

**插件名和版本 / Plugin name & version:**
未卜先知 7.8.5

**你遇到了什么样的问题 / The problem you've met:**
1,2队为联合舰队时使用3/4队出击 舰队名称仍显示为联合舰队名称(空母机动部队)
解除联合后显示正常

**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:**

**Comment by KagamiChan** [comment]
讲道理有点懒得修
