### ISSUE TITLE
poi沒有回應

### ISSUE THREAD

**Issue by lay9438721** [poooi/poi#1991]
poi 版本 / poi version:
9.0.3

操作系统 / OS:
Window7

你遇到了什么样的问题 / The problem you've met:
調整視窗解析度的時候不小心讓解析度過大，導致poi直接崩潰，啟動poi就會沒有回應
![error](https://user-images.githubusercontent.com/37425583/46576768-97c8cf80-ca04-11e8-8078-2df459a0b24c.jpg)

**Comment by KagamiChan** [comment]
删除 %appdata%/config.cson 试试看

**Comment by lay9438721** [comment]
可以正常使用了，非常感謝!!
