### ISSUE TITLE
poi打开没有反应

### ISSUE THREAD

**Issue by yewuya00** [poooi/poi#1992]
**poi 版本 / poi version:9.0.3

**操作系统 / OS:win7

**插件名和版本 / Plugin name & version:**

**你遇到了什么样的问题 / The problem you've met:最新版本的poi突然就不能打开了，之前还能正常使用。多次双击打开没有反应，有且仅有一次出现过一个崩溃窗口，写的是poi然后什么browser，就记得这些。然后卸载重装之类的都不行。换了别的版本，其中最新的能打开的是8.2.0，但是无法自动获取游戏窗口，只自动识别了左上角的游戏区域。

**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:

**Comment by KagamiChan** [comment]
把 %appdata%/poi 换一个名字能不能打开？用 9.0.3
我们不再考虑对 9.0 之前的版本的支持，所以不需要尝试 8.x

**Comment by yewuya00** [comment]
> 把 %appdata%/poi 换一个名字能不能打开？用 9.0.3
> 我们不再考虑对 9.0 之前的版本的支持，所以不需要尝试 8.x

把里面的poi文件夹改名字？试了一下还是不行。

**Comment by KagamiChan** [comment]
那只能看突然不能打开前后你有没有做过什么操作了

**Comment by KochiyaOcean** [comment]
管理员权限打开命令提示符输入 `netsh winsock reset` 回车

**Comment by yewuya00** [comment]
> 管理员权限打开命令提示符输入 `netsh winsock reset` 回车

用这个方法解决了，谢了。
poi，加油！
