### ISSUE TITLE
遊戲BGM無法撥放

### ISSUE THREAD

**Issue by Jim94625** [poooi/poi#1995]
**poi 版本 / poi version:**

poi-9.0.3

**操作系统 / OS:**

WIN7

**你遇到了什么样的问题 / The problem you've met:**

遊戲BGM無法撥放，但其他聲音如艦娘語音均正常
且進入第三海域時，地圖中BGM會出現(燈...)的長音，戰鬥中則無BGM，但艦娘語音、戰鬥音效均正常
遊戲設定並未將BGM靜音
嘗試清除快取及cookie均無效
嘗試解除安裝poi並進入Appdata資料夾下刪除設定後重新安裝也無效
更換使用chrome瀏覽器測試均正常

**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:**
[https://i.imgur.com/hHfmTyq.png](url)

**Comment by KagamiChan** [comment]
可能和 #1966 属于同一种情况……
但是还是找不到具体的原因

**Comment by KagamiChan** [comment]
现在还有这种情况吗
