### ISSUE TITLE
插件排版全部乱掉，如何解决？

### ISSUE THREAD

**Issue by KN33S0XXX** [poooi/poi#1996]
**poi 版本 / poi version: 9.0.3

**操作系统 / OS: 1803 (OS 17134.345) 64bit

**插件名和版本 / Plugin name & version: 所有插件

**你遇到了什么样的问题 / The problem you've met: 之前一直好好的，刚刚重装了电脑系统，新下载的干净poi客户端，所有插件排版全部乱掉，安装和压缩版均进行了尝试，Roaming文件夹下配置档全部删除重新安装也不行。如图
![-4ada3q5-fnkrkgt1ksd8-9r](https://user-images.githubusercontent.com/33807663/46906813-612f0f80-cf44-11e8-8abd-5a72a597b067.png)
![-4ada3q5-dkiuk16t1ksdd-la](https://user-images.githubusercontent.com/33807663/46906817-65f3c380-cf44-11e8-8590-64acaf89e058.png)

**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:
![1](https://user-images.githubusercontent.com/33807663/46906799-49578b80-cf44-11e8-935d-1be4a10db2ae.png)
![2](https://user-images.githubusercontent.com/33807663/46906805-4eb4d600-cf44-11e8-9e27-0dcd66b13a30.png)

**Comment by KagamiChan** [comment]
你是把用户文件夹链接到别的地方了吗
这看起来是路径特殊所以无法加载资源

**Comment by KN33S0XXX** [comment]
对，我把AppData移动到了D盘，但是之前没有问题，难道是因为我在文件夹名称中加了符号“#”？

**Comment by KochiyaOcean** [comment]
@KN33S0XXX 不要加

**Comment by KagamiChan** [comment]
应该是这个原因

**Comment by KN33S0XXX** [comment]
好的，我去修改下试试，之前一直没有想到这个原因

**Comment by KN33S0XXX** [comment]
感谢大家可以了，果然是因为这个符号，如此低级的错误...
