### ISSUE TITLE
战斗回母港时，控制台报错

### ISSUE THREAD

**Issue by n313893254** [poooi/poi#1998]
**poi 版本 / poi version:** v9.0.3

**操作系统 / OS:**

win10 1803
**插件名和版本 / Plugin name & version:**

**你遇到了什么样的问题 / The problem you've met:**

战斗回母港时，控制台报错

**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:**

![image](https://user-images.githubusercontent.com/18737885/47093094-073b8c00-d25b-11e8-91ed-655213494740.png)

**Comment by KagamiChan** [comment]
已知问题，原因是性能监视器的请求返回了 undefined，不影响其它功能的使用
