### ISSUE TITLE
nahimic導致秘書通知沒聲音

### ISSUE THREAD

**Issue by newkai** [poooi/poi#2005]
**poi 版本 / poi version:**9.0.3

**操作系统 / OS:**
Windows 10 1809
**插件名和版本 / Plugin name & version:**

秘書通知 2.0.3

**你遇到了什么样的问题 / The problem you've met:**nahimic若沒開啟虛擬環繞，秘書通知完全沒有聲音

**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:**

**Comment by KagamiChan** [comment]
没有用过，不了解是什么情况，爱莫能助
