### ISSUE TITLE
每次打開poi之後都要重新安裝插件

### ISSUE THREAD

**Issue by raven0015** [poooi/poi#2006]
**poi 版本 / poi version:**v9.0.3

**操作系统 / OS:**win10 1803（內部版本：17134.345）

**插件名和版本 / Plugin name & version:**

**你遇到了什么样的问题 / The problem you've met:**
每次打開poi都需要重新下載插件

**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:**
全部插件都消失了

![default](https://user-images.githubusercontent.com/38522352/47698723-c3318980-dc53-11e8-924f-b6fca09ff42d.jpg)

**Comment by KagamiChan** [comment]
你是把 poi 的数据目录给链接到别的地方了吗

**Comment by raven0015** [comment]
> 你是把 poi 的数据目录给链接到别的地方了吗

具體是怎麼操作的？我昨天安裝了一個插件，後來發現安裝失敗之後，就變成這樣了。請問怎麼還原數據目錄呢？

**Comment by KagamiChan** [comment]
是哪一个插件？

那先把 %appdata%/poi/plugins 目录删掉，重新打开 poi 看看吧

**Comment by raven0015** [comment]
> 是哪一个插件？
> 
> 那先把 %appdata%/poi/plugins 目录删掉，重新打开 poi 看看吧

好了，謝謝~
