### ISSUE TITLE
设置代理后启动程序未响应

### ISSUE THREAD

**Issue by lwkanjao** [poooi/poi#2007]
**poi 版本 / poi version:**903

**操作系统 / OS:**win10

**插件名和版本 / Plugin name & version:**

**你遇到了什么样的问题 / The problem you've met:**打开程序后未响应 每次 现在用不了poi
有没有一键还原所以设置

**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:**二期之后上ooi 按他的方法设置代理 之后就这样了

**Comment by KagamiChan** [comment]
删除 `%appdata%/poi/config.cson`

**Comment by lwkanjao** [comment]
> 删除 `%appdata%/poi/config.cson`
没这个路径

**Comment by KagamiChan** [comment]
@lwkanjao 按 win+R，输入 `%appdata%/poi`，再回车

**Comment by lwkanjao** [comment]
> @lwkanjao 按 win+R，输入 `%appdata%/poi`，再回车

解决了 非常感谢
