### ISSUE TITLE
关于UI的一些小问题和建议

### ISSUE THREAD

**Issue by zhuxiaoran429** [poooi/poi#2008]
**poi 版本 / poi version:** 9.03

**操作系统 / OS:** MacOS High Sierra 10.13.6

**插件名和版本 / Plugin name & version:** 一心二用3.1.1，任务信息5.5.0

**你遇到了什么样的问题 / The problem you've met:**
1. 因为用的是配置比较一般的Macbook Air，长时间开着poi会导致电脑发热得比较厉害，所以平时习惯关掉游戏界面只开着poi面板，需要收远征或者入渠结束的时候再打开游戏，但是目前游戏和面板分离的布局下似乎游戏窗口关掉以后就没有办法再打开了，不知道有没有可能优化一下这个问题。
2. 因为上面的问题，现在暂时想到使用一心二用插件来暂时解决一下，但是使用起来稍微有点麻烦，要"打开面板-跳转页面-点击自动调整-手动调整窗口尺寸"这一整套下来，有没有可能自己设置主页和窗口的默认尺寸和分辨率之类的呢。
3. 在我的电脑上一心二用里那个分辨率调整的小窗口似乎有问题，窗口特别小导致文字显示不全，背景色是透明的而且文字是白色，什么都看不清楚，至少从9.0beta开始到现在就一直是这样的。
4. 有一个任务信息插件的小bug，这个插件似乎是个第三方插件，我也不知道是插件的问题还是poi本身的问题，就先一起放上来。也是在游戏和面板分离的情况下，把鼠标放到概览下的任务名称的时候会显示翻译过的任务详情，但是因为分离模式下面板窗口比较小，超出窗口的部分就不会显示了。

问题有点多，而且不知道怎么截图传上来，总之感谢作者大大的付出，辛苦了~

**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:**

**Comment by KochiyaOcean** [comment]
关于 1，隐藏最小化窗口之后 mac 会自动停止该窗口的线程，所以不需要关闭
剩下的由于项目在重构可能会发生比较大的变动，暂时不回答
