### ISSUE TITLE
无法登陆游戏,一直显示黑屏

### ISSUE THREAD

**Issue by kigari298** [poooi/poi#2012]
**poi 版本 / poi version:9.03

**操作系统 / OS: macOs 10.13.6

**你遇到了什么样的问题 / The problem you've met: 无法加载游戏,一直显示黑屏,偶尔登上dmm官网后点登陆会跳转到404页面

**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related: 试过重启/刷新/重安装了...没用

![a87c3371-08ca-4e89-980b-399046c37149](https://user-images.githubusercontent.com/44855605/48173877-9de7ef80-e2d3-11e8-9a65-e63fb6365aa4.png)

**Comment by kigari298** [comment]
> @kigari298 检查代理设置

我是改host的,safari上能正常打开游戏但是Poi一直黑屏....

**Comment by KochiyaOcean** [comment]
@kigari298 代理设置是不使用？

**Comment by kigari298** [comment]
> @kigari298 代理设置是不使用？

是的

**Comment by KagamiChan** [comment]
在 poi 的地址栏里面输入一些常用网址能打开吗，比如 qq.com 之类的
