### ISSUE TITLE
我又来了，这又是什么情况？

### ISSUE THREAD

**Issue by KN33S0XXX** [poooi/poi#2013]
**poi 版本 / poi version: 9.0.3

**操作系统 / OS: 1803(17134.345)

**你遇到了什么样的问题 : 花屏？我也不知道怎么描述，看图吧。。。

**有没有重现的方法，或者与问题相关的任何信息 : 暂时不清楚如何重现

![2018-11-8t22 12 46](https://user-images.githubusercontent.com/33807663/48201022-3d74b300-e3a4-11e8-9fb6-a023d0f6b525.png)
![2018-11-8t22 14 58](https://user-images.githubusercontent.com/33807663/48201023-3d74b300-e3a4-11e8-9c32-3b8d61951d17.png)

这是重启了的截图，忘了截图
![_20181108221938](https://user-images.githubusercontent.com/33807663/48201065-6d23bb00-e3a4-11e8-817d-bc5e51b24be7.png)

**Comment by KagamiChan** [comment]
是否开启了硬件加速？
显卡是？有没有更新到最新的显卡驱动？

**Comment by KN33S0XXX** [comment]
> 是否开启了硬件加速？
> 显卡是？有没有更新到最新的显卡驱动？

硬件加速开启，显卡GTX970，驱动为最新的416.34

需要关闭硬件加速吗？

**Comment by KochiyaOcean** [comment]
由于其他浏览器也有类似情况，暂时不作为 poi 的问题考虑
