### ISSUE TITLE
使用高清图标时，插件卡顿

### ISSUE THREAD

**Issue by yujunqin** [poooi/poi#2020]
**poi 版本 / poi version:** 9.0.3

**操作系统 / OS:** Win10 1803 17134.345

**插件名和版本 / Plugin name & version:**  装备信息，舰娘信息等。装备信息最严重。

**你遇到了什么样的问题 / The problem you've met:** 以装备信息为例，使用高清图标时，在页面最上方滑动滚轮有明显延迟，勾选、全选、全不选等动作均有明显卡顿。关闭高清图标后流畅。

**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:** http://bbs.nga.cn/read.php?tid=15648262

**Comment by KochiyaOcean** [comment]
是什么硬件配置？

**Comment by FerrariFA** [comment]
CPU: i7-8750H
GPU: Intel UHD Graphics 630
RAM: 16G 2666MHz
poi限制在60fps工作，即使在插件卡顿时，GPU占用率也保持在30%左右，没有剧烈波动。

**Comment by KochiyaOcean** [comment]
i7 7700k 没有复现，需要额外调查

**Comment by KagamiChan** [comment]
尝试做了一些优化，请下载 https://ci.appveyor.com/project/KochiyaOcean/poi/builds/20575031/artifacts 这里的版本测试一下是否有所改善
