### ISSUE TITLE
11月16号更新之后只有游戏画面无法显示任何插件

### ISSUE THREAD

**Issue by jimmyzzxhlh** [poooi/poi#2022]
**poi 版本 / poi version:**
9.0.3

**操作系统 / OS:**
Windows 10 1803 (OS Build 17134.407)

**插件名和版本 / Plugin name & version:**
N/A

**你遇到了什么样的问题 / The problem you've met:**
所有插件都不能使用

**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:**
打开游戏即可
![poi](https://user-images.githubusercontent.com/11505867/48634744-2f61fc00-e97b-11e8-9861-859a6e932f6c.png)
![poi_dev_tools_1](https://user-images.githubusercontent.com/11505867/48634745-2ffa9280-e97b-11e8-9c1e-acd2c1a55cc8.png)
![poi_dev_tools_2](https://user-images.githubusercontent.com/11505867/48634746-2ffa9280-e97b-11e8-8f62-0d887ba9eed5.png)

**Comment by KochiyaOcean** [comment]
更新
