### ISSUE TITLE
macOS 下插件切换快捷键失效

### ISSUE THREAD

**Issue by Sponge-bink** [poooi/poi#2023]
**poi 版本 / poi version:** POI 9.0.4.5709

**操作系统 / OS:** macOS High Sierra 10.13.6

**你遇到了什么样的问题 / The problem you've met:** 只有当最后一次点击在插件栏时，「⌘ + 数字键」和 Tab 切换插件的快捷键才有效。如果上一次点击在游戏界面内，则快捷键失效。

**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:** 重现见问题描述。不知道是不是 9.0.4 才有的，用的上一个版本还是 9.0.0 beta 2（or  3?），没有出现此问题。

<img width="912" alt="image" src="https://user-images.githubusercontent.com/33798984/48671657-b8895680-eb66-11e8-8f0d-2dbd2658c579.png">

**Comment by KochiyaOcean** [comment]
和内核升级有关，属于预期内行为
