### ISSUE TITLE
操作一段时间之后就卡死

### ISSUE THREAD

**Issue by AXIHIXA** [poooi/poi#2024]
**poi 版本 / poi version:**
v9.0.4

**操作系统 / OS:**

Version 1803 (OS build 17134.407)

**插件名和版本 / Plugin name & version:**

**你遇到了什么样的问题 / The problem you've met:**
操作一段时间之后就卡死，有时是黑屏，有时是正常屏幕。刷新后好用一段时间又会卡死（左上角的圆圈还是会转的，但是点击游戏UI没反应，右下角没有显示加载中图标。鼠标在游戏画面上一直是指针状，而不是手状）。
试过清poi以及锅go的cache或者cookie，没用。

**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:**

如上文所述，次次都有。

**Comment by AXIHIXA** [comment]
![untitled](https://user-images.githubusercontent.com/32153465/48689104-f092a700-ec03-11e8-84ee-15088235fc8d.jpg)

**Comment by finaljsy** [comment]
一样的问题，昨天还好好的今天就不行了

**Comment by finaljsy** [comment]
> @finaljsy 字幕插件的问题，安装翻译插件应该可以解决

感谢大佬！卸了字幕插件就好了~
