### ISSUE TITLE
Poi v9.0.4 + kcwiki语音字母插件v1.12.19 问题

### ISSUE THREAD

**Issue by PangCY1812** [poooi/poi#2025]
**poi 版本 / poi version:**
Poi v9.0.4

**操作系统 / OS:**
Win 10 Pro 64bit

**插件名和版本 / Plugin name & version:**
 kcwiki语音字母插件v1.12.19

**你遇到了什么样的问题 / The problem you've met:**
更新v9.0.4后进入游戏发现语音没有播放，对应的字幕也没有出现。

点击秘书舰，没有语音，没有字幕。
工厂，任务界面，明石和大淀语音和字幕都没有播放，直接黑频卡没有，也没有猫100。
甚至在演习和战斗中，开场我方舰娘本应该有攻击语音，直接卡，等了30分钟都没有任何反应，也没有猫100。

尝试删除字幕文件档 + 重装插件，依然不行。
暂时解决方法为禁用或移除该插件。

**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:**

![image](https://user-images.githubusercontent.com/42483836/48691261-e75a0800-ec0c-11e8-8fd8-933572e2689e.png)

**Comment by KochiyaOcean** [comment]
https://github.com/kcwikizh/poi-plugin-subtitle/pull/27
已经修复
