### ISSUE TITLE
poi 每次重启后， cookie 就没了，我该如何排错？

### ISSUE THREAD

**Issue by slime7** [poooi/poi#2026]
**poi 版本 / poi version:**9.0.3(a6297794e3e5935fbaf380acb9a39bf1fe332925)

**操作系统 / OS:**win10x64 1803(17134.407)

**插件名和版本 / Plugin name & version:**

**你遇到了什么样的问题 / The problem you've met:**
poi 关闭后再次打开时，网页的 cookie 就清空了，上一个正常工作的版本不记得了。网页是自己的游戏登录页，不是 dmm 或者游戏的 ip。控制台没有报错只有 electron 的 Security Warning 。

**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:**

**Comment by KochiyaOcean** [comment]
Electron 4.0.0 的 bug github.com/electron/electron/issues/15365

**Comment by KagamiChan** [comment]
目前可以先手动安装 electron 3.x 版本来使用

**Comment by slime7** [comment]
> 目前可以先手动安装 electron 3.x 版本来使用

安装3.x解决了并且“消失”的cookie自动回来了……

**Comment by EdiTurn** [comment]
使用 https://github.com/poooi/poi/commit/14463b5f82714221a5f4757b3eab1c3270ca45b4 后，若开启「设置 DMM 地区 cookie」，会在登录界面反复弹出如下提示：

![2018-11-29 130652](https://user-images.githubusercontent.com/5492805/49200472-eb89e080-f3d7-11e8-95bc-acf515ceb91a.jpg)

**Comment by KagamiChan** [comment]
目前是这样的……

我们也在等待上游能有新版本发布

**Comment by KagamiChan** [comment]
目前 master 分支已经能更新
