### ISSUE TITLE
血量显示错误

### ISSUE THREAD

**Issue by YuiTH** [poooi/poi#2027]
**poi 版本 / poi version:**
v9.0.4

**操作系统 / OS:**

macOS Mojave 10.14.1 (18B75)

**你遇到了什么样的问题 / The problem you've met:**
在登陆游戏后，显示旗舰的血量错误
![image](https://user-images.githubusercontent.com/22416062/48779281-389fef80-ed12-11e8-9ab1-6acc14d95ad2.png)

旗舰血量实际 10/31
显示31/31

**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:**
登录前最后一次战斗（使用其他电脑）造成旗舰血量从31下降到10。
编成切换舰船问题依旧，回到母港一次后回归正常。
虽然暂时无法复现，但是游戏如果出现血量显示错误可能会造成的问题大家都明白。所以还是汇报一下。

![image](https://user-images.githubusercontent.com/22416062/48778923-689ac300-ed11-11e8-9cc7-3dbcfb0e5ee4.png)

**Comment by KochiyaOcean** [comment]
完全没有报错就非常诡异了
