### ISSUE TITLE
kcwiki语音字幕语音不更新

### ISSUE THREAD

**Issue by LowenSunday** [poooi/poi#2032]
**poi 版本 / poi version:**
v9.0.4

**操作系统 / OS:**
Windows 10 version 1803

**插件名和版本 / Plugin name & version:**
kcwiki语音字幕 Ver.1.2.20

**你遇到了什么样的问题 / The problem you've met:**
语音字幕已经好久没有更新了。就我自己的观察的话语音还停留在秋刀鱼的语音。

**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:**
不知道是poi更新还是插件更新的缘故，还是本身就有问题，原本每次启动游戏的时候都会显示“语音字幕更新”和语音字幕更新的时间（格式不一定对_( ﾟДﾟ)ﾉ然而现在启动游戏只显示poi获取游戏数据，获取完了以后就是旗舰的语音字幕了_(:з」∠)_然后在console里面显示"no translate file found."

![image](https://user-images.githubusercontent.com/23163322/49201224-0fb0d780-f36e-11e8-8f58-fa42770176be.png)

**Comment by KochiyaOcean** [comment]
大概是 kcwiki 那边没人维护了，可以联系 kcwiki 汇报这个问题

**Comment by LowenSunday** [comment]
请问是联系插件的作者还是kcwiki官方呢_( ﾟДﾟ)ﾉ

**Comment by KochiyaOcean** [comment]
@LowenSunday 官方就行

**Comment by LowenSunday** [comment]
谢谢谢谢(｡･∀･)ﾉﾞ
