### ISSUE TITLE
面板全黑

### ISSUE THREAD

**Issue by jerry78424** [poooi/poi#2033]
**poi 版本 / poi version:**
9.0.3

**操作系统 / OS:**

win7 64bit

**插件名和版本 / Plugin name & version:**

**你遇到了什么样的问题 / The problem you've met:**

遊戲本體正常，poi面板全黑
![2018-12-01 - 20 24 34](https://user-images.githubusercontent.com/3656749/49328190-23934e00-f5a7-11e8-894f-a261e4f4997d.png)

**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:**

![2018-12-01 - 20 23 18](https://user-images.githubusercontent.com/3656749/49328195-2beb8900-f5a7-11e8-9c77-788b8034b21b.png)

**Comment by KochiyaOcean** [comment]
更新
