### ISSUE TITLE
win10 1803更新(17134.441)后黑屏

### ISSUE THREAD

**Issue by LostXine** [poooi/poi#2035]
**poi 版本 / poi version:**
9.0.4

**操作系统 / OS:**
Win10 1803 17134.441

**你遇到了什么样的问题 / The problem you've met:**
poi页面全黑，CPU占用维持在25%左右（故障前为6%-9%），开发者页面也是黑的
![image](https://user-images.githubusercontent.com/10805205/49329971-9a8a1000-f5c2-11e8-8103-a41b0364c1ea.png)

**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:**
更新一下系统应该就会出这个问题？…
笔记本配置：
CPU i5 2450M 2.5GHz
GPU GT630M 驱动389.12
RAM 8G 

尚无法完全排除是硬件驱动问题，不过既然能用Chrome发issue感觉驱动翻车概率不大，总之感谢关注

**Comment by KochiyaOcean** [comment]
试试看用核心显卡和用独立显卡打开有什么区别，以及关闭硬件加速的情况

**Comment by LostXine** [comment]
感谢回复，把poi设置到集显确实可以显示了，（虽然CPU利用率暴涨
请问现在能确定or有什么方法断定这是谁的锅吗？

**Comment by KochiyaOcean** [comment]
你可以试试看 appveyor 上的每夜版本有没有问题，如果没问题就是 Chrome 内核相关了

**Comment by LostXine** [comment]
强行更新了一下显卡驱动就可以运行当前版本的poi了，CPU在母港维持16%-26%（所以为什么要手贱升级呢
测试了每夜版（最新好像是9.0.3？）驱动更新前后都无法使用
总之先算解决了吧，谢谢
