### ISSUE TITLE
索敵計算公式未計算到水爆改修

### ISSUE THREAD

**Issue by jerry78424** [poooi/poi#2036]
**poi 版本 / poi version:**
9.0.4

**操作系统 / OS:**

win7 64bit
**插件名和版本 / Plugin name & version:**

**你遇到了什么样的问题 / The problem you've met:**

按照明石網資料
水偵改修的額外海圖索敵是1.2*改修星數^0.5
水爆改修的額外海圖索敵是1.15*改修星數^0.5
但是poi目前的索敵計算公式只計算水偵改修，未計算水爆改修

**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:**

**Comment by KagamiChan** [comment]
看起来公式有所更新
大型电探的系数也不对了……
