### ISSUE TITLE
Question: Where to find documentation for Poi plugins

### ISSUE THREAD

**Issue by takase1121** [poooi/poi#2037]
**poi 版本 / poi version:** 9.0.4

**操作系统 / OS:** Windows 10 Single Language build 1803

**插件名和版本 / Plugin name & version:**

**你遇到了什么样的问题 / The problem you've met:** I don't know if this is the right place to ask questions, but where can I find documentations to make a plugin for Poi?

**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:**

**Comment by KochiyaOcean** [comment]
Its mentioned in readme https://dev.poooi.app/

**Comment by KagamiChan** [comment]
updated site: https://dev.poi.moe
