### ISSUE TITLE
老板键隐藏界面会导致游戏动画暂停

### ISSUE THREAD

**Issue by XuZhilei** [poooi/poi#2039]
**poi 版本 / poi version:**
v9.0.4，但是这个问题前几个版本也存在。

**操作系统 / OS:**

Win10，1803版本。

**你遇到了什么样的问题 / The problem you've met:**
在战斗中使用老板键隐藏界面之后，如果出现需要加载立绘的场景（例如中破），动画就会卡住不动，必须切回前台才会继续。一期没有这个问题，似乎和二期HTML化有关？

**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:**
打把演习就能发现，从语音可以听出来游戏卡住了。我有段时间没出击过了，不知道出击时会不会出现这种问题……

**Comment by KochiyaOcean** [comment]
Chrome 会阻止看不到的页面的渲染来节省性能，属于内核行为，换 Chrome 大概也是类似的结果
（之所以之前不拦 Flash 是因为阻止不了

**Comment by XuZhilei** [comment]
我也是这么怀疑的，但是我自己不太懂Chrome。既然这样的话那就没办法了…

**Comment by KochiyaOcean** [comment]
因为还原的时候战斗动画之类会直接跳到结束，所以目前不作为非常严重的问题来看
