### ISSUE TITLE
关于Poi v10 beta10限制帧率 可以自定义输入吗 

### ISSUE THREAD

**Issue by XM4096** [poooi/poi#2040]
我是120hz萤幕 v10 beta0只可以限制到30fps 可以弄一个自定义输入吗?
不能的话加几个选项也可以(30,60,120...)

**Comment by KagamiChan** [comment]
限制帧率适用于硬件性能不足的用户，如果硬件性能足够的话，感觉也没有必要做限制了。

所以具体来说是什么样的情况需要自定义输入

**Comment by XM4096** [comment]
> 限制帧率适用于硬件性能不足的用户，如果硬件性能足够的话，感觉也没有必要做限制了。
> 
> 所以具体来说是什么样的情况需要自定义输入

我是筆記本的 如果不限制60fps 集显佔用直接上80%

**Comment by KagamiChan** [comment]
@XM4096 了解了，那可以先按照 https://github.com/poooi/poi/issues/1978#issuecomment-427620392 的方式，修改一下快捷方式
之后我们会考虑添加的

**Comment by XM4096** [comment]
> @XM4096 了解了，那可以先按照 [#1978 (comment)](https://github.com/poooi/poi/issues/1978#issuecomment-427620392) 的方式，修改一下快捷方式
> 之后我们会考虑添加的

好
