### ISSUE TITLE
Poi 10.0.0 Beta DARK主題 主介面配色問題

### ISSUE THREAD

**Issue by Squall-Lucifer** [poooi/poi#2043]
**poi 版本 / poi version:**
10.0.0 BETA-0

**操作系统 / OS:**
Windows 10 1709

**你遇到了什么样的问题 / The problem you've met:**
由9.0.4更新上10.0.0 BETA-0之後DARK主題之POI介面配色和舊版本相比變化太大，對比度十分高，和艦娘主介面配起來相當傷眼，但"設定>>顯示>>主題"裡卻未能將之修改，即使轉換成Light主題都未有太大改善，希望能增加回舊版本的配色對比度....

**Comment by KochiyaOcean** [comment]
需要更详细的说明……

**Comment by KagamiChan** [comment]
能否提供更详细一点的描述，具体是哪一部分的配色的对比度问题，如果能有更定量的描述就更好了

**Comment by Squall-Lucifer** [comment]
https://imgur.com/a/W4F2RRu

紅圈部份，即通知欄和插件欄之底色，通知欄目前預設的底色使得開發成功失敗比較難看清
插件欄則是底色的淺灰色部份問題，和遊戲主介面配起來會有傷眼的感覺，特別是主介面在母港時比較明顯，出撃時則暫時可以

不排除是改版差別較大，肉眼習慣需時ORZ

**Comment by KochiyaOcean** [comment]
@Squall-Lucifer 感觉与其说是主界面配色问题不如说是三式改的配色问题...

**Comment by Squall-Lucifer** [comment]
POI 9.0.4版本時插件部份黑底黑的比較深色，現時是黑底上方再多一層淺灰layer，或許這就是問題所在?
是了，另一個小疑問，我從POI切換回白底的網頁，比如Github這裡，會有一種刺眼的感覺，雙眼需要數秒時間適應，這是正常的嗎?

**Comment by KagamiChan** [comment]
你使用的是什么样的显示屏，有没有进行过校准。先看看显示屏的对比度饱和度方面设置是不是合理吧

**Comment by Squall-Lucifer** [comment]
BenQ GL2250，使用出廠設置，因為我不懂弄(｀・ω・´)

**Comment by KagamiChan** [comment]
我用过 benq gw2250，感觉默认亮度有点高，你可以先调节一下亮度看看

我们这边也会看其他用户有没有类似反馈

**Comment by jerry78424** [comment]
在我這不是單純亮度的問題，是之前用的Theme不見了，原本有好多個Theme，
之前9版用的Darkly看起來最舒服，現在的Dark太亮了，一點都不Dark
![2018-12-15 - 00 10 02](https://user-images.githubusercontent.com/3656749/50014279-797fe100-fffe-11e8-8814-c2e863ccc6b6.png)

![2018-12-15 - 00 15 02](https://user-images.githubusercontent.com/3656749/50014285-843a7600-fffe-11e8-8ab4-e6aa7d317be9.png)

**Comment by KochiyaOcean** [comment]
@jerry78424 可以试试看自定义背景 + 全黑图片

**Comment by jerry78424** [comment]
@KochiyaOcean 
試過了，面板還是藍灰色的

**Comment by KochiyaOcean** [comment]
@jerry78424 毕竟设计上就是偏蓝色的

**Comment by x60516** [comment]
@KochiyaOcean 希望能改回以前的面板配色，新配色不是很舒適

**Comment by x60516** [comment]
@KochiyaOcean 另外入渠與建造面板分成2個了，沒辦法像以前放在同一個面板裡面嗎?

**Comment by KochiyaOcean** [comment]
@x60516 "原来的"主题有很多种，而在太多种配色方案中为 UI 元素寻找平衡的难度正是我们放弃原来的系统的原因

**Comment by fonirs** [comment]
舰船模块的状态显示，建议和9.0一样，数字颜色和状态提示保持一致，现在只有状态显示黄色橙色白色红色，没有原来直观。

**Comment by fonirs** [comment]
> @fonirs
> 这个方案在浅色主题下的辨认度很低，所以换成了现在的样子

有没有可能单独对dark主题生效，现在这个辨识度感觉也不高，尤其是在监控支援舰队状态的时候，有时候就会漏掉已经没有闪的船。

另外升级10.0之后，我单独解压了一个9.04版本，打开的时候整个状态面板都是空的，没有任何东西只有最上面的截图，打开缓存，开关声音那几个快捷按钮在。游戏部分正常，只是底下的操作面板没了，这是和10.0冲突造成的么？

**Comment by KagamiChan** [comment]
@fonirs 回退到 9.x 版本需要删除设置文件

**Comment by jerry78424** [comment]
https://bbs.nga.cn/read.php?tid=16035567

NGA有人提供了自改的CSS設置，用起來與之前的一個主題幾乎完全相同，
喜歡舊主題的可以試試

**Comment by fonirs** [comment]
蹭了大佬的css，感觉好多了，感谢提醒。
