### ISSUE TITLE
poi使用cpu高

### ISSUE THREAD

**Issue by xiaoshuaivONE** [poooi/poi#2044]
**poi 版本 / poi version:**
v9.0.4

**操作系统 / OS:**

**插件名和版本 / Plugin name & version:**

**你遇到了什么样的问题 / The problem you've met:**
poi使用时使用CPU高达百分之三十多

**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:**

**Comment by KagamiChan** [comment]
求问计算机配置？
是否关闭了硬件加速？

**Comment by xiaoshuaivONE** [comment]
> 求问计算机配置？
> 是否关闭了硬件加速？

i5 4570 已经关闭，进入游戏就快百分之五十多了

**Comment by KochiyaOcean** [comment]
关了硬件加速是要吃 CPU 的啊……

**Comment by xiaoshuaivONE** [comment]
> 关了硬件加速是要吃CPU的啊......

开着更吃啊，开着就想怪物一样吃了更多

**Comment by KochiyaOcean** [comment]
总之看看 10.0.0 的 beta 版什么情况吧

**Comment by xiaoshuaivONE** [comment]
> 总之看看 10.0.0 的 beta 版什么情况吧

恩，试试看吧，这个CPU吃的确实让我惊了。。

**Comment by xiaoshuaivONE** [comment]
![qq 20181214184715](https://user-images.githubusercontent.com/45873105/49999022-b6cd7a00-ffd0-11e8-9368-f945fd16eb9a.png)
这就是使用poi是的CPU

**Comment by KagamiChan** [comment]
如果用安全模式打开的话 cpu 占用会是什么样的

**Comment by xiaoshuaivONE** [comment]
> 如果用 poi 的安全模式打开的话 cpu 占用会是什么样的
同样居高不下，CPU一半都没了

**Comment by KochiyaOcean** [comment]
@xiaoshuaivONE 所以 10.0.0 是什么情况

**Comment by xiaoshuaivONE** [comment]
> @xiaoshuaivONE所以10.0.0是什么情况

![qq 20181215135625](https://user-images.githubusercontent.com/45873105/50039695-488cc400-0071-11e9-8c41-f688a4c9af70.png)
有所好转

**Comment by Squall-Lucifer** [comment]
參考:
我的CPU是i7-6700K 4.2Ghz
顯卡:GTX 1060 6GB OC
CPU使用率由3%到9%，顯卡平均使用率為10%

**Comment by KagamiChan** [comment]
我的 i7 4770k 的 cpu 占用率在 10+% 左右吧，没有特别关注

只能解释为上游 electron 的性能的问题了，大部分情况下 poi 这边能够做的并不是特别多。
