### ISSUE TITLE
poi 10.0.0 beta.0 上游代理功能失效

### ISSUE THREAD

**Issue by pogox** [poooi/poi#2047]
poi 版本 / poi version: poi-10.0.0-beta.0-win
操作系统 / OS: Windows10 x64

中继模式功能，在10.0.0-beta.0中无法使用。
表现为，其他浏览器（本机，或局域网设备）使用http代理协议，仅能正常访问dmm.com主页，访问其他任何页面都会提示ERR_EMPTY_RESPONSE。
（同样的防火墙和poi设置，在poi-9.0.4及旧版中能正常生效）

**Comment by KochiyaOcean** [comment]
重构后的代理模式没有 https 支持，不过既然还有人用中继模式那么就会加回来

**Comment by pogox** [comment]
> 重构后的代理模式没有 https 支持，不过既然还有人用中继模式那么就会加回来

了解，辛苦啦~
因为用移动端玩的时候会经常走poi上游记录日志数据
