### ISSUE TITLE
poi黑屏

### ISSUE THREAD

**Issue by ChenjieShou** [poooi/poi#2048]
**poi 版本 / poi version: 10.0.0

**操作系统 / OS: win10 x64 build 17763.194

**你遇到了什么样的问题 / The problem you've met: 重装系统后poi输入帐号密码，黑屏。删除ssr，命令行管理员输入netsh winsock reset，删除appdata和安装路径文件夹，重新安装poi，依旧没有解决问题。岛风go，使用chrome可以正常登入游戏。poi里面可以正常打开baidu.com。poi.exe拉入win+r可以正常打开，当然也是输入帐号密码后黑屏。
Thanks
![2018-12-16 2](https://user-images.githubusercontent.com/44863145/50050917-9b827c00-0142-11e9-90d8-eaec7eb9ba6f.png)
![2018-12-16 3](https://user-images.githubusercontent.com/44863145/50050918-9c1b1280-0142-11e9-81b7-61a25b9b1935.png)

**Comment by KochiyaOcean** [comment]
使用的代理和代理设置是？

**Comment by ChenjieShou** [comment]
岛风go 的http 127.0.0.1 8099

**Comment by KochiyaOcean** [comment]
@ChenjieShou win+r 输入 cmd 启动命令行，拖入 poi.exe 看看网络连接出错时有没有报错

**Comment by ChenjieShou** [comment]
[WARN]  Cannot get system flash plugin path
[INFO]  Proxy listening on 54623, upstream proxy http://127.0.0.1:8099

**Comment by KochiyaOcean** [comment]
@ChenjieShou 黑屏的话应该会有更多提示才对

**Comment by ChenjieShou** [comment]
关闭poi
[WARN]  Cannot get system flash plugin path
[INFO]  Proxy listening on 55045, upstream proxy http://127.0.0.1:8099
Attempting to call a function in a renderer window that has been closed or released.
Function provided here: Array.map (<anonymous>:null:null
Remote event names: closed

**Comment by KochiyaOcean** [comment]
@ChenjieShou 没有更多信息了？

**Comment by KochiyaOcean** [comment]
@ChenjieShou https://baidu.com 能否正常访问

**Comment by ChenjieShou** [comment]
baidu.com可以正常访问，poi.exe拉进管理员命令行也没有更多信息

**Comment by ChenjieShou** [comment]
![2018-12-16 5](https://user-images.githubusercontent.com/44863145/50051138-e6eb5900-0147-11e9-93d0-869616e67a1c.png)

**Comment by ChenjieShou** [comment]
命令行重新 netsh winsock reset了

**Comment by KochiyaOcean** [comment]
@ChenjieShou 刷新下看看 network tab

**Comment by KagamiChan** [comment]
先把岛风 go 提供的那些扩展功能，比如 live2d，性能优化之类的先关闭再试试？

**Comment by ChenjieShou** [comment]
昨天下的岛风go，没有在设置里找到性能优化，也没有放入魔改文件

**Comment by ChenjieShou** [comment]
刷新游戏
![2018-12-16 7](https://user-images.githubusercontent.com/44863145/50051205-fb7c2100-0148-11e9-989c-ec56752f9c61.png)

**Comment by KochiyaOcean** [comment]
@ChenjieShou 切到 network 那边

**Comment by ChenjieShou** [comment]
切到了network， F5，poi关闭了
[WARN]  Cannot get system flash plugin path
[INFO]  Proxy listening on 50379, upstream proxy http://127.0.0.1:8099
[ERROR]  POST http://osapi.dmm.com/ShimakazeGoRunCheck?_r=0.11165008395895137 Error: connect ECONNREFUSED 127.0.0.1:8099
[ERROR]  POST http://osapi.dmm.com/ShimakazeGoRunCheck?_r=0.9806079923932463 Error: connect ECONNREFUSED 127.0.0.1:8099
[ERROR]  POST http://osapi.dmm.com/ShimakazeGoRunCheck?_r=0.12283059950948494 Error: connect ECONNREFUSED 127.0.0.1:8099
Attempting to call a function in a renderer window that has been closed or released.
Function provided here: Array.map (<anonymous>:null:null
Remote event names: closed

**Comment by ChenjieShou** [comment]
切到network， F5， poi自己关闭了。重下了岛风go，找到并关闭了live2D

**Comment by KagamiChan** [comment]
操作步骤：
- 打开 poi
- 右键开发者工具按钮
- 在打开的开发者工具上，切换到 network
- 刷新游戏

**Comment by ChenjieShou** [comment]
谢谢，打开poi可以用了

**Comment by ChenjieShou** [comment]
可能是live 2D的问题？最近的操作是关掉了live2D，清除缓存然后network错误的F5。 Thanks

**Comment by KagamiChan** [comment]
不了解，可以确认是岛风 go 侧的问题，具体问岛风 go 客服吧
