### ISSUE TITLE
无法指定截图目录

### ISSUE THREAD

**Issue by Westernnero** [poooi/poi#2049]
**poi 版本 / poi version:**
10.0.0

**操作系统 / OS:**

Win10 1809

**插件名和版本 / Plugin name & version:**

**你遇到了什么样的问题 / The problem you've met:**
按照以前一样尝试进行游戏截图，结果保存到了Appdata里面。之前一直都是指定的另外一个文件夹。修改设置里的截图目录也没有用。
![snipaste_2018-12-20_16-40-41](https://user-images.githubusercontent.com/40510735/50273623-1961c280-0476-11e9-8d04-a3e1e696fa5f.jpg)

**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:**

**Comment by KochiyaOcean** [comment]
dup  issue #2041
