### ISSUE TITLE
poi 10.0.0 beta.1 中继模式的局域网开放功能不工作

### ISSUE THREAD

**Issue by pogox** [poooi/poi#2050]
poi 版本 / poi version: poi-10.0.0-beta.1-win
操作系统 / OS: Windows10 x64

赞美beta.1第一时间恢复了中继模式~

不过测试发现，poi开放的端口似乎仅本机能访问，并没有开放到局域网？
（监视器显示poi本地地址是ip环回，防火墙也没跳提示。。）

**Comment by KochiyaOcean** [comment]
开发者工具 console 里面跑 `config.get("proxy.allowLAN")` 是什么结果

**Comment by pogox** [comment]
返回false

看了下poi的配置文件config.cson

在poi客户端里修改选项好像影响的是`config:proxy:allowLAN: true`这一行

而`proxy:allowLAN: false`这一行手动修改为true之后，局域网功能即恢复正常，
console 里面跑 config.get("proxy.allowLAN")也是true

**Comment by pogox** [comment]
> 开发者工具 console 里面跑 `config.get("proxy.allowLAN")` 是什么结果

返回false

看了下poi的配置文件config.cson

在poi客户端里修改选项好像影响的是config:proxy:allowLAN: true这一行

而proxy:allowLAN: false这一行手动修改为true之后，局域网功能即恢复正常，
console 里面跑 config.get("proxy.allowLAN")也是true

**Comment by KagamiChan** [comment]
多谢指出，路径错误导致设置没有生效
