### ISSUE TITLE
10.0.0-beta0 tab切换效果延迟

### ISSUE THREAD

**Issue by alive1944** [poooi/poi#2052]
poi1.0.0-beta0版本，win10操作系统，tab的再切换时，切换动画有明显延迟
具体体现为，当我点击另一个tab，tab下面的高亮条立刻反应并且移动至目标tab，然后在高亮条移动完毕之后，下方的tab内容才会开始动画过渡效果

**Comment by KochiyaOcean** [comment]
beta1 呢

**Comment by FX9590** [comment]
beta1 中速度上有较大改善，上方的标签栏（就是概览、舰队等）和下方的主要内容的动画看起来还是不那么同步。

**Comment by KochiyaOcean** [comment]
@FX9590 因为是故意的
