### ISSUE TITLE
10.0.0，UI排版相关bug

### ISSUE THREAD

**Issue by AndyPanda1205** [poooi/poi#2054]
**poi 版本 / poi version:**  10.0.0-beta1

**操作系统 / OS:**  Windows10 1803，17134.167

**插件名和版本 / Plugin name & version:**  未卜先知

**你遇到了什么样的问题 / The problem you've met:**

1.未卜先知插件，如图，本方舰娘的配置数据消失（注意伊400的左侧，本来应该显示出装备和舰娘数据，然而因为超出边界而消失）
![image](https://user-images.githubusercontent.com/13083990/50392998-f729b680-078d-11e9-929a-00a4cb0ef214.png)
敌方则一切正常，如图
![image](https://user-images.githubusercontent.com/13083990/50392993-ee38e500-078d-11e9-87f3-3486b149f40b.png)
2.如图，时间遮挡了舰娘名（800x1040下）
![2](https://user-images.githubusercontent.com/13083990/50392939-6fdc4300-078d-11e9-8a8f-2a411aabdeca.png)
舰娘名变成省略号（960x1040下）
![image](https://user-images.githubusercontent.com/13083990/50393135-078e6100-078f-11e9-879d-8cd8b416a1b6.png)
3. （10.0.0 beta0没有，beta1出现）如图
![1](https://user-images.githubusercontent.com/13083990/50392933-67840800-078d-11e9-91ba-4ab92cbd4d1a.png)

**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:**

可能相关的数据：
游戏分辨率：67%，800*480px
缩放：100%
窗口大小：800x1040（贴靠屏幕一侧并左右缩小窗口大小，直到不能缩小为止），960x1040（仅贴靠屏幕一侧，不修改窗口大小）
布局及主题如图所示，其中Dark和Light主题我都试过，都有这个问题
![image](https://user-images.githubusercontent.com/13083990/50392896-24c23000-078d-11e9-87fb-71ca6ad04579.png)

**Comment by KagamiChan** [comment]
1. 未卜先吃会适配新的 ui，之后应该能够正常显示

2. 可能需要调整一些显示方式

3.beta.1 为了避免分离模式下的一些 bug 所以对于显示方向进行了一些调整，不过的确有可能不适用于其它的显示模式。我之后看一下有没有什么优化的空间

**Comment by KagamiChan** [comment]
2 和 3 都做了一些更改，可以到

https://ci.appveyor.com/project/KochiyaOcean/poi/builds/21251689/artifacts

这里下载体验一下
