### ISSUE TITLE
MAC能不能做一个把程序放在顶部菜单栏的功能

### ISSUE THREAD

**Issue by alive1944** [poooi/poi#2055]
希望可以有一个设置可以吧poi放在顶部菜单栏，像qq那样，然后同时隐藏掉dock栏的图标
我尝试过修改包内info.plist的方法，但这么做的后果是我无法在切换应用中看见他

**Comment by KochiyaOcean** [comment]
不了解 macOS 开发，不过现有的情况来讲隐藏 dock 大概不现实

**Comment by KagamiChan** [comment]
顶部状态栏可以加图标，但是 dock 图标基本上没有见到有专门隐藏的

**Comment by alive1944** [comment]
我想说dock的隐藏作为一个可选配置选项，实在不行我还可以通过该info.plist实现。当然有这个想法实际还是因为上班悄悄艹船的需求，本身也是程序员，经常会有人过来对需求或者其他什么事情，如果隐藏dock的话感觉风险会降低很多
我倒是知道有个叫ghosttile的软件可以隐藏dock，他自己也是dock可以不显示，只在菜单栏停留。如果隐藏dock困难，那是否可以将程序运行图表加入菜单栏？隐藏dock可以通过别的外部搜狐段也无所谓

**Comment by KagamiChan** [comment]
实现 tray 的主要问题可能还是缺少一个（组？）符合 macOS 系统风格的图标

**Comment by KochiyaOcean** [comment]
自己动手的话把 https://github.com/poooi/poi/blob/master/app.js#L214~L224 这里的 `process.platform` 的判断去掉就能增加托盘图标了（当然，不好看

**Comment by KochiyaOcean** [comment]
@alive1944 icon path 那边 ico 改成 png 看看

**Comment by KagamiChan** [comment]
@alive1944 如果 icon 叫做 icon.png 的话，可以在同目录下放对应的 icon@2x.png icon@3x.png

**Comment by alive1944** [comment]
可以，很强！~附一张效果图，放大看细节很差，不过实际使用的时候因为很小，看上去效果海星.jpg
![image](https://user-images.githubusercontent.com/21339652/50444182-136e5480-0942-11e9-9b6b-13a6903cc9c1.png)

**Comment by alive1944** [comment]
撒，问题来了，我如何打包mac-app呢？我没玩过这个，有打包教程吗，我尝试npm build然而并没什么卯月

**Comment by KagamiChan** [comment]
@alive1944 试一下 npm run build？

**Comment by alive1944** [comment]
```
$ npm run build

> poi@10.0.0-beta.1 build /Users/my_mac/Documents/poi
> gulp build && electron-builder -p never

/Users/my_mac/Documents/poi/lib/utils.es:133
      options = { ...options,
                  ^^^

SyntaxError: Unexpected token ...
    at createScript (vm.js:74:10)
    at Object.runInThisContext (vm.js:116:10)
    at Module._compile (module.js:533:28)
    at Module._compile (/Users/my_mac/Documents/poi/node_modules/pirates/lib/index.js:83:24)
    at Module._extensions..js (module.js:580:10)
    at Object.newLoader [as .es] (/Users/my_mac/Documents/poi/node_modules/pirates/lib/index.js:88:7)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! poi@10.0.0-beta.1 build: `gulp build && electron-builder -p never`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the poi@10.0.0-beta.1 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/my_mac/.npm/_logs/2018-12-26T11_49_45_351Z-debug.log
```

运行报错，跟我之前看到的是一样的信息

**Comment by KochiyaOcean** [comment]
@alive1944 node 太旧了

**Comment by alive1944** [comment]
666，不愧是专业的开发大佬，node确实一年多没更新了，成功了，多谢大佬们的指点

**Comment by alive1944** [comment]
你是指git commit 提交到github嘛？

**Comment by KagamiChan** [comment]
@alive1944 不是，在本地 commit 就可以了，build 过程中只会复制 commit 过的内容

**Comment by alive1944** [comment]
```
git status
On branch master
Your branch is up to date with 'origin/master'.

Changes to be committed:
  (use "git reset HEAD <file>..." to unstage)

	modified:   app.js
	new file:   assets/icons/p.png
	new file:   assets/icons/p@2x.png
	new file:   assets/icons/p@3x.png
	new file:   assets/icons/p@4x.png

Untracked files:
  (use "git add <file>..." to include in what will be committed)

	.idea/

```

emmm。。。我已经commit了，但是build出来的代码还是没有托盘，试了好几回，也有预先删掉dist文件夹内容再build

**Comment by KagamiChan** [comment]
@alive1944 这个是 staged 状态？

**Comment by KagamiChan** [comment]
@alive1944 你也可以稍微等两天，我们正准备正式写一下这部分

**Comment by alive1944** [comment]
嗯，不过现在这个激起了我的好奇心...emmm搞不定就很难受，我将build出来的poi启动后，开发者工具打印appIcon，显示undefined，用过npm start启动是有值得对象

build出来的代码
```
appIcon
undefined
```


直接 npm start 的console
```
appIcon
{...}
```

我将appIcon设置成global变量了，不然托盘会出现几秒后就消失，查过过后说是被垃圾自动回收掉了。

```
global.appIcon = null

  global.appIcon = new Tray(poiIconPath)
  global.appIcon.on('click', () => {
    if (mainWindow.isMinimized()) {
      mainWindow.restore()
    } else {
      mainWindow.show()
    }
```

**Comment by alive1944** [comment]
已经基本实现 托盘 显示，并且启动时隐藏dock图标，通过comman+w或者x关闭窗口不会退出程序而是隐藏，由托盘区菜单实现主程序窗口的再显示。嗯！再也不同担心突然来人了！

**Comment by KagamiChan** [comment]
@alive1944 https://poidb.0u0.moe/nightly/5859/
我这边写的，可以看一下符不符合你的预期

**Comment by alive1944** [comment]
@KochiyaOcean 
你这个托盘UI比我这个好太多了~。而且这个功能符合我的预期~
我自个而又加了些魔改内容，现在变成了专门上班悄悄船C的个人魔改版本。以后打算研究研究再继续魔改

**Comment by promotion-xu** [comment]
@KagamiChan 这个链接403了，可以放个新的吗

**Comment by KagamiChan** [comment]
@promotion-xu 这个链接里面的版本已经很老了，请问你是有什么需求吗
