### ISSUE TITLE
macOS 版的标题栏不再隐藏

### ISSUE THREAD

**Issue by kisinsagume** [poooi/poi#2056]
**poi 版本 / poi v10.0:**

**操作系统 / OS: macOS

**插件名和版本 / Plugin name & version:**无

**你遇到了什么样的问题 / The problem you've met:**macOS 版的标题栏不再隐藏

**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:**

<img width="828" alt="poi issue" src="https://user-images.githubusercontent.com/46159496/50444077-5845bb80-0941-11e9-937f-819d65723ac0.png">
<img width="828" alt="poi issue" src="https://user-images.githubusercontent.com/46159496/50444084-5e3b9c80-0941-11e9-916a-c581753b2031.png">

**Comment by KagamiChan** [comment]
@kisinsagume macOS 哪个版本

**Comment by kisinsagume** [comment]
> @kisinsagume macOS 哪个版本

macOS Sierra version 10.12.6

**Comment by KagamiChan** [comment]
@kisinsagume 上游升级了导致 sierra 及以下没有办法开启无边框模式

**Comment by kisinsagume** [comment]
啊啊好的，谢谢

**Comment by KagamiChan** [comment]
看了一下上游 electron/electron#14730 已经修复了。但是我手边没有 sierra 的机器了，请问你可以帮忙验证一下是否修复吗，如果可以的话我会单独给你生成一个去掉系统版本检测的版本
