### ISSUE TITLE
更新10.0之后运行程序完全黑屏

### ISSUE THREAD

**Issue by yanagi310** [poooi/poi#2057]
**poi 版本 / poi version:**

10.0-beta1
**操作系统 / OS:**
win10 1803

**你遇到了什么样的问题 / The problem you've met:**
更新10.0之后打开程序完全黑屏，窗口里什么控件都不显示，也没有任何类似报错的弹窗提示
之后运行更低版本也出现相同问题，更新10.0之前9.04是正常的，目前是完全无法使用的状态

**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:**

**Comment by KochiyaOcean** [comment]
@yanagi310 ctrl + shift + i 可以打开开发者工具么

**Comment by yanagi310** [comment]
可以的

**Comment by KochiyaOcean** [comment]
@yanagi310 看看报错内容

**Comment by yanagi310** [comment]
好的，谢谢

**Comment by KagamiChan** [comment]
@yanagi310 如果看到有报错内容麻烦截图
