### ISSUE TITLE
鼠标在主界面舰娘信息上面移动，提示框会不停的闪

### ISSUE THREAD

**Issue by EmiliaMiyuki** [poooi/poi#2061]
**poi 版本 / poi version:**
10.0.0

**操作系统 / OS:**

win10 1809
**插件名和版本 / Plugin name & version:**

**你遇到了什么样的问题 / The problem you've met:**
在主界面了鼠标移到舰队信息上面的舰娘头像上，两个不同的提示框会交替闪，闪几次提示框就没有了

![image](https://user-images.githubusercontent.com/9192383/50544054-fb3d5480-0c23-11e9-9f03-8c9a2c2aae9b.png)

**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:**
鼠标移到主界面舰娘信息上面就会出现重叠的信息框，并且鼠标只要动一下就会重新闪，个人觉得是不是应该换一下监听的事件，以前是没有动画效果的因此鼠标移动一次就执行一个事件也看不出来，但是现在有动画鼠标移动一次就会重新播放一次动画导致不停的闪。

![image](https://user-images.githubusercontent.com/9192383/50544060-13ad6f00-0c24-11e9-8060-5119fcae228c.png)

**Comment by KagamiChan** [comment]
能否截一个你的主面板的完整图

**Comment by EmiliaMiyuki** [comment]
![](https://emiliamiyuki.github.io/images/181230.gif)

**Comment by Cuiyn** [comment]
这里poi 10.0.0在Windows 10 1803上遇到了类似现象，感觉可能是电脑的屏幕太小导致自适应出现问题，请参考下面的截图：
![poi](https://user-images.githubusercontent.com/13913903/50555311-44190a00-0d05-11e9-8173-fba04b5c4ff4.gif)
开发者工具终端：
![poi](https://user-images.githubusercontent.com/13913903/50555314-55621680-0d05-11e9-8460-d9db7740c606.png)
