### ISSUE TITLE
10.0.0 WebView开发者工具无法打开

### ISSUE THREAD

**Issue by sandwichii** [poooi/poi#2064]
**poi 版本 / poi version:**
10.0.0

**操作系统 / OS:**
Windows 7 x64 SP1

**你遇到了什么样的问题 / The problem you've met:**
点击**显示** >**Webview开发者工具**，没正常打开网页的控制台。

这个截图提示的warning来自**显示**>**开发者工具**。

![sp181230_173132](https://user-images.githubusercontent.com/8279800/50545912-53427e00-0c59-11e9-9321-fda94659bdc9.png)

**Comment by KochiyaOcean** [comment]
是否是只有分离模式下出现的问题？
