### ISSUE TITLE
Please Fix Translate new quest new year 2019 xD

### ISSUE THREAD

**Issue by wayinsight** [poooi/poi#2067]
**poi 版本 / poi version:**

**操作系统 / OS:**

**插件名和版本 / Plugin name & version:**

**你遇到了什么样的问题 / The problem you've met:**

**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:**

**Comment by KagamiChan** [comment]
It's because last year's quest ID are reused. I've published a new quest plugin and remove them
