### ISSUE TITLE
poi浏览器用socks5代理黑屏

### ISSUE THREAD

**Issue by EzioMIA** [poooi/poi#2068]
**poi 版本 / poi version:**

**操作系统 / OS:**

**插件名和版本 / Plugin name & version:**

**你遇到了什么样的问题 / The problem you've met:**

**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:**

**Comment by EzioMIA** [comment]
poi 版本 / poi version:
10.0.0
操作系统 / OS:
windows 1803
你遇到了什么样的问题 / The problem you've met:
  ##使用socks5连接黑屏。就是把shadowsocks的服务器地址和服务器端口对应填入后就没反应了，一直黑屏，连dmm的登陆界面都显示不出来
有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:

**Comment by KochiyaOcean** [comment]
@EzioMIA 请提供代理设置截图

**Comment by EzioMIA** [comment]
![image](https://user-images.githubusercontent.com/46293390/50571387-d5f74480-0de3-11e9-8510-cce5f0f2dc45.png)

**Comment by EzioMIA** [comment]
![image](https://user-images.githubusercontent.com/46293390/50571394-fd4e1180-0de3-11e9-839f-4b3cacc13103.png)

**Comment by KochiyaOcean** [comment]
@EzioMIA shadowsocks 客户端运行以后设置 127.0.0.1 端口 1080，不应该指定远程服务器端口，shadowsocks 不是 socks5
