### ISSUE TITLE
macOS 10.0.0版本 一直等待游戏数据

### ISSUE THREAD

**Issue by oracion7** [poooi/poi#2070]
**poi 版本 / poi version:** 10.0.0

**操作系统 / OS:** macOS Mojave 10.14.2 (18C54)

**插件名和版本 / Plugin name & version:**

**你遇到了什么样的问题 / The problem you've met:** 设置了代理为http 127.0.0.1 端口8123一直等待游戏数据

**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:**

![image](https://user-images.githubusercontent.com/10421044/50572986-d30d4b80-0e05-11e9-852d-b60997027cd7.png)

**Comment by oracion7** [comment]
用的是ACGPower，所以是8123

**Comment by KochiyaOcean** [comment]
@oracion7 菜单选显示 - webview 开发者工具，切到 network 部分截图看看

**Comment by oracion7** [comment]
Webview开发者工具点不动，开发者工具切到Network一片空白
![image](https://user-images.githubusercontent.com/10421044/50573755-c80de780-0e14-11e9-97fc-b20bd5ce41db.png)
不是acgpower的问题，chrome可以用，win版的poi也可以用，只有mac版用不了

**Comment by KochiyaOcean** [comment]
@oracion7 要刷新一下才有数据

**Comment by oracion7** [comment]
@KochiyaOcean 刷新了没用鸭，重启poi也这样T^T

**Comment by KochiyaOcean** [comment]
@oracion7 webview 开发者攻击，不是开发者工具

**Comment by oracion7** [comment]
@KochiyaOcean Webview开发者工具点了没反应的，什么都没发生
![image](https://user-images.githubusercontent.com/10421044/50573837-5fc00580-0e16-11e9-9251-c0d59ed99b1f.png)

**Comment by KochiyaOcean** [comment]
@oracion7 那么「右击」左下的开发者工具图标看看

**Comment by oracion7** [comment]
@KochiyaOcean 
![image](https://user-images.githubusercontent.com/10421044/50573892-934f5f80-0e17-11e9-97d7-7a9b38c7507a.png)

**Comment by KochiyaOcean** [comment]
@oracion7 其他网页（dmm 主页，百度等）是否是相同情况？

**Comment by oracion7** [comment]
@KochiyaOcean 如图所示，分别是百度，dmm主页，dmm游戏
![image](https://user-images.githubusercontent.com/10421044/50573921-1a043c80-0e18-11e9-9766-b9a1290ffb89.png)
![image](https://user-images.githubusercontent.com/10421044/50573924-28525880-0e18-11e9-94c3-e851eac4c3ea.png)
![image](https://user-images.githubusercontent.com/10421044/50573926-3e601900-0e18-11e9-9554-76bac33fc249.png)

**Comment by KochiyaOcean** [comment]
@oracion7 有修改过 hosts 之类的文件么

**Comment by oracion7** [comment]
@KochiyaOcean 因为在用jetbrains ide所以加过一个，别的没了
![image](https://user-images.githubusercontent.com/10421044/50573952-c47c5f80-0e18-11e9-9e77-9bd1a2d8012b.png)

**Comment by KochiyaOcean** [comment]
@oracion7 开发者工具的 console 里面跑 `await fetch('https://games.dmm.com').then(e => e.text())` 是什么结果

**Comment by oracion7** [comment]
@KochiyaOcean 
![image](https://user-images.githubusercontent.com/10421044/50573984-5c7a4900-0e19-11e9-9a1a-9ddbf1f6f9bf.png)

**Comment by KochiyaOcean** [comment]
@oracion7 证书错误……有试过换线之类的操作么？还有 ACGP 里面有没有相关设置（证书导入之类）？

**Comment by oracion7** [comment]
@KochiyaOcean 
1. 换线没用
2. 没有证书导入，但有一个重新生成证书，点了没用
![image](https://user-images.githubusercontent.com/10421044/50574067-73ba3600-0e1b-11e9-9ea3-2b3ffac9b4d4.png)
3. 同一个acgp，在chrome里面可以打开dmm游戏，poi 9.0.4也可以用（白天卸载了10.0.0，装回了9.0.4可以用）

**Comment by oracion7** [comment]
@KochiyaOcean 
10.0.0
![image](https://user-images.githubusercontent.com/10421044/50574112-aca6da80-0e1c-11e9-94c4-6c64a12c0ae8.png)
9.0.4
![image](https://user-images.githubusercontent.com/10421044/50574147-54240d00-0e1d-11e9-8910-8acc6640d130.png)

**Comment by oracion7** [comment]
@KochiyaOcean 
![image](https://user-images.githubusercontent.com/10421044/50574234-1d4ef680-0e1f-11e9-8f37-d90c4e81228f.png)

**Comment by KochiyaOcean** [comment]
@oracion7 require('dns').lookup('games.dmm.com', (...e) => console.log(e)) 呢

**Comment by oracion7** [comment]
@KochiyaOcean 
![image](https://user-images.githubusercontent.com/10421044/50574279-35734580-0e20-11e9-92d0-8ac9c7e279d8.png)

**Comment by oracion7** [comment]
@KagamiChan 
10.0.0
![image](https://user-images.githubusercontent.com/10421044/50577998-801bae80-0e6e-11e9-849b-1dfdb147ee17.png)
9.0.4
![image](https://user-images.githubusercontent.com/10421044/50578002-84e06280-0e6e-11e9-90fd-c96de2c68c1d.png)

**Comment by KochiyaOcean** [comment]
@oracion7 购买 ACGP 测试以后未能复现，请问在载入 https 页面（https://games.dmm.com 等） webview 开发者工具的 security tab 显示的证书是什么？
正常情况是如图所示的
![image](https://user-images.githubusercontent.com/8194131/50592961-be9a8300-0ed9-11e9-9eb3-93e9e6597255.png)

**Comment by oracion7** [comment]
@KochiyaOcean 
9.0.4可以正常游戏，但是证书好像有问题...这么说是我这里acgp的证书问题吗？
![image](https://user-images.githubusercontent.com/10421044/50595559-dc68e780-0edb-11e9-9aee-b1876663cfad.png)
嗯，发现chrome访问的话也有这个问题
![image](https://user-images.githubusercontent.com/10421044/50595586-028e8780-0edc-11e9-835e-cd96dc4fab63.png)
是因为9.0.4认为证书不安全后转为载入http，而10.0.0必须是https吗？

**Comment by KochiyaOcean** [comment]
@oracion7 ACGP 的 windows 版会要求导入自签证书所以这个证书被认证了，mac 版应该也有类似设置，感觉这个需要问一下作者……
至于 poi 从 9.0.x 到 10.0.x 不能用的原因，大概是 Chrome 内核更新导致原来设置的无视证书错误的 switch 失效了……

**Comment by oracion7** [comment]
@KochiyaOcean 嗯，我大概了解了，谢谢dalao

**Comment by oracion7** [comment]
已解决，办法是在macOS的**钥匙访问串**里将acgp目录下的ap.cer证书添加到系统中并修改为总是信任。
macOS用acgp默认是没有导入证书的，必须手动...
