### ISSUE TITLE
10.0.0截图不显示签名与舰队名

### ISSUE THREAD

**Issue by yujunqin** [poooi/poi#2071]
**poi 版本 / poi version:** 10.0.0

**操作系统 / OS:** Win10 1803 17134.472

**插件名和版本 / Plugin name & version:**

**你遇到了什么样的问题 / The problem you've met:** 截图中签名栏和舰队名一片空白，翻看秋活截图不存在该现象。

**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:** 多次截图均存在该情况。

![image](https://user-images.githubusercontent.com/12068945/50574277-2be9dd80-0e20-11e9-8542-c69764dae9e4.png)
![image](https://user-images.githubusercontent.com/12068945/50574280-3906cc80-0e20-11e9-91e6-115f868b62ab.png)

**Comment by KochiyaOcean** [comment]
10.0.0 以后截图行为变更，现在类似于 chrome 右键选择保存图片的效果，副作用就是带输入框的部分都无法显示

**Comment by KochiyaOcean** [comment]
由于这种方式的截图质量更高，需要讨论是否回到旧模式

**Comment by KagamiChan** [comment]
理论上可以保留两个模式，让用户来选择

**Comment by KagamiChan** [comment]
于是我们默认已经切回旧模式了
