### ISSUE TITLE
能正常进行游玩，但一直显示poi等待游戏数据中

### ISSUE THREAD

**Issue by 794673085** [poooi/poi#2074]
**poi 版本 / poi version:**
10.0.0

**操作系统 / OS:**

win10 1803 17134.472
**插件名和版本 / Plugin name & version:**

**你遇到了什么样的问题 / The problem you've met:**
能正常进行游玩，但一直显示poi等待游戏数据中

![qq 20190102224236](https://user-images.githubusercontent.com/33588311/50596582-bb09fa80-0edf-11e9-8ed3-a5421553a3c0.png)

**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:**

![qq 20190102223906](https://user-images.githubusercontent.com/33588311/50596579-ba716400-0edf-11e9-8b0a-125cc36665d7.png)
![qq 20190102224201](https://user-images.githubusercontent.com/33588311/50596580-bb09fa80-0edf-11e9-918f-f05f06c49e1a.png)

**Comment by KochiyaOcean** [comment]
代理设置错误
poi 端口不要设置为上游代理的端口

**Comment by 794673085** [comment]
中继模式那里的吗

**Comment by KochiyaOcean** [comment]
对，如果你不使用串联模式（航海日志接 poi 之类）就不要修改那边的数值，代理设置在上面

**Comment by 794673085** [comment]
那要怎么改呢，我默认是9005，勾选允许。
改成9006或是别的数还是不行。

**Comment by KochiyaOcean** [comment]
不需要固定数值的时候改成 0。
对于代理设置的端口，在上面的代理类型里选择正确的类型（岛风 Go 等是 HTTP，Shadowsocks 是 socks5），然后填入本地代理的端口（按你的描述应该是 9005）

**Comment by 794673085** [comment]
还是不行，我使用的是acgp，端口是8123。
![qq 20190102231219](https://user-images.githubusercontent.com/33588311/50597923-09b99380-0ee4-11e9-84a3-d2d9a364c347.png)

**Comment by KochiyaOcean** [comment]
改完需要重启

**Comment by KochiyaOcean** [comment]
ctrl + r 输入 cmd 回车，poi 图标拖进去以后回车看看输出

**Comment by 794673085** [comment]
[WARN]  Cannot get system flash plugin path
[INFO]  Proxy listening on 3006, upstream proxy http://127.0.0.1:8123

**Comment by KochiyaOcean** [comment]
查看一下防火墙设置是否拦截了 poi

**Comment by 794673085** [comment]
防火墙已经被我禁用了，整个wd都禁用了。10.0之前也正常。

**Comment by KochiyaOcean** [comment]
开发者工具有无报错？

**Comment by 794673085** [comment]
yo有
![x0d x1b rzap9lx7 uq9 q](https://user-images.githubusercontent.com/33588311/50599362-d9282880-0ee8-11e9-858f-2569c72db0fb.png)

**Comment by KochiyaOcean** [comment]
你确定代理是正确设置的么…… 代理的设置也截图看看吧

**Comment by 794673085** [comment]
![qq 20190102234938](https://user-images.githubusercontent.com/33588311/50599490-3a4ffc00-0ee9-11e9-942b-04ff5da7ead6.png)
![qq 20190102235026](https://user-images.githubusercontent.com/33588311/50599492-3a4ffc00-0ee9-11e9-8589-c9e8fbe69be4.png)
能正常游玩。

**Comment by 794673085** [comment]
![qq 20190102235219](https://user-images.githubusercontent.com/33588311/50599607-8bf88680-0ee9-11e9-88ae-f704a9594062.png)
![qq 20190102235238](https://user-images.githubusercontent.com/33588311/50599609-8bf88680-0ee9-11e9-90e1-23c94f3cf458.png)

**Comment by KochiyaOcean** [comment]
能正常显示游戏数据么

**Comment by 794673085** [comment]
能，剧透也正常

**Comment by KochiyaOcean** [comment]
那没有安装字幕插件而且关闭了网络状态显示的情况下是正常的……

**Comment by KochiyaOcean** [comment]
之后会加一个状态表示游戏已经收到数据

**Comment by 794673085** [comment]
开了网络状态显示就会这样
![qq 20190103000618](https://user-images.githubusercontent.com/33588311/50600219-68364000-0eeb-11e9-9030-bc97088d1ab4.png)

**Comment by KochiyaOcean** [comment]
嗯，正常情况

**Comment by 794673085** [comment]
那现在就是暂时用不了字幕插件其他没有问题。

**Comment by KochiyaOcean** [comment]
重装字幕插件看看吧……

**Comment by 794673085** [comment]
不行，重装插件后重启poi后，还是一直是显示poi等待游戏数据中

**Comment by 794673085** [comment]
！好吧问题解决了

**Comment by 794673085** [comment]
辛苦了
