### ISSUE TITLE
10.0.0 無法開啟

### ISSUE THREAD

**Issue by 7mountain** [poooi/poi#2076]
**poi 版本 / poi version:  10.0.0  10.1.0

**操作系统 / OS:  Win10家用 1803

**你遇到了什么样的问题 / The problem you've met:**

10版本點擊後螢幕會閃爍一下但無法啟動
9.0.4以前都沒問題

**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:**

cmd截圖
![0103](https://user-images.githubusercontent.com/46347726/50639037-d423b180-0f9a-11e9-96db-3a9f0a55e433.JPG)

**Comment by KochiyaOcean** [comment]
@7mountain 重新下载安装包安装

**Comment by 7mountain** [comment]
已重安裝  
![01032](https://user-images.githubusercontent.com/46347726/50639210-9d01d000-0f9b-11e9-87b4-a752182f1c05.JPG)

**Comment by KochiyaOcean** [comment]
@7mountain 重新下载了么

**Comment by 7mountain** [comment]
是
64位Windows安裝包
poi-setup-10.1.0.exe 這個

**Comment by KochiyaOcean** [comment]
@7mountain 托盘有无小图标？

**Comment by 7mountain** [comment]
沒有  
但工作管理員  後台 ![01034](https://user-images.githubusercontent.com/46347726/50640279-5ada8d80-0f9f-11e9-908c-e5616729e165.JPG)

10.1.0

**Comment by KochiyaOcean** [comment]
管理员权限 cmd 跑 `netsh winsock reset` 看看

**Comment by 7mountain** [comment]
順利重設 Winsock Catalog。
重開機
情況一樣

**Comment by KochiyaOcean** [comment]
@7mountain cmd 启动的时候在后面加上 --dev 看看？

**Comment by 7mountain** [comment]
![01035](https://user-images.githubusercontent.com/46347726/50641091-d9382f00-0fa1-11e9-85c5-f9427384d7ba.JPG)

**Comment by KagamiChan** [comment]
@7mountain 系统里面是不是还有其他盘？麻烦换一个驱动器安装试一下，或者下载绿色 7z 版本解压运行

**Comment by KochiyaOcean** [comment]
@7mountain 这里测试并没有触发列出的 ERROR……
下载下来的安装包特征码是什么？sha512 的值应该是 `BPPWSrkmQG4n6iIUip6CIEdacgIG0rCTaecgfdR8C5lSCykaaE/Y3vZM7lRccgqk62sSwhKNlCjzgzxmADdtGA==`

**Comment by 7mountain** [comment]
@KagamiChan 各盤都試過 都一樣  解壓版本也試過

**Comment by 7mountain** [comment]
@KochiyaOcean 非專業  請問怎麼看特征码

**Comment by 7mountain** [comment]
Filename   poi-setup-10.1.0.exe
SHA-512 
04f3d64ab926406e27ea22148a9e8220475a720206d2b09369e7207dd47c0b99520b291a684fd8def64cee545c720aa4eb6b12c2128d9428f3833c6600376d18

**Comment by KochiyaOcean** [comment]
https://github.com/poooi/poi/releases/tag/v10.1.0 从这里下载看看？

**Comment by 7mountain** [comment]
跟原本的檔一樣

**Comment by 7mountain** [comment]
非常感謝你
我先用9.0.4吧
