### ISSUE TITLE
poi9.04黑屏

### ISSUE THREAD

**Issue by onlykotori** [poooi/poi#2077]
**poi 版本 / poi version:**

**操作系统 / OS:**

**插件名和版本 / Plugin name & version:**

**你遇到了什么样的问题 / The problem you've met:**

**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:**

**Comment by onlykotori** [comment]
C:\Users\tanluwei>C:\Users\tanluwei\Desktop\poi.lnk

C:\Users\tanluwei>
[INFO]  Proxy listening on 54933
[ERROR]  Connection failed: GET http://www.dmm.com/netgame/social/application/-/detail/=/app_id=854854/ Error: socket hang up
npm WARN saveError ENOENT: no such file or directory, open 'C:\Users\tanluwei\AppData\Roaming\poi\wctf-db\package.json'
npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\tanluwei\AppData\Roaming\poi\wctf-db\package.json'
npm WARN wctf-db No description
npm WARN wctf-db No repository field.
npm WARN wctf-db No README data
npm WARN wctf-db No license field.

+ whocallsthefleet-database@20190101.0.2
updated 1 package in 1.632s

**Comment by KochiyaOcean** [comment]
请说得详细点（至少把问题填上

**Comment by KochiyaOcean** [comment]
开发者工具有无报错

**Comment by onlykotori** [comment]
上面那个是放到cmd里面显示的，不知道怎么弄。。。

**Comment by onlykotori** [comment]
没有

**Comment by KochiyaOcean** [comment]
@onlykotori ctrl + shift + i 可以弹出开发者工具，以及是否是从 10.x 回来的

**Comment by onlykotori** [comment]
![1111](https://user-images.githubusercontent.com/46369052/50678674-30daa700-1043-11e9-855b-47123e5be14d.png)

**Comment by onlykotori** [comment]
什么10.x回来的，不懂..

**Comment by KochiyaOcean** [comment]
@onlykotori 就是更新过最新版么，其实建议使用最新版

**Comment by onlykotori** [comment]
额不清楚啊，昨天还是前天有个新版本更新我就更了啊，我也没看，然后昨晚还可以的，今天开就不行了

**Comment by onlykotori** [comment]
我现在按检查更新也没反应

**Comment by KochiyaOcean** [comment]
@onlykotori 呃你 poi.io 下个安装包重新装下

**Comment by onlykotori** [comment]
换了10.1.0了，也黑屏，说我网络连接失败，但我端口什么的没错啊

**Comment by onlykotori** [comment]
![22222](https://user-images.githubusercontent.com/46369052/50680052-93cf3c80-1049-11e9-94f7-55cd0e9d8620.png)

**Comment by KagamiChan** [comment]
你用什么方式连接的
贴一下 poi 设置里面的网络部分看一下

**Comment by onlykotori** [comment]
![image](https://user-images.githubusercontent.com/46369052/50680085-b7928280-1049-11e9-99fe-35f7f7b95fd7.png)

**Comment by KagamiChan** [comment]
岛风 go ？

**Comment by onlykotori** [comment]
嗯啊

**Comment by KagamiChan** [comment]
@onlykotori 管理员权限 cmd 运行 netsh winsock reset 看看，再试试其它线路

**Comment by onlykotori** [comment]
已运行，换了华南地区线路，然后重新开dmm官网进舰c，已经ok了，thx
