### ISSUE TITLE
战斗记录保存图片背景&文字的分辨度极差

### ISSUE THREAD

**Issue by FungJiHsu** [poooi/poi#2078]
**poi 版本 / poi version:**

10.1.0
**操作系统 / OS:**

win10
**插件名和版本 / Plugin name & version:**

战斗记录5.5.0
**你遇到了什么样的问题 / The problem you've met:**

如图所示
![download2019](https://user-images.githubusercontent.com/14539399/50723599-d01e9d80-111a-11e9-9b74-5e92c9b87d1d.png)

**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:**

**Comment by KochiyaOcean** [comment]
fixed by df4d602e1424621ff1b6882f999d606f3e6a2e50
