### ISSUE TITLE
战斗记录相关

### ISSUE THREAD

**Issue by sinlolicon** [poooi/poi#2079]
win10

战斗记录的节点视图还是无法使用吗？那怎么生成KC3回放记录呢

我知道有工具可以转POI记录成KC3 但是我就是先问问是等更新还是这个功能已经不做了

以及战斗记录保存截图好像也有问题

https://wx4.sinaimg.cn/orj360/82e3931bly1fywldqr4u6j20u01xgdnp.jpg

**Comment by Javran** [comment]
close as duplicate to https://github.com/poooi/plugin-battle-detail/issues/58 https://github.com/poooi/plugin-battle-detail/issues/59
