### ISSUE TITLE
poi不能拖动窗口

### ISSUE THREAD

**Issue by janmelin** [poooi/poi#2084]
**poi 版本 / poi version:**
10.1.0

**操作系统 / OS:**
macOS 10.14

**你遇到了什么样的问题 / The problem you've met:**
不能拖动窗口，包括使用窗口栏和三指拖动

**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:**
在删除`~/Library/Application Support/poi` 文件夹后重新安装poi 10.1，仍不能拖动窗口

打开开发者工具后能拖动窗口，但一旦关闭开发者工具就又不能拖动窗口了

**Comment by KagamiChan** [comment]
![jan-10-2019 16-32-14](https://user-images.githubusercontent.com/3816900/50955959-6d9c1780-14f5-11e9-840c-6f50c69b9fbf.gif)

**Comment by KagamiChan** [comment]
好像没有能够重复

你有没有安装什么辅助工具类的应用

**Comment by janmelin** [comment]
![10 1](https://user-images.githubusercontent.com/29978205/50957632-ae962b00-14f9-11e9-9ade-7b1a67b1a20a.gif)

这是10.1的

![9 0 4](https://user-images.githubusercontent.com/29978205/50957635-b0f88500-14f9-11e9-9bd9-548c99449014.gif)

这是9.0.4的
都是打开开发者工具才能拖。之前使用9.0.4也没出过这问题，就是前两天升级10.1后出现的。

**Comment by KagamiChan** [comment]
@janmelin 我们调整过拖放区域，可以多试一下？
主要也是我没能复现

**Comment by janmelin** [comment]
![panding](https://user-images.githubusercontent.com/29978205/50958361-7bed3200-14fb-11e9-9dd1-5a93f832d03a.gif)
无意中发现只有窗口上方一像素左右（凭经验已经算点到窗口外面了）可以拖。
奇怪的是重装9.0.4也存在这个问题。

**Comment by KagamiChan** [comment]
我做一下调查吧

在我这里有时候这个拖动区域出现得不是很及时

但是用开发者工具能看到 body 下面有个 div 是有 `-webkit-app-regeion` 的 style 属性的时候就可以拖动了

**Comment by matthew-z** [comment]
我现在用的 Mac (Mojave) 是没问题, 给老款 MBA (High sierra) 装了最新的poi之后发现也很难拖动, 不知道会不会跟Safari版本有关系
