### ISSUE TITLE
长时间运行POI之后，无法正常播放声音

### ISSUE THREAD

**Issue by shiqi3885** [poooi/poi#2086]
**poi 版本 / poi version:10.0.0

**操作系统 / OS:windows 10 1803内部版本17134.472

**你遇到了什么样的问题 / The problem you've met:长时间运行POI之后，无法正常播放任何声音，不仅限于KC的游戏BGM，包括POI的提升音，甚至影响了系统的部分音频功能

**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:
重现方法：打开POI，放置在母港页面，进过7,8小时，最多10小时，之后就会出现这个现象，KC的BGM无法正常播放，都是嘟嘟嘟杂音，POI自带的远征，大破提示等也都会变成这样的声音
相关信息：曾经怀疑过是否是KC游戏的问题，使用谷歌原生浏览器（版本71，最新那个），长时间不关闭游戏玩了2天，没有出现这个现象。后来使用POI玩游戏，吧游戏内所有BGM全部关闭，长时间放置之后，仍旧出现同样情况

控制台输出等再次出现该状况时会截图补充

**Comment by KochiyaOcean** [comment]
我跑了 40 个小时都没出现这个问题…… 音频驱动之类的更新有考虑过么

**Comment by shiqi3885** [comment]
考虑过，但是我这边驱动已经都更新到最新了，而且这个问题是更新10.0 beat版开始出现的，我现在也不是很确定到底是哪的问题

**Comment by shiqi3885** [comment]
前天升级window1809还有一系列补丁之后，暂时没再次出现这个问题，可能还是系统的问题

**Comment by shiqi3885** [comment]
今天又出现了类似的问题了，点选阵型的时候，出现了很长的一声“叮”的声音，然后就只剩下BGM了，效果音和语音全部没有，并且控制台有以下警告
![default](https://user-images.githubusercontent.com/46570531/51214289-7149f700-1958-11e9-836e-aa4b461f867a.png)

**Comment by shiqi3885** [comment]
刷新游戏之后，问题解决

**Comment by KochiyaOcean** [comment]
webview 开发者工具看看也没有报错之类的吧

**Comment by shiqi3885** [comment]
很长时间没出现过了，关闭了
