### ISSUE TITLE
希望增加出擊前裝備檢查

### ISSUE THREAD

**Issue by jerry78424** [poooi/poi#2088]
**poi 版本 / poi version:**
10.1.0
**操作系统 / OS:**
win7 64bit

**插件名和版本 / Plugin name & version:**

**功能的详细描述 / Details on the feature:**

在出擊前檢查隊伍中是否有未使用裝備格，有則進行提示。
可減少使用者刷閃後忘記帶上裝備或者是未在使用洋上補給和損管後重新補充等狀況下的誤出擊。

**Comment by KochiyaOcean** [comment]
Added by https://github.com/poooi/poi/pull/2175
