### ISSUE TITLE
关于维修时间提醒的小建议

### ISSUE THREAD

**Issue by mzykiller** [poooi/poi#209]
希望舰队那一栏，鼠标放在损血的舰娘血条上时，能看到需要维修的时长。这样有助于计算下是扔修理渠还是用明石修。

**Comment by magicae** [comment]
https://github.com/poooi/plugin-ship-info/pull/9
通过舰娘信息插件支持如何？

**Comment by mzykiller** [comment]
很好啊，祝早日完善，越做越好

**Comment by magicae** [comment]
加了加了
