### ISSUE TITLE
能否增加全透明的主题那

### ISSUE THREAD

**Issue by 2823974468** [poooi/poi#2096]
**poi 版本 / poi version:**
10.1.0
**操作系统 / OS:**
window

1809
**插件名和版本 / Plugin name & version:**
无

**功能的详细描述 / Details on the feature:**
![default](https://user-images.githubusercontent.com/32291201/51721974-bd9ae280-208e-11e9-9ac6-4f84f3b5bd4e.png)
编辑css 最多到这种毛玻璃的效果 但我想要那种全透明的效果 作者能否增加下 或者给我说说怎么改成全透明那 谢谢

**Comment by KochiyaOcean** [comment]
修改 js 可以实现，但是效果太糟糕了所以不考虑加入

**Comment by 2823974468** [comment]
也就说最多就像这种效果吗？ 还有我把翻找了项目 发现引用了个electron-vibrancy 插件 是否是因为这个插件的效果导致 如果删除掉会出现什么效果

**Comment by KochiyaOcean** [comment]
@2823974468 删除掉就会不透明 毛玻璃的效果是由 windows api 决定的

**Comment by KochiyaOcean** [comment]
@2823974468 删掉关于这个模块的调用并调用 electron 的 browserwindow 的 opacity 参数可以实现透明窗口，参照 https://github.com/electron/electron/blob/master/docs/api/browser-window.md

**Comment by 2823974468** [comment]
有机会研究下 首先我需要先研究下node 其次 全英文好头疼啊

**Comment by KochiyaOcean** [comment]
@2823974468 有中文文档但是很旧

**Comment by 2823974468** [comment]
行 到时候研究下 谢谢
