### ISSUE TITLE
 错误代码100

### ISSUE THREAD

**Issue by itoumatoko** [poooi/poi#2098]
**poi 版本 / poi version:**10.2.0

**操作系统 / OS:**windows 10

1803

**插件名和版本 / Plugin name & version:**

**你遇到了什么样的问题 / The problem you've met:**游戏活动后无法打开游戏，一直显示错误代码100，清除了缓存后仍然无法打开游戏，还是显示错误代码100，删除后重新下载还是无法打开还是显示错误代码100，用的不是DMM，用的是ooi

**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:**

**Comment by KochiyaOcean** [comment]
系统时间可能有错

**Comment by itoumatoko** [comment]
??什么意思，请问怎么解决

**Comment by KagamiChan** [comment]
请访问 https://time.is/ 看一下系统时间是不是已经对准

**Comment by itoumatoko** [comment]
请问对准是北京时间吗

**Comment by itoumatoko** [comment]
时间是对准的

**Comment by itoumatoko** [comment]
我进去的时候显示已经获得数据，但是读条完后点进入游戏按钮就马上崩，显示错误代码100

**Comment by KochiyaOcean** [comment]
@itoumatoko 是否使用过自定义缓存包

**Comment by itoumatoko** [comment]
没有，以前也发生过同样的事

**Comment by KochiyaOcean** [comment]
@itoumatoko 不使用 ooi 使用别的方式呢

**Comment by itoumatoko** [comment]
我edge打开ooi是没有问题，就是用poi打不开ooi

**Comment by itoumatoko** [comment]
DMM也是可以打开的

**Comment by itoumatoko** [comment]
edge

**Comment by itoumatoko** [comment]
有没有人知道为什么
