### ISSUE TITLE
关于自动更新

### ISSUE THREAD

**Issue by vsoulstudio** [poooi/poi#2099]
poi 版本 / poi version:9.*/10.*

操作系统 / OS:WIN10 1803

功能的详细描述 / Details on the feature:自动更新能不能保持安装目录不变啊，我个人习惯安装到programfiles的文件夹下面而且本身我觉得大多数都是一个电脑一个账户，然而自动更新总是给安装到APPDATA里面整的跟360啊百度啊这些个流氓全家桶一样的。当时9.几版本更新到10的时候有那个ui尺寸问题我当时重新装回9的时候因为这个路径问题导致完全不能用，后来删了所有POI相关文件才正常了，而且原来手动添加的桌面快捷方式也没用了要重新拉一遍快捷方式。

**Comment by KochiyaOcean** [comment]
@vsoulstudio 必须用安装版安装一次才能保证每次都安装到相同位置
