### ISSUE TITLE
[Feature request] 面板分离模式和抽屉模式相关

### ISSUE THREAD

**Issue by slime7** [poooi/poi#2100]
**poi 版本 / poi version:** 10.2.0

**功能的详细描述 / Details on the feature:**

面板分离模式下，能不能给面板设置不同于游戏窗口的标题栏名字？分离模式真·主窗口变成面板，思维跟不上，收远征时老点开第一个窗口。
![2](https://user-images.githubusercontent.com/8674371/51796841-8a925380-2234-11e9-8975-e40ded2e08fd.png)

抽屉模式，能否在抽屉打开时，给游戏窗口覆盖点击区（或者可以自由设置是否启用这个功能），点击抽屉以外时关闭抽屉。好几次想关抽屉发现点到游戏中的按钮。

**Comment by KagamiChan** [comment]
改窗口标题也许是可以的

抽屉模式点击外部区域收回没有办法实现。主要原因是游戏区域的点击事件的捕捉，几种方案实现起来都很困难
