### ISSUE TITLE
poi10.2.0 卡掉帧顿现象

### ISSUE THREAD

**Issue by zcrspoi** [poooi/poi#2101]
**poi 版本 / poi version:**
10.2.0
**操作系统 / OS:**
win10教育版1803

**你遇到了什么样的问题 / The problem you've met:**
整个软件卡顿，包括游戏和工具面板，帧数不到60fps，未禁用硬件加速或限制帧数
**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be**
gpu信息如下，cpu占用不到10%，cpu i7 4790k 。缓存也清过
Data exported | 2019-01-29T19:11:32.024Z
-- | --
Chrome version | Chrome/69.0.3497.106
Operating system | Windows NT 10.0.17134
Software rendering list URL | https://chromium.googlesource.com/chromium/src/+/857b284701ddf7bef0f14fa76416cf7ca786b411/gpu/config/software_rendering_list.json
Driver bug list URL | https://chromium.googlesource.com/chromium/src/+/857b284701ddf7bef0f14fa76416cf7ca786b411/gpu/config/gpu_driver_bug_list.json
ANGLE commit id | 6ffc489d4f18
2D graphics backend | Skia/69 e110fd1ebd2d559838c49a8821ebf18986bd6ec2-
Command Line | "C:\Users\Administrator\AppData\Local\Programs\poi\poi.exe" --no-sandbox --allow-file-access-from-files --ppapi-flash-path="C:\Windows\system32\Macromed\Flash\pepflashplayer64_24_0_0_194.dll" --js-flags="--harmony --harmony-do-expressions" --autoplay-policy=no-user-gesture-required --disk-cache-size=1073741824

**Comment by KochiyaOcean** [comment]
如果不到 60fps 就是卡顿那暂时没有什么改进的方法……
或者希望有人提供一下

**Comment by zcrspoi** [comment]
> 如果不到 60fps 就是卡顿那暂时没有什么改进的方法……
> 或者希望有人提供一下
以前好像也没出现过这种情况，连ui都是目测30fps左右

**Comment by Ice-Cirno** [comment]
试试关闭高清图标？
