### ISSUE TITLE
如何设置插件后台常驻？该问题导致任务信息插件使用体验较差。

### ISSUE THREAD

**Issue by hot36952** [poooi/poi#2105]
**poi 版本 / poi version:10.2.0**

**操作系统 / OS:Windows 10 1803**

**插件名和版本 / Plugin name & version:任务信息5.5.3**

**你遇到了什么样的问题 / The problem you've met:我记得poi以前的版本可以设置插件是否后台常驻的，现在的版本没找到在哪里设置。似乎因为任务信息插件没有常驻后台，导致每次打开任务信息里面的任务全部都是已完成的状态，需要手动刷新游戏任务界面每一页，才能正确显示任务的完成状态。关闭任务信息后再打开，又回到所有任务已完成状态，游戏在出击或其他状态下无法查看。**

**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:请问新版本如何设置每个插件是否后台常驻？如果没办法，请问任务信息插件的问题如何解决？**

![qq 20190203144148](https://user-images.githubusercontent.com/21011227/52173617-a9f42800-27c2-11e9-95bf-3c12b80bad30.jpg)
![qq 20190203144244](https://user-images.githubusercontent.com/21011227/52173618-a9f42800-27c2-11e9-9388-3ea63c4e4f4f.jpg)
![qq 20190203144635](https://user-images.githubusercontent.com/21011227/52173619-a9f42800-27c2-11e9-9557-e09f96f56458.jpg)

**Comment by KochiyaOcean** [comment]
@hot36952 目前的情况只有改为非窗口模式可以解决

**Comment by hot36952** [comment]
> @hot36952 目前的情况只有改为非窗口模式可以解决

是否可以理解成：目前的版本插件，非窗口模式=常驻后台，窗口模式=不常驻后台？

**Comment by KochiyaOcean** [comment]
@hot36952 可以

**Comment by hot36952** [comment]
> @hot36952 可以

明白了，谢谢

**Comment by KagamiChan** [comment]
@hot36952 任务信息插件的任务完成情况没有记录，都是靠当前信息推断的。之后应该会取消掉这部分功能……
