### ISSUE TITLE
沒有遊戲畫面

### ISSUE THREAD

**Issue by Fung43597** [poooi/poi#2106]
**poi 版本 / poi version:**
１０．２．０
**操作系统 / OS:**
ｗｉｎｄｏｗｓ１０版本１８０３

**插件名和版本 / Plugin name & version:**

**你遇到了什么样的问题 / The problem you've met:**
下載後可以開啟遊戲　但沒有任何畫面　　　　　　　　　　　　　　　　　　　　　　　　　　　　　
　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:**
![image](https://user-images.githubusercontent.com/47082190/52216219-bff00e80-28d0-11e9-8609-ad57f9f7d17d.png)

**Comment by KagamiChan** [comment]
@Fung43597 按 ctrl shift i 看一下有没有什么报错信息

**Comment by KagamiChan** [comment]
看起来没有报错

你是第一次安装 poi 吗

**Comment by cul9** [comment]
I have the same symptoms...
It's the same if i delete cookies,cache
![cap 2019-02-10 07-49-00-718](https://user-images.githubusercontent.com/41810694/52527245-c9caa500-2d08-11e9-9632-03a98e0bde3a.png)
