### ISSUE TITLE
舰娘解体后右侧状态栏无法显示

### ISSUE THREAD

**Issue by mfy0120** [poooi/poi#2108]
**poi 版本 / poi version:**
10.0
**操作系统 / OS:**
mac

**插件名和版本 / Plugin name & version:**

**你遇到了什么样的问题 / The problem you've met:**
点击解体后，右侧所有舰娘状态栏目崩溃（舰队，远征，任务，工厂，入渠等）
![image](https://user-images.githubusercontent.com/4901819/52482299-bdf2ad80-2b65-11e9-9e21-a0afe6e70aad.png)

**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:**
![image](https://user-images.githubusercontent.com/4901819/52482368-f2666980-2b65-11e9-962f-18c0adacc0bb.png)

**Comment by KagamiChan** [comment]
@mfy0120 在 10.2.0 上无法复现，请升级到最新版本
