### ISSUE TITLE
10.2.0 Random crashes, no logs could be captured

### ISSUE THREAD

**Issue by kazenorin** [poooi/poi#2109]
**poi 版本 / poi version:** 10.2.0

**操作系统 / OS:** Windows 10 1803

**你遇到了什么样的问题 / The problem you've met:** Random crashes. When crashing, all poi windows are blacked out and appears to be unresponsive. The unresponsive state does not stress my CPU/GPU, it's just "dead".

**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:**

This happened several times, the entire poi application crashes with no warning no error no prompt, just entirely blacks out. Every poi window blacks out, no key-binds work, music stops and not even title bar menus could be seen. I had to kill the application from start menu (no need to kill from task manager though).

The first time when this happened, launching poi again resulted in immediate black-out. I logged with another computer (also 10.2.0/1803) and it worked. Logged in back on this computer, and found that before the canvas loads, poi doesn't crash.

Since it crashed consistently, I tried capturing some logs. I started poi from cmd and launched devtools with it. When it crashed and blacks out, the devtools says it got disconnect (thus I'm unable to do any inspection) and nothing could be seen from the command line.

Interesting, restarting the computer seems to relieve me from crashing on launch.

However, a couple days later (i.e. today), I experience random crashes during battles. Unlike the previous time, restarting poi does not immediately crash but only randomly during battles. Though even with the computer restarted, I still can get rid of the random crashes (sortied 7 times, 2 crashes).

**Comment by kazenorin** [comment]
It's similar to this issue here: https://github.com/mudio/bce-client/issues/72

But I've been using poi for a long time on this computer, never had this problem before, until these few days.

**Comment by KagamiChan** [comment]
@kazenorin thank you for the detailed reports, we have had several similar reports, and it seems the cause is underneath the upstream Electron.

**Comment by KochiyaOcean** [comment]
@kazenorin The problem can be resolved by disable GPU acceleration in setting if GPU actually caused this problem (as the above-mentioned issue says)
