### ISSUE TITLE
关于索敌值的计算公式

### ISSUE THREAD

**Issue by nanjingsnow** [poooi/poi#211]
现在比较通用的索敌值计算都是以2-5算法来算的哇：(侦察机×2)+(电探)+√(舰娘不带装备的索敌值合计)
或者在设置的时候可以有个选项可以选择以那种算法来计算索敌值，像kcv一样的选项
现在我看我舰队的索敌值好奇怪~和别人提供的索敌值好难对应起来。

**Comment by KochiyaOcean** [comment]
你所提到的是 2-5 旧式，因为没有考虑到等级的负修正所以不是非常准确
poi 自带的是 2-5 秋式

**Comment by magicae** [comment]
Added by https://github.com/poooi/poi/commit/3f7702bd1454cb74b0a08670d6e70def5ef0d975

**Comment by c933103** [comment]
KCV還有種 單純加總

**Comment by magicae** [comment]
@c933103 那个有人用吗…

**Comment by c933103** [comment]
間中看到有人說索敵值二百幾三百之類的…
