### ISSUE TITLE
卡住在loading畫面

### ISSUE THREAD

**Issue by buttsauce777** [poooi/poi#2110]
**poi 版本 / poi version: 10.2.0

**操作系统 / OS: Windows 10

**插件名和版本 / Plugin name & version:**

**你遇到了什么样的问题 / The problem you've met: 如題, 卡住在loading畫面

開發者截圖: https://imgur.com/a/LJLqsax

**Comment by KagamiChan** [comment]
@buttsauce777 需要 console 部分的内容

**Comment by buttsauce777** [comment]
https://imgur.com/a/JeUiBjR

**Comment by KagamiChan** [comment]
请看看这里的版本是否可以使用 [ci.appveyor.com/project/KochiyaOcean/poi/builds/22244818/artifacts](https://ci.appveyor.com/project/KochiyaOcean/poi/builds/22244818/artifacts)

**Comment by buttsauce777** [comment]
可以了 謝謝
