### ISSUE TITLE
手動烤餅乾失敗問題

### ISSUE THREAD

**Issue by jeanskywang** [poooi/poi#2111]
**poi 版本 / poi version:**
10.2.0
**操作系统 / OS:**
Win10 Ver. 1803

**你遇到了什么样的问题 / The problem you've met:**
因內建的烤餅乾失效，嘗試手動用[英文wiki](https://kancolle.fandom.com/wiki/Tutorial:_Proxy_Connection)新版的烤餅乾方法，卻一直遇到"Uncaught Error: Cookie not in this host's domain. Cookie:dmm.com Request:analytics.poooi.app"。

確定該段cookie在chrome (Ver. 71.0.3578.98)是可以使用的。

**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:**
![image](https://user-images.githubusercontent.com/14091875/52520439-3449f980-2ca5-11e9-8b57-a0e5d77276c4.png)

**Comment by KagamiChan** [comment]
@jeanskywang 你是左键打开的开发者工具吧，这个是 poi 自己的。内置浏览器的开发者工具是右键打开

**Comment by jeanskywang** [comment]
好的...我試試看

**Comment by jeanskywang** [comment]
可以登入了，感謝~~
