### ISSUE TITLE
卡在POI等待遊戲資料中

### ISSUE THREAD

**Issue by xanthorius** [poooi/poi#2113]
**poi 版本 / poi version:**10.2.0

**操作系统 / OS:**WIN10

**插件名和版本 / Plugin name & version:**

**你遇到了什么样的问题 / The problem you've met:**今天關了POI後再開一直卡在等待遊戲資料中, 把POI的\AppData\Roaming\poi 全刪後登入後一樣卡住, 刪掉重裝問題也是一樣
![1](https://user-images.githubusercontent.com/47476368/52520966-07004a00-2cab-11e9-9d9c-c6b00aa5a7eb.JPG)

**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:**

**Comment by KagamiChan** [comment]
@xanthorius 请看看这里的版本是否可以使用 https://ci.appveyor.com/project/KochiyaOcean/poi/builds/22244818/artifacts

**Comment by xanthorius** [comment]
成功登上
謝謝!
