### ISSUE TITLE
依然黑屏

### ISSUE THREAD

**Issue by naruru** [poooi/poi#2115]
**poi 版本 / poi version:**
10.2.2
**操作系统 / OS:**
win10 1903 18329.1

**插件名和版本 / Plugin name & version:**

**你遇到了什么样的问题 / The problem you've met:**
依然是之前在#1577 提到过的黑屏问题，因为那个issue最终还是没有解决，所以也就一直没有再用poi，
然后现在尝试了更新显卡驱动（GT 240M）到最新的版本，也尝试按其他的issue里的方法关闭了硬件加速，以及删除了appdata目录里面的对应文件，然而现在还是黑屏
用命令行启动poi.exe只有[INFO] Proxy listening on xxxxx 这样的一句话

**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:**

console的报错信息如下
![20190212033831](https://user-images.githubusercontent.com/31871876/52585333-ce619b80-2e77-11e9-9a7c-67a17ec23736.png)

**Comment by KochiyaOcean** [comment]
重新下载安装看看

**Comment by KuuHaaKuu** [comment]
download and install version 10.2.3

**Comment by naruru** [comment]
> 重新下载安装看看

重新下载以后，有画面了，但那个readme对话框永远按不了确认，关掉再开的证书画面也永远按不了信任，就像卡住了一样

相性不合，我还是用回KCV吧……

**Comment by KochiyaOcean** [comment]
@naruru 加载插件的时候会卡一段时间
