### ISSUE TITLE
the maximize button to make it full screen for Poi didn't work

### ISSUE THREAD

**Issue by fajarmf94** [poooi/poi#2116]
**poi 版本 / poi version:** 10.2.3

**操作系统 / OS:** Windows 10, ver 1803 (OS Build 17134.590)

**你遇到了什么样的问题 / The problem you've met:**

so i found that the Poi can't maximize the app and even the maximize button from the app and from right click didn't work

![image](https://user-images.githubusercontent.com/24492178/52783544-d6daf180-3084-11e9-81d7-596c023a2aca.png)

**Comment by KochiyaOcean** [comment]
Have you checked this option?
![image](https://user-images.githubusercontent.com/8194131/52783791-54f3c400-3096-11e9-903a-ca77fd68c6ff.png)

**Comment by fajarmf94** [comment]
> Have you checked this option?
> ![image](https://user-images.githubusercontent.com/8194131/52783791-54f3c400-3096-11e9-903a-ca77fd68c6ff.png)

yes, but the result isn't satisfy me, there are borders around it and it's not actually like full screen or something
![image](https://user-images.githubusercontent.com/24492178/52785052-9df14b80-3089-11e9-878d-89198ee38b86.png)

**Comment by fajarmf94** [comment]
oh wait now it's fixed after i change the zoom

![image](https://user-images.githubusercontent.com/24492178/52785256-1ce68400-308a-11e9-9522-154bc8365942.png)
