### ISSUE TITLE
使用cookie登录每次重启时会提示地区错误

### ISSUE THREAD

**Issue by sysunoob** [poooi/poi#2119]
**poi 版本 / poi version:**
10.2.4

**操作系统 / OS:**
win10 1803

**插件名和版本 / Plugin name & version:**

**你遇到了什么样的问题 / The problem you've met:**
使用cookie登录每次重启时提示地域错误

**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:**
使用非日本的代理，设置游戏页面为首页，每次重启都会跳出地域错误，需要重新点击dmm.com才能成功识别为日本。可以进游戏，但是每次重启后都是地域错误页面，需要先跳到dmm，再跳到dmm games，然后再打开游戏页面。为什么不是像日本代理一样，一重启直接进入游戏页面呢？

**Comment by KochiyaOcean** [comment]
选择设置地区 cookie 了么

**Comment by sysunoob** [comment]
> 选择设置地区 cookie 了么

选了，但是不是启动后立即生效的
必须重新按上述点一遍才能生效

**Comment by sysunoob** [comment]
一些补充：
cookie 是勾上了的
![1](https://user-images.githubusercontent.com/23278600/53943446-77f71e00-4100-11e9-9f52-56ee893c19a5.JPG)

这是重启后的页面，停在地域错误上。首页设的是游戏页面。
![2](https://user-images.githubusercontent.com/23278600/53943448-788fb480-4100-11e9-9348-7dc5b77aff19.JPG)
需要点击左上角的 dmm.com 图标再重新进入 dmm，然后再进入 dmm games 才能进入游戏
![3](https://user-images.githubusercontent.com/23278600/53943449-79284b00-4100-11e9-90b7-7b967ff4d1eb.JPG)
![4](https://user-images.githubusercontent.com/23278600/53943451-7a597800-4100-11e9-8ef4-9f0c729c8601.JPG)
重启后无法直接进入游戏页面。

**Comment by KagamiChan** [comment]
应该是某个域名没有应用 cookies，不过我只在启动的时候网络连接不对无法载入，再次刷新的时候会看到这个现象
