### ISSUE TITLE
新窗口未卜先知显示舰娘装备功能出错

### ISSUE THREAD

**Issue by deepsea666** [poooi/poi#2125]
**poi 版本:10.2.4

**操作系统:win7 64位

**插件名和版本:未卜先知 8.1.0

**功能的详细描述 :
当未卜先知没有选择在新窗口打开时，这个功能正常
![QQ截图20190327093736](https://user-images.githubusercontent.com/21211204/55049822-c9a02200-5088-11e9-9ff5-ff2732662194.jpg)

选择在新窗口打开时，鼠标移到舰娘上poi本体的主窗口就会出现问题
![QQ截图20190327093601](https://user-images.githubusercontent.com/21211204/55049845-e50b2d00-5088-11e9-80c6-698b660f5b0f.jpg)
![QQ截图20190327093625](https://user-images.githubusercontent.com/21211204/55049847-e89eb400-5088-11e9-80f3-bb5115b98971.jpg)

**Comment by KagamiChan** [comment]
@stale[bot] 这次活动前估计是没时间换上 styled components 了

**Comment by KochiyaOcean** [comment]
Should already be fixed?
