### ISSUE TITLE
远征提示“第1舰队远征完成”

### ISSUE THREAD

**Issue by Kurotsuba** [poooi/poi#2127]
**poi 版本 / poi version:**
10.2.4
**操作系统 / OS:**
win10 1803 

**插件名和版本 / Plugin name & version:**

**你遇到了什么样的问题 / The problem you've met:**
第4舰队跑东急2结束以后，windows提示“第1舰队 远征完成”
**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:**
重现失败，不知道和未激活的windows是否有关

![image](https://user-images.githubusercontent.com/19948901/55285177-de4a2600-53b8-11e9-910f-95b3becdd804.png)

**Comment by KochiyaOcean** [comment]
@Kurotsuba 游戏内部记录编程的时候会把舰队名也一起记录，应该是你把第一舰队的记录展开到第四舰队导致舰队名改变了

**Comment by Kurotsuba** [comment]
确实是这样，不好意思
