### ISSUE TITLE
点击按钮卡死

### ISSUE THREAD

**Issue by silver211** [poooi/poi#2129]
**poi 版本 / poi version:**10.2.4

**操作系统 / OS:**mac OS Mojave

**插件名和版本 / Plugin name & version:**

**你遇到了什么样的问题 / The problem you've met:**
从dmm登录游戏时，载入完毕卡在game start页面，按钮点下去没有反应。直接用chrome登录也是一样的问题，但是换safari就好了。

**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:**
并不能稳定重现。有时候可以正常点击进入游戏。

**Comment by KagamiChan** [comment]
如果 chrome 也有同样的问题，那可能这边就没有什么办法解决了
