### ISSUE TITLE
远征和入渠不刷新

### ISSUE THREAD

**Issue by AXIHIXA** [poooi/poi#2130]
**poi 版本 / poi version:**
10.2.4 64位 Windows版

**操作系统 / OS:**
WIndows 10 教育版 64位 1809（17763.437）

**你遇到了什么样的问题 / The problem you've met:**
远征或者入渠结束后就停留在0:00状态，无法刷新。
（即：远征结束后进入母港界面后不显示远征归来，入渠结束后进入入渠界面会发现船仍然占住位置，时间显示0:00）
另：进入入渠界面时会完全失去反应，鼠标点击哪儿都没反应。
如图：
![56334349-8a1daf00-61ca-11e9-817b-c13b8cb3a289](https://user-images.githubusercontent.com/32153465/56334512-3364a500-61cb-11e9-9017-621f3194cfa9.png)

**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:**
次次重现

![console](https://user-images.githubusercontent.com/32153465/56334199-fea41e00-61c9-11e9-9654-4cd2cb1949c5.jpg)

**Comment by KagamiChan** [comment]
第一个问题，请到 https://time.is/ 确认一下是否系统时间不正常

入渠界面这个看起来是卡在网络，这个时候点击 poi 其它区域也没有响应吗？如果这时候拉大窗口尺寸的话，窗口内容也会卡住吗

**Comment by AXIHIXA** [comment]
已解决，就是系统时间的问题。
