### ISSUE TITLE
使用OBS-Studio捕获窗口时黑屏

### ISSUE THREAD

**Issue by ttsunboy** [poooi/poi#2134]
**poi 版本 / poi version:** 10.2.4 deb release

**操作系统 / OS:** Ubuntu 18.04.2 LTS Desktop with kernel 4.15.0-48-generic

**你遇到了什么样的问题 / The problem you've met:**

使用OBS-Studio捕获窗口时黑屏，禁用硬件加速无效。测试捕获Firefox浏览器等正常，应当是poi窗口问题。

**Comment by KagamiChan** [comment]
捕获 chromium 呢？

**Comment by ttsunboy** [comment]
好问题，我去找Chromium发issue了
