### ISSUE TITLE
接7个任务后下方出现未解锁

### ISSUE THREAD

**Issue by deepsea666** [poooi/poi#2135]
接6个任务的时候没有，接了第7个就出现这个未解锁了
![001](https://user-images.githubusercontent.com/21211204/56875507-130ed300-6a74-11e9-9929-ddf834d475f1.jpg)

![002](https://user-images.githubusercontent.com/21211204/56875473-d216be80-6a73-11e9-9cbb-ce4d5f318104.jpg)

**Comment by KochiyaOcean** [comment]
已修复等发布

**Comment by gaoc09** [comment]
Poi 10.2.4, Win10 x64 17763仍存在该问题。
