### ISSUE TITLE
MacOS下无法运行 (OSStatus error 99999.)

### ISSUE THREAD

**Issue by matthew-z** [poooi/poi#2136]
无网络加速, 原生日本网络

**poi 版本 / poi version:**
10.2.4

**操作系统 / OS:**
MacOS 10.14.1 (Mojave)

**插件名和版本 / Plugin name & version:**
None

**你遇到了什么样的问题 / The problem you've met:**
第一次使用POI, 官网下载后打开, 先是因为没有开发者证书被mac的security拦截, 选择open anyway之后提示 The operation couldn’t be completed. (OSStatus error 99999.)

**Comment by matthew-z** [comment]
研究了一番是MacOS的gatekeeper (限制非认证的第三方软件运行) 挂了导致open anyway失败. 暂时没找到有效修复方案, 只能先手动关闭gatekeeper了:

`sudo spctl --master-disable`

FYI: 网上找的解决方案, 但没有效果 `sudo cp /var/db/.SystemPolicy-default /var/db/SystemPolicy`

**Comment by KochiyaOcean** [comment]
之后的版本会追加签名...
