### ISSUE TITLE
kcwiki語音字幕選擇正體中文卻顯示簡體中文

### ISSUE THREAD

**Issue by canonho** [poooi/poi#2137]
**poi 版本 / poi version:**
10.2.2
**操作系统 / OS:**
WIN7

**插件名和版本 / Plugin name & version:**

kcwiki語音字幕

**你遇到了什么样的问题 / The problem you've met:**

kcwiki語音字幕選擇正體中文卻顯示簡體中文

**Comment by KagamiChan** [comment]
cc @MZIchenjl

**Comment by MZIchenjl** [comment]
@canonho 能够提供截图作为参考吗

**Comment by XxJimmy122xX** [comment]
![螢幕擷取畫面 (220)](https://user-images.githubusercontent.com/25565500/57444922-d4eb8d80-7283-11e9-8b81-4a2b3a022d54.png)

**Comment by MZIchenjl** [comment]
我无法复现这个情况

能麻烦执行一下以下的步骤吗？

1. 打开开发者工具
![image](https://user-images.githubusercontent.com/14719366/57469440-4265e100-72b9-11e9-892b-8339111dc8af.png)

2. 在console标签内执行以下命令，查看结果

```
window.config.get('plugin.subtitle.locale')
```
![image](https://user-images.githubusercontent.com/14719366/57469517-6a554480-72b9-11e9-9831-be0b85ce9706.png)

**Comment by canonho** [comment]
![image](https://user-images.githubusercontent.com/32305815/57475086-33d1f680-72c6-11e9-8b94-86a585035291.png)

**Comment by canonho** [comment]
我的情况和 @XxJimmy122xX 一样 插件选了正体中文 可是早几天字幕突然显示简体了

**Comment by KagamiChan** [comment]
据了解是 kcwiki 的调整，关闭了正体中文的转换。

**Comment by MZIchenjl** [comment]
已经重新打开繁简转换了 @canonho @XxJimmy122xX
