### ISSUE TITLE
插件自動消失

### ISSUE THREAD

**Issue by mic4126** [poooi/poi#2140]
**poi 版本 / poi version:**
10.2.3
**操作系统 / OS:**
Win 10 1607

**插件名和版本 / Plugin name & version:**
全部

**你遇到了什么样的问题 / The problem you've met:**

**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:**
1.插件全部安裝
2.關掉poi
3.開poi

**Comment by mic4126** [comment]
[poi-plugin-missing.zip](https://github.com/poooi/poi/files/3169367/poi-plugin-missing.zip)
錄屏

**Comment by KagamiChan** [comment]
请按 win + R，输入 CMD 并确定，在出来的命令行窗口里面把 poi 的 exe 档拖进去，按回车运行，看一下有没有什么报错信息

**Comment by mic4126** [comment]
![image](https://user-images.githubusercontent.com/4671533/57573838-39b00f00-7461-11e9-8df5-53d3b78005d5.png)

**Comment by KagamiChan** [comment]
@mic4126 就是按正常的操作，安装一些插件，然后关闭，再拖进去，重新打开，重复一下看看

**Comment by mic4126** [comment]
試了幾次都是重開後自動消失
裝plugin 時 出了一堆npm warn npm audit fix

**Comment by KagamiChan** [comment]
求一些截图

**Comment by mic4126** [comment]
你想要debug console 截圖?

**Comment by KagamiChan** [comment]
对，cmd 的截图

**Comment by mic4126** [comment]
![image](https://user-images.githubusercontent.com/4671533/58170710-cf9c3300-7cc6-11e9-91da-e297dade0c95.png)

**Comment by KagamiChan** [comment]
@mic4126 所以你的把数据是放到网络位置上了？我们的代码可能没有考虑这种情况

**Comment by mic4126** [comment]
是的,用群組原則去放到網絡上(folder redirection)

**Comment by KagamiChan** [comment]
@mic4126 于是每次安装插件完毕之后，在日志里面的那个网络位置上可以看到文件存在吗

**Comment by mic4126** [comment]
安裝完插件後package-lock.json和package.json 都不存在
但是node_module 裡的插件有修改過(看到修改日期有更新)

**Comment by KagamiChan** [comment]
目测是读取插件的时候没有读取到

代码没有网络地址存放个人数据进行过考虑，目前短期内也可能无法投入时间来做详细的排查……

**Comment by mic4126** [comment]
明白的
慢慢來也沒有問題
