### ISSUE TITLE
游戏界面白屏

### ISSUE THREAD

**Issue by solaract** [poooi/poi#2141]
**poi 版本 / poi version:**
10.2.4
**操作系统 / OS:**
win10 1803

**插件名和版本 / Plugin name & version:**

**你遇到了什么样的问题 / The problem you've met:**
更新poi之后打开，登陆dmm账号之后跳转到游戏界面部分一直白屏加载不出来，ss流量也没有怎么跑，代理沿用的之前OK的设置。但是网页版可以玩。
**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:**
![image](https://user-images.githubusercontent.com/5858546/57578660-04d4a400-74c3-11e9-95ae-eb59a875a021.png)

![image](https://user-images.githubusercontent.com/5858546/57578648-e078c780-74c2-11e9-9433-dc5bbfda5751.png)

**Comment by KagamiChan** [comment]
请在浏览器里面输入 baidu.com 之类的网站试一下能不能打开

**Comment by solaract** [comment]
甚至可以肝船.jpg
![image](https://user-images.githubusercontent.com/5858546/57590714-220b8000-7560-11e9-9c29-77849a7cade3.png)
然而poi就是一直白屏，很绝望

**Comment by KochiyaOcean** [comment]
浏览器指 poi

**Comment by Ayaphis** [comment]
检查 poi 浏览器地址

**Comment by KagamiChan** [comment]
![image](https://user-images.githubusercontent.com/3816900/57598867-6bbb9100-7587-11e9-97a8-d630a0b91e95.png)
我说的浏览器是这个 = =

**Comment by solaract** [comment]
都没问题
![image](https://user-images.githubusercontent.com/5858546/57598988-dd93da80-7587-11e9-9dd6-6be4c9b47aa6.png)
![image](https://user-images.githubusercontent.com/5858546/57598729-ecc65880-7586-11e9-8752-af406ced67d3.png)

就游戏页面闪一下网页的header就一直白了
![image](https://user-images.githubusercontent.com/5858546/57598871-6cecbe00-7587-11e9-878f-6596c1cb89ff.png)

ss流量也不跑了
![image](https://user-images.githubusercontent.com/5858546/57598935-b210f000-7587-11e9-96ff-1acc56465487.png)

**Comment by KagamiChan** [comment]
清空缓存之类的看一下？

**Comment by solaract** [comment]
清空缓存没用
清空cookie之后好了= =

感谢
