### ISSUE TITLE
運行極卡

### ISSUE THREAD

**Issue by lylle200** [poooi/poi#2143]
**poi 版本 / poi version:**
10.2.4
**操作系统 / OS:**
Windows 10 1809
**你遇到了什么样的问题 / The problem you've met:**
Poi 運行卡, 反應極慢, 相隔數秒會沒有回應
**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:**
每次啟動都是如此, 嘗試過清除appdata/roaming/poi或重新安裝, 仍然如此
![螢幕擷取畫面 (82)](https://user-images.githubusercontent.com/50950049/58247257-24f24600-7d94-11e9-8fff-f74628586d5e.png)
![螢幕擷取畫面 (83)](https://user-images.githubusercontent.com/50950049/58247258-258adc80-7d94-11e9-8284-5d12ddba1e14.png)

**Comment by KagamiChan** [comment]
你的 PC 配置是怎么样的

**Comment by lylle200** [comment]
Machine name: I7-4790
Operating System: Windows 10 專業版 64-bit (10.0, Build 17763) (17763.rs5_release.180914-1434)
Processor: Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz (8 CPUs), ~3.6GHz
Memory: 8192MB RAM
Available OS Memory: 8116MB RAM
Card name: NVIDIA GeForce GTX 1050

**Comment by KagamiChan** [comment]
@lylle200 记忆体容量可能少了一点，不过应该是可以运行的。其它程式有没有类似的卡顿现象？

**Comment by KagamiChan** [comment]
另外在启动初期因为加载的内容比较多，有一段时间无法响应属于正常现象。但是之后运行应该是可以的

**Comment by lylle200** [comment]
其他程式未有類似卡頓狀況，而且卡頓不只是開啟後一段時間，而是一直持續一直卡，每次點擊按鈕大概需要5-10秒回應

**Comment by lylle200** [comment]
嗯…卸載 重開機 再安裝（非安裝包）就神奇的解決了
