### ISSUE TITLE
ubuntu 进战斗后游戏画面突然画面消失

### ISSUE THREAD

**Issue by slime7** [poooi/poi#2144]
**poi 版本 / poi version:** 10.2.4, 使用官网下载的 deb 安装

**操作系统 / OS:** Linux 4.18 Ubuntu 18.04 LTS Gnome (in VMWare)

**你遇到了什么样的问题 / The problem you've met:** 点完阵型进入战斗后仅游戏画面突然消失，然后听到战斗的声音，应该也可以操作（只开了音效的声音所以点击画面没声音没法判断）。不确定其他操作是否触发。

截图和控制台记录在附件。

![2](https://user-images.githubusercontent.com/8674371/58369305-14280880-7f2b-11e9-8035-bb5313f3e845.png)
[-1558787073095.log](https://github.com/poooi/poi/files/3219377/-1558787073095.log)

**Comment by slime7** [comment]
另外，程序的图标没显示，可能是你们的图片命名格式没被 electron 识别到。

**Comment by KagamiChan** [comment]
看起来没有什么相关的错误信息。比较像是显卡或者渲染部分挂掉了。
因为游戏对于硬件需求还是比较高的，请确认你的 vm 满足运行需求

程序图标没显示不是很理解，求详细，有截图吗

**Comment by slime7** [comment]
我确实没设置太高的配置而且还开了蛮多东西，可能是渲染挂了。
图标问题，就是那种类似没有图标的 win 程序， Ubuntu 里面的poi显示个斜着的方形。
据我所知， electron-builder 目前版本自动引用需要作为图标的 png 应该是 `32x32.png` 这种格式的。

![2](https://user-images.githubusercontent.com/8674371/58376696-9d2e5680-7fa2-11e9-8d9a-1d15f5736d1e.png)

**Comment by KagamiChan** [comment]
关于图标目前开发没有在用 Linux 的，所以没有办法确认……我只知道两年前的时候是可以的……
