### ISSUE TITLE
插件 - 舰娘信息 过滤选项

### ISSUE THREAD

**Issue by toooonyy** [poooi/poi#2147]
**poi 版本 / poi version:**
Not related
**操作系统 / OS:**
Not related

**插件名和版本 / Plugin name & version:**
舰娘信息 7.0.0

**功能的详细描述 / Details on the feature:**
如图，携带大发选项其实不只是大发，内火和战车也算进去了
![Screen Shot 2019-05-27 at 12 26 26](https://user-images.githubusercontent.com/3480434/58416986-e352eb00-8072-11e9-9fa3-2eff62a7a69d.png)
![Screen Shot 2019-05-27 at 12 26 33](https://user-images.githubusercontent.com/3480434/58416991-e77f0880-8072-11e9-9aee-a079697e8e21.png)

建议: 
* 携带大发选项拆分出来？变成大发、战车、内火，不过这样过滤项似乎有点拥挤
* 携带大发变成只能带大发的

**Comment by KagamiChan** [comment]
感谢建议，目前有这个计划

**Comment by toooonyy** [comment]
@KagamiChan 啊，突然发现 l10n 也不太对，截图上出现了 `FilterDE Equip incl.` 这种字符串

**Comment by KagamiChan** [comment]
= =
