### ISSUE TITLE
关于官网的版本问题

### ISSUE THREAD

**Issue by GhMoose** [poooi/poi#2150]
**poi 版本 / poi version:** 10.3

**操作系统 / OS:** Windows

**插件名和版本 / Plugin name & version:**

**你遇到了什么样的问题 / The problem you've met:**
您好，想请问官方网站的「Windows版」跟「Windows安装包」差别在哪里?

以为前者是免安装版不过看起来资料好像都另外放在C槽底下?

如果想要彻底删除干净或是删除后重新安装的话具体要怎么做呢?

谢谢

**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:**

**Comment by KochiyaOcean** [comment]
一个是压缩版一个是安装包版，使用安装包版安装可以指定自动更新的安装位置（否则自动更新会装到 `%localappdata%/poi` 下），安装包版的卸载和其他程序类似，在控制面板内卸载
用户数据无论版本都存放在 `%appdata%/poi` 下

**Comment by GhMoose** [comment]
谢谢回覆
自动更新的安装位置指的是poi本身的自动更新吗?

另外卸载的部份主要想问的是压缩版的部份，因为压缩版在控制面板是看不到的，而且我看数据不只存在poi程式资料夹内，像您提到用户数据的部份就在其他位置，所以才想询问如果要卸载的话要具体要删除哪些地方的资料?

现在看来是有poi本身的程式资料夹, `%localappdata%/poi` , `%appdata%/poi`(这个指的是AppData\Roaming\poi?)  这三个地方是吗?

再麻烦您协助了 谢谢

**Comment by KochiyaOcean** [comment]
@GhMoose 是
