### ISSUE TITLE
使用10.3.0會死機

### ISSUE THREAD

**Issue by kenny61207** [poooi/poi#2151]
**poi 版本 / poi version:**
10.3.0

**操作系统 / OS:**
1809 OS組建 17763.503

**你遇到了什么样的问题 / The problem you've met:**
使用10.3.0版本會造成電腦死機，開啟POI之後只要鼠標或鍵盤再點擊一次就會完全死機不能動，但10.2.4版本能夠正常使用沒問題

**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:**

顯示卡是MSI GAMING GTX 960 2G 驅動版本430.64

死機了完全沒法操控，只能提供10.2.4版本的
https://imgur.com/a/LXv0Ssz

**Comment by KagamiChan** [comment]
请使用开始菜单里的 poi (safe mode) 打开看看是否会死机

**Comment by kenny61207** [comment]
> 请使用开始菜单里的 poi (safe mode) 打开看看是否会死机

我試了一下發現
1.從10.2.4版本用自動更新成10.3.0 會死機
2.下載10.3.0壓縮檔解壓縮使用      會死機
3.下載10.3.0安裝檔安裝      可以正常使用

**Comment by KagamiChan** [comment]
应该是没有差别的。目前没有收到类似的报告。

**Comment by shiqi3885** [comment]
我也报告一个吧，10.3.0，我用的是安装板，每次启动的时候都会有概率死机，概率不是很高，系统是WIN10，死机等待一段时间之后就会蓝屏，出现这个错误
dpc_watchdog_violation

**Comment by shiqi3885** [comment]
补充一下，我也没有先卸载10.2.4，是下载安装板之后，直接覆盖安装的，已经碰到过好几次了

**Comment by shiqi3885** [comment]
再补充一个神奇的现象，蓝屏之后，如果重启，POI的所有设置会初始化，就是我之前的个人设置，例如窗口大小，布局，缩放比例啥的都会回复到默认状态，但是插件都还在

**Comment by KagamiChan** [comment]
@shiqi3885 蓝屏属于系统硬件或者驱动的问题，poi 这边没有什么可以做的，建议更新一下驱动，扫描一下磁盘错误看看
