### ISSUE TITLE
舰娘信息有没有必要把结婚HP和改修HP分别显示？

### ISSUE THREAD

**Issue by mikadochihaya** [poooi/poi#2152]
有时候时间长了会忘记有没有吃过船，特别是部分+1的，需要进改修画面一个个检查

**Comment by KagamiChan** [comment]
数据上没有办法区分出两部分的 hp 加成

**Comment by KagamiChan** [comment]
可能需要研究看看游戏里面是怎么区分

不过结婚都是 +3 起步？

**Comment by KagamiChan** [comment]
好像也不是如此，有很多反例的样子

不过 hp 这部分的逻辑本身就比较混乱，一直都不知道怎么整理比较好，如果有合适的方法的话我可以试着加进去，否则就只好摊手了

**Comment by mikadochihaya** [comment]
所有舰娘结婚增加的HP都是固定的，WIKI有具体数据，大部分是依存于结婚前的耐久增加对应数值，有一部分舰娘比较特殊。https://wikiwiki.jp/kancolle/%E3%82%B1%E3%83%83%E3%82%B3%E3%83%B3%E3%82%AB%E3%83%83%E3%82%B3%E3%82%AB%E3%83%AA
理论上可以加一个检测机制，对比超过100级的HP数据，如果比固定值高显示额外+1或者+2。但是这样需要把所有舰娘的100级后HP建立数据库，如果游戏内没有数据区分大概工作量大概会很大……
