### ISSUE TITLE
10.3.0 滚动条显示异常

### ISSUE THREAD

**Issue by De26Moon** [poooi/poi#2154]
**poi 版本 / poi version:**
10.3.0
**操作系统 / OS:**
Window 7

**插件名和版本 / Plugin name & version:**

**你遇到了什么样的问题 / The problem you've met:**
滚动条显示异常。在一屏能浏览的单元，右下角显示一个白色方框。需要滚动条浏览的单元，显示正常。
**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:**
概览界面异常
![poi1](https://user-images.githubusercontent.com/34669296/58640263-453d7a00-832b-11e9-8dff-bdf11ea90857.png)
关于界面正常
![poi2](https://user-images.githubusercontent.com/34669296/58640278-4cfd1e80-832b-11e9-9bd4-1b557a4e784f.png)

控制台
![poi3](https://user-images.githubusercontent.com/34669296/58640295-55555980-832b-11e9-8017-2e69383b0edb.png)

**Comment by KagamiChan** [comment]
@De26Moon 卸载经验计算插件之后是否会恢复？

**Comment by De26Moon** [comment]
> @De26Moon 卸载经验计算插件之后是否会恢复？

卸了经验计算还是一样 我试了安全模式进一个个启动插件 应该是舰娘信息的问题 7.0.2

**Comment by De26Moon** [comment]
> > @De26Moon 卸载经验计算插件之后是否会恢复？
> 
> 卸了经验计算还是一样 我试了安全模式进一个个启动插件 应该是舰娘信息的问题 7.0.2

在公司用mac才发现都更新到7.1.5了。。。更新后正常 就是不知道Win7怎么没自动更新。

**Comment by KagamiChan** [comment]
之前没想过有人会把舰娘信息当作面板插件来用
