### ISSUE TITLE
Linux環境下無法正常運行

### ISSUE THREAD

**Issue by NarihiroCH** [poooi/poi#2155]
poi 版本 / poi version: 10.3.0
操作系统 / OS: Manjaro Linux( Kernel Ver.: 4.19.45-1-MANJARO)
你遇到了什么样的问题 / The problem you've met: 無法運行. 控制臺輸出:
```                                                                                                                              
> poi@10.3.0 start /usr/share/poi
> electron .

sh: electron: command not found
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! poi@10.3.0 start: `electron .`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the poi@10.3.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/narihiro/.npm/_logs/2019-06-01T07_10_49_789Z-debug.log                                                                       
```

有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related: 
使用yay命令通過aur軟件倉庫安裝, 已嘗試重裝, 無法解決. 系統及依賴版本均爲最新.
[2019-06-01T07_10_49_789Z-debug.log](https://github.com/poooi/poi/files/3243524/2019-06-01T07_10_49_789Z-debug.log)

**Comment by NarihiroCH** [comment]
我好象自己找到原因了...
不知道什麼時候electron被滾沒了. 
建議Poi把electron直接設置爲依賴,這樣在安裝的時候可以自動安裝上,來避免類似的事情再發生.

**Comment by KagamiChan** [comment]
在目前的 build 的流程中会安装所有的依赖，所以 Electron 不能够作为依赖引入。

+ aur 包的维护者 @swordfeng

**Comment by NarihiroCH** [comment]
但是在我兩次重裝的過程中electron都沒有被安裝。

**Comment by swordfeng** [comment]
@NarihiroCH 之前是有在包里自带electron（beta版）最近去掉了，没注意package.json也去掉了。我会加上系统依赖的。

**Comment by swordfeng** [comment]
奇怪npm不是应该装一个electron么

**Comment by NarihiroCH** [comment]
然而，并沒有。

**Comment by KagamiChan** [comment]
stage2 里面运行的是 `npm install --production`，不会安装作为 dev dep 的 electron

**Comment by KagamiChan** [comment]
主要是我们的 production 环境是打包好的 electron project，本身是不需要把 electron 作为 dep 的。这也是 electron 官方的推荐用法

**Comment by swordfeng** [comment]
原来如此。
