### ISSUE TITLE
瀏覽器變得十分lag

### ISSUE THREAD

**Issue by ColemanChung** [poooi/poi#2157]
**poi 版本 / poi version:*10.3.0*

**操作系统 / OS:*Window 10 1803 * 

**插件名和版本 / Plugin name & version:**

**你遇到了什么样的问题 / The problem you've met:*我一直使用poi瀏覽器,十分順暢
但某天開始瀏覽器變得十分lag,每按一個按鈕都要2,3分鐘才有反應,有時候瀏覽器更會"沒有回應"
我已經嘗試過重新安裝,也不能解決
我也十分肯定不是網絡問題,也沒有安裝過新的程式
![圖片](https://user-images.githubusercontent.com/51267335/58750476-8ff2f980-84c5-11e9-87dd-3a3e1f20d5e1.png)
*
**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:**

**Comment by KochiyaOcean** [comment]
写错了可以 edit 不需要重开……

**Comment by KochiyaOcean** [comment]
以及 log 上看不出有什么问题
