### ISSUE TITLE
新舰力保能不能加个提示音？

### ISSUE THREAD

**Issue by mikadochihaya** [poooi/poi#2158]
加个工厂建造完成的语音感觉不错

自定义模式无例外选项
活动海域拿到奖励以后屏幕右下角貌似没有弹出提示，不知道是不是我看漏了……
拆船的时候还好多看了一眼，差点侠了……

**Comment by SoraYama** [comment]
例外选项是指什么?
奖励没通知是bug, 目前看貌似是修了但是还没测试
因为是通知类所以暂且是统一走POI的通知了, 看后续如果有反馈的话再改成单独加音效吧
