### ISSUE TITLE
头像

### ISSUE THREAD

**Issue by pougu** [poooi/poi#2159]
**poi 版本 / poi version:10.3

**操作系统 / OS:Win 7 win10 1809

**插件名和版本 / Plugin name & version:**

**你遇到了什么样的问题 / The problem you've met: 使用自建的http代理 但是无法显示出【编成】以及【战斗】界面的所有舰娘及深海头像

**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:**
我自建vps 并且使用境内服务器再将SS的流量用Privoxy转成http代理  升级到二期以后使用http代理总是无无法正常显示【编成】以及【战斗】界面的所有舰娘及深海头像
主要情况见下
![image](https://user-images.githubusercontent.com/7188315/58762169-ce4cef00-857f-11e9-9051-2086d419578d.png)
console返回403错误

![image](https://user-images.githubusercontent.com/7188315/58762183-fd636080-857f-11e9-979f-7ce25e037cf1.png)

**Comment by KagamiChan** [comment]
不了解你是如何配置的，但是从界面上来看应该和 poi 无关。shadowsocks windows 客户端内置的也是 privoxy，使用起来并没有问题
