### ISSUE TITLE
When I open POI, I can not connect. Please check your network and proxy settings. It will be displayed. There is no abnormality in the network, and only "Kancolle" has an abnormality. It is strange from 6/02 10:30. Please help me because I do not know the cause

### ISSUE THREAD

**Issue by Maikaze0315** [poooi/poi#2160]
**poi 版本 / poi version:**

**操作系统 / OS:**

**插件名和版本 / Plugin name & version:**

**你遇到了什么样的问题 / The problem you've met:**

**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:**

![2019-6-2T23 36 18](https://user-images.githubusercontent.com/51293101/58762935-1d028500-8590-11e9-8433-4e9cab20f464.jpg)

**Comment by KagamiChan** [comment]
Hi, How do you connect to the game? via VPN or direct?

Have you tried clearing the cache in Poi's settings?

**Comment by Maikaze0315** [comment]
I am directly connected  And I deleted the cookies and cash.  But it did
not go away.


2019年6月3日(月) 0:34 かがみ <notifications@github.com>:

**Comment by KagamiChan** [comment]
There's a built-in browser plugin which will open a new DMM page, please see if you could log into game with it
