### ISSUE TITLE
请问为什么我船一修好页面就会卡死？

### ISSUE THREAD

**Issue by hb406980** [poooi/poi#2161]
**poi 版本 / poi version:**
10.3.0 

**操作系统 / OS:**
windos7

**插件名和版本 / Plugin name & version:**

**你遇到了什么样的问题 / The problem you've met:**
只要有船修好，然后点进入渠界面，网页就会卡主什么都点不了，只能通过刷新重进游戏解决。游戏中其他功能没有问题。试着卸载了全部插件，但发现还是这样。

**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:**
![1WC4KRS5P6NP)LMS%`OHL5](https://user-images.githubusercontent.com/51305458/58771697-215a8c80-85e8-11e9-96ce-95e37a2e860e.png)

![A@J@EK553VCFEFGK 2~L ~K](https://user-images.githubusercontent.com/51305458/58771707-2f101200-85e8-11e9-901e-18cc4c4532d3.png)

**Comment by KagamiChan** [comment]
@hb406980 先把入渠完成提醒关掉试试看？

**Comment by hb406980** [comment]
大佬，好像没有用，关掉了也是入渠完成就会卡主。
![7RF9VHF~$L7(0GB3_(G 0B4](https://user-images.githubusercontent.com/51305458/58784542-47972100-8616-11e9-8c9a-1ea6692f5ca5.png)

**Comment by KagamiChan** [comment]
@hb406980 那建议清除一下缓存吧

**Comment by hb406980** [comment]
额，大佬，好像还是没用，我仔细看了一下，他是在修好的那一瞬间右下角会转一下圈，大概是连接一些还是加载一下，然后就会卡主不动了。

**Comment by hb406980** [comment]
大佬，没事了，是我自己的问题。我把acgp的自签证书打开就好了。
