### ISSUE TITLE
我要一个紧急刷新按钮

### ISSUE THREAD

**Issue by Th-pr** [poooi/poi#2162]
点了刷新后要反应很久才有用，而且还需要确认。紧急情况下差点出大事。我想要一个按钮可以去掉刷新确认并紧急刷新的按钮。情急之下只记得点刷新会忘了加shift的，而且刷新迟了的后果要比误刷新的后果严重。

**Comment by dislido** [comment]
可以使用右键点击刷新按钮

**Comment by taroxd** [comment]
Ctrl+R

**Comment by KagamiChan** [comment]
近期会把这些隐藏设置在界面中全部列出来
