### ISSUE TITLE
遊戲畫面上部會隨時間縮小

### ISSUE THREAD

**Issue by a0902031845** [poooi/poi#2168]
**poi 版本 / poi version:**10.3.0

**操作系统 / OS:**win7 sp1 64bit

**插件名和版本 / Plugin name & version:**

**你遇到了什么样的问题 / The problem you've met:**
遊戲畫面會隨時間縮小

**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:**
![tujhfygj](https://user-images.githubusercontent.com/12900336/59218425-d1388700-8bf2-11e9-8336-bb0ac36b3407.PNG)
剛打開正常的時候

![DEjPSDH](https://user-images.githubusercontent.com/12900336/59218478-f3caa000-8bf2-11e9-9ee2-180b620bd252.png)
![hgfhfgh](https://user-images.githubusercontent.com/12900336/59218805-a7cc2b00-8bf3-11e9-8acc-20e014c47f96.png)

一段時間後 可以看到右上的bar 縮了

![54535](https://user-images.githubusercontent.com/12900336/59218560-21afe480-8bf3-11e9-8c10-6266a0286dd6.png)
同時最底部也由上圖變成下面
![vjvjgh](https://user-images.githubusercontent.com/12900336/59218573-26749880-8bf3-11e9-8b18-1f4cfb458c1f.png)
最底部變寬了一點點

------------------
還有另一個不重要但也想說的問題
為什麼每次更新都要在POI所在的資料夾內容全部刪掉呢
我本來為了方便在電腦間移動
POI是放在USB的 各種諸如魔改和航海日誌也是放在同一個資料夾
一更新就消失了 
這實在讓我很好奇.....

**Comment by KagamiChan** [comment]
可以确定是由于 toast 引起的， 但是具体的原理不明

**Comment by KagamiChan** [comment]
姑且在 1b3b855acda20e2b361b626288efe9edb21ad891 中尝试做了修复
