### ISSUE TITLE
使用一直是DMM地域错误

### ISSUE THREAD

**Issue by yozokaze** [poooi/poi#2174]
**poi 版本 / poi version:**10.3.0

**操作系统 / OS:**window 10 1803

**插件名和版本 / Plugin name & version:**

**你遇到了什么样的问题 / The problem you've met:**从一直延续的设置到最新版本联合岛风代理使用poi登录DMM账号遇到地域错误，返回DMM主页TOP也是错误。

**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:**只需正常打开代理和打开poi点击舰C游戏登录界面登录完毕即触发。

`C:\Users\yozora\Down…tor\lib\index.js:65 [BABEL] Note: The code generator has deoptimised the styling of C:\Users\yozora\Downloads\poi-8.2.0\resources\app.asar\node_modules\lodash\lodash.js as it exceeds the max of 500KB.
C:\Users\yozora\Down…\info\quests.js:717 Scheduling daily refresh at 331200000 (now 1561305254245)
C:\Users\yozora\Down…date\wctf-db.js:138 No update for wctf-db, current: 20190608.0.0, remote: 20190608.0.0
C:\Users\yozora\Down…anager\utils.js:168 poi-plugin-kcwiki-report: No translate file found.
C:\Users\yozora\Down…ut\update\fcd.js:99 No newer version of map: current 2019/05/25/01, remote 2019/05/25/01, mode default
C:\Users\yozora\Down…ut\update\fcd.js:99 No newer version of shipavatar: current 2018/09/08/02, remote 2018/09/08/02, mode default
C:\Users\yozora\Down…ut\update\fcd.js:99 No newer version of shiptag: current 2019/05/25/02, remote 2019/05/25/02, mode default
C:\Users\yozora\Down…t\update\fcd.js:108 Update fcd from https://poi.io/fcd/ successfully in mode default.
C:\Users\yozora\Down…rvices\update.js:81 Remote version: v10.3.0. Current version: 10.3.0
C:\Users\yozora\Down…vtool-message.js:13 This is poi@10.3.0 on win32 x64 with Electron@4.2.2,
        PLUGINS: ,
        FCD: map@2019/05/25/01, shipavatar@2018/09/08/02, shiptag@2019/05/25/02
﻿

​`

**Comment by KagamiChan** [comment]
你是使用了岛风 go？

**Comment by yozokaze** [comment]
> 你是使用了岛风 go？

是，以前的设置没有改变过，但是现在不行了

**Comment by KagamiChan** [comment]
@yozokaze 先换线路看看

**Comment by yozokaze** [comment]
@KagamiChan 已经检查过了，全部的线路都一样的结果，也是地域错误。如果是谷歌页岛风代理插件反而没有问题。应该与线路无关

**Comment by yozokaze** [comment]
PS:也尝试关闭了所有防火墙造成的可能，但是也没有解决问题，岛风端口变更也测试过了，也没有解决

**Comment by yozokaze** [comment]
也确定勾选了设置DMM地区cookie的选项

**Comment by KagamiChan** [comment]
看起来 poi 的代理设置部分的问题，你修改一下设置再改回来看看吧

**Comment by yozokaze** [comment]
HTTP代理
127.0.0.1   8099
以前一直沿袭这个代理设置没有变动  直到最近是因为从日本回到国内，期间在日本更新过poi
已尝试修改网络代理设置再改了回来，还是没解决，dmm games top还是地域错误了。

**Comment by KagamiChan** [comment]
@yozokaze 清除 cookies 看看吧

**Comment by yozokaze** [comment]
已尝试清除缓存和cookies  重启发生代理链接异常没打开到dmm页，再刷新进入登录还是地域错误。

**Comment by KagamiChan** [comment]
@yozokaze 打开开发者工具，输入 config.get('poi.misc.homepage') 得到的结果是？

**Comment by yozokaze** [comment]
@KagamiChan 
config.get('poi.misc.homepage')
"http://www.dmm.com/netgame/social/application/-/detail/=/app_id=854854/"

**Comment by KagamiChan** [comment]
@yozokaze 这就不是很了解了，看起来你的 poi 设置没什么问题

**Comment by yozokaze** [comment]
@KagamiChan 是否可以通过删除再安装解决？若要清除原有文件系统目录的cookie要手动清除不？

**Comment by KagamiChan** [comment]
@yozokaze 所有的设置资料是放在 %appdata%/poi 下面的
