### ISSUE TITLE
Many missing lines in English Subtitle Plugin

### ISSUE THREAD

**Issue by Dahzz** [poooi/poi#2176]
**poi 版本 / poi version:**10.3.0

**操作系统 / OS:** Windows 10

 Version 1903

**插件名和版本 / Plugin name & version:** Subtitle Plugin, Version 1.2.21

 

**你遇到了什么样的问题 / The problem you've met:** Missing many shipgirl lines in English, especially when shipgirl is in kai or kaini form and for the newer shipgirls

**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:**

**Comment by KagamiChan** [comment]
CC @MZIchenjl
