### ISSUE TITLE
poi黑屏了，能进dmm进不去游戏

### ISSUE THREAD

**Issue by uesakasumire** [poooi/poi#2178]
**poi 版本 / poi version: 10.2.4（压缩包版）**

**操作系统 / OS: win10 1903版**

![QQ图片20190630094233](https://user-images.githubusercontent.com/52363959/60391243-8e484000-9b1c-11e9-95ed-3d9c9d50a0c6.png)
查看代码是这个问题
找到这个文件后它是这个状态
![QQ图片20190630095145](https://user-images.githubusercontent.com/52363959/60391260-ae77ff00-9b1c-11e9-9afe-ec73bd472b0b.png)
这要怎么解决

**Comment by uesakasumire** [comment]
**poi 版本 / poi version: 10.2.4（压缩包版）**

**操作系统 / OS: win10 1903版**

**Comment by KochiyaOcean** [comment]
没看出来有什么问题
如果是突然出现这种情况，检查一下防火墙设置，清除缓存和 cookie 和看看是不是开启了加速器之类的代理性质的软件

**Comment by uesakasumire** [comment]
@KochiyaOcean 没有用呀，我把缓存，cookie清了，甚至防火墙都关掉了，还是不行，poi重装了一遍也不行，能上dmm，但是一点进入游戏就黑了，其他浏览器也能上游戏，应该不是岛风go的问题吧？

**Comment by KochiyaOcean** [comment]
@uesakasumire 换过线么

**Comment by uesakasumire** [comment]
@KochiyaOcean 都换过一遍了，还是不行

**Comment by KochiyaOcean** [comment]
右键开发者工具图标，刷新以后看看弹出的开发者工具有没有显示什么报错

**Comment by uesakasumire** [comment]
@KochiyaOcean 
![QQ图片20190630143302](https://user-images.githubusercontent.com/52363959/60393214-4210f600-9b44-11e9-8b96-6511e6be5c43.png)
![QQ图片20190630143444](https://user-images.githubusercontent.com/52363959/60393217-463d1380-9b44-11e9-9dff-ec5e8fdfe505.png)
就是这样，点开始之后就黑屏了

**Comment by KochiyaOcean** [comment]
@uesakasumire 你第二次截的不是右键的那个开发者工具…… 要的是标题栏有 DMM 的那个的截图

**Comment by uesakasumire** [comment]
@KochiyaOcean 
![QQ图片20190630190925](https://user-images.githubusercontent.com/52363959/60395746-caa28d00-9b6a-11e9-828a-4d58c5a79139.png)
这样么？可是点开始之后右键开发者工具是空白的诶

**Comment by KochiyaOcean** [comment]
左键开发者工具（poi/index.html 那个）console 输入 `$('webview').getWebContents().addListener('did-fail-load', (...arg) => console.log(arg))` 回车，然后刷新页面再看看有没有报错

**Comment by uesakasumire** [comment]
![QQ图片20190630220046](https://user-images.githubusercontent.com/52363959/60397734-9044ea00-9b82-11e9-8331-9f00cc7a1f75.png)
@KochiyaOcean 输了成这样了，还是黑的

**Comment by KochiyaOcean** [comment]
你代理怎么设置的……

**Comment by uesakasumire** [comment]
![QQ图片20190630220456](https://user-images.githubusercontent.com/52363959/60397789-385ab300-9b83-11e9-9745-7434aa2265d9.png)
![QQ图片20190630220511](https://user-images.githubusercontent.com/52363959/60397791-3abd0d00-9b83-11e9-9955-7b9a1f4c474c.png)
![QQ图片20190630220542](https://user-images.githubusercontent.com/52363959/60397792-3c86d080-9b83-11e9-9f69-0ac9b512885c.png)
@KochiyaOcean 这样应该没错吧？

**Comment by KochiyaOcean** [comment]
试试看开发者工具开命令提示符，输入 `netsh winsock reset` 然后重开 poi 看看

**Comment by uesakasumire** [comment]
![QQ图片20190630222115](https://user-images.githubusercontent.com/52363959/60397997-f2ebb500-9b85-11e9-932c-7a166cb3b681.png)
![QQ图片20190630222509](https://user-images.githubusercontent.com/52363959/60398000-f5e6a580-9b85-11e9-9470-82a9b84bddef.png)
@KochiyaOcean 电脑重启过了，还是8行

**Comment by KochiyaOcean** [comment]
确定y没用使用其他的 VPN 或者代理么

**Comment by uesakasumire** [comment]
@KochiyaOcean 确定，我就开着一个岛风go而且岛风go一关谷歌都进不去，后台没有其他vpn残留

**Comment by KochiyaOcean** [comment]
DNS 是什么

**Comment by uesakasumire** [comment]
@KochiyaOcean 
![QQ图片20190630223314](https://user-images.githubusercontent.com/52363959/60398103-1400d580-9b87-11e9-86f2-6e50f2ea3c27.png)
是这个么

**Comment by KochiyaOcean** [comment]
@uesakasumire 去 internet 设置里面更换一个看看，比如 114.114.114.114

**Comment by uesakasumire** [comment]
@KochiyaOcean 终于好了！多谢大佬！感谢感谢，我应该是被DNS 污染了
![QQ图片20190630224607](https://user-images.githubusercontent.com/52363959/60398263-efa5f880-9b88-11e9-8f3f-3727d380ec27.png)
