### ISSUE TITLE
Add method to indicate error code when webview throws connection failed event

### ISSUE THREAD

**Issue by KochiyaOcean** [poooi/poi#2179]
If webview throw an connection failed error, it will be redirected to `chrome-error://chromewebdata` page, which presents as a blank web page. Add some extra process to show certain error message instead.

**Comment by gnattu** [comment]
<img width="1312" alt="Screen Shot 2020-12-20 at 12 16 40" src="https://user-images.githubusercontent.com/12995396/102719710-8b677f00-42bd-11eb-9ccd-a00dd0f09163.png">
Now webview should show the error information.
