### ISSUE TITLE
缓存在理应尚未过期时即失效

### ISSUE THREAD

**Issue by Ithildin** [poooi/poi#2182]
**poi 版本 / poi version:**10.3.0

**操作系统 / OS:**win7

**你遇到了什么样的问题 / The problem you've met:**最大缓存设置无效，缓存大小达近1G时即开始删除旧缓存，导致重新下载资源。Chromium/Chrome内核本身理应支持最大2G缓存。

![t](https://user-images.githubusercontent.com/9719697/60821719-b0098d00-a1d6-11e9-88a5-8b5a9e9f748b.png)

**Comment by KagamiChan** [comment]
![image](https://user-images.githubusercontent.com/3816900/60863503-82aef480-a253-11e9-869d-1686afd09855.png)

在 windows 10 上是没问题的。


请问调整最大缓存之后是否重启了？最大缓存大小是在重启后才会生效。

**Comment by Ithildin** [comment]
打开其他站点测试了一下，发现确实不是最大缓存大小的问题，那应该是砍口垒本身的旧有缓存失效了？
但我不能理解为何缓存会失效。游戏没有进行维护，同样的资源理应没有超出max-age。
获得普通无限定立绘的dd、cl；进近期刚看过的图鉴页面；尤其是，进改修工厂改修昨日改修过的同一装备，都会需要重新向服务器请求资源，这些在我看来都是理应不会过期的缓存，故怀疑是缓存大小出了问题。
![temp](https://user-images.githubusercontent.com/9719697/60887629-6af16380-a287-11e9-8b5b-3dc973ac8572.png)
如图，同一页图鉴，缓存有效期应当是一致的，然而实际上部分命中部分失效，就很困惑。

**Comment by KagamiChan** [comment]
@Ithildin 你是使用的什么代理

**Comment by Ithildin** [comment]
自搭的ss，加上走cn2的优质转发，网络质量肯定没问题的。

**Comment by KagamiChan** [comment]
我这边看起来是很正常的，你检查一下 response 的 last modified 和 date 看看吧

**Comment by Ithildin** [comment]
一下子没找到向服务器请求完整资源的案例，先拿一个304的来看一下。

![t](https://user-images.githubusercontent.com/9719697/60945202-8018d180-a31d-11e9-8bad-e256e4bbd18f.png)
这两个分别是图鉴里相邻的扶桑改二和山城改二的预览图。last modified都是2018年的事了。

![39](https://user-images.githubusercontent.com/9719697/60945301-c5d59a00-a31d-11e9-8089-c4c1fa797380.png)
扶桑的图片资源。可见该页图鉴的缓存是6月26日下载的（活动结束维护后）。本次访问直接200。

![33](https://user-images.githubusercontent.com/9719697/60945397-046b5480-a31e-11e9-8dd0-61dadbdb9e38.png)
山城的则向服务器请求了过期检查。

按理说，这两项资源应该没有任何区别才对呀。

**Comment by MisakaMikoto52** [comment]
最近我也遇到看似是同样的问题。
**poi 版本 / poi version:**10.3.0
**操作系统 / OS:**win8.1

之前我也是设置了2G缓存大小，但缓存只用到1842-1843MB，改成3G缓存大小也是这个使用量，就算万圣节更新后也依旧是这个使用量。可以感觉到砍口累载入和载入画面的时等待时间变的较长。

无代理，使用的cookie区域设置。
有什么需要看的告诉我发上来。
