### ISSUE TITLE
关于第三方缓存的能不能直接用锅GO的

### ISSUE THREAD

**Issue by shiqi3885** [poooi/poi#2183]
**poi 版本 / poi version:**
10.3.0
**操作系统 / OS:**
win10 1903

**功能的详细描述 / Details on the feature:**
因为我系统硬件可能有点问题，偶尔会因为读写硬盘死机，然后重启之后POI的缓存就全部没了，全部要重新下，所以想问问这个第三方缓存能不能直接用锅GO的

**Comment by KagamiChan** [comment]
不了解，可以试试看
