### ISSUE TITLE
游戏内远征界面部分字体异常显示为衬线体

### ISSUE THREAD

**Issue by EdiTurn** [poooi/poi#2186]
**poi 版本 / poi version:**
10.3.0

**操作系统 / OS:**
Windows 10 1903 

**你遇到了什么样的问题 / The problem you've met:**
7 月 18 日更新后，若使用 poi，游戏远征界面中部分字体会显示为衬线体，如图（已尝试清除 roaming 下的整个 poi 文件夹）：
![image](https://user-images.githubusercontent.com/5492805/61471606-9b3aaf80-a9b5-11e9-8206-5b4423574337.png)

chrome 、Edge 中：
![image](https://user-images.githubusercontent.com/5492805/61472432-046ef280-a9b7-11e9-883a-566ae53b491a.png)

**Comment by KagamiChan** [comment]
浏览器默认字体字体的原因，而游戏本身其实是自带了一个字体的，不知道是不小心忘了还是准备放弃了

程序上可以通过 `will-attach-webview` 事件给 `webPreference` 设置 `defaultFontFamily` 来解决，类似：

```
  mainWindow.webContents.on('will-attach-webview', (e, webPreferences) => {
    webPreferences.defaultFontFamily = {
      standard: 'Source Han Serif SC',
      serif: 'Source Han Serif SC',
      sansSerif: 'Source Han Serif SC',
    }
  })
```

不过需要先收集一波各个平台的可用日文字体的信息

**Comment by KagamiChan** [comment]
@EdiTurn 想了解一下你有没有安装日语补充字体？在设置里面搜索添加功能应该能找到添加的地方

**Comment by taroxd** [comment]
已安装，poi 里仍为衬线体

**Comment by EdiTurn** [comment]
原未安装，安装后情况依旧。

**Comment by EdiTurn** [comment]
我这里刚才突然正常了，官方修复？

**Comment by KagamiChan** [comment]
@EdiTurn 不了解，安装字体之后可能是需要重新启动 poi 的

**Comment by KagamiChan** [comment]
感觉应该是已经修复了
