### ISSUE TITLE
装备浮窗闪烁

### ISSUE THREAD

**Issue by toooonyy** [poooi/poi#2188]
**poi 版本 / poi version:**
10.3
**操作系统 / OS:**
unrelated

**插件名和版本 / Plugin name & version:**
未卜先知 8.2.0
本体

**你遇到了什么样的问题 / The problem you've met:**

**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:**
分离模式下，当插件面板过窄时+装备名字长度足够时，会让本来显示在右侧的装备信息变成尝试左侧显示，然后导致闪烁。个人测试的阈值大概是 690px 左右
进一步减小插件面板宽度，装备会在下面显示，此时正常。
另外本体的主面板第一页那个 miniship 块的装备浮窗也有这个问题

![Screen Shot 2019-07-22 at 12 08 15](https://user-images.githubusercontent.com/3480434/61628357-96a21f80-ac71-11e9-89fa-7339f7920ff6.png)
![Screen Shot 2019-07-22 at 12 06 38](https://user-images.githubusercontent.com/3480434/61628358-96a21f80-ac71-11e9-9f5d-13b394050fd4.png)

**Comment by KagamiChan** [comment]
这个比较难以判断应该在哪里弹出，因为整个应用的布局是很灵活的，在任何方向上都可以出现空间不够的情况

**Comment by catsking1025** [comment]
如果可以的话，可以尝试在“概览”和“未卜先知”等窗口中限制装备名可显示的最大长度？
因为现在出现了“九七式舰攻改 试制三号戊型（空六号电探改装备机）”（这玩意甚至还有个熟练！）这一最凶最恶的装备（它甚至能量产，你有可能在复数船上看到它！），通过自动判定弹出方向已经不是很能解决这个浮窗闪烁的问题了。
