### ISSUE TITLE
游戏界面显示错误

### ISSUE THREAD

**Issue by Stardaweide** [poooi/poi#2189]
**poi 版本 / poi version:** 10.3.0

**操作系统 / OS:** Windows 10 Version 1803 OS Build 17134.885

**插件名和版本 / Plugin name & version:** N/A

**你遇到了什么样的问题 / The problem you've met:** 登录DMM进入游戏页面后不显示游戏界面，网页分成2部分且无法上拉或者下拉。

**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:** DMM页面左上角进入DMM GAMES再选择舰队collection也还是这样。重新登录也一样。

![Screenshot (11)](https://user-images.githubusercontent.com/23143674/61990398-ae78fb00-b005-11e9-8a8a-c2a85266d120.png)

poi显示的样子：
![2019-7-27T0 27 23](https://user-images.githubusercontent.com/23143674/61990405-c2246180-b005-11e9-8708-190e95d3f403.png)

**Comment by KagamiChan** [comment]
用什么方式连上的游戏？

**Comment by Stardaweide** [comment]
@KagamiChan 我算是美国直连的吧，我目前还没设置poi的链接方式，网络代理也没有设置。

**Comment by KagamiChan** [comment]
@Stardaweide 清除缓存看看吧，这个更多是网页没加载完整

**Comment by Stardaweide** [comment]
@KagamiChan 我试了用poi自带的清除缓存以及自己手动进入文件夹删除。进入poi登录后还是这个样子
