### ISSUE TITLE
大破通知不能关闭吗？

### ISSUE THREAD

**Issue by aimao058** [poooi/poi#2190]
**poi 版本 / poi version:**

**操作系统 / OS:**

**插件名和版本 / Plugin name & version:**

**功能的详细描述 / Details on the feature:**

**Comment by aimao058** [comment]
![Uploading QQ图片20190728123220.png…]()

**Comment by aimao058** [comment]
![Uploading QQ图片20190728123220.png…]()

**Comment by KochiyaOcean** [comment]
@aimao058 不能

**Comment by aimao058** [comment]
> @aimao058 不能

原来真的不能阿，，希望保留可以开启或关闭，目前的这个弹窗一样的提示感觉真的很不友好，可能对避免沉船会有帮助吧，但是对于不需要的人来说这样的强制性很头疼，，请考虑一下，，感谢开发者们，🙏辛苦了

**Comment by KagamiChan** [comment]
@aimao058 这是一开始开发时候就有的设计，同时我也不理解为什么会有大破进击的需求

**Comment by aimao058** [comment]
> @aimao058 这是一开始开发时候就有的设计，同时我也不理解为什么会有大破进击的需求
是这样的，2-2的B点打完可以到A收铝，A点是没有战斗的。但它一样也提示，或者可以改成不战斗的区域不提示，，这样可以吗？

**Comment by aimao058** [comment]
> @aimao058 这是一开始开发时候就有的设计，同时我也不理解为什么会有大破进击的需求

是这样的，2-2的B点打完可以到A收铝，A点是没有战斗的。但它一样也提示，或者可以改成不战斗的区域不提示，，这样可以吗？

**Comment by vuryleo** [comment]
我记得N年之前我有个mr是增加这个feature，最后因为不能「保证」安全就没合。
