### ISSUE TITLE
Unable to connect with region cookie

### ISSUE THREAD

**Issue by xedmel** [poooi/poi#2192]
**poi 版本 / poi version:**
10.3.0
**操作系统 / OS:**
Windows 10 version180(Build 17134.885)
**你遇到了什么样的问题 / The problem you've met:**
Error message tells me to check network and proxy settings.
**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:**
Using VPN, I am able to connect to KanColle server. With direct connection, I am unable to access and poi shows error. Webpage does not display.

![image](https://user-images.githubusercontent.com/53676694/62419385-bc093300-b64c-11e9-8dd1-f7ce8e85b0e0.png)

**Comment by KagamiChan** [comment]
@xedmel please try opening some websites inside poi browser, say, google.com

**Comment by xedmel** [comment]
Seems like it takes forever to open. After about 8~10 reload, it opened.

**Comment by KochiyaOcean** [comment]
@xedmel I think that was caused by you network condition, not by cookie. Maybe you should keep using VPN so that you can have a stable connection to DMM server.
