### ISSUE TITLE
已接受任务显示数量不足 接受超过六个任务后菜单将不再更新

### ISSUE THREAD

**Issue by ASIjacket** [poooi/poi#2194]
**poi 版本 / poi version:10.3

**操作系统 / OS:win10 ： 1903

**你遇到了什么样的问题 / The problem you've met:**
1. 目前一共可以同时接受七个任务 poi终只能显示六个 虽然之前加了一次 但是还是不够
2. 这有时会导致接受七个任务后 任务菜单便不再更新 处于一个卡死状态 重启poi后可修复

**Comment by KagamiChan** [comment]
有界面的截图吗？可能，你需要扩展一下任务面板的高度？

**Comment by ASIjacket** [comment]
> 有界面的截图吗？可能，你需要扩展一下任务面板的高度？

分窗显示模式
尝试了貌似需要拉到半个屏宽才可以显示。。。 要是把这个bottom再低一些就很棒了

--------------------------------------------------------------------------------

![Snipaste_2019-08-22_02-46-51](https://user-images.githubusercontent.com/26643085/63459953-23feac80-c488-11e9-8daa-659aedefe08f.png)
![Snipaste_2019-08-22_02-47-39](https://user-images.githubusercontent.com/26643085/63459954-23feac80-c488-11e9-9e76-6b7b7dcbaa58.png)

**Comment by KochiyaOcean** [comment]
![image](https://user-images.githubusercontent.com/8194131/63462994-23b9dd80-c497-11e9-888b-b5114767852c.png)
按下这个锁按钮可以自由调节面板位置和大小

**Comment by ASIjacket** [comment]
> ![image](https://user-images.githubusercontent.com/8194131/63462994-23b9dd80-c497-11e9-888b-b5114767852c.png)
> 按下这个锁按钮可以自由调节面板位置和大小

👍👍👍👍👍👍👍
