### ISSUE TITLE
将窗口最大化再还原导致选项卡点击判定问题

### ISSUE THREAD

**Issue by catsking1025** [poooi/poi#2195]
**poi 版本 / poi version:10.3.0

**操作系统 / OS:MacOS Mojave

**插件名和版本 / Plugin name & version:**

**你遇到了什么样的问题 / The problem you've met:在“窗口分离式”布局下，点击poi概览/插件窗口左上角的”最大化“按钮再还原会导致上方概览/舰队/插件/设置四个选项卡难以点击（只有一小部分像素有判定）
**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:在分离式窗口中最大化之并还原即可重现。另外，如果能改善点击“概览”选项卡时容易误触最大化的问题的话也是可行的？

![image](https://user-images.githubusercontent.com/50289105/63599507-b758ee80-c5fc-11e9-80a6-bdac6bc3566f.png)
![image](https://user-images.githubusercontent.com/50289105/63599521-c049c000-c5fc-11e9-8299-f9707042fb77.png)

------
更新，“内嵌呼出式”窗口将窗口最大化再还原之后也有这样的问题。顺带，将分离式窗口转为内嵌式后这个问题不会还原。
重启软件可以解决这个问题，但（尤其是在出击中）这么做还是挺费事的。

**Comment by KagamiChan** [comment]
我手头没有可用的 macOS 系统了，咕咕
