### ISSUE TITLE
内嵌呼出式布局闪烁问题

### ISSUE THREAD

**Issue by catsking1025** [poooi/poi#2196]
**poi 版本 / poi version:10.3.0

**操作系统 / OS:MacOS Mojave

**插件名和版本 / Plugin name & version:**

**你遇到了什么样的问题 / The problem you've met:在“内嵌呼出式”窗口布局下，游戏概览/插件窗口会时不时闪烁。

**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:在显示-布局中选择第一行第六个即可复现。另外，这种布局方式下体感cpu占用率比其他布局有明显的上升，目前没有数值测试，但具体表现为macbook air的风扇转速在其他进程相同的情况下要更快。

![image](https://user-images.githubusercontent.com/50289105/63600057-c9875c80-c5fd-11e9-9ae0-4f55fd536617.png)
![image](https://user-images.githubusercontent.com/50289105/63600068-d015d400-c5fd-11e9-8f46-acffab0cbbaf.png)

**Comment by KagamiChan** [comment]
内嵌式布局有可能因为有透明图层遮盖的原因，计算量会稍微大一点
