### ISSUE TITLE
请问这个对话框怎么关掉？附带提一下，建议优化优化！

### ISSUE THREAD

**Issue by erikaemma** [poooi/poi#2199]
第一部分：
版本：10.3.0
系统：1803, 17134.827
启动之后有一个欢迎界面附带快速设置选项卡，这玩意怎么关掉它？x没用，取消没用，选项卡切换不了。不一会就自己消失了。我以为下次启动就不会有了，可是...

第二部分：
强烈建议优化一下。我是14年大一被我室友拉入坑的，后来室友用上poi（不记得什么时候了），他电脑还不如我的配置（我：i5处理器、12g内存、950m独显，我是用独显运行的poi，核显运行的话更卡），可以后台挂着poi打lol或者战舰世界。
这中间我afk了，后来我回归之后也用poi，但是，启动黑屏、切换卡、gpu报表，想打别的游戏？chrome看个视频都能卡掉天...
我天真的以为是插件的问题，我撤掉了所有的插件，问题依旧。

**Comment by KagamiChan** [comment]
@erikaemma 你需要点击 “好的” 按钮

**Comment by erikaemma** [comment]
> @erikaemma 你需要点击 “好的” 按钮

你好皮QAQ

**Comment by KagamiChan** [comment]
关于性能优化问题。游戏二期对于系统性能的要求是更高的，并且涉及到系统版本和驱动的各类因素，而且有底层程序之类我们没有办法控制的因素，需要有更明确的比较来确认
