### ISSUE TITLE
希望提示音poi能有变化

### ISSUE THREAD

**Issue by mzykiller** [poooi/poi#220]
发现远征，修复，建造，士气回复的时候都有poi~的声音提醒，非常奈斯，点赞。建议是提示音能有所变化，舰娘大破的时候的poi音可以是很委屈的声音，远征归来的时候可以是poi~poi~两声很急促的声，其余基本可以不用修改，这样子可以在干其他事情的时候能得到及时的提醒，比仅仅弹窗提醒效果要好很多

**Comment by magicae** [comment]
目前有接口可以设置 不过由于空间问题目前还没写在设置面板里 等4.0.0的独立设置面板

**Comment by PHELiOX** [comment]
https://github.com/dazzyd/poi-secretary

相关插件
