### ISSUE TITLE
底部信息栏高度异常

### ISSUE THREAD

**Issue by xyixc** [poooi/poi#2200]
**poi 版本 / poi version:**
10.3.0
**操作系统 / OS:**
Windows 10 1903（18362.329）

**插件名和版本 / Plugin name & version:**
/

**你遇到了什么样的问题 / The problem you've met:**
运行一段时间后，底部信息栏高度出现异常
**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:**
![批注 2019-09-01 235631](https://user-images.githubusercontent.com/54774309/64079169-ca637100-cd16-11e9-8bc2-70809c1f1a78.png)
![2019-09-02](https://user-images.githubusercontent.com/54774309/64079193-304ff880-cd17-11e9-8c34-774ac51a6ee5.png)

**Comment by KagamiChan** [comment]
下个版本会修复
