### ISSUE TITLE
航海日志 出击记录

### ISSUE THREAD

**Issue by xyixc** [poooi/poi#2201]
**poi 版本 / poi version:**
10.3.0
**操作系统 / OS:**
Windows 10 1903（18362.329）

**插件名和版本 / Plugin name & version:**
航海日志 7.2.0

**你遇到了什么样的问题 / The problem you've met:**
二期以来，“出击”不再记录第二舰队的信息了
会不会是一期数据的锅……如果真是这样，能不能把旧数据转换/保留？

**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:**
![批注 2019-09-02 003047](https://user-images.githubusercontent.com/54774309/64079445-30052c80-cd1a-11e9-92c1-e72c6767a520.png)

**Comment by KagamiChan** [comment]
下次活动看一下……

**Comment by xyixc** [comment]
> 下次活动看一下……

清所有数据重装后……
![批注 2020-03-08 122638](https://user-images.githubusercontent.com/54774309/76156638-31d00280-6138-11ea-896c-112b5cf8b241.png)
![批注 2020-03-08 122717](https://user-images.githubusercontent.com/54774309/76156641-35fc2000-6138-11ea-83eb-f3e989616a12.png)

**Comment by KochiyaOcean** [comment]
Should be already fixed

**Comment by xyixc** [comment]
> Should be already fixed
还是没有……
![Snipaste_2020-09-06_02-44-16](https://user-images.githubusercontent.com/54774309/92311603-05177d80-efeb-11ea-8145-6e66514c180a.png)

**Comment by KochiyaOcean** [comment]
> > Should be already fixed
> > 还是没有……
> > ![Snipaste_2020-09-06_02-44-16](https://user-images.githubusercontent.com/54774309/92311603-05177d80-efeb-11ea-8145-6e66514c180a.png)

修复后的版本还没发布，而且旧的记录是不会被修复的……
