### ISSUE TITLE
未卜先知界面显示错误

### ISSUE THREAD

**Issue by kl4428** [poooi/poi#2203]
poi 版本 / poi version:
10.3.0

操作系统 / OS:
win10 1803(17134.950)

插件名和版本 / Plugin name & version:
未卜先知 8.3.0
装备信息 4.1.4
耗资记录 0.7.4

你遇到了什么样的问题 / The problem you've met:
未卜先知显示错误，装备信息与耗资记录图标尺寸错误

[有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any:
二期前后重装过系统，之后发现问题，之后试过安装运行库和重装poi和回退到10.0.0都并未解决

未卜先知显示错误
![捕获](https://user-images.githubusercontent.com/54893094/64253894-d6d30e00-cf50-11e9-8534-55c333d826e7.PNG)
未卜先知装备显示
![捕获2](https://user-images.githubusercontent.com/54893094/64253897-d6d30e00-cf50-11e9-9282-44275be8da42.PNG)
耗资记录 0.7.4
![捕获3](https://user-images.githubusercontent.com/54893094/64253898-d76ba480-cf50-11e9-91aa-9597052329ed.PNG)

![捕获4](https://user-images.githubusercontent.com/54893094/64253899-d76ba480-cf50-11e9-8b92-568fe0a85eff.PNG)

**Comment by KochiyaOcean** [comment]
用户名里面有特殊字符导致无法加载……

**Comment by KochiyaOcean** [comment]
可以试试看这个版本 https://ci.appveyor.com/project/KochiyaOcean/poi/build/artifacts
