### ISSUE TITLE
未卜先知血条不正常

### ISSUE THREAD

**Issue by kl4428** [poooi/poi#2204]
**poi 版本 / poi version:**
10.3.0

**操作系统 / OS:**
win 10 1803(17134.950)

**插件名和版本 / Plugin name & version:**
未卜先知 8.30
耗资记录 0.74
装备信息 4.1.4

**你遇到了什么样的问题 / The problem you've met:**
插件界面显示错误，图标大小不正常

**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:**
未卜先知血条不在正常位置，装备栏被资源图标占据（之前重装过系统，不知道是不是缺了什么运行库之类的）

![捕获4](https://user-images.githubusercontent.com/54893094/64306471-6dd9ad80-cfc5-11e9-8b79-a26fac1c22f4.PNG)
![捕获](https://user-images.githubusercontent.com/54893094/64306467-6ca88080-cfc5-11e9-9aee-155df1317cf3.PNG)
![捕获2](https://user-images.githubusercontent.com/54893094/64306469-6d411700-cfc5-11e9-8af0-06c2ab1f7adf.PNG)
![捕获3](https://user-images.githubusercontent.com/54893094/64306470-6dd9ad80-cfc5-11e9-81e4-a98953778ab6.PNG)

**Comment by KochiyaOcean** [comment]
请不要重复发布
