### ISSUE TITLE
Missing English Lines 

### ISSUE THREAD

**Issue by smithysteadfast** [poooi/poi#2205]
**poi 版本 / poi version:** 10.3.0

**操作系统 / OS:** Windows 10 Build 18362.295

**插件名和版本 / Plugin name & version:** Subtitle 1.2.23 by Grzhan

**你遇到了什么样的问题 / The problem you've met:** Missing English subtitles for a lot of the newer girls and recent Kai Ni versions. 

**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:**

**Comment by soloblast** [comment]
For EN translations (including issue #2176 ) you might want to contact Leyana on Discord, EN translations are done by him and a few others (Mikado, /a/nonymous, etc.) Think they recently finished checking/editing some of the older translations as well.

**Comment by MZIchenjl** [comment]
@Tricklin
