### ISSUE TITLE
poi掉落頁面久未更新

### ISSUE THREAD

**Issue by leader92gogo** [poooi/poi#2206]
poi掉落已經超過3天沒有更新了，尤其E3停留在多數人還在苦解謎的時候，雖然這裡是回報有關poi瀏覽器的問題我知道，但是poi掉落的githud回報管道已經被停用了我只好在這回報

**Comment by KochiyaOcean** [comment]
@leader92gogo 掉落页面是 kcwiki 维护的，poi 开发组只提供数据

**Comment by leader92gogo** [comment]
> @leader92gogo 掉落页面是 kcwiki 维护的，poi 开发组只提供数据

那我可以在哪裡回報kcwiki？

**Comment by KochiyaOcean** [comment]
@leader92gogo 找官方微博之类的问一下吧...

**Comment by Gizeta** [comment]
我的锅。

项目被停用是因为本来计划这次活动上新版的，归档了旧项目，结果咕咕咕了，我暂时先开放了旧项目的repo。

数据没更新也是我的疏忽，现在已经在开始统计这3天的数据了。

\[背锅.png\]

**Comment by KagamiChan** [comment]
@Gizeta 新版页面需要帮忙吗，咕咕咕

**Comment by Gizeta** [comment]
@leader92gogo 已经更新了

@KagamiChan 现在还在选型踩坑阶段，连整体框架都没完全搭起来:see_no_evil:
目前计划上拖到下次活动前了
https://github.com/kcwikizh/poi-stat-kai/tree/dev
