### ISSUE TITLE
圖鑑收集進度

### ISSUE THREAD

**Issue by x60516** [poooi/poi#2208]
**poi 版本 / poi version:**
10.3.0
**操作系统 / OS:**
windows 7

**插件名和版本 / Plugin name & version:**

**功能的详细描述 / Details on the feature:**

以前的圖鑑收集進度可以加回來嗎?

https://i.imgur.com/tea9eeo.png

**Comment by KochiyaOcean** [comment]
@x60516 会有的……

**Comment by Shell32-Natsu** [comment]
@x60516 我写了个插件显示图鉴进度<https://www.npmjs.com/package/poi-plugin-collection-progress>，你可以试一下。第一次写插件，React不熟，欢迎帮忙测试。
