### ISSUE TITLE
希望可以增加遊戲面板置中，艦隊和插件面板分別在左右兩邊的佈局樣式

### ISSUE THREAD

**Issue by nagatoaneki** [poooi/poi#2210]
**poi 版本 / poi version:**
9.0.2

**你遇到了什么样的问题 / The problem you've met:**
在筆電上無論把遊戲面板放左邊右邊上面下面都很奇怪，希望可以把面板放中間

**Comment by KochiyaOcean** [comment]
之前的 issue 有讨论过，结论是不准备支持
