### ISSUE TITLE
数据丢失？

### ISSUE THREAD

**Issue by xpgr233** [poooi/poi#2212]
poi版本/ poi版本：10.3.0

操作系统/ OS：win10

插件名和版本/插件名称和版本：

你遇到了某种的问题/您遇到的问题：重置系统保留个人文件，但是poi的插件和数据全都没了，能否找回

**Comment by KochiyaOcean** [comment]
@xpgr233 不保留程序数据的话可能已经被删了

**Comment by taroxd** [comment]
poi 数据默认放在 `C:\Users\<你的用户名>\AppData\Roaming\poi` 下，你可以翻一翻 windows.old 看看里面有没有
