### ISSUE TITLE
游戏内切换界面时侧边插件也被切出到主界面

### ISSUE THREAD

**Issue by erikaemma** [poooi/poi#2213]
比如我正在看远征信息
这个时候我要点击到编成界面，再切换到指定的队伍
这个时候，侧边栏就自动切换到主界面了

**Comment by SoraYama** [comment]
这个是设定里面的功能，如果你想关闭这个功能的话可以在 设置 -> 游戏 中关闭勾选 「允许自动切换至主面板」这个选项
