### ISSUE TITLE
下部信息界面全部消失

### ISSUE THREAD

**Issue by zhangyunhai210** [poooi/poi#2218]
**poi 版本 / poi version:**
10.3.0.0
**操作系统 / OS:**
win10 1903

**插件名和版本 / Plugin name & version:**
所有下部界面

**你遇到了什么样的问题 / The problem you've met:**
下部界面突然消失
![O{E7AVP()~L~1)47W~8`W4D](https://user-images.githubusercontent.com/14874389/67100820-fb2e3580-f1f2-11e9-8bf3-2a6d6d44f976.png)

**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:**
重启 即可，没有恢复

![OOJL O5)BEQAV(~QZ`@GCWL](https://user-images.githubusercontent.com/14874389/67100794-ef427380-f1f2-11e9-8ed3-85a0495e70d9.png)

**Comment by KochiyaOcean** [comment]
@zhangyunhai210 大概是主面板之类的地方崩溃了，但是错误信息不是提供的这个。上面应该有别的错误信息才是

**Comment by zhangyunhai210** [comment]
[BABEL] Note: The code generator has deoptimised the styling of  E:\poi\resources\app.asar\node_modules\lodash\lodash.js as it exceeds the max of 500KB.

normalizeOptions @ E:\poi\resources\app.asar\node_modules\@babel\core\node_modules\@babel\generator\lib\index.js:65

TypeError: Cannot read property 'api_area_id' of null

qh @ E:\poi\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:198

TypeError: Cannot read property 'api_area_id' of null

componentDidCatch @ E:\poi\resources\app.asar\views\components\tab-area\index.js:529

**Comment by zhangyunhai210** [comment]
> @ zhangyunhai210大概是主面板之类的地方崩溃了，但是错误信息不是提供的这个。上面应该有别的错误信息才是

[BABEL] Note: The code generator has deoptimised the styling of E:\poi\resources\app.asar\node_modules\lodash\lodash.js as it exceeds the max of 500KB.

normalizeOptions @ E:\poi\resources\app.asar\node_modules@babel\core\node_modules@babel\generator\lib\index.js:65

TypeError: Cannot read property 'api_area_id' of null

qh @ E:\poi\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:198

TypeError: Cannot read property 'api_area_id' of null

componentDidCatch @ E:\poi\resources\app.asar\views\components\tab-area\index.js:529

**Comment by KagamiChan** [comment]
@zhangyunhai210 请试一下开始菜单里面的 poi(safe mode)，用安全模式打开看看

**Comment by zhangyunhai210** [comment]
> @zhangyunhai210 请试一下开始菜单里面的 poi(safe mode)，用安全模式打开看看

抱歉，并没有找到safe mode
![% W6~VGRXM) 2P2@ U DZE1](https://user-images.githubusercontent.com/14874389/67101877-113cf580-f1f5-11e9-8bc4-13d3e226d139.png)

**Comment by KagamiChan** [comment]
@zhangyunhai210 windows 的开始菜单

**Comment by zhangyunhai210** [comment]
> @zhangyunhai210 windows 的开始菜单

没有问题，safe模式下一切正常

**Comment by KagamiChan** [comment]
@zhangyunhai210 嗯，那就应该好了。

**Comment by zhangyunhai210** [comment]
> @zhangyunhai210 嗯，那就应该好了。

非常感谢，是一个插件的问题，我删除就好了

**Comment by CloudyMoonShape** [comment]
遇到同样问题，Safe Mode也加载不出来。试过了用Windows 7兼容模式，重装Poi，删除%AppData%/Poi下全部内容等方法均不Work。

**Comment by KagamiChan** [comment]
@CloudyMoonShape 请重新开一个 issue，并且贴一下出错的记录，谢谢
