### ISSUE TITLE
日进携带二式大艇时，舰队面板搭载状态显示错误

### ISSUE THREAD

**Issue by dislido** [poooi/poi#2222]
**poi 版本 / poi version: 10.4.0-beta.0**

**操作系统 / OS: Windows 10 18362**

**你遇到了什么样的问题 / The problem you've met:**
二式大艇最高搭载数为1，在舰队面板上显示为未补满的颜色
![image](https://user-images.githubusercontent.com/25094788/67633176-f999f700-f8ef-11e9-9420-a323b88c8ec0.png)

**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:**
日进甲在任意格搭载二式大艇

**Comment by taroxd** [comment]
因为确实没有补满，此时会把多出来的 35 铝退到你的资源里 <del>甚至可以超过 30w</del>
