### ISSUE TITLE
"poi (safe mode)" shortcut not removed when uninstalled

### ISSUE THREAD

**Issue by takase1121** [poooi/poi#2223]
**poi 版本 / poi version:** 10.3.0 (Setup version)

**操作系统 / OS:** Windows 10 Pro v19008.vb_release 191019-1715 (Windows Insider, Fast Ring)

**你遇到了什么样的问题 / The problem you've met:**

The shortcut "Poi (safe mode)" is not removed after Poi is uninstalled

**Comment by KagamiChan** [comment]
Thanks for reporting. We missed this point.

But it is a little complicated to add a stable and working script to remove this item
