### ISSUE TITLE
Subtitle Plug-In Automatically Changes To English

### ISSUE THREAD

**Issue by soloblast** [poooi/poi#2224]
**poi 版本 / poi version:** 10.3.0

**操作系统 / OS:** Windows 10 (OS Build 18362.418), macOS 10.14 Mojave

**插件名和版本 / Plugin name & version:** Subtitle 1.2.23

**你遇到了什么样的问题 / The problem you've met:** The subtitle text will sometimes change into English without any changes to the settings, despite the settings having been set to 日本語. Problem will occur again even after manually switching it back to 日本語 in the settings.

虽然插件设置是日本文，字幕有时会自己换成英文。把设置换回日本文后，问题还是会发生。

**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:** Poi main setting language is English. Poi基本设置语文是英文。

**Comment by KagamiChan** [comment]
cc @MZIchenjl
