### ISSUE TITLE
Certificate Error

### ISSUE THREAD

**Issue by soloblast** [poooi/poi#2225]
**poi 版本 / poi version:** 10.3.0

**操作系统 / OS:** Windows 10 (OS Build 18362.418), macOS 10.14 Mojave

**插件名和版本 / Plugin name & version:** N/A

**你遇到了什么样的问题 / The problem you've met:** [Certificate error](https://imgur.com/a/HDZmwqN) on both platforms running on the same internet connection. sha256 value is the same on both platforms.

**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:** Problem did not occur before today, no changes to internet connection on my end. I do not use a proxy. Can still log into game without issues so far. Tried to revoke all certificates and clear cookies from settings, problem still occurs.

**Comment by soloblast** [comment]
Apparently it's for ups.analytics.yahoo.com which expired yesterday and is used by DMM. Never mind, thanks.

**Comment by KagamiChan** [comment]
Thanks for investing time on this. Normally you could feel free to click cancel

**Comment by soloblast** [comment]
No problem, better to document this way in case someone has the same question in the near future (especially since the cert just expired today so other people might get the message too).

**Comment by KochiyaOcean** [comment]
![image](https://user-images.githubusercontent.com/8194131/68132834-b3cdd600-ff62-11e9-91e8-1ae6f152dde1.png)
Seems to be a problem caused by yahoo analysis script included in the webpage. You can just ignore it
