### ISSUE TITLE
禁用硬體加速會掉偵

### ISSUE THREAD

**Issue by x60516** [poooi/poi#2228]
**poi 版本 / poi version:**
10.4.0-bata.0
**操作系统 / OS:**
windows 10
**你遇到了什么样的问题 / The problem you've met:**
開啟【禁用硬體加速】會掉偵
請問有辦法解決嗎?

**Comment by KagamiChan** [comment]
比较遗憾没有什么特别好的办法。掉帧主要原因是游戏对于硬体需求较高

**Comment by KochiyaOcean** [comment]
如果不是有兼容问题（闪烁，表示错误）之类一般不建议关闭硬件加速

**Comment by x60516** [comment]
不禁用硬體加速的話
使用OBS錄影軟體擷取不到遊戲視窗
有別的辦法嗎?

**Comment by KochiyaOcean** [comment]
@x60516 OBS 也是对 CPU 压力很大的软体，如果需要软解 + OBS 的话对 CPU 性能要求比较高。
另外有一个选择是 OBS 的来源设置为获取整个屏幕然后只截取游戏区域（而非使用捕捉窗口），这样在硬体加速的情况下也可以使用 OBS
