### ISSUE TITLE
lag問題

### ISSUE THREAD

**Issue by karta0636606** [poooi/poi#2229]
**poi 版本 / poi version:**10.4.0

**操作系统 / OS:**win10 1903

**插件名和版本 / Plugin name & version:**

**你遇到了什么样的问题 / The problem you've met:**
感覺好像自從更新後會經常卡讀取或是黑畫面，有時等2~3分鐘就可以繼續動作但有時就卡住半小時以上也沒反應
![1573826902365](https://user-images.githubusercontent.com/57802162/68949227-90254e00-07f4-11ea-90a4-eada63e8d2a9.jpg)
重新安裝或是輕cookie等都試了仍無改善

**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:**

![1573827172916](https://user-images.githubusercontent.com/57802162/68949489-18a3ee80-07f5-11ea-9e75-d2df58cf5c51.jpg)

**Comment by KochiyaOcean** [comment]
有没有试过换一个网络环境
