### ISSUE TITLE
任务计数器在任务刷新后未正常清空

### ISSUE THREAD

**Issue by FXuZ** [poooi/poi#223]
第一天的日常任务没有完成并且领完任务的时候关掉poi,
第二天poi在任务刷新前启动然后日常任务刷新出来并且再接到同一个任务(这边发现的是日常10远征)的时候会看到这个任务的计数器没有清零而且看起来像把中间不该有的计数都加上了结果显示不正常.

**Comment by magicae** [comment]
你电脑的时间和你所在的当地时间的关系是？

**Comment by FXuZ** [comment]
电脑用的local time, 系统时钟用的UTC, 时区在-5，有夏季时。

----- Reply message -----

**Comment by malichan** [comment]
看来是夏令时的锅  学姐哭哭哦

**Comment by FXuZ** [comment]
夏季时吗…真辛苦呢…不过有可能在任务出现的时候重置计数器吗…？其实我至今也没弄清楚游戏从什么时候开始计数的，是任务出现的时候还是第一次领任务的时候…

----- Reply message -----

**Comment by c933103** [comment]
應該都是領仼務起計(不知道有沒有例外)

**Comment by FXuZ** [comment]
那如果poi已经判定任务完成了(这时候其实任务已经刷新了)的时候领了任务会如何判定呢...?

**Comment by magicae** [comment]
判定任务完成的话poi会直接把追踪记录清空的

**Comment by FXuZ** [comment]
我说的是计数达到要求但是并没有领任务的时候任务刷新消失了的情况…

----- Reply message -----

**Comment by magicae** [comment]
poi大概30秒会根据本地时间判断是否过了东京时间5点…如果过了就清一次日常的所有counter

**Comment by FXuZ** [comment]
嗯，那我这边显然就不是这个原因了…但是不算夏季时的话日本时间是提前了一个小时并不是推后了一个小时呢…我尝试重现一下看看吧，找个不怎么必要的任务。你说的清所有counter是无论当时是否在活动状态的都清理吗？

----- Reply message -----

**Comment by magicae** [comment]
嗯 只要type为日常的都清空

**Comment by magicae** [comment]
master里的似乎没问题了 活动相关代码完善后就出新版本

**Comment by magicae** [comment]
在v3.3.1中修复了
