### ISSUE TITLE
面板調整

### ISSUE THREAD

**Issue by welson050917** [poooi/poi#2230]
**poi 版本 / poi version:10.4.0**

**操作系统 / OS:win 7**

**功能的详细描述 / Details on the feature:**

![未命名](https://user-images.githubusercontent.com/57126126/69911931-825f0200-145d-11ea-9048-b5ca7b429cd0.png)

我想拉長概覽中艦隊欄位的長度，請問該如何調整?

**Comment by KochiyaOcean** [comment]
点击工具栏里面的锁图标

**Comment by welson050917** [comment]
我嘗試過，但我只能移動欄位的位置無法調整長度

**Comment by KochiyaOcean** [comment]
@welson050917 拖动右下角

**Comment by welson050917** [comment]
成功了，謝謝您的協助
