### ISSUE TITLE
一定情况下，鼠标放到“概览”的任务部分出现的浮窗会鬼畜

### ISSUE THREAD

**Issue by doomedtraveler** [poooi/poi#2231]
**poi 版本 / poi version:10.4.0

**操作系统 / OS:Win10 版本1903（OS 内部版本 18362.476）

在双窗口布局中
<img src="https://s2.ax1x.com/2019/12/02/QnKdUK.png" alt="QnKdUK.png" border="0" />
一定宽度下，字数较长的任务显示会鬼畜
<img src="https://s2.ax1x.com/2019/12/02/QnKBCD.gif" alt="QnKBCD.gif" border="0" />
（好像gif不怎么流畅，我也不知道GitHub怎么发图。。https://s2.ax1x.com/2019/12/02/QnKBCD.gif）
窗口拉宽恢复
<a href="https://imgse.com/i/QnKw4O"><img src="https://s2.ax1x.com/2019/12/02/QnKw4O.md.png" alt="QnKw4O.png" border="0" /></a>

**Comment by Nankyoku-D** [comment]
macOS 10.15.1 (19B88)

也有这个问题。不是所有的都会抖，但是基本总有那么几个会抖，特别是旗舰。
10.3.0 就已经这样了。10.4.0 更严重一点

**Comment by KagamiChan** [comment]
对于分离模式这个属于已知问题，因为默认情况下弹出内容会在左边出现，但是如果左边的宽度不足的话，就会改为右侧出现，然而右侧空间也是不足的，于是就会出现闪烁。因为本质上是空间不足以放下内容，所以暂时没有一个很好的解决方法

建议放宽窗口

**Comment by Nankyoku-D** [comment]
原来如此。那应该是向右侧弹出的装备，以及向左侧弹出的任务，这两个的问题了。
不知道之后能否升级成根据宽度改变弹出方向？
