### ISSUE TITLE
耗資紀錄無法正常紀錄

### ISSUE THREAD

**Issue by USedhcnW** [poooi/poi#2232]
**poi 版本 / poi version:** 10.4.0

**操作系统 / OS:** 18362.476 win10 1903

**插件名和版本 / Plugin name & version:** 耗資紀錄 0.7.4

**你遇到了什么样的问题 / The problem you've met:** 
poi重新啟動後,耗資紀錄的新紀錄會消失。

**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:**
![圖片 982](https://user-images.githubusercontent.com/58424541/69956163-42218180-153a-11ea-9ef5-2074d1df0a92.png) 

<!-- Love poi? Please consider supporting our collective:

**Comment by JimmyKuo-24** [comment]
poi 版本 / poi version:：10.4.0

操作系统 / OS：win7 專業版

插件名和版本 / Plugin name & version:：耗資紀錄 0.7.4

你遇到了什么样的问题 / The problem you've met：
同上一樣的問題，之前在試用beta版的時候也是這樣，改回前個版本10.3.0就好了...

**Comment by KochiyaOcean** [comment]
fixed by 20601d88918e9ce43d234c947743f16e3ee0e008
