### ISSUE TITLE
POI URL跳转至dmm login的地址时会黑屏

### ISSUE THREAD

**Issue by Megumi-RQY** [poooi/poi#2235]
poi 版本 / poi version: 10.4.0

操作系统 / OS: 18362.476 win10 1903

你遇到了什么样的问题 / The problem you've met:
无法连接到dmm login的地址。

有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:
step1.
开启poi后进入舰娘游戏主页：
![1](https://user-images.githubusercontent.com/26399538/70250239-b0cc3c80-17d1-11ea-8f96-a59c5be34489.png)
step2.
点击今すぐ出撃/ログイン，黑屏。
![2](https://user-images.githubusercontent.com/26399538/70250745-7c0cb500-17d2-11ea-9f50-3002276a15db.png)

其他可能有帮助的信息：
代理是岛风go，通过chrome可成功登陆游戏。

**Comment by KagamiChan** [comment]
请点击移除信任 / 无视证书按钮，再从首页登录试试看

**Comment by Megumi-RQY** [comment]
> 请点击移除信任 / 无视证书按钮，再从首页登录试试看

还是黑屏，不过报错信息变了。
![3](https://user-images.githubusercontent.com/26399538/70252631-dfe4ad00-17d5-11ea-8dbf-ecfe477f3873.png)

**Comment by KochiyaOcean** [comment]
@Megumi-RQY 换线看看

**Comment by Megumi-RQY** [comment]
> @Megumi-RQY 换线看看

换到线路2登上去了。
感谢！
