### ISSUE TITLE
10.4.0 耗资记录丢失

### ISSUE THREAD

**Issue by Nankyoku-D** [poooi/poi#2239]
**poi 版本 / poi version:** 
10.4.0

**操作系统 / OS:** 
macOS 10.15.1 (19B88)

**插件名和版本 / Plugin name & version:**
耗资记录  0.7.4

**你遇到了什么样的问题 / The problem you've met:**
更新版本后，某天突然发现丢失了 12/3～12/7 的所有耗资记录，相对应的书签也消失了。
之前和之后的记录似乎正常。
看见其他群友也出现了一段时间内所有耗资记录消失的情况。他大概是 12/2早晨～12/8。

**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:**
航海日志和战斗记录似乎没有问题。

**Comment by Nankyoku-D** [comment]
【更新】
新的记录虽然会被记录。但是只要关闭POI，然后重启，重登账号以后，所有新记录都不见了。
换回 10.3.0 以后，消失的记录还是消失了……
最后一条记录是 12/2 19:39:01 （东京时间）

**Comment by deepsea666** [comment]
问题基本就是出在新版本冲突，都半个月了还没解决，如果不是开了活动都不知道有这个BUG

**Comment by KochiyaOcean** [comment]
fixed by 20601d88918e9ce43d234c947743f16e3ee0e008
