### ISSUE TITLE
点击截图灰屏

### ISSUE THREAD

**Issue by GalliumNitride** [poooi/poi#2240]
**poi 版本 / poi version:10.4.0**

**操作系统 / OS:WIN10 发行版本1903**

**插件名和版本 / Plugin name & version:**

**你遇到了什么样的问题 / The problem you've met:点击截图后灰屏，然后点击刷新游戏程序就闪退**

**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:**

**Comment by KagamiChan** [comment]
10.5.1 beta 版已经换回了原来的截图方式
