### ISSUE TITLE
插件无法安装和更新，删除耗资记录后无法安装，任务信息无法更新

### ISSUE THREAD

**Issue by KuaiGexun** [poooi/poi#2241]
**poi 版本 / poi version: 10.4.0**

**操作系统 / OS: win10/1809**

**插件名和版本 / Plugin name & version:可能是全部**

**你遇到了什么样的问题 / The problem you've met: 插件无法安装和更新，删除耗资记录插件后无法安装，任务信息插件无法更新**

**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related: 重启和重装并没有解决问题**

**Comment by KagamiChan** [comment]
![image](https://user-images.githubusercontent.com/3816900/70553358-e9935980-1bb5-11ea-9a65-567c5b841cbc.png)

**Comment by KuaiGexun** [comment]
解决了
