### ISSUE TITLE
未卜先知插件陆航守家伤害不能正确显示

### ISSUE THREAD

**Issue by xiaohuixin** [poooi/poi#2243]
**poi 版本 / poi version:poi 10.4 

**操作系统 / OS:Win10

**插件名和版本 / Plugin name & version: 未卜先知 8.2

**你遇到了什么样的问题 / The problem you've met:打活动，陆航守家都被炸烂了，插件显示还是满血

**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:

**Comment by KagamiChan** [comment]
这是田中修改了 api 的问题
目前只在某些服务器出现，实在是太田中了
