### ISSUE TITLE
游戏黑屏

### ISSUE THREAD

**Issue by MVPmkll** [poooi/poi#2244]
**poi 版本 / poi version:** 10.4.0

**操作系统 / OS:**macOS

**插件名和版本 / Plugin name & version:**

**你遇到了什么样的问题 / The problem you've met:**游戏黑屏了，已嘗試淸除cookie及快取，以及地址栏里面输入 baidu.com 等地址共不能正确打开

以下是代理设置的截图
![image](https://user-images.githubusercontent.com/59001285/71050340-48de0480-2188-11ea-9cb5-be6fe6b6fd3c.png)
![image](https://user-images.githubusercontent.com/59001285/71050346-4c718b80-2188-11ea-8ac9-a67d351d0450.png)
![image](https://user-images.githubusercontent.com/59001285/71050348-4ed3e580-2188-11ea-95db-78da485d4155.png)

**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:**

![image](https://user-images.githubusercontent.com/59001285/71050135-c05f6400-2187-11ea-90cd-e00e7a962a86.png)

**Comment by KochiyaOcean** [comment]
请问现在是否解决？

**Comment by MVPmkll** [comment]
已解決了。感謝。

2020年6月16日(火) 0:41 東風谷オーシャン <notifications@github.com>:
