### ISSUE TITLE
启动时静音设置失效

### ISSUE THREAD

**Issue by einbrain** [poooi/poi#2246]
**poi 版本 / poi version:**
10.5.0 Beta 0 / Beta 1

**操作系统 / OS:**
Windows 10 1909 (64bit)

**你遇到了什么样的问题 / The problem you've met:**
平时玩的时候都开静音。升级到10.5.0-beta.0之后启动时静音设置失效，具体表现为：
- 主界面左下按钮显示为静音
- 舰娘：(ﾟ∀ﾟ)＜艦これ！
- 等启动画面舰娘语音开始播放之后再设置静音关闭->开启，可实现本次启动后静音
- 重启poi后问题重现

升级至10.5.0-beta.1问题依旧

**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:**
见↑

**Comment by KagamiChan** [comment]
来自上游的神秘问题，暂时还没有找到原因……
