### ISSUE TITLE
Tab key selects panels below KC interface (cuts off top part of screen until refresh)

### ISSUE THREAD

**Issue by soloblast** [poooi/poi#2247]
![2019-12-28T5 32 57](https://user-images.githubusercontent.com/57139915/71533524-34da9580-2934-11ea-82b1-c09e4620f7fa.png)

**poi 版本 / poi version:** 10.5.0-beta,1

**操作系统 / OS:** Windows 10 Version 1909 (OS Build 18363.535)

**你遇到了什么样的问题 / The problem you've met:** See screenshot.

**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:** Seems to occur when Tab key is pressed, usually during sorties. There doesn't seem to be a way to revert back to the original screen other than by refreshing, which can be problematic if you need to select anything in the top part of the screen (e.g. LBAS in picture above)

**Comment by KochiyaOcean** [comment]
This issue should be already fixed in long time ago...
Anyway, if you see this problem, a temporary fix is to right-click auto-adjust button and left click it again
![image](https://user-images.githubusercontent.com/8194131/71540243-41d6a380-298b-11ea-9787-004e433ee4d0.png)
