### ISSUE TITLE
POI出现了2个问题 页面圈圈转动很慢和之后猫了

### ISSUE THREAD

**Issue by 45jjk-ik4** [poooi/poi#2248]
**poi 版本 / poi version:**POI 10.5.0-beta.1

**操作系统 / OS:**win7

**插件名和版本 / Plugin name & version:**

**你遇到了什么样的问题 / The problem you've met:**
 有两个问题 
  第一个问题是POI刚登陆进去后 速度还是很快的 可是过了几分钟之后，左下就会突然圈圈转动很慢，大概一分钟后又回复正常，然后过了几分钟后左下又会突然圈圈转动很慢，按时间来计算的了 大概是E1的2个战斗点
  第二个问题是前一个问题的圈圈如果转到了一定时间，没有回复正常的话 ， 就会直接猫 可是左下显示岛风GO运行正常，
 这个两个问题从一个半星期以前开始出现，期间尝试过清理系统全部游览器的缓存  POI和岛风GO也重新下载过2次 POI10.4和10.5.0-beta-1版本都使用过 还是解决不了问题 魔改和缓存全部清理过还是无效 ，现在使用的版本是POI 10.5.0-beta.1

**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:**

由于不会截图 直接放复制和张贴了

[BABEL] Note: The code generator has deoptimised the styling of D:\poi\resources\app.asar\node_modules\lodash\lodash.js as it exceeds the max of 500KB.
                                                                                      D:\poi\resources\app…tor\lib\index.js:65

Failed to load resource: net::ERR_FILE_NOT_FOUND                  
                                                                                          %E8%8B%8D%E9%BE%991.jpg:1

Uncaught TypeError: Cannot read property 'api_ship_id' of undefined
D:\poi\resources\app.asar\views\services\sortie-expedition-resupply-check.js:20 Uncaught 

    at D:\poi\resources\app.asar\views\services\sortie-expedition-resupply-check.js:20:31
    at Array.some (<anonymous>:null:null)
    at D:\poi\resources\app.asar\views\services\sortie-expedition-resupply-check.js:18:98
    at parseResponses (D:\poi\resources\app.asar\views\env-parts\data-resolver.js:114:10)
    at resolveResponses (D:\poi\resources\app.asar\views\env-parts\data-resolver.js:122:7)
    at handleProxyGameOnResponse (D:\poi\resources\app.asar\views\env-parts\data-resolver.js:137:7)
    at CallbacksRegistry.apply (electron/js2c/renderer_init.js:1799:29)
    at electron/js2c/renderer_init.js:1598:21
    at EventEmitter.<anonymous> (electron/js2c/renderer_init.js:1588:7)
    at EventEmitter.emit (events.js:203:13)
    at Object.onMessage (electron/js2c/renderer_init.js:2394:16)

开发者工具的打开方式是按 ctrl + shift + i (macOS 上为 ⌥ + ⌘ + i），或游戏区域下方信息栏的最左边齿轮按钮。
Please provide a screenshot of developer tool's console tab, if possible.
To open the dev tool, press ctrl + shift + i (⌥ + ⌘ + i for macOS), or the leftmost gear button on the info bar below the game area.
-->

**Comment by KagamiChan** [comment]
这属于网络问题，岛风 go 换一个线路试试看

**Comment by 45jjk-ik4** [comment]
所有线路换了一遍 还是不行

**Comment by KochiyaOcean** [comment]
代理配置是什么样的

**Comment by 45jjk-ik4** [comment]
网络代理类型是HTTP代理 地址127.0.0.1 端口8099 其他的没有设置

**Comment by KochiyaOcean** [comment]
？怎么关上了

**Comment by 45jjk-ik4** [comment]
关上是因为早上起来测试了一下 发现没有昨天的情况了 但问题还是有的 估计是网络问题，昨天是所有重新下载和岛风GO用其他线路 没有用推荐线路 可能是要换线路丙开机重新启动 不过现在情况是还是坐下会有圈圈转动 大概一场E1 比之前好多了 每次转动大概10SA左右就没有 已经一天没有猫了

**Comment by 45jjk-ik4** [comment]
关上是因为早上起来测试了一下 发现没有昨天的情况了 但问题还是有的 估计是网络问题，昨天是所有重新下载和岛风GO用其他线路 没有用推荐线路 可能是要换线路丙开机重新启动 不过现在情况是还是坐下会有圈圈转动 大概一场E1 比之前好多了 每次转动大概10SA左右就没有 已经一天没有猫了
