### ISSUE TITLE
Poi doesn't open the game page, showing only the DMM site page.

### ISSUE THREAD

**Issue by Joey-K** [poooi/poi#2249]
**poi 版本 / poi version:** Version 10.4.0

**操作系统 / OS:** Windows 10 Home 

 Build 1903

**你遇到了什么样的问题 / The problem you've met:** I've been using Poi for almost two years, and needed to re-install it. When i start Poi, it shows-me the page with the red button, clicking the red button i go to the login page, and after i put my login it quickly shows my DMM profile and changes to what looks like the end of the site page (the one in the screenshot), but the game is nowhere to be seen. 

**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:** I already had this problem before, and it seemed to go away when i marked "Prevent DMM network change popup" but i don't know if there's any relation with this option, since this time it did not work.

 
![POI Problem](https://user-images.githubusercontent.com/59371204/71594936-922f3c00-2b18-11ea-8c6f-042c5c0f885d.png)

**Comment by KagamiChan** [comment]
I don't think the option you mentioned is related

How do you connect to the game? via VPN, proxy or in direct?

**Comment by Joey-K** [comment]
In direct since i just installed and put my login, not changing anything. Never Proxy keeping the option "No proxy" marked, and i don't know how to use the VPN with Poi so, i'm pretty sure i never used it.

**Comment by KagamiChan** [comment]
Please try emptying cache and cookies and also certs, and restart poi

![image](https://user-images.githubusercontent.com/3816900/71596127-54163480-2b79-11ea-8817-2df2c818950b.png)

let's see if this could help

**Comment by Joey-K** [comment]
Used the three options, but the problem remains. When i clicked the "Revoke trusted / ignored certificates" i did not receive a popup (like the first two options) saying it worked.

**Comment by KagamiChan** [comment]
From your screen shot it seems the content loading has some issue
did you manage to open the game in other browsers like Chrome or Firefox?

**Comment by Joey-K** [comment]
I already used Chrome and Opera, with KC3Kai. It worked fine, despite some connection problems.

**Comment by KagamiChan** [comment]
If they're fine then poi should also be fine, that's weird

please make sure you are on the page `http://www.dmm.com/netgame/social/-/gadgets/=/app_id=854854/`

And try open the command line (cmd or powershell) and run `netsh winsock reset` command

**Comment by Joey-K** [comment]
Hello! Happy new year! I wish the best for you!
Sorry for the delay. Unfortunately that didn't work. I will try to uninstall, Run netsh winsock reset and then install it again.
