### ISSUE TITLE
POI擴展程式無法安裝

### ISSUE THREAD

**Issue by ReaLusional** [poooi/poi#2254]
**poi 版本:**10.4.0
**操作系统 / OS**:Windows 10 專業版
**插件名和版本 / Plugin name & version:**
**你遇到了什么样的问题 / The problem you've met:** 
POI擴展程式無法安裝, 按下"安裝後"一直顯示"安裝中"
![擷取](https://user-images.githubusercontent.com/59536300/71783079-9a0d4580-301c-11ea-9f02-1b514fae1504.PNG)

**Comment by KochiyaOcean** [comment]
@ReaLusional 插件 - 高级设置 - 自动修复
