### ISSUE TITLE
战果计算器无法使用

### ISSUE THREAD

**Issue by pineapple94666** [poooi/poi#2255]
**poi 版本 / poi version:10.4.0

**操作系统 / OS:WIN10 1903内部版本18362.535家庭中文版

**插件名和版本 / Plugin name & version:我变强了4.4.2
无法使用,文字错位，点击任何一个位置都没有反应，每次打开都是这个问题

**Comment by a98015** [comment]
https://github.com/poooi/poi/issues/2245

是不是跟我一樣?
總算找到同樣出現問題的好兄弟了(哭
我朋友沒刷戰果,沒安裝那個插件,又沒有人回答我,我還以為就我一個人出問題呢

**Comment by KochiyaOcean** [comment]
@a98015 7102 年就坏了，没人力修

**Comment by jerry78424** [comment]
poi-plugin-achievement
改用這個吧，好用多了，雖然近來也沒有更新

**Comment by a98015** [comment]
安b了,xx!

 Windows 10 的]件<https://go.microsoft.com/fwlink/?LinkId=550986>魉

________________________________
寄件者: jerry78424 <notifications@github.com>
寄件日期: Saturday, February 1, 2020 8:32:20 PM
收件者: poooi/poi <poi@noreply.github.com>
副本: a98015 <a98015@hotmail.com>; Mention <mention@noreply.github.com>
主旨: Re: [poooi/poi] 战果计算器无法使用 (#2255)


poi-plugin-achievement
改用@吧，好用多了，m然近硪]有更新

―
