### ISSUE TITLE
異常卡頓

### ISSUE THREAD

**Issue by lylle200** [poooi/poi#2257]
**poi 版本 / poi version:**
10.5.0-beta.2
**操作系统 / OS:**
Windows 10 1909

**你遇到了什么样的问题 / The problem you've met:**
程式異常卡頓, 剛剛開啟就是這樣, 每個操作需要大約十幾秒才反應, 但是如果是以系統管理員身分執行就沒問題, 之前數個版本也是這樣, 也試過刪除後重新安裝, 但也沒解決
**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:**

所以是卡頓到連開發者工具打不開啦

**Comment by KagamiChan** [comment]
麻烦按 win + R，在弹出的窗口里面输入 cmd 并执行，打开命令行
再把 poi 的程式图标拖到命令行窗口里面执行，麻烦把打出来的内容贴一下

**Comment by lylle200** [comment]
![擷取](https://user-images.githubusercontent.com/50950049/71891194-67349000-3189-11ea-9ee9-9e8347232c5a.PNG)

**Comment by lylle200** [comment]
![擷取](https://user-images.githubusercontent.com/50950049/71891565-46206f00-318a-11ea-9939-ec6025b66435.PNG)

**Comment by KagamiChan** [comment]
看起来并无异常之处……我之前也没有收到过类似的管理员权限无问题，普通权限运行很慢的报告

有没有安装什么杀软？
