### ISSUE TITLE
文月改二对空ci显示错误？

### ISSUE THREAD

**Issue by mfy0120** [poooi/poi#2259]
**poi 版本 / poi version:**
10.5.2
**操作系统 / OS:**
mac

**插件名和版本 / Plugin name & version:**

**你遇到了什么样的问题 / The problem you've met:**
<img width="1274" alt="d2" src="https://user-images.githubusercontent.com/4901819/71868566-7e10af00-30c3-11ea-88f6-35a00ea2d6d1.png">
文月改二并没有搭配机铳，却显示能够进行对空ci

**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:**

**Comment by mfy0120** [comment]
版本号写错了,是10.5.0-beta.2:(

**Comment by KochiyaOcean** [comment]
dup https://github.com/poooi/poi/issues/2256
下个版本修复
