### ISSUE TITLE
舰队页”对空CI“错误显示

### ISSUE THREAD

**Issue by xyixc** [poooi/poi#2260]
**poi 版本 / poi version:**
10.5.0-beta.2
**操作系统 / OS:**
Win10 1909 （18363.535）

**插件名和版本 / Plugin name & version:**

**你遇到了什么样的问题 / The problem you've met:**
当舰娘携带“**· · ·**”/其他分类装备时（如大发/探照灯）舰队面板错误显示”**对空CI**“
![批注 2020-01-08 022626](https://user-images.githubusercontent.com/54774309/71920384-91a23f80-31c1-11ea-9a39-8f613493283a.png)
![批注 2020-01-08 025246](https://user-images.githubusercontent.com/54774309/71920696-4e949c00-31c2-11ea-93a0-46a590e4ff05.png)

**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:**

**Comment by KochiyaOcean** [comment]
dup #2256
发 issue 以前请记得检查最近有没有重复 issue……
