### ISSUE TITLE
分辨率设置导致程序变成小方框

### ISSUE THREAD

**Issue by kagaraw** [poooi/poi#2261]
**poi 版本 / poi version:**10.4.0

**操作系统 / OS:**win10 64位
Windows 10 用户请说明具体的发行版本号1909
**你遇到了什么样的问题 / The problem you've met:**
设置分辨率为0后程序变成小方框，卸载重装也无效
![2020-01-09 222742](https://user-images.githubusercontent.com/59696739/72077420-33e13500-3332-11ea-810e-85f32a84921d.png)

**Comment by KochiyaOcean** [comment]
@kagaraw 右键托盘图标 -> 显示 -> 重置布局
