### ISSUE TITLE
球球你们能不能帮我或者至少告诉我一下能不能缩短血条

### ISSUE THREAD

**Issue by pougu** [poooi/poi#2263]
**poi 版本 / poi version:** 
10.5

**操作系统 / OS:**
win7

**插件名和版本 / Plugin name & version:**

**功能的详细描述 / Details on the feature:**
![image](https://user-images.githubusercontent.com/7188315/72228088-7fb80680-35de-11ea-8896-8de353cdbcae.png)
![image](https://user-images.githubusercontent.com/7188315/72228108-afffa500-35de-11ea-8f7e-713f4f2a1801.png)

在概览这边靠左边有一条缩略显示各舰娘血条及士气值的  本来在10.3版本都因为血条不会那么长能显示出来后面的士气值 但是升级到10.4以后因为我屏幕比较窄 后面的士气值因为血条太长都显示不出来了 求求你们帮帮我 有什么办法不让血条那么长 或者能让后面的士气显示出来 

逼死强迫症的我了

**Comment by taroxd** [comment]
可以解锁面板，用满右边的宽度（截图仅为示例，没有在意美观性）
![图片](https://user-images.githubusercontent.com/6070540/72229960-4cc93f00-35ed-11ea-8120-7e4b89ea4f5d.png)

**Comment by pougu** [comment]
> 可以解锁面板，用满右边的宽度（截图仅为示例，没有在意美观性）
> ![图片](https://user-images.githubusercontent.com/6070540/72229960-4cc93f00-35ed-11ea-8120-7e4b89ea4f5d.png)

这个方法确实稍微修正了一下 我现在发觉问题出在 
![image](https://user-images.githubusercontent.com/7188315/72237039-105d0980-3614-11ea-9249-6a17841218ae.png)
这边的三个栏目的宽度是锁死无法改变的 请问有什么办法改变？

**Comment by KochiyaOcean** [comment]
可以设置游戏分辨率啊……
