### ISSUE TITLE
拯救一下弱智用户，编成日记怎么才能导出导入啊！！

### ISSUE THREAD

**Issue by yubanmeixiao** [poooi/poi#2264]
**poi 版本 / poi version:10.4.0

**操作系统 / OS:WIN10，专业，1909

**插件名和版本 / Plugin name & version:编成日记 5.0.1

**你遇到了什么样的问题 / The problem you've met:
1：编程日志的总体无法导出，也就是左边加号按钮下面第三个导出记录文件，无法导出
2：单一的编成记录（比如专门保存的打5-5的设置），导出的代码选项有poi和第三方，其中poi的代码找不到导入到poi里的方法（也就是poi的编程日志似乎没有导入编成代码的选项）

**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:**

**Comment by yubanmeixiao** [comment]
更新到5.0.4之后，已经可以导出了，但是代码还是无法导入- -如果不能导入的话，为什么会有POI代码和第三方代码的区别

**Comment by KochiyaOcean** [comment]
自己导出的一般可以导入，第三方的话估计是第三方改了不兼容格式导致无法转换。如果是这样的话目前没有去兼容新版格式的打算

**Comment by yubanmeixiao** [comment]
不是，指的是编成日记里，有【导出】、【编辑】和【删除记录】三个选项，然后点导出的话，代码类型有【poi】和【第三方】，其中第三方是可以把代码复制然后在呼叫舰队里使用的，但是poi的代码，在poi里反而找不到导入的方法

**Comment by yubanmeixiao** [comment]
![7MB5A}8 YX3U@GI2~2~TUAD](https://user-images.githubusercontent.com/59812878/72250142-e1578f80-3635-11ea-9bb6-82329f633b69.png)
![5~OMCGZ@OR%{M{}%)7$V855](https://user-images.githubusercontent.com/59812878/72250144-e288bc80-3635-11ea-821f-cd2c0b79738b.png)
就是这个

**Comment by KochiyaOcean** [comment]
加号菜单里面导出成文件然后导入啊……剪切板保存到文本文件也是可以的

**Comment by yubanmeixiao** [comment]
> 加号菜单里面导出成文件然后引入啊……剪切板保存到文本文件也是可以的

我指的是这个导出里面的代码要怎么导入到编成日记里，以前有的，现在没有了

**Comment by yubanmeixiao** [comment]
> 加号菜单里面导出成文件然后引入啊……剪切板保存到文本文件也是可以的

还是说现在无法用代码直接导入，只能复制到文本文档里，然后改名成json导入？

**Comment by KochiyaOcean** [comment]
没有代码直接导入的功能了

**Comment by yubanmeixiao** [comment]
> 没有代码直接导入的功能了

好吧orz，其实那个功能挺好用的……
