### ISSUE TITLE
poi面板異常

### ISSUE THREAD

**Issue by kentkuo527** [poooi/poi#2267]
**poi 版本 / poi version:**
10.5
**操作系统 / OS:**
win10 版本1803

**插件名和版本 / Plugin name & version:**

**你遇到了什么样的问题 / The problem you've met:**
poi開啟之後設定面板沒有反應 也沒辦法設定
![QQ截图20200113134050](https://user-images.githubusercontent.com/59818008/72236296-3339ee80-3611-11ea-9db6-d89d4f91aed0.png)

**Comment by KochiyaOcean** [comment]
更新 10.5.1
