### ISSUE TITLE
改Cookies直连，更新poi以后出现地域错误

### ISSUE THREAD

**Issue by Vader1977** [poooi/poi#2268]
**poi 版本 / poi version:** 
10.5.1
**操作系统 / OS:**
Win10 64bit 版本1709 内部版本16299.431

**插件名和版本 / Plugin name & version:**

**你遇到了什么样的问题 / The problem you've met:**
装了10.5.1以后，重启poi，主页设定的是游戏页面（http://www.dmm.com/netgame/social/-/gadgets/=/app_id=854854/）
poi的“设置DMM地区Cookie”是开启的（关了也试过，不行）， 打开游戏地址，出现地域错误。
清cookies，打开dmm主页，登陆账号，登陆完直接显示地域错误。

挂日本VPN，成功从dmm主页登陆账号，打开Webview控制台，输入document.cookie='ckcy=1;expires=Thu, 16-Jan-2020 00:00:00 GMT;path=/netgame;domain=.dmm.com'
（除这个外还试了英文wiki的  expires=new Date(+new Date()+31536e6).toUTCString()
document.cookie=`ckcy=1;expires=${expires};path=/netgame;domain=.dmm.com`），回车

输入游戏主页，能打开。
关掉VPN，还是能玩，但一刷新页面，就会出现地域错误。
重新挂vpn登录的话，游戏内的设置（其实也就音量都会回到默认）
似乎Cookies

**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:**

![TIM20200113103736](https://user-images.githubusercontent.com/59823509/72245509-0249c180-35f1-11ea-8f74-ea440882b2d8.png)
![TIM20200113105240](https://user-images.githubusercontent.com/59823509/72246385-de877b00-35f2-11ea-9fcd-f5fd25b9870c.png)

**Comment by HCui91** [comment]
升级10.5.1，同样问题，系统 MacOS Catalina 10.15.2。
目前退回10.3.0 Cookies 直连工作正常。

**Comment by Vader1977** [comment]
按照微博上的教程降级到10.3.0，打开登陆直接就进游戏了。看来确实是版本的问题。航海日志筛选器的问题也解决了。

**Comment by slui** [comment]
降級到10.3.0vpn直連還是出現地區問題.

**Comment by aprilies** [comment]
10.5.1一样的问题，设置地区cookie功能无效，不得不TimeMachine退回10.3

**Comment by KochiyaOcean** [comment]
@aprilies 官方网站可以下载历史版本的不至于 timemachine 吧……

**Comment by BTmanMk2** [comment]
build d7342688 还是地域错误

**Comment by KochiyaOcean** [comment]
@BTmanMk2 手动访问舰娘页面也会么
