### ISSUE TITLE
艦隊面板的火力與對潛值未加入星數補正

### ISSUE THREAD

**Issue by rangerk90** [poooi/poi#2271]
**poi 版本 / poi version:**
10.5.1
**操作系统 / OS:**
Windows 10.1909.18363.592

**插件名和版本 / Plugin name & version:**
1.艦隊面板
2.易及遠征 擴充套件 版本1.7.1

**你遇到了什么样的问题 / The problem you've met:**
艦隊介面的火力、對潛值未加入星數補正

**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:**
![未命名](https://user-images.githubusercontent.com/60051976/72673206-18003080-3aa2-11ea-98e0-8eed8b50f001.png)

以這狀況來說
滿潮面板火力確實是72沒錯，但C砲星數加算後會超過72
而下方POI的火力值顯示72也未加入星數補正

另外易及遠征這個擴展程式在月間遠征部分也未加入星數補正
這會影響到月間遠征的配裝(像是43 B4兩個遠征)

請問這部分有解嗎?
還是要等版本修正呢?

**Comment by KochiyaOcean** [comment]
@rangerk90 因为目前条件不明确而且很复杂，所以短期内不考虑实现
