### ISSUE TITLE
界面设置是否能提供一个类别不显示游戏画面

### ISSUE THREAD

**Issue by zhailingzy** [poooi/poi#2275]
**poi 版本 / poi version:**

**操作系统 / OS:**

**插件名和版本 / Plugin name & version:**

**功能的详细描述 / Details on the feature:**
现在有分离式的mode，但是希望更进一步自定义显示哪部分。
需求是使用74式为主但是通过代理的方式将数据过到poi，因此poi的游戏界面没用，但是也关不掉

**Comment by KochiyaOcean** [comment]
@zhailingzy 分辨率设置为 0

**Comment by zhailingzy** [comment]
> 
> 
> @zhailingzy 分辨率设置为 0

但是内存什么的还是占用的吧……
不过也算是个解决方法

**Comment by KagamiChan** [comment]
记得你之前问过如何搭配 74eo 来使用

poi 有中继模式支持这种用法，这样子的话是不会显示游戏内容的，占用的内存也会变小

**Comment by zhailingzy** [comment]
> 
> 
> 记得你之前问过如何搭配 74eo 来使用
> 
> poi 有中继模式支持这种用法，这样子的话是不会显示游戏内容的，占用的内存也会变小

就是不载入h5只是最初的那个网页是吧
