### ISSUE TITLE
页面任务显示错误

### ISSUE THREAD

**Issue by zhailingzy** [poooi/poi#2276]
**poi 版本 / poi version:10.5.1

**操作系统 / OS:win 10 1903 18362.592

**插件名和版本 / Plugin name & version:**

**你遇到了什么样的问题 / The problem you've met:
如图，也许是把两个开发任务统计到一起了 ？
![image](https://user-images.githubusercontent.com/14784500/73327862-7e4f3500-4292-11ea-9f67-9a48a172b7f6.png)

**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:**

**Comment by KagamiChan** [comment]
本来就是统计到一起的
你在开发一个，在任务列表里面就显示成 50% 了
