### ISSUE TITLE
Accidentally set game pixel to 1 and can't set default even after reinstall

### ISSUE THREAD

**Issue by XPrinzEugen** [poooi/poi#2277]
Is there anyway to make it default? Because it's so tiny that i cannot see anything only can open developer tools

**Comment by KagamiChan** [comment]
Are you using Windows? On Windows you may use the tray menu to reset the resolution.

![image](https://user-images.githubusercontent.com/3816900/73363649-217c6a80-42e4-11ea-895f-6733256d37a7.png)
