### ISSUE TITLE
Socks5 proxy does not seem to work/missing feature?

### ISSUE THREAD

**Issue by JasperTecHK** [poooi/poi#2278]
**poi 版本 / poi version:**
10.5.1
**操作系统 / OS:**
Win10 (1909/18363.592) (Though this also occurs in 1809, so I don't think it's relevent)

**插件名和版本 / Plugin name & version:**

**你遇到了什么样的问题 / The problem you've met:**
Socks5 proxy does not want to connect. I have my own proxy server running, and testing with my android phone, I am able to connect and browse on the proxy. On the Socks5 proxy tab though, it drops connection. Using wireguard to the same server is fine, so I know for a fact that it is the Socks5 proxy that is faulty. I believe it is due to the server having a password on it, which the browser does not seem to support.
**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:**
Create a shadowsocks 5 server with a password. then try connecting to it.

**Comment by JasperTecHK** [comment]
Wait a minute. Just read a different thread. Shadowsocks and socks5 is different? I fyes, I'm just closing this issue. otherwise, feel free to reopen it.

**Comment by KagamiChan** [comment]
@JasperTecHK Shadowsocks and socks5 are different. Some Shadowsocks client could provide a socks5 proxy, you need to use a such client.

**Comment by JasperTecHK** [comment]
Quick Nekros, Can we not connect using Socks5 if it has a username+password? This time i properly set up a socks5 proxy, verified using Kcanotify becuase of the ddos preventing international access.

**Comment by KagamiChan** [comment]
technically it is possible. But I'd like to understand why do you have a proxy with username/password. If you expose it to the Internet, it will be easy to be detected and attacked. If you use it locally, you may not need an auth

**Comment by JasperTecHK** [comment]
For the first point: Why not? Is there any disadvantage to not having one?
For the second: It's not local. That's the point, because they are currently banning international IP's I made my proxy off AWS in Kyoto. Thus, my proxy allows me to play without using softether or other vpn solutions.

**Comment by KagamiChan** [comment]
To explain, I understand your reason for using a proxy, but I don't quite recommend using socks with password in the Internet. Socks traffic is not encrypted and easy to compromise.

We added support for socks without auth because we do setup some local socks proxies with Shadowsocks client. But adding password support would be a very low priority item for the reason above.

**Comment by JasperTecHK** [comment]
I see, so user+passwd would most likely never be added. And yeah, Socks isn't encrypted, which is why I chose to use that instead of OpenVPN or Wireguard, since that would add additional packets and with the low internet bandwidth I have here, i would have low speeds with encryption.
