### ISSUE TITLE
輔助工具介面跟遊戲畫面重疊

### ISSUE THREAD

**Issue by ian920911313** [poooi/poi#2279]
-->如題

**poi 版本 / poi version:**
v.10.5.1
**操作系统 / OS:**
windows 10
![poi 2020_02_12 上午 02_17_22](https://user-images.githubusercontent.com/43114505/74266080-a59c0c80-4d3e-11ea-9375-77a52a7ef4c1.png)
**你遇到了什么样的问题 / The problem you've met:**
如題

**Comment by KagamiChan** [comment]
请问你的荧幕分辨率是？

**Comment by ian920911313** [comment]
60hz


かがみ <notifications@github.com> 於 2020年2月12日 週三 上午2:27寫道：

**Comment by KochiyaOcean** [comment]
@ian920911313 台语讲应该是解析率

**Comment by KochiyaOcean** [comment]
@ian920911313 如果窗口不能拖大，试试看左上菜单的poi-重置布局

**Comment by ian920911313** [comment]
處理好了!謝謝你!


東風谷オーシャン <notifications@github.com> 於 2020年2月12日 週三 下午9:11寫道：
