### ISSUE TITLE
Win10中任务栏会出现两个图标

### ISSUE THREAD

**Issue by sktfree** [poooi/poi#228]
windows10，poi运行后右键固定到任务栏时会出现两个图标
![qq 20150810083306](https://cloud.githubusercontent.com/assets/13722982/9157709/a35cec62-3f3a-11e5-9fe2-acb44587def1.png)

**Comment by magicae** [comment]
都赖微软，打他

**Comment by potaty** [comment]
哈哈哈哈好可爱哦
