### ISSUE TITLE
希望能增加一个树莓派版本

### ISSUE THREAD

**Issue by MizuharaNagisa** [poooi/poi#2280]
**poi 版本 / poi version:**

**操作系统 / OS:**
raspbian 10(buster)

**功能的详细描述 / Details on the feature:**
希望能有32位的deb安装包（特指armhf），当然后期也希望能增加对arm64的支持

**Comment by KochiyaOcean** [comment]
@MizuharaNagisa 可以自己编译，参照 readme

**Comment by xys20071111** [comment]
现在树莓派能带动舰C了吗？
