### ISSUE TITLE
 Do not load after starting session :'c

### ISSUE THREAD

**Issue by KuuHaaKuu** [poooi/poi#2282]
**poi 版本 / poi version:*10.5.1*

**操作系统 / OS:*Windows 10 1909 (compilation 18363.693)*

**插件名和版本 / Plugin name & version:**

**你遇到了什么样的问题 / The problem you've met:* After entering my data to start the game the game does not load, the screen goes blank and at the bottom the text "Wait for for response ..." was working fine two days ago but then just did not load. Do not make any software changes or installation of any kind. Try reinstalling and even format my pc and still nothing please help me :c This is the Developer Tools
![image](https://user-images.githubusercontent.com/46344220/75511661-37ee1280-59c5-11ea-80d3-32354524521a.png)

And the Developer Tools of WebView
![image](https://user-images.githubusercontent.com/46344220/75512085-ad0e1780-59c6-11ea-93c1-1df4e046ac4c.png)

*

**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:* I have no idea since it was working very well until two days ago :'c*

**Comment by KochiyaOcean** [comment]
@KuuHaaKuu DMM has changed its strategy to detect oversea users. You may need to get a VPN to access to DMM sites

**Comment by KuuHaaKuu** [comment]
@KochiyaOcean  Which one would you recommend?
