### ISSUE TITLE
Fluctuating CPU usage on KC idle? HW Acceleration related?

### ISSUE THREAD

**Issue by DatHoax** [poooi/poi#2284]
**poi version:**
Version 10.5.1 Stable - Build A088ED13

**OS:**
Windows 7

**The problem you've met and how to reproduce, or any information that might be related:**
I hope it's okay to post this here, I tried digging through older tickets but I didn't find much and I don't speak Chinese. CPU is a i5-4670k.
So CPU usage over all of the Poi processes fluctuates between 25% and 40% when I have the game being idle, it goes even higher when doing a sortie. I recently switched over from plain Firefox and had at most 25% to 30% there when doing sorties. This is kind of obnoxious when I'm trying to do other CPU intensive things.
I have a feeling it may be hardware acceleration related, I had to turn the option off due rendering issues with the game. The game would frequently turn into a white screen when switching screens, making me have to reload the page to solve it. This is very frustrating, especially when it happens in sorties and especially with the required VPN login now.
I didn't check the CPU usage with the hardware acceleration option enabled though, so I'm not 100% sure switching it off caused this. Hence the ticket.
I'm just wondering if it's a Poi or a Chromium issue and if there's anything I can do beside reporting it?

**Comment by KochiyaOcean** [comment]
If you disabled HW acceleration, the graphic calculation cost will be afforded by CPU, so it's recommended to enable HW acceleration if there is no compatibility issue.

**Comment by KagamiChan** [comment]
Thanks for reaching us. The idle CPU usage is expected, because on the port view there're still many kinds of animations which require calculations

For the white screen issue, given that Windows 7's support has been discontinued, the behavior on this OS is not longer guaranteed.

And we could not know about the causes as devs are using Windows 10 now.
