### ISSUE TITLE
Can't login without use of VPN

### ISSUE THREAD

**Issue by smithysteadfast** [poooi/poi#2286]
**poi 版本 / poi version: 10.5.1

**操作系统 / OS: Windows 10 10.0.18362 Build Version 18362

**插件名和版本 / Plugin name & version: Software itself

**你遇到了什么样的问题 / The problem you've met: Can't login without using a VPN, outside of Japan.

**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related: Simply start the game up with an IP Address outside of Japan

**Comment by KagamiChan** [comment]
Since Feb. 2020, there's a new region check, previous bypassing tricks might fail. see #2281
