### ISSUE TITLE
建议将入渠和建造显示弄小点，首页加上舰队血量显示

### ISSUE THREAD

**Issue by suikakz** [poooi/poi#229]
每次都要点来点去总感觉不是很方便。。。

**Comment by mehwww** [comment]
+1 建议把资源显示栏改成可折叠的，概览里加上基本的舰队信息，这样刷闪的时候就不用点来点去的了

**Comment by KochiyaOcean** [comment]
![image](https://cloud.githubusercontent.com/assets/8194131/9177725/7da44d90-3fc5-11e5-8923-4214ef4ee54f.png)
还在测试中，诸君感觉如何

**Comment by magicae** [comment]
4.0.0的概览界面基本定为上面这个了

**Comment by PHELiOX** [comment]
入渠建造竖过来的空间利用率。。。＝。＝
popover确实不好看。。需要透明度
舰队编号。。呃。。

**Comment by KochiyaOcean** [comment]
横向长条在布局上相当麻烦（尤其是竖屏
因为空间不是很够就不显示装备详细啦！
透明度什么的交给主题不管了

**Comment by PHELiOX** [comment]
失误
横条既然宽度伸缩。。不知道有什么麻烦 ＝。＝
另外地方并不会不够。。那么大。。
<img width="232" alt="2015-08-11 02 35 13" src="https://cloud.githubusercontent.com/assets/1183568/9179998/983efe22-3fd2-11e5-8451-67e8b64b3c41.png">
资源看着很挤，应该在调一下
罗马数字并不存在看不懂的问题。。还有天国的倒计时 ＝。＝

**Comment by KochiyaOcean** [comment]
就是感觉很难调整出好看的布局啦在纵向的情况下
果然还是要调小字体么……我明天去改一下……
不是看不懂的问题而是个人的恶趣味（。
倒计时感觉功能重复就不加了……

**Comment by PHELiOX** [comment]
资源的问题并不是调小字体，而是留出间距

**Comment by KochiyaOcean** [comment]
总之明天改吧=。=

**Comment by aajiangzz** [comment]
这个界面好多了，要是入渠和建造也可以不用切换一起显示出连就更好了

**Comment by KochiyaOcean** [comment]
那就没空间噜……

**Comment by yumisea** [comment]
这个界面看着很棒。至于资源显得拥挤的问题，其实我觉得再把资源放在右边并不是很实用。油弹钢铝桶资材都是可以在原游戏界面直接看到的，切换到工、入渠界面也可以看到，需要浏览器替代的场合也就是出击和看图鉴的时候——这些场合基本不需要去了解有多少资源吧。实际上资源界面只需要显示改修资材就好了，或者干脆像KCV4.0一样，留几个框让玩家自己选择显示什么资源

**Comment by aajiangzz** [comment]
我也觉得资源没必要显示，螺丝放到装备数右边的空区就好，省出来的资源区可以把建造或者入渠放过去，这样就能不用切换就可以看到所有关键信息了。真的就想看资源的话，可以把资源和建造界面设成切换而不是建造和入渠切换。因为建造和入渠是大部分时候都需要看的而资源不是，把一个不常看的设成切换比把不常看的设成永久把常看的设成切换要好

**Comment by magicae** [comment]
建造我倒是觉得不会经常看…

**Comment by aajiangzz** [comment]
建造我经常看的，我每天建完2个去做日常看建造时间有到了的，就补一个建造,而且建造通常界面都看不到只能看这个。入渠应该没人不常看吧，把常看的单列出来，建造和资源都有人不常看的话设成切换

**Comment by KochiyaOcean** [comment]
相对的资源我也是经常看的，以及入渠和建造属于类似模块所以整合到了一起，酱。

**Comment by yukixz** [comment]
个人觉得看资源数比看建造的次数多。
而且建造完成有通知不需要看也行。

**Comment by nagatoyk** [comment]
资源我觉得可以参考kcv4.1版本 就是让用户自己选择要显示的某些比较关心的项目
做成下拉菜单来选择 会比较节省空间

**Comment by KochiyaOcean** [comment]
再怎么节省也不会节省出多一个面板的空间的（资源面板是最小的面板）
现在的目标是排版之后横向模式高度不超过 470px，而且面板的分类尽量合理

**Comment by PHELiOX** [comment]
来个kcv4.1的图呗

**Comment by ruiii** [comment]
我觉得，用户的意思是说，需求自定义概览面板。

**Comment by yumisea** [comment]
呃……其实我想说的是有些资源并不是不可替代的。比如看资源，因为在游戏里只有看图鉴和出征的时候看不到资源，其他时候抬眼看下游戏面板就可以了解，不必特意在POI浏览器里面给油弹钢铝留位置，如果要给资源留的话也是留给改修资材这种需要点进别的页面才能看到的。资源面板的位置可以相应调小甚至干脆取消让位给舰队、修理渠显示，让概览面板看上去不是那么乱。

**Comment by KochiyaOcean** [comment]
相对的建造信息也不需要常态显示。而且现在的排版已经相对合理了，在没有强烈的需求下不会重新修改面板（因为懒

**Comment by KochiyaOcean** [comment]
自定义面板作为隐藏功能其实一直有，不过实在懒得再写一套另外的了……

**Comment by aajiangzz** [comment]
建造信息只有进入工厂才能看到，相反资源信息一直可以从游戏主界面看到除了螺丝根本用不到看poi，我的理解这种辅助工具作用就是把游戏里看不到的东西显示出来的

**Comment by aajiangzz** [comment]
另外这个界面把升级剩余经验直接显示出来多好，新版怎么隐藏了还要鼠标移上去才显示，肝船时挨个看好麻烦

**Comment by KochiyaOcean** [comment]
因为不够放而且会导致密集恐惧

**Comment by magicae** [comment]
新面板实装了 这个issue close
