### ISSUE TITLE
希望新增功能

### ISSUE THREAD

**Issue by gn01102368** [poooi/poi#2290]
**poi 版本 / poi version: 10.5.1**

**操作系统 / OS:win 7**

希望能新增面板自動切換開關的功能,以及艦隊面板顯示位置太靠左邊
👉  https://opencollective.com/poi/donate -->

**Comment by KochiyaOcean** [comment]
![image](https://user-images.githubusercontent.com/8194131/80979488-5d364b80-8e62-11ea-8baa-b7478bf24eb4.png)
应该是已经有这个功能了
显示位置太左边指的是？希望有截图之类说明
