### ISSUE TITLE
頻繁貓

### ISSUE THREAD

**Issue by Noviynna** [poooi/poi#2293]
**poi 版本 / poi version:**
10.3.0
試過10.5.0,問題一樣發生

**操作系统 / OS:**
Mac OS Catalina 10.15.4

**插件名和版本 / Plugin name & version:**

**你遇到了什么样的问题 / The problem you've met:**
高頻率的貓, 尤其是在任務界面的時候

**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:**

<img width="1440" alt="Screen Shot 2020-05-08 at 23 23 31" src="https://user-images.githubusercontent.com/65058124/81463913-f2974f80-9182-11ea-9b23-5cc3d22f5550.png">

**Comment by KochiyaOcean** [comment]
@Noviynna 缺乏详细信息，比如猫的时候是否显示错误代码？
