### ISSUE TITLE
10.6.0-beta.1完全黑屏

### ISSUE THREAD

**Issue by fanofpal** [poooi/poi#2295]
**poi 版本 / poi version:10.6.0-beta.1

**操作系统 / OS:win10

**插件名和版本 / Plugin name & version:**

**你遇到了什么样的问题 / The problem you've met:安装10.6.1之后，打开程序完全黑屏，程序界面都没加载出来

![image](https://user-images.githubusercontent.com/19284371/81589057-b31f6c00-93eb-11ea-8adc-7fa535fd9c8f.png)

**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:**

**Comment by KochiyaOcean** [comment]
应该已经修复了，可以去 https://ci.appveyor.com/project/KochiyaOcean/poi/build/artifacts 试试看每夜版

**Comment by fanofpal** [comment]
> 应该已经修复了，可以去 https://ci.appveyor.com/project/KochiyaOcean/poi/build/artifacts 试试看每夜版

啊可以了，感谢！
