### ISSUE TITLE
游戏刷新了某些数据后截图会产生错误

### ISSUE THREAD

**Issue by Jimmysyou** [poooi/poi#2297]
**poi 版本 / poi version: 10.5.1**

问题：
在游戏数据进行某些刷新之后，截到的第一张图会是裂图

如下例，新掉落的黑卡出来时还是正常截图，闪一下后截的第一张图就会裂的
![image](https://user-images.githubusercontent.com/46279547/83430767-cf517e80-a468-11ea-8c93-04cbfa573793.png)
 要收集彩底无介绍立绘时就很麻烦

截图设置：
![image](https://user-images.githubusercontent.com/46279547/83430541-6a962400-a468-11ea-93c7-a7aea2d3efea.png)

问题再现方法：
战斗结束→经验结算→点击→有新舰娘→卡片旋转飞出来→**闪一下**【这里之后第一张截图必裂】→出现立绘→下面介绍栏升起来
打开任务、item（道具栏、道具屋、家具屋）有概率第一张出来的是裂图，进入游戏后第一次打开这些页面时截图出错的几率更大
![image](https://user-images.githubusercontent.com/46279547/83432545-a088d780-a46b-11ea-8f5b-d08206659456.png)

**Comment by KochiyaOcean** [comment]
把通过 canvas 截图关掉

**Comment by Jimmysyou** [comment]
> 把通过 canvas 截图关掉

关掉截出来的不就变成设置的游戏显示分辨率，而不是原始分辨率了吗

**Comment by KochiyaOcean** [comment]
两种方法原理不一样， canvas 截取就是会有各种玄学问题的，没有什么好的解决办法

**Comment by Jimmysyou** [comment]
> 两种方法原理不一样， canvas 截取就是会有各种玄学问题的，没有什么好的解决办法

那只能和之前一样，快速截两张图了
十分感谢
