### ISSUE TITLE
全屏時畫面ｐｏｉ無法貼齊顯示器邊框

### ISSUE THREAD

**Issue by andy9005** [poooi/poi#2299]
**poi 版本 / poi version:10.6.0

**操作系统 / OS: windows10 1903 OS組建 18362.900

**你遇到了什么样的问题 / The problem you've met:全屏時無法完整貼齊畫面 會出現白色方框

**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:
![圖片 3](https://user-images.githubusercontent.com/66863533/84562932-e5c5d700-ad92-11ea-9c95-05245e3b25fa.png)

![圖片 2](https://user-images.githubusercontent.com/66863533/84562721-b1055000-ad91-11ea-8b2f-6cc7926e76f9.png)

**Comment by KochiyaOcean** [comment]
是否开启了兼容模式

**Comment by andy9005** [comment]
啊 是的 關掉就好了 謝謝
