### ISSUE TITLE
控制栏移到游戏界面之上

### ISSUE THREAD

**Issue by linzhibinghan** [poooi/poi#230]
1.我点了选择驱逐舰和轻巡，过滤掉远征中的，然后再点排序,下面任何变化也没啊，还是乱乱的,各种各样的船在那里。
2.能否提供猫后自动刷新功能的切换，只有出猫的时候F5 1次，其他时候报错就不F5，必须固定个面板也行，以前KCV用习惯了某个防猫插件,感觉蛮依赖的。
3.shadowsocks代理时能否提供网络超时时，自动保存一遍当前代理配置达成重新建立一个新连接防止当前连接错误直接就卡那的功能，这就好比用shadowsocks客户端时有时候超时弹ss_polipo.exe错误，必须点一遍代理重新开启一样。
4.防猫重试次数最大可以填写多少次，是否有范围。我填999999999，然后发现貌似就重试了2-3次，然后显示网络连接超时，界面就卡那了，还好我机智的点了一下保存当前代理配置让他新建续连了，不然差点以为只能F5。

问题大概就这些，谢谢了，排序问题就是用的最新版本，WIN64，上面怎么点，下面感觉都是不动的。

**Comment by linzhibinghan** [comment]
....突然发现过滤又OK了,刚才重启了下机器,那么排序没问题,提个面板问题,就是游戏界面下面那个横条,能否考虑弄个位置可调整,比如弄到上面去,我手滑党,总感觉容易点错的样子.
再有是否浏览那个确定和刷新按钮的下面考虑再加上一个后退的按钮,有时候经常会手贱点错的不排除。

**Comment by Wafer-Li** [comment]
这个可以考虑。
舰娘最常用的出击按钮、补给按钮、废除按钮、建造按钮均在画面较为下方的位置，
而上方的常用按钮大概只有母港的图标和任务，其余按钮的使用频率均没有上述的高。

不过就是不知道移至上方后美观性如何。

**Comment by PHELiOX** [comment]
控制栏离常用操作位置越近越好，考虑到纵版布局还是放在下面

**Comment by Wafer-Li** [comment]
@PHELiOX 
这点我不同意，正是由于控制栏离常用操作位置过近，导致经常有误操作的出现。
有时候想点解体确定按钮却把声音给关了，或者截了一张图下来

**Comment by PHELiOX** [comment]
@Wafer-Li 那样的话你要考虑的不是工具条摆在哪，而是那几个按钮怎么摆。。

**Comment by alvin-777** [comment]
我倒是觉得截图按钮应该放在角落（甚至做得比别的按钮大），这样如果突然想截图的话能够立刻找到，不至于按错或者错过时机
另外一些不常用的按钮可以做成overlay的形式，点一个“more”的按钮再显示，不用总是排在下面

**Comment by ruiii** [comment]
不放在右下就可以，收发远征补给会按到（个人手滑

**Comment by PHELiOX** [comment]
那就放到左下角吧
