### ISSUE TITLE
安裝程式

### ISSUE THREAD

**Issue by ymh1246** [poooi/poi#2300]
**poi 版本 / poi version:10.6.0**

**操作系统 / OS:Win10-64bits**

**插件名和版本 / Plugin name & version:18363.900&1909**

**你遇到了什么样的问题 / The problem you've met:安裝到一半上面顯示已停止安裝之後讀條就卡在那個地方10分鐘以上**

**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:**

**Comment by KochiyaOcean** [comment]
目前不清楚原因，如果一直不成功可以使用压缩包版
![image](https://user-images.githubusercontent.com/8194131/84564810-96d26e80-ad9f-11ea-979e-1034d9ed4649.png)

**Comment by ymh1246** [comment]
問題已解決，謝謝您~
