### ISSUE TITLE
关于窗口分辨率无法固定的问题

### ISSUE THREAD

**Issue by chenyx94** [poooi/poi#2302]
**poi 版本 / poi version: 10.6.0**

**操作系统 / OS: Win10**

**插件名和版本 / Plugin name & version: 18363**

**你遇到了什么样的问题 / The problem you've met: 在布局设置中选择分窗口（即游戏窗口和信息窗口分开的那个设置，第一排第5个）时，游戏窗口分辨率会不断扩大，而舰队信息的窗口不会放大。**

**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related: 显示设置中选择第一排第5个的分窗口的那个选项即能出现该问题，表现为游戏窗口不断变大，显示设置中的游戏分辨率百分比也逐px变大，点击“设置固定分辨率”按钮后能够变回100%但是随即变大**

[链接：https://pan.baidu.com/s/1jGpqOrhBFxlZGWuuy20JLQ 
提取码：k03w](url)
抱歉刚刚上传失败，包括gif图

这个问题的解法我好像是没有搜到，不清楚是确实别人没遇到这个问题还是关键词不对。wiki的常见问题里也没有这个情况。
谢谢！

**Comment by KochiyaOcean** [comment]
和上游 bug 相关，会考虑 workaround

**Comment by chenyx94** [comment]
> 
> 
> 和[上游 bug](https://github.com/electron/electron/issues/22440#issuecomment-643172443) 相关，会考虑 workaround

好的，谢谢！

**Comment by KochiyaOcean** [comment]
大概是修复了，可以去试试看每夜版 https://ci.appveyor.com/project/KochiyaOcean/poi
