### ISSUE TITLE
Poi浏览器界面显示有问题，字体会看不清

### ISSUE THREAD

**Issue by LinAAAAA** [poooi/poi#2303]
**poi 版本 / poi version:**poi 10.6.0

**操作系统 / OS:** Win10 1903

**你遇到了什么样的问题 / The problem you've met:**Poi浏览器界面显示问题

**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:**

<img width="900" alt="微信截图_20200625151228" src="https://user-images.githubusercontent.com/21039781/85674337-5a840400-b6f7-11ea-8437-3f32ddf3389c.png">
<img width="1920" alt="微信截图_20200625151836" src="https://user-images.githubusercontent.com/21039781/85674415-68398980-b6f7-11ea-982b-b83df52e32fe.png">
<img width="1920" alt="微信截图_20200625151850" src="https://user-images.githubusercontent.com/21039781/85674434-6b347a00-b6f7-11ea-90ba-240eeaf90c11.png">
<img width="1920" alt="微信截图_20200625151858" src="https://user-images.githubusercontent.com/21039781/85674445-6cfe3d80-b6f7-11ea-8701-9b7fff5d7dbb.png">

**Comment by KochiyaOcean** [comment]
怀疑是显卡驱动问题，可以试试看更新驱动或者在设置里禁用硬件加速
