### ISSUE TITLE
为poi添加了scoop的安装方式

### ISSUE THREAD

**Issue by Darkatse** [poooi/poi#2304]
**poi 版本 / poi version:**
latest  
**操作系统 / OS:**
win 7/8/10  

为poi添加了win下包管理器scoop的安装方式  
[Scoop-KanColle](https://github.com/Darkatse/Scoop-KanColle)

scoop类似于chocolatey，但是比起chocolatey更干净、更简洁，而且不需要UAC权限

安装scoop后使用方法：  
`scoop bucket add kancolle https://github.com/Darkatse/Scoop-KanColle.git  `  
`scoop install poi`（便携版），或者
`scoop install poi-np` （安装版）

**Comment by gnattu** [comment]
已加入readme: cf020ab
非常感谢
