### ISSUE TITLE
易及远征的信息更新一下

### ISSUE THREAD

**Issue by deepsea666** [poooi/poi#2307]
**poi 版本 / poi version:**
10.6
**操作系统 / OS:**
win10

**插件名和版本 / Plugin name & version:**
易及远征1.7.2

**功能的详细描述 / Details on the feature:**

新远征A5A6B5E1出来也有一段时间了，插件里还是信息不足

**Comment by Javran** [comment]
有PR的话欢迎,个人不愿意浪费时间支持没有跑的价值的远征...

**Comment by Javran** [comment]
closing as fulfilled by https://github.com/poooi/poi-plugin-ezexped/pull/33.
