### ISSUE TITLE
卡在工廠

### ISSUE THREAD

**Issue by mikey4011** [poooi/poi#2308]
**poi 版本 / poi version:**

**操作系统 / OS:**

**插件名和版本 / Plugin name & version:**

**你遇到了什么样的问题 / The problem you've met:**

**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:**

**Comment by mikey4011** [comment]
![2020-7-11T1 0 23](https://user-images.githubusercontent.com/68122262/87179901-18230f80-c312-11ea-8c1a-239d6c8f96b3.png)

**Comment by KagamiChan** [comment]
如果你使用网络加速服务来连接游戏  ，并且无法载入游戏，请先与网络加速服务客服联系。

**Comment by mikey4011** [comment]
我可以载入游戏 只有工廠進不了

**Comment by KagamiChan** [comment]
@mikey4011 清空一下快取看看

**Comment by mikey4011** [comment]
也不行

**Comment by KagamiChan** [comment]
建议你点击这里的清空快取之后
![image](https://user-images.githubusercontent.com/3816900/87182574-05f7a000-c317-11ea-82ac-19dc2601ba57.png)
退出 poi 再重新进入，然后如果还黑的话再稍微等一下

**Comment by mikey4011** [comment]
还黑QQ
