### ISSUE TITLE
关于装备信息的改良意见

### ISSUE THREAD

**Issue by vessalius90** [poooi/poi#231]
在此先感谢制作组的热情和付出。非常感谢你们对于广大提督做出的贡献。

以下是我对此软件的改良意见，希望并不会给你们带来困扰。由于新人提督并不熟悉装备，所以在可行的范围内，希望能有所改良。

1）装备信息显示：希望加入属性，以帮助分辨优劣
![001](https://cloud.githubusercontent.com/assets/12453817/9189784/9eef38a2-3fbb-11e5-913b-e8e342600726.png)

2） 舰队装备显示
![002](https://cloud.githubusercontent.com/assets/12453817/9189817/2f8d5f88-3fbc-11e5-905a-672ad8f36565.png)

谢谢

**Comment by magicae** [comment]
插件部分 /cc @myzWILLmake

**Comment by PHELiOX** [comment]
显示所有属性会导致表格巨大，参见KCV鬼佬版。。需要一个其他显示方法

**Comment by aajiangzz** [comment]
用过KCV鬼佬版的表示显示属性简直就是灾难，遇上浦风炮这种属性一大堆的装备一页只能显示几个装备而且也无法比较因为同类装备分到很多不同页面去了
