### ISSUE TITLE
先制对潜不应当记入加成/OASW Indicator shall not include bonus ASW value

### ISSUE THREAD

**Issue by axmmisaka** [poooi/poi#2314]
poi 版本 / poi version:
poi nightly, commit 4d06844f

你遇到了什么样的问题 / The problem you've met:
先制对潜指示器使用了计入装备加成的先制对潜/OASW indicator used values with equipment bonus

复现 / Reproduction:
在Lv34大鹰装备两个九七931和一个村田，大鹰的面板对空将达到阈值65，但由于每架931提供+1对潜加成，大鹰不会先反；面板显示其会先反
Equip 2 *Type 97 Torpedo Bomber (931 Wings)* and one *Tenzan Model 12 (Murata Squadron)* on Lv.34 Taiyou, the indicator will show it has OASW capability while it will not
![image](https://user-images.githubusercontent.com/6500159/88550297-ffc22d00-d053-11ea-8c9e-e973eec6478b.png)

可能的解决方案 / Possible solution:
https://github.com/poooi/poi/blob/1584bf96536cd68171d99dba5b2d386186f1b10f/views/utils/oasw.es#L13
使用`ship.api_taisen[0]-装备加成`或分别计算

等我做完作业去研究一下api……

**Comment by KochiyaOcean** [comment]
装备加成是写死的只能特别判断

**Comment by axmmisaka** [comment]
api无法获取装备和舰娘的裸装对潜么？这样看来需要队对潜装备和对潜值或者队所有对潜加成打表，gg

**Comment by taroxd** [comment]
2019年8月8日現在、軽空母にボーナスのある装備*15の対潜値ボーナス分が必要対潜値の計算から除外されているので、ボーナス分を除いた値を考慮しないと先制対潜攻撃の条件を満たしていない場合がありえる。
他方、一部の艦への三式ソナー・四式ソナーの装備ボーナスは必要対潜値の計算に含まれている。

补充个信息，只有 cvl 先反是不算装备加成的

**Comment by axmmisaka** [comment]
ok，等下测试好后我把打的表发上来试试……

**Comment by KochiyaOcean** [comment]
本质上属于田氏 bug，说实话不是非常想修……

**Comment by KochiyaOcean** [comment]
https://github.com/Tibowl/KCBugTracker/issues/9 姑且加入到 KCBugTracker 里了
