### ISSUE TITLE
在WSL1中使用npm运行提示[ERROR] Another instance is running, exiting

### ISSUE THREAD

**Issue by axmmisaka** [poooi/poi#2316]
**poi 版本 / poi version:**
Commit 1f16429779a
**操作系统 / OS:**
WSL1
Linux 4.4.0-18362-Microsoft #836-Microsoft Mon May 05 16:04:00 PST 2020 x86_64 x86_64 x86_64 GNU/Linux
Ubuntu 20.04.1 LTS
宿主机Windows 10 1909 18363.959

**插件名和版本 / Plugin name & version:**

**你遇到了什么样的问题 / The problem you've met:**
`npm start`后出现
```
[ERROR] Another instance is running, exiting
```
，尽管wsl和宿主机上都没有poi实例在运行。
**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:**
导入官方的wsl1虚拟机镜像，宿主机运行Xming (版本号忘了）
安装npm和election后在wsl中执行了以下操作：
```bash
git clone https://github.com/poooi/poi
cd poi
npm install
export npm_config_platform=win32 && npm install
DISPLAY=:0 npm start
```
命令行出现：
```
misakam@tokiwadai:~/poi$ npm start

> poi@10.6.0 start /home/misakam/poi
> electron .


[WARN] Cannot get system flash plugin path
[ERROR] Another instance is running, exiting
(electron) The default value of app.allowRendererProcessReuse is deprecated, it is currently "false".  It will change to be "true" in Electron 9.  For more information please check https://github.com/electron/electron/issues/18397
```
（第一次用wsl跑这种东西）

**Comment by KagamiChan** [comment]
不确定为什么会让 Electron 认为会有多个实例。你可以先在代码里面去除单个实例的限制，然后运行

WSL 运行不在预期的支持范围内

**Comment by axmmisaka** [comment]
OK, 只是在wsl上测试方便一些，感谢回复

**Comment by axmmisaka** [comment]
更新：就像在网吧一样，重启系统有可能可以解决此问题。
