### ISSUE TITLE
航海日志正则表达式怎么写？

### ISSUE THREAD

**Issue by LBCHN** [poooi/poi#2317]
Rt，可以举个例子吗？除了写**n**匹配到了48-2（**？**）其他任何字符（比如w或者\w）都不能匹配，请问正则表达式是怎么写的？

**Comment by axmmisaka** [comment]
正则表达式是以`/`开始和结束的字符串，例如，若要搜索常规海域的123图：
```regex
/\(\d-[123]\)$/
```
具体实现见：https://github.com/poooi/plugin-Akashic-records/blob/e6cea59787f301815a696f4ac8c7bb7b83a22303/views/selectors/index.es#L56
