### ISSUE TITLE
期间限定海域的非最终boss不计入a号作战计数器

### ISSUE THREAD

**Issue by axmmisaka** [poooi/poi#2318]
又一个田氏bug\feature? /Yet another Tanaka-style bug (or feature?)

期间限定海域的boss除了最终一P不计入A号作战（至少有一些boss不计入A号作战计数器）
No boss but the one in the last phase (or at least some in events) should be included in quest completion counter for Op. A-gou (namely Bw1)

可能的解决方案（也可能不是，我懒了）：
Possible solution (or not but I'm too lazy to verify)
https://github.com/poooi/poi/blob/85e47ce0df339adf73eca3b5154b805b165269e7/views/redux/info/quests.es#L205-L207
如果出击海域>7, 那么打表特判
Get a table to handle special case if the world current sortie is in is >7

**Comment by KochiyaOcean** [comment]
没有很干净的修复方法的情况下还是选择不修……
游戏内 bug 参照 https://github.com/Tibowl/KCBugTracker/issues/27

**Comment by axmmisaka** [comment]
也就是如果没有开启下一P本P的boss还算在A号里？我去

可不可能把这里的options处理器修改成符合游戏实际的（即特判）？我觉得可能并不会让代码变得不好康（逃
https://github.com/poooi/poi/blob/85e47ce0df339adf73eca3b5154b805b165269e7/views/redux/info/quests.es#L396

**Comment by KagamiChan** [comment]
对于一个道中 boss 点，我印象中也有算进 a 号的情况，因为游戏本身也不会返回实际的计数，所以没有办法做完全的确认

如果打活动的话一般 a 号也不至于做不完，有一些偏差的影响也不会很大

**Comment by KochiyaOcean** [comment]
就是因为不想做特判所以不想修，API 上想区分还是比较难的（各 P 的 boss 点在 API 里面都是显示为 boss 点的

**Comment by axmmisaka** [comment]
这样；不知道会不会有更优雅的解决方案
（另，如果是
> 
> 
> 对于一个道中 boss 点，我印象中也有算进 a 号的情况，因为游戏本身也不会返回实际的计数，所以没有办法做完全的确认
> 
> 如果打活动的话一般 a 号也不至于做不完，有一些偏差的影响也不会很大

的话，还同时需要判断当前有没有打有血条的boss，并不一定是最终P？

**Comment by KochiyaOcean** [comment]
7-2 的 p1 boss 就是算进计数的

**Comment by axmmisaka** [comment]
嗯，我指期间限定海域
