### ISSUE TITLE
poi锁定到屏幕一侧时游戏界面不完整

### ISSUE THREAD

**Issue by Donchka** [poooi/poi#2322]
**poi 版本 / poi version:**10.6.0

**操作系统 / OS:**Windows 10 version 1909

**插件名和版本 / Plugin name & version:**

**你遇到了什么样的问题 / The problem you've met:**拖动poi到分屏模式时（比如浏览器和poi各占一半屏幕），游戏界面最右边会被遮掉一部分。在poi的显示设置中调整缩放比例后恢复正常。

**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:**
拖动poi并锁定至屏幕右侧，游戏界面被遮挡
![1](https://user-images.githubusercontent.com/22917096/89833714-820c2000-db2f-11ea-95d8-4e0aa9b5f274.PNG)
调整缩放后（比如调到95%再调回100%），再次拖动poi，游戏界面不被遮挡。
![2](https://user-images.githubusercontent.com/22917096/89833729-86d0d400-db2f-11ea-8f29-3ca011004506.PNG)

**Comment by KochiyaOcean** [comment]
没有复现……

**Comment by Donchka** [comment]
关于复现的方法，详细一些的步骤是：
1.在poi最大化状态下直接拖动并锁定，有几率直接出现异常
2.如果第一步没有出现异常现象，最大化屏幕另一侧的程序（比如浏览器）
3.切回poi，此时poi是半屏状态，拖动poi重新锁定出现异常
希望能帮到您

**Comment by KochiyaOcean** [comment]
大概就是事件处理顺序不稳定的问题了，看起来不好修……
