### ISSUE TITLE
是否有考虑过增加截图的键盘快捷键（虽然已经有了截图按钮），或者说如何自行取消功能按钮的浮窗文字说明？

### ISSUE THREAD

**Issue by georeneagle** [poooi/poi#2323]
**poi 版本 / poi version:** 10.6.0

**操作系统 / OS:** Windows 10 1903

**插件名和版本 / Plugin name & version:**

**功能的详细描述 / Details on the feature:**

目前poi已经有一个“一键截图”功能按钮，使用也很方便，只是鼠标悬停时会有浮窗文字说明：
![QQ截图20200812003149](https://user-images.githubusercontent.com/69467778/89929821-5dea3500-dc3c-11ea-9567-4e1a80d49bc0.png)
不影响截图，但是使用录屏的时候想要额外截图就会很突兀地出现在录制画面中，不知道目前poi是否有截图的键盘快捷键（可能是字幕插件的问题，使用系统截图的话游戏画面边缘会被覆盖一到两个像素宽的灰边），或者能否在之后的版本考虑新增？
当然如果可以通过修改CSS代码取消掉这个浮窗是最好的，毕竟这可能只是极少数人的需求，能自己在本地解决就不用劳烦各位了，我翻阅了以前的issue找到如下一段但可能因为版本不适用所以并没有起效
```
#poi-screenshot-button {
  display: none;
}
```
不知是否有当前可用的代码咱可以自己丰衣足食一下？
谢谢！

**Comment by lawvs** [comment]
可以试试

```css
#webview-wrapper {
  z-index: 9999;
}
```
强制让游戏画面保持在最顶层，从而遮挡掉（所有）工具栏的浮窗

**Comment by georeneagle** [comment]
尝试了一下，着实有效，但也如描述所说，太暴力了，目之所及的浮窗都被盖在了下面……

感谢建议，虽然这剂猛药不适合长期服用，用作救急应对还是没问题的@_@

**Comment by KagamiChan** [comment]
可以加一个截图快捷键，之后看一下
