### ISSUE TITLE
编成日记制空计算和POI舰队编程制空不一致

### ISSUE THREAD

**Issue by mihane-ichinose** [poooi/poi#2325]
**poi 版本 / poi version:**10.6.0 Build 1F164297

**操作系统 / OS:**Windows 10 2004 19041.388

**插件名和版本 / Plugin name & version:**编程日记 5.0.4

**你遇到了什么样的问题 / The problem you've met:**编入格子一样，熟练度一样的舰载机时，插件保存的队伍制空值和poi面板显示的制空值不一致。

**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:**
![image](https://user-images.githubusercontent.com/53740908/90149633-4a170e00-ddb7-11ea-870f-4a642cbc1a04.png)
![image](https://user-images.githubusercontent.com/53740908/90149795-80ed2400-ddb7-11ea-8b9b-08f2a9e4f8dc.png)
![image](https://user-images.githubusercontent.com/53740908/90149822-877b9b80-ddb7-11ea-8ba9-3d69acbc9ca8.png)
![image](https://user-images.githubusercontent.com/53740908/90149809-83e81480-ddb7-11ea-91b9-5590da977408.png)
如图所示，一样的舰载机配置，格子位置，熟练度，改修度。面板显示制空169+最高171，插件显示的是180，差距很大。不知道以哪个为准。

**Comment by axmmisaka** [comment]
参见
https://github.com/poooi/plugin-hensei-nikki/blob/master/utils/calc.es#L188
和
https://github.com/poooi/poi/blob/master/views/utils/game-utils.es#L220
以及
https://github.com/poooi/poi/commit/b980e1ed722e1bd64a224c74316981db481e44e9?branch=b980e1ed722e1bd64a224c74316981db481e44e9&diff=unified

编成日记的制空计算的最近一次提交在2018年1月8日（https://github.com/poooi/plugin-hensei-nikki/commit/64ab37d645824f8128ecb70e264e06d0f0d5fcb0），在这之后poi本体的制空计算进行了多次更新。

应当以poi主程序为准。

**Comment by KochiyaOcean** [comment]
编程日记重构中（还在天上
