### ISSUE TITLE
使用Canvas获得的截图是花屏

### ISSUE THREAD

**Issue by lisongyuan99** [poooi/poi#2326]
**poi 版本 / poi version:**10.6.0

**操作系统 / OS:**win10 1909

**你遇到了什么样的问题 / The problem you've met:**
使用Canvas直接获得截图有时会出现这样的图案
![2020-7-21T21 56 43](https://user-images.githubusercontent.com/42134107/90200393-3a74e500-de0a-11ea-87c7-e6e6bf4b4bd6.png)
![2020-7-31T23 36 14](https://user-images.githubusercontent.com/42134107/90200528-b5d69680-de0a-11ea-9a6a-13364ce50fa5.png)

**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:**
一般在掉落界面或者进入Boss点显示Boss的立绘第一次截图很大概率是这种

**Comment by KagamiChan** [comment]
dup of #2297
