### ISSUE TITLE
使用反馈及功能建议

### ISSUE THREAD

**Issue by yjiangcscrc** [poooi/poi#2330]
**poi 版本 / poi version:**
10.6.0

**操作系统 / OS:**
Win10 Version 2004 Build 19041.450

**功能的详细描述 / Details on the feature:**
**以下使用反馈及功能建议纯属个人反馈, 某些功能上的建议非常主观, 建议适当讨论.**

0 从上至下: 标题栏, 游戏框架, 状态栏, 功能标签, 功能页面
1. 状态栏
1.1 是否可以在台词信息框右侧开发功能按钮, 例如提供将较为常用的截图/静音等按钮安排至右边不隐藏的功能
1.2 是否可以提供按钮边框显示的功能 (比如截图按钮和静音按钮之间有垂直竖线明示按钮区域)
1.3 是否可以提供增粗状态栏的功能 (按钮可以变大, 台词信息框可以变成两行)

2. 主面板
2.1 是否可以为主面板功能标签增加边缘描线 
     目前标签之间有大量空白使得在横向移动鼠标点击的时候必须根据按钮文字填充色变化才能确定是否已经移动到正确标签上
2.2 是否可以将标签以短标签的形式居中而不是占据整个页面宽度:
<pre>
       |                                          |  *概览  |  %舰队  |  插件>  |                              齿轮  |
</pre>

3. 概览页面
3.1 概览页面任务栏高度足够时, 是否可以将任务名与任务完成提示分为两行:
<pre>
      R Bd03 - 敌舰队10回邀击       R Bw03 - 海上同上破坏作战
                          [10/10]                       [6/20]
      G D03 - ``远征" 10回成功*&(!  G D22 - 输送船团护卫强化&*!
                          [5/10]                         [1/4]
</pre>
3.2 概览页面舰队栏是否可以增加疲劳恢复时间的提示:
<pre>
      高/低速     制空: 0     索敌: -2.3   疲劳: 11:59
</pre>
      在这点上, 我的个人理解是, 概览应该可以快速反馈是否``ALL GREEN"以至于可以出击, 因此疲劳等待的数据应该有高优先级,
      而舰队速率,制空,索敌这些应该是在舰队配置时候就完成的, 如果在舰队页面有详细提供数据就足够了. 
      这个等待时间也的确与概览页面的其他时间数据的功能性吻合, 比如建造时间, 远征时间, 入渠时间等等.
3.3 概览页面舰队栏舰队按钮是否可以设置为小按钮且居中, 在狭长的按钮上横向移动反而增加操作要求:
<pre>
      |           | I | II | III | IV | 陆 |           |
</pre>

4 舰队页面
4.1 是否可以考虑修改舰队页面关于舰船信息显示的设计:
      缩短血量条与燃弹条, 提供更多的空间给装备栏, 这样就可以显示比如装备名, 熟练度, 改修度, 射程等核心信息
      单船显示例:
<pre>
            [等级][速力][CItag]         [燃料百分比]       [装备1]           [装备2]             [装备3]
[头像]      [船名][血量]    [贴条][状态] [弹药百分比]           
            [next][4格血量提示]         [燃弹条]                      [装备4]          [装备5]           [打孔]
|  长度1          |  长度X1.25          |  长度1          |  长度1            长度1            长度1          |
</pre>
4.2 舰队数据是否可以进行部分修改:
<pre>
      |        速力        |        制空        |        索敌        |        回复        |        远征统计        |
</pre>
     然后将 旗舰等级, 合计等级, 合计火力值, 合计对空值, 合计对潜值, 合计索敌值 统统放入``远征统计"里,
     并以鼠标指向提示的方式显示.
4.3 如果认为舰队页面使用率一般不想进行额外设计上的调整, 是否可以考虑提供舰队详情的功能作为独立窗口.

5 插件页面
5.1 是否可以提供强制将插件页面弹窗的按钮, 
      比如可以一边看舰队页面, 窗口看未卜先知, 或者一边看概览, 一边看经验计算器

6 设置页面
6.1 设置页面的标签是否可以考虑以短标签的形式居中而非动态标签平铺:
<pre>
      |                 |  *基本设置  |  %游戏设置  |  <显示设置  | >网络设置  |  $插件设置  |  关于POI|                 |
</pre>
      个人由于网络和插件原因, 经常要重新从dmm主页重进游戏或者调解游戏显示比率, 动态长度的标签点击倍感疲劳...
6.1.1 是否可以为设置页面下的子标签添加标签边缘描线?

稍微总结一下, 因为本人是把界面贴屏幕左侧使用的, 所以在使用过程中更希望鼠标靠近屏幕中间的区域移动, 或者靠近界面中间的区域小范围移动, 也希望制作组能考虑到靠左或者靠右使用过程中对移动区域的习性来提高一些操作性上的增强.

以上.
非常感谢.

**Comment by KochiyaOcean** [comment]
插件强制弹窗
![image](https://user-images.githubusercontent.com/8194131/91798715-79a39280-ec60-11ea-91a5-705dcb443f73.png)

**Comment by yjiangcscrc** [comment]
> 插件强制弹窗
> ![image](https://user-images.githubusercontent.com/8194131/91798715-79a39280-ec60-11ea-91a5-705dcb443f73.png)

我来找一下这个功能, 谢谢告知.

**Comment by KagamiChan** [comment]
感谢你提出的详尽的建议。关于显示与布局部分，因为我们的用户的设备、窗口大小和布局等方面都是不一样的，所以目前的显示效果有很多相互协调的部分。举一些例子：
> 3.3 概览页面舰队栏舰队按钮是否可以设置为小按钮且居中, 在狭长的按钮上横向移动反而增加操作要求:

对于触摸屏用户，需要保证足够大小的点击区域避免误点击

> 6.1 设置页面的标签是否可以考虑以短标签的形式居中而非动态标签平铺:

横向或者纵向的双栏布局下，标签不一定能显示完整

> 4.1 是否可以考虑修改舰队页面关于舰船信息显示的设计

对于宽度足够的情况我们也希望能显示更多内容，但是怎么适配宽度不足情况的显示，需要大量的设计与微调



每次布局的调整都涉及到各种显示模式下的试错与迭代，只能说希望将来有足够的资源去做

---------
其它一些功能上的增强我觉得很不错，会加到开发的考虑当中
