### ISSUE TITLE
7-3道中的敌舰队名出现逗号导致航海日志中被不正确分割

### ISSUE THREAD

**Issue by TieriaSail** [poooi/poi#2333]
**poi 版本 / poi version:10.6.0**

**操作系统 / OS:WIN10 1909**

**插件名和版本 / Plugin name & version:航海日志 7.3.2**

**你遇到了什么样的问题 / The problem you've met:7-3道中的敌舰队名出现逗号导致航海日志中被不正确分割**

**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:请见图片**

![QQ图片20200920122341](https://user-images.githubusercontent.com/32562735/93694260-2eccba80-fb3c-11ea-8fa4-fa1c9e18df8e.png)
正确的显示应该是：
![QQ图片20200920122348](https://user-images.githubusercontent.com/32562735/93694272-499f2f00-fb3c-11ea-8aca-ec9dab2cd4c4.png)

**Comment by KochiyaOcean** [comment]
会定位修复，不过目前插件正在重构中所以可能会比较花时间

**Comment by TieriaSail** [comment]
> 会定位修复，不过目前插件正在重构中所以可能会比较花时间

OK收到~

**Comment by KochiyaOcean** [comment]
![image](https://user-images.githubusercontent.com/8194131/93709504-96552b00-fb79-11ea-9b83-c5a7c38189db.png)
姑且在我本机上修复了（只有修复后的版本记录的 log 可以正常显示）不过新版发布大概还需要一些时间
