### ISSUE TITLE
網路連線問題

### ISSUE THREAD

**Issue by welson050917** [poooi/poi#2334]
系統環境:WIN10
VPN軟體:VPN Gate Client 
問題:開啟POI後一直卡在載入遊戲資料，切換IP仍無法解決，網頁版可正常開啟
謝謝您

**Comment by KochiyaOcean** [comment]
在 poi 里面访问 ipaddress.com 能看到是 VPN 的 ip 么

**Comment by welson050917** [comment]
顯示的IP是VPN的沒錯
![未命名](https://user-images.githubusercontent.com/57126126/95194386-cb16e280-0807-11eb-9e69-52eedd004ad2.png)

**Comment by KochiyaOcean** [comment]
试试看清除快取？

**Comment by welson050917** [comment]
成功登入了
謝謝您的協助
