### ISSUE TITLE
全局VPN連接日本IP後,poi瀏覽器仍然無法進入google或者dmm登入頁面。

### ISSUE THREAD

**Issue by slui** [poooi/poi#2335]
**poi 版本 / poi version:** 10.6.0

**操作系统 / OS:** Win10 V1909

如題。 使用QuickQVPN連接日本VIP36伺服器 全局狀態, Chrome 和其他瀏覽器都可以進入DMM登入畫面， 但poi仍然報錯誤地區，不能海外登入，且google官網無法瀏覽。

**Comment by KagamiChan** [comment]
@slui 在 poi 里面访问 ipaddress.com 能看到是 VPN 的 ip 么

**Comment by akagikawa** [comment]
同问题，也是一样的vpn，出现了一样的问题

**Comment by KochiyaOcean** [comment]
没用过，VPN 是什么协议的

**Comment by akagikawa** [comment]
协议在哪里看啊

发送自 Windows 10 版邮件应用

发件人: 東風谷オーシャン
发送时间: 2020年10月14日 21:38
收件人: poooi/poi
抄送: akagikawa; Comment
主题: Re: [poooi/poi] 全局VPN連接日本IP後,poi瀏覽器仍然無法進入google或者dmm登入頁面。 (#2335)

没用过，VPN 是什么协议的

**Comment by KochiyaOcean** [comment]
@akagikawa 总之就是你怎么连接的……

**Comment by akagikawa** [comment]
就這樣，但是就顯示我不在日本，不能使用




发送自 Windows 10 版邮件应用

发件人: 東風谷オーシャン
发送时间: 2020年11月22日 0:35
收件人: poooi/poi
抄送: akagikawa; Mention
主题: Re: [poooi/poi] 全局VPN連接日本IP後,poi瀏覽器仍然無法進入google或者dmm登入頁面。 (#2335)

@akagikawa 总之就是你怎么连接的……

**Comment by KochiyaOcean** [comment]
@akagikawa poi 连接 ipaddress.com 可以看到是 vpn 的 ip 么……

**Comment by akagikawa** [comment]
发送自 Windows 10 版邮件应用

发件人: 東風谷オーシャン
发送时间: 2020年11月28日 10:10
收件人: poooi/poi
抄送: akagikawa; Mention
主题: Re: [poooi/poi] 全局VPN連接日本IP後,poi瀏覽器仍然無法進入google或者dmm登入頁面。 (#2335)

@akagikawa poi 连接 ipaddress.com 可以看到是 vpn 的 ip 么……

**Comment by KochiyaOcean** [comment]
@akagikawa 呃，看不到图……

**Comment by akagikawa** [comment]
My IPV4 Address

                                                                 【中国国旗】42.249.18.129

                                                                     
                                                                     My internal IP addresses
                                                       240e:40d:e00:8ac8:2d75:52b3:4469:2752
                                                       240e:40d:e00:8ac8:50ed:e67c:447b:2cbe

                                                                             192.168.43.77

这样的



发送自 Windows 10 版邮件应用

发件人: 東風谷オーシャン
发送时间: 2020年11月28日 11:01
收件人: poooi/poi
抄送: akagikawa; Mention
主题: Re: [poooi/poi] 全局VPN連接日本IP後,poi瀏覽器仍然無法進入google或者dmm登入頁面。 (#2335)

@akagikawa 呃，看不到图……

**Comment by KochiyaOcean** [comment]
@akagikawa 这个看起来是根本没走 vpn 啊，可能需要设置代理协议为 socks5 之类的看看

**Comment by akagikawa** [comment]
啊这，那怎么设置啊，我这个VPN是应用内设置连接区域，怎么在poi内改呢

发送自 Windows 10 版邮件应用

发件人: 東風谷オーシャン
发送时间: 2020年11月28日 11:16
收件人: poooi/poi
抄送: akagikawa; Mention
主题: Re: [poooi/poi] 全局VPN連接日本IP後,poi瀏覽器仍然無法進入google或者dmm登入頁面。 (#2335)

@akagikawa 这个看起来是根本没走 vpn 啊，可能需要设置代理协议为 socks5 之类的看看

**Comment by KochiyaOcean** [comment]
@akagikawa Windows 的 Internet 设置里面看看代理怎么设置的（参照 https://www.kuaidaili.com/doc/using/win10/

**Comment by akagikawa** [comment]
开了日本代理之后是这样的

发送自 Windows 10 版邮件应用

发件人: 東風谷オーシャン
发送时间: 2020年11月28日 13:58
收件人: poooi/poi
抄送: akagikawa; Mention
主题: Re: [poooi/poi] 全局VPN連接日本IP後,poi瀏覽器仍然無法進入google或者dmm登入頁面。 (#2335)

@akagikawa Windows 的 Internet 设置里面看看代理怎么设置的（参照 https://www.kuaidaili.com/doc/using/win10/

**Comment by KochiyaOcean** [comment]
@akagikawa 邮件回复看不到图，如果发图可以用网页版发一下

**Comment by akagikawa** [comment]
网页版打不开了。。

代理服务器地址：127.0.0.1  端口：11000

发送自 Windows 10 版邮件应用

发件人: 東風谷オーシャン
发送时间: 2020年11月28日 14:19
收件人: poooi/poi
抄送: akagikawa; Mention
主题: Re: [poooi/poi] 全局VPN連接日本IP後,poi瀏覽器仍然無法進入google或者dmm登入頁面。 (#2335)

@akagikawa 邮件回复看不到图，如果发图可以用网页版发一下
