### ISSUE TITLE
輔助工具介面以及下方工具欄消失

### ISSUE THREAD

**Issue by ma12334** [poooi/poi#2336]
**poi 版本 / poi version:**10.6.0

**操作系统 / OS:**Window 10 1903

**插件名和版本 / Plugin name & version:**

**你遇到了什么样的问题 / The problem you've met:**
如下圖顯示，在一次黑屏死機之後右邊的輔助工具介面以及下方工具欄都消失不見
 按Poi->設定也沒有反應
試過卸載再安裝都無法解決

**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:**
![Image](https://github.com/ma12334/AAA/raw/main/%E8%9E%A2%E5%B9%95%E6%93%B7%E5%8F%96%E7%95%AB%E9%9D%A2%202020-10-09%20003123.png)

**Comment by KochiyaOcean** [comment]
试试看这个选项？ 
![image](https://user-images.githubusercontent.com/8194131/95492036-7923b780-09d5-11eb-8fd3-196f9118ef07.png)

**Comment by ma12334** [comment]
> 试试看这个选项？
> ![image](https://user-images.githubusercontent.com/8194131/95492036-7923b780-09d5-11eb-8fd3-196f9118ef07.png)

試過了，只是單純地將視窗最大化
還是無法解決

**Comment by KochiyaOcean** [comment]
那就删除 `%appdata%/poi/config.cson` (会丢失设置) 吧……

**Comment by ma12334** [comment]
問題解決了，感謝
