### ISSUE TITLE
希望提示功能做一个可选的弹窗

### ISSUE THREAD

**Issue by g-glamdring** [poooi/poi#2337]
**poi 版本 / poi version: 10.6.0**

**操作系统 / OS: windows 10 1903**

**插件名和版本 / Plugin name & version:**

**功能的详细描述 / Details on the feature:
提示只有声音的话经常注意不到/离开的时候没听见。希望增加可选的弹窗提示。**

**Comment by KochiyaOcean** [comment]
有系统通知弹窗的啊

**Comment by g-glamdring** [comment]
原来如此，我一直关着win10的通知系统。。。
