### ISSUE TITLE
主界面信息栏没法读取游戏，一点出击或者远征就整个信息界面消失

### ISSUE THREAD

**Issue by naiyouxiaolongxia** [poooi/poi#2339]
**poi 版本 / poi version:10.6.0

**操作系统 / OS:WIN10

**插件名和版本 / Plugin name & version:**

**你遇到了什么样的问题 / The problem you've met:主界面一点出击或者远征就整个插件界面消失，也没法重现，设置也点不出来，试过删除缓存，重装旧版本，安全模式打开

**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:**

]
![QQ图片20201108132618](https://user-images.githubusercontent.com/74127191/98457882-08371180-21c6-11eb-80d1-932e19d53bf0.png)
![QQ图片20201108132605](https://user-images.githubusercontent.com/74127191/98457883-0a996b80-21c6-11eb-8aa6-ac15a1158e21.png)

**Comment by naiyouxiaolongxia** [comment]
![Uploading QQ图片20201108132841.png…]()

**Comment by KagamiChan** [comment]
请问你是使用什么方式连接游戏的？

**Comment by naiyouxiaolongxia** [comment]
用岛风go连接的，也没有用过其他工具，之前就装过KCV

**Comment by KagamiChan** [comment]
换一个线路试试
由于不明原因拿到的数据有缺失

**Comment by KagamiChan** [comment]
确认一下，你的修理渠是解锁了几个？

**Comment by naiyouxiaolongxia** [comment]
线路的话都试过换过，修理渠是3个

**Comment by naiyouxiaolongxia** [comment]
我把渠位开到了4个，也还是依然会崩
