### ISSUE TITLE
3.1.2及3.2.0版本任务计数异常清零

### ISSUE THREAD

**Issue by xiaodiganbi** [poooi/poi#234]
3.1.2的时候周日早上a号的计数就清零了
3.2.0刚刚删除缓存重启了一次以后 a号、i号和南西和远征任务的计数异常清零了，远征十次和大规模远征的计数也清零了……大规模演习、海上通商和近代化改修是正常的
![image](https://cloud.githubusercontent.com/assets/13745836/9194481/1a1c8d4e-404e-11e5-8d3e-13f3eeec64e3.png)
_(:з」∠)_求修正……十分感谢

**Comment by magicae** [comment]
Merge to https://github.com/poooi/poi/issues/223
