### ISSUE TITLE
Windows7下无法启动

### ISSUE THREAD

**Issue by BakaCirno1** [poooi/poi#2343]
**poi 版本 / poi version:10.6.0**

**操作系统 / OS:Windows 7 Ultimate**

**插件名和版本 / Plugin name & version:**

**你遇到了什么样的问题 / The problem you've met:启动之后只有一个毛玻璃窗口 没有任何显示**

**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:每次启动复现**

**Comment by KochiyaOcean** [comment]
ctrl + shift + i 是否有开发者工具报错？
