### ISSUE TITLE
启动时任务信息，阵型选择信息及陆航信息消失

### ISSUE THREAD

**Issue by yukizasa** [poooi/poi#2345]
**poi 版本 / poi version:** 10.6.0

**操作系统 / OS:** Windows 10 Home，Version 20H2，OS build 19042.685， Windows Feature Experience Pack 120.2212.551.0

**插件名和版本 / Plugin name & version:** 未卜先知 8.4.1

**你遇到了什么样的问题 / The problem you've met:** 大约两周前开始，每次打开POI的时候任务栏里没有任何信息，需要进入游戏界面的任务界面才能刷新出正在执行的任务。出击的时候，未卜先知插件的上次选择也是被清空了。只要不关闭POI，再次出击倒是正常显示上次选择的阵型。面板中的陆航信息也无法正常显示。已经尝试清空缓存，cookie及重新安装POI，无法解决问题。

**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:** 每次关闭及启动POI都是一样的问题。

**Comment by KochiyaOcean** [comment]
能否提供开发者工具的报错信息

**Comment by yukizasa** [comment]
> 能否提供开发者工具的报错信息

抱歉，之前忘掉添加这个附件了。

![image](https://user-images.githubusercontent.com/75836176/101954419-f943e480-3bf3-11eb-97ab-6d749ad4cb66.png)

[-1607720357222.log](https://github.com/poooi/poi/files/5681590/-1607720357222.log)

**Comment by KagamiChan** [comment]
看日志没有什么问题，一般情况下这些数据都是会存储在 %appdata%/poi 目录下的，你是否有对这个目录进行过什么操作

**Comment by yukizasa** [comment]
> 看日志没有什么问题，一般情况下这些数据都是会存储在 %appdata%/poi 目录下的，你是否有对这个目录进行过什么操作

你好，并没有对这目录下有过操作。最近一年使用POI都是只用到最基础的功能和插件，也没有用过魔改。

**Comment by KagamiChan** [comment]
@yukizasa 一般的原因就是 poi 没有办法在那个文件夹里面保存文件，但是造成这个现象的原因比较多，比如安全软件，某些权限设置等等，无法给出统一的解决方法。你可以试试把这个文件夹改个名字看看是不是能正常工作

**Comment by yukizasa** [comment]
> @yukizasa 一般的原因就是 poi 没有办法在那个文件夹里面保存文件，但是造成这个现象的原因比较多，比如安全软件，某些权限设置等等，无法给出统一的解决方法。你可以试试把这个文件夹改个名字看看是不是能正常工作

谢谢你提醒的这个方向，好像是原%appdata%/poi有莫名其妙的问题。我备份了文件夹，同时把原%appdata%/poi改名。

重新启动POI浏览器后，POI是初始化状态，自动创建新的%appdata%/poi，这个文件夹在POI重启后能正常保存文件，之后把插件数据转移过来也没有丢失，一切正常了......
