### ISSUE TITLE
GPU 使用率非常高 (禁用硬體加速)

### ISSUE THREAD

**Issue by yuuga128** [poooi/poi#2348]
**poi 版本 / poi version: 10.6.0**

**操作系统 / OS: Windows 10 Pro 20H2 19042.685**

**插件名和版本 / Plugin name & version: **

**你遇到了什么样的问题 / The problem you've met: 使用硬體加速時POI的顯示卡使用率大概在30至50%附近禁用後只是換成 Client Server Client與Desktop Windows Manager合吃40至50% 有無方法換成處理器執行**

**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related: 開遊戲就這樣了**

**Comment by yuuga128** [comment]
電腦配置為 Ryzen 9 5950X, 32GB DDR4 3200 CL18, RTX 3080 Tuf OC

**Comment by KochiyaOcean** [comment]
@yuuga128 怀疑显示器的刷新率太高，NVIDIA 设置里面可以限制最大刷新率（设置为 60 即可

**Comment by yuuga128** [comment]
@KochiyaOcean 問題有好轉一點 不過目前是沒有方法透過限制遊戲內FPS解決問題 還是與這無關 如果有其他方法我想避免調整刷新率

**Comment by KochiyaOcean** [comment]
@yuuga128 游戏内 fps 取决于屏幕刷新率。旧版 chrome 内核曾经可以单独调整不过最近的版本这个接口被移除了。NVIDIA 设置里面应该可以针对单独程序设置最大刷新率，这样不会影响到其他程序的表现

**Comment by yuuga128** [comment]
@KochiyaOcean 請問一下是在Nvidia Panel調整Chrome方面的幀數還是Poi自身的呢 感謝回答

**Comment by KochiyaOcean** [comment]
@yuuga128 调整 poi 自身的

**Comment by yuuga128** [comment]
@KochiyaOcean 雖然調整成20FPS後看起來還是跟144一樣順暢 不過使用率變成9-12%左右了 感謝
