### ISSUE TITLE
未卜先知插件 - 界面显示不全

### ISSUE THREAD

**Issue by yukizasa** [poooi/poi#2349]
**poi 版本 / poi version:** 10.6.0

**操作系统 / OS:** Windows 10 Home，Version 20H2，OS build 19042.685， Windows Feature Experience Pack 120.2212.551.0

**插件名和版本 / Plugin name & version:** 未卜先知 - 8.5.1

**你遇到了什么样的问题 / The problem you've met:** 约一周前，发现未卜先知界面联合舰队敌我双方舰名均只显示一个汉字字符，最下方的战果字母也变大跟正常情况不一样。虽然功能正常，但是很难看清对应舰船的状态。

![image](https://user-images.githubusercontent.com/75836176/103642837-a4259500-4f4b-11eb-8331-97c1db19e49f.png)
![image](https://user-images.githubusercontent.com/75836176/103642848-a8ea4900-4f4b-11eb-84f9-b387256408d5.png)

此为之前正常的未卜先知界面显示的联合舰队名称截图
![image](https://user-images.githubusercontent.com/75836176/103642950-cddebc00-4f4b-11eb-8839-1474f24aefb5.png)

**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:** 尝试过重新安装插件及重建%appdata%/poi文件夹，无效。

![image](https://user-images.githubusercontent.com/75836176/103642725-80624f00-4f4b-11eb-96dd-5db543fe216a.png)

**Comment by KagamiChan** [comment]
文字显示不全的问题做了修复。不过联合舰队本身就需要很宽的空间来显示内容的，这个没有一个一了百了的方法

**Comment by yukizasa** [comment]
> 文字显示不全的问题做了修复。不过联合舰队本身就需要很宽的空间来显示内容的，这个没有一个一了百了的方法

谢谢，我重启并更新插件后显示正常了。第三张截图是出现问题前的，之前一直显示的完整内容。

![image](https://user-images.githubusercontent.com/75836176/103648534-f15a3480-4f54-11eb-9a4a-2fccdb4e38b1.png)
