### ISSUE TITLE
無法正常安裝程式

### ISSUE THREAD

**Issue by write3** [poooi/poi#2351]
**poi 版本 / poi version: 10.6.0

**操作系统 / OS: Windows 10 (1909)

**插件名和版本 / Plugin name & version: ---

**你遇到了什么样的问题 / The problem you've met: 無法正常安裝程式

**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related: 每次開啟 poi-setup-10.6.0.exe，包括以管理員權限執行
[https://i.imgur.com/0F9s7YA.png](url)

**Comment by KochiyaOcean** [comment]
有尝试更换安装目录么？如果依然无效可以试试看非安装版
![image](https://user-images.githubusercontent.com/8194131/104809483-efd01c80-5830-11eb-81f4-0dcb61b583e0.png)
![image](https://user-images.githubusercontent.com/8194131/104809486-f9598480-5830-11eb-8251-5ce5d35a1be0.png)

**Comment by write3** [comment]
感謝
