### ISSUE TITLE
win10字體模糊問題

### ISSUE THREAD

**Issue by thomaskclai** [poooi/poi#2360]
poi ver10.6.0 win 10

如題，字體有時候會變模糊，雖然不是不能閱讀的程度，但是十分影響使用體驗。之前有搜尋過，似乎是win10自身的問題，在跟microsoft官方的指引下開了override high DPI scaling behaviour (properties->compatibility->Change high DPI settings->tick override high DPI scaling behaviour, Scaling performed by system (enhanced))，但是問題沒有改善，所以在這裡問下有解決方法嗎？謝謝！

**Comment by KagamiChan** [comment]
请问可否上传一些截图

并且请告知一下你的荧幕解析度，是否开启了系统的缩放等

**Comment by thomaskclai** [comment]
![image](https://user-images.githubusercontent.com/79457860/108717014-c1441080-7557-11eb-84f7-f3ad009e20ee.png)

**Comment by thomaskclai** [comment]
圖片上傳好像有些問題

**Comment by thomaskclai** [comment]
https://imgur.com/a/DVJrHyp

**Comment by thomaskclai** [comment]
display resolution 1920x1080
螢幕縮放100%
遊戲解析度80%，960x576

**Comment by KochiyaOcean** [comment]
試試看關閉硬體加速？

**Comment by thomaskclai** [comment]
沒有改善QQ

**Comment by KochiyaOcean** [comment]
https://ci.appveyor.com/project/KochiyaOcean/poi/build/artifacts 这里的测试版呢

**Comment by thomaskclai** [comment]
請問我要下載哪一個file？

**Comment by KochiyaOcean** [comment]
@thomaskclai .exe 那个

**Comment by KagamiChan** [comment]
稍等，我看看为什么没有 exe 了

**Comment by thomaskclai** [comment]
我下載了arm下面的ia（？）版本後問題似乎解決了
謝謝解答
