### ISSUE TITLE
Windows10 布局折叠

### ISSUE THREAD

**Issue by LycorisDR** [poooi/poi#2361]
**poi 版本 / poi version:安定版 v10.6.0**

**操作系统 / OS:Windows10 Pro Version 1909(OS build 18363, 1198)**

**你遇到了什么样的问题 / The problem you've met:
我是日本人。 我用翻译服务来写我的句子。 我觉得这很难读。 我对此表示歉意。
I am Japanese. I use a translation service to write my text. I think it is very difficult to read. I apologize for that.**

显示游戏信息的部分的字体(?)和排版都坏了。 而布局被打破。(The font(?) of the part that displays information about the game is broken. and the layout is broken.)

我试过了(Tried.)

・将Windows恢复到绝对正常工作的日期。(Restore Windows to a date when it was definitely working properly.)
碎(broken)

・Poi的降级(Downgrading Poi)
即使在9.0.0版本中也是如此(Broken even with v9.0.0)

・重新安装了Poi(Reinstalled Poi.)
\AppData/Roaming/poi被删除了，但已经断掉了(was deleted but broken)**

**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:
问题出现在2021年2月23日22:30(JST)左右。
我没有安装任何新的东西。
执行了系统文件检查、内存检查和磁盘检查。

(The problem appeared on 2021/02/23(JST) around 22:30.
I did not install anything new.
System file check, memory check, and disk check were performed.)

我已经是宝岛的老用户了。
还想继续使用。
![ae9a0517cab695c3594f01ccc0b8e34d](https://user-images.githubusercontent.com/70319675/108963476-7c39ee80-76bd-11eb-8516-9cbe65b4a4d4.jpg)
![5e19bb46699dfa894413a7c0288e519c](https://user-images.githubusercontent.com/70319675/108963487-7e03b200-76bd-11eb-8446-ae0901cdefff.png)

**Comment by KochiyaOcean** [comment]
https://ci.appveyor.com/project/KochiyaOcean/poi/build/artifacts
![image](https://user-images.githubusercontent.com/8194131/108964039-506b3880-76be-11eb-906c-f2d7cdc0f28f.png)
ここのナイトリービルドをインストールしてみてください

**Comment by lszshww** [comment]
reset your nvidia control panel

**Comment by LycorisDR** [comment]
@lszshww 
I initialized the Nvidia 3D settings and that fixed it!
I really appreciate it.

@KochiyaOcean 
日本語での対応、ありがとうございました。
Nvidiaの3D設定を初期化したところ、正常に表示されるようになりました。
