### ISSUE TITLE
无法登录 Google 帐号

### ISSUE THREAD

**Issue by sanyinfu** [poooi/poi#2362]
**poi 版本 / poi version:**
10.6.0
**操作系统 / OS:**
Windows10 20H2

**插件名和版本 / Plugin name & version:**

**功能的详细描述 / Details on the feature:**
poi使用 Google 帐号登录 显示此浏览器或应用可能不安全。
请尝试使用其他浏览器。如果您使用的是受支持的浏览器，则可以刷新屏幕，然后重新尝试登录。

**Comment by japan2021** [comment]
我也一样
操作系统/操作系统：
Windows10 20H2
poi使用Google帐号登录显示此浏览器或应用可能不安全。
请尝试使用其他浏览器。如果您使用的是受支持的浏览器，则可以刷新屏幕，然后重新尝试登录。

**Comment by KochiyaOcean** [comment]
目前的内核版本比较旧了，可以下载测试版使用 https://ci.appveyor.com/project/KochiyaOcean/poi/build/artifacts

**Comment by japan2021** [comment]
> 目前的内核版本比较旧了，可以下载测试版使用https://ci.appveyor.com/project/KochiyaOcean/poi/build/artifacts

是这个吗ci: build full for appveyor   下载完放哪  不知道啊  大佬   能说的详细点吗

**Comment by KagamiChan** [comment]
可以下 exe，是安装程序

**Comment by japan2021** [comment]
大佬&nbsp; &nbsp;你是开发者？&nbsp; &nbsp;这个下完&nbsp; 安装&nbsp; &nbsp;就能用了吗




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "かがみ"<notifications@github.com&gt;; 
发送时间: 2021年2月27日(星期六) 晚上11:36
收件人: "poooi/poi"<poi@noreply.github.com&gt;; 
抄送: "吾无物语"<651706127@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [poooi/poi] 无法登录 Google 帐号 (#2362)





 
可以下 exe，是安装程序
 
&mdash;

**Comment by japan2021** [comment]
版本一样啊    好像依然不能用    是把那个单独的exe下载  解除压缩   就可以了   对吗

**Comment by KochiyaOcean** [comment]
@japan2021 确认一下关于页面的 electron 版本

**Comment by sanyinfu** [comment]
> @japan2021 确认一下关于页面的 electron 版本
electron 版本的内核是chrome 87吗
依然不能用

**Comment by japan2021** [comment]
注册个推特   在dmm上绑定推特   再用推特登录  就可以了

**Comment by a1615041784** [comment]
有解决的吗

**Comment by KochiyaOcean** [comment]
@a1615041784 总之就是内核版本太旧了（测试版也被 Google 认为太旧）所以目前只能不用 Google 登录（换用 DMM 账号登录或者推特登录等

**Comment by gnattu** [comment]
我这里用最新的artifact可以登陆，如果确认版本和我这个一致的话或许是因为某种原因被谷歌风控了

<img width="671" alt="Screen Shot 2021-03-02 at 12 54 37" src="https://user-images.githubusercontent.com/12995396/109599678-8e50dc80-7b56-11eb-8184-70f19c9149b9.png">

**Comment by a1615041784** [comment]
我这个不是一致的 能发下链接吗



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "gnattu"<notifications@github.com&gt;; 
发送时间: 2021年3月2日(星期二) 中午12:56
收件人: "poooi/poi"<poi@noreply.github.com&gt;; 
抄送: "1615041784"<1615041784@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [poooi/poi] 无法登录 Google 帐号 (#2362)





 
我这里用最新的artifact可以登陆，如果确认版本和我这个一致的话或许是因为某种原因被谷歌风控了

**Comment by KochiyaOcean** [comment]
@a1615041784 参照我上面的评论

**Comment by japan2021** [comment]
我的比较旧   但这好像是最新的   没法跟新   是我笔记本用太久了吗    poi越来越卡了
![Uploading QQ图片20210303004030.png…]()

**Comment by japan2021** [comment]
![QQ图片20210303004030](https://user-images.githubusercontent.com/79741161/109673393-5333c500-7bb9-11eb-8e66-31fe4f1a016c.png)

**Comment by KochiyaOcean** [comment]
在 4278cc8c5f934939d4bfb6b2f0fcef9b21cda27a 中新增了一个选项以允许绕过 Google 的安全检查（Google 并不建议在 Electron 中使用 Google 登录，所以请自行判断开启此选项的风险
