### ISSUE TITLE
概览面板不支持8个进行中任务

### ISSUE THREAD

**Issue by atacms** [poooi/poi#2367]
**poi 版本 / poi version:** 
10.7.0 beta1

**操作系统 / OS:** 
win10 Version2004 build19041.867

**你遇到了什么样的问题 / The problem you've met:**
概览面板最多只支持7个进行中任务的跟踪，而游戏中可以激活8个任务

**Comment by KagamiChan** [comment]
@atacms 可能是你的面板高度不足，请稍微调节一下布局试一下
