### ISSUE TITLE
Broken Plugins as of 10.7.0 Beta 1

### ISSUE THREAD

**Issue by soloblast** [poooi/poi#2368]
**poi 版本 / poi version:** 10.7.0 Beta 1

**操作系统 / OS:** Windows 10 (OS Build 19042.867)

**插件名和版本 / Plugin name & version:** EZ Exped (Javran), Senka Calc (Rui), Leveling (Javran), Morale Monitor (Javran), Equipment Improvement (KochiyaOcean), Navy Album (Javran), Subtitle (Grzhan).

**你遇到了什么样的问题 / The problem you've met:** Plugins not working at startup, probably broke in 10.7.0 (working as of 10.6.0)

**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:** N/A

**Comment by soloblast** [comment]
Seems to have fixed it, thanks. Will close this issue.

**Comment by KagamiChan** [comment]
Thanks for the confirmation, we'll kick off a new beta release soon
