### ISSUE TITLE
POI设置HTTP代理能否增加像KCV那样账号密码的设定？

### ISSUE THREAD

**Issue by yukanana** [poooi/poi#237]
![kcv](https://cloud.githubusercontent.com/assets/10300433/9216637/21112d48-40ef-11e5-9959-36afa91fcb08.jpg)
如果没有这个账号密码的设置的话，就需要去chrome的代理设置里设置全局代理，但是我的代理不能上DMM以外的网址，希望能有这个选项m(_ _)m

**Comment by KochiyaOcean** [comment]
Fixed by https://github.com/poooi/poi/commit/1b69940d8671eee409c03a268bb4147be3be0d59

**Comment by fifth** [comment]
4.0添加了这个功能之后反而无法通过http代理登陆游戏了
因为我用的http代理是不含账号密码的

**Comment by KochiyaOcean** [comment]
留空的话就和原来一样
