### ISSUE TITLE
v10.7.0-beta.2版本，插件下拉菜单均无法打开，回滚至v10.6.0后恢复正常

### ISSUE THREAD

**Issue by zqzhang1996** [poooi/poi#2374]
**poi 版本 / poi version:**
v10.7.0-beta.2

**操作系统 / OS:**
Win 10 Version 20H2 (OS Build 19042.928)

**插件名和版本 / Plugin name & version:**

**你遇到了什么样的问题 / The problem you've met:**
v10.7.0-beta.2版本，插件下拉菜单均无法打开，如士气速查中舰种筛选及航海日志资源页面切换按小时/天显示处下拉菜单均失效

**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:**
没有进行多设备测试，本机在回滚至v10.6.0后恢复正常，再次安装v10.7.0-beta.2可复现

附上控制台日志，%LocalAppData%替换了环境变量内容
[-1619537013539.log](https://github.com/poooi/poi/files/6385753/-1619537013539.log)

**Comment by KagamiChan** [comment]
fixed
