### ISSUE TITLE
特定机种下的舰载机数量显示错误

### ISSUE THREAD

**Issue by Wafer-Li** [poooi/poi#238]
Win 10 x64 Pro
Electron v0.30.3 ia32
commmit : f2a727e248c69824edf35fe9773027e73144c1c6

![qq 20150812152144](https://cloud.githubusercontent.com/assets/12459199/9217700/d959bbe8-4105-11e5-94c0-683ac7b7c2a2.png)
![qq 20150812152201](https://cloud.githubusercontent.com/assets/12459199/9217705/e8d2a954-4105-11e5-97cb-0d3dfc59b259.png)
![qq 20150812152207](https://cloud.githubusercontent.com/assets/12459199/9217706/e8d946a6-4105-11e5-8c23-c09b50e64bb4.png)

**Comment by Wafer-Li** [comment]
目前仅发现这两种舰载机存在显示错误。
或许和舰载机熟练度有关，亦或是名字太长？

**Comment by PHELiOX** [comment]
嘛 我也碰到一个
![2663278b-cdb9-4312-a302-e1d19cd534f7](https://cloud.githubusercontent.com/assets/1183568/9217923/0b23a36a-4100-11e5-8010-fc13239e3796.png)
![909bdf3f-52bc-488e-b2e6-6604f1afa1ff](https://cloud.githubusercontent.com/assets/1183568/9217924/0bfa0ff4-4100-11e5-84e9-8f9ff2b6d7da.png)

**Comment by PHELiOX** [comment]
应该修复了，麻烦再试一下

https://github.com/poooi/poi/commit/2ebe26e4bb1870973850adaf951292f70b6eae77

**Comment by Wafer-Li** [comment]
恩，解决了
