### ISSUE TITLE
关于poi的颜色显示设置

### ISSUE THREAD

**Issue by XiangNingZhi** [poooi/poi#2381]
**poi 版本 / poi version: 10.7.0-beta2**

**操作系统 / OS: win10 20H2**

**插件名和版本 / Plugin name & version: 非插件建议**

**功能的详细描述 / Details on the feature: 因为最近笔记本换了100%aRGB的广色域屏幕，经常发现Chrome内核的浏览器的颜色显示不能正确的引用校色文件，最近发现在浏览器设置里的【flags/#force-color-profile】可以调整色域设置，不过poi设置的输入框里并不能转到设置，请问控制台或是其他的配置文件里有关于【chrome://flags/#force-color-profile】的设置么？还是说莓办法设置？**

**Comment by KochiyaOcean** [comment]
@XiangNingZhi 应该是可以通过设置启动项 parameter 实现的，只要 chrome 支持 poi 一般也能支持

**Comment by XiangNingZhi** [comment]
请问是Chrome Options里设置么？poi有program file文件夹和Roaming两个文件夹，请问我需要在哪个文件夹的哪个js文件里调试呢？没有前端开发经验可以的话麻烦多多指教。

**Comment by KochiyaOcean** [comment]
直接改快捷方式。参考 https://www.chromium.org/developers/how-tos/run-chromium-with-flags

**Comment by XiangNingZhi** [comment]
原来是设置启动参数么！理解了！非常感谢！帮大忙了！
