### ISSUE TITLE
v10.7.0-beta.2 'Capture screenshot using canvas directly' is not work.

### ISSUE THREAD

**Issue by m-saeki-muj** [poooi/poi#2387]
**poi 版本 / poi version:**
v10.7.0-beta.2

**操作系统 / OS:**
Win10 21H1 (build 19043.1165)

**插件名和版本 / Plugin name & version:**

**你遇到了什么样的问题 / The problem you've met:**
'Capture screenshot using canvas directly' is not work.
This is probably due to the discontinuation of the getWebContents() API.

**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:**

**Comment by KochiyaOcean** [comment]
It works on my machine so I think it's just because capture by canvas is not a stable function itself.

We have a [polyfill ](https://github.com/poooi/poi/blob/master/views/components/etc/webview.es#L103) for `getWebContents()` method so I don't think it's the problem
