### ISSUE TITLE
进入到游戏界面就持续白屏

### ISSUE THREAD

**Issue by Ghandstark** [poooi/poi#2390]
**poi 版本 / poi version:**
10.6.0

**操作系统 / OS:**
win10 21H1 19043.1237

**插件名和版本 / Plugin name & version:**

**你遇到了什么样的问题 / The problem you've met:**
某次POI打开突然就白屏，之前都是正常的，之后再怎么处理到游戏界面那步就持续白屏。进入DMM首页、百度、换线路都是正常的，在浏览器里面打开游戏也是正常的。

**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:**
![image](https://user-images.githubusercontent.com/91936944/135985582-03fc44d8-66f2-453b-a72f-660a0bfda8c3.png)
![image](https://user-images.githubusercontent.com/91936944/135985622-3f8f4657-c380-4a92-995d-ab2f80420f3a.png)

**Comment by Ghandstark** [comment]
前几天为了回退版本重装过系统

**Comment by KochiyaOcean** [comment]
确认一下代理是否正确配置

**Comment by Ghandstark** [comment]
> 确认一下代理是否正确配置

确认过了，应该是没问题，因为出现白屏问题之前配置和之后的是完全一样的

**Comment by KochiyaOcean** [comment]
看报错像是网络的问题…… 你使用的是什么代理

**Comment by Ghandstark** [comment]
netch和clash

**Comment by KochiyaOcean** [comment]
看看防火墙设置有没有把 poi 拦截，如果没有试试看管理员权限跑命令提示符输入 `netsh winsock reset` 回车重启

**Comment by Ghandstark** [comment]
试了，防火墙直接关掉然后输入重启了也不行，不过同样是白屏，报错变成这样了
![image](https://user-images.githubusercontent.com/91936944/136003339-507804a5-d0a8-497e-bd9e-d1f84f116381.png)

**Comment by KochiyaOcean** [comment]
这几个都是资源没加载的报错，建议拿别的代理试试看……

**Comment by Ghandstark** [comment]
解决了，把代理挂到路由器上就正常了，大概率是clash和netch不知道为啥识别不到程序，用clash就算开全局poi也走的直连，netch则是资源没加载,具体也不知道啥情况突然就这样

**Comment by Ghandstark** [comment]
重新配置完正常了，看来具体还是没走成代理的整的毛病
