### ISSUE TITLE
海域地图消失了

### ISSUE THREAD

**Issue by mohsiaoran** [poooi/poi#2399]
poi 版本 / poi version:
10.6.0

操作系统 / OS:
Windows 11 专业版 21H2

你遇到了什么样的问题 / The problem you've met:
活动海域的地图显示不出来，活动海域当前的位置也是一个问号
![0610{K7{~{ DYWFF${V3YEE](https://user-images.githubusercontent.com/43316242/142848396-c963c461-6b4a-4c72-bd45-99ae883a37ae.png)

**Comment by vuryleo** [comment]
活动图似乎从未有过海域地图的样子。

普通图都是手工画出来的数据……并不是OCR出来的……

**Comment by KagamiChan** [comment]
@vuryleo 有的

**Comment by KagamiChan** [comment]
这个地方的原因是 poi 10.6 内置的根证书过期了，无法连接到 poi 服务器，可以先试试 10.7 beta 版

**Comment by vuryleo** [comment]
> 

太强了，看样子是我入场太早了还没画出来？

**Comment by mohsiaoran** [comment]
> 原因是poi 10.6 内置的根证书过期了，无法连接到poi服务器，可以先学习10.7 beta版
