### ISSUE TITLE
航母舰载机数量显示不正确

### ISSUE THREAD

**Issue by ilufang** [poooi/poi#240]
舰队页面上, 航母舰载机badge中显示的数字与游戏中不匹配, 有时偏多有时偏少
![Inconsistent Plane Count](https://cloud.githubusercontent.com/assets/6183259/9223129/f9e59c00-4129-11e5-8e91-22478310b978.png)

**Comment by PHELiOX** [comment]
最新版的应该修复了 pull一下看看

**Comment by ilufang** [comment]
赞~
