### ISSUE TITLE
关于自定义CSS的问题 

### ISSUE THREAD

**Issue by deepsea666** [poooi/poi#2400]
**poi 版本 / poi version:10.7

**操作系统 / OS:win10
这个部分的空袭要如何缩小，升级到10.7后原来用的代码失效了
![image](https://user-images.githubusercontent.com/21211204/143172751-b4eb02b1-c5d6-4931-be54-f924d3a0c74f.png)
这两个都无效了
![QQ截图20211124120326](https://user-images.githubusercontent.com/21211204/143172872-2385d86b-0fb9-46b1-b911-f7ee110cc660.png)

**Comment by KochiyaOcean** [comment]
测试结果讲自定义 css 应该是工作的。
顺便在 7d22efe09ebd3092ef3d3477a4a3d0af60c2f540 调整了一下 css 现在的版本应该是不需要再做这个自定义 css 调整了（大概？
