### ISSUE TITLE
macos arm64版本打不开，显示poi.app已损坏

### ISSUE THREAD

**Issue by acane77** [poooi/poi#2410]
**poi 版本 / poi version:**
10.7.0 arm64版本

**操作系统 / OS:**
MacOS 12.0.1

**插件名和版本 / Plugin name & version:**

**你遇到了什么样的问题 / The problem you've met:**
打开时显示已损坏
![image](https://user-images.githubusercontent.com/9192383/148261203-aa55d2ef-c666-4e88-911e-c09ea1cde45e.png)

**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:**

直接运行即出现上述错误

**Comment by KochiyaOcean** [comment]
Duplicated issue https://github.com/poooi/poi/issues/2401
