### ISSUE TITLE
更新10.7.0后cpu占用超过80%，界面动画非常卡，gpu信息显示Gpu compositing has been disabled

### ISSUE THREAD

**Issue by atacms** [poooi/poi#2414]
**poi 版本 / poi version:**
10.7.0

**操作系统 / OS:**
win10 version 21H1 build 19043.1466

**插件名和版本 / Plugin name & version:**
除航海日志以外，全部临时禁用。

**你遇到了什么样的问题 / The problem you've met:**
显卡3070
更新10.7.0后cpu占用超过80%，界面动画非常卡，
设置/关于tab下点GPU信息显示
Gpu compositing has been disabled, either via blocklist, about:flags or the command line. The browser will fall back to software compositing and hardware acceleration will be unavailable. Disabled Features: gpu_compositing
界面最小化以后则降低至5%以下。
无论是否选中“禁用硬件加速”均没有变化。
试图输入chrome://flags去调整Override software rendering list， 但是因为无论输入什么地址都会被poi加上http://前缀，变成了http://chrome://flags,所以无法修改。

不得已回滚到10.7.0beta4，问题解决，母港CPU占用率掉到4～6%之间。
GPU信息可以看到硬件加速正常工作，不再是之前的software only模式。

**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:**

**Comment by KochiyaOcean** [comment]
@atacms 驱动更新一下看看，以及 flags 是不能访问的

**Comment by charles711103** [comment]
同atacms，一更新完就發生同樣問題。

**Comment by atacms** [comment]
10.8.0后已经没有问题了，虽然有个新的小问题，GPU信息按钮点开后出现的对话框是空白的。
