### ISSUE TITLE
poi viewer 10.8 - flickering frame with hardware acceleration enabled

### ISSUE THREAD

**Issue by Whitechapel-1888** [poooi/poi#2419]
**The frame of both the game area (and the overview window if one chooses the separated layout) wildly flicker when hardware acceleration is enabled.**

_poi version:_ 10.8

_OS:_ Windows 11 home (build 22000.469)

When enabling hardware acceleration, the window frame of the poi viewer flickers exessively. Is this maybe an issue with windows 11? The flickering is so bad, it's almost unusable. This problem didn't appear on version 10.7 (beta).

_How to reproduce:_ Install poi viewer 10.8, enable hardware acceleration.

I downgraded to 10.6 due to the issues of 10.8, so no console output.

**Comment by KochiyaOcean** [comment]
duplicated #2418
