### ISSUE TITLE
详细的网络层日志

### ISSUE THREAD

**Issue by expnobody** [poooi/poi#242]
第一次重试就直接见猫神了。。
![wzch u3t 3h8ngibzy zp](https://cloud.githubusercontent.com/assets/375928/9230196/e62f4426-40ee-11e5-9ceb-39c92ae007e0.png)

**Comment by magicae** [comment]
有些猫暂时不敢防，比如api_result 100的直接猫和包没收全这些服务器炸了的猫。目前只防了HTTP 50X和断网猫。

**Comment by expnobody** [comment]
出猫的时候建议显示是什么原因？

或者哪里有log文件我没看到。。

**Comment by magicae** [comment]
猫的原因太多了……

**Comment by expnobody** [comment]
刚才shadowsocks代理抽了，舰娘猫了之后刷新服务器返回http503，poi说好的拦住50x呢。。

**Comment by magicae** [comment]
看了一下50x也不防，当时的考虑应该是服务器炸了就不要试图给他加大流量了。。。

**Comment by expnobody** [comment]
能考虑加入猫后自动刷新么。。高峰期猫的频繁总要进设置里点刷新有点烦。。主要问题还是现在夏活旗舰官方小霸王服务器也会间歇性返回503。。

**Comment by dkwingsmt** [comment]
老早的版本添加了刷新的快捷键，这个 issue 看起来没有别的待处理事项了。
