### ISSUE TITLE
下载win版本提示无法运行

### ISSUE THREAD

**Issue by PrlHelsy** [poooi/poi#2426]
**poi 版本 / poi version:**
10.8.0
**操作系统 / OS:**
windows10 21H2 

**插件名和版本 / Plugin name & version:**

**功能的详细描述 / Details on the feature:**
![QQ图片20220223214040](https://user-images.githubusercontent.com/100291519/155330781-dcebd89c-ab58-4f46-904f-82489886c949.png)

**Comment by KochiyaOcean** [comment]
下载的哪个文件

**Comment by KochiyaOcean** [comment]
这是 arm 版啊……你去下带 x64 的那个 windows 版，或者去 poi.moe 直接点下载就能直接给你正确的版本

**Comment by PrlHelsy** [comment]
原来如此...谢谢
