### ISSUE TITLE
因为github 导致不能加载flash？

### ISSUE THREAD

**Issue by checkyh** [poooi/poi#243]
Failed to load resource: net::ERR_EMPTY_RESPONSE
https://avatars1.githubusercontent.com/u/1183568?v=3&s=460 
Failed to load resource: net::ERR_EMPTY_RESPONSE
https://avatars2.githubusercontent.com/u/6861365?v=3&s=460 
Failed to load resource: net::ERR_TIMED_OUT

今天不知什么原因不开vpn上不了github 结果flash一直加载不出来
感觉应该是作者信息加载失败 是否可以考虑最后加载 避免这个问题

**Comment by magicae** [comment]
你这是网络质量有问题  chrome加载所有元素之间并不会互相干预。
