### ISSUE TITLE
舰娘信息插件里的过滤和出击计划总是停留在上次活动的贴条，更新数据更新不进去

### ISSUE THREAD

**Issue by fengxc** [poooi/poi#2431]
**poi 版本 / poi version:10.8.0

**操作系统 / OS:win11 21H2 22000.527

**插件名和版本 / Plugin name & version:舰娘信息 7.2.3

**你遇到了什么样的问题 / The problem you've met:舰娘信息插件里的过滤和出击计划总是停留在上次活动的贴条，更新数据更新不进去，目前E1是 第百四战队

**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:打开舰娘信息插件，点击出击计划按钮，信息仍然是旧的，点击设置里的更新数据起不到作用

**Comment by KochiyaOcean** [comment]
@fengxc poi.moe 是否能访问

**Comment by fengxc** [comment]
> @fengxc poi.moe 是否能访问

看起来是可以访问的

**Comment by KochiyaOcean** [comment]
@fengxc https://update.poi.moe/fcd/meta.json 的结果是什么样的

**Comment by fengxc** [comment]
> @fengxc https://update.poi.moe/fcd/meta.json 的结果是什么样的

[{"name":"map","version":"2022/03/06/01"},{"name":"shipavatar","version":"2018/09/08/02"},{"name":"shiptag","version":"2021/03/06/01"}]

**Comment by fengxc** [comment]
> @fengxc 用 poi 访问呢

也显示相同内容的json

**Comment by KochiyaOcean** [comment]
@fengxc 那理论上是没理由不能更新的，开发者工具有无报错

**Comment by KagamiChan** [comment]
我刚刚修复了一下，请等上几分钟再更新数据看看

**Comment by KagamiChan** [comment]
@fengxc 还没有添加。api 数字和贴条的对应关系不明，需要等有专家打完了帮忙验证

**Comment by fengxc** [comment]
> @fengxc 还没有添加。api 数字和贴条的对应关系不明，需要等有专家打完了帮忙验证

@KagamiChan 了解
