### ISSUE TITLE
10.7.0浏览器检查更新，未检测到新版本10.8.0

### ISSUE THREAD

**Issue by hundun000** [poooi/poi#2432]
**poi 版本 / poi version:** 10.7.0

**操作系统 / OS:** win10 21H2

**你遇到了什么样的问题 / The problem you've met:** 关于poi -> 检查更新，未检测到新版本10.8.0

**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:**

Console显示：Remote version: v10.7.0. Current version: 10.7.0

![image](https://user-images.githubusercontent.com/22592888/158148028-2612e119-ec07-4eb0-abf3-ae9e3b45d0d4.png)

**Comment by KagamiChan** [comment]
多谢汇报，现在重试会有了吗

**Comment by hundun000** [comment]
有了
