### ISSUE TITLE
山汐丸舰种错误

### ISSUE THREAD

**Issue by trankcai** [poooi/poi#2434]
**poi 版本 / poi version: 10.8.0**

**操作系统 / OS: Win10 21H2 19044.1586**

**你遇到了什么样的问题 / The problem you've met:**
在"舰队"页面上，山汐丸的舰种被错标成了"補給艦"，应该是"特設護衛空母"
![image](https://user-images.githubusercontent.com/3646798/158326466-7c1d6b3f-3ada-4d2e-aece-e6f39856e1f7.png)

同样的问题也出现在"舰娘信息"插件上，即还没有新的舰种分类
![image](https://user-images.githubusercontent.com/3646798/158326794-566beaf7-8e1a-415a-b413-77cee0907056.png)

**Comment by KochiyaOcean** [comment]
内部分类确实是补给舰，并没有问题
