### ISSUE TITLE
通过cookie直连的浏览器默认地址

### ISSUE THREAD

**Issue by agewreck** [poooi/poi#244]
DMM 8月的更新以后，原先指向的默认地址似乎已经无法通过修改cookies regional flag绕过。通过cookie直连的话，会在开启浏览器后显示“地区错误”。

在这种情况下，手动访问游戏地址( http://www.dmm.com/netgame/social/-/gadgets/=/app_id=854854/  )仍然可以进行游戏。

建议将浏览器默认地址修改为此游戏地址， 或者提供一个修改默认地址的接口。

谢谢！

**Comment by magicae** [comment]
一直都是这个默认地址的
