### ISSUE TITLE
poi10.8

### ISSUE THREAD

**Issue by chenzhin** [poooi/poi#2446]
**poi 版本 / poi version:**

**操作系统 / OS:**

**插件名和版本 / Plugin name & version:**

**你遇到了什么样的问题 / The problem you've met:**

**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:**

**Comment by chenzhin** [comment]
擴充頁面的部份自重按了重新安裝後就沒出現了

**Comment by chenzhin** [comment]
![image](https://user-images.githubusercontent.com/105625803/168531156-fb1630e5-17c9-4856-8cb3-1d02450728ca.png)

**Comment by KagamiChan** [comment]
请删除 `%appdata%/poi/config.cson` 再试一下

**Comment by chenzhin** [comment]
還是沒有辦法,只會在剛開啟時出現一下後就消失了

**Comment by KagamiChan** [comment]
@chenzhin 那再试一下开始菜单里面的 poi (safe mode)

**Comment by chenzhin** [comment]
但我一開poi就到遊戲裡了,而且右邊也沒有選項能開safe mode

**Comment by KagamiChan** [comment]
@chenzhin 抱歉，我说的是系统的开始功能表里面有的一项 poi (safe mode)

**Comment by chenzhin** [comment]
解決了,感謝,請問安全模式是跟一般有甚麼差別呢
