### ISSUE TITLE
poi.io is down, Error 1001

### ISSUE THREAD

**Issue by ibicdlcod** [poooi/poi#2447]
Cloudflare Ray ID: 70d743decdea7cc8

What happened?
You've requested a page on a website (poi.io) that is on the Cloudflare network. Cloudflare is currently unable to resolve your requested domain (poi.io). There are two potential causes of this:

Most likely: if the owner just signed up for Cloudflare it can take a few minutes for the website's information to be distributed to our global network.
Less likely: something is wrong with this site's configuration. Usually this happens when accounts have been signed up with a partner organization (e.g., a hosting provider) and the provider's DNS fails.

**Comment by KochiyaOcean** [comment]
We now has deprecated poi.io and you can use poi.moe now
