### ISSUE TITLE
希望提供調整右方介面視窗方格大小的功能

### ISSUE THREAD

**Issue by siyouyu** [poooi/poi#2451]
poi 版本 / poi 10.8.0
操作系统 / win 10
![螢幕擷取畫面 2022-06-17 193130](https://user-images.githubusercontent.com/99458969/174291190-a3c04ce0-36af-4442-a37f-3842efe2d4fb.png)
右邊的介面(紅色框)，希望可以增加調整方格的功能
舉例來說入渠、建造欄位現在只看得到2個、任務欄沒辦法全部看到(藍色框)，希望可以游標移動到方格邊界就能直接往下拉調整大小
這樣就能完全善用紅框下方的剩餘空間

**Comment by siyouyu** [comment]
就像是這種感
![螢幕擷取畫面 2022-06-17 194211](https://user-images.githubusercontent.com/99458969/174292959-a4838ed9-2e12-48d1-b461-ba13306de8bb.png)
覺

**Comment by siyouyu** [comment]
就像是這種感覺
![螢幕擷取畫面 2022-06-17 194211](https://user-images.githubusercontent.com/99458969/174293008-a0d1963f-35a5-4425-8c8a-8e73e7564013.png)

**Comment by KochiyaOcean** [comment]
![image](https://user-images.githubusercontent.com/8194131/174294447-0d7acaa8-6a0a-4c84-b004-79412bab39f7.png)
点这里

**Comment by siyouyu** [comment]
> ![image](https://user-images.githubusercontent.com/8194131/174294447-0d7acaa8-6a0a-4c84-b004-79412bab39f7.png) 点这里

哦哦 了解 謝謝你@@!
