### ISSUE TITLE
10.8.0無法截圖

### ISSUE THREAD

**Issue by namodaze** [poooi/poi#2455]
**poi 版本 / poi version:** 
10.8.0

**操作系统 / OS:** 
Win10 1903

**插件名和版本 / Plugin name & version:**
一鍵截圖

**你遇到了什么样的问题 / The problem you've met:**
沒打活動沒怎麼使用截圖功能，直到最近才發現沒辦法截圖，確定以前的活動是可以的。
試過重開；重新安裝，也都不能解決這個問題，希望可以獲得幫助，非常感謝。

**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:**

![POI壞了](https://user-images.githubusercontent.com/88684561/176849183-1440bdda-4610-42b8-9c04-d633b9a9f354.png)

**Comment by mic4126** [comment]
遇到同樣問題 (只是把username 塗黑)
![image](https://user-images.githubusercontent.com/4671533/177015160-fe694d01-5f20-4e08-a4d8-6436bb776c79.png)

**Comment by namodaze** [comment]
![POI壞了2](https://user-images.githubusercontent.com/88684561/182045288-468d1468-4b8c-43d3-8e25-d3a1b9f2eb50.png)
您好，感謝您的回應，然而經查

**Comment by namodaze** [comment]
您好，感謝您的回應，然而我發現不使用分離模式一樣沒有辦法截圖，
以下是開發者模式的錯誤代碼，再麻煩您們檢查一下，非常感謝
![POI壞了2](https://user-images.githubusercontent.com/88684561/182045353-b0c46f0d-4ae8-4be6-8f8d-0003b530ad37.png)
。

**Comment by KochiyaOcean** [comment]
@namodaze 存储位置不放在根目录就可以了
