### ISSUE TITLE
[BUG]无法显示设置+插件

### ISSUE THREAD

**Issue by misaka10843** [poooi/poi#2456]
**poi 版本 / poi version:** 10.8

**操作系统 / OS:** Windows11 25145.1011

**插件名和版本 / Plugin name & version:** 无

**你遇到了什么样的问题 / The problem you've met:**

在修复插件时闪退后再进入就无法再显示设置/插件，并且在工具栏打开设置也不行

并且无法从工具栏和快捷键中打开开发者工具

Roaming文件夹下的poi文件夹尝试删除但是无果

**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:**
![image](https://user-images.githubusercontent.com/69132853/176908573-3dbdc3f3-d59e-4c60-a683-fe6e56ba6bd7.png)
![image](https://user-images.githubusercontent.com/69132853/176909297-08fc1a31-01e5-433b-92ed-ad78e1e3bea1.png)

**Comment by canpoTD** [comment]
怎么解决的
