### ISSUE TITLE
內建主題樣式建議(papercyan)

### ISSUE THREAD

**Issue by jianhuatw** [poooi/poi#2458]
**poi 版本 / poi version:**
10.8.0

**操作系统 / OS:**
MACOS 12.2.1

**插件名和版本 / Plugin name & version:**
theme-papercyan
https://github.com/govizlora/theme-papercyan

**功能的详细描述 / Details on the feature:**
這是我之前非常喜歡用的主題樣式，可惜於某次改版後就無法適配了，剛好看到微博上有討論到主題配色，所以建議可否新增該主題，感謝！

**Comment by KagamiChan** [comment]
@jianhuatw 舊 papercyan 主題不適用於現在的 UI，所以要增加的話基本要重新適配一遍，組內目前沒有餘力開發
