### ISSUE TITLE
添加一个刷新快捷键F5

### ISSUE THREAD

**Issue by linzhibinghan** [poooi/poi#246]
看蛮多人都说希望出猫后自动刷新的,不过记得这里早期就有人反应了说是技术方面不能实现,那么直接出一个F5或者自定义按钮用来刷新当前界面能否可行呢,省的每次都切面板或者鼠标点点点。

**Comment by expnobody** [comment]
这个好，跪求快捷键f5。。。

**Comment by c933103** [comment]
但建議要防誤觸…

**Comment by dkwingsmt** [comment]
所以又得加个确认……
