### ISSUE TITLE
错误警告 - 未使用的装备格

### ISSUE THREAD

**Issue by toooonyy** [poooi/poi#2463]
**poi 版本 / poi version:**
`10.9.0`
**操作系统 / OS:**
`macOS 12.5`

**插件名和版本 / Plugin name & version:**
大概是本体或者未卜先知的问题？
`未卜先知 8.11.1`

**你遇到了什么样的问题 / The problem you've met:**
提示有格子空着，但实际没有
<img width="1310" alt="Screen Shot 2022-08-22 at 15 56 15" src="https://user-images.githubusercontent.com/3480434/185939753-af27e151-4750-491a-9a34-6a9be7e1ff36.png">

**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:**
稳定重现，还在测试到底是什么装备摆放导致的。带的装备：
<img width="1275" alt="Screen Shot 2022-08-22 at 16 03 54" src="https://user-images.githubusercontent.com/3480434/185940401-fd561497-52a9-454a-8f8c-35b03c65cd4b.png">

`This is poi@10.9.0 on darwin arm64 with Electron@20.0.1,        PLUGINS: poi-plugin-prophet@8.11.1, poi-plugin-quest-info-2@0.8.9, poi-plugin-ezexped@1.8.5, poi-plugin-map-hp@6.2.1, poi-plugin-akashic-records@8.1.4, poi-plugin-battle-detail@5.12.0, poi-plugin-wheres-my-fuel-gone@0.7.4, poi-plugin-item-improvement@7.1.3, poi-plugin-ship-info@7.2.3, poi-plugin-item-info@4.2.1, poi-plugin-lock-reminder@1.0.6, poi-plugin-kcwiki-report@3.2.22, poi-plugin-let-me-in@1.0.0, poi-plugin-report@8.0.0, poi-plugin-subtitle@1.4.0,        FCD: map@2022/06/17/01, shipavatar@2018/09/08/02, shiptag@2022/06/29/01`

**Comment by KochiyaOcean** [comment]
如果你的 2-4 队没有出击而且有空的格子这个警告也会出现, 是正常情况

**Comment by KagamiChan** [comment]
简单地说我们并不知道你会用哪个舰队出击，只能对目前没有远征的舰队都做一次检查

当然提示具体是哪个舰娘可能会体验更好一点
