### ISSUE TITLE
傻瓜式兼容航海日志

### ISSUE THREAD

**Issue by expnobody** [poooi/poi#247]
poi虽然自带ss代理。设置虽然是。好，但是用了那个就用不了航海日志了，还得自己开ss，能否像岛风go一样设置开启航海日志，然后仍然使用poi自带的代理设置呢

ps：poi公共代理密码丢了怎么恢复。。

**Comment by magicae** [comment]
不支持航海日志 因为航海日志的代理模块实现是有问题的
