### ISSUE TITLE
清除缓存功能无法清理掉js的缓存

### ISSUE THREAD

**Issue by Frimaire** [poooi/poi#2473]
**poi 版本 / poi version:** main / 10.9.2

**操作系统 / OS:** GNU/Linux 

**插件名和版本 / Plugin name & version:** 不适用

**你遇到了什么样的问题 / The problem you've met:** 

使用设置里面的清除缓存功能, 只能清理掉页面中媒体内容(比如图片)的缓存, 这个位于~/.config/poi/Cache下, 
而无法清理掉页面中js的缓存, 这个位于~/.config/poi/Code Cache下, 其中的内容看起来是js编译后的字节码.

**可能的原因和解决方法:**

 清除缓存的工作是由设置中的storage-config.es(位于views/components/settings/main)的handleClearCache事件侦听器完成的, 它调用了Electron的clearCache函数,这个函数似乎不能清除掉js的缓存.

Electron的Session类中还有另外一个函数, 叫[clearCodeCache](https://www.electronjs.org/docs/latest/api/session#sesclearcodecachesoptions). 把clearCache改成clearCodeCache之后, Code Cache下的文件被清理掉了.

一个可能的解决方法是修改代码让清除缓存时同时调用clearCodeCache, 把js的缓存一起清理掉. 但是我更倾向于增加一个独立的用于清除代码缓存的按钮, 可以只清除代码缓存, 因为重新get到js所用的时间应该比get全部资源少很多.

p.s. 最近经常100猫, 有相同情况的吗?

**Comment by KagamiChan** [comment]
清除 code cache 会带来什么好处吗

**Comment by Frimaire** [comment]
> 清除 code cache 会带来什么好处吗

My mistake.

我想用清除缓存的方法解决100猫的问题， 但是还是猫了.
