### ISSUE TITLE
minimap popup potential tweak

### ISSUE THREAD

**Issue by evantrees** [poooi/poi#2487]
**poi 版本 / poi version:**
10.9.2
**操作系统 / OS:**
Windows 10
22h2

**功能的详细描述 / Details on the feature:**
I really like the minimap popup feature but would it be possible to stop the pinned version from removing the ability to select line abreast formation, and if I recall correctly vanguard formation during events.

**Comment by KochiyaOcean** [comment]
Actually, the former version of pinned minimap can be clicked through, but the feature failed to work after some dependencies updates. The clicked-through function should be fixed in future versions.
