### ISSUE TITLE
概览舰队插件无法更新数据

### ISSUE THREAD

**Issue by Gujh212** [poooi/poi#2489]
**poi 版本 / poi version:10.9.2**

**操作系统 / OS:21H2 19044.2604**

**你遇到了什么样的问题 / The problem you've met:概览数据卡住，之前在别的地方登陆过，再回到家登录后，概览和舰队数据就卡住了，插件也无法读取数据，清理缓存，重装poi也无法解决**

**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:重新编队后，编队功能可以恢复，远征功能也可以恢复，但是任务状态完全失能**
![image](https://user-images.githubusercontent.com/96736666/221603599-d726cee3-463a-459a-a79b-5377c3f5bd17.png)

**Comment by KochiyaOcean** [comment]
`%appdata%/poi` 改个名看看？

**Comment by Gujh212** [comment]
改了名之后在旁边又生成了一个poi文件夹，重装了C++环境之后红色报错没有了，但是还是无法加载来源映射
![捕获223](https://user-images.githubusercontent.com/96736666/221902513-f02d4487-df82-4b1a-8911-bc4bcecc12a2.png)

**Comment by KochiyaOcean** [comment]
这个警告和实际使用没什么关系，可以忽略

**Comment by Gujh212** [comment]
维护完之后上线，又出现错误了，只有资源能载入，其他功能还是不可用
![捕获3333](https://user-images.githubusercontent.com/96736666/222016707-b6edc258-b3ec-4af7-bdac-47c485af87ff.JPG)

**Comment by Gujh212** [comment]
解决了，原来是我岛风go没开舰C模块，:confounded:我是猪
