### ISSUE TITLE
[bug反馈]win10下不显示主界面

### ISSUE THREAD

**Issue by liuyuesakura** [poooi/poi#249]
win10，64位双屏幕下界面不显示，鼠标移动到任务栏上有预览，但是无法显示或切换到主界面。任务管理器CPU占用率一直处于1%以下，绝大部分时间都只有0%。
![qq 20150813233621](https://cloud.githubusercontent.com/assets/6565855/9254082/1f48155a-4214-11e5-8c8e-b177e6bc552c.jpg)
![qq 20150813233512](https://cloud.githubusercontent.com/assets/6565855/9254088/214af908-4214-11e5-8dac-5c83f6000bfa.png)

**Comment by myzWILLmake** [comment]
CPU占用率低是因为图中看得到网络连接错误，flash都还未打开。
找不到窗口的问题建议按住shift键右击图标，然后选择最大化。

**Comment by magicae** [comment]
Electron的BUG 删config.cson可破
