### ISSUE TITLE
Display spoiler enemy composition returned by new API/显示新API剧透的敌方编成

### ISSUE THREAD

**Issue by axmmisaka** [poooi/poi#2498]
Tanaka modified the API such that it returns the top 3 ships of the enemy composition in the 10th anniversary update; we could update poi to get that API data as well;
New API explanation: https://nga.178.com/read.php?tid=36062812

十周年更新中田中让API同时返回敌方编成中前三船；我们或许可以小改一下代码获取这个数据
API解析：https://nga.178.com/read.php?tid=36062812

**Comment by hot36952** [comment]
希望尽快利用到这个API，比如未卜先知里显示

**Comment by KochiyaOcean** [comment]
42d00e3551c172f4a31d4dbf887192b90aa46103
