### ISSUE TITLE
FCF

### ISSUE THREAD

**Issue by c933103** [poooi/poi#250]
使用FCF時的數據參考https://github.com/dragonjet/KC3Kai/issues/461#issuecomment-129687727

相關功能：
- [x] 退避後艦隻狀態更新
- [x] 對護衛退避艦隻的標記
- [ ] 顯示現在艦隊是否裝備有FCF，二隊有沒有可以護衛退避的DD，在使用護衛退避後艦隊會否還有其他大破船隻再加上相關船隻有沒有配備損管

**Comment by magicae** [comment]
别说了 我正在捞大淀 :cry:

**Comment by PHELiOX** [comment]
https://github.com/poooi/poi/pull/298
https://github.com/poooi/poi/pull/307

**Comment by PHELiOX** [comment]
高级损管检查功能待实现？
