### ISSUE TITLE
使用ooi时poi无法载入游戏信息

### ISSUE THREAD

**Issue by Billons007** [poooi/poi#2504]
**poi 版本 / poi version:**
10.6.0/10.10.0-beta.0

**操作系统 / OS:**
Windows 10 22H2 (19045.2364)

**你遇到了什么样的问题 / The problem you've met:**
使用ooi时poi无法载入游戏信息，通知栏也没有显示API被读取，但实际api请求是正常的
10.6.0的release和10.10.0-beta.0的npm包都有这个问题，其他版本不明

**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:**
ooi poi模式：

<img width="718" alt="Snipaste_2023-06-11_01-39-03" src="https://github.com/poooi/poi/assets/67461674/53c592d8-f297-4b65-8953-8ad3034c5c7a">
<br>ooi 普通模式：
<img width="1331" alt="Snipaste_2023-06-11_01-40-15" src="https://github.com/poooi/poi/assets/67461674/dc97226a-4d1c-4ab9-9d04-0e055f12068b">
api有在正常请求，但poi均无法读取

[遇到同样问题的Issues（未被回复，未解决）](https://github.com/poooi/poi/issues/2371)

**Comment by KochiyaOcean** [comment]
@Billons007 不要用 https 开，开 https 怎么中间人

**Comment by Billons007** [comment]
> @Billons007 不要用 https 开，开 https 怎么中间人

感谢，已解决。
