### ISSUE TITLE
布局适配的迟滞

### ISSUE THREAD

**Issue by Wafer-Li** [poooi/poi#251]
Electron v0.30.4 ia32
Win 10 x64 Pro
commit SHA: 2d4ac00099502bf8321364c2e21ce817577c5c8c

从横版布局切换到纵版布局，需要重启一次程序才能达到最适化

如图，目前采用的是横版布局
![qq 20150814145124](https://cloud.githubusercontent.com/assets/12459199/9267999/07a91842-4294-11e5-8a29-e33de6279d70.png)

切换到纵版布局后
![qq 20150814145300](https://cloud.githubusercontent.com/assets/12459199/9268013/35ad29ea-4294-11e5-999c-aa56e2ca038a.png)

可以发现，概览界面的排布仍然为横版中的
口口
口口

而非纵版中的
口口口口

重启程序后，布局方才实现最适化
![qq 20150814145520](https://cloud.githubusercontent.com/assets/12459199/9268034/9843906c-4294-11e5-96d0-ce467e4622fd.png)

**Comment by KochiyaOcean** [comment]
肿殃研究决定了，布局设置重启后完全生效
