### ISSUE TITLE
登录游戏约数十秒后显示Webview load error Error Code: -111

### ISSUE THREAD

**Issue by YXZ20A** [poooi/poi#2510]
**poi 版本 / poi version:10.9.2**

**操作系统 / OS:Win10 22H2 内部版本19045.3570**

**插件名和版本 / Plugin name & version:**

**你遇到了什么样的问题 / The problem you've met:岛风go连接，登录游戏越数十秒后显示“Webview load error
Error Code: -111
Description: ERR_TUNNEL_CONNECTION_FAILED
URL: https://asia.creativecdn.com/tags?type=iframe&id=pr_pX0Lk8iTEuUkxXsNGR68&id=pr_pX0Lk8iTEuUkxXsNGR68_lid_YRapR4QzNQlv16D2dydX&su=http%3A%2F%2Fwww.dmm.com%2Fnetgame%2Fsocial%2F-%2Fgadgets%2F%3D%2Fapp_id%3D854854&sr=&ts=1697102947931”**

**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:几乎每次登录就会出现，有时能正常游戏，活动结束更新后明显开始变多
![poi](https://github.com/poooi/poi/assets/147708507/8c8eb18d-bebd-455b-ae66-c5c1b0e7d640)
**

**Comment by KochiyaOcean** [comment]
@YXZ20A 这个错误一般来说是代理连接出错导致的
