### ISSUE TITLE
Option to show detailed ship view instead of ship mini

### ISSUE THREAD

**Issue by liu-ziyang** [poooi/poi#2513]
**poi 版本 / poi version:**
10.9.2

**功能的详细描述 / Details on the feature:**
It would be great to have an option to allow showing detailed ship information (as in the fleet panel), instead of the ship mini panel which drops equipment info and some others. It is not a big deal to go back and forth, but the experience would be smooth if the fleet view is optionally integrated into the summary view

**Comment by KochiyaOcean** [comment]
I dont think it could be a release version feature because the ship panel is not designed for small space, but you can still pull the source code and change the mini ship panel to the normal one
