### ISSUE TITLE
联合舰队的剧透，两队船数不一样时显示不全

### ISSUE THREAD

**Issue by taroxd** [poooi/poi#252]
打E7航空战时发现的……一队5船二队6船，然而二队只显示前面的五艘

我猜是计算高度的时候没考虑这种情况？

此外，当1、2队组成联合舰队，用第3舰队出击时，剧透的显示是联合舰队。

**Comment by taroxd** [comment]
此外，无论用几队出击，疲劳值总是显示一队的

**Comment by Chibaheit** [comment]
fixed
