### ISSUE TITLE
11.0.0-beta.0/1无法使用windows窗口贴靠屏幕边缘自动分屏功能

### ISSUE THREAD

**Issue by zqzhang1996** [poooi/poi#2521]
**poi 版本 / poi version:**
11.0.0-beta.0
11.0.0-beta.1

**操作系统 / OS:**
Windows 10 Version 22H2(OS Build 19045.3570)
Windows 11 Version 22H2(OS Build 22621.2283)

**你遇到了什么样的问题 / The problem you've met:**
更新后无法使用windows贴靠窗口自动分屏功能

**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:**
分别在win10和win11设备进行测试，beta.0、beta.1均存在该问题，回退至10.9.2后功能正常

**Comment by KochiyaOcean** [comment]
上游问题等下个版本
