### ISSUE TITLE
希望切换网络设置时不需要重启软件，可以做到吗？

### ISSUE THREAD

**Issue by taroxd** [poooi/poi#253]
比如，我代理挂了的时候，趁防猫功能启用的时候切换成直连之类的

就和之前的KCV一样，可以么- -

**Comment by KochiyaOcean** [comment]
其实本来就不需要重启，直接切换就行了
[del]那个提示只是装饰而已（下略[/del]

**Comment by magicae** [comment]
目前就不需要重启。
