### ISSUE TITLE
Webview load error

### ISSUE THREAD

**Issue by 258654aun** [poooi/poi#2530]
**poi 版本 / poi version:*v11.0.0-beta1*

**操作系统 / OS:*Windows11 23H2 22631.2861*

**插件名和版本 / Plugin name & version:**

**你遇到了什么样的问题 / The problem you've met:*有时候玩两局就猫（大概率在出击过程中），刷新页面就提示Webview load error，需要等几分钟再刷新或重启POI才能显示出网页，偶尔在刚开启POI时也会出现这种情况。*

**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:**

**Comment by 258654aun** [comment]
![0](https://github.com/poooi/poi/assets/129575695/a8411f03-1f32-415c-ac9d-4eeed005bdff)
![1](https://github.com/poooi/poi/assets/129575695/3085113c-68c7-421d-8deb-a294115a386f)
![2](https://github.com/poooi/poi/assets/129575695/b5f13cf7-f88d-4674-888f-796bbe6661ee)

**Comment by KochiyaOcean** [comment]
一般是网络不稳定导致

**Comment by 258654aun** [comment]
应该不是网络问题，我用家里的网、学校的网还有手机流量都试过了，都有这个问题。但是我用浏览器玩，或者在OOI里选择在浏览器中运行都没这个问题

**Comment by 258654aun** [comment]
而且只有出击的时候容易猫

**Comment by KochiyaOcean** [comment]
@258654aun 总之换 11 测试版看看吧

**Comment by 258654aun** [comment]
用的就是最新的测试版，这个问题从今年年初就有了

**Comment by KochiyaOcean** [comment]
@258654aun 11 是直接使用代理连接的所以很难考虑是这里的问题啊...

**Comment by slui** [comment]
我也出现这个问题, 今天过了凌晨后就出现Webview load error, 
有errorcode: -7 和 101。
用的版本是10.9.2。
但我用其他KC3类型的系统运行,却不会出现这个问题。

**Comment by KochiyaOcean** [comment]
@slui 升最新版
