### ISSUE TITLE
出击关卡卡住 没有罗盘娘

### ISSUE THREAD

**Issue by landibex** [poooi/poi#2533]
![image](https://github.com/poooi/poi/assets/94696916/2b72ad3c-1b0e-4adc-8c11-451a42f9367c)

**poi 版本 / poi version:**11.0.0 beta-1

**操作系统 / OS:** windows 11

**你遇到了什么样的问题 / The problem you've met:**  其他功能正常运行 但是出击普通海域之后会卡住 不出现罗盘娘

**有没有重现的方法，或者与问题相关的任何信息 ：基本上每次打开都会卡住

可以的话请提供开发者工具 Console 选项卡的截图，
![image](https://github.com/poooi/poi/assets/94696916/24d0b371-aa3c-471c-9a29-4091d112433e)
![image](https://github.com/poooi/poi/assets/94696916/25d21237-1adf-479b-b60c-570d7cc542fa)
 使用的是岛风go 设置应该没问题
![image](https://github.com/poooi/poi/assets/94696916/d11f3ef7-4a32-43c1-a5a6-85086e83ee40)
![image](https://github.com/poooi/poi/assets/94696916/e5910afe-364e-44a0-a3dc-cc8f8c1a09c6)
![image](https://github.com/poooi/poi/assets/94696916/5363333a-2bfe-4043-9396-f7c87214dbf4)
![image](https://github.com/poooi/poi/assets/94696916/be75b29d-ac70-42f3-b34a-ec81f98461dc)

**Comment by landibex** [comment]
![image](https://github.com/poooi/poi/assets/94696916/09283cca-8503-4996-ace2-f052428e0a3a)
 但是未卜先知 已经有结果了 多半已经解到包了

**Comment by landibex** [comment]
![image](https://github.com/poooi/poi/assets/94696916/7fe574e3-5fd3-4f0b-aa0d-b4987a95d93d)
而且仓库里面的小人 也似乎消失了

**Comment by KochiyaOcean** [comment]
网络连接超时，检查代理和网络连接吧

**Comment by landibex** [comment]
尝试过了 包括重新安装了代理 不太行

**Comment by landibex** [comment]
![image](https://github.com/poooi/poi/assets/94696916/be2c5f1b-a78e-45d8-8040-d08e25283939)
而且也是可以上dmm官网的

**Comment by KochiyaOcean** [comment]
检查代理主要是

**Comment by landibex** [comment]
您的意思是我要去找岛风go 的客服是吗

**Comment by KochiyaOcean** [comment]
Go 的话检查缓存吧……

**Comment by landibex** [comment]
![image](https://github.com/poooi/poi/assets/94696916/4adddb91-41aa-4e28-907a-b2f648eeb22c)
检查过了 似乎一直卡在0.01

**Comment by landibex** [comment]
还有祝您新年快乐

**Comment by KochiyaOcean** [comment]
直接关掉本地缓存应该也行

**Comment by landibex** [comment]
![image](https://github.com/poooi/poi/assets/94696916/50d95d4f-d4b4-44da-aa5d-b2f97b92d6e7)
好的 可以领 谢谢
