### ISSUE TITLE
关于【舰船修复中】的增强显示

### ISSUE THREAD

**Issue by Wafer-Li** [poooi/poi#254]
可以类似于KCV一样，在舰队面板内，如果有船正在入渠，则在血条上覆盖一个半透明的【修复中】的提示条。
3-2练级的时候看到潜艇大破总是怕是不是没有修……

**Comment by taroxd** [comment]
哪有我退避之后看着那个大破怕……

**Comment by Wafer-Li** [comment]
退避的包如果能解析的到的话，也可以同上进行处理

**Comment by magicae** [comment]
@Wafer-Li 退避的包暂时是打算按照退避优先级判定，目前不做额外，显示仅仅在大破退避进击的时候忽略。这些显示在目前 @PHELiOX 的v4.0.0面板里实现了，v3.x分支估计不予实现了。活动结束后我会开始v4.0.0的合并和重构。

**Comment by c933103** [comment]
退避算#250 吧

**Comment by PHELiOX** [comment]
https://github.com/poooi/poi/pull/298
https://github.com/poooi/poi/pull/316

Done.
