### ISSUE TITLE
poi占用显存过多

### ISSUE THREAD

**Issue by iamydp** [poooi/poi#2541]
**poi 版本 / poi version:10.9.2**

**操作系统 / OS:22621.3007**

**你遇到了什么样的问题 / The problem you've met:**  
poi自启动开始就不停的吃显存,直到占用9g左右.
![image](https://github.com/poooi/poi/assets/26623485/e25aadd7-62f3-4a3d-b18c-2e78d85994da)

**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:**  
不稳定复现,大概出现概率有50%.关闭硬件加速能解决但是会稳定100%占用我的cpu3-4个线程,且画面比较卡顿.在windows 图形设置里指定poi跑在核显也会占用大量独显显存,怀疑是英特尔的锅

**Comment by iamydp** [comment]
![image](https://github.com/poooi/poi/assets/26623485/302875b1-a4da-4699-b7d2-0e99c24f59cd)
![image](https://github.com/poooi/poi/assets/26623485/50f0e70b-9d3d-4312-92ed-ecac2633a82a)
重装了显卡驱动,再次尝试指定在核显上,把我内存爆了.附上当前设置里的gpu debug信息,希望有用.
另外我发现从全屏应用切到poi窗口时100%复现.
[](https://pastebin.com/qjSLGs9X)

**Comment by KochiyaOcean** [comment]
手动使用其他 electron 版本（如果能）的话是否能复现？

**Comment by iamydp** [comment]
使用11版本poi没有这个问题了
