### ISSUE TITLE
大破進擊bug？

### ISSUE THREAD

**Issue by siyouyu** [poooi/poi#2547]
poi 版本：11.0.0-beta.5
操作系统 ：win11

有得到使用poi瀏覽器，大破時未跳出警告視窗bug的回報

**Comment by KochiyaOcean** [comment]
请提供详细信息

**Comment by siyouyu** [comment]
疑似為開幕雷擊API修改，導致未卜先知運作異常

**Comment by KochiyaOcean** [comment]
重复 issue，插件已发布新版本修复，详见 https://github.com/poooi/poi/issues/2546
