### ISSUE TITLE
猫了之后点刷新按钮，重新进入游戏后部分插件会失效

### ISSUE THREAD

**Issue by jayjayzju** [poooi/poi#255]
包括主面板各种倒计时等等

**Comment by PHELiOX** [comment]
是不是没重新刷登录界面的包?

**Comment by PHELiOX** [comment]
已修复
https://github.com/poooi/poi/commit/af840473069825d059857dd9fb49ff4ff5fe1415
https://github.com/poooi/poi/commit/120a291fe58b80538eed157a9dc2b231871b08f3
