### ISSUE TITLE
开发文档页面访问不了了

### ISSUE THREAD

**Issue by KyoMiko** [poooi/poi#2562]
感觉上应该不是证书那么简单，是不是已经死了（
开发文档还会继续维护么，我看github仓库里面的那个好像也是版本9的了，虽然之前写过可以照猫画虎，但是能有准确的文档就最好了

**Comment by KagamiChan** [comment]
因为要把网站从 netlify 转走所以旧网站删掉了。尴尬的是项目依赖太老了在 cloudflare 那边构建不起来……更新依赖的话又有很多很大的变化。因为文档很久没更新了，所以觉得可能留存意义不大，不过有需要的话后续会继续上线。在这期间可以先看仓库里面的 markdown 文档

**Comment by KagamiChan** [comment]
总之一番折腾之后现在回来了，网址是新的

https://dev.poi.moe/
