### ISSUE TITLE
POI瀏覽器插件介面消失  POI browser plugin interface disappears

### ISSUE THREAD

**Issue by SalveRobert** [poooi/poi#2567]
**poi 版本 / poi version:10.9.2**
![image](https://github.com/user-attachments/assets/12be55dc-8d1f-4a29-a1a8-a4b623d80789)

**操作系统 / OS:Windows 11 家用版 23H2**

**你遇到了什么样的问题 / The problem you've met:
開啟POI瀏覽器的時候插件介面會出現一下下，然後馬上全部消失
When opening the POI browser, the plugin interface appears for a moment and then disappears immediately.**

![image](https://github.com/user-attachments/assets/1ef8ad91-895d-4fd8-9bac-5a9dc8e632c3)
![image](https://github.com/user-attachments/assets/81a33ba2-e45c-4755-aa42-0197e7d6ea14)

**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:
每次重開都會重複發生
It happens every time I restart.**

![image](https://github.com/user-attachments/assets/47def1ce-7eb7-411d-affd-cc3140c358e5)

**Comment by KochiyaOcean** [comment]
![image](https://github.com/user-attachments/assets/6e354d89-b4a0-429d-a85d-b3625be45267)
开发者工具的这里点红叉看看有什么报错信息，以及是否使用了第三方插件

**Comment by SalveRobert** [comment]
不好意思這麼晚回覆，很感謝您的幫忙，以下是抱錯的詳細內容，有Log檔
Sorry for the late reply. Thank you very much for your help. Below are the details of the mistaken package, including the log files.

[-1726469916244.log](https://github.com/user-attachments/files/17009436/-1726469916244.log)


![image](https://github.com/user-attachments/assets/9325aeab-366e-474e-8474-ed01e2466365)
![image](https://github.com/user-attachments/assets/738d89ed-f25a-4eef-bef1-93d3c232182d)
![image](https://github.com/user-attachments/assets/9e2f4faa-6f2f-411e-beee-f84fa590679c)
![image](https://github.com/user-attachments/assets/2dccd1f2-302d-47f5-8270-ff5618f8863c)

**Comment by KochiyaOcean** [comment]
> 不好意思這麼晚回覆，很感謝您的幫忙，以下是報錯的詳細內容，有Log檔 我沒有安裝 Poi 以外的插件 Sorry for the late reply. Thank you very much for your help. Below are the details of the error report, including the log files. I haven't installed any plugins other than Poi.
> 
> [-1726469916244.log](https://github.com/user-attachments/files/17009436/-1726469916244.log)
> 
> ![image](https://private-user-images.githubusercontent.com/160444542/367670425-9325aeab-366e-474e-8474-ed01e2466365.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY2ODUwNjIsIm5iZiI6MTcyNjY4NDc2MiwicGF0aCI6Ii8xNjA0NDQ1NDIvMzY3NjcwNDI1LTkzMjVhZWFiLTM2NmUtNDc0ZS04NDc0LWVkMDFlMjQ2NjM2NS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxOFQxODM5MjJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03OTdmNTNlMGIwOGJlYzVjZTc2MjYwMDU0NzlhY2M0MjFkMDI3MmEyODk0NmFiNGE3YTQ4NDRhNTRlMjJmMzRmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.kHJ1wmHN7ClaG9aUTpYgGAsIGw8B0T4adskgzoywZro) ![image](https://private-user-images.githubusercontent.com/160444542/367670709-738d89ed-f25a-4eef-bef1-93d3c232182d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY2ODUwNjIsIm5iZiI6MTcyNjY4NDc2MiwicGF0aCI6Ii8xNjA0NDQ1NDIvMzY3NjcwNzA5LTczOGQ4OWVkLWYyNWEtNGVlZi1iZWYxLTkzZDNjMjMyMTgyZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxOFQxODM5MjJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zYjI1MmQxM2Y0ZmQ5MDU4N2M2MDljYzk1MDQwZjQzMzFhMzg2MTFiODdlZTMyNmFkMjNlM2E5YjlkM2JkYWVlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.hxJ8FwlYecJhWDULpnQd_H0ac4agh2pDsUUdALwNf30) ![image](https://private-user-images.githubusercontent.com/160444542/367670748-9e2f4faa-6f2f-411e-beee-f84fa590679c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY2ODUwNjIsIm5iZiI6MTcyNjY4NDc2MiwicGF0aCI6Ii8xNjA0NDQ1NDIvMzY3NjcwNzQ4LTllMmY0ZmFhLTZmMmYtNDExZS1iZWVlLWY4NGZhNTkwNjc5Yy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxOFQxODM5MjJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zNWEwMzQzYTk5OWI5ZTA0OWM1MmRhYmQyMTdlOTIwMDQ3NWY0OTNhYzg1OTllMTAyNWFmZGQ4NmZkNTM0ZmRlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.1oLhBW-elQCO2GCDovw_a411riUEW7mimwbUszLJze0) ![image](https://private-user-images.githubusercontent.com/160444542/367670783-2dccd1f2-302d-47f5-8270-ff5618f8863c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY2ODUwNjIsIm5iZiI6MTcyNjY4NDc2MiwicGF0aCI6Ii8xNjA0NDQ1NDIvMzY3NjcwNzgzLTJkY2NkMWYyLTMwMmQtNDdmNS04MjcwLWZmNTYxOGY4ODYzYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxOFQxODM5MjJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04NGJkZDNjMmFlYzEwMzhjNGUzYmMzYjVmOTgzYjNmNWEzYjAxZWI3ZTAzNGI2YmVmMDQ4YjFjYTFhZTczZjVkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.LFbTExVS8RV8_XQaMseg88rE20eMez5QSUnCSnirh-A)

可以试试看安全模式启动（在开始菜单里面会有快捷方式）然后在插件页面选择修复插件看看

**Comment by SalveRobert** [comment]
HI，我找不到安全模式
![image](https://github.com/user-attachments/assets/2b4fc686-1098-4445-b44f-409ab22bf46d)
![image](https://github.com/user-attachments/assets/9e56fc04-becc-4e12-a024-4f4463f117fe)
![image](https://github.com/user-attachments/assets/ae4f7d32-a470-4b3c-bb35-a3c49529e617)

**Comment by KochiyaOcean** [comment]
> HI，我找不到安全模式 ![image](https://private-user-images.githubusercontent.com/160444542/369359299-2b4fc686-1098-4445-b44f-409ab22bf46d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY5MzQ3MzksIm5iZiI6MTcyNjkzNDQzOSwicGF0aCI6Ii8xNjA0NDQ1NDIvMzY5MzU5Mjk5LTJiNGZjNjg2LTEwOTgtNDQ0NS1iNDRmLTQwOWFiMjJiZjQ2ZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyMVQxNjAwMzlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lNmNhMTAxNTc1MjY1ZDMyZDViODAyOTJjNDkyZmIwNzNlMWYzOWYxMDM0NmZlOTE1MmI2YjcwNjA2ZGJkYzQzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.tkUNdiQyRXLnDm_g-6qkJOps--bP294aHeXj8VOTOLc) ![image](https://private-user-images.githubusercontent.com/160444542/369359494-9e56fc04-becc-4e12-a024-4f4463f117fe.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY5MzQ3MzksIm5iZiI6MTcyNjkzNDQzOSwicGF0aCI6Ii8xNjA0NDQ1NDIvMzY5MzU5NDk0LTllNTZmYzA0LWJlY2MtNGUxMi1hMDI0LTRmNDQ2M2YxMTdmZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyMVQxNjAwMzlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zNzI2NjY1YjY1ODc1YmVkZWQ2ODdhZGExNWFiNDA4OWQyOTE4YTA4MGE1MTZiZjNmMjk4MThkMDU1ZWEwNDA2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.wyoP9lXB8DXALWAtiSR8NsBqfVncSgLBIEAw5tI9cPc) ![image](https://private-user-images.githubusercontent.com/160444542/369359804-ae4f7d32-a470-4b3c-bb35-a3c49529e617.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY5MzQ3MzksIm5iZiI6MTcyNjkzNDQzOSwicGF0aCI6Ii8xNjA0NDQ1NDIvMzY5MzU5ODA0LWFlNGY3ZDMyLWE0NzAtNGIzYy1iYjM1LWEzYzQ5NTI5ZTYxNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyMVQxNjAwMzlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yZTYwM2RhNDQ3NzBlNzNkNjdhNTQ1M2Y1YWU4NWZjMmNmYzlhYWU2OWI3MmExZmU2ZGJiNmM5ZDk3NzNlMGU2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.zxWrhU_RLkIMA7KNJl9OE0v-emCz1EilMEO85UOYfKI)

如果不行的话可以尝试直接删除 `%appdata%/poi/plugins`
