### ISSUE TITLE
登录慢的出奇，而且打开后是账户登录界面

### ISSUE THREAD

**Issue by hy1996** [poooi/poi#257]
每天打开后就是账户登录界面，又要重输入一次账户和密码，这是否算是一个bug呢？

**Comment by magicae** [comment]
我每天点开都是直接登录游戏的 你用的代理是？

**Comment by hy1996** [comment]
背锅go

**Comment by magicae** [comment]
背锅go有很多包没有代理 慢是很正常的 不属于poi的问题

**Comment by hy1996** [comment]
主要是想问打开后重新登录的问题，我删了重下了一次，不知道会不会好点

**Comment by magicae** [comment]
@hy1996 背锅go有很多页面加载需要的包都没有代理，重新登录应该是因为最近背锅go的https线路不太稳定，换个线路应该好些。
