### ISSUE TITLE
Error in loading Poi Viewer 

### ISSUE THREAD

**Issue by Jetset117** [poooi/poi#2571]
poi version:** 10.9.2

OS: Windows 10

For Windows 10 users, please specify your build version (can be obtained through `winver` command)
--> OS Build 19045.5131

The problem you've met: Login to white screen game doesn't load. only english patch is loaded into Poi but even taking it off doesn't fix the issue.

Error in dev tools shows a parse error and that it can't load the map. Below is an example of the error. It is erroring every item as it tries to load source map.

How to reproduce, or any information that might be related:**
Login and it fails to load 
Please provide a screenshot of developer tool's console tab, if possible.
To open the dev tool, press ctrl + shift + i (⌥ + ⌘ + i for macOS), or the leftmost gear button on the info bar below the game area.
-->
![Capture](https://github.com/user-attachments/assets/405d72e2-66a8-4652-abbf-1cad1f644c6a)

**Comment by KochiyaOcean** [comment]
@Jetset117 Check your url to ensure it's http, not https. The game is just not https ready

**Comment by KochiyaOcean** [comment]
@Jetset117 All of them are not related, just ignore

**Comment by Jetset117** [comment]
@KochiyaOcean After the change it is still not loading. the link is HTTP but I'm getting the same yellow errors

12:25:07.622: Socket error Error: write ECONNABORTED
12:25:06.706: Srvsocket error Error: This socket has been ended by the other party

Those are what I am seeing in KCCacheProxy

**Comment by Jetset117** [comment]
![image](https://github.com/user-attachments/assets/49eab1c2-f789-4ad9-8261-6809adb3dc51)
@KochiyaOcean  This is a new error

**Comment by KagamiChan** [comment]
that's irrelevant too.

could you please **right** click on the devtools button and show us the screenshot there?

**Comment by Jetset117** [comment]
Is there anything specific I should be looking for? @KagamiChan 
![image](https://github.com/user-attachments/assets/5c356210-bae1-4f24-8efb-1c343e3472c6)

**Comment by KagamiChan** [comment]
please right click this one
<img width="122" alt="image" src="https://github.com/user-attachments/assets/1b36c0fc-e036-4a16-9b83-b6a6266f888d">
 a different devtools window would open, and in the console there might be something useful

**Comment by Jetset117** [comment]
@KagamiChan the image above is from when you open the devtool

**Comment by Jetset117** [comment]
![image](https://github.com/user-attachments/assets/1fd7d967-be95-4cdd-adc0-524d6c32c95b)

**Comment by KagamiChan** [comment]
I mean, you need to **right click**

**Comment by Jetset117** [comment]
This is what I got when I right clicked
![image](https://github.com/user-attachments/assets/26c82c03-2f79-4302-953a-665a2d89cb90)

**Comment by KagamiChan** [comment]
Thanks, from the logs here it seems that there's something wrong with your proxy
<img width="594" alt="image" src="https://github.com/user-attachments/assets/aaf3794e-2257-4e8d-a149-4e80263c480f">

**Comment by Jetset117** [comment]
Is there a way to fix this?

**Comment by Jetset117** [comment]
@KagamiChan I got it to work, I set the Proxy to none and it booted up fine

**Comment by KagamiChan** [comment]
glad to know that, I'm closing this ticket
