### ISSUE TITLE
希望在联合舰队中出现退避时给予显示

### ISSUE THREAD

**Issue by hz359lw** [poooi/poi#258]
联合舰队退避后的油弹和状态值不能立刻更新，而且现在在贴吧上有看到退避不成功导致沉船的情况，希望能在界面上给予明确显示。

**Comment by Wafer-Li** [comment]
See here #250

**Comment by aajiangzz** [comment]
不是进击以后士气会变成超低吗

**Comment by PHELiOX** [comment]
https://github.com/poooi/poi/pull/307
