### ISSUE TITLE
希望添加在线更新功能

### ISSUE THREAD

**Issue by ruiii** [poooi/poi#262]
有些用户反映老下更新包（
问：可以做个在线更新或者自动更新么？

**Comment by magicae** [comment]
做不到 尝试几百遍了

**Comment by PHELiOX** [comment]
=。= 做成了就是史上最酷功能。。

**Comment by myzWILLmake** [comment]
试下这个？ https://github.com/juampi92/auto-updater

**Comment by PHELiOX** [comment]
其实我想说的是hotfix，=。= 感觉在线更新也能实现hotfix
