### ISSUE TITLE
如何自定义主页？

### ISSUE THREAD

**Issue by djj200504001** [poooi/poi#263]
我使用舰队司令部，然而不能保存密码也不能修改主页，有没有什么办法可以改一下这方面的设置？

**Comment by yukixz** [comment]
暂时没提供设置项，可以改代码实现。
` poi/index.html`里替换第21行`http://www.dmm.com/netgame/social/application/-/detail/=/app_id=854854/`即可。

**Comment by magicae** [comment]
嗯 就改resources/app/index.html 里的这个网址就好了
