### ISSUE TITLE
poi浏览器异常自动关闭

### ISSUE THREAD

**Issue by xiaodiganbi** [poooi/poi#264]
bug反馈：今天交南西日常任务之后poi自动关闭了 之前也出现过一次，当时还以为是自己手滑关了就没记下当时的状况 
另外现在任务计数器已经变成了只要关闭重开就会清零 每天周常都会清零的状态……

**Comment by magicae** [comment]
我知道了 master里已经修复了。交任务后自动关闭没有稳定重现过。
