### ISSUE TITLE
App does not launch upon use of 'electron ./' when cd to poi, or when using just 'electron poi'

### ISSUE THREAD

**Issue by etrastew** [poooi/poi#266]
Hello, I've followed the instructions word for word, to get poi installed on my MacBook. I'm currently running OS X 10.8.5 Mountain Lion, and have electron installed globally. When I cd into my poi directory and execute 'electron ./' or if I just use 'electron poi' from a new terminal window, the results are:

![screen shot 2015-08-18 at 3 05 00 pm](https://cloud.githubusercontent.com/assets/13859153/9344008/839dc852-45ba-11e5-9db9-c046588403f3.png)

And as you can see, electron just closes.

Any help is appreciated!

**Comment by PHELiOX** [comment]
Electron 30.2 recommended, higher version seems has bugs. Old OSX versions are not tested, probably.

**Comment by etrastew** [comment]
Thank you very much! This solved it right away :)
