### ISSUE TITLE
3.3.0版改造Z1后异常关闭

### ISSUE THREAD

**Issue by xiaodiganbi** [poooi/poi#272]
改完以后没有立刻异常关闭，点了下补强增设又取消了，之后稍微过了片刻返回母港时浏览器异常关闭。重启之后出现了猫的画面但是自动刷新恢复正常了，是因为猫的原因吗……？（同时使用了一心二用刀剑乱舞出击中……整个都突然关闭了

**Comment by magicae** [comment]
不知道什么原因 应该是Chrome crash了

**Comment by xiaodiganbi** [comment]
更新3.3.1之后今天2-3偷油的时候自动关闭了 出击中会自动关闭有点吓人_(:з」∠)_  重启清了缓存之后闪了一下猫的画面

**Comment by magicae** [comment]
升级了一次Chrome版本，用 poi v3.5.0试试

**Comment by xiaodiganbi** [comment]
刚刚换上3.5.0还没发现啥状况……其实好像3.4.0以后就没出现过了 应该是解决了 非常感谢~

**Comment by magicae** [comment]
恭喜～
