### ISSUE TITLE
航海日志无法使用

### ISSUE THREAD

**Issue by ceesd** [poooi/poi#276]
![image](https://cloud.githubusercontent.com/assets/13891041/9390830/255c7dd6-47a6-11e5-8f5e-ac0763e28eb6.png)
这个插件在重启poi浏览器后可以正常使用一次，关闭后再次打开便是这种情况。win10x64+chrome44

**Comment by ceesd** [comment]
就我了解舰C的单格制空=[单格搭载量^1/2]*飞机制空值而不是[单格搭载量^1/2*飞机制空值]

**Comment by Wafer-Li** [comment]
1. 航海日志是chrome v8的问题，目前还没有办法解决
2. 制空值的计算公式的确是  [ (搭载量)^1/2 * (对空值) ]
![qq 20150821031921](https://cloud.githubusercontent.com/assets/12459199/9391760/aa0d00d4-47b3-11e5-8674-e88cb3d9193e.png)

**Comment by ceesd** [comment]
多谢了

**Comment by JenningsWu** [comment]
在新发布的 electron v0.31.0 中 chrome 版本升级为44，该版本解决了白屏问题。
也就是说 poi 更新 electron 版本之后就可以和白屏说拜拜啦！
（然而大概要在 poi 4.0.0 的时候才更 electron 版本，所以可能还要再等一段时间。

**Comment by Wafer-Li** [comment]
@JenningsWu 
之前升级到0.30.0的时候好像没有写到changelog里面去，如果更新上游版本的话，能不能都写上去呢？

**Comment by magicae** [comment]
Fixed by https://github.com/poooi/poi/commit/43c890a1a59b2c5545aceee513220eb764e50006 .
