### ISSUE TITLE
[Feature Request] 更改截图目录

### ISSUE THREAD

**Issue by Wafer-Li** [poooi/poi#277]
有人提到了我就说说
![qq 20150821040231](https://cloud.githubusercontent.com/assets/12459199/9392773/7a80d61e-47b9-11e5-9468-30f001eb5b35.png)

**Comment by PHELiOX** [comment]
目录现在并不能，可以先写个接口等4.0 =。=

**Comment by alvin-777** [comment]
截图目录我正在看。
统计你可以试试这个插件 https://github.com/alvin-777/poi-plugin-poi-stats/releases

**Comment by magicae** [comment]
不改截图目录了，放appdata下咯
