### ISSUE TITLE
English Version?

### ISSUE THREAD

**Issue by Nekobana** [poooi/poi#278]
i don't know what the language used in this app, can you please make english version of this app? or is there a way to change the language to english?

this app is good and i think it had potentiality to beat KCV or other Kancolle viewer/browser.
and one more think, how to enable cache?

**Comment by taroxd** [comment]
I18n is partly supported currently, but as a Chinese, I don't know how to enable it :sob:

Cache is stored in the `%APPDATA%/poi/Cache`. The button at the bottom of the window may open a wrong folder in Windows.

**Comment by Chibaheit** [comment]
you change change to the branch 4.0.0 i18n is the feature of the version 4.0.0

**Comment by Nekobana** [comment]
it's strange, everytime i starts this app, it always redownload whole kancolle data from server, wasting time. I think cache is disable or something, but when i check %appdata%\poi\cache folder, it was there.

Could someone please provide me menu translations? i don't know chinese at all

**Comment by c933103** [comment]
As stated in #149 , English support of this software have been planned for the next major version, v4.0.0. 

You can check https://github.com/poooi/poi/blob/v4.0.0/i18n/zh_CN.json for an English-Chinese translation of Chinese strings, however some items on that page might not be same as the current released version

**Comment by Nekobana** [comment]
thanks, i hope it completes as soon as posible :)

**Comment by Wafer-Li** [comment]
@Nekobana 
If you have the right cache files, you can place them in `root_of_poi/cache`.  This dir will be automatically open when you click the button which contains a thunder icon.
It might resolve the redownload problem.
If not, you might need to download the cache files from here:
http://pan.baidu.com/s/1bnjUJ0r

**Comment by magicae** [comment]
Merge this into https://github.com/poooi/poi/issues/149
