### ISSUE TITLE
CPU占用异常

### ISSUE THREAD

**Issue by dorasir** [poooi/poi#282]
机型为Retina MacbookPro Late2013，系统为OS X10.10.2，没有安装使用除chrome自带以外的Flash插件，经常会有占用莫名高并且卡顿的现象发生
<img width="912" alt="screen shot 2015-08-21 at 20 23 01" src="https://cloud.githubusercontent.com/assets/3439187/9408237/7120bb40-4843-11e5-9a9d-adb90f58a827.png">

**Comment by yukixz** [comment]
mac 上跑 flash 就是 CPU 占用高，找 Jobs 投诉去
你需要解决的是 kernel_task 的问题

**Comment by PHELiOX** [comment]
mac系的日常

**Comment by magicae** [comment]
Mac自身对Flash的支持就不是很好。在Mac下CPU占用最高的是poi内置的Chrome用的Pepper Flash。这点无能为力
