### ISSUE TITLE
希望下个版本的UI的改变（个人

### ISSUE THREAD

**Issue by Dream41** [poooi/poi#283]
1、远征状态栏后面可以添加一个div或者span显示一下234队的状态，目前最新版（v3.3.1）必须要切换到舰队标签栏才能看到，有可能会导致收了远征之后去干别的了然后回来之后误以为自己已经补给了然后把舰队送出去的尴尬（别问我是怎么知道的）
2、未卜先知这个插件个人觉得可以和舰队标签栏做一下整合（考虑部分用户不喜欢剧透可以做一个类似checkbox之类的来做开关）
3、大破进击的提示以及大破船上面装备的提示（包含打洞），不知道以前的版本有没有这个功能，我觉得这个是有必要的
4、未卜先知的插件中能不能加上路径点已经路径点的性质（战斗，资源，漩涡，能动分歧，战斗回避）的剧透
目前就是这样_(:з」∠)_

**Comment by magicae** [comment]
1. ok 由于主面板即将大改，这个纳入4.0.0计划
3. 目前逻辑是非退避且不携带损管才会提示

其余的和插件有关 需要更多讨论

**Comment by KochiyaOcean** [comment]
1、已经实现，请等待 4.0.0
2、@吃吧
3、已经实现，请等待 4.0.0
4、因为现在的 API 限制所以并无意义

**Comment by PHELiOX** [comment]
https://github.com/poooi/poi/pull/307
https://github.com/poooi/poi/pull/298
