### ISSUE TITLE
Refresh in any window will only reload the main kancolle page

### ISSUE THREAD

**Issue by alvin-777** [poooi/poi#287]
Version 3.3.1

To reproduce:
* Open any plugin that creates a new window. Eg, 一心二用.
* Click "reload" from menu, or press the shortcut key (when the plugin window is active).

**Comment by magicae** [comment]
应该是子窗口共用了主窗口菜单栏的问题。

**Comment by alvin-777** [comment]
我今天正好在看这个。是因为这段code
```
        {
          label: 'Reload'
          accelerator: 'CmdOrCtrl+R'
          click: ->
            $('kan-game webview').reload()
        },
```
最新版的electron应该有办法fix。
