### ISSUE TITLE
Custom CSS doesn't take effect on plugins with a popup

### ISSUE THREAD

**Issue by Dibel** [poooi/poi#288]
I modified EXROOT/hack/custom.css to change the font, but it only takes effect on main page, including navbar and panels. It doesn't work on plugins with a popup, including ShipInfo, ItemInfo, Logbook and NewWindow.

Here is the screenshot. I altered the font from STHei to PingFang. You can see the logbook window's font is still STHei while the main page's font has successfully changed to PingFang.
<img width="467" alt="2015-08-22 02 07 33" src="https://cloud.githubusercontent.com/assets/3395113/9415595/0529bf88-4873-11e5-836c-2e90c54f8de4.png">

**Comment by magicae** [comment]
It need the plugin's support. I can't do it.
