### ISSUE TITLE
关于POI 3.3.1版本窗口最前置的问题

### ISSUE THREAD

**Issue by ColorValue** [poooi/poi#295]
可 能否选择最前置这个功能

**Comment by yukixz** [comment]
你一定是不小心点到了
![screen shot 2015-08-22 at 10 45 08 pm](https://cloud.githubusercontent.com/assets/3337921/9424444/7910702a-491f-11e5-9594-8c4b3c286f0c.png)

**Comment by ColorValue** [comment]
好吧 我犯糊涂 感谢提醒
