### ISSUE TITLE
猫了之后点击POI的刷新按钮，显示功能会失效

### ISSUE THREAD

**Issue by fishsama** [poooi/poi#297]
我在建造完成的时候点船经常会猫（这个应该是官方问题？我用网页和KCV都会这样），现在问题是，POI的设置内的基本设置中有一个刷新的按钮，点击之后确实可以刷新，但是刷新之后概况和舰队两个面板的数据就完全不会更新，维持在原有的状态，游戏内变更数据也不会更新，相当于失效了。我的版本是3.3.1。

**Comment by magicae** [comment]
在这儿应该修复了 https://github.com/poooi/poi/commit/120a291fe58b80538eed157a9dc2b231871b08f3
