### ISSUE TITLE
希望加入设置本地cookies的功能

### ISSUE THREAD

**Issue by djj200504001** [poooi/poi#299]
kcv也有这个功能，而且，在poi的开发者界面显示的是整个页面的代码，而不是网页里面的代码，不能直接找到token，很不习惯
最后，祝舰队登录器的站长能在三次元找到一个好妹子，嗯~

**Comment by KochiyaOcean** [comment]
右击开发者工具图标就可以了

**Comment by djj200504001** [comment]
还有…新版本poi打开时有一定概率最下面的工具条会消失不见，希望检查一下

**Comment by magicae** [comment]
右击开发者工具图标就可以了
