### ISSUE TITLE
win8 64位固定到任务栏失常

### ISSUE THREAD

**Issue by nagaho5** [poooi/poi#300]
如果直接右键poi固定到任务烂 打开时会在任务栏上显示两个poi图标
而打开poi后，右键不会显示菜单...一般软件都会显示包含“将此程序固定到任务烂”“关闭程序”的菜单的...

**Comment by PHELiOX** [comment]
应该是electron的bug，不知道最新版修复了没

**Comment by dkwingsmt** [comment]
总之这个 bug 应该是 electron 负责的，electron 什么时候修了就修了。暂时关闭了。
