### ISSUE TITLE
希望增添设置快捷键功能

### ISSUE THREAD

**Issue by nagaho5** [poooi/poi#301]
kcv有插件可以设置快捷键，比如音量开关，舰娘一览，装备一览和截图等等。另外还有大破进击的提示也比较需要...

**Comment by PHELiOX** [comment]
音量这种酒在面板上的按钮还要快捷键？

**Comment by taroxd** [comment]
Tab 大法好

**Comment by Wafer-Li** [comment]
@magicae 
#### Feature Request
Please support to change the shortcut key, sometimes the default setting will be conflict with another software

**Comment by steveny9911** [comment]
Is it possible to have shortcuts for opening plugins?

**Comment by dkwingsmt** [comment]
@Wafer-Li 5.0.0增设了老板键的自定义。还有什么别的快捷键希望自定义吗？

**Comment by Wafer-Li** [comment]
@dkwingsmt  
:joy: ……你不 @ 我，我都忘了这么久的 issue 了。 
:flushed: 我上面说的那个其实就是老板键。 
其实我是鼠标党，并不使用什么快捷键。
只是由于在打代码的时候当时的 `ctrl + i` 的确跟一些软件的快捷键冲突了，所以才要求可不可以自定义。

对于现在能自定义老板键，我已经没有什么意见了。
