### ISSUE TITLE
APPCRASH....

### ISSUE THREAD

**Issue by w46245** [poooi/poi#303]
win7 64位系统..运行win64，和win32都会有这个提示..最开始的时候通过大力出奇迹打开过一次..然后就再也没有打开过了..求解..

 问题事件名称:	APPCRASH
  应用程序名:	poi.exe
  应用程序版本:	3.4.0.0
  应用程序时间戳:	55d6a6a6
  故障模块名称:	poi.exe
  故障模块版本:	3.4.0.0
  故障模块时间戳:	55d6a6a6
  异常代码:	80000003
  异常偏移:	0000000000082ee0
  OS 版本:	6.1.7601.2.1.0.256.1
  区域设置 ID:	2052
  其他信息 1:	bba1
  其他信息 2:	bba1ea60fdfe5ae4439aaec43c539926
  其他信息 3:	f61c
  其他信息 4:	f61c49601c3147bfb67113fcb9e72ffd

联机阅读隐私声明:
  http://go.microsoft.com/fwlink/?linkid=104288&clcid=0x0804

如果无法获取联机隐私声明，请脱机阅读我们的隐私声明:
  C:\Windows\system32\zh-CN\erofflps.txt

**Comment by magicae** [comment]
Electron的问题 修不了 只是个例
