### ISSUE TITLE
希望加入UI界面字体大小调整的功能

### ISSUE THREAD

**Issue by Sakisawa** [poooi/poi#306]
目前显示器分辨率普遍在1080p以上，导致UI界面看起来字体过小，至少比KCV要小。尤其是重要的远征和入渠时间信息，视力不佳的人在离屏幕正常距离的情况下难以做到扫一眼即可辨认。希望加入针对不同分辨率设置不同字体大小的功能方便用户。

**Comment by KochiyaOcean** [comment]
设置中选择编辑自定义 CSS，然后在弹出的文件中输入
{
    font-size: **px;
}
保存重启即可

**Comment by magicae** [comment]
设置中选择编辑自定义 CSS，然后在弹出的文件中输入
html {
  zoom: 2;
}
双倍大小

**Comment by PHELiOX** [comment]
咦，这样的话百分比缩放有望了
