### ISSUE TITLE
[Bug] 数据界面消失了？

### ISSUE THREAD

**Issue by Wafer-Li** [poooi/poi#308]
Electron v0.30.6 ia32
Win 10 x64 Pro
Commit SHA : 85c9f13ba5d03127391b60aa4165ff71be61c330

另外我原本用的 Electron v0.30.5 ，也出现了这个问题

![qq 20150826210831](https://cloud.githubusercontent.com/assets/12459199/9492916/afb0e2a8-4c36-11e5-9ad2-5b14bd8dd9c3.png)

**Comment by magicae** [comment]
git submodule foreach npm i
