### ISSUE TITLE
64位win7点3.4.0的poi.exe没反应，连错都不报

### ISSUE THREAD

**Issue by ifunu** [poooi/poi#310]
是啥原因呢

**Comment by magicae** [comment]
不知道

**Comment by igax** [comment]
Please install x86 electron. PepperFlash in poi can't be carried out by x64.

**Comment by lyfgod** [comment]
我也有这问题，64位win7，试了32位版和64位版的3.4.0的poi都没反应。
以前用3.3.0的时候也有着问题，但多试几次就启动了……

**Comment by 476210180** [comment]
Version 3.4.0 running good on Win 7 x64 SP1.
PPAPI flash plugin not installed.

**Comment by magicae** [comment]
@476210180 放在全英文目录下

**Comment by zghbssjzzhx** [comment]
安装PPAPI的flash试试，poi好像用的chrome的内核。

**Comment by KochiyaOcean** [comment]
自带一个 Pepper flash 了
