### ISSUE TITLE
3.4.0無法使用"艦隊面板"插件 (plugin-ship-panel-patcher)

### ISSUE THREAD

**Issue by Harunalive** [poooi/poi#311]
請問一下3.4.0有支援這個插件嗎?

還是現在忙著更新4.0所以比較沒空更新這樣

迫切想要使用這個插件rrrr

**Comment by dkwingsmt** [comment]
那是一个测试用的、过时的、现在已经失效的、只是因为疏忽而忘了在发布时去掉的插件……它也并不是用来完成你可能所想象的那个功能的，嗯。

**Comment by Harunalive** [comment]
了解  非常感謝回答
