### ISSUE TITLE
miniship 在小宽度下状态图标位置错误

### ISSUE THREAD

**Issue by yukixz** [poooi/poi#315]
![screenshot](https://cloud.githubusercontent.com/assets/3337921/9560842/789b5fb8-4e5d-11e5-837e-6581755024e7.jpg)
此时 `div#Miniship` 宽度为 180px。
~~屏幕小没人权~~

**Comment by KochiyaOcean** [comment]
![image](https://cloud.githubusercontent.com/assets/8194131/9561137/90c71272-4e6b-11e5-95f4-96cd80035c6c.png)
稍微增加了点人权……

**Comment by yukixz** [comment]
#(喷)
miniship 放的东西是不是有点多了=。=
（直观上完全不知道这个 icon 是什么意思

**Comment by KochiyaOcean** [comment]
锁船的状态指示，另外还有维修等

**Comment by yukixz** [comment]
调整了一下感觉这个宽度下显示完整是可以的、元素定位写的不是很好

**Comment by yukixz** [comment]
![screen shot 2015-08-29 at 4 54 10 pm](https://cloud.githubusercontent.com/assets/3337921/9561207/987991f4-4e6e-11e5-8cc3-fcdf9ff7c5ae.png)
这样子的话还是能用的= =

**Comment by KochiyaOcean** [comment]
并不觉得这是一个能用的状态……

**Comment by yukixz** [comment]
也是=。=
![screen shot 2015-08-29 at 5 01 58 pm](https://cloud.githubusercontent.com/assets/3337921/9561237/ae8a1364-4e6f-11e5-905f-a91fe4b1e2fc.png)
`div#Miniship` 为 194px、宽度压缩不下去了...

**Comment by KochiyaOcean** [comment]
决定取消剩余经验值显示了

**Comment by yukixz** [comment]
辛苦了= =
（改好之前我先拿这个用着

**Comment by KochiyaOcean** [comment]
Fixed #316
