### ISSUE TITLE
ubuntu中poi使用不能

### ISSUE THREAD

**Issue by momoxionger** [poooi/poi#318]
![2015-08-30 21 49 16](https://cloud.githubusercontent.com/assets/11884106/9567590/97d57b64-4f63-11e5-9c06-24470e2c889b.png)

在chrome中可以正常游戏（设置好代理以后，是shadowsocks）
但是在poi里面会在输入完帐号密码点击登录后一直没反应而无法进入游戏
在poi里面浏览其他dmm网页正常，速度很快（代理没问题）
在chrome中能进入游戏玩（flash没问题）
于是我就想不通了  ，问题在哪呢？

**Comment by ruiii** [comment]
会不会是dns污染 有广告覆盖到了这个页面某处导致无法点击

**Comment by momoxionger** [comment]
我试了poi自带的shadowsocks  可以使用，我用本地端口1080转发用sock5就不行，看来是sock5的问题

**Comment by momoxionger** [comment]
舰娘游戏服务器和dmm网站服务器貌似是分开的，帐号密码是加密的，而游戏过程发包貌似是http的 ，kcv4.1不能设置https可以看出来这个问题，不支持加密的ss，可能是poi的socks在这方面没做好的问题（这些是我的猜测，网络方面不是很懂，错了就当我没说）

**Comment by magicae** [comment]
我的socks5正常 ArchLinux x64

**Comment by momoxionger** [comment]
好吧  ，能玩就行 ，我不管了
