### ISSUE TITLE
舰娘信息中按舰名排序混乱

### ISSUE THREAD

**Issue by kagamiJZ** [poooi/poi#319]
舰娘信息中，选择按照舰名排序出现排序混乱的状况
以此图为例 
![default](https://cloud.githubusercontent.com/assets/14050893/9574337/75004854-4ff8-11e5-9aa7-9b78622a86eb.png)

若是按照拼音排序则：
三(san)日月、卯(mao)月、夕(xi)立
存在排序混乱

若按照日语假名排序：
ヴェールヌイ　三（み）日月　初（はつ）霜/風　卯（う）月、等
存在排序混乱

同时，按照罗马音排序也是十分混乱的(在此不详细列出)。

希望能给出具体的排序规则

**Comment by magicae** [comment]
Reference
```javascript
let a = ['啊', '波', '次', '的', '饿'];
a.sort();
console.log(a);
```
output: [ '啊', '次', '波', '的', '饿' ]

**Comment by Chibaheit** [comment]
这是根据\u 判断的?


On August 31, 2015 at 4:05:59 PM, Magica (notifications@github.com) wrote:

Reference

let a = ['啊', '波', '次', '的', '饿'];
a.sort();
console.log(a);
output: [ '啊', '次', '波', '的', '饿' ]

**Comment by Z-Shang** [comment]
目测是按 Unicode 编码排的。。。

**Comment by alvin-777** [comment]
```javascript
let a1 = ['啊', '波', '次', '的', '饿'];
a1.sort(function (a, b) { return a.localeCompare(b, "zh-CN-u-co-pinyin"); });
console.log(a1);
// output: ["啊", "波", "次", "的", "饿"]
```

```javascript
let a2 = ['江風', '照月', '瑞穂', '海風'];
// ["江風", "照月", "瑞穂", "海風"]

a2.sort();
// ["江風", "海風", "照月", "瑞穂"] (&#27743; &#28023; &#29031; &#29790;)

a2.sort(function (a, b) { return a.localeCompare(b, "zh-CN"); });
// ["海風", "江風", "瑞穂", "照月"] (Hai, Jiang, Rui, Zhao)

a2.sort(function (a, b) { return a.localeCompare(b, "ja-JP"); });
// ["海風", "江風", "照月", "瑞穂"] (う、か、て、み)
```

Optimisation for sorting large arrays:
```javascript
var collater = new Intl.Collator("ja-JP");

// ......

let a2 = ['江風', '海風', '照月', '瑞穂'];
a2.sort(collator.compare);
```

**Comment by ruiii** [comment]
ship-info fixed

**Comment by magicae** [comment]
似乎没修？

**Comment by yukixz** [comment]
没有。
https://github.com/poooi/plugin-ship-info/pull/19 只是改了舰种和等级排序。
暂时没有人去决定舰名排序时的规则。

**Comment by c933103** [comment]
按Unicode編碼的話暫且能當成八成是部首筆劃順？
