### ISSUE TITLE
内存优化

### ISSUE THREAD

**Issue by expnobody** [poooi/poi#324]
poi消耗内存严重啊。。求优化
![y 3 b5tp8gjn 9gnt 55x](https://cloud.githubusercontent.com/assets/375928/9620416/0dcac240-50e8-11e5-9407-c390bf5aeba9.png)

**Comment by KochiyaOcean** [comment]
建议你去 Google 那边要求降低 Chrome 的内存占用
Chrome 的内存占用不降下来 poi 就还得吃那么多内存

**Comment by alvin-777** [comment]
并不完全准确。
部分插件在“关闭”时并不会退出，只是隐藏而已，也就是说完全不会释放内存。
所以实在想要榨一点内存出来的话也不是完全不可能。或者关闭隐藏都做出来用户自己决定怎么办。

**Comment by magicae** [comment]
那些插件只能隐藏 做不到退出 因为要持续监听数据 目前内存优化不可能 只能关闭一些新窗口插件

**Comment by alvin-777** [comment]
改修/舰娘/装备信息这些感觉能关？
另外需要监听的插件能不能留一个监听的process，关闭render process？（只是一个摄像，不过我觉得有价值尝试一下，如果可行的话应该能够很大程度的缓解现状）

**Comment by KochiyaOcean** [comment]
重新载入 Render 的速度参照装备改修插件的打开速度
得不偿失。

**Comment by alvin-777** [comment]
是不是得不偿失是因人而异的。
你可能觉得为了省一点内存每次打开多花2秒钟是得不偿失，同样会有人觉得让一个一天开不了2次的插件占去几百M内存是得不偿失。
这就是为什么我前面提出“给出选项，让用户自己选择”
