### ISSUE TITLE
最大化之后游戏显示不正常

### ISSUE THREAD

**Issue by NeilAlpha** [poooi/poi#325]
系统Windows 10 屏幕分辨率 1080P
无意一次将poi最大化之后，再缩小，屏幕显示变成了这样，必须重启poi才能解决
![default](https://cloud.githubusercontent.com/assets/13724102/9623309/8c902492-5171-11e5-80cc-d51db2dd6a80.PNG)

**Comment by KochiyaOcean** [comment]
调整一下窗口大小就可以了

**Comment by alvin-777** [comment]
* 这确实是个bug 
* 这个bug调整窗口大小就能重现
* 不用重启，调整一下大小就消失了

**Comment by NeilAlpha** [comment]
问题解决，感谢回复
