### ISSUE TITLE
希望可以增加更改缓存目录的功能

### ISSUE THREAD

**Issue by cicimfb** [poooi/poi#327]
本人一般是用岛风GO的缓存，虽然可以把岛风GO的缓存复制到POI的缓存文件夹里，但是每次更新的话又要重新复制，希望可以增加这么一个更改缓存目录的功能，可以手动直接定位到岛风GO的缓存文件夹，这样就不用每次更新都复制了

**Comment by KochiyaOcean** [comment]
岛风Go用户直接使用岛风Go代理即可，不必复制缓存
