### ISSUE TITLE
为什么网络物理断线重连后，poi总有5~15分钟无法获取数据？

### ISSUE THREAD

**Issue by athtamis** [poooi/poi#334]
解决方法倒是很简单，静静等上十来分钟，一切就会恢复正常。

因为网卡接口氧化，经常（平均每天都能遇到）会物理性掉线。大概是接口的问题，更换了网线也没有明显了的效果，还是会断。
网络断线重新插拔连接后，只要几秒就网页能开、QQ能上、KCV能进。
只有poi长达数分钟无法连接，一直无限请求数据。
在此时间内，任何操作都无法登入游戏。比如刷新、比如关掉重开程序、比如启动vpn、比如设置poi使用http代理并重启等等。
虽然也不是什么大毛病，可是等得人很心焦啊……尤其是经常能遇见

最近一次断线，2015/09/06 03:13分恢复网络，2015/09/06 03:21分poi成功获取到数据。无法登入的时间为9分钟
系统：win7x64Ultimate
网络：路由有线连接，固定IP
poi版本：poi-v3.4.0-win-x64
连接方式：改host直连

另外提个小建议，希望疲劳度显示能更明显一点（比如未卜先知插件中那样）。舰队界面的小数字看颜色实在是很不明显…

**Comment by KochiyaOcean** [comment]
麻烦查看一下开发者工具里是否有报错信息

**Comment by athtamis** [comment]
嗯，等下次遇到的时候

**Comment by magicae** [comment]
这些报错没啥问题 都是头像没载出来。这个应该在https://github.com/poooi/poi/commit/f04a58b86de71dc44440dd8ac7eb5617931e772b 修复掉了
