### ISSUE TITLE
9月7日 维护后 关于战斗剧透

### ISSUE THREAD

**Issue by nagatoyk** [poooi/poi#335]
不知道是不是bug还是怎么了
维护前 己方舰队 出击如果是单舰队就是单舰队 联合舰队就是联合舰队
但是维护后编成了联合舰队 <明明是单舰队出击,战斗剧透的列表上己方舰队居然是两个舰队的列表>
如下图
![战斗剧透己方舰队显示错误](http://ww4.sinaimg.cn/large/64909e84jw1evtz26j3r4j20eg0ed41p.jpg)
附注: 第二列<四艘驱逐舰在远征的>

**Comment by magicae** [comment]
以后插件bug尽量在插件issue里开

**Comment by alvin-777** [comment]
pr poooi/plugin-prophet#25

**Comment by Alicese** [comment]
+1遇到相同问题了。。

**Comment by zydxn** [comment]
+1，我的也是

**Comment by zydxn** [comment]
今天又不会出现了这种情况了

**Comment by magicae** [comment]
Fixed by https://github.com/poooi/poi/commit/783d01e6b5e506893a25bc697ba78251337c8905 .
