### ISSUE TITLE
[Question] How to update this app when update the dependencies

### ISSUE THREAD

**Issue by Wafer-Li** [poooi/poi#342]
I am using the git version of this app.
I've noticed that when the dependencies was updated, the data panel just showed nothing.
I also run `npm install` `bower install` and `gulp`
It just doesn't work.
And I have to delete the whole folder and reclone it.
It's really waste of time.

How could I update this app safely without deleting the whole app?

**Comment by magicae** [comment]
`npm i`
`git submodule foreach npm i`

**Comment by Wafer-Li** [comment]
If possible, could you please add it to `README.md` for those who does not familiar with the npm package management?
