### ISSUE TITLE
未卜先知默认联合舰队

### ISSUE THREAD

**Issue by gnattu** [poooi/poi#344]
现在哪怕不是联合舰队出击也是显示二队的，而且似乎不能手动切换？

<img src="http://ww2.sinaimg.cn/large/bc69e012gw1evvw28o9tlj20d20e00td.jpg" />

**Comment by Ayaphis** [comment]
已知BUG，手动更新 未仆先知插件，或者等待下个poi版本发布

**Comment by Chibaheit** [comment]
fixed
