### ISSUE TITLE
4.0版本的几个建议

### ISSUE THREAD

**Issue by locustetc** [poooi/poi#345]
一点建议。希望开发组能看见。
第一，4.0更新了概览可以简单查看舰队，但是希望与舰队栏里的选项关联起来。
第二，希望在舰队查看、入渠建造的查看等范围内添加鼠标滚轮切换。
第三，希望在概览面板里增加自定义倒计时的插件。最好2个（20分、3分）尽量可以手动校对时间。
第四，浏览器网址一直没法按enter来打开新网址，希望添加按键。
第五，希望将网络重试次数修改为弹框确认之后再重试，或者增加一个手动点击的按钮。（我网络不稳定，经常丢包猫，曾经遇到过重试的bug，导致现在不敢开）

**Comment by Ayaphis** [comment]
@locustetc 路过问下三，倒计时的作用是什么？，看时间是泊地修理第一次结算和循环cond恢复计时，这两个倒计时与远征倒计时共享同一倒计时区域你觉得怎么样（一个舰队不可能同时泊地修理或远征或恢复cond）。校对时间的用处是？是否是校正cond恢复倒计时的偏差值，校正cond恢复倒计时的偏差可以对照各次回母港时的cond恢复情况自动校正（大概以后会写），这样的话是否还需要手动校对时间？

**Comment by djj200504001** [comment]
看了看百度盘发现4.0被删了……还想报告一下未卜先知会把第一队错误识别为一二队联合舰队的问题的

**Comment by magicae** [comment]
@djj200504001 3.5.0刚发。

**Comment by aajiangzz** [comment]
3.5和4.0是什么关系

**Comment by KochiyaOcean** [comment]
因为 4.0 的开发计划非常长所以就先发布一个 3.5.0 。 之前的 4.0.0-stage0 是测试版，离 4.0.0 正式版的计划还有很远的距离
