### ISSUE TITLE
分割组件与插件面板后希望能自动调节字体和模块大小

### ISSUE THREAD

**Issue by fishersonic** [poooi/poi#348]
现阶段分割组件与插件面板后，在窗口较小时字全挤在一团根本无法看清。希望能够随窗口大小变化自动调整字体大小和模块大小

**Comment by KochiyaOcean** [comment]
只要你会 CSS 你就能调
然而并不建议小窗口使用分割面板

**Comment by fishersonic** [comment]
谢谢解答，本人不会CSS，看来只好用回普通面板了

**Comment by KochiyaOcean** [comment]
切割面板原意是给 1600px（横向模式）以上的屏幕使用的
未来考虑加入缩放选项，不过为了不影响体验，还是建议在该尺寸以上的屏幕中使用
