### ISSUE TITLE
v3.5：疲劳回复倒计时在窗口最小化 10 分钟后停止

### ISSUE THREAD

**Issue by xupefei** [poooi/poi#349]
系统是 Windows 10 10240 x64，poi 3.5 x32 版本。

具体重现步骤：

1. 找地方打一架，比如 5-4-A。
2. 回母港后，疲劳度减少，这时倒计时开始工作，如图 1。
3. 最小化 poi 窗口。
4. 等待 15 分钟后回到 poi 窗口，这时倒计时还剩 5 分钟，如图 2。

也就是说，最小化 10 分钟后，倒计时被停了。

我下载了 3.4 版本测试，并未发现此问题，于是排除 Windows 10 的嫌疑，推断是 Chromium 35 新加入的省电优化引起的。

另外，在疲劳回复倒计时停止的时候，远征归来和入渠倒计时仍然正常工作（因为仍有提示出现）。

图 1：
![1](https://cloud.githubusercontent.com/assets/1687847/9783957/b880a1ca-57da-11e5-958d-a68702dc59ac.png)

图 2：
![2](https://cloud.githubusercontent.com/assets/1687847/9783960/be09a6aa-57da-11e5-9f00-37e48403f36a.jpg)

====================================================

另外，能不能再给概览页面的舰队信息加上疲劳回复倒计时……？

**Comment by magicae** [comment]
Chrome 45的问题吗？我不知道诶。。。

**Comment by xupefei** [comment]
奇怪的是远征和修理倒计时工作正常……两者实现有什么不同吗……

**Comment by PHELiOX** [comment]
前一个由于显示的需要用的是setInterval吧
