### ISSUE TITLE
新默认主题下难以分辨舰队状态

### ISSUE THREAD

**Issue by Wafer-Li** [poooi/poi#350]
![qq 20150910192629](https://cloud.githubusercontent.com/assets/12459199/9786041/e4c4f0da-57f1-11e5-9613-2674c26f5a81.png)
如图，我的第一舰队正在出击，其余舰队正在远征，然而在本主题下，体现不出其区别。
希望就这一点进行一些改良。
<del>毕竟是一个默认主题嘛。</del>

**Comment by magicae** [comment]
https://github.com/govizlora/theme-papercyan
