### ISSUE TITLE
astrill不支持poi，google能上而poi不能，不知道有什么解决办法吗

### ISSUE THREAD

**Issue by noneshadow** [poooi/poi#355]

**Comment by KochiyaOcean** [comment]
代理设置选择无代理一般是没问题的

**Comment by noneshadow** [comment]
那请问poi不支持hd高清缓存和汉化吗?岛风go支持astrill吗？


通过 Android 版 Outlook 发送





On Sat, Sep 12, 2015 at 10:35 PM -0700, "東風谷オーシャン" <notifications@github.com> wrote:
代理设置选择无代理一般是没问题的

---

**Comment by athtamis** [comment]
问一下楼主HD界面和汉化界面从哪里获得？
百度贴吧上见过很多预告帖，然后就……没看到然后了

**Comment by magicae** [comment]
不会支持岛风go系列的例如hd高清缓存、汉化之类的东西。

**Comment by KochiyaOcean** [comment]
岛风 Go 系列的深入魔改大都涉及改包，poi 目前没有修改的打算
