### ISSUE TITLE
关于cond的颜色和特效

### ISSUE THREAD

**Issue by alvin-777** [poooi/poi#359]
这个问题现在争议比较大，所以我觉得应该先讨论出一套多数人赞同的方案之后再作修改。

目前git最新版poi使用的方案是，Cond 根据数值分为了7段：
* 0~19
* 20~29
* 30~39
* 40~48
* 49
* 50~52
* 53~100

在paperdark下的效果如下
![image](https://cloud.githubusercontent.com/assets/13615512/9893582/31ecf640-5c5d-11e5-889c-503c89105cc1.png)
在papercyan下的效果如下
![image](https://cloud.githubusercontent.com/assets/13615512/9893599/59b9e4e4-5c5d-11e5-9f83-f01d2a6ad3bb.png)

因为cond50～52使用的是主题默认字体颜色，而papercyan的默认颜色较淡的缘故，使得cond50～52在papercyan下的显示可能给人一种模糊的错觉。
我略做调整之后在papercyan下的效果如下
![image](https://cloud.githubusercontent.com/assets/13615512/9893660/2f9cbdc0-5c5e-11e5-965e-ad37c8f8cd7b.png)

如果有人有更好的配色方案敬请提出（请附上效果截图）。

目前最新版的cond style在poi主体的app.css里面，可通过修改自定义css轻松覆盖（最新版在自定义css保存之后只需切换一下theme即可生效，不必重启poi）

我昨晚特地写了个插件 [Cond Colours](https://github.com/alvin-777/poi-plugin-cond-colours/releases/latest)，可以方便查看调整自定义css之后的cond效果，以及可以方便你们截图。

个人认为配色方案需要满足的最低标准：
1. 7个区间的用色区别较明显，肉眼能够轻松辨别
2. 至少给出paperdark和papercyan下的效果图（我想这两种theme应该是使用人数最多的）
（当然如果有人对这两点要求有意见或者补充也请提出）

希望这次能有一个大家都满意的结果。

**Comment by dkwingsmt** [comment]
哇这文章写得赞哭了

**Comment by ruiii** [comment]
我的建议是移除shadow。
不知道为什么楼主那么坚持，糊得难受死了。

**Comment by alvin-777** [comment]
下面是直接移除shadow之后的效果
paperdark
![image](https://cloud.githubusercontent.com/assets/13615512/9894341/f889a098-5c65-11e5-8d4a-be91bed9c14a.png)
papercyan
![image](https://cloud.githubusercontent.com/assets/13615512/9894344/09ca08e8-5c66-11e5-94d3-d08dd7fa6a38.png)

**Comment by dkwingsmt** [comment]
唔……我觉得至少50-52不该有shadow。毕竟是假闪。

**Comment by alvin-777** [comment]
假闪对战斗无效，对远征有效，这就是为什么专门把50～52这一段分出来。
现在是靠加shadow区分49和50，去掉shadow这俩就一个色了。

**Comment by dkwingsmt** [comment]
我觉得靠shadow区分50和53比较说得通啊 0 0

50   黄色，无shadow
53   黄色，有shadow

【咦，我到底是哪一方的

**Comment by PHELiOX** [comment]
三层闪可以用不同的黄色作区分，如果说直接看可能区别不大，其实放在一起看时对比非常明显。

这种事情应该全权交给主题，本体做好cond分级和自定义支持，剩下的完全不用讨论了。

**Comment by KochiyaOcean** [comment]
其实最初发光是为了解决黄色系在白色主题上不明显的问题而设计的……为什么会变成现在这样呢

**Comment by Ayaphis** [comment]
shadow的效果并不好。能不能bold?  

此外papercyan这类伪dark下，49 50的体验非常不好。也应该有很多人提过这个问题了

**Comment by Chibaheit** [comment]
我建议直接remove 假闪与否玩多了自然知道

**Comment by ruiii** [comment]
同意吃吧观点，闪的用一个颜色就好了，而且40和49不用分吧。
刷闪和等cond的话会一直盯着数值，平时的话也不太需要区分这两个。

**Comment by dkwingsmt** [comment]
不过话说回来，对于真的想要刷6闪/12闪推图的时候，53闪有特别的引人注目的特效的话确实会比较明显一点呢……虽然没有的时候其实也完全没有关系……

**Comment by alvin-777** [comment]
@KochiyaOcean 
最初把发光加到暗主题里是为了解决剧透在联合舰队下cond根本显示不出来的问题。按照上面的分段只要颜色区别足够明显的话即使看不到cond数值也无大碍。
后来发3.5的时候不知道谁把这套配色也搬到概览和舰队面板，然后矛盾就进一步激化了。。

@dkwingsmt 
单靠shadow区别50和53一开始就试过了，然而我感觉效果并不好
![image](https://cloud.githubusercontent.com/assets/13615512/9907727/d39285ca-5cd3-11e5-8383-97c9695bb9dd.png)
特别是联合舰队看不到cond值的情况下，至少我自己不把脸凑到离屏幕30cm之内是分辨不出的。
![image](https://cloud.githubusercontent.com/assets/13615512/9907775/033d0340-5cd4-11e5-9fcc-e57949b2c7a8.png)
区分50~52和53+的主要目的并不是为了刷闪，而是连续出击的时候可以一眼就看出有没有船需要补闪，尤其是活动期间联合舰队，比起挨个点popover或者切换几个面板方便太多。

@PHELiOX 
用不同的黄色我也早试过了，效果感觉还不如上面的单靠shadow分辨。。下面是#ffff00和#ffff80的效果
![image](https://cloud.githubusercontent.com/assets/13615512/9908357/9ac063ea-5cd6-11e5-8c1c-e558b83d78dd.png)
浅了容易跟白色混淆，深了容易跟黄色混淆。。
自定义支持已经做好了，我一开始就提到了，直接在自定义css里改了就行，然而他们并不不满意。。

@Ayaphis 
3.5.0带的剧透就是带了bold效果，结果就是一大群人被闪瞎了（暗主题下bold黄色确实很亮），所以bold应该是不大可能再用了。。
我并没说过shadow就好，能不用shadow我也不想用。然而并没有人提出更好的配色方案，光是说“要改”“要去掉”并没有什么实际帮助，要是去掉shadow就能搞定的话，我也不用码这么多字了。


至于说不需要分色的。。需求摆在那里，我已经不想再重复理由了。。

**Comment by dkwingsmt** [comment]
摸摸头……嗯我也觉得比较intuitive的方法是只靠shadow区分50和53，不应该没有试过。

这个版本剧透是bold+shadow吧？可能因为被bold了的原因shadow被强化了。如果仍然只靠特效来区分50和53，但是只有bold没有shadow呢？昨天好像试过了，效果不错？

**Comment by alvin-777** [comment]
3.5.0的剧透：50－黄＋shadow，53－bold黄＋shadow（我没记错的话）
git版：50－原色＋shadow，53－黄＋shadow

只靠bold区分效果如下
![image](https://cloud.githubusercontent.com/assets/13615512/9910391/47b1467e-5ce0-11e5-927c-29e69f608950.png)
如果50和53排在一起的话相对上面几种方案好像稍稍明显一点，不过还是需要仔细辨别

另外我感觉这样多半还是有人会嫌太亮。。

**Comment by alvin-777** [comment]
试着把黄色调淡了点，感觉比上面一个效果稍好
![image](https://cloud.githubusercontent.com/assets/13615512/9910949/09e9a7a2-5ce3-11e5-8d20-3ed3e5bac4e8.png)

**Comment by dkwingsmt** [comment]
我个人能够提出的建议就是，如果要采用任何特效的话，也不要用在50上面，因为只有50以上是黄色，这已经足够独一无二了。

以及下次截图的时候把“name cond lv”都带上吧，因为只看cond的话比较短，即使“太亮”的话也不太明显，但加上名字之后比较长可能反而比较明显了。

嗯，辛苦了。

**Comment by alvin-777** [comment]
实测中。。。
