### ISSUE TITLE
当chrome播放视频时poi游戏会很卡顿

### ISSUE THREAD

**Issue by huangsinchu** [poooi/poi#360]
最近发现当我chrome浏览器开着直播（斗鱼）或者看视频（b站）时，poi玩舰娘会很卡，用其他浏览器看视频则不会，而且chrome最小化或者切换到其他标签页就不卡了，也就是只有chrome前台播放时poi会卡。
是chrome内核的省电之类的机制吗？有没有办法解决？

**Comment by Wafer-Li** [comment]
目前本人使用
Electron v0.32.3 ia32 
Win 10 x64 Pro
并没有发现此类问题，估计升级到这个版本应该能得到解决？

**Comment by yukixz** [comment]
加内存吧... 4G 内存开两个 chrome+flash 不够用的（poi 也是 chrome

**Comment by Chibaheit** [comment]
估计mac..双屏可以解决

**Comment by huangsinchu** [comment]
我是8G内存，网页再怎么开RAM也没上过80%

**Comment by PHELiOX** [comment]
应该是flash的锅，mac下双开flash CPU占用会飙升。

**解决办法是缩小窗口。**

**Comment by magicae** [comment]
我们能做的只能等待 Chrome / Electron / PepperFlash 的优化了。
