### ISSUE TITLE
舰娘信息很多問題

### ISSUE THREAD

**Issue by vax68080** [poooi/poi#364]
跟KCV比起來其他功能都很好用
唯獨"舰娘信息"
格式會錯亂  有時   種類名稱  居然對不齊
不然就是NO只顯示一半  像我不知為何只能到157  以下就沒號碼
跟KCV比起來顏色有點不明顯   並且少了  修改完否的選項

另外我比較希望有匯出EXCEL檔的功能  
感謝你的付出!!

**Comment by yukixz** [comment]
改修完成选项已有、请等新版本发布。

**Comment by ruiii** [comment]
@myzWILLmake

**Comment by PHELiOX** [comment]
excel大概不会有吧 csv可以直接导入到excel

**Comment by fifth** [comment]
感谢付出
希望能加入“改造完成”的判定，对近代化改修有重要帮助

**Comment by PHELiOX** [comment]
插件开发者交接中，可能不会短时间内更新
