### ISSUE TITLE
Memory Leak

### ISSUE THREAD

**Issue by expnobody** [poooi/poi#365]
我的电脑8g内存，开机就开着poi和qq，所有插件除了装备改修全关

poi运行第2-3天我电脑内存被吃光。。开着所有插件只需要一天半。。动作次数越高内存占用速度越快。。我实在想不到除了内存泄露之外的原因。。就算是chrome吃内存也不会一个程序吃5-6g

**Comment by magicae** [comment]
Electron有内存泄漏
