### ISSUE TITLE
关于POI卡读条的问题

### ISSUE THREAD

**Issue by Louisknight** [poooi/poi#366]
大大们 你们好 幸苦你们了

我之前用POI 一直没有问题 很顺畅 （下了岛风GO 最新的缓存包 也是秒读取 我用的是改HOST的方法上的）

可是今天上的时候 网页可以秒读取 但是POI会一直卡舰队C读取缓存的界面不动

请问下如何解决（已经清过360和IE的缓存）

谢谢

**Comment by KochiyaOcean** [comment]
如果清除缓存，请在 poi 的设置里清除

**Comment by magicae** [comment]
清poi的缓存 清其他浏览器没用
