### ISSUE TITLE
部分情况下舰娘信息不会刷新？

### ISSUE THREAD

**Issue by NeilAlpha** [poooi/poi#367]
系统Windows 10  poi 3.5.0
部分情况下，右边的状态栏信息完全不能刷新，返回母港也不行，重启poi后正常
除了自带的插件也没有安装其他任何插件
图中千代田的血量和右边的概览中血量不同
换了旗舰，右边也没有刷新
![2](https://cloud.githubusercontent.com/assets/13724102/9955889/e8972bde-5e26-11e5-967c-16872af33087.PNG)
![3](https://cloud.githubusercontent.com/assets/13724102/9955890/e8d6629a-5e26-11e5-8f46-4205dff3be9b.PNG)

**Comment by ruiii** [comment]
猫过了吗

**Comment by NeilAlpha** [comment]
并没有...

**Comment by magicae** [comment]
下次碰到这个情况的时候开下开发人员工具 看看有没有报错

**Comment by taroxd** [comment]
一般都是报一个 Cannot read property 'api_xxx' of undefined 错误

我上一次遇到这个情况时，应该是读取 api_slot 失败（但我可能记错

**Comment by Ayaphis** [comment]
目测楼上近代化改修猫了（

**Comment by PHELiOX** [comment]
肥帅不是跟踪这个bug了么

**Comment by Ayaphis** [comment]
不猫没事，感觉不能重现bug

**Comment by NeilAlpha** [comment]
今天早上问题再次出现....开发人员工具报错截图
![default](https://cloud.githubusercontent.com/assets/13724102/9978834/4ee3500e-5f7e-11e5-8c02-335104c694db.PNG)

**Comment by magicae** [comment]
https://github.com/poooi/poi/commit/120a291fe58b80538eed157a9dc2b231871b08f3
