### ISSUE TITLE
任務欄顯示6個label

### ISSUE THREAD

**Issue by robberwong** [poooi/poi#368]
我poi 3.5.0 版本，任務最多可以接5個，卻有6個位置

**Comment by ruiii** [comment]
[司令部要員](http://wikiwiki.jp/kancolle/?%A5%A2%A5%A4%A5%C6%A5%E0#middle)

**Comment by robberwong** [comment]
原來是這樣，我想問我現在按了置頂，然後關閉poi再打開，置頂的按鈕還亮這著，但沒有效果，要取消再按一下置頂才有效

**Comment by Ayaphis** [comment]
需要把第六格显示成Locked么？
https://github.com/Ayaphis/poi/commit/d20bfa0d6329f43fa8eb6b0b3a128ecd49b3e950

**Comment by magicae** [comment]
@Ayaphis 挺好的

**Comment by Ayaphis** [comment]
https://github.com/poooi/poi/pull/378  https://github.com/poooi/plugin-quest/pull/4
