### ISSUE TITLE
3.5版本在OSX下无法使用不支持SSL的代理服务器

### ISSUE THREAD

**Issue by gnattu** [poooi/poi#370]
Electron 0.32更新到了Chrome45，这个版本的Chrome默认会阻止版本不符的SSL链接,于是某些不支持SSL的本地代理服务器就悲剧了。但是对于Chrome，可以在终端输入
<pre>
/Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome --ssl-version-max=tls1
</pre>
来规避此问题，poi如何做到呢？

**Comment by magicae** [comment]
你试试poi也加这个命令行参数

**Comment by gnattu** [comment]
poi的话，我是这么输入的：
<pre>
/Applications/Poi.app/Contents/MacOS/Electron --ssl-version-max=tls1
</pre>
终端不断的跳：
<pre>
[5823:0919/212509:ERROR:ssl_client_socket_openssl.cc(1060)] handshake failed; returned -1, SSL error code 1, net_error -100
</pre>
需要SSL连接的地方（比如登录）依然是一片白屏

**Comment by magicae** [comment]
唔 看来 Chrome45 不支持 acgp 的自签证书了。

**Comment by magicae** [comment]
应该不可能修复了 Electron的版本之后应该只会升不会降

**Comment by gnattu** [comment]
Electron 0.33.2已经新增了一个Swich<code>ssl-version-fallback-min</code>,将poi的Electron升级至0.33.2后在poi的app.coffe中<code># Proxy setting</code>最后加这么一行
<pre>app.commandLine.appendSwitch 'ssl-version-fallback-min', "tls1"</pre>
就可以正常使用了
完整的Proxy Setting长这个样子：
<pre># Proxy setting
listenPort = config.get 'poi.port', 12450
app.commandLine.appendSwitch 'proxy-server', "127.0.0.1:#{listenPort}"
app.commandLine.appendSwitch 'ignore-certificate-errors'
app.commandLine.appendSwitch 'ssl-version-fallback-min', "tls1"
</pre>
我自己整合0.33.2版Electron的3.5版poi,这个是OS X版的
<url>http://t.cn/RySOGhE</url>
