### ISSUE TITLE
请问poi可以自定义缓存位置吗？

### ISSUE THREAD

**Issue by ok8634673** [poooi/poi#374]
win8系统强制关机的话 缓存需要重新下载。

**Comment by magicae** [comment]
不能 缓存是Chrome内置的缓存

**Comment by ok8634673** [comment]
@magicae 我去岛风go下了个缓存包放到cache那里了 暂时能解决问题。不过缺点对内存不大的机子不算友好。曾经用过kcv 也有相关插件可以缓存到安装文件夹根目录，不知道poi能开发这种插件的可能性大不大呢？
