### ISSUE TITLE
氪金道具

### ISSUE THREAD

**Issue by FungJiHsu** [poooi/poi#375]
氪金道具點擊購買沒有反應
換其他瀏覽器正常

還有提議增加一個逆向自適應的按鈕，這樣方便查餘額和去其他頁面

**Comment by ruiii** [comment]
重启可以解决点击购买没反应 原因我不清楚
查余额和去其他页面可以使用一心二用插件

**Comment by ruiii** [comment]
重启可以解决点击购买没反应 原因我不清楚
查余额和去其他页面可以使用一心二用插件

**Comment by KochiyaOcean** [comment]
![image](https://cloud.githubusercontent.com/assets/8194131/9987852/02e92416-607e-11e5-8804-30d0081d0ea9.png)
怀疑是网络问题

**Comment by FungJiHsu** [comment]
@KochiyaOcean 都說了換其他瀏覽器正常...

**Comment by magicae** [comment]
我这儿没问题。只能说网络问题了。

**Comment by KochiyaOcean** [comment]
@FungJiHsu 就像那个经典的日经问题“岛风Go为什么不能自动适配”一样可能是因为网络环境的微小差异造成的
