### ISSUE TITLE
請問如何查詢制空以及索敵

### ISSUE THREAD

**Issue by mm770912** [poooi/poi#381]
請問如何查詢制空以及索敵

**Comment by dkwingsmt** [comment]
舰队面板，第一行。

**Comment by mm770912** [comment]
哪個是哪個？

**Comment by Wafer-Li** [comment]
![qq 20150923122017](https://cloud.githubusercontent.com/assets/12459199/10037184/7a4b10b2-61ed-11e5-8ad5-7d30281f153c.png)
