### ISSUE TITLE
桌面通知的 logo 不见了？

### ISSUE THREAD

**Issue by Wafer-Li** [poooi/poi#386]
Electron v0.32.3 ia32
Win 10 Pro
commit SHA: a84285e243d2dbf1a6b6a157ee42d361b03cca1d

![qq 20150925235636](https://cloud.githubusercontent.com/assets/12459199/10103829/26181b02-63e1-11e5-9e34-844a324c19f4.png)

**Comment by KochiyaOcean** [comment]
最新的 Git 版么？资源文件的位置修改了，需要叫吃吧修复一下
另外这个通知是来自未卜先知插件的

**Comment by Wafer-Li** [comment]
恩……的确只有大破通知会没掉logo

**Comment by Wafer-Li** [comment]
checked.
