### ISSUE TITLE
优化运行速度

### ISSUE THREAD

**Issue by JenningsWu** [poooi/poi#387]
重构界面之后运行速度有所减慢，需要重新进行优化。
核心思想大概是**避免界面进行不必要的render**。

具体为：
- [x] 只显示miniPaneBody时，禁止paneBody的render
- [x] 显示paneBody时，因为概览面板此时隐藏，禁止概览面板元素render
- [ ] 将概览面板中的倒计时由react改为DOM操作。
  - 是否可行？
- [ ] 入渠和建造部分，不显示的不render。
- [ ] 优化概览面板render事项，汇总分析api，仅在需要更新时更新。即精简render次数。
  - 在哪几个api时，资源部分需要刷新。
  - 在哪几个api时，澡堂部分需要刷新。
  - 在哪几个api时，建造部分需要刷新。
  - 在哪几个api时，远征部分需要刷新。
  - 在哪几个api时，任务部分需要刷新。

**Comment by JenningsWu** [comment]
> 只显示miniPaneBody时，禁止paneBody的render
效率对比：
前：
![p f9a _mx 6u231a 0lo kx](https://cloud.githubusercontent.com/assets/6861365/10113905/87cf5bbe-639e-11e5-9f39-44bff819c655.png)
后：
![ve2pz _lk58zlib qz 1 q](https://cloud.githubusercontent.com/assets/6861365/10113906/8d98c7ba-639e-11e5-8e56-3f84aaffcba9.png)

**Comment by KochiyaOcean** [comment]
话说怎么显示 render 时间的

**Comment by JenningsWu** [comment]
```
componentWillUpdate: (nextProps, nextState) ->
  @nowTime = (new Date()).getTime()
componentDidUpdate: (prevProps, prevState) ->
  cur = (new Date()).getTime()
  console.log "the cost of ship-module's render: #{cur-@nowTime}ms" if process.env.DEBUG?
```
我在miniShip里加入了这段代码，用来显示每次miniShip render的时间。

**Comment by PHELiOX** [comment]
后端逻辑不是还没整合吗 =。= 又开始优化了？

**Comment by JenningsWu** [comment]
话说有两个问题啊…
1. 记得之前有过把倒计时改成纯DOM操作的尝试？当时最后是个什么结果来着，好像说碰到了问题？
2. 要做到最大程度精简render次数，需要总结一个api列表，就是上面提到的“哪些api与哪些信息有关”。这个要协作一下，总结个文档？

**Comment by JenningsWu** [comment]
诶，后端逻辑计划要怎么个改法？会涉及到现有界面么？
以为界面这部分差不多了，就先加了些简单有效的优化。

**Comment by PHELiOX** [comment]
呃 倒计时好像是独立成模块效率不会更高？后端逻辑主要是倒计时部分打算重写，另外把 panebody里那堆复杂的逻辑清理一下 =。=
我得国庆再动手。。还有人搞这个么

**Comment by JenningsWu** [comment]
倒计时独立模块那个是把每个倒计时都单独抽成一个react类，这样render只影响倒计时数字，以尽量减少render界面的范围。见 splited-countdown-class 这个branch。但这样做增加了render的次数，而render本身的固定开销也挺可观的…所以效率很一般。
如果把倒计时改成纯DOM操作的话，可以避免render本身的固定开销，理论上大概效率上更高一些。只是记得之前曾有人做过这种尝试，好像后来出问题了？又改回来了。

目前修改的是概览面板中“资源”、“舰队mini”、”入渠“、”建造“、”远征“、”任务“这几个部分以及”舰队面板“模块什么时候刷新的问题，不涉及各个模块自身如何实现。看起来是不冲突的？
目前简单的几条已经做完了，剩下的也可以等以后再说( ͡° ͜ʖ ͡°) ☆

**Comment by KochiyaOcean** [comment]
学姐弃坑后端预计的改动计划都废除了，按照现在的标准改就行了<(=OᆸO=)>

**Comment by PHELiOX** [comment]
嗯 概览下的各面板修改是不冲突的 做吧做吧 =。=

**Comment by magicae** [comment]
http://facebook.github.io/immutable-js/

**Comment by KochiyaOcean** [comment]
@JenningsWu 
吴钩老师你这边写的有一个问题
miniship 的显示模式除了点击按钮切换以外还有使用 ctrl/cmd+1/2 切换的方法
在使用这种方法时面板无法侦测到 @state.show 的变动，会造成数据无法刷新
例：在显示详细面板的状态下接受任务，再使用 ctrl+1 切换回简略面板，此时任务面板的任务不会刷新，只有在点击切换按钮再切换后才会刷新。
如下图所示
![image](https://cloud.githubusercontent.com/assets/8194131/10117860/9d12de9c-6498-11e5-9030-e6a2a86806e1.png)

**Comment by alvin-777** [comment]
直接改DOM大概并不会更快？https://facebook.github.io/react/docs/advanced-performance.html
另外直接改DOM的话会不会让React的Virtual DOM陷入混乱？

统一countdown的话能不能让主process每秒发一个‘tick’的event，各panel 自己register那个event 刷新就是了？（感觉不会有什么性能的改善，只是统一做法而已）

另外我有点想重写入渠／建造panel，不知道有没有其他人打算动这块。。？

**Comment by PHELiOX** [comment]
你可以先把思路弄出来看看，或者样品。。
主面板天天都有人盯着要改。。
