### ISSUE TITLE
Flash 卡住问题

### ISSUE THREAD

**Issue by Wafer-Li** [poooi/poi#390]
Electron v0.32.3 ia32
Win 10  x64 Pro
Commit SHA: 4f9393f6eace350e269d3651787406619b48d0ab

最近几天经常出现这种情况，玩着玩着 Flash 就卡住了。
**画面静止、游戏声音停止，但是其他按钮（数据区域）可以正常操作。**

试着缩放了一下窗口，会出现如图的情况
![qq 20150927040010](https://cloud.githubusercontent.com/assets/12459199/10119289/d3bb0f12-64cc-11e5-9cb9-a14dd0e23b1b.png)

但是开发工具却并没有报什么错误？
![qq 20150927040037](https://cloud.githubusercontent.com/assets/12459199/10119290/ed62f524-64cc-11e5-85eb-b306fb104ac4.png)

**Comment by gnattu** [comment]
cmd里启动poi，输入以下参数看看？
<pre>poi.exe --disable-gpu --disable-gpu-compositing</pre>

**Comment by Wafer-Li** [comment]
这是个偶发情况，不一定能重现成功。不过我可以尝试着先看看

**Comment by Wafer-Li** [comment]
似乎重现成功了，CMD 输出在 http://pastebin.com/M2UWjDkG

**Comment by gnattu** [comment]
应该是PepperFlash的锅。。。这个在原版Chrome下也时有发生。你可以尝试用Adobe官方的ppapi插件（通常是一个叫NPSWF32_XXXX.dll)替换掉poi中的pepflashplayer.dll文件路径请善用搜索功能

**Comment by Wafer-Li** [comment]
Ok, I see.

**Comment by Wafer-Li** [comment]
嗯……今天晚上又试着重现了一遍，发现 CMD 的 log 和这个 bug 没有什么关系。
这几天找到的唯一的共同点应该是 **接受了过多的鼠标点击事件之后** 才出现的 卡住问题。
另外每次都会检测到内存泄露问题，会不会是这个的锅呢？

本 bug 在我这里的出现率已经上升到每启动程序期间必定有一次了，希望能予以解决。

**Comment by Wafer-Li** [comment]
It seems to solved
