### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by lsdyz0301** [poooi/poi#395]
笔记本用纵向排版感觉排版还可以优化。
提督名那行右边很空，而下面的资源又占了很大的地方。完全可以像kcv一样，这些信息只占一行。
另外概览等四个标签，我觉得竖着放在右边会更好。任务远征入渠这列感觉没必要这么宽（记得kcv是一共三列）。

**Comment by gnattu** [comment]
小屏幕建议横向排版，现在的页面布局在横向排版下空间利用率是最高的

**Comment by lsdyz0301** [comment]
右边还想留着看动画之类的

**Comment by KochiyaOcean** [comment]
舰队概览硬性吃 320px 左右的高度，高度上没什么缩减空间。
纵向 tab 效果不尽如人意。
