### ISSUE TITLE
作为一个外行 想反映几个bug

### ISSUE THREAD

**Issue by infter** [poooi/poi#396]
1，在设置选项卡中 切换纵版布局和横版布局后 回到概览页 再切换入渠建造选项卡  之后发现概览页读取的信息全部消失
2，猫了一次后 点刷新 重新进入游戏 有时会发现概览页的信息不再刷新

不知道这些bug大家有没有遇到过 还是我自己系统的问题 如果bug确实存在 还希望能够修复

**Comment by infter** [comment]
对了 poi版本 应该是3.5.0 系统win7旗舰版

**Comment by KochiyaOcean** [comment]
1、切换横纵布局后需要重启以完全生效
2、已经修复，请等待下个版本

**Comment by infter** [comment]
感谢开发组回复 希望这个项目越做越好
