### ISSUE TITLE
【請求】增添緩衝List TXT

### ISSUE THREAD

**Issue by KyoriAsh** [poooi/poi#397]
就如KanColleCacher的那個生成緩衝List的TXT文檔那樣，這樣以後也方便一些人自行尋找SWF的列表。

**Comment by KochiyaOcean** [comment]
poi 使用的 Chrome 内核和 KCV 的 IE 内核缓存机制不同
它的缓存长这样：
![image](https://cloud.githubusercontent.com/assets/8194131/10126294/1bb84780-65c2-11e5-867d-2505f436fffd.png)
（以下略
