### ISSUE TITLE
关于启动时保留上次关闭时位置的一个问题

### ISSUE THREAD

**Issue by SuperHentai** [poooi/poi#407]
建议给出选项，让用户选择在屏幕中间启动还是在原位置启动。
因为本人是双屏，经常把poi放在第二屏，当移除第二屏以后（比如把电脑带出去的时候），打开程序就会发现他在屏幕外，必须手动修改配置文件，甚为不便。
反映这样一个问题，期待能够得到回应，谢谢~

**Comment by PHELiOX** [comment]
这个行为应该是系统控制的，建议你不外接屏幕的时候把现实模式改成单屏解决。

**Comment by magicae** [comment]
https://github.com/poooi/poi/blob/master/app.coffee#L72-L73
这边需要判断一下在不在primary display的有效范围内。

**Comment by KagamiChan** [comment]
fixed
