### ISSUE TITLE
[Request] Add keymap description to Wiki Page

### ISSUE THREAD

**Issue by Wafer-Li** [poooi/poi#409]
Could you please add keymap to Wiki Page, or allow the user to modify the shortcut key?
I am always confused about that.

**Comment by PHELiOX** [comment]
Why would you confused about wiki hotkey? And in which window will you open the wiki page?

**Comment by alvin-777** [comment]
I think what he wants is documentation for all shortcut keys.

**Comment by Wafer-Li** [comment]
@alvin-777  is right.
@PHELiOX 
The Wiki Page I mean is the **repo Wiki Page** not the kancolle wiki page.

**Comment by PHELiOX** [comment]
I see. This will be good.

**Comment by taroxd** [comment]
https://github.com/poooi/poi/wiki/%E5%BF%AB%E6%8D%B7%E9%94%AE

Feel free to edit it.
