### ISSUE TITLE
3.6版本小建议

### ISSUE THREAD

**Issue by locustetc** [poooi/poi#415]
希望在舰队面板做些微调——
1.个人认为舰队名称基本无用，不如将舰队名称的显示改为等级、制空值的显示。
2.希望添加双击扩大缩小的功能。最近才知道未卜先知的双击隐藏等级显示，既然能支持双击功能，何不优化一下呢？

**Comment by ruiii** [comment]
有按钮就够了 为何还要双击？

**Comment by KochiyaOcean** [comment]
详细信息宽度有 200px 左右非常容易爆，所以使用 Overlay 显示。

**Comment by magicae** [comment]
我觉得1不错 我本地也是这么改的

**Comment by PHELiOX** [comment]
为啥要不断增加这种隐性的功能，点一个按钮跟双击有多大区别？

**Comment by taroxd** [comment]
讲真的，按钮和双击的区别挺大的。尤其是从点击范围上来考虑。

**Comment by PHELiOX** [comment]
那你要的不该是重新设计切换按钮吗

**Comment by taroxd** [comment]
我希望是范围大到能顺手点到的，毕竟这个切换还是经常要做的
如果没有双击的话，我宁可用键盘快捷键也不会去点那个按钮

**Comment by magicae** [comment]
@PHELiOX 
![screenshot from 2015-10-04 20-46-24](https://cloud.githubusercontent.com/assets/6753092/10267909/6f8b03f4-6ad9-11e5-95b8-e39fb921de50.png)
就总等级制 空索敌会有人关心

**Comment by yukixz** [comment]
@magicae 这个... 实在太...丑...

除了配装的时候、其他情况不会关心等级制空索敌这种数据，
所以我觉得没有必要放到概览中

**Comment by magicae** [comment]
噢 那就这样吧

**Comment by PHELiOX** [comment]
@magicae 哦 这个地方。。像原来一样是应该显示这些
