### ISSUE TITLE
poi自带的shadowsocks模块有问题

### ISSUE THREAD

**Issue by sxc562586657** [poooi/poi#418]
环境是osx
我挂上自己的代理poi就一直白屏什么都出不来
同样的代理用goagentx以及shadowsocks客户端都可以连接
什么情况……orz？

**Comment by KochiyaOcean** [comment]
自带的 Shadowsocks-nodejs 一年多没维护了，出问题不要太正常
请尽量使用另外的 Shadowsocks 客户端
