### ISSUE TITLE
魔改

### ISSUE THREAD

**Issue by WTdragonfist** [poooi/poi#421]
請問能夠魔改嗎 還是需要使用插件

**Comment by KochiyaOcean** [comment]
右击
![image](https://cloud.githubusercontent.com/assets/8194131/10263305/e023e8f6-6a1b-11e5-8239-9079c03aee85.png)

**Comment by yukixz** [comment]
![screen shot 2015-10-03 at 10 12 05 pm](https://cloud.githubusercontent.com/assets/3337921/10263306/e4915df6-6a1b-11e5-8bc9-61088ab48316.png)
第二个按钮点右键，魔改文件放进去

**Comment by WTdragonfist** [comment]
感謝 本來以為是左键
