### ISSUE TITLE
還是希望艦娘訊息有改造完成否的選項

### ISSUE THREAD

**Issue by vax68080** [poooi/poi#424]
感謝3.6.1版  各位的付出
還是希望有改造完成與否的選項
這樣可以讓改造完成的艦娘  優先進行性能修改  不然修改完後   再改造   通常會回到每次改造初始值  很不划算   
也可以讓提督知道有哪些鑑娘還可以繼續往上改造   不必急於修改

**Comment by taroxd** [comment]
还有人背不出来哪些船有改二改三改五么....

**Comment by Ayaphis** [comment]
现在有个问题，翔鹤是不是永远属于改造未完？

**Comment by yukixz** [comment]
@Ayaphis 个人觉得应该改二甲算改造完成。

不过这功能我不想加...

**Comment by Ayaphis** [comment]
@yukixz 为什么不想加？

**Comment by Chibaheit** [comment]
是的..因为在包里面.next一直有

**Comment by Ayaphis** [comment]
@vax68080 这个issue开重复了，回上次那个讨论吧。。。关了

https://github.com/poooi/poi/issues/364

**Comment by KochiyaOcean** [comment]
说起来翔鹤改二之后 poi 能回避卡死的原因就是没有显示改造完成的选项（有该功能的 74EO 就吃了一鳖
