### ISSUE TITLE
3.6.1 OSX 版本 無法運行

### ISSUE THREAD

**Issue by alex5huang** [poooi/poi#428]
開發人員辛苦了。
我是macbook使用者，但是新版本遇到了一些問題。
今天看到Poi瀏覽器有更新，於是乎就照著下載頁的指示，刪Resources資料夾，然後下載安裝新檔案。
但是我要打開dmg檔的時候，卻顯示這張圖
http://i.imgur.com/2XjAKUM.png
我把3.5版本刪掉在安裝也不行，都是顯示這個視窗。
我在想會不會有可能是Apple 發佈的新OS系統 EI Capitan 的關係？（我已經升級上去了）
因為我刪掉舊檔案後3.5以前的版本還是可以正常重新安裝。

如果可以的話，請幫忙看一下dmg檔是否有哪裡有出問題？
非常謝謝！！

**Comment by Exodus000** [comment]
可能是开发者上传百度云的版本有问题，我有遇到和你一样的报错。你在github的发布页面下载试试
https://github.com/poooi/poi/releases/tag/v3.6.1

2015-10-04 16:11 GMT-07:00 alex5huang <notifications@github.com>:

**Comment by alex5huang** [comment]
從Github下載的檔案安裝成功了，看來應該是開發人員放錯版本了。
謝謝 Exodus000 大大。

**Comment by Chibaheit** [comment]
貌似被百度云强奸了...

**Comment by KochiyaOcean** [comment]
@今天的吃吧吃鳖了么

**Comment by Chibaheit** [comment]
@KochiyaOcean 啧..您的锅还想推给我?我10.3重新update了还@了你给了链接

**Comment by KochiyaOcean** [comment]
@Chibaheit 我又没有那个帐号的密码……你老应该找学姐才对啊
