### ISSUE TITLE
希望能增加快速更改窗口大小的选项

### ISSUE THREAD

**Issue by Exodus000** [poooi/poi#429]
感谢开发组的不断更新。

有时手动输入分辨率经常会导致画面不对齐，使用自动调整也没有效果。
比如看视频的时候想缩小到50%固定顶层方便无脑练级，需要手动调整很久。

以及最新版本中舰娘信息折叠起来不方便快速查看装备和制空，能不能给出选项选择放在右侧顶栏里？

**Comment by KochiyaOcean** [comment]
鼠标放在舰队名上可以显示（触摸屏轻触也可以触发

**Comment by magicae** [comment]
I'll use a [draggable splitter](https://github.com/hiltonjanfield/jquery.enhsplitter) in Kamo.
