### ISSUE TITLE
poi异常的内存占用

### ISSUE THREAD

**Issue by ceesd** [poooi/poi#430]
即使chrome内核的通病，这种内存占用也太夸张了，希望能有合适的释放内存的机制。
![default](https://cloud.githubusercontent.com/assets/13891041/10277217/166d1a92-6b87-11e5-9e98-a26f283b61b5.png)
刚打开时内存占用正常，使用时间长了就内存占用就越来越大

**Comment by ceesd** [comment]
这应该是某个插件的问题吧，毕竟我在用的chrome的浏览器并没有这么明显的内存泄露

**Comment by KochiyaOcean** [comment]
试着禁用插件看看

**Comment by gnattu** [comment]
我可以说这是Electron的锅。。。Electron在win下就是内存泄漏的。而poi是基于electron写的

**Comment by igax** [comment]
try latest electron. The similar bug is corrected.
https://github.com/atom/electron/issues/2312

**Comment by yukixz** [comment]
Close by https://github.com/poooi/poi/issues/676
