### ISSUE TITLE
关于截图保存的位置

### ISSUE THREAD

**Issue by 0CBH0** [poooi/poi#431]
来问下截图保存的位置是定义在哪里的？
因为一直有一个文件夹放截图的，换poi后在AppData里不怎么习惯又懒得去翻代码QAQ
THX~

**Comment by yukixz** [comment]
![screen shot 2015-10-05 at 9 36 04 pm](https://cloud.githubusercontent.com/assets/3337921/10281723/18aebc94-6ba9-11e5-965c-33a51fe9a9f4.png)
按这里、打开截图目录

**Comment by 0CBH0** [comment]
咱知道位置，咱想改位置QAQ

**Comment by 0CBH0** [comment]
总算是找到了，分别在app.cjsx和utils.coffee里~这下爽快多了(´ ∀ ` *)

**Comment by yukixz** [comment]
激萌！
