### ISSUE TITLE
未卜先知的舰船攻击伤害计算问题

### ISSUE THREAD

**Issue by BTmanMk2** [poooi/poi#432]
未卜先知新加的的攻击伤害记录没有把航母开幕航空战的伤害算入，导致MVP判断有误（开幕雷击未验证）

**Comment by yukixz** [comment]
api 中没有给出航空战伤害的来源，无法判断哪只航母打出了多少伤害。
无法解决。

**Comment by yukixz** [comment]
另、开幕雷击是正确的。

**Comment by Chibaheit** [comment]
航空战 在均分,加权均分,不计算方面选了最后一个,除此之外都正常
