### ISSUE TITLE
Some bundled plugins are abandoned.

### ISSUE THREAD

**Issue by magicae** [poooi/poi#433]
Merge issues here. Wait for new maintainers or new plugin.
统一在这儿讨论这些插件的未来吧，不过怎么看来都是需要有新的维护人员或者新的插件来替代了。

## ShipInfo & ItemInfo
+ [x] 舰娘信息很多問題 https://github.com/poooi/poi/issues/364 (Issue has been closed)
+ [x] 舰娘信息和装备信息里看不到打孔后放置的装备 https://github.com/poooi/poi/issues/331
+ [x] 舰娘信息中按舰名排序混乱 https://github.com/poooi/poi/issues/319
+ [x] 关于装备信息的改良意见 https://github.com/poooi/poi/issues/231 (Issue has been closed)

## QuestInfo & Expedition
+ [x] QuestInfo data is updated,
+ [x] Expedition data is updated.

**Comment by PHELiOX** [comment]
改修好像也没更新 =。=

**Comment by Ayaphis** [comment]
爬了一下，舰娘信息部分
## ShipInfo
+ [ ] 舰娘信息很多問題 https://github.com/poooi/poi/issues/364
+ [ ] 舰娘信息和装备信息里看不到打孔后放置的装备 https://github.com/poooi/poi/issues/331
+ [ ] 舰娘信息中按舰名排序混乱 https://github.com/poooi/poi/issues/319

**Comment by alvin-777** [comment]
poooi/plugin-ship-info#21

**Comment by dkwingsmt** [comment]
远征是不是已经更新了？

**Comment by Ayaphis** [comment]
https://github.com/poooi/plugin-ship-info/pull/28

**Comment by alvin-777** [comment]
poooi/plugin-ship-info#40

**Comment by dkwingsmt** [comment]
Since #364 and #231 has been closed, this issue should be completed now.
