### ISSUE TITLE
关于快捷键的一个问题

### ISSUE THREAD

**Issue by jayjayzju** [poooi/poi#435]
之前的版本cmd+5是切换到海域血量插件

现在中间多了个编成日记，于是cmd+5变成了编成日记

然后我禁了编成日记插件，我的期望是cmd+5恢复到海域血量，但事实上是无效的

不知这个是否可以改进一下

**Comment by PHELiOX** [comment]
快捷键切换是按照下拉列表的顺序进行切换的，并不会绑定某插件到某个数字

**Comment by jayjayzju** [comment]
这我知道，我的意思是，被禁止了的插件，从你所说的下拉列表的顺序里T出去

**Comment by PHELiOX** [comment]
被禁止了是会踢出列表呀。。列表里的都是开启的插件

**Comment by PHELiOX** [comment]
唔 竟然没剔除

**Comment by jayjayzju** [comment]
列表显示是T了，但是快捷键没T

**Comment by alvin-777** [comment]
@KochiyaOcean 的锅
以前是num <= components(概览＋舰队)的length＋plugin的length有效
舰队面板移除了之后这个计算就错了，所以plugin列表里的最后一个是切不到的
我一会儿看看能不能fix

**Comment by KochiyaOcean** [comment]
妹想到

**Comment by alvin-777** [comment]
于是一个衍生的问题：
目前tab和shift＋tab切换会无视mini/expanded ship view，只在概览及插件间切换，这个行为要不要保留(我感觉用着也没什么问题)？还是改成跟快捷键一样 mini->expanded->plugins?
