### ISSUE TITLE
截圖功能

### ISSUE THREAD

**Issue by seika850113** [poooi/poi#438]
希望截圖功能能夠直接鎖定遊戲視窗，截取原始大小（800x480），以及調整截圖目錄。
新增截圖功能的設置我認爲是不錯的方案。

截圖設置
-------------
修改圖片截取大小
 - 預設（原始大小）
 - 自定義 x 自定義 （固定比例）

修改圖片儲存目錄
 - 預設
 - 自定義

**Comment by Ayaphis** [comment]
印象里electron没有截取flash原始图的能力，现在的截图是直接对webview窗口的截图。

**Comment by yukixz** [comment]
只截 flash 看起来不好实现。
https://github.com/poooi/poi/commit/afe615ace43ef5d20c0b25be1e6f0751193bc2f0
