### ISSUE TITLE
请问，如何关闭3.6.1版poi的罗盘剧透功能？

### ISSUE THREAD

**Issue by cloud820120** [poooi/poi#442]
个人认为跪罗盘娘是这游戏的一大乐趣，，，剧透功能虽然不错，但是希望能告诉怎么才能关掉。
如果不能关希望后续版本能够增加开关功能，来方便我们这些心灵弱小的鶸娱乐，谢谢。

**Comment by yukixz** [comment]
罗盘剧透已经合并到剧透插件。
3.6.1 发布时来不及合并，下个版本就可以看不见啦w
