### ISSUE TITLE
请问如何设置截图路径和保存格式?并且调整下方UI排列位置

### ISSUE THREAD

**Issue by xuxukkk** [poooi/poi#444]
RT
截图只能保存在固定路径很不方便..........
下方UI是否能把左方的资源和任务窗口与右边舰队状态窗口互换?
可能的话希望以后能加入自由拖放功能........

**Comment by taroxd** [comment]
fork一份改代码

**Comment by KochiyaOcean** [comment]
拖放什么的实现起来超麻烦啊……不想写

**Comment by xuxukkk** [comment]
不能拖放的话至少能设定一下吧..............做成设置形式会不会简单点...........orz

**Comment by taroxd** [comment]
工作量大概和重新写一遍UI的代码差不多吧= =||

**Comment by yukixz** [comment]
https://github.com/poooi/poi/commit/afe615ace43ef5d20c0b25be1e6f0751193bc2f0
