### ISSUE TITLE
希望未卜先知的罗盘娘剧透能够优化

### ISSUE THREAD

**Issue by zx35728** [poooi/poi#445]
未卜先知的插件非常好用，但是罗盘娘剧透所用的战斗地点的名称（如普通战斗1，boss战19）和官方的名称（A 点,F点）不一致让我非常苦恼。。。希望能改一下。。。
还有我还是比较喜欢3.5版本，未卜先知和舰队概览放在同一个版面的编排，更方便一些（个人意见）。
感谢大神们制作了poi！

**Comment by KochiyaOcean** [comment]
官方的名称就是这些数字……换成常用标号的工程量太大实在没有兴趣还请原谅

**Comment by c933103** [comment]
https://github.com/KC3Kai/KC3Kai/blob/master/src/data/edges.json 其他工具倒是有整理過對應表…

**Comment by Ayaphis** [comment]
一个比较尴尬的问题是，存在一部分提督习惯于看数字，换成ABCD以后他们会看不懂。。。

**Comment by dkwingsmt** [comment]
……真的有提督会习惯看数字吗？？？？以及，这个数字是edge编号而不是点编号……真的会习惯看数字吗？？

**Comment by Ayaphis** [comment]
。。。这DK，当初提出这个地图剧透需求的提督就是看数字的。。。他的需求是“显示数字就行”，以及，因为所有edge都是单向的，映射成点编号没有问题。。。我特么会背2-3的数字，我会到处说？

**Comment by dkwingsmt** [comment]
深深地跪了，真心地跪了

**Comment by taroxd** [comment]
反正我不看数字，字母也不需要。有方向就够了

**Comment by zx35728** [comment]
打开邮箱看到每一个回复都被编成了邮件发过来吓我一跳。。。感谢大神的解答。。。

**Comment by c933103** [comment]
1.不喜歡的話可以點unsubscribe關閉郵件提示，
2.不同人習慣不同可以弄個開關什麼的

**Comment by Chibaheit** [comment]
标号是网站吧..舰载机厨就用的数字

**Comment by c933103** [comment]
具體來說，數字是指航向，是綫，字母是點，1-1等圖的字母只是約定俗成，但1-6等圖有在圖片上標示字母。

**Comment by KagamiChan** [comment]
我想请教一下，数字的航向和字母点的对应关系，对于没有表示字母的地图，是怎么确定下来的？有官方的资料，还是当初 dalao 们自己决定的？

**Comment by KochiyaOcean** [comment]
@KagamiChan 最早是 wiki 编辑者决定的，后期的图由官方标注

**Comment by KagamiChan** [comment]
@KochiyaOcean 那么可以认为目前各个 wiki 的这份资料都是一致的了
我在思考如果用额外的插件来维护这个列表的可能性 - -
但是 `map-reminder` 也要开放一个 api 了，感觉会不会太特殊化

**Comment by KagamiChan** [comment]
啊，缺少一个本体和插件配合的思路啊 = =

**Comment by KochiyaOcean** [comment]
@KagamiChan 放弃本体由未卜先知实现？

**Comment by JenningsWu** [comment]
@KagamiChan 类似任务插件的形式，本体提供接口，单独插件负责？（

**Comment by KagamiChan** [comment]
@KochiyaOcean @JenningsWu 
poooi/plugin-prophet#64 已经把显示编号的锅甩到本体来了
于是既要保证没安装任何插件下能够显示编号，又能在安装了某个插件之后显示为字母点

我想到的方法：
- 检测是否存在插件，然后调用插件的转换方法（但是总觉得为了修改本体来单独适应某个插件并不是很合理）
- 创建一个从外部修改 state 的方法接口（我不知道能不能实现）
- 由插件创建 `CustomEvent` 并 dispatch，然后本体来监听

**Comment by KochiyaOcean** [comment]
@KagamiChan 我改天写个接口吧
