### ISSUE TITLE
有關在平板上用poi遇到的問題以及其他事項

### ISSUE THREAD

**Issue by c933103** [poooi/poi#446]
- 初次啟動提示超出邊界 http://i.imgur.com/tEbHl7w.png (解像度1280×800，用了windows的150%縮放)
- 在解像度偏低的平板上看不見poi的界面 見上面那截圖
- Contributor第一位的頭像裂了 http://i.imgur.com/PqW7HVe.png
- 平板在旋轉後界面不能自適應而出現白色 http://i.imgur.com/PqW7HVe.png
- 在系統語言為日語的平板上初次啟動語言顯示為簡體中文而非日文
- 在Windows系統內設定為150%縮放時，800×480的網頁畫面亦被放大到了1200×720，在開始工具列縱置的情況下有機會與開始工具列重疊而且會導致poi面板不能顯示。建議可選性地進行補正。進入遊戲畫面後倒是會縮放，但有類似放大過再縮小的不太好看的效果？而且也是要設成600×360才會出現800×480的畫面
- 建議在窗口模式運行poi的情況，把設定面板拆到另一窗口
- 插件的 遠征信息 和 任務信息 未i18n
- 阿克夏記錄 一心二用 艦娘信息 裝備改修 等等的彈出窗口標題未i18n
- 在Overview面板 當寬度過小時 第一欄的文字會截掉但第二欄中間的construction會跑了出來 建議統一 http://i.imgur.com/NkmOuab.png
- 經驗計算有英文的i18n但沒有zh-tw的i18n
- about頁沒有i18n
- settings>plugins的Organization Records的描述和數據匯報那行也沒i18n，還有就是艦Colle編成的英文比較常用Conposition…
- 另外順便問一下阿克夏記錄的英文Akashic Records是故意撞明石的嗎？
- 大破進擊彈窗的彈窗標題和關閉按鈕和彈窗框建議用鮮紅底色，並且如可能的話閃爍。
- HTTP回應提示和出擊狀態重疊了 http://i.imgur.com/zvaotZJ.png
- 分別啟動kcv和poi，在經過了kcv顯示登入網頁所需時間後，poi還在白屏轉黑屏，再過大概兩倍的時間才進入等待載入然後載入完成的畫面。
- 建議預設啟用關閉前確認
- http://i.imgur.com/cFdJj1u.png  艦隊裝備在橫移時有個別飛機數字沒跟着移
- 經驗計算建議加入艦隊司令部等級的經驗計算

**Comment by Ayaphis** [comment]
你平板屏幕的宽度。。。也许你可以尝试手动修改poi/config.cson，

![qq 20151011171002](https://cloud.githubusercontent.com/assets/11754367/10415945/26e02e1a-703b-11e5-8ac3-9b07c9b2b065.png)

其中第一个width是poi窗口的宽度，第二个width是游戏窗口的宽度
减小第二个width数值以期显示poi的设置面板。。。



（在如此小的屏幕上无法保证poi的游戏体验。。。

**Comment by KochiyaOcean** [comment]
Contributor 的头像来源是原网站而非本地存储，加载不出说明和服务器通信不好

**Comment by dkwingsmt** [comment]
# Progress until Nov. 11


## Fixed (AFAIK)
- [x] HTTP回應提示和出擊狀態重疊了 http://i.imgur.com/zvaotZJ.png
 - Status bar now scrolls if too short

## Not a bug
- [x] 另外順便問一下阿克夏記錄的英文Akashic Records是故意撞明石的嗎？
 - Fixed poooi/plugin-Akashic-records#35 。另外这是一个历史梗，参见 https://en.wikipedia.org/wiki/Akashic_records
- [x] Contributor第一位的頭像裂了 http://i.imgur.com/PqW7HVe.png
 - 见上面欧选的回答

## Wont fix / Not fixable (AFAIK)
- [x] about頁沒有i18n
 - Not important for now and no translator
- [x] 建議在窗口模式運行poi的情況，把設定面板拆到另一窗口
 - Too hard for now
- [x] 經驗計算建議加入艦隊司令部等級的經驗計算
 - Not the purpose for this plugin. Low demand.
- [x] 在系統語言為日語的平板上初次啟動語言顯示為簡體中文而非日文
 - 我记得之前好像讨论过读取系统语言的问题然后最后决定是不做？ @KochiyaOcean 

## Should fix
- [ ] 插件的 遠征信息 和 任務信息 未i18n
- [ ] 阿克夏記錄 一心二用 艦娘信息 裝備改修 等等的彈出窗口標題未i18n
- [ ] 經驗計算有英文的i18n但沒有zh-tw的i18n
- [ ] http://i.imgur.com/cFdJj1u.png  艦隊裝備在橫移時有個別飛機數字沒跟着移
 - Image no longer available, please update
- [ ] settings>plugins的Organization Records的描述和數據匯報那行也沒i18n，還有就是艦Colle編成的英文比較常用Conposition…  @ruiii 
- [ ] 在Overview面板 當寬度過小時 第一欄的文字會截掉但第二欄中間的construction會跑了出來 建議統一 http://i.imgur.com/NkmOuab.png
- [ ] 初次啟動提示超出邊界 http://i.imgur.com/tEbHl7w.png (解像度1280×800，用了windows的150%縮放)。以及 在解像度偏低的平板上看不見poi的界面 
 - 这个问题我在微博上收到过几次反应，初启动时连设置面板都进不去的问题在平板上有点令人绝望……考虑读取下系统宽度然后自己计算一个初始的小zoom？

## To discuss
- [ ] 建議預設啟用關閉前確認
 - 我赞成
- [ ] 大破進擊彈窗的彈窗標題和關閉按鈕和彈窗框建議用鮮紅底色，並且如可能的話閃爍。
 - 我感觉不太需要这么严重……

## I have no idea 
- [ ] 平板在旋轉後界面不能自適應而出現白色 http://i.imgur.com/PqW7HVe.png
- [ ] 在Windows系統內設定為150%縮放時，800×480的網頁畫面亦被放大到了1200×720，在開始工具列縱置的情況下有機會與開始工具列重疊而且會導致poi面板不能顯示。建議可選性地進行補正。進入遊戲畫面後倒是會縮放，但有類似放大過再縮小的不太好看的效果？而且也是要設成600×360才會出現800×480的畫面
- [ ] 分別啟動kcv和poi，在經過了gkcv顯示登入網頁所需時間後，poi還在白屏轉黑屏，再過大概兩倍的時間才進入等待載入然後載入完成的畫面。

**Comment by ruiii** [comment]
提督经验值可以看秃秃阿（笑
另外编成的英文我是参考wikia的

**Comment by dkwingsmt** [comment]
秃秃只提供了排位而没有提供提督等级吧？另外秃秃到底什么时候实装……

wikia 的编成好像确实是用的Orginaze作为动词，以及Organization作为这个动作的名词，但是对于编成出来的内容好像并没有专门的词汇（否则上次我跟你讨论Hensei Nikki的中文翻译的时候就不会没有结论了）。我觉得Composition是一个相当不错的翻译？……我去reddit上搜搜看？

**Comment by ruiii** [comment]
麻烦dkk啦 最近满课赶大程所以没什么时间（x
秃秃的话 等想到合适的名字 也有时间的时候吧

**Comment by dkwingsmt** [comment]
Just FYI
群里有人提起这个 issue 我来 update 而已～

**Comment by c933103** [comment]
http://i.imgur.com/cFdJj1u.png 艦隊裝備在橫移時有個別飛機數字沒跟着移

Unable to reproduce this one.

**Comment by c933103** [comment]
#561

**Comment by c933103** [comment]
彈出窗口標題未i18n #714
