### ISSUE TITLE
关于排版显示的一个问题

### ISSUE THREAD

**Issue by 1136358656** [poooi/poi#447]
横版布局的某些情况下，poi右端的div会有一部分挤进左端的flash框里面，对于强迫症来说观感甚是。。。
如果把右边的div加一个有几个像素的padding-left效果则会好很多。
详细情况可以看附图~
![2](https://cloud.githubusercontent.com/assets/5331336/10422370/10020dd8-70ec-11e5-81e4-382057bb28b0.jpg)
![1](https://cloud.githubusercontent.com/assets/5331336/10422371/100b74e0-70ec-11e5-97f2-205e59148113.jpg)

**Comment by Ayaphis** [comment]
勾选“使用固定分辨率”似乎可修正这一现象=。=

**Comment by 1136358656** [comment]
勾选了，然而似乎是一样的结果

**Comment by PHELiOX** [comment]
面板并没有留出太多外边距

**Comment by PHELiOX** [comment]
面板并没有留出太多外边距，左右都是
