### ISSUE TITLE
似乎POI的本地缓存功能不会自动更新缓存？

### ISSUE THREAD

**Issue by ttytyun** [poooi/poi#448]
现在POI的本地缓存功能似乎只能使用岛风的缓存，不会跟服务器端的缓存进行比较然后自动更新？
对于我这种现在不使用岛风go的人来说，维护后只能等岛风更新缓存差分包更新，感觉挺不方便的，希望能加上这个功能

**Comment by yukixz** [comment]
岛风狗用户建议使用岛风狗的本地缓存功能，不使用 poi 的本地缓存功能。

**Comment by ttytyun** [comment]
就是因为不是岛风用户所以才希望能能有这个功能……

**Comment by c933103** [comment]
Related info: http://kancolle.wikia.com/wiki/Thread:341303

**Comment by KochiyaOcean** [comment]
必须手动更新，CDN 太贵买不起（全套流量将近 1G 贵到出血……又不能收费

**Comment by PHELiOX** [comment]
跟cdn没关系吧。。单纯就是本地缓存不会更新。。古代问题

**Comment by KochiyaOcean** [comment]
是说缓存包不会自动更新吧

**Comment by Ayaphis** [comment]
electron的缓存太奇怪，访问不了，poi又不能以游戏名义去官方服务器下缓存。要实现维护缓存的功能需要额外的缓存服务器吧=。=

**Comment by KochiyaOcean** [comment]
缓存包本来就是用来解决从服务器上下载缓存太慢的问题而生的啊……也就是说不用 CDN 就没意义了。然而并没有开 CDN 的钱

**Comment by ttytyun** [comment]
我就是缓存包不会自动更新，比如上次维护后设置里清了无数次缓存但是一直是读条完就猫。
我把缓存文件夹移出去登陆就完全没问题，等登陆上去后我又把之前的缓存移了回来，这时游戏读出来的缓存都是旧的，然后我再在设置里清理缓存重启poi，又开始读条猫了，也不知道问题出在哪

**Comment by yukixz** [comment]
@ttytyun 那个缓存包设置是代替游戏服务器的返回而已。

**Comment by Ayaphis** [comment]
@ttytyun 舰娘会验证缓存时效性。。。旧的缓存包直接用会猫

**Comment by KochiyaOcean** [comment]
无法增加该功能，理由上面也说了，我们不像某个每月收 8 块的代理那样有足够的资金运营一个缓存 CDN

**Comment by ttytyun** [comment]
话说，不能比对本地缓存和服务器缓存的时间之类的属性然后选择更新本地缓存么？那个74式貌似就是直接下载和更新本地缓存的啊，虽然之前用的时候他更新的缓存时不时会出问题……（更新完本地缓存立绘还是旧的）

**Comment by KochiyaOcean** [comment]
更新缓存包以后手动自动清理一下缓存就行了，主要是懒得写（哈欠
