### ISSUE TITLE
關閉建造/開發劇透選項

### ISSUE THREAD

**Issue by c933103** [poooi/poi#450]
參照 http://m.gamer.com.tw/forum/C.php?bsn=24698&snA=10670&bpage=0&keyword=&page=2

**Comment by yukixz** [comment]
建造剧透，在最新概览面板中，只要不切换过去就不会看到了。

**Comment by yukixz** [comment]
另、感谢您的汇报。

**Comment by c933103** [comment]
@yukixz 原文提到的還有在開發時於http回應那裡顯示的劇透 參照http://truth.bahamut.com.tw/s01/201509/424cc54a0118692de43a3c3578541b04.PNG

**Comment by Chibaheit** [comment]
開發劇透只能夠通過hack 源碼的方式來解決.建造的可以切換

**Comment by c933103** [comment]
嗯，那可以在未來版本加入相應開關嗎？

**Comment by alvin-777** [comment]
有空的话可以考虑。。

**Comment by PHELiOX** [comment]
是设置里直接开关呢。。还是面板上开关呢

**Comment by c933103** [comment]
…設置開關和面板開關有什麼分別？
2015/10/14 21:59 "Artoria" <notifications@github.com>:

**Comment by alvin-777** [comment]
#457 
在console输入`config.set('poi.delayItemDevResult', true)`之后下面的结果显示会跟游戏同步，_重启生效_。

先就这样吧，如果需求大的话再加设置开关（或者谁想做谁做。。

**Comment by KochiyaOcean** [comment]
设置开关就不加了，设置项已经够多的了……
