### ISSUE TITLE
舰队面板上，船在用桶修的时候也会有入渠中标志

### ISSUE THREAD

**Issue by dkwingsmt** [poooi/poi#453]
是这个设定吗？感觉在用桶修的时候只回血不加入渠中标志会比较好。用桶之后服务器那边也不会认为此船入渠中。

**Comment by Ayaphis** [comment]
https://github.com/poooi/poi/commit/bc51dc847be9878ad97a88c7cc270f7673592a03

**Comment by Chibaheit** [comment]
不是..只是没做判定而已..
