### ISSUE TITLE
KC3 Kai devs would like to send construction/development/drop data to poi database

### ISSUE THREAD

**Issue by c933103** [poooi/poi#460]
See https://github.com/KC3Kai/KC3Kai/issues/952 . Any comments? Like is it welcomed or is there anything that should be caution about and etc.

**Comment by magicae** [comment]
Known. Welcomed. I will draft a doc about poi-server report api soon(about a week).

**Comment by c933103** [comment]
https://github.com/poooi/poi-server/issues/1
