### ISSUE TITLE
关于调整分辨率时的两个问题

### ISSUE THREAD

**Issue by dkwingsmt** [poooi/poi#464]
1. 3.7.0的Mac版隐藏了标题栏，但这样会导致在高度过小时标题栏和工具栏重合，感觉并不恰当，建议设置一个最小高度。
![image](https://cloud.githubusercontent.com/assets/1596656/10566955/dc651014-75ba-11e5-8b4b-ec1a4fbaa608.png)
2. 在游戏分辨率直接设为0的时候，似乎采用的逻辑是直接让flash消失，但反而不执行调整高度的逻辑部分，导致上面会留有一块和原高度相同的空白区域。
![image](https://cloud.githubusercontent.com/assets/1596656/10566959/07950d84-75bb-11e5-86b2-3a013277c97f.png)

Mac，github版3.7.0，纵版，分离。

**Comment by KochiyaOcean** [comment]
设置成 1 那种高度根本不像想玩的样子……
没有重现 2

**Comment by dkwingsmt** [comment]
2我可以重现，在显示设置里面设置游戏分辨率为0即可。
1是为了“真·分离面板”啊，就是所谓用一心二用来玩游戏然后用这个主面板来看数据。

**Comment by dkwingsmt** [comment]
我知道了，2
欧选你是不是一位一位删的

这么做：
宽度首先设为800
然后在框里全选
输入0

而不是 退格 退格 退格 0
