### ISSUE TITLE
win 板哭了

### ISSUE THREAD

**Issue by Wafer-Li** [poooi/poi#472]
现在 win 板 很多都是 32 位的啊……
现在直接上 64 位 让 win 板 怎么办？

**Comment by KochiyaOcean** [comment]
只是 build 的时候从 CDN 上默认下载 64 位而已（之前默认 32 位，用 64 位 Electron 同样无法运行，需要另外提取 64 位 Pepperflash
发行版会带有 32 位的 pepperflash 的

**Comment by Wafer-Li** [comment]
:sob:  然而我用 git 版的怎么办？

**Comment by KochiyaOcean** [comment]
用 git 版也不需要每次都 build 吧

**Comment by Wafer-Li** [comment]
……不是升级了一次 Flash 到 19 了吗？

**Comment by Wafer-Li** [comment]
:cry: 结果更新的时候就发现 couldn't load plugin

**Comment by KochiyaOcean** [comment]
只要文件名一样就可以继续用 18.x，或者 4.0.0 发布的时候会有 19.x，或者从 32 位 Chrome 里扒

**Comment by KochiyaOcean** [comment]
文件名改下就行了如果你看得懂代码的话

**Comment by Wafer-Li** [comment]
明白了
