### ISSUE TITLE
工具栏的overlay挡住别的按钮

### ISSUE THREAD

**Issue by dkwingsmt** [poooi/poi#474]
![image](https://cloud.githubusercontent.com/assets/1596656/10643542/19595fa4-77e9-11e5-96fd-8cc557ff22bd.png)

把它调到下方或者上方会比较好的样子

以及每次点完取消静音之后按钮还是会保持显示按下很久，是feature？
![image](https://cloud.githubusercontent.com/assets/1596656/10643550/1fe3ddfe-77e9-11e5-9349-6ffa0aa8557a.png)

**Comment by KochiyaOcean** [comment]
那个是选中状态不是按下状态，在下次点击时解除

**Comment by dkwingsmt** [comment]
（•̥̥̥̥̥̥̥ ﹏ •̥̥̥̥̥̥̥̥๑） 按钮还有选中判定啊……建议修掉诶，能修吗

**Comment by KochiyaOcean** [comment]
![image](https://cloud.githubusercontent.com/assets/8194131/10643725/f1adc72e-7856-11e5-9247-d18a8648b738.png)
其实选中效果和按下效果一般来说是有一些差距的。

**Comment by dkwingsmt** [comment]
一方面确实比较像，另一方面确实也是没有必要的效果吧？

**Comment by KochiyaOcean** [comment]
=。=大概？
