### ISSUE TITLE
Papercyan 这个主题对于血条的显示有点问题

### ISSUE THREAD

**Issue by dkwingsmt** [poooi/poi#490]
@荼梦之影:Papercyan 这个主题对于血条的显示有点问题，满血是亮蓝色，破损后发暗，但是小中破血条颜色并没有变色提示，大破血条变粉。但还是请求能为这个主题追加血条中小破变色以及船体出击油弹的损耗变色。

**Comment by KochiyaOcean** [comment]
papercyan 到底谁做的啊……

**Comment by ruiii** [comment]
这个 最好去作者的repo题issue。。？

**Comment by dkwingsmt** [comment]
papercyan是自带的？然后poi只是引用了其规定的色系中的几个颜色？结果其中几个颜色恰好相同了？所以解决的方式只有硬code？

**Comment by ruiii** [comment]
没。。我看了看他是基本把几个颜色的分类 都改成了只有2种颜色

**Comment by dkwingsmt** [comment]
噗，真是完全不适合poi的配色……

**Comment by magicae** [comment]
@govizlora 你们看gulp脚本不就知道作者了

**Comment by dkwingsmt** [comment]
已转告

**Comment by govizlora** [comment]
我修复啦！见master：https://github.com/govizlora/theme-papercyan
有建议可以去那里+issue
