### ISSUE TITLE
关于一些小建议

### ISSUE THREAD

**Issue by tianrongze** [poooi/poi#492]
概览：
1、远征状态栏，在远征结束后最好显示“补给状态"或者"闪的剩余量"，不要显示个“准备完成”，免得误会已经补给了；
2、舰队状态，希望显示“明石修理时间”，建议时间就放在血量和疲劳值之间；
3、舰队状态，建议现实疲劳剩余时间，免得老是点到“舰队”去看，时间的位置同上。

舰队：
1、最好显示老司机熟练度，鼠标挪过去略麻烦；
2、建议显示改修等级。

未卜先知：
1、破损状态最好能用文字显示，不然五颜六色的眼花，文字可以显示在生命条居右；
2、建议鼠标悬停能显示对应的装备。

航海日志：
最好能集成战斗详情功能。

舰娘信息：
建议显示搭载量、老司机熟练度、改修等级。

先感谢作者们付出的无限努力，和百忙之中看我这矫情用户的请求。
谢谢！

**Comment by KochiyaOcean** [comment]
概览
1 再考虑。不过舰队指示器
![image](https://cloud.githubusercontent.com/assets/8194131/10711074/2bf8b2d8-7aa3-11e5-8439-b5eb651d1dd7.png)已经有出击状态指示，可以直接参考
2 
![image](https://cloud.githubusercontent.com/assets/8194131/10711077/430d012c-7aa3-11e5-9248-9bce1d6ae482.png)明石修理时间和实际维修时间相同（只是 20 分钟回港可以提前结算而已）
3 ![image](https://cloud.githubusercontent.com/assets/8194131/10711082/6529dae6-7aa3-11e5-96c5-9d1250981ba0.png)
舰队
1 早就是了
2 再考虑

未卜先知
插件功能不宜太复杂

航海日志
战斗详情已经是独立插件

舰娘信息
再考虑
