### ISSUE TITLE
对后续版本一些小建议及使用POI的一些小惊喜

### ISSUE THREAD

**Issue by yxmxyxy** [poooi/poi#493]
建议
1.改修工厂的插件：现在是用下拉列表选择星期几的改修，毕竟只有7天可选建议改为七个单选按钮，如果能做成复选按钮对比两天的改修区别就更好了，在纠结当天的改修任务是十一点前做好还是十一点后做时会有很大帮助。
2.装备开发的剧透：建议和罗盘剧透一样隐藏起来，比如放到“建造”栏里。
3.任务进度计数只是单纯的对比用户操作记录和任务条件？好像5补给船任务会比poi显示的提前完成。
4.经验计算插件的默认海域是1-1…而实际主流的肝船图就1-5、3-2、4-3、5-4…建议以上四个图单独做成按钮，其他海域放进下拉列表里。
5.能不能识别出演习时对方的配置？能的话自动计算一下经验，不行的话在经验计算的插件里增加演习经验预估，手动输入对方前两舰的等级，看值不值得打。
6.增加插件：海域带路/制空：既然软件能识别、计算出舰队的阵容、装备、索敌、制空，那么根据wiki上的带路条件判断一下当前这个配置一定or可能会怎么走、每个点的简单敌阵容和各制空情况的概率范围。
7.战斗详情插件：交战情况不太直观…
8.用什么办法提醒提督君一下”你的远征收了就一直没派出去哦！“(<_<)
9.舰娘信息插件：游戏界面太窄（平板竖屏）时第一列”NO.“会和后面的几列串行（虽然不影响啥就是了）。
10.舰队界面增加该阵容一场战斗的油弹消耗量，远征插件增加刨去补给远征队的实际资源收入。
11.”晚安“功能（可以放在关闭游戏的确认对话框中）：晚安，睡觉之前poi帮你看一下远征都派了吗、是不是有伤员但明石和澡堂还闲着、今天还有XX日常任务没有完成不做了吗……
E(nao)X(dong)：勋章/成就系统——POI软件的奖杯库，开发二连烈风四发仨46？大建四发四傻不重样？婚舰1-1刷闪大破D败？一口气拆了一百个装备？田中不管你poi给你发奖杯~

惊喜：
远征没补给或者条件不满足、大破进击会有弹窗提示
经验计算插件默认目标等级是你选的船的改一/改二等级
远征信息插件三个红绿点的这种显示方法真是太棒了
制空终于在概览界面显示了

**Comment by KochiyaOcean** [comment]
1 再考虑
2 再考虑
3 娇喘的锅，不背
4 再考虑
5 问吃吧
6 数据量太大维护起来太麻烦，如果愿意帮忙维护倒是很欢迎
7 给个直观的建议
8 多余
9 无法考虑如此极端的条件
10 多余
11 多余
E 什么鬼

**Comment by yukixz** [comment]
部分回答一下
3. 是的。5 补给船是角川计数有 bug，而不是 poi 计数有 bug。
4. 不实现。
5. 即将实装。
7. ~~需要做个动画么？~~
10.2 远征插件已经扣除远征消耗了

**Comment by Ayaphis** [comment]
1.@KochiyaOcean . 
2.你说的建造栏是什么。。。  
3.是的，poi不处理源于角川的各种计数BUG  
4.5.@chibaheit
6.这个要维护大量的数据和逻辑，形成可用插件的工作量不小。
7.你有没有具体的表现方案？
8.10.11 可以开发新的可选插件来实现这些功能，但是应该不会列入捆绑

总之只能希望更多的人贡献代码或者维护数据来丰富这些可选功能。

**Comment by alvin-777** [comment]
2 打开开发者工具 ![image](https://cloud.githubusercontent.com/assets/13615512/10711862/3eec0d9e-7acc-11e5-8ffc-3422dd0f6194.png) ，在控制台输入`window.config.set('poi.delayItemDevResult', true)`

10.2 
![image](https://cloud.githubusercontent.com/assets/13615512/10711883/aa11bede-7acc-11e5-8c31-0923aba8f76c.png)

**Comment by yxmxyxy** [comment]
7.战斗详情
简单说一下我想象中的效果吧……
双方血条的组成部分，最左是被攻击后剩余血量，实心纯色，和现在一样；
中间此次攻击打掉的血量，用斜杠/密斑点等“半透明”质感表示；
右面是被此次攻击打到前就已经损耗的血，和现在一样背景色无填充；
效果图 http://ww3.sinaimg.cn/mw1024/005wtrh8jw1excuqxryx4j30mt0btdh4.jpg

**Comment by yukixz** [comment]
@yxmxyxy hmm、这个效果我之前做过、不过存在损管/女神回血的情况...
我考虑一下之后版本加入。

**Comment by yukixz** [comment]
@yxmxyxy 
战斗详情加上掉血量的暂时效果
（花花草草什么的太难做了）
![screen shot 2015-10-27 at 11 34 32 pm](https://cloud.githubusercontent.com/assets/3337921/10763040/68551534-7d03-11e5-8873-4515b93acd8c.png)
