### ISSUE TITLE
界面UI的提议

### ISSUE THREAD

**Issue by edwardaaaa** [poooi/poi#494]
- 4.0版本后，POI功能时越来越多，选项也越来越多，色彩已经眼花缭乱了。虽然默认主题paperdark逻辑上比较清晰，但是界面元素请加工下，个人PS了一张效果图，相关提议和图具体如下：

![default](https://cloud.githubusercontent.com/assets/11089376/10752936/5f4af9da-7cc8-11e5-8cf8-cad51e869871.jpg)
- 字体显示：
  - 不同平台上的物理条件差异很大，Windows和Linux平台依然是普通屏为主；OS X平台高分屏的普及也没能全面覆盖。
  - 不同字体在两种屏幕下的显示效果天差地别，比如说OS X的丽黑在Retina显示下很好，但是在Air这类非Retina显示效果下字体会严重发虚，究其原因还是字重问题。
  - 以后的版本希望能够选入那些有很多字重的字体，比如截图中10.11的“苹方”字体，拥有超过7种字重，显示效果在两种屏幕上都非常好。
- 界面元素：
  - 目前POI提供的主题的界面元素基本上都是大面积的彩色色块，虽然很显眼，但是时间长了比较容易视觉疲劳。
  - 截图中在paperdark主题的基础上规划统一了色块的尺寸，颜色以及对应的功能含义。
  - 同时对于线条的运用进行规整。
  - 比如绿色块＋线条，同时紧贴融合在一起时，代表的是标签切换功能。
  - 同样绿色块＋线条，同时分开上下在一起时，代表的是独立的功能按钮和信息分割。
- 模块布局：
  - paperdark主题的概览界面布局可以进一步优化，截图中对于信息进行了分类。
  - 比如说：以文字为主的任务模块和提督基本信息被置于上方，这样空间足够，显示效果明晰。
  - 比如说：以数字为主的建造模块和修理模块信息被同一置于右下方，同时还有远征和资源模块。
  - 舰队简介面板加入了双击切换至详细信息的效果，同时作为点击次数最多的模块置于原来的位置不变，方便玩家操作。
- 一点私心：
  - OS X原生的模糊效果个人一直钟爱，不少软件也都能支持，不知能否在未来版本增加模糊效果的选项

**Comment by KochiyaOcean** [comment]
字体：会考虑加入多字重字体作为优先选项。
界面元素：属于主题的管辖范围内暂不讨论。顺便 text-shadow 效果曾经在测试版中使用过但是争议太大所以并未最终采用
模块布局：这个布局相当具有启发性，不过感觉对于低分辨率屏幕的支持太过糟糕（比如我的 1280*800 小屏幕），故需要再做考虑
![image](https://cloud.githubusercontent.com/assets/8194131/10754016/c4f952b6-7ccf-11e5-836a-85bde32017a5.png)
顺便受限于上游，Chrome 能做到的事 poi 大都能做到，Chrome 做不到的事就……（所以毛玻璃透明什么的……

**Comment by magicae** [comment]
这个布局挺好看的 把行距改小的点应该就可以了 我觉得可以考虑

**Comment by KochiyaOcean** [comment]
建造和维修面板仍然需要合并才能保证有足够的空间……总之周末改个看看

**Comment by KochiyaOcean** [comment]
![image](https://cloud.githubusercontent.com/assets/8194131/10760197/4d848c92-7cf6-11e5-81e4-90d502cc9fe5.png)
やばり無理だな

**Comment by ruiii** [comment]
考虑到切分面板 感觉任务那部分会被压缩的惨不忍睹
但是如果切分面板和单面版使用两种布局的话也是一种选择

**Comment by KochiyaOcean** [comment]
我有空的时候也写个主题吧……
不使用原图的主题效果就算是这种布局也不会很好看……

**Comment by PHELiOX** [comment]
稍微吐槽一下设置面板的按钮阵列和蓝色的远征。。

**Comment by edwardaaaa** [comment]
* 关于字体：
    * 希望根据不同平台给予用户不同的多字体选择配置方案。

* 界面元素：
    * 等待开发组提上日程，但是界面元素会直接影响POI对于不同屏幕尺寸的支持程度。

* 模块布局：
    * 开发组临时重新制作的的面板，看上去有些局促，主要问题个人认为是模块切割方面的看法不同。
    
    * 首先是资源界面的图标其实换做文字也是不错的。
     
    * 其次是下方的面板切割不一定需要按照中线切割左右大小一样。右下方多出了不少空间，而这部分文字信息的重要性不高，名字过长可用省略号代替，就像BSM名字那样，如此便能压缩出不少空间，同时不影响信息。

* 关于KochiyaOcean所提到的对于小屏幕支持不佳，根据你提供的分辨率数据为1280＊800，则：
	* 如果是 = 13寸标准屏显示器，效果图的创作环境是13寸显示器2x高分辨率，因此矢量缩放到1x分辨率的13寸标屏上不会有问题。
	
	* 如果是 < 13寸非标屏显示器，此时显示器特征为略高于普通屏的PPI，略小于普通屏的显示面积。以显示效果来看，应为较为清晰，较为锐利的字体，比例缩小的字体显示，也就是你提到的问题。
	
	* 对于此问题的解决办法：相同分辨率时，采用缩放能解决视角效果较小和视觉效果不清晰的情况，其缩放比例为：
			
			当前使用的屏幕尺寸：当前分辨率的标准屏幕尺寸
	
	* 举例来说，比如显示器为10寸，分辨率为1280＊800，则根据此分辨率标准普通屏尺寸：13寸，比例约为1:1.3，此时可以考虑放大为120%～130%。
	
	* 此时可能会发生的负面效应就是非标准屏幕缩放导致的显示拥挤，这也就是本人提出的界面元素需要修改的原因之一。
	
	* 如效果图所示采用统一色块代表按钮功能，统一的线条进行信息和模块的切割，甚至是依靠数字和文字区分来进行模块切割所创造出的空间能够妥善解决非标准分辨率屏幕需要缩放时所带来的闲适拥挤问题，从而能进一步强化POI的多平台，高兼容策略。
	
	* 举例子说：paperdark使用圆角矩形＋空间间距来进行模块的切割。两个圆角矩形和当中的空隙造成了画面拥挤感和相当一部分空间损耗。

* 关于设置界面的诸多方块，一方面是目前设置方面较多选项，且没有进行一定程度的归类；另一方面是考虑到平板用户，这样操作起来会十分方便，原先的小方格勾选在点按方面需要一定的操作精度；最后一点也是希望统一风格，作为一款个人认为越发成熟稳健的浏览器，这点还是比较重要的。

**Comment by ruiii** [comment]
看了那么多 我觉得要实现这样的需求 需要面板重新规划（更换部分组件）+ 定制主题
另外 考虑下切分面板？
顺便 看text-shadow真的很难受

**Comment by KochiyaOcean** [comment]
poi 是用 javascript 写的，所以如果想实现获取已安装字体并进行设置的功能的话，实现会相当麻烦，暂不考虑
参照 http://stackoverflow.com/questions/28710775/javascript-how-detect-system-fonts-all-fonts-that-exists-in-system
poi 的布局标准基于游戏原生尺寸（800*480），故横向面板高度只有约 470px 左右的空间。以及使用图标其实也是缩小高度的策略之一……同样的情况如果使用文字的话效果会更糟糕

**Comment by KagamiChan** [comment]
对于换字体，可能并不需要考虑得那么复杂，让大家自己找字体对应名就行

目前版本下修改自定义 css 就能办到，比如说在自定义 css 里边暴力地图炮：
```css
* {
    font-family: 'Open Sans', 'Hiragino Sans GB', sans-serif;
}
```
当然如果能够像 atom 那样，专门有一个设置项填写自定义字体名（顺便能设置字重什么的），应该会更友好一点吧，这个设置也避免了像我上边那样暴力轰一遍

**Comment by KochiyaOcean** [comment]
现在的字体设置就是这样的
```
font-family: "Ubuntu", "Helvetica Neue", "Helvetica", "Arial", "Heiti SC", "WenQuanYi Micro Hei", "Microsoft YaHei", "Droid Sans Fallback", sans-serif;
```
要获得所有系统字体的实现还是太麻烦了

**Comment by KagamiChan** [comment]
其实就是像下边多出一个地方让大家输入自定义字体啦，至于这个字体名称是什么，让用户自己查就好。当然也可以有一些预置的方案，对应不同的平台。
相比于地图炮的好处，可能就是可以专门加入到某个 class 上去，实现更细致的调节——虽然目前地图炮也暂时没感觉到有什么不对劲的地方

![2015-11-02 23_43_50-settings - c__users_kagami_desktop - atom](https://cloud.githubusercontent.com/assets/3816900/10886129/a3d2a812-81bb-11e5-9e22-836547fc8546.png)

**Comment by KochiyaOcean** [comment]
唔，知道 font-family 是什么东西的人基本都会改 css……

**Comment by edwardaaaa** [comment]
之前一直以为自定义CSS要编译一整套，现在实验下来效果不错。 
		
		*{
		font-weight: semibold;
		font-family: 'PingFang SC';
		}

但是这样设置只有字体改变了，但是字重依然没有产生效果，请问如何编译CSS来调整字重问题？

**Comment by KagamiChan** [comment]
关于这一点，KCV 的 slot item 之类的都是矢量路径绘制的 （粗粗看上去是 svg），说不定可以参考
https://github.com/Grabacr07/KanColleViewer/blob/57a8493f47f9f00aee6df77728b8b671b8b20064/source/Grabacr07.KanColleViewer.Controls/Themes/Generic.SlotItemIcon.xaml

**Comment by KochiyaOcean** [comment]
如果愿意提供的话当然兹茨啦

**Comment by xupefei** [comment]
这里是 KCV 中所有的装备图标，我提取成了 SVG 矢量：

https://onedrive.live.com/redir?resid=7F77567C52BB35F9!27982&authkey=!ADNwXaICkDQUrmw&ithint=file%2c7z

目前没发现什么去白边的好工具，只有一个 [Method Draw](http://editor.method.ac/) 还不错。

**Comment by magicae** [comment]
@xupefei 我以前向KCV中的矢量图标作者要过授权，他并没有同意。

**Comment by xupefei** [comment]
@magicae KCV 是 MIT协议吧，可以直使用的。

**Comment by magicae** [comment]
@xupefei 搞图标的那家伙直接回绝了。。。

**Comment by magicae** [comment]
@xupefei Ref: https://twitter.com/Nrtwd/status/531636726209323008

**Comment by edwardaaaa** [comment]
目前按照kancolle的图标龟速绘制ing，和kcv不同，绘制完成转成SVG。时间方面别太期待就是了。。。

**Comment by KochiyaOcean** [comment]
感谢！

**Comment by edwardaaaa** [comment]
麻烦请先测试一下能否使用，地址如下：
https://drive.google.com/file/d/0B-J-nq9cHXQxbGg1R0N0TzkxS0k/view?usp=sharing

**Comment by KagamiChan** [comment]
效果好棒，有 svg 的话就可以转成 glyphicon 字体，很棒的

**Comment by edwardaaaa** [comment]
@KagamiChan 麻烦截下图我看看，我看下有无需要改进的地方。

**Comment by KagamiChan** [comment]
不好意思，我就是拿浏览器打开预览了一下……确定能应用

**Comment by KagamiChan** [comment]
@edwardaaaa 试着用几个在线工具转换了一下这个 svg，发现大家对于 stoke 的识别都有问题，icomoon 是直接不认，glyphter 转换错误，于是效果变成了这样
![2015-11-09 23_07_18- 1](https://cloud.githubusercontent.com/assets/3816900/11037048/c24e7ffc-8736-11e5-903a-1abf0af35b55.png)
看来还是得麻烦你按照 https://icomoon.io/#docs/stroke-to-fill 写的方法修改一下，把 stroke 转换成 path

**Comment by xupefei** [comment]
没必要转成字体吧，字体可是不带颜色的。直接显示为svg不就好了么

**Comment by KagamiChan** [comment]
自己用 inkscape 改了一下，生成了字体，嗯目前效果是这样的
![2015-11-10 00_03_51-poi](https://cloud.githubusercontent.com/assets/3816900/11038606/da7d628e-873e-11e5-9daf-3bc117ee583c.png)

假想的高分屏下的效果 (font-size:800%;)
![2015-11-10 00_07_39-poi](https://cloud.githubusercontent.com/assets/3816900/11038698/43b11a5c-873f-11e5-8e97-f00e6c403888.png)


@xupefei 在网页中插入的话用 glyphicon 比较方便，而且不带颜色就比较方便自定义主题了

**Comment by KochiyaOcean** [comment]
用 embed 也可以调用吧……4.1.0 发布以后会着手这方面的工作

**Comment by KagamiChan** [comment]
嗯，我忘了还有 embed 了。
我只是用开发者工具做的暴力改，的确没考虑程序方面的事情

新版本，拭目以待

**Comment by edwardaaaa** [comment]
怎么会这么大。。。。。代码层面能缩小么，而且笔画貌似太粗了，如果缩小会不会糊成一团。。

**Comment by dkwingsmt** [comment]
看起来效果好棒啊！超清晰

**Comment by KagamiChan** [comment]
@edwardaaaa  你是说哪一个？第一幅图我是按照下边的水雷图标的大小来调的。至于舰队信息未展开界面下的浮动 tooltip / popover 用开发者工具不好捕捉……
因为我的屏幕只是 fullHD，没有办法展现高分屏下的效果，下面那张截图是用来说明在放到极大之后的表现

缩小后的图标效果也应该不会比现在的差，原本缩小的图标应该也只是根据颜色和大体外形来进行分辨

如果你需要在你那边实时预览效果的话，应该可以写一个专门的开发插件，输入 svg 文件，就能预览在不同界面下的效果。但是我不了解将来在 poi 中如何使用这些图形，而且我对 coffee 和 react 都不熟 = =

P.S. 有没有方法能够取消掉右键的禁用？我想能像普通网页一样右键 inspect 元素

**Comment by KochiyaOcean** [comment]
虽然说 Electron 是 Chrome 内核但是不是说它就是 Chrome 啊，右键菜单行为是要开发者自己写的。
用快捷工具栏里的开发者工具吧

**Comment by KagamiChan** [comment]
看来是我太想当然了 :stuck_out_tongue:

**Comment by edwardaaaa** [comment]
好吧，之前只看到了第二个截图，那个图标尺寸着实吓了我一跳。现在看了下第一截图，貌似没多大问题。对于一些细节，比如说“水听”图标里的“点点点”等诸如此类的会有选择性删除，以免普通屏下效果不佳。
总共会有：
* 装备图标
* 资源图标资源图标也会和目前装备图标一样统一做扁平化处理，制作组可以选择性是否采用。

**Comment by magicae** [comment]
需要一个长期提供图标的人。
Contributors里也要加上icon providers啦。

**Comment by edwardaaaa** [comment]
i would love to

**Comment by KagamiChan** [comment]
新的矢量图标非常棒，不过我还是想提两个小建议：
1. 某些图标的颜色白色底色下看不清，例如图中瑞风上的那个彩云
~~嘛，目前白色主题都存在一些对比度过大的问题~~
![2015-12-02 12_28_25-poi](https://cloud.githubusercontent.com/assets/3816900/11522241/4f0309c0-98f0-11e5-9c11-3816989d83af.png)

2.图标的间距或者大小是否需要微调，比如我图里面的 500 的电探和喷炮，感觉距离有一点近

![2015-12-02 12_02_22-poi](https://cloud.githubusercontent.com/assets/3816900/11522025/a9c2948c-98ed-11e5-9548-9e2ad5a586ec.png)

**Comment by PHELiOX** [comment]
刚发现换图标了，我觉得图标形状不求和游戏一致，但求看起来相似。目前的一些图标**看起来无法和游戏内容建立关联**，识别上需要一个过程，增加了复杂性且不利于使用。

希望能从以下方面继续调节：

1. 图标形状

  - 既然大部分图标都是描摹游戏图标，那么主炮鱼雷和飞机还是没必要绘制新的形状了，带来的不一致性难以识别。希望换回游戏图标形状。

2. 图标摆放方式

  - 主炮图标整体轮廓接近游戏图标，但是摆放方式是NW45，和游戏中角SE45度相反，也容易造成识别错误。

3. 图标颜色

  - 默认图标颜色应取游戏颜色，目前的颜色饱和度和亮度太高，和背景反差强烈。除了不一致性还会刺眼。**不过既然是svg，图标可受主题控制，面板结构上应该加入这部分内容。**

**Comment by KagamiChan** [comment]
我也比较赞成图标的形状和颜色能够跟着主题走

关于雷，我是这么理解这个图标的：原版就是一坨蓝色，虽然应该是用 61cm四联装酸素鱼雷的外观拓出来的形状，但是在那个分辨率下基本看不出是雷了。而矢量图标是为了高分辨率来做的，所以不得不有所改动
![2015-12-2t14 22 24](https://cloud.githubusercontent.com/assets/3816900/11523779/3851ffaa-9900-11e5-9c3f-a3d2eb03579a.png)

**Comment by alvin-777** [comment]
我也觉得新图标不要跟游戏原本的图标相差太多比较好。。
比如那个鱼雷我看到的第一反应是“这是哪个飞机？”。。
但是哪怕仅仅是把形状和角度稍作调整，识别起来也会容易不少（大概？？）
![image](https://cloud.githubusercontent.com/assets/13615512/11527076/774580d6-992a-11e5-865b-41f375da11f4.png)

**Comment by dkwingsmt** [comment]
我个人觉得图标还是照着原游戏图标完全临摹比较好，不管是形状还是配色，毕竟原来做新图标的主要原因是原图标没有高清以及油弹钢铝等图标不是扁平化。这样改动了形状的话，虽然和现实物体更相近一点，但是会带来很大的困惑，比如这个鱼雷……

**Comment by ruiii** [comment]
试用了一下新图标。
个人感觉图标尽量靠近游戏吧。。适应需要一个过程
另外感觉颜色有点亮。

**Comment by gnattu** [comment]
@KochiyaOcean 挖个坟，毛玻璃是可能的，但是需要一套新的主题去优化它
<img width="1289" alt="screen shot 2017-07-19 at 7 13 15 pm" src="https://user-images.githubusercontent.com/12995396/28364418-f911e184-6cb6-11e7-9b3c-c6dd32fc923f.png">

**Comment by KochiyaOcean** [comment]
@gnattu 就这个 issue 的时间点而言当时是没法实习的就是了……
https://github.com/electron/electron/pull/7898 11 月加进来的

**Comment by KagamiChan** [comment]
现在看基本都实现了
