### ISSUE TITLE
舰娘信息：删除无用的特效，添加 “无” 过滤按钮

### ISSUE THREAD

**Issue by xupefei** [poooi/poi#500]
如题。
Mouseover 的字体变化在列表项目多的时候明显有延迟，而且这个特效没什么用处啊……

另外，过滤之后想回到 “未过滤” 只能展开过滤选项手动选择。

**Comment by taroxd** [comment]
路过膜拜一下做 LE 的大神- -

**Comment by Ayaphis** [comment]
未过滤，，，要放到过滤选项外面么。。唔

**Comment by xupefei** [comment]
@Ayaphis 是啊，会方便很多

**Comment by Ayaphis** [comment]
@xupefei 唔，不太能想象到所有过滤选项都选全部的场合，默认过滤是lv2及以上，已锁定  
或者你的意思是把船型选项拉出来？

**Comment by xupefei** [comment]
不，我指的是：

1. 在这里点击 “驱逐舰”yi'hou以后，下面的列表中全是驱逐舰

![image](https://cloud.githubusercontent.com/assets/1687847/10990222/d8b10c86-848b-11e5-8533-fe3d97a785ba.png)

2. 这时你想看全部的舰娘，需要展开 “过滤设置”，然后选择“全部”

![image](https://cloud.githubusercontent.com/assets/1687847/10990239/06152f22-848c-11e5-9ea2-9b04e393e64f.png)

我的意思是，在 “驱逐舰” 按钮左边加上一个 “全部” 按钮，无需展开 “过滤设置” 就能回到全舰娘列表。

**Comment by Ayaphis** [comment]
了解。。。我理解失误了
