### ISSUE TITLE
poi遇到的问题

### ISSUE THREAD

**Issue by Anisento** [poooi/poi#502]
在打开舰娘信息 点击排序后出现闪退情况 闪退后再启动poi无限白屏

**Comment by Ayaphis** [comment]
版本？错误信息？必要的话配置文件？

**Comment by alvin-777** [comment]
操作系统？

**Comment by Anisento** [comment]
版本4.0.0 win7 系统重启后恢复正常

**Comment by Anisento** [comment]
再次进入舰娘信息后重复相同操作未出现闪退

**Comment by Anisento** [comment]
另外还有个问题 在使用poi时 途中关闭代理如岛风go后 点击出击或者需要获得数据的操作时会显示失去连接，但在之后开启代理仍然无法连接代理继续使用   需要手动刷新才行

**Comment by Exvoke** [comment]
版本4.0.0 win8.1 x64 打开舰娘信息 点击排序后会出现白屏情况，重启程序后若继续打开舰娘信息 拖动舰娘信息窗口就会出现poi主程序白屏。

**Comment by KochiyaOcean** [comment]
怀疑是 Electron v0.34.0 在 Windows 平台上的 bug，参照 https://github.com/atom/electron/issues/3191
不知道最新的 v0.34.3 是否修复，需要进一步测试

**Comment by KochiyaOcean** [comment]
https://github.com/atom/electron/releases/tag/v0.34.3 这里可以下载最新版的 Electron
解压后覆盖 poi 根目录下的同名文件然后运行 electron.exe 就可以运行了
如果不嫌麻烦的话请帮忙测试一下这个版本是否还有相同问题

**Comment by dkwingsmt** [comment]
补充一下，是下载
electron-v0.34.3-win32-ia32.zip
或者
electron-v0.34.3-win32-x64.zip

以及，覆盖之后是运行 electron.exe 而不是 poi.exe

**Comment by magicae** [comment]
那个Issue和这个问题无关。
