### ISSUE TITLE
浮动的风格不一致

### ISSUE THREAD

**Issue by dkwingsmt** [poooi/poi#503]
![image](https://cloud.githubusercontent.com/assets/1596656/11013196/607e9cc8-84c8-11e5-8cb7-f80f4bb467a3.png)

Yvonone
回复@今天poi出新版本了吗:反馈下：左边两图中，浮动窗口色调不一致，同时最左边的的那张截图的浮动窗口尖头处有白线。 另外一点就是这个主题的好多框框线条，感觉还是paperdark那样比较干净。 个人最喜欢的还是papercyan，除了色调需要调和下，部分虚线改为横线就好了。

Yvonone
回复@今天poi出新版本了吗:这个新主题还有一点就是字体颜色，改为偏灰色比较好，不然长时间看255的纯白色和偏暗的底色，眼睛会不舒服。

**Comment by ruiii** [comment]
浮动窗口不一致那个啊 应该是因为是两个控件

**Comment by KochiyaOcean** [comment]
一个是 Tooltip 一个是 Popover……
不过 Popover 的背景调暗一点应该会比较好吧

**Comment by dkwingsmt** [comment]
不能统一吗？统一了的话代码也会统一一点吧……？

**Comment by alvin-777** [comment]
主题的问题啊，跟代码没关系

**Comment by dkwingsmt** [comment]
我的意思是统一成都是 Tooltip 或 Popover

**Comment by alvin-777** [comment]
Tooltip代码简单明了，全部改成Popover看着都累。。

我觉得还不如统一两个的CSS来得实际

**Comment by KochiyaOcean** [comment]
![image](https://cloud.githubusercontent.com/assets/8194131/11020073/c8a9900a-864e-11e5-9eca-4b2555fa04d5.png)
换成 Tooltip 的感觉如何

**Comment by KochiyaOcean** [comment]
![image](https://cloud.githubusercontent.com/assets/8194131/11020147/0cb0b70e-8651-11e5-8ace-1d790b32c2f1.png)
![image](https://cloud.githubusercontent.com/assets/8194131/11020148/0ffd729e-8651-11e5-80c2-4a239a0a53d9.png)
调整了一下字体大小

**Comment by KochiyaOcean** [comment]
没人评价的话我明天直接 push 噜

**Comment by dkwingsmt** [comment]
哇赞欧选

**Comment by dkwingsmt** [comment]
欧选先 pr 一下呗【
