### ISSUE TITLE
screenshots path 改跪了

### ISSUE THREAD

**Issue by Wafer-Li** [poooi/poi#505]
Electron v0.34.3 x64
Win 10 x64 Pro
commit SHA: 7e7c04020a2400a3194a49c7ae4af57569529731

截图路径改跪了，点击 `打开截图目录` 会弹出一个什么都没有的框
进 `config.cson`(Electron 根目录下的) 强行改回来也不行。

**Comment by taroxd** [comment]
我没有碰过【打开截图目录】按钮的行为。

你看一下 config.cson 里面的 screenPath 设置是字符串还是数组？如果是数组的话，可以改回字符串。如果是字符串的话，那和这个 commit 无关

**Comment by KochiyaOcean** [comment]
拖动文件夹设置是没有问题的，把文件夹拖入设置区域试试看

**Comment by Wafer-Li** [comment]
:joy: 其实我改动的时候是这个 commit 的上一个 commit，然后那东西就莫名的变成数组了。
:joy: 然后发现有问题之后才 pull 的新 commit，现在改回字符串就没有问题了。
