### ISSUE TITLE
无限黑船无法进入游戏 本地重连开启后显示网络错误

### ISSUE THREAD

**Issue by Yayayoi** [poooi/poi#507]
3.6.1版本时可正常运行。

更新4.0.0后不能进入游戏。

更新的时候操作是，删除3.6.1文件夹，后解压4.0.0文件夹。

无限黑船无法进入游戏，开启本地重连后显示network error

开始怀疑是新版本BUG后将4.0.0删除，解压3.6.1 老版本同样出现这一问题

现在完全无法解决。

console 上显示
file:///D:/poi-v4.0.0-win64/hack/custom.css Failed to load resource: net::ERR_FILE_NOT_FOUND

系统是64位 WIN10 HOME 日文版。

文件目录全英文。

没使用任何VPN。

NTT+so-net提供网络服务，IE浏览器和chrome均可正常进入游戏。 

POI的插件全部关闭之后重启打开也不能进入游戏。

运气好的时候能进入母港，然后随便切一个页面就重复network error。

**Comment by Yayayoi** [comment]
缓存和cookie删除已尝试很多次，都不能解决问题。

**Comment by taroxd** [comment]
用命令行打开（`/path/to/poi`）的话，有没有错误信息打到命令行上呢？

**Comment by Yayayoi** [comment]
[ERROR] Api failed: POST http://203.104.209.55/kcsapi/api_port/port Error: socke
t hang up

**Comment by yukixz** [comment]
看起来你的网络跟角川服务器连接可能不佳。
试试普通浏览器有没有问题？

**Comment by Yayayoi** [comment]
kcv ie chrome均可正常进入

**Comment by magicae** [comment]
[ERROR] Api failed: POST http://203.104.209.55/kcsapi/api_port/port Error: socke
t hang up

说明连接不佳，母港请求失败了。使用的代理是？
