### ISSUE TITLE
Data Collection Help Request

### ISSUE THREAD

**Issue by c933103** [poooi/poi#508]
Recently, we want to check the rumor that kanmusus without any gun would get an accuracy debuff, and since poi is now collecting users' data into a database, I wonder can you guys help collect some data and share those data to us in order to confirm or deny the rumor?

To do so, we think the following data would be needed:
all the lv.1 DD's hit/miss record in 1-1, separated by enemy being I/Ro/Ha/Ho-Class, and categorized by that they are equipped with 0/1/2, 12/12.7cm twin guns. discard data for lv.1 dds that equip other equipments for simplicity.
filter away all records where those DD's morale are not 40-49, and also only include those data that those DDs are not chuuha nor taiha, and exclude those data that are not line ahead. Only include day battle data.

Can Poi help us collect these daata for analysis? thanks for your attention.

**Comment by dkwingsmt** [comment]
It sounds like different ships are all treated as the same lv-1-DD, and differ only by equipments?

**Comment by c933103** [comment]
exclude those data that are not lv.1DD, and no need to differentiate between different dd.

**Comment by JenningsWu** [comment]
收集数据存在本地，还是发到某个服务器？
另外，单纯包含战斗数据大概还不够的，战斗数据里没有关于当前舰队的数据，无法得知正在战斗的是什么样的船、带着怎样的装备...还需要存一份对应的舰队队状态数据包。

另，相关的数据包收集检证插件之前有人做过，参见
https://github.com/cnrpman/battle-logger

如果是想本地储存下来这些数据包进而进行分析检证的话，可以参考上面那个插件的工作方式。如果能接受它所定义的[战斗数据包](https://github.com/cnrpman/battle-logger/blob/master/info/%E6%88%98%E6%96%97%E6%95%B0%E6%8D%AE%E5%8C%85%E5%AE%9A%E4%B9%89v0.1.txt)，那可以直接在这个插件的基础上做了。再加上数据筛选，排除不要的战斗数据就可以（实际上，这些筛选其实也可以本地处理数据的时候做）。

**Comment by c933103** [comment]
1.是想說參考現在poi收集掉落/建造數據的插件/模式…可以用現在poi的服務器嗎？
2.相關數據本地記錄的話是有航海日誌擴充版/赤版…所以應該可行的吧

**Comment by yukixz** [comment]
@JenningsWu 咦、battle detail 插件现在也是自己维护了一份[战斗数据包格式](https://github.com/poooi/plugin-battle-detail/blob/master/docs/packet-standard.md)
