### ISSUE TITLE
poi web? Project Kamo!

### ISSUE THREAD

**Issue by magicae** [poooi/poi#509]
<del><b>去年 11 月放了 poi 这个卫星，今年的 11.11 也例行放卫星。</b></del>

考虑了一段时间 web 版的可行性，现在感觉是可以搞的一个东西了。代码上的话应该是__完全做不到共用__，于是直接叫 Kamo 好了。之前重写 poi 的计划也不是很必要了，毕竟现在有这么多插件支持，orphan 的插件也都找到了接盘侠。嗯接下来讨论下一些考虑和技术选型。这个项目不像 poi 那样游戏行为和正常的 Chrome 完全一致，因此可能有__潜在的危险__，但是看 ooi 运行这么久也没什么大问题，因此可以开坑。

感谢一下[ooi](https://github.com/acgx/ooi2)在技术上的分享，以下内容__大部分__从 ooi 中参考而来。

### 为什么需要网页版

主要是为了解决 poi 中难以解决的一些问题。比如：

1. 难以 hotfix。
2. 下载包较大。
3. Electron 导致的内存占用较大与内存泄漏等问题。

但是网页版失去了大部分本地交互能力，总体上来说会有很多不可避免的功能缺失<del>，并且服务器的参与导致会多很多锅</del>，功能上来说__完全无法__替代目前 poi 的很多本地特化的功能。

### 游戏连接方式

参考各种舰队登录器和 ooi 的原理，服务器使用__自动发送__登陆、获取 token、验证包的方式获取游戏的 api_token，然后 iframe 嵌入网页。服务器发包的时候 cookies 中附带 ckey=1，也就是传统的__改Cookies登录__的方式来做到不使用代理来登录（基于网速考虑，会加上可选启用的代理）。

### 游戏抓包方式

iframe 嵌入的游戏 swf 指向目前 Kamo 站点，游戏的 api 发包（/kcsapi，/kcs）会自动发向目前域名，在这些域名上做反向代理到游戏服务器，并且在反代的时候抓到一份包返回给前端。

### 游戏资源缓存

参考 ooi。服务器直接进行游戏资源下载与缓存。

这意味着和 ooi 一样，需要相对高额的服务器带宽和流量费用，目前 ooi 的用户量下，费用大约在 60 CNY / day。

### 基本架构（讨论中）

语言上前后端全部使用 JavaScript / Babel (ECMAScript 6 + ECMAScript 7 async / await)，服务端选用 Node.js。

前端

- Views: React([Flux](https://facebook.github.io/flux/)? [Redux](https://github.com/rackt/redux)? +Angular? 讨论中)
- CSS Framework: Bootstrap v3([Bootstrap Material Design](https://github.com/FezVrasta/bootstrap-material-design)?)
- Dependencies and compile: gulp + browserify(Webpack?)

后端

- Server: Nginx + Node.js
- Framework: Koa v2(Express?)
- Database: Redis + RethinkDB(PostgreSQL? MongoDB?)

前后端通信

- Socket.IO

## 运营模式

+ 一个官方自动部署的 demo 服务器，仅做测试 + 预览之用。
+ 不提供公众服务，倡导自建服务器提供小范围服务。
+ 可能可以从 ooi 那边赞助一个服务器。

## 开源协议

AGPLv3，只是一种道德约束。

## 目前状态

GitHub: [kamo](https://github.com/magicae/kamo)

npm: [kamo](https://www.npmjs.com/package/kamo)

**Comment by dkwingsmt** [comment]
对费用比较在意，特别是我猜到时候用户量会比 ooi 大

**Comment by taroxd** [comment]
赞美学姐 <del>虽然我可能还是会用本地?</del>

**Comment by magicae** [comment]
@dkwingsmt 增加了运营模式的问题。提倡自建。

**Comment by dkwingsmt** [comment]
因为涉及到服务器的问题感觉合作开发的难度变大了？

**Comment by magicae** [comment]
目前打算是我独立维护 功能的话基本都是先在 poi 这边实现 然后迁移到 Kamo

**Comment by magicae** [comment]
Won't do that.
