### ISSUE TITLE
截图目录设置可以多次打开

### ISSUE THREAD

**Issue by dkwingsmt** [poooi/poi#511]
截图目录不是模态窗口，因此可能因为多次点击打开多个文件夹选择窗口。

经测试，只有第一个打开的窗口选择的文件夹被记录，但是需要所有打开的窗口都关闭之后。

**Comment by dkwingsmt** [comment]
这个issue 是不是可以关闭了？ @taroxd

**Comment by taroxd** [comment]
可以自己关吧 = =

**Comment by dkwingsmt** [comment]
我只是不确定
