### ISSUE TITLE
gulp现存的问题

### ISSUE THREAD

**Issue by dkwingsmt** [poooi/poi#516]
重要问题
- [x] 部分下载的文件放在 `~/` 而不是 `/tmp`
- [x] 下载的electron文件没有区分win32和win64
 - 导致先build 32位再build 64位不会重新下载electron而出错
- [x] 简单地复制整个plugins目录，导致开发中的插件也被复制进去
 - 用`git archive`解决
- [x] `gulp build` 没有包含 `gulp` 的内容，导致比如 theme 的更新可能会被错过
- [x] 无法一次性自动 build 所有平台
- [x] 无法自动 7z 打包和 app.7z 打包
 - 关于 win 下 exe 的问题，用“两步build”解决
 - 目的：尽可能用脚本解决而不是手动输入命令

一些其它问题
- [ ] poi 版本号分在三个文件里（至少把gulp的改为读取`package.json`的）
- [x] 对于electron下载路径的设置（美国无法访问taoabo镜像，需要访问github下载electron）
- [x] 打包 7z 前去掉 config.cson 等注意事项，用脚本解决。

**Comment by KochiyaOcean** [comment]
- 下载的electron文件没有区分win32和win64
加入 process.arch 的判断
- 简单地复制整个plugins目录，导致开发中的插件也被复制进去
直接用 npm 解决
- 打包 7z 前去掉 config.cson 等注意事项，用脚本解决。
每次运行都会在根目录产生该文件，刚打包完成的时候是不会有这个文件的

**Comment by dkwingsmt** [comment]
- 下载的electron文件没有区分win32和win64

 - 加入 process.arch 的判断
 - 不是使用什么来判断，而是现在下载出来的文件名没有包含systembit信息。整个不是为了多平台打包而设计的。

- 简单地复制整个plugins目录，导致开发中的插件也被复制进去

 - 直接用 npm 解决
 - 5.0.0的飞机落地前这都不打算解决了吗？

- 打包 7z 前去掉 config.cson 等注意事项，用脚本解决。

 - 每次运行都会在根目录产生该文件，刚打包完成的时候是不会有这个文件的
 - 加入脚本对这些事情进行确保是有必要的。

**Comment by KochiyaOcean** [comment]
- 无法自动 7z 打包和 app.7z 打包
需要添加额外的依赖

**Comment by dkwingsmt** [comment]
- 无法自动 7z 打包和 app.7z 打包

 - 需要添加额外的依赖
 - 哪些？`7z`吗？取消对 win 下的打包的支持即可。

**Comment by KochiyaOcean** [comment]
- 无法自动 7z 打包和 app.7z 打包

 - 需要添加额外的依赖
 - 哪些？`7z`吗？取消对 win 下的打包的支持即可。
 - OS X 下也不是自带的，需要从 homebrew 安装

**Comment by dkwingsmt** [comment]
- 无法自动 7z 打包和 app.7z 打包

 - 需要添加额外的依赖
 - 哪些？`7z`吗？取消对 win 下的打包的支持即可。
 - OS X 下也不是自带的，需要从 homebrew 安装
 - 那就添加，一切有利于本项目打包的事情都是本项目的打包依赖
  - 即使没有这条自动 7z 打包功能，你也并没有减少对 7z 的依赖，你只不过是换成了手动右键或者命令行打包了而已。
  - 并没有添加使用依赖，毕竟直接在根目录下`electron .`是不需要这些东西的。
  - 如果你愿意也可以换回 zip ，毕竟 zip 是自带的。（而且还可以防止用户解压工具不当导致出错）

**Comment by KochiyaOcean** [comment]
https://www.npmjs.com/package/node-7z 一个可能用得到的东西

**Comment by KochiyaOcean** [comment]
- 简单地复制整个plugins目录，导致开发中的插件也被复制进去

 - 直接用 npm 解决
 - 5.0.0的飞机落地前这都不打算解决了吗？
 - 下一个版本是 4.2.0，如果仅为了这个版本实现的话我不反对啦

**Comment by dkwingsmt** [comment]
- 简单地复制整个plugins目录，导致开发中的插件也被复制进去

 - 直接用 npm 解决
 - 5.0.0的飞机落地前这都不打算解决了吗？
 - 下一个和最后一个使用 submodule 的版本是 4.2.0，如果仅为了这个版本实现的话我不反对啦
 - git archive 一遍终归是有好处的，gulp里使用直接复制assets i18n等目录的方法，不能排除以后也有这些文件夹里偶然出现了 untracked 的开发中文件的可能。

**Comment by dkwingsmt** [comment]
初版释出，欢迎 review。基于最新的 master 版本，已测试 win64版本可用（再次赞美欧选，原来的 plugins submodule 方法对我这个脚本造成了极大阻碍，恰好这次把 plugins 挪走了）

dkwingsmt/poi@1239a9191efb36e880578d4b9139f7e510685822

## 打包
用法：```coffee build.coffee```

即会在当前 build 文件夹下开始打包 lin64和 win64版本。

在打包即将结束的时候会在命令行端提示你（ouxuan）更换 poi.exe 的图标和版本信息。

## 本地安装
在``build.coffee``下把其中一段代码取消注释，另一段代码注释掉之后，运行``coffee build.coffee``即可在本地安装 flash 和 themes。

## 关于放弃 gulp
gulp 的优点在于生成 DAG 使得 task 的依赖能够按照依赖顺序不重不漏地并行执行，然而这实际上给我带来了很大的阻碍，因为我实际上需要让同一段代码按照不同的参数执行多遍，即在不同平台打包的过程。由于 gulp task 不接受参数，导致整个这一部分都无法使用 task 完成，只能使用普通的函数。在这种情况下，不如整体使用普通的 async 函数执行，加上 promise 来完成并行。

## 下一步
+ 提高 ``build_detail.coffee`` 内函数的稳定性
+ 在 ``build.coffee`` 里面解析命令行参数

**Comment by dkwingsmt** [comment]
#582
