### ISSUE TITLE
任务以及船的英文翻译

### ISSUE THREAD

**Issue by yuanzongli** [poooi/poi#518]
需要的话我可以帮你直接翻译所有船为罗马音，方便让非中国提督使用poi
因为目前没有英文翻译的船会有点难懂所以不是很想用，有翻译的话我觉得会很多人会开始用
任务翻译的话其实我可以帮你翻译 如果有需要的话

**Comment by taroxd** [comment]
http://kancolle.wikia.com/wiki/Quests

问题不在翻译，而是在修改代码以及苦力工作...

**Comment by dkwingsmt** [comment]
Finished 
https://github.com/poooi/plugin-translator/commit/a62ac1c50bad53534ed5d76fc1f191efd41edfb6
https://github.com/poooi/plugin-quest/commit/b622a5c736ca319a1ac1a4fdabe6652cad7663b8
