### ISSUE TITLE
關於快速鍵的問題

### ISSUE THREAD

**Issue by sodasu11** [poooi/poi#519]
poi在執行的期間，似乎會將Ctrl+I 佔據 (變成老闆鍵)，用Word變得綁手綁腳
請問有辦法修改快速鍵的設置嗎?

**Comment by dkwingsmt** [comment]
Windows的话在 poi 根目录下的 config.cson ，使用写字板进行编辑即可

**Comment by taroxd** [comment]
我记得老板键似乎是写死的？

**Comment by KochiyaOcean** [comment]
可以改但是不能禁用

**Comment by sodasu11** [comment]
感謝回答!

**Comment by dkwingsmt** [comment]
然而为啥不允许禁用呢……读取那个设置，如果为空就禁用？如何？
