### ISSUE TITLE
OS X 下全屏时，打开新窗口插件，关闭后会出现黑屏

### ISSUE THREAD

**Issue by dkwingsmt** [poooi/poi#523]
复现方法：
在 OS X 下全屏 poi，然后打开比如“装备信息”的自带窗口的插件，然后关闭该插件。

（据反映有时候无法关闭）
就算关掉之后，也会留下一个无法消失的黑屏。

**Comment by gnattu** [comment]
Mission Control里把全屏退出就没了。

**Comment by dkwingsmt** [comment]
总之是正常的么……

**Comment by KochiyaOcean** [comment]
应该是将关闭按钮重载成隐藏的原因，使用了 realClose 设置的插件没有这个问题

**Comment by dkwingsmt** [comment]
关闭重载成隐藏……现在还有插件这样做？这不是好早以前的白屏bug的临时workaround吗？

**Comment by KochiyaOcean** [comment]
隐藏和最小化是不一样的，在后台持续收集数据的插件一直是重载为隐藏

**Comment by alvin-777** [comment]
Related to #553

**Comment by were** [comment]
啊啊，黑屏这这个屏幕是可以关掉的，你只要四个手指上推到多桌面的那个界面。

然后鼠标挪上去到那个全黑有叉叉可以关掉的。

**Comment by KochiyaOcean** [comment]
其实这个 Electron 已经修复了我就关掉吧

**Comment by dkwingsmt** [comment]
只是补充一下，刚测试了下好像并没有修复的样子？……

**Comment by alvin-777** [comment]
严格地说这并不是bug (因为是我们自己改变了关闭的行为)，所以electron自然也不会去“修”
我试过在全屏的时候先退出全屏再隐藏，但是没用，因为退出全屏的动画会强行显示窗口

しかし！我刚刚突然想到怎么修了！这就去pr！
