### ISSUE TITLE
弹出式警告框应只在点击按钮的时候关闭

### ISSUE THREAD

**Issue by dkwingsmt** [poooi/poi#525]
现在的弹出式警告窗口（大破进击、远征失败，以及升级提示和第一次登陆的欢迎）在任意点击的时候即会关闭，前几天报告了有人因为发远征的时候鼠标狂点点点，导致警告框刚开始渐现就关闭，完全没看到，回来发现远征失败的事。

应使得警告框只在点击按钮的时候关闭。

**Comment by taroxd** [comment]
怎么看都是 electron 的锅吧......

**Comment by yukixz** [comment]
不是。
`<ReactBootstrap.Modal onHide={@doNothing} />` 就可以关掉点空白地方消失的功能。
但这改动会让关掉 modal 显得繁琐，我认为不需要为个别手贱用户改这个功能。

**Comment by taroxd** [comment]
好吧，我错了

我支持改这个功能。Modal 出现的目的就是为了不让随便关掉。
默认情况下的 Modal 主要就是退出时的弹框和大破提示了，而退出时通常都是要去点那个「确定」的

**Comment by yukixz** [comment]
退出时的 modal 随便点的地方都能取消退出不是更便利吗？非要鼠标移过去执行「取消退出」这个动作是不是太傻了...
同样的，大破进击能快速关掉 modal 接着执行刷新的动作，毕竟播船只移动动画然后加载 battle 只要5~6秒。

**Comment by dkwingsmt** [comment]
modal 的目的是被人看见而不是被人关闭。

换个方面来说，所有你能看见的应用程序的对话框都是需要鼠标手动过去点击按钮的，证明这并不是很大的问题。

**Comment by yukixz** [comment]
被用户看见，同时提供一个便利的关闭方式，这两点并不冲突。
这个 issue 的起因是、有个手贱用户不看屏幕的同时一直点鼠标。

（作为 mac 用户我很讨厌移动鼠标、都是按 enter 解决

**Comment by dkwingsmt** [comment]
实际上并不只是如此，比如我今天就遇到了类似的情况。情景如下
我在 windows 上打开 poi，双击 exe 之后启动很慢，我就切换到别的窗口去了
这时候 poi 载入了，我看到 poi 弹出了一个窗口（欢迎使用新版本的窗口），我就鼠标点一下那个窗口切过去看（不使用 AltTab 而是使用鼠标点击窗口切换很合理吧），结果那个弹出的窗口就关闭了。

**Comment by yukixz** [comment]
另外、所有你能看见的应用程序的对话框都能按 Enter 执行默认动作，poi 不能。

**Comment by yukixz** [comment]
嗯？点 modal 内区域是不会执行 `onHide` 的呀...

**Comment by magicae** [comment]
> 我认为不需要为个别手贱用户改这个功能。
