### ISSUE TITLE
Ctrl+I全局快捷键和Photoshop等冲突

### ISSUE THREAD

**Issue by MinamiChan** [poooi/poi#527]
建议选项里允许关闭这个快捷键，不然会和一些软件的快捷键冲突。

**Comment by Ayaphis** [comment]
参考 https://github.com/poooi/poi/issues/519

**Comment by taroxd** [comment]
Implemented in https://github.com/poooi/poi/commit/9d22a312ab423aa516d6da9c6cf226ab7b04d70b
