### ISSUE TITLE
請問poi的緩存地址怎麼找？

### ISSUE THREAD

**Issue by cheunghim** [poooi/poi#528]
求教，我想試試魔改，但是找不到緩存地址

**Comment by yukixz** [comment]
![screen shot 2015-11-14 at 7 30 09 pm](https://cloud.githubusercontent.com/assets/3337921/11163339/22fa6744-8b06-11e5-8432-743f1a5cadf3.png)
点右键

**Comment by cheunghim** [comment]
謝謝，不過為什麼裡面是空的？

**Comment by yukixz** [comment]
里面是放手动缓存和魔改的，所以正常情况为空。
