### ISSUE TITLE
win32 下 git 版本中 EXROOT 设定问题

### ISSUE THREAD

**Issue by taroxd** [poooi/poi#529]
目前 EXROOT 是设为可执行文件（即 electron）的文件夹。这样如果用 npm 更新 electron 的话，之前所有的设置和缓存都会被清空。希望可以解决。

1. 判断 process.execPath.endsWith('electron.exe')。如果是的话，将 EXROOT 设为与 ROOT 相同。
2. 或者干脆把 EXROOT 放到 %APPDATA%/poi

**Comment by dkwingsmt** [comment]
话说这点我一直很疑问……我记得好久以前一直都在 %APPDATA%/poi 下的？

**Comment by taroxd** [comment]
我也一直很疑问

**Comment by dkwingsmt** [comment]
而且git版的default_config.cson和config.cson之间的关系，还有release版的表·config.cson 和里·config.cson 之间的关系，说实话我也觉得有点谜_(:3 」∠ )_
