### ISSUE TITLE
在设置中添加一个按钮：打开config.cson所在的文件夹

### ISSUE THREAD

**Issue by dkwingsmt** [poooi/poi#530]
方便需要编辑高级属性的人使用。
可以在使用红色标注“如果不知道你在做什么，请勿打开”之类。

之所以是打开文件夹而不是文件，是因为win下不要用记事本去打开它［是吧

**Comment by taroxd** [comment]
openItem 会自动选择默认的文本编辑器。参考「编辑自定义CSS」

**Comment by dkwingsmt** [comment]
对，就是不让用记事本打开它……

**Comment by taroxd** [comment]
哦 我这里默认编辑器是 sublime

fuck windows notepad
