### ISSUE TITLE
poi浏览器的窗口捕捉（自动调整？）时间有点久

### ISSUE THREAD

**Issue by sh210510182** [poooi/poi#538]
算了一下估计要两分钟左右，是不是能稍微再缩短一点游戏窗口捕捉的时间？

**Comment by taroxd** [comment]
不用岛风GO

**Comment by sh210510182** [comment]
什么意思？（摸不着头脑）

**Comment by taroxd** [comment]
字面意思，不要用岛风GO

**Comment by sh210510182** [comment]
用别的代理吗= =

**Comment by taroxd** [comment]
yes

**Comment by sh210510182** [comment]
好吧= =

**Comment by sh210510182** [comment]
这个捕捉时间难道跟岛风go有关系？

**Comment by KochiyaOcean** [comment]
只有页面完全载入完成的时候才能完成捕捉
岛风 Go 不会代理页面上的来自 FB 和 Twitter 的元素
所以载入时间被延长至强制超时时间（2min）
所以完成捕捉的时间也被延长
只有直连和岛风 Go 会有这种情况
一个「正常的」代理是不会有这种情况的
