### ISSUE TITLE
v4.2.0（秋活版）需要更新的内容

### ISSUE THREAD

**Issue by dkwingsmt** [poooi/poi#539]
v4.2.0 在秋活开了之后尽快发布，除了秋活后实装的任务或机能之外，原则是在4.1.0的基础上尽量不改东西。（反正打包交给欧选）

如果有什么认为需要加入的在这里征集一下，我现在知道的就只有

+ [x] 任务信息有一个 typo
+ [x] 编成日记有一个 fix
+ [x] 战斗详情的 yukibug 
+ [x] 任务信息更新了 远征15允许装母
+ [x] 未卜先知更新活动图罗盘数据
+ [ ] 海域血条适配E5双血条
+ [x] 远征插件：活动图的支援远征
+ [x] ~~未卜先知和战斗详情手撕 battle 包（新联合舰队）~~ 就是机动部队的api
+ [x] ~~主体的截图目录双击问题~~ wontfix

_另外吃吧打包 Mac 版的时候别忘了改通知图标（4.1.0漏了）_
_而且吃吧你需要把 Electron 更新到 0.34.0_

**Comment by yukixz** [comment]
不用是否... 已经确认有 yukibug 了 (wa2

**Comment by taroxd** [comment]
截图目录设置的问题

**Comment by yukixz** [comment]
截图目录上个版本修了=3=

**Comment by taroxd** [comment]
我说的是那个连开两次截图目录那个

**Comment by yukixz** [comment]
测试了下=。= master 双击还是开两次...

**Comment by dkwingsmt** [comment]
ok 这个确实是

**Comment by taroxd** [comment]
开两次之后设置结果是符合人的认知的...

**Comment by dkwingsmt** [comment]
我测试了很久到底是第一次打开的那个窗口有效，还是最后一次打开的那个窗口有效，还是第一次提交的窗口有效，还是最后一次提交的窗口有效……

**Comment by taroxd** [comment]
现在是最后一次点「确定」

**Comment by yukixz** [comment]
callback 的原理=。

**Comment by dkwingsmt** [comment]
把所有的插件更新到了需要的版本
7b6ccc246887f5157d5d103965bff91abe8a4f1e

Plugin | Version (empty for not updated since poi v4.1.0)
-------|-----
akashic-records     | 
battle-detail       | Fixed yukibug
exp-calc            | 
expedition          | Added armored carrier to exp15
hensei-nikki        | Latest master
item-improvement    | 
item-info           | V1.3.1 (used in poi v4.1.0)
map-hp              | 
new-window          | Tag (used in poi v4.1.0)
prophet             | 
quest-info          | Fixed typo 
report              | Fixed remain reporting when disabled
ship-info           | Latest master

主体截图目录的事 @yukixz 还没 push 到 master 吗？等你 push 之后我 pick 到4.2.0吧

**Comment by taroxd** [comment]
我觉得版本号 4.1.1 比较好？

**Comment by dkwingsmt** [comment]
我也觉得，不过我有点担心学姐有点跳版本强迫症【学姐：“我的跳版本都是有依有据的！（敲头）”我：“好好好 QwQ”】

总之看到时候秋活加不加新机能，然后看大家的意见吧

**Comment by yukixz** [comment]
4. 截图双击不管啦、用户手贱不负责

**Comment by yukixz** [comment]
3 把 `fca0f4c2c0bcc9d748daaccbf0954d0ba74920e9` 也 pick 一下=3= 这是损管消耗之后的界面显示

**Comment by yukixz** [comment]
6 未卜先知需要更新罗盘剧透的数据（手撕 swf

**Comment by Ayaphis** [comment]
ship info是不是要打TAG，好不想写Changlog啊啊啊啊

**Comment by Chibaheit** [comment]
罗盘数据等yuki.. 战斗详情的yukibug..

**Comment by dkwingsmt** [comment]
Changelog
4.2.0
功能
* [战斗详情] 损管消耗时添加了图标提示。
修正
* [任务信息] 修复了岩本小队系列任务中的一个任务说明。
* [编成日记] 修复了联合舰队下的一些问题。
* [编成日记] 修复了删除一个空舰队时崩溃的问题。
* [数据汇报] 修复了即使设置关闭该插件也会继续汇报数据的问题。
* [舰娘信息] 修复了记录窗口位置的相关问题。

R.F.C

**Comment by alvin-777** [comment]
4.1.0 Mac版还在用electron 0.33.3？？？

**Comment by dkwingsmt** [comment]
你怎么发现的！……吃吧出来接锅 @Chibaheit  另外已经更新到主楼

**Comment by alvin-777** [comment]
![image](https://cloud.githubusercontent.com/assets/13615512/11235063/cd807850-8e19-11e5-9f5e-e90a2b3586f0.png)
![image](https://cloud.githubusercontent.com/assets/13615512/11235066/d78bea5a-8e19-11e5-9f34-d3498ddf1843.png)
（顺便那个about poi 里面的显示什么时候才能改成真正的poi的信息？）

**Comment by dkwingsmt** [comment]
我觉得把 version 改对就不错了……
