### ISSUE TITLE
把推送信息的舰队名改为舰队编号

### ISSUE THREAD

**Issue by dkwingsmt** [poooi/poi#543]
编成展开的受害者太多，太日经
舰队编号本身也很直观，不损伤使用体验

+ 修改为“第4舰队「第3艦隊」”这种形式
+ 需要改 i18n
+ 考虑把基础四类的内容改到 title
+ 考虑塞 option

**Comment by yukixz** [comment]
bump @dkwingsmt

**Comment by dkwingsmt** [comment]
感觉已经没有很多类似汇报了。暂时关了吧。
