### ISSUE TITLE
HTTP 代理认证无法使用

### ISSUE THREAD

**Issue by azuis** [poooi/poi#547]
如果设置代理服务器密码，点击登陆直接白屏。 从开发者工具中看不到有任何网络请求。
代理服务器用户名含有 @ 字符。

**Comment by azuis** [comment]
经测试，如果用户名中没有 @ 字符的话是可以看到正常请求的。 大概是用户名中特殊字符处理的问题

**Comment by KochiyaOcean** [comment]
用户名含有`@`的话再加一个`\`试试看？
比如 `blah\@blah`

**Comment by azuis** [comment]
@KochiyaOcean 添加后重启poi 直接提示网络错误

**Comment by KochiyaOcean** [comment]
JS 的 http 代理设置是 
`http://#username:password@address:port`
您可能需要换一个不带有 @ 的用户名……

**Comment by KochiyaOcean** [comment]
或者使用 `%40` 代替 @ 看看？

**Comment by azuis** [comment]
@KochiyaOcean 都是能显示第一页，但是点击任何链接白屏

**Comment by KochiyaOcean** [comment]
…………还是换一个不带 @ 的用户名吧……

**Comment by nekopoi** [comment]
不行啊 用户名 密码都只有字母和数字的情况下 依旧会在login的地方白屏…… 5.1.0-beta1也还是这样。感觉其实是poi的浏览器的https访问代理会出现问题。
