### ISSUE TITLE
调整分辨率处增加“恢复原分辨率”按钮

### ISSUE THREAD

**Issue by dkwingsmt** [poooi/poi#548]
有很多新米不知道原分辨率是多少呢……

**Comment by KagamiChan** [comment]
既然加了一个原始分辨率，可不可以再加几个比如1.5倍2倍分辨率的快速预置？感觉对部分平板用户会有用

**Comment by dkwingsmt** [comment]
这样做下去就没完了啊……说实话分辨率基本上也都是一次设置的，也就是说比如你想设两倍，那你就直接输入1600然后就一劳永逸了。恢复原分辨率的意义其实只是有些新米_不知道_原分辨率是多少。

**Comment by KagamiChan** [comment]
平板有横向和竖向，有切换分辨率的可能性？
虽然我觉得竖向玩比较舒服
