### ISSUE TITLE
Add the fleet LoS value calculation (in addition to 2-5 (fall)) into poi 

### ISSUE THREAD

**Issue by c933103** [poooi/poi#549]
As per http://kankoregouchin.blog.fc2.com/blog-entry-23.html , it seems like arillery spotting trigger rate positively correlated to the fleet los. the current los value calculation only include setting for 2-5 (old) and 2-5 (fall), but does not include the calculation of this fleet los. (Well, since the post being made in the link were 1.5 years old so I don't know if it still hold true for the current game environment in kancolle, but at least it show that the fleet los which simply adding los value of all the equipment and kanmusu together have its use at least up to the time.)

**Comment by dkwingsmt** [comment]
Whether it should be added depends on, not whether "it has its use", but whether users care about it.
I wouldn't say it worths being added there unless a considerable portion of users are really going to use it.

**Comment by KagamiChan** [comment]
Close because LoS formulae have evolved since the issue
