### ISSUE TITLE
希望增加复制粘贴功能啊！

### ISSUE THREAD

**Issue by Lenserf** [poooi/poi#55]
Mac 版本，1.0.0 无法复制粘贴，很不方便，希望改进！

**Comment by magicae** [comment]
只有 Mac 不能复制粘贴，应该是 Electron 平台相关问题，目前无法 Fix。

**Comment by magicae** [comment]
Fixed by https://github.com/yudachi/poi/pull/124

**Comment by magicae** [comment]
似乎问题还在

**Comment by PHELiOX** [comment]
地址栏复制粘贴没问题

**Comment by Lenserf** [comment]
3.0.0 beta2 git版本，OS X 10.10.4 (14E46)，地址栏和代理页面复制粘贴正常

**Comment by magicae** [comment]
@PHELiOX @Lenserf 试试git版

**Comment by PHELiOX** [comment]
@magicae 试了最新的了，也没问题

**Comment by magicae** [comment]
@Lenserf @PHELiOX 试试打包后的最新版

**Comment by PHELiOX** [comment]
打包版本不能复制了。。大概是因为快捷键没了？
另外也不存在拖放之类的方法

**Comment by magicae** [comment]
https://github.com/yudachi/poi/commit/1aa92b77d1b8bd9a1f9f19e9ed337ffc5f3259fc

把这个commit revert一下再打包试试

**Comment by PHELiOX** [comment]
也不行

**Comment by Chibaheit** [comment]
需要重写menu..因为移除了默认的menu

**Comment by magicae** [comment]
@Chibaheit 我上面那个让他revert的commit里就是重写的menu

**Comment by Chibaheit** [comment]
@magicae 作者给我的答复是这样..我去看看吧..

**Comment by magicae** [comment]
Related https://github.com/atom/electron/issues/2402
