### ISSUE TITLE
有没有关于提督个人信息的API? API for teitoku information

### ISSUE THREAD

**Issue by KagamiChan** [poooi/poi#550]
具体一点来说，就是存储 `/kcsapi/api_get_member/record` 所得到的部分信息，比如各类出击数、胜率之类的

More specifically, the API providing information from `/kcsapi/api_get_member/record`

**Comment by Ayaphis** [comment]
不是很明白你的意思？ poi里game.response事件不区分包，你可以监听这个事件，然后在读到这个包的时候自行保存？

**Comment by KagamiChan** [comment]
嗯，自己试着写的一个插件有这方面的数据的需求，看开发者文档的时候发现没有，所以问一下，毕竟内置的会比较方便
嗯那我就自己监听好了

**Comment by yukixz** [comment]
hmm... 目前来说没有提供这几个数据的公开接口，建议您自己捕获数据。

**Comment by KagamiChan** [comment]
看了一下，其实我需要的数据在 `/kcsapi/api_port/port` 的 `api_basic` 里面都有，娇喘这 api……
