### ISSUE TITLE
求分辨率调整时手滑多打了一位数于是白屏的解决办法

### ISSUE THREAD

**Issue by hoshinotaichi** [poooi/poi#552]
今天刚下了POI ，改分辨率的时候手滑多打了一位，然后白屏卡死，第二次打开之后就成了没有响应的UI界面 改动窗口大小直接白屏。有啥能在程序外改设置的办法……也就是设置文件在哪 删掉也好打开修也罢……
所以要怎么办呢orz

**Comment by Ayaphis** [comment]
非4.2.0版本的win用户么？在poi目录下的config.cson

**Comment by hoshinotaichi** [comment]
已经暴力修改了 多谢
