### ISSUE TITLE
Mac平台全屏关闭窗口导致崩溃

### ISSUE THREAD

**Issue by BowenYang** [poooi/poi#553]
poi版本4.0.0，OS版本El Captain
Mac平台上开启poi全屏后，打开其他插件自动全屏后，command+W关闭插件窗口时会视插件不同出现黑屏或主程序崩溃问题。怀疑是上游Electron的锅。
目前比较严重并在我的机器上复现过的是：
全屏开启“装备改修”窗口后，关闭插件窗口，poi主程序崩溃并报错，部分报错信息如下：

    Process:               Electron [31814]
    Path:                  /Applications/Poi.app/Contents/MacOS/Electron
    Identifier:            com.github.electron
    Version:               0.33.3
    Code Type:             X86-64 (Native)
    Parent Process:        ??? [1]
    Responsible:           Electron [31814]
    OS Version:            Mac OS X 10.11.1 (15B42)
    Report Version:        11 
    Crashed Thread:        0  CrBrowserMain  Dispatch queue: com.apple.main-thread

    Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
    Exception Codes:       KERN_INVALID_ADDRESS at 0x0000000000000018
    Exception Note:        EXC_CORPSE_NOTIFY

    VM Regions Near 0x18:
    --> 
        __TEXT                 000000010fc0c000-000000010fc0d000 [    4K] r-x/rwx SM=COW  /Applications/Poi.app/Contents/MacOS/Electron

    Application Specific Information:
    objc_msgSend() selector name: windowDidResize:
望能修复。

**Comment by alvin-777** [comment]
这个问题分两种情况：
1. 一些新窗口插件如舰娘信息和装备信息，因为需要在后台持续接收数据，所以在“关闭”的时候其实只是隐藏了窗口，所以在全屏的情况下看起来就像是“黑屏了”。这是electron的问题，只能无视，如果忍受不了话。。就先把窗口还原再关闭吧。。
2. 另一些新窗口插件如装备改修，并不需要在后台接收数据，为了节省电脑资源，在关闭时会完全退出其render process。这个时候crash肯定也是clectron的锅，不过我试了electron v0.33.3和 v0.35.0在Yosemite下都能正常关闭并不会crash，所以我估计是electron在El captain下特有的bug。。只能等他们修了。。

**Comment by BowenYang** [comment]
OK 我觉得也是…那麻烦了…这个问题先close掉吧…

**Comment by alvin-777** [comment]
虽然我自己没遇到过，不过Electron v0.35.2 号称fix了你所描述的crash： https://github.com/atom/electron/releases/tag/v0.35.2
