### ISSUE TITLE
喷火的时候资源统计错误

### ISSUE THREAD

**Issue by KochiyaOcean** [poooi/poi#558]
喷火前
![image](https://cloud.githubusercontent.com/assets/8194131/11345173/618e8318-9250-11e5-9343-e058e3bfe5b1.png)
![image](https://cloud.githubusercontent.com/assets/8194131/11345178/665629c8-9250-11e5-8ee1-e5fdee73dc55.png)
喷火后
![image](https://cloud.githubusercontent.com/assets/8194131/11345184/6eece1c6-9250-11e5-915d-4b8ff541d0b9.png)
![image](https://cloud.githubusercontent.com/assets/8194131/11345203/73b82c42-9250-11e5-889d-428e4dd10f49.png)
没有扣去喷火器的 10 个计数反而是铝扣了 1

**Comment by dkwingsmt** [comment]
为了展示这件事专门大建了一次欧选（x
