### ISSUE TITLE
旋转屏幕时画面不更新

### ISSUE THREAD

**Issue by dkwingsmt** [poooi/poi#561]
![image](https://cloud.githubusercontent.com/assets/1596656/11380916/994621da-92be-11e5-90fa-0167409feb9e.png)

![image](https://cloud.githubusercontent.com/assets/1596656/11381767/95ba0ff4-92c3-11e5-9fd6-8fd0a5fd06d2.png)

**Comment by KochiyaOcean** [comment]
求资助平板测试

**Comment by dkwingsmt** [comment]
嗯所以加上了 help wanted 标签【x

**Comment by dkwingsmt** [comment]
更新【】

**Comment by c933103** [comment]
#446
