### ISSUE TITLE
开发读取和向其他数据库发送建造/开发/掉落数据的插件是否可能?

### ISSUE THREAD

**Issue by axmmisaka** [poooi/poi#563]
如kancolle-db这类数据库 是否可以开发发送向其数据库数据的插件

同样地,是否可以开发读取包括poi-statistics中的建造/开发/掉落数据 方便直接在游戏中使用?
虽然我想开发但是我是不会coffeescript...而且kancolledb只给了一种第三方发送api(忘记了...好像是只有一种吧

**Comment by yukixz** [comment]
关于向 kancolle db 发送数据：https://github.com/poooi/poi/issues/78

**Comment by Chibaheit** [comment]
1.KanColle-db没有打算
2. poi-statistics用的是mongodb存储的.可以参照 https://docs.mongodb.org/manual/ 处理,没有作为插件的考虑 
PS: 有需求的话可以试着自己开发一下…

**Comment by axmmisaka** [comment]
感谢。

**Comment by magicae** [comment]
自己写插件没问题的 不需要会coffeescript 因为coffeescript只是糖衣javascript 用传统的js就好了

**Comment by axmmisaka** [comment]
😞本初中狗只会cpp
准备拿example改下

**Comment by KagamiChan** [comment]
最近也在研究发送数据，参考 poi-statistics 和 akashic-records 是极好的，主要逻辑就是对 response 进行监听，按不同的 api url 来提取数据，再 post 到指定的地址。感觉最大的障碍不是 coffee 而是娇喘的乱七八糟的 api ……
