### ISSUE TITLE
关于4.2.1直连不能

### ISSUE THREAD

**Issue by August18** [poooi/poi#564]
原来3.6.1用控制台直连的，换了4.0.0之后一直到4.2.1点击设置本地cookie都无法直连游戏，用chrome控制台直连也不行了。现在只有3.6.1版本还能直连

**Comment by taroxd** [comment]
> 用chrome控制台直连也不行了

那就去问 chrome 咯。可能是因为 chrome 版本更新了吧

**Comment by August18** [comment]
重装了好多遍chrome似乎都没有效果

**Comment by taroxd** [comment]
我的意思是，这是 chrome 的问题而不是 poi 的问题

**Comment by dkwingsmt** [comment]
也就是说咱这边没法解决……

**Comment by August18** [comment]
好的我再想办法搞搞
