### ISSUE TITLE
字型問題

### ISSUE THREAD

**Issue by xoxoxoooxx** [poooi/poi#565]
這邊跑的平台是mac book(OSX Yosemite 10.10.5)
大致看了一下源碼
知道有些插件的字並不全寫在json(會有部分到index.cjsx之類的)，所以有些插件會一半正體一半簡體
因此我直接對dmg做修改

我嘗試性的修改插件的index.cjsx部分(有幾個插件的字寫在裡面)
但發現只能改插件的名稱(任务信息任 這類的)
再詳細改下去(编成任务 等等)
會造成整個程式的字全部消失的狀況(左下角的按鈕也都不見了)
我修改過不只“任务信息”這個插件，其他的一樣也有這個問題

最後想要知道一下windw.language這個global設定在哪裡
很明顯的像是经验计算的插件都有正體中文，但設定檔都只載入簡體的
就算我修改插件內部的defaultLocale: 'zh-TW'，也會造成字全部消失
所以我想要直接把global設定成'zh-TW'看會不會好一點

先感謝開發者的辛勞跟解答

**Comment by KochiyaOcean** [comment]
i18n 模组不支持多组 configure，需要每个插件使用单独的 i18n 模组。
参照已有 i18n 模组的插件的 package.json 文件吧

**Comment by xoxoxoooxx** [comment]
我觀察插件是分兩種：有i18n跟沒i18n的
有i18n的我改過index.cjsx內部的
locales: ['en-US', 'ja-JP', 'zh-CN']
  defaultLocale: 'zh-CN'
將zh-CN換成zh-TW
當然插件本身有zh-TW
這一樣會讓所有字都消失

然後沒有i18n的，assets內部通常都有json的資料檔
修改了會出事
而index.cjsx內部只能動
module.exports內的
  displayName: <span><FontAwesome key={0} name='indent' /> 任務資料</span>
我如果動其他的部分也是會出事

**Comment by alvin-777** [comment]
只是字消失了还是所有东西包括按钮tab图标等等全消失了？

一般如果全消失了代表程序load的时候出错了，你按 Cmd+Opt+i 打开开发者工具看看console有没有什么error message？

**Comment by xoxoxoooxx** [comment]
原來開發者工具有辦法用鍵盤叫...
是所有東西都消失沒錯
有出現一行
Uncaught SyntaxError: unmatched OUTDENT
/Applications/Poi.app/Contents/Resources/app/node_modules/coffee-react/lib/coffee-react-script.js:53

**Comment by KochiyaOcean** [comment]
locales: ['en-US', 'ja-JP', 'zh-CN']
有加 zh-TW 进去么

**Comment by KochiyaOcean** [comment]
unmatched OUTDENT 应该是括号没成对之类的问题……

**Comment by alvin-777** [comment]
indentation的问题吧？
coffee script 对空格很敏感

**Comment by xoxoxoooxx** [comment]
感謝各位的解答
我應該是被MAC內建的editor給賣了
用terminal開vi editor改就成功了
能麻煩開發者提供一下好用的編輯器嗎？
不想再被賣了...

**Comment by KochiyaOcean** [comment]
推荐使用 Atom
Github 官方出品，插件多
就是启动速度慢了点（x

**Comment by jayjayzju** [comment]
推荐sublime text 2

**Comment by dkwingsmt** [comment]
推荐 Mac Vim

**Comment by alvin-777** [comment]
我觉得如果不是需要大量编程的话，用~~卡卡的~~ [Atom](https://atom.io/) 就完全足够了，功能齐全，界面友好

Sublime毕竟不是免费(原则上来说)

vim什么的如果不是狂热到一定程度还是算了吧。。。

**Comment by KagamiChan** [comment]
atom 貌似要安装 react 插件
还有貌似还需要调整缩进为 2 空格

**Comment by xoxoxoooxx** [comment]
感謝大家的推薦，沒有問題了！

**Comment by xoxoxoooxx** [comment]
所以coffee對於空格的接受度到底是多大？
Subllime有輔助套件可以用嗎？

**Comment by yukixz** [comment]
sublime 设置成 2空格缩进 就好了

**Comment by KagamiChan** [comment]
sublime 的 react 语法包有 ReactJS https://github.com/reactjs/sublime-react
但是高亮方案貌似只有 coffeescript 或者 react 的
babel 的维护者说不接 cjsx 的锅，better-coffeescript 貌似支持度也不好

**Comment by taroxd** [comment]
@KagamiChan https://github.com/Guidebook/sublime-cjsx

**Comment by KagamiChan** [comment]
@taroxd 多谢，看了一下效果还不错，虽然我还是会用 atom - -

**Comment by xoxoxoooxx** [comment]
感謝各位的熱心回覆，問題解決了！
