### ISSUE TITLE
经常性的画面卡住不动但是游戏继续运行

### ISSUE THREAD

**Issue by 7964** [poooi/poi#570]
在出击的时候经常出现，然后鼠标还可以点击操作游戏，用截图键截到的画面是实时更新的。。。
其他程序都正常运行，内存也没占多少

**Comment by Ayaphis** [comment]
<del>FLASH卡了吧。。。</del>

**Comment by 7964** [comment]
所以怎么解决？别的要用到flash的地方都没问题啊

**Comment by xoxoxoooxx** [comment]
我也有這個問題
剛剛自己試了一下，chrome單獨開遊戲是沒問題的...

我隨便自己開關了poi的功能
我把設定裡的裝備檢查關掉就沒那麼卡
參考看看吧

**Comment by nagatoyk** [comment]
装备检查和床位检查 都会卡屏, 我是这两个开关开着的时候 任何点击操作之前都会卡住 然后在猛的一跳界面

**Comment by 7964** [comment]
床位检查和装备检查都关闭了还是会卡，刚刚刷闪的时候又gg了
现在就开着最基本的未卜先知，任务舰娘装备信息看看= =
我用chrome和kcv的时候是没这个问题的

**Comment by 7964** [comment]
插件只剩4个也还是会卡死。。。

**Comment by Wafer-Li** [comment]
嗯……我曾经遇到过这个问题，后来是升级了一下 Electron 就好了，个人认为是 Electron 的某个版本对 Flash 的支持不佳导致的。

**Comment by taroxd** [comment]
我有一同学遇到类似的问题，发现是金山词霸的自动取词功能导致的。

**Comment by Wafer-Li** [comment]
@taroxd 
:joy:  金山毒霸什么时候改行成字典软件了？

发现我上面描述的状况和楼主不一样，当时那个版本的时候是直接连 游戏音乐都停了。

**Comment by taroxd** [comment]
我说的金山词霸不是金山毒霸啦= =

**Comment by Wafer-Li** [comment]
@taroxd 
:joy:  写一晚上程序有点心力疲惫。

顺便有时候也出现过画面卡住但是有声音的问题，可以通过调整一下窗口大小解决。

**Comment by nagatoyk** [comment]
总感觉poi 特吃内存
