### ISSUE TITLE
插件列表为空时，插件下拉菜单提示用户去插件中心下载

### ISSUE THREAD

**Issue by dkwingsmt** [poooi/poi#573]
> 在寻找你的插件吗？
> 到设置里找到“插件中心”
> 安装你想要的插件，再重启 poi 就有啦

【……好像并没有这么长的空间……

**Comment by Ayaphis** [comment]
空？！？！？

**Comment by dkwingsmt** [comment]
第一次打开新版本的时候，一个插件都没有啊。插件下拉菜单为空。

说实话，当时让我恐慌了一小下呢。

**Comment by taroxd** [comment]
为空的时候点击直接跳转到插件中心吧

**Comment by dkwingsmt** [comment]
我觉得这样不如给出提示信息。

一方面不够直观（我点的插件列表，还是为空啊……用户并不一定会注意到你的插件列表界面更新了）

**Comment by KochiyaOcean** [comment]
增加插件中心选项的话设置的 tab 就不得不从使用 Tabs 的内置方法改为 setState 了
性能不可避免的会下降（试验结果
