### ISSUE TITLE
Better accessibility of language settings

### ISSUE THREAD

**Issue by dkwingsmt** [poooi/poi#575]
建议：
- 将“语言”的设置放到设置的最上面
- 添加一个“地球”的图标【或者别的用于指明这是 i18n 的图标
- 在选择语言栏下方添加“更改语言后，部分文字需要重启才能应用”

**Comment by alvin-777** [comment]
* 第一次打开poi的时候 / config 里没有language setting的时候，弹框(或者随便怎样)提示选择语言

**Comment by dkwingsmt** [comment]
如果能做出来的话，感觉非常不错

**Comment by dkwingsmt** [comment]
不过，希望这个框不会被“随便点到屏幕的任何地方”给消失掉

**Comment by magicae** [comment]
默认情况下已经是navigator.language了 取决于电脑设置的系统语言的

**Comment by KochiyaOcean** [comment]
主要是 en_UK 之类的语言的场合
还是需要对 navigator.language 做一些调整的

**Comment by c933103** [comment]
新加坡和馬來西亞的中文用戶貌似也是簡體為主。
2015/11/29 21:59 "東風谷オーシャン" <notifications@github.com>:
