### ISSUE TITLE
4.2.1没有自带代理了吗

### ISSUE THREAD

**Issue by aajiangzz** [poooi/poi#578]

**Comment by dkwingsmt** [comment]
内置ss模块已经因为无人维护导致稳定性不佳而去掉了。使用ss的话请寻找独立客户端并使用socks5代理。原来的测试用代理也一并取消了。

**Comment by aajiangzz** [comment]
感觉这个还是很有用的，岛风狗今年开始关键时刻总是抽疯，基本都是靠poi挺过来的

**Comment by KochiyaOcean** [comment]
shadowsocks 配置可以参照旧版的配置文件
