### ISSUE TITLE
关于新的plugin management的几个问题及建议

### ISSUE THREAD

**Issue by alvin-777** [poooi/poi#579]
首先赞美一下欧选，几个月前我就想做这功能，但一直没机会研究，然后欧选几天就做好了

* 下载新插件有时会莫名卡住，然后。。就会只见那个圈圈一直转，永远卡下去。。。没有error message，没有任何提示，也不会重试或者time-out，只能重开然后才能再install
* 鼠标cursor指在button上和指在button上的字上时都不一样，普通button和disabled button都不一样
* disabled button在好几个theme下都。。看起来怪怪的。。。
* check update按了之后没有任何回馈，让人感觉十分不安。。（比起“我所有插件都是最新的”，给人更多的感觉是“这功能还没做吧／没起作用吧？”）

另外希望能够更新doc，新写一个插件的话要做些什么才能用得上自动更新之类的功能，什么的

**Comment by KochiyaOcean** [comment]
文档更新了哦。
是否有更新由全部更新按钮来指示，如果不放心我可以再写 alert

**Comment by dkwingsmt** [comment]
@KochiyaOcean 你是说poi平常使用的那个状态栏？我觉得容易被忽视……不如就地加一个条比较好……

**Comment by KochiyaOcean** [comment]
另外可能是我这边网络太好了下载从来没出过问题啊（逃

**Comment by alvin-777** [comment]
* 如果插件爆炸，有可能导致poi整体爆炸，这个情况下完全无法通过poi来禁用/更新/删除插件，只能手动打开plugins文件夹删除。而且往往不知道出问题的插件到底是哪个，还要全删。
而普通用户很可能根本找不到plugins文件夹（比如mac上Library文件夹默认为隐藏，普通用户可能根本不知道其存在），相当麻烦。希望有更好的解决方案。
* 为什么。。install 跟插件名不对齐。。。？每次要看半天到底是上面的还是下面的
![image](https://cloud.githubusercontent.com/assets/13615512/11557303/bd4dc7e6-99f7-11e5-8c90-974c72ffb104.png)
* 希望增加“添加本地Repo”选项，现在用git版插件操作起来不太方便

**Comment by taroxd** [comment]
git 版操作不方便+1。

本地提升版本号不上传的话，每次启动都会有更新提醒 #581 希望可以解决

**Comment by KochiyaOcean** [comment]
有一个本地文件用来限制启用插件的最低版本，低于该版本则主动禁用
安装前后使用同一套布局

**Comment by KochiyaOcean** [comment]
高版本提示的问题已经解决 https://github.com/poooi/poi/commit/c533db10b3e5f2febd61dc8d22f7f5acae414c6e

**Comment by KagamiChan** [comment]
从我对于新插件系统的理解来看，只要在 npm 上以发布以 poi-plugin 为开头的 module，就会在插件列表中显示。于是我有两个疑问：

- 是否需要标识官方插件（或者，基本插件），防止用户误下载到李鬼插件
- 现有的主程序与 API 是否足够安全，比如说，仅仅靠插件是否有获得 api_token 的可能性？

**Comment by KochiyaOcean** [comment]
只有官方插件才能从本体中下载
非官方插件只能手动安装

**Comment by taroxd** [comment]
剩下的爆炸情况：比如 loadUrl 改成 loadURL，React 改成 ReactDOM 之类的。
比如，如果将来插件为了适应 poi 6.0.0  而做出了不兼容更新，仍在使用 poi 5.x.x 的用户更新插件后就会爆炸

**Comment by KochiyaOcean** [comment]
所以只能更新到最新版本了
插件方维护一个可以启动的本体最高版本也是一种可行方案

**Comment by taroxd** [comment]
如果这样做的话，把插件下载下来才能知道所需本体最低版本是多少吧 ORZ

**Comment by KochiyaOcean** [comment]
对，不过暂时没有更好的解决方法了

**Comment by JenningsWu** [comment]
这种不兼容爆炸问题感觉很严重啊…感觉需要在服务器维护一个插件兼容列表了，然后每次启动的时候向服务器获取一个这个表的version，如果不匹配就更新这个表？
另外，感觉也需要有“更新到插件指定版本”的功能。不一定有这个UI，但是可以限制不总是更到最新版本。

**Comment by KochiyaOcean** [comment]
可以是可以不过这回就必须用自己的服务器了……还是说这个列表也作为 npm 模组发布？

**Comment by KagamiChan** [comment]
两个脑洞：
- 在本地记录一个上次成功运行没有爆炸的插件版本列表
如果爆炸了，在载入插件之前，能够选择回退到这个列表上的插件版本

- 如果爆炸了，在下次启动之后切换到“安全模式”，列出爆炸之前的插件更新记录，让用户选择回退……

**Comment by Ayaphis** [comment]
小白求问npm上所有历史发布过的版本都在？

**Comment by KochiyaOcean** [comment]
感觉挺麻烦的……
目前的想法是爆炸的插件不加载，提示本体版本过旧
然后可以从发布的插件包中获得旧版本插件

**Comment by KochiyaOcean** [comment]
https://github.com/poooi/poi/commit/462e304a4aa6fc04f8cea5fb723e59c10b3958b6 https://github.com/poooi/poi/commit/4c8b9f45b9254ca44aba26ab0c4a9e57b37b6597 
在插件将会加载失败的时候报错并禁用……大体的写好了

**Comment by alvin-777** [comment]
维护兼容列表实在太过麻烦

我的想法是这样：
* 检测到新版本，用户点了“更新”之后，先把现有插件复制一份作为备份
* 更新插件，重启poi
* 插件爆炸，load失败，自动禁用该插件，在插件管理里显示“无法使用此版本”，并提供“删除”和“恢复前一版本”
* 如果用户选“恢复”，直接删掉新版文件夹，把旧版文件夹移回来
* 重启poi，插件复活

这样还有个好处，就是前一版的插件就算用户魔改过也能够完美恢复

----
另外我觉得其实可以在插件中心列出npm上所有能找到的poi-plugin，非官方的打个“非官方”tag就是了。
或者(至少)加一个“寻找更多插件”的按钮，点击直接跳转到 https://www.npmjs.com/search?q=poi-plugin-
这样也能够有效吸引和刺激更多的人来为poi写插件
毕竟对于绝大多数用户来说根本不知道npm是个什么鬼，非官方插件基本死路一条

**Comment by KochiyaOcean** [comment]
太麻烦了，目前没有对旧版本做持续支持的打算

**Comment by yukixz** [comment]
这里的「旧版插件」已经是历史的尘埃了
