### ISSUE TITLE
[卫星]舰娘名自动翻译成罗马注音

### ISSUE THREAD

**Issue by alvin-777** [poooi/poi#580]
目前的想法是：
* 自动把api里给的api_yomi翻译成romaji
* 少数舰名单独特殊处理，比如"Bismarck drei"不翻，"Prinz Eugen改"只翻最后的"改"字，以及伊号潜水艇等等
* 原名／romaji 自动切换——即render的时候不需要做额外判断
* 提供相应api以求现有code的最小改动，以及所有插件都可以直接用

不使用i18n的理由：
- 舰名跟其他东西不太一样，只需要一种翻译。识得汉字的都能看原名，即使以后有了法文版、德文版的poi（有生之年），舰名依然是给他们romaji
- i18n工作量大，容易出错
- i18n需要频繁手动维护

预计活动结束后开工（或者如果我能提前捞到船。。。）

因为刚看到欧选开了https://github.com/poooi/plugin-translator 所以感觉还是先提一下，以免重复造轮子。。

_欢迎更多的建议_

**Comment by dkwingsmt** [comment]
日文字 - Romaji 的翻译我已经从 wikia 上扒下来啦。大概长这样
```
{
  "長門": "Nagato",
  "陸奥": "Mutsu",
  "伊勢": "Ise",
  "日向": "Hyuuga",
  "雪風": "Yukikaze",
  "赤城": "Akagi",
  "加賀": "Kaga",
  "蒼龍": "Souryuu",

...


  "海風改": "Umikaze Kai",
  "江風改": "Kawakaze Kai",
  "速吸改": "Hayasui Kai",
  "Graf Zeppelin改": "Graf Zeppelin Kai",
  "嵐改": "Arashi Kai",
  "萩風改": "Hagikaze Kai",
  "鹿島改": "Kashima Kai",
  "伊168改": "I-168 Kai",
  "伊58改": "I-58 Kai",
  "伊8改": "I-8 Kai",
  "伊19改": "I-19 Kai",
  "まるゆ改": "Maruyu Kai",
  "伊401改": "I-401 Kai",
  "U-511改": "U-511 Kai"
}
```

**Comment by KochiyaOcean** [comment]
translator 的想法是翻译所有 api_name，不过不是所有有 api_name 的都有 api_yomi

**Comment by JenningsWu** [comment]
想到日志的i18n问题就好想哭啊(´･ω･`)
目前想法是找个或造个轮子实现从日文到任意语言的相互转换。。

**Comment by dkwingsmt** [comment]
日志的 i18n 怎么了啊 0 0

**Comment by c933103** [comment]
直接hotlink
https://github.com/KC3Kai/kc3-translations/blob/master/data/en/ships.json
呢？
2015/11/30 17:46 "Tong Mu" <notifications@github.com>:

**Comment by dkwingsmt** [comment]
……表格做得真是齐全啊噗。未实装的船全部一股脑写上去了。

**Comment by JenningsWu** [comment]
涉及到显示、储存、导入导出的问题，以及要避免部分英语部分日文的情况。
所以经常面临要转换的问题。。

**Comment by dkwingsmt** [comment]
我还是认为直接从 wikia 扒比较好。

一方面，这个表格只做了无印的名字，涉及到处理改造的问题。

另一方面，反正都要扒一大堆东西……刚才把装备列表扒下来了（和船的格式几乎一样），之后再去扒任务和远征……这些东西，都是要定期更新的。

**Comment by c933103** [comment]
這表格把改造狀態分開處理放在頂了
2015/11/30 18:03 "Tong Mu" <notifications@github.com>:

**Comment by dkwingsmt** [comment]
![image](https://cloud.githubusercontent.com/assets/1596656/11468754/9613e24c-9717-11e5-98e6-7b51317d26e2.png)
吐个槽，这翻译是怎么回事，只把あきつ带上了没有丸，但是后面的罗马字是有丸的。


嗯我知道，但是我们自己做的时候也要处理改造了，parse string 什么的……真是能不做就不想做呀。

**Comment by c933103** [comment]
Line 131有有個丸字的秋津丸。沒記錯的話kc3改有些位置顯示秋津丸時在日文模式只能顯示三個字的樣子所以兩個都譯成英文全名

**Comment by c933103** [comment]
另外，同目錄下也有裝備任務遠征…如果可以處理使用的話就能省下另行維護的需要…

**Comment by dkwingsmt** [comment]
直接拿给我的感觉不太好_(:3 」∠ )_

不过远征和任务要是能直接拿确实方便得多啦【【

船名我还是建议就拖 wikia。

**Comment by c933103** [comment]
反正那邊基本上也是拖wikia然後cc-by-sa的…不然去那邊問問？

**Comment by dkwingsmt** [comment]
然而 poi 是 MIT 的【【不重要

**Comment by KagamiChan** [comment]
我问一下，之后的模式会是下边的哪一种，或者会有别的方式？
1. `$ships` 的 `api-yomi` 存储假名，在启用插件/功能之后变成罗马字
2. `$ships` 的 `api-yomi` 存储罗马字，启用插件/功能之后，换成 render `api_yomi`

此外对于 `_ships` 的 `api_yomi`，是不是也就跟着 `$ships` 一起变了


----
法文版的 poi ，如果真有人提了需求的话我可以帮忙做……

https://github.com/KC3Kai/kc3-translations/blob/master/data/en/ships.json 这个表没有麦姐的改三和改四，也没有各种甲

**Comment by Ayaphis** [comment]
api_yomi是游戏自带的假名，然而不是每个船都是，此外目前似乎并没有应用到这一值的场合
translator应该是直接改$ship的api_name
而所有的_ship的api_name都来自$ship

**Comment by alvin-777** [comment]
@KochiyaOcean 我的意思是translator只是不用管ships了，其他的还是你怎么想的怎么搞

@ 其他 去wiki或者其他proj扒一扒看起来的确不太麻烦。只是。。我觉得这明明是完全可以自动化实现的东西，为什么非要搞成人工的呢。。。？

@Ayaphis 舰娘信息的排序用了yomi，用汉字排序会有种种问题，具体参考comments： poooi/plugin-ship-info#21

另外我不赞成修改$ships或者_ships，我觉得那是api给出来的东西不应该随便去改动

**Comment by KagamiChan** [comment]
可不可以考虑加一个新的键，比如 `poi_romaji` 或者按照官方的风格 `poi_roma` 什么的

**Comment by KochiyaOcean** [comment]
修改 $ 数据已经有先例了，任务插件就是
而且不这么修改的话成本相当大，而且对插件不友好

**Comment by Ayaphis** [comment]
@alvin-777 OK，那边我没follow到。了解了

**Comment by c933103** [comment]
@dkwingsmt kc3主程式是MIT 翻譯檔(簡中除外)是ccbysa
@KagamiChan 甲和改二甲在頂部，zwei和drei無需翻譯

**Comment by KagamiChan** [comment]
@c933103 了解了

**Comment by dkwingsmt** [comment]
@alvin-777 不太懂你的回复，我是用脚本自动从 wikia 扒的，不是我手动一个一个拖的……

**Comment by alvin-777** [comment]
@dkwingsmt 扒下来是自动啦，但是扒下来之后总得检查吧？（可能还会需要调整）然后还得更新现有文件，test，pr，merge，发布插件新版本，最后用户还必须手动更新了插件并重启poi才能够生效，不是吗？

**Comment by KochiyaOcean** [comment]
![image](https://cloud.githubusercontent.com/assets/8194131/11503184/2bedb91a-987a-11e5-9619-4a947f7dfd1b.png)
海外舰和敌舰仍然需要特殊处理。
过度相信 api_yomi 乃是大忌

**Comment by KochiyaOcean** [comment]
如果确定需要使用 api_yomi 进行翻译的话依然推荐整合进 translator 插件。
毕竟特别判定的需要仍然存在，本体的更新速度还是太慢了

**Comment by alvin-777** [comment]
确实。。敌舰的yomi没有给出来，那没办法。。不过敌舰好像只有两个剧透里面才会用到吧？只能跟其他一样处理了。。。

做成插件的话有一个问题，其他的插件怎么用呢？修改api的方式我是不太喜欢。。

目前为止我想不出有什么舰名handle不了的，无非就是汉字翻译非汉字保留，只要做好了就没什么可更新的了。

**Comment by KochiyaOcean** [comment]
之前也说过了，修改 api 数据不是没有先例
只要没有深刻的不良影响，还是按照对本体改动最小的方法处理。

**Comment by KochiyaOcean** [comment]
与其大费周章地修改 poi 的 API 以后提供一个不能完全翻译的解决方法，还不如将这些工作交给插件。

**Comment by dkwingsmt** [comment]
你们说的我都看不太懂，总之，有什么我可以帮忙的吗？

**Comment by dkwingsmt** [comment]
这个算完工了吗？

**Comment by alvin-777** [comment]
不做了。你们都没人打算用
除非哪天有特殊需求了，或者我心血来潮。。

**Comment by dkwingsmt** [comment]
⋯⋯已经做完了啊我们😂 你拖现在的github版然后切换到英语看
