### ISSUE TITLE
poi是不是基于chrome开发的啊？是的话是不是可以把kc3kai移植到poi上？

### ISSUE THREAD

**Issue by OniityanH** [poooi/poi#588]
真行的话不就太刁了

**Comment by KochiyaOcean** [comment]
Electron 提供了加载开发者工具插件的功能，参见[这里](https://github.com/atom/electron/blob/master/docs/tutorial/devtools-extension.md)

不过不一定能够成功加载，或许需要做一定的适配
开放组暂时对此没有兴趣，不知道有没有人愿意做

**Comment by KagamiChan** [comment]
做过一些粗浅的尝试，简单总结一下：
- 通过载入开发者工具插件的功能，kc3kai 的 devtool 部分能够运行，不过需要通过 `$('webview').openDevTools()` 打开 webview 的 devtool
- 其余部分，比如设置和战术室，是需要手动载入的，试过在通过新窗口载入战术室，不通过 `chrome-extension` protocol 载入的话，kc3kai 的相对路径无法定位到部分代码；因为 kc3kai 使用全局的 jQuery 与 Dexie，需要单独进行载入；最后由于 `Electron` 本身架构的原因，新窗口的数据流与全局变量无法与 webview 的共享，需要进行额外的适配或模拟。这部分我对于 kc3kai 的代码不熟悉，就没有接着往下做了。

结论就是，不改动 kc3kai 与 poi 代码的情况下，通过插件形式加入 kc3kai 有可能性 - -

**Comment by KagamiChan** [comment]
作为补充，kc3kai 的运行需要在 electron 上模拟很多 chrome.* API。工作量会相当之大。

**Comment by Javran** [comment]
前kc3kai开发表示: 需要啥挪过来就是了(
