### ISSUE TITLE
经常无限转圈然后猫

### ISSUE THREAD

**Issue by binss** [poooi/poi#589]
版本为 MAC 4.2
代理方案为SS
具体表现为偶尔执行操作时开始转圈，然后等待若干秒后猫，已把网络错误重试次数设置为10，但好像并没有帮助？
使用Chrome时不会出现这种状况，偶尔转圈后，Switchy Omega跳一个数字然后就好了。推测进行了重试。
请问是否是POI的重试功能没有生效？

**Comment by PHELiOX** [comment]
大部分网络问题都是代理引起，你可以试试浏览器接ss登录游戏，看有没有相同问题。

**Comment by KochiyaOcean** [comment]
出于谨慎 poi 的防猫类型很有限，并不是所有类型都能防

**Comment by binss** [comment]
确实代理不够优质，SS是自建的，最近线路有点抽风，偶尔丢包。
经过几天的使用，发现在我当前的网络状况下，poi的猫率比Chrome高很多。但是我感觉是Chrome在丢包时进行了重试？
今天刷nga的时候发现有同样的问题：http://bbs.nga.cn/read.php?tid=8570200
