### ISSUE TITLE
希望增加对PAC的支持

### ISSUE THREAD

**Issue by smlrx1** [poooi/poi#593]
http代理不支持PAC自动切换。
我一般是dmm网站用代理的，游戏Flash用直连，这个切换用PAC实现，但现在的poi没找到能设置pac的地方

**Comment by OniityanH** [comment]
直连现在稳定吗？被ban几率大不大？

**Comment by smlrx1** [comment]
抱歉这么久才恢复。我是从9月开始用一个日本的服务器来绕过ip检测的，flash则是直连。直连至今没有什么问题，连接稳定，几乎不猫（但是这个跟网络有关，学校的网挺稳定的，家里的就不太行）。至于ban，这个我也无法保证，毕竟这都看dmm的。

在 2015-12-03 18:58:16，"OniityanH" <notifications@github.com> 写道：


直连现在稳定吗？被ban几率大不大？

**Comment by magicae** [comment]
https://github.com/poooi/poi/pull/773
