### ISSUE TITLE
请问能加上锁定窗口大小和位置功能么

### ISSUE THREAD

**Issue by solodefen** [poooi/poi#599]
我个人喜欢记录游戏经过，然而有次不小心（手抖）拖动了窗口一下，窗口大小变了，导致录出来的视频大小也改变了，强迫症伤不起，所以~请问能加上锁定窗口大小和位置功能么~

**Comment by KagamiChan** [comment]
给一个暂时的魔改方法（针对 4.2.0 版本）：
打开 /resources/app/app.coffee

在第 86 行（`global.mainWindow = mainWindow = new BrowserWindow`）后插入一行
````coffeescript
    resizable: false
````

改完的代码包含上下文如下所示：
````coffeescript
  global.mainWindow = mainWindow = new BrowserWindow
    resizable: false
    x: config.get 'poi.window.x', 0

````

记住，resizable前边有四个半角空格

**Comment by yukixz** [comment]
打开开发者工具、切换到 Console。
输入以下代码，可以锁定窗口大小
`remote.getGlobal('mainWindow').setResizable(false)`
没有找到可以禁止移动。

**Comment by KochiyaOcean** [comment]
其实我挺想加这个按钮的（强迫症（。

**Comment by KochiyaOcean** [comment]
禁止移动的实现……因为系统都没提供 API 所以解决方法是 Bound 的 x、y 偏离的时候修正为原值（然后就会各种闪什么的（。

**Comment by yukixz** [comment]
我觉得可以吧开发者工具那个按钮做成：点一下展开一系列 advanced options 的列表
然后把 开发者工具 窗口置顶 这两个少用的塞进去（逃

**Comment by KochiyaOcean** [comment]
不行，我还挺经常用那个按钮的说

**Comment by taroxd** [comment]
BTW, 我还想加一个打开 EXROOT。

目前做法一般是打 %APPDATA%/poi 或者点插件的「手动安装」去打开……

**Comment by dkwingsmt** [comment]
极其强烈支持

**Comment by solodefen** [comment]
好~已成功固定大小，感谢各位的指引~

**Comment by c933103** [comment]
如果要開advanced option的話 不如把 延遲狀態欄建造提示 之類 放進去
2015/12/05 1:33 "Dazzy Ding" <notifications@github.com>:

**Comment by alvin-777** [comment]
我记得几个月前我就提过点击展开不常用按钮的方案：#230

以及常用按钮放大，不常用按钮缩小双排放置的方案：
![image](https://cloud.githubusercontent.com/assets/13615512/11608063/ee3e58b6-9baa-11e5-9ea7-40e9b358eb14.png)

然而并没有人表示感兴趣。。。

**Comment by KochiyaOcean** [comment]
增加高度的还是谨谢不敏啦

**Comment by alvin-777** [comment]
不到10px而已，我觉得完全不是什么问题
或者两种都做出来用户自己选择也不是很难

**Comment by KochiyaOcean** [comment]
对于纵向布局还是很致命的

**Comment by alvin-777** [comment]
所以说让用户可以自己选就好了啊

**Comment by yukixz** [comment]
个人意见：除非必要、否则不提供两种方案给用户选择。
可选方案提高代码维护成本，而大部分用户只会使用默认。

**Comment by KochiyaOcean** [comment]
通过 Collapse 实现了展开功能 https://github.com/poooi/poi/commit/89bfeacdda24e4576db46af6b9336b51fca2de68
（不过不知道为什么横向 Collapse 并没有动画所以手动补上了
![image](https://cloud.githubusercontent.com/assets/8194131/11608751/304c1c64-9bad-11e5-8f06-a08e2f5df749.png)
![image](https://cloud.githubusercontent.com/assets/8194131/11608752/3554b540-9bad-11e5-8542-ab573bedddda.png)
