### ISSUE TITLE
为概览 tab 下的 MiniShip 增加一个 id

### ISSUE THREAD

**Issue by KagamiChan** [poooi/poi#600]
展开到舰队tab 的 MiniShip 有一个 `ShipView` 的 id
但是在概览 tab 下的 panel 并没有 id，无法单独针对该形式下的 MiniShip 进行样式的定义

P.S. 貌似 MiniShip 样式表优先度要高于主题的样式表，我得用 `!important` 才能实现属性的覆盖。

**Comment by KochiyaOcean** [comment]
![image](https://cloud.githubusercontent.com/assets/8194131/11606192/217da22a-9b53-11e5-81da-62845393cea7.png)
？？？

**Comment by KagamiChan** [comment]
如果用 css path 的话，那就只能是 `#MiniShip > div > div:nth-child(1)` 了，这个总觉得有点暴力，如果只通过 id 和 class，是定位不到的
