### ISSUE TITLE
[Feature Request] 舰队面板中，航母格子为空时显示格子大小。

### ISSUE THREAD

**Issue by yukixz** [poooi/poi#601]
方便配装

**Comment by taroxd** [comment]
我觉得可以不限于航母，还有航巡、航战、大淀之类的……

**Comment by dkwingsmt** [comment]
我建议：只在四个格子搭载不完全相同的时候显示。

**Comment by dkwingsmt** [comment]
#603 Merged

**Comment by KagamiChan** [comment]
![image](https://cloud.githubusercontent.com/assets/3816900/11919990/7521f1b0-a79c-11e5-8032-001489e91859.png)
我觉得对于驱逐舰不用显示格子大小吧

**Comment by dkwingsmt** [comment]
我觉得0的不显示吧？

**Comment by KagamiChan** [comment]
会有另外一些特殊情况，比如夕张可以装侦察机但是搭载为0，秋津丸可以装烈风但是搭载为0，所以我觉得对驱逐舰进行处理比较合适

**Comment by KagamiChan** [comment]
不过还有潜艇以及一些别的特例……对所有装不上飞机的舰娘都不显示计数会比较好

**Comment by yukixz** [comment]
对装不上飞机的船不显示需要大量 hardcode。
代码难看，界面上有些船有数字、有些没有，也很难看。
就这样了、不做。

**Comment by KagamiChan** [comment]
那换个思路，对于可以装飞机的格子，装上了飞机之后再显示计数？

**Comment by dkwingsmt** [comment]
那就是 revert 到这个 commit 之前了。

**Comment by dkwingsmt** [comment]
提示你关注一下本 issue 的标题……

**Comment by KagamiChan** [comment]
哦，说错了 - - 
可以装飞机的格子才显示计数

**Comment by yukixz** [comment]
https://github.com/poooi/poi/issues/601#issuecomment-166195713
