### ISSUE TITLE
Win 10 平板 用v4.2.1 出現地區錯誤

### ISSUE THREAD

**Issue by clothoest** [poooi/poi#606]
選了 設置dmm 地區cookie 也一樣

mac版本沒問題，只是win10平板有問題

**Comment by KochiyaOcean** [comment]
设置地区 Cookie 不一定对所有的网络生效，原因不明
如果有代理还是使用代理比较好

**Comment by clothoest** [comment]
奇怪就是....mac和win10平板也是同一個網絡....

**Comment by c933103** [comment]
剛看到個blog說凱擘大寬頻等ISP會受影響…
2016/01/06 15:03 "Dazzy Ding" <notifications@github.com>:
