### ISSUE TITLE
能否加入设定禁止通讯终止的弹窗？

### ISSUE THREAD

**Issue by djj200504001** [poooi/poi#607]
我家的网直连没问题，但是经常连接错误，但其实这时候随便操作一下就能变回正常状态，不过网页会弹一个通讯终止的弹窗要求刷新页面，我想禁止掉这个弹窗，能不能这设定里加入这个选项？或者有什么其他办法么？

**Comment by alvin-777** [comment]
从来没见过。。我就算把wifi关掉网线拔掉也没弹过什么窗口。。。

**Comment by c933103** [comment]
那個窗我記得是DMM彈的？禁掉算不算修改遊戲封包…？
2015/12/11 4:35 "Alvin" <notifications@github.com>:

**Comment by djj200504001** [comment]
明显不算啊……脚本的运用而已，Flash自适配也是同理

**Comment by djj200504001** [comment]
理论上只需要在控制台输入一段代码就行……然而我并不知道怎么弄

**Comment by KagamiChan** [comment]
没看到截图，不知道弹窗是怎么一个形式，如果是 alert 或者 confirm 的话…… 可以覆盖掉这两个方法，但是具体会有什么后果我就不清楚了……

**Comment by yukixz** [comment]
翻了一下、打开开发者工具、输入运行
`$('webview').executeJavaScript("DMM.netgame.reloadDialog=function(){}")`
就可以禁用这个弹窗。

**Comment by alvin-777** [comment]
右键点开发者工具，在console输入
`DMM.netgame.reloadDialog=function(){}`
与上面的方法等效

**Comment by Wayne8807** [comment]
@yukixz 
 然而并没有用...

**Comment by yukixz** [comment]
@Wayne8807 请自行搜索mactype教程

**Comment by dkwingsmt** [comment]
不要管楼上的傻 yuki。
@Wayne8807 poi 现在已经加入了这个选项了呀。在设置-基本设置最下面。

**Comment by Wayne8807** [comment]
@dkwingsmt 那个似乎也没用...
