### ISSUE TITLE
能否給航海日誌加入搜索功能

### ISSUE THREAD

**Issue by FungJiHsu** [poooi/poi#608]
現在只有統計
如果想搜索帶關鍵字的一條信息，需要導出才行

譬如，我忘記了我是甚麼時候撈出XX或者大建出YY的時候
我可以在輸入欄輸入XX或者YY（如果能自定義搜索範圍更好，撈，MVP，大破，旗艦）
然後包含關鍵字的條目都被篩選出來

**Comment by JenningsWu** [comment]
这个功能不是好早好早之前就有了嘛。。
![qq 20151120201814](https://cloud.githubusercontent.com/assets/6861365/11714212/7745b2c2-9eed-11e5-8a3d-c3b895e91eed.png)

**Comment by yukixz** [comment]
![screen shot 2015-12-10 at 7 24 22 pm](https://cloud.githubusercontent.com/assets/3337921/11714229/a2a7aa5c-9f73-11e5-9ea5-5aaf2a69eb7c.png)
请点击此处输入

**Comment by alvin-777** [comment]
![image](https://cloud.githubusercontent.com/assets/13615512/11714234/72788cf0-9f84-11e5-8a71-c4f38d8aaec7.png)
？？？
