### ISSUE TITLE
poi遇到问题

### ISSUE THREAD

**Issue by fantasiahunt** [poooi/poi#611]
win8 64位，岛风go，poi是3.5版本，此前一直用的都很好。今天心血来潮想试试魔改，结果替换完魔改文件白屏上不去，于是换回原来文件，依然白屏上不去。校验缓存，清缓存，重下缓存包，重启等各种方法都试了，就是上不去。改用kcv可以上去。求教这个问题怎么解决

**Comment by alvin-777** [comment]
清缓存了吗。。？
![image](https://cloud.githubusercontent.com/assets/13615512/11727529/0100f232-9fd0-11e5-8e33-05d6eb28f9da.png)

**Comment by alvin-777** [comment]
感觉是岛风go的问题，去问一下他们的客服看看
另外魔改应该是额外的文件，并不需要删除或替换掉原文件，所以不太明白你所谓的“换回原来文件”是什么意思

**Comment by fantasiahunt** [comment]
因为我不会用魔改，所以就擅自将战列表中找到缓存文件夹对应某船的文件删掉(已备份)，再把该船对应的魔改文件复制进来，发现此法不行后，又删掉该魔改文件，把此前备份的原始文件复制进来

**Comment by dkwingsmt** [comment]
那你应该提出的问题不该是“请问如何使用魔改？”吗

**Comment by fantasiahunt** [comment]
现在的问题是，无法用poi登录游戏，一直卡在“poi等待游戏数据”的状态，不出现黑船。所以跟魔改没有关系

**Comment by dkwingsmt** [comment]
你直接删掉所有缓存（浏览器缓存和用户缓存）重新来能解决吗？

**Comment by alvin-777** [comment]
请问你“清缓存”是清的哪里的缓存？

**Comment by fantasiahunt** [comment]
poi浏览器带的清缓存，清cookie也试过

**Comment by alvin-777** [comment]
3.5实在是有点老了，有些什么问题也很难考证，我建议你先去下个最新版试试能不能上

**Comment by alvin-777** [comment]
![image](https://cloud.githubusercontent.com/assets/13615512/11728672/e3b78ebe-9fd6-11e5-9348-c716c9ac7808.png)

**Comment by fantasiahunt** [comment]
谢谢，能上了
