### ISSUE TITLE
为了方便测试，希望能让部分用户检测并下载插件的 prerelease 版本

### ISSUE THREAD

**Issue by JenningsWu** [poooi/poi#613]
#### 新版本插件发布与更新的变化
* 旧版本：git 版用户（相当于内测用户）通过 git 更新插件。每过一段时间发布一次 poi，其中包含各插件的稳定版。
* 5.0.0: 各插件自行使用 npm 进行发布，每次发布后所有用户都会收到通知，并选择是否更新。移除了 submodule，现在 git 用户通过 github 手动跟插件最新 commit 变得很麻烦。

#### 可能带来的后果
插件发布频率变得很快，但发布前缺少除开发者以外人群的测试与使用报告。容易轻率发布包含 bug 的版本。
### 建议解决方案
规定插件必须先发 beta 版本，使用一段时间之后再正式发布。
例如若插件现版本为 2.4.2，在加了新的功能后，应先依次发 2.5.0-beta.0，2.5.0-beta1 等版本，待稳定后再发 2.5.0，供所有用户检测下载。
然后用户可以选择是否检测/下载插件体验版本。可以通过设置选项，或是 DEBUG=1 标识。

**Comment by JenningsWu** [comment]
看起来要做一些预测，比方说如果检测到正式版最新版本号为 4.3.2 的话，prerelease 版就要尝试两次检测，分别是 >= 4.3.3-a 和 >= 4.4.0=a ? (前提是插件版本遵守规定)

**Comment by JenningsWu** [comment]
哦，三次，还有 >= 5.0.0-a

**Comment by jayjayzju** [comment]
设置里加个选项就行了吧，愿意接收体验版更新通知的自己勾上，默认不勾

**Comment by JenningsWu** [comment]
现在的情况是没有“体验版”这回事，插件一发就是正式版。

**Comment by alvin-777** [comment]
应该可以通过github的api检测有没有prerelease版
不过更新么。。。。直接跳转到github release页面自己下载手动安装？

**Comment by JenningsWu** [comment]
一个方案
所有插件发测试版的时候打 beta 这个 tag
本体加个“检测插件 beta 版”选项，选了之后对于每个插件挨个 npm dist-tag，拿 beta 的 version 和 latest 的作对比……
