### ISSUE TITLE
能不能把宽屏和窄屏布局分开让用户自己选

### ISSUE THREAD

**Issue by aajiangzz** [poooi/poi#616]
就像横屏竖屏是分开的那样。现在的布局，字体和间距都过大看着不舒服，升级经验和建造界面还被隐藏了。

**Comment by KochiyaOcean** [comment]
没听懂……

**Comment by aajiangzz** [comment]
就是让宽屏幕和窄屏幕使用完全不同的布局，就像现在有横版和纵版选项，再加个宽屏选项，现在的布局完全不适合宽屏，显示内容太少字体和各种间距也过大。记的之前看过一个布局就很好，但dalao说那个用窄屏字体太小，dalao把那个布局改了以后还是显示不出升级经验和建造面板。既然窄屏和宽屏不适合一样的布局就分开吧

**Comment by KochiyaOcean** [comment]
我也挺想要一个大点的屏幕这样就有动力写了（逃

**Comment by aajiangzz** [comment]
https://github.com/poooi/poi/issues/494
找到了就是这个布局，还是希望把这个布局放出来。

**Comment by Ayaphis** [comment]
这个布局是效果图，从未实装过

**Comment by aajiangzz** [comment]
所以说希望能够实装，感觉这个布局很好，不希望再被压缩成窄屏版，dalao如果有空写就考虑一下吧

**Comment by PHELiOX** [comment]
宽屏不是可以用双栏么，为什么说被压缩

**Comment by aajiangzz** [comment]
被压缩是指我引述的那个帖子，lz的布局被压缩成5楼的窄屏版本

**Comment by PHELiOX** [comment]
两个布局的内容一致，区别在于外观，哪里被压缩了

**Comment by aajiangzz** [comment]
建造面板没了，升级剩余经验没了只有外观风格保留了

**Comment by dkwingsmt** [comment]
在现在的设计下，
![image](https://cloud.githubusercontent.com/assets/1596656/11765870/146c9670-a131-11e5-9d83-2e2ef819d827.png)
现有的建造面板在这里。两者切换。
升级剩余经验在详细舰队里面。
![image](https://cloud.githubusercontent.com/assets/1596656/11765877/424dcbea-a131-11e5-96df-d257930161e1.png)


如果想要做“建造和入渠同时直接显示”的界面或者“升级剩余经验在外面”的界面，那么最好的方案是点击
![image](https://cloud.githubusercontent.com/assets/1596656/11765880/5ca20196-a131-11e5-9194-0356e2603006.png)键然后自己修改代码。

这些是因为，无论如何改，基本的外观设定都将会是固定的。我们并不想同时维护两套完全不同的界面。而在这种前提下，我们必须以适应窄屏为准。

**Comment by PHELiOX** [comment]
合并面板确实是出于空间利用的考虑，界面布局也还在调整中。
单双栏下主面板使用不同布局也可以考虑。

**Comment by KagamiChan** [comment]
有一些布局的改变是可以通过 css 的调节完成的，例如放在主题里。不过现在 panel 有自己的单独的样式表，还是在主题之后载入的，优先度比主题还要高。总之是还有点乱吧。
另外的一些涉及到 DOM 的改动可以通过插件覆盖掉内置 module 或者直接进行 DOM 操作，不过可行性感觉不是特别好……

**Comment by dkwingsmt** [comment]
暂时关闭吧，如果确实有更好的建议再打开。
