### ISSUE TITLE
force touch support

### ISSUE THREAD

**Issue by mic4126** [poooi/poi#623]
chrome has a bug that if you open it in pc without touch support but later you use a tablet or phone to control .Then it will not response to touch event (except close , minimise windows)
In chrome ,  I can toggle chrome://flags/#touch-events to on to avoid the bug.

**Comment by mic4126** [comment]
I can read chinese but don't know how to type.

**Comment by magicae** [comment]
Just a setting item and a commandLine switch

/cc @KochiyaOcean

**Comment by KochiyaOcean** [comment]
Seems fixed.
