### ISSUE TITLE
界面分离的功能，直接把游戏主界面跟功能分开

### ISSUE THREAD

**Issue by dkwingsmt** [poooi/poi#626]
![image](https://cloud.githubusercontent.com/assets/1596656/11885738/f8f33a4c-a4e7-11e5-85eb-9f0c938f88ab.png)

这个需求已经有十几个人提过了，我觉得可以在什么时候考虑一下……

**Comment by Ayaphis** [comment]
https://github.com/poooi/poi/wiki/%E9%9A%90%E8%97%8F%E5%8A%9F%E8%83%BD#%E5%88%86%E7%A6%BBflash%E7%AA%97%E5%8F%A3%E5%92%8C%E6%B8%B8%E6%88%8F%E9%9D%A2%E6%9D%BF

**Comment by dkwingsmt** [comment]
仔细看图片里最后一句话。

**Comment by KochiyaOcean** [comment]
poi-control 无法和舰娘放在同一个窗口里哦，不然就是痛苦的进程间通信了

**Comment by dkwingsmt** [comment]
我是想的就是个一键“把本体flash尺寸变0并且打开一个内置一心二用”的按钮就可以了吧？

**Comment by Ayaphis** [comment]
啊，没看清楚，分离后poi-control放哪呢

**Comment by KochiyaOcean** [comment]
如果要作为本体功能的话还是独立比较好啊，毕竟一心二用不是必选依赖

**Comment by dkwingsmt** [comment]
我的意思是代码实现这么做啦……至于插件嘛……把那部分挪进主体呗【

或者挪进主体之后让一心二用引用主体那部分

【或者再做一个让主体引用插件的 dirty hack

**Comment by KochiyaOcean** [comment]
一心二用方面做下修改吧

**Comment by alvin-777** [comment]
* 主窗口隐藏游戏以外所有面板
* 再开一个主窗口，游戏区域设为0
* 合并的时候直接关闭第二个主窗口，恢复第一个主窗口隐藏的部分
好处是可以不打断游戏进行热切换，不过细节上应该有不少需要调整的地方

----
我简单地试了下应该是可行的：
![image](https://cloud.githubusercontent.com/assets/13615512/11905702/99c00dac-a613-11e5-943f-4479cc659c79.png)

**Comment by dkwingsmt** [comment]
竟然可以热切换！

**Comment by KochiyaOcean** [comment]
毕竟走的是同一个 ip 同一个代理
问题是快捷操作栏……不重新构建的话很容易陷入痛苦的进程间通信大坑

**Comment by alvin-777** [comment]
试了一下确实现在只是简单的“只有当前窗口吃快捷键”
不过我觉得只要先建立起一套好的通讯机制，剩下的并不会太难，顺便还可以解决一些一直存在的诸如“新窗口插件不会随主体切换theme”之类的问题
（现在的一个想法是全局的event（如何实现还是个问号

**Comment by KochiyaOcean** [comment]
发送事件需要 webview.send 方法，如果需要向插件窗口发送全局事件，需要每个插件窗口都在主体注册一个变量（比如航海日志那种
为了方便管理或许全部设置为 window.plugin.pluginWindow 比较好
（又要改插件了有点麻烦……

**Comment by KagamiChan** [comment]
有了有了
