### ISSUE TITLE
如何从源码编译

### ISSUE THREAD

**Issue by wbsdty331** [poooi/poi#627]

**Comment by taroxd** [comment]
运行：见 [README.md](https://github.com/poooi/poi/blob/master/README.md)
编译：先确保成功运行一次之后，在 poi 的目录下执行 `cjsx -c views lib app.coffee`
编译并打包：
在 Linux 环境下，在 poi 的目录下执行 `./node_modules/.bin/gulp build`。
Windows 环境下暂时没有脚本
Mac 环境请咨询 @Chibaheit

**Comment by KochiyaOcean** [comment]
Mac 也能使用 gulp 打包啊
虽然要做成单个 app 文件还是要手动操作一下

**Comment by Chibaheit** [comment]
gulp会有解压方面的好些问题。。

**Comment by dkwingsmt** [comment]
稍微针对taroxd的回复再给楼主解释一下：
- 如何__使用__ git 版 poi：简单来说，就是完整执行 Readme 中的几步就可以了。
 - 下载 electron （``npm i electron-prebuilt``）
 - clone poi，然后执行``npm i`` 
 - 执行 Readme 中所说的的 gulp install
 - ``electron .`` 就可以直接执行了，也即实际上只要依赖齐全了是不需要“编译”的
- taroxd 告诉你的编译过程是将 poi 开发所使用的 coffeescript 编译为 javascript 使得加载速度更快。并不是运行必须。
- ``gulp build`` 是用来我们发布release版的。
 - 运行环境支持 Linux 和 Mac，支持 Win 吗？我没测试过（``gulp install``支持 win）
 - 打包结果支持 Linux 和 Win ，Mac 因为上述原因所以暂时没有融合进去，所以是 Chiba 手动打包。

也@taroxd

**Comment by alvin-777** [comment]
纠正DK一点：`npm install electron-prebuilt -g`

所以说po主到底是想要干啥？问题能不能具体一点？

**Comment by dkwingsmt** [comment]
已修改。我猜应该就是想玩 git 版吧……然后以为咱这跟 C 程序一样是要编译的……

**Comment by Wafer-Li** [comment]
:flushed:  不是有一个 `gulp build` 的东西吗？ 我记得这个是什么都会给你下好的。

**Comment by taroxd** [comment]
首先你得有 gulp 里面需要的所有依赖……

win 里面可以用 gulp install（还是我给改好的）。至于 gulp build 涉及的破事太多，我懒得改了，反正 win 是不能用的- -

**Comment by dkwingsmt** [comment]
``gulp install`` 里面所需要的依赖都可以用 ``npm i``解决

**Comment by taroxd** [comment]
嗯，这就是你上面那楼所说的那个方法嘛

**Comment by dkwingsmt** [comment]
也是 Readme 种所说的那个方法……完全按照 Readme 操作是不会有问题的【

**Comment by Wafer-Li** [comment]
:joy:  其实我只在久远的 3.0 时代用过这个东西，当时好像还是可以用的。

**Comment by dkwingsmt** [comment]
当年还只用 ``gulp`` 而不是 ``gulp install`` ……我后来重写了一遍
