### ISSUE TITLE
窗口最大化与窗口大小记录的问题

### ISSUE THREAD

**Issue by KagamiChan** [poooi/poi#639]
最大化窗口后关闭程序，再次运行时窗口变为非最大化状态，并且窗口大小和最大化的一样

按照一般的使用习惯，记录窗口大小记录的是非最大化状态下的窗口大小。我觉得在更新窗口大小信息之前，判断窗口是否最大化，这样会更合理一些

（我目前手上只有 windows，所以不知道别的平台上是怎么样的表现）

**Comment by alvin-777** [comment]
Mac上也有同样的问题
全屏时也是同样效果（Win上最大化比较多，Mac全屏比较多）
我也同意你的意见，不过最大化／全屏时get出来的值就是最大的值，晚上我看看能怎么处理吧
