### ISSUE TITLE
检测系统语言以决定默认情况下使用什么 npm 源

### ISSUE THREAD

**Issue by dkwingsmt** [poooi/poi#643]
墙外访问墙内的源基本上不行，反之亦然……所以，如果没有 npm 源的设置，检测系统语言，如果是中文就用cnpm，如果不是，就使用 US 源。

**Comment by c933103** [comment]
但話說在中國大陸以外用簡中OS玩艦的人不少…雖然不一定都會用POI……
2015/12/22 8:05 "Tong Mu" <notifications@github.com>:

**Comment by dkwingsmt** [comment]
是啊，只能说这是适配最广的方案……除非你能用脚本向两边各 ping 一次……

**Comment by KochiyaOcean** [comment]
Fix by a88473d9909ec6dcebd3a069130ecbc803aebd0f

**Comment by Ayaphis** [comment]
个人觉得很没必要，另外这个会覆盖用户选择么？

**Comment by dkwingsmt** [comment]
在 config 有设置的情况下就不会变，没有的情况下就使用这个。
