### ISSUE TITLE
i18n-2 修改了 .json 文件

### ISSUE THREAD

**Issue by dkwingsmt** [poooi/poi#646]
话说欧选的 i18n-2 通用头是从 i18n 抄过来的吗？
```coffeescript
window.i18n.battleInfo = new(require 'i18n-2')
  locales: ['en-US', 'ja-JP', 'zh-CN', 'zh-TW'],
  defaultLocale: 'zh-CN',
  directory: path.join(__dirname, 'assets', 'i18n'),
  updateFiles: false,
  indent: '\t',
  extension: '.json'
```
其中 ``updateFiles: false`` 这一个选项在[i18n-2的文档](https://github.com/jeresig/i18n-node-2)里面并没有搜到……
今天在写 quest 的时候发现 i18n 文件被修改了，indent 全部被换成了``'\t'``
- 将那个选项去掉并且加上``devMode: false``的话可以阻止其改文件（而且我真的并不觉得我们需要它帮我们改文件……）
- 为什么 indent 会是``'\t'``啦咱不是一直用的两个空格吗！
- 另外我似乎看到很多“通用头”里面的 locales 没有添加 'zh-TW'

**Comment by KochiyaOcean** [comment]
其实大部分修改都只是把 `i18n.configure` 改成了 `window.i18n[namespace] = new(require 'i18n-2')` 而已

**Comment by dkwingsmt** [comment]
噫！大规模替换之前你先瞧一眼啊！

**Comment by KochiyaOcean** [comment]
懒得看详细的噜……

**Comment by Ayaphis** [comment]
噫，DK给个范例，我去清理下自己插件的代码

**Comment by dkwingsmt** [comment]
如果是我的话就用这个了……（我把 indent 直接删了
```coffeescript
window.i18n.battleInfo = new(require 'i18n-2')
  locales: ['en-US', 'ja-JP', 'zh-CN', 'zh-TW'],
  defaultLocale: 'zh-CN',
  directory: path.join(__dirname, 'assets', 'i18n'),
  devMode: false,
  extension: '.json'
```

**Comment by KochiyaOcean** [comment]
devMode: false 就可以了
妈呀这还是默认开启选项…

**Comment by dkwingsmt** [comment]
说在开发模式下就是 true，在发布版就是 false 什么的……反正……

**Comment by dkwingsmt** [comment]
都已经改动了~
