### ISSUE TITLE
关于软件调试的完善以及规范

### ISSUE THREAD

**Issue by alvin-777** [poooi/poi#652]
## 目前的状况
* 通过设置环境变量`DEBUG=1`来控制调试代码是否运行
* 设置该环境变量的方法有：
  * poi启动后，打开dev tool，在console输入`process.env.DEBUG=1` —— 最广为人知的方法
  * 在代码中(如index.cjsx里)加上`process.env.DEBUG=1` —— 需要hack本地代码
  * 启动poi前 export shell 变量`DEBUG=1` —— 只有部分人知道此方法
* 调试代码需要用到chrome自带的dev tool，打开dev tool的方法有：
  * 点击poi控制栏里的“开发者工具”按钮，可以打开本体的dev tool
  * 新窗口插件需要打开自己的dev tool，在poi主体的dev tool console输入: `remote.getGlobal('windows')[N].openDevTools({detach: true})`  (其中的N对应该插件在插件列表中的位置)
  * 有的插件在开启新窗口时设置了 `window.pluginWindow = pluginWindow` ，此时也可以通过 `window.pluginWindow.openDevTools({detach: true})` 的方式打开
  * Mac用户可以通过程序menu或者快捷键`Option+Command+I`来打开当前窗口的dev tool
  * 当使用了前面提到的hack本地代码或者export shell 变量的方法来设置`DEBUG=1`时，poi会在启动时自动打开本体及所有新窗口插件的dev tool（由于electron(or maybe chrome)的设计问题，打开/关闭dev tool时其对应的窗口就算是隐藏的也会强行显示）
* 调试模式一旦开启便无法关闭

## 最近新加入的功能
* 处理启动poi的命令行参数。于是通过传递参数的方式来使poi一启动便开启调试模式也成为可能。不过跟上面说的两种方法一样(hack / export)，这种方法也会让poi在启动主体的同时便打开所有可能打开的窗口。

## 计划添加/修改的功能
* 为Windows/Linux增加“打开当前窗口dev tool”快捷键 `Ctrl+Shift+I` (同[Chrome](https://developer.chrome.com/devtools))
* 使用命令行参数取代hack本地代码和export shell变量的方式来开启debug模式
  (参数名为暂定。具体内容我会在后面详细解释) 
```
Usage: electron poi [options]

Options:
-d, --debug            从一开始便开启调试模式
--debug-extra=....     开启特定调试代码
```
* 当设置了`--debug`时只有poi主体自动打开dev tool，各新窗口插件的dev tool可根据自己需求用快捷键打开。极限情况下需要插件的dev tool也在启动时自动打开的话，可同过传递`--debug-extra`参数来实现（插件中需要有对应的代码）
* 当设置了`--debug`时主程序会在运行 index.cjsx 中的任何代码之前先alert一次。这样做的目的是让dev tool有充足的时间load所有代码文件，于是你可以在任意地方设置breakpoint，以达到特定调试目的。
* 增加一个window.debug模块（在env.coffee中被初始化，并预处理传进来的调试信息）。以后我们将不再对 `process.env.DEBUG`作任何操作，而是通过 `window.debug.isEnabled()` 和 `window.debug.isEnabledExtra('....')` 来判断（分别对应命令行参数的`--debug`和`--debug-extra`）。在dev tool的console中输入`process.env.DEBUG=1`打开调试模式的方法也替换为在console输入`window.debug.enable()`（当然这样做的话`window.debug.disable()`自然也成为可能，当你不再需要某些调试信息的时候可以直接disable掉，而不用重启poi）
* 所有现有代码即使不作修改应该依旧正常工作，不过无法保证以后永远都不变，并且一些新功能可能对它们无效。

## 关于`debug`和`debug-extra`
以前所有的调试代码都是由`process.env.DEBUG`这一个开关控制，以后将会做一些细分：
* 普通调试内容，即在调试模式下需要总是运行的内容（最常见的就是在console显示收到的包），由debug控制
* 一些有针对性的／需要消耗大量资源的／不想影响整体或其他部分的内容，便应放到 debug-extra 里。例如：
  * 显示切换tab render消耗的时间，这信息在需要的时候很有用，但平时大部分人根本不关心，所以完全可以把判断改为 `if debug.isEnabledExtra('show-ship-module-render-cost')`
  * 也许出于某些原因你需要你的调试代码做一些非常复杂的运算，或者反复render一些东西，所以你并不希望所有人都一开debug就运行这些代码。以前只能在需要的时候添加进去，用完了必须立刻comment掉或者删掉。不过把它们放到 debug-extra 里的话就可以方便的控制，随时都可以调用了。例如 `if debug.isEnabledExtra('my-plugin-do-this-heavy-work')`
  * 你可能需要某新窗口插件一启动就自动打开dev tool，与其让其它不关心的窗口也一同全部把dev tool打开，不如放在debug-extra里更易控制
```
if debug.isEnabledExtra('plugin-name-open-dev-tool-on-start')
  pluginWindow.openDevTools
    detach: true
```
* --debug-extra可一次传入多个值，值与值之间用逗号隔开，或者重复`--debug-extra`参数：
```
electron poi --debug-extra=do-this,do-that --debug-extra=also-do-this
```
* 判断时也可复合使用：
```
if debug.isEnabledExtra('my-plugin-show-everything') or debug.isEnabledExtra('my-plugin-do-blahhhh')
```
* 简单的说，其实就是给不常用的／不是所有人都需要的debug内容加一个tag。tag具体叫什么各位可根据需求自己决定。我个人的建议是：
  * 不要过于简单，以便区分
  * 根据用途决定tag名，tag名能反映用途

### TODOs
- [x] Add shortcut to open dev tool for Win/Linux
- [x] window.debug
- [x] Update existing code

----
欢迎补充。

**Comment by yukixz** [comment]
插件用 `debug-extra` 应该用插件名做前缀，避免冲突。
比如：`ship-info-show-render-cost`，`battle-detail-log-simulation`。

**Comment by taroxd** [comment]
插件各管各的就好了，我觉得不一定要前缀插件名。 冲突了也不会影响到正常玩家，以开发者舒服为准吧。

~~设置环境变量不是之前最普通的方式么  怎么变成一部分人知道了~~

**Comment by Ayaphis** [comment]
怎样设计我没意见，只要留下类似DEBUG = 1 这样简单设置就能啪啪啪让所有插件的dev tool打开的方式就行了。

**Comment by JenningsWu** [comment]
在 tag 划分之外，建议规定一些调试级别，从低到高，例如
0-> 通用调试信息，错误提示类
1-> 通用调试信息，状态显示类
2-> 通用调试信息，开发环境额外调试代码
3-> dev-tool 开启
……

大概类似这种东西。每个自定义的调试 tag 都遵循规范对应于某一个调试级别。
具体级别划分~~以及是数字低级别高还是数字高级别高~~待讨论。

**Comment by yukixz** [comment]
@JenningsWu 这个用 `console.log` `console.warn` `console.error` 不就是嘛=。=

**Comment by JenningsWu** [comment]
用来留下啪啪啪全打开的接口嘛。

**Comment by yukixz** [comment]
插件对 `--debug` 的行为保持跟 `process.env.DEBUG` 一直咯...
不过这种事情需要插件作者做的呀，
从可执行性上来讲、人家不做你一点办法都没有=。=

**Comment by alvin-777** [comment]
一定要啪啪啪的，等改完了我给你们写一个shell script，一劳永逸。

不过我建议你们先体验一下快捷键的快感，兴许尝试过快捷键之后就再也不想啪啪啪了

**Comment by PHELiOX** [comment]
还没做？

**Comment by taroxd** [comment]
快捷键已经做了，还是很棒的，果断支持。

命令行参数看戏中

**Comment by alvin-777** [comment]
快捷键已经做好了。

其他部分如果下周一之前没有反对意见的话，就照我最上面说的做了，如何？

**Comment by alvin-777** [comment]
我自己补充两点吧：
- 以后可以适当增加一些debug logging，诸如“Initialising blah blah blah”。尤其是main process那边（因为没办法用dev tools来debug），在出了问题的时候会很有用。参考 #680 
- 我赞成 @yukixz 说的，插件用插件名作为debug-extra tag的前缀（新窗口部分大概就随便了，反正是不同的dev tool窗口？）。当然这个最终还是取决于插件作者自己了。。

**Comment by cleverdango** [comment]
哇这个地方用来干嘛的

**Comment by yukixz** [comment]
@alvin-777 新窗口插件和本体共用 CLI options 的吧=。=

**Comment by alvin-777** [comment]
@yukixz 共用的
(设想) 程序启动之后会立刻parse CLI options，然后根据options创建window.debug。所有窗口的window.debug初始值都一样，不过程序启动之后各窗口对自己的window.dubug所做的修改不会同步到所有窗口

**Comment by yukixz** [comment]
=。= 窗口为啥要修改 window.debug ...

**Comment by alvin-777** [comment]
比如新窗口插件可以自己随意在window.debug里加一些function啊variable什么的
另外前面提到的窗口可以call window.debug.enable() / disable() 而不会影响到其他窗口

**Comment by yukixz** [comment]
哦哦、运行时开启 debug。

**Comment by alvin-777** [comment]
先更新在这里，稳定及确认无bug了之后再更新doc。

----

### CLI 支持

* `--debug[=true|false]` 开启/关闭 debug模式。`--debug` 同 `--debug=true`
* `-d` 同 `--debug`
* `--debug-extra=option1,option2,option3 --debug-extra=anotherOption` 开启extra debug option `option1`,`option2`,`option3`&`anotherOption`。Extra options 的命名规则与variable命名规则相同，option 之间用逗号隔开。
* `--debug-extra-d=options` 关闭相应的extra debug option。用法同 `--debug-extra`
* `--version | -v` 输出版本信息到console，然后退出。

以上所有arguments都可重复使用(`--version | -v` 除外，版本信息显示之后会立刻退出)，处理顺序为从左至右，重复的extra debug option会自动被处理掉。

### 访问

Main process 在 `global.dbg`，renderer process 在`window.dbg`。
都可以通过`dbg`直接访问。

### API

* `dbg.enable()`  
开启debug
* `dbg.disable()`  
禁用debug
* `dbg.isEnabled()`  
返回debug是否开启
* `dbg.log(msg)`  
仅在debug开启时有效的log
* `dbg.assert(cond, msg)`  
仅在debug开启时有效的assert

举个栗子：
![image](https://cloud.githubusercontent.com/assets/13615512/12860073/02004a2c-cca6-11e5-8609-720cf7c40b34.png)

* `dbg.enableExtra(optionName)`
* `dbg.disableExtra(optionName)`
* `dbg.isExtraEnabled(optionName)`  
看名字应该能猜到是干嘛的
* `dbg.extra(optionName)`  
返回`dbg.ex`中相应的handler，如果还没有的话，创建一个新的并返回这个新handler。
* `dbg.extra(optionName).enable()`
* `dbg.extra(optionName).disable()`
* `dbg.extra(optionName).isEnabled()`
* `dbg.extra(optionName).log(msg)`
* `dbg.extra(optionName).assert(cond, msg)`  
与前面的`dbg.xxxxx()`类似，只是基于相应的option的状态。  
.
* `dbg.list()`  
一个神秘的魔法

##### 关于extra debug option handler
`dbg.extra()` 会在 `dbg.ex` 中(如果还不存在的话)创建一个同名的handler (`dbg.enableExtra()` 因为会call `dbg.extra()` 所以也能创建）。一旦handle被创建之后，`dbg.ex.name` 便等效于 `dbg.extra('name')`。
例如：
![image](https://cloud.githubusercontent.com/assets/13615512/12861206/7c6ce7c8-ccad-11e5-8e05-4c3139cc4c03.png)
Handler的目的是为了可以充分利用dev tools的自动完成功能来简化我们需要手动完成的操作。例如：
![image](https://cloud.githubusercontent.com/assets/13615512/12861507/a31588e2-ccaf-11e5-961d-2f4b5132bf26.png)

为避免混淆，简单概括如下：  
* 在code中一般用到的是 `dbg.extra('xxxx').isEnabled()`, `dbg.extra('xxxx').log(msg)`, `dbg.extra('xxxx').assert(cond, msg)`
* 在dev tools console一般用到的是 `dbg.ex.xxxx.enable()`, `dbg.ex.xxxx.disable()`

----
大概还有。。起床后补充。。。

**Comment by KochiyaOcean** [comment]
都 merge 了这个 issue 还开着，快去更新文档啦

**Comment by KagamiChan** [comment]
我觉得需要给 dbg 加一个启用全部 debug 的功能，比如 dbg.enableAllExtra() 什么的，看文档只有一个一个地开启？

**Comment by KagamiChan** [comment]
另外在 windows 下使用 github 版，在快捷方式中添加 --debug 还是没有启用 debug，是不是需要特殊的打开方式？
![image](https://cloud.githubusercontent.com/assets/3816900/13197536/6a11ed06-d82b-11e5-885c-16553a195807.png)

**Comment by alvin-777** [comment]
全开的话，处理稍微有点麻烦，而且我想不到什么要extra全开的需求

----
快捷方式。。。。你倒是把 `--debug` 放路径后面啊。。。。

**Comment by KagamiChan** [comment]
嗯，--debug 放后面可以了，虽然我有印象是以前放在前面也行的

全开的需求是因为不想写那么长的参数……多开几个看起来也没什么坏处……
