### ISSUE TITLE
[Bug?] 界面无法显示

### ISSUE THREAD

**Issue by Wafer-Li** [poooi/poi#653]
Electron v0.35.4 x64
Win 10 x64 Pro
Commit SHA: 6135da0ce2e1af851599d1ed7e765ff8085e33be

![qq 20151223233350](https://cloud.githubusercontent.com/assets/12459199/11978309/ddbfba80-a9cd-11e5-9dff-10f74645520d.png)
大概就是 这样子了。

具体经历的操作有
```
// 正常的更新流程
git pull
npm i

// 发现问题之后
gulp install    // 然而并没有什么卵用
```

尝试着更新到 Electron v0.36.1, 然而除了弹一堆命令行的弹窗之外并没有什么卵用

**Comment by Ayaphis** [comment]
尝试
手动安装依赖 
```
npm i mousestrp 
```

npm i 过程好像会把这个拆了

**Comment by Wafer-Li** [comment]
![qq 20151223234711](https://cloud.githubusercontent.com/assets/12459199/11978522/88f844de-a9cf-11e5-8a6e-b8a7129cce63.png)

404, 正在添加代理后重试。

**Comment by Ayaphis** [comment]
之前我typo了（逃

**Comment by Wafer-Li** [comment]
:joy:  去 npm 搜了一下， 搞定了。

……这年头这东西越来越不靠谱了？
