### ISSUE TITLE
在舰队界面，hover 到装备时把装备的属性显示出来

### ISSUE THREAD

**Issue by dkwingsmt** [poooi/poi#654]
![image](https://cloud.githubusercontent.com/assets/1596656/11992497/4a994e46-a9ec-11e5-9892-115d7fb547f4.png)

**Comment by KochiyaOcean** [comment]
数据收集就交给你了 DK！

**Comment by KagamiChan** [comment]
于是我们还可以有
hover 到舰名上时把属性都显示出来
hover 到油弹条的时候把具体数字显示出来
有时候的确挺方便的
