### ISSUE TITLE
build 脚本还需要改进的一些问题

### ISSUE THREAD

**Issue by KochiyaOcean** [poooi/poi#656]
今晚决定用新的 gulp 脚本 build，于是我到现在都还没做完……
几个建议：
建议添加不下载 Electron 和 Flash 的选项，这两个东西不是每次发新版本都会下载的，换言之，一个只 build app 文件夹的选项（顺便直接通过 Chrome 下载速度也比脚本下载来得快……
建议添加超时失败的设置，学姐还没把 flash for win32 的压缩包挂到 CDN 上，于是脚本居然就在那里用 404 Not Found 的错误信息把整个 ttl 都占满了……

**Comment by Wafer-Li** [comment]
所以现在 git 版还不能更新吗？

**Comment by KochiyaOcean** [comment]
可以更新，就是对于打包来说现在这个脚本还是有点坑

**Comment by dkwingsmt** [comment]
抱歉⋯⋯关于下载的话，手动把各文件放到下载文件夹吧，有文件了就不会下载了。

**Comment by KochiyaOcean** [comment]
=。=算了先这样吧……

**Comment by dkwingsmt** [comment]
另外可以考虑在gulpfile里去掉win32⋯⋯这个是hardcode的没写选项（

**Comment by dkwingsmt** [comment]
https://github.com/poooi/poi/pull/683/files
- 添加了只打包 app 的选项 ``gulp build_app`` 
- 平台还是 hardcode
- 超时失败还是没做，反正现在Flash 又齐全了
- 各个包可以直接通过 Chrome 下载到 build/download 文件夹下
