### ISSUE TITLE
Mac下面怎么用魔改包？

### ISSUE THREAD

**Issue by were** [poooi/poi#657]
我打开了MyCache文件夹复制进去，这肯定不对，对吧？

因为连`*.swf`的影子都没看见啊

**Comment by KochiyaOcean** [comment]
是在 MyCache 下，不过要增加一些路径
![image](https://cloud.githubusercontent.com/assets/8194131/11996846/e8762d72-aaa6-11e5-845f-dc77ff78d00f.png)
简单的说右击这个按钮之后直接丢进去就行了

**Comment by Ayaphis** [comment]
因为是第三方缓存，而不是浏览器缓存

**Comment by were** [comment]
也就是把缓存清掉，然后放进这个文件夹，Chrome-based浏览器也是能认这个缓存的对吧？
