### ISSUE TITLE
Win 8.1 下，使用 Notification API 无法弹出通知

### ISSUE THREAD

**Issue by taroxd** [poooi/poi#659]
QQ 群里出现的问题。我这里没有测试环境。

**Comment by JenningsWu** [comment]
打完演习~~以及洗完碗~~之后我测一下吧，刚试了下我这边也没弹窗，win 8.1

**Comment by taroxd** [comment]
嗯。经过测试，使用 node-notifier 没有问题

**Comment by yukixz** [comment]
`require('os').release()` ?

**Comment by JenningsWu** [comment]
`notification = new Notification("Hi there!");` 不会弹出通知。`Notification.permission`是`granted`。windows 有什么管理通知的地方么？

**Comment by JenningsWu** [comment]
大概清楚是怎么回事了。
electron 的 [Desktop Environment Integration](https://github.com/atom/electron/blob/master/docs/tutorial/desktop-environment-integration.md) 里关于 notification 提到
> * On Windows 8.1 and Windows 8, a shortcut to your app, with a [Application User
Model ID](https://msdn.microsoft.com/en-us/library/windows/desktop/dd378459%28v=vs.85%29.aspx), must be installed to the Start screen. Note,
however, that it does not need to be pinned to the Start screen.

MSDN 上关于 [How to enable desktop toast notifications through an AppUserModelID](https://msdn.microsoft.com/en-us/library/windows/desktop/hh802762%28v=vs.85%29.aspx) 也提到
> This topic shows you how to create a shortcut for your app, assign it an AppUserModelID, and install it in the Start screen. We strongly recommend that you do this in the Windows Installer rather than in your app's code. Without a valid shortcut installed in the Start screen or in All Programs, you cannot raise a toast notification from a desktop app.

所以目前 poi 在 win 8.1 上是无法弹出 HTML5 Notification 的。

解决方法有两种
1. 用 [grunt-electron-installer](https://github.com/atom/grunt-electron-installer) 来生成一个 Windows installer。
2. win 8.1 也用 node-notifier 来通知。

**Comment by KochiyaOcean** [comment]
后者比较简单，还是使用后者吧……
