### ISSUE TITLE
[Feature Request] 所以插件能不能用新图标呢？

### ISSUE THREAD

**Issue by Wafer-Li** [poooi/poi#661]
:+1:  我只能说你们搞的这个新的 SVG 啊，excited!

但是插件好像还是没能用上这个 SVG，还是希望能获取一个统一的体验。
所以有没有这个计划呢？

:joy: 个人比较懒，就不到处去提 issue 了

-----------------------------------

其实可以直接让本体的
` - [ ] 使用高清图标`

直接 override 所有的包括插件的图标设定。嗯。

**Comment by KochiyaOcean** [comment]
@ruiii @Ayaphis @taroxd @yukixz 你们自行改动吧=。=

**Comment by yukixz** [comment]
@KochiyaOcean 把 ./views/components/etc/icon.cjsx` 抽象出来嘛=。=

**Comment by KochiyaOcean** [comment]
你们直接用绝对路径调用就行了噜……

**Comment by yukixz** [comment]
你敢不敢保证这个路径永远不会变...

**Comment by Ayaphis** [comment]
。。。拒绝直接路径调用
多一套图标你准备让我们多一次适配么？

**Comment by KochiyaOcean** [comment]
如果你们担心路径变更的话直接把这个文件复制到自己的插件下就行了嘛
反正现在调用图标也是用绝对路径不知道飞帅在说什么

**Comment by edwardaaaa** [comment]
注意用最新上传的图标，不要把公测版的图标整合进去。。。。

**Comment by KochiyaOcean** [comment]
本体已经使用最新的了，所有插件都会依赖它

**Comment by dkwingsmt** [comment]
- [x] poi-plugin-akashic-records
      - [x] poi-plugin-battle-detail
      - [x] poi-plugin-exp-calc
      - [x] poi-plugin-expedition
      - [x] poi-plugin-hensei-nikki
      - [x] poi-plugin-item-improvement
      - [x] poi-plugin-item-info
      - [x] poi-plugin-map-hp
      - [x] poi-plugin-new-window
      - [x] poi-plugin-prophet
      - [x] poi-plugin-quest-info
      - [x] poi-plugin-report
      - [x] poi-plugin-ship-info
      - [x] poi-plugin-senka-calc
      - [x] poi-plugin-almanac
      - [x] poi-plugin-wheres-my-fuel-gone

**Comment by yukixz** [comment]
done
