### ISSUE TITLE
部分插件的 i18n zh-TW 存在问题

### ISSUE THREAD

**Issue by yukixz** [poooi/poi#665]
目测是 locales 没有写 zh-TW。

* [ ] prophet
* [ ] exp calc
* [x] expedition
* [x] item improvement

**Comment by ruiii** [comment]
有几个插件zh-TW为空的
不太熟悉TW用语 请求帮助。。

**Comment by dkwingsmt** [comment]
直接用 opencc.byvoid.com 转换一下就好，虽然主要是转换简繁字，用语差别处理得不多，但是八九不离十。

**Comment by dkwingsmt** [comment]
剩下这俩插件已经更新了嘛？~

**Comment by Ayaphis** [comment]
剩下两个都是吃吧的啊cc @Chibaheit

**Comment by taroxd** [comment]
plugin.json 的远征插件也需要更新

**Comment by dkwingsmt** [comment]
你们查的时候顺便也查下这个 issue 
https://github.com/poooi/poi/issues/646

**Comment by NatLee** [comment]
路過 :+1: 
有哪些需要寫 zh-TW

**Comment by dkwingsmt** [comment]
都已经加上了~

**Comment by yukixz** [comment]
没有啊、prophet 的 locales 里面还是没有 `zh-TW`。
![screen shot 2016-01-06 at 3 05 27 pm](https://cloud.githubusercontent.com/assets/3337921/12136880/f0d57cc2-b486-11e5-9774-dc1dcdf28827.png)

**Comment by dkwingsmt** [comment]
我更新到 github 里面，又没有 publish

**Comment by dkwingsmt** [comment]
https://github.com/poooi/plugin-prophet/blob/master/index.cjsx#L12

**Comment by yukixz** [comment]
![screen shot 2016-01-06 at 3 11 20 pm](https://cloud.githubusercontent.com/assets/3337921/12136980/c2a4f25a-b487-11e5-970d-7dd8890530bf.png)
