### ISSUE TITLE
ship-info 网盘版的 离线包无法安装

### ISSUE THREAD

**Issue by Ayaphis** [poooi/poi#667]
win8.1 x64

**Comment by Ayaphis** [comment]
![image](https://cloud.githubusercontent.com/assets/11754367/12007784/99131256-ac57-11e5-9946-c5b78775126c.png)

使用网盘的安装包必然出现此错误

**Comment by Ayaphis** [comment]
![image](https://cloud.githubusercontent.com/assets/11754367/12007789/f2cd906e-ac57-11e5-87c0-5584d6feac2c.png)

手工解压则会报告一下错误，不知是否关联

**Comment by Ayaphis** [comment]
使用github release版能安装成功

**Comment by KochiyaOcean** [comment]
内置的版本是 1.6.0，tarball 里的 i18n 的依赖带有 symlink 所以在 Windows 下安装失败

**Comment by Ayaphis** [comment]
github release最新版也是1.6.0啊

**Comment by dkwingsmt** [comment]
Solved in https://github.com/poooi/poi/commit/70bef8c3cb3b97a0cd5451fb53746d3b8aeac64b
添加了``--no-bin-links``选项，不会再产生 symlink。
