### ISSUE TITLE
linux版本下必须获取权限才能安装插件,安装后又必须在root下启动才能看到插件

### ISSUE THREAD

**Issue by williamking** [poooi/poi#672]

**Comment by KochiyaOcean** [comment]
Linux 的话文件在 ~/.config/poi 下，你是否具有该目录的写权限？

**Comment by williamking** [comment]
应该怎么设置权限呢,我设置成create-and-delete files也没有用,非root状态仍然卡在安装中

**Comment by KochiyaOcean** [comment]
```shell
chmod +w ~/.config
chmod +w ~/.config/poi
```

**Comment by williamking** [comment]
仍然卡在安装中。。。终端显示一堆undefined和一堆npm ERR! registry parsing json

**Comment by KochiyaOcean** [comment]
把 log 贴出来吧……

**Comment by williamking** [comment]
不知怎么回事，github无法上传图片。。。。我放到在线图片上了。。
http://xiangce.baidu.com/picture/detail/45c5aa7afa259c630ae4b75a31e15700b4daa966?from=dialog

**Comment by ibicdlcod** [comment]
我无法重现这个问题

**Comment by KagamiChan** [comment]
无法重现 +1
debian 8
electron 0.36
master 分支
建议先运行
```shell
ls -ld ~/.config
ls -ld ~/.config/poi
node -v
nodejs -v
npm -v
```
并将输出贴一下，如有必要，用户名和组名可以自行屏蔽
然后，尝试换一下 npm 的服务器

**Comment by williamking** [comment]
最后还是在终端手动npm install 解决了,多谢了......

**Comment by williamking** [comment]
运行ls -ld ~/.config 和 ls -ld ~/.config/poi的输出是
drwxrwxr-x 35 name name 4096 12月 27 22:47 /home/name/.config/
drwxrwxr-x 15 name name 4096 12月 28 14:44 /home/name/.config/poi
