### ISSUE TITLE
缩放的配置文件储存在哪儿？

### ISSUE THREAD

**Issue by HsoYo** [poooi/poi#674]
不小心改成了缩放200%，直接超过了屏幕分辨率（古董1024x768小屏幕），然后一打开就只显示游戏界面的一部分，数据部分完全不显示了，也就没法设置回去了。
于是乎删掉重新下了一个，还是缩放200%显示不出设置......

**Comment by KochiyaOcean** [comment]
5.0.0 后在 `%appdata%/poi/config.cson`
直接在资源管理器中输入这个地址就可以了

**Comment by HsoYo** [comment]
谢谢解答！
