### ISSUE TITLE
插件管理的一个小 bug

### ISSUE THREAD

**Issue by wafer-li** [poooi/poi#675]
Update at 2016/1/4 ：
另一个 BUG，请看 [这条评论](https://github.com/poooi/poi/issues/675#issuecomment-168630101)

---

当有插件可以更新时，不点击 `全部更新` 按钮而在插件列表中**单独点击更新**

之后 `全部更新` 按钮并没有 disable，而且点击此按钮之后则会一直转圈，然后并没有什么事情发生，因为所有插件都已经被更新到最新版本了（之前的单独点击更新）。

**Comment by dkwingsmt** [comment]
哈哈哈哈哈哈哈哈欧选前几天刚去掉了“更新后检查一遍版本号”

**Comment by KochiyaOcean** [comment]
本来就是为了解决这个问题的留着你们又不高兴那是没什么办法噜

**Comment by dkwingsmt** [comment]
更新到最新版本的话就把内存中的数组也直接按照最新版本更新一遍，然后全部更新按钮直接比较内存中的数组就好了嘛。不要再联线update了。

**Comment by JenningsWu** [comment]
这个 issue 说的不是检查版本号的问题吧，是说更新之后“全部更新”的按钮不会 disable

**Comment by KochiyaOcean** [comment]
所以就拜托你了

**Comment by Wafer-Li** [comment]
@KochiyaOcean  
前几天乱搞了几下，好像又发现了一个 BUG。
感觉还是不新开 issue 了，直接在这里回复吧。

点击 `全部安装` 之后，此时这个按钮被 disable；
在插件列表里面删掉几个插件，但是就算重启程序，`全部安装` 也没有重新 enable。

主楼同步更新。
