### ISSUE TITLE
win 上的内存泄露主要原因大致确定

### ISSUE THREAD

**Issue by JenningsWu** [poooi/poi#676]
目前看来是 electron 的锅， electron 的 remote object 在 windows 平台上存在循环引用，以致内存泄露。
举例来说，`env.coffee` 中的这段代码
```
window.proxy = remote.require './lib/proxy'
proxy.addListener 'game.on.response', (method, path, body, postBody) ->
  # Invalid response
  return if body.api_result isnt 1
  body = body.api_data if body.api_data?
  responses.push [method, path, body, postBody]
  resolveResponses() if !locked
```
里，参数 `method`, `path`, `body`, `postBody` 都是 remote object，对其属性的引用实质都是通过函数发出跨进程信息。electron 为每个 remote object 创建了 get 和 set 函数闭包，似乎这些闭包都含有对于其本身的引用，以致出现循环调用进而导致内存泄露，具体表现为所有的 remote object 在创建后都无法被回收。

**Comment by JenningsWu** [comment]
去 electron 提了个 issue

**Comment by ibicdlcod** [comment]
https://github.com/atom/electron/pull/3942
