### ISSUE TITLE
是否移除 game.on.request

### ISSUE THREAD

**Issue by JenningsWu** [poooi/poi#679]
之前通过 `game.on.request` 事件在 control 上显示 `正在请求 xxxx` 的信息，最近的版本里保留了对该事件的响应，但不做任何操作并移除了相关的显示。
于是是否要彻底移除该事件？

**Comment by JenningsWu** [comment]
一个引申的问题就是是否增加接口，支持 “侠客伴侣” 这类插件？

**Comment by yukixz** [comment]
讨论过不加侠客伴侣了。

**Comment by dkwingsmt** [comment]
``game.request`` 事件被近代化改修模块监听。因为需要储存“改修前”的舰船数值，所以必须是发包时刻。

**Comment by JenningsWu** [comment]
喷了，这样看来不能删...
除了 `game.request` 之外还有其他实现方法么？
昨天搜的时候看到那段代码还以为和 alert 一样是残留代码，结果是修改了变量啊…我的锅 orz

**Comment by dkwingsmt** [comment]
alert 什么时候是残留代码啊！

也不是“修改了变量”，只是“保存了变量”。因为收包的一刻 _ships 就会变化了嘛，所以必须在发包的时候就保存。

我感觉是没有别的实现方法，现在的步骤是这样的
- 在发包时
 - 获取目标舰编号，然后从``_ships``得到目标舰的五项属性
 - 获取狗粮舰编号，然后从``_ships``得到狗粮舰的图鉴编号
- 在收包时
 - 获取目标舰现在的五项属性
 - 计算，比较。

**Comment by JenningsWu** [comment]
`service.coffee` 里对于 `game.request` 的那段代码就是残留代码嘛。。我说的 alert 是值的那个

**Comment by dkwingsmt** [comment]
总之看起来并不能删的样子_(:3 」∠ )_
