### ISSUE TITLE
win10 10586版本下 POI有出现进程但是没窗口

### ISSUE THREAD

**Issue by jkmiku** [poooi/poi#680]
本人64位WIN10，运行5.0.0BETA版-1时只有进程，没有窗口。在CMD打开提示
C:\WINDOWS\system32>d:\poi-v5.0.0-beta.1-win64\poi-v5.0.0-win64\poi.exe

C:\WINDOWS\system32>
[INFO] Proxy listening on 12450
undefined
undefined
undefined
包括32位的程序也是如此

**Comment by KochiyaOcean** [comment]
试过 `netsh winsock reset` 么

**Comment by jkmiku** [comment]
刚刚打完命令准备重启

**Comment by jkmiku** [comment]
依然不行，还和之前一样

**Comment by alvin-777** [comment]
旧版能打开吗？

试试：
- 按快捷键`Ctrl+Shift+I`看能不能打开开发者工具
- 用`poi.exe --debug`来启动，看能不能打开开发者工具

如果能打开开发者工具的话看看console有没有error或者warning
如果打不开的话，尤其是用第二种方法都打不开的话，说明主程序在创建窗口前就挂了。。

**Comment by jkmiku** [comment]
额，C:\WINDOWS\system32>d:\poi-v5.0.0-beta.1-win64\poi-v5.0.0-win64\poi.exe --debug

C:\WINDOWS\system32>
Debug Mode
[INFO] Proxy listening on 12450
Registering shortcut: 颅        => Boss Key
undefined

**Comment by KagamiChan** [comment]
10586 全新解压执行试了下是正常的

可以尝试删除 %AppData%/poi 下的 config.cson，这样子会重置 poi 设置
清空 %AppData%/poi/plugins/node_modules 文件夹的内容，这样子会删除所有插件

**Comment by alvin-777** [comment]
额。。所以我的问题呢？
1. 旧版能打开吗？
2. 开发者工具打开了吗？

另外再附加两个问题：
3. 最后一次正常启动的时候，你修改过什么设置吗？比如老板键什么的
4. 用文本编辑器打开`%AppData%/poi/config.cson`，看里面有没有奇怪的内容？比如汉字。。

**Comment by jkmiku** [comment]
1. 旧版能打开吗？能打开
2. 开发者工具打开了吗？打不开
3. 最后一次正常启动的时候，你修改过什么设置吗？比如老板键什么的   没有设置老板键
4. 用文本编辑器打开%AppData%/poi/config.cson，看里面有没有奇怪的内容？比如汉字。还没看，刚刚出去了下

**Comment by jkmiku** [comment]
@KagamiChan 删除后可以用了，感谢！！

**Comment by jkmiku** [comment]
@alvin-777 感谢大佬细心教导

**Comment by KagamiChan** [comment]
@alvin-777 我的错。下次遇到类似情况我会说把文件名改了而不是删除了……

**Comment by alvin-777** [comment]
我的推断是不知什么缘故config里存的老板键变成了非正常字符，因为：
1. debug 模式下console输出的是个“颅”字（实际config里存的不一定就是这个字（巨硬的cmd显示不可信），不过肯定也不正常）
2. win下注册了老板键之后接着应该是注册开dev tool快捷键，而上面的console输出在老板键之后就没了，所以多半是注册老板键失败导致主程序挂了

如果在删除config之前能确认一下就好了，嗯。。。
