### ISSUE TITLE
建議修改正體中文的文本

### ISSUE THREAD

**Issue by jeanskywang** [poooi/poi#684]
發現正體中文的文本顯示不正確，變成英文了
(OS: Win 10 64 bit 企業版 build 10240 / Win 10 64 bit 家用版 bulid 10586)
![001](https://cloud.githubusercontent.com/assets/14091875/12061346/7314f8e8-afbe-11e5-93e5-b0c8bb4dbe7e.png)
![002](https://cloud.githubusercontent.com/assets/14091875/12061347/733bc5e0-afbe-11e5-817b-66b0801d706b.png)

將poi/i18n/main/zh-CN.json與poi/i18n/main/zh-TW.json做比較後發現
![003](https://cloud.githubusercontent.com/assets/14091875/12061348/73527dee-afbe-11e5-90e6-1893e0dbcfef.png)

1. 37~39行多了": "
    以37行為例，應為「"Fighter Power": "制空",」

2. 41~42行多了空格
    以41行為例，應為「"Autumn": "秋式",」

3. 另外15行的文本看起來打錯了
    應為「"repair completed": "修復完成",」

**Comment by KochiyaOcean** [comment]
总之先这么修改了，麻烦再看看有没有别的问题

**Comment by KochiyaOcean** [comment]
=。=那我先关上吧

**Comment by jeanskywang** [comment]
sorry 沒看到
其它的應該沒問題

**Comment by KochiyaOcean** [comment]
嗯，感谢指正啦~
