### ISSUE TITLE
关于新窗口插件进程索引的提案·暂定

### ISSUE THREAD

**Issue by KochiyaOcean** [poooi/poi#687]
由于目前所有新窗口插件保存于数组 `global.windows` 的方案对于新窗口插件之间通信的需求而言过于繁琐，故考虑添加一个新的 object `global.windowsIndex` 以便于插件窗口之间的访问

需要在该 object 下加入自己的 key 的新窗口插件在调用 `windowManager.createWindow` 方法时添加一个 key `indexName`，对于有 `indexName` 的调用请求，将会由 `lib/window` 创建名为 `global.windowsIndex[indexName]` 的 key，以方便进程间调用。

窗口销毁时该 key 一并销毁，以满足哈里发的意愿。

此为暂定方案，如果有异议请提出。

**Comment by JenningsWu** [comment]
建议 windowManager 增加相关的 get 函数

**Comment by KochiyaOcean** [comment]
也就是重载一遍 `require('remote').getGlobal('windowsIndex[indexName]')` 么

**Comment by JenningsWu** [comment]
window.coffee 里提供相关的操作函数吧，到时候就不通过 `remote.getGlobal` 来进行操作了，而是用 `remote.require('./lib/window.coffee').xxxFunction`

**Comment by KochiyaOcean** [comment]
可

**Comment by KochiyaOcean** [comment]
Fixed by de4ee50041188720f78ee827d4485774d7877eb7
