### ISSUE TITLE
插件的生命周期 (Done)

### ISSUE THREAD

**Issue by yukixz** [poooi/poi#688]
### `pluginDidEnable`
插件安装后、插件启用后、poi 启动后调用。

### `pluginWillDisable`
插件卸载前、插件禁用前调用。

以上调用都允许 100ms 运行时间。
插件若未能在 100ms 内执行完成，可能导致错误。

**Comment by yukixz** [comment]
考虑的开新窗口的插件和不开的插件实现差距极大、具体实现需要讨论=。=

**Comment by alvin-777** [comment]
我之前的一些想法，加上上面的那些想法：
用一句话来概括，就是“让各插件都可以自发暴露一些API”。

首先需要一个容器，比如`window.plugins`。
接着插件需要将其想公开的API注册到这个容器中去。
然后其他部分就可以任意调用这些API了

#### 举个简单的例子
map-hp 插件可以向外公开一个`getMapHp(areaNo, mapNo)`的function，返回一个`[nowHp, maxHp]`的array
map-hp 的index.cjsx中可以export一个`registerApi()`:
``` coffeescript
registerApi: ->
  window.plugins.mapHp.getMapHp = (areaNo, mapNo) ->
    # ... get the values...
    [nowHp, maxHp]
```
在pluginManager里面：
```
p = require 'poi-plugin-map-hp'
p.registerApi()
```
这样从本体／其他插件就可以直接call `window.plugins.mapHp.getMapHp(2, 5)`，得到`[1, 4]`，而不用自己再维护一套重复的代码。

至于有新窗口的插件，如果想要从新窗口中去调用其他插件的API，或者反过来，想让自己提供的API被调用时在新窗口中运行相应代码，我觉得可以建立一套 `index.cjsx <==> 新窗口` 间的通信机制，做一个模版／模块，然后剩下的就跟上面一样了。


#### 通过相同的方法可以实现
* 插件间的联动
* 插件可以提供诸如`pluginDidLoad()`, `pluginWillRemove()`之类的API（即这个issue的主题）
* 血量，秘书，一心二用之类的插件可以提供一个`canReload()`的function，这样便可直接在plugin config里重载这些插件
* 插件甚至可以给自己提供API：
``` coffeescript
# At beginning of index.cjsx:
# transfer data from old instance, if exists
if window.plugins.pluginX.getFixedData?
  preprocess(window.plugins.pluginX.getFixedData())

# ......................

# Exported functions:
registerApi: ->
  window.plugins.pluginX.getFixedData = ->
    @fixedData
```
如此想要重载需要监听数据的插件也非不可能。

----
上面的只是一个思路，当然还可以有各种变化或者许多不同的实现方式，总之用起来越简单越好啦

**Comment by Ayaphis** [comment]
我想讨论下关于插件生命的起点（初始化），目前有许多插件是基于特定提督本地数据记录运行的（航海日志，我变强了，编程日志）。
这些插件的初始化方式好像有两种，航海日志好像是记录了前一个提督的提督ID然后在POI启动时同步加载该提督数据的的（我不是很熟悉）。
另两个插件则是监听Flash加载后的Basic包，根据其中提供的提督ID获取本地数据然后初始化的。

而Basic包在进入游戏后，正常游戏中没有再次获得的可能；因此在游戏进行过程中重新载入这两个插件的操作会导致插件无法正常初始化，而不能使用。

需要注意的大概有：本地记录提督ID的行为可能无法应对切换账号的操作。
且上述两个插件也无法支持热切换（不重启POI）账号的行为（热切换账号时强制重新载入插件可解决

我目前考虑的解决方案有：
1.       本体部分 封装提督识别事件，在监听到 提督ID时，以及有插件需要重新载入时发布一遍。
          插件部分 将监听game.response事件改为监听提督识别事件，并在收到一次后即移除该监听。
          （此改动将导致新插件不支持旧本体

2.       本体部分 维护提督ID信息并开发给插件
          插件部分 先尝试读取本体的提督ID信息，如有直接读取并初始化，如无则自行监听 Basic包
          （似乎可以兼容

3.      还在想    


大概就是这样=。=求指导

**Comment by yukixz** [comment]
@Ayaphis `window._nickNameId`

**Comment by yukixz** [comment]
由于所有 life cycle 方法均为异步调用，所以给插件保留 100ms 的时间用于处理，然后无条件执行下一步。如：
```
plugin.pluginWillRemove()  # async call
sleep(100ms)
removePlugin(plugin)  # Remove plugin in memory and disk
```

**Comment by Ayaphis** [comment]
@yukixz 今天想起来 window._nickNameId 特么是nickName字符串的ID

**Comment by dkwingsmt** [comment]
只保留两个接口
```
pluginDidEnable

pluginWillDisable
```
