### ISSUE TITLE
希望poi能增加疲劳倒计时功能

### ISSUE THREAD

**Issue by Misaka2623** [poooi/poi#701]
比如像KCV那样……最好能设置疲劳到XX时提醒（比如40）
感觉看不到疲劳倒计时好难受

**Comment by dkwingsmt** [comment]
疲劳倒计时在详细舰队面板，疲劳到 xx 时提醒在设置里有，在基本设置-通知-最右边的箭头下面。

**Comment by Misaka2623** [comment]
呜，居然在详细面板里，平时一般都不点开的2333
话说5.0beta里的css样式读取得好慢
