### ISSUE TITLE
[Bug] 关闭前确认不起作用

### ISSUE THREAD

**Issue by Wafer-Li** [poooi/poi#702]
Electron v0.35.4 x64
Win 10 x64 Pro
poi's version SHA: 2702eda4e7437ee840eea6d900290e53cc6bf6dd

如题，勾选了关闭前确认。
然而关闭前并没有什么提示出现。

**Comment by Wafer-Li** [comment]
可能是偶然情况。不知道为什么又好了。

**Comment by taroxd** [comment]
手太快，那个事件还没有加载进去吧= =
