### ISSUE TITLE
[Question] 有无计划搞搞云端同步？

### ISSUE THREAD

**Issue by Wafer-Li** [poooi/poi#704]
嗯……好像百度云提供了一些 API，不知道开发组有无搞搞双向同步的想法。比如说同步一些编成日记啊，资源的变化履历啊等等。

具体 API 看这里。
http://developer.baidu.com/wiki/index.php?title=docs/pcs/guide/overview

**Comment by KagamiChan** [comment]
要说云同步的话，我感觉更喜欢 github 的 api。npm 上也有现成的 wrapper

**Comment by Wafer-Li** [comment]
个人觉得 github 不是很靠谱，小白用户并没有 github 账号。

**Comment by dkwingsmt** [comment]
FYI，百度云对于墙外用户基本上速度为0……

**Comment by Wafer-Li** [comment]
:joy: 看了一下，难点主要在于国外的好网盘基本都被墙了。

或许只能做两套东西来解决？

**Comment by KochiyaOcean** [comment]
连不上 5.0.0 的 npm 服务器的人都大把的有更何况 Google Drive……除非自己建同步服务器

**Comment by dkwingsmt** [comment]
@KochiyaOcean 自己建也是建国内国外访问不了、建国外国内访问不了好吗（

**Comment by ibicdlcod** [comment]
http://45.63.123.187/

楼上吓得我赶紧检查了一遍

**Comment by Wafer-Li** [comment]
不过自建服务器就要搞一套用户系统了，想起来这个应该比单纯调用第三方 API 要有毒得多。

**Comment by KochiyaOcean** [comment]
所以现在的结论是 \没有/
issue 我先关啦

**Comment by Wafer-Li** [comment]
好的。

**Comment by JenningsWu** [comment]
这事儿做起来要考虑的坑太多了
感觉比较可行的方案是提供一套搭服务器的框架方案，想用的人自己去配置服务器、自己维护服务器的数据与可连性

**Comment by c933103** [comment]
最簡單的方法是把存放記錄的文件夾設置成dropbox同步資料夾吧。
2016/01/03 15:59 "Donglin Li" <notifications@github.com>:

**Comment by taroxd** [comment]
@c933103 

嗯，你说的很有道理。然而大陆好像是上不了 dropbox 的吧（虽然可以用各种方式上去）

另外记得把浏览器缓存的文件夹排除掉

**Comment by Wafer-Li** [comment]
@c933103 大多数需要同步的情况主要是电脑和平板的同步，比较少有两台电脑同步的情况。

:joy: 平板要折腾一番代理还是很麻烦的。
之前在平板上折腾 poi 的 git 版，最后还是太累人不了了之。。

**Comment by taroxd** [comment]
平板不能用 Dropbox 吗。我没有平板不清楚 @Wafer-Li

**Comment by Wafer-Li** [comment]
不是不能用，是不好折腾。

寨板太卡了，搞什么都卡……

:joy:

2016-01-04 15:09 GMT+09:00 taroxd <notifications@github.com>:

**Comment by KagamiChan** [comment]
onedrive 的存在感好低:smile:
不过昨天瞄了一下 api 文档， 感觉比百度云复杂多了

其实我有设想过推送到服务器上，除了同步之外，还能存储更多的内容，比如可以晒船，可以查看每个舰娘的成长情况，哪一天做的二改之类的……不过目前暂时做不来

**Comment by c933103** [comment]
也就是說類似http://myfleet.moe的設計 <http://myfleet.xn--moe-5w2hu64flga>？
2016/01/04 16:59 "Seki Kagami" <notifications@github.com>:

**Comment by KagamiChan** [comment]
@c933103 嗯是的，但不是很想做成 proxy 形式的。原本计划像统计一样用 ajax 传送数据，不过只停留在设想的阶段……
