### ISSUE TITLE
开启了“不可变更大小”后切换纵横向时，不会变更大小

### ISSUE THREAD

**Issue by dkwingsmt** [poooi/poi#705]
![image](https://cloud.githubusercontent.com/assets/1596656/12078010/2f807810-b1c5-11e5-876d-171ff2002cca.png)

**Comment by ibicdlcod** [comment]
锁定界面大小时还要切换纵横向什么鬼 应该是误操作 禁了吧

**Comment by dkwingsmt** [comment]
然而这是可行的操作啊。锁定界面大小在工具栏上，纵横向切换在设置里面

**Comment by dkwingsmt** [comment]
总之 disable 也是一种方案啦……本来我是想的，因为切换纵横向是有默认窗口大小的，让那个窗口大小的变更的优先级高于锁定尺寸
