### ISSUE TITLE
关于插件清单UI的建议

### ISSUE THREAD

**Issue by akira02** [poooi/poi#706]
新的插件下载功能很实用，不过载好的插件清单仍是点击 插件 后展示下拉式插件选单，能不能把插件按键改成页籤的形式，点击切换到象是下载中心那样的，一个独立的分页，而非下拉式选单？这样各插件的按键也会较大，设计上也跟其他分页一样，比较有统一的风格？谢谢

**Comment by dkwingsmt** [comment]
![image](https://cloud.githubusercontent.com/assets/1596656/12084688/971a106e-b27c-11e5-9382-2289f92a3bbd.png)
那这么多插件的情况下，如果插件都摆在标签页的话，标签页岂不就长这样了……
![image](https://cloud.githubusercontent.com/assets/1596656/12084700/b6af072c-b27c-11e5-8ae8-cf3131dd5968.png)

**Comment by akira02** [comment]
不是，是“插件”页籤里面显示插件选单

**Comment by akira02** [comment]
![tmp_8508-received_1154354374589644625226377](https://cloud.githubusercontent.com/assets/4176802/12084742/8fd2f7dc-b2f2-11e5-9164-a3ce70e06063.jpeg)
大概是像右图那样，个别插件单击另开窗口？

**Comment by dkwingsmt** [comment]
老实说看起来意外地不错

**Comment by akira02** [comment]
因为总觉得那个插件摆在标签页的位置，实际上的作用却是下拉选单按纽，感觉有点怪

**Comment by edwardaaaa** [comment]
其实这个插件栏还有个问题，就是每次要用插件了，必须重新下啦菜单选择一遍。这样遇到要重复使用插件，比如说远征信息时，就要下拉两次，再点击两次。
其实可以设计成这样：
每次使用某个插件后，插件面板就保留在这个插件页面，切换面板后再次调用插件，依然是这个插件。如果要更换插件，就点击下拉箭头，打开插件列表，重新选择插件，这样会大大节省一些使用频率极高的插件点击频率，比如说：远征，预知，日志，详情等等。

**Comment by dkwingsmt** [comment]
你可以考虑用分离模式，显示里面选分离组件与面板～不过这是个可以考虑的想法，私认为

**Comment by edwardaaaa** [comment]
13寸及以下的屏幕用分离模式就比较难受，板子用户估计也是感同身受。
![screen shot 2016-01-04 at 15 40 58](https://cloud.githubusercontent.com/assets/11089376/12085345/0ba7c700-b2fa-11e5-974f-c892d83a1cf5.png)

**Comment by KochiyaOcean** [comment]
如果说 @akira02 的方尚且有实现的可能性的话 @edwardaaaa 的方案则是不 patch 掉 react-bootstrap 则不能做到了
另外修改这个菜单给使用方式带来的改动太大了，需要进一步讨论

**Comment by KagamiChan** [comment]
![untitled-1](https://cloud.githubusercontent.com/assets/3816900/12086655/227c9340-b307-11e5-9d54-5300d2c8c84a.png)


如何，这个tab按钮可以做得大一点

**Comment by KochiyaOcean** [comment]
目前的控件做不到，需要重写一个控件然后维护 fork
其实蛮麻烦的……

**Comment by KagamiChan** [comment]
一个想法，在 `NavDropdown` 前插入一个 `NavItem` ，`NavDropDown` 不显示当前插件而由新的 `NavItem` 来显示。

在显示效果上，这个  `NavDropdown`  大小要缩小，不如把设置的 tab 也同样缩小了……

![image](https://cloud.githubusercontent.com/assets/3816900/12088723/c1f2aebc-b318-11e5-961b-70ad707093e3.png)


不过对应的 handle 也得加，真的相当于重写控件了（逃

**Comment by akira02** [comment]
我先 fork 出来试试看好了...研究看看 Electron 跟代码结构。
这么说来 KCV 的标签页是在左侧的，用多层标签处理。

**Comment by taroxd** [comment]
哇，支持支持。在不切分面板的情况下应该很有用！

**Comment by KagamiChan** [comment]
![animation](https://cloud.githubusercontent.com/assets/3816900/12092230/b36734bc-b336-11e5-925e-d482526de8fc.gif)

**Comment by akira02** [comment]
哇，太感谢了。
另外插件的选单间距能不能稍微大一些？触屏容易点错

**Comment by KagamiChan** [comment]
这个只是初步的一个尝试，还要再看大家的讨论

对于选单间距，你可以暂时试试在自定义 css 里面加入以下内容：

```css
ul[aria-labelledby="plugin-dropdown"] a {
  line-height: 180%;
  font-size: 120%;
}
```

里边的百分比可以看情况调节，太大了可能会显示不全列表……

**Comment by KochiyaOcean** [comment]
插件的默认状态是空页啊……我做些改动好了

**Comment by KagamiChan** [comment]
刚才看了一下还有快捷键的处理 = =

**Comment by KochiyaOcean** [comment]
原来快捷键没改么！

**Comment by KochiyaOcean** [comment]
算了剩下的交给我改吧

**Comment by KagamiChan** [comment]
好的，拜托了（正在做日常

**Comment by KochiyaOcean** [comment]
修复了快捷键以及无插件选择时弹出 dropdown。
总之先这样吧
