### ISSUE TITLE
5.0自訂提示音

### ISSUE THREAD

**Issue by Harunalive** [poooi/poi#715]
想問5.0有辦法自訂提示音嗎?

4.2原本有\resources\app\assets\audio可以修改  5.0卻不見了

希望正式版能把提示音自訂放出來

**Comment by yukixz** [comment]
`config.set('poi.notify.audio', "/path/to/audio.file")`

**Comment by KagamiChan** [comment]
看来把 app 打包之后，还可能需要指定一个新的语音存放位置了

**Comment by dkwingsmt** [comment]
不是都说了``config.set('poi.notify.audio', "/path/to/audio.file")``了么……

**Comment by yukixz** [comment]
啊？语音的设置一直是有的、只是设置面板没地方放而已。

**Comment by KagamiChan** [comment]
我只是觉得让用户打开开发者工具然后输入命令的方式不够友好 :confused: 而且属于由于程序本身的改变出现的问题

**Comment by dkwingsmt** [comment]
让用户访问resources/assets的方式也一样不够友好啊⋯⋯poi中有很多这种隐藏设置，虽然可以通过config设置，但是没有反映在任何ui上，因为这些设置要么是使用的人较少，要么是我们不希望用户广泛更改使用。在这种情况下，如果真的有此需要的用户，打开命令行输入一次这句话，然后一劳永逸，我觉得也不是不可接受。更多隐藏选项参见（正在收集中的）wiki首页下的隐藏选项列表～～

**Comment by KagamiChan** [comment]
嗯，同意 :+1:

**Comment by dkwingsmt** [comment]
另外要采用原来的文件夹也很简单，去搜索asar然后把app.asar解开成app文件夹摆在原位置就可以了。然后你想修改assets也可以自便了

**Comment by Harunalive** [comment]
ok 解決了  非常感謝  :+1:

**Comment by arho1422** [comment]
為什麼我遠征/入渠完成,大破都沒有了POI的音效 有人知道嗎?

**Comment by KagamiChan** [comment]
@arho1422 
是有通知，但是没音效吗？

有下面一些建议：
- 提供版本和操作系统的信息
- 确认设置-基本设置中的通知音量设置
- 在开发者工具中运行`notify()`，确认是否听到了声音，并将执行结果贴出来

**Comment by c933103** [comment]
話說可以直接把該說明集成在軟件內可以點開的位置嗎？
2016/01/06 15:42 "Tong Mu" <notifications@github.com>:

**Comment by dkwingsmt** [comment]
要说的话也_不是完全_没有提示，在“关于poi”下有 wiki 的链接，而 wiki 首页就摆着“隐藏设置列表”【
