### ISSUE TITLE
5.0 POI音效消失

### ISSUE THREAD

**Issue by arho1422** [poooi/poi#717]
是我有什麼插件沒有下載嗎 我通知音效有開 但是遠征完成等等都沒有POI一聲了
遊戲內的聲音是沒有問題的

**Comment by KagamiChan** [comment]
是有通知，但是没音效吗？

有下面一些建议：
- 提供准确版本和操作系统的信息
- 确认设置-基本设置中的通知音量设置
- 在开发者工具中运行`notify()`，确认是否听到了声音，并将执行结果贴出来

看情况可能后续还需要一些别的信息

**Comment by arho1422** [comment]
我用的是5.0BETA.2 WIN64BIT 右下角是有通知的 只是沒有聲音 設置已調過了 100%音量 是有開的
請問開發者工具那裡是怎樣運行的

**Comment by arho1422** [comment]
window.notify = function(msg, options) {
    var audio, enabled, icon, sound, title, volume;
    enabled = config.get('poi.notify.enabled', true);
    audio = config.get('poi.notify.audio', "file://" + ROOT + "/assets/audio/poi.mp3");
    volume = config.get('poi.notify.volume', 0.8);
    title = 'poi';
    icon = NOTIFY_DEFAULT_ICON;
這一段嗎

**Comment by KagamiChan** [comment]
你应该是没有输入括号，要输入 `notify()`

**Comment by arho1422** [comment]
輸入notify()出現undefined了

**Comment by yukixz** [comment]
windows 10 请检查 windows 通知中心的设置。

**Comment by arho1422** [comment]
我是WINDOW7的

**Comment by yukixz** [comment]
![screen shot 2016-01-06 at 6 43 41 pm](https://cloud.githubusercontent.com/assets/3337921/12140782/6de1885a-b4a5-11e5-9f0b-fac8493882ce.png)
是否安装了这个插件？

**Comment by arho1422** [comment]
啊 有安裝..是有什麼衝突嗎

**Comment by yukixz** [comment]
去插件面板恢复默认通知音吧

**Comment by arho1422** [comment]
依舊沒有音效呢 移除了這個也一樣

**Comment by KagamiChan** [comment]
`notify()` 输入之后正常情况下会有声音才对 - -

**Comment by yukixz** [comment]
![screen shot 2016-01-06 at 6 47 52 pm](https://cloud.githubusercontent.com/assets/3337921/12140876/204288f0-b4a6-11e5-8559-8ebf7b8c1a77.png)

**Comment by arho1422** [comment]
這個我也有按個 可是按下之後上面通知語音變成了已禁用

**Comment by yukixz** [comment]
@KagamiChan 对哦=。= 即使装了这个插件、`notify()` 也会又声音才对

**Comment by yukixz** [comment]
`(new Audio("file://"+ROOT+"/assets/audio/poi.mp3")).play()`
Console 运行这个试试

**Comment by arho1422** [comment]
也是undefined 這什麼鬼= =

**Comment by yukixz** [comment]
有没有声音？！

**Comment by arho1422** [comment]
沒有..= =

**Comment by yukixz** [comment]
你的系统音量是不是把 poi 静音了？

**Comment by arho1422** [comment]
不會吧 我遊戲內有聲音阿

**Comment by yukixz** [comment]
= = 重下吧。搞不懂你的情况

**Comment by KagamiChan** [comment]
`require('fs').stat(ROOT+"/assets/audio/poi.mp3",function(err, stat){console.log(err, stat)})`
运行结果是？

**Comment by arho1422** [comment]
![123](https://cloud.githubusercontent.com/assets/16573902/12141400/f292dc80-b4a9-11e5-8e92-102f8c830097.PNG)

**Comment by KagamiChan** [comment]
那么这个文件是存在的，但是播放的时候就没有声音了 = =
顺便问一下，启动时插件有新版本的提示也没声音吧

**Comment by arho1422** [comment]
不知道呢 插件全都更新到最新了

**Comment by KagamiChan** [comment]
在全新安装的 windows 7 home basic 64 位系统上测试了，是有声音的，摊手 = =

**Comment by arho1422** [comment]
那好吧 謝謝你

**Comment by KagamiChan** [comment]
这个问题可以等等看还有没有别的提督有报告
