### ISSUE TITLE
poi5.0一心兩用插件bug

### ISSUE THREAD

**Issue by robberwong** [poooi/poi#719]
![2](https://cloud.githubusercontent.com/assets/14359886/12163136/af4984fa-b545-11e5-9077-1b700feb51ea.png)
當我開poi一心兩用時，有幾率會出現像圖中顯示的bug，窗口沒有任何按鈕，拉長窗口也會造成灰色區塊，而不會放大界面，並且無法關閉，需要用工作管理員強制關閉。右上角按鈕無效。但可以使用界面。網頁也可以通過按鈕跳轉，flash也可以執行

**Comment by KochiyaOcean** [comment]
什么版本的？

**Comment by robberwong** [comment]
poi版本5.00 一心兩用版本1.6.4 還是已經修復好了？我想問快取目錄裡面為什麼沒文件 而清理快取是清理另一個目錄的文件？

**Comment by KochiyaOcean** [comment]
试试看 ctrl + shift + i 打开开发者工具有没有报错？

**Comment by KochiyaOcean** [comment]
面向用户的是第三方快取包的路径，可以不放
清理按钮清理的是浏览器的快取

**Comment by robberwong** [comment]
剛才升級了一心兩用插件，暫時還沒見到bug 如果我見到後再試一下吧，我想問魔改的話swf檔案是放在快取的路徑嗎，因為我沒用vpn 是直接用cookie連得，我放過swf文件進去并清理快取重開後魔改并沒有發生變化

**Comment by KochiyaOcean** [comment]
魔改的话在那个文件夹下建立 `kcs/resources/swf` 再放进去。
或者右击闪电图标也可以

**Comment by Gizeta** [comment]
同遇到过，貌似第一次开的时候有一定几率会遇到，之后就不容易复现。
![default](https://cloud.githubusercontent.com/assets/1572561/12163746/76df717a-b553-11e5-8933-21a620bd0520.png)

**Comment by KochiyaOcean** [comment]
先推了个 1.7.1，不知道能不能修复（。

**Comment by Gizeta** [comment]
还是遇到了canGoBack未定义的问题。我觉得有可能是Electron里WebView初始化时的坑。

感觉触发这个问题可能与下面的代码有关
https://github.com/poooi/plugin-new-window/blob/master/views/navigator-bar.cjsx#L213
https://github.com/atom/electron/blob/master/atom/renderer/lib/web-view/web-view.coffee#L311

**Comment by KochiyaOcean** [comment]
我先改下看吧，虽然从来没遇到过……

**Comment by KochiyaOcean** [comment]
再发了新版本，求测试

**Comment by Gizeta** [comment]
这个错误没找到复现的规律，等下次报错需要一定RP

不过，我曾经在render函数中加入过判断webview.canGoBack的代码，返回的是webview内部的一个回调函数（就是我之前发的图片那个，不会为undefined），所以我觉得错误是指canGoBack在internal.webContents (https://github.com/atom/electron/blob/master/atom/renderer/lib/web-view/web-view.coffee#L311) 中未定义。（以上是一些口胡，Electron的代码我并没有仔细研究过

**Comment by alvin-777** [comment]
```
  canGoBack: ->
    try
      webview.canGoBack()
    catch error
      false
```
`canGoForward` 同理

**Comment by Gizeta** [comment]
![bug](https://cloud.githubusercontent.com/assets/1572561/12228566/bc34ce70-b880-11e5-9720-1d07989abdea.png)
好像确实没有修复呢。
认同 @alvin-777 的方法

**Comment by KochiyaOcean** [comment]
总而言之按照这种写法更新了
没法重现所以只能保证正常情况下工作……
