### ISSUE TITLE
[重构] 关于插件系统重构

### ISSUE THREAD

**Issue by KochiyaOcean** [poooi/poi#725]
该 issue 用于集合与重构插件载入相关的 issue 和 pull request

由于预计的开发时间可能会非常长，本重构计划在开发期间不并入 roadmap，开发完成后并入最近的 roadmap

在该分支下执行这项工作 https://github.com/poooi/poi/tree/plugin-reload

实现目标(暂定)
 - [x] 独立的 Plugin Manager 模块
 - [x] 进程间通信机制
 - [ ] 插件的生命周期
 - [ ] 新窗口插件的初始化
 - [ ] 重载插件实现

相关的 issue
 + [[Draft] 插件的生命周期](https://github.com/poooi/poi/issues/688)
 + [动态重载插件](https://github.com/poooi/poi/issues/690)

相关的 pull request
 + [Implementing PluginManager](https://github.com/poooi/poi/pull/619)
 + [Load plugin asyncly](https://github.com/poooi/poi/pull/731)

**Comment by KochiyaOcean** [comment]
Assignee 到底怎么用啊……还是 at 好了
@yukixz @dkwingsmt

**Comment by Wafer-Li** [comment]
一个 issue 好像只能  assign  一个人
