### ISSUE TITLE
分辨率随窗口大小自动调整问题

### ISSUE THREAD

**Issue by 0CBH0** [poooi/poi#735]
使用分辨率随窗口大小自动调整+纵版布局,导致poi-app的高度只有6 pixel而不可见,
用的64位的版本,2160*1440 px的屏幕

p.s.
顺带求教如何从开发者工具里获取webview中页面的相关元素呀,
有一个inner的广告iframe需要关闭,
以前可以直接在源文件里加$('kan-game webview').executeJavaScript "..."来操作,
现在不能改源文件了,求解...咱对网络开发不是很懂QAQ

**Comment by JenningsWu** [comment]
左键单击
![jirdxxud 850qioo v bf](https://cloud.githubusercontent.com/assets/6861365/12225629/7955fa74-b7c3-11e5-9dc3-5ea76ecd1ff1.png)
在 console 里输入你要输入的内容。

或者是右键单击那个按钮，打开的就是 webview 的开发者工具

**Comment by 0CBH0** [comment]
似乎在之儿，views\services\layout.vertical.cjsx，因为window.webviewWidth == -1，所以
factor = Math.ceil(window.innerWidth /  800.0 * 100) / 100.0 == 1.8
poiapp?.style?.height = "#{window.innerHeight - Math.ceil(480.0 * factor) - poiControlHeight}px" == 6px

**Comment by 0CBH0** [comment]
原来如此，行了~谢咧o(*≧▽≦)ツ
