### ISSUE TITLE
似乎代理设置有些问题？

### ISSUE THREAD

**Issue by trdurg** [poooi/poi#737]
今天终于克服懒癌下了500的poi，结果忘了设置代理直接就连上了。。。。啊我是用岛风go的，不过poi代理设置里是默认的不使用代理，岛风go也显示未检测到游戏链接，不过依然可以进游戏，之后又关掉岛风go重启poi依然可以直连，去dmm查ip发现用poi直连的时候的ip和岛风go的ip长得很像hhh，不过岛风go已经完全退出了也不知道是哪里的问题=。=我也除了疯狗没用任何其他vpn或者类似的东西hh
poi一直很好用不过突然出来个黑科技有点怕怕的hhh

**Comment by KochiyaOcean** [comment]
设置里有一个项目 “设置 DMM 地区 Cookie” 可以在非日本 ip 的情况下访问 DMM
不过不是一定生效就是了

**Comment by trdurg** [comment]
确实看到这个了不过我并没有点上诶hhh确认了3遍的确是没有勾选这个选项不过还是可以。。

**Comment by alvin-777** [comment]
以前改过host吧？你试试用别的浏览器直接开dmm

**Comment by trdurg** [comment]
别的浏览器显示的是地区错误。。。
