### ISSUE TITLE
Windows 10 Poi 5.0會無故閃退

### ISSUE THREAD

**Issue by artoodetoo3301** [poooi/poi#738]
4.2時沒有的 5.0就經常出現

**Comment by KochiyaOcean** [comment]
信息量太少不知道是什么情况

**Comment by artoodetoo3301** [comment]
在海域玩時有出現過 母港都有出現過 就是無故關掉消失了

**Comment by JenningsWu** [comment]
是不是不小心碰到了老板键

**Comment by artoodetoo3301** [comment]
>> 是不是不小心碰到了老板键
不會吧 我沒有設定的
在beta時都有出現過這些事件

很困擾呀 玩EO或活動時出現就不可能再使用

**Comment by KochiyaOcean** [comment]
任务管理器里没有进程了？

**Comment by artoodetoo3301** [comment]
>> 任务管理器里没有进程了？

抱歉 任务管理器是甚麼來的?

**Comment by KochiyaOcean** [comment]
![image](https://cloud.githubusercontent.com/assets/8194131/12240820/85376438-b8ca-11e5-95d0-d375f7edc1c3.png)

**Comment by dkwingsmt** [comment]
台湾是叫“工作管理员”？

**Comment by artoodetoo3301** [comment]
>> 台湾是叫“工作管理员”？

好像是 但我用英文的

**Comment by dkwingsmt** [comment]
那就是 task manager ……

**Comment by artoodetoo3301** [comment]
又出現了 task manager是沒了Poi的
就是關掉了
是老板键的問題出錯嗎? 但我可以沒有設定呀

**Comment by KochiyaOcean** [comment]
那应该是普通的崩溃了……
有什么特征么（比如在某些特定操作的时候发生？

**Comment by artoodetoo3301** [comment]
沒有呀 就是無故沒了

**Comment by KochiyaOcean** [comment]
唔，没法重现的话不好判断 bug 是在哪里啊……
还请先使用旧版本或者看后续版本是否还有这个问题……

**Comment by JenningsWu** [comment]
系统具体版本是多少呢？以及内存大小和平时的占用量是？

**Comment by artoodetoo3301** [comment]
又死了

https://na.cx/i/9nq9Ct.png

**Comment by artoodetoo3301** [comment]
旧版本 4.2是絕對沒有問題的

**Comment by JenningsWu** [comment]
迷。。从 cmd 里启动呢，能不能在闪退之后看到一些信息？

**Comment by artoodetoo3301** [comment]
應該不行 我試試吧

**Comment by taroxd** [comment]
是否在windows中禁止了poi的通知？

**Comment by artoodetoo3301** [comment]
>> 是否在windows中禁止了poi的通知？

的確有個不明原因禁止了所有通知 現在開了
正在用admin cmd開Poi 再有問題我再回報

**Comment by taroxd** [comment]
问题可能就在这里。Windows 下 electron 发通知的时候，如果通知被禁用的话是可能造成闪退的。

如果不想使用 poi 的通知，请在 poi 软件中关闭，不要在 Windows 里面禁止。现在只能这么办了……

上游 electron 的锅，我们不背（逃
