### ISSUE TITLE
1-5 10次 A 胜月常的任务计数似乎有问题

### ISSUE THREAD

**Issue by dkwingsmt** [poooi/poi#740]
![image](https://cloud.githubusercontent.com/assets/1596656/12257672/1d454422-b8ce-11e5-8bd6-47f37f638f0e.png)

![image](https://cloud.githubusercontent.com/assets/1596656/12257580/889de13a-b8cd-11e5-802c-f15d95051930.png)
然而完全不知道为什么的样子。
也确认了没有 B 胜……（而且代码写得很漂亮也不太会是这个问题）

总之 issue 先放在这里好了。

**Comment by JenningsWu** [comment]
航海日志里晒一下有几次 boss 点胜利？

**Comment by dkwingsmt** [comment]
![image](https://cloud.githubusercontent.com/assets/1596656/12257933/324e1e0a-b8d0-11e5-97e5-d373828c99b2.png)
![image](https://cloud.githubusercontent.com/assets/1596656/12257934/33a128e2-b8d0-11e5-9b9a-3edbcdefa82d.png)
比10次多……其中应该有一些是没有接任务的

**Comment by JenningsWu** [comment]
有换设备登陆的经历么，是不是换设备取消任务过

**Comment by dkwingsmt** [comment]
然而现在是本地任务计数比远端__多__呀……

**Comment by JenningsWu** [comment]
* 本地最后退出时接了任务
* 另外设备登陆，取消了任务
* 本地再次登陆，出击 1-5 boss 胜利。此时本地计数仍在进行，但实际任务未接。

这个意思

**Comment by dkwingsmt** [comment]
目瞪口呆。

以及，原来现在是会记录“接任务情况”的啊……我说为什么经常刚开 poi 不刷新任务也会记录呢……

**Comment by JenningsWu** [comment]
嗯，设定上是 “只要一直同一个设备玩，不管什么玩法统计都不会出错”

**Comment by dkwingsmt** [comment]
可以稍微修改成“这些任务计数为 pending 状态，只有在刷新任务发现‘确实已接’的情况下才并入；在刷新任务发现‘确实未接’的情况下就丢弃”。
【为了处理一个非常 edge 的 case 而变得超复杂

**Comment by dkwingsmt** [comment]
以及既然并没有 pending 状态……那么为什么不启动游戏的时候自动就把那些记录下来的“接任务情况”显示在任务面板呢？

**Comment by dkwingsmt** [comment]
![image](https://cloud.githubusercontent.com/assets/1596656/12258149/02172298-b8d2-11e5-9270-642df9ebf4cd.png)
确实有换设备玩游戏过。具体记不太清，但是应该可以认为是这个原因了。

**Comment by JenningsWu** [comment]
如果是
* 某设备上未刷新任务，做了3次月常
* 换设备登陆，取消任务
* 换回原设备登陆，刷新任务
这样不又出错了么

所以就保持现在的设定嘛~ 不然深究起来太太太麻烦了，而且没法彻底处理的。现在的原则也更清晰一些，既然多设备玩又是本地计数，就别指望计数正常了。
