### ISSUE TITLE
不知為何會無限貓.VPN.COOKIE.重裝.各種姿勢都會貓

### ISSUE THREAD

**Issue by butterfly815** [poooi/poi#741]
如題
但KCV和火狐皆能正常使用.但我果然還是喜歡poi阿
求個不會貓的姿勢

**Comment by JenningsWu** [comment]
迷，为什么会猫呢..
去 `%APPDATA%/poi` 里删掉**除了**
* akashic-records
* battle-detail
* battle-records
* hensei-nikki
* new-window
* plugins
* screenshots

之外的所有文件试试？
记得上面提到的文件夹不要动，不然之前的记录和数据就没了。

**Comment by KochiyaOcean** [comment]
一般来说是缓存错误
设置里删缓存看看罢

**Comment by NatLee** [comment]
感覺上不是瀏覽器的問題
我用KCV IE CHROME POI全都會貓QQ

**Comment by taroxd** [comment]
@NatLee 要么是你网络确实不好，要么是你被娇喘针对了

**Comment by JenningsWu** [comment]
@NatLee nga 上有人说他也是各种莫名其妙猫，然后给娇喘发了一封邮件问情况，马上就好了。

**Comment by NatLee** [comment]
我也覺得我是被針對
換電腦or網路依然貓
出擊打完第一關就貓
這樣怎麼打(´ー`)

**Comment by taroxd** [comment]
@NatLee 
可以试试注册一个小号，看看小号猫不猫。如果不猫，说明你大号被针对了。

休息几天，或者按照上面所说·给娇喘发一封邮件问情况·吧

**Comment by NatLee** [comment]
我剛查了網上
最近很多人被貓
共通點都是 柱島

看來有可能是伺服器問題(◞‸◟)

**Comment by yukixz** [comment]
啊=。= 我是柱岛的呀、除了自己网络问题之外、没猫过...

**Comment by taroxd** [comment]
所以说都被娇喘针对了……

如果你没开过脚本之类的话，那就是躺枪_(:з」∠)_

**Comment by butterfly815** [comment]
但如果被針對的話不是應該連KCV跟火狐都開不起來嗎?

**Comment by taroxd** [comment]
被针对的那些都是对 NatLee 说的。
你就清一下缓存什么的试试吧

**Comment by butterfly815** [comment]
可是清緩存也沒用說

**Comment by NatLee** [comment]
@butterfly815 有試過換電腦或換網路?

雖然我這樣依然貓 Q___Q

**Comment by NatLee** [comment]
啊
我更新完就不貓了 X)
