### ISSUE TITLE
OS X重启软件后变成最大化且无法调整大小

### ISSUE THREAD

**Issue by dorasir** [poooi/poi#744]
如题
系统版本为El Capitan

**Comment by KochiyaOcean** [comment]
![image](https://cloud.githubusercontent.com/assets/8194131/12302348/bd9e023c-ba5f-11e5-8cfd-933322e555c0.png)
快捷操作栏的最后一项，锁定窗口大小

**Comment by dorasir** [comment]
多谢，已解决，我居然忘了这茬= =
不过我是比较好奇为什么会突然最大化

**Comment by KochiyaOcean** [comment]
唔，我去检查一下

**Comment by KochiyaOcean** [comment]
确定是一个 bug
