### ISSUE TITLE
触摸屏的情况下，在设置中调整缩放的 range input 不会弹出缩放比率的 tooltip

### ISSUE THREAD

**Issue by KagamiChan** [poooi/poi#746]
没有平板的情况下的重现方法 （electron 0.36.3）：
1. 打开开发者工具
2. 在 emulation 标签页中，启用 emulate，之后选择一个 model，比如 google nexus 10
![image](https://cloud.githubusercontent.com/assets/3816900/12347230/fd735e2e-bb96-11e5-92ec-610068dd1c68.png)
3. 拖动缩放的 range input，看不到缩放比率的 tooltip 

我自己找不到原因，react-bootstrap 的 tooltip component 示例给出的按钮是能够在点击之后出现 tooltip 的，所以可能还是 range input 的特殊性

**Comment by KagamiChan** [comment]
顺便一提，估计就算有 tooltip，由于按下才能显示，也可能会被手指挡住的……

**Comment by KochiyaOcean** [comment]
点击空白处可以唤出就是了……

**Comment by KochiyaOcean** [comment]
找了几个样例都不能实现，目测是通病=。=

**Comment by KagamiChan** [comment]
我这边还是显示不出来，附近的空白处试了一下也没试出来 - -
至少 miniship 部分的 tooltip 点击之后是有效的

我的建议是既然右边还有点空间，不如改成数字显示在右边？
