### ISSUE TITLE
希望可以把游戏画面移到正中间（或者右边）

### ISSUE THREAD

**Issue by Fliuhuo** [poooi/poi#749]
现在游戏画面在左边，各种数据插件在右边
然后为了画面不失真
我选择的是画质100%
就感觉右边区域超大。
这个其实还好，最主要是画面一直在左边，导致得歪着头玩才行
（画面在左边，鼠标一般在右边）

所以是否可以考虑把ui进行拆分，分一部分到左边

**Comment by KochiyaOcean** [comment]
改起来超级麻烦能不能不改啊（逃

**Comment by Fliuhuo** [comment]
因为真的觉得好别扭啊。
其实可以考虑把组件和插件面板分开，一边一个看起来也不别扭。
我看到有人提到界面分离的需求，个人觉得其实和这个类似。
因为现在游戏主界面在左边，人一眼看过去，看不到游戏的画面。

**Comment by KagamiChan** [comment]
都实现了
