### ISSUE TITLE
poi5.0無法分析數據,何故?

### ISSUE THREAD

**Issue by qq251988** [poooi/poi#751]
剛開始還行的 用段時間後重開一直顯示提督'未登入'
試過用管理員身分開啟 也試過把視窗調到各種尺寸
似乎都沒有成效 有人有相同問題嗎?

**Comment by JenningsWu** [comment]
检查一下是否有未关闭的 poi 程序
重启电脑试试看

**Comment by qq251988** [comment]
謝謝 已解決
