### ISSUE TITLE
Suface Pro 4 / Win 10下手指無法觸控

### ISSUE THREAD

**Issue by urakagi** [poooi/poi#752]
現在Chrome有這個bug：https://productforums.google.com/forum/#!topic/chrome/EvX1pgXzEsM
他無法偵測Win10平板的觸控，所以手指觸控會失效
正常Chrome的解決方式是打開chrome://flags修改，但poi沒辦法打開這頁，用開發者工具我也找不到改flag的方法
請問有辦法解嗎？謝謝！

**Comment by KochiyaOcean** [comment]
SP4 的触控还和普通触控不一样的？普通的山寨 win10 版似乎是没问题的……

**Comment by KagamiChan** [comment]
https://github.com/atom/electron/blob/master/docs/api/browser-window.md 中提到了一些 `webPreferences` 参数，比如 `experimentalFeatures` 和 `blinkFeatures`，可能有用

**Comment by urakagi** [comment]
結果好像Chrome這次的更新修好了
