### ISSUE TITLE
可以把第二欄「艦隊詳細」改善一下?

### ISSUE THREAD

**Issue by artoodetoo3301** [poooi/poi#755]
不是只用圖示標示有什麼裝備
而好像編成日記一樣詳細用文字列出裝備
特別在空母時飛機只看到圖示跟本沒有意義吧?

**Comment by taroxd** [comment]
简单来说：写不下

除了贴出配置以外，也没看到用文字有什么意义。要贴配置可以使用编成日志。

**Comment by artoodetoo3301** [comment]
不夠位置嗎?

**Comment by KochiyaOcean** [comment]
以横屏的约 420px*400px 大小为标准，肯定不够

**Comment by artoodetoo3301** [comment]
真可惜了
