### ISSUE TITLE
当显示设置为竖屏时,插件栏选择插件时候,插件太多,能否增加一个可以鼠标滚轮滑动的设计。

### ISSUE THREAD

**Issue by linzhibinghan** [poooi/poi#758]
RT,现在插件多起来了,想全部安装,个人习惯的是竖屏,然后点开插件的时候,分辨率问题导致下面几个显示不出来,有点麻烦,希望能改善这个设计。
比如竖屏的时候是这样,我还以为可以滚轮滑动,结果并不能。
![1](https://cloud.githubusercontent.com/assets/12961467/12419211/8e5c7988-beef-11e5-8fd2-3ac389e5d726.png)

**Comment by yukixz** [comment]
@linzhibinghan 咦、这个功能不是实装了么

**Comment by linzhibinghan** [comment]
。。。。好像是又可以了,求删,刚没进游戏不行,进了游戏就可以了。。 我错了,可以删除了。打扰

**Comment by yukixz** [comment]
@linzhibinghan 下面 close 掉就好

**Comment by KochiyaOcean** [comment]
唔，开启的时候就发一个 resize 事件会比较好？
