### ISSUE TITLE
OSX 下最小化窗口后就会无法再次打开

### ISSUE THREAD

**Issue by matthew-z** [poooi/poi#759]
OSX (10.11)下载覆盖了了5.0后就出现了这样的状况:

1. 窗口一直被前置, 无法通过激活别的窗口将 poi 后置

2. 一旦点击最小化窗口后, poi窗口就再也召不出来 (准确的说, 最小化以后再点 dock 上的 logo 后窗口会出现一下, 然后立刻消失了, 然后再怎么点击 logo 也没用了, 进程是一直在运行)

**Comment by KochiyaOcean** [comment]
@matthew-z 应该是在快速设置栏启用了总在最前。

**Comment by matthew-z** [comment]
@KochiyaOcean 原来如此, 怪不得我在设置里翻了半天也找不到. =,=
