### ISSUE TITLE
强烈建议改一点小细节

### ISSUE THREAD

**Issue by tianrongze** [poooi/poi#760]
出击时候右下角的那个。出击海域：X-X
强烈建议加上“当前所在的点”（如：出击海域：4-3J）~不用剧透~战斗开始后显示就行了
主要是43肝船的时候~都不知道走到哪了……多谢了

**Comment by yukixz** [comment]
Duplicate issue of https://github.com/poooi/plugin-prophet/issues/64

**Comment by yukixz** [comment]
@KagamiChan 您有没有兴趣把这功能写了？=。=

**Comment by KagamiChan** [comment]
字母点的显示的话 #445 有讨论
最近比较忙，这个功能还要去查 api，能伸手的话我就躺会……

**Comment by KochiyaOcean** [comment]
@KagamiChan 实现好麻烦的我也伸个手（逃

**Comment by yukixz** [comment]
@KagamiChan 不显示字母就简单多了

**Comment by KagamiChan** [comment]
嗯，毕竟自己提出的 issue
那我就试试吧 = =

**Comment by KagamiChan** [comment]
wow，阿姨洗铁路
