### ISSUE TITLE
能否在一心二用中增加缩放功能

### ISSUE THREAD

**Issue by iamdefer** [poooi/poi#764]
无法通过Ctrl + +/-及Ctrl + 滚轮缩放。
高分大屏桌面机上基本看不清。
谢谢。

**Comment by KochiyaOcean** [comment]
因为 Chrome 的部分只是内核所以当然不能那么缩放啦……

**Comment by KochiyaOcean** [comment]
总而言之已经完成了请更新到 1.8.0
