### ISSUE TITLE
我方舰娘轰沉之后未卜先知的结果不准确。

### ISSUE THREAD

**Issue by were** [poooi/poi#769]
如果我方有被击沉，即使全灭对面也只有B胜了。

未卜先知返回结果为S。

**Comment by vuryleo** [comment]
我觉得由于涉及沉船的代码测试起来都很有负罪感…所以我觉着这种corner case还是wont fix的好…

**Comment by yukixz** [comment]
@vuryleo 演习呀

**Comment by were** [comment]
我最近刚好学了JS了，不介意可以让我看一下代码，我磨磨蹭蹭一个月内给fix出来？

感觉不是很难？

我甚至都想实现一个插件沉船返还多少燃弹233333

**Comment by magicae** [comment]
https://github.com/poooi/plugin-prophet
未卜先知插件代码

**Comment by Wafer-Li** [comment]
另外，旗舰大破损管进击之后的血量也不正确。

**Comment by Chibaheit** [comment]
won't fix
