### ISSUE TITLE
增加“取消SSL也使用代理”选项

### ISSUE THREAD

**Issue by ibicdlcod** [poooi/poi#772]
http://www.crystalacg.com/whiteping/

**Comment by yukixz** [comment]
你们开发代理的都不喜欢实现正常的完全代理？

**Comment by ibicdlcod** [comment]
瞎 我跟crystalacg开发又没关系 就是来问一问

**Comment by KochiyaOcean** [comment]
登录的时候选择不使用代理然后登录以后再设置成使用吧
不变更重试次数的话代理设置不需要重启

**Comment by yukixz** [comment]
或者用命令行参数将就一下
`poi.exe --proxy-pac-url=https://super.crystalacg.com/proxy_ssl.pac`

**Comment by ibicdlcod** [comment]
确认可用 Thx
