### ISSUE TITLE
5.1.0 changelog：请补充。

### ISSUE THREAD

**Issue by dkwingsmt** [poooi/poi#778]
# poi v5.1.0
## 功能
- 网络代理设置添加 PAC 支持（实验性功能）。
- 添加插件的设置功能。
 - （不过现在唯一支持插件设置的『未卜先知』并没有实际使用设置。大家假装这个功能存在）
- 通过插件名安装插件时，添加了安装进度的提示。
- OS X 下可以通过 ``Cmd+逗号`` 访问设置面板。
- 在各面板之间切换时添加了动画。
- 在网络设置下，添加了端口号选项。
 - 默认情况下，每次启动会选择一个随机可用端口。
 - 也可以选择沿用以前的策略，采用固定端口号，此时，如果启动时该端口已被占用，会弹出警告框。

## 修正
- 修复了通过插件名安装插件有时会安装失败的问题。
- 修复了Flash分辨率尺寸限制有时过于宽松的问题。
- 修复了运行 poi 同时打开低分辨率程序会导致 poi 窗口尺寸问题。
- 修复了刚打开 poi 时设置面板无法滚动的问题。
- 修复了 Windows 10 下通知语音会与系统默认通知音效同时触发的问题。
- 修改了默认的皮肤，从而修复启动全新 poi 时有时会无法操作的问题。
- 美化了近代化改修结果提示的界面。
- 切换切分/不切分面板时不用再重启 poi，不过部分插件需要刷新游戏才会有效
- 修复了某些时候启动时窗口会在屏幕外的问题。

## 插件
- 新插件：**耗资记录**
 - 记录你的每次出击的资源损耗，添加筛选器，统计数据。
- 新插件：**舰娘百科数据收集**
 - 自动向舰娘百科``http://zh.kcwiki.moe/``汇报船只数值、地图资源点等数据，帮助 wiki 编写！请大家多多支持哦。
- 航海日志
 - 移除了战果模块（已由插件“我变强了”提供），从而解决了有时启动会白屏的问题。
- 未卜先知
 - 编成和入渠时也会更新数据。

# 相对于 v5.1.0-beta.1的改动
## 功能
- 在网络设置下，添加了端口号选项。
 - 默认情况下，每次启动会选择一个随机可用端口。
 - 也可以选择沿用以前的策略，采用固定端口号，此时，如果启动时该端口已被占用，会弹出警告框。

## 修复
- 修复了 Win7 下通知无效的问题。
- 修复了某些时候启动时窗口会在屏幕外的问题。
- 修复了 Linux 下的``poi``没有“可执行”权限的问题。
## 插件
- 耗资记录
 - 修复了在有支援舰队时会无法记录的问题。

# poi v5.1.0
## Features
- Added "PAC file" to proxy settings. (Experimental feature)
- Added support for individual settings of plugins.
 - (However, the only supporting plugin "Prophet" has yet to really apply that setting. So please look forward to future versions.)
- Added installation progress notification when installing plugin by plugin-name.
- Added shortcut ``Cmd+,``  (comma) to switch to Settings panel under OS X.
- Added transition animation when switching between panels.
- Add option for "poi port" under Network Settings panel.
 - The default behaviour is to use a random port on every start up.
 - You can change and set a fixed port as poi used to do. In this case, an alert will pop up if that port has been used on start up.

## Fixes
- Fixed an issue that could prevent a plugin from being properly installed by name.
- The limit on resolution of Flash is now stricter and will take consideration of zoomming.
- poi will no longer shrink to a low resolution when opening another low-resolution programming.
- The settings panel will be able to scroll from the very beginning of the start up.
- The notification sound effect of Windows will no longer be also triggered upon notification.
- Changed the default theme therefore fixing an issue that may cause poi to be unresponsive at a fresh start.
- The interface of modernization notification has been polished.
- Switching between single tab and double tab now no longer requires a restart, but some plugins might need the flash to refresh in order to properly work.
- Fixed an issue that causes the window to be out of the visible screen in some cases.

## Plugins
- New plugin: **Where's My Fuel Gone**
 - Records the resource consumption during sortie. Filter, analyse.
- New plugin: **Kcwiki data collection**
 - Automatically collect data and reports to Kcwiki, ``http://zh.kcwiki.moe/``, including ship stats, map resources, among others. Please support the construction of our wiki if possible :)
- Logbook
 - Removed the "Senka" panel (this feature has been provided by another plugin "SenkaCalc"), therefore solving an issue that causes this plugin to crash under some cases.
- Prophet
 - Data will now be refreshed when changing composition and docking.

**Comment by JenningsWu** [comment]
@dkwingsmt 航海日志：移除了战果模块。

**Comment by KochiyaOcean** [comment]
@dkwingsmt 修改横纵与单双栏时不需要重启（某些插件需要刷新以恢复工作

**Comment by alvin-777** [comment]
主面板：重构了入渠、建造、远征面板，修复了一大波bug

剧透：编成和入渠时会实时更新了

**Comment by yukixz** [comment]
修复了多屏幕切换会单屏幕后 poi 位置在屏幕外的问题？

On Wednesday, 10 February 2016, Alvin <notifications@github.com> wrote:

> 主面板：重构了入渠、建造、远征面板，修复了一大波bug
>
> 剧透：编成和入渠时会实时更新了
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/poooi/poi/issues/778#issuecomment-181978551>.
>


-- 
*Dazzy Ding*
Email: h@dazzyd.org

**Comment by dkwingsmt** [comment]
@alvin-777 修复了一大波 bug 要是你不具体说出来是什么的话我也没法加进去的……

另外说一下是相对于 beta1的修复还是相对于500的修复。
