### ISSUE TITLE
月常「精鋭艦隊演習」的bug

### ISSUE THREAD

**Issue by alvin-777** [poooi/poi#780]
如果没有在一天之内把这个任务完成（演习7次胜利），然后在领取该任务的状态下拖到第二天任务更新，任何任务页面的操作（翻页／领取／取消）都会导致下面的error
![image](https://cloud.githubusercontent.com/assets/13615512/12762810/c30ad6b8-ca3c-11e5-9cb0-6b4cc0f192cf.png)
![image](https://cloud.githubusercontent.com/assets/13615512/12762822/da176db2-ca3c-11e5-9313-983086e9292b.png)
此时游戏中该任务会自动取消，且完成度清零。而任务面板会陷入混乱：
![image](https://cloud.githubusercontent.com/assets/13615512/12762877/1a6a8070-ca3d-11e5-8fd4-55238a4dbcb2.png)
再次领取该任务后恢复正常。

不过也有一定几率会导致poi整个炸掉（任何操作都无反应，游戏仍能正常进行），只能关掉重开。（昨天就发生了，然而今天没能重现。印象中上个月好像也是直接炸了）

**Comment by Ayaphis** [comment]
https://github.com/poooi/poi/blob/af87a929df3bbfc22d0ba4c64810dd3404e851d3/views/components/main/parts/task-panel.cjsx#L194

感觉是这里的问题，这个任务比较特殊的地方在于进度清零和接受状态更新不同步，我修修看
