### ISSUE TITLE
疑似内存泄露

### ISSUE THREAD

**Issue by zhudhjen** [poooi/poi#788]
内存占用最高到达 8G，3G+ 出现复数次，小内存表示很惶恐。。前台挂一晚上未发生泄露，在最后一次更新全部插件前未注意到泄露，重现方法未知。。

接下来计划禁用全部插件使用一段时间，如果有新的发现会来更新。。

Poi 版本：5.0.0
操作系统：Mac OS X 10.11.2
已启用插件列表及版本：
- 未卜先知 3.7.0
- 经验计算 1.2.3
- 远征信息 2.0.3
- 任务信息 2.0.5
- 海域血量 1.2.3
- 舰娘黄历 1.1.0
- 航海日志 2.2.3
- 战斗详情 1.7.0
- 装备改修 2.0.2
- 数据汇报 2.3.1

插件中最常用的是未卜先知，在最新的一次泄露时没用切换到其他插件过。

**Comment by KochiyaOcean** [comment]
@zhudhjen 关于 5.0.0 的内存泄漏报告这大概算第一例了吧😳

**Comment by zhudhjen** [comment]
关闭全部插件，在母港放置一晚，现在内存占用是 5.01GB

**Comment by JenningsWu** [comment]
@zhudhjen 贴个详细的内存占用的图？

**Comment by zhudhjen** [comment]
@JenningsWu 是关于所有 Electron Helper 进程的内存情况？
![image](https://cloud.githubusercontent.com/assets/3236031/12836987/d999893e-cbf8-11e5-90b3-538b917dc4ff.png)
![image](https://cloud.githubusercontent.com/assets/3236031/12836990/df294cea-cbf8-11e5-96d2-ff588c220faa.png)

**Comment by JenningsWu** [comment]
对。强关 5G 那个进程试试看？看下到底是哪一个进程（有可能的结果是 flash 关闭，poi 黑屏 / poi 白屏 / 无变化）

**Comment by zhudhjen** [comment]
@JenningsWu 是 flash 区域黑屏

**Comment by KochiyaOcean** [comment]
@zhudhjen flash 的内存泄漏呢……

**Comment by zhudhjen** [comment]
@KochiyaOcean 然而为什么 flash 会内存泄露呢，我明明没有大凤的……

**Comment by KochiyaOcean** [comment]
@zhudhjen Adobe 的问题……

**Comment by KochiyaOcean** [comment]
[PepperFlashPlayer.plugin.zip](https://github.com/poooi/poi/files/118645/PepperFlashPlayer.plugin.zip)
这个是更新的 flash player，右击 app 文件选择查看包内容，在 `Contents/MacOS/Pepperflash/darwin` 下替换原文件看看？

**Comment by zhudhjen** [comment]
@KochiyaOcean 尝试了新的 Flash：直到晚上六点都没有发现明显的内存泄露，在 1.1GB 左右。然而晚上出去吃饭回来到九点半内存占用到达 3.65GB。杀死后还是 Flash 黑屏

**Comment by KochiyaOcean** [comment]
@zhudhjen 没有比这个更新的 flash 版本了……只能等 adobe 了

**Comment by zhudhjen** [comment]
在非 retina 的外接显示器上放置时，泄漏量相较 retina 有所减小，8 小时左右放置后内存占用不到 2G
