### ISSUE TITLE
增加舰娘信息和装备信息的导出功能

### ISSUE THREAD

**Issue by axmmisaka** [poooi/poi#794]
懒 活动求鉴定不想截图
能导出一个csv文件也可以 图片也可以
(包括所有船，船的属性，装备数量，改修情况和资源)
我看看这个寒假也许也能自己做出来…

**Comment by yukixz** [comment]
Duplicate issues of https://github.com/poooi/plugin-ship-info/issues/14 https://github.com/poooi/plugin-ship-info/issues/41. Close them.

**Comment by yukixz** [comment]
啊不=。=
我的意思是：保留这个 issue、关掉那两个。

**Comment by axmmisaka** [comment]
对不起 我英语初中水平(因为我就是初中水平……)

**Comment by KochiyaOcean** [comment]
@axmmisaka

**Comment by yukixz** [comment]
cc @Ayaphis @taroxd

**Comment by Explorare** [comment]
所以这个功能有没有实装？咕咕咕？

**Comment by KagamiChan** [comment]
@Explorare 本来是等楼主的寒假的……姑且先接下了，不过完成时间未定

**Comment by Explorare** [comment]
@KagamiChan  不急，只要能在你游彻底过气之前搞定就好了，至少信浓还没出不是么

**Comment by KagamiChan** [comment]
舰娘信息目前已经能导出 csv 了
装备信息还没有实现

**Comment by axmmisaka** [comment]
这个寒假有空的话试试(咕咕咕咕咕)
