### ISSUE TITLE
Ubuntu Kylin 14.01LTS，无法运行poiv500/Cannot execute poiv500

### ISSUE THREAD

**Issue by axmmisaka** [poooi/poi#800]
Tried poi v420 and executed successfully
When executing poi v500 the system asks to install packages but cannot execute poi after installing them either
Tried using terminal and desktop both dont work
==========
尝试过poi v420 无问题
运行poi v500时系统要求安装一堆包，安装后并无卵用，依然无法正常运行(打开electron)
用终端和可视化桌面一个样

**Comment by axmmisaka** [comment]
超级碗比赛结束后会上传可以气死饶罗翔的照片

**Comment by dkwingsmt** [comment]
![image](https://cloud.githubusercontent.com/assets/1596656/12875138/29ab3e0c-cda9-11e5-96bf-7a62befc2a27.png)
新装的 Kylin 14.01 x64，直接下载的 poi 5.0.0 linux-x64。
需要安装的软件只有 p7zip ，除此之外需要做的事是``chmod +x poi``
应该是5.0.0采用了新解压脚本之后解压后丢失了 executive 权限的原因。
如果你试试 chmod +x poi 之后能够运行的话，下个版本前会修复。

**Comment by axmmisaka** [comment]
解决 感谢
