### ISSUE TITLE
希望能有选项把切换动画关掉

### ISSUE THREAD

**Issue by Wafer-Li** [poooi/poi#804]
如题，新版用了两周左右，还是适应不下来，切换多了有种头晕的感觉。
可能是因为我使用过程中的切换比较频繁。

如果目前有解决方案，请告知。
THANKS.

**Comment by KochiyaOcean** [comment]
@Wafer-Li 自定义 css 里加上 .poi-tab-child-positioner {transition: 0s} 就行了

**Comment by Wafer-Li** [comment]
@KochiyaOcean  Thanks.
