### ISSUE TITLE
一些界面相关细节优化的提议

### ISSUE THREAD

**Issue by edwardaaaa** [poooi/poi#805]
- 插件相关：
  - “`舰娘信息`”／“`改修装备`”／“`航海日志`”插件：
    - 插件对于自定义CSS的`字体`修改没有生效，有可能大多数插件都没有支持自定义CSS。
    -  SVG矢量图标在需要生效的地方没有生效；
      ![screen shot 2016-02-10 at 09 54 31](https://cloud.githubusercontent.com/assets/11089376/12938554/3b8f21ee-cff0-11e5-982b-875f4764073b.jpg)
      ![screen shot 2016-02-10 at 09 55 02](https://cloud.githubusercontent.com/assets/11089376/12938555/3b8f937c-cff0-11e5-83c7-2db0bc05aa75.png)
      ![screen shot 2016-02-10 at 09 55 15](https://cloud.githubusercontent.com/assets/11089376/12938556/3baf7516-cff0-11e5-8aa8-98e92728e493.png)
  - “`资源消耗`”插件：
    - 该插件目前似乎只能显示英文，希望能把剩下的语言也加进去。PS：本人用的是日文界面。
      ![screen shot 2016-02-10 at 09 54 39](https://cloud.githubusercontent.com/assets/11089376/12938549/3b5fee56-cff0-11e5-8b71-e5dc9783b892.png)
- 格式相关：
  - 栏目对其：
    - 目前界面上文字和符号没有对齐，比如“`概览`”面板的“`状态`”数值。
    - 具体来说就是“`状态`”栏和同界面下的`HP`和`舰娘名称`这两个栏目是平级关系。
    - 所以应该是和前两栏数值一样是“`左对齐`”，也就是说五角星应该是对其的。开发组编写时可能是为了美观，其实左对齐统一后的效果一样美观。
      ![screen shot 2016-02-10 at 09 53 40](https://cloud.githubusercontent.com/assets/11089376/12938552/3b87ac34-cff0-11e5-93b6-ae81144d109b.jpg)
    - 诸如这个问题还体现在“`舰队`”面板和“`预知能力`”插件。包括“`等级`”数值在“`预知能力`”插件中也没有对齐
      ![screen shot 2016-02-10 at 09 53 47](https://cloud.githubusercontent.com/assets/11089376/12938551/3b86998e-cff0-11e5-8ba0-b73b3180ef8f.jpg)
      ![screen shot 2016-02-10 at 09 41 16](https://cloud.githubusercontent.com/assets/11089376/12938548/3b2ede88-cff0-11e5-8c58-5632ec0c518c.jpg)
  - 文字对齐：
    - 该问题就是文字行与行之间没有对齐，上下参差不齐，视觉上会造成混乱。
    - 造成这个原因可能是自定义CSS的问题，也可能是字体问题，可能并不属于开发者的责任。
    - 但是POI是基于全平台特色的，希望能考虑到多平台和个性化兼容性。
    - 该问题主要体现在设置面板的“`插件中心`”。插件名称和右边的开关设置按钮没有对齐。同时希望每个插件之间能用横线隔开，这样做比较清晰。
      ![screen shot 2016-02-10 at 09 50 16](https://cloud.githubusercontent.com/assets/11089376/12938553/3b8d6c50-cff0-11e5-89dd-3cfeed63e983.jpg)
- 动画相关：
  - 动画开关：
    - 新的动作动画是个很有必要的特征，但是目前为止，至少在OS X的平台上，动画不流畅，长时间看会导致不舒服的感觉，因此希望能和SVG一样，提供动画开关，供大家选择。
  - 动画效果：
    - 另外曾今的版本中，在点击切换面板的按钮时，会有类似android的动画效果，如果将这个效果整个运用到面板切换动画，那这个效果相对左右平移的动画效果来的更加温和平滑，而且该效果会一定程度上增加动画时间，从而增强流畅度，这点和iOS7开始出现的放大缩小效果是异曲同工的。
    - 如果开发组始终无法在动画流畅度上有更好的效果，那么可以参考papercyan的主题效果。
    - papercyan主题在点击按钮时，两个“`关闭`／`启动`”的动作会导致面板上的按钮同时发生“`高亮`-`暗淡`”／“`暗淡`-`高亮`”的效果。PS：现版本该主题动画效果已经消失。
    - 同理，面板切换时，可以从“`当前面板`”渐变到“`全黑`”渐变到“`新面板`”。

**Comment by dkwingsmt** [comment]
耗资记录插件缺少日文界面翻译，因为我不懂日语( ´･ᴗ･` )     你能帮忙翻译吗？

**Comment by edwardaaaa** [comment]
只能靠组里日文大佬，我也不行额

**Comment by dkwingsmt** [comment]
总之这个插件是有中文和英语界面的。日语因为没有翻译所以都 fallback 到英语了。

**Comment by charlie5188** [comment]
i can translate to both ja and en, but seems i don't have permission?

**Comment by KochiyaOcean** [comment]
@charlie5188 You can fork it and make a pull request.
