### ISSUE TITLE
希望可以用缓存玩其他DMM游戏

### ISSUE THREAD

**Issue by galgamekami** [poooi/poi#81]
毕竟有了一心二用功能 如果其他游戏也可以用缓存玩就好了

如果其实已经可以的话 求教 我试了一下并没有用

**Comment by magicae** [comment]
其他游戏的缓存系统我并不了解
比如舰娘是 /cache/kcs/filename -> http://server/kcs/filename的关系
其他游戏的规则分别是什么样的？

**Comment by galgamekami** [comment]
刚刚把魔塔的缓存删了 细分我不记得了 但是
/cache/之后是ole 
毕竟都是Dmm的 应该类似吧？

**Comment by magicae** [comment]
似乎不类似…目前需要更多信息

**Comment by galgamekami** [comment]
ACG power 和 岛风go 上有的下缓存……你可以看看……

**Comment by magicae** [comment]
@galgamekami 并不玩其他游戏。。。需要玩家们提供一下具体信息了

**Comment by galgamekami** [comment]
@magicae 比如哪些信息？

**Comment by magicae** [comment]
就是上面我提到的
> 比如舰娘是 /cache/kcs/filename -> http://server/kcs/filename 的关系
其他游戏的规则分别是什么样的？

**Comment by galgamekami** [comment]
……那个……我并看不懂

**Comment by magicae** [comment]
舰娘缓存包的规则是，获取一个http://游戏服务器ip/kcs/PortMain.swf 这个swf，那么poi应该去cache/kcs/PortMain.swf寻找这个缓存文件。
其他游戏的规则我都不知道。

**Comment by galgamekami** [comment]
我过会在下一次看看有没有类似文件

**Comment by galgamekami** [comment]
我过会在下一次看看有没有类似文件

**Comment by galgamekami** [comment]
到处翻了一下 带有main的貌似是对应内容是猫 然后有很多js文件和swf

**Comment by magicae** [comment]
你可能需要找一个了解你所玩的这款游戏的缓存机制的人来提供一下信息

**Comment by galgamekami** [comment]
我试试去问问

**Comment by KochiyaOcean** [comment]
使用一心二用里的齿轮按钮召唤开发者工具然后在 Network 标签页里查看游戏元素的来源吧

**Comment by KochiyaOcean** [comment]
举个栗子比如 しんけん 元素的 URL 是 http://snkncdn.swordlogic.com/更新日期/ 后面跟着一堆路径，那么它的缓存就是 /cache/shinken/filename -> http://server/更新日期/filename 这样

**Comment by KochiyaOcean** [comment]
Fixed by https://github.com/poooi/poi/commit/a9aa6fa030474620109fe6a80faf4af14ff6f53c
