### ISSUE TITLE
ubuntu下beta5.2.0运行问题

### ISSUE THREAD

**Issue by Dhentai** [poooi/poi#820]
![2016-02-14 08 51 26](https://cloud.githubusercontent.com/assets/11966706/13031035/7c169eb2-d2f8-11e5-93a7-01c90a79f766.png)
不知道是不是我操作有问题，还不怎么懂（笑
5.10没问题

**Comment by dkwingsmt** [comment]
我这能够重现。正在检查原因。Win 和 OSX 貌似没有问题。

**Comment by dkwingsmt** [comment]
经过我的二分法查找，是在 https://github.com/poooi/poi/commit/a213a0a503c93a36b8b16ecf081cb7443c2bf74c 这个 commit 开始出错的。这个 commit 的 parent 能够正常运行。

**Comment by KochiyaOcean** [comment]
![image](https://cloud.githubusercontent.com/assets/8194131/13031369/4f4feffa-d307-11e5-949a-cfd69e614072.png)
Debian Jessie，桌面环境为 xfce，工作正常。

**Comment by KochiyaOcean** [comment]
![image](https://cloud.githubusercontent.com/assets/8194131/13031494/8fe25afa-d30a-11e5-83f0-1ff2607f39ac.png)
Gnome3 工作正常。似乎需要考虑一下是不是 Unity 专属的问题了？

**Comment by KochiyaOcean** [comment]
撤销 Linux 的 appIcon 并使用通常的窗口菜单代替，应该不会再出现这类问题了
