### ISSUE TITLE
关于当前出击海域显示的提议

### ISSUE THREAD

**Issue by Wafer-Li** [poooi/poi#821]
目前对于当前战斗点的显示是数字形式，但是很多人不会去记数字，实际上并没有起到相应的效果。

当然显示字母也是一样的，**并没有什么区别**。

所以不如 **弹一张小的地图的图片出来**，这样更直观。

当然，为了避免误操作和鼠标乱移动导致的体验下降，可以采用 **右键点击弹出** 这种形式。

不知道各位 dalao 意下如何？

**Comment by KochiyaOcean** [comment]
@Wafer-Li ちょっと面倒だな……

**Comment by dkwingsmt** [comment]
就我个人而言的话，如果需要做到这个程度，那么就把当前战斗点取消好了。
毕竟当初就没想过加这个。

**Comment by taroxd** [comment]
支持完全取消~

**Comment by Wafer-Li** [comment]
:joy:  
当然这只是一个提议而已，实在太麻烦了也可以不做。。

至于完全取消嘛……我觉得不是很合适，毕竟现在不都出了新版本的 beta 了吗？  
现在再说取消这个功能……

**Comment by KagamiChan** [comment]
为什么又变成完全取消了 = =
我觉得现在这样，然后可以切换显示数字还是字母就可以了

这种更适合丢插件里，做一个新窗口插件，和当前出击海域同步显示地图以及攻略……

**Comment by yukixz** [comment]
无法达成共识
