### ISSUE TITLE
小建议和个小问题

### ISSUE THREAD

**Issue by linzhibinghan** [poooi/poi#827]
一直觉得点装备,不显示属性,挺别扭的,不是大佬,总会有一些装备的属性给他忘掉.

以前用kcv的时候,kcv鼠标移动上去装备属性他会显示的,后来kcv实在没法用,就开始用poi用到现在,也有蛮久了,感觉挺好的,反馈F5刷新之类的也都更新出来了,但是装备这个一直还是没变化,是否因为工作量太大或者别的原因导致没做呢?

不要求显示改修或者列表显示,只是说能否增加个基础属性在名字下方,当鼠标移动过去的时候.
比如以下这2个界面的情况....

![1](https://cloud.githubusercontent.com/assets/12961467/13061394/c207dfc8-d472-11e5-80dd-eb09d02d19c7.png)
这个是舰队界面,鼠标移动到装备的位置,会显示装备的名字,能否在名字下面加上基础属性呢....

![2](https://cloud.githubusercontent.com/assets/12961467/13061412/d52b7fba-d472-11e5-95ea-e5459ad4f5e1.png)
这个是装备属性插件的界面,鼠标移动过去是没有任何反应的,同理能否加一个鼠标放在上面的时候,显示对应基础属性呢....

顺带问下,设置网络代理,除了端口(ss一般默认为1080) 外又多了一个本地端口,有什么用？

**Comment by KochiyaOcean** [comment]
@linzhibinghan 整理数据太麻烦不想做

**Comment by KochiyaOcean** [comment]
![image](https://cloud.githubusercontent.com/assets/8194131/13064534/d94c4608-d48e-11e5-8c70-e83973c383d7.png)
性能数据倒是有但是娇喘这 api 太心累了……什么时候有心情了再考虑做吧……（逃

**Comment by dkwingsmt** [comment]
本地端口是因为 poi 从舰娘 flash 获取数据是通过监听本地端口抓取的。一般情况下保持默认值就可以了，除非串联logbook等其它工具。

**Comment by KagamiChan** [comment]
小建议这个和 #654 说的应该差不多。~~如果捞船捞得开心，~~活动完之后没有人接手的话我会试试看……

**Comment by KochiyaOcean** [comment]
E1 捞酒匂地狱中
好吧好吧我早上起来就写……

**Comment by KagamiChan** [comment]
上班狗表示活动期间光捞船就精疲力竭了，还要加班  = =

**Comment by linzhibinghan** [comment]
谢谢了,才想起来我有留言这个,其实这个poi刚出来的时候我就想建议的,但是看你们工作多,F5什么也还没弄那时候,就没提.我关闭话题吧.
那天也是确实发出来,就发现有人早提过了.本地端口串联么,那我确实用不到,但是大概意思懂了,谢谢.
