### ISSUE TITLE
5.2.0b1 纵版布局问题

### ISSUE THREAD

**Issue by KagamiChan** [poooi/poi#833]
![image](https://cloud.githubusercontent.com/assets/3816900/13153126/70c5491a-d6ad-11e5-8b17-09d3a5c15011.png)

复现方式：
改成纵版布局

windows 10 64bit, electron@latest
master 版本，执行过 npm 和 gulp
也试过重置 config.cson
非 debug 模式下 console 无 warning

昨天晚上用得还是好好的，所以也不知道是不是我的打开方式有问题……

**Comment by JenningsWu** [comment]
进游戏就正常了
（被这个 bug 戳中笑点

**Comment by KagamiChan** [comment]
我是因为重置了设置所以截了一张未登录的图。在我的平板上这个问题登录后也没有解决，平板上是开了分辨率缩放的。
晚上回去再测试一下

**Comment by KagamiChan** [comment]
#835
