### ISSUE TITLE
5.2.0-beta.1 在 windows 下无法启动

### ISSUE THREAD

**Issue by dkwingsmt** [poooi/poi#834]
启动即白屏
![image](https://cloud.githubusercontent.com/assets/1596656/13168520/254b13f2-d6a3-11e5-83d0-c5fd2551e91b.png)
 然而 Mac 上可用的样子。app.asar 从 Mac 复制过去也是这样。

**Comment by dkwingsmt** [comment]
经测试不打包 app.asar 就能够启动。虽然似乎有别的问题。

**Comment by dkwingsmt** [comment]
关于楼上，是这个
![image](https://cloud.githubusercontent.com/assets/1596656/13168723/06de404a-d6a5-11e5-92fd-51dd431debec.png)

**Comment by KagamiChan** [comment]
win10 下是好的
![image](https://cloud.githubusercontent.com/assets/3816900/13176769/7de88a6a-d74f-11e5-95b5-944a565c5a96.png)

**Comment by KochiyaOcean** [comment]
@KagamiChan 唔，可能要附带一个 md5 了

**Comment by KagamiChan** [comment]
@KochiyaOcean 

```
  File: poi-v5.2.0-beta.1-win32-x64.7z
CRC-32: 4091e27f
   MD4: 056903ef143b0b1fa4788b0c649b6bda
   MD5: 7e02e467a884b51dde9a3a3691649c5c
 SHA-1: d9c3ca42bdc29f0ac3a5779cec0cda4c4f5311b2
```

7z 包自带校验，里边的东西应该没问题

想起来上次用作测试的 win7 虚拟机还在，又试了一下
![windows 7 x64 for test-2016-02-19-21-55-38](https://cloud.githubusercontent.com/assets/3816900/13177373/a6b0e8da-d753-11e5-92f0-4bd61b132f9f.png)

网卡驱动貌似被更新给搞没了，不过应该没什么影响

**Comment by dkwingsmt** [comment]
可能是测试环境为网络磁盘的问题。
