### ISSUE TITLE
5.2.0-beta.1 在“分辨率随窗口大小自动改变”的时候无法显示Flash

### ISSUE THREAD

**Issue by dkwingsmt** [poooi/poi#835]
![image](https://cloud.githubusercontent.com/assets/1596656/13168544/664d9960-d6a3-11e5-937c-d587caad3581.png)
此问题全平台有效

**Comment by sage417** [comment]
https://github.com/poooi/poi/blob/master/views/services/layout.cjsx#L55

**Comment by dkwingsmt** [comment]
5.2.0-beta.2 实测这个 bug 并没有得到解决？？纵版分离
