### ISSUE TITLE
耗资计算不知道是否是有bug

### ISSUE THREAD

**Issue by Fliuhuo** [poooi/poi#836]
![default](https://cloud.githubusercontent.com/assets/3762179/13180917/8890f9f0-d765-11e5-8a9f-b88b02730166.png)
![default](https://cloud.githubusercontent.com/assets/3762179/13180921/8df096c6-d765-11e5-8f62-a231ff32fa04.jpg)

通过战斗详情可以看到我今天进出了几次e3的boss点试图斩杀

但是耗资记录里面今天活动的记录离奇消失了
但是1-1刷闪之前的记录什么都在

**Comment by dkwingsmt** [comment]
你用的什么版本？一个很老的版本无法记录带有支援舰队的出击。最新版本是 v0.3.9

**Comment by Fliuhuo** [comment]
是0.39

**Comment by dkwingsmt** [comment]
插件里面确实有些判断在某些情况不记录，有可能那一段的逻辑有点问题。
以后我对于这种情况加个 log 吧，等下次出现的时候根据 log 来 debug。
