### ISSUE TITLE
征求poi主页设计

### ISSUE THREAD

**Issue by magicae** [poooi/poi#837]
poi主页的坑一直飞着，找个时间填了吧，从征集设计开始

欢迎投稿！

**Comment by dkwingsmt** [comment]
先做好定位吧，是为了解决什么问题？

**Comment by magicae** [comment]
包含一个主页 上面两个下载地址 一个GitHub地址 一个文档地址
顺便包含一个捐赠页也可以
面向群体是用户
估计就两个静态页面 所以可以狂霸酷炫屌炸天一点 于是求设计

**Comment by KochiyaOcean** [comment]
@magicae 再加个简短介绍什么的？你组急需一个设计师……

**Comment by magicae** [comment]
差不多就是为了解决"poi怎么没有主页啊, 每次都看个度盘"的问题

**Comment by JenningsWu** [comment]
@magicae 柑橘美酒，需要外援

**Comment by dkwingsmt** [comment]
@magicae 基本思路是直接基于某 bootstrap 现成模板？

**Comment by magicae** [comment]
gayhub人才那么多 比如@edwardaaaa

**Comment by magicae** [comment]
看设计稿 如果设计的很炫的话 当然要手写ui了

**Comment by c933103** [comment]
整個網頁就 http://i.imgur.com/RIRk9Qy.jpg 這樣怎樣？
註：下面的----•----•----具體來說就是 百度網盤(中國大陸用)•Github (國際用/Download)•幫助文檔

**Comment by KochiyaOcean** [comment]
太灵魂了……Orz

**Comment by alvin-777** [comment]
总之先吧readme.md里的内容全搬过去？

**Comment by steveny9911** [comment]
![img_1578](https://cloud.githubusercontent.com/assets/8460976/13210023/abdac564-d8df-11e5-8c82-a636346188a9.jpg)

不知这样的Framework感觉如何，主要就是几个板块拼的
简洁明了，不算特别复杂吧，不过应该还算好看
之后可以Framework细节和修改一下，试试色彩，文字／字体，图标／图片什么的
估计Bootstrap＋稍微CSS修改可以整出来

**第一个板块**就是主板
上面的Main description可以是全名什么的
Logo应该可以正好可以放成字母O
之后的3个Link可以分别下载，度盘，捐赠之类的（Github可以放在左上角的小banner）

**第二块**就是详细，剪短一些的解释什么的
可以从Ready里面拽一些简介什么的

**第三个板块**可以重复调换使用（mini屏幕有点小画不下orz）
大概就是左／右面是截图，然后相反方向就是标题和详细解释
可以讲讲Main features，丰富的plugin扩展，或者wiki里面的user guide什么都可以放

**之后**可以膜拜一下制作者什么的 TwT

**最底下**就是简单的Bootstrap footer一扔就好咯
可以hyperlink到个别板块，还是连接什么的

基础估计差不多就这5大板块吧～
有些地方，比如3 Link感觉还需要更改，嘛 ～( ´ ▽ ` )ﾉ 各位大佬多多指教

**Comment by NatLee** [comment]
QQ
http://natlee.github.io/poiSite/

**Comment by Ayaphis** [comment]
感觉不错=3=

**Comment by c933103** [comment]
置頂的poi三個字可以在窄屏幕(e.g.手機)上縮小以便完整顯示嗎？

**Comment by NatLee** [comment]
@c933103 已修正css
這樣應該可以正常顯示了XD
http://natlee.github.io/poiSite/

**Comment by edwardaaaa** [comment]
@magicae 不好意思呀，平时光顾gaybar，许久不上gayhub了，@NatLee设计主页个人挺喜欢的，同时希望主页可以支持高分屏，如果有素材需要美化的或者其他美化事宜，欢迎Q我，或者E我：edwardzeissmccartney@gmail.com~

PS：一直想知道POI图标是哪一位大神画的，不知道在开发组里吗。。。

**Comment by KochiyaOcean** [comment]
@edwardaaaa Contributor 第一位那位就是（

**Comment by NatLee** [comment]
@edwardaaaa 請問高分屏大概是多少，因為網頁本身是對分辨率去做偵測的XD
如果是覺得圖像分辨率低的話，我可能需要高分辨率的POI圖標..QQ
感謝提供建議 :+1:

**Comment by KagamiChan** [comment]
可以以 5k imac 为上限：5120 x 2880
我觉得 banner 的 500k 体积稍微有点大，如果要做高分的话还是需要控制一下体积，也许可以用原图 + css 滤镜的形式

**Comment by KochiyaOcean** [comment]
个人觉得 1200 宽就好了……

**Comment by KagamiChan** [comment]
感觉主流浏览器都支持根据系统的缩放比例来渲染网页，不用加额外的 media query，所以我上边说的分辨率不用太在意……
但是图像的高分应该还是有点效果的

**Comment by edwardaaaa** [comment]
@NatLee PPI目前最高的并且是主流的荧幕应该是MacBook Retina和iMac的Retina荧幕，PPI浮动在226左右，换算下来就是常规尺寸的荧幕长宽各*2既可以满足高清显示。

**Comment by NatLee** [comment]
我想試試看高清圖片XDD
有人能提供一張試試嗎？

**Comment by c933103** [comment]
https://imgur.com/a/w7DLI 圖標鋸齒明顯…

**Comment by magicae** [comment]
http://poi.io 初稿
代码在 poooi/poi-server 下

**Comment by edwardaaaa** [comment]
打开速度各方面都不错，就是开了一会风扇莫名飞起了。

**Comment by KagamiChan** [comment]
`.Typist ` 的内容不能根据所选择的语言而变换

**Comment by magicae** [comment]
@KagamiChan Fixed

**Comment by wudifeixue** [comment]
话说从poi.io出来以后这个issue可以关了吧
