### ISSUE TITLE
Tooltip 和独立窗口的插件不跟随界面缩放设置

### ISSUE THREAD

**Issue by xupefei** [poooi/poi#838]
如图。界面缩放是 200%
![image](https://cloud.githubusercontent.com/assets/1687847/13201939/55a2f270-d88f-11e5-89a2-b694f8604cc2.png)

![image](https://cloud.githubusercontent.com/assets/1687847/13201944/711500a2-d88f-11e5-88a5-9004a4f58a54.png)

**Comment by KochiyaOcean** [comment]
因为 Tooltip 并不是它所在的位置的子元素……处理起来过于麻烦所以不处理了

**Comment by xupefei** [comment]
那能不能至少把独立窗口插件的缩放修一下……

**Comment by KochiyaOcean** [comment]
非同一进程间的通信比较麻烦，需要各插件独立实现
后续版本考虑加入吧

**Comment by KagamiChan** [comment]
tooltip 和独立窗口插件的 Node 是动态生成的，可以用注入 css 来做
但是 react 对于 <style> 标签的 render 好麻烦……

**Comment by yukixz** [comment]
done?

**Comment by KochiyaOcean** [comment]
Fixed by https://github.com/poooi/poi/pull/890
