### ISSUE TITLE
在lubuntu下遊戲畫面上方出現white border

### ISSUE THREAD

**Issue by bckps7336** [poooi/poi#848]
系統：lubuntu 15.10 x64
內核版本：4.2.0-27
截圖：
![2016-02-24-235803_1366x768_scrot](https://cloud.githubusercontent.com/assets/8579700/13291390/7c1c7758-db52-11e5-9cfe-708385b9fd9c.png)

**Comment by KochiyaOcean** [comment]
固定分辨率？

**Comment by bckps7336** [comment]
是的，因為不固定的話右面介面會太窄
現在用的是100%
下面是不固定的截圖
![2016-02-25-002347_1366x768_scrot](https://cloud.githubusercontent.com/assets/8579700/13292290/214e7ade-db56-11e5-91c0-35be91395501.png)

**Comment by KochiyaOcean** [comment]
开发者工具里是否有报错？

**Comment by bckps7336** [comment]
沒有，只是一些版本信息
![2016-02-25-002623_1366x768_scrot](https://cloud.githubusercontent.com/assets/8579700/13292370/6ff89fde-db56-11e5-99cb-45a814a6d622.png)

**Comment by KochiyaOcean** [comment]
右击开发者工具确认页面中是否有插入的 CSS 内容
![image](https://cloud.githubusercontent.com/assets/8194131/13292416/9f70444c-db56-11e5-8b40-338abc06e0c3.png)
![image](https://cloud.githubusercontent.com/assets/8194131/13292423/a5aca8a0-db56-11e5-9bdc-4d8c9e27c2e9.png)
![image](https://cloud.githubusercontent.com/assets/8194131/13292435/b27c6eee-db56-11e5-93a2-8218de3f5b56.png)

**Comment by bckps7336** [comment]
3個都沒有

**Comment by KochiyaOcean** [comment]
左键开发者工具运行
```
$('webview').insertCSS("html {\n  overflow: hidden;\n}\n#w, #main-ntg {\n  position: absolute !important;\n  top: 0;\n  left: 0;\n  z-index: 100;\n  margin-left: 0 !important;\n  margin-top: 0 !important;\n}\n#game_frame {\n  width: 800px !important;\n  position: absolute;\n  top: -16px;\n  left: 0;\n}\n.naviapp {\n  z-index: -1;\n}");
```
试试看

**Comment by bckps7336** [comment]
好像不行。。
不過我看見了一個div#spacing_top的東西，高度16px。
運行
`$('webview').insertCSS('div#spacing_top {\n display: none;\n}')`
成功了
有沒有辦法可以自動化這個過程？（啟動的時候自動隱藏）

**Comment by KochiyaOcean** [comment]
Windows 和 OSX 都没有出现这个 div，或许是 DMM 那边的问题吧……
我去把这个 css 加上好了
