### ISSUE TITLE
插件和开发文档的问题

### ISSUE THREAD

**Issue by kimi641** [poooi/poi#850]
直接在%AppData%\Roaming\poi\plugins\node_modules下建立插件的目录加入index.cjsx后所有插件不能显示，设置页面中插件信息也会消失(win10)。index.cjsx中的代码使用开发文档中的代码，开发文档中index.cjsx中`initialItemImprovementWindow()`是笔误，之后的`tar cvf [repo] [repo].tar.gz`打包也有笔误。希望能提供本地写插件的方法。

**Comment by KochiyaOcean** [comment]
@kimi641 可能读取插件的部分有疏忽，作为暂时解决方法请放入一个 package.json 文件。详细参照 npm 文档
