### ISSUE TITLE
插件API v2讨论

### ISSUE THREAD

**Issue by dkwingsmt** [poooi/poi#853]
希望能够达成这些目的
- 能够与主体互认版本兼容性。
- 包括 pluginWillUnmount 在内插件生命周期。
- 专门设定的插件用 env 接口和工具函数。（现存机制是 require + hard-code string，封成一个函数）
- 解决一些 export 的现存问题。如标题栏的 DOM 格式
- 插件 exports.windowURL exports.windowOptions
- 创建新窗口及维护交由本体处理

欢迎补充。

----
关于版本兼容性
- 在下个主体版本时，提前在主体和所有插件上实装兼容性检查。经过一段时间之后应该基本上都能更新了。
- API v2实装后就能够直接提示不兼容了。

**Comment by dkwingsmt** [comment]
之前记得有次提到要把新窗口插件的窗口创建移动到本体内？

**Comment by yukixz** [comment]
插件 exports.windowURL exports.windowOptions
创建新窗口及维护交由本体处理

On Saturday, 27 February 2016, Tong Mu <notifications@github.com> wrote:

> 之前记得有次提到要把新窗口插件的窗口创建移动到本体内？
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/poooi/poi/issues/853#issuecomment-189616084>.
>


-- 
*Dazzy Ding*
Email: h@dazzyd.org

**Comment by dkwingsmt** [comment]
一个卫星：有没有可能统一新窗口插件和内部插件的用法，实现之前的某 issue “插件可以独立出来”？即使要求完成之后需要刷新 Flash。

**Comment by yukixz** [comment]
合并到 #725 讨论？
