### ISSUE TITLE
插件系统的重构

### ISSUE THREAD

**Issue by yukixz** [poooi/poi#855]
本 issue 用于集合与重构插件系统相关的内容。
有更新时请直接修改顶楼。

## 想要实现什么？
- [ ] 可在 poi 运行时，动态重载插件，即运行时启用/禁用/安装/卸载
- [ ] 统一所有类型的插件的 API，即 inline/window 两类插件使用相同的 API
- [ ] （可选）实现插件 inline/window 可由用户切换

## 细分目标
- [ ] 整理插件 exports 的字段（即插件 API） #864
- [ ] 新窗口插件的创建与管理交由本体处理
- [ ] 插件状态变化时、调用插件暴露出来的 API #688 
- [ ] 实现插件的动态重载 #865
- [ ] 提供插件与本体通信的机制 #866

**Comment by yukixz** [comment]
@dkwingsmt DK 把 #853 的内容合并过来、然后我们一条一条开 issue 讨论=。=

**Comment by dkwingsmt** [comment]
已合并

**Comment by KochiyaOcean** [comment]
关于需要 export 的字段
在原有基础上

增加
 - `defaultMode` // 默认启动插件的形式，可以选择 `inline`、`window` 和 `window-only` 3 种
 - `windowOptions` // 启动形式为窗口时的窗口属性
 - `multiWindow` // 是否允许存在多个插件窗口
 - `realClose` // 是否真正关闭窗口（或者只是隐藏），在 `multiWindow` 为 `true` 时无视该项
 - `useEnv` // 是否加载本体的 view/env 并接受来自本体窗口的初始化数据

删除
 - `handleClick`
