### ISSUE TITLE
關於poi5.2版本的固定視窗功能?

### ISSUE THREAD

**Issue by qq251988** [poooi/poi#859]
今天因為更新顯卡驅動導致以往慣用視窗大小跳掉

才發現5.2版本的固定視窗功能疑似被拿掉了?

後來我才載回5.0版本 調回去的   

5.2版本是不小心拿掉這功能還是改放在其他地方呢?

**Comment by taroxd** [comment]
右键下方托盘图标或者在主面板中按下alt可以有设置菜单

**Comment by KochiyaOcean** [comment]
@qq251988 因为误点击的太多改到 alt 菜单里了
