### ISSUE TITLE
允许调节游戏画面与信息栏之间的距离

### ISSUE THREAD

**Issue by einbrain** [poooi/poi#860]
能不能在主画面与信息栏之间放个splitter用来调整两者宽度比例？特别是信息栏右置的时候。

现在（5.2.0）是主画面大小根据窗口高度调整，余下空间给信息栏，然后信息栏本身有个最小宽度这样
但是很多时候这个最小宽度并不能提供足够的可读性(e.g. fullhd分辨率开全屏)，必须调整窗口大小，
而调整窗口宽高会同时影响两者大小，不是很方便。

**Comment by KochiyaOcean** [comment]
@einbrain 为什么不使用固定分辨率呢

**Comment by einbrain** [comment]
只使用一种窗口大小时可以这样，但是如果总是调整窗口size的话还不如自动分辨率方便。
所以总在想如果有个splitter就更好了

**Comment by KochiyaOcean** [comment]
说实话代码有点麻烦暂时没有兴趣（改相关代码已经改累了……

**Comment by KagamiChan** [comment]
已经加入了信息栏宽度/高度的设置
