### ISSUE TITLE
Mac 下 Poi cpu内存占用飞起

### ISSUE THREAD

**Issue by oufumihiko** [poooi/poi#861]
莫名就占了1.4g的内存。有时还能占用90％的cpu

**Comment by KochiyaOcean** [comment]
@oufumihiko 用任务管理器查看一下是哪个 poi 进程占用内存高，以及终止它以后有什么影响

**Comment by oufumihiko** [comment]
![screen shot 2016-03-01 at 23 10 18](https://cloud.githubusercontent.com/assets/8544939/13431093/d7b26136-e002-11e5-833b-26c62f818cac.png)
![screen shot 2016-03-01 at 23 08 46](https://cloud.githubusercontent.com/assets/8544939/13431099/ddb3a3b0-e002-11e5-9e94-7248e52e8f38.png)

前面都飙到150%了233

**Comment by alvin-777** [comment]
业界毒瘤 flash 吃CPU是常事，尤其是包含了复数运动物体的画面（比如母港飘的花瓣，编成页面的闪，战斗后飘纸片等等），你都可以看到CPU烧得飞起。只要不是静止页面(比如战果页面)也是CPU狂飙就应该算是正常。。

至于内存占用，我这里一直都是在正常范围内，复现不了。之前似乎听人提过跟retina屏有关，不知是真是假

**Comment by KochiyaOcean** [comment]
吃内存的是 Electron Helper 还是 poi 本体进程？如果是前者请试着终结此进程并看看有何影响

**Comment by oufumihiko** [comment]
@KochiyaOcean  Electron Helper 终结掉，游戏页面就消失（白屏）了

**Comment by KochiyaOcean** [comment]
@oufumihiko 那就是 flash 的问题和 poi 没什么关系噜

**Comment by oufumihiko** [comment]
@alvin-777 问题是上一个版本并没有这样233

**Comment by KochiyaOcean** [comment]
@oufumihiko 那就先用上个版本吧 466

**Comment by oufumihiko** [comment]
@KochiyaOcean 清除了下缓存占用就不是特别高了
