### ISSUE TITLE
插件系统的重构 - API v2

### ISSUE THREAD

**Issue by yukixz** [poooi/poi#864]
目前插件 API 包含以下内容：
```
module.exports = {
  name: String // 插件的英文名
  displayName: String | ReactElement // 插件在界面显示时的名字
  priority: Number // 插件在菜单里排序的优先级，值越小插件就会显示在越前
  show: Boolean // 插件是否应该被显示
  realClose: Boolean // 窗口插件在关闭时是否完全终结进程，默认为否
  author: String | ReactElement // 插件作者
  link: String // 插件作者的链接
  description: String | ReactElement // 插件基本描述
  version: String | ReactElement // 插件版本
  reactClass: ReactClass // 插件的视图和逻辑，将会渲染进 poi 插件面板里，使用 React.createClass 生成
  handleClick: Function // 如果插件拥有这个属性，那么它的 reactClass 属性会被忽略，并且不会在插件面板里，你可以指定用户点击菜单时的反馈（比如新建窗口等）。
};
```

API v2 需要对这些字段进行整理和更新
_待更新_

**Comment by KochiyaOcean** [comment]
- `defaultMode` // 保留字段，数组，默认启动插件的形式，可以是 `inline` 和 `window`（只有 `renderClass` 或者 `windowURL` 时固定为相应形式，都没有则固定为 `[]`
 - `windowOptions` // 启动形式为窗口时的窗口属性
 - `multiWindow` // 是否允许存在多个插件窗口
 - `realClose` // 是否真正关闭窗口（或者只是隐藏），在 `multiWindow` 为 `true` 时该项目固定为 `true`
 - `windowURL` // 新窗口加载的 URL
 - `useEnv` // 是否加载本体的 view/env 并接受来自本体窗口的初始化数据
 - `pluginDidLoad` // 插件加载后执行的函数
 - `pluginWillUnload` // 插件将要卸载时执行的函数

**Comment by alvin-777** [comment]
建议去掉 `name/author/link/description/version`，直接从 package.json 里取

**Comment by KochiyaOcean** [comment]
@alvin-777 考虑到有不在 npm 上发布的插件，这些信息仍然应该保留（不过可以考虑优先从 package.json 获取
