### ISSUE TITLE
[Bug] 十分迷离的任务计数

### ISSUE THREAD

**Issue by wafer-li** [poooi/poi#867]
Electron v0.36.9 win32-x64
poi's version: at this commit 949fed40c8579d0a3769cae0738a2e0eab3bb210

如图

![qq 20160303125535](https://cloud.githubusercontent.com/assets/12459199/13484230/487d503c-e13f-11e5-92ef-60bff080902c.png)

同一台电脑。
今天刚开电脑做这个任务。

**Comment by Wafer-Li** [comment]
貌似只有这个任务有这种现象

**Comment by JenningsWu** [comment]
@Wafer-Li devTool 里有 error 么

**Comment by Wafer-Li** [comment]
有这么一条

```
Failed to load resource: the server responded with a status of 404 (Not Found)
http://125.6.187.205/kcs/sound/kclitugbpkilsf/6.mp3 
```

**Comment by KagamiChan** [comment]
同样情况。这个任务计数只到 2/10

那个 404 的错误是秘书通知的。我这边开了 debug 模式，也没有什么相关错误提示，除了 poi-plugin-report 连不上服务器……

**Comment by yukixz** [comment]
We may need to revert #854.
cc @sage417

**Comment by alvin-777** [comment]
![image](https://cloud.githubusercontent.com/assets/13615512/13488282/f11214fe-e16b-11e5-9550-f62d445f633f.png)
![image](https://cloud.githubusercontent.com/assets/13615512/13488305/1b655478-e16c-11e5-9066-47e1e6f0b050.png)

各种炸。。重启之后依然炸

**Comment by KagamiChan** [comment]
我这边 10 回远征也在炸 - -

**Comment by KochiyaOcean** [comment]
说实话我这里没有爆炸诶

**Comment by Wafer-Li** [comment]
看了一下，应该没什么问题了。
