### ISSUE TITLE
插件系统的重构 - i18n 规范

### ISSUE THREAD

**Issue by dkwingsmt** [poooi/poi#868]
- 要求所有插件的 i18n 文件放在 插件根目录的``i18n``文件下，或者在 package.json 中的指定字段中设定。
- 两个规定字段：
 - key 为 package.json.``poi-plugin``.``name`` 的内容，用于本体的插件列表中显示的名字
 - key 为 package.json.``poi-plugin``.``description`` 的内容，用于本体的插件列表中显示的说明
- 这两个字段将会被本体读取，用于插件列表中的显示。

例如
```js
// package.json
{
  "poi-plugin": 
  {
    "name": "Item Info",
    "description": "List your items"
  }
}
```
```js
// i18n
{
  "Item Info": "装备信息",
  "List your items": "显示你的所有装备"
}
```

**Comment by KagamiChan** [comment]
关于第二点的规定字段
意思是 `module.exports` 中不再有 `displayName` 和 `description` 了吗，如果还有的话，我觉得这两个字段的 i18n 还是交给插件作者自行决定

**Comment by dkwingsmt** [comment]
没有了。我们现在正在商讨的是，在插件 disable 的时候，不需要 require 插件，就能够获取到足够的信息。

**Comment by KagamiChan** [comment]
哦，这样，了解了

**Comment by KagamiChan** [comment]
关于字段名，也许用驼峰会更自然一些？`__pluginName` 这样的

**Comment by dkwingsmt** [comment]
根据 https://github.com/poooi/poi/issues/869 修改了 key 规范
