### ISSUE TITLE
插件系统的重构 - package.json 规范

### ISSUE THREAD

**Issue by dkwingsmt** [poooi/poi#869]
__注意：本 issue 中的所有信息都在讨论中。随时可能变动。__

- ``author``字段，要求按照 npm 的要求，至少提供 ``name`` 和 ``url`` 两个字段，即
```js
{
  "name" : "Barney Rubble",
  "url" : "http://barnyrubble.tumblr.com/"
}
```
- 额外的 poi 专用字段。
 - 在 package.json 中使用一个额外的字段（暂定为``poi-plugin``）用于放置 poi 所需要的信息和选项。
 - 暂定的下属结构为
```js
{
  "name": "Item Info",            // Readable English name。用于 Fallback 和 i18n 字段
  "description": "List all your items" // Readable English description。用于 Fallback 和 i18n 字段
  "icon": "blah"或"fa/blah",      // 用于插件列表中的图标。字符串中没有"/"时默认为 FontAwesome
  "earlist-compatible-main": "5.2.0", // 用于与主体的兼容性检查
  "last-api-ver": "1.4.1",        // 在不兼容的时候提供的回滚功能
  "i18n-dir": "blah/i18n",        // 可选的 i18n 目录自定义，要求这个目录存放带有#868所述字段
  "priority": 100,
}
```

**Comment by dkwingsmt** [comment]
兼容性检查相关字段放在 package.json 的原因是，不兼容的时候很可能无法成功 require。

**Comment by KochiyaOcean** [comment]
name 也一并暴露出来好了

**Comment by dkwingsmt** [comment]
加入 i18n 目录自定义的原因是欧选提到可能有插件存有多个 i18n 系列的情况。

**Comment by dkwingsmt** [comment]
添加了 name 和 description 字段。考虑到
- 不应要求所有插件都使用 i18n 模块（怎么都还是需要吧……）
- 在添加新语言的时候应该 fallback 到一个 readable name 而不是 ``__poiplugin_name``这种无意义字段
因此添加这两个字段，并且用于 i18n 规范的 key。
https://github.com/poooi/poi/issues/868

**Comment by dkwingsmt** [comment]
规范化了 icon 的格式。``"fa/blah"``的格式来自于 https://github.com/gorangajic/react-icons ，以便于扩展到别的图标库，虽然现在还没有支持。

**Comment by KagamiChan** [comment]
要不要考虑到某些作者就是喜欢自己画一个图标的情况

**Comment by dkwingsmt** [comment]
现在还没有这种情况。以后有这种情况的时候 icon 字段的名字还可以扩展。等 issue 吧。

**Comment by dkwingsmt** [comment]
https://github.com/poooi/poi/commit/482a25fcbb542dd1fca0f9e8eda670a5d4e627d4 实现了这个接口（虽然有些问题）。

在这之后，接口应该修改的部分：
- ``poi-plugin``下的``name`` 修改为``title``。这样，“name”这个术语只用于 packageName，避免歧义。
- 包括``poi-plugin``及其下的字段都改为驼峰式，以于 package.json 的其它部分一致，并且便于 js 访问。

**Comment by KochiyaOcean** [comment]
@dkwingsmt 这样处理好了：packageName 为 npm 式的包名，name 为 packageName 的驼峰化

**Comment by dkwingsmt** [comment]
@KochiyaOcean 如果你觉得有必要保留一个驼峰化的名字的话（另外去掉开头的 poi-plugin-）。从 config 格式的统一性来说确实更好看，不过并不是特别必要？

**Comment by KochiyaOcean** [comment]
@dkwingsmt 那就直接把 packageName 改成 name 吧

**Comment by dkwingsmt** [comment]
@KochiyaOcean 我是这么想的。不过这个处理起来不着急（而且需要小心），等稳定下来之后再改好了。

**Comment by KochiyaOcean** [comment]
应增加一个 `priority`
