### ISSUE TITLE
战果插件的“点击查看本月战果功能”不能智能地关闭

### ISSUE THREAD

**Issue by bobjiang6** [poooi/poi#871]
在切换到其他插件标签卡之后，这个功能的小标签仍然存在并遮挡界面
不知道这是什么的的用户可能会受到困扰

**Comment by KochiyaOcean** [comment]
和 `OverlayTrigger` 的触发机制有关。
可以考虑改成 `Overlay` 并手动控制其触发
cc @ruiii

**Comment by yukixz** [comment]
cc @Ayaphis

**Comment by ruiii** [comment]
- -没看到 @ 
下个版本修
