### ISSUE TITLE
演习月常C08计数可能未正常重置

### ISSUE THREAD

**Issue by FXuZ** [poooi/poi#872]
演习月常任务C08, 虽然是月常但是要求一天之内打赢7场演习, 所以应该也需要每天重置计数, 不过今天发现它的显示有问题... 最近的操作是这样的:
- 第一天, 完成5次, 显示5/7, 鼠标指上去也是显示5/7
- 第二天, 完成2次, 显示1/7, 但是本人没注意更多, 2次完成的判断来自于演习胜利日常任务C03的计数
- 第三天, 无论胜利几次, 面板都是显示0/7, 但是鼠标指上去会显示完成7/7

目测可能是计数器没有每天重置..?
怀疑和#867 是同一个...

**Comment by Ayaphis** [comment]
你的poi版本？

**Comment by FXuZ** [comment]
git的master...

**Comment by alvin-777** [comment]
This is a duplicate of #780 and #867
