### ISSUE TITLE
发现好像不能在FLASH里面输入？

### ISSUE THREAD

**Issue by djj200504001** [poooi/poi#873]
发现舰队名字和个人签名都改不了。
是electron的falsh插件的限制么？还是poi的问题？

**Comment by Glaceon-Hyy** [comment]
你是用的token直连吗？token模式下改不了舰队名和个人签名

**Comment by alvin-777** [comment]
与你的链接方式有关，跟poi无关

**Comment by Ayaphis** [comment]
某些代理设置也可能导致这种现象，与poi无关
