### ISSUE TITLE
插件管理的 i18n 炸了

### ISSUE THREAD

**Issue by Wafer-Li** [poooi/poi#879]
Electron v0.36.9 darwin-x64
commit SHA: 947246281d4e01659465c850d572f7afe825fcd1

嗯。

<img width="792" alt="2016-03-06 02 47 38" src="https://cloud.githubusercontent.com/assets/12459199/13549308/eaf25d8c-e345-11e5-850e-af86cfbadd12.png">

**Comment by KochiyaOcean** [comment]
刚才的一个关于插件重构的 pull request 使得它与旧插件不兼容了。
https://github.com/poooi/poi/pull/878#issuecomment-192685858
这里有修改过的插件

**Comment by Wafer-Li** [comment]
那我还是等等。
直接下 NPM 的好了。

**Comment by KochiyaOcean** [comment]
npm 考虑到与旧版的兼容不会立即更新的

**Comment by Wafer-Li** [comment]
OK. I see.
