### ISSUE TITLE
艦娘「建造」艦隊強化！ 0/4

### ISSUE THREAD

**Issue by taroxd** [poooi/poi#880]
After updating the task panel, I am getting `艦娘「建造」艦隊強化！ 0/4` from it, which should have been `艦娘「建造」艦隊強化！ 1/4`

/cc @sage417

**Comment by KagamiChan** [comment]
seems working for me, for information, my first construction was large, though

```
PS D:\Projects\poi> git log -1
commit 947246281d4e01659465c850d572f7afe825fcd1
Merge: 08fad8a 4529a0b
Author: KochiyaOcean <root@kochiyaocean.org>
Date:   Sun Mar 6 01:03:38 2016 +0800

    Merge pull request #876 from sage417/patch-3

    Update task-panel.cjsx
PS D:\Projects\poi>
```

**Comment by taroxd** [comment]
My first construction was large, also.
I am sure I have not touched any file under `%APPDATA%/poi`.

**Comment by KagamiChan** [comment]
Off topic, but I got Musashi for that construction

**Comment by sage417** [comment]
more details please?

**Comment by taroxd** [comment]
I wish I could offer more details. :(

Maybe (I am not sure) I restarted poi after accepting the quest when I am testing the plugin.

**Comment by KagamiChan** [comment]
It seems to me a bug related to the dispayed position on quest panel. Today the same problem happened on my 10-expedition quest. I'll take screenshots next time I notify it.

![image](https://cloud.githubusercontent.com/assets/3816900/13594356/ae83d54c-e53e-11e5-9b82-53ea177f79b4.png)

**Comment by KagamiChan** [comment]
Well, quest positions keep changing because of completion and activation, so my idea may be totally wrong.
But there must be something that blocks the counter update.
![image](https://cloud.githubusercontent.com/assets/3816900/13594441/66f641aa-e53f-11e5-881e-ce015e9db41b.png)

Let's wait for other report.

**Comment by KagamiChan** [comment]
I'm sorry. For today's report, I've switched to another PC but forgot to pull the latest master. So it might be the bug that has been fixed.

**Comment by taroxd** [comment]
The problem recurred. I have not restarted `poi` this time, and the bug seems even more weird.

![qq 20160309061850](https://cloud.githubusercontent.com/assets/6070540/13618395/d6d73680-e5be-11e5-920d-71fd81775163.png)

![qq 20160309062122](https://cloud.githubusercontent.com/assets/6070540/13618464/2c4a8248-e5bf-11e5-941e-d8cd3eb3226e.png)

**Comment by sage417** [comment]
I have found sth. cause this problem. I will fix it
> After updating the task panel, I am getting 艦娘「建造」艦隊強化！ 0/4 from it, which should have been 艦娘「建造」艦隊強化！ 1/4

**Comment by sage417** [comment]
This problem has been fixed by #876 

> The problem recurred. I have not restarted poi this time, and the bug seems even more weird.

>I was using an older version today and the bug may have been fixed. I have updated to beta.0 now and am ready to test again tomorrow.

**Comment by sage417** [comment]
quest counter should be reseted to it's init value not zero.

**Comment by KagamiChan** [comment]
Will this bug also prevent counter being updated?
I noticed my operation A-go counter broke. I switched to this PC in the morning, It was 50% then and now 80%. I've already updated to latest master, but not applied your patch at sage417/poi 
![image](https://cloud.githubusercontent.com/assets/3816900/13667988/89cb11f4-e6f4-11e5-9a61-e577c6c100ef.png)
![image](https://cloud.githubusercontent.com/assets/3816900/13667994/934084c6-e6f4-11e5-8d35-246dd1dffbbb.png)

**Comment by KagamiChan** [comment]
I realize that the treatment for A-go is a different, and it has worked like this before. So it is not related.
