### ISSUE TITLE
无法调整窗口大小

### ISSUE THREAD

**Issue by Absolutero** [poooi/poi#882]
win10
画面下方的按钮里面找不到锁定窗口大小的按钮。。。展开了也找不到。。。。
![image](https://cloud.githubusercontent.com/assets/17703271/13569908/e3f30f84-e4a5-11e5-8b5a-0d66a2edaf13.png)

**Comment by KochiyaOcean** [comment]
@Absolutero 按 alt，poi-允许窗口大小变更

**Comment by Absolutero** [comment]
已解决，谢谢菊苣！
