### ISSUE TITLE
Remove network retry setting

### ISSUE THREAD

**Issue by yukixz** [poooi/poi#887]
poi 的网络重试功能是直接重发包、很危险。
我认为应当移除，将防猫功能交给专业的代理。

~~考虑到某个不具名的欧选需要网络重试，~~
~~可以把这个功能改成隐藏功能。~~

~~所以我提出以下方案：~~
~~1. 设置界面移除网络重试的设置。~~
~~2. 使用 `config.get('proxy.retries')` 代替 `config.get('poi.proxy.retries')`，从而重置此设置。~~

**Comment by KochiyaOcean** [comment]
@yukixz 不不不去年 6 月的时候是我最先提出要移除的啊

**Comment by yukixz** [comment]
我上次 tg 问你要不要删掉你又说你要用=。=

**Comment by yukixz** [comment]
修改方案、直接删掉网络重试

**Comment by dkwingsmt** [comment]
@yukixz 反对，我也需要，并且我遇到过不少人咨询这个问题，证明他们也需要。

**Comment by yukixz** [comment]
sink your ships as you wish.
