### ISSUE TITLE
Display issue in macbook pro 13'

### ISSUE THREAD

**Issue by ganyifan1121** [poooi/poi#891]
在OSX版本下如何调整主窗口和右边窗口的比例？
现在左边画面比网页版看起来更大，但是右边的边栏有些字压缩到看不见了。。

**Comment by KochiyaOcean** [comment]
现在的横版布局策略改为由窗口高度决定 webview 大小了。

**Comment by ganyifan1121** [comment]
实际左边的内容大小没有太大关系。问题是右边边栏的左下角的内容缩在一起，有些内容看不见，改变窗口大小也不能解决这个问题。

![image](https://cloud.githubusercontent.com/assets/3349258/13768014/9612fce6-ea47-11e5-9b13-8e627677ba77.png)

**Comment by KochiyaOcean** [comment]
如果不是固定分辨率的话左边内容的高度由窗口高度决定，然后横向:纵向比例是5:3，所以会占据右边空间的内容。
所以方案有三种：增加窗口的横向大小或者减小窗口的纵向大小，或者使用固定分辨率

**Comment by ganyifan1121** [comment]
谢谢！已经解决问题。

![image](https://cloud.githubusercontent.com/assets/3349258/13768125/ba27f342-ea48-11e5-9643-669dec0d272d.png)

显示设置中去掉分辨率自动调整后解决了。
