### ISSUE TITLE
两个BB出击6-1，不计入任务统计的BUG

### ISSUE THREAD

**Issue by fzzf-akari** [poooi/poi#894]
A号作战，36次出击。只要出击就算一次。所以最省事的就算2BB出击6-1，直接沟回家，算一次出击但无任何消耗。但是我发现poi没有把这样的出击计入A号的统计里面

**Comment by KochiyaOcean** [comment]
现在的机制是第一次战斗之后才结算あ号的出击。

**Comment by fzzf-akari** [comment]
比如昨天我做A号的时候。补给24个做完了，这时候任务统计是71/78，然后我2BB出击6-1，出击7次后还是显示71/78。但是这时候我打开任务面板发现A号已经完成了

**Comment by KochiyaOcean** [comment]
唔现在不清楚出门猫是否算作计数……姑且认为算好了

**Comment by fzzf-akari** [comment]
不是猫，就是钻了带路机制的空子，出门直接拐到一个空的沟里回家。这是肯定算一次出击的，我经常这样做

**Comment by KochiyaOcean** [comment]
不，我的意思是说猫是否应该加入计数，这和代码将如何修改有关
