### ISSUE TITLE
能不能求授权图标资源的使用权

### ISSUE THREAD

**Issue by Gizeta** [poooi/poi#897]
这里是舰娘百科，目前有个开发[安卓端app](https://github.com/YubariNavalArsenal/Akashi_Toolkit)的计划。
请问能不能求一份图标资源在app上的使用授权？

@edwardaaaa

**Comment by edwardaaaa** [comment]
@Chibaheit@taroxd@yukixz@JenningsWu@dkwingsmt@alvin-777@KochiyaOcean@magicae(不分先后）
还有其他开发组dalao不一一@了。

各位好，舰娘百科的开发组成员申请授权使用高清图标，考虑到POI和舰娘百科之间无论是数据上还是微博上，都在互相共享扶持，因此我决定同意此issue所提说权申请。但是我仍旧希望参考下开发组dalao的想法，欢迎各位不吝赐教~

**Comment by KochiyaOcean** [comment]
@edwardaaaa 我认为没什么问题啦~

**Comment by Gizeta** [comment]
@edwardaaaa 
非常感谢。

如果没有dalao有疑问的话，稍后就close掉。

**Comment by magicae** [comment]
没有问题
