### ISSUE TITLE
装备「特二式内火艇」的类型图标为新图标

### ISSUE THREAD

**Issue by yukixz** [poooi/poi#901]
需要更新图标。

* [x] 从 swf 中提取新图标到 `./assets/img/slotitem/`
* [x] 需绘制对应的高清图标

**Comment by yukixz** [comment]
cc @@edwardaaaa

**Comment by edwardaaaa** [comment]
已完成新图标，编号: 36
[36.svg.zip](https://github.com/poooi/poi/files/180825/36.svg.zip)
@yukixz

**Comment by KochiyaOcean** [comment]
@edwardaaaa 太快了！感谢

**Comment by edwardaaaa** [comment]
@KochiyaOcean 你这回复更快。。。做的时间短，难免粗糙。。。

**Comment by yukixz** [comment]
@edwardaaaa 讲道理、你们单身多少年了

**Comment by taroxd** [comment]
@yukixz 19年
