### ISSUE TITLE
把插件更新通知独立出来？三态通知？

### ISSUE THREAD

**Issue by dkwingsmt** [poooi/poi#912]
现在有人想要屏蔽插件更新通知的话就会屏蔽掉所有的插件通知，就很无奈。

以及把通知做成三态的，
- 气泡+声音
- 气泡
- 无

因为有较多人反映刚打开 poi 时的“语音”比较恼人。

**Comment by KochiyaOcean** [comment]
@dkwingsmt 有隐藏选项，直接做成设置项目就行了

**Comment by yukixz** [comment]
@dkwingsmt 声音调到 0 就是屏蔽声音了

**Comment by dkwingsmt** [comment]
@yukixz 那就屏蔽掉所有声音了
