### ISSUE TITLE
更新后，横版布局右侧面板的显示问题

### ISSUE THREAD

**Issue by otoha9** [poooi/poi#914]
更新6.0.1版本之后，使用横版布局时，右侧面板的文字显示不全，放大右侧面板文字大小也会一同变化。
实际上这个问题从5.2.0版本就有了。
![qq 20160322183330](https://cloud.githubusercontent.com/assets/18004791/13948994/05302b50-f05e-11e5-9539-92ea66076fb5.png)
![qq 20160322183402](https://cloud.githubusercontent.com/assets/18004791/13948995/0536327a-f05e-11e5-87dd-0dc5e721e951.png)

**Comment by yukixz** [comment]
拉宽一点
