### ISSUE TITLE
還是航海日誌的問題

### ISSUE THREAD

**Issue by FungJiHsu** [poooi/poi#916]
重啟POI后，導入的記錄不見

https://github.com/poooi/poi/issues/906在這個問題后，我導入之前的記錄（不過之後的記錄是正常的）
昨天已經發現沒有導入記錄，以為手誤沒弄進去
今天還這樣
![qq 20160323132002](https://cloud.githubusercontent.com/assets/14539399/13976583/12bf2174-f0fc-11e5-8123-f01798258979.png)
插件文件夾下面，有這問題之後以日期為名生成的文件，會不會因為沒有生成導入記錄相關才這樣

**Comment by JenningsWu** [comment]
加自定义数据路径的设置的时候没改导入模块这里的路径
一会儿发 4.1.2-beta.0…

**Comment by JenningsWu** [comment]
哦对，你可以去 %APPDATA% 那个老目录下把记录复制到自定义的那个新目录下（

**Comment by FungJiHsu** [comment]
@JenningsWu 老目錄下的我刪了....我等4.1.2吧

**Comment by JenningsWu** [comment]
@FungJiHsu 如果是导入之前删的话那现在还有

**Comment by FungJiHsu** [comment]
@JenningsWu 是還在，搬過去之後OK
