### ISSUE TITLE
poi里面提督没登入

### ISSUE THREAD

**Issue by rachel123456** [poooi/poi#918]
![default](https://cloud.githubusercontent.com/assets/18074672/14050189/34dd594c-f2f5-11e5-9fcf-b0353dd8ae2d.png)
就如图所示
poi里面显示没登入

**Comment by KochiyaOcean** [comment]
打开左下角的开发者工具
输入 `delete localStorage._teitokuExp` 然后回车试试看

**Comment by yukixz** [comment]
代理设置 - 本地端口填 0

**Comment by rachel123456** [comment]
请问在哪输入

**Comment by KochiyaOcean** [comment]
![image](https://cloud.githubusercontent.com/assets/8194131/14050281/c9d37aae-f2f5-11e5-88fe-c188668b0d77.png)
左键左下角那个齿轮

**Comment by rachel123456** [comment]
行了谢谢
