### ISSUE TITLE
岛风GO适配延迟的解决方案

### ISSUE THREAD

**Issue by q767939287** [poooi/poi#919]
经过测试可以添加HOST 到达秒适配窗口，如下：127.0.0.1 www.googletagmanager.com

**Comment by DSakura1987** [comment]
@q767939287 这是国内封了谷歌的缘故吧，ping一下这个网址看看是不是timed out。

**Comment by KochiyaOcean** [comment]
并没有权限向 host 写东西的说……
说到底还是由于某个看似代理的东西不愿意代理页面上的全部内容导致网页加载超时嘛_(:3」∠)_

**Comment by DSakura1987** [comment]
岛风狗是一个超选择性的代理，只代理到KC服务器的资源，所以这问题可以关了？HOSTS是需要管理员权限才能更改的文件（笑

**Comment by yukixz** [comment]
这个域名的处理应该交给自称神的开发者在他的垃圾代理里面实现。

**Comment by c933103** [comment]
可否在偵察到部分頁面內容不能加載時彈窗提醒由於網絡連線原因導致部分內容適配延遲建議用戶切換連線工具以改善體驗？
2016/04/05 16:20 "Dazzy Ding" <notifications@github.com>:

**Comment by DSakura1987** [comment]
@c933103 这个问题是connection timed out导致的，而不是connection refused，所以必须等底层返回才行，要加入不少延时判断（

**Comment by KochiyaOcean** [comment]
https://github.com/poooi/poi/commit/c94460e07f516f7709aa498f26edc4f5043a712d 重构地址栏把停止加载丢进来了，大概可以算 fixed？
