### ISSUE TITLE
提供禁用GPU硬件加速的方式

### ISSUE THREAD

**Issue by maonickbob** [poooi/poi#92]
因为发现你这个用的是chrome的内核，所有有个特有的”开启硬件加速的功能“，这个功能一直以来都有问题，在高配的电脑上是没问题的，但是某些低配电脑开启后会有奇怪的问题，卡屏，只有调整窗口大小才能恢复一小会儿，之后再点点其他的又卡住了，希望是能像chrome一样有个选项能去掉这个硬件加速的功能，或者默认不开启。。。我在海色论坛@你了但是你一直没出现。对这个软件非常感兴趣啊，希望大佬能越做越好！

**Comment by magicae** [comment]
是指Flash卡住了吗 还是整个软件卡住了

**Comment by magicae** [comment]
你用的什么操作系统 会用命令行吗 在群里吗 需要你来试验一下

**Comment by maonickbob** [comment]
是整个窗口卡了，假死一样，但是调整一下窗口会好，但一用插件就又是这个问题，肯定是那个硬件加速的问题，如果需要的话可以录个视频什么的给你，看下是什么情况。。

**Comment by magicae** [comment]
嗯 cmd

**Comment by maonickbob** [comment]
cmd我会用额，这个修复了么？

**Comment by magicae** [comment]
你用cmd开poi
poi.exe --disable-gpu --disable-gpu-compositing
试试这两个参数

**Comment by maonickbob** [comment]
OK了，用了--disable-gpu这个参数就好了，但是这样每次开都要打这个参数好麻烦，能不能添加选项去掉？

**Comment by magicae** [comment]
嗯 以后设置里可以加一项这个
目前先用--disable-gpu解决吧

**Comment by KochiyaOcean** [comment]
Fixed by https://github.com/poooi/poi/commit/17ea6d209931e1426e7250c464f34be1108e4f4f
