### ISSUE TITLE
Rending issues with remotefx v-gpu

### ISSUE THREAD

**Issue by mic4126** [poooi/poi#922]
![14](https://cloud.githubusercontent.com/assets/4671533/14145659/355bc068-f6c7-11e5-9107-21fbb8e3663c.png)
As seen in the screencap above the rending issue occur when using remotefx v-gpu driver
![15](https://cloud.githubusercontent.com/assets/4671533/14145722/712fec5e-f6c7-11e5-9d3f-7b00270805cc.png)
The bug happen in chrome and firefox as well but can be fixed by disabling the hardware acceleration.
https://bugs.chromium.org/p/chromium/issues/detail?id=529658
I have disabled the hardware acceleration feature and reopen for a few times but still have the problem same as the feature on show in screencap.

**Comment by yukixz** [comment]
The 'disable hardware acceleration' option of poi takes the same effect as `--disable-gpu` command line options of chrome.

**Comment by KochiyaOcean** [comment]
Is `/path/to/poi.exe --disable-gpu` command takes effect?

**Comment by mic4126** [comment]
The --disable-gpu option works
but the poi show the --disable-gpu is an invalid  argument
![16](https://cloud.githubusercontent.com/assets/4671533/14149644/b3c0c86c-f6d7-11e5-89a1-93f582020ae7.png)

**Comment by alvin-777** [comment]
emmm, you can ignore that message...

**Comment by mic4126** [comment]
Well,after i test a few time more.
I may conclude that the --disable-gpu option works but the button in the option to disable hardware acceleration seem have no effect on poi behavior. So Is this a new problem?

**Comment by KochiyaOcean** [comment]
Yes, maybe the only solution is remove it lol
