### ISSUE TITLE
Plugin missing after reopen if %appdata% is an unc path

### ISSUE THREAD

**Issue by mic4126** [poooi/poi#925]
Well is me aging.
This time i find that plugin will not load in at startup if the %appdata% path is pointed to another server.
To use plugin i have to install them aging every i start poi.
Checked the plugin folder and i have full control to the folder.
I have record a video about this problem. Do you want to have a look?
To sum up , installed plugin will disappear after poi restart but i can use plugin if  i install them aging.

**Comment by JenningsWu** [comment]
> if the %appdata% path is pointed to another server.

In fact I don't know what does it mean… Could you plz provide more details about "another server" ?

**Comment by mic4126** [comment]
it is a smb file server which is where %appdata% pointed
2016年4月2日 12:12 於 "Jennings Wu" <notifications@github.com> 寫道：

**Comment by DSakura1987** [comment]
I guess you made a symbolic link pointed to the unc path? It is known that only cmd.exe can run an executable file while others wont. Maybe something similar happened here. 
If possible, please post more details, such as how you set %appdata% and the permission of the share for guest user.

**Comment by mic4126** [comment]
I set the %appdata% path by using folder redirection which change the appdata to a unc path so that I can sign in into any computer in the same domain and use the same setting.
About the permission and owner stuff, I have run the command "takeown /R /F .\poi" and
"icacls .\poi /grant username:F /T" at appdata folder and problem still exist.
I think poi can access to the %appdata%\poi folder as poi can load the cookie and enter kancolle without login aging.
https://en.wikipedia.org/wiki/Folder_redirection
https://technet.microsoft.com/en-us/library/cc732275.aspx
https://support.microsoft.com/en-us/kb/232692

**Comment by mic4126** [comment]
Try run as admin still fail 
OS Windows 8.1 x64 Enterprise
poi version : v6.13 x64

**Comment by DSakura1987** [comment]
It looks like a permission issue, or an implementation issue in OS...
Did poi need to cache file each time when it starts? If so, please try grant permission by "icacls .\poi /grant username:(OI)(CI)F /T". 
If it is not working, could you please try rename poi folder then restart poi and install plugins? If the problem still exists, it looks like an implementation issue in OS.

**Comment by mic4126** [comment]
No "icacls .\poi /grant username:(OI)(CI)F /T".  does not work
renaming folder does not work either.

**Comment by DSakura1987** [comment]
I think it is an issue in your environment, not poi. 
Currently I cannot repo the issue since I did not have a domain environment to test, but since renaming does not work, I think it is in your environment.
Let's give it last try - start poi with -d argument, and post the log. Hope it will give something new.

**Comment by mic4126** [comment]
Where can i find the log?

**Comment by KochiyaOcean** [comment]
@mic4126 Run poi on cmd or powershell then you can see the log

**Comment by mic4126** [comment]
ok it is in stdout.

**Comment by mic4126** [comment]
https://na.cx/i/QJ4D93.png

**Comment by DSakura1987** [comment]
Can you please not redirect stdout? Maybe there is some information.
I notice you are using traditional Chinese, right? Could you please check:
1) Did you use a Chinese user name?
2) Did you profile path include Chinese? (check by type "echo %USERPROFILE%" in cmd window)
Thank you!

**Comment by mic4126** [comment]
1) no
2)no
the echo %appdata% is \\server\folder-redirection\michael\appdata
I fix the issues move disable appdata folder redirection
I think using %localappdata% variable instead of %appdata% on windows vista or above would be a easy fix . 
sorry for my very late reply. because I am having public exam last month
