### ISSUE TITLE
2016/4/1游戏更新导致的问题

### ISSUE THREAD

**Issue by einbrain** [poooi/poi#933]
1. 4/1更新导致poi无法读取部分游戏数据
    - 可以看到当前资源数，提督名称等级等信息，舰娘数，远征，任务，入渠，建造（包括剩余时间）
    - 不能看到装备数，舰队构成
2. 同时信息栏UI出现不能正常换页的问题。（当前页锁死？）

**Comment by yukixz** [comment]
Fixed by #931
