### ISSUE TITLE
是否能將UI下面"獲得數據xxxx"不顯示

### ISSUE THREAD

**Issue by bassercat** [poooi/poi#935]
如題
因艦娘百科字幕上架
及poi內建tip
甚至建造開發
很容易被此擋住 必須一直手動點開歷史來看
是否有方法讓"獲得數據xxxx"不顯示

另改版poi人員辛苦了 感謝

**Comment by DSakura1987** [comment]
建议把“获得数据XXX”独立成一个debug插件，然后把debug功能都放到这里边
不过好像要不少代码重构的样子……

**Comment by yukixz** [comment]
新 增 选 项 不 可 避

**Comment by dkwingsmt** [comment]
我觉得确实可以直接关了……确实没用……DEBUG再开

**Comment by taroxd** [comment]
我希望留着。游戏卡在「战斗开始」的时候，我希望看到是收包失败还是立绘没下载好。前者我会立刻F5，后者我会等
