### ISSUE TITLE
[6.1.0] App Not Responding

### ISSUE THREAD

**Issue by wafer-li** [poooi/poi#938]
Electron v0.37.3 win32-x64
Win 10 Pro x64

The whole app is not responding. 
It just stuck, only **force close** will work.

![qq 20160402003221](https://cloud.githubusercontent.com/assets/12459199/14211758/bd3d5c04-f86a-11e5-9a46-6d64dacb133a.png)

**Comment by EdiTurn** [comment]
同样的问题，同时还伴随着 CPU 满载和内存泄露

**Comment by KochiyaOcean** [comment]
真是遗憾…… Electron 还是使用旧版本吧
