### ISSUE TITLE
6.1.1及6.1.2在調整視窗大小時會crash

### ISSUE THREAD

**Issue by as1234884** [poooi/poi#941]
如題，6.1.2開啟時正常，在用滑鼠調整視窗大小時會卡死，沒辦法點擊任何東西
向下測試，6.1.1也與6.1.2有同樣的問題，但是多了個記憶體洩漏的問題
追加：不只用滑鼠，使用設定裡面的顯示設定調整時會有同樣問題

**Comment by JenningsWu** [comment]
@as1234884 操作系统版本，以及用的 poi 具体的版本（64/32位）是？

**Comment by JenningsWu** [comment]
@as1234884 唔，另外确认一下，在用 6.1.1 和 6.1.2 的时候，是下下来直接用，不是粘贴覆盖之前的文件吧？

**Comment by as1234884** [comment]
OS：WIN7 64bit
POI Version：poi-v6.1.2-win32-x64、poi-v6.1.1-win32-x64

**Comment by as1234884** [comment]
@JenningsWu 另外又以上述四個版本進行測試，刪除舊資料外又清除cookie及快取，還是有相同問題

**Comment by JenningsWu** [comment]
@as1234884 1. 是否方便发一份你的配置文件？在 %APPDATA%/poi 下，名为 config.cson
2. 开一下 devtool （按游戏窗口 左下角锯齿按钮）看看有没有红色 error，以及调整窗口， 卡死时，是否出现 error？
3. 在卡死时，CPU  占用率是否正常？

**Comment by as1234884** [comment]
@JenningsWu 以四個版本開啟devtool進行確認，卡死前後皆沒有報Error
                        同上述四個版本，在卡死時皆出現記憶體洩漏問題
另外附上onfig.cson

**Comment by JenningsWu** [comment]
@as1234884 config.cson  好像没发上来？

**Comment by as1234884** [comment]
@JenningsWu 不好意思我無法在這裡上傳，另外以MEGA上傳給您

[https://mega.nz/#!DgogjLwA](url)

**Comment by JenningsWu** [comment]
@as1234884 下载要求输入解密密钥

**Comment by as1234884** [comment]
@JenningsWu 已經在上面回復串附上為不用解密密要的網址，麻煩您重新進入

**Comment by as1234884** [comment]
@JenningsWu 剛剛又測試了一下，發現devtool中的html欄位的webkit-text-size-adjust: 100%;會出現unkown property name

接著改變視窗大小後就記憶體洩漏了，devtool只有同樣的訊息，再開一次的話會直接crash，除非刪除appdata的poi資料夾

**Comment by JenningsWu** [comment]
Fixed by 9dd97be
