### ISSUE TITLE
界面显示BUG了

### ISSUE THREAD

**Issue by asdiuy** [poooi/poi#943]
![qq 20160402111600](https://cloud.githubusercontent.com/assets/18224457/14224134/621adcb6-f8c4-11e5-9ca2-845f938270c9.png)
![qq 20160402111616](https://cloud.githubusercontent.com/assets/18224457/14224135/6270778e-f8c4-11e5-9a49-1566a6c854d2.png)
![qq 20160402111632](https://cloud.githubusercontent.com/assets/18224457/14224136/63a0e49a-f8c4-11e5-8f8c-8d240eab0fe4.png)
只有概览可以看。显示也有一点问题。是我设置问题还是？

**Comment by JenningsWu** [comment]
是否是 6.1.0 及之后的版本？
娇喘改 api 了，之前的都不能用了

**Comment by asdiuy** [comment]
噢，我的6.0.1

**Comment by asdiuy** [comment]
顺带一提6.1在哪下啊

**Comment by KochiyaOcean** [comment]
@asdiuy 看 Github release
