### ISSUE TITLE
OSX 上執行特別慢

### ISSUE THREAD

**Issue by eul721** [poooi/poi#944]
幾乎不能用
ＵＩ按鍵都沒反應

ＣＰＵ用量
![CPU](https://gyazo.com/7bba1c5a3ffa8ddf37a8ee4a4ab6ab22.png)

v6.1.2

**Comment by JenningsWu** [comment]
@eul721 是否已经进入了游戏，还是在游戏登陆页面？

**Comment by eul721** [comment]
@JenningsWu 在母港

**Comment by JenningsWu** [comment]
@eul721 重启一下 poi 试试看，如果直接进入游戏（自动登录），而不经过那个登陆界面的话，是否还会出现相同的问题？

**Comment by eul721** [comment]
@JenningsWu 一樣ＵＩ沒反應 連Electron inspector都會hang

**Comment by JenningsWu** [comment]
@eul721 一会儿会发 6.1.3，到时候换那个版本试试看吧

**Comment by eul721** [comment]
發現用ＤＭＭ官網連就OK了
我平常都是用 ooi.la-foret.me 的暫存系統登入 所以可能是那邊的問題
跟6.1.2應該沒關係

**Comment by JenningsWu** [comment]
ok
