### ISSUE TITLE
任務進度錯誤

### ISSUE THREAD

**Issue by fansteven7** [poooi/poi#945]
**使用版本：**
poi-v6.1.2-win32-x64

**作業系統：**
Win 10 專業版 64位元

**出現問題：**
あ号作戦 任務進度異常
(更新前已經完成80% 61/78 ，更新後顯示為 0/78
其餘任務皆無問題

快取、Cookie都清過
poi更新方法為 晚整移除舊版本 整個重新解壓縮

**截圖：**
![issue_0402](https://cloud.githubusercontent.com/assets/18224761/14224302/dd0903ca-f8ca-11e5-81ea-b8c345fdb93e.png)

**Comment by KochiyaOcean** [comment]
@fansteven7 更新了使用新 API 的版本后将无法使用更新之前的任务计数记录
