### ISSUE TITLE
改二签名生成器

### ISSUE THREAD

**Issue by Javran** [poooi/poi#948]
KC3开发跑过来say hello/

之前和改二签名生成器 http://threebards.com/kaini/index-cn.php 的作者合作了一下,现在可以通过发POST请求的方法自动填空.想把这个功能推广下,希望大家都能用上.

相关文档这个:
https://github.com/cyrismustang/k2badge/wiki
不知道是否有意向实现?

**Comment by KochiyaOcean** [comment]
很值得考虑，感谢提供资源

**Comment by KochiyaOcean** [comment]
已经完成了，在 poi 里安装 `poi-plugin-k2badge` 即可
代码在 https://github.com/poooi/plugin-k2badge
