### ISSUE TITLE
艦隊裝備顯示及遠征信息時不時顯示錯誤

### ISSUE THREAD

**Issue by renhigashino** [poooi/poi#949]
4月1日更新後，發現poi（使用的是最新的v6.0.1）出現異常，最明顯的包括：
1.替換裝備後，艦隊介面裝備無法更新
2.查看遠征信息插件時無法顯示遠征條件
儘管不是每次打開poi都會出現上述問題，但還是屬經常出現的狀況 #

**Comment by KochiyaOcean** [comment]
@renhigashino 所以更新到 6.1.3 不就行了……
