### ISSUE TITLE
 POI 6.1.3 安装插件 会黑频

### ISSUE THREAD

**Issue by Snownote** [poooi/poi#950]
![image](https://cloud.githubusercontent.com/assets/18033138/14225848/2dbd126e-f904-11e5-974e-2b356f46dc09.png)

![image](https://cloud.githubusercontent.com/assets/18033138/14225849/33493e4c-f904-11e5-9a36-aef0742fff13.png)

**Comment by JenningsWu** [comment]
@Snownote 稳定重现？还是 偶发情况，重启再试的话就没问题了？

**Comment by Snownote** [comment]
稳定重现唷 重开也一样 尝试很多次了。

**Comment by JenningsWu** [comment]
@Snownote 操作系统版本，以及具体所用的 poi 版本（32 或64位）？

**Comment by Snownote** [comment]
OS: Windows7 SP1 旗舰版 64bit

版本 poi-v6.1.3-win32-x64

**Comment by JenningsWu** [comment]
@Snownote 试了下，没有重现…  
1. 能否把 %APPDATA%/poi 下的 config.cson 发过来？
2. 开着 developer tool （ 点击游戏界面左下角齿轮按钮打开）安装插件，看看在黑屏前后 console 里是否会有 error 显示？

**Comment by Snownote** [comment]
config.cson 档案已发过去

按 安装插件 过几秒后 就直接黑频了 没出现 error 显示

**Comment by JenningsWu** [comment]
@Snownote 还是没能重现
是点的“全部安装”么？如果一个一个手动点过去呢？

**Comment by Snownote** [comment]
黑频后 跑出 黑色视窗上面那段文字
![image](https://cloud.githubusercontent.com/assets/18033138/14226228/51629900-f90e-11e5-9e93-a2725129d027.png)


全部安装 或 一个一个手动安装一样 黑频

**Comment by JenningsWu** [comment]
@Snownote 关掉 poi 后，进入 %APPDATA%，将 poi 文件夹重命名为另一个名字（例如 poitemp）。然后打开poi，试试是否仍然安装插件黑屏？

**Comment by Snownote** [comment]
一样黑频

把原POI 改为别的名子后

再打开POI 会产生另一个全新POI资料夹 设定全部都重回预设

不过 安装插件 还是会黑频

**Comment by KochiyaOcean** [comment]
@Snownote 换 32 位版的呢？

**Comment by JenningsWu** [comment]
@Snownote 以及尝试在 设置-扩展程序-高级设置 里更换一个 npm 服务器，然后再试试看？
因为 开发组这边完全没法重现黑屏情况…搞不清楚到底是因为什么，只能尝试下各种可能性了

**Comment by Snownote** [comment]
所有 NPM  都嘗試過了 都繪黑頻 換成32BIT 一樣情況

還是 我把POI  壓縮 整個丟過去給你們檢查??

**Comment by JenningsWu** [comment]
@Snownote poi 的网盘 http://0u0.moe/poi 里 
poi-plugins_2016-4-2.7z  是离线插件包，可以下载下来，解压缩之后，把里面的一堆插件包挨个丢到扩展程序面板那里的 那个框里。看看通过离线插件包的形式安装是否 还会出问题
poi 压缩之后丢过来看看吧…

**Comment by Snownote** [comment]
那我传过去啰

还是一样 变成 卡在 安装中

卡了 15分钟了

![image](https://cloud.githubusercontent.com/assets/18033138/14226446/1b025628-f915-11e5-93d5-3617f9757602.png)

**Comment by JenningsWu** [comment]
@Snownote 重启 poi，打开 Developer Tools，在 console 输入
require("npm").install("poi-plugin-akashic-records")
看一下会有什么结果

**Comment by Snownote** [comment]
![image](https://cloud.githubusercontent.com/assets/18033138/14226528/a921b3b6-f917-11e5-8198-2d9d6a671f15.png)

**Comment by JenningsWu** [comment]
@Snownote require("npm").view("poi-plugin-akashic-records")
这个呢

**Comment by Snownote** [comment]
![image](https://cloud.githubusercontent.com/assets/18033138/14226635/b7ce8252-f919-11e5-9a04-6e17fb04db57.png)

![image](https://cloud.githubusercontent.com/assets/18033138/14226637/c183f98a-f919-11e5-9f78-c67d34cc7381.png)

**Comment by JenningsWu** [comment]
@Snownote 6.0.1 安装插件会黑屏么

**Comment by Snownote** [comment]
![image](https://cloud.githubusercontent.com/assets/18033138/14226688/987f20c6-f91b-11e5-8444-57b91ddb67b9.png)

一样呢 卡住了

**Comment by JenningsWu** [comment]
@Snownote 右键管理员权限运行呢？
如果还是不行的话…就把之前下的那个压缩包里的插件分别解压缩，然后手动放到 %APPDATA%/poi/plugins/node_modules 里去吧…

**Comment by DSakura1987** [comment]
@Snownote 试试在poi的路径里面不用中文，或者新建一个英文用户名的用户再试。
