### ISSUE TITLE
如何得知貓襲代號？

### ISSUE THREAD

**Issue by realredpig** [poooi/poi#955]
剛剛去查了下才知道，碰到201貓還繼續玩就完蛋了

可是該怎麼知道是200貓還是201貓呢？

聽說透過74式可以看，不知道poi有沒有類似的功能？

**Comment by yukixz** [comment]
已实装、等下个版本 #953

**Comment by ibicdlcod** [comment]
有那么可怕？顶着201猫玩了半个月了
