### ISSUE TITLE
移除 bootstrap 主题

### ISSUE THREAD

**Issue by yukixz** [poooi/poi#956]
之前有说到 Bootstrap 主题因为包含了 Google Font、会导致加载 css 文件失败。
然后似乎没下文了、讨论一下？

**Comment by taroxd** [comment]
~~汇报插件顺便汇报一下 config，看看大家用的什么主题吧。虽然我觉得估计没人用 Bootstrap 主题~~

**Comment by DSakura1987** [comment]
问个笨蛋问题，是不是bootstrap主题被ReactBootstrap引用了？或者说默认主题是BootStrap？好像目前的预定义主题都引用了google font

**Comment by KagamiChan** [comment]
看了下原生主题（./node_modules/bootstrap/dist/css/ 里面的）没有 google font 依赖。有依赖的是从bootswatch 上下回来的大部分主题

我个人用 darklykai
感觉很多 bs 主题因为不是为 poi 专门设计的，配色会不够和谐，样式也不够简约，像 darklykai 这样专门优化过的会看起来舒服一点

**Comment by dkwingsmt** [comment]
兹磁移除 bs 自带主题

**Comment by yukixz** [comment]
@dkwingsmt 兹瓷+1

**Comment by dkwingsmt** [comment]
然而就我从微博上收到的汇报来说……还真有不少人用的是白色主题……

**Comment by KagamiChan** [comment]
我记得有一个主要版本的新安装默认主题就是白色的，感觉会有从来不改主题，或者不知道可以改主题的用户……

显示血量可能算是大部分浅色系主题的一个比较尴尬的点吧
![image](https://cloud.githubusercontent.com/assets/3816900/14290737/d87e8166-fb92-11e5-9247-63a6f2e65999.png)

**Comment by DSakura1987** [comment]
下一个版本移除白色主题，并且硬性用黑色主题替代好了（喂

**Comment by yukixz** [comment]
bump

**Comment by dkwingsmt** [comment]
以个人身份表示一下兹磁

**Comment by taroxd** [comment]
@dkwingsmt 依旧资词

**Comment by Javran** [comment]
加些个人想法:

- 主题可能还是保持着,或许已经有用户习惯了,不好改.

- 但在这基础上poi是否能提供一些对游戏里的概念正确的配色: 比如 小破/中破/大破/四项资源 的颜色等等, 个人觉得在一些地方使用primary / warning / error 这样的东西并不符合本意.

- 可以考虑维护两个这样的配色集合,黑色系白色系主题各用一套

- 此外不懂能不能搞个统计调查,白主题如果没多少人用确实就可以移除掉了吧

**Comment by vuryleo** [comment]
为什么不搞点统计呢……

**Comment by yukixz** [comment]
如何获得唯一用户id？

**Comment by vuryleo** [comment]
安装时生成一个？

**Comment by Javran** [comment]
提督id吧

**Comment by DSakura1987** [comment]
用户ID可以hash一下服务器名字和提督ID

**Comment by gnattu** [comment]
Removed
