### ISSUE TITLE
显示设置的窗口分辨率随大小调整在surface上的问题

### ISSUE THREAD

**Issue by bobjiang6** [poooi/poi#958]
surface上设置自动调节窗口大小的时候，我使用右侧边栏，舰队面板的舰船等级和名字都被吞掉了
能不能改一下宽度的设置…至少能看到船名也好吧

**Comment by KochiyaOcean** [comment]
截图？

**Comment by yukixz** [comment]
应该是右边不够宽、然后舰队面板那里名字被覆盖了

**Comment by DSakura1987** [comment]
![image](https://cloud.githubusercontent.com/assets/4421906/14288660/eda52a78-fb14-11e5-8dac-452ee91fa5d5.png)
是不是像这样？的确是右边不够宽，看了一下CSS是这么指定的：
#MiniShip .ship-details-mini .ship-item .ship-info .ship-name {
  flex: 1.5;
  margin-right: 5px;
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
}
#MiniShip .ship-details-mini .ship-item .ship-info .ship-lv-text {
  flex: 2;
  font-size: 70%;
  margin-top: 1px;
  margin-right: 4px;
  line-height: 1;
  overflow: hidden;
}
这两个分别对应名字和等级。我觉得这里的缩放逻辑应该和旁边的入渠面板一致，不知道各位大大怎么想的（我是网页设计小白

**Comment by DSakura1987** [comment]
又找了一下，问题出在旁边船的状态显示上面。这个地方被指定了最小宽度125px，所以会把左边的名字挤进去。我自己改了一下解决掉了，不过同时发现两个小瑕疵（如图所示）
![image](https://cloud.githubusercontent.com/assets/4421906/14292095/bbcc05ee-fb23-11e5-9d9d-2ca840c737f6.png)
一个是舰队等级，制空和索敌这里。因为这里是多个组件构成，所以估计要修一部分代码来让这里变成自适应的。
另一个是这个修理图标，遮挡了HP数字。
这两个都是由于右边太窄导致的问题。要在这个issue里面也修了吗？不用的话我就把我现在的更改发pull request。

**Comment by KochiyaOcean** [comment]
宽度太低的情况下无法显示完整的信息是正常情况……我将面板最低宽度调大一点好了

**Comment by KagamiChan** [comment]
要不要把 div.ship-info 设置的 min-width 改成 4em 什么的

**Comment by DSakura1987** [comment]
无论是指定为4em还是不指定，我没从显示效果上面看出区别。最后都是压缩成我发的图片那样。当船的血量有三位数的时候，最大HP的数字在极端情况下还会和星重合……
我觉得不指定好一点，就让系统自己掌握吧

**Comment by bobjiang6** [comment]
我自己的情况是 SP4 2736*1824分辨率
系统DPI 150%
大概具体情况是开了那个勾以后 最大化或者类似的屏幕比例会出现各种各样的显示问题

**Comment by KochiyaOcean** [comment]
@bobjiang6 各种各样的显示问题也请截个图啊……
