### ISSUE TITLE
使用蓝牙耳机时会没有声音

### ISSUE THREAD

**Issue by nagaho5** [poooi/poi#962]
别的软件声音全部正常 切成有线耳机也是好的 确定问题肯定出在poi上
从6.1.2升到6.2beta也没用 难道poi的音频不能通过蓝牙传输？

**Comment by KochiyaOcean** [comment]
@nagaho5 没蓝牙耳机

**Comment by alvin-777** [comment]
操作系统是。。？

**Comment by nagaho5** [comment]
@alvin-777 win10 pro x64

**Comment by nagaho5** [comment]
@alvin-777 把耳机线插上poi有声音 拔掉变蓝牙模式就没声音了

**Comment by yukixz** [comment]
@nagaho5 chrome 的声音正常否？

**Comment by nagaho5** [comment]
@yukixz 正常 舰娘有声音 看视频也有

**Comment by yukixz** [comment]
看来是 electron bug ?

**Comment by nagaho5** [comment]
@yukixz 那这bug是不是没办法解决.....？

**Comment by KochiyaOcean** [comment]
@nagaho5 至少不是我们负责的范围内

**Comment by nagaho5** [comment]
@KochiyaOcean 好吧....运气太差 看待会到的新蓝牙适配器 换aptX编码能不能解决.....

**Comment by nagaho5** [comment]
换了另一台设备 6.0版本poi 有声音。。我再测试下看看问题到底出在哪。。

**Comment by nagaho5** [comment]
现在推断是这个博通方案的蓝牙芯片和electron不兼容....待会换个CSR的芯片上去试试

**Comment by nagaho5** [comment]
@KochiyaOcean @alvin-777 的确是博通方案的蓝牙芯片和electron不兼容 CSR的芯片有声音 麻烦各位了
