### ISSUE TITLE
窗口不能调整大小

### ISSUE THREAD

**Issue by Gruttyricardo** [poooi/poi#963]
右上角的”最大化“是灰的，并且将鼠标移到边框也不能调整大小以及全屏

![qq 20160409121141](https://cloud.githubusercontent.com/assets/18249956/14404773/3cd95fb2-fe4c-11e5-8472-c5808930409b.png)

**Comment by KochiyaOcean** [comment]
按 alt 键，poi -> 允许窗口大小变化
话说这设置都藏这么深了你们到底怎么点到的……

**Comment by taroxd** [comment]
是时候用隐藏设置的方式了（x

**Comment by dkwingsmt** [comment]
说实话我真心觉得是某个地方的代码不小心设置了这个设置。无数人即使到了这么深的地方，都不知道 Alt 菜单的时候，都过来汇报说窗口大小不能改变……

**Comment by taroxd** [comment]
@dkwingsmt 我全局搜索了 poi.content.alwaysOnTop，没找到其他会修改的地方。我觉得你们用 config 的时候应该都是用字符串字面量的吧

**Comment by dkwingsmt** [comment]
我也搜过。但是实在是太奇怪了
