### ISSUE TITLE
win7下无法启动

### ISSUE THREAD

**Issue by ffts** [poooi/poi#964]
win7 64，用的是打包好的
之前是能启动的，后来我重装了一次系统，就运行不了了，试了6.1.3和5.2.0都不行
打包好的有什么地方能看到日志吗？还是说得自己下源码跑一个才行？

**Comment by taroxd** [comment]
用命令行打开。具体方式是按 win+R，然后按下 cmd，把 poi.exe 拖到那个黑黑的窗口里面，然后按下 Enter 即可。

**Comment by ffts** [comment]
多谢，我试试看

**Comment by ffts** [comment]
[DEBUG] Debug Mode
[WARN] cannot read config.cson
[INFO] Proxy listening on 50721

只有这个
[WARN] cannot read config.cson 这个的问题？

**Comment by KagamiChan** [comment]
按 win + R ，在弹出的运行的窗口里输入 %appdata%/poi，把 config.cson 改个名，再重复之前的运行步骤试试

**Comment by ffts** [comment]
@KagamiChan 这个路径下什么都没有，config.cson在poi程序在的目录里，我试过把这个改名，不过还是一样

**Comment by KagamiChan** [comment]
你提到的 poi 版本第一次运行时候会创建 %appdata%/poi 目录并且把 config.cson 放进去的
在一个新的文件夹里解压你的 poi 程序再运行试试看
再检查一下权限和杀毒软件的问题

**Comment by ffts** [comment]
@KagamiChan 新建一个解压了也还是不行，杀软用的微软的关掉了也不行，管理员权限运行poi也不行
我把之前的config.cson放到%appdata%/poi下面之后不会再提示cannot read config.cson不过还是没有反应

[DEBUG] Debug Mode
[INFO] Proxy listening on 52546

变成只有这两条了

**Comment by KagamiChan** [comment]
我刚才用 6.1.3 在 Windows 7 Home basic 64bit sp1 上试了，启动正常
你用的是修改版系统吗？如果是的话只能摊手了。

**Comment by ffts** [comment]
@KagamiChan 不是，官方的镜像，旗舰版 64位，不过不是sp1
主要是之前也是启动正常，重新装了一次就这样了，用的都是一张盘，实在没有头绪

**Comment by ffts** [comment]
升到 sp1就可以启动了...
