### ISSUE TITLE
miniShip 图标响应较慢

### ISSUE THREAD

**Issue by wafer-li** [poooi/poi#970]
Electron v0.37.5 
OS X 10.11.4
poi: 6.2.0-alpha a86a94727a847361057a69c7029fd0aef03e51ff

如图
<img width="695" alt="2016-04-13 19 31 32" src="https://cloud.githubusercontent.com/assets/12459199/14490617/b3d0fe9e-01ae-11e6-8e7c-6f0ee8d17f84.png">

舰队面板是没有这个问题的
<img width="674" alt="2016-04-13 19 31 46" src="https://cloud.githubusercontent.com/assets/12459199/14490627/c39733d4-01ae-11e6-8db2-3559059a231b.png">

console 无报错

通常需要 5s 左右才能显示正常，有时候甚至需要 1-2 min 才会消掉补给图标

===================================================
更新一下，突然就变得好像是显示不出来了，嗯。神奇

<img width="724" alt="2016-04-13 20 32 44" src="https://cloud.githubusercontent.com/assets/12459199/14491969/05280a28-01b7-11e6-9190-f09a016dc203.png">

console 同样无报错

**Comment by KagamiChan** [comment]
点击补给之后动画就会开始播放了，但是面板上的状态是要收到 `/kcsapi/api_req_hokyu/charge` 的响应才会更新的，会不会和这个有关系？

**Comment by wafer-li** [comment]
@KagamiChan  但是大面板和 flash 是保持同步的，应该不会存在 API 收不到的情况啊？

**Comment by KochiyaOcean** [comment]
我觉得只是单纯的卡了而已……
