### ISSUE TITLE
“远征信息”插件远征38条件验证有误

### ISSUE THREAD

**Issue by Yogomove** [poooi/poi#973]
远征38（东急2）成功条件是有4条以上各自携带2个以上桶，而插件似乎只验证总桶数>8...事实上例如三条三桶+一条一桶的配置远征仍然会失败（派出时poi会提示失败，估计api能收到失败信息？），但插件上显示配置可行的绿点。
望予修正，多谢。
另，远征24的大成功条件已经确证为至少4桶4闪，望能加入文字部分说明。

**Comment by ruiii** [comment]
close 了吧？
到具体插件去提（

**Comment by yukixz** [comment]
merge to https://github.com/poooi/plugin-quest/issues/28
