### ISSUE TITLE
能删除这条么？

### ISSUE THREAD

**Issue by were** [poooi/poi#974]
?直接关闭吧。我发错了。

**Comment by Ayaphis** [comment]
=。=

**Comment by yukixz** [comment]
不能

On Tuesday, 19 April 2016, Ayaphis <notifications@github.com> wrote:

> =。=
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/poooi/poi/issues/974#issuecomment-211865771>
>


-- 
*Dazzy Ding*
Email: h@dazzyd.org
