### ISSUE TITLE
Win7 64bit及Win10系統下無法使用

### ISSUE THREAD

**Issue by roiayano** [poooi/poi#975]
可以正常登入(使用VPN) IE FIREFOX都可以登入
但使用poi會直接卡在地區錯誤

**Comment by KochiyaOcean** [comment]
勾选设置面板里的设置地区 cookie 选项看看？

**Comment by roiayano** [comment]
沒用...

**Comment by roiayano** [comment]
另外遇到的狀況是官網的圖片都跑不出來,且game start的頁面也跑不動 點了選項也是卡很久
我進入遊戲頁面方式是直接抓IE的遊戲網址進去的
直接用點的都跑不動

**Comment by DSakura1987** [comment]
在poi里面用一心二用打开http://www.dmm.com/netgame/social/-/gadgets/=/app_id=854854/ 能正常访问吗？此外请描述一下你所在的地区以及登录时的网络条件，例如是否使用了VPN，poi是否设定了使用代理

**Comment by roiayano** [comment]
人在東莞,有用VPN,使用的網速測試約為60m 上下對等實際速度,
poi開關都試過了,
昨天試了某方法改了Host之後可以使用了...
