### ISSUE TITLE
建议:希望在概览页面增加一个实时战斗评价的剧透

### ISSUE THREAD

**Issue by Tierc** [poooi/poi#977]
日常使用中很多情况只要剧透战斗评价判断是否夜战就足够了,潜艇做2-3南西,潜艇做4-2东方周常或者5-4刷战果,这些都不需要详细的剧透.显然切换到未卜先知插件看战斗评价再切回概览页面这个操作是多余的.
         希望能在设置按钮的正下方提供一个实时显示战斗评价的剧透,在设置中添加个开关,方便不想剧透的那部分用户.
         在poi群里提过这个建议,开发组的人建议我来着发个issue,希望开发组能够采纳.
         希望POI越来越完善,谢谢!

**Comment by KochiyaOcean** [comment]
原则上不为插件在主面板提供只能为插件所用的模块。
但是可以考虑其他实现方式
cc@Chibaheit

**Comment by JenningsWu** [comment]
其实可以让剧透插件发个“字幕”？

**Comment by KochiyaOcean** [comment]
会被战斗台词盖住吧……不过这都是细节

**Comment by Tierc** [comment]
设置按钮下面的位置不行的话,把台词显示区域右边的那一块"出击海域:X-X"这块精简下"海域:X-X"把战斗评价塞进去,这个位置是否也不可行?

**Comment by KochiyaOcean** [comment]
总归这是插件而非本体需要考虑的事
刚才没 cc 到再来一遍 @Chibaheit

**Comment by JenningsWu** [comment]
@Tierc 右边那一块有插件在用，所以需要和之前的插件讨论下如果那里放战斗评价的话要怎么改
