### ISSUE TITLE
Redux 讨论

### ISSUE THREAD

**Issue by dkwingsmt** [poooi/poi#978]
> 本 issue 里的内容都是暂定，如果准备开始实现了需回复告知。

# Store 结构
# 文件结构
# Misc
- 尽可能保持插件兼容性
 - window 添加 getter 引用到 store
- tools: [redux](https://github.com/reactjs/redux/), [immutable.js](https://github.com/facebook/immutable-js/)
- es6?

**Comment by dkwingsmt** [comment]
## 关于文件结构
我现在看到过两种结构
### 分离型
- reducer/*.js
 - ``import`` TYPE
 - reducers
 - ``export`` reducer
- actions/*.js
 - ``export`` TYPE
 - ``export`` action creators

### 合并型
- redux/
 - (local) TYPE
 - ``export`` action creators
 - reducers
 - ``export`` reducer

**Comment by magicae** [comment]
个人用后一种 前一种需要大量import/export
