### ISSUE TITLE
希望cmd/ctrl + 3能切到之前选择的插件界面

### ISSUE THREAD

**Issue by jayjayzju** [poooi/poi#98]
目前是固定切到 未卜先知 界面

**Comment by malichan** [comment]
并不是切到未卜先知呢。。只是切到插件列表的第一个插件。。
不过加一个功能来在最近使用的两个面板之间切换确实是个好想法！

**Comment by magicae** [comment]
现在是按插件列表顺序的第一个插件

**Comment by magicae** [comment]
返回上一个用Ctrl+`？

**Comment by malichan** [comment]
我觉得需要一个更快捷的键位

**Comment by malichan** [comment]
有一种CS里Q键的感觉……

**Comment by jayjayzju** [comment]
cmd + ` 在mac上是切换一心二用的窗口的

我觉得cmd + 1234已经满足面板间的切换需求了，可以把tab或者ctrl+tab改成插件界面间的切换，然后cmd+3切换到当前正在使用的插件

最近两个面板间切换感觉用处不大

**Comment by malichan** [comment]
我倒是觉得现在的tab键功能用处不大，最近两个面板间切换比较有用，我建议用tab键来切换最近使用的两个面板。
不是一直有人抱怨舰队界面和剧透直接切换太麻烦了么，如果有这个功能的话，只要先打开舰队界面，再打开未卜先知，然后就可以用tab来回切换啦！

**Comment by jayjayzju** [comment]
额我觉得cmd+2和cmd+3不是比tab跟方便么。。比如中途去看了经验计算，还得再点次舰队和剧透，才能得到想要的tab效果

**Comment by malichan** [comment]
这种情况倒是也存在啦，但组合键肯定不如单键方便。主要是我觉得现在的tab键功能实在没啥用，谁会为了找一个面板切过去那么多面板，鼠标点点都比这快。

**Comment by jayjayzju** [comment]
单tab平时也比cmd+tab用的频率低吧

**Comment by magicae** [comment]
关于这个快捷键的问题估计要长期讨论一下

**Comment by jayjayzju** [comment]
建议先把插件按钮改成点击显示剧透，悬停显示插件列表供选择

实际用的过程中，点击操作绝大多数都是为了切到剧透。现在每次都要点两下，很麻烦

**Comment by magicae** [comment]
插件地位平等…

**Comment by jayjayzju** [comment]
平等归平等，总得考虑下用户体验吧。。或者就像最上面说的，切到上一次选择的插件界面，现在这样点击两下很不方便。用户体验：点击一次 > 悬停+点击一次 > 点击两次

**Comment by KochiyaOcean** [comment]
悬停之前有加入过，不过不是很好处理所以又去掉了

**Comment by magicae** [comment]
我觉得应该要考虑如何进行插件布局比较直接…

**Comment by jayjayzju** [comment]
其实我就是希望把这事提上议程_(:з」∠)_

**Comment by KochiyaOcean** [comment]
不知道 tab 的 dropdown 是否可以做成 split 的样式，如果可以的话倒是简单不少……

**Comment by PHELiOX** [comment]
3tab布局直接解决问题 ＝。＝

**Comment by ruiii** [comment]
屏幕宽度。。

**Comment by Chibaheit** [comment]
我觉得不如让用户自定义?

**Comment by yukixz** [comment]
Related https://github.com/poooi/poi/issues/706

**Comment by dkwingsmt** [comment]
#706 竟然把这个 issue 给解决了哈哈哈哈哈。

#706 在非分离界面下将插件栏分为了一个按钮和一个下拉菜单。按钮可以直接切换到之前的插件。
分离界面下本来就长期显示插件。
