### ISSUE TITLE
Mac版 v6.1.3／v6.2.0 舰娘信息插件无法显示

### ISSUE THREAD

**Issue by Ricardo-Zhang** [poooi/poi#980]
<img width="1021" alt="screen shot 2016-05-04 at 6 02 16 pm" src="https://cloud.githubusercontent.com/assets/16185679/15011071/6003b6d8-1222-11e6-98d0-a6f5714015dc.png">

**Comment by KochiyaOcean** [comment]
卸载然后重新安装一次看看

**Comment by Ricardo-Zhang** [comment]
重裝了ver6.2.0 問題未解決
