### ISSUE TITLE
可以考虑支持神姬的缓存吗？

### ISSUE THREAD

**Issue by ueinohakono** [poooi/poi#981]
看了下更新记录似乎没有的样子，能考虑支持下吗？
比如岛风Go的缓存之类的？

**Comment by KochiyaOcean** [comment]
@ueinohakono 全年龄的缓存包有意义么

**Comment by ueinohakono** [comment]
@KochiyaOcean 岛风的那个缓存不是全年龄的啊。scenarios底下有papapa的图

**Comment by edwardaaaa** [comment]
说到这点，我想到了一心二用那个插件，每次点开玩别的DMM游戏，似乎都要重新加载，虽然SS速度可以，但是总归不如像舰娘那样可以秒开，请问是我的姿势不对吗？

**Comment by KochiyaOcean** [comment]
可能是缓存太大被清了……

**Comment by wudifeixue** [comment]
现在神姬..都没人玩了吧
