### ISSUE TITLE
未卜先知-陆基航空战结果未计入BUG

### ISSUE THREAD

**Issue by Shazi199** [poooi/poi#985]
如图
![image](https://cloud.githubusercontent.com/assets/3175890/15072579/559482b8-13c6-11e6-8d69-221f10c77683.png)

敌方DD是在陆基航空战时被击沉的

**Comment by ibicdlcod** [comment]
经我在E7亲测 这个bug 有时候不只是不计入的问题 有时候能导致poi的未卜先知乃至整个程序直接卡死 当时我还是大破带损管的 差点以为自己bug沉船了

**Comment by taroxd** [comment]
fixed
