### ISSUE TITLE
建议：能否做一个省电模式，只保留最基本的功能

### ISSUE THREAD

**Issue by Sion2015** [poooi/poi#989]
poi实在是太费电了，笔记本的电源实在有些遭不住

**Comment by KochiyaOcean** [comment]
@Sion2015 做不了……

**Comment by JenningsWu** [comment]
@Sion2015 把所有的插件都关掉

**Comment by taroxd** [comment]
https://github.com/taroxd/poi

除了走代理看 flash 之外没有其他功能，直播的时候可以使用（x

再费电就是 flash 的锅了
